### ISSUE TITLE
Reference errors when creating SACSegmentation object

### ISSUE THREAD

**Issue by shehroze37** [PointCloudLibrary/pcl#1024]
Im getting these error when trying to run the plane segmentation code on the website

URL : http://pointclouds.org/documentation/tutorials/planar_segmentation.php

CMakeFiles/plane_extraction_text.dir/plane_extraction.cpp.o:(.rodata._ZTVN3pcl15SACSegmentationINS_8PointXYZEEE[_ZTVN3pcl15SACSegmentationINS_8PointXYZEEE]+0x48): undefined reference to `pcl::SACSegmentation<pcl::PointXYZ>::segment(pcl::PointIndices&, pcl::ModelCoefficients&)'
CMakeFiles/plane_extraction_text.dir/plane_extraction.cpp.o:(.rodata._ZTVN3pcl15SACSegmentationINS_8PointXYZEEE[_ZTVN3pcl15SACSegmentationINS_8PointXYZEEE]+0x50): undefined reference to`pcl::SACSegmentationpcl::PointXYZ::initSACModel(int)'
CMakeFiles/plane_extraction_text.dir/plane_extraction.cpp.o:(.rodata._ZTVN3pcl15SACSegmentationINS_8PointXYZEEE[_ZTVN3pcl15SACSegmentationINS_8PointXYZEEE]+0x58): undefined reference to `pcl::SACSegmentationpcl::PointXYZ::initSAC(int)'
collect2: error: ld returned 1 exit status
make[2]: **\* [plane_extraction_text] Error 1
make[1]: **\* [CMakeFiles/plane_extraction_text.dir/all] Error 2
make: **\* [all] Error 2

How do I resolve this ??

Thanks

**Comment by LUCASLLA** [comment]
Hi, have you discovered the solution?

**Comment by ShaneTsui** [comment]
It may have something to do with your cmakelist.txt. Use the official's example as well.
```
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(planar_segmentation)

find_package(PCL 1.2 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (planar_segmentation planar_segmentation.cpp)
target_link_libraries (planar_segmentation ${PCL_LIBRARIES})
```

**Comment by kunaltyagi** [comment]
I'm closing this issue since
* this appears old (and solved, thanks to @ShaneTsui)
* this should not pop up in the master branch with correct CMake usage
