### ISSUE TITLE
pcl::FastBilateralFilterOMP changes NaN points []

### ISSUE THREAD

**Issue by dimtziwnas** [PointCloudLibrary/pcl#1027]
Hi all,

I'm using PCL 1.7 installed with apt-get on Ubuntu 12.04

While using the function `pcl::FastBilateralFilterOMP` I observed that points
like this  -> `(x=NAN, y=NAN, z=NAN)` 
become -> `(x=NAN, y=NAN, z=const)`
In my case const value is `const=0.898` for all points (at least for the test-dataset) and this is why I used to get some weird results in later steps of my pipeline (*).

I'm not sure if this was observed by others and corrected for a future release, but I thought that reporting this could be of some help.

Best,
dimitris

PS - (*) - The issue was observed while trying to interface PCL with cpu_tsdf. For more details you can have a look here -> https://github.com/sdmiller/cpu_tsdf/issues/4

**Comment by kunaltyagi** [comment]
All NaN are set to z_max in order to increase overall speed of the algorithm. Not exactly a bug. Without doing this, every iteration involving z would need to branch on z being finite or not instead of just once.
