### ISSUE TITLE
grabSingleCloud in EnsensoGrabber causing exception

### ISSUE THREAD

**Issue by fubusak** [PointCloudLibrary/pcl#1065]
Hi everybody!

Function grabSingleCloud in io/ensenso_grabber.cpp is causing exception
with code 13 `<ItemTypeNotCompatible>` in NxLib API. This problem is caused by this line:
https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ensenso_grabber.cpp#L315 

It looks it's not possible to read info from `itmRaw` node so I'm reading timestamp from one of its child nodes and it is seems to be working:
`_camera[itmImages][itmRaw][itmLeft].getBinaryDataInfo(0, 0, 0, 0, 0, &timestamp);` 
I have PCL v1.8.0 from trunk built with VS2013.
Thank you all!

**Comment by VictorLamoine** [comment]
Hello,
Good to see another Ensenso user! It's a very simple error, I remember fixing this but the commit must have gone wild.

Does the Ensenso grabber work good for you?
What framerates do you achieve?

 Bye

**Comment by fubusak** [comment]
Victor, thank you for your quick reaction! grabSingleCloud works great for me as I need to trigger camera on demand. FPS rate in debug mode is about 2-3 fps, but with use of grabSingleCloud method. 

Continuous grabber doesn't work due to some problem with boost callback. I haven't been able to track it down yet, but it might be caused by my build also...

Have a nice day!

**Comment by VictorLamoine** [comment]
> Continuous grabber doesn't work due to some problem with boost callback. I haven't been able to track it down yet, but it might be caused by my build also...

If you have time please fill an issue so that we can solve the problem. Unfortunately I don't have the skills (and maybe not the time) to compile PCL on Windows.

The Ensenso SDK states that we can obtain 30 FPS with continuous grabbing (for example with nxView) but I never got better than 7 FPS.

**Comment by fubusak** [comment]
OK, I'll try it. 

According to the info from NxView, the bottleneck in pointcloud acquisition is the computation of disparity map. Capture itself takes less then 10 ms, but the computation takes up to 300 ms. I'll test it with better hardware later...

**Comment by fubusak** [comment]
I've discovered scaling settings in nxView. After downscaling I've achieved more than 25 fps so it's about hardware :)

**Comment by VictorLamoine** [comment]
Yes and they provide no  hardware (CUDA, OpenMP, OpenCL) acceleration; it's very slow.
I'm using a `Intel® Core™ i7-3740QM ` which is more than a decent CPU.

**Comment by pionex** [comment]
Sorry, I know this is old, but Ensenso suggests running a 4th generation Core processor or later.  Apparently the SDK uses some of the new vectorization technologies in those later processors in order to speed up stereo matching.  Ensenso suggests it will run at 1.6x the speed with these newer processors although I have yet to verify.

**Comment by VictorLamoine** [comment]
Please share benchmark results if you have the opportunity to test the Ensenso on one of these CPUs.

**Comment by ngcngc1** [comment]
Victor, thanks for your EnsensoGrabber source code ant its very useful. I am also meeting the problem of low FPS in the code and I have found some reasons. The most important thing is the trigger mode was not set up and cost six times longer than the sdk. Just replace the capture command by
NxLibCommand capture(cmdCapture);
capture.parameters()[itmInitialTrigger] = valNone;       
capture.parameters()[itmWaitFor] = valNone;       
capture.parameters()[itmFinalTrigger] = valUntriggered;
capture.execute();
And also using gpu can speed the program in a large scale.

**Comment by taketwo** [comment]
@ngcngc1 thanks for sharing. You are welcome to submit a pull request if you think that this fix would benefit other people.
