### ISSUE TITLE
Ensenso viewer exception

### ISSUE THREAD

**Issue by fubusak** [PointCloudLibrary/pcl#1070]
Hello again :)

I'm trying to run this example http://pointclouds.org/documentation/tutorials/ensenso_cameras.php. 
Calling `ensenso_grabber->registerCallback (f);` causes exception in `grabber.h ` on line 251 as a consequence of passing expression `if (signals_.find (typeid (T).name ()) == signals_.end ()) ` (ln238). 
**Exception text:**
```
no callback for type:
void __cdecl(class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZ> const > const & __ptr64)
```
**List of registered callbacks contains just this one:**
```
void __cdecl(class boost::shared_ptr<class pcl::... ...} }
```
It looks there's some problem with callback matching. There might be some problem in my build because I've used prebuilt dependencies from http://unanancyowen.com/?p=1255&lang=en as a base for compiling PCL from trunk. It should be built with the same compiler as I used, however I'm not sure if this is a correct way. I have PCL 1.8.0 from trunk compiled with VS2013 x64. 

Thank you in advance!

**Comment by VictorLamoine** [comment]
I did not update the tutorial at the moment, this code works with an old version of the Ensenso PCL implementation. I have an [updated version on my branch](https://github.com/VictorLamoine/pcl/blob/82f50fc0930897332e8a65c0da7889b6a4c2839f/visualization/tools/ensenso_viewer.cpp).

I'll probably wait a few weeks before updating the tutorial because I want to tweak other things.

**Comment by VictorLamoine** [comment]
The Ensenso grabber allows to grab cloud and also to visualize images, [here is an example project](https://gist.github.com/VictorLamoine/e604aec3ffd5ce3f8ae2) to visualize both the point cloud and the raw/overlaid images.

OpenCV is a dependency as I did not manage to display the Ensenso images with the pcl::ImageViewer, it crashes.

**Comment by fubusak** [comment]
Nice, updated version works fine. Thank you!
