### ISSUE TITLE
example_difference_of_normals does not compile

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1097]
` BUILD_examples                   ON`
```bash
CMakeFiles/pcl_example_difference_of_normals.dir/example_difference_of_normals.cpp.o: In function `main':
/home/victor/pcl/src/examples/features/example_difference_of_normals.cpp:212: undefined reference to `pcl::EuclideanClusterExtraction<pcl::PointNormal>::extract(std::vector<pcl::PointIndices, std::allocator<pcl::PointIndices> >&)'
CMakeFiles/pcl_example_difference_of_normals.dir/example_difference_of_normals.cpp.o:(.rodata._ZTVN3pcl19NormalEstimationOMPINS_11PointXYZRGBENS_11PointNormalEEE[_ZTVN3pcl19NormalEstimationOMPINS_11PointXYZRGBENS_11PointNormalEEE]+0x58): undefined reference to `pcl::NormalEstimationOMP<pcl::PointXYZRGB, pcl::PointNormal>::computeFeature(pcl::PointCloud<pcl::PointNormal>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pcl_example_difference_of_normals] Error 1
make[1]: *** [examples/features/CMakeFiles/pcl_example_difference_of_normals.dir/all] Error 2
make: *** [all] Error 2
```

Not sure why.. it seems to be be [correctly linked](https://github.com/PointCloudLibrary/pcl/blob/master/examples/features/CMakeLists.txt#L22).

**Comment by taketwo** [comment]
Has something to do with OMP. I have it disabled, and the thing is built without problems.

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen Can you try to verify this please? With and without OpenMP.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho Sorry, I don't understand the test case yet.
Which is it?

* Try compiling example_difference_of_normals with PCL that was compiled with enable/disable OpenMP?
* Try compiling example_difference_of_normals with enable/disable OpenMP?

**Comment by stefanbuettner** [comment]
Hey there,

could #1642 solve the problem? 'Cause it seems as the example should link against NormalEstimationOMP<..., PointNormal> which is not precompiled.

Cheers,
Stefan

**Comment by UnaNancyOwen** [comment]
I tried PCL 1.8.0 examples (<code>BUILD_examples</code> options to ON) on Visual Studio.
I was set <code>OpenMP_CXX_FLAGS</code> option to <code>/openmp</code> when to enable OpenMP (default), and set to <code>/openmp-</code> when to disable OpenMP.
It can be built successfully in both cases that enable and disable OpenMP.
Please tell me if I'm saying something wrong. I will try the more test.

**Comment by SergioRAgostinho** [comment]
Just noticed there was nothing on Victor's initial post mentioning that it was specific to Windows. I enabled the examples on my build and it got through with no errors. 

@VictorLamoine Can you still reproduce this? The issue dates do Jan 2015 :)

@UnaNancyOwen That was it. Thanks.

@stefanbuettner That's also true... that should have yielded the typical linker error [here](https://github.com/PointCloudLibrary/pcl/blob/master/examples/features/example_difference_of_normals.cpp#L118). At first sight I'm not totally sure why the linker is not complaining when I tried to build it. To be honest I also don't understand why do we [instantiate different types](https://github.com/PointCloudLibrary/pcl/blob/master/features/src/normal_3d.cpp#L47-L48) between NormalEstimation and NormalEstimationOMP.

**Comment by VictorLamoine** [comment]
I confirm that the latest trunk allows to build the examples without any compilation error on Linux.
Closing as this seems to be solved for every platform we support.
