### ISSUE TITLE
Failed to process package 'depth_image_proc'

### ISSUE THREAD

**Issue by chien800614** [PointCloudLibrary/pcl#1108]
Undefined symbols for architecture x86_64:
  "cv::_InputArray::_InputArray(cv::Mat const&)", referenced from:
      depth_image_proc::PointCloudXyzrgbNodelet::imageCb(boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::CameraInfo_<std::__1::allocator<void> > const> const&) in point_cloud_xyzrgb.cpp.o
      depth_image_proc::PointCloudXyziNodelet::imageCb(boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::CameraInfo_<std::__1::allocator<void> > const> const&) in point_cloud_xyzi.cpp.o
  "cv::_OutputArray::_OutputArray(cv::Mat&)", referenced from:
      depth_image_proc::PointCloudXyzrgbNodelet::imageCb(boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::CameraInfo_<std::__1::allocator<void> > const> const&) in point_cloud_xyzrgb.cpp.o
      depth_image_proc::PointCloudXyziNodelet::imageCb(boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::__1::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::CameraInfo_<std::__1::allocator<void> > const> const&) in point_cloud_xyzi.cpp.o

**Comment by jspricke** [comment]
This has nothing to do with PCL. I would propose to ask on http://answers.ros.org.
