### ISSUE TITLE
PCL Plotter does wrong axis scaling when adding histogram data

### ISSUE THREAD

**Issue by hacke1978** [PointCloudLibrary/pcl#1123]
on the first call it scales the axis nicely, but when you call addHIstogramData the second time, axis are both scaled from -0.01 to 0.01.

``` cpp
#include <iostream>
#include<pcl/visualization/pcl_plotter.h>

int
main (int argc,
      char** argv)
{
  pcl::visualization::PCLPlotter * plotter = new pcl::visualization::PCLPlotter;
  std::vector<double> data_vec;
  data_vec.push_back (3);
  data_vec.push_back (3);
  data_vec.push_back (3.5);
  data_vec.push_back (4);

  std::vector<double> data_vec2;
  data_vec2.push_back (30);
  data_vec2.push_back (30);
  data_vec2.push_back (30.5);
  data_vec2.push_back (40);

  plotter->addHistogramData (data_vec, 5);
  plotter->spin ();
  plotter->clearPlots ();

  plotter->addHistogramData (data_vec2, 4);
  plotter->spin ();
}
```

**Comment by VictorLamoine** [comment]
I can't reproduce the bug, this is what I get (using PCL latest master)
![hist_1](https://cloud.githubusercontent.com/assets/5566160/10263194/837f0cc0-69e4-11e5-8358-6866d0eeff73.png)
![hist_2](https://cloud.githubusercontent.com/assets/5566160/10263195/8440e552-69e4-11e5-8f46-80b5e1581f8e.png)

**Comment by VictorLamoine** [comment]
The example code works fine with VTK trunk, not with VTK 5.8.

![1](https://cloud.githubusercontent.com/assets/5566160/11713245/77b3ec5c-9f32-11e5-8036-84e278c78f57.png)
![2](https://cloud.githubusercontent.com/assets/5566160/11713246/78afa7ae-9f32-11e5-99db-5ed7c291c5e7.png)
The data is here but the histogram view is shifted:
![3](https://cloud.githubusercontent.com/assets/5566160/11713247/796e762a-9f32-11e5-9450-5557cc6d6292.png)

The only difference between the 2 versions in PCL code is in [addPlotData](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_plotter.cpp#L127-L131).

So I guess i think it's a VTK bug. I tried adding `line->Update();` but it doesn't change anything.

**Comment by kunaltyagi** [comment]
Closing VTK 5.8 is no longer supported since quiet a while
