### ISSUE TITLE
Support of structure.io sensor

### ISSUE THREAD

**Issue by wolfviking0** [PointCloudLibrary/pcl#1134]
Hi, 

I just receive my structure sensor (http://structure.io/), I want do some test with PCL.
I build PCL using the occipital version of OpenNI2 https://github.com/occipital/OpenNI2.

When I launch the app pcl_openni2_viewer I habe this error : 

Warning: USB events thread - failed to set priority. This might cause loss of data...
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted (core dumped)

May be someone already tried to play with the structure sensor.

**Comment by VictorLamoine** [comment]
What platform are you using?
Did you compile PCL latest trunk?

Unfortunately without the device itself it is difficult to help you; maybe you could debug the application and provide and `gdb` trace?

The `pcl_openni2_viewer` should work with any OpenNI2 compliant device but it doesn't look like it's the case.

**Comment by metacomgd** [comment]
The structure sensor does not have color video; in the initialization in  pcl-master/io/src/openni2/openni2_device.cpp
There is this call, which doesn't take into account the lack of color sensor. 
 setColorVideoMode (getDefaultColorMode ());

hasColorSensor should be used to check before this;

In pcl-master/io/src/openni2_grabber.cpp

pcl::io::OpenNI2Grabber::startSynchronization ()

There is also a call to getColorVideoMode which also is not wrapped in hasColorSensor

I tried commenting out the calls but there is still a problem somewhere which I can't seem to figure out

**Comment by taketwo** [comment]
Fixed long ago via #1372.
