### ISSUE TITLE
Compilation fails on 32bit Nvidia Jetson due to lack of memory.

### ISSUE THREAD

**Issue by dtmoodie** [PointCloudLibrary/pcl#1136]
This is more of a warning than an issue.  
NVidia Jetson's platform is 32bit thus even with virtual memory I cannot compile the full pcl.
It fails here consistently even with only one build thread:

[ 66%] Building CXX object recognition/CMakeFiles/pcl_recognition.dir/src/cg/geometric_consistency.cpp.o
In file included from /home/ubuntu/libsrc/pcl/sample_consensus/include/pcl/sample_consensus/sac_model_registration.h:338:0,
                 from /home/ubuntu/libsrc/pcl/registration/include/pcl/registration/correspondence_rejection_sample_consensus.h:46,
                 from /home/ubuntu/libsrc/pcl/recognition/include/pcl/recognition/impl/cg/geometric_consistency.hpp:45,
                 from /home/ubuntu/libsrc/pcl/recognition/src/cg/geometric_consistency.cpp:43:
/home/ubuntu/libsrc/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp: In member function 'bool pcl::SampleConsensusModelRegistration<PointT>::isSampleGood(const std::vector<int>&) const [with PointT = pcl::PointDEM]':
/home/ubuntu/libsrc/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp:62:80: warning: 'p10.pcl::PointDEM::<anonymous>.pcl::_PointDEM::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous struct>::z' is used uninitialized in this function [-Wuninitialized](p21.x * p21.x + p21.y * p21.y + p21.z * p21.z) > sample_dist_thresh_);
                                                                                ^
/home/ubuntu/libsrc/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp:62:80: warning: 'p20.pcl::PointDEM::<anonymous>.pcl::_PointDEM::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous struct>::z' may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/ubuntu/libsrc/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp:62:80: warning: 'p21.pcl::PointDEM::<anonymous>.pcl::_PointDEM::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous>.pcl::_PointDEM::<anonymous union>::<anonymous struct>::z' may be used uninitialized in this function [-Wmaybe-uninitialized]
virtual memory exhausted: Cannot allocate memory
make[2]: **\* [recognition/CMakeFiles/pcl_recognition.dir/src/cg/geometric_consistency.cpp.o] Error 1
make[1]: **\* [recognition/CMakeFiles/pcl_recognition.dir/all] Error 2
make: **\* [all] Error 2

This is with an additional 4gb of swap space added.  When monitoring via top it crashes around when the total allocation reaches approx 4gb.

**Comment by VictorLamoine** [comment]
Did you manage to compile PCL?
What about 8 Gb (or more) of swap ?

You can check [memory/swap usage](http://www.cyberciti.biz/faq/linux-check-swap-usage-command/) with something like:
`$ free -m`

I've compiled PCL on an ODROID-U2 board so I would be a bit surprised you can't on your Jetson.

**Comment by dtmoodie** [comment]
I disabled recognition and it built fine.  It would seem that module takes the most memory to compile.
I tried monitoring with free and it didn't fully fill my virtual memory, but it did approach the 4gb limit on 32bit platforms.
I'm assuming total memory usage cannot exceed the limitations of a 32 bit platform regardless of amount of virtual memory.

**Comment by lrvk123** [comment]
That is not true, more than 4GB of swap will be used.  I have successfully compiled PCL on Jetson. Just plug a SD/SSD and turn on swap.

**Comment by LGinC** [comment]
when I built the io module and search module,it occured some error.

**Comment by LGinC** [comment]
make -j2
20%  io moudle....error

**Comment by kunaltyagi** [comment]
Closing. Memory constraint systems have this issue. Please use a cross-compilation instead
