### ISSUE TITLE
Bug in ExtractPolygonalPrismData when using ConvexHull

### ISSUE THREAD

**Issue by ngoonee** [PointCloudLibrary/pcl#1137]
Output of ConvexHull is a list of points forming the convex hull of a 2D projection (from ProjectInliers, presumably). Using this hull directly in ExtractPolygonalPrismData via setInputPlanarHull) results in the following bug (hull is around the yellow container, the panel flooring should not be visible).
![extractpolygonalprismwithbug](https://cloud.githubusercontent.com/assets/135656/6076718/0788811a-ae22-11e4-9fac-d4d82acc32dc.png)

If I 'close' the hull (example code at the bottom) this is the result, which is what I expect.
![extractpolygonalprismwithoutbug](https://cloud.githubusercontent.com/assets/135656/6076719/07947b32-ae22-11e4-816e-8473c1b19024.png)

I suspect ExtractPolygonalPrismData makes erronous assumptions regarding the hull. Or the hull output by ConvexHull should be closed by default. I have not tried ConcaveHull, sorry, it only just occured to me while writing this up. I wanted to just put this up, I will try that out when I get time off from pushing this project forward.

Code involved, assuming an input projected_cloud is provided, and a main_cloud which contains all the points we want to filter:-

``` c++
// Find convex hull around the points on the projected plane
pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud_hull (new pcl::PointCloud<pcl::PointXYZRGBA>);
pcl::ConvexHull<pcl::PointXYZRGBA> chull;
chull.setInputCloud (projected_cloud);
chull.reconstruct (*cloud_hull);
cloud_hull->push_back(cloud_hull->at(0)); // If this line is commented, the bug occurs

// Extend the hull in both z directions on the original cloud to return the desired box.
pcl::ExtractPolygonalPrismData<pcl::PointXYZRGBA> prism;
prism.setInputCloud(main_cloud);
prism.setInputPlanarHull(cloud_hull);
prism.setHeightLimits(-10, 10);
pcl::PointIndices::Ptr inliers (new pcl::PointIndices);
prism.segment(*inliers);
```

**Comment by ngoonee** [comment]
Additional comment, same issue with ConcaveHull, and simply adding the first doesn't fully solve the issue (understandable, as the concave hull I'm using has a low Alpha value and actually consists of a few different areas). I'm fairly sure a higher Alpha that would get something along the lines of ConvexHull would be solvable in the same way I did it.

**Comment by taketwo** [comment]
> Or the hull output by ConvexHull should be closed by default.

We had some controversy about this: #552 #869 #1044.
