### ISSUE TITLE
compiling error with libXNVCtrl.a

### ISSUE THREAD

**Issue by wenbinli** [PointCloudLibrary/pcl#1145]
Hi,

I got compiling error with pcl1.8 on ubuntu 14.04

[  4%] Built target pcl_common
[  4%] Built target pcl_octree
[  4%] Built target pcl_io_ply
make[2]: *** No rule to make target `/usr/lib/libXNVCtrl.a', needed by `lib/libpcl_io.so.1.8.0'.  Stop.

I have no idea where the libXNVCtrl.a is called in the PCL, which seems to be something related to the nvidia-settings

**Comment by VictorLamoine** [comment]
This kind of question belongs to [PCL-users](http://www.pcl-users.org/) (because the bug is most probably on your side).

This errors should happen when compiling CUDA / GPU.
You might have a driver problem; did you recently change anything driver related ?
Try (at your own risk!) `sudo apt-get install nvidia-modprobe`, reboot and see what you get.

**Comment by wenbinli** [comment]
I did install the binary (driver343.35) from nvidia on this machine but sample code from cuda was compiled fine anyway. also note with/without the gpu/cuda selected for cmake do not make a difference. 

I tested on early driver (340.32), which compiled just fine, but neither is the libXNVCtrl.a existed there.

**Comment by VictorLamoine** [comment]
I had this once and I remember solving it pretty easily with a `sudo apt-get install`, sadly I can't remember which package was missing.

**Comment by jspricke** [comment]
https://packages.debian.org/search?searchon=contents&keywords=libXNVCtrl.a&mode=path&suite=unstable&arch=any

**Comment by wenbinli** [comment]
I cannot find the package libxnvctrl-dev in ubuntu, but I managed to fix the error with installing the nvidia-settings -- it's strange that the binary driver does include the nvidia-setting, yet after installing the nvidia-settings from ubuntu's repo, I still cannot find the "libXNVCtrl.a" file, but the error is just gone

**Comment by jspricke** [comment]
Ah, Ubuntu :)
http://packages.ubuntu.com/search?searchon=contents&keywords=libXNVCtrl.a&mode=exactfilename&suite=trusty&arch=any

**Comment by VictorLamoine** [comment]
Mine is in `/usr/lib/libXNVCtrl.a`

**Comment by wenbinli** [comment]
no, I cannot find the file even on the machine successfully compiles the library

**Comment by VictorLamoine** [comment]
If everyone is working now, please close the issue.

**Comment by wenbinli** [comment]
Sure.
