### ISSUE TITLE
StatisticalOutlierRemoval hangs on point clouds with single point data.

### ISSUE THREAD

**Issue by pbeeson** [PointCloudLibrary/pcl#1146]
I have a uniq PC sensor that can occasioanlly send a single PC that is large but all the values are 0. Obviously, there is an issue in the hardware driver that needs fixing, but this also highlighted an issue in the StatisticalOutlierRemoval class, where a cloud of all zeroes (and presumably any cloud with all the same points) will hang forver and the program must be killed with SIGTERM as CTRL-C not sufficient.

This is easy to reproduce. Make a pointcloud of size 200,000 containing all x=y=z=0; Then run StatisticalOutlierRemoval with that cloud as the input. The call to filter() hangs. This happens in 1.5 and 1.7.
pbeeson

```
Write
Preview
```

Markdown supported
Edit in fullscreen

Attach images by dragging & dropping or selecting them.

**Comment by VictorLamoine** [comment]
In fact it's working, you have to be patient:
(all points coordinates are x=1, y=2, z=3)

```bash
$ time ./statOutRem 
Cloud before filtering:
points[]: 200000
width: 200000
height: 1
is_dense: 1
sensor origin (xyz): [0, 0, 0] / orientation (xyzw): [0, 0, 0, 1]

Cloud after filtering:
points[]: 200000
width: 200000
height: 1
is_dense: 1
sensor origin (xyz): [0, 0, 0] / orientation (xyzw): [0, 0, 0, 1]

real	24m21.377s
user	24m21.588s
sys	0m1.033s
```

I'm pretty sure this happens because of [this pull request](https://github.com/PointCloudLibrary/pcl/pull/709).

**Comment by pbeeson** [comment]
Can you be more clear?  This happens because of the issues FIXED by the
pull request or INTRODUCED by the pull request.  If the latter, then I'd
say that pull request is not adequate.

**Comment by VictorLamoine** [comment]
The pull request has improved the speed in many cases; but I think it also has introduced undesired behavior such as this huge computation time. (in the precise case of all points being equals)

Can you compile PCL with a revert-patch of this pull request and tell us if it works better in this precise use case?
`git revert b1cae67adef7ab7cf1b784c4e802dce46e996b45`

**Comment by pbeeson** [comment]
No, I do not have the time to help debug this right now.  Plus I'm using
this with the Ros installed Debian binaries, not a pulled tree.
>
>

**Comment by kunaltyagi** [comment]
The issue is OP was running an algorithm meant for dense point clouds on a point cloud that's clearly not dense. Simply setting `pointcloud.is_dense = false;` before calling the filters would revert to the old behavior.

Not a bug in PCL since we can't be expected to perform custom error checking.
