### ISSUE TITLE
Point index is specified regardless to Point Cloud id in PCLVisualizer Picking events

### ISSUE THREAD

**Issue by mshafiei** [PointCloudLibrary/pcl#1149]
### Brief:

   When you have two or more point clouds in PCLVisualizer, and assign point picking callback function, you cannot tell the point cloud ID when the event has occured.
### Reproduce:

   Running the code below, picking a point from each point cloud, gives you the index between 0-n (n = number of points in the corresponding point cloud).
### Suggestion:

   The problem will be solved if there would a getter in PointPickingEvent returning the ID of corresponding point cloud of the picked point.
### Test Case:

``` c++
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/pcl_base.h>
#include <iostream>
#include <Windows.h>
using namespace std;
using namespace pcl;

typedef pcl::PointXYZRGBA PointT;
typedef pcl::PointCloud<PointT> CloudT;
typedef CloudT::Ptr ptrCloudT;


void PointSelection_callback(const pcl::visualization::PointPickingEvent &event, void*)
{
    cout << " point index: " << event.getPointIndex() << endl;
}

ptrCloudT GeneratePlanePointCloudXWithShift(int NumberOfPoints, float EdgeLength, int XShift)
{
    ptrCloudT Surface(new CloudT);
    int len = sqrt(NumberOfPoints);
    float step = EdgeLength / len;
    for (float x = 0; x < EdgeLength; x += step)
        for (float y = 0; y < EdgeLength; y += step)
        {
            PointT p;
            p.x = x + XShift; p.y = y;
            p.r = 255; p.g = 255; p.b = 255; p.a = 0;
            Surface->insert(Surface->end(), p);
        }

    return Surface;
}


int main()
{
    pcl::visualization::PCLVisualizer::Ptr m_PCLVisualization(new pcl::visualization::PCLVisualizer("view", true));
    m_PCLVisualization->registerPointPickingCallback(PointSelection_callback);
    ptrCloudT cloud = GeneratePlanePointCloudXWithShift(1000, 10,0);
    ptrCloudT ShiftedCloud = GeneratePlanePointCloudXWithShift(1000, 10,40);

    m_PCLVisualization->addPointCloud(cloud,"Cloud1"); 
    m_PCLVisualization->addPointCloud(ShiftedCloud, "Cloud2");
    m_PCLVisualization->spin();
}
```

Reported on [the mailing list](http://www.pcl-users.org/Point-picking-from-two-point-clouds-in-PCLVisualizer-td4036575.html)

**Comment by mshafiei** [comment]
Excuse me if this have been so long! Most of you might know everything written in the Background section. I wrote it mainly because I was not familiar with vtk data types before and thought you might also have the same problem.

### Background:
Member function ```PointPickingCallback::Execute``` is responsible to call the picking callbacks (point or area picking). Currently, only points indices are passed to events (point/area picking events).

```vtkAreaPicker``` and ```vtkPointPicker``` classes are supposed to perform the picking process. I will write about ```vtkAreaPicker``` picking scenario since they both have similar issues.

When the user drags the picking rubber band, a frustum is built in ```vtkAreaPicker::AreaPick``` member funtion. Thereafter ```vtkAreaPicker::PickProps``` member function will select the "Prop" which has an intersection with the frustum. "Prop"s (which ```vtkAbstractPicker::PickList``` is the container) are actually all of those things added to PCLVisualizer to be drawn.

### Problem:
Now, ```vtkAreaPicker::PickProps``` does not hold the "Prop"s which the selected frustum has intersection with. This function only picks the "Prop" and puts it in the ```vtkAreaPicker::DataSet``` member variable.

### Solution
#### Index based:
```vtkAbstractPicker::PickList``` holds the "Prop"s in the same order that the user has added and removed with PCLVisualizer member funtions. There could be placed an appropriate member variable to hold selected "Prop"s indices. PCL can take those indices after vtk function calls and pass them to the events.
#### ID based:
Since the user uses string ID on adding/removing/updating a shape or point cloud, this is far better to get back those IDs instead of indices (since there must be a mapping procedure in user source code). This is possible if vtk objects (here ```vtkProp``` which ```vtkAbstractPicker::PickList``` holds) would be able to hold the string ID. I have not yet been able to find any capability.

**Comment by taketwo** [comment]
Hi, I think everyone who used point picking with several clouds displayed will agree that providing IDs of picked clouds would be a really valuable addition to PCL. Therefore I will be happy to merge a pull request if you find a good way to implement it. As for the proposals, I think that we should definitely go with returning ID strings.

**Comment by mshafiei** [comment]
Is there any way to have a string inside vtkProp or vtkActor or any kind of user pointer? This would take less effort if ```vtkAbstractPicker::PickList``` can hold the ID of each ```vtkProp``` (point cloud, shape, etc.). I am new to vtk so any help is appreciated.

**Comment by taketwo** [comment]
Unfortunately I have no knowledge of _vtk_. Perhaps some one else might be able to comment.

**Comment by ccmonter** [comment]
Is there any resolution to this issue?  I would like to avoid implementing this myself if it has already been done.

**Comment by VictorLamoine** [comment]
I don't know anyone who solved the problem.

**Comment by mshafiei** [comment]
I have solved this problem, but unfortunately It's not possible for me to
push it for weeks, since I'm in the middle of another project!

On Thu, Apr 9, 2015 at 5:01 PM, Victor Lamoine <notifications@github.com>
wrote:

> I don't know anyone who solved the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PointCloudLibrary/pcl/issues/1149#issuecomment-91256001>
> .
>



-- 
Mohammad

**Comment by ccmonter** [comment]
Is this something that you can share until such a time that it is pulled?
Do you have a fork or branch that we could view?

Thanks for working on the problem.

**Comment by mshafiei** [comment]
​The modifications are done on another copy of PCL which is no more linked
to PCL master repository. I'm also not sure that I'm allowed to publish the
modifications yet. I will make sure until tomorrow and let you know about
the details.

**Comment by mshafiei** [comment]
I can apply the modifications and push them after a while (maximum of two
weeks). I hope it won't be too late for you.

On Thu, Apr 9, 2015 at 5:42 PM, Mohammad Shafiei <
mohammad.shafiei00@gmail.com> wrote:

> ​The modifications are done on another copy of PCL which is no more
> linked to PCL master repository. I'm also not sure that I'm allowed to
> publish the modifications yet. I will make sure until tomorrow and let you
> know about the details.
>
> On Apr 9, 2015 5:27 PM, "Christian Monterroso" <notifications@github.com>
> wrote:
>
>> Is this something that you can share until such a time that it is pulled?
>> Do you have a fork or branch that we could view?
>>
>> Thanks for working on the problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PointCloudLibrary/pcl/issues/1149#issuecomment-91264578>
>> .
>>
>


-- 
Mohammad

**Comment by VictorLamoine** [comment]
@mshafiei Can you share with us the modifications done?

**Comment by janekT** [comment]
Hi, 
Did anyone solved this issue? Or shoulůd I try to find my way? thanks

**Comment by VictorLamoine** [comment]
This issue is not solved yet.

**Comment by janekT** [comment]
Hi, I think I have a solution. 
I change picking events to get actors of selected point. Please see the attached code in pullrequest #1529  and test it. I am still a newbie in vtk and  c++.

**Comment by larshg** [comment]
Should have been added by https://github.com/PointCloudLibrary/pcl/pull/5476
