### ISSUE TITLE
[docs] Point out that `POINT_CLOUD_REGISTER_POINT_STRUCT` can't be used from inside a namespace

### ISSUE THREAD

**Issue by cjhanks** [PointCloudLibrary/pcl#1152]
Hi,

Defining a type using this macro while within some arbitrary namespace does not work.  In retrospect, that seems reasonable, however I thought I would create this grepable ticket since error messages aren't obvious.  No mention is made in this documentation ->http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php#example

If you can point me to where to update documentation, I would be happy to add the line.

Ie:

```
namespace terrestrial {
struct FusedLidarFull {
    union {
        struct {
            double x;
            double y;
            double z;
        };

        double xyz[3];
    };
};

POINT_CLOUD_REGISTER_POINT_STRUCT(FusedLidarFull,
        (double, x, x)
        (double, y, y)
        (double, z, z)
)

} // ns terrestrial
```

error: 'name' is not a class template
error: wrong number of template arguments (3, should be 1)
error: provided for 'template<int dummy> struct terrestrial::pcl::traits::name'
error: template declaration of 'const char terrestrial::pcl::traits::value []'

```
```

**Comment by taketwo** [comment]
Hi, it would be great if you clarify the tutorial. Please send us a patch against [this](https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/adding_custom_ptype.rst) file.

**Comment by kunaltyagi** [comment]
[New link to tutorial](https://pcl-tutorials.readthedocs.io/en/latest/adding_custom_ptype.html#adding-custom-ptype)

**Comment by themightyoarfish** [comment]
Any chance to get this added to the docs?
