### ISSUE TITLE
Using POINT_CLOUD_REGISTER_POINT_STRUCT with uint64_t does not work

### ISSUE THREAD

**Issue by cjhanks** [PointCloudLibrary/pcl#1153]
I have a structure type I want to register as a PCL type, one of the elements of that structure is a `uint64_t`, it fails with the error

```
error: 'value' is not a member of 'pcl::traits::asEnum<long unsigned int>'
 POINT_CLOUD_REGISTER_POINT_STRUCT(...
```

I believe I have tracked the root cause in two files:
1. A few missing type specializations.
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_traits.h#L73
2. A missing enumeration:
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/PCLPointField.h#L27

Is there any great reason which uint64 types are not permitted as field types?  Is there any objection to them being added?  I can see that there are a few other locations which may need specialization...

**Comment by taketwo** [comment]
@rbrusu could you comment on why `uint64` type is not supported?

I am not intimately familiar with the evolution of PCL in its early years, but from my current perspective there is no reason why we can not have `uint64` fields. Of course, we'll need to make sure that we don't break PCL on all supported platforms and also that the conversion between PCL and ROS messages does not break.

**Comment by nightsparc** [comment]
Got the same problem here :) 
Seems to be an old (but still unfixed) issue with uint64_t. @cjhanks I know, long time ago - ...have you fixed it? Or just lived with it?

@taketwo Where there any attempts from your side to fix this? *Should* this be fixed?

**Comment by taketwo** [comment]
I don't recall any new requests/attempts to add 64-bit int fields.

There clearly is not much demand for it. But if you need it and want to spend effort implementing it, then why not.

**Comment by nightsparc** [comment]
Yeah, that shouldn't be a big problem...but I'm a bit unsure due to your comment:

> Of course, we'll need to make sure that we don't break PCL on all supported platforms and also that the conversion between PCL and ROS messages does not break.

I'm not quite familiar with this PCL/ROS conversion...we're using PCL standalone here atm. Any more hints or ideas what (or how) could be broken...by adding a new trait and extending this enum? I did a short compile and integration test in our own setup here...but that's not really comprehensive.

**Comment by taketwo** [comment]
Basically, we need to grep the whole codebase for `PCLPointField` and `.fields` to find every location where the fields are directly manipulated and a) extend `switch` constructs where appropriate; b) verify that logic is not broken due to addition of new type.

**Comment by cjhanks** [comment]
@nightsparc I don't recall what I did to fix, I might have just used a `double` as a work around (which would have likely been enough bits for me).  I haven't been using PCL for some time, though,

**Comment by PeterQFR** [comment]
Hi I'm interested in this for communicating microsecond timing data for points, and having long representation on non-double enabled gpu. 64 bit integers are just as basic requirement as double, so it would be handy to have supported natively.
