### ISSUE TITLE
PCA does not recompute when setIndices is called

### ISSUE THREAD

**Issue by tmoerwald** [PointCloudLibrary/pcl#1161]
since the setIndices functions are not overwritten, PCA is not computed when working on a different set of indices. The following functions are missing in common/pca.h

inline void 
setIndices (const IndicesPtr &indices)
{ 
    Base::setIndices (indices);
    compute_done_ = false;
}

 void
 setIndices (const PointIndicesConstPtr &indices)
 {
    Base::setIndices (indices);
    compute_done_ = false;
  }

**Comment by jspricke** [comment]
Hi Thomas,

good catch, can you send a pull request with the patch? Thanks!

**Comment by tmoerwald** [comment]
Hi Jochen,
I'm on it. It seems that the pcl_common module does not recompile when I change pca.h or pca.hpp (no cpp file in sources). However, I'll test the changes on my own examples and send the pull request when finished.
