### ISSUE TITLE
Can't build PCL_Filters on Mac OS X...

### ISSUE THREAD

**Issue by drhalftone** [PointCloudLibrary/pcl#1166]
I followed the instructions for installing on Mac OS X using Brew with the following options:

brew install pcl --without-apps --without-tools --without-vtk --without-qt

Here is the error message that I'm receiving:

=> make
/usr/local/Library/ENV/4.3/clang++  -ftemplate-depth=1024 -Qunused-arguments -Wno-invalid-offsetof  -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.7.0 -current_version 1.7.2 -o ../lib/libpcl_filters.1.7.2.dylib -install_name /tmp/pcl-geXb2z/pcl-pcl-1.7.2/macbuild/lib/libpcl_filters.1.7.dylib CMakeFiles/pcl_filters.dir/src/conditional_removal.cpp.o CMakeFiles/pcl_filters.dir/src/crop_box.cpp.o CMakeFiles/pcl_filters.dir/src/extract_indices.cpp.o CMakeFiles/pcl_filters.dir/src/filter.cpp.o CMakeFiles/pcl_filters.dir/src/filter_indices.cpp.o CMakeFiles/pcl_filters.dir/src/passthrough.cpp.o CMakeFiles/pcl_filters.dir/src/shadowpoints.cpp.o CMakeFiles/pcl_filters.dir/src/project_inliers.cpp.o CMakeFiles/pcl_filters.dir/src/radius_outlier_removal.cpp.o CMakeFiles/pcl_filters.dir/src/random_sample.cpp.o CMakeFiles/pcl_filters.dir/src/normal_space.cpp.o CMakeFiles/pcl_filters.dir/src/sampling_surface_normal.cpp.o CMakeFiles/pcl_filters.dir/src/statistical_outlier_removal.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid.cpp.o CMakeFiles/pcl_filters.dir/src/approximate_voxel_grid.cpp.o CMakeFiles/pcl_filters.dir/src/bilateral.cpp.o CMakeFiles/pcl_filters.dir/src/fast_bilateral.cpp.o CMakeFiles/pcl_filters.dir/src/fast_bilateral_omp.cpp.o CMakeFiles/pcl_filters.dir/src/crop_hull.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_covariance.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_label.cpp.o CMakeFiles/pcl_filters.dir/src/frustum_culling.cpp.o CMakeFiles/pcl_filters.dir/src/covariance_sampling.cpp.o CMakeFiles/pcl_filters.dir/src/median_filter.cpp.o CMakeFiles/pcl_filters.dir/src/voxel_grid_occlusion_estimation.cpp.o CMakeFiles/pcl_filters.dir/src/normal_refinement.cpp.o CMakeFiles/pcl_filters.dir/src/grid_minimum.cpp.o CMakeFiles/pcl_filters.dir/src/morphological_filter.cpp.o CMakeFiles/pcl_filters.dir/src/local_maximum.cpp.o CMakeFiles/pcl_filters.dir/src/model_outlier_removal.cpp.o /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib -lm ../lib/libpcl_sample_consensus.1.7.2.dylib ../lib/libpcl_search.1.7.2.dylib ../lib/libpcl_kdtree.1.7.2.dylib ../lib/libpcl_octree.1.7.2.dylib ../lib/libpcl_common.1.7.2.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib -lm /usr/local/lib/libflann_cpp.dylib 
cd /tmp/pcl-geXb2z/pcl-pcl-1.7.2/macbuild/filters && /usr/local/Cellar/cmake/3.1.3/bin/cmake -E cmake_symlink_library ../lib/libpcl_filters.1.7.2.dylib ../lib/libpcl_filters.1.7.dylib ../lib/libpcl_filters.dylib
/usr/local/Cellar/cmake/3.1.3/bin/cmake -E cmake_progress_report /tmp/pcl-geXb2z/pcl-pcl-1.7.2/macbuild/CMakeFiles  22 23 24 25 26 27 28 29 30 31 32 33 34
[ 48%] Built target pcl_filters
make: *** [all] Error 2

**Comment by drhalftone** [comment]
Here is my latest attempt to include PCL on my MBP:

DrHalftone:lib dllau$ brew install homebrew/science/pcl --without-apps --without-tools --without-vtk --without-qt --HEAD
==> Installing pcl from homebrew/homebrew-science
==> Cloning https://github.com/PointCloudLibrary/pcl.git
Updating /Library/Caches/Homebrew/pcl--git
==> Checking out branch master
==> Patching
patching file cmake/pcl_find_cuda.cmake
Hunk #2 succeeded at 45 (offset 8 lines).
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/pcl/HEAD -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_S
==> make
/usr/local/Library/ENV/4.3/clang++  -ftemplate-depth=1024 -Qunused-arguments -Wno-invalid-offsetof  -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.8.0 -current_version 1.8.0 -o ../lib/libpcl_surface.1.8.0.dylib -install_name /tmp/pcl-bBL7qx/macbuild/lib/libpcl_surface.1.8.dylib CMakeFiles/pcl_surface.dir/src/processing.cpp.o CMakeFiles/pcl_surface.dir/src/ear_clipping.cpp.o CMakeFiles/pcl_surface.dir/src/gp3.cpp.o CMakeFiles/pcl_surface.dir/src/grid_projection.cpp.o CMakeFiles/pcl_surface.dir/src/marching_cubes.cpp.o CMakeFiles/pcl_surface.dir/src/marching_cubes_hoppe.cpp.o CMakeFiles/pcl_surface.dir/src/marching_cubes_rbf.cpp.o CMakeFiles/pcl_surface.dir/src/bilateral_upsampling.cpp.o CMakeFiles/pcl_surface.dir/src/mls.cpp.o CMakeFiles/pcl_surface.dir/src/organized_fast_mesh.cpp.o CMakeFiles/pcl_surface.dir/src/simplification_remove_unused_vertices.cpp.o CMakeFiles/pcl_surface.dir/src/surfel_smoothing.cpp.o CMakeFiles/pcl_surface.dir/src/texture_mapping.cpp.o CMakeFiles/pcl_surface.dir/src/poisson.cpp.o CMakeFiles/pcl_surface.dir/src/concave_hull.cpp.o CMakeFiles/pcl_surface.dir/src/convex_hull.cpp.o CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/factor.cpp.o CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/geometry.cpp.o CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/marching_cubes_poisson.cpp.o /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib -lm ../lib/libpcl_search.1.8.0.dylib ../lib/libpcl_kdtree.1.8.0.dylib ../lib/libpcl_octree.1.8.0.dylib /usr/local/lib/libqhull_p.dylib ../lib/libpcl_common.1.8.0.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib -lm /usr/local/lib/libflann_cpp.dylib 
cd /tmp/pcl-bBL7qx/macbuild/surface && /usr/local/Cellar/cmake/3.1.3/bin/cmake -E cmake_symlink_library ../lib/libpcl_surface.1.8.0.dylib ../lib/libpcl_surface.1.8.dylib ../lib/libpcl_surface.dylib
/usr/local/Cellar/cmake/3.1.3/bin/cmake -E cmake_progress_report /tmp/pcl-bBL7qx/macbuild/CMakeFiles  91 92 93 94 95 96 97 98
[ 38%] Built target pcl_surface
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

**Comment by fran6co** [comment]
There were some fixes to the formula, could you test it again?

**Comment by drhalftone** [comment]
I am trying to find time to get to this.  I need initially to go back and see if the NaN filter error is repeatable, but this is on my radar.  On another note, is there any examples or documentation about how to extract the last set of point pairings from ICP as well as how to get the error in the best-fit.  I know there is a way to get the data output to disk, but I wanted my source code to read that data from the ICP object.




On May 4, 2015, at 9:59 AM, Francisco Facioni <notifications@github.com> wrote:

There were some fixes to the formula, could you test it again?

**Comment by SergioRAgostinho** [comment]
Just gave it a try with the current recipe, passing the options mentioned in the OP and pcl was built correctly. 

It should be ok to close this.
