### ISSUE TITLE
Problem in loadOBJFile

### ISSUE THREAD

**Issue by ghost** [PointCloudLibrary/pcl#1169]
Hi, 

I believe there is a bug in loadOBJFile. Suppose I want to load a textured obj file into a TextureMesh.

I tried loadPolygonFileOBJ

``` cpp
pcl::TextureMesh mesh1;
pcl::io::loadPolygonFileOBJ ("mesh.obj", mesh1);
pcl::visualization::PCLVisualizer visu("Test");
visu.addTextureMesh (mesh1,"texture");
visu.spin ();
```

This one shows the model without texture. I look into the code it seems it is using a dummy material, and the readme also said there won't be material yet.

I also tried

``` cpp
pcl::TextureMesh mesh2;
pcl::io::loadOBJFile ("mesh.obj", mesh2);
pcl::visualization::PCLVisualizer visu("Test");
visu.addTextureMesh (mesh2,"texture");
visu.spin ();
```

This one shows "[PCLVisualizer::addTextureMesh] No textures coordinates found!", and I look into the code and realized the "vt" in the obj file has to appear before "usemtl" otherwise the texture coordinates won't be pushed, note that loadPolygonFileOBJ does not have this problem. But when I rearrange the "vt" to appear in front of "usemtl", it shows texture but it looks all messed up.

However, I somehow got it to work in a dirty way...

``` cpp
pcl::TextureMesh mesh1;
pcl::io::loadPolygonFileOBJ ("mesh.obj", mesh1);
pcl::TextureMesh mesh2;
pcl::io::loadOBJFile ("mesh.obj", mesh2);
mesh1.tex_materials = mesh2.tex_materials;
pcl::visualization::PCLVisualizer visu("Test");
visu.addTextureMesh (mesh1,"texture");
visu.spin ();
```

This works but I had to load the model twice with loadPolygonFileOBJ and loadOBJFile just to get the correct pieces from both. I am using the latest trunk. Please let me know if I miss anything

Thanks

**Comment by HaiyangXu** [comment]
As the documents say` loadPolygonFileOBJ(const std::string &,
pcl::TextureMesh & )`will not not load the material information,it only load uv-coordinates in addition to  `loadPolygonFileOBJ (const std::string, pcl::PolygonMesh&)`.

so I guess some bug is in `pcl::io::loadOBJFile	(	const std::string & 	file_name,
pcl::TextureMesh & 	mesh 
)	` it dose not load the textures coordinates right.
**ref:**
PCL_EXPORTS int [pcl::io::loadPolygonFileOBJ](http://docs.pointclouds.org/1.7.0/group__io.html#ga2b90827631bdbb91202f526348207cce)	(	const std::string & 	file_name,
pcl::TextureMesh & 	mesh 
)		
Load an OBJ file into a TextureMesh object.

Note

>In addition to the loadPolygonFileOBJ (const std::string, pcl::PolygonMesh&) method, this method also loads the uv-coordinates from the file. It does not load the material information.

Parameters

[in]	file_name	the name of the file that contains the data
[out]	mesh	the object that we want to load the data in

**Comment by 761687049** [comment]
hello,I load all the information , but when show, I can't see the picture information . it just is white. I don't know how to use the .png information .

**Comment by taketwo** [comment]
Closing this in favor of #2252.
