### ISSUE TITLE
[cmake] Detect GLU and disable targets using it if GLU is not found

### ISSUE THREAD

**Issue by de-vri-es** [PointCloudLibrary/pcl#1173]
When compiling pcl 1.7.2 on archlinux without glu installed, I get a compilation error that `GL/glu.h` can not be found.  I realise this can be fixed easily by installing glu but it seems to me that cmake should have errored out before compilation even started or disabled whatever features depend on glu.

As far as I can tell, the cmake files look for opengl and optionally glut, but not glu.

```
/build/pcl/src/pcl-pcl-1.7.2/apps/point_cloud_editor/src/cloudEditorWidget.cpp:51:21: fatal error: GL/glu.h: No such file or directory
 # include <GL/glu.h>
```

**Comment by taketwo** [comment]
PCL looks for `OpenGL` (in "pcl_find_gl.cmake"):

```
find_package(OpenGL QUIET REQUIRED)
```

According to the comments in "FindOpenGL.cmake" that is distributed with _CMake_:

> This module sets the following variables:
> ``OPENGL_GLU_FOUND``
> True, if the system has GLU.

Therefore it should be easy to check whether _GLU_ is present before creating targets that depend on it. Pull requests welcome!
