### ISSUE TITLE
pcl::io::OrganizedConversion applies focal length twice when passed DepthData

### ISSUE THREAD

**Issue by ngoonee** [PointCloudLibrary/pcl#1180]
Came across this simple bug when I was attempting to re-create my Asus Xtion point clouds from the provided depth map and RGB image.

In line 543, the inverse of focal length is calculated.
In line 552, the pixel depth is obtained from depthData.
In line 556, a new value 'depth' is obtained using focal length over pixel depth (this does not make sense)
In lines 559-560, values for z, x, and y are found based on the inverse and this 'depth' value.

Effectively, focal length has been applied twice, and the resulting cloud is wrong. With focal lengths of close to 10, 100, 1000 this will not be very evident visually, but the measurement values are then unreliable.

The correct procedure (which is used in openni2_grabber.cpp) is to use the depth value obtained from depthData directly as the z value while applying the inverse of focal length (multiplied with depth) to the x and y values.

This is easily accomplished by changing line 556 to set depth = pixel_depth. The same should be done for the non-RGB template in line 254.

P.S. - While I was looking at this, why the hell is there a test for pixel_depth == pixel_depth in line 554? It should probably just be a text for pixel_depth (refer line 251).

Anyway, I've tested the fixed I talk about on top and they work for me.

**Comment by jspricke** [comment]
Hi @ngoonee, thanks for looking into it. Can you please send a pull request? Just ask, if you need help.

**Comment by ngoonee** [comment]
Wow this was a long time ago. @jspricke not sure if the PR was ever considered?

**Comment by jspricke** [comment]
@ngoonee the PR is still open, someone needs to find time to review it.

**Comment by kunaltyagi** [comment]
Which PR is it? Could you link it here please?

**Comment by jspricke** [comment]
@kunaltyagi it's linked above but the PR is not against mainline but @ngoonee fork (that's why it was never considered): https://github.com/ngoonee/pcl/pull/1. @ngoonee can you open a PR for this repo?

**Comment by ngoonee** [comment]
Sorry I've lost access to the equipment (and the workplace) where I was doing this work. It's a two line change, but one line no longer applies cleanly. Honestly I'm not sure if this is still an issue since I'm no longer working on that project.
