### ISSUE TITLE
PFH buffer erases most recent element

### ISSUE THREAD

**Issue by strothmw** [PointCloudLibrary/pcl#1188]
At

https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/pfh.hpp#L147

the most recent element is erased from the feature map --> however, this element it most likely the most useful one in future calculations. Moreover, a wrong key is erased from the key map.

The doc of std::queue says:

http://www.cplusplus.com/reference/queue/queue/

back ->    Access last element (public member function )
pop ->   Remove next element (public member function )

Therefore at
https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/pfh.hpp#L147
 feature_map_.erase (key_list_.back ());

the last element is erased from feature map

but at 

https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/pfh.hpp#L148
 key_list_.pop ();

the next element is poped from the key list. This is inconsistent. I think it'd better be

 feature_map_.erase (key_list_.front());

front ->   Access next element (public member function )

**Comment by taketwo** [comment]
I think you are right.
