### ISSUE TITLE
PFH buffer, addes to key list even is key was found

### ISSUE THREAD

**Issue by strothmw** [PointCloudLibrary/pcl#1189]
At

https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/pfh.hpp#L142

the key will be added to the key list, even if it was found at (i. e. is not new)

https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/pfh.hpp#L97

Therefore the key list may contain duplicate keys and the feature map will be truncated even if it has not yet reached the allowable size in memory.

**Comment by taketwo** [comment]
I think you are right. Could you please create a separate pull request with your solution?
