### ISSUE TITLE
Is travis.ci currently not working??

### ISSUE THREAD

**Issue by strothmw** [PointCloudLibrary/pcl#1193]
The build failed for my PR 1191 somewhere in registation, while I've only made minor changes to features module:

https://travis-ci.org/PointCloudLibrary/pcl/jobs/55833431

Moreover, it's failing for many other currently pending PRs apparently at the same point???

**Comment by jspricke** [comment]
Yes, we are running out of memory and computing time. Sometimes it works, so we kept it till now. Making PCL work with the free Travis would mean to restructure the library dependencies and unit tests. For now ignore the errors.

**Comment by VictorLamoine** [comment]
Travis builds are now working fine thanks to Sergey's work (#1302 #1303).
