### ISSUE TITLE
pcl_ensenso_viewer calls pure virtual method

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1200]
I only noticed this behavior after updating the Ensenso SDK to `1.2.348`
```cpp
$ pcl_ensenso_viewer 
Initialising nxLib
Opening Ensenso stereo camera id = 0
FPS: 4.26439
FPS: 4.06268
FPS: 3.83008
FPS: 4.12265
FPS: 4.35143
Closing Ensenso stereo camera
pure virtual method called
terminate called without an active exception
Aborted
```

Threads about this:
http://stackoverflow.com/questions/1987602/pure-virtual-method-called
http://stackoverflow.com/questions/2167335/pure-virtual-method-called

The problems probably lies in the [virtual destructor](http://stackoverflow.com/questions/461203/when-to-use-virtual-destructors).

- [ ] Test with latest Ensenso SDK

**Comment by taketwo** [comment]
Is this still a problem? Would be nice to have it fixed before releasing Ensenso grabber for the first time.

**Comment by VictorLamoine** [comment]
I test with the new Ensenso SDK version tomorrow and keep you posted!

**Comment by VictorLamoine** [comment]
I can't reproduce this issue with the new SDK version:
- Ensenso SDK `1.3.167`
- PCL trunk

I can't test with the old version because I didn't keep an archive of the installer!

**Comment by VictorLamoine** [comment]
I wanted to check a mnimum Ensenso version at PCL configuration but it's not possible as is.
Ensenso now provides a [FindEnsenso.cmake - Version 1.3.146](http://www.ensenso.com/manual/) file on Linux installs but no way to check the version via CMake.

Closing

**Comment by taketwo** [comment]
If you have some spare time, version detection is actually not that hard to implement. An example from my DepthSense finder script:

```cmake
# Version
  set(DSSDK_VERSION 0)
  file(STRINGS "${DSSDK_INCLUDE_DIRS}/DepthSenseVersion.hxx" _dsversion_H_CONTENTS REGEX "#define DEPTHSENSE_FILE_VERSION_STRING.*")
  set(_DSSDK_VERSION_REGEX "([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)")
  if("${_dsversion_H_CONTENTS}" MATCHES ".*#define DEPTHSENSE_FILE_VERSION_STRING .*${_DSSDK_VERSION_REGEX}.*")
    set(DSSDK_VERSION "${CMAKE_MATCH_1}")
  endif()
  unset(_dsversion_H_CONTENTS)
```

Typically, there would be some "version.h", "config.h", or whatever file inside SDK that has a macro defining the version. You need to find it and construct an appropriate regex to get the version out. That's it!
