### ISSUE TITLE
Problems with openMP, pointers, and MSVC++ in KLT tracker

### ISSUE THREAD

**Issue by mdering** [PointCloudLibrary/pcl#1208]
I am using visual studio 2013. the klt tracker will segfault on any invocation of compute() due to this variable at this line. I believe there are pointer issues somewhere since the pointer reliably has an integer value, but I cannot determine where.

**Comment by mdering** [comment]
this is an unfortunate title since I think the issue is a problem with the openMP support provided by VS. the openmp clause provided there seems to be causing an error with the variable in the title, ii. This is a shame since I'll need to disable this feature for the whole program if i wish to use KLT. I'm not familiar is there a way to require a certain version of openmp for a specific pragma? That might be the best solution for this, since VS does not support 3.0 and has no plans to.

**Comment by mdering** [comment]
I'll refine this further. If you check out [this here](https://github.com/PointCloudLibrary/pcl/blob/3b867193538bdf57cb7ec04e7a9350f2c210d892/tracking/include/pcl/tracking/impl/pyramidal_klt.hpp#L237), this pragma is defined if _OPENMP is, which is not enough since ii refers to a pointer. Can someone change this so it requires both OPENMP and not MSVC? Perhaps if there's time later I can do it myself.

**Comment by mdering** [comment]
I opened pull request https://github.com/PointCloudLibrary/pcl/pull/1214 which should resolve this issue.

**Comment by taketwo** [comment]
(If you add something like "Fixes #1208" to the pull request description, this issue will be closed automatically as soon as the pull request is merged.)
