### ISSUE TITLE
ICP problem: transformation becomes crippled when translating simple point cloud 

### ISSUE THREAD

**Issue by gismo141** [PointCloudLibrary/pcl#1209]
When using a simple point cloud:
- with 8 points,
- formed as quader with:
  - 8 vertices `V1` of length `a`
  - and 4 vertices `V2` connecting both planes >= 2*`a`

and translating the cloud in direction of the vertices `V2` by `a`, the transformation gets crippled.

See [gismo141/pcl_mover/pcl_icp.cpp](https://github.com/gismo141/pcl_mover/blob/master/pcl_icp.cpp) for an implementation, showing the problem.

**Comment by VictorLamoine** [comment]
The problem you showcase is a drawback of the ICP algorithm, not it's implementation.
A "solution" to this problem is to set a very low threshold so that ICP continues even with a very good score; but there comes the question.. when to stop?

ICP is ok for fine tuning alignments, it won't work for coarse alignments. Here you are trying to do coarse alignement.

**Comment by gismo141** [comment]
I partly agree with you, but when you change the parameter QUAD_LENGTH to a smaller value than 1.9f you get no problem. Also when you keep the QUAD_LENGTH larger and you move the quader differently (in y axis instead of x) you don't get the problem either.

That is the thing that made it interesting ;)

**Comment by gismo141** [comment]
Do you have any update or further information on this subject?

**Comment by VictorLamoine** [comment]
I have just tested your code (thanks for it) with PCL latest trunk, the transformation gets weird after we reach the `QUAD_LENGTH / 2` translation you talk about.

[Video clip](https://mega.nz/#!RUsSRJTL!BY7sBxnJ8NigoE5jxNEreq98Z6bFjWGXpQ4UEnaGGaY)

There is indeed something wrong here!

**Comment by gismo141** [comment]
Exactly!
The interesting thing is, when you transform the cloud in **y-axis** instead of **x** the problem disappears.

e.g.:
```c++
for (size_t i = 0; i < cloud_out->points.size (); ++i)
      cloud_out->points[i].y = cloud_out->points[i].y + 0.02f;
```

Also the problem disappears when `QUAD_LENGTH` is smaller than `1.9f`.

**Comment by gismo141** [comment]
@VictorLamoine do you have any updates on this subject?

**Comment by VictorLamoine** [comment]
No sorry.
One needs to dig into the code to find what's wrong, I don't have time to do so right now.

**Comment by gismo141** [comment]
Alright thanks for your effort!

**Comment by kunaltyagi** [comment]
The source code and the video are unavailable. Closing due to lack of info to proceed
