### ISSUE TITLE
CMake, OSX 10.10 and clang-omp problems

### ISSUE THREAD

**Issue by mdering** [PointCloudLibrary/pcl#1219]
When compiling with a brewed version of clang-omp, since brewed gcc for mac will fail on the objective-c files included (should this be an issue too, with someone?), and normal mac clang does not support openMP, the cmake file shipped with pcl fails on the linking phase, because of generated -Wl with no options appended to it which appear in link.txt for every module. I'm not by any means a cmake expert so I cannot figure out how to fix this myself, but I did eventually find the provenance of these -Wl's, in [cmake/pcl_targets.cmake](https://github.com/PointCloudLibrary/pcl/blob/ad223dd2d3da5f85b8ad61fbecae8e5869a81e02/cmake/pcl_targets.cmake#L208). By adding a dummy -w (suppressing linker warnings) to the end of these lines (208, 256, 298, 344, 391 and 429), I was able to successfully link. To be honest, this seems like a bad workaround to me, so I wanted to open this issue and see if a more experienced cmake user could provide insight as to why this happened and how to fix it. 

Steps needed to reproduce:

* install clang-omp with homebrew `brew install clang-omp` 
* direct cmake to these compilers by setting CXX and C compilers to `clang-omp++` and `clang-omp` respectively (I did this using the cmake gui, from the caskroom)
* Configure all the other cmake options as normally as possible (I can provide my cache if needed)
* Generate makefiles and compile using make, and it will fail because of an invalid option `-Wl'. 

Can someone help, or point me in the right direction, so I can make a more convincing change here? 

Thanks
Matt

**Comment by SergioRAgostinho** [comment]
This problem was fixed in in the combo #1454, #1434 and #1414. 

Should be good to be closed.
