### ISSUE TITLE
Bug in GreedyProjectionTriangulation::connectPoint

### ISSUE THREAD

**Issue by donno** [PointCloudLibrary/pcl#1220]
The following line found in pcl::GreedyProjectionTriangulation::connectPoint looks very suspicious and like a potential bug:
`
if ((ffn_[sfn_[next_index]] = ffn_[current_index_]) || (sfn_[sfn_[next_index]] == ffn_[current_index_]))
`
The = looks like it should be ==, given that the rest of the statement is the similar looking if statement in the other case in the switch statement..

[gp3.hpp](https://github.com/PointCloudLibrary/pcl/blob/d78270ab50b550d89d1e9d4890f4700cf44071f1/surface/include/pcl/surface/impl/gp3.hpp#L1482)

**Comment by taketwo** [comment]
Indeed, looks suspicious. However, if we want to change this line, it's better to actually understand the logic behind and not base the decision only on "look-alike" reasoning.

**Comment by donno** [comment]
Two years later, @puzzlepaint pointed out that the same thing that I did here but in pull request #1879.

You signed on of the pull request and it has been accepted so this issue has been resolved.
