### ISSUE TITLE
 fmin calling host function error with Cuda 7 and MSVC 12.0

### ISSUE THREAD

**Issue by benbennett** [PointCloudLibrary/pcl#1224]
gpu/kinfu_large_scale/src/cuda/tsdf_volume.cu(250) (col. 25) : error : calling a __host__ function("fmin<int, float> ") from a __device__ function("pcl::device::kinfuLS::Tsdf::operator ()") is not allowed
Reference #812  was the same issue.  
Doing same fix as #813 

I have a fix and will push to my fork soon.

**Comment by taketwo** [comment]
Fixed with #1225.
