### ISSUE TITLE
Boost asio throws exception before entering main

### ISSUE THREAD

**Issue by brotherofken** [PointCloudLibrary/pcl#1238]
hdl_grabber.cpp:52

```
const boost::asio::ip::address pcl::HDLGrabber::HDL_DEFAULT_NETWORK_ADDRESS = boost::asio::ip::address::from_string ("192.168.3.255");
```

Call stack screenshot
![Call stack screenshot](http://i.snag.gy/pgxIS.jpg)

Error code `m_val = 10106 (0x0000277a)` (Windows Sockets error?)

System: PCL 1.72 (tag 1.72 from github), Windows 7 64-bit, boost 1.57, Visual Studio 2013 x64.

For some reason I cannot reproduce it on another PC with similar setup, probably because of my wrong configuration. But I still cannot figure out how to eliminate this exception.

Thank you.

**Comment by kunaltyagi** [comment]
PCL doesn't use boost asio. Please reopen with more information if you feel the issue is still in PCL.
