### ISSUE TITLE
Allow displaying LUT in PCLVisualizer when adding a vtkPolyData

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1240]
Colors are nice (#1143) but the LUT cannot be displayed, when `U` is pressed in the visualizer:

```
Warning: In /build/buildd/vtk-5.8.0/Rendering/vtkScalarBarActor.cxx, line 270
vtkScalarBarActor (0x840a9a0): Need a mapper to render a scalar bar
```

A problem arise if the user has multiple `vtkPolyData` in the viewer and the LUTs are not the same
- Minimum/maximum scalar values are unlikely to be the same
- The user might have chosen 2 different LUTs for the `vtkPolyData`

https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/interactor_style.cpp#L1057

**Comment by taketwo** [comment]
Well, if there are two different LUTs, then it's not much we can do about it. But if there is only one (which I expect to be the case most often), then it would be nice to have a color bar for it.

**Comment by VictorLamoine** [comment]
Ok, my problem is that there is not `shape_actor_map_` (see https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/interactor_style.h#L261) in the interactor_style; so I don't know how to search for existing shape actors in the renderer.
