### ISSUE TITLE
PCLVisualizer shape handling is bad

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1244]
This simple example will crash the PCLVisualizer:
```cpp
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/pcl_visualizer.h>

int
main (int argc,
      char *argv[])
{
  pcl::visualization::PCLVisualizer viewer ("Viewer");
  viewer.addText("coucou", 50, 50, "text");
  pcl::PointXYZ p1 (0, 0, 0), p2 (1, 1, 1);
  viewer.addLine(p1, p2, "line");
  viewer.updateText("make the visualizer crash", 50, 50, "line");
  viewer.spin();
  return 0;
}
```

Both `text` and `line` are added in the `shape_actor_map_`, so when you try to update the ID `line` as if it was a text, the ID is found and the [`SafeDownCast`](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L2666) crashes because a `vtkLODActor` (line) cannot be casted into a `vtkTextActor`:

```cpp
vtkTextActor* actor = vtkTextActor::SafeDownCast (am_it->second);
```

**Comment by taketwo** [comment]
I wonder why it is called `safe`? Perhaps it throws an exception? Then we can catch it and warn the user.

**Comment by VictorLamoine** [comment]
I can't find any documentation about this; I would have expected a `NULL` pointer but it throws a segfault.

**Comment by taketwo** [comment]
Are you sure that segfault occurs in down cast, not on the next line, when the pointer is used without NULL check?

**Comment by VictorLamoine** [comment]
Yup
