### ISSUE TITLE
core dumped on ubuntu 14.10 when including any filters

### ISSUE THREAD

**Issue by higerra** [PointCloudLibrary/pcl#1246]
Hi, 
I'm using PCL 1.8 on ubuntu 14.10. Each time I include any header files under 'filters' folder, my program will crash and report segmentation fault even before main function. Seems that the issue is about  pcl/filters/boost.h .
However, everything works perfectly on my OS X Yosemite.
Any one has any idea?
Thanks!

**Comment by higerra** [comment]
OK I figured it out myself.
Briefly, you cannot use c++ 11 with pcl...

**Comment by VictorLamoine** [comment]
Related: #619
