### ISSUE TITLE
SampleConsensusModelLine isSampleGood always returns True

### ISSUE THREAD

**Issue by wolfv** [PointCloudLibrary/pcl#1251]
Not sure if this is intentional but 
https://github.com/PointCloudLibrary/pcl/blob/eb3fafaaf1af77d4f01bfcc1199800c6f46ed5fe/sample_consensus/include/pcl/sample_consensus/impl/sac_model_line.hpp#L58

always returns true.

**Comment by taketwo** [comment]
Looks like a bug.

**Comment by kunaltyagi** [comment]
Fixed in master
