### ISSUE TITLE
transformPointCloud not vectorized

### ISSUE THREAD

**Issue by bricerebsamen** [PointCloudLibrary/pcl#1255]
in `transformPointCloud`, the matrix multiplication is expressed as a manual equation. Why not let Eigen do the transform? See:
https://github.com/PointCloudLibrary/pcl/blob/pcl-1.7.0/common/include/pcl/common/impl/transforms.hpp#L65

In my transform code, I have compared 1) calling `pcl_ros::transformPointCloud` and 2) creating a `Eigen::Vector3f` to represent each point and multiplying by an `Eigen::Affine3f` and I got a 10 times speed improvement.
There are 2 factors to this speedup:
a) I'm using a float transform instead of a double (standard ros tf transform)
b) the Eigen multiplication is vectorized
I haven't quantified the impact of each factor

2 years ago, the ros function to transform a pointcloud used ublas to create a large 4xN matrix to hold all the points and then multiplied it by a transform matrix. This used to be very fast, but that implementation has disappeared. I tried to reproduce this with Eigen but failed.

Anyway, I just wanted to draw some attention on that point, and share my recent experience. It's easy to try and do a benchmark. Maybe there are other factors that I did not consider.

**Comment by taketwo** [comment]
I had the same question some time ago, see [this comment](https://github.com/PointCloudLibrary/pcl/commit/0266f79136d8c214628ba8d86a02bb2a08a431d8#commitcomment-7772811).
