### ISSUE TITLE
.ply files with unix line endings ('LF') cannot be read 

### ISSUE THREAD

**Issue by nyholku** [PointCloudLibrary/pcl#1256]
Attempts to read .ply files which have unix end of line markers ('LF') instead of windows ('CRLF') will result in runtime error:
```
[pcl::PLYReader] /Users/nyholku/sfm2/testdata/test1/sfm_output/reconstruction_global/colorized.ply:2: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
```
converting an offending  .ply file to Windows/DOS format for example with 'unix2dos' utility circumvents the problem.

**Comment by VictorLamoine** [comment]
Reported on the mailing list:
http://www.pcl-users.org/loadPLYFile-problem-parsing-header-td4038565.html
