### ISSUE TITLE
ApproxMVBB

### ISSUE THREAD

**Issue by gabyx** [PointCloudLibrary/pcl#1259]
I am the author of this Library:

Maybe there is interest of fusing this into the PCL library at some time :-)
I think this tool might be handy for some people :-)

Just a thought :-)

https://github.com/gabyx/ApproxMVBB

(using eigen3, and some external sources (its MPL 2.0 licensed so far...? might that work?)

**Comment by kunaltyagi** [comment]
Sorry for the late reply. How is this different from existing OrientedBB algorithms in PCL?

**Comment by kunaltyagi** [comment]
Feel free to create a PR. There's nothing in the license (MPL2 and you're the license holder) that might be an issue. Please do provide the benefits and advantages of your algorithm in the PR. The repo looks interesting with ~250 stars and continuous upkeep.
