### ISSUE TITLE
vtk 3rd party make error

### ISSUE THREAD

**Issue by sketchc89** [PointCloudLibrary/pcl#1268]
I'm compiling 3rd party libraries from pcl-trunk because the current Ubuntu openni libraries aren't recognized when compiling from 1.7.2 release. I'd also like to use some of the features left out of the release like organized_edge_detection. 
I receive the following error when running `make` in cpack.patch.
```
...
patching file VTK/VTKCPack.cmake
patch: **** malformed patch at line 1788: @@ -33,7 +35,6 @@
```
I'm not familiar with .patch files. I commented out everything between the previous `@@ -7,8 +7,15 @@` and this line but received another error 

```
A logical block opening on the line

    /home/sketchc89/pcl/3rdparty/vtk/VTK/VTKCPack.cmake:5 (IF)

  is not closed.
```
which was probably caused by messing with the patch. I went and closed that block and it's errored out again. Could use some help.

**Comment by VictorLamoine** [comment]
Can you detail your configuration?
CMakeCache.txt would be nice.

**Comment by taketwo** [comment]
I'm not really familiar with this "3rdparty" thing, but I suppose it is only for Windows users. On other operating systems you should get dependencies from a package manager.

**Comment by VictorLamoine** [comment]
Yes there is no need to deal with this when using Linux.
Moreover
> the current Ubuntu openni libraries aren't recognized when compiling from 1.7.2 release

Is not true, it has always been working.
@sketchc89 Can you tell us more about your problem?

**Comment by sketchc89** [comment]
The original purpose of compiling from source was to test [organized edge detection](http://www.pointclouds.org/blog/gsoc12/cchoi/index.php) detailed on a GSOC PCL blog post. When I installed from the package managers the package didn't contain the [libraries](https://github.com/PointCloudLibrary/pcl/blob/e8a88803bc5ffdabaf366e02f7e2f72fcf7fd4fb/features/include/pcl/features/organized_edge_detection.h) or examples needed to get this to work.

I thought the best solution was to compile from source. I don't remember if I tried installing all of the libraries in 3rd party from the package manager first or not. I'm not at the workstation this is on currently so I will need to look into the configuration later.

If the library/feature mentioned above is deprecated then there's no need to look into this further. I forget why I said that about openni @VictorLamoine . The only issues I've had with openni is conflicts with ROS's openni drivers.

**Comment by VictorLamoine** [comment]
In general on Ubuntu you can use: (if you have the PPA installed)
`sudo apt-get build-dep libpcl-all`

Another option:
```
sudo apt-get install -y libopenni-dev libboost-all-dev libflann-dev \
libeigen3-dev libvtk5.8* libqhull-dev libusb-1.0 libgtest-dev
```

If you feel that your problem is solved, feel free to close the issue!
