### ISSUE TITLE
Using non-CUDA built PCL with CUDA compile error

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#1272]
How to reproduce the error:

Download the pre-compiled PCL from http://unanancyowen.com/?p=1255. This built does not include CUDA. Write your own CUDA code and link with the pre-compiled PCL, when compiling the error below is shown

nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

This is related to #776, if I remove the VTK definitions from nvcc_flags manually it compiles. However the fix at #824 only address the issue when PCL is built with CUDA. Some fix should be applied in the situation where PCL is not built with CUDA but will be linked with other pre-existing CUDA code. Do someone know how to fix it?

**Comment by jasjuang** [comment]
Using pre-compiled PCL is an outdated approach so no need to solve this issue anymore. The best approach now to build PCL on windows is using [vcpkg](https://github.com/Microsoft/vcpkg/).

**Comment by taketwo** [comment]
I'm not into Windows and vcpkg. What's the status of this? Is it trivial to get PCL through this mechanism? Do you think we need a tutorial on that?

**Comment by taketwo** [comment]
Sounds great.
If anyone has a bit of time, a pull request with a tutorial similar to [Homebrew](http://pointclouds.org/documentation/tutorials/installing_homebrew.php#installing-homebrew), but for vcpkg will be super welcome.
