### ISSUE TITLE
Croos Compile for Raspberry pi 

### ISSUE THREAD

**Issue by praveen-science** [PointCloudLibrary/pcl#1281]
I want crass compile PCL library for Raspberry PI 2. I successfully built a toolchain in my Ubuntu for Raspberry pi 2 called 'arm-unknown-linux-gnueabi-gcc'. 

I want to know how to compile PCL using this toolchain, and transfer to Raspberry pi 2.   

Any help would be great. 
Thanking you in advance.

**Comment by jspricke** [comment]
PCL is in the Ubuntu and Debian repos, compiled for armhf, which should work on the Pi2 out of the box. Closing as not PCL related.
