### ISSUE TITLE
no member named 'loadPLYFile' in namespace 'pcl::io' on Mac Brew

### ISSUE THREAD

**Issue by pranny** [PointCloudLibrary/pcl#1284]
The [docs](http://docs.pointclouds.org/trunk/group__io.html#gaabd8b779b0be30eec7c2c7af8fa6f3c8) suggest the method [pcl::io::loadPLYFile](http://docs.pointclouds.org/trunk/group__io.html#gaabd8b779b0be30eec7c2c7af8fa6f3c8). However, when I try using pcl::io::loadPLYFile, I get the error saying

`error: no member named 'loadPLYFile' in namespace 'pcl::io'; did you mean 'loadPCDFile'?`

I am using Brew on OS X Yosemite. I was earlier using PCL 1.7.2 (which is what is installed if you do `brew install pcl`). However, I updated pcl by uninstalling 1.7.2 and installing from HEAD (1.8) by `brew install pcl --HEAD`. I am still getting the error.

I am trying to run the [Robust Pose Estimation](http://pointclouds.org/documentation/tutorials/alignment_prerejective.php) example, with loadPLYFile instead of loadPCDFile.

What could be going wrong here?

**Comment by pranny** [comment]
The above error goes away when by adding following line
`#include <pcl/io/ply_io.h>`

**Comment by Leedehai** [comment]
I added `include <pcl/io/ply_io.h>`, the error didn't go away..

**Comment by taketwo** [comment]
This issue is about `loadPLYFile`, and you have problems with `loadPCDFile`. You need `pcl/io/pcd_io.h` header.
