### ISSUE TITLE
PCLConfig.cmake needs to be updated for OS X

### ISSUE THREAD

**Issue by ahundt** [PointCloudLibrary/pcl#1289]
The part that finds GLEW is fairly broken on mac. The mac specific section can pretty much be eliminated and replaced with the simpler version below, at least as far as I can tell with my homebrew based install.

Starting at line 442 of PCLConfig.cmake:

```cmake
ELSE (WIN32)

    FIND_PATH( GLEW_INCLUDE_DIR GL/glew.h
      /usr/include/GL
      /usr/openwin/share/include
      /usr/openwin/include
      /usr/X11R6/include
      /usr/include/X11
      /opt/graphics/OpenGL/include
      /opt/graphics/OpenGL/contrib/libglew
      /usr/local/include
    )

    FIND_LIBRARY( GLEW_GLEW_LIBRARY GLEW
      /usr/openwin/lib
      /usr/X11R6/lib
      /usr/local/lib
    )

ENDIF (WIN32)

```

#492 mentions some things to this effect, but since it is closed I don't think the changes were being merged. Note that I added `/usr/local/lib` which is where homebrew installs pcl.

**Comment by japzi** [comment]
After this change, I'm still getting,
[ 25%] Linking CXX executable /Users/ruwan/work/libs/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/convert_pointcloud_to_image
ld: framework not found GLEW
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/name/work/libs/ros_catkin_ws/devel_isolated/pcl_ros/lib/pcl_ros/convert_pcd_to_image] Error 1
make[1]: *** [CMakeFiles/convert_pcd_to_image.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

do you have any pointers for that? 
Thanks.

**Comment by ilidar** [comment]
it doesn't work on El Captain ;-(

**Comment by korymath** [comment]
@ilidar, thank you! I think that nasty hack sorted things out.

**Comment by ahundt** [comment]
this bug is still present...

```
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework
CMake Error at /usr/local/share/pcl-1.8/PCLConfig.cmake:49 (message):
  simulation is required but glew was not found
Call Stack (most recent call first):
  /usr/local/share/pcl-1.8/PCLConfig.cmake:648 (pcl_report_not_found)
  /usr/local/share/pcl-1.8/PCLConfig.cmake:811 (find_external_library)
  CMakeLists.txt:9 (find_package)
```

**Comment by ahundt** [comment]
Had to go through this again and here is what worked for me this time:

```
  IF (APPLE)
# These values for Apple could probably do with improvement.
    FIND_PATH( GLEW_INCLUDE_DIR GL/glew.h
      /usr/local/include
      /System/Library/Frameworks/GLEW.framework/Versions/A/Headers
      ${OPENGL_LIBRARY_DIR}
    )

    FIND_LIBRARY( GLEW_GLEW_LIBRARY GLEW
      /usr/local/lib
      /usr/openwin/lib
      /usr/X11R6/lib
    )

    if(NOT GLEW_GLEW_LIBRARY)
        SET(GLEW_GLEW_LIBRARY "-framework GLEW" CACHE STRING "GLEW library for OSX")
        SET(GLEW_cocoa_LIBRARY "-framework Cocoa" CACHE STRING "Cocoa framework for OSX")
    endif()
  ELSE (APPLE)
```

**Comment by SergioRAgostinho** [comment]
This should be good to be closed.
