### ISSUE TITLE
BOOST_VERSION not defined in image_ir.cpp

### ISSUE THREAD

**Issue by simbaforrest** [PointCloudLibrary/pcl#1312]
Hi All,

When I compile the head version (aab76e177c3051c3ae5d9d014f478abbb341f30d) of PCL, I encountered a compile error related to BOOST_VERSION not defined so when compiling the file [io/src/image_ir.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/image_ir.cpp)
it can not recognize boost::chrono related symbols.

If we add
```C++
#include <boost/version.hpp>
```
in *io/include/pcl/io/boost.h* before [line 69](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/boost.h#L69)
```C++
#if BOOST_VERSION >= 104700
```
The error can be resolved.

BTW, I'm using boost 1.49 downloaded from the PCL website, and I'm compiling the project using VS 2010 x64 under windows 7.

Best,
Chen

**Comment by taketwo** [comment]
Pull request is welcome!

**Comment by taketwo** [comment]
Actually, should be fixed by #1311.

**Comment by ByteChen** [comment]
u r so kind.
