### ISSUE TITLE
Compile error of example_lccp_segmentation.cpp

### ISSUE THREAD

**Issue by simbaforrest** [PointCloudLibrary/pcl#1314]
There is a compile error in [line 179 of file examples/segmentation/example_lccp_segmentation.cpp](https://github.com/PointCloudLibrary/pcl/blame/master/examples/segmentation/example_lccp_segmentation.cpp#L179). The "not" should be changed to "!".

**Comment by taketwo** [comment]
Could you submit a pull request?

**Comment by taketwo** [comment]
Fixed via #1315
