### ISSUE TITLE
Eclipse code formatting settings not working with CDT 8.7.0 on Mars

### ISSUE THREAD

**Issue by stefanbuettner** [PointCloudLibrary/pcl#1338]
Hi there,

I just wanted to import the code formatting template PCL_eclipse_profile.xml under doc/advanced/content/files into Eclipse Mars 4.5.0 (20150621-1200) using C/C++ Development Tools SDK 8.7.0.201506070905 but ran into several import errors. Some of which are:

- Problems reading profiles from XML Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
- Problems reading profiles from XML The element type "link" must be terminated by the matching end-tag "</link>".
- Problems reading profiles from XML The element type "meta" must be terminated by the matching end-tag "</meta>".

I tried to fix them manually but after all the import errors were resolved, no new profile showed up in the Active Profile drop-down list. Hope I didn't make an obvious mistake.

Best,
Stefan

**Comment by VictorLamoine** [comment]
I have just downloaded a release of Mars and tested this, it works fine on my side:

- Download [PCL_eclipse_profile.xml](https://raw.githubusercontent.com/PointCloudLibrary/pcl/master/doc/advanced/content/files/PCL_eclipse_profile.xml)
- Open Eclipse > Window > Preferences
- Search for "formatter" and click import, choose the XML file downloaded

Does it work for you this way?

**Comment by stefanbuettner** [comment]
Yep, as I expected. A stupid error on my side. Sorry to bother you...

Best,
Stefan
