### ISSUE TITLE
Compiling from source: Redirect to new tutorial

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1342]
It's been a while since a new tutorial on how to build PCL from source has been added to the automatically generated doc: https://github.com/PointCloudLibrary/pcl/pull/1107.

Maybe it's time to redirect http://www.pointclouds.org/downloads/source.html to http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php ?

**Comment by taketwo** [comment]
Shouldn't we rather put links for tutorials for different operating systems?

**Comment by VictorLamoine** [comment]
Yes this would be nice, a section like `Using prebuilt binaries` with images but redirecting to the platform specific tutorials:

- http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php
- http://www.pointclouds.org/documentation/tutorials/compiling_pcl_macosx.php
- http://www.pointclouds.org/documentation/tutorials/compiling_pcl_windows.php

**Comment by taketwo** [comment]
I updated the "Compiling from source" section on the ["Downloads"](http://www.pointclouds.org/downloads/) page. The old page http://www.pointclouds.org/downloads/source.html still exists, but there are no links leading to it.

**Comment by taketwo** [comment]
No, wrong. There is a link on top right of the "Downloads" page that leads to this old from source page. Should we get rid of it completely?

**Comment by VictorLamoine** [comment]
It should point to the new tutorial, it's easier to maintain 1 tutorial :+1: .

I'd recommend redirecting http://www.pointclouds.org/downloads/source.html to http://www.pointclouds.org/documentation/tutorials/ so that users don't get a `404 error` instead of deleting anything.

**Comment by taketwo** [comment]
I'd rather delete this link altogether. Anyway it does not fit in the "Linux", "Windows", "Mac OS" line. And also it's misleading if on the "Downloads" page you click "Source" link, and end up on tutorials list page...

**Comment by VictorLamoine** [comment]
I'm ok with that :+1:

**Comment by taketwo** [comment]
Done.
