### ISSUE TITLE
Modules included in releases

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1351]
It's not clear what is included/not included in PCL releases for most users; I think making a list of included modules (or the inverse) would make sense.

Maybe in a tutorial?

**Comment by taketwo** [comment]
AFAIR we don't include modules that are set to `OFF` by default.

**Comment by VictorLamoine** [comment]
This information is not clear enough for end-users; I've answered many posts of people asking "is XXX module included in the releases?" and I think their question is legitimate .

Where should we add it?

**Comment by taketwo** [comment]
Everything that is visible in the repository under the corresponding tag version (e.g. [1.7.2](https://github.com/PointCloudLibrary/pcl/tree/pcl-1.7.2)) was released. An alternative way is to consult the corresponding [documentation page](https://github.com/PointCloudLibrary/pcl/tree/pcl-1.7.2). I really don't think we need anything in addition.

Nevertheless, if you have something specific in mind about how and where we can make this additional note, please propose.

**Comment by SergioRAgostinho** [comment]
My two cents. 

The [modules documentation page](http://docs.pointclouds.org/trunk/modules.html) should always be the de facto reference, it should list all modules and the brief one liner description, and it if it is enabled or disabled by default. Currently that doesn't seem to be updated. 

Alternatively, one could also replicate that information in the repo readme.md, so that it is splattered in the "front page".

**Comment by taketwo** [comment]
Agree regarding modules documentation page.

Apparently, for the previous release(s) we excluded:
 * `2d`
 * `cuda` and `gpu`
 * `ml`
 * `simulation`
 * `stereo`

Should we exclude all again? Only some? Or just disable building by default?

**Comment by jspricke** [comment]
I would propose to keep the flags as they are in master.
Looking at what I did [last time](https://github.com/PointCloudLibrary/pcl/commits/pcl-1.7.0rc1), Only https://github.com/PointCloudLibrary/pcl/commit/b576d170003a6df33ceb24f9362dc6c38f0e2dd1 and https://github.com/PointCloudLibrary/pcl/commit/de3906b5146a04ddff0e537121e3ed5681a4ee19 seem to be relevant. For the first one I've just opend #1450. For the second one I'm not sure about a more permanent solution.

**Comment by SergioRAgostinho** [comment]
Kinfu is really popular on the mailing list so it would be good to try to include ```gpu``` on the release.

**Comment by taketwo** [comment]
> Kinfu is really popular on the mailing list so it would be good to try to include gpu on the release.

I am strongly against this. The Kinfu implementation that we have is obsolete and there are many newer maintained alternatives around. To name a few:

  * https://github.com/Nerei/kinfu_remake remake from the original author of KinFu
  * https://github.com/victorprad/InfiniTAM with large scale support
  * https://github.com/mp3guy/Kintinuous not there yet, but will soon be

I'd rather explicitly deprecate Kinfu, point the users to the alternatives, and remove it in future even from master.

> I would propose to keep the flags as they are in master.

This means: release 2d (on), ml (on), stereo (on), and simulation (off). Looking back at our [modules documentation page](http://docs.pointclouds.org/trunk/modules.html), I don't see any entries for these.

**Comment by SergioRAgostinho** [comment]
> I am strongly against this. The Kinfu implementation that we have is obsolete and there are many newer maintained alternatives around.
:+1:  strong arguments

**Comment by taketwo** [comment]
We are not excluding any modules from releases anymore.
