### ISSUE TITLE
Bug in esf.hpp , compute ESF , vector out of range

### ISSUE THREAD

**Issue by ctaggese** [PointCloudLibrary/pcl#1353]
Hi 

in features/impl/esf.hpp 

Line 110:   if (s \* (s-a) \* (s-b) \* (s-c) <= 0.001f)

if this condition becomes true, the vectors

d2v and d3v  has 59.997 and 19.999 elements and not 60.000 and 20.000

and so in Line 218:   for (size_t nn_idx = 0; nn_idx < sample_size; ++nn_idx)

there is an error if there is some access to the 59998 element. because it not exists

Also noticed in:

http://www.pcl-users.org/ESF-vector-subscript-out-of-range-td4033348.html
http://stackoverflow.com/questions/22914825/debug-error-vector-subscript-out-of-range-pcl

**Comment by taketwo** [comment]
Could you suggest a fix?

**Comment by ctaggese** [comment]
I will try it tomorrow.

2015-10-01 18:08 GMT+02:00 Sergey Alexandrov <notifications@github.com>:

**Comment by ctaggese** [comment]
Ok i fixed it:

Insert  " nn_idx--;  " in Line 112 so that it looks so:

if (s * (s-a) * (s-b) * (s-c) <= 0.001f){
      nn_idx--;
      continue;
    }

I have tested it with several pointclouds

**Comment by VictorLamoine** [comment]
The best would be that you contribute yourself. You can prepare a pull request so that we can review the changes and discuss/accept the changes.

You can find information here: [CONTRIBUTING.md](https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md#pull-requests).
Tell us if you need help!

**Comment by mvieth** [comment]
Seems like the suggested fix was added in pull request #1755
