### ISSUE TITLE
Error with return of transform

### ISSUE THREAD

**Issue by martijnvwezel** [PointCloudLibrary/pcl#1359]
Something is wrong with D:\GIT\pcl\doc\tutorials\content\sources\registration_api\example1.cpp

 161    Transformation (output, tgt, good_correspondences, transform);

It only gives NaN results back, so the second time it does ICP it breaks. Working on it to solve!

**Comment by jspricke** [comment]
This depends a lot on your input data. Closing as it's not a bug.
