### ISSUE TITLE
about the documents of VFH 

### ISSUE THREAD

**Issue by summer1216** [PointCloudLibrary/pcl#1362]
Hello, in the description part of VFH (Viewpoint Feature Histogram), 

there's 
How it works:

1.Calculate the centroid pc of the point cloud and its normal nc. Calculate the vector between the viewpoint and the centroid vc and normalize it.
2.The VFH consists of two components: A viewpoint component and an extended FPFH component.
3.To map the viewpoint component iterate over all points in P and calculate the angle between their normal and vc. Increment the corresponding histogram bin.
4.For the viewpoint component simply calculate the FPFH at the centroid pc setting the entire surrounding point cloud P as neighbours.
5.Add the two histograms together.

in the 4th sentence, at the beginning "For the viewpoint component".  Is it actually "FPFH component", is this a writing fault?

**Comment by jspricke** [comment]
I guess you are referring to https://github.com/PointCloudLibrary/pcl/wiki/Overview-and-Comparison-of-Features. @Freddixx, can you comment?

**Comment by Freddixx** [comment]
Hey, yep, you're right. That's supposed to be the FPFH component. I edited the article.
