### ISSUE TITLE
Question: Extracting the visible mesh surface?

### ISSUE THREAD

**Issue by Randa-Almadhoun** [PointCloudLibrary/pcl#1376]
Hi, 
I'm trying to get the intersection surface between RGBD camera FOV and mesh model.. this intersection surface is the visible mesh surface from the RGBD camera point of view. I tried to use PCL::RangeImage since it simulates the sensor FOV, position and orientation and performs z buffering to extract the visible surface but I get the point cloud part that is inside the FOV frustum regardless of its visibility to the camera as it is shown in the following image link :
![capture](https://cloud.githubusercontent.com/assets/7913167/10442796/14e1258e-7167-11e5-84d9-b7fd6a53cb76.JPG)

Here is the github link of the code ( I preformed frustum culling then range image and I also used the loaded mesh points directly but I get the same result ): 
https://github.com/kuri-kustar/aircraft_inspection/blob/master/component_test/src/frustum_test.cpp

does pcl::RangeImage suppose to do that although it is applying z buffer? does PCL include another function that extract the visible surface or implement z-buffer like pcl::RangeImage ?

**Comment by jspricke** [comment]
This is a bug tracker, please use our mailing list on http://www.pcl-users.org to ask questions.
