### ISSUE TITLE
Sample consensus warnings

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1403]
There is a huge amount of warnings when compiling PCL trunk. I think it comes from #1396

```bash
/home/victor/libraries/pcl/src/sample_consensus/include/pcl/sample_consensus/model_types.h:101:67: warning: ‘sample_size_pairs’ is deprecated (declared at /home/victor/libraries/pcl/src/sample_consensus/include/pcl/sample_consensus/model_types.h:76): This array is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
                                                                   ^

```

**Comment by taketwo** [comment]
Can you point me to a the relevant Travis log? What I see now (e.g. [here](https://travis-ci.org/PointCloudLibrary/pcl/jobs/87789530)) is lots of warnings coming from VTK.

**Comment by VictorLamoine** [comment]
I don't have a Travis build showing this, it's only on my PC for now.!

**Comment by SergioRAgostinho** [comment]
I'm also experiencing this.

**Comment by SergioRAgostinho** [comment]
Here's a [log](https://travis-ci.org/PointCloudLibrary/pcl/jobs/89558014) with the described behaviour.

The current trunk is no longer generating these.
