### ISSUE TITLE
CMake config generates invalid compiler flag when the (optional) dependency libusb-1.0 can not be found

### ISSUE THREAD

**Issue by harendt** [PointCloudLibrary/pcl#1406]
When I'm compiling code that depends on PCL without the (optional) dependency libusb-1.0, I get a huge number of the following warnings:

> \<command-line\>:0:15: warning: ISO C99 requires whitespace after the macro name [enabled by default]

The warning comes from the token ```-DDISABLE_LIBUSB-1.0``` that is added to the compiler flags by PCL. The minus sign and the dot in ```DISABLE_LIBUSB-1.0``` are not allowed for macro names.

I found the place where this invalid macro definition comes from ([PCLConfig.cmake.in, line 618](https://github.com/PointCloudLibrary/pcl/blob/83c02003a2316f8e08fecc14030a2aab0cb7f6d4/PCLConfig.cmake.in#L618)):

> add_definitions("-DDISABLE_${LIB}")

When ```${LIB}``` is ```LIBUSB-1.0```, it should be changed to ```LIBUSB_1_0``` or something similar.

**Comment by SergioRAgostinho** [comment]
Can you provide more information on your setup? I just tried disabling libusb and building and no warnings were generated.

**Comment by harendt** [comment]
I'm working on Ubuntu 14.04. And libusb is not installed. I compiled PCL (version 1.7.2) on my own. The error occurs, when I try to compile code, that depends on PCL (pcl-common and pcl-io, I guess). I'm using CMake as build system. And CMake's function ```find_package()``` uses the file PCLConfig.cmake that is installed by PCL.

On line [618](https://github.com/PointCloudLibrary/pcl/blob/83c02003a2316f8e08fecc14030a2aab0cb7f6d4/PCLConfig.cmake.in#L618) this CMake file adds the compiler flag ```-DDISABLE_LIBUSB-1.0```, if libusb is not found:
> add_definitions("-DDISABLE_${LIB}")

The problem is that -- as the warning indicates -- the characters ```-``` and ```.``` are not allowed in macro definitions. Hence these characters should be replaced (e.g. replaced by ```_```).

I could add a patch to ```PCLConfig.cmake```, that replaces these invalid characters, but I don't know, if this would affect anything else.

**Comment by taketwo** [comment]
I don't see any usage of such `DISABLE` variables anywhere besides `pcl_config.h.in`, where OpenNI and QHull support is tested. I think it's very safe to fix the invalid characters in `-DDISABLE_LIBUSB-1.0`. I'd even say it's okay to remove it completely, but we don't need to go that far :)
