### ISSUE TITLE
Error occurs while compiling!

### ISSUE THREAD

**Issue by gsamful** [PointCloudLibrary/pcl#1412]
I have received an error "‘FLT_MAX’ was not declared in this scope, float max_dist = -FLT_MAX" when i try to compile the library recently. As you can see, it was  all right several moths ago!  I have no idea what's wrong with it. Please help me out of this problem and i use archlinux!Thanks a lot!

**Comment by SergioRAgostinho** [comment]
Not discarding the possibility of this being a bug, this is not the place to ask support question. Use the [mailing list](http://www.pcl-users.org/) for that. Don't forget to subscribe to the mailing list before posting, otherwise your email won't be visible to the majority of the users.

**Comment by taketwo** [comment]
Find out which file produces errors and add `#include <cfloat>` on top.
