### ISSUE TITLE
Compiling for OSX with gcc

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1414]
Hey, 

I had some issue compiling pcl for OS X using gcc and started a discussion on the user mailing list [here](http://www.pcl-users.org/Issues-compiling-PCL-trunk-OS-X-gcc-5-2-td4039819.html). Eventually I traced down the problem to [pcl_targets.cmake](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake), more specifically lines:
* [206-209](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L206-L209)
* [254-257](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L254-L257)
* [296-299](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L296-L299)
* [342-345](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L342-L345)
* [389-392](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L389-L392)
* [428-430](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_targets.cmake#L428-L430)

Basically that was generating a command like the one below, with a stray -Wl flag.
````
/usr/local/bin/g++-5  -Wall -Wextra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion  -msse4.2 -mfpmath=sse -Wabi -pthread -fopenmp  -g -dynamiclib -Wl,-headerpad_max_install_names -Wl   -compatibility_version 1.8.0 -current_version 1.8.0 -o ../lib/libpcl_common.1.8.0.dylib -install_name @rpath/libpcl_common.1.8.dylib CMakeFiles/pcl_common.dir/src/point_types.cpp.o CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o CMakeFiles/pcl_common.dir/src/io.cpp.o CMakeFiles/pcl_common.dir/src/common.cpp.o CMakeFiles/pcl_common.dir/src/correspondence.cpp.o CMakeFiles/pcl_common.dir/src/distances.cpp.o CMakeFiles/pcl_common.dir/src/parse.cpp.o CMakeFiles/pcl_common.dir/src/poses_from_matches.cpp.o CMakeFiles/pcl_common.dir/src/print.cpp.o CMakeFiles/pcl_common.dir/src/projection_matrix.cpp.o CMakeFiles/pcl_common.dir/src/time_trigger.cpp.o CMakeFiles/pcl_common.dir/src/gaussian.cpp.o CMakeFiles/pcl_common.dir/src/colors.cpp.o CMakeFiles/pcl_common.dir/src/feature_histogram.cpp.o CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.o CMakeFiles/pcl_common.dir/src/range_image.cpp.o CMakeFiles/pcl_common.dir/src/range_image_planar.cpp.o CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o CMakeFiles/pcl_common.dir/src/fft/kiss_fftr.c.o /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib -lm  
g++-5: error: unrecognized command line option '-Wl'

make[2]: *** [lib/libpcl_common.1.8.0.dylib] Error 1

make[1]: *** [common/CMakeFiles/pcl_common.dir/all] Error 2

make: *** [all] Error 2
```

I'm not sure if the intended behaviour was for the linker options to be somehow appended after the -Wl, but was not happening with my setup. 

I want to submit a pull request deleting those lines but just wanted to confirm if I might be overlooking something. 

Cheers

**Comment by taketwo** [comment]
No idea about why this flag is appended. Looking at 8b03e7a04 it seems that the problem did show up already long ago. At that time guards for _clang_ were added. Since we need the same for _gcc_, I guess it's time to remove these flags completely. Or are there any other compilers in use on Mac?

**Comment by taketwo** [comment]
And another relevant commit: 89072ed814fd

**Comment by SergioRAgostinho** [comment]
Thanks for the digging.

> Or are there any other compilers in use on Mac?

Apparently there's an Intel C++ compiler also for OS X. Nevertheless, [this post](http://www.pcl-users.org/Linker-error-trying-to-compile-PCL-on-MacOSX-10-6-td2919632.html) suggests that the reason behind 89072ed814fdf3a7fdf698e5d360dcd034370c87 was complains generated by some Mac users due to -Wl,--as-needed.

So, even if some old OS X ld did not support the -Wl,--as-needed option, the isolated -Wl as it is now, doesn't do anything (other than generating linker errors). AFAIK the syntax is always ```-Wl,<option>```.

**Comment by taketwo** [comment]
So I think we should either return `--as-needed`, or remove `-Wl`.

**Comment by SergioRAgostinho** [comment]
llvm-ld does not support --as-needed. That's something from gnu ld. I just made a test to confirm passing ```-Wl,--as-needed``` and it failed pretty quickly.

Removal is the only option.

**Comment by taketwo** [comment]
:+1:
