### ISSUE TITLE
PCL GPU Octree demo. thrust::system::system_error at memory location

### ISSUE THREAD

**Issue by Hagen23** [PointCloudLibrary/pcl#1418]
I was testing the octree gpu example found at https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/octree/src/octree_search.cpp
and I got the following error message when running the program:

Unhandled exception at 0x7689C41F in PCL_TEST_GPU.exe: Microsoft C++ exception: thrust::system::system_error at memory location 0x0023EA8C.

The code stops at the following line:

octree_device.build();

I am testing the code on a Windows 7 laptop, with Visual studio 2013. I built PCL with CUDA 7.0, VTK 6.2, and Boost 1.58. My GPU is a Nvidia GeForce GT 630M (Compute capability 2.1, Fermi)

I found some references in the users mailing list that have not been adressed:
http://www.pcl-users.org/Error-while-testing-pcl-gpu-Octree-td4031246.html
http://www.pcl-users.org/Is-it-absolutely-essential-to-have-a-fermi-card-td3720635.html
http://www.pcl-users.org/thrust-system-error-gpu-octree-td4031649.html
http://www.pcl-users.org/PCL-Thrust-help-td4038778.html

**Comment by ChemicCn** [comment]
Hello,
has a solution or workaround been found for this issue?

**Comment by larshg** [comment]
Closing as no response since I mentioned this issue. Probably solved by #4197.
