### ISSUE TITLE
Custom SampleConsensusModel subclass difficult because of enum SacModel

### ISSUE THREAD

**Issue by maccesch** [PointCloudLibrary/pcl#1420]
Mirrorring all subclasses of ```SampleConsensusModel``` in an enum is bad OO design practice. As far as I found out it is only used to determine the required sample size which is a method in ```SampleConsensusModel```.

Wouldn't it be a lot better if every class overwrote that method? That way it would be easily possible to create custom subclasses.

If you agree I would be willing to create a pull request for this.

**Comment by taketwo** [comment]
See #1396

**Comment by maccesch** [comment]
Nice! Thanks
