### ISSUE TITLE
PCL.IterativeClosestPoint_PointToPlane test not stable

### ISSUE THREAD

**Issue by fran6co** [PointCloudLibrary/pcl#1422]
The test fails randomly in Travis, https://travis-ci.org/PointCloudLibrary/pcl/jobs/90801423#L3909 https://travis-ci.org/PointCloudLibrary/pcl/jobs/89065382#L4276

**Comment by SergioRAgostinho** [comment]
Also affecting #1415 
https://travis-ci.org/PointCloudLibrary/pcl/jobs/90771960#L3919

**Comment by mvieth** [comment]
This test does not fail randomly any more
