### ISSUE TITLE
Fail to build apps on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by bu2** [PointCloudLibrary/pcl#1441]
Dear PCL team,

Is it possible to build PCL apps on OS X 10.11 (El Capitan)

Here is an extract of the cmake output:
```
...
-- The following subsystems will not be built:
-- apps: No reason
...
```

Please find the full CMake output attached to this message.
[cmake.txt](https://github.com/PointCloudLibrary/pcl/files/40818/cmake.txt)

I installed required dependencies with Homebrew (under my home folder !).

And I am especially interested in the app in_hand_scanner.

Regards.

**Comment by SergioRAgostinho** [comment]
Can you post your CMakeCache.txt? Did you manually enabled them on CMake? You can do it like this.
````
cmake <something> -DBUILD_apps=ON
```

**Comment by bu2** [comment]
Hi,

I just discovered those BUILD_xxx flags and now I am able to build the app I am interested in (in_hand_scanner) with the following command:
```
$ cmake -DPCL_QT_VERSION=4 -DBUILD_apps=ON -DBUILD_apps_in_hand_scanner=ON -DOPENNI2_INCLUDE_DIRS=/Users/bu2/.brew/include/ni2/ -DOPENNI2_LIBRARY=/Users/bu2/.brew/lib/ni2/libOpenNI2.dylib ..
```

Here is an extract of cmake output:

```
...
-- The following subsystems will be built:
...
--   apps
       building: 
       |_ in_hand_scanner
       not building: 
       |_ 3d_rec_framework: No reason
       |_ cloud_composer: No reason
       |_ modeler: No reason
       |_ optronic_viewer: FZAPI was not found.
       |_ point_cloud_editor: No reason
...
```

So we can close the issue.

Thank you.
