### ISSUE TITLE
is_dense not properly set when loading PLY files

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1455]
`is_dense` is wrongly set to false when loading a PLY cloud (reported [here](https://github.com/PointCloudLibrary/pcl/issues/1381#issuecomment-160484645) and [here](https://github.com/SergioRAgostinho/pcl/commit/1df66e98bd45a63b625b3b4601a072c33f04d4f8#diff-d26f5b6c66bf2ad9e198530d7a280a0eR940)).
This line is responsible: [io/src/ply_io.cpp#L62](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ply_io.cpp#L62)

Is must be set to true, and when adding vertex the variable should be set to false if one of the components is not finite.

Test code:
https://github.com/PointCloudLibrary/pcl/issues/1433

It should be tested within PCL:
https://github.com/PointCloudLibrary/pcl/issues/1381#issuecomment-160484645

**Comment by SergioRAgostinho** [comment]
:+1: When you submit the PR for this can you please uncomment the lines in the color [test](https://github.com/SergioRAgostinho/pcl/commit/1df66e98bd45a63b625b3b4601a072c33f04d4f8#diff-d26f5b6c66bf2ad9e198530d7a280a0eR940)?

**Comment by VictorLamoine** [comment]
Ok but I'm not sure how should I check if the values are finite or not, I see 2 options:
- Just before returning the ply loading function, loop through the cloud and search for non-finite values. Dumb & slow but easy to implement.
- When parsing the values, if one is non-finite, change `is_dense` to true.

The scalar values are parsed [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/ply/ply_parser.h#L553-L604) but I don't see an easy way to modify the `is_dense` property from here, it requires modifying the function signature.

**Comment by jspricke** [comment]
Can't we check it in the global loop? I guess it's this one: https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ply_io.cpp#L603

**Comment by VictorLamoine** [comment]
We only go into this loop if the PLY file has the range_grid field.
From what I understand it would be here:
https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ply/ply_parser.cpp#L251-L297

**Comment by SergioRAgostinho** [comment]
@VictorLamoine Notice that at some point, the value inferred in [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/ply/ply_parser.h#L553-L604) needs to be stored on the pointcloud/blob. That happens further ahead, probably in whatever get's called in [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/ply/ply_parser.h#L601). 
Look at ```scalarPropertyDefinitionCallback``` and "friends" in ```ply_io.cpp```. Eventually you'll find the callback which store the value on the cloud/blob. Sorry for not being precise, but I'm not on my development pc at the moment.

**Comment by SergioRAgostinho** [comment]
I have the impression it takes place [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ply_io.cpp#L268). 

Now the question for me is, under which conditions do you set ```is_dense``` to false? I know it happens when one of the coordinates from a point is set to ```NaN```. Is this also valid for any other (float) scalar one might need to parse, e.g. a normal, an intensity? What happens if your scalar value is ```Inf```?

**Comment by VictorLamoine** [comment]
Yes it's exactly here, using `pcl_isfinite` works fine, I've just compiled PCL with that and it works;

```cpp
    if (!pcl_isfinite (value))
      cloud_->is_dense = false;
```

I was about to ask the same question, the documentation is not very clear about this:
http://docs.pointclouds.org/trunk/classpcl_1_1_point_cloud.html#a3ca88d8ebf6f4f35acbc31cdfb38aa94

If the color is invalid, should we set the point cloud to non dense? Etc.
