### ISSUE TITLE
PLYReader fails to parse .ply file normals generated by meshlab

### ISSUE THREAD

**Issue by ahundt** [PointCloudLibrary/pcl#1466]
I tried using the PLYReader to load in a .ply file generated by [meshlab](http://meshlab.sourceforge.net/) which you can download at [cereal_box_ply.zip](https://github.com/PointCloudLibrary/pcl/files/56218/cereal_box_ply.zip), but pcl fails to read the file normals and I believe this to be a bug in PCL, or if it is by design this should be added as a supported use case.

Here is what it looks like:

![cereal_box](https://cloud.githubusercontent.com/assets/55744/11616853/c00a06f8-9c53-11e5-9462-9e6b11ca82ba.png)

Here is the start of the ply file:
```
ply
format ascii 1.0
comment VCGLIB generated
comment TextureFile tex_0.jpg
comment TextureFile tex_1.jpg
element vertex 54994
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 109969
property list uchar int vertex_indices
property list uchar float texcoord
property int texnumber
end_header
-0.00975001 0.0446061 0.100448 3.93319 4.87961 0.225451 255 255 255 255 
-0.0108772 0.0455421 0.0995715 3.8933 4.88062 0.574719 255 255 255 255 
-0.0109632 0.0455708 0.101327 3.81002 4.9581 -0.416174 255 255 255 255 
-0.0321507 0.0600317 0.104951 3.68022 4.96696 -1.1212 255 255 255 255 
```
The file continues from here, with a set of points, normals, and colors.

Here is the debug output:
```

[1;33m[pcl::PLYReader] /Users/athundt/Google Drive/Robone/surface matching/models/4829212_Cereal box and coffee cup/cereal_box/4829212_Cereal_box_and_coffee_cup-2015-12-05/cereal_box_ascii_accurate_scale_colorized.ply:15: property 'list uint8 int32 vertex_indices' of element 'face' is not handled
[0;m[1;33m[pcl::PLYReader] /Users/athundt/Google Drive/Robone/surface matching/models/4829212_Cereal box and coffee cup/cereal_box/4829212_Cereal_box_and_coffee_cup-2015-12-05/cereal_box_ascii_accurate_scale_colorized.ply:16: property 'list uint8 float32 texcoord' of element 'face' is not handled
[0;m[1;33m[pcl::PLYReader] /Users/athundt/Google Drive/Robone/surface matching/models/4829212_Cereal box and coffee cup/cereal_box/4829212_Cereal_box_and_coffee_cup-2015-12-05/cereal_box_ascii_accurate_scale_colorized.ply:17: property 'int32 texnumber' of element 'face' is not handled
[0;m[1;33mFailed to find match for field 'normal_x'.
[0;m[1;33mFailed to find match for field 'normal_y'.
[0;m[1;33mFailed to find match for field 'normal_z'.
[0;m[1;33mFailed to find match for field 'curvature'.
```

I believe simply supporting nx,ny,nz in addition to normal_x,normal_y,normal_z would solve the problem.

Thanks, help with solving the problem is very much appreciated.

**Comment by ahundt** [comment]
Was able to solve the problem and it was a bit silly, the path wasn't loaded correctly so it was opening a directory as a file and looking at junk from who knows where.

**Comment by ahundt** [comment]
Reopened this issue and tied it to the real problem of loading normals as exported by meshlab.

**Comment by ahundt** [comment]
I'm also aware that simply opening the file and renaming n* to normal_* will work, nonetheless n* is a use case that should be supported natively without manual editing.

**Comment by SergioRAgostinho** [comment]
Tried to reproduce your problem but for me the normals of the file you uploaded, are being loaded correctly. Have you tested this with HEAD or the latest release candidate?

**Comment by ahundt** [comment]
looks like there is a fixed in master:
https://github.com/PointCloudLibrary/pcl/blob/4b8071e30cd64338cca8329cf78af78e8d7e8d11/io/src/ply_io.cpp#L630
