### ISSUE TITLE
kinfu_largeScal_release run error,Error:invalid device function ../tsdf_volume.cu:164

### ISSUE THREAD

**Issue by jiaxing-li** [PointCloudLibrary/pcl#1468]
In detail, this is what I used to compile pcl_gpu_containers and pcl_gpu_kinfu:
GPU: GeForce GT 705
Microsoft Visual Studio 2013
CUDA 7.5
Boost 1.56
Eigen 3.0.5
FLANN 1.7.1
VTK 6.3.0

i'm try change CUDA_ARCH_PTX to 2.0 and 3.0. But the error is still there.

can anyone help me? thanks!

**Comment by soulslicer** [comment]
Did you manage to fix this?

**Comment by yuanxy92** [comment]
Hello, kinfu works OK when my gpu is gtx970. However, after I replace it with gtx1080, kinfu can not work any more. The error is also Error:invalid device function ../tsdf_volume.cu:164

I try vs2013/vs2015 cuda7.5/cuda8.0, none of them works.

**Comment by soulslicer** [comment]
Yes, the PCL CUDA functionality doesn't seem to work with the new 10xx cards

**Comment by SergioRAgostinho** [comment]
Closing this since it's duplicate #1712, now has more relevant information.
