### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1477]
Just want to merge all information on the current unstable tests
- [ ] a_recognition_cg_test [PCL.Hough3DGrouping](https://github.com/PointCloudLibrary/pcl/blob/master/test/test_recognition_cg.cpp#L105-L139)
- [x] filters_filters [ExtractIndices.Filters](https://github.com/PointCloudLibrary/pcl/blob/master/test/filters/test_filters.cpp#L109-L277) [#1537]
- [x] a_transforms_test [PCL.Matrix4Affine3Transform](https://github.com/PointCloudLibrary/pcl/blob/master/test/test_transforms.cpp#L270-L359) [#1511]
- ~~[ ] a_registration_test [PCL.IterativeClosestPoint_PointToPlane](https://github.com/PointCloudLibrary/pcl/blob/master/test/registration/test_registration.cpp#L395-L481) [#1422]~~

**Comment by taketwo** [comment]
Recognition CG test should succeed now, however I'm not convinced that #1538 was a proper fix.

**Comment by kunaltyagi** [comment]
Closing because the tests haven't failed for a long time. If some underlying issue is still causing bugs, please reopen with more details
