### ISSUE TITLE
Question: Intel Real Sense, 1.8 and automating capture of pointclouds for animation..

### ISSUE THREAD

**Issue by robeastham** [PointCloudLibrary/pcl#1486]
I've managed to compile and install the full version of 1.7.2 on Windows 10 64bit (32bit build) and can grab individual pointclouds by pressing 'S' manually when using the realsense_viewer.exe from https://github.com/taketwo/rs. I've also managed to partially build 1.8 (64bit build), but I'm getting some build errors, the included 1.8 realsense_viewer.exe did build and is working though. Perhaps it might be best if I stick with 1.7.2 until 1.8 is released officially, not sure if there is any major difference when it comes to Real Sense support in 1.8 and the separate lib for 1.7.2.

Anyway it would be great if someone could point me to some information on how I can automate grabbing of frames so that I can capture pointclouds live as they stream in, this is so I can later reconstruct multiple frames as a pointcloud animation? Obviously I don't want to do this manually by pressing the 'S' button really really fast :-)

I'm guessing I'll have to dive in to writing my own program for this, but I'm not a C++ programmer and so am a bit lost as to where to start. One thing I do know is that I'll probably need to use binary compressed format and an SSD to keep a decent capture framerate?

Also does anyone know if I can connect more than one Real Sense camera to a single PC when using PCL on Windows 10 with the current official Intel Real Sense SDK? I'd like to capture from multiple different angles and then use registration to make each frame whole before stringing the fully reconstructed individual frames in to an animated point cloud. This would then be further processed for animations I intend to put in to a VR app.

If multi-cam on one PC is not supported on Windows via PCL, then maybe I could do all this on ARM based boards on Linux or maybe an Atom Cherry Trail boards running Windows, one machine for each camera, but from what I've read support is not quite there yet on Linux and only partial on Atom Cherry Trail. I'm using F200  cameras and I guess I just need depth data and perhaps color if possible to. Is there a way to do this with PCL? Anyone got any boards that they'd recommend for Real Sense and PCL - Jeston, oDroid XU4, Minnowboards or Asus Vivo Stick perhaps...?

Any advice anyone can give would be most welcome.

**Comment by digitologist** [comment]
A new set of cross-platform RealSense camera libraries, Librealsense, was released as open source last month, you should take a look.  Supports multiple cameras and a streamlined interface for depth capture (at the expense of not supporting the advanced computer vision capabilities like face and hand tracking).

https://github.com/IntelRealSense/librealsense

**Comment by taketwo** [comment]
PCL grabber is a thin wrapper around the facilities provided by the RealSense SDK. Since the SDK itself support multi-camera setups, there should be no problem creating several PCL grabbers. However, I should admit I have never tested this functionality.

Please note that this is a bug tracker, not a support forum. Please forward your questions to the PCL users mailing lists.
