### ISSUE TITLE
Error C2436 in vlp_grapper.cpp

### ISSUE THREAD

**Issue by darkpavian** [PointCloudLibrary/pcl#1489]
Hello everyone, 

unfortunately I am no longer able to build PCL from master branch. 
I am trying to build the current version of PCL with VS 2013 x64 against VTK 7.1 and always receive the "Error C2436: '{ctor}': Member function or nested class in constructor initializer list" in the file vlp_grabber.cpp on lines 49 and 57. 

Any idea?

Thanks,
Florian

**Comment by UnaNancyOwen** [comment]
I fixed this issue in #1492.
