### ISSUE TITLE
R200 Grabber

### ISSUE THREAD

**Issue by giacomodabisias** [PointCloudLibrary/pcl#1490]
Hi,
I am creating an interface for the intel realsense R200 camera. The library for the camera is a proprietary lib of intel released as a .so . I wanted to create a grabber for pcl, but I don't know if I can add it to pcl. Is it ok from the pcl point of view? then I will check intel.

**Comment by taketwo** [comment]
I assume you are talking about Linux driver/grabber. We definitely won't add an `.so` file to the PCL repository. But I think it is fine to write a grabber that uses such an `.so`. In fact, it's the case for many other grabbers. For example, to use `DepthSenseGrabber` you need to install proprietary `DepthSenseSDK`, which is basically an `.so` file and headers.

One other concern here is to make the Linux grabber use the same interface as the already existing Windows grabber.

**Comment by giacomodabisias** [comment]
OK thanks.
I will start creating it and then check on that issue. I hope the two interfaces are the same, else if they are not too different I will just add some flags for the precompiler to use the different APIs.
