### ISSUE TITLE
Compilation failure with boost 1.60

### ISSUE THREAD

**Issue by opoplawski** [PointCloudLibrary/pcl#1506]
We're getting the following with boost 1.60 on Fedora Rawhide:

```
[ 63%] Generating include/pcl/apps/moc_openni_passthrough.cxx
cd /builddir/build/BUILD/pcl-0ddf11a6ad1175b6f1c253da003de20c1295cde0/build/apps/include/pcl/apps && /usr/lib/qt4/bin/moc-qt4 @/builddir/build/BUILD/pcl-0ddf11a6ad1175b6f1c253da003de20c1295cde0/build/apps/include/pcl/apps/moc_openni_passthrough.cxx_parameters
usr/include/boost/type_traits/detail/has_prefix_operator.hp:46: Parse error at "BOOST_JOIN"
```

**Comment by jpgr87** [comment]
It looks like some arch people had some success by [blocking out problematic boost includes](https://aur.archlinux.org/packages/pcl/) with #ifndef Q_MOC_RUN.

**Comment by jspricke** [comment]
We have a ton of them already, more patches very welcome ;)

**Comment by mvieth** [comment]
Since this issue is quite old and boost 1.60 is more or less not used any more, I am going to assume that this is no longer a problem. If you or someone else still has this problem, please comment/reopen this issue/open a new issue.
