### ISSUE TITLE
Euclidean_cluster_comparator ignores normals

### ISSUE THREAD

**Issue by NikolasE** [PointCloudLibrary/pcl#1514]
https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/euclidean_cluster_comparator.h

This comparator claims to cluster points which are close together and have a similar normal vector. It allows to set the angularThreshold and a normalCloud but ignores both of them in the compare-Function. So I suggest to either implement the normal-check or to remove the setter functions for the angular-Thresholds (or put a "not Implemented!") warning inside so that no user wonders why the values have no influence on the clustering.

**Comment by taketwo** [comment]
Great find! Of course, it's best to have this check implemented. But in the meanwhile some runtime warning with `PCL_WARN` and a note in the docstring can be of a good help for the users. A pull request is certainly welcome.

**Comment by SergioRAgostinho** [comment]
I'm looking at this now.
