### ISSUE TITLE
pcl::MovingLeastSquares<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal> doesn't work

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1518]
It seems that declaring the MovingLeastSquares filter as such results in a linker error:

Other decleration types such as:
pcl::MovingLeastSquares pcl::PointXYZRGB, pcl::PointXYZRGBNormal

work fine

**Comment by SergioRAgostinho** [comment]
Can you post a reduced test case for us to be able replicate it?
