### ISSUE TITLE
Cant make cmake configuration 

### ISSUE THREAD

**Issue by nitinmaru** [PointCloudLibrary/pcl#1520]
hi 
i AM facing problem to configure using cmake 
Here is my Pc configuration

WIn 7 , cmake 2.8.4 ,VS2010 

Error during cmake configure 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Check for working C compiler using: Visual Studio 10
Check for working C compiler using: Visual Studio 10 -- broken
CMake Error at C:/Program Files/CMake 2.8/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:52 (MESSAGE):
  The C compiler "cl" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/Admin/Desktop/pcl2/pcl-master/pcl-master/build/CMakeFiles/CMakeTmp

  

  Run Build Command:C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
  cmTryCompileExec.vcxproj /p:Configuration=Debug

  Microsoft (R) Build Engine version 4.0.30319.17929

  [Microsoft .NET Framework, version 4.0.30319.17929]

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  Build started 04-Feb-16 4:41:58 PM.

  Project
  "C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj"
  on node 1 (default targets).

  InitializeBuildStatus:

    Creating "cmTryCompileExec.dir\Debug\cmTryCompileExec.unsuccessfulbuild" because "AlwaysCreate" was specified.

  ClCompile:

    C:\Program Files\Microsoft Visual Studio 10.0\VC\bin\CL.exe /c /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTryCompileExec.dir\Debug\\" /Fd"C:/Users/Admin/Desktop/pcl2/pcl-master/pcl-master/build/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec.pdb" /Gd /TC /analyze- /errorReport:queue testCCompiler.c  /Zm1000 /GZ 

  cl : Command line warning D9035: option 'GZ' has been deprecated and will
  be removed in a future release
  [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]

  cl : Command line warning D9036: use 'RTC1' instead of 'GZ'
  [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]

    testCCompiler.c

  ManifestResourceCompile:

    C:\Program Files\Microsoft SDKs\Windows\v7.0A\bin\rc.exe /nologo /fo"cmTryCompileExec.dir\Debug\cmTryCompileExec.exe.embed.manifest.res" cmTryCompileExec.dir\Debug\cmTryCompileExec_manifest.rc 

  Link:

    C:\Program Files\Microsoft Visual Studio 10.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\Debug\cmTryCompileExec.exe" /VERSION:"0.0" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /ManifestFile:"cmTryCompileExec.dir\Debug\cmTryCompileExec.exe.intermediate.manifest" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /PDB:"C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\Debug\cmTryCompileExec.pdb" /SUBSYSTEM:CONSOLE /STACK:"10000000" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Admin/Desktop/pcl2/pcl-master/pcl-master/build/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec.lib" /MACHINE:X86 cmTryCompileExec.dir\Debug\cmTryCompileExec.exe.embed.manifest.res
    cmTryCompileExec.dir\Debug\testCCompiler.obj  /machine:X86 /debug 

  LINK : fatal error LNK1123: failure during conversion to COFF: file invalid
  or corrupt
  [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]

  Done Building Project
  "C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj"
  (default targets) -- FAILED.

  

  Build FAILED.

  

  
  "C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj"
  (default target) (1) ->

  (ClCompile target) -> 

    cl : Command line warning D9035: option 'GZ' has been deprecated and will be removed in a future release [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]
    cl : Command line warning D9036: use 'RTC1' instead of 'GZ' [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]

  

  

  
  "C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj"
  (default target) (1) ->

  (Link target) -> 

    LINK : fatal error LNK1123: failure during conversion to COFF: file invalid or corrupt [C:\Users\Admin\Desktop\pcl2\pcl-master\pcl-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec.vcxproj]

  

      2 Warning(s)
      1 Error(s)

  

  Time Elapsed 00:00:00.47

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)

++++++++++++++++++++++++++++++++++++++++++++++

Kindly provide Feedback
Thank you

**Comment by SergioRAgostinho** [comment]
Please use the mailing list for questions. This doesn't seem like a PCL bug, especially because it's failing on the first steps 
```
Check for working C compiler using: Visual Studio 10 -- broken
```
