### ISSUE TITLE
about switching method of optimized code or non-optimized code

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#1521]
The optimized code or non-optimized code has switching code by the preprocessor macros ( "\__SSE\__" and "\__SSE2\__" ).
(For example,　[pcl/common/include/pcl/sse.h](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/sse.h#L41))

However, These preprocessor macros ( "\__SSE\__" and "\__SSE2\__" ) is not defined in Visual C++.
(But, The intrinsic instructions of SSE and SSE2 can be use in Visual C++.)
Therefore, These preprocessor macros should not be used to switching code that has been optimized.

```cpp
#if defined(__SSE2__)
    /* optimized code */
#elif
    /* non-optimized code */
    /* VC++ always not optimizing because always not defined "__SSE2__" in VC++. */
#endif
```

I think, this case should be used the "**HAVE_SSE_EXTENSIONS**" and "**HAVE_SSE2_EXTENSIONS**" that defined in [pcl_find_sse.cmake](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_find_sse.cmake).
These macros ( "HAVE_SSE_EXTENSIONS" and "HAVE_SSE2_EXTENSIONS" ) are confirmed to be able to run by CMake (check_cxx_source_runs()), and defined in [pcl_config.h](https://github.com/PointCloudLibrary/pcl/blob/master/pcl_config.h.in#L38-L39).

```cpp
#if defined(HAVE_SSE2_EXTENSIONS)
    /* optimized code */
#elif
    /* non-optimized code */
#endif
```

What do you think?
Thanks.

**Comment by SergioRAgostinho** [comment]
:+1:

**Comment by taketwo** [comment]
I think we should use **HAVE_*** macros indeed :+1:

**Comment by UnaNancyOwen** [comment]
Thanks.
I will send a pull request after.

**Comment by jspricke** [comment]
That sounds VC specific. I would add something like this:
```
#ifdef _MSC_VER
#if (defined(_M_AMD64) || defined(_M_X64) || _M_IX86_FP == 2)
#define __SSE__
#define __SSE2__
#elif _M_IX86_FP == 1
#define __SSE__
#endif
#endif
```
(Based on http://stackoverflow.com/a/18570487)

**Comment by taketwo** [comment]
Right. So the **HAVE_*** macros indicate if SSE is supported in principle. But it does not say anything about whether the code is actually being compiled with SSE enabled. (Because the user can disable it with `PCL_ENABLE_SSE` option.) Therefore a check based on macros defined by the compiler (i.e. like proposed by Jochen) is more appropriate.

**Comment by UnaNancyOwen** [comment]
I think so too.
I agree to the Jochen's proposed.

**Comment by UnaNancyOwen** [comment]
How to define SSE4.1(\__SSE4_1\__)? (SSE4.1 has been used [here](https://github.com/PointCloudLibrary/pcl/blob/master/keypoints/src/brisk_2d.cpp#L45).)
Visual C++ does not defined these macros as well as SSE and SSE2.
Of course, The intrinsic instructions of SSE3 and later can be use in Visual C++.

**Comment by jspricke** [comment]
I haven't found anything for SSE4, I guess we have to do something like pcl_find_sse.cmake for them :/.

**Comment by UnaNancyOwen** [comment]
I propose the following changes of [CMakeLists.txt#L136-L139](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L136-L139).
What do you think?

```
if(MSVC)
  SET(CMAKE_COMPILER_IS_MSVC 1)
  add_definitions ("-DBOOST_ALL_NO_LIB -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -DPCL_ONLY_CORE_POINT_TYPES /bigobj")
+ if(HAVE_SSE4_1_EXTENSIONS)
+   add_definitions("-D__SSE4_1__")
+ endif()
+ if(HAVE_SSE2_EXTENSIONS)
+   add_definitions("-D__SSE2__")
+ endif()
+ if(HAVE_SSE_EXTENSIONS)
+   add_definitions("-D__SSE__")
+ endif()
  if("${CMAKE_CXX_FLAGS}" STREQUAL " /DWIN32 /D_WINDOWS /W3 /GR /EHsc")	# Check against default flags
```

**Comment by UnaNancyOwen** [comment]
I propose the following changes of [pcl/CMakeLists.txt#L136-L138](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L136-L138).

```
if(MSVC)
  SET(CMAKE_COMPILER_IS_MSVC 1)
  add_definitions ("-DBOOST_ALL_NO_LIB -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -DPCL_ONLY_CORE_POINT_TYPES /bigobj")
+ # ToDo : Add check SSSE3 to pcl_find_sse.cmake
+ if(HAVE_SSSE3_EXTENSIONS)
+   add_definitions("-D__SSSE3__")
+ endif()
+ if(HAVE_SSE2_EXTENSIONS)
+   add_definitions("-D__SSE2__")
+ endif()
+ if(HAVE_SSE_EXTENSIONS)
+   add_definitions("-D__SSE__")
+ endif()
```

What do you think?

**Comment by taketwo** [comment]
I'd propose that in [pcl_find_sse.cmake:168-173](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_find_sse.cmake#L168-L173) analogously to `SSE_FLAGS` we create an `SSE_DEFINITIONS` variable and append to it. Then in the main CMakeLists file we append this variable to the `add_definitions` call on [line 138](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L138).

By the way, any idea how to check for SSSE3 on MSVC? Which `HAVE_SSE_***` do you currently get?

**Comment by UnaNancyOwen** [comment]
The intrinsic instructions seems can be always used regardless of compiler option settings in VC++.
If the CPU is compatible, all HAVE_SSE*_EXTENSIONS indicates 1(true) in MSVC.
(The VC++ compiler option (/arch:sse2) seems opration is different to the GCC compiler option (-msse2). The GCC can not be used intrinsic instructions when not setting corresponding compiler option.)

Therefore, it should always be define preprocessor macros in Visual C++.
SSSE3 chaeck and set SSE_DEFINITIONS is following.
```
include(CheckCXXSourceRuns)

# check SSSE3
set(CMAKE_REQUIRED_FLAGS)
if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG)
    set(CMAKE_REQUIRED_FLAGS "-mssse3")
endif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG)

check_cxx_source_runs("
    #include <tmmintrin.h>
    int main ()
    {
        __m128i a, b;
        int vals[4] = { -1, -2, -3, -4 };
        a = _mm_loadu_si128( (const __m128i*)vals );
        b = _mm_abs_epi32( a );
        _mm_storeu_si128( (__m128i*)vals, b );
        return 0;
    }"
    HAVE_SSSE3_EXTENSIONS)

# check SSE2 has implemented in pcl_find_sse.cmake
# check SSE  has implemented in pcl_find_sse.cmake

set(CMAKE_REQUIRED_FLAGS)

set(SSE_DEFINITIONS)
if(MSVC)
    if(HAVE_SSSE3_EXTENSIONS)
        set(SSE_DEFINITIONS "${SSE_DEFINITIONS} -D__SSSE3__")
    endif()
    if(HAVE_SSE2_EXTENSIONS)
        set(SSE_DEFINITIONS "${SSE_DEFINITIONS} -D__SSE2__")
    endif()
    if(HAVE_SSE_EXTENSIONS)
        set(SSE_DEFINITIONS "${SSE_DEFINITIONS} -D__SSE__")
    endif()
endif()
```

**Comment by taketwo** [comment]
Thanks for the explanation, makes sense.

**Comment by UnaNancyOwen** [comment]
I sent a pull request #1525.
Please review it.

Thanks.
