### ISSUE TITLE
loadPCL() : segmentation fault

### ISSUE THREAD

**Issue by mrcharlie90** [PointCloudLibrary/pcl#1524]
I would like to report this problem 
http://www.pcl-users.org/segmentation-fault-in-loadPCDFile-tc4040629.html#a4040816
The following code 

``` cpp
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>

int main (int argc, char** argv)
{
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);

  if (pcl::io::loadPCDFile<pcl::PointXYZ> ("test_pcd.pcd", *cloud) == -1) //* load the file
  {
    PCL_ERROR ("Couldn't read file test_pcd.pcd \n");
    return (-1);
  }
  std::cout << "Loaded "
      << cloud->width * cloud->height
            << " data points from test_pcd.pcd with the following fields: "
            << std::endl;
  for (size_t i = 0; i < cloud->points.size (); ++i)
    std::cout << "    " << cloud->points[i].x
              << " "    << cloud->points[i].y
              << " "    << cloud->points[i].z << std::endl;

  return (0);
}
```

output a **segmentation fault** at `pcl::io::loadPCDFile<pcl::PointXYZ> ("test_pcd.pcd", *cloud)`

I've installed **PCL 1.7.2** through homebrew  on a  **Mac Pro Retina (2012) with OS X El Capitan**.

When debugging the program, the problem is in the function 

`read (file_name, blob, ... , offset)` which gives me the following error:
`Exception: EXC_BAD_ACCESS (code=1, address=0x0))`

in the following function (in the **pcd_io.h**):

``` cpp
read (const std::string &file_name, pcl::PointCloud<PointT> &cloud, const int offset = 0)
{
        pcl::PCLPointCloud2 blob;
        int pcd_version;
        int res = read (file_name, blob, cloud.sensor_origin_, cloud.sensor_orientation_, 
                        pcd_version, offset);

        // If no error, convert the data
        if (res == 0)
          pcl::fromPCLPointCloud2 (blob, cloud);
        return (res);
}
```

**Comment by SergioRAgostinho** [comment]
Does this happen with all PCD files or only with this test_pcd.pcd you load in your code?

**Comment by mrcharlie90** [comment]
All pcd files.

**Comment by SergioRAgostinho** [comment]
Can you try purging and pcl and all its dependencies in homebrew, and reinstalling everything again. This feels like an issue in your development environment. Not really a PCL bug.

**Comment by carbomap** [comment]
Interesting... I've got the exact same issue! and same hardware configuration

**Comment by mrcharlie90** [comment]
I've tried to remove all dependencies and install it again through homebrew several times,  but the segmentation fault is still there.

**Comment by carbomap** [comment]
Just did the same... removed PCL and all dependencies via brew. Reinstall all... got same error.

**Comment by SergioRAgostinho** [comment]
@mrcharlie90 & @carbomap - do you guys mind trying it with the trunk or [1.8.0-rc1](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.0rc1)?

**Comment by soyersoyer** [comment]
Are you using the same libc++/libstdc++ in boost_filesystem and libpcl?
You can check it with otool -L

**Comment by mrcharlie90** [comment]
@SergioRAgostinho I don't know, how can I check it? I think it's the trunk version, however. I've tried to look inside the brew's formulae (which I installed through `brew install pcl`) and it downloads the 1.7.2 version from the following link:
[https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz](url)

@soyersoyer Could you please give me the right command? I've never used otool before

**Comment by carbomap** [comment]
yes same here… advice on using otool would be welcome.
Indeed brew installs the 1.7.2 version. I’ve downloaded the 1.8 trunk and ready to install it… will do that later today.
Antoine

> On 17 Feb 2016, at 08:46, mrcharlie90 <notifications@github.com> wrote:
> 
> @SergioRAgostinho <https://github.com/SergioRAgostinho> I don't know, how can I check it? I think it's the trunk version, however. I've tried to look inside the brew's formulae (which I installed through brew install pcl) and it downloads the 1.7.2 version from the following link:
> https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.2.tar.gz <x-msg://6/url>
> @soyersoyer <https://github.com/soyersoyer> Could you please give me the right command? I've never used otool before
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PointCloudLibrary/pcl/issues/1524#issuecomment-185099867>.
> 

-----------------------
Dr Antoine Cottin
Chief Technology Officer
Carbomap Ltd.
Edinburgh Centre for Carbon Innovation
High School Yards
Edinburgh EH1 1LZ
-----------------------
http://www.carbomap.com
http://carbomap.wordpress.com
http://github.com/carbomap
@carbomap
+44 (0)7577 444-046

**Comment by SergioRAgostinho** [comment]
Basically it's as @soyersoyer mentioned. Locate boost_filesystem.dylib and pcl_io.dylib (not sure if this is the actual name but I can confirm later), and then 
```
$ otool -L <path/to/lib.dylib>
````
Then copy the output here

**Comment by carbomap** [comment]
Here is the output:

Darkwater:~ moi$ otool -L /usr/local/Cellar/boost/1.60.0_1/lib/libboost_filesystem.dylib

/usr/local/Cellar/boost/1.60.0_1/lib/libboost_filesystem.dylib:
	/usr/local/opt/boost/lib/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)


Darkwater:~ moi$ otool -L /usr/local/Cellar/pcl/1.7.2/lib/libpcl_io.1.7.2.dylib 

/usr/local/Cellar/pcl/1.7.2/lib/libpcl_io.1.7.2.dylib:
	/usr/local/opt/pcl/lib/libpcl_io.1.7.dylib (compatibility version 1.7.0, current version 1.7.2)
	/usr/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_iostreams-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	@loader_path/libpcl_common.1.7.dylib (compatibility version 1.7.0, current version 1.7.2)
	@loader_path/libpcl_io_ply.1.7.dylib (compatibility version 1.7.0, current version 1.7.2)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/lib/libvtkDomainsChemistry-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/local/lib/libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/lib/libsz.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/lib/libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/lib/libvtkFiltersFlowPaths-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersGeneric-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersHyperTree-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersParallelImaging-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersProgrammable-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersPython-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/usr/local/lib/libvtkWrappingPython27Core-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersSelection-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersSMP-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersVerdict-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkverdict-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkGeovisCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/lib/libpng16.16.dylib (compatibility version 35.0.0, current version 35.0.0)
	/usr/local/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/local/lib/libvtkproj4-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkGUISupportQtOpenGL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkGUISupportQtSQL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOSQL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtksqlite-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkGUISupportQtWebkit-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkViewsQt-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkViewsInfovis-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingMath-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingMorphological-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingStatistics-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingStencil-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInfovisBoostGraphAlgorithms-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInteractionImage-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOAMR-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOEnSight-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOExodus-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOExport-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingGL2PS-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingContextOpenGL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOImport-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOInfovis-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/local/lib/libvtkIOLSDyna-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOMINC-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOMovie-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkoggtheora-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOParallel-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkjsoncpp-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOParallelXML-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOPLY-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOVideo-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingFreeTypeFontConfig-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingImage-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingLIC-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingLOD-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingQt-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingVolumeOpenGL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkViewsContext2D-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libusb-1.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libpcap.A.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkChartsCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersImaging-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInfovisLayout-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersAMR-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkgl2ps-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInfovisCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkexoIIc-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersParallel-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIONetCDF-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkNetCDF_cxx-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkNetCDF-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkParallelCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOXML-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOGeometry-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOXMLParser-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOLegacy-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersTexture-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkGUISupportQt-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/QtGui.framework/Versions/4/QtGui (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/lib/QtNetwork.framework/Versions/4/QtNetwork (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/lib/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
	/usr/local/lib/libvtkRenderingLabel-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingOpenGL-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/usr/local/lib/libvtkRenderingContext2D-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkViewsCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInteractionWidgets-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersHybrid-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingGeneral-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingSources-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersModeling-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingHybrid-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOImage-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkDICOMParser-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkIOCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkmetaio-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkInteractionStyle-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingAnnotation-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingFreeType-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkftgl-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkfreetype-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.4.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingColor-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingVolume-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkRenderingCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonColor-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersExtraction-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersStatistics-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkalglib-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingFourier-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkImagingCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersGeometry-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersSources-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersGeneral-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkFiltersCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonExecutionModel-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonComputationalGeometry-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonDataModel-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonMisc-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonTransforms-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonMath-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonSystem-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtkCommonCore-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libvtksys-6.3.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)


> On 17 Feb 2016, at 09:57, Sérgio Agostinho <notifications@github.com> wrote:
> 
> Basically it's as @soyersoyer <https://github.com/soyersoyer> mentioned. Locate boost_filesystem.dylib and pcl_io.dylib (not sure if this is the actual name but I can confirm later), and then
> 
> $ otool -L <path/to/lib.dylib>
> Then copy the output here
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PointCloudLibrary/pcl/issues/1524#issuecomment-185129353>.
> 

-----------------------
Dr Antoine Cottin
Chief Technology Officer
Carbomap Ltd.
Edinburgh Centre for Carbon Innovation
High School Yards
Edinburgh EH1 1LZ
-----------------------
http://www.carbomap.com
http://carbomap.wordpress.com
http://github.com/carbomap
@carbomap
+44 (0)7577 444-046

**Comment by SergioRAgostinho** [comment]
You seem to have two boost versions installed, one through homebrew and another manually. Get rid of the manual one installed in ```/usr/local/lib``` and try reinstalling again.

**Comment by carbomap** [comment]
ok so what I have in /usr/local/lib are aliases pointing to my brew boost installation. actually this folder only have aliases…
So should I just remove the aliases or the actual boost folder in /usr/local/Cellar/boost?
A-

> On 17 Feb 2016, at 10:09, Sérgio Agostinho <notifications@github.com> wrote:
> 
> You seem to have two boost versions installed, one through homebrew and another manually. Get rid of the manual one installed in /usr/local/lib and try reinstalling again.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PointCloudLibrary/pcl/issues/1524#issuecomment-185133150>.
> 

-----------------------
Dr Antoine Cottin
Chief Technology Officer
Carbomap Ltd.
Edinburgh Centre for Carbon Innovation
High School Yards
Edinburgh EH1 1LZ
-----------------------
http://www.carbomap.com
http://carbomap.wordpress.com
http://github.com/carbomap
@carbomap
+44 (0)7577 444-046

**Comment by soyersoyer** [comment]
When did you build the libpcl? The libsystem.B.dylib version looks different than the libboost_filesystem's, which is suspicios. Did you use the same compiler?
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1) vs
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by carbomap** [comment]
same compiler… but I just see that PCL has been updated this morning via Brew
Boost install (via brew too) dates from January 26th 2016.
A-


> On 17 Feb 2016, at 16:10, soyer <notifications@github.com> wrote:
> 
> When did you build the libpcl? The libsystem.B.dylib version looks different than the libboost_filesystem's, which is suspicios. Did you use the same compiler?
> /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1) vs
> /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PointCloudLibrary/pcl/issues/1524#issuecomment-185275805>.
> 

-----------------------
Dr Antoine Cottin
Chief Technology Officer
Carbomap Ltd.
Edinburgh Centre for Carbon Innovation
High School Yards
Edinburgh EH1 1LZ
-----------------------
http://www.carbomap.com
http://carbomap.wordpress.com
http://github.com/carbomap
@carbomap
+44 (0)7577 444-046

**Comment by eythor** [comment]
Same issue for me. Did updating PCL to 1.8 fix it?

MacBook Pro (15-inch, Mid 2010), OS X El Capitan 10.11.3

$ brew info pcl
homebrew/science/pcl: stable 1.7.2 (bottled), HEAD


$ brew info boost
boost: stable 1.60.0 (bottled), HEAD
Collection of portable C++ source libraries
http://www.boost.org
/usr/local/Cellar/boost/1.59.0 (10,928 files, 429.2M)
  Poured from bottle
/usr/local/Cellar/boost/1.60.0_1 (11,139 files, 436.0M)

**Comment by lilouch** [comment]
I have the same issue with PCL 1.8 and a MAC El Capitan.

**Comment by lilouch** [comment]
I have the same issue with PCL 1.8 and a  Mac Pro Retina (2015) with OS X El Capitan.

**Comment by Galto2000** [comment]
I have the same issue still using PCL 1.8, also compiled from source on Ubuntu 16.04 LTS using OpenNI-Bin-Dev-Linux-x64-v1.5.8.5.

Any ideas?

Thanks

Galto

**Comment by mickeyouyou** [comment]
Ubuntu 18.04 pcl 1.8 same issue.

**Comment by kunaltyagi** [comment]
Issue seems to regarding broken ABI of boost libraries. Closing since it is not actionable by PCL
