### ISSUE TITLE
OpenNI Grabber Question

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1531]
I notice that the point cloud extracted from the OpenNI Grabber in pcl/io is far superior (less noisy and higher resolution) than the one provided by the ROS API. I'd like to know if any kind of post-processing is applied to the point cloud or the depth map before points are generated?

https://github.com/PointCloudLibrary/pcl/blob/master/io/src/openni_grabber.cpp

**Comment by taketwo** [comment]
This is a bug tracker, not a support forum. Please use PCL users mailing list to ask such questions.
