### ISSUE TITLE
How to generate executable files of Kinfu ?

### ISSUE THREAD

**Issue by haopo2005** [PointCloudLibrary/pcl#1544]
Hi, 
 I want to generate the executable file of pcl_gpu_kinfu_large_scale and pcl_gpu_kinfu. 
 I have downloaded the source  code from github pcl-1.8.0-rc1. And my os is ubuntu 14.04 armhf (Nvidia TK1) 
  
 I have chosen  the option in the CMake-gui: 
BUILD_CUDA 
BUILD_GPU 
BUILD_gpu_kinfu 
BUILD_gpu_kinfu_large_scale 
BUILD_apps 
BUILD_examples 

There is no  error  after the compile: 
ubuntu@tegra-ubuntu:~/share/PCL/pcl/pcl-pcl-1.8.0rc1/build/bin$ cd .. 
ubuntu@tegra-ubuntu:~/share/PCL/pcl/pcl-pcl-1.8.0rc1/build$ make 
[  3%] Built target pcl_common 
[  3%] Built target pcl_octree 
[  3%] Built target pcl_io_ply 
[ 10%] Built target pcl_io 
[ 10%] Built target pcl_convert_pcd_ascii_binary 
[ 11%] Built target pcl_converter 
[ 11%] Built target pcl_hdl_grabber 
[ 12%] Built target pcl_pcd_convert_NaN_nan 
[ 12%] Built target pcl_pcd_introduce_nan 
[ 12%] Built target pcl_ply2obj 
[ 12%] Built target pcl_ply2ply 
[ 12%] Built target pcl_ply2raw 
[ 12%] Built target pcl_plyheader 
[ 14%] Built target pcl_stereo 
[ 14%] Built target pcl_kdtree 
[ 15%] Built target pcl_search 
[ 18%] Built target pcl_sample_consensus 
[ 24%] Built target pcl_filters 
[ 24%] Built target pcl_2d 
[ 31%] Built target pcl_features 
[ 32%] Built target pcl_ml 
[ 36%] Built target pcl_segmentation 
[ 40%] Built target pcl_visualization 
[ 40%] Built target pcl_hdl_viewer_simple 
[ 40%] Built target pcl_openni2_viewer 
[ 40%] Built target pcl_pcd_image_viewer 
[ 40%] Built target pcl_timed_trigger_test 
[ 40%] Built target pcl_viewer 
[ 40%] Built target pcl_vlp_viewer 
[ 40%] Built target pcl_people 
[ 45%] Built target pcl_surface 
[ 46%] Built target pcl_cuda_segmentation 
[ 46%] Built target pcl_cuda_features 
[ 47%] Built target pcl_cuda_sample_consensus 
[ 47%] Built target pcl_gpu_containers 
[ 47%] Built target pcl_gpu_utils 
[ 49%] Built target pcl_gpu_octree 
[ 49%] Built target pcl_gpu_segmentation 
[ 51%] Built target pcl_gpu_features 
[ 55%] Built target pcl_gpu_kinfu 
[ 59%] Built target pcl_gpu_kinfu_large_scale 
[ 60%] Built target pcl_tracking 
[ 68%] Built target pcl_registration 
[ 71%] Built target pcl_recognition 
[ 73%] Built target pcl_keypoints 
[ 73%] Built target pcl_add_gaussian_noise 
[ 73%] Built target pcl_boundary_estimation 
[ 74%] Built target pcl_cluster_extraction 
[ 75%] Built target pcl_compute_cloud_error 
[ 75%] Built target pcl_compute_hausdorff 
[ 75%] Built target pcl_compute_hull 
[ 75%] Built target pcl_concatenate_points_pcd 
[ 75%] Built target pcl_crf_segmentation 
[ 75%] Built target pcl_crop_to_hull 
[ 75%] Built target pcl_demean_cloud 
[ 75%] Built target pcl_elch 
[ 75%] Built target pcl_extract_feature 
[ 75%] Built target pcl_fast_bilateral_filter 
[ 75%] Built target pcl_fpfh_estimation 
[ 76%] Built target pcl_generate 
[ 76%] Built target pcl_gp3_surface 
[ 77%] Built target pcl_grid_min 
[ 77%] Built target pcl_icp 
[ 77%] Built target pcl_icp2d 
[ 77%] Built target pcl_linemod_detection 
[ 78%] Built target pcl_local_max 
[ 78%] Built target pcl_lum 
[ 78%] Built target pcl_marching_cubes_reconstruction 
[ 78%] Built target pcl_match_linemod_template 
[ 78%] Built target pcl_mesh2pcd 
[ 79%] Built target pcl_mesh_sampling 
[ 79%] Built target pcl_mls_smoothing 
[ 80%] Built target pcl_morph 
[ 80%] Built target pcl_ndt2d 
[ 80%] Built target pcl_ndt3d 
[ 81%] Built target pcl_normal_estimation 
[ 81%] Built target pcl_obj2pcd 
[ 81%] Built target pcl_obj2ply 
[ 81%] Built target pcl_obj2vtk 
[ 81%] Built target pcl_obj_rec_ransac_accepted_hypotheses 
[ 82%] Built target pcl_obj_rec_ransac_hash_table 
[ 82%] Built target pcl_obj_rec_ransac_model_opps 
[ 82%] Built target pcl_obj_rec_ransac_orr_octree 
[ 82%] Built target pcl_obj_rec_ransac_orr_octree_zprojection 
[ 82%] Built target pcl_obj_rec_ransac_result 
[ 83%] Built target pcl_obj_rec_ransac_scene_opps 
[ 83%] Built target pcl_octree_viewer 
[ 83%] Built target pcl_organized_pcd_to_png 
[ 84%] Built target pcl_outlier_removal 
[ 84%] Built target pcl_passthrough_filter 
[ 84%] Built target pcl_pcd2ply 
[ 84%] Built target pcl_pcd2png 
[ 84%] Built target pcl_pcd2vtk 
[ 84%] Built target pcl_pcd_change_viewpoint 
[ 84%] Built target pcl_pclzf2pcd 
[ 84%] Built target pcl_plane_projection 
[ 85%] Built target pcl_ply2pcd 
[ 85%] Built target pcl_ply2vtk 
[ 86%] Built target pcl_png2pcd 
[ 86%] Built target pcl_poisson_reconstruction 
[ 86%] Built target pcl_progressive_morphological_filter 
[ 87%] Built target pcl_radius_filter 
[ 87%] Built target pcl_registration_visualizer 
[ 87%] Built target pcl_sac_segmentation_plane 
[ 87%] Built target pcl_spin_estimation 
[ 87%] Built target pcl_tiff2pcd 
[ 87%] Built target pcl_train_linemod_template 
[ 88%] Built target pcl_train_unary_classifier 
[ 88%] Built target pcl_transform_from_viewpoint 
[ 88%] Built target pcl_transform_point_cloud 
[ 88%] Built target pcl_unary_classifier_segment 
[ 88%] Built target pcl_uniform_sampling 
[ 89%] Built target pcl_vfh_estimation 
[ 89%] Built target pcl_virtual_scanner 
[ 90%] Built target pcl_voxel_grid 
[ 90%] Built target pcl_voxel_grid_occlusion_estimation 
[ 90%] Built target pcl_vtk2obj 
[ 90%] Built target pcl_vtk2pcd 
[ 90%] Built target pcl_vtk2ply 
[ 91%] Built target pcl_xyz2pcd 
[ 91%] Built target pcl_outofcore 
[ 91%] Built target pcl_outofcore_print 
[ 92%] Built target pcl_outofcore_process 
[ 92%] Built target pcl_apps 
[ 92%] Built target pcl_convolve 
[ 92%] Built target pcl_dinast_grabber 
[ 92%] Built target pcl_face_trainer 
[ 93%] Built target pcl_feature_matching 
[ 93%] Built target pcl_fs_face_detector 
[ 93%] Built target pcl_grabcut_2d 
[ 93%] Built target pcl_multiscale_feature_persistence_example 
[ 93%] Built target pcl_nn_classification_example 
[ 93%] Built target pcl_pcd_organized_edge_detection 
[ 93%] Built target pcl_pcd_organized_multi_plane_segmentation 
[ 94%] Built target pcl_pcd_select_object_plane 
[ 94%] Built target pcl_ppf_object_recognition 
[ 94%] Built target pcl_pyramid_surface_matching 
[ 94%] Built target pcl_statistical_multiscale_interest_region_extraction_example 
[ 94%] Built target pcl_stereo_ground_segmentation 
[ 94%] Built target pcl_surfel_smoothing_test 
[ 94%] Built target pcl_test_search_speed 
[ 95%] Built target pcl_example_stereo_baseline 
[ 95%] Built target pcl_example_check_if_point_is_valid 
[ 96%] Built target pcl_example_copy_point_cloud 
[ 96%] Built target pcl_example_get_max_min_coordinates 
[ 96%] Built target pcl_example_organized_point_cloud 
[ 96%] Built target pcl_example_scope_time 
[ 96%] Built target pcl_example_half_edge_mesh 
[ 96%] Built target pcl_example_cpc_segmentation 
[ 96%] Built target pcl_example_extract_clusters_normals 
[ 96%] Built target pcl_example_lccp_segmentation 
[ 96%] Built target pcl_example_region_growing 
[ 96%] Built target pcl_example_supervoxels 
[ 96%] Built target pcl_example_extract_indices 
[ 96%] Built target pcl_example_remove_nan_from_point_cloud 
[ 96%] Built target pcl_example_difference_of_normals 
[ 97%] Built target pcl_example_fast_point_feature_histograms 
[ 98%] Built target pcl_example_normal_estimation 
[ 98%] Built target pcl_example_point_feature_histograms 
[ 99%] Built target pcl_example_principal_curvatures_estimation 
[ 99%] Built target pcl_example_rift_estimation 
[100%] Built target pcl_example_shape_contexts 
[100%] Built target pcl_example_spin_images 
[100%] Built target pcl_example_outofcore 
[100%] Built target pcl_example_outofcore_with_lod 
[100%] Built target pcl_example_get_keypoints_indices 
[100%] Built target pcl_example_sift_keypoint_estimation 
[100%] Built target pcl_example_sift_normal_keypoint_estimation 
[100%] Built target pcl_example_sift_z_keypoint_estimation 

However I can’t find any executable file about GPU under the  ../build/bin path ,only so under ../build/lib
Can anybody help me? 

I have posted on the Point Cloud Library Mail List:
[http://www.pcl-users.org/How-to-generate-executable-files-of-Kinfu-td4041004.html](url)

**Comment by SergioRAgostinho** [comment]
This is a bug tracker to report bugs. Use the mailing list for questions (and wait).

**Comment by haopo2005** [comment]
The Reason seems to be kinfu not compatible with OpenNI2. 
How can I make kinfu compiled with OpenNI2? 
There are many OpenNI API in kinfu_app.cpp 

Thanks
