### ISSUE TITLE
cloud composer rejects any pcd file

### ISSUE THREAD

**Issue by 42loop** [PointCloudLibrary/pcl#1555]
I have finally successfully built pcl including cloud_composer using qt4 and vtk6.0 on ubuntu 14.04.3

most of the binaries work just fine, however, trying to load any .pcd cloud into cloud_composer yields the following error:
[setPointCloudRenderingProperties] Could not find any PointCloud datasets with id <bun00031615344>!
(this one from the stanford bunny pcd)

is this tool deprecated?
any hints welcome...

**Comment by 42loop** [comment]
of course there is an id in brackets before the exclamation mark, `<bun00031615344>` in this case

**Comment by 42loop** [comment]
ok, this was a misleading error message: cloud composer works fine with XYZRGBA clouds

**Comment by lakehanne** [comment]
How'd you fix the setPointCloudRenderingProperties Issue?
