### ISSUE TITLE
Error in pcl::registration::TransformationEstimation2D

### ISSUE THREAD

**Issue by nenadpol** [PointCloudLibrary/pcl#1559]
Hi, 

Rows(columns) in TransformationEstimation2D output transformation are not normalized. Error is not huge but if you use this transformation to transform clouds several times that you get big difference in distances between points. 
This transformation as it is know scales point coordinates in XY plane. 
That is why I am getting difference in length between points before and after transformation. 

pcl::registration::TransformationEstimation2Dpcl::PointXYZ,pcl::PointXYZ,double est2D; 
est2D.estimateRigidTransformation(*source, *target , output_finalTransformation); 

double test=sqrt( output_finalTransformation(0,0)_output_finalTransformation(0,0)+output_finalTransformation(0,1)_output_finalTransformation(0,1)); 

"test" value should be =1 but it deviates already in 4-5 decimal point. 

cheers 
Nenad

**Comment by SergioRAgostinho** [comment]
Hey Nenad, can you provide some testing code. I tried with this snippet but got ```1``` as the final result. 

```cpp
#include <iostream>
#include <pcl/registration/transformation_estimation_2D.h>

int
main (int argc, char *argv[])
{
  pcl::PointCloud<pcl::PointXYZ>::Ptr source (new pcl::PointCloud<pcl::PointXYZ>);
  pcl::PointCloud<pcl::PointXYZ>::Ptr target (new pcl::PointCloud<pcl::PointXYZ>);
  Eigen::Matrix4d output_finalTransformation;

  source->width = 5;
  source->height = 1;
  source->points.resize (5);
  source->points[0].x = 0.f; source->points[0].y = 0.f; source->points[0].z = 0.f;
  source->points[1].x = 0.f; source->points[1].y = 1.f; source->points[1].z = 0.f;
  source->points[2].x = 0.5f; source->points[2].y = 0.5f; source->points[2].z = 0.f;
  source->points[3].x = 1.f; source->points[3].y = 1.f; source->points[3].z = 0.f;
  source->points[4].x = 1.f; source->points[4].y = 0.f; source->points[4].z = 0.f;
  *target = *source;

  pcl::registration::TransformationEstimation2D<pcl::PointXYZ, pcl::PointXYZ, double> est2D; 
  est2D.estimateRigidTransformation (*source, *target , output_finalTransformation);

  double test = sqrt (output_finalTransformation (0,0) * output_finalTransformation (0,0)
                      +output_finalTransformation (0,1) * output_finalTransformation (0,1));

  std::cout << test << std::endl;
  return 0;
}
```

which yielded 
```
$ ./trans_est_2d 
1
$
```
:/
