### ISSUE TITLE
1.8 rc2 CUDA + Qt Compiler errors on Mac OS X

### ISSUE THREAD

**Issue by ahundt** [PointCloudLibrary/pcl#1563]
Relevant to 1.8 release issue #1373

I'm encountering quite a few compiler issues on OS X:

[Full make -i output](https://gist.github.com/ahundt/cfd6fca1499361cab27d)

[ 68%] Building NVCC (Device) object gpu/features/CMakeFiles/pcl_gpu_features.dir/src/pcl_gpu_features_generated_fpfh.cu.o
/Users/athundt/source/git/pcl/gpu/features/src/fpfh.cu(235): error: "__any" is ambiguous

1 error detected in the compilation of "/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T//tmpxft_00008583_00000000-19_fpfh.compute_52.cpp1.ii".
CMake Error at pcl_gpu_features_generated_fpfh.cu.o.cmake:266 (message):
  Error generating file
  /Users/athundt/source/git/pcl/build/gpu/features/CMakeFiles/pcl_gpu_features.dir/src/./pcl_gpu_features_generated_fpfh.cu.o

CUDA errors:
```
[ 68%] Building NVCC (Device) object gpu/features/CMakeFiles/pcl_gpu_features.dir/src/pcl_gpu_features_generated_fpfh.cu.o
/Users/athundt/source/git/pcl/gpu/features/src/fpfh.cu(235): error: "__any" is ambiguous

1 error detected in the compilation of "/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T//tmpxft_00008583_00000000-19_fpfh.compute_52.cpp1.ii".
CMake Error at pcl_gpu_features_generated_fpfh.cu.o.cmake:266 (message):
  Error generating file
  /Users/athundt/source/git/pcl/build/gpu/features/CMakeFiles/pcl_gpu_features.dir/src/./pcl_gpu_features_generated_fpfh.cu.o


[ 68%] Building NVCC (Device) object gpu/features/CMakeFiles/pcl_gpu_features.dir/src/pcl_gpu_features_generated_fpfh.cu.o
/Users/athundt/source/git/pcl/gpu/features/src/fpfh.cu(235): error: "__any" is ambiguous

1 error detected in the compilation of "/var/folders/9f/jr_p974d3j318tmvrfkjl55w0000gp/T//tmpxft_000085b0_00000000-19_fpfh.compute_52.cpp1.ii".
CMake Error at pcl_gpu_features_generated_fpfh.cu.o.cmake:266 (message):
  Error generating file
  /Users/athundt/source/git/pcl/build/gpu/features/CMakeFiles/pcl_gpu_features.dir/src/./pcl_gpu_features_generated_fpfh.cu.o


[ 68%] Linking CXX shared library ../../lib/libpcl_gpu_features.dylib
clang: error: no such file or directory: 'CMakeFiles/pcl_gpu_features.dir/src/pcl_gpu_features_generated_fpfh.cu.o'
```

The Qt errors are much more numerous, it probably makes sense to just check the link above for those.

**Comment by ahundt** [comment]
rc2 is out and I've encountered the same compiler errors:
https://gist.github.com/ahundt/cfd6fca1499361cab27d#file-compiler_errors_rc2-txt

**Comment by victl** [comment]
In case you haven't found a solution, there's a walk around:
edit `gpu/features/src/fpfh.cu`, comment out this line: `using namespace std;`
I think this is a silly mistake. The programmer imported the `std` namespace by habit, but actually didn't used it. But the `std::__any()` must be conflicting with some function also named `__any()` (e.g. cuda or pal itself)
I'm not so familiar with git. So just mention it here, with the hope that somebody could update the repository for everybody

**Comment by VictorLamoine** [comment]
Hey, thanks a lot for the report.
@ahundt does it work with the #1586 patch?

**Comment by ahundt** [comment]
@VictorLamoine @victl seems to get past the CUDA issue now! Thanks!

**Comment by victl** [comment]
I've encountered similar qt issue before. Have you solved it?
I my case, the primary problem is related to other library like VTK are compiled with qt4. Here is how I solved this issue:
- Remove system version of qt4: There is a uninstalling python script located in /Library, I forgot the exact location, you can google it.
- Remove Homebrew version of qt4: `brew unlink qt4`
- manual compile vtk-7.0.0 from source configured with qt5
- compile pcl-1.8 rc2 with vtk-7 and qt5
Everything works fine for me. I'm using Mac OS X 10.10.3 + Qt5.5.1(Homebrew version).
All the best!

**Comment by ahundt** [comment]
@victl thanks for the info. Yeah I've got to switch between qt 4 and 5 depending on the task/toolkit I'm working on so that definitely gets interesting...
