### ISSUE TITLE
Saving .ply mesh with savePLYFile will generate a  .ply file which can not be read by meshlab

### ISSUE THREAD

**Issue by hanxiaomax** [PointCloudLibrary/pcl#1575]
an error called unexpected eof occured.

any tips?

I also tried to write my own function to save .ply file and it also failed.

**Comment by ahundt** [comment]
One likely source of error I encountered is that if you open the file in a text file it is the lines that differ between something like nx and normal_x it may not be processed correctly.

``
property float nx
property float ny
property float nz
``
I believe should become 
``
property float normal_x
property float normal_y
property float normal_z
``

or vice-versa.

Here are some equivalent fixes I had to make in opencv contrib:
https://github.com/Itseez/opencv_contrib/pull/463/commits/1f566a8d46b46d9868dd04a40f351b0683f607fc

**Comment by mvieth** [comment]
This is pretty much impossible to solve without further information. Since this issue is also rather old, I am going to close it. The problem might have been fixed in the meantime.
However, if you (or anyone else) still have this problem, please open a new issue.
