### ISSUE TITLE
BUG: vlp_grabber.cpp LINE130

### ISSUE THREAD

**Issue by secretxu** [PointCloudLibrary/pcl#1576]
`if (j > VLP_MAX_NUM_LASERS)`
should be `if (!j < VLP_MAX_NUM_LASERS)`

**Comment by jspricke** [comment]
Interesting, can you send a pull request with the patch? Have a look here how to do it: https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md.

**Comment by secretxu** [comment]
@jspricke ok

**Comment by seasonsfx** [comment]
the right code should be `if (j >=VLP_MAX_NUM_LASERS)`

**Comment by seasonsfx** [comment]
good someone file the issue, this issue cause my code crush, please merge the fix soon
