### ISSUE TITLE
Problem with two kinect v2 devices

### ISSUE THREAD

**Issue by MM88** [PointCloudLibrary/pcl#1579]
Hi, I'm trying to run two devices at the same time, I have to following code:

void run () {
//first kinect
std::string device_id1 = "#"+boost::lexical_cast<std::string>(1);
pcl::io::OpenNI2Grabber interface1 (device_id1);
boost::function<void (const PointCloud<PointXYZRGBA>::ConstPtr&)> f = boost::bind(&SimpleOpenNIViewer::grabberCallback,this, _1);
interface1.registerCallback (f);
interface1.start ();
//second kinect
std::string device_id2 = "#"+boost::lexical_cast<std::string>(2);
pcl::io::OpenNI2Grabber interface2 (device_id2);
boost::function<void (const PointCloud<PointXYZRGBA>::ConstPtr&)> f2 = boost::bind(&SimpleOpenNIViewer::cloud_cb_2_,this, _1);
interface2.registerCallback (f2);
interface2.start ();
while (!viewer.wasStopped())
{ sleep (1); }
interface2.stop ();
interface1.stop ();
}

This code works fine with two PrimeSense devices and with one Kinect2 and one PrimeSense, but with two kinect2 it open two times the same device.
It seams that when I have two kinect2 connected I can't adress them, nor with device id or serial number.

Thanks in advance.

**Comment by MM88** [comment]
I found out that the second device needed to be addressed with "#5" not "#2", sorry to bother

**Comment by VictorLamoine** [comment]
Please close this issue if your problem is solved.
For this type of questions, please use the [pcl-users](www.pcl-users.org) mailing list.
