### ISSUE TITLE
A GPU Implementation of Moving Least Squares (MLS) for Unorganized Clouds?

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1582]
Does PCL have such an implementation? I have been searching for open source projects, and all of there is one existing project and it is designed for organized point clouds (using pixel wise search instead of a kd-tree/oct-tree)

I have to fuse data from 4 Kinects. Even after downsampling (to 1cm) and using a about a 5cm search space, and using the OpenMP optimization, the processing time is **unacceptable**. It runs at about 0.5Hz. 

If there is no such implementation, I would like to see if it is worth rolling out my own.

**Comment by jspricke** [comment]
Please use our mailing list for questions, this is a issue tracker: http://www.pcl-users.org.

**Comment by soulslicer** [comment]
Unfortunately, the pcl-users website has a very poor response rate. My posts there often go unnoticed, as has this one

**Comment by jspricke** [comment]
I'm sorry for that, but we are all working on voluntary basis, so it's not easy to support everyone.
