### ISSUE TITLE
Issues when building without VTK

### ISSUE THREAD

**Issue by humanoid2050** [PointCloudLibrary/pcl#1584]
I tried to compile without VTK, both through auto detection of VTK being missing and explicitly setting WITH_VTK=FALSE. In both cases, compilation failed with 

```
In file included from /home/user/custom_builds/pcl/src/pcl-pcl-1.8.0rc2/io/tools/converter.cpp:52:0:
/home/user/custom_builds/pcl/src/pcl-pcl-1.8.0rc2/io/include/pcl/io/vtk_lib_io.h:57:24: fatal error: vtkVersion.h: No such file or directory

```

It seems that there is an unprotected reference to VTK components outside the parts disabled by the VTK flags.
As an additional comment, there is no FindVTK.cmake in cmake/Modules/. Not a problem if cmake can automatically find VTKConfig.cmake under a known directory, but cmake will throw a warning if not found. Additionally, the logic in CMakeLists.txt seems to leave VTK_FOUND and HAVE_VTK uninitialized in this situation.

**Comment by VictorLamoine** [comment]
My bad, I forgot to check that VTK is here to build `pcl_converter` and the David SDK grabber.
Pull request #1585 should fix the compilation.

**Comment by jspricke** [comment]
Should be fixed in master, Thanks!
