### ISSUE TITLE
when i replace pcl::PointXYZRGBA  to  pcl::PointXYZRGB,  this tutorial: correspondence_grouping.cpp line16  occur Error LNK2019 Unresolved External Symbol

### ISSUE THREAD

**Issue by zkl99999** [PointCloudLibrary/pcl#1590]
at
[https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/correspondence_grouping/correspondence_grouping.cpp#L16](url)
   line 16
typedef pcl::PointXYZRGBA PointType;

cg.obj : error LNK2001 Unresolved External Symbol  "private: virtual void __cdecl pcl::NormalEstimationOMP<struct pcl::PointXYZRGB,struct pcl::Normal>::computeFeature(
cg.obj : error LNK2019 Unresolved External Symbol   "public: bool __cdecl......
pcl::GeometricConsistencyGrouping<struct pcl::PointXYZRGB,struct pcl::PointXYZRGB>::recognize(class std::vector<class Eigen::Matrix<fl.......
cg.obj : error LNK2019 Unresolved External Symbol  "protected: virtual void __cdecl pcl::GeometricConsistencyGrouping<struct pcl::PointXYZRGB,struct pcl::PointXYZRGB>::clusterCorrespondences(cla....
cg.exe : fatal error LNK1120:  three unresolved external commands

**Comment by UnaNancyOwen** [comment]
These APIs which is used in that tutorial code does not support pcl::PointXYZRGB.
For this reason, that compiler error occurs.
You need to use the PointTypes these API supports, or to be implementing in yourself.

* [pcl::NormalEstimationOMP](https://github.com/PointCloudLibrary/pcl/blob/456bf44205ac7ed09b2754e2062d08a1a7fbed53/features/src/normal_3d.cpp#L48) has been implemented for following input PointTypes (pcl::PointXYZ, pcl::PointXYZI, pcl::PointXYZRGBA).

* [pcl::GeometricConsistencyGrouping](https://github.com/PointCloudLibrary/pcl/blob/456bf44205ac7ed09b2754e2062d08a1a7fbed53/recognition/src/cg/geometric_consistency.cpp#L46) has been implemented for following input/output PointTypes (pcl::PointXYZ, pcl::PointXYZI, pcl::PointXYZRGBA).

For this type of questions, please use the [pcl-users mailing list](http://www.pcl-users.org/).

**Comment by zkl99999** [comment]
thank you

**Comment by SergioRAgostinho** [comment]
It is worth mentioning that if you really want to use your original point type, you can do it by adding it to the instantiation list and recompiling PCL.
