### ISSUE TITLE
Integration of ReLOC algorithm for Pairwise 3D registration

### ISSUE THREAD

**Issue by aliosciapetrelli** [PointCloudLibrary/pcl#1591]
Hi there,
I'm the author of ReLOC algorithm that I proposed in : 
Petrelli A., Di Stefano L., "Pairwise registration by local orientation cues", Computer Graphics Forum, 2015.

I'm interested in integrating the algorithm in PCL.
Before I go ahead, I would ask for the green light.

Alioscia

**Comment by VictorLamoine** [comment]
Hi,

Contributions are more than welcome, you should follow these guidelines:
https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md

Do not hesitate to ask us questions if you have any problem during the process. (using git, github etc.)
Closing as this is not an "issue", feel free to ask questions here though.

Bye
