### ISSUE TITLE
TextureMesh struct needs additional texture index buffer public attribute

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#1592]
Currently TextureMesh has 

cloud: A list of XYZ points
tex_polygons:  index buffer for XYZ points, so we know which 3 points should form a triangle
tex_coordinates: A list of UV points

The index buffer for UV points is missing, without it we would have no idea which UV correspond to which XYZ point in a triangle.

I notice that the obj file produced by saveOBJFile, the texture index buffer is in a perfect order

f ?/1/? ?/2/? ?/3/?
f ?/4/? ?/5/? ?/6/?
...

and loadOBJFile only handles index buffer for vertices as shown in obj_io.cpp line 800~814, assuming the list of UV points is in a certain order

but it is totally likely for a OBJ file to have randomly ordered texture index buffer 

f ?/2/? ?/1/? ?/5/?
f ?/4/? ?/5/? ?/3/?

Causing loadOBJFile to return erroneous results when the OBJ is generated elsewhere (like MeshLab) instead of from saveOBJFile.

One approach to solve it is create an additional texture index buffer public attribute for TextureMesh struct, and loadOBJFile will simply parse it.

If adding an additional texture index buffer public attribute for TextureMesh struct is not desired, another approach is loadOBJFile will still need to read the texture index buffer info from the obj file, and re-order/duplicate the list of UV points to the assumed order.

What do you think?

**Comment by junsmog** [comment]
Could it be related to the following issue [https://github.com/PointCloudLibrary/pcl/issues/1602](url) ?

**Comment by jasjuang** [comment]
Yes, I downloaded your test file and the texture index buffer is randomly ordered so PCL cannot handle this correctly due to this issue. Hopefully this will get fixed sometime soon

**Comment by 761687049** [comment]
thank you.  At least I want to see a little color, but only a white box, and have the texture picture. when using cube.obj. How to trigger the display of texture？ http://www.pcl-users.org/How-to-load-obj-with-texture-td4041450.html. there is the cube.

**Comment by jasjuang** [comment]
Again randomly ordered texture buffer. Another potential is the faces are quadrilaterals instead of triangles, I am not sure if PCL can handle this.

If you want to test, I suggest creating a simple OBJ file by PCL and load it. The OBJ file created by something like below will work 

``````
  pcl::TextureMesh mesh;
  pcl::PointCloud<pcl::PointNormal> xyz;

  pcl::PointNormal point1;
  pcl::PointNormal point2;
  pcl::PointNormal point3;
  point1.x = 0;
  point2.x = 1;
  point3.x = 0;
  point1.y = 0;
  point2.y = 0;
  point3.y = 1;
  point1.z = 2;
  point2.z = 2;
  point3.z = 2;
  xyz.push_back(point1);
  xyz.push_back(point2);
  xyz.push_back(point3);
  pcl::toPCLPointCloud2(xyz, mesh.cloud);

  std::vector<pcl::Vertices> mesh_poly;
  std::vector<Eigen::Vector2f, Eigen::aligned_allocator<Eigen::Vector2f> >
      mesh_tex;
  pcl::TexMaterial mesh_material;

  pcl::Vertices v;
  v.vertices.push_back(0);
  v.vertices.push_back(1);
  v.vertices.push_back(2);
  mesh_poly.push_back(v);

  Eigen::Vector2f tex1;
  Eigen::Vector2f tex2;
  Eigen::Vector2f tex3;
  tex1(0) = -1.0;
  tex1(1) = 0.0;
  tex2(0) = -1.0;
  tex2(1) = 1.0;
  tex3(0) = 2.0;
  tex3(1) = 0.0;

  mesh_tex.push_back(tex1);
  mesh_tex.push_back(tex2);
  mesh_tex.push_back(tex3);

  mesh_material.tex_file = "lena.png";
  mesh_material.tex_name = "material_0";

  mesh.tex_polygons.push_back(mesh_poly);
  mesh.tex_coordinates.push_back(mesh_tex);
  mesh.tex_materials.push_back(mesh_material);

  pcl::io::saveOBJFile("test.obj", mesh);
``````

**Comment by 761687049** [comment]
For the simplest example,  I display a triangle with texture,but i only still can see a white triangle,without color. my cube.png is a red picture. and i can see the color in the meshlab . below is some datas.
test.mtl:
#
# Wavefront material file
#
newmtl material_0
Ka 0 0 0
Kd 0 0 0
Ks 0 0 0
d 0
Ns 0
illum 0
map_Kd cube.png
###
test.obj:
####
# OBJ dataFile simple version. File name: test.obj
# Vertices: 3
# Faces: 1
# Material information:
mtllib test.mtl
####
# Vertices
v 0 0 2
v 1 0 2
v 0 1 2
# 3 vertices
vn 0 0 0
vn 0 0 0
vn 0 0 0
# 3 vertex textures in submesh 0
vt -1 0
vt -1 1
vt 2 0
# The material will be used for mesh 0
usemtl material_0
# Faces
f 1/1/1 2/2/2 3/3/3
# 1 faces in mesh 0
# End of File
and the .cpp is:
#include <pcl/common/common.h>
#include <pcl/io/obj_io.h>
#include <pcl/io/vtk_lib_io.h>
#include <pcl/visualization/pcl_visualizer.h>
int main()
{
	pcl::TextureMesh mesh7;
	pcl::io::loadOBJFile("test.obj", mesh7);
	pcl::visualization::PCLVisualizer viewer_pre7("PCL Viewer_pre7");
	viewer_pre7.addTextureMesh(mesh7, "texture",0);
		viewer_pre7.spin();
}
I don't know where is the problem . Thank you.

**Comment by jasjuang** [comment]
It works for me. Not sure what is the problem. Maybe you want to check your texture file path and do another git pull origin master to make sure you are using the most up to date PCL.

**Comment by taketwo** [comment]
Closing this in favor of #2252.
