### ISSUE TITLE
Error 'Posix_memalugn' was not declared

### ISSUE THREAD

**Issue by GoldGshok** [PointCloudLibrary/pcl#1595]
Hi! I want build pcl with mingw, when i linking in cmake i ger error:
`"D:\Program Files\Qt\Tools\mingw492_32\bin\g++.exe"     -DHAVE_POSIX_MEMALIGN   -o CMakeFiles\cmTC_b5d6f.dir\src.cxx.obj -c D:\Download\pcl-pcl-1.7.0\PCL\CMakeFiles\CMakeTmp\src.cxx

D:\Download\pcl-pcl-1.7.0\PCL\CMakeFiles\CMakeTmp\src.cxx: In function 'int main()':

D:\Download\pcl-pcl-1.7.0\PCL\CMakeFiles\CMakeTmp\src.cxx:6:47: error: 'posix_memalign' was not declared in this scope

           return posix_memalign (&mem, 16, 100);

                                               ^

mingw32-make.exe[1]: *** [CMakeFiles/cmTC_b5d6f.dir/src.cxx.obj] Error 1

CMakeFiles\cmTC_b5d6f.dir\build.make:64: recipe for target 'CMakeFiles/cmTC_b5d6f.dir/src.cxx.obj' failed

mingw32-make.exe[1]: Leaving directory 'D:/Download/pcl-pcl-1.7.0/PCL/CMakeFiles/CMakeTmp'

makefile:125: recipe for target 'cmTC_b5d6f/fast' failed

mingw32-make.exe: *** [cmTC_b5d6f/fast] Error 2

Return value: 1
Source file was:

        #include <stdlib.h>
        int main()
        {
          void* mem;
          return posix_memalign (&mem, 16, 100);
        }`
help solve this solve this?

**Comment by jspricke** [comment]
That's a mingw issue, see: http://stackoverflow.com/questions/10862121/undefined-reference-to-posix-memalign-using-mingw32 (and a lot of more results in any search engine ;) ).
