### ISSUE TITLE
pcl_io: cannot locate program entry point oniDeviceGetDepthColorSyncEnabled

### ISSUE THREAD

**Issue by yanzhicong** [PointCloudLibrary/pcl#1596]
Hi,

I just downloaded the newest pcl library yesterday and I compilied it successfully, but when i run the basic program pcl_xyz2pcd,  pcl_voxel_grid, it came out with the same error that it poped up a dialog shows 

"cannot locate program entry point oniDeviceGetDepthColorSyncEnabled in dynamic link library E:\lib\pcl-master\pcl-master\build\bin\pcl_io_release.dll"

I tried in release mode and debug mode, I used both VS2013 and VS2010, but in the end I got the same error;

**Comment by UnaNancyOwen** [comment]
I tried in my development environment, but that error did not occur. 
I was tested PCL master/HEAD with [this configuration](https://gist.github.com/UnaNancyOwen/c5250181b3985eeb5e79).

**Comment by yanzhicong** [comment]
@UnaNancyOwen Thanks! I'll have a try
