### ISSUE TITLE
PCL 1.7.2 build error (VTK 6.3 , QT 5.4.2 , windows 10)

### ISSUE THREAD

**Issue by NahomKidane** [PointCloudLibrary/pcl#1597]
Found unsuitable Qt version "5.4.2" from C:/Qt/5.4/msvc2012_opengl/bin/qmake.exe
CMake Error at cmake/pcl_find_qt5.cmake:72 (file):
  file failed to open for writing (Permission denied):

```
C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/UseQt4.cmake
```

Call Stack (most recent call first):
  CMakeLists.txt:343 (include)

**Comment by UnaNancyOwen** [comment]
Did you try the [PCL 1.8.0 RC2](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.0rc2) or [Git master/HEAD](https://github.com/PointCloudLibrary/pcl/tree/master)?
It has been fixed a lot of issues.
Please check whether the same issue occurs.

**Comment by taketwo** [comment]
Closing due to lack of feedback.
