### ISSUE TITLE
loadOBJFile() cannot load texture

### ISSUE THREAD

**Issue by junsmog** [PointCloudLibrary/pcl#1602]
I found that loadOBJFile() cannot load texture (Windows 8.1, VS2015, PCL 1.8.0).

Test code:

```
#include <pcl/common/common.h>
#include <pcl/io/obj_io.h>
#include <pcl/io/vtk_lib_io.h>
#include <pcl/visualization/pcl_visualizer.h>

int main()
{
pcl::TextureMesh mesh7;
pcl::io::loadOBJFile("3DScan_test3.obj", mesh7);
pcl::visualization::PCLVisualizer viewer_pre7("PCL Viewer_pre7");
viewer_pre7.addTextureMesh(mesh7, "texture", 0);
viewer_pre7.spin();

return 0;
}
```

Please find attached sample files. They can be loaded successfully in Meshlab.
[3DScan_test3.zip](https://github.com/PointCloudLibrary/pcl/files/254335/3DScan_test3.zip)

3DScan_test3.obj ( generated from Intel RealSense SDK )
3DScan_test3a.obj ( converted from Meshlab)

Results:
3DScan_test3.obj 
After loadOBJFile function, I got error message, "Debug Assertion Failed! Expression:vector subscript out of range"

3DScan_test3a.obj
addTextureMesh() said "No textures coordinates found!"

I announced this issue in PCL Users mailing list also. 
http://www.pcl-users.org/How-to-load-obj-with-texture-td4041450.html
In Mac platform,
3DScan_test3.obj : texture was loaded but texture mapping was messed up.
3DScan_test3a.obj : texture could not be loaded.
In Windows, even a simple cube obj texture could not be loaded.

**Comment by 761687049** [comment]
Is there a format of the using addtexturemesh? or a example?

**Comment by 761687049** [comment]
I see it. At least I want to see a little color, but only a white box, and the texture picture is red.when using cube.obj. How to trigger the display of texture？ http://www.pcl-users.org/How-to-load-obj-with-texture-td4041450.html. there is the cube.

**Comment by samarth-robo** [comment]
Have you tried using the `OBJReader` class for loading obj files with texture? 

```
#include <pcl/conversions.h>
#include <pcl/io/obj_io.h>
#include <pcl/visualization/pcl_visualizer.h>

using namespace pcl;

typedef PointCloud<PointXYZ> PC; 

int main(int argc, char **argv) {
  if(argc != 2) {
    cout << "Usage: ./show_obj_file <obj_filename>";
    return -1; 
  }

  // read polygon textured mesh
  PC::Ptr cloud(new PC);
  TextureMesh::Ptr mesh(new TextureMesh);
  OBJReader obj;
  if(obj.read(argv[1], *mesh) == -1) {
    cout << "Could not read " << argv[1];
    return -1; 
  }

  // convert polygon mesh to point cloud
  fromPCLPointCloud2(mesh->cloud, *cloud);
        
  boost::shared_ptr<visualization::PCLVisualizer> viewer(new visualization::PCLVisualizer);
  viewer->addTextureMesh(*mesh);
  while(!viewer->wasStopped()) {
    viewer->spinOnce(100);
    pcl_sleep(0.5);
  }
  return 0;
}
```
This shows me some texture, but the texture is not always right.

**Comment by 761687049** [comment]
Maybe the version I installed is not correct, lacking somethings. (32 Windows 7, VS2012, PCL 1.8.0)

**Comment by RFHO-BDSS** [comment]
Has this issue been resolved? 
I have been experiencing the same problems on a windows machine and haven't found a solution yet. 
I've opened a question [here](http://stackoverflow.com/questions/40344182/loading-textured-obj-with-pcl-c) with a link to some sample code that demonstrates the issue

**Comment by iamdpak** [comment]
Will this issue be worked upon any time soon? Is there an alternative to display mesh with texture stored in .mtl file? Is there any other file format that will work other than .obj file?

**Comment by taketwo** [comment]
Closing this in favor of #2252.
