### ISSUE TITLE
Compiled version of PCL (pcl-1.8.0rc2) Much Slower than Pre-built Binary (libpcl-1.7-all:all/trusty 1.7.1-3+trusty3 uptodate)

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1603]
I installed a binary package of PCL via apt-get and my MLS operations are able to run under 1 second. However, upon compiling PCL 1.8, the same file with MLS takes upwards of a minute with very poor performance, but the same output point cloud result. The same is true for other operations like Voxel grid etc.

Why might this be the case? Is there any particular optimization flag required to be set that the binary packages available has but I am required to set in the compiled version?

**Comment by soulslicer** [comment]
To test this, I attempted to run the following code, which does a very simple downsample operation.

http://robotica.unileon.es/~victorm/PCL_downsample.tar.gz

It takes 0.011 seconds on the binary libpcl, while it takes 0.3s on the compiled version

**Comment by andersgb1** [comment]
Could you post your CMakeCache.txt file?

**Comment by soulslicer** [comment]
http://dumptext.com/0WcpJ3X1

**Comment by soulslicer** [comment]
http://dumptext.com/tkkGGFsQ

This is a dump of my Downsample code cache, the fast version using the pre-build libpcl binary

**Comment by andersgb1** [comment]
It seems that you are running with build type set to empty (which usually means un-optimized code). Could you try recompiling both PCL and your code in Release mode? This is usually done by running CMake with **-DCMAKE_BUILD_TYPE=Release**

**Comment by soulslicer** [comment]
I tried that..still the same performance. 0.301 seconds

**Comment by soulslicer** [comment]
I've included a package of my testing code and testing cloud. Would really appreciate if you could try this out on your build of PCL

http://www.filedropper.com/pcldownsampletar

**Comment by soulslicer** [comment]
Wow..just wow. I just checked out the master version and compiled it and guess what. No more issues with performance. I have a feeling that something is broken in the pcl-1.8.0rc2 branch

**Comment by soulslicer** [comment]
Apologies it seems I have set the following

cmake -DCMAKE_BUILD_TYPE=None 

Didn't think the performance would drastically be reduced
