### ISSUE TITLE
3d_rec_framework is excluded from the build_unable to complete pcl installation

### ISSUE THREAD

**Issue by HarshadaModak** [PointCloudLibrary/pcl#1608]
Platform: Ubuntu 64 bit version 14.02

Steps followed to build pcl are as follows:
sudo apt-get update
sudo apt-get install git

git clone https://github.com/PointCloudLibrary/pcl.git pcl-trunk
ln -s pcl-trunk pcl

sudo apt-get install g++
sudo apt-get install cmake cmake-gui
sudo apt-get install doxygen  
sudo apt-get install mpi-default-dev openmpi-bin openmpi-common  
sudo apt-get install libflann1 libflann-dev
sudo apt-get install libeigen3-dev
sudo apt-get install libboost-all-dev
sudo apt-get install libvtk5.8-qt4 libvtk5.8 libvtk5-dev
sudo apt-get install libqhull*
sudo apt-get install libusb-dev
sudo apt-get install libgtest-dev
sudo apt-get install git-core freeglut3-dev pkg-config
sudo apt-get install build-essential libxmu-dev libxi-dev 
sudo apt-get install libusb-1.0-0-dev graphviz mono-complete
sudo apt-get install qt-sdk openjdk-7-jdk openjdk-7-jre

To install OpenNI, do:

mkdir ~/kinect
cd ~/kinect
git clone https://github.com/OpenNI/OpenNI.git
And change the branch to unstable:

cd OpenNI
git checkout unstable
Run these lines to install OpenNI:

cd Platform/Linux/CreateRedist/
chmod +x RedistMaker
./RedistMaker
cd ../Redist/OpenNI-Bin-Dev-Linux-x64-v1.5.8.5
sudo ./install.sh
Now download another repository to the kinect folder:

cd ~/kinect/
git clone https://github.com/ph4m/SensorKinect.git
And change the branch to unstable

cd SensorKinect
git checkout unstable
And run these lines to install SensorKinect:

cd Platform/Linux/CreateRedist/
chmod +x RedistMaker
./RedistMaker
cd ../Redist/Sensor-Bin-Linux-x64-v5.1.2.1/
chmod +x install.sh
sudo ./install.sh

mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON ..
sudo make install

when checked cmake ..

output for building apps is as follows:
--   apps
       not building: 
       |_ optronic_viewer: VTK was not built with Qt support.
       |_ 3d_rec_framework: No reason
       |_ cloud_composer: Cloud composer requires QVTK
       |_ modeler: VTK was not built with Qt support.
       |_ in_hand_scanner: No reason
       |_ point_cloud_editor: No reason

How to build 3d_rec_framework?

Regards,
Harshada

**Comment by SergioRAgostinho** [comment]
This is not really a bug, as the app comes disabled by default. You need to specify manually to build it. Pass the ```-DBUILD_apps_3d_rec_framework=ON``` additional option into your cmake command. 

This is good to close.

**Comment by HarshadaModak** [comment]
Thanks for your help.
Closing the issue.
