### ISSUE TITLE
setCameraParameters() window size math

### ISSUE THREAD

**Issue by samarth-robo** [PointCloudLibrary/pcl#1610]
This issue has been posted to the mailing list too: http://www.pcl-users.org/PCL-Visualizer-setCameraParameters-math-td4041757.html

The window size is calculated from the intrinsics matrix at https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/interactor_style.cpp#L230 as:
`// Get the width and height of the image - assume the calibrated centers are at the center of the image`
`Eigen::Vector2i window_size;`
`window_size[0] = static_cast<int> (intrinsics (0, 2));`
`window_size[1] = static_cast<int> (intrinsics (1, 2));`

Since the 'calibrated centers are at the center of the image', this seems wrong to me. It seems to me that the window size must be 2 * camera center.

**Comment by SergioRAgostinho** [comment]
Makes sense. Come up with simple test case so that we can verify it quickly and submit a pull request please.

**Comment by taketwo** [comment]
Can we close this now?
