### ISSUE TITLE
getMaxSegment could be optimized

### ISSUE THREAD

**Issue by antonxy** [PointCloudLibrary/pcl#1613]
https://github.com/PointCloudLibrary/pcl/blob/86f1a19/common/include/pcl/common/distances.h#L100
For PointXYZ we could speed up the function about 5-10 times by calculating the distance directly like this
```
float dist = (cloud.points[i].x - cloud.points[j].x) * (cloud.points[i].x - cloud.points[j].x)
           + (cloud.points[i].y - cloud.points[j].y) * (cloud.points[i].y - cloud.points[j].y)
           + (cloud.points[i].z - cloud.points[j].z) * (cloud.points[i].z - cloud.points[j].z);
```
Our point cloud size is about 1000 points.

**Comment by jspricke** [comment]
Interesting, can you send a pull request with the changes?
Also, can you provide more information who you tested it? (hardware, OS, compiler flags, exact measuerments...).

**Comment by antonxy** [comment]
We tested it on the laptop of a colleague yesterday on Ubuntu 14.04 in Debug mode.

On my laptop (also Ubuntu 14.04, Intel i5 2.5 GHz) in cmake Debug mode it takes about 0.073 secs with the optimization vs 1.02 without.
In Release mode and DebWithRelInfo both take about 0.008 secs.
We should have tried that right away.

So it probably makes no sense to optimize that as the optimization would be specific to PointXYZ.
