### ISSUE TITLE
linking error with static library in windows

### ISSUE THREAD

**Issue by RobertSpir** [PointCloudLibrary/pcl#1617]
I built pcl as static library using visual studio, everything works ok, only problem is when I try to compile program which loads ply file using pcl::io::loadPLYFile, then during compilation I get linking error
`pcl_io_release.lib(ply_io.obj) : error LNK2019: unresolved external symbol "public: bool __cdecl pcl::io::ply::ply_parser::parse(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parse@ply_parser@ply@io@pcl@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "private: bool __cdecl pcl::PLYReader::parse(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parse@PLYReader@pcl@@AEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)`
When I build shared libraries, everything works, I'm using visual studio 2015 update 2

**Comment by monticle** [comment]
Hi RobertSpir,

Have you fix this problem?
I am facing the same problem with you.
Error LNK2019 occurred when I use PCL1.8.0 as static library.

**Comment by monticle** [comment]
found the symbol in pcl_io_ply.lib, solve the problem by add the lib to link libs.

**Comment by kunaltyagi** [comment]
I'm hoping the linker error went away?

**Comment by vanloctc** [comment]
Has the problem been resolved yet?

**Comment by kunaltyagi** [comment]
This isn't an issue on our CI. The author didn't give more information.

**Comment by RobertSpir** [comment]
so, it only took 4 years to get to this issue, congratulations. I haven't been using PCL for last 3 years, so I have no idea in what state it is now.

**Comment by vanloctc** [comment]
> This isn't an issue on our CI. The author didn't give more information.

Using " pcl_io_ply.lib " in Linker will solved the issue
