### ISSUE TITLE
PCL1.8.0 VS2013  openni2   gpu_kinfu build?

### ISSUE THREAD

**Issue by wangsen1312** [PointCloudLibrary/pcl#1619]
First: 
gpu_kinfu:OpenNI was not found or was disabled by the user.
I change the CMakelists WITH_OPENNI to WITH_OPENNI2
And Kinfu_app.cpp changed

But it change to gpu_kinfu: Disabled manually. still not compile!

Anyone have some suggestion? Thanks!

**Comment by SergioRAgostinho** [comment]
Use the mailing list for these types of questions. You need to manually enable the compile options passing the following arguments ```-DBUILD_CUDA:BOOL=ON -DBUILD_GPU:BOOL=ON -DBUILD_gpu_kinfu:BOOL=ON ```. More importantly, kinfu is going to be removed from PCL. Use [this](https://github.com/Nerei/kinfu_remake) instead. 

Please close the issue.

**Comment by wangsen1312** [comment]
@SergioRAgostinho    Thank you very much. I will close the issue
