### ISSUE TITLE
pcl_mesh2pcd need help plz

### ISSUE THREAD

**Issue by nomi321** [PointCloudLibrary/pcl#1620]
pcl_mesh2pcd test1.ply test.pcd

Convert a CAD model to a point cloud using ray tracing operations. For more information, use: pcl_mesh2pcd -h
Segmentation fault (core dumped)

i get this error while execute the above command .

can anybody help what is going wrong

**Comment by VictorLamoine** [comment]
What version of PCL are you using?

Please try the latest version of the code:
https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh2pcd.cpp

You also might be interested in:
https://github.com/PointCloudLibrary/pcl/blob/master/io/tools/converter.cpp

**Comment by nomi321** [comment]
I am using Ros indigo and i think PCL version is 1.2.7.

**Comment by nomi321** [comment]
How can i update this version to latest version. I tried to install pcl using 
sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl
sudo apt-get update
sudo apt-get install libpcl-all

so now i have 2 pcl i.e standalone 1.7.2 and the one with ROS but still I am facing the issue

**Comment by nomi321** [comment]
@VictorLamoine i even tried this 
noaman@Rime:~/Desktop/model$ 

Convert a PLY file to PCD format. For more information, use: pcl_ply2pcd -h
PCD output format: binary
[pcl::PLYReader] cone_blender.ply:14: property 'int32 flags' of element 'face' is not handled
Segmentation fault (core dumped).

Please guide me so that i can get rid of this. I shall b very thankful to you.

**Comment by nomi321** [comment]
@VictorLamoine sir i was despratly waiting for your reply. please reply. i shall be thankful to you. Moreover i also show you the contents of my ply file. is there something with the file too ?

ply
format ascii 1.0
comment Created by Blender 2.69 (sub 0) - www.blender.org, source file: ''
element vertex 60
property float x
property float y
property float z
property float nx
property float ny
property float nz
element face 26
property list uchar uint vertex_indices
end_header
0.000000 1.000000 -2.500000 0.309017 0.951056 0.000000
0.000000 1.000000 2.500000 0.309017 0.951056 0.000000
0.587785 0.809017 2.500000 0.309017 0.951056 0.000000
0.587785 0.809017 -2.500000 0.309017 0.951056 0.000000
0.587785 0.809017 -2.500000 0.809017 0.587785 0.000000
0.587785 0.809017 2.500000 0.809017 0.587785 0.000000
0.951057 0.309017 2.500000 0.809017 0.587785 0.000000
0.951057 0.309017 -2.500000 0.809017 0.587785 0.000000
0.951057 0.309017 -2.500000 1.000000 -0.000000 0.000000
0.951057 0.309017 2.500000 1.000000 -0.000000 0.000000
0.951056 -0.309017 2.500000 1.000000 -0.000000 0.000000
0.951056 -0.309017 -2.500000 1.000000 -0.000000 0.000000
0.951056 -0.309017 -2.500000 0.809017 -0.587785 0.000000
0.951056 -0.309017 2.500000 0.809017 -0.587785 0.000000
0.587785 -0.809017 2.500000 0.809017 -0.587785 0.000000
0.587785 -0.809017 -2.500000 0.809017 -0.587785 0.000000
0.587785 -0.809017 -2.500000 0.309017 -0.951056 0.000000
0.587785 -0.809017 2.500000 0.309017 -0.951056 0.000000
-0.000000 -1.000000 2.500000 0.309017 -0.951056 0.000000
-0.000000 -1.000000 -2.500000 0.309017 -0.951056 0.000000
-0.000000 -1.000000 -2.500000 -0.309017 -0.951056 0.000000
-0.000000 -1.000000 2.500000 -0.309017 -0.951056 0.000000
-0.587785 -0.809017 2.500000 -0.309017 -0.951056 0.000000
-0.587785 -0.809017 -2.500000 -0.309017 -0.951056 0.000000
-0.587785 -0.809017 -2.500000 -0.809017 -0.587785 0.000000
-0.587785 -0.809017 2.500000 -0.809017 -0.587785 0.000000
-0.951056 -0.309017 2.500000 -0.809017 -0.587785 0.000000
-0.951056 -0.309017 -2.500000 -0.809017 -0.587785 0.000000
-0.951056 -0.309017 -2.500000 -1.000000 -0.000000 0.000000
-0.951056 -0.309017 2.500000 -1.000000 -0.000000 0.000000
-0.951056 0.309017 2.500000 -1.000000 -0.000000 0.000000
-0.951056 0.309017 -2.500000 -1.000000 -0.000000 0.000000
0.587785 0.809017 2.500000 -0.000000 0.000000 1.000000
0.000000 1.000000 2.500000 -0.000000 0.000000 1.000000
-0.587785 0.809017 2.500000 -0.000000 0.000000 1.000000
-0.951056 0.309017 2.500000 -0.000000 0.000000 1.000000
0.951057 0.309017 2.500000 0.000000 -0.000000 1.000000
-0.951056 -0.309017 2.500000 0.000000 -0.000000 1.000000
0.951056 -0.309017 2.500000 0.000000 0.000000 1.000000
0.587785 -0.809017 2.500000 0.000000 0.000000 1.000000
-0.587785 -0.809017 2.500000 0.000000 0.000000 1.000000
-0.000000 -1.000000 2.500000 0.000000 0.000000 1.000000
0.000000 1.000000 2.500000 -0.309017 0.951057 0.000000
0.000000 1.000000 -2.500000 -0.309017 0.951057 0.000000
-0.587785 0.809017 -2.500000 -0.309017 0.951057 0.000000
-0.587785 0.809017 2.500000 -0.309017 0.951057 0.000000
-0.951056 0.309017 -2.500000 -0.809017 0.587785 0.000000
-0.951056 0.309017 2.500000 -0.809017 0.587785 0.000000
-0.587785 0.809017 2.500000 -0.809017 0.587785 0.000000
-0.587785 0.809017 -2.500000 -0.809017 0.587785 0.000000
0.000000 1.000000 -2.500000 0.000000 0.000000 -1.000000
0.587785 0.809017 -2.500000 0.000000 0.000000 -1.000000
-0.587785 0.809017 -2.500000 0.000000 0.000000 -1.000000
-0.951056 0.309017 -2.500000 0.000000 -0.000000 -1.000000
0.951057 0.309017 -2.500000 0.000000 0.000000 -1.000000
-0.951056 -0.309017 -2.500000 0.000000 0.000000 -1.000000
0.951056 -0.309017 -2.500000 0.000000 0.000000 -1.000000
0.587785 -0.809017 -2.500000 0.000000 0.000000 -1.000000
-0.587785 -0.809017 -2.500000 0.000000 0.000000 -1.000000
-0.000000 -1.000000 -2.500000 0.000000 0.000000 -1.000000
4 0 1 2 3
4 4 5 6 7
4 8 9 10 11
4 12 13 14 15
4 16 17 18 19
4 20 21 22 23
4 24 25 26 27
4 28 29 30 31
3 32 33 34
3 32 34 35
3 32 35 36
3 35 37 36
3 37 38 36
3 37 39 38
3 37 40 39
3 40 41 39
4 42 43 44 45
4 46 47 48 49
3 50 51 52
3 51 53 52
3 51 54 53
3 54 55 53
3 54 56 55
3 56 57 55
3 57 58 55
3 57 59 58

**Comment by nomi321** [comment]
and i exported .obj too and it was converted successfuly using obj2pcd. however it is showing only the points of vertices. i.e. only 20 points against the file ...  i m attaching converted pcd file of a cylinder.

![converted_pcd](https://cloud.githubusercontent.com/assets/18333073/15806621/9da24d68-2b60-11e6-9c46-94bc5308fa99.png)

please helppp ....

**Comment by SergioRAgostinho** [comment]
A bunch of your points seem to have the same vertex coordinates, but different normals. So the points are actually there, just perfectly overlapped. 

This doesn't look like a PCL bug. Use the mailing list for further questions.

**Comment by nomi321** [comment]
@ mschoeler please look into this problem and let me know ...  i shall be thankful to you...

**Comment by nomi321** [comment]
@SergioRAgostinho, @VictorLamoine  if nothing is wrong then why i am not able to view it completly. and also when i try to view it using cloudviewer i get this error

Failed to find match for field 'rgb'.
Loaded 60
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!

please guide.... thanks
