### ISSUE TITLE
Segmentation Fault, PCD from Intel RealSense pcl::RangeImage::getImagePoint

### ISSUE THREAD

**Issue by deebuls** [PointCloudLibrary/pcl#1622]
While running the example code for Border Detection http://pointclouds.org/documentation/tutorials/range_image_border_extraction.php#range-image-border-extraction

The code runs for other pcd images but gives segfault for pcd from Intel Realsense camera.
Please find the used pcd file https://drive.google.com/open?id=0B27qL_QI6Li_VG01Y0dVaUhaV1U

gdb output

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff799d8b4 in pcl::RangeImage::getImagePoint(Eigen::Matrix<float, 3,
(gdb) bt
#0  0x00007ffff799d8b4 in pcl::RangeImage::getImagePoint(Eigen::Matrix<float
#1  0x000000000046a9a4 in void pcl::RangeImage::doZBuffer<pcl::PointCloud<pc
    ()
#2  0x000000000046745f in void pcl::RangeImage::createFromPointCloud<pcl::Poigen::Transform<float, 3, 2, 0> const&, pcl::RangeImage::CoordinateFrame, fl
#3  0x0000000000463e3a in void pcl::RangeImage::createFromPointCloud<pcl::Poransform<float, 3, 2, 0> const&, pcl::RangeImage::CoordinateFrame, float, fl
#4  0x000000000045dce7 in main ()
```

System : Ubuntu 14.04

**Comment by SergioRAgostinho** [comment]
The link to the PCD file is broken.

**Comment by deebuls** [comment]
Please find the pcd file here : 
https://drive.google.com/open?id=0B27qL_QI6Li_VG01Y0dVaUhaV1U

**Comment by mvieth** [comment]
Fixed by https://github.com/PointCloudLibrary/pcl/pull/5149
