### ISSUE TITLE
SHOT doesnot support PointNormal on 1.8?

### ISSUE THREAD

**Issue by MUSAZOU** [PointCloudLibrary/pcl#1626]
pcl::PointNormal contains xyz and normal data, so claims like below are supposed to work fine.  
`pcl::FPFHEstimation<pcl::PointNormal, pcl::PointNormal, pcl::FPFHSignature33> est
pcl::SpinImageEstimation<pcl::PointNormal, pcl::PointNormal, pcl::Histogram<153>> est;
pcl::SHOTEstimation<pcl::PointNormal, pcl::PointNormal, pcl::SHOT352> est;`

however, **FPFH** and **SI** **works fine**. for **SHOT**, it **fails** on branch **1.8.0rc2** or **master**, while works fine on 1.7.2.(All libraries compiled from source.)
Could any one test it to let me know it is my compile problem or a bug on pcl-1.8?
Thanks.

**Comment by andersgb1** [comment]
What fails? Compilation, running it or something else? What is your test case?

**Comment by MUSAZOU** [comment]
@andersgb1 
it fails on the compilation stage. I'm running win7 64bit with VS2013.
I've tried with an empty project, in which only FPFH&SI&SHOT descriptors were declared. it compiled fine on 1.7.2 while failed on 1.8.0 or master branch because of SHOT, but I can't see why..

int main()
{

	pcl::FPFHEstimation<pcl::PointNormal, pcl::PointNormal, pcl::FPFHSignature33> est1;
	pcl::SpinImageEstimation<pcl::PointNormal, pcl::PointNormal, pcl::Histogram<153>> est2; 

    //the next declaration fails on 1.8.0rc2 or master branch
    //pcl::SHOTEstimation<pcl::PointNormal, pcl::PointNormal, pcl::SHOT352> est3;
	return 0;
}

**Comment by andersgb1** [comment]
Could you send your CMakeLists.txt file, your full source (with includes) and your CMakeCache.txt file, and finally the compilation output error?

**Comment by UnaNancyOwen** [comment]
Please re-try after add the following code.

```cpp
#define PCL_NO_PRECOMPILE
```

**Comment by SergioRAgostinho** [comment]
You will need to need recompile pcl and add the PointNormal type to the first entry of the triplet defined [here](https://github.com/PointCloudLibrary/pcl/blob/master/features/src/shot.cpp#L48). Probably also on SHOTEstimationBase in the line above. 

Another option is to remove the definition ```PCL_ONLY_CORE_POINT_TYPES``` and let it compile for all XYZ and Normal points types. 

Nevertheless this is not a bug, it's just to avoid ridiculous time and memory requirements for compiling PCL. For more question on this please use the mailing list.
