### ISSUE TITLE
equations behind Models 

### ISSUE THREAD

**Issue by ObadaM** [PointCloudLibrary/pcl#1628]
Hi all, 

Is there any documentation or tutorial for the theoretical background of the models implementations?
For cone, sphere, cylinder and plane. 

I could not understand how the models are computed for each one.

Thanks!

**Comment by SergioRAgostinho** [comment]
Normally the theoretical primer and tutorial, if it exists, is provided on the [tutorials page](http://pointclouds.org/documentation/tutorials/). If it's not there it's unlikely to exist anywhere else in the [repo](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content) and website. Nevertheless, if you feel like writing a tutorial and explanations based on your findings, we will be happy to include it :)

Last comment, this is a bug tracker, so in the future use our mailing list pcl-users@pointclouds.org for these types of questions.
