### ISSUE TITLE
operator () hdl_grabber??

### ISSUE THREAD

**Issue by selmagoga** [PointCloudLibrary/pcl#1632]
Hello all!
Can one please tell me where is operator() declared? VS says it is not overwritten. What does it do actually?
It appears in the hdl_grabber.cpp:
 voidpcl::HDLGrabber::fireCurrentSweep ()
{
  if (sweep_xyz_signal_ != NULL && sweep_xyz_signal_->num_slots () > 0)
    sweep_xyz_signal_->**operator()** (current_sweep_xyz_);

  if (sweep_xyzrgb_signal_ != NULL && sweep_xyzrgb_signal_->num_slots () > 0)
    sweep_xyzrgb_signal_->**operator()** (current_sweep_xyzrgb_);

  if (sweep_xyzi_signal_ != NULL && sweep_xyzi_signal_->num_slots () > 0)
    sweep_xyzi_signal_->**operator()** (current_sweep_xyzi_);
}

**Comment by selmagoga** [comment]
I figured it out. Thank's!

**Comment by SergioRAgostinho** [comment]
@selmagoga This is a bug tracker. Please use the mailing list pcl-users@pointclouds.org for this type of questions.
