### ISSUE TITLE
pcl_visualization occur compile error on MSVC

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#1634]
The pcl_visualization occur compile error c2440 on msvc.

```
Error	C2440	'static_cast': cannot convert from 'double' to 'pcl::visualization::LookUpTableRepresentationProperties'	pcl_visualization	C:\pcl-1.8.0\visualization\src\pcl_visualizer.cpp	1495	
Error	C2440	'static_cast': cannot convert from 'double' to 'pcl::visualization::LookUpTableRepresentationProperties'	pcl_visualization	C:\pcl-1.8.0\visualization\src\pcl_visualizer.cpp	1741	
```

This error occurs because that can not directly cast to enum type from double type in msvc.
It must explicitly cast to int type from double type before cast to enum type.
(It seems to be implicitly cast to int type from double type in gcc. But, It seems not allowed in msvc.)

**Comment by SergioRAgostinho** [comment]
Fix got merged
