### ISSUE TITLE
Defining new octree container types

### ISSUE THREAD

**Issue by ozaslan** [PointCloudLibrary/pcl#1636]
Hi,

I want to define an application specific octree container type and use it as my leaf container. As I could follow from your code, you precompile the code due to speed up the end user compile time. Because of this we can only change the point type but can modify neither the leaf nor the branch type. For example OctreePointCloudSearch cannot be declared with a OctreeContainerPointIndex leaf container (this causes linking error). I wonder whether you can offer a method to work around this problem.

Thanks

**Comment by jspricke** [comment]
Hi, this is a issue tracker, please use our mailing list for questions: www.pcl-users.org.
