### ISSUE TITLE
Point cloud ICP always has a score of 0 even if Iḿ using the same point clouds

### ISSUE THREAD

**Issue by AndreAhmed** [PointCloudLibrary/pcl#1641]
You can download a sample of point cloud here
http://www.mediafire.com/download/eftgkuepz3pdaz2/dm2hm_left43.pcd

    // All the objects needed
    pcl::PCDReader reader;
    pcl::PassThrough<PointT> pass;
    pcl::NormalEstimation<PointT, pcl::Normal> ne;
    pcl::SACSegmentationFromNormals<PointT, pcl::Normal> seg;
    pcl::PCDWriter writer;
    pcl::ExtractIndices<PointT> extract;
    pcl::ExtractIndices<pcl::Normal> extract_normals;
    pcl::search::KdTree<PointT>::Ptr tree (new pcl::search::KdTree<PointT> ());

    // Datasets
    pcl::PointCloud<PointT>::Ptr input_cloud (new pcl::PointCloud<PointT>);
    pcl::PointCloud<PointT>::Ptr cloud_filtered (new pcl::PointCloud<PointT>),
            cloud_projected(new pcl::PointCloud<PointT>);
    pcl::PointCloud<pcl::Normal>::Ptr cloud_normals (new pcl::PointCloud<pcl::Normal>);
    pcl::ModelCoefficients::Ptr coefficients_plane (new pcl::ModelCoefficients), coefficients_cylinder (new pcl::ModelCoefficients);
    pcl::PointIndices::Ptr inliers_plane (new pcl::PointIndices), inliers_cylinder (new pcl::PointIndices);

    pcl::PointCloud<PointT>::Ptr target_cloud (new pcl::PointCloud<PointT>);

    reader.read ("match.pcd", *target_cloud);
    // Read in the cloud data
    reader.read ("dm2hm_left25.pcd", *input_cloud);
    std::cerr << "PointCloud has: " << input_cloud->points.size () << " data points." << std::endl;

    pass.setInputCloud (input_cloud);
    pass.setFilterFieldName ("z");
    pass.setFilterLimits (-600,600);
    pass.filter (*cloud_filtered);
    std::cerr << "PointCloud after filtering has: " << cloud_filtered->points.size () << " data points." << std::endl;
    writer.write ("table_scene_mug_stereo_textured_filtered.pcd", *cloud_filtered, false);

    // Estimate point normals
    ne.setSearchMethod (tree);
    ne.setInputCloud (cloud_filtered);
    ne.setKSearch (50);
    ne.compute (*cloud_normals);

    // Create the segmentation object for the planar model and  set all the parameters
    seg.setOptimizeCoefficients (true);
    seg.setModelType (pcl::SACMODEL_NORMAL_PLANE);
    seg.setNormalDistanceWeight (0.1);
    seg.setMethodType (pcl::SAC_RANSAC);
    seg.setMaxIterations (100);
    seg.setDistanceThreshold (11);
    seg.setInputCloud (cloud_filtered);
    seg.setInputNormals (cloud_normals);
    seg.setEpsAngle(0.05320);
    Eigen::Vector3f YAxis(0,1,0);
    seg.setAxis(YAxis);
    // Obtain the plane inliers and coefficients
    seg.segment (*inliers_plane, *coefficients_plane);
    std::cerr << "Plane coefficients: " << *coefficients_plane << std::endl;

    // Extract the planar inliers from the input cloud
    extract.setInputCloud (cloud_filtered);
    extract.setIndices (inliers_plane);
    extract.setNegative (false);

    // Write the planar inliers to disk
    pcl::PointCloud<PointT>::Ptr cloud_plane (new pcl::PointCloud<PointT> ());
    extract.filter (*cloud_plane);
    std::cerr << "PointCloud representing the planar component: " << cloud_plane->points.size () << " data points." << std::endl;
    pcl::ProjectInliers<pcl::PointXYZ> proj;
    proj.setModelType (pcl::SACMODEL_PLANE);
    proj.setIndices (inliers_plane);
    proj.setInputCloud (cloud_filtered);
    proj.setModelCoefficients (coefficients_plane);
    proj.filter (*cloud_projected);
    std::cerr << "PointCloud after projection has: "
              << cloud_projected->points.size () << " data points." << std::endl;

    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_hull (new pcl::PointCloud<pcl::PointXYZ>);
    pcl::ConvexHull<pcl::PointXYZ> chull;
    chull.setInputCloud (cloud_projected);
    chull.setComputeAreaVolume(true);
    chull.reconstruct (*cloud_hull);

    std::cerr <<"area of convex hull: "<< chull.getTotalArea()<<std::endl;
    std::cerr << "Convex hull has: " << cloud_hull->points.size () << " data points." << std::endl;

    writer.write ("table_scene_mug_stereo_textured_hull.pcd", *cloud_hull, false);

    pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointXYZ> icp;
    icp.setInputCloud(cloud_filtered);
    icp.setInputTarget(cloud_filtered);
    icp.setEuclideanFitnessEpsilon(-1.797e+5);
    icp.setMaximumIterations(4000);
    icp.setRANSACIterations(2000);
    icp.setTransformationEpsilon(1e-3);

    pcl::PointCloud<pcl::PointXYZ> Final;
    icp.align(Final);
    std::cout << "has converged:" << icp.hasConverged() << " score: " <<
    icp.getFitnessScore() << std::endl;
    std::cout << icp.getFinalTransformation() << std::endl;

**Comment by jspricke** [comment]
Not a bug report.
