### ISSUE TITLE
FPCSInitialAlignment core dump data is not aligned

### ISSUE THREAD

**Issue by xxsong5** [PointCloudLibrary/pcl#1643]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

## Context

#0  0x00007f7d0fa1ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f7d0fa1e028 in __GI_abort () at abort.c:89
#2  0x00007f7d0fa13bf6 in __assert_fail_base (fmt=0x7f7d0fb643b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7f7d140e8428 "(!(internal::traits<Derived>::Flags&AlignedBit) || ((size_t(m_data) % 16) == 0)) && \"data is not aligned\"", 
    file=file@entry=0x7f7d140e83f8 "/usr/include/eigen3/Eigen/src/Core/MapBase.h", line=line@entry=160, 
    function=function@entry=0x7f7d1415c140 "void Eigen::MapBase<Derived, 0>::checkSanity() const [with Derived = Eigen::Map<const Eigen::Array<float, 4, 1>, 1>]") at assert.c:92
#3  0x00007f7d0fa13ca2 in __GI___assert_fail (
    assertion=0x7f7d140e8428 "(!(internal::traits<Derived>::Flags&AlignedBit) || ((size_t(m_data) % 16) == 0)) && \"data is not aligned\"", file=0x7f7d140e83f8 "/usr/include/eigen3/Eigen/src/Core/MapBase.h", line=160, 
    function=0x7f7d1415c140 "void Eigen::MapBase<Derived, 0>::checkSanity() const [with Derived = Eigen::Map<const Eigen::Array<float, 4, 1>, 1>]") at assert.c:101
#4  0x00007f7d13ff7a87 in pcl::SampleConsensusModelPlane<pcl::PointXYZ>::computeModelCoefficients(std::vector<int, std::allocator<int> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1>&) ()
   from /usr/lib/libpcl_sample_consensus.so.1.7
#5  0x00000000004419f7 in pcl::registration::FPCSInitialAlignment<pcl::PointXYZ, pcl::PointXYZ, pcl::Normal, float>::selectBase(std::vector<int, std::allocator<int> >&, float (&) [2]) ()
#6  0x00000000004421aa in pcl::registration::FPCSInitialAlignment<pcl::PointXYZ, pcl::PointXYZ, pcl::Normal, float>::computeTransformation(pcl::PointCloud<pcl::PointXYZ>&, Eigen::Matrix<float, 4, 4, 0, 4, 4> const&) ()
#7  0x00000000004359f4 in pcl::Registration<pcl::PointXYZ, pcl::PointXYZ, float>::align(pcl::PointCloud<pcl::PointXYZ>&) ()

**Comment by SergioRAgostinho** [comment]
Fill-in the Environment information (OS, compiler and PCL version) and a code snippet to reproduce.

**Comment by SergioRAgostinho** [comment]
With no feedback it will be hard to address this. Nevertheless see if #1665 solved your issue. If not reopen this.
