### ISSUE TITLE
PCL GPU Segmentation only supports XYZ no XYZRGB?

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1645]
https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/segmentation/src/seg.cpp

The example above works fine with XYZ point clouds, but throws a compile error when I use a XYZRGB type. 

`/home/robotserver/catkin_ac2/src/perception/cloud_fusion/src/CloudFusion.cpp:122: error: no matching function for call to 'pcl::gpu::DeviceArray<pcl::PointXYZ>::upload(std::vector<pcl::PointXYZI, Eigen::aligned_allocator<pcl::PointXYZI> >&)'`

https://github.com/PointCloudLibrary/pcl/blob/master/gpu/octree/include/pcl/gpu/octree/octree.hpp

This is because of these two lines:

```

            /** \brief Point typwe supported */
            typedef pcl::PointXYZ PointType;

            /** \brief Point cloud supported */
            typedef DeviceArray<PointType> PointCloud;
```

Seems like only XYZ is supported at this point. Is this the case? Any plans to support other formats?

**Comment by kyesh** [comment]
Dealing with the same thing. I'd be happy if there was a clear way to convert from XYZRGB to purely XYZ in the interim.
