### ISSUE TITLE
aligned_malloc() calls unaligned std::malloc()

### ISSUE THREAD

**Issue by Chungzuwalla** [PointCloudLibrary/pcl#1651]
Due to a bug in pcl_macros.h, aligned_malloc() will always call (the possibly unaligned) std::malloc(), regardless of the platform or configuration flags.  On 32-bit Windows at least, this will cause a crash.
[offending code](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L376)
MALLOC_ALIGNED is #defined as 0 or 1 depending on whether std::malloc() is believed to be aligned.  However, the implementation of aligned_malloc() only tests whether MALLOC_ALIGNED is #defined, which it always is.  Therefore, std::malloc() is always used, even when MALLOC_ALIGNED is 0.

## Your Environment

* Operating System and version: Windows 7 x64
* Compiler: Visual C++ 2015
* PCL Version: 1.8

## Expected Behavior
aligned_malloc() returns memory with 16-byte alignment on Win32.

## Current Behavior
aligned_malloc() returns memory with 8-byte alignment on Win32, causing a crash.

## Possible Solution
#define MALLOC_ALIGNED only when std::malloc() is believed to be aligned.
i.e.:

`#if defined(__APPLE__) || defined(_WIN64) || GLIBC_MALLOC_ALIGNED || FREEBSD_MALLOC_ALIGNED`
`#define MALLOC_ALIGNED`
`#endif`

**Comment by stefanbuettner** [comment]
Hi Chungzuwalla,

looks like a bug indeed. Thanks for the notification. I'll file a fix.

Cheers,
Stefan
