### ISSUE TITLE
Endless loop in pcl::compute3DCentroid()

### ISSUE THREAD

**Issue by Chungzuwalla** [PointCloudLibrary/pcl#1658]
The function
`pcl::compute3DCentroid (ConstCloudIterator<PointT> &cloud_iterator,
                        Eigen::Matrix<Scalar, 4, 1> &centroid)` [here](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/impl/centroid.hpp#L66) enters an endless loop if a non-finite point is encountered, because the `continue` bypasses the increment of the iterator:

      while (cloud_iterator.isValid ())
      {
        // Check if the point is invalid
        if (!pcl_isfinite (cloud_iterator->x) ||
            !pcl_isfinite (cloud_iterator->y) ||
            !pcl_isfinite (cloud_iterator->z))
          continue;
        ...
        ++cloud_iterator;
      }

## Your Environment

* Operating System and version: Windows 7 x64
* Compiler: Visual C++ 2015
* PCL Version: 1.8

## Expected Behavior
The function should always terminate

## Current Behavior
The function loops endlessly if a non-finite point is encountered

## Possible Solution
      while (cloud_iterator.isValid ())
      {
        // Check if the point is invalid
        if (pcl_isfinite (cloud_iterator->x) &&
            pcl_isfinite (cloud_iterator->y) &&
            pcl_isfinite (cloud_iterator->z))
        {
          centroid[0] += cloud_iterator->x;
          centroid[1] += cloud_iterator->y;
          centroid[2] += cloud_iterator->z;
          ++cp;
        }
        ++cloud_iterator;
      }

**Comment by taketwo** [comment]
Nice find, please send a pull request. By the way, there is as `pcl::isFinite()` function to test all three coordinates with a single call.
