### ISSUE TITLE
ply generated by pcl showed wrong in meshlab.

### ISSUE THREAD

**Issue by HIT-LWQ** [PointCloudLibrary/pcl#1659]
these days, I find a problem. the ply file generated by pcl showed right in pcl, but showed wrong in meshlab. 
here is the code:

``` cpp
pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> n;
    pcl::PointCloud<pcl::Normal>::Ptr normals(new pcl::PointCloud<pcl::Normal>);
    pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
    tree->setInputCloud(cloud);
    n.setInputCloud(cloud);
    n.setSearchMethod(tree);
    n.setKSearch(20);
    cout << "Computing normals...\n";
    n.compute(*normals); 


    pcl::PointCloud<pcl::PointNormal>::Ptr cloud_with_normals(new pcl::PointCloud<pcl::PointNormal>);
    pcl::concatenateFields(*cloud, *normals, *cloud_with_normals);
    //* cloud_with_normals = cloud + normals

    pcl::search::KdTree<pcl::PointNormal>::Ptr tree2(new pcl::search::KdTree<pcl::PointNormal>);
    tree2->setInputCloud(cloud_with_normals);

    pcl::GreedyProjectionTriangulation<pcl::PointNormal> gp3;

    pcl::PolygonMesh triangles;

    gp3.setSearchRadius(1); 
    gp3.setMu(2.5f); 
    gp3.setMaximumNearestNeighbors(100); 
    gp3.setMaximumSurfaceAngle(M_PI / 4); 
    gp3.setMinimumAngle(M_PI / 18); 
    gp3.setMaximumAngle(2 * M_PI / 3); 
    gp3.setNormalConsistency(false); 

    gp3.setInputCloud(cloud_with_normals);
    gp3.setSearchMethod(tree2);
    cout << "reconstruct\n";
    gp3.reconstruct(triangles);
    finish = clock();
    cout << double(finish - start) / CLOCKS_PER_SEC << " (s) " << endl;
    pcl::io::savePLYFile("result.ply", triangles);
    // Additional vertex information
    //std::vector<int> parts = gp3.getPartIDs();
    //std::vector<int> states = gp3.getPointStates();

    boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
    viewer->setBackgroundColor(0, 0, 0);
    viewer->addPolygonMesh(triangles, "my"); 

```

there is the screenshots:
![image](https://cloud.githubusercontent.com/assets/16587031/17089820/182dc0e4-525d-11e6-83c4-7ceb6f45a3b2.png)
this is in pcl;
![image](https://cloud.githubusercontent.com/assets/16587031/17089848/5fc93c44-525d-11e6-9c63-eff8d37de838.png)
this is in meshlab,
what's wrong with me ?thank you.

**Comment by VictorLamoine** [comment]
It looks like faces with wrong normals (flipped).

PCL/VTK probably does render with double sided lightning, which means that both sides of the faces will be illumated. By default MeshLab does not, the "interior" of the face is not illuminated.

You can switch on double sided lightning in MeshLab by going in the `Render` > `Lightning` menu. You should see what PCL rendered.

Can you post a complete/short code example demonstrating this issue?
It might not be an issue in the way that you have to apply a filter to make the normals uniform.

**Comment by Chungzuwalla** [comment]
There appears to be a flag `consistent_ordering_` in GreedyProjectionTriangulation:

       /** \brief Set the flag to order the resulting triangle vertices consistently (positive direction around normal).
        * @note Assumes consistently oriented normals (towards the viewpoint) -- see setNormalConsistency ()
        * \param[in] consistent_ordering set it to true if triangle vertices should be ordered consistently
        */
      inline void 
      setConsistentVertexOrdering (bool consistent_ordering) { consistent_ordering_ = consistent_ordering; }


The flag is initialized to false.  Perhaps setting it true will solve the problem? (Haven't tried, just skimmed the code)
