### ISSUE TITLE
PCL x64 can't run on windows 10

### ISSUE THREAD

**Issue by hwdong** [PointCloudLibrary/pcl#1662]
![driver](https://cloud.githubusercontent.com/assets/4346276/17216477/705f88a2-5513-11e6-8e54-4f3790359169.jpg)

**Comment by hwdong** [comment]
I solved this problem after I searched on internet and put my solution here and hope helpful to other people with similar problem.

http://hongweidong.tumblr.com/post/148051519601/cant-install-openni-kinect-driver-on-windows-10

**Comment by SergioRAgostinho** [comment]
Closing since it's not PCL issue.
