### ISSUE TITLE
Error linking (make command) people_detect : undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'

### ISSUE THREAD

**Issue by ashokbugude** [PointCloudLibrary/pcl#1664]
* Operating System and version: Linux Ubuntu 16.04
* Compiler: gcc 5.4
* PCL Version: 1.8

I am trying to build people_detect in pcl/gpu/people folder
cmake .. command executed fine
When i run 'make' command, I get below error

people_detect.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIiED2Ev[_ZN3pcl3gpu13DeviceArray2DIiED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
collect2: error: ld returned 1 exit status
CMakeFiles/people_detect.dir/build.make:182: recipe for target 'people_detect' failed
make[2]: *** [people_detect] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/people_detect.dir/all' failed
make[1]: *** [CMakeFiles/people_detect.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Pls help resolve the issue

.......................................................................................

Below is the output of make command
zayyon@zayyon-MS-7693:/home/roitberg/workspace/pcl/gpu/people/build$ make
[ 50%] Building CXX object CMakeFiles/people_detect.dir/src/people_detector.cpp.o
[100%] Linking CXX executable people_detect
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::PeopleDetector()':
people_detector.cpp:(.text+0x324): undefined reference to `pcl::gpu::people::OrganizedPlaneDetector::OrganizedPlaneDetector(int, int)'
people_detector.cpp:(.text+0x36e): undefined reference to `pcl::gpu::people::ProbabilityProcessor::ProbabilityProcessor()'
people_detector.cpp:(.text+0x3b8): undefined reference to `pcl::gpu::people::PersonAttribs::PersonAttribs()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::allocate_buffers(int, int)':
people_detector.cpp:(.text+0x89a): undefined reference to `pcl::device::Dilatation::prepareRect5x5Kernel(pcl::gpu::DeviceArray<unsigned char>&)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::process(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<pcl::RGB> const&)':
people_detector.cpp:(.text+0x1073): undefined reference to `pcl::device::computeHueWithNans(pcl::gpu::DeviceArray2D<uchar4> const&, pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<float>&)'
people_detector.cpp:(.text+0x1128): undefined reference to `pcl::device::computeCloud(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::device::Intr const&, pcl::gpu::DeviceArray2D<float4>&)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::process(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGBA> const> const&)':
people_detector.cpp:(.text+0x1333): undefined reference to `pcl::device::computeHue(int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::process()':
people_detector.cpp:(.text+0x14de): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::process(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::PointCloud<pcl::PointXYZ> const&, int)'
people_detector.cpp:(.text+0x14f5): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::getBlobMatrix() const'
people_detector.cpp:(.text+0x16ff): undefined reference to `pcl::device::Dilatation::invoke(pcl::gpu::DeviceArray2D<unsigned char> const&, pcl::gpu::DeviceArray<unsigned char> const&, pcl::gpu::DeviceArray2D<unsigned char>&)'
people_detector.cpp:(.text+0x1733): undefined reference to `pcl::device::prepareForeGroundDepth(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<unsigned char>&, pcl::gpu::DeviceArray2D<unsigned short>&)'
people_detector.cpp:(.text+0x1771): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::process(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::PointCloud<pcl::PointXYZ> const&, int)'
people_detector.cpp:(.text+0x1788): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::getBlobMatrix() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::processProb(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGBA> const> const&)':
people_detector.cpp:(.text+0x4432): undefined reference to `pcl::device::computeHue(int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::people::PeopleDetector::processProb()':
people_detector.cpp:(.text+0x45e9): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processProb(pcl::gpu::DeviceArray2D<unsigned short> const&)'
people_detector.cpp:(.text+0x4640): undefined reference to `pcl::gpu::people::ProbabilityProcessor::SelectLabel(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<unsigned char>&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)'
people_detector.cpp:(.text+0x46d9): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processProb(pcl::gpu::DeviceArray2D<unsigned short> const&)'
people_detector.cpp:(.text+0x472d): undefined reference to `pcl::gpu::people::ProbabilityProcessor::CreateGaussianKernel(float, int)'
people_detector.cpp:(.text+0x4870): undefined reference to `pcl::gpu::people::ProbabilityProcessor::GaussianBlur(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&, pcl::gpu::DeviceArray<float>&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)'
people_detector.cpp:(.text+0x490f): undefined reference to `pcl::gpu::people::ProbabilityProcessor::CombineProb(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&, float, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&, float, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)'
people_detector.cpp:(.text+0x497d): undefined reference to `pcl::gpu::people::ProbabilityProcessor::SelectLabel(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<unsigned char>&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)'
people_detector.cpp:(.text+0x49ca): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processSmooth(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::PointCloud<pcl::PointXYZ> const&, int)'
people_detector.cpp:(.text+0x4a0b): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processRelations(boost::shared_ptr<pcl::gpu::people::PersonAttribs>)'
people_detector.cpp:(.text+0x4a64): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::getBlobMatrix() const'
people_detector.cpp:(.text+0x4c19): undefined reference to `pcl::device::Dilatation::invoke(pcl::gpu::DeviceArray2D<unsigned char> const&, pcl::gpu::DeviceArray<unsigned char> const&, pcl::gpu::DeviceArray2D<unsigned char>&)'
people_detector.cpp:(.text+0x4c4d): undefined reference to `pcl::device::prepareForeGroundDepth(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<unsigned char>&, pcl::gpu::DeviceArray2D<unsigned short>&)'
people_detector.cpp:(.text+0x4c75): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processProb(pcl::gpu::DeviceArray2D<unsigned short> const&)'
people_detector.cpp:(.text+0x4ccc): undefined reference to `pcl::gpu::people::ProbabilityProcessor::SelectLabel(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::gpu::DeviceArray2D<unsigned char>&, pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)'
people_detector.cpp:(.text+0x4d0a): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processSmooth(pcl::gpu::DeviceArray2D<unsigned short> const&, pcl::PointCloud<pcl::PointXYZ> const&, int)'
people_detector.cpp:(.text+0x4d4b): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::processRelations(boost::shared_ptr<pcl::gpu::people::PersonAttribs>)'
people_detector.cpp:(.text+0x4da4): undefined reference to `pcl::gpu::people::RDFBodyPartsDetector::getBlobMatrix() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray<unsigned char>::~DeviceArray()':
people_detector.cpp:(.text._ZN3pcl3gpu11DeviceArrayIhED2Ev[_ZN3pcl3gpu11DeviceArrayIhED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory::~DeviceMemory()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::~DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEED2Ev[_ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::~DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIfED2Ev[_ZN3pcl3gpu13DeviceArray2DIfED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::~DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DItED2Ev[_ZN3pcl3gpu13DeviceArray2DItED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned char>::~DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIhED2Ev[_ZN3pcl3gpu13DeviceArray2DIhED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray<float>::~DeviceArray()':
people_detector.cpp:(.text._ZN3pcl3gpu11DeviceArrayIfED2Ev[_ZN3pcl3gpu11DeviceArrayIfED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory::~DeviceMemory()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray<unsigned char>::DeviceArray()':
people_detector.cpp:(.text._ZN3pcl3gpu11DeviceArrayIhEC2Ev[_ZN3pcl3gpu11DeviceArrayIhEC5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory::DeviceMemory()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEEC2Ev[_ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEEC5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIfEC2Ev[_ZN3pcl3gpu13DeviceArray2DIfEC5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DItEC2Ev[_ZN3pcl3gpu13DeviceArray2DItEC5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned char>::DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIhEC2Ev[_ZN3pcl3gpu13DeviceArray2DIhEC5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::DeviceMemory2D()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::create(int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEE6createEii[_ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEE6createEii]+0x27): undefined reference to `pcl::gpu::DeviceMemory2D::create(int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::create(int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIfE6createEii[_ZN3pcl3gpu13DeviceArray2DIfE6createEii]+0x29): undefined reference to `pcl::gpu::DeviceMemory2D::create(int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::create(int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DItE6createEii[_ZN3pcl3gpu13DeviceArray2DItE6createEii]+0x25): undefined reference to `pcl::gpu::DeviceMemory2D::create(int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned char>::create(int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIhE6createEii[_ZN3pcl3gpu13DeviceArray2DIhE6createEii]+0x22): undefined reference to `pcl::gpu::DeviceMemory2D::create(int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::rows() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DItE4rowsEv[_ZNK3pcl3gpu13DeviceArray2DItE4rowsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::rows() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::cols() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DItE4colsEv[_ZNK3pcl3gpu13DeviceArray2DItE4colsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::colsBytes() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::operator=(pcl::gpu::DeviceArray2D<unsigned short> const&)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DItEaSERKS2_[_ZN3pcl3gpu13DeviceArray2DItEaSERKS2_]+0x1f): undefined reference to `pcl::gpu::DeviceMemory2D::operator=(pcl::gpu::DeviceMemory2D const&)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `void pcl::gpu::DeviceArray2D<float>::download<Eigen::aligned_allocator<float> >(std::vector<float, Eigen::aligned_allocator<float> >&, int&) const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DIfE8downloadIN5Eigen17aligned_allocatorIfEEEEvRSt6vectorIfT_ERi[_ZNK3pcl3gpu13DeviceArray2DIfE8downloadIN5Eigen17aligned_allocatorIfEEEEvRSt6vectorIfT_ERi]+0x73): undefined reference to `pcl::gpu::DeviceMemory2D::colsBytes() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `void pcl::gpu::DeviceArray2D<pcl::PointXYZ>::download<Eigen::aligned_allocator<pcl::PointXYZ> >(std::vector<pcl::PointXYZ, Eigen::aligned_allocator<pcl::PointXYZ> >&, int&) const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE8downloadIN5Eigen17aligned_allocatorIS2_EEEEvRSt6vectorIS2_T_ERi[_ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE8downloadIN5Eigen17aligned_allocatorIS2_EEEEvRSt6vectorIS2_T_ERi]+0x73): undefined reference to `pcl::gpu::DeviceMemory2D::colsBytes() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::cols() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE4colsEv[_ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE4colsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::colsBytes() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::rows() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE4rowsEv[_ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE4rowsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::rows() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>::swap(pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>&)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_6device14prob_histogramEE4swapERS4_[_ZN3pcl3gpu13DeviceArray2DINS_6device14prob_histogramEE4swapERS4_]+0x1f): undefined reference to `pcl::gpu::DeviceMemory2D::swap(pcl::gpu::DeviceMemory2D&)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray<float>::DeviceArray(unsigned long)':
people_detector.cpp:(.text._ZN3pcl3gpu11DeviceArrayIfEC2Em[_ZN3pcl3gpu11DeviceArrayIfEC5Em]+0x27): undefined reference to `pcl::gpu::DeviceMemory::DeviceMemory(unsigned long)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray<float>::upload(float const*, unsigned long)':
people_detector.cpp:(.text._ZN3pcl3gpu11DeviceArrayIfE6uploadEPKfm[_ZN3pcl3gpu11DeviceArrayIfE6uploadEPKfm]+0x2f): undefined reference to `pcl::gpu::DeviceMemory::upload(void const*, unsigned long)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::cols() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DIfE4colsEv[_ZNK3pcl3gpu13DeviceArray2DIfE4colsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::colsBytes() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::rows() const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DIfE4rowsEv[_ZNK3pcl3gpu13DeviceArray2DIfE4rowsEv]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::rows() const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::download(void*, unsigned long) const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DIfE8downloadEPvm[_ZNK3pcl3gpu13DeviceArray2DIfE8downloadEPvm]+0x27): undefined reference to `pcl::gpu::DeviceMemory2D::download(void*, unsigned long) const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::download(void*, unsigned long) const':
people_detector.cpp:(.text._ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE8downloadEPvm[_ZNK3pcl3gpu13DeviceArray2DINS_8PointXYZEE8downloadEPvm]+0x27): undefined reference to `pcl::gpu::DeviceMemory2D::download(void*, unsigned long) const'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::PointXYZ>::upload(void const*, unsigned long, int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEE6uploadEPKvmii[_ZN3pcl3gpu13DeviceArray2DINS_8PointXYZEE6uploadEPKvmii]+0x39): undefined reference to `pcl::gpu::DeviceMemory2D::upload(void const*, unsigned long, int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<float>::upload(void const*, unsigned long, int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIfE6uploadEPKvmii[_ZN3pcl3gpu13DeviceArray2DIfE6uploadEPKvmii]+0x3b): undefined reference to `pcl::gpu::DeviceMemory2D::upload(void const*, unsigned long, int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned short>::upload(void const*, unsigned long, int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DItE6uploadEPKvmii[_ZN3pcl3gpu13DeviceArray2DItE6uploadEPKvmii]+0x37): undefined reference to `pcl::gpu::DeviceMemory2D::upload(void const*, unsigned long, int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<unsigned char>::upload(void const*, unsigned long, int, int)':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DIhE6uploadEPKvmii[_ZN3pcl3gpu13DeviceArray2DIhE6uploadEPKvmii]+0x34): undefined reference to `pcl::gpu::DeviceMemory2D::upload(void const*, unsigned long, int, int)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function `pcl::gpu::DeviceArray2D<pcl::device::prob_histogram>::~DeviceArray2D()':
people_detector.cpp:(.text._ZN3pcl3gpu13DeviceArray2DINS_6device14prob_histogramEED2Ev[_ZN3pcl3gpu13DeviceArray2DINS_6device14prob_histogramEED5Ev]+0x14): undefined reference to `pcl::gpu::DeviceMemory2D::~DeviceMemory2D()'
collect2: error: ld returned 1 exit status
CMakeFiles/people_detect.dir/build.make:182: recipe for target 'people_detect' failed
make[2]: *** [people_detect] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/people_detect.dir/all' failed
make[1]: *** [CMakeFiles/people_detect.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by VictorLamoine** [comment]
Stop spamming the issue tracker, we will block your account if you keep doing so.

Already two times, you have been answered:
- https://github.com/PointCloudLibrary/pcl/issues/1681
- https://github.com/PointCloudLibrary/pcl/issues/1696

Please consider reading these answers. The problem is NOT on PCL side.
