### ISSUE TITLE
Out of range runtime error in 'octree2buf_base.hpp', function serializeTreeRecursive

### ISSUE THREAD

**Issue by sandy-ssdut** [PointCloudLibrary/pcl#1667]
Ubuntu PCL1.8

In .hpp file octree2buf_base.hpp, function:
 unsigned int Octree2BufBase<LeafContainerT, BranchContainerT>::createLeafRecursive (const OctreeKey& key_arg, ... )

When the current BranchNode reach the leaf node, this function will check the leaf node in the previous buff in the same position, if the leaf node exits in the previous buff, the leaf node in current buff will be pointed to the leaf node in the previous leaf.

And here is the problem, unlike the branch node, which will be reset if this branch has been taken from previous buffer, the leaf node will not be reset. So the container of this leaf node will contain the index in both current buff and previous buff. When function **serializeTreeCallback** is called, an out of range runtime error will be caused.

Could anyone fix this runtime error?

**Comment by sandy-ssdut** [comment]
I fix this runtime error.
Some code is deleted in octree2buf_base.hpp: line 400-415 ,737-750 .
Am I right?

**Comment by SergioRAgostinho** [comment]
Can you a simply test case exemplifying your runtime error?

**Comment by mvieth** [comment]
Fixed by #4642
