### ISSUE TITLE
Could NOT find openni (missing:  OPENNI_LIBRARY) 

### ISSUE THREAD

**Issue by swjtuztg** [PointCloudLibrary/pcl#1669]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment
* Operating System and version: win10, x64
* Compiler: vs2010 X64 , Cmake3.6.1
* PCL Version: 1.6.0

## Expected Behavior
When I make the samples provided in tutorials directory, the cmake always tell me could not find
OPENNI_INCLUDE_DIRS, and OPENNI_LIBRARY. So I try to modify the C:\Program Files\PCL 1.6.0\cmake\PCLConfig.cmake.
the line 195 and 196 are changed to as follows:
    set(OPENNI_INCLUDE_DIRS_HINT "${PCL_ROOT}/3rdParty/OpenNI/Include")
    set(OPENNI_LIBRARY_HINT "${PCL_ROOT}/3rdParty/OpenNI/Lib64/openNI64.lib")

After the modification, the CMAKE can find the OPENNI_INCLUDE_DIRS, but still could not find the OPENNI_LIBRARY.

When I changed "OPENNI_LIBRARY" manually in CMAKE's gui, it works well.
 
(btw: I am sure the directorys "${PCL_ROOT}/3rdParty/OpenNI/Include", and "${PCL_ROOT}/3rdParty/OpenNI/Lib64/openNI64.lib" are both correct!)

I want to know why CMAKE could not find the "OPENNI_INCLUDE_DIRS", and how to modify the PCLConfig.cmake ? I do not want to modify it manually each time.

**Comment by jspricke** [comment]
As noted above, please ask questions on the mailing list.

PCLConfig.cmake is generated when compiling PCL, so you should set it there to have it automatically.
