### ISSUE TITLE
Function for saving range image

### ISSUE THREAD

**Issue by wangshp** [PointCloudLibrary/pcl#1671]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

Function for saving range image.
## Your Environment

* Operating System and version: ubunutu 
* Compiler: cmake
* PCL Version: 1.7

## Expected Behavior

improvement: need to have a function to save the range image after i get it. 
## Current Behavior

there is no such function now.
## Possible Solution

could add this function in RangeImageVisualizer class or RangeImageSpherical class.
## Code to Reproduce

http://pointclouds.org/documentation/tutorials/range_image_visualization.php#range-image-visualization
like the example above, after visualize the range image, how can i save it.
## Context

i am trying to match the image captured by camera and lidar data captured by lidar. So i need to save the range image after getting it.

**Comment by SergioRAgostinho** [comment]
This [method](http://docs.pointclouds.org/trunk/group__io.html#ga7291a029cdcde32ca3639d07dc6491b9) allows you to do that. Instead of creating a ```pcl::RangeImage``` from your point cloud create a ```pcl::RangeImagePlanar``` instead, which is a child class of ```pcl::RangeImage```. 

In case of doubt use first the mailing list.

**Comment by jeychandar** [comment]
@SergioRAgostinho Hi I am able to see spherical image on range image widget.My issue is how can i save as png when live update is on. Is it possible? Could you please help me out with this issue. Thanks in advance
