### ISSUE TITLE
PCL-git build fail with CUDA?

### ISSUE THREAD

**Issue by jiapei100** [PointCloudLibrary/pcl#1674]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

- Operating System and version: Ubuntu 16.04
- Compiler: GCC 5.3.0 + Cuda 8.0.27 + CUDA_ARCH: 5.2 (GTX 980M)
- PCL Version: 1.8.0 (Current Git)

> .../pcl/gpu/people/src/cuda/nvidia/NPP_staging.cu(2082): error: identifier "__iAtomicCAS" is undefined
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00007691_00000000-5_NPP_staging.cpp4.ii".
> -- Removing .../pcl/build/gpu/people/CMakeFiles/cuda_compile.dir/src/cuda/nvidia/./cuda_compile_generated_NPP_staging.cu.o
> /usr/bin/cmake -E remove .../pcl/build/gpu/people/CMakeFiles/cuda_compile.dir/src/cuda/nvidia/./cuda_compile_generated_NPP_staging.cu.o
> CMake Error at cuda_compile_generated_NPP_staging.cu.o.cmake:266 (message):
>  Error generating file 
>  .../pcl/build/gpu/people/CMakeFiles/cuda_compile.dir/src/cuda/nvidia/./cuda_compile_generated_NPP_staging.cu.o
> 
> gpu/people/CMakeFiles/pcl_gpu_people.dir/build.make:1602: recipe for target 'gpu/people/CMakeFiles/cuda_compile.dir/src/cuda/nvidia/cuda_compile_generated_NPP_staging.cu.o' failed
> make[2]: **\* [gpu/people/CMakeFiles/cuda_compile.dir/src/cuda/nvidia/cuda_compile_generated_NPP_staging.cu.o] Error 1
> make[2]: Leaving directory '.../pcl/build'
> CMakeFiles/Makefile2:15380: recipe for target 'gpu/people/CMakeFiles/pcl_gpu_people.dir/all' failed
> make[1]: **\* [gpu/people/CMakeFiles/pcl_gpu_people.dir/all] Error 2
> make[1]: **\* Waiting for unfinished jobs....

Exactly the same issue as asked here:
https://devtalk.nvidia.com/default/topic/950328/cant-install-pcl-point-cloud-with-cuda-help/

Can anybody help please?

Cheers
Pei

**Comment by hanshammel1337** [comment]
Did you solve this problem?

**Comment by hanshammel1337** [comment]
I solved this by changing line 2073 in cuda_compile_generated_NPP_staging.cu
https://github.com/PointCloudLibrary/pcl/blob/master/gpu/people/src/cuda/nvidia/NPP_staging.cu#L2073
to `#if ((defined __CUDA_ARCH__) && (__CUDA_ARCH__ < 200)) `

I found the solution here https://devtalk.nvidia.com/default/topic/950328/cant-install-pcl-point-cloud-with-cuda-help/

CUDA 8.0.44, GCC 5.4 (Ubuntu 16.04 LTS), Arch 6.1

I didn't check if the people module works correctly, but the build is fine now. Maybe a pull request can be created for this.

**Comment by jiapei100** [comment]
@hanshammel1337 

Yes, That's great... Problem solved... Your solution is correct !!!

**Comment by jspricke** [comment]
@hanshammel1337 great find. Could you please open a pull request?

**Comment by caomw** [comment]
Good
