### ISSUE TITLE
OctreePointCloudCompression not properly restoring original data.

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1680]
## Your Environment

* Operating System and version: OS X El Capitan 10.11.6
* Compiler: Apple LLVM version 7.3.0 
* PCL Version: Git

## Current Behavior

OctreePointCloudCompression is not compressing and restoring data to its original values. Verified while addressing #1221. Check that PR for more info.

## Expected Behavior

Unless I misunderstood the point of this class, "This class enables compression and decompression of point cloud data based on octree data structures.", I expected this compression to be lossless and all the original data to be restored.

## Possible Solution

Who knows, more pressing matters now :)

## Code to Reproduce

Check #1221.

## Context

n.a.

**Comment by SergioRAgostinho** [comment]
Learned that compression is lossy.

**Comment by taketwo** [comment]
Does it make sense to add a note or something to the docstring?

**Comment by SergioRAgostinho** [comment]
It definitely wouldn't hurt.
