### ISSUE TITLE
Errors compiling People Dectect

### ISSUE THREAD

**Issue by ashokbugude** [PointCloudLibrary/pcl#1681]
I am trying to build cmakeLists.txt in pcl/gpu/people/src folder

But I get below error messages
CMake Error at CMakeLists.txt:7 (PCL_SUBSYS_OPTION):
  Unknown CMake command "PCL_SUBSYS_OPTION".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/zayyon/Downloads/pcl-master/gpu/people/build/CMakeFiles/CMakeOutput.log".

* Operating System and version: Linux 16.04
* Compiler: gcc 5.4.0
* PCL Version: 1.7

**Comment by taketwo** [comment]
This is a bug tracker. For questions like this one please use our mailing list.

As per your problem, GPU/People is is not a standalone project, it is not supposed to be built separately from the rest of PCL. Instead, you should enable corresponding option when configuring the library.

**Comment by ashokbugude** [comment]
Can I know how to configure the library ?

**Comment by taketwo** [comment]
Please refer to the platform specific instructions: https://github.com/PointCloudLibrary/pcl

**Comment by ashokbugude** [comment]
Thanks

**Comment by ashokbugude** [comment]
Hi , I posted my issue in pcl mailing lists 5 days ago , but its still not accepted. Hence continuing my issue here



    Operating System and version: Linux , Ubuntu 16.04
    Compiler: gcc 4.9 ( tried with gcc 5.4 also )

    PCL Version: 1.8

    I am trying to build people_detector code in code blocks form pcl/gpu/people/src/people_detector.cpp, but I get below errors although I have added all .so files of pcl in project -> build options -> Linker Settings. 
 am trying to put the contents of CMakeLists.txt as described in http://pointclouds.org/documentation/tutorials/gpu_people.php ie

cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(people_detect)

find_package(PCL 1.7 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

#Searching CUDA
FIND_PACKAGE(CUDA)

#Include the FindCUDA script
INCLUDE(FindCUDA)

cuda_add_executable (people_detect src/people_detector.cpp)
target_link_libraries (people_detect ${PCL_LIBRARIES})



I get the errors when I run cmake as ahown below

zayyon@zayyon-MS-7693:/home/roitberg/workspace/pcl/gpu/people/build$ make
[ 50%] Building CXX object CMakeFiles/people_detect.dir/src/people_detector.cpp.o
[100%] Linking CXX executable people_detect
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function start': (.text+0x20): undefined reference tomain'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function pcl::gpu::people::PeopleDetector::PeopleDetector()': people_detector.cpp:(.text+0x324): undefined reference topcl::gpu::people::OrganizedPlaneDetector::OrganizedPlaneDetector(int, int)'
people_detector.cpp:(.text+0x36e): undefined reference to pcl::gpu::people::ProbabilityProcessor::ProbabilityProcessor()' people_detector.cpp:(.text+0x3b8): undefined reference topcl::gpu::people::PersonAttribs::PersonAttribs()'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function pcl::gpu::people::PeopleDetector::allocate_buffers(int, int)': people_detector.cpp:(.text+0x89a): undefined reference topcl::device::Dilatation::prepareRect5x5Kernel(pcl::gpu::DeviceArray&)'
CMakeFiles/people_detect.dir/src/people_detector.cpp.o: In function pcl::gpu::people::PeopleDetector::process(pcl::gpu::DeviceArray2D const&,

**Comment by ashokbugude** [comment]
Hi,
Can I pls know how do I resolve it ?

**Comment by VictorLamoine** [comment]
Did you configure, build and install PCL?
As Sergey mentionned, the `pcl/gpu/people` module is not stand-alone, you need to compile the whole PCL library first

**Comment by ashokbugude** [comment]
Yes , I have done it

**Comment by ashokbugude** [comment]
Could you pls tell if the steps mentioned in http://pointclouds.org/documentation/tutorials/gpu_people.php are correct ?

**Comment by ashokbugude** [comment]
Below are the errors generated while re configuring after enabling people detect

[ 67%] Built target pcl_openni_mobile_server
[ 67%] Built target pcl_openni_change_viewer
[ 67%] Built target pcl_openni_tracking
[ 67%] Built target pcl_nn_classification_example
[ 67%] Built target pcl_dinast_grabber
[ 67%] Built target pcl_openni_voxel_grid
[ 67%] Built target pcl_openni_shift_to_depth_conversion
[ 67%] Built target pcl_multiscale_feature_persistence_example
[ 67%] Built target pcl_apps
[ 67%] Built target pcl_ppf_object_recognition
[ 68%] Built target pcl_face_trainer
[ 68%] Built target pcl_surfel_smoothing_test
[ 68%] Built target pcl_convolve
[ 68%] Built target pcl_feature_matching
[ 69%] Built target pcl_openni_planar_segmentation
[ 69%] Built target pcl_openni_3d_convex_hull
[ 69%] Built target pcl_openni_organized_multi_plane_segmentation
[ 70%] Built target pcl_openni_uniform_sampling
[ 70%] Built target pcl_openni_boundary_estimation
[ 71%] Built target pcl_openni_3d_concave_hull
[ 72%] Built target pcl_openni_mls_smoothing
[ 73%] Built target pcl_openni_face_detector
[ 74%] Built target pcl_test_search_speed
[ 74%] Built target pcl_openni_planar_convex_hull
[ 75%] Built target pcl_grabcut_2d
[ 76%] Built target pcl_ni_linemod
[ 76%] Built target pcl_ni_susan
[ 76%] Built target pcl_ni_trajkovic
[ 76%] Built target pcl_openni_organized_compression
[ 76%] Built target pcl_openni_klt
[ 76%] Built target pcl_gpu_containers
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_utils.so
[ 76%] Built target pcl_gpu_utils
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_surface.so
[ 77%] Built target pcl_gpu_surface
[ 77%] Linking CXX shared library ../../lib/libpcl_gpu_people.so
[ 79%] Built target pcl_gpu_people
[ 79%] Linking CXX executable ../../../bin/pcl_people_pcd_prob
../../../lib/libpcl_gpu_people.so.1.8.0: undefined reference to `ncvDebugOutput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/build.make:308: recipe for target 'bin/pcl_people_pcd_prob' failed
make[2]: *** [bin/pcl_people_pcd_prob] Error 1
CMakeFiles/Makefile2:8516: recipe for target 'gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all' failed
make[1]: *** [gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
