### ISSUE TITLE
wrong statistics

### ISSUE THREAD

**Issue by AlirezaJav** [PointCloudLibrary/pcl#1693]
## Your Environment

- Operating System and version: Windows 10 Home
- Compiler: Visual studio 10
- PCL Version: PCL 1.8
## Expected Behavior

After Coding an intra frame, in the statistics shown on the screen, the type of the encoding frame should be "Intra Frame".
## Current Behavior

After Coding an intra frame, in the statistics shown on the screem the type of the encoding frame will be "Prediction Frame" which is wrong. This is because the intra flag is turned off to be ready for the next inter frame just before showing the statistics.
## Possible Solution

move "i_frame_= false;" below the instructions which are showing the statistics

**Comment by SergioRAgostinho** [comment]
Hey. Can you actually post some code (cpp and cmake) so that we can reproduce your setup. The more minimal the example, the better. Submit it [here](https://gist.github.com/) and link to us.

**Comment by AlirezaJav** [comment]
Source: https://gist.github.com/AlirezaJav/932f4718c812e504c893b7170f97d8a0
Cmake: https://gist.github.com/AlirezaJav/5d91c594f47bc3d2562e060bcfcda921

**Comment by kunaltyagi** [comment]
Resolved in the master branch a long time ago
