### ISSUE TITLE
‘openni_wrapper’ was not declared in this scope

### ISSUE THREAD

**Issue by ashokbugude** [PointCloudLibrary/pcl#1699]
* Operating System and version: Linux, Ubuntu 16.04
* Compiler: gcc 4.9
* PCL Version: 1.8

I am trying to compile people detect as described in http://pointclouds.org/documentation/tutorials/gpu_people.php 
When I run make , I get below errors

zayyon@zayyon-Lenovo-ideapad-300-15ISK:~/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/build$ make
Scanning dependencies of target people_detect
[ 50%] Building CXX object CMakeFiles/people_detect.dir/src/people_detect.cpp.o
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:45: error: ‘openni_wrapper’ was not declared in this scope
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                             ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:66: error: template argument 1 is invalid
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                                                  ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:45: error: ‘openni_wrapper’ was not declared in this scope
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                             ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:66: error: template argument 1 is invalid
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                                                  ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:45: error: ‘openni_wrapper’ was not declared in this scope
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                             ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:66: error: template argument 1 is invalid
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                                                  ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:45: error: ‘openni_wrapper’ was not declared in this scope
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                             ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:66: error: template argument 1 is invalid
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                                                  ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:27: error: invalid use of template-name ‘boost::shared_ptr’ without an argument list
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                           ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:192:44: error: expected ‘,’ or ‘...’ before ‘<’ token
     void source_cb2(const boost::shared_ptr<openni_wrapper::Image>& image_wrapp
                                            ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp: In member function ‘void PeoplePCDApp::source_cb2(int)’:
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:201:17: error: ‘depth_wrapper’ was not declared in this scope
         int w = depth_wrapper->getWidth();
                 ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:213:13: error: ‘image_wrapper’ was not declared in this scope
         w = image_wrapper->getWidth();
             ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp: In member function ‘void PeoplePCDApp::startMainLoop()’:
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:247:33: error: ‘openni_wrapper’ was not declared in this scope
       typedef boost::shared_ptr<openni_wrapper::DepthImage> DepthImagePtr;
                                 ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:247:59: error: template argument 1 is invalid
       typedef boost::shared_ptr<openni_wrapper::DepthImage> DepthImagePtr;
                                                           ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:248:54: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class boost::shared_ptr’
       typedef boost::shared_ptr<openni_wrapper::Image> ImagePtr;
                                                      ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:248:54: note:   expected a type, got ‘openni_wrapper’
In file included from /usr/include/boost/bind.hpp:22:0,
                 from /usr/local/include/pcl-1.8/pcl/features/feature.h:49,
                 from /usr/local/include/pcl-1.8/pcl/features/integral_image_normal.h:44,
                 from /usr/include/pcl/gpu/people/organized_plane_detector.h:44,
                 from /usr/include/pcl/gpu/people/people_detector.h:57,
                 from /home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:49:
/usr/include/boost/bind/bind.hpp: In instantiation of ‘struct boost::_bi::result_traits<boost::_bi::unspecified, void (PeoplePCDApp::*)(int)>’:
/usr/include/boost/bind/bind_template.hpp:15:48:   required from ‘class boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >’
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:251:149:   required from here
/usr/include/boost/bind/bind.hpp:69:37: error: ‘void (PeoplePCDApp::*)(int)’ is not a class, struct, or union type
     typedef typename F::result_type type;
                                     ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp: In function ‘int main(int, char**)’:
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:327:22: error: expected type-specifier
   capture.reset( new pcl::OpenNIGrabber() );
                      ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp: In instantiation of ‘void savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::PointXYZRGBA; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:170:61:   required from here
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:108:23: warning: ‘void pcl::io::savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::PointXYZRGBA; std::__cxx11::string = std::__cxx11::basic_string<char>]’ is deprecated: pcl::io::savePNGFile<typename T> (file_name, cloud) is deprecated, please use a new generic function pcl::io::savePNGFile (file_name, cloud, field_name) with "rgb" as the field name. [-Wdeprecated-declarations]
   pcl::io::savePNGFile(filename, cloud);
                       ^
In file included from /home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:56:0:
/usr/local/include/pcl-1.8/pcl/io/png_io.h:123:5: note: declared here
     savePNGFile (const std::string& file_name, const pcl::PointCloud<T>& cloud)
     ^
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp: In instantiation of ‘void savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::RGB; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:172:60:   required from here
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:108:23: warning: ‘void pcl::io::savePNGFile(const string&, const pcl::PointCloud<PointT>&) [with T = pcl::RGB; std::__cxx11::string = std::__cxx11::basic_string<char>]’ is deprecated: pcl::io::savePNGFile<typename T> (file_name, cloud) is deprecated, please use a new generic function pcl::io::savePNGFile (file_name, cloud, field_name) with "rgb" as the field name. [-Wdeprecated-declarations]
   pcl::io::savePNGFile(filename, cloud);
                       ^
In file included from /home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:56:0:
/usr/local/include/pcl-1.8/pcl/io/png_io.h:123:5: note: declared here
     savePNGFile (const std::string& file_name, const pcl::PointCloud<T>& cloud)
     ^
In file included from /usr/include/boost/function/detail/maybe_include.hpp:28:0,
                 from /usr/include/boost/function/detail/function_iterate.hpp:14,
                 from /usr/include/boost/preprocessor/iteration/detail/iter/forward1.hpp:62,
                 from /usr/include/boost/function.hpp:64,
                 from /usr/local/include/pcl-1.8/pcl/features/feature.h:48,
                 from /usr/local/include/pcl-1.8/pcl/features/integral_image_normal.h:44,
                 from /usr/include/pcl/gpu/people/organized_plane_detector.h:44,
                 from /usr/include/pcl/gpu/people/people_detector.h:57,
                 from /home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:49:
/usr/include/boost/function/function_template.hpp: In instantiation of ‘static void boost::detail::function::void_function_obj_invoker3<FunctionObj, R, T0, T1, T2>::invoke(boost::detail::function::function_buffer&, T0, T1, T2) [with FunctionObj = boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >; R = void; T0 = const int&; T1 = const int&; T2 = float]’:
/usr/include/boost/function/function_template.hpp:940:38:   required from ‘void boost::function3<R, T1, T2, T3>::assign_to(Functor) [with Functor = boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >; R = void; T0 = const int&; T1 = const int&; T2 = float]’
/usr/include/boost/function/function_template.hpp:728:7:   required from ‘boost::function3<R, T1, T2, T3>::function3(Functor, typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type) [with Functor = boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >; R = void; T0 = const int&; T1 = const int&; T2 = float; typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type = int]’
/usr/include/boost/function/function_template.hpp:1077:16:   required from ‘boost::function<R(T0, T1, T2)>::function(Functor, typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type) [with Functor = boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >; R = void; T0 = const int&; T1 = const int&; T2 = float; typename boost::enable_if_c<boost::type_traits::ice_not<boost::is_integral<Functor>::value>::value, int>::type = int]’
/home/zayyon/Downloads/pcl-master/doc/tutorials/content/sources/gpu/people_detect/src/people_detect.cpp:251:149:   required from here
/usr/include/boost/function/function_template.hpp:159:11: error: no match for call to ‘(boost::_bi::bind_t<boost::_bi::unspecified, void (PeoplePCDApp::*)(int), boost::_bi::list4<boost::_bi::value<PeoplePCDApp*>, boost::arg<1>, boost::arg<2>, boost::arg<3> > >) (const int&, const int&, float&)’
           BOOST_FUNCTION_RETURN((*f)(BOOST_FUNCTION_ARGS));
           ^
CMakeFiles/people_detect.dir/build.make:62: recipe for target 'CMakeFiles/people_detect.dir/src/people_detect.cpp.o' failed
make[2]: *** [CMakeFiles/people_detect.dir/src/people_detect.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/people_detect.dir/all' failed
make[1]: *** [CMakeFiles/people_detect.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by VictorLamoine** [comment]
Stop spamming the issue tracker, we will block your account if you keep doing so.

Already two times, you have been answered:
- https://github.com/PointCloudLibrary/pcl/issues/1681
- https://github.com/PointCloudLibrary/pcl/issues/1696

Please consider reading these answers. The problem is NOT on PCL side.

**Comment by ashokbugude** [comment]
Sorry , I didn't meant to spam the issue tracker

Thanks
Ashok

**Comment by ashokbugude** [comment]
HI

Below are the errors generated while re configuring after enabling people
detect

[ 67%] Built target pcl_openni_mobile_server
[ 67%] Built target pcl_openni_change_viewer
[ 67%] Built target pcl_openni_tracking
[ 67%] Built target pcl_nn_classification_example
[ 67%] Built target pcl_dinast_grabber
[ 67%] Built target pcl_openni_voxel_grid
[ 67%] Built target pcl_openni_shift_to_depth_conversion
[ 67%] Built target pcl_multiscale_feature_persistence_example
[ 67%] Built target pcl_apps
[ 67%] Built target pcl_ppf_object_recognition
[ 68%] Built target pcl_face_trainer
[ 68%] Built target pcl_surfel_smoothing_test
[ 68%] Built target pcl_convolve
[ 68%] Built target pcl_feature_matching
[ 69%] Built target pcl_openni_planar_segmentation
[ 69%] Built target pcl_openni_3d_convex_hull
[ 69%] Built target pcl_openni_organized_multi_plane_segmentation
[ 70%] Built target pcl_openni_uniform_sampling
[ 70%] Built target pcl_openni_boundary_estimation
[ 71%] Built target pcl_openni_3d_concave_hull
[ 72%] Built target pcl_openni_mls_smoothing
[ 73%] Built target pcl_openni_face_detector
[ 74%] Built target pcl_test_search_speed
[ 74%] Built target pcl_openni_planar_convex_hull
[ 75%] Built target pcl_grabcut_2d
[ 76%] Built target pcl_ni_linemod
[ 76%] Built target pcl_ni_susan
[ 76%] Built target pcl_ni_trajkovic
[ 76%] Built target pcl_openni_organized_compression
[ 76%] Built target pcl_openni_klt
[ 76%] Built target pcl_gpu_containers
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_utils.so
[ 76%] Built target pcl_gpu_utils
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_surface.so
[ 77%] Built target pcl_gpu_surface
[ 77%] Linking CXX shared library ../../lib/libpcl_gpu_people.so
[ 79%] Built target pcl_gpu_people
[ 79%] Linking CXX executable ../../../bin/pcl_people_pcd_prob
../../../lib/libpcl_gpu_people.so.1.8.0: undefined reference to
`ncvDebugOutput(std::__cxx11::basic_string, std::allocator > const&)'
collect2: error: ld returned 1 exit status
gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/build.make:308: recipe
for target 'bin/pcl_people_pcd_prob' failed
make[2]: *** [bin/pcl_people_pcd_prob] Error 1
CMakeFiles/Makefile2:8516: recipe for target
'gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all' failed
make[1]: *** [gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all]
Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ashokbugude** [comment]
Below are the errors generated while re configuring after enabling people
detect

[ 67%] Built target pcl_openni_mobile_server
[ 67%] Built target pcl_openni_change_viewer
[ 67%] Built target pcl_openni_tracking
[ 67%] Built target pcl_nn_classification_example
[ 67%] Built target pcl_dinast_grabber
[ 67%] Built target pcl_openni_voxel_grid
[ 67%] Built target pcl_openni_shift_to_depth_conversion
[ 67%] Built target pcl_multiscale_feature_persistence_example
[ 67%] Built target pcl_apps
[ 67%] Built target pcl_ppf_object_recognition
[ 68%] Built target pcl_face_trainer
[ 68%] Built target pcl_surfel_smoothing_test
[ 68%] Built target pcl_convolve
[ 68%] Built target pcl_feature_matching
[ 69%] Built target pcl_openni_planar_segmentation
[ 69%] Built target pcl_openni_3d_convex_hull
[ 69%] Built target pcl_openni_organized_multi_plane_segmentation
[ 70%] Built target pcl_openni_uniform_sampling
[ 70%] Built target pcl_openni_boundary_estimation
[ 71%] Built target pcl_openni_3d_concave_hull
[ 72%] Built target pcl_openni_mls_smoothing
[ 73%] Built target pcl_openni_face_detector
[ 74%] Built target pcl_test_search_speed
[ 74%] Built target pcl_openni_planar_convex_hull
[ 75%] Built target pcl_grabcut_2d
[ 76%] Built target pcl_ni_linemod
[ 76%] Built target pcl_ni_susan
[ 76%] Built target pcl_ni_trajkovic
[ 76%] Built target pcl_openni_organized_compression
[ 76%] Built target pcl_openni_klt
[ 76%] Built target pcl_gpu_containers
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_utils.so
[ 76%] Built target pcl_gpu_utils
[ 76%] Linking CXX shared library ../../lib/libpcl_gpu_surface.so
[ 77%] Built target pcl_gpu_surface
[ 77%] Linking CXX shared library ../../lib/libpcl_gpu_people.so
[ 79%] Built target pcl_gpu_people
[ 79%] Linking CXX executable ../../../bin/pcl_people_pcd_prob
../../../lib/libpcl_gpu_people.so.1.8.0: undefined reference to
`ncvDebugOutput(std::__cxx11::basic_string, std::allocator > const&)'
collect2: error: ld returned 1 exit status
gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/build.make:308: recipe
for target 'bin/pcl_people_pcd_prob' failed
make[2]: *** [bin/pcl_people_pcd_prob] Error 1
CMakeFiles/Makefile2:8516: recipe for target
'gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all' failed
make[1]: *** [gpu/people/tools/CMakeFiles/pcl_people_pcd_prob.dir/all]
Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
