### ISSUE TITLE
Hough3dGrouping returns improper rotation matrices

### ISSUE THREAD

**Issue by jolesinski** [PointCloudLibrary/pcl#1707]
## Your Environment

- Operating System and version: Ubuntu 14.04
- Compiler: gcc 4.8.5
- PCL Version: master 2f695d53892446b2991833184fbc5c5209c2bce5
## Expected Behavior

All rotation matrices returned by Hough3dGrouping.recognize() should be proper.
## Current Behavior

Some transformations contain improper rotation matrices (determinant = -1).
## Possible Solution

In Hough3dGrouping, transformations are retrieved from
correspondence_rejection_sample_consensus. I'll try to narrow down the issue.

**Update:**
The issue is within CorrespondenceRejectionSampleConsensus.

Enclosing code and data that shows this.
## Code to Reproduce

Snippet:  

```
using Pose = Eigen::Matrix4f;
using Poses = std::vector<Pose, Eigen::aligned_allocator<Pose>>;

pcl::Hough3DGrouping<pcl::PointXYZRGBA, pcl::PointXYZRGBA> clusterer;
clusterer.setHoughBinSize (.03);
clusterer.setHoughThreshold (5);
clusterer.setUseInterpolation (true);
clusterer.setUseDistanceWeight (false);

clusterer.setInputCloud (model.keypoints_);
clusterer.setInputRf (model.ref_frames_);
clusterer.setSceneCloud (scene.keypoints_);
clusterer.setSceneRf (scene.ref_frames_);
clusterer.setModelSceneCorrespondences (correspondences);

Poses poses;
clusterer.recognize(poses, clusters);

for (Pose& pose : poses)
{
  std::cout << pose << std::endl;
  std::cout << pose.block(0,0,3,3).determinant() << std::endl;
}
```

Output:

```
-0.0395593   0.443782  -0.895261   0.305219
 -0.158374   0.881852   0.444133  -0.172605
 -0.986586  -0.159356 -0.0353981   0.907983
         0          0          0          1
-1
  0.695129  -0.718884 0.00159533  0.0866627
 -0.450718  -0.434093    0.78001  -0.147977
 -0.560044  -0.542926  -0.625765    1.02924
         0          0          0          1
1
 0.119357 -0.880231   0.45929  0.115467
 0.209291 -0.429896 -0.878286  0.229099
-0.970542 -0.200955 -0.132913   1.02281
        0         0         0         1
-1
   -0.293105     -0.95608  0.000878571    -0.504923
    0.956079    -0.293106  -0.00144951     0.109681
 -0.00164336 -0.000415125    -0.999999      1.55684
           0            0            0            1
-1
0.0506383  0.948721  0.312031  0.592244
-0.943586  0.147817 -0.296303 -0.446786
 0.327232  0.279424 -0.902686   1.62344
        0         0         0         1
-1
 0.689415 -0.605067 -0.398247  0.400591
 0.720617  0.517016  0.461959 -0.661957
-0.0736159 -0.605465   0.79246   1.47573
        0         0         0         1
1
```

Impropers started to appear when I loosened correspondence distance to find more hypotheses.

**Update**

```
  pcl::PointCloud<pcl::PointXYZRGBA>::Ptr model(new pcl::PointCloud<pcl::PointXYZRGBA>);
  pcl::PointCloud<pcl::PointXYZRGBA>::Ptr scene(new pcl::PointCloud<pcl::PointXYZRGBA>);

  pcl::io::loadPCDFile("/path/model.pcd", *model);
  pcl::io::loadPCDFile("/path/scene.pcd", *scene);

  int query_idxes[25] = {
      184, 184, 323, 112, 323,
      214, 250, 323, 244, 323,
      250, 238, 235, 148, 399,
      184, 244, 323, 323, 271,
      168, 168, 271, 323, 250
  };
  int match_idxes[25] = {
        187,   357,   359,   359,   360,
        360,   388,   388,   388,   390,
        390,   421,   421,  2690,  5840,
       6551, 12325, 12325, 14595, 14595,
      14595, 20044, 20044, 20353, 20353
  };
  float distances[25] = {
      7.496268, 7.288277, 5.904928, 6.305154, 6.382112,
      6.798561, 5.934322, 5.967296, 6.119963, 6.072414,
      6.217568, 7.026330, 7.402331, 6.970789, 6.198461,
      7.539804, 7.566788, 7.803745, 7.114636, 7.120316,
      7.415527, 7.171877, 7.756444, 5.705190, 6.393744
  };

  pcl::Correspondences input_corrs;
  pcl::Correspondences filtered_corrs;
  for (int idx = 0; idx < 25; ++idx)
  {
    pcl::Correspondence corr(query_idxes[idx], match_idxes[idx], distances[idx]);
    input_corrs.push_back(corr);
  }

  pcl::registration::CorrespondenceRejectorSampleConsensus<pcl::PointXYZRGBA> corr_rejector;
  corr_rejector.setMaximumIterations (10000);
  corr_rejector.setInlierThreshold (.01);
  corr_rejector.setInputSource (model);
  corr_rejector.setInputTarget (scene);

  corr_rejector.getRemainingCorrespondences (input_corrs, filtered_corrs);

  Eigen::Matrix4f transform = corr_rejector.getBestTransformation ();

  std::cout << transform << std::endl;
  std::cout << transform.block(0,0,3,3).determinant() << std::endl;
```

Input clouds (had to append the txt):
[model.pcd.txt](https://github.com/PointCloudLibrary/pcl/files/447524/model.pcd.txt)
[scene.pcd.txt](https://github.com/PointCloudLibrary/pcl/files/447525/scene.pcd.txt)
## Context

I was trying to send those transformations as PoseArray in ROS, by converting them with tf::poseEigenToMsg. Converting improper ones back with tf::poseMsgToEigen gives different transformations with scaling, so transformed objects look weird.

**Comment by jolesinski** [comment]
## Further analysis
After reviewing PCL code, I've identified three issues related to the original problem:

- The root cause is [umeyama](https://github.com/PointCloudLibrary/pcl/blob/46cb8fe5589e88e36d79f9b8b8e5f4ff4fceb5de/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp#L292) method inside SampleConsensusModelRegistration (used by CorrespondenceRejectionSampleConsensus). Transform estimation returns improper rotations when one of the input matrices is rank deficient. The following test case exposes this problem:

```
TEST (PCL, UmeyamaDeficientRank)
{
  Eigen::Matrix3d src;
  src <<  1,  0,  0,
          0,  1,  0,
          0,  0,  1;

  Eigen::Matrix3d tgt;
  tgt <<  1,  0,  1,
          0,  1,  0,
          0,  0,  0;

  Eigen::Matrix4d transformation_matrix = pcl::umeyama (src, tgt, false);

  EXPECT_FLOAT_EQ(transformation_matrix.block(0,0,3,3).determinant(), 1);
}
```

Output:
> Failure
> Value of: 1
> Expected: transformation_matrix.block(0,0,3,3).determinant()
> Which is: -1

- SampleConsensusModelRegistration implements its own [estimateRigidTransformationSVD](https://github.com/PointCloudLibrary/pcl/blob/46cb8fe5589e88e36d79f9b8b8e5f4ff4fceb5de/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp#L268), whereas it should use [TransformationEstimationSVD](https://github.com/PointCloudLibrary/pcl/blob/46cb8fe5589e88e36d79f9b8b8e5f4ff4fceb5de/registration/include/pcl/registration/transformation_estimation_svd.h).

- Starting [from this line](https://github.com/PointCloudLibrary/pcl/blob/46cb8fe5589e88e36d79f9b8b8e5f4ff4fceb5de/registration/include/pcl/registration/impl/correspondence_rejection_sample_consensus.hpp#L154) of getRemainingCorrespondences, an unordered_map is used to filter correspondences based on the RANSAC inliers. This can return incorrect results, if index_queries in the input correspondences are not unique. For example, given a correspondence vector with an inlier followed by outlier with the same index_query, the outlier is returned. It can be exemplified by the following test case:
```
TEST (CorrespondenceRejectors, NotUniqueQueries)
{
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
  cloud->width = 20;
  cloud->height = 1;
  cloud->points.resize (cloud->width * cloud->height);

  pcl::Correspondences input_corrs;
  for (size_t idx = 0; idx < cloud->points.size (); ++idx)
  {
    cloud->points[idx].x = idx;
    cloud->points[idx].y = idx;
    cloud->points[idx].z = idx;

    input_corrs.push_back(pcl::Correspondence (idx, idx, 0));
  }
  input_corrs.back().index_query = input_corrs.front().index_query;

  pcl::Correspondences filtered_corrs;
  pcl::registration::CorrespondenceRejectorSampleConsensus<pcl::PointXYZ> corr_rejector;
  corr_rejector.setMaximumIterations (100);
  corr_rejector.setInlierThreshold (.01);
  corr_rejector.setInputSource (cloud);
  corr_rejector.setInputTarget (cloud);

  corr_rejector.getRemainingCorrespondences (input_corrs, filtered_corrs);

  EXPECT_EQ(filtered_corrs.front().index_query, filtered_corrs.front().index_match);
}
```
Output:

> Failure
> Value of: filtered_corrs.front().index_match
>   Actual: 19
> Expected: filtered_corrs.front().index_query
> Which is: 0

Note that the issue 3 occurs only when someone allows for multiple neighbours of a single descriptor during the matching phase. I'm still learning the recognition pipeline, but feel that such case should be handled properly, for example if user wants to recognize multiple model instances in the scene. The original issue, however, may occur with correspondence grouping tutorial code, if two different model points are matched to to the same scene point. I think the rank should be checked before transformation estimation with svd. Please share your comments on the problem.

**Comment by jspricke** [comment]
This should be fixed in master, please reopen otherwise.
