### ISSUE TITLE
PointCloud to Eigen Matrix conversion dimensions bug?

### ISSUE THREAD

**Issue by renatoGarcia** [PointCloudLibrary/pcl#1709]
When running the code bellow:

``` c++
pcl::PointCloud<pcl::PointXYZRGB> r;
pcl::PointXYZRGB p0, p1, p2;
p0.x = 0.551; p0.y = 0.059; p0.z = 0.984; p0.r =  50; p0.g =  17; p0.b =  54;
p1.x = 0.049; p1.y = 0.963; p1.z = 0.433; p1.r =  44; p1.g = 149; p1.b =  43;
p2.x = 0.854; p2.y = 0.542; p2.z = 0.935; p2.r = 209; p2.g = 163; p2.b = 135;
r.push_back(p0); r.push_back(p1); r.push_back(p2);

auto const m = r.getMatrixXfMap();
std::cout << m.rows() << " x " << m.cols() << std::endl;
std::cout << m << std::endl;
```

I would expect to see as output something like:

```
5 x 3
       0.551        0.049        0.854
       0.059        0.963        0.542
       0.984        0.433        0.935
           1            1            1
 4.59795e-39  4.09427e-39  1.92523e-38
```

Where each X-Y-Z-W component is viewed as a row (4*float -> 4*4 bytes) and the RGBA
components are jointly viewed as a unique row (1*uint32_t -> 1*4 bytes), since each
PointXYZRGB has an internal structure like this (not showing padding data):

``` c++
struct _PointXYZRGB
{
    union {
        float data[4];
        struct {
            float x;
            float y;
            float z;
        };
    };

    union
    {
        union
        {
            struct
            {
                uint8_t b;
                uint8_t g;
                uint8_t r;
                uint8_t a;
            };
            float rgb;
        };
        uint32_t rgba;
    };
};
```

However, that program output is something like this:

```
8 x 3
       0.551        0.049        0.854
       0.059        0.963        0.542
       0.984        0.433        0.935
           1            1            1
 4.59795e-39  4.09427e-39  1.92523e-38
 4.59163e-41  4.57608e-41            0
-1.09698e+08 -1.42066e+08  1.90433e-38
 4.57608e-41  4.57608e-41            0
```

Each PointXYZRGB object has 20 bytes of data plus 12 padding bytes, hence that extra 3
rows are a padding to 16-bytes align the point cloud. So far, so good. My question is:
wouldn't be better to return a 5x3 eigen Matrix with a proper stride?

Is this a bug? If I change the getMatrixXfMap method to work as I was expecting, this
could be merged back to PCL?

**Comment by colby-ham** [comment]
^Bump

**Comment by stefanbuettner** [comment]
To my understanding, the `getMatrixXfMap()` methods are to get fast access to the raw data of the point cloud. I admit, it's weird at first but the documentation also says "This method is for advanced users only! Use with care!". The `PointXYZRGB` is 16 byte aligned and you get an Eigen matrix which reflects that. And as `getMatrixXfMap(dim, stride, offset)` provides what you'd expect and an Eigen matrix referring to aligned 16 byte data with no stride might have some performance benefits I wouldn't change it.

**Comment by taketwo** [comment]
In general, I agree with Stefan. The function does what is advertised in the docstring (and even warns the users) so I don't think we can consider this a bug.

Can you describe your use-case? Perhaps one of the other overloads is more appropriate?

**Comment by SergioRAgostinho** [comment]
> Wouldn't be better to return a 5x3 eigen Matrix with a proper stride?

That would require specializing that method for all available point types, since I don't see an easy way to detect the last padding elements.

Since it's an advanced memory mapping method, I would keep it as it is, since we do provide an overload that allows to specify the dim, stride and offset individually I really see no issue with it.

**Comment by taketwo** [comment]
> That would require specializing that method for all available point types

Yeah. We can come up with a function to count the total size of registered fields in a point type, however this won't include "inner" padding elements (like the fourth float after XYZ).

**Comment by phil0stine** [comment]
> That would require specializing that method for all available point types, since I don't see an easy way to detect the last padding elements.

I agree that, if we wanted to detect and remove padding elements, this would be required. I do think it would be a nice feature, but as stated would only apply to the trailing padding elements.

In my case, am ok with having the padding elements in my `Eigen` matrix. I want to use `Eigen` semantics for obtaining zero-copy slices of the resultant matrix, but I still need to recover the correct `rgb` values. My surprise came from the fact that the `rgb` data was not interpreted as a single `float rgb`, but instead by its 4 individual struct fields.

**Comment by SergioRAgostinho** [comment]
> My surprise came from the fact that the rgb data was not interpreted as a single float rgb, but instead by its 4 individual struct fields.

This is not exactly true. Your rgb data is only on the first float (fifth in the OP example). Out of those (last) 4 float components you're seeing, the last 3 are trash.

**Comment by kunaltyagi** [comment]
Closing since not a bug. Proper stride is provided for advanced usage.
