### ISSUE TITLE
PCD files generated with PCL 1.8 in PointXYZRGB format does not compatible with PCD files saved with PCL 1.6.0. 

### ISSUE THREAD

**Issue by nikkadim** [PointCloudLibrary/pcl#1710]
PCD files generated with PCL 1.8 in PointXYZRGB format does not compatible with PCD files saved with PCL 1.6.0. 

If I load PCD-file saved with PCL 1.6 in program compiled with 1.8 and then save it as PCD the RGB value will changed:

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 1942464
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1942464
DATA ascii
[...]
66.873619 -91.371956 773.60254 9.8649324e-039
66.99012 -91.368729 773.57526 9.7727368e-039
67.108971 -91.368729 773.57526 9.5883455e-039
67.227821 -91.368729 773.57526 9.4961499e-039
67.349045 -91.371956 773.60254 9.5883455e-039
67.470276 -91.375175 773.62976 9.4961499e-039
67.589142 -91.375175 773.62976 9.4961499e-039
67.715157 -91.384834 773.71161 9.4961499e-039
[...]
```

PCD file from PCL 1.8.0

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 1942464
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1942464
DATA ascii
[...]
66.873619 -91.371956 773.60254 7039851
66.99012 -91.368729 773.57526 6974058
67.108971 -91.368729 773.57526 6842472
67.227821 -91.368729 773.57526 6776679
67.349045 -91.371956 773.60254 6842472
67.470276 -91.375175 773.62976 6776679
67.589142 -91.375175 773.62976 6776679
67.715157 -91.384834 773.71161 6776679
[...]
```

**Comment by SergioRAgostinho** [comment]
Are you having any type of error reading the pointcloud or did you just got scared because you saw a different number in the colour column? It's just a different representation, bitwise they are (or should be) similar. 

We are progressively dropping the float representation of colour because it raised issues if you had to use the alpha component.

**Comment by nikkadim** [comment]
I have some software compiled with old PCL version (1.6), and it does not read correctly new PCL format.
Any workaround to save old PCD format from new PCL 1.8?

**Comment by SergioRAgostinho** [comment]
Do the following, compile the repo as it is right now, save that PCD file again, and change the `FIELDS` line to 
```
FIELDS x y z rgba
```
let me know if it works. Providing backwards compatibility is desirable, but we probably can't do it without breaking the ABI at this point, which means it can done on 1.9.0.

**Comment by nikkadim** [comment]
No, "rgba" does not help.

**Comment by taketwo** [comment]
Also in the program that loads PCD files change `PointXYZRGB` into `PointXYZRGBA`.
