### ISSUE TITLE
Error: invalid device function    /pcl/gpu/octree/src/cuda/octree_host.cu:64

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1712]
Good day,

I have compiled PCL with GPU functionaility, and I've run the example file (https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/segmentation/src/seg.cpp)

I have a geforce 1070 with the latest version of cuda 7.5 installed

None of the CUDA PCL Libraries are working
## Your Environment

- Operating System and version: Ubuntu 14.04 LTS
- Compiler: gcc 4.8 and CUDA 7.5 on a 1070
- PCL Version: Trunk 1.8
## Expected Behavior

CUDA Sample codes should run. /pcl/cuda/samples
## Current Behavior

Crashing

```

INFO: PointCloud_filtered still has 30146 Points 
CPU Time taken: 0.08s
PointCloud representing the Cluster: 13418 data points.
PointCloud representing the Cluster: 13145 data points.
PointCloud representing the Cluster: 186 data points.
PointCloud representing the Cluster: 165 data points.
PointCloud representing the Cluster: 136 data points.
PointCloud representing the Cluster: 123 data points.
INFO: starting with the GPU version
Error: invalid device function  /home/user/pcl/gpu/octree/src/cuda/octree_host.cu:64
```
## Possible Solution

No idea
## Code to Reproduce

Install CUDA 7.5 on 14.04
Compile pcl/cuda/samples
run any of them

**Comment by SergioRAgostinho** [comment]
@soulslicer the issue template exists for a reason. Please modify your post to conform to it.

**Comment by soulslicer** [comment]
modified. also, does this mean i have to modify the source code and remove the cudaSafeCall calls in that particular file?

**Comment by SergioRAgostinho** [comment]
> modified.

Thanks. 

> also, does this mean i have to modify the source code and remove the cudaSafeCall calls in that particular file?

No. I'm not sure about the other guys, but I personally don't have the hardware to test it, so I rarely touch on cuda related code. 

> Also that error is from 2012, hasnt pcl trunk been updated to fix this, its been years

But the beauty of open source projects is that you can do something yourself about it and contribute back. :) From what I understood the issue is with the use of the function when cudaToolkit is 5 or bigger. Start the pull request telling you want to address the issue and asking suggestions on how to proceed with it and me and the other guys will guide you from there.

**Comment by soulslicer** [comment]
Any update on this bug? How come no one else with similar hardware to mine has it

**Comment by sjdrc** [comment]
@soulslicer I managed to get gpu octree code running by installing CUDA 8 and the latest nvidia driver and using -DCUDA_ARCH_BIN="6.1" -DCUDA_ARCH_PTX="6.1". I have a GTX 1080.

**Comment by soulslicer** [comment]
Very nice. I will look into this

**Comment by soulslicer** [comment]
I just tried this again:

Still getting Error: invalid device function	/home/raaj/pcl/gpu/octree/src/cuda/octree_host.cu:64

**Comment by soulslicer** [comment]
Wow..okay, it seems i specifically need to set my -DCUDA_ARCH_BIN="6.1" flags to 6.0 and 6.1. And remove all the older ones. That fixes the issue and it now works.

**Comment by Zeppelin5** [comment]
Is there any way to solve this with C++ code in Visual Studio, not in Cmake

**Comment by Goldesel23** [comment]
I had the same problem. I tried to compile only with -DCUDA_ARCH_BIN="5.0" since I have a NVIDIA GTX 960M, but the problem persists. I also have CUDA 8.0. 

when I run octree_device.build(); the program ends without any message. 

Does anybody know how to solve this?

**Comment by chenhonghua** [comment]
@soulslicer 
Hi, I set my DCUDA_ARCH_BIN the same with you, but the problem still existed. 
Any suggestions?

**Comment by mwl1993** [comment]
Hi,i have the same problem, I set my DCUDA_ARCH_BIN with my GPU,like you ,but the problem still existed.Does anybody know how to solve this? Please

**Comment by caibf** [comment]
> @soulslicer the [issue template](https://github.com/PointCloudLibrary/pcl/blob/master/.github/issue_template.md) exists for a reason. Please modify your post to conform to it.
> 
> In the meantime read [this](https://devtalk.nvidia.com/default/topic/525084/what-happened-to-cudasafecall-in-v5-0-/) and remove that `cudaSafeCall` "wrapper" to see if that's the issue.

@soulslicer Hi, I follow your instructions that replace `cudaSafeCall( cudaFuncGetAttributes(&attrs, get_cc_kernel) );` with `cudaFuncGetAttributes(&attrs, get_cc_kernel);`, the runtime error now turn to `Error: This must be compiled for compute capability >= 2.0      <Path>\pcl-pcl-1.9.1\gpu\octree\src\octree.cpp:71`. 

What't wrong with it? Could you help me?

My coding environment
- Operating System: Windows 10(1909)
- IDE: Visual Studio 2017 Community
- PCL: 1.9.1（enabled GPU, CUDA）
- Graphics Card: GeForce GT 730
- CMake: 3.11

**Comment by kunaltyagi** [comment]
> compute capability >= 2.0

CUDA SDK or hardware is too old. See the [lists in this section and next](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

**Comment by caibf** [comment]
> > compute capability >= 2.0
> 
> CUDA SDK or hardware is too old. See the [lists in this section and next](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

Thanks @kunaltyagi. From the [official website](https://developer.nvidia.com/cuda-gpus), I know the compute capability of my Graphics Card is 3.5. And the version of CUDA SDK is 10.0.

**Comment by haritha-j** [comment]
@caibf Are your nvidia drivers up-to date? [this link](https://github.com/alicevision/meshroom/issues/260 ) mentions that this issue may be fixed with a driver update.
