### ISSUE TITLE
PCLVisualizer segmentation fault

### ISSUE THREAD

**Issue by holazollil** [PointCloudLibrary/pcl#1714]
- Operating System and version: Ububtu 15.04
- Compiler: gcc 4.8
- PCL Version: 1.8

VTK version : 7.0 

I want to use pcl viewer. But I could not use pclviewer class. I get a segmentation fault error using below code : 

 `pcl::visualization::PCLVisualizer *viewer = new pcl::visualization::PCLVisualizer("3D Viewer");`

**Comment by VictorLamoine** [comment]
Can you provide a full example code to reproduce the bug?
Can you compile in debug mode and provide a backtrace?

This code works fine with PCL latest trunk (46cb8fe) and VTK 7.0

```cpp
#include "pcl/common/common_headers.h"
#include "pcl/io/obj_io.h"
#include "pcl/io/ply_io.h"
#include "pcl/io/vtk_lib_io.h"
#include "pcl/visualization/pcl_visualizer.h"

int main()
{
  pcl::PolygonMesh mesh;
  pcl::io::loadPolygonFile("suzanne.stl", mesh);
  pcl::visualization::PCLVisualizer viewer;
  viewer.addPolygonMesh(mesh);
  viewer.spin();
  return 0;
}
```

```bash
$ ldd test_pcl_1 | grep libvtkCommonCore
	libvtkCommonCore-7.0.so.1 => /usr/local/lib/libvtkCommonCore-7.0.so.1 (0x00007fc359137000)
```

**Comment by holazollil** [comment]
I run this code on terminal. 
`pcl::visualization::PCLVisualizer viewer2;` throws segmentation fault error due intercative->Initialiye() line in pcl_viewer.cpp.

**Comment by holazollil** [comment]
It is interactor error.

If I set second parameter as false, I dont get seg error. But I could not show viewer screen.

`pcl::visualization::PCLVisualizer *viewer = new pcl::visualization::PCLVisualizer("3D Viewer", false);`

**Comment by VictorLamoine** [comment]
```cpp
#include <pcl/visualization/pcl_visualizer.h>

int main()
{
  pcl::visualization::PCLVisualizer::Ptr viewer(new pcl::visualization::PCLVisualizer("PCLVisualizer", false));
  //int viewPlane = -1;
  //viewer->createViewPort(0.0, 0.0, 1.0, 1.0, viewPlane);
  viewer->addCoordinateSystem(5.0);
  viewer->setBackgroundColor(0.2, 0.2, 0.2/*, viewPlane*/);
  return 0;
}
```

I cannot reproduce your issue on my machine with this code. It still works with the viewport creation un-commented.

**Comment by holazollil** [comment]
If you want to produce the issue, you run `pcl::visualization::PCLVisualizer *viewer = new pcl::visualization::PCLVisualizer("3D Viewer")); ` not false value.

**Comment by VictorLamoine** [comment]
It works perfectly with the default behavior (PCL handles the interactor creation), still no segfault.

**Comment by holazollil** [comment]
What is your vtk version? I use vtk7.0

**Comment by haldersbuschd** [comment]
I have the same problem.. Are there any news on that issue?

**Comment by Logrus** [comment]
I have tried it just now and I confirm that everything works fine.
I use VTK 7.1 and PCL 1.8 on Ubuntu 16.06 LTS

The code I used:

``` c++
#include <pcl/visualization/pcl_visualizer.h>

int main()
{
  pcl::visualization::PCLVisualizer *viewer = new pcl::visualization::PCLVisualizer("3D Viewer");
  viewer->addCoordinateSystem(5.0);
  viewer->setBackgroundColor(0.2, 0.2, 0.2);
  while (!viewer->wasStopped ())
     viewer->spinOnce (100);

  return 0;
}

```

Please try to run program with gdb and show backtrace.

**Comment by nizar-sallem** [comment]
@holazollil, do you have VTK installed by the system or are you installing it ? If installing, are you sure you are properly linking against it ?

**Comment by holazollil** [comment]
I don't remember completely. But I think my pcl version was incompatible.
It didn't work with pcl 1.8. I installed pcl 1.7 and it worked.

2017-03-26 16:12 GMT+03:00 nizar sallem <notifications@github.com>:

**Comment by rickyyunjiao** [comment]
I have the same problem. 
I use VTK 5.8 and PCL 1.7 on Ubuntu 14.04 LTS  QT5.4.
Then, I add CONFIG -= qt to the '.pro' file.
Problem solved!

**Comment by inckagan** [comment]
Hi, I have a quite similar problem.

I am able to run pcl tutorial examples without any trouble but when I combine it with a simple freenect2 code which supposed to give x, y, z coordinates to the pcl cloud I get segmentation fault error. Any idea would be appreciated.

Regards

**Comment by meng-zha** [comment]
I have the same "segmentation fault" problem using pcl-1.9.1 and vtk-8.2 while trying a simple pcl visulization. 
I finally find that you should build pcl of the "release" version.
There may be a bug in the "debug" version.

**Comment by kunaltyagi** [comment]
OP seems to be stuck on VTK 5.8

**Comment by huand** [comment]
basic cloud_viewer example segfaults with vtk-9.1.0 and pcl-1.12.0 on Ubuntu 21.10.

**Comment by larshg** [comment]
> basic cloud_viewer example segfaults with vtk-9.1.0 and pcl-1.12.0 on Ubuntu 21.10.

Could you open a new ticket with as much information about stack trace etc. so we could try look at it.

**Comment by huand** [comment]
vscode CALL STACK tells me its the line

`while (XPending((*rwi)->DisplayId) != 0)`

in `VTK-9.1.0/Rendering/UI/vtkXRenderWindowInteractor.cxx` in function `StartEventLoop()`

**Comment by huand** [comment]
i also get a bunch of warnings
```
F3892640]vtkOpenGLPolyDataMapper:306   WARN| vtkOpenGLPolyDataMapper::GetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetVertexShaderCode instead.
```
