### ISSUE TITLE
toPCLPointCloud2 crashes if cloud has no points

### ISSUE THREAD

**Issue by magro11** [PointCloudLibrary/pcl#1716]
Dear PCL Team,

the method toPCLPointCloud2 (conversion.h) crashes in line 257 if the incoming cloud contains no points:

`memcpy (&msg.data[0], &cloud.points[0], data_size);`

since data_size is 0.

My environment: Visual Studio 2013, 64bit, PCL 1.8.0 (current master branch), Win 7.

Would it be possible, to replace the line by:

`
if (data_size)
{
    memcpy (&msg.data[0], &cloud.points[0], data_size);
}
`

Cheers
Marc

**Comment by SergioRAgostinho** [comment]
The issue is not so much the data_size being, the function can cope with it as long as the pointers you are providing to it are valid. In this particular case, they aren't. This is an issue indeed but I'm not sure your suggestion is the best fix.

**Comment by SergioRAgostinho** [comment]
It actually is. Please submit a pull request with the changes.
