### ISSUE TITLE
loadOBJFile() segfaults when the OBJ file contains per-face normals

### ISSUE THREAD

**Issue by mikhail-matrosov** [PointCloudLibrary/pcl#1718]
- Operating System and version: Ubuntu Linux 15.10, 4.2.0-16-generic. 
- Compiler: gcc 5.2.1
- PCL Version: 1.8 (commit 46cb8fe)

An OBJ file can be composed in such a way, that vertices have per-face normals, so the file can end up having different number of "vn" entries than "v" entries. E.g. each vertex of a cube has 3 normals - one for each adjacent face - that gives you only 8 "v" entries and 24 "vn" entries. In this case pcl::io::loadOBJFile() will cause a segmentation fault, probably because of trying to read more normals than there's space available in the cloud.
## Expected Behavior

Correctly load an OBJ file with multiple vertex normals (see an **example.obj** in an attached file - works fine for Blender and Meshlab).
## Current Behavior

`*** Error in ./pclTest: free(): invalid next size (normal): 0x0000000001ab7aa0 ***`
OR
`Segmentation fault (core dumped)`
## Possible Solution

As far as I understand, there's currently no proper way to handle multiple normals for each vertex in PCL. As a stub I suggest detecting this situation and printing an error. A slightly better solution would be to create multiple copies of such vertices but with corresponding vertex normals and linking faces to them accordingly.

[pcl_loadOBJ_issue.zip](https://github.com/PointCloudLibrary/pcl/files/467353/pcl_loadOBJ_issue.zip)

**Comment by SergioRAgostinho** [comment]
For PointCloud types I don't think it makes sense to support it, but for the Mesh types I would expect this be supported.

**Comment by kunaltyagi** [comment]
Present since 1.9.0 and added via 67235435a1fadc6361e68ee4a76e1ebeb69e07d6
