### ISSUE TITLE
Build PCL Without VTK...

### ISSUE THREAD

**Issue by jiapei100** [PointCloudLibrary/pcl#1727]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Ubuntu 16.04.1
* Compiler: GCC/GCC 5.4.0
* PCL Version: Git, 1.8.0+

## Expected Behavior

Just want to build PCL without VTK. That is to say: I only need to save the file in some particular 3D format, but I can view 3D object in meshlab or some other 3D software, instead of VTK.

The reason why? VTK is too heavy, which clearly brought the inconvenience.

Can anybody give me a hint?

Cheers

**Comment by VictorLamoine** [comment]
```
cmake ../src/ -DWITH_VTK=OFF
```
