### ISSUE TITLE
All in one installed issue

### ISSUE THREAD

**Issue by mxgbs** [PointCloudLibrary/pcl#1729]
Operation System: win10 version
Compiler Visual Studio 2012
 PCL1.8.0

After installed, try to run a test case. However, following error occurred:
 1>LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc110-mt-gd-1_61.lib'
I checked the C:\Program Files (x86)\PCL 1.8.0\3rdParty\Boost\lib\, the file in that is libboost_thread-cv120-mt-gd-1_61.lib instead. Could you please help with issue? Is there any easy way for me to fix this?

**Comment by UnaNancyOwen** [comment]
Perhaps, You've installed PCL using the All-in-one Installer for MSVC2013 (VC12).
But, It doesn't include pre-built binaries for MSVC2012 (vc11).
You will need to use the MSVC2013.

If you want to use MSVC2012, You need to build PCL and 3rdParty for MSVC2012 yourself.
In that case, This [documents](https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-8-0-md) would be helpful for you.

**Comment by mxgbs** [comment]
Thanks.
