### ISSUE TITLE
command not found: pcd_viewer on Macos

### ISSUE THREAD

**Issue by universewill** [PointCloudLibrary/pcl#1732]
I install pcl using command "brew install pcl".
I run command "pcl_viewer 1.pcd" in terminal but the command is not found.

I find the pcl_viewer binary file in path:
/usr/local/Cellar/pcl/1.8.0_2/pcl_viewer.app/Contents/MacOS

How can i fix this problem?

**Comment by jspricke** [comment]
Please fill this with the brew people here: https://github.com/Homebrew/homebrew-science/
