### ISSUE TITLE
Add 6.1 for default CUDA_ARCH_BIN

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#1733]
Currently after cloning the latest repo and do

```
ccmake ..
```

In the CUDA_ARCH_BIN section it by defaults only shows 3.0 3.5 5.0 5.2. I suggest adding in 6.1 for the newest Pascal GPUs that recently comes out.

**Comment by UnaNancyOwen** [comment]
@jasjuang I sent a pull request. Please check it.

**Comment by jasjuang** [comment]
Thanks for creating the pull request, I believe cuda compatibility 8.0 does not exist as shown in [here](https://en.wikipedia.org/wiki/CUDA), the newest seems to be 7.1. That might be the reason that the pull request doesn't pass travis CI.

**Comment by UnaNancyOwen** [comment]
@jasjuang "8.0" is CUDA SDK version.
Compute Capability 6.x (Pascal) is supported from CUDA SDK 8.0 and later.

This PR is not cause the test fails.
The problem of test is being discussed here (#1785).

**Comment by jasjuang** [comment]
oh I see you are right, hope they merge your PR soon!

**Comment by UnaNancyOwen** [comment]
@jasjuang Thank you for checking!

**Comment by jspricke** [comment]
Done, thx!
