### ISSUE TITLE
No option to run PCL tools WITHOUT visualization

### ISSUE THREAD

**Issue by mravanba** [PointCloudLibrary/pcl#1736]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

I'm trying to use the command line tools such as "pcl_mesh_sampling" on a batch of files. Unfortunately, there does not seem to be any option for disabling the viewer. One has to manually close the viewer after application of the command-line tool to each individual file.

Am I missing something?

## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc
* PCL Version: 1.7

## Expected Behavior
There should be an option or and environment variable for no-display

**Comment by VictorLamoine** [comment]
I agree this is not practical at all, the code is right here;
https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh_sampling.cpp

You can comment the visualization section or even better; add an option to disable visualisation.

Would you be so kind as to make a pull request?

**Comment by mravanba** [comment]
Unfortunately, I have a hard time compiling this from source on my ubuntu 16.04. So I'm running it using the default apt-get installation. I thought it best to report the problem here so as to find out if there's a work-around or if not then as a feature-request.

**Comment by VictorLamoine** [comment]
Use this CMake file:
```cmake
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(pcl-mesh_sampling)

find_package(PCL 1.7.1 EXACT)
#find_package(PCL 1.8.0 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (mesh_sampling mesh_sampling.cpp)
set_property(TARGET mesh_sampling APPEND_STRING PROPERTY COMPILE_FLAGS "-Wall -Wextra")
target_link_libraries (mesh_sampling ${PCL_LIBRARIES})

```

You will probably get this compile error:
```bash
In file included from /usr/include/pcl-1.7/pcl/visualization/point_cloud_color_handlers.h:725:0,
                 from /usr/include/pcl-1.7/pcl/visualization/point_cloud_handlers.h:42,
                 from /usr/include/pcl-1.7/pcl/visualization/common/actor_map.h:40,
                 from /usr/include/pcl-1.7/pcl/visualization/pcl_visualizer.h:47,
                 from /home/dell/code/mesh_sampling/src/mesh_sampling.cpp:38:
/usr/include/pcl-1.7/pcl/visualization/impl/point_cloud_color_handlers.hpp: In member function ‘virtual bool pcl::visualization::PointCloudColorHandlerHSVField<PointT>::getColor(vtkSmartPointer<vtkDataArray>&) const’:
/usr/include/pcl-1.7/pcl/visualization/impl/point_cloud_color_handlers.hpp:254:9: error: return-statement with no value, in function returning ‘bool’ [-fpermissive]
         return;
         ^~~~~~
/usr/include/pcl-1.7/pcl/visualization/impl/point_cloud_color_handlers.hpp:292:9: error: return-statement with no value, in function returning ‘bool’ [-fpermissive]
         return;
         ^~~~~~
```

You can fix the file (`usr/include/pcl-1.7/pcl/visualization/impl/point_cloud_color_handlers.hpp`) with the updated function;
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp#L251

**Comment by VictorLamoine** [comment]
I had no problem compiling PCL on Ubuntu 16.04, please ask a question on [pcl-users](www.pcl-users.org) if you have troubles.

**Comment by mravanba** [comment]
Thanks for the CMake file. I will follow up on this on the mailing list if this is not resolved.
