### ISSUE TITLE
OpenNIGrabber and pcl::visualization::ImageViewer SegFault

### ISSUE THREAD

**Issue by idini** [PointCloudLibrary/pcl#1739]
Hi all. I'm trying to use Pcl library with Kinect for my master thesis. 

When i'm tried to add an ImageViewer modifying "openni_grabber_depth_example" located in https://github.com/PointCloudLibrary/pcl/tree/master/io/tools, it compile but when i execute the code, it crash with a Segmentation Fault error when i call **FillRGB**. 

What do i do wrong? 

**Environment**
*Operating System and version: Ubuntu 16.04
*Compiler: Gcc 6
*PCL version: 1.7

**Expected Behavior**
Expect to show a camera stream frame in pcl visualizer

**Current Behavior**
Window is created but program crash at the first frame

**Code to Reproduce**

`
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/io/openni_grabber.h>
#include <pcl/common/time.h>
#include <pcl/console/parse.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/visualization/boost.h>
#include <pcl/visualization/image_viewer.h>

using namespace std; 

class SimpleOpenNIProcessor 
{ 
  public: 
    bool save; 
    openni_wrapper::OpenNIDevice::DepthMode mode; 

    SimpleOpenNIProcessor (openni_wrapper::OpenNIDevice::DepthMode depth_mode = openni_wrapper::OpenNIDevice::OpenNI_12_bit_depth) : mode (depth_mode) {} 

    void imageCallback (const boost::shared_ptr<openni_wrapper::Image>& image){ 
      boost::mutex::scoped_lock lock (image_mutex_); 
      image_ = image; 
      cout << image->getFrameID() << endl; 
      if (image->getEncoding () != openni_wrapper::Image::RGB) 
      { 
        if (rgb_data_size_ < image->getWidth () * image->getHeight ()) 
        { 
          if (rgb_data_) 
            delete [] rgb_data_; 
          rgb_data_size_ = image->getWidth () * image->getHeight (); 
          rgb_data_ = new unsigned char [rgb_data_size_ * 3]; 
        } 
        image_->fillRGB (image_->getWidth (), image_->getHeight (), rgb_data_); 
      } 

      /*if (++count == -1) 
      { 
        double now = pcl::getTime (); 
        std::cout << "got image. Average framerate: " << double(count)/double(now - last) << " Hz" <<  std::endl; 
        std::cout << "Depth baseline: " << d_img->getBaseline () << " and focal length: " << d_img->getFocalLength () << std::endl; 
        count = 0; 
        last = now; 
      }*/ 
    } 

    void keyboard_callback (const pcl::visualization::KeyboardEvent& event, void*) 
    { 
      if (event.getKeyCode ()) 
        cout << "the key \'" << event.getKeyCode() << "\' (" << event.getKeyCode() << ") was"; 
      else 
        cout << "the special key \'" << event.getKeySym() << "\' was"; 
      if (event.keyDown()) 
        cout << " pressed" << endl; 
      else 
        cout << " released" << endl; 
    } 
    
    void mouse_callback (const pcl::visualization::MouseEvent& mouse_event, void*) 
    { 
      if (mouse_event.getType() == pcl::visualization::MouseEvent::MouseButtonPress && mouse_event.getButton() == pcl::visualization::MouseEvent::LeftButton) 
      { 
        cout << "left button pressed @ " << mouse_event.getX () << " , " << mouse_event.getY () << endl; 
      } 
    } 

    void run (){ 
      save = false; 

      // create a new grabber for OpenNI devices 
      pcl::OpenNIGrabber interface; 

      // Set the depth output format 
      interface.getDevice ()->setDepthOutputFormat (mode); 

      // make callback function from member function 
      boost::signals2::connection image_connection; 
      image_viewer.reset (new pcl::visualization::ImageViewer ("PCL OpenNI image")); 
      image_viewer->registerMouseCallback (&SimpleOpenNIProcessor::mouse_callback, *this); 
      image_viewer->registerKeyboardCallback(&SimpleOpenNIProcessor::keyboard_callback, *this); 
      boost::function<void (const boost::shared_ptr<openni_wrapper::Image>&) > image_cb = boost::bind (&SimpleOpenNIProcessor::imageCallback, this, _1); 
      image_connection = interface.registerCallback (image_cb); 
            
      bool image_init = false; 
    

      // start receiving point clouds 
      interface.start (); 

      std::cout << "<Esc>, \'q\', \'Q\': quit the program" << std::endl; 
      std::cout << "\' \': pause" << std::endl; 
      char key; 
      while I(image_viewer && !image_viewer->wasStopped ()) { 
        boost::shareId_ptr<openni_wrapper::Image> image; 
        image_viewer->spinOnce(); 
        // See if we can get an image 
        if (image_mutex_.try_lock ()) 
        { 
          image_.swap (image); 
          image_mutex_.unlock (); 
        } 

        if (image) 
        { 
          if (!image_init) 
          { 
            image_viewer->setPosition (0, 0); 
            image_viewer->setSize ( image->getWidth (), image->getHeight ()); 
            image_init = !image_init; 
          } 

          if (image->getEncoding() == openni_wrapper::Image::RGB) 
            image_viewer->addRGBImage (image->getMetaData ().Data (), image->getWidth (), image->getHeight ()); 
          else 
            image_viewer->addRGBImage (rgb_data_, image->getWidth (), image->getHeight ()); 
          image_viewer->spinOnce (); 
        } 
      } 
        interface.stop (); 
      
        image_connection.disconnect (); 
        if (rgb_data_) 
          delete[] rgb_data_; 
    } 

    
    boost::mutex image_mutex_; 
    boost::shared_ptr<openni_wrapper::Image> image_; 
    unsigned char* rgb_data_; 
    unsigned rgb_data_size_; 
    boost::shared_ptr<pcl::visualization::ImageViewer> image_viewer; 
  }; 

 int main (int argc, char **argv){ 
  int mode = openni_wrapper::OpenNIDevice::OpenNI_12_bit_depth; 
  pcl::console::parse_argument (argc, argv, "-mode", mode); 

  SimpleOpenNIProcessor v (static_cast<openni_wrapper::OpenNIDevice::DepthMode> (mode)); 
  v.run (); 
  return (0); 
} 
`

  
`
cmake_minimum_required(VERSION 2.8 FATAL_ERROR) 

project(openni_grabber_depth_example) 

#SET(CMAKE_CXX_COMPILER g++) 

find_package(PCL 1.4 REQUIRED) 
find_package(Qt4 4.7 REQUIRED) 

include_directories(${PCL_INCLUDE_DIRS} ${QT_INCLUDE_DIRS}) 

include(${QT_USE_FILE}) 

link_directories(${PCL_LIBRARY_DIRS} ${QT_LIBRARY_DIRS}) 
add_definitions(${PCL_DEFINITIONS})# -DQT_NO_KEYWORDS ${QT_DEFINITIONS}) 
ADD_DEFINITIONS (-DQT_NO_KEYWORDS ${QT_DEFINITIONS}) 

SET(openni_grabber_depth_example_SOURCES openni_grabber_depth_example.cpp ) 

QT4_WRAP_CPP(qtpcl_HEADERS_MOC ${openni_grabber_depth_example_HEADERS}) 

add_executable (openni_grabber_depth_example ${openni_grabber_depth_example_SOURCES}) 
target_link_libraries (openni_grabber_depth_example ${PCL_LIBRARIES} ${QT_LIBRARIES}) 
`

Thanks.

**Comment by SergioRAgostinho** [comment]
This is a bug tracker. Please use our mailing list for these types of questions.
