### ISSUE TITLE
pointclouds.org is down again :( 

### ISSUE THREAD

**Issue by saranshvora** [PointCloudLibrary/pcl#1743]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

**Comment by hanshammel1337** [comment]
Yes, it is :(

I hope the renew the site, as they said at hackfest in June. The tutorials are outdated and last news are from 2014... 

The maillist are also dead. There is a mess with PCL users, PCL developers and Github issues.
Maybe it is difficult for a small team to manage a projekt like this, but an informative und updated homepage should be the basis beside of the code in github.

**Comment by jspricke** [comment]
We are still working on the new repo, please mail us if you want to help. Closing.
