### ISSUE TITLE
PCL website is down as of Oct 25th

### ISSUE THREAD

**Issue by bloyl** [PointCloudLibrary/pcl#1744]
Neither docs.pointclouds.org nor pointclouds.org are responding as of yesterday (oct 25th) in the morning.

An issue was posted on the users-list ( http://www.pcl-users.org/http-docs-pointclouds-org-is-down-td4043117.html ) but no one has responded.

Is this just a hiccup or something more serious?

**Comment by rbrusu** [comment]
fixed, thanks for reporting! damn spammers/hackers, got nothing else better to do :-P

**Comment by bloyl** [comment]
The site was up last night, however it is down again as of Oct 27th 9AM eastern.
