### ISSUE TITLE
logic error about print encoding statistics result in octree_pointcloud_compression.hpp

### ISSUE THREAD

**Issue by fengjim** [PointCloudLibrary/pcl#1745]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

- Operating System and version: any
- Compiler: any
- PCL Version: master branch
## Expected Behavior

in octree_pointcloud_compression.hpp, around line 153# to 156#, it checks member 'i_frame_' to decide print 'Encoding Frame: Intra frame' or 'Encoding Frame: Prediction Frame'. However, 'i_frame_' will always be set as 'false' after switch buffer once encoding is done, see line 141#. Consequently statistic result always show 'Encoding Frame: Prediction Frame'. 

Line 141# 'i_frame_ = false;' should be moved down after printing statistics.

**Comment by SergioRAgostinho** [comment]
Can you please file a pull request. Thanks.

**Comment by fengjim** [comment]
Thanks, SergioRAgostinho!

Pull Request is sent: https://github.com/PointCloudLibrary/pcl/pull/1749

**Comment by mvieth** [comment]
I guess since the pull request is merged, this issue can be closed. Thanks!
