### ISSUE TITLE
Compression time using octree increased slowly

### ISSUE THREAD

**Issue by fengjim** [PointCloudLibrary/pcl#1746]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

- Operating System and version: Ubuntu 14.04
- Compiler: gcc
- PCL Version: 1.8.0
## Expected Behavior

the time to compress the same static point cloud data should be almost the same. 
## Current Behavior

I'm using the following method to encoding one static point cloud (point cloud data from file milk_cartoon_all_small_clorox.pcd) continuously:

OctreePointCloudCompression<PointT, LeafT, BranchT, OctreeT>::encodePointCloud (const PointCloudConstPtr &cloud_arg, std::ostream& compressed_tree_data_out_arg) 

the profile is the default built-in profile LOW_RES_ONLINE_COMPRESSION_WITH_COLOR, and no matter the output stream is a new stream like the following or socket stream
    std::stringstream ss;
    mEncoder->encodePointCloud(pointcloud, ss);

What was observed in the statistic result was that the compression time slightly went up.

it doesn't look right logically, because theorectially if the input point cloud data is the same/static, the octree compression should cost nearly the same time for p-frames:

**\* POINTCLOUD ENCODING ***
Frame ID: **1**
Encoding Frame: Prediction frame
Number of encoded points: 25355
XYZ compression percentage: 2.720371%
XYZ bytes per point: 0.326444 bytes
Color compression percentage: 24.626307%
Color bytes per point: 0.985052 bytes
Size of uncompressed point cloud: 396.171875 kBytes
Size of compressed point cloud: 32 kBytes
Total bytes per point: 1.311497
Total compression percentage: 8.196855
Compression ratio: 12.199801

finish encode: 1477560052296
time for encoding: **26**
start to encode: 1477560052296
**\* POINTCLOUD ENCODING ***
Frame ID: **2**
Encoding Frame: Prediction frame
Number of encoded points: 25355
XYZ compression percentage: 0.353974%
XYZ bytes per point: 0.042477 bytes
Color compression percentage: 24.626307%
Color bytes per point: 0.985052 bytes
Size of uncompressed point cloud: 396.171875 kBytes
Size of compressed point cloud: 25 kBytes
Total bytes per point: 1.027529
Total compression percentage: 6.422057
Compression ratio: 15.571335

finish encode: 1477560052322
time for encoding: **25**
....
**\* POINTCLOUD ENCODING ***
Frame ID: **50**
Encoding Frame: Prediction frame
Number of encoded points: 25355
XYZ compression percentage: 0.353974%
XYZ bytes per point: 0.042477 bytes
Color compression percentage: 24.626307%
Color bytes per point: 0.985052 bytes
Size of uncompressed point cloud: 396.171875 kBytes
Size of compressed point cloud: 25 kBytes
Total bytes per point: 1.027529
Total compression percentage: 6.422057
Compression ratio: 15.571335

finish encode: 1477560053695
time for encoding: **34**
start to encode: 1477560053695
## Code to Reproduce

It's quite easy to reproduce it. Just to read point cloud from file, and create one encoder to encode it frame-by-frame.
## Context

We're trying to transmit point cloud from one computer to another over internet. The increased encode/decode time would cause more latency (unexpected).

Does anyone see similar issue before? or I'm doing something in a wrong. 

Thanks in advance!

**Comment by fengjim** [comment]
See the attached capture time for different frames:

[compression_statistics.txt](https://github.com/PointCloudLibrary/pcl/files/555537/compression_statistics.txt)

**Comment by kunaltyagi** [comment]
Does this issue exist on PCL head?
