### ISSUE TITLE
PCL website is down Again

### ISSUE THREAD

**Issue by bloyl** [PointCloudLibrary/pcl#1747]

**Comment by midhunharikumar** [comment]
Website is down. Consistently for the past 3 days. Comes back in the evening though. Server issues ?

**Comment by bloyl** [comment]
At least last night, I posed an issue here. rbrusu responded and I assume brought the site back up.

Does any one know how to build local pcl documentation. There doesn't seem to be a cmake target and the instructions (pointclouds.org/documentation/tutorials/generate_local_doc.php) are of course hosted on the web site

**Comment by midhunharikumar** [comment]
I did a Wget on the docs page and pulled most of it locally but its not an elegant solution. Just for critical situations.

**Comment by SergioRAgostinho** [comment]
Up again.
