### ISSUE TITLE
Strange behavior with organized kinect2 pointcloud, when setting color: p.r, p.g, p.b vs. p.rgb

### ISSUE THREAD

**Issue by aeitel** [PointCloudLibrary/pcl#1751]
## Your Environment
* Operating System and version: Ubuntu 14.04.3
* Compiler: gcc 4.8.4
* PCL Version: 1.8

## Expected Behavior
I have an organized pointcloud from a Kinect2 device.
I am trying to set the color values, manually using the rgb image because it seems the rgb channel is broken in the original pcd file (see first snapshot). Therefore I load the image (.png) and set the rgb values in the cloud as specified in the code snippet.
This should work I guess, but it does not give the right colorization. It acually outputs the same cloud as the orginal one, which is already wrong:

      uint8_t r = rgb_img.at<cv::Vec3b>(y,x)[2], g = rgb_img.at<cv::Vec3b>(y,x)[1], b = rgb_img.at<cv::Vec3b>(y,x)[0];
      cloud->at(x,y).r =  r;
      cloud->at(x,y).g =  g;
      cloud->at(x,y).b =  b;

## Possible Solution
      // This produces the correct result (see second snapshot)
      uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);
      cloud->at(x,y).rgb = *reinterpret_cast<float*>(&rgb);

![screenshot from 2016-11-04 12 28 19](https://cloud.githubusercontent.com/assets/8167086/20004036/2f8ead5c-a28a-11e6-9f9f-b814e0663390.png)

![screenshot from 2016-11-04 12 27 23](https://cloud.githubusercontent.com/assets/8167086/20004023/186e143c-a28a-11e6-86c0-91dfa778283d.png)
## Code and Data
[colorize_cloud.tar.gz](https://github.com/PointCloudLibrary/pcl/files/571358/colorize_cloud.tar.gz)

**Comment by kunaltyagi** [comment]
I don't really grasp the difference between the two calls. 
* assigning to the anonymous struct members: `struct { uint8 b, g, r, a; };`
* assigning to the union: `union { struct Anon; float rgb; };`

```cpp
uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);

cloud->at(x,y).r = r; cloud->at(x,y).g = g; cloud->at(x,y).b = b;
// vs
cloud->at(x,y).rgb = *reinterpret_cast<float*>(&rgb);
```

Can you replicate the issue on master?

**Comment by kunaltyagi** [comment]
Actually, `uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);` might be the issue. Please use the struct members because the layout might not be what you're expecting
