### ISSUE TITLE
Color-based region growing segmentation tutorial needs to be revisited

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1752]
## Your Environment

* Operating System and version: Mac OSX 10.11.6
* Compiler: LLVM clang 3.8
* PCL Version: master

## Expected Behavior

It's hard to tell because the original tutorial didn't include pictures of the expected output, but I would assume that the intention was to have the individual objects seen in the original pointcloud with different colors segmented.
![screen shot 2016-11-06 at 20 00 47](https://cloud.githubusercontent.com/assets/1709142/20046178/dcf2d414-a45b-11e6-8c32-7532a3501cf6.png)

## Current Behavior

A big red blob 
![screen shot 2016-11-06 at 20 01 22](https://cloud.githubusercontent.com/assets/1709142/20046184/eb2d354c-a45b-11e6-80a3-b5177eebc12a.png)

## Code to Reproduce

Just ran the [tutorial](http://www.pointclouds.org/documentation/tutorials/region_growing_rgb_segmentation.php#region-growing-rgb-segmentation) with the specified [point cloud](https://raw.github.com/PointCloudLibrary/data/master/tutorials/region_growing_rgb_tutorial.pcd).

**Comment by tuturha** [comment]
I'm having an issue with the sane tutorial. It only detects 1 cluster wich size is 36838 points.

i'm not sure how i should work on with this.

**Comment by muzo583** [comment]
Yeah, it has a bug I think.

**Comment by taketwo** [comment]
@muzo583 You are welcome to fix this and submit a patch.

**Comment by muzo583** [comment]
![rgb](https://user-images.githubusercontent.com/16136052/39656257-36d81892-5007-11e8-86d0-78b8a757e439.png)

Dear all,
you can see my result on image. There is a interestingly wrong parameter at tutorial. I have changed the parameter of passthrough limit from 1 to 5. I don't know how to edit tutorial page. I am beginner at C++ and PCL.  Could you check it please? @taketwo 

Cheers, 
Mustafa
