### ISSUE TITLE
Wrong code in SAC NormalParallelPlane

### ISSUE THREAD

**Issue by nenadpol** [PointCloudLibrary/pcl#1754]
Documentation for SAC MODEL NORMAL PEARALLEL PLANE is clear "... In 
addition, the plane normal must lie parallel to an user-specified axis." 

So computed plane normal and user defined axis should be parallel within 
defined treshold . 
 
Take a look at the code: 
> ------------------------------------------------------- 
if (fabs (axis_.dot (coeff)) < cos_angle_) 
      return  (false); 
> ------------------------------------------------------- 
 
 axis_.dot(coeff) is cosinus (angle between plane normal and user defined 
 axis). 
 
cos_angle_ is cosinus ( defined treshold). 
 
 
If  axis_.dot(coeff) should be inside treshold then why is code returning 
FALSE?

**Comment by Chungzuwalla** [comment]
Is it because cosine of the angle gets smaller as the angle gets larger?  If angular threshold is 5° and coeff angle is 7°, return false, if coeff angle is 3°, don't return false.
7 > 5, cos(7°) < cos(5°).
3 < 5, cos(3°) > cos(5°).

**Comment by mvieth** [comment]
@Chungzuwalla is correct. Can this issue be closed?
