### ISSUE TITLE
Is there any advantage by using Nvidia Quadro card with PCL?

### ISSUE THREAD

**Issue by hanshammel1337** [PointCloudLibrary/pcl#1758]
hello,

will there be any performance differences when using a nvidia quadro card compared to a similar nvidia geforce card? i kown the differences for CAD applications, but does PCL with cuda get any boost by using a quadro card?

greetings

**Comment by VictorLamoine** [comment]
Please use our mailing list for questions: www.pcl-users.org.

In short: No, expect for the code that belongs in the [cuda](https://github.com/PointCloudLibrary/pcl/tree/master/cuda) module. As for visualisation, a high end graphics card (with appropriate drivers) helps visualizing big point clouds/meshes.
