### ISSUE TITLE
Error when compile PCL 1.8 on TX1

### ISSUE THREAD

**Issue by paulb24** [PointCloudLibrary/pcl#1765]
I'm trying to compile PCL 1.8 by following PCL site steops on TX1 with CUDA enable but my make (GNU Make 4.1) fail. I'm using Linux For Tegra R24.2.1

`/home/ubuntu/pcl-master/sample_consensus/include/pcl/sample_consensus/model_types.h:99:3: note: declared here
[ 16%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_sac_model_1point_plane.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 16%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_ransac.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:158: recipe for target 'sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o' failed
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o] Error 4
CMakeFiles/Makefile2:829: recipe for target 'sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all' failed
make[1]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target pcl_cuda_sample_consensus
[ 16%] Linking CXX shared library ../../lib/libpcl_cuda_sample_consensus.so
[ 16%] Built target pcl_cuda_sample_consensus
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2`

Thank you very much,
Paul

**Comment by jspricke** [comment]
You are running out of memory. Use cross compile, disable parallel build or use the packages in Debian ;). Btw. this is a issue tracker, please ask questions on the mailing list.

**Comment by paulb24** [comment]
Ok thank you, I will do that next time ;)
