### ISSUE TITLE
create point clouds using an equi density random point sampling on the faces of each object+source code+c++ site:github.com

### ISSUE THREAD

**Issue by tufei911** [PointCloudLibrary/pcl#1771]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version:Windows 64   
* Compiler:VS2013
* PCL Version:PCL 1.8.0

**Comment by SergioRAgostinho** [comment]
Please describe your problem appropriately, using the issue template properly. This issue report is incomprehensible.
