### ISSUE TITLE
error in SampleConsensusModelRegistration

### ISSUE THREAD

**Issue by zhufan** [PointCloudLibrary/pcl#1772]
## Your Environment

* OS: win10
* Compiler: vs2013
* PCL Version: the SHA is e66d90e5

I use Eigen 3.2.8 with pcl, and want to use ransac to slecet good pairs between too pointcloud, the code is:

    inliers.clear();
    pcl::SampleConsensusModelRegistration<zf::PointType>::Ptr model(new pcl::SampleConsensusModelRegistration<zf::PointType>(SourceCloud, sourceIndice));
    model->setInputTarget(TargetCloud, targetIndice);
	std::cout << "ransac indice size " << targetIndice.size() << std::endl;
    Eigen::VectorXf coeff;
    pcl::RandomSampleConsensus<zf::PointType> ransac(model, ransacThreshold);
    ransac.computeModel();

when the program execute computeModel, an error occur:

    [pcl::RandomSampleConsensus::computeModel] No samples could be selected!

after debug, I found it is because sample_dist_thresh_ is invalid
in file sample_consensus\sac_model_registration.h , line 284, the code:

    sample_dist_thresh_ = eigen_values.array ().sqrt ().sum () / 3.0;

eigen_values is (0, -0.000173772205, 2.01412167e-5)
because there is an negative number -0.000173772205， so the sqrt is invalid, and this caused my problem.
so, anybody knows how to solve this? Or is there some problem with my pointcloud?

**Comment by mvieth** [comment]
Sorry that you did not get any advice in the last four years. In case you still need it or anyone else comes across this issue:
Yes, those Eigen values definitely do not look right. To debug this further, it would be important to look at the covariance matrix from which the Eigen values are computed. There might be a problem with your point cloud, but that is difficult to say.
I am going to close this issue, but feel free to reopen it if you are still having trouble with this.
