### ISSUE TITLE
Conflicting software license issue in 4PCS & K-4PCS implementations

### ISSUE THREAD

**Issue by Chungzuwalla** [PointCloudLibrary/pcl#1775]
4PCS header file: [https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/ia_fpcs.h](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/ia_fpcs.h)

The license superficially appears to be a BSD 3-clause license.  The first line reads "Software License Agreement (BSD License)".
However a new condition "The use for research only (no for any commercial application)" has been added at line 13.  This addition is not part of the BSD license and is incompatible with it, as the BSD license allows commercial use.  The incompatible conditions need to be reconciled and made clear to users.

The same conflict affects the 4PCS implementation file and the K-4PCS files too.

**Comment by Chungzuwalla** [comment]
@theilerp are you able to do anything with this?  PCL is widely advertised as being BSD licensed, I am concerned that if your contribution couldn't be made BSD compatible it may have to be removed from PCL...

**Comment by jspricke** [comment]
That's indeed an issue, thanks for bringing it up. I noticed it already when packaging PCL for Debian and excluded it [there](https://anonscm.debian.org/cgit/debian-science/packages/pcl.git/tree/debian/copyright#n5). If @theilerp doesn't answer, I would propose to either remove it or move it to a non-free module, as opencv does.

**Comment by SergioRAgostinho** [comment]
Your change hasn't been committed to the pcl master yet, just to your personal fork. Why did it close the issue automatically?

**Comment by jspricke** [comment]
* Sérgio Agostinho <notifications@github.com> [2016-12-19 13:33]:
> Your change hasn't been committed to the pcl master yet, just to your personal fork. Why did it close the issue automatically? 

Oups, thanks for noticing. Pushed to master now.

Cheers Jochen
