### ISSUE TITLE
PolygonMesh visualization with color interpolation

### ISSUE THREAD

**Issue by rbregier** [PointCloudLibrary/pcl#178]
Hi, 
I would like to reopen issue 969 (http://dev.pointclouds.org/issues/969) regarding the
choice of a color interpolation method for PolygonMesh (not flat as default).

The solution proposed by Alexandru to use

``` cpp
setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_SHADING, pcl::visualization::PCL_VISUALIZER_SHADING_PHONG, "my_mesh_id");
```

 does not work with a PolygonMesh.

The ID of a PolygonMesh is not added to the attribute shape_actor_map_ of PCLVisualizer when `addPolygonMesh` is called, and thus when calling `setShapeRenderingProperties` the function quit with error message 

``` bash
"[setShapeRenderingProperties] Could not find any shape with id <%s>" in pcl/visualization/src/pcl_visualizer.cpp line 1435.
```

Is there a reason why the id of a PolygonMesh is added to the attribute `cloud_actor_map_` and not `shape_actor_map_` ?
(cf. addPolygonMesh in pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp line 1514)

Thanks,
Romain Brégier

**Comment by VictorLamoine** [comment]
Closing as this is now possible thanks to #1241 

Code example
---
```cpp
#include <pcl/console/parse.h>
#include <pcl/io/vtk_lib_io.h>
#include <pcl/visualization/pcl_visualizer.h>

using namespace pcl::visualization;
PCLVisualizer::Ptr viewer;

void keyboardEventOccurred(const KeyboardEvent& event, void* nothing)
{
  if (event.getKeySym() == "y" && event.keyDown()) // Flat shading
  {
    viewer->setShapeRenderingProperties(PCL_VISUALIZER_SHADING,
                                        PCL_VISUALIZER_SHADING_FLAT, "polygon");
  }
  else if (event.getKeySym() == "t" && event.keyDown()) // Gouraud shading
  {
    viewer->setShapeRenderingProperties(PCL_VISUALIZER_SHADING,
                                        PCL_VISUALIZER_SHADING_GOURAUD, "polygon");
  }
  else if (event.getKeySym() == "n" && event.keyDown()) // Phong shading
  {
    viewer->setShapeRenderingProperties(PCL_VISUALIZER_SHADING,
                                        PCL_VISUALIZER_SHADING_PHONG, "polygon");
  }
}

int main(int argc, char * argv[])
{
  std::vector<int> stl_file_indices = pcl::console::parse_file_extension_argument (argc, argv, ".stl");
  if (stl_file_indices.empty())
    PCL_ERROR ("Please provide one STL file as argument");

  pcl::PolygonMesh mesh;
  pcl::io::loadPolygonFileSTL(argv[stl_file_indices[0]], mesh);

  viewer.reset(new PCLVisualizer);
  viewer->registerKeyboardCallback(&keyboardEventOccurred, (void*) NULL);
  viewer->addPolygonMesh(mesh, "polygon");
  viewer->spin();
  return 0;
}
```

Flat
---
![flat](https://cloud.githubusercontent.com/assets/5566160/9568792/4b5151e0-4f55-11e5-9bd0-99750d0458de.png)

Phong
---
![phong](https://cloud.githubusercontent.com/assets/5566160/9568793/4df30bf0-4f55-11e5-91b0-85bb9ffea429.png)

**Comment by jpapon** [comment]
I think this needs to be re-opened if there isn't another issue for it already - the above code gives me the "Could not find any shape with id" error - it seems setShapeRenderingProperties is not looking in the cloud_actor_map_ where meshes are stored.

**Comment by zkl99999** [comment]
me too, same error
[setShapeRenderingProperties] Could not find any shape with id <polygon>!
[setShapeRenderingProperties] Could not find any shape with id <polygon>!
[setShapeRenderingProperties] Could not find any shape with id <polygon>!

**Comment by VictorLamoine** [comment]
I confirm the behavior, something is broken

**Comment by ShangxuanWu** [comment]
Is this issue fixed now?

**Comment by soulslicer** [comment]
Still broken

**Comment by SergioRAgostinho** [comment]
Pull requests are welcome.

**Comment by ricshaw** [comment]
This is also broken in setPointCloudRenderingProperties with a PolygonMesh. See code below:

viewer->addPolygonMesh(input_mesh_,"input_mesh",0);
viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_SHADING,
                                        pcl::visualization::PCL_VISUALIZER_SHADING_GOURAUD, "input_mesh",0);

This gives the error Unknown property (7) specified! However it does work with the PCL_VISUALIZER_COLOR property, just not the shading property.

**Comment by SamuelSJTU** [comment]
you have to use vtkSmartPointer<vtkPolyData>  to add shape, as you can see in the source file,  the solution is transform pcl::PolygonMesh to vtkSmartPointer<vtkPolyData>, here is the demo
`    pcl::PolygonMesh mesh;
    vtkSmartPointer<vtkPolyData> poly_data;
    pcl::io::loadPolygonFilePLY("duck.ply",mesh);
    mesh2vtk(mesh,poly_data);
    boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
    viewer->setBackgroundColor (0, 0, 0);
viewer->addModelFromPolyData(poly_data,"poly_data",0);
viewer->addCoordinateSystem (1.0);
    viewer->initCameraParameters ();
    viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_SHADING,pcl::visualization::PCL_VISUALIZER_SHADING_PHONG,"poly_data");`

**Comment by ricshaw** [comment]
That was actually super helpful. Thank you!
But will this work with a TextureMesh, i.e. an obj mesh with texture read from file?

**Comment by mhwasil** [comment]
You can also use terminal to visualize mesh or pointcloud.
If you have the obj, ply or pcd file, you first need to convert it to vtk using terminal as well
* Convert obj, ply or pcd to vtk
```
 pcl_ply2vtk input_object.ply output_object.vtk
 pcl_ply2obj input_object.obj output_object.vtk
 pcl_ply2pcd input_object.pcd output_object.vtk
```
* Visualize mesh
```
pcl_viewer -shading 'phong' output_object.vtk
```

Hope it helps
