### ISSUE TITLE
fail when cmake make the pcl trunk using ubuntu 16.04

### ISSUE THREAD

**Issue by uiossha** [PointCloudLibrary/pcl#1780]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment
<Ubuntu 16.04 LTS>
* Operating System and version:
* Compiler:
* PCL Version: pcl-trunk

##Introduction
after installing completely the pcl 1.7 on my ubuntu
I was using Qt4 to run some c++ program using pcl, then the following error occurs:
error: cannot find -lvtkproj4
So I searched and found that there's a vtk bug within, and someone mentioned that the bug may have been fixed in pcl 1.8

So Try to install pcl-trunk using the guide from the following links:
https://github.com/hsean/Capstone-44-Object-Segmentation/wiki/PCL-1.8:-Ubuntu-14.04-Installation-Guide
Also, I skipped the part of step02 and step03 since I think my pcl 1.7 runs prettty well

When I 

cd ~/Documents/pcl 
mkdir release 
cd release 
cmake -DCMAKE_BUILD_TYPE=None -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON .. 
make 

the errors occurs(shows below), and I am looking for some hope here.

## Current Behavior
[  3%] Built target pcl_common
[  4%] Built target pcl_kdtree
[  5%] Built target pcl_octree
[  6%] Built target pcl_search
[  8%] Built target pcl_sample_consensus
[ 12%] Built target pcl_filters
[ 12%] Built target pcl_io_ply
[ 17%] Built target pcl_io
[ 18%] Built target pcl_pcd_convert_NaN_nan
[ 18%] Linking CXX executable ../../bin/pcl_openni_grabber_example
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/usr/lib/x86_64-linux-gnu/libvtksys-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFNumberOfDirectories@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOCore-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtksys-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFReadRGBAImage@LIBTIFF_4.0'
../../lib/libpcl_io.so.1.8.0: undefined reference to `GOMP_parallel'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsoncpp.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFReadTile@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtksys-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
../../lib/libpcl_io.so.1.8.0: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `_TIFFfree@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFTileSize@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `_TIFFmalloc@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkCommonCore-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkCommonCore-6.2.so.6.2.0: undefined reference to `std::out_of_range::out_of_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtksys-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOGeometry-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFNumberOfTiles@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOCore-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libvtkIOMPIParallel-6.2.so.6.2.0: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
io/tools/CMakeFiles/pcl_openni_grabber_example.dir/build.make:287: recipe for target 'bin/pcl_openni_grabber_example' failed
make[2]: *** [bin/pcl_openni_grabber_example] Error 1
CMakeFiles/Makefile2:623: recipe for target 'io/tools/CMakeFiles/pcl_openni_grabber_example.dir/all' failed
make[1]: *** [io/tools/CMakeFiles/pcl_openni_grabber_example.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jspricke** [comment]
It's still a bug in VTK coming with 16.04. Someone needs to invest the time to help with this one: https://bugs.launchpad.net/ubuntu/+source/vtk6/+bug/1573234

**Comment by Macranius** [comment]
I'm exactly on the same point at this moment, is there any fix yet?

**Comment by bikong2** [comment]
mark for the same problem

**Comment by SergioRAgostinho** [comment]
Checking the link @jspricke provided, supposedly a fix was released on 2016-05-29 so it should roll out eventually. Upgrade your packages, and recompile.

There's always the [workaround](https://bugs.launchpad.net/ubuntu/+source/vtk6/+bug/1573234/comments/2) mentioned in that thread for a quick solution.

**Comment by jspricke** [comment]
If anyone of you could fill the SRU, that would be great. Otherwise it's fixt in 16.10 ;).
