### ISSUE TITLE
Can not install pcl via home-brew

### ISSUE THREAD

**Issue by LuZhouheng** [PointCloudLibrary/pcl#1783]
```
$ brew install pcl --without-apps --without-tools --without-vtk --without-qt
Updating Homebrew...
==> Installing pcl from homebrew/science
==> Installing dependencies for homebrew/science/pcl: cminpack, qhull, glew
==> Installing homebrew/science/pcl dependency: cminpack
==> Downloading http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz

curl: (7) Failed to connect to devernay.free.fr port 80: Operation timed out
Error: Failed to download resource "cminpack"
Download failed: http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz
```

My network is great but just can not download this package ? Did I do something wrong?

**Comment by SergioRAgostinho** [comment]
The link for downloading the dependence is unreachable. This can either be an issue with your network, the cminpack hosting server or simply the a bad link in the homebrew recipe. 

Nevertheless this not really a PCL issue, we don't maintain the homebrew recipe for pcl.

**Comment by LuZhouheng** [comment]
Thanks, Fixed here:

https://github.com/Homebrew/homebrew-science/issues/4749
https://github.com/devernay/cminpack/issues/7

Just because the "great-wall". Hope this will helpful for others.
