### ISSUE TITLE
Potential bug CropBox filter

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#1796]
There is a [very suspicious line](https://github.com/PointCloudLibrary/pcl/blob/ad67293f02f9ca12234500e13de46085105ea5e9/filters/include/pcl/filters/impl/crop_box.hpp#L111) in `CropBox` filter. Did not have time to investigate, test, etc., so just for the record:

```cpp
if (translation_is_zero)
{
  local_pt.x -= translation_ (0);
  local_pt.y -= translation_ (1);
  local_pt.z -= translation_ (2);
}
```

The test condition should probably be negated.

**Comment by Chungzuwalla** [comment]
bool translation_is_zero = (translation_ != Eigen::Vector3f::Zero ());

So the code works, but the variable should probably be renamed to translation_is_nonzero.

**Comment by taketwo** [comment]
Fair enough.
