### ISSUE TITLE
Index out of range in OrganizedConnectedComponentSegmentation

### ISSUE THREAD

**Issue by mtsep** [PointCloudLibrary/pcl#1798]
Hi,
I think there is a bug in the bounds checking code in the file organized_connected_component_segmentation.hpp, line 103:

 if (x >= 0 && y < int(labels->width) && y >= 0 && y < int(labels->height) && labels->points[index].label == label)
        break;

Looks like the code **y** < int(labels->width) should really be **x** < int(labels->width).
Current code leads to _labels->points[index]_ crashing when index out of bounds (x too high).

Error encountered in PCL Version 1.7.2, but looks like it is still present in the version 1.8.0

**Comment by jspricke** [comment]
Sounds right, can you send a pull request?

**Comment by mtsep** [comment]
Ok I made a pull request with this bugfix.
Hopefully everything is correct with the fork/branch, since I'm kind of new in GitHub.

**Comment by jspricke** [comment]
You need to create the pull request against the pcl repo ;). Also, please add some more comments to the commit.

**Comment by mtsep** [comment]
Alright, another try :)
