### ISSUE TITLE
Is there a particular reason why Poisson Surface Threads are disabled?

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1799]
https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/impl/poisson.hpp#L104

At the above source, you will notice that threads have been disabled. This is despite the fact there is a full openmp implementation of that particular tree library. Why is this so?

**Comment by soulslicer** [comment]
Just to note, i literally just enabled that line and set a value to my number of cores. My performance increased 3 fold

**Comment by atammaro** [comment]
Hello, 
I Opened a [merge request](https://github.com/PointCloudLibrary/pcl/pull/4332) for this issue.

**Comment by kunaltyagi** [comment]
Closed by #4332
