### ISSUE TITLE
Bug in fromPCLPointCloud2()

### ISSUE THREAD

**Issue by Chungzuwalla** [PointCloudLibrary/pcl#1802]
fromPCLPointCloud2() contains this test

    // Check if we can copy adjacent points in a single memcpy
    if (field_map.size() == 1 &&
        field_map[0].serialized_offset == 0 &&
        field_map[0].struct_offset == 0 &&
        msg.point_step == sizeof(PointT))
    {
        ... copy an entire row/cloud with a single memcpy() ...
    }

Unfortunately this test is not strict enough, as it does not test that field_map[0].size == sizeof(PointT).
Here is a test case:

    PointCloud<PointXYZ> test;
    loadPLYFile("test.ply", test);

test.ply:

    ply
    format ascii 1.0
    element vertex 3
    property float x
    property float y
    property float z
    property uchar red
    property uchar green
    property uchar blue
    property uchar alpha
    element face 0
    property list uchar int vertex_indices
    end_header
    1.0 2.0 3.0 255 255 255 255 
    4.0 5.0 6.0 255 255 255 255 
    7.0 8.0 9.0 255 255 255 255 

Note that in this example, msg.point_step is 16 and sizeof(PointXYZ) is also 16.
createMapping() correctly determines that we should copy the 3 float fields x,y,z (12 bytes) for each point and discard the RGBA, and creates a field_map with one entry having size 12.  Clearly the fields are not contiguous and we must copy one point at a time.  However the above test will pass (since 16 == 16), and the data[3] of each PointXYZ is overwritten with RGBA data, becoming NaN (0xFFFFFFFF).

## Possible Solution
I changed the test above to:

    // Check if we can copy adjacent points in a single memcpy
    if (field_map.size() == 1 &&
        field_map[0].serialized_offset == 0 &&
        field_map[0].struct_offset == 0 &&
        field_map[0].size == msg.point_step &&
        field_map[0].size == sizeof(PointT))
    {

That is, field_map[0].size must be the entire size of both the input and output types.
This fixes my specific case, can't say it is correct for all.

## Code to Reproduce
See above

**Comment by jspricke** [comment]
thanks for the bug report and the analysis. Could you please send a pull request with the change?
