### ISSUE TITLE
off-by-one bug in PCLVisualizer::addText3D

### ISSUE THREAD

**Issue by timjr** [PointCloudLibrary/pcl#1803]
There seems to be a bug in PCLVisualizer::addText3D here:

https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp#L688

i starts off at 1, when it should start off at 0 as in PCLVisualizer::addActorToRenderer.

If your viewport is, e.g., 1, you will have to pass in viewport 2 to get it to add the text.

**Comment by taketwo** [comment]
Looks like a bug indeed. Would you mind to submit a pull request?
