### ISSUE TITLE
pcl::toPCLPointCloud2() on a pcl::PointXY pcl::PointCloud Produces (y, z) Fields

### ISSUE THREAD

**Issue by KermMartian** [PointCloudLibrary/pcl#1806]
Calling `pcl::toPCLPointCloud2()` on a pcl::PointCloud containing points of type pcl::PointXY (ie, 2D points) produces (y, z) fields of type double in the resulting pcl::PCLPointCloud2, not (x, y) fields of type float. Attempting to use pcl::PointUV instead of pcl::PointXY produces the same results (ie, double fields y and z instead of float fields u and v).

## Your Environment

* Operating System and version: Ubuntu 16.10
* Compiler: g++
* PCL Version: 1.8.0

## Expected Behavior
x and y fields of type float should be produced.

## Current Behavior
y and z fields of type double are produced.

## Possible Solution

Not clear, because the following code in common/pcl/include/point_types.h appears correct:
```
POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::PointXY,
    (float, x, x)
    (float, y, y)
)
```

**Comment by taketwo** [comment]
Could you please post a short program that demonstrates the bug?

**Comment by KermMartian** [comment]
Apologies; once I created a MWE I realized it was programmer error! [notabug]
