### ISSUE TITLE
Compiler Warning: pcl::SAC_SAMPLE_SIZE is deprecated

### ISSUE THREAD

**Issue by hanshammel1337** [PointCloudLibrary/pcl#1807]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc 5.4
* PCL Version: 1.8 / trunk

## Expected Behavior
detect a parallel plan to a given axis. get the plane coefficients and the inliers.
compile the code without any warning.

## Current Behavior
i get the following warning
`/usr/local/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations] SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel))`

i tried two different code examples. each of course in a stand alone project. but both lead to the mentioned warning. i found a merged pull request about this issue, but my fresh PCL trunk installation still produces this warning. both code examples work as excepted.

the warning is coded here : https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/model_types.h

## Code to Reproduce

Code 1
```
#include <pcl/sample_consensus/sac_model_parallel_plane.h>
#include <pcl/sample_consensus/ransac.h>

Eigen::VectorXf coefficients_;
pcl::IndicesPtr inliers_;

pcl::SampleConsensusModelParallelPlane<pcl::PointXYZ>::Ptr model (new pcl::SampleConsensusModelParallelPlane<pcl::PointXYZ> (mycloud_));
pcl::RandomSampleConsensus<pcl::PointXYZ> sac (model, 0.03);

model->setAxis (Eigen::Vector3f (0.0,0.0,1.0));   
model->setEpsAngle(pcl::deg2rad (2.0f));        
sac.computeModel ();
sac.getInliers (*inliers_);
sac.getModelCoefficients (coefficients_);
```

Code 2
```
#include <pcl/sample_consensus/method_types.h>
#include <pcl/sample_consensus/model_types.h>
#include <pcl/segmentation/sac_segmentation.h>

pcl::ModelCoefficients::Ptr coefficients_;
pcl::PointIndices::Ptr inliers_;
pcl::SACSegmentation<pcl::PointXYZ> seg_;
pcl::PointCloud<pcl::PointXYZ>::Ptr mycloud_ (new pcl::PointCloud<pcl::PointXYZ>);

seg_.setModelType (pcl::SACMODEL_PARALLEL_PLANE);
seg_.setMethodType (pcl::SAC_RANSAC);
seg_.setDistanceThreshold (0.03);
seg_.setAxis (Eigen::Vector3f (0.0,0.0,1.0)); 
seg_.setEpsAngle(pcl::deg2rad (2.0f)); 
seg_.setInputCloud (mycloud_);
seg_.segment (*inliers_, *coefficients_);
```

**Comment by taketwo** [comment]
Unfortunately, for now we have to live with this warning. `SAC_SAMPLE_SIZE` can not be removed because we may break existing code.

**Comment by hanshammel1337** [comment]
Ok. Thank you for the quick answer.
Which code snippet (1 or 2) should be preferred?

**Comment by taketwo** [comment]
I can not say with 100% certainty without looking into the actual implementations, but I'm pretty sure there is no difference.

**Comment by hanshammel1337** [comment]
In my opinion code snippet 2 is more structured and readable.
I have one object and "work" with it.
