### ISSUE TITLE
Compiling error Ubuntu 16.04

### ISSUE THREAD

**Issue by rmsalinas** [PointCloudLibrary/pcl#1808]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Ubuntu
* Compiler: g++ 5.4
* PCL Version:1.8 (master branch)

## Expected Behavior

Compile
## Current Behavior

Not compiling:

/usr/lib/x86_64-linux-gnu/libproj.so', required for 'lib/libpcl_io.so.1.8.0'

**Comment by jolesinski** [comment]
I've compiled it in the same env recently and without any issues, but u may try this: http://stackoverflow.com/a/40034779

**Comment by fishfreetaken** [comment]
I also compiled it, but it costs me a day!

**Comment by taketwo** [comment]
Same as #1828.
