### ISSUE TITLE
Segmentation fault in function align in ICP

### ISSUE THREAD

**Issue by RonaldEnsing** [PointCloudLibrary/pcl#1819]
The `align` function of `IterativeClosestPoint` results in a segmentation fault.

Code to reproduce the bug:
```
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/registration/icp.h>
#include <pcl/point_types.h>

int main(int argc, char * * argv) {
	if (argc != 3) {
		std::cerr << "Usage: " << argv[0] << " <source cloud> <target cloud>" << std::endl;
		exit(0);
	}

	// Load point clouds
	pcl::PointCloud<pcl::PointXYZ>::Ptr source (new pcl::PointCloud<pcl::PointXYZ>);
	pcl::PointCloud<pcl::PointXYZ>::Ptr target (new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile(argv[1], *source);
	pcl::io::loadPCDFile(argv[2], *target);

	// Run ICP
	pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointXYZ> icp;
	icp.setInputSource(source);
	icp.setInputTarget(target);
	pcl::PointCloud<pcl::PointXYZ> transformed;
	Eigen::Isometry3f guess = Eigen::Isometry3f::Identity();
	icp.align(transformed, guess.matrix());
}
```

Additional information:
- OS: Arch Linux
- Compiler: Clang 3.9.1
- PCL version: 1.8.0

Source and target point clouds are available in the attachment.

[point_clouds.zip](https://github.com/PointCloudLibrary/pcl/files/763376/point_clouds.zip)

The segmentation fault does not occur when switching source and target.

The initial guess is quite far off, and the number of points between source and target point cloud is not comparable, but nevertheless I think that a segmentation fault is unexpected.

**Comment by y9luiz** [comment]
I had the same problem, did you solve this?

**Comment by RonaldEnsing** [comment]
You could try to remove the NaN values from the point cloud.

**Comment by y9luiz** [comment]
I try this but don't solve :/, but thanks for the help

**Comment by y9luiz** [comment]
Did you have another suggestion ? 
i'm trying something like this:

 pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointXYZ> icp;
 vector <int> index;
 pcl::removeNaNFromPointCloud(*cloud_in,*cloud_in,index);	
 pcl::removeNaNFromPointCloud(*cloud_out,*cloud_out,index);	
  icp.setInputCloud(cloud_in);
  icp.setInputTarget(cloud_out);
  pcl::PointCloud<pcl::PointXYZ> Final;
  icp.align(Final);

**Comment by SergioRAgostinho** [comment]
Yes. First of all you should always check if the current PCL master has the same problem. So compile it and have a go. 

If so, then run the debugger and try to understand why the segmentation fault occurs. Is there a pointer which isnull and it shouldn’t? Do your funtion arguments make sense? Are you getting what you expect at each step? Try to reduce your code to understand the minimum required for that  seg fault to occur.

**Comment by y9luiz** [comment]
Ok, i will try, when you say "current PCL master" you wanna say the last stable PCL version? 
Sorry, bad english, and thanks again for the help

**Comment by SergioRAgostinho** [comment]
> Ok, i will try, when you say "current PCL master" you wanna say the last stable PCL version?
No. I mean compile the repository as it is now.

**Comment by y9luiz** [comment]
ah, ok, now  i understand

**Comment by RonaldEnsing** [comment]
I just checked what happens with the code from my original post. It appears the segfault occurs on line 140 in the transformation_estimation_svd.hpp file: https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/transformation_estimation_svd.hpp#L140

The variable `cloud_tgt` is constructed with a size of `npts`: https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/transformation_estimation_svd.hpp#L124, but with `npts` is the size of `source_it`, and when `target_it` is smaller than `source_it`, then it makes sense that it segfaults. I do not know what's the proper way to fix this. You can try to swap your inputs (make target your source and source your target). Maybe `npts` should be changed to be the minimum of the number of points of source and target.

**Comment by emilianogagliardi** [comment]
Is there some news about this? I'm facing the same problem

**Comment by kunaltyagi** [comment]
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/transformation_estimation_svd.hpp#L62 (`estimateRigidTransformation`)

It clearly emits a warning when target and source cloud points aren't the same.

Segfault in ICP can occur in 2 cases, both need handling by the user:
* NaN in cloud
* Target and Source don't have same number of points

**Comment by K296** [comment]
@kunaltyagi The comment about NaNs helped me solve my issue. I wonder however if "Target and Source don't have same number of points" is really true and thus is using target and source clouds with different amount of points prohibited? I can add that I'm doing this and it works fine but obviously I would like to know if I'm doing it wrong...
