### ISSUE TITLE
Warning Open NI could not be added to path, Path variable too long

### ISSUE THREAD

**Issue by ahsteven** [PointCloudLibrary/pcl#1825]
I tried to install PCL 1.8 using the all-in-one installer but about half way through it says warning openni was not added to the path because the path is too long.  I removed a lot of items from the path to another variable path2 and then refered to path2 in the path. However I still get the same warning.

After the warning the PCL all-in-one installer says the installation is finished even though it looked to be only half-way done. 

Is there a way to fix this?

**Comment by taketwo** [comment]
@UnaNancyOwen sounds like Windows, any idea about it?

**Comment by UnaNancyOwen** [comment]
That is a limitation by the Windows OS. And, It's a problem with your system.
I think It will be hard to resolve with the All-in-one Installer.

You should be organize environment variables of your system.
You can remove paths that the your system and programs does not use.
Also, You can shorten the environment variable "PATH" by using references to other variables.
(Be careful in those operations! If you make a mistake your system may stop working.)

e.g.
before:
PATH <code>...;C:\Program Files (x86)\Software\bin;...</code>

after: 
SOFTWARE <code>C:\Program Files (x86)\Software</code>
PATH <code>...;%SOFTWARE%\bin;...</code>

Please restart the OS after doing these organize.
Perhaps, You can install PCL.
In install procese, Please choose "Do not add PCL to the system PATH".
Then, You manually add the following paths to environment variable "PATH" after installed the PCL All-in-one Installer.


<code>;%PCL_ROOT%\bin</code>
<code>;%OPENNI2_REDIST64%</code> (or <code>;%OPENNI2_REDIST%</code>)

If it doesn't resolve yet, you can reopen this issue.

**Comment by taketwo** [comment]
Thanks for an elaborated explanation, Tsukasa!
