### ISSUE TITLE
Build failure. Another missing dependency check for pcl_io

### ISSUE THREAD

**Issue by petern3** [PointCloudLibrary/pcl#1828]
While building PCL, it failed when linking pcl_io due to a missing dependency. This error occurred on a fresh install of Ubuntu 16.04.2, but not on 14.04.4. It's not a huge issue, but I figured I should post this in case anyone else has this problem.

## Environment

* Operating System and version: Ubuntu 16.04.2 (fresh install)
* Compiler: gcc
* PCL Version: 1.8

## Expected Behavior
    ...
    [ 11%] Linking CXX shared library ../lib/libpcl_io.so
    [ 11%] Built target pcl_io
    ...

## Current Behavior
    ...
    make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by 'lib/libpcl_io.so.1.8.0'.  Stop.
    CMakeFiles/Makefile2:287: recipe for target 'io/CMakeFiles/pcl_io.dir/all' failed

## Solution
`sudo apt-get install libproj-dev`

This is similar to the problem in issue https://github.com/PointCloudLibrary/pcl/issues/1349

**Comment by ningscapr** [comment]
Thank you so much for your solution !
