### ISSUE TITLE
CMake Warning (dev) at /home/projects/VTK-7.1.0/build/VTKTargets.cmake:28

### ISSUE THREAD

**Issue by fishfreetaken** [PointCloudLibrary/pcl#1831]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

ccmake  ..
VTK_DIR /home/projects/VTK-7.1.0/build 
when i press 'c' to configure, cmake remote me that "CMake Warning (dev) at /home/projects/VTK-7.1.0/build/VTKTargets.cmake:28, Policy CMP0054 is not set"  and " CMake Warning (dev) at /home/projects/VTK-7.1.0/build/VTKTargets.cmake:33, Policy CMP0054 is not set .."
 
I have no idea to overcome it, so i want to know what is wrong with it?
## Your Environment

* Operating System and version: ubuntu16.04
* Compiler: cc
* PCL Version:1.8.0

**Comment by SergioRAgostinho** [comment]
Is this a CMake warning you got while building VTK? If so, this is the wrong place to ask that question. The vtk mailing list is the way to go.
