### ISSUE TITLE
find_package( PCL 1.8) should not modify the compiler flag

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#1833]
## Your Environment
* Operating System and version: Ubuntu 16.04
* Compiler: GCC 5.4
* PCL Version: Latest

## Expected Behavior
When I call `find_package( PCL 1.8 REQUIRED )` in my CMakeLists, I am expecting my `CMAKE_CXX_FLAGS` to remain the same.

## Current Behavior
After calling `find_package( PCL 1.8 REQUIRED )` there is an additional `-Wno-deprecated` on my `CMAKE_CXX_FLAGS`

## Context
Why is it bad? Lets say I am creating a shared library A that does the usual `find_package( PCL 1.8.0 REQUIRED )` `target_include_directories(${PROJECT_NAME} SYSTEM PUBLIC ${PCL_INCLUDE_DIRS})`  `target_link_libraries` to PCL_LIBRARIES in the CMakeLists of A, and I have a shared library B which is also using PCL and something from A, under normal circumstances if this is some other external library I can simply `target_link_libraries` to A and it will work, but because of this problem I had to `target_link_libraries` to A and do a `find_package( PCL 1.8.0 REQUIRED )` to compile otherwise I will get `-Wno-deprecated` warnings from vtk. I treat all warnings as error hence my code cannot compile.

## Code to Reproduce
Find a random CMakeLists.txt 

``````
message(CMAKE_CXX_FLAGS "flag is ${CMAKE_CXX_FLAGS}")

find_package( PCL 1.8 REQUIRED )

message(CMAKE_CXX_FLAGS "flag is ${CMAKE_CXX_FLAGS}")
``````

## Possible Solution
While PCL is including VTK headers in it's CMakeLists, do something like `target_include_directories(${PROJECT_NAME} SYSTEM PUBLIC ${VTK_INCLUDE_DIRS})` so the external headers are treated as system headers hence the warnings will be silenced. Therefore there won't be a need to add in `-Wno-deprecated` into the compiler flags anymore.

**Comment by jspricke** [comment]
HI @jasjuang, thanks for the report. Can you send a pull request with the proposed fix? Thanks!

**Comment by jasjuang** [comment]
@jspricke Once `-Wno-deprecated` is removed, for some reason including the directory as SYSTEM would not remove the `Wcpp` warnings from VTK. I figured out a workaround which is building VTK from source and the warnings will be gone. I was doing a simple `sudo apt-get install libvtk5-dev` and it installed VTK 5.10.

However, if I send in the pull request that simply removes the additional `-Wno-deprecated` it might break compilation for someone. We still have to figure out how to silence the warnings in PCL itself without needing to add `-Wno-deprecated` to the `CMAKE_CXX_FLAGS`

**Comment by jspricke** [comment]
I did a quick grep and all I found was https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L121 which doesn't apply to you. Also, I tested you example on Debian unstable and it didn't set any flags.

**Comment by jasjuang** [comment]
I just tested this again with the latest PCL and VTK and this error is gone. I am guessing VTK propagates INTERFACE_COMPILE_DEFINITIONS incorrectly and it's being fixed in later commits.

**Comment by SergioRAgostinho** [comment]
We did some changes at some point because we had to propagate SSE flags properly as well, so it might have been there. But cool to know!
