### ISSUE TITLE
Spin Image Estimation Crash

### ISSUE THREAD

**Issue by nlynn12** [PointCloudLibrary/pcl#1834]
The Spin Image Estimation crashes (core dumped) when you set the image width different than default 8, **and** the angular support cos different than default 0.0.

An image width of 200 does **not** work with an angular support of say 0.5.

However it **does** work if the image width is 200 and the angular support is 0.0.

## Your Environment

* Operating System and version: Ubuntu 16.04.1 LTS
* Compiler: cmake version 3.5.1, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
* PCL Version: 1.8.0

## Expected Behavior

Not to crash ;)

## Current Behavior

Crashes with core dumped.

## Code to Reproduce

```c++
#define IMG_WIDTH 200
#define N_BINS ((IMG_WIDTH + 1) * (IMG_WIDTH * 2 + 1))

...

pcl::SpinImageEstimation<PointT, PointT, pcl::Histogram<N_BINS>> si(IMG_WIDTH, 0.0, 0);

si.setInputCloud(cloud);
si.setInputNormals(normals);

// Set search surface
si.setSearchMethod(kdtree);
si.setRadiusSearch(radius);
si.setSearchSurface(surface);

// Compute spin image features
si.compute(spin_images);
```

## Context
I'm visualizing spin images in regular 2D images.

**Comment by liuxinhai** [comment]
How should i change the size of spin image？ There is a compiling error when i changed the size like you.
