### ISSUE TITLE
pcl compilation fails on centos 6.3 with assembler message: no such instruction

### ISSUE THREAD

**Issue by erictamlam** [PointCloudLibrary/pcl#1837]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Centos 6.3
* Compiler: gcc (GCC) 6.3.0
* PCL Version: github master
* Cmake Version: 3.7.2

## Expected Behavior

successful compilation

## Current Behavior

The assembler reports error message as follows:
`/tmp/ccc5TLrz.s: Assembler messages:`
`/tmp/ccc5TLrz.s:11887: Error: no such instruction: 'shlx %r10,%rax,%r10'`
`/tmp/ccc5TLrz.s:45385: Error: no such instruction: 'shlx %rbp,%rsi,%rbp'`
`/tmp/ccc5TLrz.s:46372: Error: no such instruction: 'shlx %rbp,%rsi,%rbp'`
`make64[2]: *** [common/CMakeFiles/pcl_common.dir/src/time_trigger.cpp.o] Error 1`
`make64[2]: Leaving directory '/home/hadmap/pcl/build'`
`make64[1]: *** [common/CMakeFiles/pcl_common.dir/all] Error 2`
`make64[1]: Leaving directory '/home/hadmap/pcl/build'`
`make64: *** [all] Error 2`

## Possible Solution

Tried to remove "-=march=native" from CMakeLists.txt but no such flags found

## Code to Reproduce

`tar xvf pcl-master.tar.gz` 
`mv pcl-master pcl`
`cd pcl`
`mkdir build && cd build`
`cmake .. -DCMAKE_CXX_FLAGS:="-march=haswell"`
`make`

## Context

Trying to compile pcl on Centos 6.3 with gcc 6.3.0 and cmake 3.7.2

**Comment by nizar-sallem** [comment]
march=native is in cmake/pcl_find_sse.cmake

**Comment by erictamlam** [comment]
@nizar-sallem I changed "march=native" to "march=haswell" in cmake/pcl_find_sse.cmake, but the problem still exists.

**Comment by SergioRAgostinho** [comment]
@erictamlam Does the library build if you don't specify `-DCMAKE_CXX_FLAGS:="-march=haswell"` or any other `CMAKE_CXX_FLAGS`? This will basically have `march=native` enabled by default. Because just from what you describe, it just seems you're passing wrong cpu architecture to the compiler...

**Comment by taketwo** [comment]
@erictamlam have you solved the problem? Please reopen if not. The `shlx` instruction belongs to BMI2 feature set and should be available on haswell.
