### ISSUE TITLE
PCL 1.8.0 doesn't build correctly with VTK 5.6.0

### ISSUE THREAD

**Issue by haferburg** [PointCloudLibrary/pcl#1838]
When building `io`, there are linker errors because the VTK libraries are missing.

In the main CMakeLists.txt:

    if (${VTK_MAJOR_VERSION} VERSION_LESS "6.0")
        message(STATUS "VTK found (include: ${VTK_INCLUDE_DIRS}, lib: ${VTK_LIBRARY_DIRS})")
        message(STATUS "VTK_LIBRARIES: ${VTK_LIBRARIES}") # <- I added this line for debugging
        link_directories(${VTK_LIBRARY_DIRS})
    else(${VTK_MAJOR_VERSION} VERSION_LESS "6.0")
        include (${VTK_USE_FILE})
        message(STATUS "VTK found (include: ${VTK_INCLUDE_DIRS}, lib: ${VTK_LIBRARIES}")
    endif (${VTK_MAJOR_VERSION} VERSION_LESS "6.0")

Then in `io\CMakeLists.txt`:

    target_link_libraries("${LIB_NAME}" pcl_common pcl_io_ply ${VTK_LIBRARIES} )

The problem: `VTK_LIBRARIES` is empty.

Proposed solution: Either set `VTK_LIBRARIES` or require VTK>=6.0.

**Comment by taketwo** [comment]
Closing this as obsolete, PCL now requires VTK >= 6.2.
