### ISSUE TITLE
pcl_octree_viewer displays spurious points when visualizing a PointCloud | Octree Viewer .pcd

### ISSUE THREAD

**Issue by dbworth** [PointCloudLibrary/pcl#1840]
I think the `pcl_octree_viewer` is displaying some erroneous points that don't exist.

## Your Environment
* Operating System and version:  Ubuntu 14.04 LTS
* PCL Version: 1.7.2

## Expected Behavior
**(1)**  
I would expect the Octree viewer to display a down-sampled version of the input PointCloud, similar to the voxelized Bunny shown on this page:  
http://docs.pointclouds.org/trunk/group__octree.html  
Notice that the voxels are within the general shape of the Bunny.

**(2)**  
The maximum resolution of the displayed cloud should be the same as the input.  
The Viewer should not add extra points at a finer resolution.

## Current Behavior

**Issue 1:**

`pcl_octree_viewer teapot.pcd 0.10`

You can see that the PointCloud of the teapot is surrounded by spurious points that should not exist 
![pcl_octree_viewer_spurious_points](https://cloud.githubusercontent.com/assets/949758/23839174/7db068d4-0772-11e7-855f-94c28fc9aec7.png)

**Issue 2:**

When displaying at the highest resolution (maximum depth), the Octree Viewer seems to add extra points like "noise" around the location of the original points:     
![octree_viewer_extra_points](https://cloud.githubusercontent.com/assets/949758/23839360/e6e35aea-0773-11e7-8db6-a58e259fc062.png)

This is what it should look like:  
Notice the evenly-spaced points.

`pcl_viewer teapot.pcd`

![pcl_viewer_teapot_correct](https://cloud.githubusercontent.com/assets/949758/23839195/a626d690-0772-11e7-8849-5ef0125e4d60.png)

## Possible Solution

I'm not sure.

## Code to Reproduce

Using this sample PointCloud:
https://github.com/dbworth/pcl_binvox/blob/master/data/teapot.pcd

`pcl_octree_viewer teapot.pcd 0.10`

Or use the sample data `bunny.pcd` from PCL.

## Context

In other software programs, a low-resolution visualization will display the points at the center of the voxels.  At the highest resolution (maximum octree depth) then it looks like the original cloud. Of course I don't know if this is possible in PCL  :-)

**Comment by SergioRAgostinho** [comment]
Could verify the same with HEAD

**Comment by taketwo** [comment]
Can someone confirm that this is fixed now?

**Comment by frozar** [comment]
This issue was fixed with the merge request #1973. But, to be honest, later I realises that the computation of the centroid doesn't take into account correctly the weight of sub-centroid, but I'll explain it better in a coming soon merge request. Don't worry, it's fixed.
