### ISSUE TITLE
Surface reconstruction misbehaves for point clouds far from the origin

### ISSUE THREAD

**Issue by nblythe** [PointCloudLibrary/pcl#1842]
* Operating System and version: Ubuntu 16.10 "Yakkety Yak" x64
* Compiler: gcc 6.2.0
* PCL Version: 1.8

## Expected Behavior
pcl::Poisson should produce the same shaped surface when run on the same point cloud, regardless where the point cloud's centroid is relative to the origin.

## Current Behavior
If a point cloud is far from the origin (on the order of 1e6 along at least one axis) pcl::Poisson will produce a surface that is "choppy" along the long axis.

## Code to Reproduce
The centroid of the CSite1_orig_utm.pcd (available [here](https://github.com/PointCloudLibrary/data)) is at [512434, 5.40559e+06, 348.523]. After some downsampling, smoothing, and normal estimation, pcl::Poisson doesn't do a good job of coming up with a surface.
`
  // Load the culprit file
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloudInput(new pcl::PointCloud<pcl::PointXYZ>());
  pcl::io::loadPCDFile<pcl::PointXYZ>("CSite1_orig_utm.pcd", *cloudInput);

  // Downsample
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloudDownsampled(new pcl::PointCloud<pcl::PointXYZ>);
  pcl::VoxelGrid<pcl::PointXYZ> downsampler;
  downsampler.setInputCloud(cloudInput);
  downsampler.setLeafSize(5, 5, 5);
  downsampler.setMinimumPointsNumberPerVoxel(10);
  downsampler.filter(*cloudDownsampled);

  // Uncomment this and surface reconstruction will work.
  //Eigen::Vector4f centroid;
  //pcl::compute3DCentroid(*cloudDownsampled, centroid);
  //Eigen::Affine3f transform = Eigen::Affine3f::Identity();
  //transform.translation() << -centroid[0], -centroid[1], -centroid[2];
  //pcl::PointCloud<pcl::PointXYZ>::Ptr cloudTranslated(new pcl::PointCloud<pcl::PointXYZ>());
  //pcl::transformPointCloud(*cloudDownsampled, *cloudTranslated, transform);

  // Upsample and smooth
  pcl::MovingLeastSquares<pcl::PointXYZ, pcl::PointNormal> mls;
  pcl::PointCloud<pcl::PointNormal>::Ptr cloudUpsampledNormals(new pcl::PointCloud<pcl::PointNormal>());

  mls.setInputCloud(cloudTranslated);
  mls.setComputeNormals(true);

  pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>());
  mls.setSearchMethod(tree);

  mls.setSearchRadius(10);

  mls.setUpsamplingMethod(pcl::MovingLeastSquares<pcl::PointXYZ, pcl::PointNormal>::RANDOM_UNIFORM_DENSITY);
  mls.setPointDensity(100);

  mls.setPolynomialFit(true);
  mls.setPolynomialOrder(4);

  mls.process(*cloudUpsampledNormals);

  // Surface reconstruction
  pcl::PolygonMesh mesh;
  pcl::Poisson<pcl::PointNormal> poisson;
  poisson.setInputCloud(cloudUpsampledNormals);
  poisson.setDepth(8);
  poisson.setSolverDivide(8);
  poisson.setIsoDivide(8);
  poisson.setSamplesPerNode(10);
  poisson.reconstruct(mesh);

  // Save it
  pcl::io::saveVTKFile("CSite1_orig_utm.vtk", mesh);
`

[Without translating to the origin](http://www.pcl-users.org/file/n4044129/E9iUt21.png)
[With translating to the origin](http://www.pcl-users.org/file/n4044132/fw0Nqbq.png)

(See [pcl-users thread](http://www.pcl-users.org/Poisson-mesh-construction-fails-in-PCL-works-in-MeshLab-td4044129.html))

**Comment by nblythe** [comment]
Confirmed this occurs in trunk as well

**Comment by coolshahabaz** [comment]
I have also reported this bug "Possible Bug in PCL_visualizer when adding model object. #1781" it only occurs above 1.6 version

**Comment by jspricke** [comment]
@coolshahabaz can you try to git bisect to find the commit in question? Thanks!

**Comment by coolshahabaz** [comment]
@jspricke Currently, No. I have been moved to 1.6 since my project requires correct visualization.

**Comment by mvieth** [comment]
Found the problem: the surface reconstruction is fine, but the file output is problematic: `saveVTKFile` produces an ASCII file, so some precision might be lost for large numbers. If you request a higher output precision, e.g. 7 (default is 5), results are much better: `pcl::io::saveVTKFile("CSite1_orig_utm.vtk", mesh, 7);`. Alternatively, use another output file format like binary PLY.
