### ISSUE TITLE
Building Fault

### ISSUE THREAD

**Issue by alexsmartens** [PointCloudLibrary/pcl#1844]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

Building Fault

## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:
Linux/Cmake/PCL 1.8

## Context

$make
Scanning dependencies of target pcl_common
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/point_types.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/io.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/common.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/correspondence.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/distances.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/parse.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/poses_from_matches.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/print.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/projection_matrix.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/time_trigger.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/gaussian.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/colors.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/feature_histogram.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.o
[  2%] Building CXX object common/CMakeFiles/pcl_common.dir/src/range_image.cpp.o
[  2%] Building CXX object common/CMakeFiles/pcl_common.dir/src/range_image_planar.cpp.o
[  2%] Building C object common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o
[  2%] Building C object common/CMakeFiles/pcl_common.dir/src/fft/kiss_fftr.c.o
[  2%] Linking CXX shared library ../lib/libpcl_common.so
[  2%] Built target pcl_common
Scanning dependencies of target pcl_octree
[  2%] Building CXX object octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o
[  2%] Linking CXX shared library ../lib/libpcl_octree.so
[  2%] Built target pcl_octree
Scanning dependencies of target pcl_io_ply
[  2%] Building CXX object io/CMakeFiles/pcl_io_ply.dir/src/ply/ply_parser.cpp.o
[  3%] Linking CXX shared library ../lib/libpcl_io_ply.so
[  3%] Built target pcl_io_ply
Scanning dependencies of target pcl_io
[  3%] Building CXX object io/CMakeFiles/pcl_io.dir/src/debayer.cpp.o
[  3%] Building CXX object io/CMakeFiles/pcl_io.dir/src/pcd_grabber.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/pcd_io.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/vtk_io.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ply_io.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ascii_io.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/compression.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/lzf.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/lzf_image_io.cpp.o
[  4%] Building CXX object io/CMakeFiles/pcl_io.dir/src/obj_io.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ifs_io.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/image_grabber.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/hdl_grabber.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/vlp_grabber.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/robot_eye_grabber.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/file_io.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/auto_io.cpp.o
[  5%] Building CXX object io/CMakeFiles/pcl_io.dir/src/io_exception.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/vtk_lib_io.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/png_io.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_device.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_device_primesense.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_image_bayer_grbg.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_depth_image.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_ir_image.cpp.o
[  6%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_device_kinect.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_device_xtion.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_device_oni.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_driver.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_exception.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_image_yuv_422.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_camera/openni_image_rgb24.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni_grabber.cpp.o
[  7%] Building CXX object io/CMakeFiles/pcl_io.dir/src/oni_grabber.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/image_rgb24.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/image_yuv422.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/image_ir.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/image_depth.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2_grabber.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_timer_filter.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_video_mode.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_convert.cpp.o
[  8%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_device.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_device_info.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/openni2/openni2_device_manager.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/dinast_grabber.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ensenso_grabber.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/davidsdk_grabber.cpp.o
[  9%] Building CXX object io/CMakeFiles/pcl_io.dir/src/libpng_wrapper.cpp.o
make[2]: *** No rule to make target '/usr/local/lib/libOpenNI2.so', needed by 'lib/libpcl_io.so.1.8.0'.  Stop.
CMakeFiles/Makefile2:232: recipe for target 'io/CMakeFiles/pcl_io.dir/all' failed
make[1]: *** [io/CMakeFiles/pcl_io.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Although (from Cmake log):
-- OpenNI found (include: /usr/include/ni, lib: /usr/lib/libOpenNI.so)
-- Found OpenNI2: /usr/local/lib/libOpenNI2.so  
-- OpenNI 2 found (include: /usr/include/openni2, lib: /usr/local/lib/libOpenNI2.so, redist: )

**Comment by jspricke** [comment]
Your OpenNI2 installation is broken (libOpenNI2.so) is missing. This is not a PCL error.
