### ISSUE TITLE
API/ABI changes review for PCL

### ISSUE THREAD

**Issue by lvc** [PointCloudLibrary/pcl#1846]
The review of API/ABI changes for PCL since 1.1.2 version: https://abi-laboratory.pro/tracker/timeline/pcl/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of https://github.com/lvc/abi-tracker.

Thank you.

![pcl-1](https://cloud.githubusercontent.com/assets/1517837/24089384/9229829a-0d4f-11e7-9d77-d79693ca909b.png)

![pcl-2](https://cloud.githubusercontent.com/assets/1517837/24089394/a195c7e8-0d4f-11e7-95f2-1334625d1dd2.png)

## Environment
* Linux x86_64
* GCC 4.9
* PCL 1.1.2 and higher

**Comment by taketwo** [comment]
Would be nice to get such a report for the current master to see if we unintentionally made any ABI breaking changes.

**Comment by SergioRAgostinho** [comment]
I was trying to do it actually. But I was having some troubles, with GCC segfaulting during compilation... Yep... during compilation...

**Comment by taketwo** [comment]
Oh well...

**Comment by SergioRAgostinho** [comment]
Managed to get it working with the new abi-dumper method he reports on the website https://lvc.github.io/abi-compliance-checker/#ABI_Dumper

It's on :+1:

**Comment by SergioRAgostinho** [comment]
[compat_reports.zip](https://github.com/PointCloudLibrary/pcl/files/1109312/compat_reports.zip)
Freshly brewed

**Comment by SergioRAgostinho** [comment]
Added summary above.

**Comment by taketwo** [comment]
There were no changes to neither `kdtree` nor `search` module since the last release, so we can not do anything about this I guess.

**Comment by lvc** [comment]
> Would be nice to get such a report for the current master to see if we unintentionally made any ABI breaking changes.

Added report for master: https://abi-laboratory.pro/tracker/timeline/pcl/

Build requires a lot of resources, so I will update it once a week or so (not daily).

![pcl-3](https://user-images.githubusercontent.com/1517837/33537677-d30318cc-d8cd-11e7-9df1-01486fdfdf01.png)

**Comment by SergioRAgostinho** [comment]
@taketwo  What about adding this to README.md ?

**Comment by taketwo** [comment]
What exactly would you add? A link to the report? They don't seem to have any badges.

**Comment by SergioRAgostinho** [comment]
```diff
diff --git a/README.md b/README.md
index b09212a..e98a330 100644
--- a/README.md
+++ b/README.md
@@ -41,3 +41,7 @@ Issues
 ------
 For general questions on how to use the PCL, please use the [pcl-users](http://www.pcl-users.org/) mailing list (do not forget to subscribe before posting).
 To report issues, please read [CONTRIBUTING.md#bug-reports](https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md#bug-reports).
+
+API/ABI Compatibility Report
+------
+For details about API/ABI changes over the timeline please check PCL's page at [ABI Laboratory](https://abi-laboratory.pro/tracker/timeline/pcl/).
```

**Comment by SergioRAgostinho** [comment]
@lvc providing an endpoint/link with an updated badge `backwards compatibilty | xx%` would be the "icing on the cake".

Nevertheless thanks for already lifting this "burden" from us :)
