### ISSUE TITLE
Local doc generation no longer works

### ISSUE THREAD

**Issue by folkwang** [PointCloudLibrary/pcl#1848]
I followed https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/generate_local_doc.rst but there is no longer a `doc` target when I invoke make in build directory.

## Your Environment

* Operating System and version: macOS Sierra
* Compiler: clang-800.0.42.1
* PCL Version: PCL 1.8

## Code to Reproduce
```
mkdir build && cd build
make -j8
VERBOSE=1 make doc
```
then
`make: Nothing to be done for 'doc'.`

## Context
I'm going to generate a docset for local use on https://kapeli.com/dash

**Comment by taketwo** [comment]
You need to pass `-DWITH_DOCS=ON` option when you configure the project with CMake.

**Comment by folkwang** [comment]
Thanks @taketwo ! Sorry about the spam.
