### ISSUE TITLE
Converter exits with -1 but exit code 0 expected, because conversion works without error

### ISSUE THREAD

**Issue by pclbel** [PointCloudLibrary/pcl#1851]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

PCL 1.8.0

## Expected Behavior
Expected that the converter ends with exit code 0, but instead exits with -1

## Current Behavior
converter exits with -1 in case of successfull conversion

## Possible Solution
line 273 if condition wrong, has to be negiated
see https://github.com/PointCloudLibrary/pcl/blob/master/io/tools/converter.cpp#L273

## Code to Reproduce
convert a ply to a binary pcd without faces

## Context
converting a ply to a binary pcd without faces

**Comment by taketwo** [comment]
Thanks for bringing this up. Could you please add a link to the relevant file/line?

**Comment by MarcoFalke** [comment]
Also, you can simply submit a pull request by opening the file in the GitHub web view and pressing the Edit icon in the top right corner.
