### ISSUE TITLE
Building failed on macOS 10.12, something wrong with boost multithread

### ISSUE THREAD

**Issue by GilgameshD** [PointCloudLibrary/pcl#1867]
## Your Environment

* Operating System and version: macOS 10.12
* Compiler: apple LLVM version 8.1.0 (clang-802.0.41)
* PCL Version: 1.8

## Current Behavior

When I was building PCL 1.8 with the code on github, I get these errors:
In file included from /Users/host/Desktop/dependency/pcl/io/src/ply/ply_parser.cpp:41:
In file included from /Users/host/Desktop/dependency/pcl/io/include/pcl/io/ply/ply_parser.h:64:
In file included from /Users/host/Desktop/dependency/pcl/io/include/pcl/io/boost.h:49:
In file included from /usr/local/include/boost/thread/mutex.hpp:12:
In file included from /usr/local/include/boost/thread/detail/platform.hpp:17:
/usr/local/include/boost/config/requires_threads.hpp:47:5: error: "Compiler threading
      support is not turned on. Please set the correct command line options for
      threading: -pthread (Linux), -pthreads (Solaris) or -mthreads (Mingw32)"
#error "Compiler threading support is not turned on. Please set the correct co...
  
In file included from /Users/host/Desktop/dependency/pcl/io/src/ply/ply_parser.cpp:41:
In file included from /Users/host/Desktop/dependency/pcl/io/include/pcl/io/ply/ply_parser.h:64:
In file included from /Users/host/Desktop/dependency/pcl/io/include/pcl/io/boost.h:49:
In file included from /usr/local/include/boost/thread/mutex.hpp:12:
/usr/local/include/boost/thread/detail/platform.hpp:69:9: error: "Sorry, no boost threads
      are available for this platform."
#error "Sorry, no boost threads are available for this platform."
    

## Context

I know that is related with the platform of boost, and I am using boost 1.6.4. But I don't know how to build it with my compiler

**Comment by SergioRAgostinho** [comment]
Yeah, this doesn't look at all like a PCL bug. The mailing list is the appropriate place for these cases.

You exactly did you install boost?
