### ISSUE TITLE
Where is pcl_viewer on OSX?

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#1868]
When compiling PCL from source (no modifications to the cmake build process), `pcl_viewer` is inside an app package in `bin/pcl_viewer.app/Contents/MacOS/pcl_viewer`. I'd like to understand why that is, given it's simply a binary that is generally run from the command line (isn't it).

Also `make install` does not place this app anywhere.

## Your Environment
* macOS 10.12.5
* Compiler: `clang`
* PCL Version: 1.7.2

## Expected Behavior
`pcl_viewer` is installed somewhere

## Current Behavior
`pcl_viewer` is built, but not installed

## Possible Solution

- Copy the binary along with the others, ditch the app package
- Put the app in `/Applications` (??)

## Code to Reproduce
```
mkdir build
cd build
cmake .. && sudo make install
```

**Comment by the-mikedavis** [comment]
I also see this (April 2019, installed through `brew install pcl`). It appears to work just fine on MacOS, so if you want it your can just link it in your path:

```
cd /usr/local/bin
sudo ln -s /usr/local/Cellar/pcl/1.9.1_3/pcl_viewer.app/Contents/MacOS/pcl_viewer .
``` 

and use it as you would on ubuntu / linux.

It'd be nice if this were auto-linked in, though

**Comment by themightyoarfish** [comment]
With the current state, the app package is actually placed in the installation prefix as well i believe. Somewhere in the build files it said that it needs to be a bundle to receive keyboard events, but that seems empirically incorrect.

**Comment by kunaltyagi** [comment]
Apologies @themightyoarfish, but could you please expand on this a bit? I'm unfamiliar with MacOS development.

**Comment by themightyoarfish** [comment]
I seem to have misremembered this info, at least I can't find the statement about receiving keyboard events in thr build files anymore. According to the Cmake docs, building an Application bundle is for allowing the executable to be run From the finder. However, that's not so useful, unless one configures that app ro be the defaulr app for PCD files. Has anyone actually tried whether that works? 
I think i tried once and it didn't actually work, but thar was some time ago.
