### ISSUE TITLE
Segfault with ApproximateProgressiveMorphologicalFilter

### ISSUE THREAD

**Issue by ClementLeBihan** [PointCloudLibrary/pcl#1871]
##  Environment
* Operating System and version: Ubuntu 16.04
* PCL Version: 1.8
* Eigen 3

## Description
I'm trying to use ApproximateProgressiveMorphologicalFilter, but I have a Segmentation Fault at line 128 of approximate_progressive_morphological_filter.hpp
```
127 Eigen::MatrixXf A (rows, cols); 
128 A.setConstant (std::numeric_limits<float>::quiet_NaN ());

```

During the execution of the code, I cout rows and cols : 

> rows : 94
> cols : 166

Here is the valgrind logs : 
==3515== Process terminating with default action of signal 11 (SIGSEGV)
==3515==  General Protection Fault
==3515==    at 0x52C2DC0: _mm256_store_ps (avxintrin.h:854)
==3515==    by 0x52C2DC0: pstore<float, __vector(8) float> (PacketMath.h:243)
==3515==    by 0x52C2DC0: pstoret<float, __vector(8) float, 32> (GenericPacketMath.h:486)
==3515==    by 0x52C2DC0: assignPacket<32, __vector(8) float> (AssignmentFunctors.h:28)
==3515==    by 0x52C2DC0: assignPacket<32, 32, __vector(8) float> (AssignEvaluator.h:598)
==3515==    by 0x52C2DC0: run (AssignEvaluator.h:386)
==3515==    by 0x52C2DC0: call_dense_assignment_loop<Eigen::Matrix<float, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1> >, Eigen::internal::assign_op<float> > (AssignEvaluator.h:653)
==3515==    by 0x52C2DC0: run (AssignEvaluator.h:790)
==3515==    by 0x52C2DC0: void Eigen::internal::call_assignment_no_alias<Eigen::Matrix<float, -1, -1, 0, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1, 0, -1, -1> >, Eigen::internal::assign_op<float> >(Eigen::Matrix<float, -1, -1, 0, -1, -1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1, 0, -1, -1> > const&, Eigen::internal::assign_op<float> const&) (AssignEvaluator.h:747)
==3515==    by 0x6E9C613: call_assignment<Eigen::Matrix<float, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1> >, Eigen::internal::assign_op<float> > (AssignEvaluator.h:712)
==3515==    by 0x6E9C613: call_assignment<Eigen::Matrix<float, -1, -1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1> > > (AssignEvaluator.h:693)
==3515==    by 0x6E9C613: _set<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1> > > (PlainObjectBase.h:682)
==3515==    by 0x6E9C613: operator=<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, -1> > > (Matrix.h:225)
==3515==    by 0x6E9C613: setConstant (CwiseNullaryOp.h:338)
==3515==    by 0x6E9C613: pcl::ApproximateProgressiveMorphologicalFilter<pcl::PointXYZ>::extract(std::vector<int, std::allocator<int> >&) (approximate_progressive_morphological_filter.hpp:128)

Anyone can help ?

**Comment by taketwo** [comment]
Most likely the same issue as #1684, #1791, #2013. Should be resolved by #2100, please re-open if not.
