### ISSUE TITLE
Normal Estimation Takes too long and IntegralImageNormalEstimation gives error

### ISSUE THREAD

**Issue by santonatos** [PointCloudLibrary/pcl#1886]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc 5.4
* PCL Version: 1.7

## Expected Behavior
I am using  a zed stereo camera and I am trying to make a normal estimation out of a point cloud with around 1,800,000 points. The regular normal estimation takes too long, so I thought of using the 'Normal Estimation Using Integral Images' method as suggested at the bottom of this page:
http://pointclouds.org/documentation/tutorials/normal_estimation.php  

Specifically it says:  
"If your dataset is organized (e.g., acquired using a TOF camera, stereo camera, etc – that is, it has a width and a height), for even faster results see the Normal Estimation Using Integral Images."

I expected the normal estimation to run properly.

## Current Behavior
Using a stereo camera,  when I ran the simple normal estimation code with integral images I got the error:

[pcl::IntegralImageNormalEstimation::setInputCloud] Input dataset is not organized (height = 1).
[pcl::IntegralImageNormalEstimation::initCompute] Input dataset is not organized (height = 1).

## Possible Solution
I tried replacing the code with regular normal estimation, with no integral images, but it takes too long.
I was wondering how long would it take to do a regular normal estimation with almost 2 million points..

## Code to Reproduce
Integral images normal estimation:

pcl::PointCloud<pcl::Normal>::Ptr normals (new pcl::PointCloud<pcl::Normal>);
  pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
  ne.setNormalEstimationMethod (ne.AVERAGE_3D_GRADIENT);
  ne.setMaxDepthChangeFactor(0.02f);
  ne.setNormalSmoothingSize(10.0f);
  ne.setInputCloud(cloud);
  ne.compute(*normals);

Regular normal estimation:

pcl::NormalEstimationOMP<pcl::PointXYZ, pcl::Normal> n;
  pcl::PointCloud<pcl::Normal>::Ptr normals (new pcl::PointCloud<pcl::Normal>);
  pcl::search::KdTree<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ>);
  tree->setInputCloud (cloud);
  n.setInputCloud (cloud);
  n.setSearchMethod (tree);
  n.setKSearch (20);
  n.compute (*normals);

## Context
I am trying to use the triangulation algorithm PCL provides for my cloud, but this involves normal estimation which is so slow if it is regular.

**Comment by stefanbuettner** [comment]
How exactly did you acquire the point cloud from you zed stereo camera?

**Comment by santonatos** [comment]
i retrieve the MEASURE_XYZRGBA and I put it in on a mat, then I tranform the mat into a point cloud with a function. It seems to work perfectly because I can view the cloud on the viewer with colors and also perform registration among clouds. But when I try to do normal estimation (needed for triangulation of a cloud), it takes too long and when I try the integral images estimation it gives me the above error.

**Comment by stefanbuettner** [comment]
I starting to think that this is not a PCL issue but an issue with the function which transforms the mat into a pointcloud. Does it set the width and height of the cloud correctly? If the cloud has a rectangular shape when displayed, doesn't mean it's organized.

**Comment by santonatos** [comment]
it does not set the height neither the width and I think that is the cause. I think I fixed error by adding two lines of setting the height and the width. I will let you know.

**Comment by santonatos** [comment]
works with integral normal images, have fixed the length and width of the camera input Matrix
