### ISSUE TITLE
MALLOC_ALIGNED not defined with mingw

### ISSUE THREAD

**Issue by Norton-breman** [PointCloudLibrary/pcl#1891]
* Operating System and version: Win7 x64
* Compiler: gcc mingw32 with codeblocks
* PCL Version: current pcl git master

MALLOC_ALIGNED is not defined in pcl_macros.h when using gcc under windows 7 (mingw) resulting in error during aligned_malloc(size_t size) definition.
Comparing with pcl_macros.h from pcl 1.8.0 version it appears that #define MALLOC_ALIGNED 0 has been removed.

Adding 
" #else
  #define MALLOC_ALIGNED 0
" in line 378 makes compilation working again.

**Comment by taketwo** [comment]
This was removing for reasons described in #1651.

**Comment by Norton-breman** [comment]
Yes I saw this issue just after writing mine. The fact is that this changes generate the new error I described with gcc compiler on windows, and the error described in #1651 does not show up with the old version of pcl_macros.h ...

**Comment by taketwo** [comment]
Please post the exact error that you are getting.

As described in referenced issue, the macro `MALLOC_ALIGNED` is only checked for _existence_, not the _actual value_. In other words there is no difference either you `#define MALLOC_ALIGNED 0` or `#define MALLOC_ALIGNED 1`.

**Comment by Norton-breman** [comment]
My computer is running on another project. I will reproduce the error as soon as it finish.

**Comment by Norton-breman** [comment]
Hi, here is the CmakeError.log file :

Run Build Command:"C:/TDM-GCC-32/bin/mingw32-make.exe" "cmTC_128a2/fast"
C:/TDM-GCC-32/bin/mingw32-make.exe -f CMakeFiles\cmTC_128a2.dir\build.make CMakeFiles/cmTC_128a2.dir/build

mingw32-make.exe[1]: Entering directory 'D:/Dev/cpp/libs/pcl-master/build/CMakeFiles/CMakeTmp'

Building CXX object CMakeFiles/cmTC_128a2.dir/src.cxx.obj

C:\TDM-GCC-32\bin\g++.exe    -DHAVE_POSIX_MEMALIGN   -o CMakeFiles\cmTC_128a2.dir\src.cxx.obj -c D:\Dev\cpp\libs\pcl-master\build\CMakeFiles\CMakeTmp\src.cxx

D:\Dev\cpp\libs\pcl-master\build\CMakeFiles\CMakeTmp\src.cxx: In function 'int main()':

D:\Dev\cpp\libs\pcl-master\build\CMakeFiles\CMakeTmp\src.cxx:6:47: error: 'posix_memalign' was not declared in this scope

           return posix_memalign (&mem, 16, 100);

                                               ^

CMakeFiles\cmTC_128a2.dir\build.make:64: recipe for target 'CMakeFiles/cmTC_128a2.dir/src.cxx.obj' failed

mingw32-make.exe[1]: *** [CMakeFiles/cmTC_128a2.dir/src.cxx.obj] Error 1

mingw32-make.exe[1]: Leaving directory 'D:/Dev/cpp/libs/pcl-master/build/CMakeFiles/CMakeTmp'

Makefile:125: recipe for target 'cmTC_128a2/fast' failed

mingw32-make.exe: *** [cmTC_128a2/fast] Error 2


Return value: 1
Source file was:

        #include <stdlib.h>
        int main()
        {
          void* mem;
          return posix_memalign (&mem, 16, 100);
        }

**Comment by SergioRAgostinho** [comment]
Isn't this the CMake SSE test to check if your platform has actually posix_memalign defined?

See https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_find_sse.cmake#L43-L50

The result tells that it does NOT have it. Just to confirm, a quick google search returns this

https://stackoverflow.com/questions/10862121/undefined-reference-to-posix-memalign-using-mingw32
https://github.com/flame/blis/pull/9

`_aligned_malloc` seems to be what you're looking for :wink:

**Comment by Norton-breman** [comment]
Yes it works ! Thanks

**Comment by Norton-breman** [comment]
Oups I compiled ran another version off PCL (1.8.0) not pcl_master. It does not work !
Seems to have HAVE_MM_MALLOC defined but _mm_malloc is not (line 390).

**Comment by taketwo** [comment]
So when you run `cmake` for the first time, you get the following output in the beginning?

```
...
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Success
...
```

**Comment by Norton-breman** [comment]
Yes

**Comment by taketwo** [comment]
And then you get compilation error at line 390? Can you post it?

This would mean that `_mm_malloc` detection in CMake is broken...

**Comment by Norton-breman** [comment]
I have this error :
D:\Dev\cpp\libs\pcl-master\common\include\pcl\pcl_macros.h||In function 'void* aligned_malloc(size_t)':|
D:\Dev\cpp\libs\pcl-master\common\include\pcl\pcl_macros.h|391|error: '_mm_malloc' was not declared in this scope|

**Comment by Norton-breman** [comment]
I can get rid of this error adding #include <mm_malloc.h> at the start of the file. But then I have another error line 409 (ptr = _mm_free (ptr);)

**Comment by taketwo** [comment]
I was just about to suggest to add that include file!

Okay, but `_mm_free` exists in that file. However, it has no return value, maybe this is the problem? Can you remove `ptr = `?

**Comment by Norton-breman** [comment]
It seems to work !

**Comment by taketwo** [comment]
Great. After you are done compiling PCL and your project, please let us know if everything works and this fix did not unintentionally break something. I will then make a PR with the fix.

**Comment by Norton-breman** [comment]
Ok. If it is the same compilation time than for 1.8 version you will have to wait about 2 hours before I can answer. And I'm not sure I have selected the working options on my computer at the cmake stage since I did it in hurry to answer your questions...

**Comment by Norton-breman** [comment]
Ok so, compilation failed at 30% linking libpcl_features.dll with this message :
"ld returned 255 exit status"
But this error occured also with version 1.8. The only solution I found until now is to uncheck shared library in cmake. I will give it a try tomorow and keep you informed.

**Comment by Norton-breman** [comment]
Sorry, I can't confirm it yet ! It's seems to work but I have an issue building WITH_VTK enabled and I don't know why... If I disable WITH_VTK an other issue appears linking libpcl_io.dll ( undefined reference to `WSAStartup@8 ). I still trying to resolve it.

**Comment by Norton-breman** [comment]
Ok so, after desabling vtk and visualization.
And modifying build\io\tools\CMakeFiles\pcl_hdl_grabber.dir\link.txt and build\io\CMakeFiles\pcl_io.dir to add -lws2_32 at the end of third line :

 it definitly works !

**Comment by taketwo** [comment]
If you figure out how to fix these other issues in PCL configuration scripts, patches are welcome!

**Comment by Norton-breman** [comment]
I will take a look at this but I think it is beyond my knowledge! One workaround I found could be to say cmake to add this library (libws2_32.a) at the end of the command line and not at the begining (it is a [known issue](https://stackoverflow.com/a/12472772) with mingw), but I don't know how to do that.

**Comment by taketwo** [comment]
I found this [SO question](https://stackoverflow.com/questions/36520283/how-to-link-ws2-32-in-clion) suggesting that we just need a CMake command to link against these libraries. However, I very much dislike using global `link_libraries`. Rather, we should do `target_link_libraries` for affected targets. Did I understand correctly that it is only "pcl_io" library that causes problems?

**Comment by Norton-breman** [comment]
Yes, this is only for pcl_io. The rest of the pcl libraries are fine!
The link you provided suggest adding -lws2_32 in the CMAKE_EXE_LINKER_FLAGS wich I did not test. I only added this in the CMAKE_CXX_FLAGS and CMAKE_C_FLAGS but like I said earlier the library is linked to at the start of the generated command line instead of the end.

**Comment by Norton-breman** [comment]
Oh and there is another error I had to deal with.
The "ld returned 255 exit status" I mentionned on monday. It happens when building pcl in shared library. The solution was to build it only in Release mode. It seems that the pcl_feature.dll is to big when builded in Debug mode (because of Debug symbols maybe). I don't know if it is related to my computer (I am not sure of this because I have 16G of RAM) or to mingw capabilities.

**Comment by Norton-breman** [comment]
Ok, I just tryed to add -lws2_32 to the CMAKE_CXX_STANDARD_LIBRARIES and CMAKE_C_STANDARD_LIBRARIES and it works. So I don't know how to do that but maybe you can add a test on WITH_VTK and if it is desabled automaticaly add -lws2_32 to the CMAKE_CXX_STANDARD_LIBRARIES and CMAKE_C_STANDARD_LIBRARIES

**Comment by taketwo** [comment]
Sorry, I meant to link the [_answer_](https://stackoverflow.com/a/36521313/1525865) to the question, not the question itself.
