### ISSUE TITLE
errors opening point clouds .ply in pcl 

### ISSUE THREAD

**Issue by Gregoriomartjim** [PointCloudLibrary/pcl#1911]
Hello i have a problem when i am trying to open a .ply file in pcl, this is a point cloud, and i have one example running , but just one, when i try to run another point cloud with the same header,i get an error that i dont know how to solve it.

~/Kermit/opensfm/depthmaps/merge.ply:1: parse error: couldn't read the magic string
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!

Hope someone could help me out 
I appriciate

**Comment by taketwo** [comment]
Please **do not** use the issue tracker for personal support requests (use  [mailing list](http://www.pcl-users.org/)).
