### ISSUE TITLE
PCL compilation error LNK2019

### ISSUE THREAD

**Issue by ziqB** [PointCloudLibrary/pcl#1915]
Hi 
I'm currently trying to build PCL so that i can use RTABmaps
I ran into some issues while trying to build the PCL

I did some research on the error LNK2019 and it says that the linker can't find a matching definition for an external symbol in any of the link files.

I did some more research and found that this issue has been solved before but the answer to it is too vague for me to understand. it says that there was a mismatch error in between PCL 1.8.0 and 1.6.0 ,and the mismatch was in choosing the Dependencies version of Boost, eigen, flann, OpenNI and VTK 5.8.0.
How do i resolve this error 

I hope someone could help me

Thanks in advance

**Comment by taketwo** [comment]
Please **do not** use this issue tracker for personal support requests (use  [mailing list](http://www.pcl-users.org/)). Also note that this problem description is not sufficient to people to help you. You will be asked for your OS, PCL version, specific error message that you get, the link to the existing solution that you do not understand, etc.

**Comment by ziqB** [comment]
Alright thanks for the pointers i am quite new to this field of expertise,
I will improve my question and use the mailing list.

Have a great day

ziqB



On Fri, Jun 30, 2017 at 3:50 PM, Sergey Alexandrov <notifications@github.com
