### ISSUE TITLE
Failing test on Debian unstable

### ISSUE THREAD

**Issue by jspricke** [PointCloudLibrary/pcl#1921]
I've some failing test with the recent RC:
``
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:501: Failure
Expected: (diff) <= (epsilon), actual: 2.0465e-14 vs 1.25e-14
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:514: Failure
Expected: (diff) <= (epsilon), actual: 2.0465e-14 vs 1.25e-14
``
I would propose to set epsilon to 1e-13, still close enough to 0 ;).

``
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:943: Failure
The difference between plane->values[i] and test[i] is 4.4742839235305789, which exceeds tolerance, where
plane->values[i] evaluates to 0.87886607646942139,
test[i] evaluates to 5.3531500000000003, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:943: Failure
The difference between plane->values[i] and test[i] is 2.4231674071693421, which exceeds tolerance, where
plane->values[i] evaluates to 0.47597259283065796,
test[i] evaluates to 2.8991400000000001, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:943: Failure
The difference between plane->values[i] and test[i] is 0.16453008593130111, which exceeds tolerance, where
plane->values[i] evaluates to 0.032317914068698883,
test[i] evaluates to 0.196848, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:943: Failure
The difference between plane->values[i] and test[i] is 41.188349713134762, which exceeds tolerance, where
plane->values[i] evaluates to -8.0904502868652344,
test[i] evaluates to -49.278799999999997, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:951: Failure
The difference between plane->values[i] and test[i] is 4.4742838639259341, which exceeds tolerance, where
plane->values[i] evaluates to 0.87886613607406616,
test[i] evaluates to 5.3531500000000003, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:951: Failure
The difference between plane->values[i] and test[i] is 2.4231674369716645, which exceeds tolerance, where
plane->values[i] evaluates to 0.47597256302833557,
test[i] evaluates to 2.8991400000000001, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:951: Failure
The difference between plane->values[i] and test[i] is 0.16453005612897872, which exceeds tolerance, where
plane->values[i] evaluates to 0.032317943871021271,
test[i] evaluates to 0.196848, and
tolerance evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/common/test_eigen.cpp:951: Failure
The difference between plane->values[i] and test[i] is 41.18834780578613, which exceeds tolerance, where
plane->values[i] evaluates to -8.0904521942138672,
test[i] evaluates to -49.278799999999997, and
tolerance evaluates to 0.0001.
``
No idea what's going on here.

``
/home/jspricke/src/pointclouds/pcl/test/features/test_rift_estimation.cpp:126: Failure
The difference between rift.histogram[i] and correct_rift_feature_values[i] is 0.013474542647600174, which exceeds 1e-4, where
rift.histogram[i] evaluates to 0.0052254572510719299,
correct_rift_feature_values[i] evaluates to 0.018699999898672104, and
1e-4 evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/features/test_rift_estimation.cpp:126: Failure
The difference between rift.histogram[i] and correct_rift_feature_values[i] is 0.013520274311304092, which exceeds 1e-4, where
rift.histogram[i] evaluates to 0.021120274439454079,
correct_rift_feature_values[i] evaluates to 0.0076000001281499863, and
1e-4 evaluates to 0.0001.
``
Sounds like they are swapped?

``
/home/jspricke/src/pointclouds/pcl/test/features/test_cppf_estimation.cpp:91: Failure
The difference between feature_cloud->points[2572].f1 and 0.0669282 is 0.0100925858551979, which exceeds 1e-4, where
feature_cloud->points[2572].f1 evaluates to 0.056835614144802094,
0.0669282 evaluates to 0.066928199999999993, and
1e-4 evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/features/test_cppf_estimation.cpp:93: Failure
The difference between feature_cloud->points[2572].f3 and 0.7856042 is 0.00011034929199216226, which exceeds 1e-4, where
feature_cloud->points[2572].f3 evaluates to 0.78549385070800781,
0.7856042 evaluates to 0.78560419999999997, and
1e-4 evaluates to 0.0001.
/home/jspricke/src/pointclouds/pcl/test/features/test_cppf_estimation.cpp:101: Failure
The difference between feature_cloud->points[2572].alpha_m and -1.852997 is 0.0054822514266967826, which exceeds 1e-4, where
feature_cloud->points[2572].alpha_m evaluates to -1.8475147485733032,
-1.852997 evaluates to -1.852997, and
1e-4 evaluates to 0.0001.
``
I would propose to increase the epsilon.

``
/home/jspricke/src/pointclouds/pcl/test/features/test_pfh_estimation.cpp:472: Failure
The difference between fpfhs->points[0].histogram[14] and 9.37615 is 0.0093137145996085025, which exceeds 1e-3, where
fpfhs->points[0].histogram[14] evaluates to 9.3854637145996094,
9.37615 evaluates to 9.3761500000000009, and
1e-3 evaluates to 0.001.
/home/jspricke/src/pointclouds/pcl/test/features/test_pfh_estimation.cpp:473: Failure
The difference between fpfhs->points[0].histogram[15] and 17.963 is 0.0095850830078134663, which exceeds 1e-3, where
fpfhs->points[0].histogram[15] evaluates to 17.953414916992188,
17.963 evaluates to 17.963000000000001, and
1e-3 evaluates to 0.001.
``
Same here.

``
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:81: Failure
      Expected: 2960
To be equal to: (*walls_indices)[walls_indices->size () * 3 / 4]
      Which is: 2503
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:89: Failure
The difference between cond_num_turtle and 20661.7663 is 1390.6013843263863, which exceeds 0.5, where
cond_num_turtle evaluates to 22052.367684326386,
20661.7663 evaluates to 20661.766299999999, and
0.5 evaluates to 0.5.
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:95: Failure
The difference between cond_num_turtle_sampled and 5795.5057 is 265.55314486777115, which exceeds 0.5, where
cond_num_turtle_sampled evaluates to 6061.0588448677709,
5795.5057 evaluates to 5795.5056999999997, and
0.5 evaluates to 0.5.
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:97: Failure
      Expected: (*turtle_indices)[0]
      Which is: 80752
To be equal to: 80344
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:98: Failure
      Expected: (*turtle_indices)[turtle_indices->size () / 4]
      Which is: 64746
To be equal to: 145982
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:99: Failure
      Expected: (*turtle_indices)[turtle_indices->size () / 2]
      Which is: 83995
To be equal to: 104557
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:100: Failure
      Expected: (*turtle_indices)[turtle_indices->size () * 3 / 4]
      Which is: 166770
To be equal to: 41512
/home/jspricke/src/pointclouds/pcl/test/filters/test_sampling.cpp:101: Failure
      Expected: (*turtle_indices)[turtle_indices->size () - 1]
      Which is: 81852
To be equal to: 136885
``
No idea what's going on.

``
/home/jspricke/src/pointclouds/pcl/test/registration/test_registration_api.cpp:541: Failure
The difference between R_LM_1_float.z () and R_ref.z () is 0.00012692809104919434, which exceeds 1e-4f, where
R_LM_1_float.z () evaluates to 0.15780343115329742,
R_ref.z () evaluates to 0.15767650306224823, and
1e-4f evaluates to 9.9999997473787516e-05.
``
Increase epsilon.

@taketwo, @SergioRAgostinho do the tests work for you? I can send a pull request, but wanted to check back with you first before doing the work. I suspect it's either the new Eigen (3.3.4) or a problem with my hardware (had to change it recently).

**Comment by SergioRAgostinho** [comment]
> do the tests work for you?

They have been failing for me since last year 😅  See https://github.com/PointCloudLibrary/pcl/issues/1702#issuecomment-243011983 and the conversation below that one.

**Comment by jspricke** [comment]
I did a quick search, but missed that one, but now as you say so I remember it :). But as we have multiple reports now, I would propose to at least increase the epsilons.

**Comment by SergioRAgostinho** [comment]
No complaints by me.

**Comment by jspricke** [comment]
Closing to continue in #1702
