### ISSUE TITLE
Generic Look Up Table Implementation

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1922]
I just noticed every time a class/algorithm needs to implement a look up table, it's being implemented from scratch. We should provide a generic interface for developers to make use of.

**Comment by taketwo** [comment]
For reference, can you list some of the classes that would need it?

**Comment by SergioRAgostinho** [comment]
I should have replied last year. Have no idea what was then. Past Sérgio's ideas.
