### ISSUE TITLE
Consider templating color conversion functions in "point_types_conversion.h"

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#1928]
Rewrite `PointCloudXYZRGBtoXYZHSV` and alike to be templated on input point type and accept any type as long as it has `rgba` field.

**Comment by SergioRAgostinho** [comment]
> ## Your Environment
> 
>     * PCL Version: the master branch
> 
> 
> ## Context
> 
> [pcl/common/include/pcl/point_types_conversion.h](https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L138-L146)
> 
> Lines 138 to 146 in [9467b94](/PointCloudLibrary/pcl/commit/9467b944ee3e30bb4cf8445d861c280f0fba1020)
>    /** \brief Convert a XYZRGB point type to a XYZHSV 
>      * \param[in] in the input XYZRGB point 
>      * \param[out] out the output XYZHSV point 
>      * \todo include the A parameter but how? 
>      */ 
>    inline void 
>    PointXYZRGBAtoXYZHSV (const PointXYZRGBA& in, 
>                          PointXYZHSV&        out) 
>    { 
> 
> the alpha value is not used during the conversion.
> In addition, this function duplicates the code from
> 
> [pcl/common/include/pcl/point_types_conversion.h](https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L101-L107)
> 
> Lines 101 to 107 in [9467b94](/PointCloudLibrary/pcl/commit/9467b944ee3e30bb4cf8445d861c280f0fba1020)
>    /** \brief Convert a XYZRGB point type to a XYZHSV 
>      * \param[in] in the input XYZRGB point  
>      * \param[out] out the output XYZHSV point 
>      */ 
>    inline void  
>    PointXYZRGBtoXYZHSV (const PointXYZRGB& in, 
>                         PointXYZHSV&       out) 
> 
> Since `PointXYZRGBAtoXYZHSV()` is used only by
> 
> [pcl/common/include/pcl/point_types_conversion.h](https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L316-L322)
> 
> Lines 316 to 322 in [9467b94](/PointCloudLibrary/pcl/commit/9467b944ee3e30bb4cf8445d861c280f0fba1020)
>    /** \brief Convert a XYZRGB point cloud to a XYZHSV 
>      * \param[in] in the input XYZRGB point cloud 
>      * \param[out] out the output XYZHSV point cloud 
>      */ 
>    inline void 
>    PointCloudXYZRGBAtoXYZHSV (const PointCloud<PointXYZRGBA>& in, 
>                               PointCloud<PointXYZHSV>&        out) 
> 
> But `PointCloudXYZRGBAtoXYZHSV()` is never used.
> ## Expected Behavior
> 
> Remove the above two functions `PointCloudXYZRGBAtoXYZHSV()`
> and `PointXYZRGBAtoXYZHSV()`.
> 
> Are there any reason to introduce the above two functions?
> ## Code to Reproduce
> 
> See the code above.
> ## Possible Solution
> 
> Remove the two unsed functions.

_Originally posted by @csukuangfj in https://github.com/PointCloudLibrary/pcl/issues/2477
