### ISSUE TITLE
Show several models in a view

### ISSUE THREAD

**Issue by arianaa30** [PointCloudLibrary/pcl#1941]
Hi, 
I'm new to PCL. But can we show several models in a single view? For instance three models, and we can specify their positions in space, their distance from camera, etc.? 

Are there any example snippet on that?

**Comment by SergioRAgostinho** [comment]
This is an issue tracker. Use the mailing list for questions such as these.

The short answer is yes. Have a look at our available documentations, more specifically the tutorials.

http://pointclouds.org/documentation/
