### ISSUE TITLE
FPS shown on the bottom left

### ISSUE THREAD

**Issue by arianaa30** [PointCloudLibrary/pcl#1944]
I am requesting a feature: That FPS shown on the bottom left of visualization window, is there any ways to access it? I need to print it.

**Comment by taketwo** [comment]
Hi, right now there is no access to it. But it will be straightforward to add, we just need to store the computed `fps` [here](https://github.com/PointCloudLibrary/pcl/blob/ad85f523e1b3b2f9ae2b29a2099a9df2471985e2/visualization/src/pcl_visualizer.cpp#L4445) to a member field in `PCLVisualizer`, and create an accessor for it.

You can try it yourself and submit a PR, or I can do this, but probably not in the next week or two.

**Comment by arianaa30** [comment]
I was trying to do it myself, and realized I used the binary installation. No way to do it unless I compile, right?

**Comment by taketwo** [comment]
Unfortunately no, no way around without recompiling.
