### ISSUE TITLE
Kfpcs not working

### ISSUE THREAD

**Issue by TFisichella** [PointCloudLibrary/pcl#1948]
Hello,

I'm using PCL 1.8 and I've tried to run the Kfpcs registration algorithme following this test example : https://github.com/PointCloudLibrary/pcl/blob/master/test/registration/test_kfpcs_ia.cpp.

The following chunk of code compile and run without error but the tranformation matrix I get is always the same (Identity matrix).
Is there an error in the source code or did I make something wrong ?

Here is the part of the code I run : 

  PointCloud <PointXYZI> cloud_source_aligned;
  KFPCSInitialAlignment <PointXYZI, PointXYZI> kfpcs_ia;
  kfpcs_ia.setInputSource (cloud_source_ptr);
  kfpcs_ia.setInputTarget (cloud_target_ptr);

  kfpcs_ia.setNumberOfThreads (1);
  kfpcs_ia.setApproxOverlap (0.5);
  kfpcs_ia.setDelta (1000, false);
  kfpcs_ia.setScoreThreshold (0.5);

  kfpcs_ia.align (cloud_source_aligned);
  Eigen::Matrix4f transformation = kfpcs_ia.getFinalTransformation();
  std::cout << transformation << std::endl;

**Comment by SergioRAgostinho** [comment]
This is an issue tracker. Please use the mailing list pcl-users for these type of questions.

If you eventually manage to find an issue with the current implementation then by all means, file another issue detailing your discoveries.

**Comment by Paulmacre** [comment]
your "setDelta " is too big,Delta should be set little as its down sample size.
