### ISSUE TITLE
pcl_viewer not displaying points when used with pcd file with size 8

### ISSUE THREAD

**Issue by JarnoRFB** [PointCloudLibrary/pcl#1953]
## Your Environment

* Operating System and version: Ubuntu 16.04
* PCL Version: 1.8

## Expected Behavior

In the documentation of the pcd file format (http://pointclouds.org/documentation/tutorials/pcd_file_format.php) it says that `SIZE` could be set to 8 for double precision. 
The points should be correctly displayed or at least an error message should be given if the pcd file is malformed.

## Current Behavior

If one sets `SIZE` to 8 in, e.g. the example file from the documentation, pcl_viewer opens, but does not display any points. 

```
# .PCD v.7 - Point Cloud Data file format
VERSION .7
FIELDS x y z rgb
SIZE 8 8 8 8
TYPE F F F F
COUNT 1 1 1 1
WIDTH 19
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 19
DATA ascii
0.93773 0.33763 0 4.2108e+06
0.90805 0.35641 0 4.2108e+06
0.81915 0.32 0 4.2108e+06
0.97192 0.278 0 4.2108e+06
0.944 0.29474 0 4.2108e+06
0.98111 0.24247 0 4.2108e+06
0.93655 0.26143 0 4.2108e+06
0.91631 0.27442 0 4.2108e+06
0.81044 0.32222 0 4.2108e+06
0.74459 0.32192 0 4.2108e+06
0.69927 0.32278 0 4.2108e+06
0.8102 0.29315 0 4.2108e+06
0.75504 0.29765 0 4.2108e+06
0.8102 0.24399 0 4.2108e+06
0.74995 0.24723 0 4.2108e+06
0.68049 0.29768 0 4.2108e+06
0.66509 0.29002 0 4.2108e+06
0.69441 0.2526 0 4.2108e+06
0.62807 0.22187 0 4.2108e+06
```

**Comment by Wyllich** [comment]
First of all, the number of points (line width and points) should be equal to 8 and not 213.
Then, the rgb is written in the wrong format.

Try something like this : 
`# .PCD v.7 - Point Cloud Data file format
VERSION .7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 8
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 8
DATA ascii
0.93773 0.33763 0 12675648
0.90805 0.35641 0 12675648
0.81915 0.32 0 12675648
0.97192 0.278 0 12675648
0.944 0.29474 0 12675648
0.98111 0.24247 0 12675648
0.93655 0.26143 0 12675648
0.91631 0.27442 0 12675648`

**Comment by JarnoRFB** [comment]
I updated the file example file with the right number of points. The problem is still that the points can only be seen when `SIZE` is set to 4, but not when it is set to 8.

**Comment by SergioRAgostinho** [comment]
What happens if you change the size of the rgb field to 4?

**Comment by JarnoRFB** [comment]
It is true that it shows a few points then, but not as many as if I set the `SIZE` of all fields to 4.

**Comment by SergioRAgostinho** [comment]
The issue comes from the fact that you're trying to store double precision coordinate data in the normal point types defined by PCL which all have single precision float as coordinates. That's why it complains it can't find a match for the field and it won't store your coordinates properly.

To be able to have double precision coordinates you're gonna need to register a custom point type on your own, which can in fact store the data with the precision you request on your pcd file. That's the issue pcl_viewer is struggling with.

Check the output of the snippet below. 

```cpp
#define PCL_NO_PRECOMPILE
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>

namespace pcl
{
  #define PCL_ADD_UNION_POINT4D_DOUBLE \
    union EIGEN_ALIGN16 { \
      double data[4]; \
      struct { \
        double x; \
        double y; \
        double z; \
      }; \
    };

  struct _PointXYZDouble
  {
    PCL_ADD_UNION_POINT4D_DOUBLE; // This adds the members x,y,z which can also be accessed using the point (which is float[4])

    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };

  struct EIGEN_ALIGN16 PointXYZDouble : public _PointXYZDouble
  {
    inline PointXYZDouble (const _PointXYZDouble &p)
    {
      x = p.x; y = p.y; z = p.z; data[3] = 1.0;
    }

    inline PointXYZDouble ()
    {
      x = y = z = 0.0;
      data[3] = 1.0;
    }

    inline PointXYZDouble (double _x, double _y, double _z)
    {
      x = _x; y = _y; z = _z;
      data[3] = 1.0;
    }

    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };
}

  POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::_PointXYZDouble,
    (double, x, x)
    (double, y, y)
    (double, z, z)
  )
  POINT_CLOUD_REGISTER_POINT_WRAPPER(pcl::PointXYZDouble, pcl::_PointXYZDouble)

int
main ()
{
  pcl::PointCloud<pcl::PointXYZ> cloud;
  if (pcl::io::loadPCDFile<pcl::PointXYZ> ("/tmp/test_2.pcd", cloud))
  {
    PCL_ERROR ("Couldn't read PCD file \n");
    exit(1);
  }
  std::cout << "Cloud1 size: " << cloud.size () << std::endl;
  for (size_t i = 0; i < cloud.size (); ++i)
    std::cout << "x: " << cloud[i].x
              << " y: " << cloud[i].y
              << " z: " << cloud[i].z
              << std::endl;

  pcl::PointCloud<pcl::PointXYZDouble> cloud2;
  if (pcl::io::loadPCDFile<pcl::PointXYZDouble> ("/tmp/test_2.pcd", cloud2))
  {
    PCL_ERROR ("Couldn't read PCD file \n");
    exit(1);
  }
  std::cout << "Cloud2 size: " << cloud2.size () << std::endl;
  for (size_t i = 0; i < cloud2.size (); ++i)
    std::cout << "x: " << cloud2[i].x
              << " y: " << cloud2[i].y
              << " z: " << cloud2[i].z
              << std::endl;

	return 0;
}
```

prints the following output
```shell
$ ./pcd_double_fields 
Failed to find match for field 'x'.
Failed to find match for field 'y'.
Failed to find match for field 'z'.
Cloud1 size: 8
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
x: 0 y: 0 z: 0
Cloud2 size: 8
x: 0.93773 y: 0.33763 z: 0
x: 0.90805 y: 0.35641 z: 0
x: 0.81915 y: 0.32 z: 0
x: 0.97192 y: 0.278 z: 0
x: 0.944 y: 0.29474 z: 0
x: 0.98111 y: 0.24247 z: 0
x: 0.93655 y: 0.26143 z: 0
x: 0.91631 y: 0.27442 z: 0
```

Maybe the documentation should express that better. Feel free to making that extra clarification on the tutorial.
