### ISSUE TITLE
Memory map error when filter applying

### ISSUE THREAD

**Issue by romdos** [PointCloudLibrary/pcl#1963]
Hi, all!
I've faced with a hard problem when I wish to apply some filter, for example Statitstical outlier removal from #include <pcl/filters/statistical_outlier_removal.h>. 
I use Ubuntu 16.04 and installed pcl 1.8 from source according to [this](https://github.com/hsean/Capstone-44-Object-Segmentation/wiki/PCL-1.8:-Ubuntu-14.04-Installation-Guide) guide. One thing that I've changed is a label in cmake row: instead of -DCMAKE_BUILD_TYPE=None I've written -DCMAKE_BUILD_TYPE=RelWithDebInfo
because when I've built with None option it run very slow. So I've built pcl 1.8 successfully except some warning relating to syntax and I compile for example next snippet of code also without problems.
```
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types_conversion.h>
#include <pcl/filters/statistical_outlier_removal.h>

typedef pcl::PointXYZRGBA PointType;
typedef pcl::Normal NormalType;
typedef pcl::ReferenceFrame RFType;
typedef pcl::SHOT352 DescriptorType;
typedef pcl::PointCloud<PointType> Cloud;
typedef Cloud::Ptr CloudPtr;

int main(int argc, char** argv)
{
    CloudPtr input_cloud(new Cloud);
    if (pcl::io::loadPCDFile("/home/roman/point_clouds/box_far.pcd", *input_cloud) < 0)
        return -1;
    CloudPtr cloud_filtered (new Cloud);
    // Create the filtering object
    pcl::StatisticalOutlierRemoval<PointType> sor;
    sor.setInputCloud (input_cloud);
    sor.setMeanK (50);
    sor.setStddevMulThresh (1.0);
    sor.filter (*cloud_filtered);
    return 0;
}
```
But when I run it with my existing (I've checked it out) point cloud and with a next CMakeLists.txt
```
cmake_minimum_required(VERSION 3.8)
project(pcl_examples)

set (CMAKE_CXX_STANDARD 11)

find_package(PCL 1.8.1 REQUIRED )

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (extract_indices example_extract_indices.cpp)
target_link_libraries (extract_indices ${PCL_LIBRARIES})
```
 it brings me next crash error (look at attached screenshot). What is the bug and what and how can I solve it? Any help!
![pcl_error](https://user-images.githubusercontent.com/15799418/29296025-61d323aa-8160-11e7-9acd-8f56dcf0fe39.png)
Note: Everything was fine in pcl 1.7.

**Comment by taketwo** [comment]
You are getting a crash while running a certain `./cg` executable? What is this? According to your CMake script, you should have `extract_indices` executable.

**Comment by romdos** [comment]
Sorry for misleading, I've pasted another CMakeList here, but error was not because of that. I've revealed that there is #define NO_PRECOMPILE option in new version. I've pasted it in my code and it began to work.  Thanks!

**Comment by taketwo** [comment]
Great that it works for you now. Can you please explain in more detail what was the problem and the fix. Does it something we need to change within the library?

**Comment by romdos** [comment]
After running ./cg executable which runs the code given in the post I had a problem that is shown in screenshot. There is no problem in CMakeLists. The problem was as I understood in including headers concerning filters (but not only). As I mentioned  #define PCL_NO_PRECOMPILE option includes ../impl folder where are appropriate headers. I don't why does it works but it works.

**Comment by taketwo** [comment]
Thanks for the explanation!
