### ISSUE TITLE
runtime Exception in pcl 1.8.1

### ISSUE THREAD

**Issue by todkang** [PointCloudLibrary/pcl#1964]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: windows 7  professional
* Compiler:Microsoft Visual Studio 2017
* PCL Version:V1.8.1

## Current Behavior

display  cloud point  and add some objects such as sphere, cube, 3dtext 
and runs  viewer.spinOnce(); 
cause crash.
The same code runs OK in PCL 1.7 
debug shows ti crash at 
0x000007FEE16253F6 (vtkRenderingOpenGL2-8.0.dll) 
pcl_visualization_release.dll
Exception:  0xC0000005:  Location 0x0000000000000008 Access violation。

## Code to Reproduce

	pcl::ConvexHull<PointT> hull;
						hull.setInputCloud (clicked_points_3d);
						hull.reconstruct (*cloud_hull);

						//pcl::io::savePCDFile("test.pcd",*cloud_hull);
						std::cout << "convexHull has " << cloud_hull->points.size() << " Points" << std::endl;
 						for (int i=0;i<cloud_hull->points.size();i++)
 						{
 							std::cout << cloud_hull->at(i).x << "\t" << cloud_hull->at(i).y << "\t" << cloud_hull->at(i).z << std::endl;
 						}
 						std::cout << std::endl;
						
						std::stringstream ss;
						for (int i=0;i<cloud_hull->points.size();i++)
						{
							ss << "sphere_"<<i;
							if (!viewer.updateSphere(cloud_hull->points.at(i),0.2,0,0,255,ss.str()))
							{
								viewer.addSphere(cloud_hull->points.at(i),0.2,0,0,255,ss.str());
							}
						}
					 if(!viewer.updateText(displayText, 10, 480, "displayText"))
						{
							viewer.addText(displayText, 10, 480, "displayText");
						}	
					if (!viewer.updateText(modeText, 10, 460, "modeText"))
		                  {
		                   viewer.addText(modeText, 10, 450,"modeText"); 

		                  }
			if (cloud_mutex_.try_lock ())
			{   
				viewer.spinOnce();
				cloud_mutex_.unlock();
			}

**Comment by UnaNancyOwen** [comment]
Unfortunately, PCL have unresolved some bug in VTK OpenGL2 backend  support on Windows.
Please check whether reproduce this problem in PCL that linked VTK OpenGL backend. (PCL All-in-one Installer includes pre-built PCL that linked VTK OpenGL backend. You can use it.)

**Comment by todkang** [comment]
Thanks for replying ,It's VTK OpenGL2 backend problem.
But PCL All-in-one Installer has not included VTK dll files. 
There is a 'Error: no override found for 'vtkPolyDataMapper'.
I want to solve it by adding VTK_MODULE_INIT(vtkRenderingOpenGL);
But can't link. 
Is there any better method than recompiling vtk ?

**Comment by caomw** [comment]
Good!

**Comment by todkang** [comment]
solved, thanks. recompile vtk8, and using OpenGL backend.

**Comment by DongDongXA** [comment]
@todkang do u mean recompile vtk8 with shared libs and using OpenGL backend, then put these libs under PCL All-in-one 3rdParty path?

**Comment by todkang** [comment]
Recompile vtk8 with OpenGL, not OpenGL2 as backend.

Using the recompiled vtk8.

VTK_MODULE_INIT(vtkRenderingOpenGL); // VTK was built with vtkRenderingOpenGL
VTK_MODULE_INIT(vtkInteractionStyle);


发件人: DongDongXA [mailto:notifications@github.com]
发送时间: 2018年6月6日 20:53
收件人: PointCloudLibrary/pcl <pcl@noreply.github.com>
抄送: Kangtao (Tod) <kangtao@huawei.com>; Mention <mention@noreply.github.com>
主题: Re: [PointCloudLibrary/pcl] runtime Exception in pcl 1.8.1 (#1964)


@todkang<https://github.com/todkang> do u mean recompile vtk8 with shared libs and using OpenGL backend, then put these libs under PCL All-in-one 3rdParty path?
