### ISSUE TITLE
Exporting textureMesh

### ISSUE THREAD

**Issue by tensorfreitas** [PointCloudLibrary/pcl#1966]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: windows10
* Compiler: VC++
* PCL Version: 1.8.0

## Expected Behavior
I was playing with textured meshes and implemented a texture in a simple cylinder. In the viewer everything seems ok:

![jxd9h6e - imgur](https://user-images.githubusercontent.com/1709142/33236569-74ce1024-d24f-11e7-9435-c1d645ea36c2.png)

When I exported the mesh using `pcl::io::saveOBJFile` and the result was this (in meshLab):

![cikd3ha - imgur](https://user-images.githubusercontent.com/1709142/33236575-81973312-d24f-11e7-825e-cc609424d2b8.png)

I realized that the  `pcl::io::saveOBJFile` function, when exporting the faces the problem is related to the texture index exported. For example:

```
f 87/1168/87 95/1169/95 15/1170/15
f 111/1171/111 139/1172/139 143/1173/143
f 143/1174/143 216/1175/216 7/1176/7
f 217/1177/217 7/1178/7 218/1179/218
```

the texture indices exported (which do not exist in the texture map vector) are wrong and should be equal to the normal and vertex indices. I noticed that in the code the exportation occurs as:
`
fs << " " << idx << "/" << 3 * (i + f_idx) + j + 1 << "/" << idx;`

I have manually calculated the uv values for each vertex, assigning a single uv to each vertex. This exportation leads to indices of uv's exported to the face that do not exist. After changing the code of the funcion to 

`
fs << " " << idx << "/" << idx << "/" << idx;`

the mesh appears correct in meshLab. 

Since I'm working with textures in PCL for the first time, is this a bug or am I just using a different method of uv mapping from PCL?

**Comment by SergioRAgostinho** [comment]
Based on the images it appears to be a bug. Since the fix appears to be simple, do you mind submitting a PR with it?

Could also include the code you used to generate the original mesh?

**Comment by Goldesel23** [comment]
Sorry for the late response, but I think the current version of this function has been updated in the meanwhile. The lines I have changed in my implementation are not present anymore in the repo. I don't know if the problem persists, but if I have some time I can test it and see if it is resolved.

**Comment by mvieth** [comment]
Since PR #4971 is now merged, this problem should be fixed. I don't have the code to create this textured cylinder, so I can't test this particular mesh, but the general problem described here is fixed by the pull request
