### ISSUE TITLE
HDL Grabber not working. (PCL1.7.2 bug)

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#1969]
## Environment

  * PCL 1.7.2 
  * Visual studio 2012 (both 32-bit) 
  *  windows 7. 

 ##Expected Behavior 

 A visualization window with pcap files on display. 

## Current Behavior

 A visualization box with no data on display. 

##Context

[HDL_Grabber PCL tutorial](http://pointclouds.org/documentation/tutorials/hdl_grabber.php)

I am trying to visualize a HDL-64E PCAP file with .xml calibration file but I am not getting any output in the window. 

this is my main argument in order to tackle the errors I am getting by using the tutorial program directly. Without these modifications I am not able to build the program. Any suggestions? 

`int main (int argc, char ** argv)
{
  pcl::HDLGrabber grabber ("abc.xml", "xyz.pcap");

  pcl::visualization::PointCloudColorHandlerGenericField<pcl::PointXYZI> color_handler ("intensity");

  SimpleHDLViewer v (grabber, color_handler);

  v.run();`

EDIT: After running the program again I realized that the grabber never gets initialized in the first place. The grabber.start( ) command doesn't initialize the data exchange. Also the boost signal variable cloud_connections shows to be disconnected at the end of the viewer function but never connected. Am I missing something?

**Comment by UnaNancyOwen** [comment]
Can you reproduce your problem with the latest version of PCL (that is PCL 1.8.1)?
If this problem reproduced in latest version of PCL, Could you provide XML and PCAP?

(By the way, the pre-built PCL included in PCL All-in-one Installer is disabled WITH_PCAP option.
If you want to retrieve data from pcap file, Please build PCL with enable WITH_PCAP option from source code yourself.)

**Comment by kavinat** [comment]
Thank you for replying so quick. I am facing an entirely different issue with 1.8.1 and not able to execute a basic cloud viewer program. I am getting unresolved external symbols issue for vtkDebugLeakManager while building. despite adding all the libraries and include and adding the bin to the system path variable. 

Coming back to the current issue, I am not familiar enough with the PCL source-code to alter it. Can you please tell me how to enable the WITH_PCAP option?

**Comment by UnaNancyOwen** [comment]
Are you using CMake to generate your own projects? We don't support generate project without CMake.
Please refer to [this tutorial](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php) about how to using PCL in your own project.

The [CMakeLists.txt](http://pointclouds.org/documentation/tutorials/hdl_grabber.php#compiling-and-running-the-program) of HDLGrabber tutorial page is incorrect. Please use the following.

```cmake
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

project(pcl_hdl_viewer_simple)

find_package(PCL 1.2 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(pcl_hdl_viewer_simple hdl_viewer_simple.cpp)
target_link_libraries(pcl_hdl_viewer_simple ${PCL_LIBRARIES})
```

Please see [here](http://unanancyowen.com/en/pcl-with-velodyne/#comment-1281) about how to build PCL with enable WITH_PCAP option on Windows.

**Comment by kavinat** [comment]
Is it possible to build PCL all in one Installer with PCAP using the same steps or do I need to build all the 3rd party libraries and PCL separately? I have already downlaoded Winpcap and set it as an environment variable.

**Comment by UnaNancyOwen** [comment]
You need to build PCL from source code using CMake.
However, You can use 3rdParty (Boost, Eigen, FLANN, QHull, VTK, OpenNI2) other than WinPCAP that included in PCL All-in-one Installer.

**Comment by wangguojun2018** [comment]
I build PCL with WITH_PCAP option. my visual studio is 2017. Then I build sample program successfully in http://pointclouds.org/documentation/tutorials/hdl_grabber.php.But when I run the program with parameter “-calibrationFile Calibration.xml -pcapFile data64.pcap”，I found the errors in following:
![image](https://user-images.githubusercontent.com/36224780/37383843-55fe8e8a-2786-11e8-8962-e33fd87ff823.png)
