### ISSUE TITLE
unresolved external symbol error VTK (PCL 1.8.1)

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#1970]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

Failing to compile PCL programs due to unresolved external errors. 

## Your Environment

* Windows7 64 bit
* VS2015 Community
* PCL 1.8.1

## Expected Behavior

A cloud viewer window with the pcd file being visualized

## Current Behavior

Error in building the project.

## Possible Solution

Giving correct path to the libraries of dependencies , but the error remains the same. 

## Code to Reproduce

```cpp
#include <pcl/visualization/cloud_viewer.h>
#include <iostream>
#include <pcl/io/io.h>
#include <pcl/io/pcd_io.h>

void main(int argc, char** argv)
{

	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile("my_point_cloud.pcd", *cloud);

	pcl::visualization::CloudViewer viewer("Simple Cloud Viewer");
	viewer.showCloud(cloud);
	while (!viewer.wasStopped())
	{
	}

}
```

## Context

My end goal is to visualize PCAP files and implement ground removal algorithms along with object recognition using clustering algorithms. But I am not able to visualize a simple PCD file due to unresolved external symbols, namely vtkObjectFacotryRegistryCleanUp and vtkDebugleakmanager:

`LNK2019	unresolved external symbol "public: __thiscall vtkDebugLeaksManager::~vtkDebugLeaksManager(void)" (??1vtkDebugLeaksManager@@QAE@XZ) referenced in function "void __cdecl `dynamic atexit destructor for 'vtkDebugLeaksManagerInstance''(void)" (??__FvtkDebugLeaksManagerInstance@@YAXXZ)´	

I have make sure the lib path to vtk in the project is correct and tried adding them manually using linker dependencies. But the error persists.

**Comment by UnaNancyOwen** [comment]
It works normally in my environment. This is not bug.
Probably, You are not using CMake to generate your own project.
We don't recommend generating projects without CMake. And, We can't support it.
Please read this [tutorial](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php#using-cmake-gui-e-g-windows).
