### ISSUE TITLE
pcl 1.8.1 bug in pcl_visualizer.hpp

### ISSUE THREAD

**Issue by nenadpol** [PointCloudLibrary/pcl#1975]
My system is windows7 x64  , pcl 1.8.1 x64 and VS 2015, vtk 1.64 

Looking at pcl_visualizer.hpp line 293 to line 296 (void  convertPointCloudToVTKPolyData) 

  vtkSmartPointer<vtkPoints> points; 
  geometry_handler.getGeometry (points); 
  polydata->SetPoints (points); 

It is obvious that pointer "points" is newer initialized. 
This has not coused problems in previous vtk versions but it does in vtk 1.64 

Taking some examples from pcl documentation and compiling EXE application works fine but 
when using pcl_visualizer in dll  than error is produced "Trying to read-write protected memory" 
when executing line " polydata->SetPoints (points);" 

This is not surprise taking into account that points = null 

Adding a new line fix the problem 

  vtkSmartPointer<vtkPoints> points; 
  points = vtkSmartPointer<vtkPoints>::New();   //  NEW LINE 
  geometry_handler.getGeometry (points); 
  polydata->SetPoints (points); 

thanks 
Nenad

**Comment by UnaNancyOwen** [comment]
Thank you for your report.
Could you provide minimal source code (and input data) to reproduce this problem?

**Comment by nenadpol** [comment]
Test code:  ()

#include <pcl/io/pcd_io.h>
#include <pcl/visualization/pcl_visualizer.h>

pcl::PointCloud<pcl::PointXYZ>::Ptr basic_cloud_ptr (new pcl::PointCloud<pcl::PointXYZ>);

  for (float z(-1.0); z <= 1.0; z += 0.05)
  {
    for (float angle(0.0); angle <= 360.0; angle += 5.0)
    {
      pcl::PointXYZ basic_point;
      basic_point.x = 0.5 * cosf (pcl::deg2rad(angle));
      basic_point.y = sinf (pcl::deg2rad(angle));
      basic_point.z = z;
      basic_cloud_ptr->points.push_back(basic_point);
    }
  }
  basic_cloud_ptr->width = (int) basic_cloud_ptr->points.size ();
  basic_cloud_ptr->height = 1;

 boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));
  viewer->addPointCloud<pcl::PointXYZ> (basic_cloud_ptr , "sample cloud");

**Comment by taketwo** [comment]
`points` are initialized inside the [`getGeometry()`](https://github.com/PointCloudLibrary/pcl/blob/8695e834e42d912a9a4f8ca2a17cc3a72a2a9d10/visualization/include/pcl/visualization/impl/point_cloud_geometry_handlers.hpp#L68-L69) function.

**Comment by SergioRAgostinho** [comment]
Please reopen if needed.

**Comment by tomorrowlyx** [comment]
@nenadpol Hi，i encountered the same issue here. i am using VS2015, PCL1.8.1 and Win10-64bit. When compiling as EXE, it works fine. But when I use it as a dll, "System.AccessViolationException" always occured. I located that the problem is coming from the function addPointCloud (viewer->addPointCloud<pcl::PointXYZRGB>(cloud, rgb, "sample cloud")).  Would you please provide me some hints on how to solve it ?   Thank you so much

**Comment by Tsung-Yu-Hsieh** [comment]
> @nenadpol Hi，i encountered the same issue here. i am using VS2015, PCL1.8.1 and Win10-64bit. When compiling as EXE, it works fine. But when I use it as a dll, "System.AccessViolationException" always occured. I located that the problem is coming from the function addPointCloud (viewer->addPointCloudpcl::PointXYZRGB(cloud, rgb, "sample cloud")). Would you please provide me some hints on how to solve it ? Thank you so much

Could you please teach me how to solve this problem? Thanks!

**Comment by tomorrowlyx** [comment]
> > @nenadpol Hi，i encountered the same issue here. i am using VS2015, PCL1.8.1 and Win10-64bit. When compiling as EXE, it works fine. But when I use it as a dll, "System.AccessViolationException" always occured. I located that the problem is coming from the function addPointCloud (viewer->addPointCloudpcl::PointXYZRGB(cloud, rgb, "sample cloud")). Would you please provide me some hints on how to solve it ? Thank you so much
> 
> Could you please teach me how to solve this problem? Thanks!



> > @nenadpol Hi，i encountered the same issue here. i am using VS2015, PCL1.8.1 and Win10-64bit. When compiling as EXE, it works fine. But when I use it as a dll, "System.AccessViolationException" always occured. I located that the problem is coming from the function addPointCloud (viewer->addPointCloudpcl::PointXYZRGB(cloud, rgb, "sample cloud")). Would you please provide me some hints on how to solve it ? Thank you so much
> 
> Could you please teach me how to solve this problem? Thanks!

Sure.  Please don't use this function in this way. just use it as : viewer->addPointCloudpcl::PointXYZRGB(cloud, "sample cloud").  Remove rgb.
