### ISSUE TITLE
Error occurs when executing pkg-config

### ISSUE THREAD

**Issue by Sirokujira** [PointCloudLibrary/pcl#1978]
## Your Environment
•Operating System and version: Ubuntu 14.04/Mac OS 10.12
•PCL Version: 1.8.1

## Current Behavior
Using pkg-config
An error occurs when reading pcl_features_1.8.pc file.

Remove 2d library (contains no symbols)  #1679

## Possible Solution
Please delete "required: pcl_2d-1.8" of pcl_feature-1.8.

pcl/features/CMakeLists.txt 
set(SUBSYS_DEPS common search kdtree octree filters 2d)
↓
set(SUBSYS_DEPS common search kdtree octree filters)

**Comment by taketwo** [comment]
We can not remove `2d` from the list because it is a dependency. A proper fix will be to return pkg file generation for `2d` module. (See inline comment [here](https://github.com/PointCloudLibrary/pcl/pull/1679/files), patches welcome.)

**Comment by taketwo** [comment]
Please let us know if this fixes the problem for you.

**Comment by Sirokujira** [comment]
I checked the modified code in the Ubuntu / MacOSX environment.

After building, in /usr/local/lib/pkgconfig folder,
I confirmed that there is pcl_2d-1.8.pc file.
(After confirming that the file does not exist, I ran the build.)

When pkg-config was executed in this state, no error occurred.

Thank you for your quick response.

**Comment by jmachowinski** [comment]
This error is still present in pcl 1.8.1. Can you apply #1979 on 1.8.1 and rerelase it as 1.8.1.1 ?
