### ISSUE TITLE
bug in PCL1.8.1msvc2017

### ISSUE THREAD

**Issue by Rancho86** [PointCloudLibrary/pcl#1984]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version:WIN10

* Compiler:VC2017
* PCL Version:1.8.1

## Code to Reproduce

![bug1](https://user-images.githubusercontent.com/31204036/29993187-341eeb70-8fe2-11e7-8157-243c9e9e4738.png)

## Context

![bug](https://user-images.githubusercontent.com/31204036/29993184-05cac230-8fe2-11e7-9a05-5ec0574c69fb.png)

**Comment by Rancho86** [comment]
Does VTK8.0 match PCL1.8.1? Why they are in an allinone setup file?

**Comment by Rancho86** [comment]
I just run the sample in PCL1.8.1. It can work in PCL1.8.0 with VS2015 on my colleague's computer. But I  have to use VS2017 for Hololens.So I need help >.<

**Comment by Rancho86** [comment]
@taketwo Could you give me some help?

**Comment by taketwo** [comment]
This is a issue tracker, please use our mailing list for questions and support: www.pcl-users.org.
Besides, I'm not a Windows user and can not help there.
