### ISSUE TITLE
How to get all the points in the same voxelgrid

### ISSUE THREAD

**Issue by ttomchy** [PointCloudLibrary/pcl#1985]
Hello ,recently I have learnt to use the pcl::VoxelGrid algorithm to downsample the points. I wonder to know if we can get all the points in the same voxelgrid. Ｉ　want to know all the coordinates of the point cloud that falls within the same 3D grid.

**Comment by taketwo** [comment]
[OctreePointCloudPointVector](http://docs.pointclouds.org/trunk/classpcl_1_1octree_1_1_octree_point_cloud_point_vector.html#details) may be what you are looking for.

This is a issue tracker, please use our mailing list for support and questions: www.pcl-users.org.
