### ISSUE TITLE
Add the ability to set custom render window and renderer for pcl_visualizer

### ISSUE THREAD

**Issue by denix56** [PointCloudLibrary/pcl#1989]
Hi all.
I started working on it due to that pcl visualizer does not work correctly with new QVTKOpenGLWidget. It requires vtkGenericOpenGLRenderWindow.
I propose to add the constructor, that takes the smart pointers to render window and renderer and assigns them to internal pointers
`PCLVisualizer(int &argc, char **argv, const std::string &name,
                      vtkSmartPointer<vtkRenderWindow>& win, vtkSmartPointer<vtkRenderer>& renderer,
                      PCLVisualizerInteractorStyle* style = PCLVisualizerInteractorStyle::New(),
                      const bool create_interactor = true);`

But there is small problem - in such signature we miss the default parameter for name.   But i think the it will be not a problem for users to set it.

**Comment by taketwo** [comment]
Hi, before we can jump into the discussion, I would like to have a better understanding of the problem we are addressing:
 * by "new" QVTKOpenGLWidget which one do you mean (VTK/Qt version)?
 * what exactly means "does not work"?
 * short example project that demonstrates the problem (you can upload it as a Gist)
 * any relevant information including tutorial links that are obsolete (provide code that does not work with new widget)

**Comment by denix56** [comment]
http://pointclouds.org/documentation/tutorials/qt_visualizer.php

**Comment by taketwo** [comment]
What are the reasons to not use the "classical" `QVTKWidget`?

**Comment by denix56** [comment]
QVTKOpenGLWidget is intended to be a replacement for QVTKWidget when using Qt 5, also it has features, that might be used in my project.

Also, I have found better solution - make win_ and some other fields protected instead of private and implement new class based on PclVisualizer.

**Comment by denix56** [comment]
Also, it will give us the ability to use the visualizer in VR with vtkExternalOpenGLRenderWindow

**Comment by taketwo** [comment]
Quick googling about `QVTKOpenGLWidget` vs. `QVTKWidget` does not yield many results. Basically, the only information I found is this passage from the [release notes](https://blog.kitware.com/vtk-8-0-0/) of VTK 8:

> The new `QVTKOpenGLWidget` leverages Qt’s new OpenGL context creation mechanism and is meant  to be a replacement for `QVTKWidget` for Qt5. Note that as of release time there are unresolved  transparency related bugs that show up with this new Qt5 enabling class on some platforms.

Additionally, I see this [list of changes](https://www.slicer.org/wiki/Documentation/Labs/Qt5-and-VTK8), with multiple bugfixes for `QVTKOpenGLWidget`, from which I conclude that it is quite unstable.

With this in mind, keeping `PCLVisualizer` compatible with `QVTKWidget` is the priority. If there is an easy and non-intrusive way to let users couple it with the new `QVTKOpenGLWidget`, then let's do this.

**Comment by denix56** [comment]
Ok, I will start working on it.
