### ISSUE TITLE
PCL 1.8.1 Kmeans implementation confusion

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#1990]
## Your Environment

* Operating System and version: Widows 7
* Compiler: VS2015 
* PCL Version: 1.8.1

## Problem Details:
In the users mailing list, I saw similar problems while initializing an instance of Kmeans. static_cast<int> is not being accepted in the argument list. Also the lack of proper tutorial of how to implement Kmeans has been a huge problem in understanding it. 

## Possible Solution
Maybe a detailed tutorial on implementing kmeans for clustering and getting all possible outputs would be a huge help.

## Code to Reproduce

```cpp
int main(int argc, char** argv)
{

	std::string filePath = "Scene02 - Cloud.pcd";
	pcl::PointCloud<pcl::PointXYZ>::Ptr tempCloud(new pcl::PointCloud<pcl::PointXYZ>);
	if (pcl::io::loadPCDFile(filePath, *tempCloud) == -1) //* load the file
	{
		printf("failed file load!\n");
	}
	else
	{
		pcl::Kmeans real ((tempCloud->points.size()), 3); 
		real.setClusterSize(10); //it is important that you set this term appropriately for your application
		for (size_t i = 0; i < tempCloud->points.size(); i++)
		{
			std::vector<float> data(3);
			data[0] = tempCloud->points[i].x;
			data[1] = tempCloud->points[i].y;
			data[2] = tempCloud->points[i].z;
			real.addDataPoint(data);
		}

		real.kMeans();
		// get the cluster centroids 
		pcl::Kmeans::Centroids centroids = real.get_centroids();
		std::cout << "points in total Cloud : " << tempCloud->points.size() << std::endl;
		std::cout << "centroid count: " << centroids.size() << std::endl;
		for (int i = 0; i<centroids.size(); i++)
		{
			std::cout << i << "_cent output: x: " << centroids[i][0] << " ,";
			std::cout << "y: " << centroids[i][1] << " ,";
			std::cout << "z: " << centroids[i][2] << std::endl;
		}
	}

	std::cin.get();
	std::cin.get();
}
```

## Context
I am trying to implement clustering algorithm on a PCD file, and then later on a PCAP file for object recognition purpose. I need to visualize the various clusters but I am not sure how to access each cluster separately.

**Comment by anshulvj** [comment]
I am having a different problem in compiling the same code: I'm getting linker errors where it can't find kmeans. I included the kmeans.h files and the compiler error went away. I also tried adding the "ml" component in my CMakeLists.txt but cmake says it can't find "PCL_ML". Is there any other name which I should add under the cmakelists to make this work?
