### ISSUE TITLE
Can not run the ply2pcd.exe file

### ISSUE THREAD

**Issue by hjz00** [PointCloudLibrary/pcl#1994]
Hello,i need your help.
I have been confused by this question for a long time.

Your Environment

Operating System and version: win8.1
PCL Version: 1.7.1

Expected Behavior

Complete the conversion from .ply format to .pcd format.

Current Behavior

![image](https://user-images.githubusercontent.com/22675140/30421293-dfbe5a3e-996e-11e7-8551-18320235cc3b.png)
Unable to connect program to dynamic link library ply2pcd.exe

Sum up:I can not complete the conversion from .ply format to .pcd format.I used the codes from PCL1.7.1 and by CMake to create new Debug folder.

**Comment by hjz00** [comment]
Thank you so much to give me some tips.

**Comment by SergioRAgostinho** [comment]
Try it first with latest version 1.8.1 and use `pcl_converter`.

**Comment by hjz00** [comment]
@SergioRAgostinho Thanks so much.I followed your advice but the same question appeared again.I don not know why.But the vision PCL1.6.0 can work well in my computer.

**Comment by Wyllich** [comment]
Something which may work if you try that:

`#include <pcl/point_cloud.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <iostream>

int main (int argc, char** argv){
  pcl::PointCloud<pcl::PointXYZ> cloud;
  
  if(pcl::io::loadPLYFile<pcl::PointXYZ>(argv[1], cloud)==-1)
  {
        PCL_ERROR ("Couldn't read file \n");
        return (-1);
  }
  
  pcl::io::savePCDFileASCII ("output.pcd", cloud);
  
  return(0);`

And don't forget to change the cloud type to match your PLY file.

**Comment by hjz00** [comment]
@Wyllich I have tried your codes and i could not accomplish ply2pcd. There were some new problems.I wonder whether you can help me to do it and my ply file is:

ply
format ascii 1.0
comment created by platoply
element vertex 8
property float32 x
property float32 y
property float32 z
element face 6
property list uint8 int32 vertex_indices
end_header
-1 -1 -1 
1 -1 -1 
1 1 -1 
-1 1 -1 
-1 -1 1 
1 -1 1 
1 1 1 
-1 1 1 
4 0 1 2 3 
4 5 4 7 6 
4 6 2 1 5 
4 3 7 4 0 
4 7 3 2 6 
4 5 1 0 4 

Thx a lot and best wishes.

**Comment by SergioRAgostinho** [comment]
I just tried to convert the ply you supplied with pcl converter and had no issue with it
```
$ bin/pcl_converter -f ascii /tmp/test.ply /tmp/test.pcd
Loaded a mesh with 8 points (total size is 128) and the following channels:
x y z
PCD file format does not support meshes! Only points be saved.
Saving file /tmp/test.pcd as ASCII.
```
Here are the contents of the PCD file created
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH 8
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 8
DATA ascii
-1 -1 -1
1 -1 -1
1 1 -1
-1 1 -1
-1 -1 1
1 -1 1
1 1 1
-1 1 1
```

**Comment by hjz00** [comment]
Thanks a lot.
I got a lot from your help.
Best wishes!




------------------ 原始邮件 ------------------
发件人: "Sérgio Agostinho";<notifications@github.com>;
发送时间: 2017年11月23日(星期四) 上午10:01
收件人: "PointCloudLibrary/pcl"<pcl@noreply.github.com>;
抄送: "Orange"<2604819720@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [PointCloudLibrary/pcl] Can not run the ply2pcd.exe file (#1994)




I just tried to convert the ply you supplied with pcl converter and had no issue with it
 $ bin/pcl_converter -f ascii /tmp/test.ply /tmp/test.pcd Loaded a mesh with 8 points (total size is 128) and the following channels: x y z PCD file format does not support meshes! Only points be saved. Saving file /tmp/test.pcd as ASCII.  
Here are the contents of the PCD file created
 # .PCD v0.7 - Point Cloud Data file format VERSION 0.7 FIELDS x y z SIZE 4 4 4 TYPE F F F COUNT 1 1 1 WIDTH 8 HEIGHT 1 VIEWPOINT 0 0 0 1 0 0 0 POINTS 8 DATA ascii -1 -1 -1 1 -1 -1 1 1 -1 -1 1 -1 -1 -1 1 1 -1 1 1 1 1 -1 1 1
