### ISSUE TITLE
pclvisualizer's interactor_ is nullptr

### ISSUE THREAD

**Issue by renc** [PointCloudLibrary/pcl#1997]
Hello, 

pclvisualizer's interactor_ is nullptr at this usage:
```cpp
        //m_pViewWidget is a qvtkWidget instance
	m_pViewer.reset(new pcl::visualization::PCLVisualizer("viewer", false));
	m_pViewWidget->SetRenderWindow(m_pViewer->getRenderWindow()); 
	// to use interactor from qvtkWidget
	m_pViewer->setupInteractor(m_pViewWidget->GetInteractor(), m_pViewWidget->GetRenderWindow());
	m_pViewWidget->update();
```

after this code, the interactor_ is still nullptr, so crash for example m_pViewer->spinOnce().  

To fix that, i think maybe at 
```cpp
PCLVisualizer::setupInteractor(....) {
    ... // same as the current version. 
    interactor_ = iren; // add this new line. 
} 
```
any idea?

**Comment by renc** [comment]
btw, if this fix make sense, i could help to add a patch. thx.

**Comment by taketwo** [comment]
I'm not entirely sure, but I think you should not call functions like `spin()` or `spinOnce()` when you are using external interactor. Your `m_pViewWidget` will take care of refreshing and redrawing the visualization window.

**Comment by renc** [comment]
thx taketwo, right that the m_pViewWidget->update() will refresh the window. Leaving interactor_ null seems a bit dangerous.

**Comment by taketwo** [comment]
It's dangerous, true. All accesses to `interactor_` need to be guarded with null checks, which is not the case currently. However, setting `interactor_` to the external interactor may be not a good idea either, because then we will start calling functions like `DestroyTimer`, `Start`, `Render`, etc on this external instance, which we are not supposed to.

**Comment by denix56** [comment]
Some related information with it - when we use QVTKOpenGLWidget it often does not update the displayed object with update() function, you should call Render() method of the current render window. But it seems to be not PCL bug, but VTK.
Maybe it will be useful for somebody.
