### ISSUE TITLE
PCL 1.8.1 all-in-one does not support Qt?

### ISSUE THREAD

**Issue by JloveU** [PointCloudLibrary/pcl#1998]
PCL 1.8.1 all-in-one does not support Qt?

**Comment by UnaNancyOwen** [comment]
Yes, If you want to use PCL with Qt on Windows, You need build PCL with enable Qt option (WITH_QT) from source code yourself.
This is a issue tracker, please use our mailing list for questions and support: www.pcl-users.org.

**Comment by JloveU** [comment]
OK, thanks!
