### ISSUE TITLE
VoxelGrid Filer implementation 

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#1999]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Windows 7 64-bit
* Compiler:Visual Studio 2015
* PCL Version:1.8.1

## Expected Behavior
Visualizing a down-sampled pcap file

## Current Behavior
constant error saying Leaf Size is too small. Integer indices would overflow

## Possible Solution
Changing LeafSize

## Code to Reproduce
                        `pcl::VoxelGrid<pcl::PointXYZ> vs;
			vs.setInputCloud(buffer_pcl);
			vs.setLeafSize(0.01f,0.01f,0.01f);
			vs.filter(*cloud_filtered);´

## Context
I am trying to visualize an HDL-32 PCAP file and implementing voxel grid filter on it to down-sample each data packet. But I am getting a constant error message for each data packet saying the leaf size is too small for the input data set. I have tried values from 0.01f to 4.50f but I am getting the same response. What is the correct way to approach this?

**Comment by mjshiggins** [comment]
As it stands right now, it may be best for you to break the PCD down into smaller files (or use the approximate voxel filter class). There has been some discussion in the past about changing from integer indices, but there are a fair amount of drawbacks to doing this.

**Comment by kavinat** [comment]
@mjshiggins  thanks for the advice. Problem is that if I do that it will make my algorithm considerably slow. And since I am using a PCAP file, it will take me forever to break it down and then process it. I will, however, give the approximate voxel filter class a shot and hope that works out. If there are any other options I can use to downsample PCAP data please let me know.

**Comment by kavinat** [comment]
@mjshiggins I wonder how come Voxelgrid worked perfectly well with a PCD file but for a PCAP file the inter indices are a problem. Is there any particular reason for that?

**Comment by SergioRAgostinho** [comment]
Are the files exactly the same? Same amount of points and the individual coordinates of each point?

**Comment by kavinat** [comment]
@SergioRAgostinho  yes they are exactly the same. I have not been able to implement all options as you suggested on my previous question. Once I do I will get back to you.

**Comment by SergioRAgostinho** [comment]
Here's the reasoning:
- I imagine you're loading both point cloud files using the corresponding io functions for it.
- This means that in theory you'll end up having your data stored in  point clouds of XYZ points.
- These are both same type objects, but you're getting different results, which means the data they're holding is different, otherwise the result would be the same.
- This likely means that the PCAP loader is struggling with something but the PCD loader is not.
- Since your cloud is actually big, I wouldn't be surprised if it was some overflow happening somewhere, especially because the use of `size_t` types is not consistent around the library code.

**Comment by SergioRAgostinho** [comment]
That being said, at some point it would be good to upload those PCAP and PCD files somewhere to be able to verify your case.

**Comment by kavinat** [comment]
UPDATE: Downsampling had no effect on the accuracy of the RANSAC Filter.

**Comment by SergioRAgostinho** [comment]
This is issue is about the VoxelGrid filter. Keep the respective topics in the respective issues unless they're causal.

**Comment by kavinat** [comment]
Approximate VoxelGrid filter works well with PCAP files no issue there.

**Comment by SergioRAgostinho** [comment]
Meaning you can no longer reproduce you reported in the first place?

**Comment by taketwo** [comment]
Closing due to lack of feedback.
