### ISSUE TITLE
TSDF About the kinfu in PCL

### ISSUE THREAD

**Issue by amoonsky** [PointCloudLibrary/pcl#2006]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Win10
* Compiler: VS Community2015
* PCL Version:1.8.0

## Expected Behavior

Two Depth images should be integrated correctly.
## Current Behavior

The two faces of the object in the integrated image are seperated too far or too near.
## Context

In kinfu_app, PCL used Camera Matrix as the parameter of the TSDF function.
```cpp
pcl::device::integrateTsdfVolume (const PtrStepSz<ushort>& depth, const Intr& intr,
                                  const float3& volume_size, const Mat33& Rcurr_inv, const float3& tcurr, 
                                  float tranc_dist,
                                  PtrStep<short2> volume, DeviceArray2D<float>& depthScaled)
```
I mean  Rcurr_inv & tcurr. Here The two parameters are calculated by ICP. But now I use two depth cameras as the input sources. So I use manual way to justify the translation matrix between the two cameras.  Here I have:
```cpp
Eigen::Affine3f
pcl::gpu::KinfuTracker::getCameraPoseBack(Eigen::Matrix<float, 3, 3, Eigen::RowMajor>  &rmat, Eigen::Vector3f &tvec) const
{
	Eigen::Affine3f aff;
	aff.linear() = (rmat * rmat2_);
	aff.translation() = rmat * tvec2_ + tvec;
	return (aff);
}
```
The  rmat2_ &  tvec2_ is the rotation matrix between the two camera. If I use the rotation matrixs to rotation/translate the XYZ datas of the two cameras in different application, the result is perfect. But If I use the matrix as the parameter of the pcl::device::integrateTsdfVolume. The two faces of the observed object are seperated too far or too near(By the way, the two cameras are posed face to face.)

I can't find out the reason of the problem. Maybe caused by tranc_dist?

**Comment by taketwo** [comment]
Hi, the kinfu implementation in PCL is not maintained. There are a number of open-source implementations of this or similar algorithms online, I'd recommend to use them. That being said, we do accept PRs with bugfixes for kinfu.

**Comment by kunaltyagi** [comment]
Maybe of interest to @haritha-j
