### ISSUE TITLE
METSlib and its license

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#2010]
My colleague has discovered that [METSlib](https://projects.coin-or.org/metslib) is officially distributed under GPLv3 license. However, we have this library [checked in](https://github.com/PointCloudLibrary/pcl/blob/master/recognition/include/pcl/recognition/3rdparty/metslib/mets.hh) PCL repository under a __different__ license, namely BSD.

I traced the repository history down to the commit e4d6501af04 where @baol adds the files and says:

> Including the headers from METSlib (https://projects.coin-or.org/metslib) version 0.5.3 modified to use the BSD license.

Based on the name and e-mail of this person, I assume he is the copyright holder and had rights to re-license the code. So we are safe here.

However, some time ago we have merged a pull request #299 that allows to build PCL against a system-wide installed METSlib (which would be GPLv3 library). I wonder, what are the legal implications?

Also, we had several discussions where @jspricke suggested that we should not maintain our own copy (https://github.com/PointCloudLibrary/pcl/pull/299#issuecomment-26316624, https://github.com/PointCloudLibrary/pcl/pull/1138#issuecomment-76389246) of the library and remove it. If we indeed do so, then the BSD licensing of the library will perish?

@baol if you are here, could you please comment? Would it be possible to relicense METSlib to BSD for the whole world, not just PCL? (If I understand the licensing logic, then in theory right now someone who wants to use METSlib in his closed source project can just take PCL, cut it down, removing everything but the 3rdparty sources of METSlib, and use it. So having METSlib with GPLv3 does not make sense as long as there is BSD licensed METSlib inside PCL?)

**Comment by baol** [comment]
Hi, the official METSlib library is hosted on coin-or (https://projects.coin-or.org/metslib) and doubly licensed with GPLv3 or at your option the EPL-1.0 (ex CPL) that is a commercially friendly license. This double licensing is verified by coin-or, that requires contributors to sign a contribution document. 

What is the problem with EPL-1.0?

**Comment by taketwo** [comment]
Hi, thanks for the clarification. We did not pay enough attention to that passage about CPL. So the conclusion is that it makes no problem to link PCL against installed METSlib. Also, we can put the removal of our copy of METSlib on the roadmap.

**Comment by hrieke** [comment]
While this is an old issue, it does come up from time to time in code audits.
Would it be possible to add this thread / relicensing to a read me and place it with the code?
Thank you

**Comment by kunaltyagi** [comment]
Please create an issue or PR (with appropriate details) to discuss this anew
