### ISSUE TITLE
max-unsigned-zero compile warning in octree_base.hpp

### ISSUE THREAD

**Issue by caedmon** [PointCloudLibrary/pcl#2011]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: osx 10.12
* Compiler: llvm/clang
* PCL Version: 1.8

## Expected Behavior
should compile without warnings

## Current Behavior
generates this warning:
In file included from /usr/local/include/pcl-1.8/pcl/octree/octree_impl.h:44:
/usr/local/include/pcl-1.8/pcl/octree/impl/octree_base.hpp:84:22: warning: taking the max of a value and unsigned zero is always equal to the other
      value [-Wmax-unsigned-zero]
  ...std::max ( (std::min (static_cast<unsigned int> (OctreeKey::maxDepth), static_cast<unsigned int> (std::ceil (Log2 (max_voxel_index_arg))))), 0u);

## Possible Solution
eliminate the call to std::max()

**Comment by taketwo** [comment]
:+1:

Please send a patch.
