### ISSUE TITLE
Trouble locating PCL_ML (for running pcl::kmeans)

### ISSUE THREAD

**Issue by anshulvj** [PointCloudLibrary/pcl#2015]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Ubuntu 16.04 LTS 64 bit
* Compiler: gcc
* PCL Version: 1.7.2 or 1.8.1 (see below)

I am trying to run a code on Ubuntu which uses pcl::kmeans.
I have run a bunch of other pcl modules (ransac segmentation, filtering etc.) on the same piece of code, and the code compiles and runs after I modify CMakeLists.txt and add the relevant components and $PCL_X_LIBRARIES. E.g my CMakeLists.txt could contain:

`find_package(PCL 1.7 REQUIRED COMPONENTS common io visualization filters segmentation surface)`

`target_link_libraries(region_growing ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES} ${PCL_VISUALIZATION_LIBRARIES} ${PCL_FILTERS_LIBRARIES} ${PCL_SEGMENTATION_LIBRARIES} ${PCL_SURFACE_LIBRARIES}  rt m pthread stdc++)`

All these libraries get included and their respective functions work. 
But as soon as I add `ml` (which contains kmeans) in `find_package` and `$PCL_ML_LIBRARIES` in `target_link_libraries` it says it can't find it.

`looking for PCL_SURFACE
-- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
-- looking for PCL_ML
-- Could NOT find PCL_ML (missing:  PCL_ML_LIBRARY PCL_ML_INCLUDE_DIR) 
`

As expected, when I try to make the code it throws linker errors:
`[100%] Linking CXX executable region_growing
CMakeFiles/region_growing.dir/region_growing.cpp.o: In function main':
region_growing.cpp:(.text+0xdda): undefined reference to pcl::Kmeans::Kmeans(unsigned int, unsigned int)'
region_growing.cpp:(.text+0x1397): undefined reference to pcl::Kmeans::kMeans()'
region_growing.cpp:(.text+0x1926): undefined reference to pcl::Kmeans::~Kmeans()'
region_growing.cpp:(.text+0x1ee8): undefined reference to pcl::Kmeans::~Kmeans()'
collect2: error: ld returned 1 exit status
CMakeFiles/region_growing.dir/build.make:1148: recipe for target 'region_growing' failed
make[2]: *** [region_growing] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/region_growing.dir/all' failed
make[1]: *** [CMakeFiles/region_growing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

I tried to search online but could not find any solution. One forum said that the ml module has to be installed separately. Any suggestions how to do this without having to recompile the whole pcl? If the whole thing needs to be recompiled, how do I make sure it installs correctly?

**Please note** that after I compiled and installed release version of PCL on my Ubuntu I was getting some library errors (this was many weeks ago so I don't remember exactly what they were), but I had to do `sudo apt-get install libpcl-all` and that solved it and the thing started working. The thing to note is that while I compiled and installed pcl-1.8, when I do `dpkg -l "pcl"` is gives me:

![screenshot from 2017-09-29 10-16-34](https://user-images.githubusercontent.com/1171507/31025350-99d36f54-a4ff-11e7-8fa9-0c9663978ba5.png)

I'm not sure if this has anything to do with the ml error I'm getting, but just in case...

Thanks in advance.
Anshul

**Comment by SergioRAgostinho** [comment]
I had a look at the source tree and I don't think that the kmeans implementation is finished. Your problem in particular is that the implementation file `kmeans.hpp` is actually commented on the ml module CMakeLists.txt, and is not being installed because of that. Even if it was, I had a look at it and it doesn't look finished so you're a little bit on your own here. :/

**Comment by taketwo** [comment]
Should we abolish it? It's existence only brings confusion.

**Comment by anshulvj** [comment]
@SergioRAgostinho thanks for your reply it clears my query i suppose. I'll figure out a way around this :+1:

**Comment by anshulvj** [comment]
@taketwo well...if someone does decide to implement it later maybe it will be useful, but it's just my opinion; it's really upto the admins
