### ISSUE TITLE
Implementing PCL Filters without pointers.

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#2019]
## Your Environment

* Operating System and version: Windows 7
* Compiler: Visual Studio Community 2015
* PCL Version: 1.8.1 

## Expected Behavior
Visualizing PCAP Filter with only ground. 

## Current Behavior
Not able to get any visualizing window.

## Possible Solution
Localized pointer for the captured data for the filters. 

## Code to Reproduce
        
		boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ>> FLasers ( new 
                pcl::PointCloud<pcl::PointXYZ>);
		capture >> lasers;
		if (lasers.empty()) 
		{
			continue;
		}
		
		*FLasers = lasers;
		
		//  filtering object
		pcl::ProgressiveMorphologicalFilter<pcl::PointXYZ> pmf;
		pmf.setInputCloud(FLasers);
		pmf.setMaxWindowSize(20);
		pmf.setSlope(0.1f);
		pmf.setInitialDistance(0.5f);
		pmf.setMaxDistance(3.0f);
		pmf.extract(ground->indices);

		// Extraction of filtering object
		pcl::ExtractIndices<pcl::PointXYZ> extract;
		extract.setInputCloud(FLasers);
		extract.setIndices(ground);
		extract.filter(*cloud_filtered);

	
		for (int j = 0; j <cloud_filtered->points.size(); j++)
		{
			
				buffer.push_back(cv::Vec3f(cloud_filtered->points[j].x,cloud_filtered->points[j].y,cloud_filtered->points[j].z));
			
		}
		FLasers->clear();
		lasers.clear();
		cloud_filtered->clear();´
		

## Context
I am trying to apply a simple PCL Filter on captured PCAP Data. I am capturing it as  a point cloud data. But when I try to take it in as a Point Cloud pointer then I am not getting an visualizing window. Is there anyway to apply PCL Filters without using the point cloud pointer? ( I tried the obvious & function and it backfired gloriously)

**Comment by SergioRAgostinho** [comment]
This is a bug tracker and what you're describing doesn't seem like a bug. Please use our mailing list www.pcl-users.org for questions of this type.
