### ISSUE TITLE
CUDA Sample Consensus build fails with error regarding thrust::device_reference members

### ISSUE THREAD

**Issue by anuppari** [PointCloudLibrary/pcl#2029]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Windows 10 64bit
* Compiler: Visual Studio 2013 (vc12)
* PCL Version: https://github.com/PointCloudLibrary/pcl/commit/f4d62036bf7b3484c873cdee7d759f5dfcdad9bf
* CUDA v9.0

## Expected Behavior

Building CUDA sample consensus should complete.

## Current Behavior

Build error: `class "thrust::device_reference<const pcl::cuda::PointXYZRGB>" has no member x, y, z` in lines 196, 199-201 of pcl_cuda_sample_consensus.cu. [These](https://stackoverflow.com/questions/8638839/thrust-vector-of-type-uint2-has-no-member-x-compiler-error) [two](https://stackoverflow.com/questions/6624049/passing-thrustdevice-vector-to-a-function-by-reference) stackoverflow posts (dated 2011) suggest that referencing PointXYZRGB members in a device_reference should never have been possible. pcl_cuda_sample_consensus.cu hasn't had any changes for 6 years, and [thrust ](http://thrust.github.io/) hasn't had any changes since early 2015, so I don't think this is related to the new CUDA version.

## Possible Solution

I don't know.

**Comment by SergioRAgostinho** [comment]
Just possibly related, I just set up quickly CUDA 9 to give it a try and I can't compile anything related to CUDA (even with some required known changes in the cmake files). So at this point, this is more like PCL doesn't support CUDA 9.

**Comment by anuppari** [comment]
I'm using the latest version of PCL (either https://github.com/PointCloudLibrary/pcl/commit/3d8ddb0f358ce2b90ad36367b3504758a044e6ef or https://github.com/PointCloudLibrary/pcl/commit/cb27ee2ab80c05ea66e0f11dae67cb01a6b5beef) and I'm able to build everything with CUDA except the cuda_sample_consensus module. I did have to fix an issue in flann to work with cuda 9 (add `#include <thrust/gather.h>` to flann\src\cpp\flann\algorithms\kdtree_cuda_3d_index.cu).

cuda 9 did split the nppi module into separate modules, which broke e.g., opencv (you can see details [here](https://devtalk.nvidia.com/default/topic/1024631/cuda-9-opencv-gt-building-errors/)). I'm not proficient enough in cmake to make the equivalent fixes in PCL's pcl_find_cuda.cmake, and I'm not even sure that's the problem since I can build most of the PCL CUDA modules.

**Comment by tudodetalhado** [comment]
Thank you! This solve my compilation problem: #include <thrust/gather.h>

**Comment by taketwo** [comment]
Closing as this is not a PCL bug

**Comment by anuppari** [comment]
I think this is a PCL bug, the error is in PCL source file `pcl_cuda_sample_consensus.cu`. The flann related error was another issue that was resolved.

**Comment by taketwo** [comment]
Was this resolved at FLANN side? Can you add a link for future reference?

**Comment by anuppari** [comment]
I don't know if the FLANN repo includes the fix, I just meant that I have personally resolved the problem by adding the include.

However, that was a separate problem that I only mentioned to aid others that are trying to compile PCL with cuda 9. The actual issue is in PCL's cuda sample consensus and still exists.

**Comment by Robzz** [comment]
I wish I had run into this issue prior to opening #2181 but oh well... Can anyone encountering this issue give this PR a try ?

**Comment by moncio** [comment]
Hi to everybody, I'm trying to build the library in Linux environment using next dependencies:

- CUDA 9.0
- CUDNN 7.2
- EIGEN 3.3.5
- FLANN 1.9.1
- BOOST 1.68
- VTK 8.1.1

I have the same error as you said in related post. So, anyone was able to build the library in Linux?

Thanks!

**Comment by larshg** [comment]
I cannot find any file named pcl_cuda_sample_consensus.cu.
But using master the cuda_sample_consensus project compiles fine with CUDA 11.1.
