### ISSUE TITLE
VoxelGridOcclusionEstimation gives incorrect results

### ISSUE THREAD

**Issue by shomedas** [PointCloudLibrary/pcl#2046]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Ubuntu 14.04, 64 bit
* Compiler: gcc 4.8.4
* PCL Version: 1.7

## Expected Behavior

Given a sensor location and a pointcloud, VoxelGridOcclusionEstimation should give which voxels in the pointcloud are occluded as seen by the sensor.

## Current Behavior
I tried to get the visible region in a sphere whose center satisfies one of 
the following: 
a. center is along x 
b. center is along y 
c. center is along z 
d. center is along x z plane 
e. center is along y z plane 
f. center is along x y plane 
The sesnor is at the origin with zero rotationn. 

I tried to  use the voxelgridOcclusionEstimation class to determine the 
visible region in the cloud as seen by the sensor 

voxelgridOcclusionEstimation yeilds wierd results. I all cases it seemed 
that the sphere contents in the first octant were processed properly. 
spheres in other octants were fully occluded. 

## Code to Reproduce

My code is: 

    Eigen::Quaternionf quat(1,0,0,0); 
    cloud_in->sensor_origin_  = Eigen::Vector4f(0,0,0,0); 

    cloud_in->sensor_orientation_= quat; 
    pcl::VoxelGridOcclusionEstimation<pcl::PointXYZ> voxelFilter; 
    voxelFilter.setInputCloud (cloud_in); 

    float leaf_size=atof(argv[2]); 
    voxelFilter.setLeafSize (leaf_size, leaf_size, leaf_size); 
    voxelFilter.initializeVoxelGrid(); 

    std::vector<Eigen::Vector3i, 
    Eigen::aligned_allocator&lt;Eigen::Vector3i> > occluded_voxels; 

    for (size_t i=0;i<cloud_in->size();i++) 
    { 
        PointT pt=cloud_in->points[i]; 
        Eigen::Vector3i grid_cordinates=voxelFilter.getGridCoordinates (pt.x, pt.y, pt.z); 

        int grid_state; 
        int ret=voxelFilter.occlusionEstimation( grid_state, grid_cordinates ); 

        if (grid_state==1) 
        { 
            cloud_occluded->push_back(cloud_in->points[i]); 
        } 
        else 
        { 
        cloud_visible->push_back(cloud_in->points[i]); 
        } 

    } 

## Context

I tried to  use the voxelgridOcclusionEstimation class to determine the  visible region in the cloud as seen by the sensor. However it gives wierd results as occlusion detection looks incorrect when viewed from the origin. It works somewhat in the first octant of the xyz system, but gives full occlusion in others.

Some images of the occlusion detection results:

sphere with center on x axis:
![sphere_along_x_cropped](https://user-images.githubusercontent.com/14357750/32223937-7c7d2f24-be65-11e7-9a7c-f4ca567c7071.png)

sphere with center on z axis:
![sphere_z_axis1](https://user-images.githubusercontent.com/14357750/32223954-91ef8802-be65-11e7-9361-ae7a33a11ee0.png)

sphere with center on y axis:
![sphere_along_y1](https://user-images.githubusercontent.com/14357750/32223965-9a53d5a2-be65-11e7-9883-9f28f01a7d7f.png)

sphere with center on yz plane:
![sphere_along_yz_plane1](https://user-images.githubusercontent.com/14357750/32224068-ede6a1cc-be65-11e7-8424-ad47b1735000.png)

sphere with center on xy plane:
![sphere_along_xy_plane1](https://user-images.githubusercontent.com/14357750/32224075-f6c1c1fa-be65-11e7-8948-7aecde25a131.png)

**Comment by SergioRAgostinho** [comment]
Since you recognized that at least the first octant, do you think you can crawl through the code and discover why the others are not really generating properly as well?

**Comment by shomedas** [comment]
Hi,

I mean it is somewhat ok. I have attached the images for reference. I have
limited abilities in c++ and have to read up ray tracing but I will give it
a try. If found I will update on the issue.

FYI the same issue has been reported in pcl users by another user as well
Error-in-ray-tracing-PCL-1-7
<http://www.pcl-users.org/Error-in-ray-tracing-PCL-1-7-td4031435.html#a4035566>.
I found similarity in his result pointcloud images and mine.


Thanks
Shome

**Comment by SergioRAgostinho** [comment]
> Hi,
    I did more experiments with the voxelgrid occlusion estimation class. I found out that it actually works-atleast for my application. The voxel size needs to be chosen very carefully. If chosen very small many voxels will be empty and the rays will pass through it. Also it may not be suitable for data captured from RGBD sensors which have many holes and non uniform point density. Due to the holes many rays may pass through the front surface and hit the back side. Hence it wasnt working properly in my initial experiments.

Reopen if needed

**Comment by themightyoarfish** [comment]
Is there any sample code for this filter? I have a cloud centered at the origin, but from almost any viewpoint set as `sensor_orientation_` and with all voxel sizes, I get no occluded voxels from `occlusionEstimationAll()`. So maybe I don't understand how it is supposed to work.
