### ISSUE TITLE
PCD file cannot show color information correctly

### ISSUE THREAD

**Issue by XuxinDoubleWang** [PointCloudLibrary/pcl#2048]
* Operating System and version: Linux 14.04
* Compiler: g++
* PCL Version: PCL 1.7.1

I am tried to record PCD file from Kinect v2. 
The 3 main libraries I used are OpenCV, PCL , OpenNi
I could record the PCD file successfully, however, when I check the PCD file, the color information only show in a little range and cannot cover all the image. Depth information seems OK.

Part of my code is shown below:

` 
while(true)  
        {  
            // read frame    
               if( oniColorStream.readFrame( &oniColorImg ) == STATUS_OK )    
            {    
                // convert data into OpenCV type    
                   Mat cvRGBImg( oniColorImg.getHeight(), oniColorImg.getWidth(), CV_8UC3, (void*)oniColorImg.getData() );    
                   cvtColor( cvRGBImg, cvBGRImg, CV_RGB2BGR );    
                   imshow( "image", cvBGRImg );    
            }    
      
            if( oniDepthStream.readFrame( &oniDepthImg ) == STATUS_OK )    
            {    
                Mat cvRawImg16U( oniDepthImg.getHeight(), oniDepthImg.getWidth(), CV_16UC1, (void*)oniDepthImg.getData() );    
                cvRawImg16U.convertTo( cvDepthImg, CV_8U, 255.0/(oniDepthStream.getMaxPixelValue()));      
                imshow( "depth", cvDepthImg );    
            }   	
        char input = waitKey(1);   
           quit  
           if( input == 'q' )        
               break;  
            // capture  depth and color data     
            if( input == 'c' )  
            {  
                //get data  
                DepthPixel *pDepth = (DepthPixel*)oniDepthImg.getData();  
                //create point cloud  
                cloud.width = oniDepthImg.getWidth();  
                cloud.height = oniDepthImg.getHeight();  
                cloud.is_dense = false;  
                cloud.points.resize(cloud.width * cloud.height); 
 
                color_cloud.width = oniDepthImg.getWidth();  
                color_cloud.height = oniDepthImg.getHeight();  
                color_cloud.is_dense = false;  
                color_cloud.points.resize(color_cloud.width * color_cloud.height);  
      
                //test = cvCreateImage(cvSize(cloud.width,cloud.height),IPL_DEPTH_8U,3);  
                IplImage temp11 = (IplImage)cvBGRImg;  
                //test2 = &IplImage(cvBGRImg);  
                test2 = &temp11;              
      
                for(i=0;i<oniDepthImg.getHeight();i++)  
                {  
                     for(j=0;j<oniDepthImg.getWidth();j++)  
                     {  
                         float k = i;    
                         float m = j;   
                         xx = pDepth[i*oniDepthImg.getWidth()+j];  
                         CoordinateConverter::convertDepthToWorld (oniDepthStream,m,k,xx,&x,&y,&z);   
              /*           cloud[i*cloud.width+j].x = x/1000;  
                         cloud[i*cloud.width+j].y = y/1000;  
                         cloud[i*cloud.width+j].z = z/1000;  
  		*/    
                         color_cloud[i*cloud.width+j].x = x/1000;  
                         color_cloud[i*cloud.width+j].y = y/1000;  
                         color_cloud[i*cloud.width+j].z = z/1000;  
                         color_cloud[i*cloud.width+j].b = (uint8_t)test2->imageData[i*test2->widthStep+j*3+0];  
                         color_cloud[i*cloud.width+j].g = (uint8_t)test2->imageData[i*test2->widthStep+j*3+1];  
                         color_cloud[i*cloud.width+j].r = (uint8_t)test2->imageData[i*test2->widthStep+j*3+2];  
                     }  
                 }  
                  
                cout<<"the "<<count<<" is saved"<<endl;  
                sprintf(filename,"./data/color_%d.pcd",count);  
                pcl::io::savePCDFileBinaryCompressed(filename,color_cloud);  
                cerr<<"Saved "<<color_cloud.points.size()<<" data points to xyzrgb pcd."<<endl;  
                sprintf(filename,"./data/color_%d.jpg",count);  
                imwrite(filename,cvBGRImg);  
                sprintf(filename,"./data/depth_%d.jpg",count++);  
                imwrite(filename,cvDepthImg);   
            }  
        }  `

I output the width and height of oniDepthImg, these are 640   480; the width and height of oniColorImg, these are 1080    1920. I think maybe I lost some color data when I combine them to PCD file.

Does anyone know what the problem is and give me some suggestions?
Any ideas are appreciated!

**Comment by taketwo** [comment]
This is a bug tracker, not a support forum. Please forward such questions to the pcl-users mailing list.

We do not have a grabber for Kinect v2 in PCL master, however there is an unmerged pull request #1410, you can give it a try.
