### ISSUE TITLE
Cannot removeText3D from specified viewport

### ISSUE THREAD

**Issue by glc12125** [PointCloudLibrary/pcl#2049]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

I have a program with multiple viewport using PCLVisualizer. However, I am not able to remove a 3D text that I added.

## Your Environment
* Operating System and version: Ubuntu 16.04.01
* Compiler: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* PCL Version: 1.8

## Expected Behavior
if I call removeText3D for an earlier added 3D text with addText3D, I should expect the same 3D text to be removed.

## Current behaviour
removeText3D() always return false for the 3d TEXT. After a few poking around, I found the items in the shape actor map (getShapeActorMap ()) contains the modified 3D text id. e.g. if I call addText3d() with id "text", it will be added as "text**". This is only happening if I use both APIs (addText3D(), removeText3D()) for more than one viewport. In my case, I created two viewports with createViewPort().
I had to manually add the extra "**" to remove the 3D text, which is hacky.

## Code to Reproduce
```cpp
pcl::visualization::PCLVisualizer pclViewer("test");
int port(0);
pclViewer.createViewPort(xMin, yMin, xMax, yMax, port);
pclVIewer.initCameraParameters();
pcl::PointXYZ textPosition;
textPosition.x = 5;
textPosition.y = 10;
textPosition.z = 7;
d_pclViewer->addText3D<pcl::PointXYZ>("text to show", textPosition, 0.2, 1.0,
                                           0.0, 0.0, "3DText", port);
// This is not the full program. but this is enough information to get the issue replicated.

```

**Comment by taketwo** [comment]
Seems like the logic behind these functions is indeed broken. In addition to the removal problem, the test on [line 672](https://github.com/PointCloudLibrary/pcl/blob/48c86f62f968293bcea4960b2f6c4ac45ec0d3d3/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp#L672) is not correct because of the `*` suffixes.

**Comment by glc12125** [comment]
[Pull Request](https://github.com/PointCloudLibrary/pcl/pull/2062) has been submitted to fix this.
