### ISSUE TITLE
MovingLeastSquaresOMP: Wrong Ptr/ConstPtr typedefs

### ISSUE THREAD

**Issue by ibtaylor** [PointCloudLibrary/pcl#2054]
https://github.com/PointCloudLibrary/pcl/blob/079cf248af2db17066e7ead5c366cbff103dd10b/surface/include/pcl/surface/mls.h#L743-L747

**Comment by taketwo** [comment]
This does look like a mistake. A patch is welcome.

**Comment by ibtaylor** [comment]
K, I'll make a PR
