### ISSUE TITLE
PCL_NO_PRECOMPILE support for flann_search

### ISSUE THREAD

**Issue by ibtaylor** [PointCloudLibrary/pcl#2056]
https://github.com/PointCloudLibrary/pcl/blob/24abc41f5eb6be447f14a96c76da7750d8e1027a/search/include/pcl/search/flann_search.h#L371-L373

Most `.h` files seem to includes the `.hpp` if `PCL_NO_PRECOMPILE` is set.. `flann_search.h` does not. Is this a bug?
For instance, all other search methods seem to do this.
https://github.com/PointCloudLibrary/pcl/blob/24abc41f5eb6be447f14a96c76da7750d8e1027a/search/include/pcl/search/octree.h#L287-L291
https://github.com/PointCloudLibrary/pcl/blob/24abc41f5eb6be447f14a96c76da7750d8e1027a/search/include/pcl/search/organized.h#L281-L283
https://github.com/PointCloudLibrary/pcl/blob/24abc41f5eb6be447f14a96c76da7750d8e1027a/search/include/pcl/search/kdtree.h#L176-L180
https://github.com/PointCloudLibrary/pcl/blob/24abc41f5eb6be447f14a96c76da7750d8e1027a/search/include/pcl/search/brute_force.h#L145-L147

**Comment by SergioRAgostinho** [comment]
Reopen if needed.
