### ISSUE TITLE
Deprecation of pcl::SAC_SAMPLE_SIZE

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2058]
Just adding this to the milestones for 1.9.0. It's time.

**Comment by taketwo** [comment]
It's deprecated already. Do you mean wiping it out? I'm all pro, it gives annoying warnings.

**Comment by SergioRAgostinho** [comment]
Yep. I think the policy was removal on the second release after it was deprecated (as long as it's not a patch one).

**Comment by taketwo** [comment]
Oh, then we can already remove soooooo many things!

**Comment by SergioRAgostinho** [comment]
Are you handling this one? I only erased a PCA constructor so far.

**Comment by taketwo** [comment]
I am indeed crafting a pull request with this right now. But I somehow misread the title and was thinking about your merged PCA request.
