### ISSUE TITLE
 error: ‘class vtkUnsignedCharArray’ has no member named ‘InsertNextTupleValue’ colors->InsertNextTupleValue (color);

### ISSUE THREAD

**Issue by yongduek** [PointCloudLibrary/pcl#2060]
* PCL Version: 1.8
* VTK 9.0
* Ubuntu 16.04

The error is caused because VTK version < 7 has `InsertNextTupleValue` but  the name is changed in newer versions of VTK.

Solution: Change the source code like the following:
```
491         // two times since we add also two points per edge
492 #if VTK_MAJOR_VERSION < 7
493         colors->InsertNextTupleValue (color);
494         colors->InsertNextTupleValue (color);
495 #else
496         colors->InsertNextTypedTuple(color);
497         colors->InsertNextTypedTuple(color);
498 #endif
```
This is according to `https://www.vtk.org/doc/nightly/html/VTK-7-1-Changes.html` which says:
The old and new method names are listed below:
    `GetTupleValue` is now `GetTypedTuple`
    `SetTupleValue` is now `SetTypedTuple`
    `InsertTupleValue` is now `InsertTypedTuple`
    `InsertNextTupleValue` is now `InsertNextTypedTuple`

**Comment by SergioRAgostinho** [comment]
Thanks 👍  Could you file a PR with the fix please?

**Comment by taketwo** [comment]
The page you referenced is called 7.1 changes. Shouldn't we check for this version rather than `< 7`?

**Comment by yongduek** [comment]
@taketwo yes, it should be 7.1.
So, the first line should have been:
```
#if (VTK_MAJOR_VERSION < 7) || (VTK_MAJOR_VERSION==7 && VTK_MINOR_VERSION==0)
```


@SergioRAgostinho I have no experience of PR. Would you teach me how to do it?

**Comment by SergioRAgostinho** [comment]
https://help.github.com/articles/proposing-changes-to-your-work-with-pull-requests/

**Comment by taketwo** [comment]
Please refer to our step-by-step guide: https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request

**Comment by SergioRAgostinho** [comment]
I just noticed that guide states the following 


> 3. If you cloned a while ago, get the latest changes from upstream:
> 
>     `git checkout master`
>     `git pull upstream master`

Should we not advise to rebase instead?

**Comment by taketwo** [comment]
Assumption is that the `master` branch is intact, with no extra commits, just outdated. Thus we pull the updates. The content of the pull request will go to a topic branch that we create in step 4 from the up-to-date `master`.
