### ISSUE TITLE
Input point cloud has no data! (Pairwise registration example)

### ISSUE THREAD

**Issue by anshulvj** [PointCloudLibrary/pcl#2065]
Hi,
I am trying to run the pairwise registration example given [here](http://pointclouds.org/documentation/tutorials/pairwise_incremental_registration.php#pairwise-incremental-registration)

I followed the steps as given without any modification (including importing the 5 .pcd files from [here](https://github.com/PointCloudLibrary/data/tree/master/tutorials/pairwise) ) but when I run the code it says 

` ./pairwise_incremental_registration capture000[1-5].pcd
[pcl::PCDReader::readHeader] No points to read
[pcl::PCDReader::readHeader] No points to read
Loaded 2 datasets.Press q to begin the registration.
Aligning capture0001.pcd (0) with capture0002.pcd (0).
[pcl::NormalEstimation::compute] input_ is empty!
[pcl::NormalEstimation::compute] input_ is empty!
[pcl::IterativeClosestPointNonLinear::setInputTarget] Invalid or empty point cloud dataset given!
Iteration Nr. 0.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 1.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 2.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 3.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 4.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 5.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 6.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 7.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 8.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 9.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 10.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 11.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 12.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 13.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 14.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 15.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 16.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 17.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 18.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 19.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 20.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 21.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 22.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 23.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 24.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 25.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 26.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 27.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 28.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Iteration Nr. 29.
[pcl::registration::IterativeClosestPointNonLinear::compute] No input target dataset was given!
Press q to continue the registration.
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!
Aborted (core dumped)
`

Which I assume basically means the pcd files are not getting read correctly. Based on the size of the pcd files there seems to be _some_ data in it!

I also tried running 1-2, 2-3, 3-4, 4-5.pcd separately but still same output.

Is there something obviously wrong in the way I am executing this? Are there any new pcd files that I can play with?

Thanks in advance
Anshul

**Comment by taketwo** [comment]
This is a bug tracker, not a support forum. Please direct such questions to the mailing list.
(That being said, I can not reproduce your problem on Ubnutu 16.04, latest PCL master.)

**Comment by CivicTesla** [comment]
I also have the same problem. Could anyone help......

**Comment by grantsadie88** [comment]
Hi there, did you download the correct files? I was experiencing the same issue but i went and redownloaded the full zip file and it worked with the new files.

**Comment by CivicTesla** [comment]
Hi, thx for the solution method. I changed the way to read the data(I used code for old version before), then it works
