### ISSUE TITLE
Appveyor integration

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2078]
I'm trying to get PCL to build on a Windows CI, through Appveyor. Since vcpkg was introduced, the effort to get this done seems considerably reduced, which drove my motivation to have another look at it.

This is what I have so far
https://github.com/SergioRAgostinho/pcl/blob/appveyor/.appveyor.yml

Here's the current results
https://ci.appveyor.com/project/SergioRAgostinho/pcl

It seems I'm going in the right direction, but my lack of a local Windows development environment is making it hard to understand what paths I need to feed to CMake in order to get this to work. Any help on this, would be much appreciated. @UnaNancyOwen since you actually wrote PCL's vcpkg port, I'm currently assuming you might be able to help me here.

Right now I just want it to compile something :sweat_smile: . CMake can't find Flann. I noticed it was able to find the vcpkg's installed eigen and flann was installed using the same method, so I assumed the problem is something else. I also noticed you patched our FindFLANN script for vcpkg https://github.com/Microsoft/vcpkg/blob/master/ports/pcl/find_flann.patch, hence my option to build shared libs.

Do I need to add all my installed packages to the path or something? Or is flann being deployed differently in vcpkg? Any ideas...anyone ?

**Comment by UnaNancyOwen** [comment]
These dependent libraries (Boost, FLANN, QHull) are generated with dynamic link libraries. (vcpkg default triplet is <code>x86-windows</code>. It is generate dynamic link library.)
Therefor, I think it need to set the following options when CMake configure of PCL.
```
cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DPCL_SHARED_LIBS=ON --DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=ON -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=ON ..
```

**Comment by SergioRAgostinho** [comment]
:+1: build completed :D
