### ISSUE TITLE
Build failed in tutorial 'point_cloud_compression' in VS2015 debug mode 

### ISSUE THREAD

**Issue by Rebecca128** [PointCloudLibrary/pcl#2081]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

Using the tutorial 'point_cloud_compression' from PCL website and encountering build fail with LNK2001 and LNK2019 in debug mode. But it build success in release mode.
## Your Environment

* Operating System and version: Win10 x64
* Compiler: VS2015 x64
* PCL Version: PCL 1.8.0 All-in-one Installer MSVC2015 x64

## Expected Behavior

Build success since all the configurations are correct

## Current Behavior

LNK2001	unresolved external symbol "public: virtual void __cdecl pcl::visualization::PCLVisualizer::FPSCallback::Execute(class vtkObject *,unsigned long,void *)" (?Execute@FPSCallback@PCLVisualizer@visualization@pcl@@UEAAXPEAVvtkObject@@KPEAX@Z)	point_cloud_compression	D:\database\point_cloud_compression\point_cloud_compression\point_cloud_compression.obj	1
LNK2019	unresolved external symbol MPI_Group_size referenced in function "public: int __cdecl boost::mpi::group::size(void)const " (?size@group@mpi@boost@@QEBAHXZ)	point_cloud_compression	D:\database\point_cloud_compression\point_cloud_compression\libboost_mpi-vc140-mt-gd-1_61.lib(group.obj)	1	
LNK2019 ...
LNK2019 ...
	

## Possible Solution

All the LNK2019 error related to the library 'libboost_mpi-vc140-mt-gd-1_61.lib' but it has been added in the VS2015.

**Comment by SergioRAgostinho** [comment]
Are you using CMake to generate your project?

**Comment by Rebecca128** [comment]
@SergioRAgostinho Thank you for your reply! I did not use CMake but directly use the PCL 1.8.0 All-in-one Installer MSVC2015 x64. The website is http://unanancyowen.com/en/pcl18/.

**Comment by SergioRAgostinho** [comment]
Then there's not much more we can do for you other than pointing you to our tutorial http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php#using-pcl-pcl-config

**Comment by SergioRAgostinho** [comment]
Also for future reference, have a look at https://github.com/Microsoft/vcpkg . PCL is one of the libraries you can install through it and this is currently the best installation method for PCL on Windows at the time.
