### ISSUE TITLE
PCLConfig.cmake should be define QHULL_USE_STATIC and FLANN_USE_STATIC

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#2084]
New PCLConfig.cmake doesn't include settings of <code>QHULL_USE_STATIC</code> (that using in <code>Modules/FindQHull.cmake</code>) and <code>FLANN_USE_STATIC</code> (that using in <code>Modules/FindFLANN.cmake</code>).
Therefore, PCLConfig.cmake always find dynamic link library of QHull and FLANN when configure user own project.
I think that PCLConfig.cmake should be define <code>QHULL_USE_STATIC</code> and <code>FLANN_USE_STATIC</code>.
In generally, I think users should be use libraries that used build PCL from source code.

@SergioRAgostinho @taketwo What do you think about it?

**Comment by UnaNancyOwen** [comment]
I think that these options are necessary to define according to the build-time options.
```patch
 macro(find_qhull)
   if(PCL_ALL_IN_ONE_INSTALLER)
     set(QHULL_ROOT "${PCL_ROOT}/3rdParty/Qhull")
   elseif(NOT QHULL_ROOT)
     get_filename_component(QHULL_ROOT "@QHULL_INCLUDE_DIRS@" PATH)
   endif(PCL_ALL_IN_ONE_INSTALLER)
  
+  set(QHULL_USE_STATIC @QHULL_USE_STATIC@)
   find_package(Qhull)
 endmacro(find_qhull)
```
```patch
 macro(find_flann)
   if(PCL_ALL_IN_ONE_INSTALLER)
     set(FLANN_ROOT "${PCL_ROOT}/3rdParty/Flann")
   elseif(NOT FLANN_ROOT)
     get_filename_component(FLANN_ROOT "@FLANN_INCLUDE_DIRS@" PATH)
   endif(PCL_ALL_IN_ONE_INSTALLER)

+  set(FLANN_USE_STATIC @FLANN_USE_STATIC@)
   find_package(FLANN)
 endmacro(find_flann)
```

**Comment by taketwo** [comment]
Agree.

Speaking of static/dynamic switches, can you please explain [`PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32`](https://github.com/PointCloudLibrary/pcl/blob/5e83e92ac579e79ffb4b4940730bab6b38a3ae82/CMakeLists.txt#L280) option? Why do we have this for FLANN, but not for QHull?

What about promoting `xxx_USE_STATIC` variables to proper CMake options that a user can toggle?

**Comment by SergioRAgostinho** [comment]
> What about promoting xxx_USE_STATIC variables to proper CMake options that a user can toggle?

:+1:

**Comment by UnaNancyOwen** [comment]
<code>PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32</code> is an option to specify use dynamic link libray of FLANN for build PCL from source code when <code>PCL_SHARED_LIBS</code> is ON and on Windows. (In that case, PCL use static link library of FLANN on Windows by default.)
PCL has a similar option <code>PCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32</code>.
I don't know the reason for not have a similar option for QHull.

> What about promoting xxx_USE_STATIC variables to proper CMake options that a user can toggle?

👍 
```patch
-  set(QHULL_USE_STATIC @QHULL_USE_STATIC@)
+  option(QHULL_USE_STATIC "Use Static Library of FLANN" @QHULL_USE_STATIC@)
```
```patch
-  set(FLANN_USE_STATIC @FLANN_USE_STATIC@)
+  option(FLANN_USE_STATIC "Use Static Library of QHull" @FLANN_USE_STATIC@)
```

**Comment by taketwo** [comment]
Oh, sorry, my proposal was misleading. I did not mean making `xxx_USE_STATIC` optional inside `PCLConfig`, I rather meant making it an option when configuring PCL before building. My thought was to replace `PCL_BUILD_WITH_xxx_DYNAMIC_LINKING_WIN32`. Because, why Windows only? Maybe people on Linux also want to be able to control this.

Now coming back to the situation in the `PCLConfig` file. Imagine PCL was built with _static_ linking of FLANN. In this case we do not need to find and link FLANN in user project at all! It's already incorporated into PCL libraries.

**Comment by UnaNancyOwen** [comment]
> Oh, sorry, my proposal was misleading. I did not mean making xxx_USE_STATIC optional inside PCLConfig, I rather meant making it an option when configuring PCL before building. My thought was to replace PCL_BUILD_WITH_xxx_DYNAMIC_LINKING_WIN32. Because, why Windows only? Maybe people on Linux also want to be able to control this.

Agree. 👍 

> Now coming back to the situation in the PCLConfig file. Imagine PCL was built with static linking of FLANN. In this case we do not need to find and link FLANN in user project at all! It's already incorporated into PCL libraries.

Currently, PCLConfig.cmake will always try to find dependency libraries (FLANN, QHull).
Should we fix this?

**Comment by taketwo** [comment]
> But, FLANN and QHull are not necessary when PCL static linked these libraries.

Thinking about this more... we still need to find them to add their include directories, right?

> Should we fix this?

I think your current PR is sufficient. In the case of static libraries we end up linking against them once again, but that does not hurt.

**Comment by SergioRAgostinho** [comment]
> I think your current PR is sufficient. In the case of static libraries we end up linking against them once again, but that does not hurt.

Considering that we now have unified the find package scripts it would be complicated to address the "while building pcl" and the "while including pcl in your project" situations differently to prevent the libraries to be added.

During the static linking, the compiler only links what is required i.e., we don't risk bloated binaries we a second static linkage right?

**Comment by UnaNancyOwen** [comment]
>Thinking about this more... we still need to find them to add their include directories, right?

OK, If include directories is necessary, It seems necessary to find those libraries.
I think this pull request is good to merge.

**Comment by SergioRAgostinho** [comment]
Aren't you missing defining  `xxx_USE_STATIC` as options during the build process?

**Comment by taketwo** [comment]
> During the static linking, the compiler only links what is required i.e., we don't risk bloated binaries if we have a second static linkage right?

To the best of my knowledge, yes.

> Aren't you missing defining xxx_USE_STATIC as options during the build process?

I can take care of this (and removing old `_WIN` options) in a separate PR.

**Comment by SergioRAgostinho** [comment]
Superseeded by #2089.
