### ISSUE TITLE
No setInputCloud function for pcl::FrustumCulling

### ISSUE THREAD

**Issue by TonythePlaneswalker** [PointCloudLibrary/pcl#2093]
It seems that there is no way to set the input point cloud for the FrustumCulling class in pcl/filters.

In the examples, there is a line to set the source point cloud

`fc.setInputCloud (source);`

But `setInputCloud` is not defined in `frustumculling.h`, and there is no other function to set the protected member `input_`.

## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc 5.3.1
* PCL Version: 1.7.2rc1

## Code to Reproduce
```
pcl::FrustumCulling<pcl::PointXYZ> fc;
fc.setInputCloud (source);
```

**Comment by taketwo** [comment]
But what is the problem with the code you posted? Do you get a compilation error?

`FrustumCulling` derives from `FilterIndices`, which derives from `Filter`, which derives from `PCLBase`. This class has the method you are interested in.

**Comment by TonythePlaneswalker** [comment]
I figured it out.

`setInputCloud` takes a pointer, not the point cloud object itself.
```
/usr/include/pcl-1.7/pcl/pcl_base.h:95:7: note: candidate: void pcl::PCLBase<PointT>::setInputCloud(const PointCloudConstPtr&) [with PointT = pcl::PointXYZ; pcl::PCLBase<PointT>::PointCloudConstPtr = boost::shared_ptr<const pcl::PointCloud<pcl::PointXYZ> >]
       setInputCloud (const PointCloudConstPtr &cloud);
       ^
/usr/include/pcl-1.7/pcl/pcl_base.h:95:7: note:   no known conversion for argument 1 from ‘pcl::PointCloud<pcl::PointXYZ>’ to ‘const PointCloudConstPtr& {aka const boost::shared_ptr<const pcl::PointCloud<pcl::PointXYZ> >&}’
```

Thanks!
