### ISSUE TITLE
Display text3D

### ISSUE THREAD

**Issue by frozar** [PointCloudLibrary/pcl#2109]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

**That's a bug.**

## Your Environment
* Operating System and version: Ubuntu 16.04.3
* Compiler: gcc 5.4.0
* PCL Version: master branch

## Situation
I don't see the 3D text I added to my scene. I provide a tiny code to test it:
[pcl_text_simple.zip](https://github.com/PointCloudLibrary/pcl/files/1522325/pcl_text_simple.zip)

I use the original `addText3D()` method (without the orientation array).

## Example in clear
```cpp
#include <iostream>
#include <pcl/point_types.h>

#include <pcl/visualization/pcl_visualizer.h>

int
main (int argc, char** argv)
{
  pcl::visualization::PCLVisualizer viz ("Visualizator");
  viz.addCoordinateSystem(1.0);

  viz.addText3D ("SIMPLE", pcl::PointXYZ(0.0, 0.0, 0.0));

  //main loop of the visualizer
  while (!viz.wasStopped ())
  {
    viz.spinOnce(100);
    boost::this_thread::sleep(boost::posix_time::microseconds(100000));
  }

  return (0);
}
```

## Possible reason
Maybe I miss something in the tiny example, or maybe it comes from recent PR (I think about #2088 but I really don't know). Ok now I'm pretty that it comes from PR #2088.

**Comment by SergioRAgostinho** [comment]
Fixed by #2110
