### ISSUE TITLE
ISSUE: terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by LiShuaixin** [PointCloudLibrary/pcl#2114]
I'm studying pcl recently and my pcl version is pcl-1.8. I define two point cloud pointers to store all points and points in current iteration respectively in a class. Both of them are public member variables. I add them up (around a million new points) at the end of each iteration. But it seems that there is something wrong. I have tried to write like this:
                              `// assume a is the stored pointer
                                // b is the new pointer 
                                for(int i = 0; i < b->size(); i++){
					a->push_back(b->points[i]);
				}`
or like this:
                               `*a += *b;`
But both of them will fail and return "terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc" 
I think it may cause by oversizing the pointer's boundary that it randomly assigned. Then I changed it like this: 
                               `a->resize(a->size() + b->size());
                               *a += *b;`
It's still wrong. However, they occurred after different times of iteration. I'd like to ask what caused this problem and how should I change mt code?

**Comment by SergioRAgostinho** [comment]
Sounds like you’re running out of memory. 

As it is stated in the issue template, for questions like this you should post them to the user mailing list at http://www.pcl-users.org/ . The bug tracker is limited to library maintenance topics.
