### ISSUE TITLE
I can't do simple compilation (pcd_read.cpp), VTK not found.  What am I doing wrong?

### ISSUE THREAD

**Issue by Tam66662** [PointCloudLibrary/pcl#2118]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

I am new to the point cloud library and all of its dependencies.  All I want to do is compile something simple like [pcd_read.cpp](http://www.pointclouds.org/documentation/tutorials/reading_pcd.php#reading-pcd).  Whenever I run cmake, it gives me an error about the VTK not being found.  I have attached the pcd_read.cpp, CMakeLists.txt, and the build output from running "cmake .." inside the build folder.

What started out as a warning turned into an error towards the end of the build:
![image](https://user-images.githubusercontent.com/12551526/33582190-e461581e-d908-11e7-8807-c86905b0d14c.png)

## Your Environment

* Operating System and version: Windows 10 Insider Preview 17064 and Windows 8.1 Version 6.3 (Build 9600)
* Compiler: Microsoft Visual Studio 2017 and Microsoft Visual Studio 2015 compilers
* PCL Version: 1.8.1, specifically installed PCL-1.8.1-AllInOne-msvc2017-win64.exe on a Windows 10 machine and PCL-1.8.1-AllInOne-msvc2015-win64 on a Windows 8.1 machine
* CMake Version: 3.10.0

## Expected Behavior
I followed the [documentation instructions](http://www.pointclouds.org/documentation/tutorials/reading_pcd.php#reading-pcd) on creating the CMakeLists.txt file and running cmake for the pcd_read example, and I expected the build to complete successfully.  

## Current Behavior
However, on both a Windows 10 and Windows 8.1 system, I get a VTK warning/error saying that it can't resolve VTK (details are in the attached build logs and the above screenshot).  I assume the VTK is installed as part of the PCL-1.8.1-AllInOne-msvc2017-win64.exe all-in-one executable.

## Possible Solution
I need help with this

## Code to Reproduce
Code and cmake build output can be found in the attached zip here:
[PcdConverter.zip](https://github.com/PointCloudLibrary/pcl/files/1529158/PcdConverter.zip)

## Context

I really want to make use of the point cloud library but I can't even get it to compile a simple console app.  All I want it to do is compile something, anything.

N/A

**Comment by SergioRAgostinho** [comment]
As the issue template states, this is an issue tracker. Use the user forum/mailing list for questions like these www.pcl-users.org

**Comment by UnaNancyOwen** [comment]
Probably, CMake uses generator that x86 configure of Visual Studio by default on Windows.
If you want to use PCL that installed by PCL-1.8.1-AllInOne-msvc2017-win64.exe, Please specify generator "Visual Studio 15 2017 Win64" to CMake. (<code>cmake .. -G"Visual Studio 15 2017 Win64"</code>)
