### ISSUE TITLE
problem with the conditional_euclidean_clustering

### ISSUE THREAD

**Issue by YongWangNJ** [PointCloudLibrary/pcl#2127]
* Operating System and version: windows 7
* Compiler: VS2015
* PCL Version: 1.8.1

problem with the example "conditional_euclidean_clustering"

Eigen::Map<const Eigen::Vector3f> point_a_normal = point_a.normal, point_b_normal = point_b.normal;

conditional_euclidean_clustering.cpp(24): error C2440: “初始化”: 无法从“const float [3]”转换为“Eigen::Map<const Eigen::Vector3f,0,Eigen::Stride<0,0>>”

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen can you give it a try?

It's this [example](https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/conditional_euclidean_clustering/conditional_euclidean_clustering.cpp).

**Comment by UnaNancyOwen** [comment]
Same compiler error occurs in [conditional_euclidean_clustering.cpp#L24](https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/conditional_euclidean_clustering/conditional_euclidean_clustering.cpp#L24) and [conditional_euclidean_clustering.cpp#L35](https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/conditional_euclidean_clustering/conditional_euclidean_clustering.cpp#L24).

```
Error	E0415	no suitable constructor exists to convert from "const float [3]" to "Eigen::Map<const Eigen::Vector3f, 0, Eigen::Stride<0, 0>>"	conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	24
Error	E0415	no suitable constructor exists to convert from "const float [3]" to "Eigen::Map<const Eigen::Vector3f, 0, Eigen::Stride<0, 0>>"	conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	24
Error	E0415	no suitable constructor exists to convert from "const float [3]" to "Eigen::Map<const Eigen::Vector3f, 0, Eigen::Stride<0, 0>>"	conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	35
Error	E0415	no suitable constructor exists to convert from "const float [3]" to "Eigen::Map<const Eigen::Vector3f, 0, Eigen::Stride<0, 0>>"	conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	35
Error	C2440	'initializing': cannot convert from 'const float [3]' to 'Eigen::Map<const Eigen::Vector3f,0,Eigen::Stride<0,0>>'		conditional_euclidean_clustering	C:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	24
Error	C2440	'initializing': cannot convert from 'const float [3]' to 'Eigen::Map<const Eigen::Vector3f,0,Eigen::Stride<0,0>>'		conditional_euclidean_clustering	C:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	24
Error	C2440	'initializing': cannot convert from 'const float [3]' to 'Eigen::Map<const Eigen::Vector3f,0,Eigen::Stride<0,0>>'		conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	35
Error	C2440	'initializing': cannot convert from 'const float [3]' to 'Eigen::Map<const Eigen::Vector3f,0,Eigen::Stride<0,0>>'		conditional_euclidean_clustering	c:\conditional_euclidean_clustering\conditional_euclidean_clustering.cpp	35
```

**Comment by SergioRAgostinho** [comment]
Can you quickly submit a fix for it?

Using `getNormalVector3fMap()` should do the trick
https://github.com/PointCloudLibrary/pcl/blob/b0e83f2681fe403a1a7c4a213449b1ebbf35bccc/common/include/pcl/impl/point_types.hpp#L208-L212

**Comment by UnaNancyOwen** [comment]
It can build successfully. I will send pull request right away.

```patch
- Eigen::Map<const Eigen::Vector3f> point_a_normal = point_a.normal, point_b_normal = point_b.normal;
+ Eigen::Map<const Eigen::Vector3f> point_a_normal = point_a.getNormalVector3fMap (), point_b_normal = point_b.getNormalVector3fMap ();
```

**Comment by YongWangNJ** [comment]
It can build successfully now, thank you very much!
