### ISSUE TITLE
A bug which results in throwing "out_of_range" exception

### ISSUE THREAD

**Issue by PengPengHub** [PointCloudLibrary/pcl#2138]
Hi Sergio

Baidu X-Lab found a bug which results in throwing "'std::out_of_range'" exception, please see the attachment for your reference.

[bug2.zip](https://github.com/PointCloudLibrary/pcl/files/1546226/bug2.zip)

Best,
Peng

**Comment by taketwo** [comment]
The PCD file is clearly malformed. @SergioRAgostinho what do you think? Is it okay to throw if a bad file is given?

```
#@.PON 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH POINT 0 0 0 0 0
POINTS 51
DAT000001 0
0.31 -0.01010880423
```

**Comment by SergioRAgostinho** [comment]
In general, the things Peng "throws at us" are intentionally corrupted PCDs. I have the idea that they're using PCL for their Apollo project and they're "stress testing" PCL against potentially bad inputs from their users.

In the two other bug submissions I worked on, the idea was to detect that the PCD header is malformed as early as possible, abort and return an error, to prevent throwing exceptions down the road. That has been my mindset so far.

Therefore it's not ok let it go all the way up to the "'std::out_of_range'" exception mentioned, assuming that there's of course a way to detect in advance that the file is malformed.
