### ISSUE TITLE
Error building pcl::visualization 

### ISSUE THREAD

**Issue by blackPython** [PointCloudLibrary/pcl#2155]
I am trying to build pcl_gpu_kinfu to be used my own application. But but building visualization is throwing errors when I run the make install command. This error is as follows
`In file included from /home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/pcl_visualizer.h:2338:0,
                 from /home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp:100:
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp: In member function ‘bool pcl::visualization::PCLVisualizer::addSphere(const PointT&, double, double, double, double, const string&, int)’:
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp:603:24: error: ‘class vtkMapper’ has no member named ‘ImmediateModeRenderingOn’
   actor->GetMapper ()->ImmediateModeRenderingOn ();
                        ^
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp: In member function ‘bool pcl::visualization::PCLVisualizer::updatePointCloud(const typename pcl::PointCloud<PointT>::ConstPtr&, const string&)’:
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp:1534:38: error: ‘class vtkMapper’ has no member named ‘ImmediateModeRenderingOff’
   am_it->second.actor->GetMapper ()->ImmediateModeRenderingOff ();
                                      ^
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp: In member function ‘bool pcl::visualization::PCLVisualizer::updatePointCloud(const typename pcl::PointCloud<PointT>::ConstPtr&, const pcl::visualization::PointCloudGeometryHandler<PointT>&, const string&)’:
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp:1570:38: error: ‘class vtkMapper’ has no member named ‘ImmediateModeRenderingOff’
   am_it->second.actor->GetMapper ()->ImmediateModeRenderingOff ();
                                      ^
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp: In member function ‘bool pcl::visualization::PCLVisualizer::updatePointCloud(const typename pcl::PointCloud<PointT>::ConstPtr&, const pcl::visualization::PointCloudColorHandler<PointT>&, const string&)’:
/home/aditya/data/pcl/pcl/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp:1646:38: error: ‘class vtkMapper’ has no member named ‘ImmediateModeRenderingOff’
   am_it->second.actor->GetMapper ()->ImmediateModeRenderingOff ();
                                      ^
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp: In member function ‘void pcl::visualization::PCLVisualizer::createActorFromVTKDataSet(const vtkSmartPointer<vtkDataSet>&, vtkSmartPointer<vtkLODActor>&, bool)’:
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp:1220:13: error: ‘class vtkDataSetMapper’ has no member named ‘ImmediateModeRenderingOff’
     mapper->ImmediateModeRenderingOff ();
             ^
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp: In member function ‘void pcl::visualization::PCLVisualizer::createActorFromVTKDataSet(const vtkSmartPointer<vtkDataSet>&, vtkSmartPointer<vtkActor>&, bool)’:
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp:1300:13: error: ‘class vtkDataSetMapper’ has no member named ‘ImmediateModeRenderingOff’
     mapper->ImmediateModeRenderingOff ();
             ^
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp: In member function ‘bool pcl::visualization::PCLVisualizer::setPointCloudRenderingProperties(int, double, const string&, int)’:
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp:1546:28: error: ‘class vtkMapper’ has no member named ‘SetImmediateModeRendering’
       actor->GetMapper ()->SetImmediateModeRendering (int (value));
                            ^
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp: At global scope:
/home/aditya/data/pcl/pcl/visualization/src/pcl_visualizer.cpp:4545:53: warning: unused parameter ‘use_vbos’ [-Wunused-parameter]
 pcl::visualization::PCLVisualizer::setUseVbos (bool use_vbos)
                                                     ^
visualization/CMakeFiles/pcl_visualization.dir/build.make:134: recipe for target 'visualization/CMakeFiles/pcl_visualization.dir/src/pcl_visualizer.cpp.o' failed
make[2]: *** [visualization/CMakeFiles/pcl_visualization.dir/src/pcl_visualizer.cpp.o] Error 1
CMakeFiles/Makefile2:1595: recipe for target 'visualization/CMakeFiles/pcl_visualization.dir/all' failed
make[1]: *** [visualization/CMakeFiles/pcl_visualization.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`
But i checked vtk documentation all the classes mentioned here are inherited from vtkMapper, and according to the documentation they do have members which are throwing errors, that is they have ImmediateModeRenderingOff(), ImmediateModeRenderingOn() and SetImmediateModeRendering(int) . So I am not able to understand the origin of this problem.Did anyone face the same problem while trying to build pcl? Please let me know .

**Comment by taketwo** [comment]
This immediate mode rendering reminded me of this: https://github.com/PointCloudLibrary/pcl/pull/2112#issuecomment-348791577. Are you using a bleeding-edge VTK with OpenGL2? Try to apply the changes from that PR and let us know if it helps.

**Comment by blackPython** [comment]
Yes i just found out that when i tried out the standard release it is no problem

**Comment by ClaudioCimarelli** [comment]
@blackPython @taketwo Hello, I have the same problem using the latest version of VTK on the Git Repo. I do not understand how should I fix this issue. Could you help?

Thanks a lot.

**Comment by taketwo** [comment]
I never faced with problem myself, but from the discussions here at PCL I understand that all the compatibility issues were solved by #2112 and #2165. So if you are using latest VTK master, please also use latest PCL master. If you still get compilation errors, please post them.
