### ISSUE TITLE
Accessing extract_removed_indices_ parameter in NormalSpaceSampling

### ISSUE THREAD

**Issue by nenadpol** [PointCloudLibrary/pcl#2157]
Hi, 

pcl::NormalSpacesamplig class inherits base clas pcl::Filter. 

pcl:.Filter has protected parameter extract_removed_indices accesed only 
through constructor. 

Shouldn't class pcl::NormalSpaceSampling also has this parameter in 
constructor (like pcl::FilterIndices)? 

Otherwise, it is impossible to change this parameter from false (default) to 
true. 

thanks, 
Nenad

**Comment by taketwo** [comment]
:+1: please send a PR
