### ISSUE TITLE
registration accuracy error 

### ISSUE THREAD

**Issue by Realitian** [PointCloudLibrary/pcl#2158]
Hi I found registration accuracy error in version up!

I tried to run "alignment_prerejective" tutorial following as http://pointclouds.org/documentation/tutorials/alignment_prerejective.php#alignment-prerejective
but I got so visual error in 1.8.1 release.
but it works in 1.7.2 release.
I guess there is a minimal difference between 1.8.1 vs 1.7.2 versions.
here are each results of pose for chef.pcd
**1.8.1(error)**

    | -0.162 -0.786  0.596 | 
R = | -0.987  0.132 -0.094 | 
    | -0.005 -0.604 -0.797 | 

t = < 0.406, -0.006, 0.127 >

**1.7.2(fine)**

    | -0.019 -0.943 -0.331 | 
R = | -0.999  0.005  0.044 | 
    | -0.040  0.332 -0.943 | 

t = < -0.266, 0.085, 0.115 >

**Comment by VyetrVik** [comment]
Hi,
I received biggest difference in this tutorial:
Compling as is,  give me next transformation:
    | -0.634 -0.410  0.656 |
R = | -0.763  0.469 -0.445 |
    | -0.125 -0.783 -0.610 |

t = < 0.462, -0.242, 0.260 >
Inliers: 1167/3432

But in it must be  :
    |  0.040 -0.929 -0.369 |
R = | -0.999 -0.035 -0.020 |
    |  0.006  0.369 -0.929 |

t = < -0.287, 0.045, 0.126 >

Inliers: 987/3432

I use  version 1.8.1 (08.08.2017)  compiled on Windpws 10 VisualStudio 2015 win64
