### ISSUE TITLE
recipe for target all failed

### ISSUE THREAD

**Issue by sivaariram** [PointCloudLibrary/pcl#2164]
nvidia@tegra-ubuntu:/media/nvidia/JetsonSSD/home/nvidia/pcl/build$ sudo make -j2 install
[sudo] password for nvidia: 
Scanning dependencies of target pcl_octree
Scanning dependencies of target pcl_common
[  0%] Building CXX object octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/point_types.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/io.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/common.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/correspondence.cpp.o
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/distances.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/parse.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/poses_from_matches.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/print.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/projection_matrix.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/time_trigger.cpp.o
[  1%] Linking CXX shared library ../lib/libpcl_octree.so
[  1%] Built target pcl_octree
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/gaussian.cpp.o
Scanning dependencies of target pcl_io_ply
[  1%] Building CXX object io/CMakeFiles/pcl_io_ply.dir/src/ply/ply_parser.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/colors.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/feature_histogram.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.o
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/range_image.cpp.o
[  1%] Linking CXX shared library ../lib/libpcl_io_ply.so
[  1%] Built target pcl_io_ply
[  1%] Building CXX object common/CMakeFiles/pcl_common.dir/src/range_image_planar.cpp.o
Scanning dependencies of target pcl_pcd_convert_NaN_nan
[  1%] Building CXX object io/tools/CMakeFiles/pcl_pcd_convert_NaN_nan.dir/pcd_convert_NaN_nan.cpp.o
[  1%] Linking CXX executable ../../bin/pcl_pcd_convert_NaN_nan
[  1%] Built target pcl_pcd_convert_NaN_nan
[  1%] Building C object common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o
Scanning dependencies of target pcl_plyheader
[  1%] Building CXX object io/tools/ply/CMakeFiles/pcl_plyheader.dir/plyheader.cpp.o
[  1%] Linking CXX executable ../../../bin/pcl_plyheader
[  1%] Built target pcl_plyheader
[  2%] Building C object common/CMakeFiles/pcl_common.dir/src/fft/kiss_fftr.c.o
Scanning dependencies of target pcl_ply2raw
[  2%] Building CXX object io/tools/ply/CMakeFiles/pcl_ply2raw.dir/ply2raw.cpp.o
[  2%] Linking CXX shared library ../lib/libpcl_common.so
[  2%] Built target pcl_common
Scanning dependencies of target pcl_ply2ply
[  2%] Building CXX object io/tools/ply/CMakeFiles/pcl_ply2ply.dir/ply2ply.cpp.o
[  2%] Linking CXX executable ../../../bin/pcl_ply2raw
[  2%] Built target pcl_ply2raw
Scanning dependencies of target pcl_ply2obj
[  2%] Building CXX object io/tools/ply/CMakeFiles/pcl_ply2obj.dir/ply2obj.cpp.o
[  3%] Linking CXX executable ../../../bin/pcl_ply2obj
[  3%] Built target pcl_ply2obj
Scanning dependencies of target pcl_kdtree
[  3%] Building CXX object kdtree/CMakeFiles/pcl_kdtree.dir/src/kdtree_flann.cpp.o
[  3%] Linking CXX executable ../../../bin/pcl_ply2ply
[  3%] Built target pcl_ply2ply
Scanning dependencies of target pcl_sample_consensus
[  3%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac.cpp.o
[  3%] Linking CXX shared library ../lib/libpcl_kdtree.so
[  3%] Built target pcl_kdtree
[  3%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_circle.cpp.o
Scanning dependencies of target pcl_ml
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/point_xy_32i.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/point_xy_32f.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/densecrf.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/pairwise_potential.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/permutohedral.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/svm_wrapper.cpp.o
[  3%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_circle3d.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/svm.cpp.o
[  3%] Building CXX object ml/CMakeFiles/pcl_ml.dir/src/kmeans.cpp.o
[  4%] Linking CXX shared library ../lib/libpcl_ml.so
[  4%] Built target pcl_ml
[  4%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o
Scanning dependencies of target pcl_people
[  4%] Building CXX object people/CMakeFiles/pcl_people.dir/src/hog.cpp.o
[  4%] Linking CXX shared library ../lib/libpcl_people.so
[  4%] Built target pcl_people
[  4%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:134: recipe for target 'sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o' failed
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target pcl_gpu_containers
[  4%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/initialization.cpp.o
[  4%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/error.cpp.o
[  4%] Building CXX object gpu/containers/CMakeFiles/pcl_gpu_containers.dir/src/device_memory.cpp.o
[  4%] Linking CXX shared library ../../lib/libpcl_gpu_containers.so
[  4%] Built target pcl_gpu_containers
[  4%] Building NVCC (Device) object cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target pcl_cuda_features
[  4%] Linking CXX shared library ../../lib/libpcl_cuda_features.so
[  4%] Built target pcl_cuda_features
[  4%] Building NVCC (Device) object cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target pcl_cuda_segmentation
[  4%] Linking CXX shared library ../../lib/libpcl_cuda_segmentation.so
[  4%] Built target pcl_cuda_segmentation
[  4%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_multi_ransac.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[  4%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_sac_model.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
CMakeFiles/Makefile2:952: recipe for target 'sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all' failed
make[1]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_sac_model_plane.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[  5%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_sac_model_1point_plane.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[  5%] Building NVCC (Device) object cuda/sample_consensus/CMakeFiles/pcl_cuda_sample_consensus.dir/src/pcl_cuda_sample_consensus_generated_ransac.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Scanning dependencies of target pcl_cuda_sample_consensus
[  5%] Linking CXX shared library ../../lib/libpcl_cuda_sample_consensus.so
[  5%] Built target pcl_cuda_sample_consensus
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SergioRAgostinho** [comment]
GCC died half way through the process.

**Comment by billwang996** [comment]
44%] Built target pcl_surface
[ 51%] Built target pcl_registration
[ 55%] Built target pcl_recognition
[ 57%] Built target pcl_keypoints
[ 58%] Built target pcl_transform_point_cloud
[ 62%] Built target pcl_visualization
[ 62%] Linking CXX executable ../bin/pcl_voxel_grid_occlusion_estimation
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSM.so：对‘uuid_generate@UUID_1.0’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libSM.so：对‘uuid_unparse_lower@UUID_1.0’未定义的引用
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_voxel_grid_occlusion_estimation.dir/build.make:251: recipe for target 'bin/pcl_voxel_grid_occlusion_estimation' failed
make[2]: *** [bin/pcl_voxel_grid_occlusion_estimation] Error 1
CMakeFiles/Makefile2:1603: recipe for target 'tools/CMakeFiles/pcl_voxel_grid_occlusion_estimation.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_voxel_grid_occlusion_estimation.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
