### ISSUE TITLE
dataset with face_detection in app

### ISSUE THREAD

**Issue by Hesy-H** [PointCloudLibrary/pcl#2169]
code in pcl/apps/src/face_detection/  needs forest.txt and face.pcd，but I don't konw what format these data files should be....Is there any guide or any sample?

**Comment by SergioRAgostinho** [comment]
Unfortunately not. This is code which was added 5 years ago, even before we used git. Maybe the original author @arbeitor can provide some insight here.

For further questions like these please use our pcl users mailing list. We use the issue tracker for bug tracking purposes.

**Comment by Hesy-H** [comment]
Thank you for your reply.I'm a novice on github , sorry for bringing trouble.
