### ISSUE TITLE
pcl::addCube problem

### ISSUE THREAD

**Issue by manhha1402** [PointCloudLibrary/pcl#2172]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: 14.04
* Compiler: The CXX compiler identification is GNU 5.4.1
* PCL Version: 1.8.1

I have recently updated  PCL version from 1.7 to 1.8.1. I tried to add a Bounding Box of an object using PCA and addCube function. I used parameters taken from PCA algorithm ((bboxTransform, bboxQuaternion, minpoint, maxpoint) to use in pcl::addCube and visualize on pcl viewer as shown:
![cube2](https://user-images.githubusercontent.com/20105284/34482062-f8b47e72-efb5-11e7-8c07-fc806af0002f.png)
The original point cloud
![cube1](https://user-images.githubusercontent.com/20105284/34482074-0be4c07e-efb6-11e7-89c6-ca18b0ea026a.png)

Can anyone tell me what happens here?
Thanks

**Comment by SergioRAgostinho** [comment]
> I have recently updated PCL version from 1.7 to 1.8.1.

Was it working properly in 1.7? 

> Can anyone tell me what happens here?

It doesn't seem to bound your object. It would be nice to see them properly overlayed just to be sure. 

The second part will be the post a code snippet and data you used to generate both images.

**Comment by manhha1402** [comment]
1. Yes. It worked perfectly in 1.7. I just want to update to 1.8 to use c++11 to work with my camera( Intel Realsense camera)
2. This is a code snippet to generate 3D bouding box using PCA. Input is the point cloud that I posted
`//Compute the 3x3 covariance matrix of a given set of points.
   // The result is returned as a Eigen::Matrix3f.
   // Note: the covariance matrix is not normalized with the number of points
   //
   pcl::PointXYZRGB min_point,max_point;
   Eigen::Vector4f pcaCentroid;
   pcl::compute3DCentroid(*cloud,pcaCentroid);
   Eigen::Matrix3f covariance;
   pcl::computeCovarianceMatrixNormalized(*cloud,pcaCentroid,covariance);
   //Compute eigenvectors and eigenvalues of covariance matrix using Eigen
   Eigen::SelfAdjointEigenSolver<Eigen::Matrix3f> eigen_solver(covariance, Eigen::ComputeEigenvectors);
   //Eigen vectors
   Eigen::Matrix3f eigenVectorsPCA = eigen_solver.eigenvectors();
   // Extract the eigenvalues and eigenvectors using PCL
   Eigen::Vector3f eigen_values;
   Eigen::Matrix3f eigen_vectors;
   pcl::eigen33 (covariance, eigen_vectors, eigen_values);

   /// This line is necessary for proper orientation in some cases. The numbers come out the same without it, but
/// the signs are different and the box doesn't get correctly oriented in some cases.
   eigenVectorsPCA.col(2) = eigenVectorsPCA.col(0).cross(eigenVectorsPCA.col(1));

   // Transform the original cloud to the origin point where the principal components correspond to the axes.
   Eigen::Matrix4f projectionTransform(Eigen::Matrix4f::Identity());
   projectionTransform.block<3,3>(0,0) = eigenVectorsPCA.transpose();
   projectionTransform.block<3,1>(0,3) = -1.f * (projectionTransform.block<3,3>(0,0) * pcaCentroid.head<3>());

   pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudPointsProjected (new pcl::PointCloud<pcl::PointXYZRGB>);
   pcl::transformPointCloud(*cloud,*cloudPointsProjected,projectionTransform);
   // Get the minimum and maximum points of the transformed cloud.
   pcl::getMinMax3D(*cloudPointsProjected, min_point, max_point);
   const Eigen::Vector3f meanDiagonal = 0.5f*(max_point.getVector3fMap() + min_point.getVector3fMap());
//Finally, the quaternion is calculated using the eigenvectors (which determines how the final box gets rotated),
//and the transform to put the box in correct location is calculated.
//The minimum and maximum points are used to determine the box width, height, and depth.
   const Eigen::Quaternionf bboxQuaternion(eigenVectorsPCA); //Quaternions are a way to do rotations
   //translation
   const Eigen::Vector3f bboxTransform = eigenVectorsPCA * meanDiagonal + pcaCentroid.head<3>();
  //Add Cube 
viewer_->addCube(bboxTransform, bboxQuaternion, max_point.x - min_point.x, max_point.y - min_point.y, max_point.z - min_point.z);
`

**Comment by SergioRAgostinho** [comment]
> Yes. It worked perfectly in 1.7. I just want to update to 1.8 to use c++11 to work with my camera( Intel Realsense camera)

Use [git bisect](https://stackoverflow.com/questions/4713088/how-to-use-git-bisect#4714297) to find out when things started to fail.

> It bounds the object, just different view points.

Can you clarify this a little bit better?

It's also good idea to also provide your specific data with the Pringles can you're using. One never knows...

**Comment by manhha1402** [comment]
I'm not able to upload the .pcd file of the Pringles cloud that I am using, screenshot from command "pcl_viewer" in linux 
![pringle](https://user-images.githubusercontent.com/20105284/34951212-d3ffbb5e-fa15-11e7-82e9-7edde681f062.png)
I will check with git bisect later

**Comment by taketwo** [comment]
Zip your PCD file and Github will accept it.

**Comment by manhha1402** [comment]
I had a new computer and don't need to visualize bounding box anymore, quite lazy to try git bisect. Hopefully no one get same problem ....

**Comment by lesterlo** [comment]
Seems the addCube function of the PCL_Visualizer use ["actor->GetProperty ()->SetRepresentationToSurface();"](https://github.com/PointCloudLibrary/pcl/blob/39732f5a7c8455ed51fd0f6278d8b25322a68dd9/visualization/src/pcl_visualizer.cpp#L2240)
rather than
["actor->GetProperty ()->SetRepresentationToWireframe ();"](https://github.com/PointCloudLibrary/pcl/blob/0ddf11a6ad1175b6f1c253da003de20c1295cde0/visualization/src/pcl_visualizer.cpp#L2187) since pcl 1.8.0.

To solve this problem, you need to edit the object properties of your bounding box to wireframe representation.
```
viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, id);
```
Reference:
http://www.pcl-users.org/Use-addCube-to-draw-a-bounding-box-td4042466.html
