### ISSUE TITLE
Distortion in point cloud after large translation with transformPointCloud

### ISSUE THREAD

**Issue by msy22** [PointCloudLibrary/pcl#2176]
## Your Environment

* Operating System and version: Ubuntu 14.04
* Compiler: Cmake/catkin (I'm using PCL with ROS)
* PCL Version: 1.7.2

## Expected Behavior
When multiplying a point cloud by a transformation matrix using the function `transformPointCloud` I would expect the cloud to remain relatively unchanged apart from the translation and rotation.

## Current Behavior
When transforming a cloud by a matrix that has a very large translation, the points in the transformed cloud become discretized into vertical silos (see the images below).

The level of distortion is roughly proportional to the translation, so doing the translation in smaller steps produces (ultimately) the same level of distortion. This happens regardless of the rotation, i.e. the effect is the same if there is a large rotation or none.

Example: 
![sliced_point_cloud](https://user-images.githubusercontent.com/17462459/34595648-872c06c2-f23e-11e7-833b-9a50cf1288a1.png)

Close up:
![voxelgrid_filtering](https://user-images.githubusercontent.com/17462459/34595659-968099bc-f23e-11e7-8ee6-3a467c276a9f.png)

## Possible Solution
Mathematically, there isn't any reason for this, so I assume that the cause is either incorrect syntax on my part or something to do with the PCL implementation.

## Code to Reproduce
    Eigen::Matrix4d transform = Eigen::Matrix4d::Identity();
    transform(0,3) = 628491.633455433;
    transform(1,3) = 5177405.903295546; 
    transform(2,3) = 28.536; 

    pcl::transformPointCloud(*cloud, *transformed_cloud, transform);

Where the original and transformed clouds are of the type `pcl::PointCloud<pcl::PointXYZ>`

## Context
I'm trying to transform a point cloud from being relative to the sensor, to global UTM coordinates (the translation basically the UTM coordinates of the sensor).

**Comment by taketwo** [comment]
Point coordinates in PCL are stored in 32-bit floating point numbers and thus have only 6-8 decimal digits of precision. Even though your transform matrix has double precision, the result of the transformation is stored back in single precision and the least significant digits are lost. That's exactly why you see vertical silos.

**Comment by msy22** [comment]
Ah, I see. Thanks for the quick answer! 

So does this essentially mean then that PCL point clouds can't have large _and_ accurate XYZ values? I.e. is there a work-around to achieve both?

**Comment by taketwo** [comment]
Not really, PCL is inherently single precision. As a workaround I would suggest to work with "demeaned" point clouds, thus maintaining precision.

**Comment by msy22** [comment]
I've spent the afternoon looking into a double-based point type, but it looks like there will be lots of challenges and compatibility issues, so I'll go with your suggestion of demeaning the clouds.

Thanks again for your help!
