### ISSUE TITLE
Highly Inaccurate behavior of RANSAC.

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#2183]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Windows7
* Compiler:C++ (Visual Studio 2015) 
* PCL Version: 1.8.1

## Expected Behavior
Seeing the floor segmented from the overall stream. 

## Current Behavior
No detection of floor and keeps detection partial walls in each frame. 

## Possible Solution
I was wondering if changing the distance threshold or max iterations has something to do with it, since those are the only two variables I can manipulate. 

## Code to Reproduce
	´pcl::SACSegmentation<pcl::PointXYZ> seg;
	pcl::PointIndices::Ptr inliers(new pcl::PointIndices);
	pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients);
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_plane(new pcl::PointCloud<pcl::PointXYZ>());		
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_objects(new pcl::PointCloud<pcl::PointXYZ>);
	seg.setOptimizeCoefficients(true);
	seg.setModelType(pcl::SACMODEL_PLANE);
	seg.setMethodType(pcl::SAC_RANSAC);
	seg.setMaxIterations(200);
	seg.setDistanceThreshold(0.2f);´

## Context
I am trying to run a PCAP File from an HDL-64E velodyne sensor through RANSAC Algorithm and trying to segment the floor from the rest of the objects. Not only is it highly inaccurate so far, but also almost never recognising the ground. Whatever little segmentation happens, it happens on partial parts of the walls only. I wonder if the problem is with the filter or with the data. How should I proceed to solve this problem?

**Comment by SergioRAgostinho** [comment]
You already opened  #2094 with the same topic. I asked a number of questions there and provided some ideas for you to try.
