### ISSUE TITLE
pcl_visualization_debug.lib not included in ${PCL_LIBRARIES} under Windows

### ISSUE THREAD

**Issue by DaveTheTroll** [PointCloudLibrary/pcl#2186]
I have followed (a slightly adapted) the PCL visualization tutorial. 

My CMakeLists.txt contains the standard line 

    target_link_libraries(cloud_viewer ${PCL_LIBRARIES}) 

But when I build I get an unresolved external for various pcl::visualization 
items. 

Adding the following fixes this 

    target_link_libraries(cloud_viewer debug pcl_visualization_debug.lib) 
    target_link_libraries(cloud_viewer optimized pcl_visualization_release.lib) 

So, I have my solution.  But I would like to understand why these libraries 
are not included as part of PCL_LIBRARIES.  i.e. why the unmodified tutorial 
code does not work for me. 

I think I have this code working previously under Ubuntu (that set up no 
longer easily available to check). 
I am now using Visual Studio 2017 under Windows 10.  Compiling for x64. 
i.e. using cmake -A x64 .. 

## Your Environment
* Operating System and version: Windows 10
* Compiler:  Visual Studio 2017
* PCL Version: 1.8.1

## Expected Behavior
All PCL libraries to be included when targeting ${PCL_LIBRARIES}

## Current Behavior
pcl_visualization_debug.lib not linked.

## Code to Reproduce
Follow CloudViewer tutorial under specified environment.
http://pointclouds.org/documentation/tutorials/cloud_viewer.php#cloud-viewer

## Context
Had to include additional library on one OS when not needed on another.

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen

**Comment by UnaNancyOwen** [comment]
Are you using "PCL 1.8.1 tag" or "PCL master/HEAD"?
Please try to use <code>-G</code> instead of <code>-A</code>.
```
cmake -G "Visual Studio 15 2017 Win64" ..
```

**Comment by niranjanreddy891** [comment]
@DaveTheTroll, you haven't included pcl_visualization library in your project.
Go to project properties and include your library. I think this will work

**Comment by DaveTheTroll** [comment]
@niranjanreddy891 That's what the target_link_libraries(cloud_viewer debug pcl_visualization_debug.lib) lines in cmake do.  Adding a library in project properties would just be a different way of doing the same thing - i.e. doing it outside cmake - one step even further from the original include.

This issue is about the fact that the target_link_libraries(cloud_viewer ${PCL_LIBRARIES}) should have already included this library, so the additional target_link_libraries should be unnecessary.

I already have **a** work around.

**Comment by DaveTheTroll** [comment]
@UnaNancyOwen I'm using 1.8.1 (only just seen this comment - I did not get a notification).

**Comment by UnaNancyOwen** [comment]
>Please try to use -G instead of -A.
> cmake -G "Visual Studio 15 2017 Win64" ..

@DaveTheTroll Could you try it and report? It is working correctly on my environment.

**Comment by DaveTheTroll** [comment]
@UnaNancyOwen 

Without
  target_link_libraries(cloud_viewer debug pcl_visualization_debug.lib) 
  target_link_libraries(cloud_viewer optimized pcl_visualization_release.lib)

I still get unresolved externals for the CloudViewer and PCL Visualizer classes.

**Comment by UnaNancyOwen** [comment]
@DaveTheTroll Hmmm, It feel strange. Please upload CMakeCache.txt.

**Comment by DaveTheTroll** [comment]
Uploaded.
Also uploaded my CMakeList.txt (which I notice I hadn't previously)

[CMakeCache.txt](https://github.com/PointCloudLibrary/pcl/files/1781179/CMakeCache.txt)
[CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/files/1781180/CMakeLists.txt)

**Comment by UnaNancyOwen** [comment]
@DaveTheTroll Your CMakeLists.txt feel strange.
That is not CMakeLists.txt of [tutorial](http://pointclouds.org/documentation/tutorials/cloud_viewer.php#cloud-viewer) that you indicated.
First of all, Please check the operation using that tutorial, and report.

BTW, I think your result that the visualization library is not included is correct.
Because, It is not specify visualization to find_pacakge in your CMakeLists.txt.
```patch
- find_package(PCL 1.8 REQUIRED COMPONENTS common io)
+ find_package(PCL 1.8 REQUIRED COMPONENTS common io visualization)
```

**Comment by DaveTheTroll** [comment]
Apologies.
Not sure at what point the COMPONENTS part was added.

Your change works.
It also works if, like the original tutorial, the COMPONENTS argument is removed all together (presumably that includes all components).
``
find_package(PCL 1.8 REQUIRED)
``

I don't have the system to try it at the moment, but I'm fairly sure that this behaved differently under Linux and Windows.  But since I can't test it now, I guess I can't be sure.

Thank you very much for your assistance.
