### ISSUE TITLE
Compiling PCL in Windows

### ISSUE THREAD

**Issue by kavinat** [PointCloudLibrary/pcl#2187]
:warning: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

Having trouble with compiling PCL

## Your Environment

* Operating System and version: Windows 10
* Compiler: VS 2015 Community C++
* PCL Version: 1.8.1

## Current Behavior
Compiling through cmake and using it on projects

## Possible Solution
a cmake file for boost 

## Context
I am trying to compile PCL on my system for personal use but when I follow the instructions written on the PCL website I am not able to build the Boost library since its source code does not have a CMakeLists file. What should I do to fic this? If there a Cmake file floating on the internet that I can use?

**Comment by SergioRAgostinho** [comment]
:warning: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning:
