### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by v4hn** [PointCloudLibrary/pcl#2189]
The latest release of PCL (1.8.1) does not support VTK 8.1.
Support for it was added in #2112 in December.

It would be great to see a released version that supports current VTK.
I'm sure many other things changed/improved too since last August.

**Comment by SergioRAgostinho** [comment]
My idea was to have a release in the first quarter of this year, but in reality only when [these](https://github.com/PointCloudLibrary/pcl/milestone/4) are done.

**Comment by taketwo** [comment]
Do we need all of these in the next release? Can as well re-target some for 1.10, especially the stale ones. I'd be in favor of shipping a new version within next couple of months.

**Comment by SergioRAgostinho** [comment]
I think i removed all of the stale ones from the milestone. I left ones in which we're missing a review, aka the authors are active but it's in our backlog.
