### ISSUE TITLE
SampleConsensusModelParallelPlane won't detect parallel planes

### ISSUE THREAD

**Issue by ejones172** [PointCloudLibrary/pcl#2194]
At its core, SampleConsensusModelParallelPlane tries to verify a plane in isModelValid using the dot product of the detected plane and the desired plane normal.  The dot product will be 1 for perfectly aligned vectors and 0 for perfectly perpendicular ones (or more generally, the dot product is the cosine of the angle between them).  Therefore, to check for parallel planes the code should be something like this:

```
if (fabs (axis.dot (coeff)) < cos_angle_)
    return false

return true;
```

But what the code actually does is this (around line 104 of sac_model_parallel_plane.hpp):
```
if (fabs (axis.dot (coeff)) > sin_angle_)
    return  (false);

return true;
```
This will only find planes nearly perpendicular to the one you're looking for.  As a simple example, if the angle tolerance is 5&deg;, cos(5&deg;) = 0.996 and sin(5&deg;) = 0.087.  For two perfectly aligned vectors, A * B = 1 which in my suggested version would make isModelValid return true (1 >= 0.996) but for the current version returns false (1 > 0.087).  The reverse is true for two perpendicular vectors.

What's really odd about this though is that looking at the history of this file the code used to be correct until commit 07292a7aaafdfe37325ddc41cd7e51ff12e4213a which explicitly mentions that SampleConsensusModelParallelPlane was detecting perpendicular planes, not parallel ones so ironically this commit appears to introduce the very bug it claims to fix.

At any rate, I fixed it locally for my project and I'd be happy to provide a pull request but given the strange history I wanted make sure there was consensus that this is the right fix.

**Comment by mvieth** [comment]
The parallel-plane-model checks if the plane itself (not the plane normal) is parallel to the specified axis. E.g. all walls in a room would be parallel to the axis (0, 0, 1). Equivalently, the detected plane _normal_  has to be _perpendicular_ to the specified axis. So in my understanding, the current version is correct.
The perpendicular-plane-model on the other hand checks if the detected plane normal is _parallel_ to the specified axis.

**Comment by ejones172** [comment]
Ah, yeah if the intent is to check for the plane itself being parallel to the axis then I agree the current version is correct.  However, that behavior seems pretty counter-intuitive to me and it looks like the surface-normal-aware version of this model (SampleConsensusModelNormalParallelPlane) uses the "plane normal is parallel to axis" definition so it looks like I'm not the only one who was confused!

**Comment by mvieth** [comment]
Yes, that is really inconsistent and confused me as well. Perhaps the documentation should make this clearer. Maybe I can make a PR for that.
