### ISSUE TITLE
How to load  and visualize .ply file

### ISSUE THREAD

**Issue by yonelay11** [PointCloudLibrary/pcl#2196]
I already had a .ply file that are generated by openMVG. I want to use this .ply file on PCL for visualization. This is my code..
`#include <iostream>
using namespace std;
#include <pcl/io/ply_io.h>									// for loading ply from incremental SfM
#include <pcl/point_types.h>
#include <pcl/visualization/cloud_viewer.h>					// for visualization
int main(int argc, char** argv)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::io::loadPLYFile<pcl::PointXYZ>("cloud_and_poses.ply", *cloud);
	pcl::PLYReader reader;
	reader.read("Path of the PLY file", *cloud);
	cout << "Loaded " << cloud->width * cloud->height
		<< " data points from cloud_and_poses.ply with the following fields: "
		<< endl << endl;

	for (size_t i = 0; i < cloud->points.size(); ++i)
		cout << "   " << cloud->points[i].x
		<< "   " << cloud->points[i].y
		<< "   " << cloud->points[i].z << endl;

	pcl::visualization::CloudViewer viewer("Incremental SfM for stpus");
	viewer.showCloud(cloud);
	while (!viewer.wasStopped())
	{

	}
	return 0;
}` 
and they show these results. I don't know how to visualize .ply file on Point Cloud Library(PCL). Please help me and I'm a new to this library.
![o1](https://user-images.githubusercontent.com/34397817/35479953-c23d3bca-043e-11e8-88e7-e55f56ec5a8b.png)
![02](https://user-images.githubusercontent.com/34397817/35479955-c929040a-043e-11e8-8293-ee69475c5023.png)

I know this is not the issues and it is a question. But, I can't register on the pcl mailing lists. So, I ask this question here. Sorry for my inconvenience.

**Comment by SergioRAgostinho** [comment]
:warning: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning:

**Comment by SergioRAgostinho** [comment]
For the mailing list problem, write me an email to sergio (dot) r (dot) agostinho (at) gmail (dot) com.
