### ISSUE TITLE
Qt  pcl example problem

### ISSUE THREAD

**Issue by TamimB** [PointCloudLibrary/pcl#2200]
When trying to build the example in the following link an error occurs without any error messages
[http://pointclouds.org/documentation/tutorials/qt_visualizer.php#qt-visualizer](url)

The result is as shown :
![qtvisulaizer](https://user-images.githubusercontent.com/35996725/35621381-d103c25a-068c-11e8-9f2e-a77f8d666f5b.PNG)

I got the files from here
[https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources/qt_visualizer](url)

Using windows 10 x64 
Visual studio community 2015
Qt 5.7
PCL 1.8.1 All-in-one Installer MSVC2015 x64 from the following link: 
[https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.8.1/PCL-1.8.1-AllInOne-msvc2015-win64.exe](url)

The main goal of what I'm doing is to add a pcl cube,then bound it with vtkBoxWidget2  and interact with it(move,scale.rotate....) in Qt but with no success so far......I thought of trying the official  example and editing it a little

**Comment by UnaNancyOwen** [comment]
The pre-built PCL included in PCL All-in-one Installer has Qt option disabled.
If you want to use PCL with Qt GUI, You need to build PCL and 3rdParty from source code yourself.

**Comment by SergioRAgostinho** [comment]
@TamimB This is a bug tracker where we track the library's bugs and pull requests. At this stage and given the report you provided us, it's very likely (to not say certain) that this is not a PCL bug, but simply you having trouble getting all your requirements to work.

With that in mind, I would ask to move this conversation to the user mailling list, where it's more suited to take place.

**Comment by bilalNet** [comment]
I has the same problem, after i used the compiled source code the sample is working well.
Thanks a lot @UnaNancyOwen
