### ISSUE TITLE
Trying to build PCL with boost 1.66, get build error

### ISSUE THREAD

**Issue by TheToadAlly** [PointCloudLibrary/pcl#2201]
Hello I am trying to build PCL 1.8.0.

I am on ubuntu 16.01, I installed boost 1.66 (because before I was trying with boost 1.58 but I was running into this "core dumped" error, so I decided to update boost).

I get a lot of warnings during the build, dunno exactly if they are the reasons for the failure. It seems some have to deal with VTK, but I installed it correctly. Here is a snapshot of the make output : 

```
[ 24%] Linking CXX executable ../../bin/pcl_pcd_introduce_nan
../../lib/libpcl_io.so.1.8.0: undefined reference to `boost::this_thread::hidden::sleep_until_realtime(timespec const&)'
collect2: error: ld returned 1 exit status
io/tools/CMakeFiles/pcl_pcd_introduce_nan.dir/build.make:229: recipe for target 'bin/pcl_pcd_introduce_nan' failed
make[2]: *** [bin/pcl_pcd_introduce_nan] Error 1
CMakeFiles/Makefile2:418: recipe for target 'io/tools/CMakeFiles/pcl_pcd_introduce_nan.dir/all' failed
make[1]: *** [io/tools/CMakeFiles/pcl_pcd_introduce_nan.dir/all] Error 2
[ 24%] Building CXX object surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/factor.cpp.o
[ 25%] Building CXX object surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/geometry.cpp.o
[ 25%] Building CXX object surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/marching_cubes_poisson.cpp.o
[ 26%] Linking CXX executable ../../bin/pcl_convert_pcd_ascii_binary
../../lib/libpcl_io.so.1.8.0: undefined reference to `boost::this_thread::hidden::sleep_until_realtime(timespec const&)'
collect2: error: ld returned 1 exit status
io/tools/CMakeFiles/pcl_convert_pcd_ascii_binary.dir/build.make:229: recipe for target 'bin/pcl_convert_pcd_ascii_binary' failed
make[2]: *** [bin/pcl_convert_pcd_ascii_binary] Error 1
CMakeFiles/Makefile2:457: recipe for target 'io/tools/CMakeFiles/pcl_convert_pcd_ascii_binary.dir/all' failed
make[1]: *** [io/tools/CMakeFiles/pcl_convert_pcd_ascii_binary.dir/all] Error 2
[ 26%] Linking CXX shared library ../lib/libpcl_sample_consensus.so
[ 26%] Linking CXX shared library ../lib/libpcl_surface.so
[ 26%] Built target pcl_sample_consensus
[ 26%] Built target pcl_surface
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SergioRAgostinho** [comment]
Is this problem affecting the current master branch? I'm asking because I just built pcl, with that exact version of boost on different platform.

**Comment by SergioRAgostinho** [comment]
I don't think this is relevant in this case but there seems to was an upstream issue with cmake and boost 1.66, to be fixed in cmake 3.11.  See https://gitlab.kitware.com/cmake/cmake/merge_requests/1625. It might be better in your case to migrate to boost 1.65 for the time being.

**Comment by ejaz-izy** [comment]
I had exactly the same issue. I was using boost 1.66 with cmake 3.11 on OS X. Compiling against an older version of boost (boost-1.58) worked.

**Comment by SergioRAgostinho** [comment]
Did you try the HEAD version of cmake? Basically `brew install cmake --HEAD'. I just want to rule out that this was actually a cmake problem and not something from our side.

**Comment by yatbear** [comment]
@SergioRAgostinho Hi, I had the exact same error. I'm on Ubuntu 16.04 and using boost 1.5.8. I tried the HEAD version of cmake but it didn't work. 

My cmake output:
`-- Using CPU native flags for SSE optimization:  -march=native
-- -- GCC > 4.3 found, enabling -Wabi
-- Found OpenMP_C: -fopenmp
-- Found OpenMP_CXX: -fopenmp
-- Found OpenMP: TRUE
-- Found OpenMP
-- Eigen found (include: /usr/include/eigen3, version: 3.2.92)
-- Checking for module 'flann>=1.7.0'
--   No package 'flann' found
-- FLANN found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libflann_cpp.so;debug;/usr/lib/x86_64-linux-gnu/libflann_cpp.so)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- QHULL found (include: /usr/include, lib: optimized;/usr/lib/x86_64-linux-gnu/libqhull.so;debug;/usr/lib/x86_64-linux-gnu/libqhull.so)
-- Found CUDA Toolkit v8.0
-- CUDA NVCC target flags: -gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_20,code=sm_21;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61
-- VTK_MAJOR_VERSION 9, rendering backend: OpenGL2
-- VTK found (include: /usr/local/include/vtk-9.0, lib: vtksys;vtkCommonCore;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkCommonDataModel;vtkCommonColor;vtkCommonExecutionModel;vtkCommonComputationalGeometry;vtkFiltersCore;vtkFiltersGeneral;vtkImagingCore;vtkImagingFourier;vtkFiltersStatistics;vtkFiltersExtraction;vtkInfovisCore;vtkFiltersGeometry;vtkFiltersSources;vtkRenderingCore;vtkzlib;vtkfreetype;vtkRenderingFreeType;vtkRenderingContext2D;vtkChartsCore;vtklz4;vtklzma;vtkIOCore;vtkIOLegacy;vtkexpat;vtkIOXMLParser;vtkIOXML;vtklibxml2;vtkIOInfovis;vtkglew;vtkRenderingOpenGL2;vtkRenderingContextOpenGL2;vtkDICOMParser;vtkmetaio;vtkjpeg;vtkpng;vtktiff;vtkIOImage;vtkTestingRendering;vtkImagingSources;vtkFiltersHybrid;vtkFiltersModeling;vtkImagingColor;vtkImagingGeneral;vtkImagingHybrid;vtkInteractionStyle;vtkRenderingAnnotation;vtkRenderingVolume;vtkInteractionWidgets;vtkViewsCore;vtkViewsContext2D;vtkFiltersProgrammable;verdict;vtkFiltersVerdict;vtkFiltersGeneric;vtkIOGeometry;vtkTestingGenericBridge;vtkDomainsChemistry;vtkDomainsChemistryOpenGL2;vtkParallelCore;vtkFiltersAMR;vtkhdf5_src;vtkhdf5_hl_src;vtkIOAMR;vtknetcdf;vtkexodusII;vtkIOExodus;vtkImagingMath;vtkRenderingVolumeOpenGL2;vtkFiltersFlowPaths;vtkFiltersImaging;vtkRenderingLabel;vtkFiltersHyperTree;vtkImagingStencil;vtkFiltersParallel;vtkFiltersParallelImaging;vtkFiltersPoints;vtkFiltersSMP;vtkFiltersSelection;vtknetcdfcpp;vtkIONetCDF;vtkjsoncpp;vtkIOParallel;vtkFiltersTexture;vtkFiltersTopology;vtkGUISupportQt;vtksqlite;vtkIOSQL;vtkGUISupportQtSQL;vtkInfovisLayout;vtkproj4;vtkGeovisCore;vtkIOEnSight;vtkgl2ps;vtkRenderingGL2PSOpenGL2;vtklibharu;vtkIOExport;vtkIOExportOpenGL2;vtkInteractionImage;vtkIOImport;vtkIOLSDyna;vtkIOMINC;vtkogg;vtktheora;vtkIOMovie;vtkIOPLY;vtkIOParallelXML;vtkTestingIOSQL;vtkIOTecplotTable;vtkIOVideo;vtkImagingStatistics;vtkRenderingImage;vtkImagingMorphological;vtkRenderingLOD;vtkRenderingQt;vtkViewsInfovis;vtkViewsQt
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   date_time
--   iostreams
--   system
--   chrono
--   atomic
--   regex
-- PCL_EXAMPLES_SUBDIRS /home/yating/dependencies/pcl-trunk/examples/common/;/home/yating/dependencies/pcl-trunk/examples/features/;/home/yating/dependencies/pcl-trunk/examples/filters/;/home/yating/dependencies/pcl-trunk/examples/geometry/;/home/yating/dependencies/pcl-trunk/examples/keypoints/;/home/yating/dependencies/pcl-trunk/examples/outofcore/;/home/yating/dependencies/pcl-trunk/examples/segmentation/;/home/yating/dependencies/pcl-trunk/examples/stereo/;/home/yating/dependencies/pcl-trunk/examples/surface/
-- Found Glew: /usr/lib/x86_64-linux-gnu/libGLEW.so
-- DOXYGEN_FOUND
-- HTML_HELP_COMPILER
-- Found CPack generators: DEB
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   visualization
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   outofcore
--   examples
--   gpu_containers
--   gpu_utils
--   gpu_octree
--   gpu_features
--   gpu_segmentation
--   people
--   tools
-- The following subsystems will not be built:
--   apps: No reason
--   gpu_kinfu: OpenNI was not found or was disabled by the user.
--   gpu_kinfu_large_scale: OpenNI was not found or was disabled by the user.
--   gpu_people: Disabled by default.
--   gpu_surface: Disabled by default.
--   gpu_tracking: Disabled by default.
--   simulation: Disabled by default.
--   global_tests: No reason
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yating/dependencies/pcl-trunk/build`

**Comment by SergioRAgostinho** [comment]
@yatbear  We're discussing a problem with Cmake introduced in Boost 1.66 due to some restructuring of Boost's modules. Your problem is something else.

**Comment by TheToadAlly** [comment]
In the end I moved to Ubuntu 17.10 that naturally support a boost version above 1.58.

**Comment by yatbear** [comment]
I reinstalled Ubuntu 16.04 and was able to build as well.
