### ISSUE TITLE
 PCLVisualizer::updatePointCloud crashes if color_handler.getColor (scalars) returns false.

### ISSUE THREAD

**Issue by DominionSoftware** [PointCloudLibrary/pcl#2206]
In pcl_visualizer.hpp, the return from color_handler.getColor() is ignored
## Your Environment

* Operating System and version: Windows 10
* Compiler: VS 2015
* PCL Version: 1.8

## Context

I'm trying to color each point. If there is not sufficient memory, my handler returns false.

If the color handler fails to allocate the scalars, the colors should be white (or some other color), rather than crashing
## Expected Behavior

Above

Above
## Current Behavior

Above

Above
## Code to Reproduce

Create a color handler that returns false from getColor(scalars).

**Comment by taketwo** [comment]
Hi, thanks for reporting. I did not reproduce the error, but I guess the fix is straightforward, please give a try.
