### ISSUE TITLE
Request for iOS framework build (arm64, no VES or VTK)

### ISSUE THREAD

**Issue by RudyAramayo** [PointCloudLibrary/pcl#2227]
Please help, scenekit can vend 3d coordinates and the voxel grid filter will be superb for the job of taking all those points and keeping the batched filtered version... its basically letting us do some basic 3d model scanning for large landscapes of points and ARKit would just love some PCL!

I have no earthly clue how to get started with the port for arm64 devices. The current scope of stuff is just 1 step behind. Can you please help provide some insight to build this for the latest arm64? The whole community would love to dive into the ARKit->ARFrame->rawFeaturePoints that are vended as 3d coordinates... HELP

## Your Environment

* Operating System and version: iOS 11.0 and above and arm64
* Compiler: xcode clang 9.0
* PCL Version: latest 1.8.1

## Context

ARKit is something the entire community would love to use with PCL

Please help me compile for ARM64 iOS devices

## Code to Reproduce

Here is some scenekit code to help you along printing the 3d coordinates of the ARKit scene:

#pragma mark - ARSCNViewDelegate

- (void)session:(ARSession *)session didUpdateFrame:(ARFrame *)frame
{
    ARPointCloud * pointCloud = frame.rawFeaturePoints;
    if (pointCloud)
    {
        
        for (int i=0; i < [pointCloud count]; i++)
        {
            vector_float3 point = pointCloud.points[i];
            NSLog(@"point%i   %f,%f,%f", i, point[0], point[1], point[2]);
        }
    }
    
}

**Comment by SergioRAgostinho** [comment]
There's way too many exclamation marks on that title 😅 

What you request takes time to figure out and I don't believe current maintainers had the need to do it before. I know there are some people in the community who needed it before but no one reported a successful case so far. The most I can do is register this issue as a request and let's see how popular it gets. Be advised there's also hardware requirements involved in order to test things.

**Comment by RudyAramayo** [comment]
Thanks for responding so quickly, looking forward to the progress

**Comment by SergioRAgostinho** [comment]
You should also ask around the user mailing list for success cases. Maybe someone is willing to share their experience upon request.

**Comment by qrasmont** [comment]
Does anyone know of an existing IOS framework equivalent to PCL ?

**Comment by kunaltyagi** [comment]
I'd recommend not using VTK to get core PCL up and running. PCL compiles with FLANN, Eigen and QHull for arm.

PR for improving PCL visualization are welcome
