### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jamessergeant** [PointCloudLibrary/pcl#2228]
https://github.com/PointCloudLibrary/pcl/blob/e84fdcded81a937d31b45ff51a740b10fe169db0/gpu/octree/src/cuda/octree_iterator.hpp#L121

**Comment by SergioRAgostinho** [comment]
Good catch. This is actually more than a typo, because it affects the logic of the algorithm.

@luzpaz how did this one get past the grep/search?

**Comment by luzpaz** [comment]
I think `codespell` doesn't regex for `--` or `++`. Will look in to it. In the meantime I'll be adding this to #2217 Thanks!
