### ISSUE TITLE
a typo in the gpu version of octree_iterator.hpp

### ISSUE THREAD

**Issue by julesmorel** [PointCloudLibrary/pcl#2232]
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:1.8.1-dev

## Context

in the file gpu/octree/src/cuda/octree_iterator.hpp (line 120), the identifier "lenght" should be changed to "length"

**Comment by SergioRAgostinho** [comment]
It was fixed by #2217. Thanks for reporting.
