### ISSUE TITLE
PCL 1.8 installation process fails because it can't find QtGui/QWidget

### ISSUE THREAD

**Issue by msy22** [PointCloudLibrary/pcl#2233]
## Your Environment

* Operating System and version: Ubuntu 14.04
* Compiler: Cmake/catkin (I'm using PCL with ROS)
* PCL Version: 1.7.2
* Qt Version: Both qt4 and qt5 are installed. 

## Context

I'm trying to install PCL 1.8. The default installation instructions for PCL in Ubuntu [(here)](http://pointclouds.org/downloads/linux.html) only install version 1.7.2. So I'm trying to install version 1.8 by following [these instructions](https://github.com/hsean/Capstone-44-Object-Segmentation/wiki/PCL-1.8:-Ubuntu-14.04-Installation-Guide). However, the installation suffers a fatal error when trying to find QtGui/QWidget, as shown by the error message below.

This is despite the fact that I have both qt4 and qt5 installed, and both have a file label `QWidget` present in the `/usr/include/qtX/QtGui/` folder. So the file clearly exists, the installation process just can't find it.

I have followed the StackOverflow answer [here](https://stackoverflow.com/questions/30770696/c-compilation-of-a-program-fatal-error-qtgui-qwidget-h-no-such-file-or-dir) and added `INCLUDE_DIRECTORIES("/usr/include/qt4/")` (or equivalent for qt5) to the first CMakeLists.txt file in the root `/pcl` folder. I've also tried adding this line to the CMakeList.txt file in `pcl/registration` as that seems to be the module the installation process is making when this error occurs. However, this doesn't work and the installation still fails. 

I'm trying to get PCL 1.8 installed so I can resolve another issue [described here](https://github.com/PointCloudLibrary/pcl/issues/2231)

## Expected Behavior
I expect the installation to succeed.

## Current Behavior
The installation fails when running `make` at the following point:

    [ 84%] Building CXX object apps/CMakeFiles/pcl_manual_registration.dir/include/pcl/apps/moc_manual_registration.cpp.o
    In file included from /home/matt/pcl/release/apps/ui_manual_registration.h:26:0,
                     from /home/matt/pcl/release/apps/include/pcl/apps/../../../../../apps/include/pcl/apps/manual_registration.h:37,
                     from /home/matt/pcl/release/apps/include/pcl/apps/moc_manual_registration.cpp:9:
    /usr/include/vtk-5.8/QVTKWidget.h:40:25: fatal error: QtGui/QWidget: No such file or directory
     #include <QtGui/QWidget>
                         ^
    compilation terminated.
    make[2]: *** 
    [apps/CMakeFiles/pcl_manual_registration.dir/include/pcl/apps/moc_manual_registration.cpp.o] Error 1
    make[1]: *** [apps/CMakeFiles/pcl_manual_registration.dir/all] Error 2
    make: *** [all] Error 2

## Possible Solution
I just need to point the installation process to the correct file, I just don't know where to put the necessary `include_directories` line.

**Comment by lesterlo** [comment]
I think the qt4 and qt5 have conflict together. You need to select either qt4 and qt5 that compile with PCL.

**Comment by taketwo** [comment]
Very quick fix which will allow you to move forward: disable building apps by passing `-DBUILD_apps=OFF` to `cmake` while configuring.

But to solve this properly, please post the output of:

* `$ dpkg -l | grep -i qt`
* `$ dpkg -l | grep -i vtk`
* `$ cmake .. -LA | grep PCL_QT_VERSION` (run inside your PCL build directory)

**Comment by msy22** [comment]
@lesterlo Thanks for the suggestion, I'll look into it.

@taketwo I've put the outputs into .txt files to make them more manageable:

[qt_grep_output.txt](https://github.com/PointCloudLibrary/pcl/files/1768745/qt_grep_output.txt)
[vtk_grep_output.txt](https://github.com/PointCloudLibrary/pcl/files/1768747/vtk_grep_output.txt)
[cmake_grep_output.txt](https://github.com/PointCloudLibrary/pcl/files/1768760/cmake_grep_output.txt)

**Comment by msy22** [comment]
So, adding `-DBUILD_apps=OFF` to `cmake` got everything installed (eventually) and seems to have successfully bypassed whatever was generating that "QWidget" error.  But I did get this warning when compiling my project:

    CMake Warning at baseline_model_correction/CMakeLists.txt:55 (add_executable):
      Cannot generate a safe linker search path for target interactive_icp
      because files in some directories may conflict with libraries in implicit
      directories:

    link library [libpcl_common.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_kdtree.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_octree.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_search.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_sample_consensus.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_filters.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_features.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_segmentation.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_io.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_surface.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_registration.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_recognition.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_keypoints.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_visualization.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_people.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_tracking.so] in /usr/lib may be hidden by files in:
      /usr/local/lib
    link library [libpcl_outofcore.so] in /usr/lib may be hidden by files in:
      /usr/local/lib

      Some of these libraries may not be found correctly.

Is this warning something I should be concerned about?

**Comment by taketwo** [comment]
Given that you have `libvtk5-qt4-dev` package installed, I think you should configure PCL to use Qt4. You can do this by passing `-DPCL_QT_VERSION=4` when running `cmake`.

@SergioRAgostinho On one hand, it would be nice to have this version swtich happen automatically. On the other hand, this is an outdated environment and I'd rather drop Qt4 and VTK5 support in foreseeable future.

Regarding the new warnings, yes, this is bad. Can you post the complete CMakeLists.txt of your project?

**Comment by msy22** [comment]
I'll try compiling with qt4 

As for my CMakeList.txt, it is:

    cmake_minimum_required(VERSION 2.8.3)
    project(baseline_model_correction)

    set(Boost_DEBUG 1)

    find_package(PCL 1.8 REQUIRED)
    find_package(catkin REQUIRED COMPONENTS
      roscpp
      rospy
      std_msgs
      sensor_msgs
      pcl_ros
      pcl_conversions
      roslaunch
    )

    catkin_package()
    include_directories(include ${catkin_INCLUDE_DIRS} ${PCL_INCLUDE_DIRS} )
    link_directories(${PCL_LIBRARY_DIRS})
    add_definitions(${PCL_DEFINTIONS})

    add_executable(pointcloud_broadcaster src/pointcloud_broadcaster.cpp)
    target_link_libraries(pointcloud_broadcaster ${PCL_LIBRARIES} ${catkin_LIBRARIES})
    ...
    # Remainder of file is repeats of above two lines for each file.

**Comment by taketwo** [comment]
Sorry, I overlooked the fact that you are using PCL with ROS. Your package depends on `pcl_ros` and `pcl_conversions`, both of which are compiled with system PCL, thus it is implicitly linked into your node. But your self-built 1.8 is also linked in, which is recipe for troubles.

**Comment by msy22** [comment]
I'll need to do some more tests, but I think that compiling PCL 1.8 with `qt4` stops the "Cannot generate a safe linker" warning.

**Comment by SergioRAgostinho** [comment]
> @SergioRAgostinho On one hand, it would be nice to have this version swtich happen automatically. On the other hand, this is an outdated environment and I'd rather drop Qt4 and VTK5 support in foreseeable future.

@taketwo  You proposed this before. I'm game with it 👍 

> As long as the error message above won't stop the program from compiling and running, that will have to be good enough.

@msy22 Don't be surprised if you have random segfaults down the road with no apparent reason behind them.

> The first time I tried building and compiling PCL 1.8 I had cloned the git repo into `/home/matt/pcl/`. I complied PCL from this directory but didn't install it. I then decided to delete it and try everything again with the repo cloned to `/usr/include/pcl-1.8/pcl/` (from which I then compiled and installed it) Is it possible that compiling PCL 1.8 from the first `home` directory could have left residual files in `/usr/local/`? 

No. You would need to invoke `sudo make install` for it to even be able to write on that folder.

I have 0 experience with ROS but given the information you provided I don't believe this to be a PCL bug, just a very messy development environment. As such, from my side this issue can be closed.

**Comment by taketwo** [comment]
For other people with the same environment reading this thread, the solution is to pass `-DPCL_QT_VERSION=4` to CMake.

**Comment by msy22** [comment]
> given the information you provided I don't believe this to be a PCL bug, just a very messy development environment

I think that's exactly the case. My dev environment is chaotic just because I'm using so many different open source libraries, and because I've repeatedly broken then fixed it trying to get everything working. So I really doubt it's a problem with PCL.

Regarding a solution, adding `-DBUILD_apps=OFF` may also be necessary to bypass the original "QWidget" error. 

Thanks to everyone for your help, I really appreciate it.
