### ISSUE TITLE
SSE flags being unconditionally exported

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2239]
A followup on https://github.com/PointCloudLibrary/pcl/pull/2100#issuecomment-368822323

> @SergioRAgostinho I think I've just caught a subtle bug in this PR which would only manifest later on when 1.9.0 is packaged and shipped to users via `apt-get`. Pay attention to [this if statement](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L111). Our `SSE_FLAGS` are appended to `CMAKE_CXX_FLAGS` only if they are empty. When they are **not empty** (which is the case for debian packaging builds), SSE flags are not appended. Yet they are still unconditionally exported to our CMake config. As a result, we have a problem which is sort of the reverse of what we are solving here: PCL deb package is built without `march=native` (for obvious reason), but configure script adds this flag to dependee projects.

**Comment by SergioRAgostinho** [comment]
@taketwo I just tried to replicate this and I couldn't.

I compiled PCL passing `-DCMAKE_CXX_FLAGS="-O2"` then created a downstream target passing no flags whatsoever. The SSE flags are not being added.

**Comment by taketwo** [comment]
Did you test #2100 branch or current master?

**Comment by SergioRAgostinho** [comment]
Current master branch.

**Comment by taketwo** [comment]
Sorry, but I do not understand what you mean by "SSE flags are not being added".

**Comment by SergioRAgostinho** [comment]
> Sorry, but I do not understand what you mean by "SSE flags are not being added".

When compiling my downstream target, the compiler was not being called with `-march=native`, `-msse4.2` and `-mfpmath=sse`.

**Comment by taketwo** [comment]
If you configure PCL passing -`DCMAKE_CXX_FLAGS="-O2"`, then PCL is compiled without any architecture flags. However, inside generated `PCLConfig.cmake` you will find:

```cmake
list(APPEND PCL_DEFINITIONS " -march=native -msse4.2 -mfpmath=sse ")
```

Thus downstream user who cared to append these definitions will compile with native architecture.

**Comment by taketwo** [comment]
> When compiling my downstream target, the compiler was not being called with 

Well yes, exported compiler flags are not appended to downstream targets automatically, this is one of the issues we are addressing in #2100.
