### ISSUE TITLE
getting segment fault when using segmentation fault error when using pcl::SampleConsensusPrerejective

### ISSUE THREAD

**Issue by muhammadaly** [PointCloudLibrary/pcl#2240]
I'm using pcl::SampleConsensusPrerejective class in order to estimate transformation between two points clous with ORB feature vectors stored in pcl::Histogram<32> object I don't know exactly what is the problem I have check all the inputs for registration object and it is all fine

**Comment by taketwo** [comment]
This is an issue tracker, use our mailing list for questions: www.pcl-users.org.
