### ISSUE TITLE
I am facing this issue while building in visualstudio 2013. 

### ISSUE THREAD

**Issue by niranjanreddy891** [PointCloudLibrary/pcl#2242]
I followed this tutorial from here [http://www.pointclouds.org/documentation/tutorials/openni_grabber.php#openni-grabber](url)
![This is my issue](https://user-images.githubusercontent.com/33854825/36970102-673646a2-208d-11e8-9603-e5c3939258f8.png)

I am using win-7 64bit
OpenNI2
Please solve this issue.

**Comment by SergioRAgostinho** [comment]
WARNING: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org.

Go to the page you linked. Press ctrl+F and type `OpenNI2Grabber`. How many results does it return? 0. You modified to the tutorial.

**Comment by niranjanreddy891** [comment]
I have figured out the error. Now everything is working fine. Thanks @SergioRAgostinho
