### ISSUE TITLE
Need help: pcl installation stops at "==>make".

### ISSUE THREAD

**Issue by Solarbird2017** [PointCloudLibrary/pcl#2249]
## Your Environment

* Operating System and version: MacOS High Sierra (version 10.13.3)
I have installed Xcode (version 9.2) and python 2.7.13_1 on my Mac.

I tried to install pcl with the command: _$ brew install pcl_
But, the installation process stops at "==>make"

I got the following information after running the command _"$ brew install pcl"_

_==> Installing dependencies for pcl: gcc, szip, hdf5, flann, glew, qhull, jpeg, libtiff, netcdf, vtk
==> Installing pcl dependency: gcc
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
Already downloaded: /Users/Nick/Library/Caches/Homebrew/gcc-7.3.0.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e0ee09389a54cc4c8fe1c24ebca3cd765ed0ba/gcc/6.1.0-jit.pa
Already downloaded: /Users/Nick/Library/Caches/Homebrew/gcc--patch-863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/df0465c02a/gcc/apfs.patch
Already downloaded: /Users/Nick/Library/Caches/Homebrew/gcc--patch-f7772a6ba73f44a6b378e4fe3548e0284f48ae2d02c701df1be93780c1607074.patch
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> Applying apfs.patch
patching file libstdc++-v3/include/Makefile.in
Hunk #1 succeeded at 1763 (offset -1 lines).
==> ../configure --build=x86_64-apple-darwin17.4.0 --prefix=/usr/local/Cellar/gcc/7.3.0 --libdir=/usr/local/Cellar/gcc/7.3.0/lib/gcc
==> make_

Then, no response even I wait for a long time. I guess the version of my MacOS is too high, but not sure about that. 

Thank you for any suggestion in advance.

**Comment by SergioRAgostinho** [comment]
1. PCL takes a long time to compile so just go cook a meal and come back later
2. We're not responsible for the Homebrew distribution. For issues with Homebrew you should file a bug at https://github.com/Homebrew/homebrew-core
