### ISSUE TITLE
"No devices connected" when debug projet with PCL MSVC2010

### ISSUE THREAD

**Issue by fannkid** [PointCloudLibrary/pcl#2254]
mailing list for questions: www.pcl-users.org. 

I am trying to use the Point Cloud Library with Visual Studio. I downloaded the all-in-one 64 bit installer, Visual Studio 10 and installed them. I create a sample project with Cmake, it can run without error but “No devices connected” althouth my computer recognize Primesense camile in Devices Manager

##  Environment

* Operating System and version: Windows 10 64bit
* Compiler:Visual Studio 2010
* PCL Version:1.60

**Comment by SergioRAgostinho** [comment]
You were already warned once that questions of this nature are to be posed in the users mailing list. This makes it twice.

**Comment by fannkid** [comment]
what can i do? i am a newbie
