### ISSUE TITLE
Fix SSE flags for Clang / AppleClang and Cross Compile

### ISSUE THREAD

**Issue by svenevs** [PointCloudLibrary/pcl#2256]
1. Addition of `-march=native` is currently skipped for all clang.
2. Cross compiling should never include `-march=native` for any compiler, currently only excluded for GCC.

Will fix after #2100.  (Assign to: @svenevs) :smile:

**Comment by SergioRAgostinho** [comment]
@svenevs You can fire up the "oven" for this one. #2100 should be merged soon. :+1:

**Comment by svenevs** [comment]
Oven is at temperature ;)

**Comment by SergioRAgostinho** [comment]
I went ahead of myself and actually submitted the PR #2416 as you can see :sweat_smile: . Can you review (last commit only) just to guaranteed I covered all points you mentioned in this Issue?

**Comment by svenevs** [comment]
Ok I'll take a closer look this weekend when I'm back at a Linux box. From the other PR it sounded like you all are pushing for more modern cmake. Generally speaking, tinkering with `CMAKE_CXX_FLAGS` is discouraged in favor of doing _everything_ target based (`target_compile_{features,options}`). It keeps things cleaner / makes the targets easier to export assuming you're doing `PUBLIC|PRIVATE|INTERFACE` appropriately.

You can also then safely use the `CheckCXXCompilerFlag` module (still guarded underneath checks for cross compiling in this specific case). That makes it so you don't need to worry about clang vs AppleClang vs gcc. You could also then check `-xHost` for Intel without actually needing to check the compiler ids.

Anyway I'll provide feedback on the PR validating when I can check on both Linux and OSX this weekend. I don't really have time to help with a more thorough removal of `CMAKE_CXX_FLAGS` but I can definitely check the PR adds the flags for clang so they get in there for what sounds like an imminent release :smile:
