### ISSUE TITLE
 undefined reference to `pcl::gpu::EuclideanClusterExtraction::extract(std::vector<pcl::PointIndices, std::allocator<pcl::PointIndices> >&)

### ISSUE THREAD

**Issue by arnasIV** [PointCloudLibrary/pcl#2258]
I am trying to compile a simple snippet of code that uses GPU version of EuclideanClusterExtraction. I have seen other people talking about this issue on forums, but nobody has presented a solution so far.

## Your Environment

* Operating System and version: Ubuntu 16.04 LTS
* Compiler: GNU 5.4.0
* PCL Version: 1.8.1
* CUDA 8.0

## Expected Behavior
The code should compile and link without any error

## Current Behavior
I cannot compile the code when I add this line:  gec.extract(clusterIndices);
I get the following error:

`undefined reference to `pcl::gpu::EuclideanClusterExtraction::extract(std::vector<pcl::PointIndices, std::allocator<pcl::PointIndices> >&)`

## Code to Reproduce
```
#include <pcl/gpu/octree/octree.hpp>
#include <pcl/io/pcd_io.h>
#include <pcl/gpu/segmentation/gpu_extract_clusters.h>

int main (const int argc, const char** const argv)
{
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile(argv[1], *cloud);

  std::cout << "Point Cloud Info:\n"
            << "height: " << cloud->height
            << " width: " << cloud->width
            << std::endl;
	pcl::gpu::Octree::PointCloud cloud_device;
	cloud_device.upload(cloud->points);
	pcl::gpu::Octree::Ptr octree_device;
	octree_device->setCloud(cloud_device);
	octree_device->build();
  pcl::gpu::EuclideanClusterExtraction gec;
  gec.setClusterTolerance(0.01);
  gec.setMinClusterSize(100);
  gec.setSearchMethod(octree_device);
  gec.setHostCloud(cloud);
  std::vector<pcl::PointIndices> clusterIndices;
  gec.extract(clusterIndices);
  
  return 0;
}
```

```
cmake_minimum_required(VERSION 3.0.0 FATAL_ERROR)
project(gpu_octree VERSION 0.1.0 LANGUAGES CXX)

find_package(PCL 1.8.1 REQUIRED)

add_executable (${PROJECT_NAME} "${PROJECT_NAME}.cpp")
target_include_directories(${PROJECT_NAME} PUBLIC ${PCL_INCLUDE_DIRS})
target_link_libraries (${PROJECT_NAME} ${PCL_LIBRARIES})
```

**Comment by arnasIV** [comment]
#include "pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp" was missing.

**Comment by jamessergeant** [comment]
@arnasIV I'm having the same issue, but your solution doesn't seem to work for me. When I use `#include "pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp"` I instead get a multiple definition error. Did you happen to come across this at all?

**Comment by uzkata** [comment]
Not really. Could you show me the exact errors your are getting?
It was missing in  a header of my template class. Now I have both includedd:

```
#include <pcl/gpu/segmentation/gpu_extract_clusters.h>
#include <pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp>
```

Did you try compiling the segmentation example?
[](https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/segmentation/src/seg.cpp)
You might be having this issue because your are not using it in a class, but it is not a template.

**Comment by jamessergeant** [comment]
I think the fact that it isn't a template is what is causing me issues. Looking at a work around now.

**Comment by jamessergeant** [comment]
I modified it to be a template class (for PointXYZ only), does the trick.

**Comment by btknzn** [comment]
If you have the solution, could you please let me know...

**Comment by shrini-mm** [comment]
I am facing this problem in PCL 1.10. Could you please let me know if the problem is fixed. If so, what is the solution? Thanks.
