### ISSUE TITLE
Build latest PCL with - VTK 8.1, Qt5.9.3, boost 1.66

### ISSUE THREAD

**Issue by eti-nne** [PointCloudLibrary/pcl#2260]
## Your Environment
* Operating System and version:
Win10 - 64 bits (10.0.16299)
* Compiler:
MSVC 2015 (14.0)
* PCL Version:
1.8.1 or latest (on master)

## Context
I tried to use the visualizer provided by VTK 8.1 (I think it's the same as VTK 8.0) with latest PCL. 
So this is a build issue
Differents version : 
Qt 5.9.3
VTK 8.1
boost 1.66

## Expected Behavior
It should build :) Those are all the last version of the main libs. pcl should be compatible with those. 
If there is a trick in the cmake to make it build with this setup (a specific flag or something), it should be automated somehow. 

## Current Behavior
There is a boost issue on multiple files, in the pcl_io component : 
path/to/boost_1_66_0/boost/interprocess/detail/os_thread_functions.hpp(509): error C3861: '_beginthreadex' : identifier not found

I managed to reproduce the issue on another setup., so it's not personal support. 

## Possible Solution
No idea. 

I googled it, and found some forum solutions. I tried them, but it didn't make trick  : 
For instance https://stackoverflow.com/questions/27230258/error-c3861-beginthreadex-identifier-not-found

**Comment by taketwo** [comment]
#2201 reported problems with the same version of Boost.

**Comment by taketwo** [comment]
Closing this since there seem to be a working workaround and since this in unlikely to be a PCL problem anyway.
