### ISSUE TITLE
 invalid use of incomplete type ‘class vtkTexture’

### ISSUE THREAD

**Issue by benglasstone** [PointCloudLibrary/pcl#2263]
## Your Environment

* Operating System and version: Linux Mint 18.3
* Compiler: gcc-5.4
* PCL Version: master

## Current Behavior

While trying to compile PCL I am getting the errors:

/home/benjamin/dev/PCL/pcl/visualization/src/pcl_visualizer.cpp: In member function ‘bool pcl::visualization::PCLVisualizer::addTextureMesh(const pcl::TextureMesh&, const string&, int)’:
/home/benjamin/dev/PCL/pcl/visualization/src/pcl_visualizer.cpp:3535:16: error: invalid use of incomplete type ‘class vtkTexture’
         texture->SetBlendingMode(vtkTexture::VTK_TEXTURE_BLENDING_MODE_REPLACE);
                ^
In file included from /usr/local/include/vtk-9.0/vtkTextActor.h:39:0,
                 from /home/benjamin/dev/PCL/pcl/visualization/src/pcl_visualizer.cpp:42:
/usr/local/include/vtk-9.0/vtkTexturedActor2D.h:34:7: note: forward declaration of ‘class vtkTexture’
 class vtkTexture;

I am currently running vtk-9.0.

**Comment by benglasstone** [comment]
Fixed by switching to vtk-8.1.

**Comment by taketwo** [comment]
Apparently an include for `vtkTexture` is required for VTK 9. I think you can solve the problem by adding:

```cpp
#include <vtkTexture>
```

to `pcl_visualizer.cpp`.
