### ISSUE TITLE
inherit.hpp can't have access to "private struct"

### ISSUE THREAD

**Issue by BroadDong** [PointCloudLibrary/pcl#2264]
Hi, I am coming the problem.The soft is PCL-1.8.1-AllInOne-msvc2017-win64. Please tell me the solution as soon as possible! Thank you very much!
![image](https://user-images.githubusercontent.com/20699811/37885724-73499694-30e9-11e8-9cbf-5502ffa0ce92.png)

**Comment by taketwo** [comment]
This is a bug tracker, not a support forum. Please use pcl-users mailing list for such questions.
