### ISSUE TITLE
cannot find people_detect application after build pcl

### ISSUE THREAD

**Issue by chiaho903** [PointCloudLibrary/pcl#2277]
## Your Environment

* Operating System and version: ubuntu 16.04
* Compiler: ccmake 3.5.1
* PCL Version: 1.8.1

## Context

Hi, I was trying to run the example on the pcl [tutorial/gpu/detect people](http://www.pointclouds.org/documentation/tutorials/gpu_people.php#gpu-people). I expect that it will be built after cmake the whole pcl  repository, my ccmake options is shown below:

![image](https://user-images.githubusercontent.com/31883845/38599771-5b2d067e-3d94-11e8-9337-1199d50b48dc.png)

I already turn on the BUILD_GPU and BUILD_GPU_PEOPLE, but even after I run `make` and `make install` successfully, I can't find an executable file name people_detect in the bin folder.

I also find the original code in `doc/tutorials/content/sources/gpu/people_detect` and try to build it, but I got the error message:
`fatal error: pcl/gpu/people/include/pcl/gpu/people/people_detector.h: No such file or directory`
I think maybe the reference include file is misplaced, but I still can't make the people_detect file executable.

**Comment by libaosuan** [comment]
I am so sorry to ask the question. Please tell me how to compile the source code in Ubuntu 16.04? I was trying to compile for two days.Do you have the installation process.Thank you!!

**Comment by libaosuan** [comment]
Thanks. I have installed the PCL.

**Comment by dhgokul** [comment]
Me too having same issue, people_detect executable file is not generated after enable BUILD_GPU ,BUILD_CUDA and BUILD_PEOPLE options .

Any help appreciated !

**Comment by dhgokul** [comment]
Thanks for review, Please let me know how to sort out this issue !

**Comment by chiaho903** [comment]
hi @dhgokul I solved this problem by enabling the WITH_VTK option, then go to build the `people_detect.cpp` in the tutorial folder. 
I think its because the people_detect needs something from VTK, and the files in tutorial folder won't be build in the general cmake.

**Comment by dhgokul** [comment]
Hi Chiah,

Thanks for your response, I have enabled option  WITH_VTK - ON (vtk-6.2), still not able to generated people binary. If you have ccmake configuration screen shot. Please share with me. will validate once

Thanks,
Gokul

**Comment by chiaho903** [comment]
@dhgokul this is my ccmake list for pcl, 
![ccmake1](https://user-images.githubusercontent.com/31883845/39570112-d9cb740e-4ef9-11e8-9990-f3e39e9e4aa0.png)
![ccmake2](https://user-images.githubusercontent.com/31883845/39570113-d9f5fb70-4ef9-11e8-9ad6-593d92be70e0.png)
![ccmake3](https://user-images.githubusercontent.com/31883845/39570114-da23030e-4ef9-11e8-9853-7c604a8346f5.png)
![ccmake4](https://user-images.githubusercontent.com/31883845/39570115-da4fe9aa-4ef9-11e8-9a41-12ad15b90b8b.png)
![ccmake5](https://user-images.githubusercontent.com/31883845/39570116-da7e9e12-4ef9-11e8-9f51-586ee51e3c64.png)
![ccmake6](https://user-images.githubusercontent.com/31883845/39570117-daac0bc2-4ef9-11e8-99bf-38f20985b3aa.png)

And here is the ccmake list for people_detect, 
![people_detect_ccmake](https://user-images.githubusercontent.com/31883845/39570135-eb6efe2e-4ef9-11e8-98e8-0e61a939ec19.png)

**Comment by dhgokul** [comment]
Chia,
Thanks for sharing screen-shot, it really helped me lot . In my build i am not able to see BUILD_gpu_* (example : BUILD_gpu_people) options . Any changes need to be done ?

**Comment by chiaho903** [comment]
@dhgokul in my `ccmake` I just press [t] to get in advanced mode, maybe you should try install `ccmake`, it's the GUI for `cmake`, the usage is the same as `cmake`.

**Comment by dhgokul** [comment]
Thanks chia. Now, I'm able to enable BUILD_gpu_people = ON.

Now, facing different issue like CUDA version issue as follows,
I have cuda 9.0 version only, but still it shows CMake error with cuda version 

**Error details :** 
```
   CMake Error at gpu/people/CMakeLists.txt:24 (if):
   if given arguments:

     "9.0" "VERSION_GREATER_EQUAL" "9.0"

   Unknown arguments specified
```

I have tried changing version in CMakeLists.txt file like 8.0, 9.0 and 9.1. But, it always shows the same error. Please let me know, anything missing here.

**Comment by smihael** [comment]
Which version of CMake are you using?

VERSION_GREATER_EQUAL logic is available only since CMake v3.7, whereas Ubuntu 16.04 ships only with v3.5.

**Comment by dhgokul** [comment]
@smihael Thanks ! will check

**Comment by SergioRAgostinho** [comment]
Based on this [comment](https://github.com/PointCloudLibrary/pcl/issues/2277#issuecomment-386517362) seems like we're not respecting the minimum required cmake version for the project. Regarding the application install location we'll still need to look into it.

**Comment by anujgpatil** [comment]
> Based on this [comment](https://github.com/PointCloudLibrary/pcl/issues/2277#issuecomment-386517362) seems like we're not respecting the minimum required cmake version for the project. Regarding the application install location we'll still need to look into it.

In my CMakeLists
`cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
`
My CMake version:
`cmake version 3.5.2`

Still getting the same error.
![1650](https://user-images.githubusercontent.com/29145342/68384945-bf95e400-017e-11ea-8076-bf7e822d9bdd.png)
*Any resolutions?*

**Comment by anujgpatil** [comment]
https://github.com/PointCloudLibrary/pcl/issues/3459#issue-520053311

Fixed it!!
