### ISSUE TITLE
unresolved external symbol class Matrix4*4 point coud library

### ISSUE THREAD

**Issue by nimashafiei** [PointCloudLibrary/pcl#2280]
## Your Environment

* Operating System and version: widows 10 
* Compiler: Visual studio 2015
* PCL Version: 1.81

## Context
I'm trying to load a pcd file using pcl library, I do and show it using cloud viewer but I'm trying to use PCLVisualizer. When I use addPointCloud function I have an error:

> Severity Code Description Project File Line Suppression State Error LNK2019 unresolved external symbol "public: static class vtkMatrix4x4 * __cdecl vtkMatrix4x4::New(void)" (?New@vtkMatrix4x4@@SAPEAV1@XZ) referenced in function "public: static class vtkSmartPointer __cdecl vtkSmartPointer::New(void)" (?New@?$vtkSmartPointer@VvtkMatrix4x4@@@@SA?AV1@XZ) SamplePCL C:\Users\Nima_S_H\Documents\Visual Studio 2015\Projects\SamplePCL\SamplePCL\Source.obj 1 

## Code to Reproduce

	`#define _CRT_SECURE_NO_DEPRECATE
	#define _CRT_SECURE_NO_WARNINGS
	#define _HAS_ITERATOR_DEBUGGING  0
	#define _ITERATOR_DEBUG_LEVEL  0
	#include <pcl/point_cloud.h>
	#include <pcl/point_types.h>
	#include <pcl/io/pcd_io.h>
	#include <pcl/visualization/pcl_visualizer.h>
	void main()
	{
	pcl::PointCloud<pcl::PointXYZ>::Ptr myCloudPtr(new pcl::PointCloud<pcl::PointXYZ>);
	if (pcl::io::loadPCDFile("e:/myCloudASCII.pcd", *myCloudPtr) == -1)
	{
		PCL_ERROR("Could not read PCD file.");
		return;
	}
	pcl::visualization::PCLVisualizer viz;
	viz.addPointCloud(myCloudPtr, "");
	viz.spin();

	}`

**Comment by nimashafiei** [comment]
anybody can't help me?

**Comment by kunaltyagi** [comment]
You're not linking the transitive dependencies. Use CMake to automate that. Not an issue in PCL-core.
