### ISSUE TITLE
Can't find the headers

### ISSUE THREAD

**Issue by libaosuan** [PointCloudLibrary/pcl#2283]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc
* PCL Version: 1.8.1

## Context
I complied the source code to install PCL. In the /usr/include ,there exists the pcl-1.8 folder. But when I compile the cpp procedure,it can not find the header file. I hope the problem can be solved.
I know the reason.For example ,when I change the #include <pcl/PCLHeader.h> into #include <pcl1.8/pcl/PCLHeader.h>,the sentence will not error.But there are too more header files to modify.

**Comment by taketwo** [comment]
WARNING: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org.
