### ISSUE TITLE
GASD signature not available for nearest neighbor search using pcl::search::KdTree

### ISSUE THREAD

**Issue by AchimG** [PointCloudLibrary/pcl#2290]
The GASD signatures are not available when using pcl::search::KdTree for nearest neighbor search.

## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* PCL Version: master branch

## Context

When working with the GASD global descriptor, a nearest neighbor search has to be performed in the descriptor space. However, using the current version of pcl::search::KdTree leads to compilation errors since KdTree has not been specialized for the GASD signatures.

## Possible Solution

Add the GASD features to the point types which are used to specify KdTree during pre-compiling.

**Comment by taketwo** [comment]
Quick fix: include "impl" file for KdTree in your code.

But actually this is a bug. `pcl::search::KdTree` is instantiated for all point types listed in [`PCL_POINT_TYPES`](https://github.com/PointCloudLibrary/pcl/blob/9084aec8cdd4bc040f24193b5a767d8dfe153299/common/include/pcl/impl/point_types.hpp#L50) macro list. This list does not include GASD descriptors, although it should. You are welcome to send a patch adding them to the list. (Also update `PCL_FEATURE_POINT_TYPES` list for completeness.)

**Comment by AchimG** [comment]
Thanks for the fast reply.

I will work on this and send a patch in the next days.

**Comment by taketwo** [comment]
Fixed with #2295.
