### ISSUE TITLE
cmake and MSVC wrong libraries of VTK linked when using RelWithDebInfo configuration

### ISSUE THREAD

**Issue by Arrowana** [PointCloudLibrary/pcl#2293]
## Your Environment

* Operating System and version: Windows 10 Enterprise 1703
* Compiler: MSVC Visual Studio 14 2015 Win64
* PCL Version: 1.8.1 release, AllInOne installer PCL-1.8.1-AllInOne-msvc2015-win64.exe

## Context
I am trying to build my own project with the build configuration RelWithDebInfo linking PCL_VISUALIZATION_LIBRARIES
I previously worked only in debug mode but I need to be able to build in RelWithDebInfo configuration

## Expected Behavior
Compilation with RelWithDebInfo configuration works

## Current Behavior
When selecting the configuration RelWithDebInfo and compiling, it tries to link the wrong library for VTK, resulting in thousands of lines highlighting the mismatch between the C++ runtime used in the project and the VTK libraries C++runtime:

  vtkRenderingOpenGL-8.0-gd.lib(vtkOpenGLScalarsToColorsPainter.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in pcl_visualizer_demo.obj [C:\Users\Arrowana\bug\build\pcl_vi sualizer_demo.vcxproj]
  vtkRenderingOpenGL-8.0-gd.lib(vtkOpenGLScalarsToColorsPainter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in pcl_visualizer_demo.obj [C:\Users\Arrowana\bug\build\pcl_visualizer_demo.vcxproj]
  vtkRenderingOpenGL-8.0-gd.lib(vtkOpenGLTexture.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in pcl_visualizer_demo.obj [C:\Users\Arrowana\bug\build\pcl_visualizer_demo.v cxproj]
  vtkRenderingOpenGL-8.0-gd.lib(vtkOpenGLTexture.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in pcl_visualizer_demo.obj [C:\Users\Arrowana\bug\bui ld\pcl_visualizer_demo.vcxproj]

## Code to Reproduce
Using the source files of the tutorial:
http://pointclouds.org/documentation/tutorials/pcl_visualizer.php

cmake --version
cmake version 3.7.0-rc2

Preparing Visual studio solution through cmake
mkdir build
cd build
cmake.exe .. -G "Visual Studio 14 2015 Win64"

All good:
msbuild.exe pcl_visualizer_viewports.sln /property:Configuration=Debug

Results in wrong library being linked, then mismatch in C++ runtime:
msbuild.exe pcl_visualizer_viewports.sln /property:Configuration=RelWithDebInfo

## Possible Solution
One workaround I use is to rename VTKTargets-debug.cmake so VTK cmake files won't find it.
Then only release libraries exists when linking is happening

It seems like the relation between RelWithDebInfo and Release mode is broken, probably something to fix in the PCL cmake files for a proper workaround or directly into the VTK third party library

**Comment by Arrowana** [comment]
Copying and pasting VTKTargets-release.cmake and renaming all release to relwithdebinfo works (in filename + in file).
So RelWithDebInfo build configuration is missing from VTK, only debug and release are available by default

Should CI build in all available configurations, CI for windows was only added way after 1.8.1 release though:
https://github.com/PointCloudLibrary/pcl/blob/master/.appveyor.yml#L5

**Comment by kunaltyagi** [comment]
Closing since the issue is actually with upstream library (and setup) not providing RelWithDebInfo
