### ISSUE TITLE
Eigen segfault in MarchingCubes::createSurface

### ISSUE THREAD

**Issue by horia-bogdan** [PointCloudLibrary/pcl#2294]
## Your Environment

* Operating System and version: Linux Mint 18.3 Cinnamon 64-bit
* Compiler: gcc (-std=c++1y)
* PCL Version: latest (cloned from github)

## Context

I am trying to reconstruct a mesh using marching cubes.

## Current Behavior

A segfault happens in createSurface(). Here is the stack trace:
![segfault](https://user-images.githubusercontent.com/888077/39473280-efb4d234-4d45-11e8-8330-d5b3bed4d090.png)

There are two distinct ways in which the problem appears:
1. Error when allocating an std::vector of Eigen objects, when using the Eigen::aligned allocator

/surface/impl/marching_cubes.hpp, line 105
`std::vector<Eigen::Vector3f, Eigen::aligned_allocator<Eigen::Vector3f> > p;`
Works when replaced with 
`std::vector<Eigen::Vector3f> p;`

and /surface/impl/marching_cubes.hpp line 123
`std::vector<Eigen::Vector3f, Eigen::aligned_allocator<Eigen::Vector3f> > vertex_list;`
Works when replaced with
`std::vector<Eigen::Vector3f> vertex_list;`

I am aware that using the Eigen::aligned_allocator is recommended by Eigen, and having the same kind of declarations in my code, rather than the pcl code, does not seem to cause any crashes.

2. Error when PointNTs are added to the PointClouds

/surface/impl/marching_cubes.hpp, lines 155, 157, 159

This does not happen instantly, but after a series of calls to createSurface. I did not count how many. I think this is because of the memory preallocation in performRconstruction:

/surface/impl/marching_cubes.hpp lines 253, 254
`double size_reserve = std::min((double) intermediate_cloud.points.max_size (),
      2.0 * 6.0 * (double) (res_y_*res_z_ + res_x_*res_z_ + res_x_*res_y_));`

When this is removed, the crash happens in the first `cloud.push_back(p1)` call.

I changed these lines to:
`double size_reserve = std::min((double) intermediate_cloud.points.max_size (),
      2.0 * 6.0 * (double) grid_.size());`
as I did not understand why less memory than the grid size is preallocated (I didn't look very deeply into it). This seems to fix the problem.

While I managed to fix it to avoid the crash, there are obviously deeper problems that need to be solved.

## Code to Reproduce

'point_cloud' is some input point cloud

`std::shared_ptr<pcl::PolygonMesh> mesh;`
`mesh = std::make_shared<pcl::PolygonMesh>();`
`pcl::MarchingCubesHoppe<pcl::PointXYZRGBNormal> mc;`
`mc.setGridResolution(30,30,30);`
`mc.setInputCloud(point_cloud);`
`mc.reconstruct(*mesh); //error here`
`pcl::io::saveOBJFile("mesh.obj", *mesh);`

**Comment by taketwo** [comment]
Hi, sorry for the late response. Are you still interested in solving this issue? If so, please post your "CMakeLists.txt".

I hypothesize that you forgot to call `add_definitions(${PCL_DEFINITIONS})`.

That said, we have recently merged #2100, which automates propagation of compiler definitions/options. Thus (if my hypothesis is righ) if you check out the very latest PCL master and try it with our project without any modifications, it should work.

**Comment by SergioRAgostinho** [comment]
Should be good now. Please reopen if needed.
