### ISSUE TITLE
why loadply can not process header with property double?

### ISSUE THREAD

**Issue by DamonsJ** [PointCloudLibrary/pcl#2301]
## Your Environment

* Operating System and version: windows10 
* Compiler: visual studio 2017
* PCL Version: 1.8.1

## Context

I want to load ply file with property double,but it gives me "failed to mathch for field ...",
why this happen? Do not PCL support double ?

ply header is like this:

ply
format ascii 1.0
comment Generated by the CGAL library
element vertex 586796
property double x
property double y
property double z
property double nx
property double ny
property double nz
end_header

**Comment by taketwo** [comment]
No, PCL does not support double fields.

WARNING: This is an issue tracker, please use our mailing list for questions in future: www.pcl-users.org.
