### ISSUE TITLE
Compilation warning: ISO C++ prohibits anonymous structs

### ISSUE THREAD

**Issue by juzzlin** [PointCloudLibrary/pcl#2303]
## Your Environment
* Operating System and version: Ubuntu 18.04 LTS
* Compiler: gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 
* PCL Version: 1.8.1

## Context
I'm compiling my code with -pedantic and GCC gives a warning of a struct in /usr/local/include/pcl-1.8/octree/octree_key.h:

    union
      {
        struct
        {
          uint32_t x;
          uint32_t y;
          uint32_t z;
        };
        uint32_t key_[3];
      };

Message: " ISO C++ prohibits anonymous structs" so I guess this is non-standard C++.

## Expected Behavior
No warnings.

## Current Behavior
Warning "ISO C++ prohibits anonymous structs"

## Code to Reproduce

    #include <pcl/octree/octree.h>
    int main() {return 0;}

Compile with -pedantic 

## Possible Solution
Don't use anonymous structs..?

**Comment by Morwenn** [comment]
Theoretically it would be possible to avoid it with an array and three reference members initialized to point to the elements of the array in order to remain strictly standard-compliant without changing the the structure API, but reference members increase the size of the class.

**Comment by kunaltyagi** [comment]
Until C++ comes with a better method for type-punning than the one in C, PCL will have to rely on this UB. Even though this is strictly a UB, all compilers we test with provide the same behavior as a C code.

Alternatives that don't increase memory size (reference) or require breaking API (using functions everywhere) are welcome. I now `memcpy` trick (copying the input into source type) is optimized out by most compilers and is the recommended method of looking into a struct, but that can't be done for data members.

There's not much that's actionable here. Sorry.

**Comment by kunaltyagi** [comment]
GCC users can disable this warning using `-fms-extensions`. Sadly, this stays for current PCL

**Comment by SergioRAgostinho** [comment]
I'm not sure this is considered UB as of C++11. The user compiled pcl 1.8.1 which is in C++03. According to cpp reference, anonymous structs are a part of the standard from C++11 onwards
https://en.cppreference.com/w/c/language/struct

> 1. Similar to union, an unnamed member of a struct whose type is a struct without name is known as anonymous struct. Every member of an anonymous struct is considered to be a member of the enclosing struct or union. This applies recursively if the enclosing struct or union is also anonymous. 
> 2. Similar to union, the behavior of the program is undefined if struct is defined without any named members (including those obtained via anonymous nested structs or unions).   

2. does not apply to us.  So the fact that we use an anonymous struct should not be UB anymore.

**Comment by Morwenn** [comment]
Using anonymous structs is legal, it's assigning to the struct members then accessing them the array which is still considered UB today.

**Comment by MattSYoung** [comment]
I've recently encountered this problem when trying to include `octree_key.h` in Ubuntu 20.04 with ROS2 and PCL 1.10. The specific error I get is:

```
/usr/include/pcl-1.10/pcl/octree/octree_key.h:155:9: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
  155 |         };
      |         ^
cc1plus: all warnings being treated as errors
``` 

I haven't yet figured out how to compile my code with `-fms-extensions` set. But so far I've tried:

1. Using `#pragma GCC diagnostic warning "-pedantic"` and similar
2. Compiling my code in C++14 

And none of those have gotten me past this compilation error. Can anyone give me more specific instructions on how to set `-fms-extensions` or another solution that fixes this issue?

**Comment by lockunkey** [comment]
> 

i too have the same issue can anyone tell me how to solve this

**Comment by ajay1606** [comment]
Hello @MattSYoung @lockunkey 
In case if you found any fix o above error, could you please share here. My case also getting same error.

```
/usr/include/pcl-1.10/pcl/octree/octree_key.h:155:9: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
  155 |         };
```

Appreciate any response.

**Comment by kunaltyagi** [comment]
I think the CMake files for you applications are wrong. They might have something like: `include_directories(${PCL_INCLUDE_DIRS})` or `include_directories(${ament_INCLUDE_DIRS})`. Please ensure PCL is considered a system library

**Comment by ajay1606** [comment]
@kunaltyagi 
Thanks for your quick response, Anyhow I tried with commenting the line `include_directories(${PCL_INCLUDE_DIRS})` But still getting the same error

```
cmake_minimum_required(VERSION 3.5)
project(pointcloud_preprocessor)

### Compile options
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)
endif()
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic -Werror)
endif()

# Ignore PCL errors in Clang
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wno-gnu-anonymous-struct -Wno-nested-anon-types)
endif()

find_package(ament_cmake_auto REQUIRED)
find_package(OpenCV REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(Boost REQUIRED)
find_package(PCL REQUIRED)
find_package(pcl_conversions REQUIRED)
find_package(OpenMP)
ament_auto_find_build_dependencies()


###########
## Build ##
###########

include_directories(
  include
  ${Boost_INCLUDE_DIRS}
  ${PCL_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
  ${GRID_MAP_INCLUDE_DIR}
)
```

Above is the actual CMake File, where am getting errors. Would you please suggest me proper configuration?

Regards,
Ajay

**Comment by kunaltyagi** [comment]
```cmake
include_directories(
  include
)
include_directories(SYSTEM
  ${Boost_INCLUDE_DIRS}
  ${PCL_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
  ${GRID_MAP_INCLUDE_DIR}
)
```

**Comment by ajay1606** [comment]
@kunaltyagi Thanks so much for your quick response
