### ISSUE TITLE
Add texture to Pointcloud

### ISSUE THREAD

**Issue by LeoSarog** [PointCloudLibrary/pcl#2304]
## Your Environment

* Operating System and version: Windows 8.1 
* Compiler: MSVC Visual Studio 2015 Win64
* PCL Version: 1.8.1

## Context
Hi, I recently started using the PCL and i am currently rendering a PointXYZ pointcloud (generated from 2D pixels and the depth stream) with the utilities of the visualizer. I was wondering how can i map a texture to this pointcloud based on an other stream, f.e. the infrared stream, assuming that i have already aligned the frames from the streams and the infrared is a grayscale frame (Unsigned with one channel).
Thanks!

**Comment by taketwo** [comment]
This is an issue tracker, please use our mailing list for questions: www.pcl-users.org.

Create a PointXYZI point cloud, iterate through the original one copying the 3d coordinates and also projecting on the texture image and picking up intensity from there.
