### ISSUE TITLE
How to remove all the files about pcl ?

### ISSUE THREAD

**Issue by zhang261007** [PointCloudLibrary/pcl#2305]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler:GCC
* PCL Version:1.8+1.7

## Context

when I use ros in pcl 1.7, it is seductive to use GPU in PCL1.8.While it makes ros down. 
Now i need to remove all of them than reload.
so, Please help to tell a way to remove all the pcl files.
Thanks!

**Comment by taketwo** [comment]
WARNING: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org.
