### ISSUE TITLE
boost interprocess file_lock fails when writing pcd files to samba share

### ISSUE THREAD

**Issue by floriankramer** [PointCloudLibrary/pcl#2306]
## Your Environment

* Operating System and version: ubuntu 16.04, kernel 4.16.2
* Compiler: gcc version 5.4.0
* PCL Version: 1.8, git rev cf45c8a7bc7440f5c1167b0718bdd02409f94dfe

## Context

We want to store a pcd file via pcl::PCDWriter::writeBinaryCompressed (or any other write function)  to a samba mount.

## Expected Behavior

Save the file without errors.

## Current Behavior

``[pcl::PCDWriter::writeBinaryCompressed] Error during write ()!`` gets thrown as an exception and the file is empty.

## Code to Reproduce

Create a samba share using the default smb.conf and adding a simple share, eg:  
```
[test]
  path = /path/to/folder/containing/a/pcd
  browseable = yes
  read only = no
  guest ok = yes 
  writeable = yes
```
Then mount the share using `sudo mount -t cifs //localhost/test /path/to/mountpoint -ouser=<sambauser>`, cd into the mountpoint and run `sudo pcl_convert_pcd_ascii_binary <in-pcd> <out-pcd> 2`. To be able to run the conversion without root permissions add `uid=<your-uid>` to the mount options.

## Possible Solution

The call to `boost::interprocess::file_lock::try_lock()` in  `pcl::PCDWriter::setLockingPermissions` in `pcd_io.cpp` causes the error. A possible solution would be to remove the file locking completely. The current implementation does not consider the lock anyways, apart from debug printing  and potentially preventing other processes using the posix file locking mechanism via `fcntl` (which is what boost uses internally) from accessing the file. Under windows the lock is created but never actually locked, as there is a `#ifndef WIN32` macro in the setLockingPermissions function. Under linux the lock is not only ignored, it is also not necessarily very useful, as there are several problems with using `fcntl` for file locking (see http://0pointer.de/blog/projects/locking.html).

In case you agree with removing the boost file locks, I can provide a PR.

**Comment by taketwo** [comment]
Sorry, I have no idea about the file locking and/or motivation of the original contributors of this feature. Have you followed the instructions regarding `mand` option (see [commit message](https://github.com/PointCloudLibrary/pcl/commit/170cb92f5bd019df153524f93a944cfe4d8e4ca7)).

**Comment by floriankramer** [comment]
I tried using the `mand` option on a local mount and the file locking worked as described. Using `mand` on a samba share does not stop the exception from occuring though.  
Samba has it's own `locking = no` option that can be added to the `smb.conf` to disable locking. Doing so prevents the exception from occuring. It is possible that the problem is not on pcl's side, but rather has something to do with samba and its `fcntl` locking support.  
A solution that allows for using pcl with samba without having to disable locking for the samba share would be adding a cmake option to disable the use of mandatory locking within pcl. That would not allow for using mandatory locking and samba, but file locking under linux seems to rarely be used anyways (and the `mand` option for mounts has it's own share of problems), so most users should not have a problem with that.

**Comment by taketwo** [comment]
As far as I can see, all the locking operations are localized in two functions, so it will easy to `#ifdef` them. So if you are interested in implementing such an option, PR is welcome.
