### ISSUE TITLE
How to disable warnings from pcl during compilation 

### ISSUE THREAD

**Issue by manhha1402** [PointCloudLibrary/pcl#2307]
## Your Environment

* Operating System and version: 16.04
* Compiler: gcc
* PCL Version: 1.8

I have just built pcl library from source, and notice that during compilation, there are many warnings from pcl([-Weffc++] ,-Wno-unused,...). How can I disable these warnings ? (maybe CMakeLists.txt or pcl ?)
Thank you
![screenshot from 2018-05-12 11-12-56](https://user-images.githubusercontent.com/20105284/39955830-2a590cdc-55d6-11e8-94e3-cf2482b0d104.png)
![warning2](https://user-images.githubusercontent.com/20105284/39955831-2b81d968-55d6-11e8-811e-782de542469b.png)
![warning3](https://user-images.githubusercontent.com/20105284/39955833-2cc7f6fe-55d6-11e8-9ebd-29e3cfd68b13.png)
![warning4](https://user-images.githubusercontent.com/20105284/39955834-2e11c42c-55d6-11e8-9d6f-0fb74e9b6e2e.png)

**Comment by taketwo** [comment]
WARNING: This is an issue tracker, please use our mailing list for questions: www.pcl-users.org.
