### ISSUE TITLE
[pcl::HDLGrabber::loadCorrectionsFile] Error reading calibration file velodyne/velodyne_pointcloud/params/32db.yaml!

### ISSUE THREAD

**Issue by szm88** [PointCloudLibrary/pcl#2312]
It can work yesterday,but when I update ,It don't work and i got error:
[pcl::HDLGrabber::loadCorrectionsFile] Error reading calibration file velodyne/velodyne_pointcloud/params/32db.yaml!

**Comment by lesterlo** [comment]
Which model of velodyne LiDAR are you using? I'm using HDL-64E S3 LiDAR and the grabber work fine on pcl-1.8.1 and pcl-1.8.0.

**Comment by taketwo** [comment]
Is this still a problem?

**Comment by taketwo** [comment]
Closing due to lack of author feedback.
