### ISSUE TITLE
How to select ROI and display in another window?

### ISSUE THREAD

**Issue by niranjanreddy891** [PointCloudLibrary/pcl#2313]
I have a pcd file, I want to select ROI and then display it in another window. How can we do this?

**Comment by taketwo** [comment]
WARNING: This is an issue tracker, not a Q&A forum. Please use our mailing list for questions: www.pcl-users.org.

**Comment by niranjanreddy891** [comment]
Sorry for asking here. But no one replied for this question in pcl-users. Can you please give me an idea on how to achieve that. :)
