### ISSUE TITLE
Installation error for pcl 1.7.2: Parse error at "BOOST_JOIN"

### ISSUE THREAD

**Issue by sanketrahul** [PointCloudLibrary/pcl#2318]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc
* PCL Version: 1.7.2

## Context

I have followed https://larrylisky.com/2014/03/03/installing-pcl-on-ubuntu/ tutorial for installation.
I have downloaded the pcl1.7.2 version from pcl website. Then I have extracted and ran makepkg command in pcl 1.7.2 folder. After that I created a folder release and inside that folder I ran following commands:
cmake -DCMAKE_BUILD_TYPE=None -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON ..
Make
After 89% of progress in the installation, I got following error:
[ 89%] Generating include/pcl/apps/moc_pcd_video_player.cxx
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
apps/CMakeFiles/pcl_pcd_video_player.dir/build.make:66: recipe for target 'apps/include/pcl/apps/moc_pcd_video_player.cxx' failed
make[2]: *** [apps/include/pcl/apps/moc_pcd_video_player.cxx] Error 1
CMakeFiles/Makefile2:6692: recipe for target 'apps/CMakeFiles/pcl_pcd_video_player.dir/all' failed
make[1]: *** [apps/CMakeFiles/pcl_pcd_video_player.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
cc: @k-okada

## Expected Behavior
 installation completion

## Current Behavior
 Parse error at 89% after running make command

**Comment by k-okada** [comment]
it works with `cmake ..; make` on my environment, see fill output ->  https://gist.github.com/k-okada/13c8a2ce1cdd6b0e75ab10b17c8333f0
So, first try with default settings and see if works. If not please upload your full output.

**Comment by taketwo** [comment]
Is there any reason you want to install this ancient version? Please try the latest release.

**Comment by taketwo** [comment]
Closing this, please re-open if you face the same issue with the latest version.
