### ISSUE TITLE
Cannot build sources / Mac OSX Sierra 10.13.4

### ISSUE THREAD

**Issue by Samsy** [PointCloudLibrary/pcl#2334]
Cannot build from sources.

Sierra 10.13.4 

![capture d ecran 2018-06-05 a 20 39 14](https://user-images.githubusercontent.com/3786958/40998729-8ae56a04-6900-11e8-8088-7f39341b1e9c.jpg)

**Comment by taketwo** [comment]
Thanks for reporting. Same problem was mentioned in [this comment](https://github.com/PointCloudLibrary/pcl/pull/2325#issuecomment-394794283). Please refer there for a temporary solution.

**Comment by Samsy** [comment]
Not only

![capture d ecran 2018-06-05 a 21 17 43](https://user-images.githubusercontent.com/3786958/41000451-e8468f0c-6905-11e8-9a37-84cd1befec75.jpg)

**Comment by Samsy** [comment]
I tried as well to compile 
pcl-1.8.1rc1 release 
pcl-1.8.0
pcl-1.8.0rc2

I've not been able to compile PCL successfully in any of them

**Comment by taketwo** [comment]
Unfortunately I don't have a Mac to test this. I do know, however, that we have Mac users and one of our maintainers used to have a Mac back when these versions were released, so they have to work (at least on older MacOS versions).

**Comment by taketwo** [comment]
The error reported in original post has been fixed by #2354. Please reopen if there are other issues.
