### ISSUE TITLE
EMSCRIPTEN EXPERIMENTAL : warning: unresolved symbol: _ZN3pcl7console5printENS0_15VERBOSITY_LEVELEPKcz

### ISSUE THREAD

**Issue by Samsy** [PointCloudLibrary/pcl#2337]
Hello there,
I'm currently working on an experimental Emscripten build so that lib can work on the web straight.

I did compiled every librairies / dependencies using emscripten before-hand.
I'm really close to get it working with webassembly.

I just got trouble figuring what this error could be : 

warning: unresolved symbol: _ZN3pcl7console5printENS0_15VERBOSITY_LEVELEPKcz

If some of you have a clue .. 

Many thanks

**Comment by taketwo** [comment]
Something weird is going on with our print functions in your environment. Looking at your previous report in #2334 I got an idea that you can try. Prepend `::` to the namespace specification in each of [these lines](https://github.com/PointCloudLibrary/pcl/blob/87d55477f351d82ca8f71e2c9b6ae4250a21b852/common/include/pcl/console/print.h#L46-L51). E.g., the first line should become:

```cpp
#define PCL_ALWAYS(...) ::pcl::console::print (::pcl::console::L_ALWAYS, __VA_ARGS__)
```

**Comment by Samsy** [comment]
Just tried !
![capture d ecran 2018-06-10 a 14 47 11](https://user-images.githubusercontent.com/3786958/41202175-2f61626c-6cbd-11e8-9889-fc6181f4e83f.jpg)

Still getting the error though !

**Comment by taketwo** [comment]
Are you still getting those compilation errors from the other issue, or is this a linker error?

**Comment by Samsy** [comment]
Only a linker error !

**Comment by taketwo** [comment]
What did you do to resolve the compiler errors?

Please give more context for the linker error (actually, the line you posted says "warning") . When exactly does it occur, what is your linker command.

**Comment by Samsy** [comment]
I got it.. Emscripten is a really weird compiler though.
I had to play a bit with format export of those static library and enable PCL_NO_PRECOMPILE for some reasons.

I successfully got a EMSCRIPTEN working in a browser build of PCL

**Comment by plusice** [comment]
@Samsy Hi~Samsy,could you show me your Emscripten build process?

**Comment by naah69** [comment]
could u share your wasm in github?

**Comment by luoxuhai** [comment]
@naah69 @plusice I built PCL using WebAssembly and now it works in the browser ✌️: https://github.com/luoxuhai/pcl.js

**Comment by naah69** [comment]
> https://github.com/luoxuhai/pcl.js

omg! 
that is great! 
thanks for your code!
