### ISSUE TITLE
Convex Hull filtering by simple bounding box

### ISSUE THREAD

**Issue by pseandersson** [PointCloudLibrary/pcl#234]
A pointcloud consist of 8 points, making up a bounding box in  3D. I wanted to select all points inside the boundingbox in another point cloud by computing a convex hull of the points and filtering the cloud by the crop hull filter in 3 dimensions. The result changed when I duplicated two points in the cloud. In both cases, approximatley one half of the points were selected.

**Comment by gtinchev** [comment]
The example by @jspricke is wrong. 
It should be:
bb_filter.setHullCloud(surface_hull);

As one should be using the points after the reconstruction.
