### ISSUE TITLE
Tracking module's particle filter incorrectly samples in rotation space

### ISSUE THREAD

**Issue by andybarry** [PointCloudLibrary/pcl#2340]
The tracking module's particle filter, when sampling in 6D space (```x, y, z, roll, pitch, yaw```) samples roll, pitch, and yaw by adding small amounts to each value.  This is incorrect, since it biases the samples towards the polls of a sphere.

Per the contribution guidelines, I'm opening this issue along with my pull request (#2339) that fixes the sampling.

**Comment by taketwo** [comment]
Typically an issue is opened before a pull request. The purpose of an issue is to gather information about a defect, keep track of it, and discuss approaches to solve it. If you provide a pull request with a solution right away, I don't see reasons to have a separate issue page.

**Comment by andybarry** [comment]
Sure, sounds good.  I'll close this.
