### ISSUE TITLE
How to use boost to read pcd file fastly?

### ISSUE THREAD

**Issue by wxt-github** [PointCloudLibrary/pcl#2342]
Hi,everyone!
I want to use the boost library to quickly read or visualize the pcd file, but I don't know how to organize the code，can anybody help?

**Comment by taketwo** [comment]
We have plenty of tutorials to get started with PCL: http://pointclouds.org/documentation/tutorials. [This one](http://pointclouds.org/documentation/tutorials/reading_pcd.php#reading-pcd) will teach you how to read PCD files, and [this one](http://pointclouds.org/documentation/tutorials/pcl_visualizer.php#pcl-visualizer) show how to use PCL Visualizer.

Please note that this is an issue tracker, it is reserved for BUG REPORTS. Please use our mailing list for questions: www.pcl-users.org.
