### ISSUE TITLE
Suggestion: To expose the found correspondences for ICP registration

### ISSUE THREAD

**Issue by Fingolfin007** [PointCloudLibrary/pcl#2345]
the process of finding the right parameters for ICP registration for a specific scene is a hard task because the found correspondences are not exposed.

**Comment by taketwo** [comment]
There is a class [`RegistrationVisualizer`](http://docs.pointclouds.org/trunk/classpcl_1_1_registration_visualizer.html#ae7d963b9d97c75df7223bcc5fe7ea4dc) that can be used debug the registration process (including visualization of found correspondences). Unfortunately we don't seem to have a good tutorial about it.
