### ISSUE TITLE
Not able to visualize range images

### ISSUE THREAD

**Issue by husong998** [PointCloudLibrary/pcl#2346]
## Your Environment

* Operating System and version: Ubuntu 16.04 LTS
* Compiler: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* PCL Version: 1.7.2-14build

## Context

I followed exactly the same steps as described in the PCL tutorial here: http://www.pointclouds.org/documentation/tutorials/range_image_visualization.php#range-image-visualization

## Expected Behavior

The code should visualize a pcd file as well as its range image as described in the link above.

## Current Behavior

The 3D viewer is functioning, but the range image viewer shows nothing but a black screen. As shown below.
![image](https://user-images.githubusercontent.com/34832485/41643399-a0935020-749d-11e8-9830-5c2f58f4c78f.png)

## Observation

I printed out all the points in the range image class, code is as follow:

`std::cout<<range_image<<endl;`
`  std::cout<<range_image.points.size()<<endl;`
`  for(int i=0; i<range_image.points.size(); i++)`
`    std::cout<<range_image.points[i].x<<" "<<range_image.points[i].y<<" "<<range_image.points[i].z<<" "<<range_image.points[i].range<<endl;`

It looks like most of the points are marked as "nan" and the range is -Inf, but some of the points have normal values. Part of the result is as follow:

`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`0.00951084 -1.43994 -0.0082128 1.44`
`-0.00177232 -1.43994 -0.0124405 1.44`
`-0.0115053 -1.44995 -0.00526637 1.45`
`-0.0106477 -1.44995 0.00683615 1.45`
`nan nan nan -inf`
`0.0106475 -1.44994 0.00683644 1.45`
`0.0115055 -1.44994 -0.00526605 1.45`
`0.00178497 -1.44994 -0.0125268 1.45`
`-0.00957666 -1.44994 -0.00827009 1.45`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`
`nan nan nan -inf`

Why does the range image viewer display black screen only?

**Comment by xiesc** [comment]
I meet the same problem.  Have you solved it?

**Comment by husong998** [comment]
> I meet the same problem. Have you solved it?

Hi, haven't solved it yet. This module seems to be unstable because when I tried it the other day it was shown normally. But became faulty agin after a while. I suspect it has something to do with the ROS integrated version.

I tried to explicitly use the 1.7 version and 1.8 version in my CMakeLists, but neither works. You may wanna give it a trial. It may work for you.

Did you subscribe to the official PCL mailing list? I cannot subscribe to it due to unknown reason. So maybe you want to post the problem there.

**Comment by PanZhichen** [comment]
Same problem...Whether it is compiled in a separate space or a ROS workspace, any suggestion? Thank u!

**Comment by khlitoshi** [comment]
Hi, 
I have exactly the same issue. any update on this ?

**Comment by husong998** [comment]
I haven't worked with this library for a long time. So I am not able to give any update on this.

**Comment by SubMishMar** [comment]
Same issue with Ubuntu 16.04 and PCL 1.7. Any leads?

**Comment by mvieth** [comment]
I tried to reproduce this but was unable to. The range image viewer always showed the image.
My best guess is that this was a problem with older VTK versions (I use VTK 9.1.0).
If anyone still has this problem, please comment here or open a new issue (with a reference to this issue).
