### ISSUE TITLE
PCL1.8.1+QT5.11.0+VTK8.0.1 error

### ISSUE THREAD

**Issue by ghost** [PointCloudLibrary/pcl#2351]
I want to use the pcl1.8.1+qt5.11.0 to display the pointcloud in the gui. I install the pcl and qt successfully, and I build the VTK8.0.1 successfully. But when I build a project including the pcl and qt in the VS2015, the following error came:
unresolved external symbol: "__declspec(dllimport) public: void __cdecl vtkDataArray::GetRange(double * const)"

## My Environment
* Win10 x64
* VS2015:
* PCL1.8.1:

the following is the code:

///header  VTKTest.h
#pragma once
#include <QtWidgets/QDialog>
#include "ui_VTKTest.h"
#define VTK_VISUAL
#ifdef VTK_VISUAL
#define NOMINMAX
//PCL Header
#include <vtkAutoInit.h> 
VTK_MODULE_INIT(vtkRenderingOpenGL2);
VTK_MODULE_INIT(vtkInteractionStyle);
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <vtkRenderWindow.h>
#endif // VTK_VISUAL
class VTKTest : public QDialog
{
    Q_OBJECT
public:
    VTKTest(QWidget *parent = Q_NULLPTR);
	void initialVtkWidget();
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud;
	boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer;
private:
    Ui::VTKTestClass ui;
};

///the source VTKTest.cpp
#include "VTKTest.h"
#include <fstream>
using namespace std;
VTKTest::VTKTest(QWidget *parent)
	: QDialog(parent)
{
	ui.setupUi(this);
	initialVtkWidget();
}
void VTKTest::initialVtkWidget()
{
	cloud.reset(new pcl::PointCloud<pcl::PointXYZ>);
	viewer.reset(new pcl::visualization::PCLVisualizer("viewer", false));
	ui.qvtkWidget->SetRenderWindow(viewer->getRenderWindow());
	viewer->setupInteractor(ui.qvtkWidget->GetInteractor(), ui.qvtkWidget->GetRenderWindow());
	viewer->addPointCloud(cloud, "cloud");
	ui.qvtkWidget->update();
}

Thank you for your answer.

**Comment by larshg** [comment]
I guess we can close this as, it seems to be a missing vtk library to be linked and if it is a bug in 1.8.1 it won't get any updates.

Also its close to 2 years old.
