### ISSUE TITLE
Error to run "Ensenso_viewer.cpp"

### ISSUE THREAD

**Issue by moncio** [PointCloudLibrary/pcl#2352]
## Your Environment
- Operating System and version: Ubuntu 16.04 LTS
- Compiler: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- PCL Version: 1.8.0
- Develop enviroment tool: Netbeans 8.2
- Camera device: Ensenso N35

## Context
I want to try the code of "[ensenso_viewer.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/tools/ensenso_viewer.cpp)". I configured the a minimal project including the necessary libraries (PCL, Boost, VTK, Ensenso SDK, Eigen and Flann) to run the sample using the connected camera.

## Expected Behavior
Displaying a point cloud grabbed from a Ensenso device.

## Current Behavior
When I run the code, I have the followed mistakes:

- In the second line of main function `viewer_ptr.reset (new CloudViewer ("Ensenso 3D cloud viewer"));` , The output reproduces next error: `enumDevices: NxLib error ItemTypeNotCompatible (13) occurred while accessing item /Cameras/BySerialNo/\0/Status`

This is the current output of the code:
![image](https://user-images.githubusercontent.com/4520583/41728484-37354270-7577-11e8-903c-386b4feb572f.png)

So, what could be the problem?

Thanks ind advance.

**Comment by taketwo** [comment]
Press "r" in the viewer to reset view. What you are seeing now is an extremely zoomed in view on the red/green/blue arrows representing coordinate system origin.

**Comment by moncio** [comment]
Thank so much!

**Comment by ZJU-PLP** [comment]
**@moncio @taketwo  I also try to run the code of "ensenso_viewer.cpp" and "ensenso_cloud_images_viewer.cpp",Howerver, I meet the erros of below:**
[ 50%] Linking CXX executable ensenso_cloud_images_viewer
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibWriteDebugMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ensenso_cloud_images_viewer.cpp:(.text+0x255): undefined reference to `nxLibWriteDebugMessage'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibGetDebugMessages()':
ensenso_cloud_images_viewer.cpp:(.text+0x2aa): undefined reference to `nxLibGetDebugMessages'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibSetDebugThreadName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ensenso_cloud_images_viewer.cpp:(.text+0x3a9): undefined reference to `nxLibSetDebugThreadName'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibInitialize(bool)':
ensenso_cloud_images_viewer.cpp:(.text+0x3f8): undefined reference to `nxLibInitialize'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibFinalize()':
ensenso_cloud_images_viewer.cpp:(.text+0x43c): undefined reference to `nxLibFinalize'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibOpenTcpPort(int, int*)':
ensenso_cloud_images_viewer.cpp:(.text+0x490): undefined reference to `nxLibOpenTcpPort'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibCloseTcpPort()':
ensenso_cloud_images_viewer.cpp:(.text+0x4d4): undefined reference to `nxLibCloseTcpPort'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `main':
ensenso_cloud_images_viewer.cpp:(.text+0xd75): undefined reference to `pcl::EnsensoGrabber::EnsensoGrabber()'
ensenso_cloud_images_viewer.cpp:(.text+0xda3): undefined reference to `pcl::EnsensoGrabber::openDevice(int)'
ensenso_cloud_images_viewer.cpp:(.text+0xdbf): undefined reference to `pcl::EnsensoGrabber::openTcpPort(int)'
ensenso_cloud_images_viewer.cpp:(.text+0xf21): undefined reference to `pcl::EnsensoGrabber::closeDevice()'
ensenso_cloud_images_viewer.cpp:(.text+0xf38): undefined reference to `pcl::EnsensoGrabber::closeTcpPort()'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `NxLibException::NxLibException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
ensenso_cloud_images_viewer.cpp:(.text._ZN14NxLibExceptionC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi[_ZN14NxLibExceptionC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi]+0x18a): undefined reference to `nxLibWriteDebugMessage'
collect2: error: ld returned 1 exit status
CMakeFiles/ensenso_cloud_images_viewer.dir/build.make:362: recipe for target 'ensenso_cloud_images_viewer' failed
make[2]: *** [ensenso_cloud_images_viewer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ensenso_cloud_images_viewer.dir/all' failed
make[1]: *** [CMakeFiles/ensenso_cloud_images_viewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Could you mind helping me solve this problem? Thanks a lot!**

**Comment by taketwo** [comment]
Please don't revive old closed issues with only vaguely related problems.
