### ISSUE TITLE
when use pcl::io::loadPCDFile in VS2015 + PCL1.8.1 ,Expression: "(_Ptr_user&(_BIG_ALLOCATION_ALIGNMENT - 1)) ==0" && 0

### ISSUE THREAD

**Issue by jackeycheng88** [PointCloudLibrary/pcl#2357]
Does anyone have a similar problem？

**Comment by taketwo** [comment]
* If you want to find out if anyone had a similar problem, please use search.
* If you want to report an issue (which is what this place is for), then please follow the issue template and provide relevant information about your environment, code and data to reproduce it, etc.

**Comment by Tsung-Yu-Hsieh** [comment]
I have the same problem!
How can I solve this issue?
