### ISSUE TITLE
PCL 1.8.1 + Cuda 8.0 + ARM64 not compiling

### ISSUE THREAD

**Issue by siquike** [PointCloudLibrary/pcl#2361]
## My Environment
* Hardware: Nvidia Jetson TX2
* Operating System and version: Ubuntu 16.04 (Jetpack 28.1/CUDA 8.0)
* Compiler: cmake v 3.10.3 /make
* PCL Version: 1.8.1

## Context
I am trying to compile PCL 1.8.1 with GPU functions enabled in an Nvidia Jetson TX2 with Jetpack 28.1 (I have also tried with Jetpack 28.2 and 28.2.1 with no success). I have tried with both CUDA 8.0 and 9.0 with no success. Please help.

## Code to Reproduce
`cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr            -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON            -DCMAKE_INSTALL_PREFIX=/usr -DCUDA_ARCH_BIN=6.2 -DCUDA_ARCH_PTX=6.2 -DCUDA_NVCC_FLAGS=-arch=sm_62 ..`

`make -j7`

## Error
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:134: recipe for target 'sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o' failed
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....

**Comment by taketwo** [comment]
Well, this looks like is a compiler error, so the bug report should go to GCC.

**Comment by barnjamin** [comment]
FWIW I got this to compile on my TX2
Ubuntu 16.04
Cuda 9.0
Cmake 3.5.1
Jetpack 28.2.1
NVCC  9.0.252
GCC 5.4.0

I did have to tweak the source in gpu/containers/src/initialization.cpp and add ```{0x62, 256},``` to the arch cores array.

I'll submit a pr with changes when I get my project to work.

**Comment by SergioRAgostinho** [comment]
The combinations of these two:
- `make -j7`
- `c++: internal compiler error: Killed (program cc1plus)`

The most common explanation is an out of memory error. Did you try reducing the number of workers to simply one?

**Comment by barnjamin** [comment]
Good point, I was using make -j4 and I added a _ton_ of swap. Can the compiler get oom killed?

**Comment by mzahana** [comment]
Hi @barnjamin. Could you please share the steps you did to get pcl working on TX2?

**Comment by SergioRAgostinho** [comment]
Invoking `make` with a smaller number of parallel jobs. Basically, the first time just run
```
$ make
```
if you don't run out of memory then feel free to increase the number of parallel jobs e.g.,  `make -j2`.
