### ISSUE TITLE
PassThough can only filter float fields

### ISSUE THREAD

**Issue by ClementLeBihan** [PointCloudLibrary/pcl#2366]
How can I filter other fields than float with the PassThough class ?

The memcpy (line 128 pcl/filters/include/pcl/filters/impl/passthrough.hpp) should have the size of the field type, and not always float ? In my case, I use uint16_t fields (own PointType), and I can't filter on this field because the memcpy take too much bytes :/

Is there any solutions except coding a new class ?

Best,
Clément

**Comment by taketwo** [comment]
You are right, `PassThrough` can only handle float fields.

> Is there any solutions except coding a new class ?

Well, passthrough filtering is essentially a for loop with condition, you don't need roll out your own class for that.

**Comment by ClementLeBihan** [comment]
Ok ! 

May be we could try to use the fields[distance_idx].datatype and an union type to make the PassThrough more robust ? :)

Best,
Clément

**Comment by taketwo** [comment]
Certainly, the filter can be improved to handle other field types. If you have interest, you are welcome to contribute a PR with extension and adequate unit test coverage.
