### ISSUE TITLE
Remove unused function arguments from OrganizedMultiPlaneSegmentation refine method

### ISSUE THREAD

**Issue by Kaju-Bubanja** [PointCloudLibrary/pcl#2370]
In the file [organized_multi_plane_segmentation](https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/organized_multi_plane_segmentation.h) the refine method has 2 unused arguments.  This is of course not a big issue, just an improvement suggestion to keep the code cleaner. Just let me know if these are not welcome or if there is a reason(interface conformance?) for the unused parameters.
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

## Possible Solution

Just removing them.

**Comment by taketwo** [comment]
We can remove them. However, we still need to keep around the old signature (with deprecation warning) to not break API.

**Comment by Kaju-Bubanja** [comment]
Not sure how to do this, is there an example where a function was deprecated, so that I could see how it's done? Like [this](https://stackoverflow.com/questions/295120/c-mark-as-deprecated) or is there a pcl way to do a deprecation?

**Comment by taketwo** [comment]
You can see some deprecation examples in this file: https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/segment_differences.h

So in this case, add something like:

```cpp
[[deprecated("centroids and covariances parameters are not used; they are deprecated and will be removed in future releases")]]
```

**Comment by Kaju-Bubanja** [comment]
Done in https://github.com/PointCloudLibrary/pcl/pull/3302

**Comment by taketwo** [comment]
Usually cross-referencing between issues and PRs is done the other way round, i.e. in the PR description you write which issue it resolves. If done so, GitHub will automatically add a back-link to the issue and also will close it once PR is merged, very convenient.

**Comment by Kaju-Bubanja** [comment]
Ah, I see thanks for letting me know.
