### ISSUE TITLE
[Eucliean Clustering] Illegal memory access in gpu/octree/src/cuda/octree_builder.cu:403

### ISSUE THREAD

**Issue by ohwonteak** [PointCloudLibrary/pcl#2371]
## Your Environment

* Operating System and version: UBUNTU 16.04
* Compiler: CUDA 9.2
* PCL Version: PCL 1.8.1

**CMAKE_LIST
find_package(PCL 1.8.1 REQUIRED)
FIND_PACKAGE(CUDA)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
INCLUDE(FindCUDA)
## Context

I want to use Euclidean clustering using gpu. I've built the source and it will be catkin_make, but when I run rosrun, the following error will be displayed.

won@won-desktop:~$ rosrun pharos_laser_taek gpu_cluster 
[ INFO] [1531073642.137339770]: started gpu_cluster.cpp
[ INFO] [1531073642.137372028]: SUBTOPIC : 
[ INFO] [1531073642.137379877]: PUBTOPIC : 
Error: an illegal memory access was encountered	/home/won/Downloads/pcl-pcl-1.8.1/gpu/octree/src/cuda/octree_builder.cu:403

how fix it? 

## Code to Reproduce

//
// Created by won on 28/6/18.
//

#include <ros/ros.h>

#include <tf/transform_broadcaster.h>
#include <tf/transform_listener.h>

#include <sensor_msgs/LaserScan.h>
#include <geometry_msgs/PointStamped.h>
#include <laser_geometry2/laser_geometry.h>
#include <pcl/gpu/octree/octree.hpp>
//#include <pcl-1.8/pcl/cuda/point_cloud.h>

#include <pcl/gpu/segmentation/gpu_extract_clusters.h>
#include <pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp> //요걸 넣어주니까 되는데 뭐냐?
#include <pcl_ros/point_cloud.h>
#include <pcl_ros/transforms.h>

#include <pcl/point_types.h>

#include <pcl/filters/extract_indices.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/features/normal_3d.h>

#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl/sample_consensus/method_types.h>

#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/segmentation/extract_clusters.h>
#include <nav_msgs/Path.h>

///전역변수///

///------////

class velodyne_
{
public:

    ros::NodeHandlePtr nh;
    ros::NodeHandlePtr pnh;

    velodyne_()
    {
        nh = ros::NodeHandlePtr(new ros::NodeHandle(""));
        pnh = ros::NodeHandlePtr(new ros::NodeHandle("~"));

        ///서브스크라이브는 this 사용 publish는 메세지형식 이것만 잘 생각해놓기
        get_topic = nh->subscribe("remove_ground", 10 , &velodyne_::GROUND_SEG_CB,this);
        gpu_cluster = nh->advertise<sensor_msgs::PointCloud2>("gpu_clustered",10);

    }

    void GROUND_SEG_CB(const sensor_msgs::PointCloud2Ptr raw_input){
        ///CALLBACK 함수
        pcl::PointCloud<pcl::PointXYZ>::Ptr raw_cloud (new pcl::PointCloud<pcl::PointXYZ>);
        pcl::fromROSMsg(*raw_input,*raw_cloud);
        pcl::PointCloud<pcl::PointXYZI>::Ptr gpu_cloud (new pcl::PointCloud<pcl::PointXYZI>);///gpu클러스터링 통해서 나온거  넣는다.
        pcl::PointCloud<pcl::PointXYZ>::Ptr sub_cloud (new pcl::PointCloud<pcl::PointXYZ>);
        pcl::PointCloud<pcl::PointXYZI>::Ptr add_i_cloud (new pcl::PointCloud<pcl::PointXYZI>);
        sensor_msgs::PointCloud2 clustering;

        if(raw_cloud->points.size() == 0){
            return;
        }

        ///1tree사용
        ///2cluster넣기.

        int minclustersize_ = 50;
        int maxclustersize_= 3000;
        float clustertorlenace_= 0.5;

        pcl::gpu::Octree::PointCloud cloud_device;
        cloud_device.upload(raw_cloud->points);

        pcl::gpu::Octree::Ptr octree_device (new pcl::gpu::Octree);

        octree_device->setCloud(cloud_device);
        octree_device->build();

        std::vector<pcl::PointIndices> cluster_indices_gpu;
        pcl::gpu::EuclideanClusterExtraction gec;

        gec.setClusterTolerance (clustertorlenace_);
        gec.setMinClusterSize (minclustersize_);
        gec.setMaxClusterSize (maxclustersize_);
        gec.setSearchMethod (octree_device);
        gec.setHostCloud(raw_cloud);
        gec.extract(cluster_indices_gpu);

        std::vector<pcl::PointCloud<pcl::PointXYZI> > clustered_obstacle_cloud_vec;
        int INTENSITY = 10;

        std::vector<pcl::PointIndices>::const_iterator it;

        for (std::vector<pcl::PointIndices>::const_iterator it = cluster_indices_gpu.begin();
             it != cluster_indices_gpu.end(); ++it) {
            ///그냥 int i=0~ 끝까지 돌리는것. 객채1 ~객채 2 객체 3 객체 4
            sub_cloud->clear();         ///******************************
            add_i_cloud->clear();

            for (std::vector<int>::const_iterator pit = it->indices.begin(); pit != it->indices.end(); ++pit) {
                //한객채 i

//                input_ptr->points[*pit].intensity = Intensity_value;        //한객체에 일정한  intensity값을 넣어준다.
                sub_cloud->points.push_back(raw_cloud->points[*pit]);  //그 객체를 클러스터에 넣는다.

                /////한객체를 다 넣는것
            }

            sub_cloud->width = sub_cloud->points.size();
            sub_cloud->height = 1;
            sub_cloud->is_dense = true;
            std::cout<<"worked"<<std::endl;
            pcl::copyPointCloud(*sub_cloud,*add_i_cloud);

            for(int i=0; i<add_i_cloud->points.size(); i++){
                add_i_cloud->points[i].intensity=INTENSITY;
            }///INTENSITY값을 입혀준다.

            INTENSITY += 20;
            if(INTENSITY>=250){
                INTENSITY=10;
            }

            clustered_obstacle_cloud_vec.push_back(*add_i_cloud);

        }///마지막 for

        for(int i=0; i<clustered_obstacle_cloud_vec.size(); i++)
        {
            *gpu_cloud+=clustered_obstacle_cloud_vec.at(i);

        }

        pcl::toROSMsg(*gpu_cloud,clustering);

        clustering.header.frame_id = "velodyne";

        ///가장 가까운 객체는 프레임 어디로?
        gpu_cluster.publish(clustering);

    }

protected:
    ros::Subscriber get_topic;
    ros::Publisher gpu_cluster;

};

int main(int argc, char **argv)
{

    ros::init(argc, argv, "gpu_cluster");       //노드명 초기화

    ROS_INFO("started gpu_cluster.cpp");
    ROS_INFO("SUBTOPIC : ");
    ROS_INFO("PUBTOPIC : ");

    velodyne_ gpu_cl;

    ros::spin();

}

**Comment by ada-hs** [comment]
did you solve this problem? I meet this error too.

**Comment by jasjuang** [comment]
@ohwonteak @ada-hs you guys are getting this error most likely due to noisy points that are too far away, try running `pcl::StatisticalOutlierRemoval` and/or `pcl::RadiusOutlierRemoval` before uploading your points into octree.

**Comment by ada-hs** [comment]
@jasjuang Thanks for your reply, actually , I do the noisy points removal operation before building the octree.

I also try to check whether the  size of the scene influence constructing gpu octree. There is no pattern....cause some times if the input point data was large(27 million), it works, but when the less data(9 million)， it crushed with the same error...

by the way, I have tested the bounding box of the point cloud, which can reflect the 
occupancy of the space....but there is no relevancy neither....

I have no idea about solving this problem.......is this a bug from cuda or pcl?

**Comment by jasjuang** [comment]
@ada-hs Can you upload your source point cloud somewhere so I can take a look? If this is indeed a pcl bug I might run into this problem too eventually.

**Comment by ada-hs** [comment]
@jasjuang . You are so nice, but for some special reason, I am not able to upload  files onto net....still. I can send data by email , could you give me your email address?

**Comment by jasjuang** [comment]
Have you try something like https://uploadfiles.io/ ? It's a better idea to upload it to somewhere public so other people can potentially look into this problem too.

**Comment by gapbridger** [comment]
hi @jasjuang we also encountered the same problem, any update on potential fix?

**Comment by gapbridger** [comment]
we tried to remove the outlier of the point cloud too with no success, same error persists

**Comment by ruslo** [comment]
I can reproduce this error with code:
```cpp
#include <pcl/gpu/features/features.hpp>  // pcl::gpu::NormalEstimation

auto main() -> int {
  const std::size_t N = 1000;
  std::vector<pcl::PointXYZ> cloud_cpu(N, {0.0, 0.0, 0.0});

  pcl::gpu::NormalEstimation::PointCloud cloud_gpu;
  cloud_gpu.upload(cloud_cpu);

  pcl::gpu::NormalEstimation ne_gpu;
  ne_gpu.setInputCloud(cloud_gpu);

  const float radius_search = 2.0F;
  const int max_results = 500;
  ne_gpu.setRadiusSearch(radius_search, max_results);

  pcl::gpu::NormalEstimation::Normals normals_gpu;
  ne_gpu.compute(normals_gpu);

  return EXIT_SUCCESS;
}
```

- Ubuntu 18.04.03
- GCC 7.4.0
- CUDA 10.2
- PCL 1.10.0

**Comment by kunaltyagi** [comment]
Thanks for the short reproducible example. Could you please run your code with `cuda-memcheck`, and see if there is any indication of the illegal memory access in the kernel code?

**Comment by ruslo** [comment]
> Could you please run your code with cuda-memcheck, and see if there is any indication of the illegal memory access in the kernel code?

Yes, I see the illegal write:

```
Invalid __global__ write of size 4
  at 0x00000bd8 in pcl::device::singleStepKernel(pcl::device::SingleStepBuild)
  by thread (0,0,0) in block (0,0,0)
  Address 0x7025cf000 is out of bounds
  Saved host backtrace up to driver entry point at kernel launch time
  Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x346) [0x297db6]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 [0x329d9]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 [0x32a67]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 [0x68dc5]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_Z69__device_stub__ZN3pcl6device16singleStepKernelENS0_15SingleStepBuildERKN3pcl6device15SingleStepBuildE + 0xaf) [0x1436f]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_ZN3pcl6device16singleStepKernelENS0_15SingleStepBuildE + 0xe) [0x1438e]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_ZN3pcl6device10OctreeImpl5buildEv + 0x445) [0x147e5]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_ZN3pcl3gpu6Octree5buildEv + 0xd) [0x24ccd]
  Host Frame:/.../pcl/lib/libpcl_gpu_features.so.1 (_ZN3pcl3gpu16NormalEstimation7computeERNS0_11DeviceArrayINS_8PointXYZEEE + 0x41) [0x34971]
  Host Frame:/.../_builds/foo (main + 0x129) [0x2453]
  Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
  Host Frame:/.../_builds/foo (_start + 0x2a) [0x224a]
```

```
Program hit cudaErrorLaunchFailure (error 719) due to "unspecified launch failure" on CUDA API call to cudaDeviceSynchronize. 
  Saved host backtrace up to driver entry point at error
  Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3ac5a3]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 [0x67066]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_ZN3pcl6device10OctreeImpl5buildEv + 0x3b5) [0x14755]
  Host Frame:/.../pcl/lib/libpcl_gpu_octree.so.1 (_ZN3pcl3gpu6Octree5buildEv + 0xd) [0x24ccd]
  Host Frame:/.../pcl/lib/libpcl_gpu_features.so.1 (_ZN3pcl3gpu16NormalEstimation7computeERNS0_11DeviceArrayINS_8PointXYZEEE + 0x41) [0x34971]
  Host Frame:/.../_builds/foo (main + 0x129) [0x2453]
  Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xe7) [0x21b97]
  Host Frame:/.../_builds/foo (_start + 0x2a) [0x224a]
```

```
Error: unspecified launch failure	/.../pcl/gpu/octree/src/cuda/octree_builder.cu:403
```

**Comment by ruslo** [comment]
> Invalid `__global__` write of size 4

Fixed here: https://github.com/PointCloudLibrary/pcl/pull/3627

Note that the [above test](https://github.com/PointCloudLibrary/pcl/issues/2371#issuecomment-577727912) is not crashing now, but the results are still inadequate. CPU based normal estimation returns NaNs as expected, but GPU returns (1,0,0), which doesn't make sense since all points are the same.

**Comment by irenji** [comment]
I have the same problem with GPU octree example.
https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/octree/src/octree_search.cpp

Just some more information it's work in debug build, It's crash in the release build.

**Comment by larshg** [comment]
@irenji please see I'd #3951 works for fixing the Release build.

**Comment by irenji** [comment]
> @irenji please see if #3951 works for fixing the Release build.

No, I still have the same problem.

**Comment by larshg** [comment]
And which version of PCL?

**Comment by irenji** [comment]
> @irenji please see if #3951 works for fixing the Release build.

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /GL")
It's working, I was rebuilding gpu_octree module.
but it seems that issue is in the gpu_container module.

now It's working for the example/gpu_octree.cpp.

Details of my system :
Windows 10
GTX 1060 3GB
PCL1.10
