### ISSUE TITLE
normal calculated by pcl is incorrect

### ISSUE THREAD

**Issue by LawrenceNJU** [PointCloudLibrary/pcl#2372]
## Your Environment

* Operating System and version: ubuntu 18.04
* Compiler: gcc 7.3.0
* PCL Version: pcl 1.8

## Context
When I use "pcl_normal_estimation" tool to calculate the normal of point cloud representing outdoor scene, the result is wrong, as shown in the following figure(the first figure is in top view and the second is in side view):
![screenshot from 2018-07-09 10-10-23](https://user-images.githubusercontent.com/19586476/42427389-db63b876-8360-11e8-96ed-44ee52052ebc.png)
![screenshot from 2018-07-09 10-15-38](https://user-images.githubusercontent.com/19586476/42427438-1565ec92-8361-11e8-9d6a-667046e33834.png)
The normal(white line) is not perpendicular to surface (green point cloud)

## Code to Reproduce

$ pcl_normal_estimation ./xyz.pcd ./xyz_normal.pcd -k 10
$ pcl_viewer xyz_normal.pcd -normals 50 -normals_scale 2
the data is: [xyz.zip](https://github.com/PointCloudLibrary/pcl/files/2174427/xyz.zip)

**Comment by taketwo** [comment]
Looks similar to #2403.

**Comment by taketwo** [comment]
Closing this in favor of #2403.

As a temporary solution you can de-mean your point cloud before computing normals. Also, as suggested by @msy22, you may want to increase the number of neighbors or switch to radius search (around 2m).
