### ISSUE TITLE
pointclouds.org (cited in tutorial section) has been hacked

### ISSUE THREAD

**Issue by ghost** [PointCloudLibrary/pcl#2381]
Navigating to the Documentation / Tutorial from the README.md leads to the official PCL webstite wich has been hacked: clicking in any part of the page bring you to ad pages.

It is impossible to read contacts page to warn webmaster so I'm opening an issue here.

**Comment by frozar** [comment]
I was experiencing the same situation (cf the attached files). The Firewall from my enterprise forbid me to access to the official PCL web page.

It's not related to the code itself, but it's a pretty big Issue!

![2018-07-20 12_20_00-window](https://user-images.githubusercontent.com/1025244/42999039-9a16e220-8c1c-11e8-9cf1-184fe22fd799.png)
![2018-07-20 12_20_29-window](https://user-images.githubusercontent.com/1025244/42999040-9a3a2622-8c1c-11e8-9d6f-be9f6e4fcd92.png)
![2018-07-20 12_20_49-window](https://user-images.githubusercontent.com/1025244/42999041-9a5131be-8c1c-11e8-8331-5722d0f8f058.png)
![2018-07-20 12_21_05-window](https://user-images.githubusercontent.com/1025244/42999042-9a676be6-8c1c-11e8-94ee-0357c0204942.png)

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho @taketwo Could you confirm this issue? I have receive same reports and confirmed that security software detect this problem.

**Comment by taketwo** [comment]
Seems so. AFAIK this happened already couple of years ago. @rbrusu is in control of the server, hope he will react.

**Comment by rbrusu** [comment]
thanks for reporting, will take care of it today.

**Comment by ac130kz** [comment]
There was a casino ad overlay the website, and it was quite violent, so beware if it comes back. Maybe static hosting on Github/Gitlab can solve such issues, if it is feasible

**Comment by gdrt94** [comment]
The site is still down. Here's the corresponding thread in the [mailing list](http://www.pcl-users.org/Point-Cloud-website-not-working-td4046326.html), no response yet. Hope it can be fixed today.

**Comment by rbrusu** [comment]
should have the rest ready soon

**Comment by UnaNancyOwen** [comment]
@rbrusu Thanks!

**Comment by rbrusu** [comment]
all should be back to normal. thanks everyone for reporting so fast! a very old 10.04 LTS machine also thanks you for being given a chance to serve again under 18.04 LTS ;)

**Comment by KCmangelma** [comment]
Seems to be hacked again, pointclouds.org and docs.pointclouds.org occasionally taking me to some ad pages.

**Comment by SergioRAgostinho** [comment]
Thank you for reporting.

**Comment by aaronrancsik** [comment]
Hello, the main page is looks like it`s hacked again. Loads advert randomly...

**Comment by bdvstg** [comment]
I'm meet same situation (ad pages) today.
but, after close ad, and click again, it normal.

**Comment by rbrusu** [comment]
this has been reported elsewhere but we need to move away from modx as a CMS because it's been a horrible experience maintaining it, but I have no time to do it at the moment. If someone has more cycles and wants to give it a try, please let me know.

**Comment by natowi** [comment]
@rbrusu you could move the homepage to [github pages](https://pages.github.com/) and enable [domain forwarding to the github pages site and enable https for the domain](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site). 
The PCL homepages has no dynamic content, so GHpages should work. Side benefit: homepage can be kept up to date by the community. The documentation could be moved to https://readthedocs.org/ ([doxygen2readthedocs](https://stackoverflow.com/questions/36064976/using-doxygen-in-read-the-docs))

**Comment by mvieth** [comment]
This is fixed (new website)
