### ISSUE TITLE
Seeking Suggestion:: Warning:PATH too long installer unable to modify PATH!

### ISSUE THREAD

**Issue by santoshnpl54** [PointCloudLibrary/pcl#2383]
I am trying to install PCL -1.8.1-AllINOne-msvc2017-win64 to implement on my project. However, installer could not complete because of this warning. "Warning:PATH too long installer unable to modify PATH!" Had any one faced the same problem while installing. If so, how were you able to resolve the issue. 
#Trying to install on Windows 10
Thanks!!

**Comment by frozar** [comment]
This is a warning. It should not prevent you to complete the setup. Don't
you have any errors?

Frozar

Le lun. 23 juil. 2018 22:01, santoshnpl54 <notifications@github.com> a
écrit :

**Comment by fburakk** [comment]
I have the same issue with "PCL-1.8.1-AllInOne-msvc2015-win64" on windows 10. Installation process ends in half.

**Comment by akesling** [comment]
Here's an image of the warning in context.

![PCL_installer_early_exit](https://user-images.githubusercontent.com/101064/72221317-89326780-3527-11ea-9a99-8416aa42c767.PNG)

**Comment by taketwo** [comment]
Perhaps @UnaNancyOwen can help here.

**Comment by UnaNancyOwen** [comment]
It seems that many paths are set in the environment variable Path of system.
In Windows, maximum value of one environment variable is 260.
Please organize unnecessary Path or Please consider set registry key LongPathsEnabled to 1. It is relaxes the character limits of environment variable. (That registry key is easy to configure with the Python installer. Please google for details about it.).
And, If it is already registered, please delete registered PCL (C:\Program Files\PCL\bin) and OpenNI2 (C:\Program Files\OpenNI2\Redist or %OPENNI2_REDIST64%) path from environment variable Path.

**Comment by UnaNancyOwen** [comment]
Just click on it.
![python](https://user-images.githubusercontent.com/816705/72228402-88faa080-35e9-11ea-823a-f25d961cb5bd.png)

**Comment by larshg** [comment]
I think this one can be closed as its not really a PCL issue, but a general windows issue.

**Comment by aatwo** [comment]
I have less than 500 characters in my PATH variable and have long paths enabled in my registry, yet I still get this error.

**Comment by jeffreyianwilson** [comment]
Is there any solution to this, I have long paths enabled and installed with the all in one installer and I am still getting the path is to long error.

**Comment by MarkusF79** [comment]
I've had the same issue. A rather simple solution that worked for me was disabling the addition of the PCL installation path to the PATH environment variable during execution of the PCL installer. The installation then finished successfully and I added the PCL installation path to PATH manually.

**Comment by ytwei1995** [comment]
just click the .msi file, and select "remove", then again click and choose "change" to reinstall the openNI.
