### ISSUE TITLE
Example of "Robust pose estimation of rigid objects"，the aligned object model is not aligned correctly

### ISSUE THREAD

**Issue by iynaur** [PointCloudLibrary/pcl#2384]
## Your Environment

* Operating System and version: Ubuntu 16.04 x64
* Compiler:
* PCL Version:master

## Code to Reproduce

Do exactly this tutorial tell you to do:
http://www.pointclouds.org/documentation/tutorials/alignment_prerejective.php#alignment-prerejective
and check the output, we can see the aligned object model is not aligned correctly.

## Possible Solution

In this tutorial, the author said: "Although we have defined the basic point type to contain normals, we only have those in advance for the object (which is often the case). We will estimate the normal information for the scene below." But the object provided by the tutorial actually has incorrect normal information(normal data changed if I re estimate it). We need to replace it with object which has correct normal information, or we add code to estimate normals for object as we did for scene.
This maybe is obvious for you but for people who need to read tutorials it will cost them long time to find the root cause.

**Comment by Maxiturne** [comment]
Same behaviour on windows 10 using the prebuilt version 1.8.1. 
Recomputing the normal estimation on the object or increasing the number of iterations to 100 000 in the prerejective settings solved the problem (the first solution being the best).
Need to change the object pcd file or add the normal estimation in the code of the tuto (even in the master branch).

pcl/doc/tutorials/content/sources/alignment_prerejective/alignment_prerejective.cpp

**Comment by git-chenjiqing** [comment]
Have you solved it yet
