### ISSUE TITLE
Calling Visualizer::spinOnce() leaks memory

### ISSUE THREAD

**Issue by Dysl3xik** [PointCloudLibrary/pcl#2386]
## Your Environment
* Window 10
* VS2017 15.5.3
* PCL 1.8.1 x64 - Installer from release page here on github

## Context
We have wrapped a thread around the visualizer that allows us to add/remove objects at will and have the visualizer update all while our application is running separately. To manage running the interactor and adding stuff in we call spinOnce to allow for updates.

## Expected Behavior
spinOnce should update the viewer and allow mouse interactions, WITHOUT using any additional memory once the visualizer is fully loaded and no content is being added or removed.

## Current Behavior
each call to spinOnce will use an increasing amount of memory, to the best of my ability to tell this memory is never reclaimed, even if the visualizer is destroyed. Also this happens without any objects in the viewer!

Running the code below (and removing spinOnce) also causes a leak with each successive creation of the visualizer...

Replacing spinOnce with spin() in the code below, and holding down the Q key also results in a leak.

Also someone mentioned this issue in the forums before with no reply http://www.pcl-users.org/Memory-leak-in-PCLVisualizer-class-td4044029.html

## Code to Reproduce
```
	while (true)
	{
		int i = 0;
		auto visualizer = pcl::visualization::PCLVisualizer();
		while (i < 10000)
		{
			visualizer.spinOnce(1);
			std::this_thread::sleep_for(1ms);
			std::cout << ++i << std::endl;
		}
		visualizer.close();
	}
```
## Possible Solution
The only thing I can gather is that something may be wrong with the message loop in VTK as calling spinOnce starts the message loop and sets a time to end it, whereas calling spin starts the message loop and pressing Q ends it.

**Comment by Dysl3xik** [comment]
So creating and destroying visualizers is leaking for you, although spinning isnt?

I can try to recompile but it's fairly painful / slow in windows, and generally prefer your releases as it makes it easier for others to get my code and build.

**Comment by taketwo** [comment]
There is certainly an issue with destroying visualizers. I'm using a tiling window manager, and depending on the current layout (tiled vs. full-screen windows) the visualizer windows either vanish after being closed (as they should), or linger around (until the whole app is terminated).

There (hopefully) will be a release soon, and (hopefully) @UnaNancyOwen  will package it with the latest VTK. If you can afford to wait, then let take this as a plan.

**Comment by larshg** [comment]
I have tested with master and it doesn't seem to leak atm.

Windows 10.
VS2019.

Lets close this. Please open a new if required.
