### ISSUE TITLE
ICP segmentation fault when input cloud contains NaN

### ISSUE THREAD

**Issue by llueder** [PointCloudLibrary/pcl#2387]
`pcl::IterativeClostestPoint` seems to have an issue with NaN values, which leads to a segmentation fault when the "in" point cloud contains NaN values.

This issue might be related to #1819 , but [this](https://github.com/PointCloudLibrary/pcl/issues/1819#issuecomment-343343849) comment says that they still had problems after removing NaNs, that's why I opened a new issue.

## Your Environment

* Operating System and version: ubuntu 16.04.10 64 bit
* Compiler: gcc 5.4.0
* PCL Version: 1.8.1, same behavior on master (310b93f33f674b3f265fb355a71185a3b6527fcd)

## Context

I was trying to register two (floating point) point clouds, which contain NaN values. The code is basically taken from the [example](http://pointclouds.org/documentation/tutorials/iterative_closest_point.php) (see below).

Additional information, should be irrelevant:
I load the point clouds from files, to which I saved the data created by the example.

## Expected Behavior

Output "has converged: [...]"

## Current Behavior

Segmentation fault during `icp.align`

## Code to Reproduce

```
int main (int argc, char** argv){
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_in (new pcl::PointCloud<pcl::PointXYZ>);
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_out (new pcl::PointCloud<pcl::PointXYZ>);

if (pcl::io::loadPCDFile < pcl::PointXYZ > ("cloud_in.pcd", *cloud_in) == -) return -1;
if (pcl::io::loadPCDFile < pcl::PointXYZ > ("cloud_out.pcd", *cloud_out) == -1) return -1;

  pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointXYZ> icp;
  icp.setInputSource(cloud_in);
  icp.setInputTarget(cloud_out);
  pcl::PointCloud<pcl::PointXYZ> Final;
  icp.align(Final);
  std::cout << "has converged:" << icp.hasConverged() << " score: " <<

 return (0);
}
```
Let the `cloud_in` contain NaN values.

## Possible Solution

Quick fix: Remove NaN values from input

If the NaNs are replaced by any valid value during file read (change l. 325 in `file_io.h` to `value = 0;`), the algorithm works fine (Obviously, this not a solution, but might help to track down the faulty code).

**Comment by kunaltyagi** [comment]
Should be fixed in master with the new checks on `isfinite`
