### ISSUE TITLE
Documentation search bar is broken

### ISSUE THREAD

**Issue by claudiofantacci** [PointCloudLibrary/pcl#2392]
## Your Environment
* Operating System and version: macOS 10.13.4 & Ubuntu Xenial
* Browser: Firefox 61.0.2, Safari 11.1, Firefox 61.0.1
* PCL documentation version: All

## Context
Just search anything in the search bar of the documentation.

## Expected Behavior
Results relevant to the search keyword about PCL.

## Current Behavior
No output provided on-screen.
The page is not rendered properly as shown in the following image

<img width="1681" alt="schermata 2018-08-19 alle 15 19 19" src="https://user-images.githubusercontent.com/14168673/44309223-a0693600-a3c3-11e8-9710-b651460488f2.png">

and the following text is shown

```
Except where otherwise noted, the PointClouds.org web pages are licensed under
Creative Commons Attribution 3.0
.

Pages generated on Mon Aug 7 2017 20:08:44
```

## Code to Reproduce
Search something in the documentation webpage.

## Possible Solution
This seems to be related to how the page is rendered by the browser, probably after some component update. Maybe it is sufficient to update Doxygen and generate again the documentation.

**Comment by taketwo** [comment]
The server does not allow to execute PHP scripts anymore. We have switched to using JavaScript based search in the latest documentation (http://docs.pointclouds.org/trunk/), however the documentation for the old releases still has to be re-generated with the new settings.

**Comment by taketwo** [comment]
1.8.0 and 1.8.1 re-generated and uploaded to the server.

**Comment by claudiofantacci** [comment]
Great, tested and running! 👍
