### ISSUE TITLE
Error when running gulp serve in SPFX

### ISSUE THREAD

**Issue by dsravankumar1987** [PointCloudLibrary/pcl#2407]
Hi,

Creating a sample webpart using SPFX with Angular 4, and getting the below error after running gulp serve. Kindly help .
[14:40:54] Starting 'serve'...
[14:40:54] Starting gulp
[14:40:54] Starting subtask 'configure-sp-build-rig'...
[14:40:54] Finished subtask 'configure-sp-build-rig' after 9.63 ms
[14:40:54] Starting subtask 'spfx-serve'...
Starting api server on port 5432.
Registring api: /getwebparts
Registring api: /*.*
Registring api: /workbench
**[14:40:55] Error - [spfx-serve] Error: Invalid glob argument:
[14:40:55] Error - 'spfx-serve' sub task errored after 488 ms
 Invalid glob argument:
[14:40:55] 'serve' errored after 514 ms
[14:40:55]
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1****

Regards,
Sravan.

**Comment by SergioRAgostinho** [comment]
Wrong project?

**Comment by smit1529** [comment]
**### Make sure your local version of gulp is not 4.0.0**

If the local version of gulp is 4.0.0 then change into the package.json and make the configuration to 3.9.1 and try **npm install --save** and then try **gulp serve**

**This will do the trick.**

**Comment by JEEVANJGA** [comment]
> **### Make sure your local version of gulp is not 4.0.0**
> 
> If the local version of gulp is 4.0.0 then change into the package.json and make the configuration to 3.9.1 and try **npm install --save** and then try **gulp serve**
> 
> **This will do the trick.**

That did help. thanks.

**Comment by reliktus** [comment]
Is there any way to make it work with gulp version ^4.0.0?
Want it due to the different version of watcher
