### ISSUE TITLE
PCD reader cant find file, but the file exists

### ISSUE THREAD

**Issue by shreyasgan** [PointCloudLibrary/pcl#2409]
## Your Environment

* Operating System and version: Ubuntu 14.01 ROS Indigo
* Compiler:
* PCL Version: 1.8

## Context
I am trying to load a PCD file to use in rviz, but the PCD file wont load, although the file is in the same workspace

## Expected Behavior
should load the file

## Current Behavior
doesnt load the file

## Code to Reproduce

 	pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGBA>());
    	pcl::io::loadPCDFile<pcl::PointXYZRGBA>("Wound_3d_mesh.pcd", *cloud);

**Comment by taketwo** [comment]
99.9999% this is not a PCL issue. Please double check that a file with this name is located in the _working directory_ or your program.

**Comment by taketwo** [comment]
I'm a bit out of touch with ROS nowadays. I do remember though that working directory depended on whether you are running with `rosrun` or as a part of a launch script. You can insert the following snippet into your program to find out the current directory:

```cpp
#include <boost/filesystem.hpp>

boost::filesystem::path full_path(boost::filesystem::current_path());
std::cout << "Current path is : " << full_path << std::endl;
```

**Comment by shreyasgan** [comment]
I am using roslaunch, and I inserted the code you provided. I got an error saying boost/filesystem.hpp: No such file or directory

**Comment by SergioRAgostinho** [comment]
You need to update your CMake file to find Boost filesystem and add it's include directories to your CMake target.

This should help https://cmake.org/cmake/help/v3.8/module/FindBoost.html

**Comment by SergioRAgostinho** [comment]
Can you print the content of `${Boost_INCLUDE_DIRS}` and `${Boost_FILESYSTEM_LIBRARIES}`?

**Comment by shreyasgan** [comment]
Sorry, I am a beginner with Cmake, how would I do this?

**Comment by taketwo** [comment]
This is a bug tracker for PCL library. This is **not** a support forum for CMake, ROS, Boost, Linux, etc. Please use a search engine and/or relevant Q&A resources to find answers to you questions.
