### ISSUE TITLE
PCLVisualizer segmentation fault when creating interactor

### ISSUE THREAD

**Issue by apalomer** [PointCloudLibrary/pcl#2413]
I have been trying to use

```cpp
PCLVisualizer (vtkSmartPointer<vtkRenderer> ren, vtkSmartPointer<vtkRenderWindow> wind, const std::string &name = "", const bool create_interactor = true);
```

constructor alongside with VTK trunk to create a pcl widget for Qt and I get segmentation faults if I set the `create_interactor` to `true`. However it is very weird because I do not get the segmentation fault all the times I run the code, but all the times that I get the segmentation fault it is in the same place, when the `pcl::visualization::PCLVisualizer` executes `createInteractor ()`. In detail when in this function the following code is called ` interactor_->Initialize ();` in [line  285 of file pcl_visualizer.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L285). This actually segfaults within vtk when it calls the function [`XtDisplayInitialize(vtkXRenderWindowInteractor::App,this->DisplayId, "VTK","vtk",nullptr,0,&argc,nullptr);`](https://gitlab.kitware.com/vtk/vtk/blob/master/Rendering/OpenGL2/vtkXRenderWindowInteractor.cxx#L329)

I am running Ubuntu 18.04 using this [commit for VTK](https://gitlab.kitware.com/vtk/vtk/commit/fd9cdefeb5bbfd6cd2fbaf1df7adbcaa4af29b1c) and [this commit for PCL](https://github.com/PointCloudLibrary/pcl/commit/b988db3c53b02a017cc5dd04e48cb64f55fb15ab). The two used libraries (VTK and PCL) are not installed, i link against this version instead of the installed one by setting the falgs `-DPCL_DIR` and `-DVTK_DIR` when configuring `cmake`: `cmake -DPCL_DIR=/path/to/pcl/custom/install/dir -DVTK_DIR=/path/to/vtk/compiled ..`

You can find an example code [here](https://github.com/apalomer/qpclvisualizer).

**Comment by taketwo** [comment]
FWIW I can not reproduce this issue with PCL trunk and VTK 8.1 on Ubuntu 16.04. I tried to run your app around 15 times and it never crashed.

**Comment by apalomer** [comment]
I also tried with [VTK 8.1.0](https://github.com/Kitware/VTK/commit/ab71574c064a9444d5ec0bbdf8dd27f8587a5c9a) and can confirm that it does not happen with that release of VTK. However, I still think this should be fixed as new releases keep appearing.

**Comment by taketwo** [comment]
> I still think this should be fixed as new releases keep appearing.

Certainly! Please let us know if you find a solution.

**Comment by larshg** [comment]
PCL supports VTK 9.
