### ISSUE TITLE
build project which use pcl library error through bazel

### ISSUE THREAD

**Issue by echotor** [PointCloudLibrary/pcl#2436]
## Your Environment
* Operating System and version: Ubuntu 16.04
* Compiler: bazel 
* PCL Version: 1.7.2

## Context
I use pcl in my project, and using bazel to compile the project. But I got a failture.
My bazel WORKSPACE file is like below:

```
new_local_repository(
    name = "pcl",
    build_file = "pcl.BUILD",
    path = "/usr/local/include/pcl-1.7",
)
```

and the pcl.BUILD file is below:

```
licenses(["notice"])

package(default_visibility = ["//visibility:public"])

# This assumes you have pcl 1.7 pre-installed in your system.
cc_library(
    name = "pcl",
    defines = ["PCL_NO_PRECOMPILE"],
    includes = ["."],
    linkopts = [
        "-L/usr/local/lib",
        "-lboost_system",
        "-lpcl_common",
        "-lpcl_features",
        "-lpcl_filters",
        "-lpcl_io_ply",
        "-lpcl_io",
        "-lpcl_kdtree",
        "-lpcl_keypoints",
        "-lpcl_octree",
        "-lpcl_outofcore",
        "-lpcl_people",
        "-lpcl_recognition",
        "-lpcl_registration",
        "-lpcl_sample_consensus",
        "-lpcl_search",
        "-lpcl_segmentation",
        "-lpcl_surface",
        "-lpcl_tracking",
        "-lpcl_visualization",
    ],
)
```
I build a binary through BUILD file like:

```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        "@pcl//:pcl",
    ],
)
```

the hello-world.cc file's content is like below:

```
#include "pcl/point_cloud.h"
#include "pcl/point_types.h"
#include <iostream>

int main(int argc, char** argv) {
    std::string who = "World";
    return 0;
}
```
I got  a build error:

```
INFO: Found 2 targets...
ERROR: /home/walle/pcl-bazel/main/BUILD:7:1: C++ compilation of rule '//main:hello-world' failed (Exit 1).
main/hello-world.cc:3:29: fatal error: pcl/point_cloud.h: No such file or directory
compilation terminated.
INFO: Elapsed time: 0.619s, Critical Path: 0.21s
```

Why?

**Comment by taketwo** [comment]
PCL does not officially support Bazel. Please re-address your question to the provider of `pcl.BUILD`.

**Comment by koshtidheeraj** [comment]
Refer this [github link](https://github.com/koshtidheeraj/bazel).
I am able to compile code but I am getting segmentation fault when I run the executable.

I am getting below error logs when I try to analyse memory leak using 'valgrind'.

==28370== Memcheck, a memory error detector
==28370== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==28370== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==28370== Command: ./bazel-bin/pcl_bazel_trial
==28370== 
==28370== Invalid read of size 1
==28370==    at 0x108047: ??? (in /home/synerzip/.cache/bazel/_bazel_synerzip/b906b18d50d8270a83131ccbbf52d7b2/execroot/__main__/bazel-out/k8-fastbuild/bin/pcl_bazel_trial)
==28370==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28370== 
==28370== 
==28370== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==28370==  Access not within mapped region at address 0x0
==28370==    at 0x108047: ??? (in /home/synerzip/.cache/bazel/_bazel_synerzip/b906b18d50d8270a83131ccbbf52d7b2/execroot/__main__/bazel-out/k8-fastbuild/bin/pcl_bazel_trial)
==28370==  If you believe this happened as a result of a stack
==28370==  overflow in your program's main thread (unlikely but
==28370==  possible), you can try to increase the size of the
==28370==  main thread stack using the --main-stacksize= flag.
==28370==  The main thread stack size used in this run was 8388608.
==28370== 
==28370== HEAP SUMMARY:
==28370==     in use at exit: 0 bytes in 0 blocks
==28370==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==28370== 
==28370== All heap blocks were freed -- no leaks are possible
==28370== 
==28370== For counts of detected and suppressed errors, rerun with: -v
==28370== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

Please let me know if I am missing anything or doing anything wrong.

Thanks,
Dheeraj.
