### ISSUE TITLE
FixedDepthIterator doesn't exist in OctreeViewer code.

### ISSUE THREAD

**Issue by NPatch** [PointCloudLibrary/pcl#2444]
## Your Environment

* Operating System and version:
Windows 10 64bit
* Compiler:
MSVC2017
* PCL Version:
1.8.1

## Context
Wanted to test out the octree viewer. The project contains a single .cpp with the viewer's code in it, taken from the master branch of this repository. Intellisense throws error at the extractPointsAtLevel function.FixedDepthIterator does not exist for a pcl::octree::OctreePointCloudVoxelCentroid.

I've used the PCL AllInOne installer and have been using the PCL Visualizer to test stuff so it shouldn't be header/linking related.

Looked at the code and it seems this [commit](https://github.com/PointCloudLibrary/pcl/commit/b165f312d3e8d334aa567d4a6d62b19ca79a011e) was the issue.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'FixedDepthIterator': is not a member of 'pcl::octree::OctreePointCloudVoxelCentroid<pcl::PointXYZ,pcl::octree::OctreePointCloudVoxelCentroidContainer<PointT>,pcl::octree::OctreeContainerEmpty>'	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\....\cloud_viewer.cpp	379	

```

**Comment by NPatch** [comment]
Seeing as the library does not contain this iterator, I reverted the code from that commit and it compiles.

**Comment by taketwo** [comment]
Do I understand correct that you have PCL 1.8.1 installed, but in your project use copy/pasted code from current master?

**Comment by NPatch** [comment]
Yep...and now that I read your comment I'm assuming I shouldn't have. I assumed master==last_release.

**Comment by NPatch** [comment]
Sooo...you are not using devel branches. Ok I guess it makes sense.

**Comment by taketwo** [comment]
Correct, all the development happens in master. If you want to use snippets from library code it's generally safer to copy them from the tagged commit corresponding to the library version installed on your machine. So in this case, use [this file](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.1/tools/octree_viewer.cpp).

**Comment by NPatch** [comment]
Okay, thx. Sorry for the unneeded fuss.
