### ISSUE TITLE
How is it trained trainedLinearSVMForPeopleDetectionWithHOG.yaml 

### ISSUE THREAD

**Issue by zmh20062257** [PointCloudLibrary/pcl#2445]
## Your Environment

* Operating System and version:ubuntu 16.04
* Compiler:gcc
* PCL Version:pcl 1.8

## Context

hi
    How is it trained trainedLinearSVMForPeopleDetectionWithHOG.yaml ? Person Dataset is INRIA ?
training code is public? thank you!

**Comment by SergioRAgostinho** [comment]
Which example/tutorial are you trying to run? Provide URL.

(Sorry if this appears rude. You seem to struggle with English so I'm keeping the sentences to the essential.)

**Comment by zmh20062257** [comment]
https://github.com/PointCloudLibrary/pcl/blob/master/people/apps/main_ground_based_people_detection.cpp

**Comment by SergioRAgostinho** [comment]
> How is it trained trainedLinearSVMForPeopleDetectionWithHOG.yaml ? Person Dataset is INRIA ?

Check the  paper.
https://www.researchgate.net/publication/261353512_Tracking_people_within_groups_with_RGB-D_data

> training code is public? 

I don't think so. @mmunaro  is it?

**Comment by mmunaro** [comment]
@SergioRAgostinho Sorry, the training code is not available. Details are in the paper you already mentioned or in my PhD thesis: http://www.dei.unipd.it/~munaro/media/Munaro_Matteo_PhDthesis.pdf.
@zmh20062257 The dataset I used is the Inria Person Dataset.

**Comment by SergioRAgostinho** [comment]
Thanks for chiming in 👍
