### ISSUE TITLE
GridProjection mesh scale

### ISSUE THREAD

**Issue by Jaykob** [PointCloudLibrary/pcl#2448]
## Your Environment

* Operating System and version:  macOS 10.13.5
* Compiler: clang
* PCL Version: Current master trunk

Hi,
I'm experiencing issues using the grid projection algorithm as already described here several years ago : [http://www.pcl-users.org/Grid-Projection-td3417708.html](http://www.pcl-users.org/Grid-Projection-td3417708.html)

The algorithm works, but the resulting mesh is scaled down significantly. Is there anything I can do to avoid this downscaling or are there better alternatives for surface reconstruction in the meantime that I missed?
Also the algorithm is quite slow compared to Greedy Triangulation, Marching Cubes or Poisson. Is this to be expected?

## Code to Reproduce
```
pcl::search::KdTree<pcl::PointNormal>::Ptr tree (new pcl::search::KdTree<pcl::PointNormal>);
tree->setInputCloud(cloud_with_normals);

pcl::GridProjection<pcl::PointNormal> gp();
gp.setInputCloud(cloud_with_normals);
gp.setSearchMethod(tree);
gp.setResolution(0.005);
gp.setPaddingSize(3);
gp.setNearestNeighborNum(100);
gp.setMaxBinarySearchLevel(10);
gp.reconstruct(*triangles);
```

**Comment by SergioRAgostinho** [comment]
Hey Jaykob. 

> The algorithm works, but the resulting mesh is scaled down significantly. Is there anything I can do to avoid this downscaling or are there better alternatives for surface reconstruction in the meantime that I missed?

Scaled down in what sense? Are point coordinates scaled? Is the resulting number of points low?

In the latter case, have you tried setting a lower resolution for the GridProjection?

> Also the algorithm is quite slow compared to Greedy Triangulation, Marching Cubes or Poisson. Is this to be expected?

I personally have no experience in running these algorithms. Unfortunately our mailing list is down undergoing a migration process so there's not much else I can recommend at the moment.

**Comment by taketwo** [comment]
Closing due to lack of author feedback.

**Comment by ipbody** [comment]
### Enviroment

- Operating System and version: Ubuntu 20.04
- Compiler: cmake 3.16.3

Hi!, im having the exact same problem so i can give a little more details about it.

While using GridProjection, if the setResolution(res) parameter is low, the result mesh have better details but the size of it looks downscale by that "res" factor.

The code i used is almost identical to the one in the docs on [this link](https://pcl.readthedocs.io/en/latest/greedy_projection.html#greedy-triangulation), changing the Greedy method with this one

```
/*Grid Projection*/
  pcl::PolygonMesh grid;
  pcl::GridProjection<pcl::PointNormal> gp;

  // Get result
  gp.setInputCloud (cloud_with_normals);
  gp.setSearchMethod (tree2);
  gp.setResolution(res);
  gp.setPaddingSize(3);
  gp.reconstruct (grid);

  /*Generate mesh files*/
  std::cout << "Genereting mesh file" << std::endl;
  std::string res_str = std::to_string(res);

  pcl::io::savePLYFile("mesh_" + res_str +".ply", grid);
  pcl::io::saveVTKFile ("mesh_" + res_str +".vtk", grid);
```

As now i tried "res" values from 0.005 to 1 and the surface gets bigger with bigger resolution values but losses tons of details until it becames just a box.

I'll attach the surface (using res=0.01) next to a new one generated with the Greedy triangulation method.

![Front_view](https://user-images.githubusercontent.com/37856401/107700911-ebafe700-6c96-11eb-92e3-91584175dda9.png)
![Top_view](https://user-images.githubusercontent.com/37856401/107700929-f10d3180-6c96-11eb-9b0e-c510a0dfb89c.png)

**Comment by Jaykob** [comment]
I think the problem is quite obvious.
Give it a try yourself, no need for further details from my side.

**Comment by ipbody** [comment]
Could you re open this issue then?

**Comment by Jaykob** [comment]
Sorry for the confusion, my reply was aimed towards @SergioRAgostinho 
I can't reopen it, needs to be done by the maintainers.

**Comment by madsherlock** [comment]
GridProjection downscales the XYZ values of the input point cloud if they are not within a 1x1x1 box.
It forgets to upscale the XYZ values of the vertices.
Here is a workaround to fix the mesh after reconstruction:

```cpp
gp.setInputCloud(cloud);
pcl::PolygonMeshPtr mesh(new pcl::PolygonMesh);
gp.reconstruct(*mesh);
Eigen::Vector4f minp, maxp;
pcl::getMinMax3D (*cloud, minp, maxp);
Eigen::Vector4f bounding_box_size = maxp - minp;
double scale_factor = (std::max)((std::max)(bounding_box_size.x (),bounding_box_size.y ()),bounding_box_size.z ());
if (scale_factor > 1) {
    pcl::PointCloud<pcl::PointXYZ>::Ptr mesh_cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::fromPCLPointCloud2(mesh->cloud, *mesh_cloud);
    mesh_cloud->getMatrixXfMap(3,sizeof(pcl::PointXYZ)/4,0) = scale_factor*mesh_cloud->getMatrixXfMap(3,sizeof(pcl::PointXYZ)/4,0).eval();
    pcl::toPCLPointCloud2(*mesh_cloud,mesh->cloud);
}
```

**Comment by mvieth** [comment]
Hi everyone, I created a pull request to fix this problem, feel free to take a look and/or test it
