### ISSUE TITLE
Dataset link in conditional euclidean clustering tutorial needs to be updated.

### ISSUE THREAD

**Issue by plumewind** [PointCloudLibrary/pcl#2451]
Hello，friends，
      I found the dataset is gone when I learning the Conditional Euclidean Clustering document：

http://pointclouds.org/documentation/tutorials/conditional_euclidean_clustering.php#conditional-euclidean-clustering

The download link given here is wrong:https://raw.githubusercontent.com/PointCloudLibrary/data/master/Trimble/Outdoor1/Statues_4.pcd

I still can not found the dataset，can someone help me? thank you very much!

**Comment by SergioRAgostinho** [comment]
It's here https://sourceforge.net/projects/pointclouds/files/PCD%20datasets/Trimble/Outdoor1/
