### ISSUE TITLE
How could we check if the point cloud has been loaded flawlessly ?...

### ISSUE THREAD

**Issue by luxigo** [PointCloudLibrary/pcl#2453]
" Failed to find match for field 'x' " when loading a point cloud does not throw an exception.

Having zeroed value(s) and not knowing what did happen without looking at the console is annoying.

One would expect a way to know the point cloud was not loaded flawlessly (optional callback to let the user decide what to do ?)

The link mentioned in https://github.com/PointCloudLibrary/pcl/blob/ceec989f5413f6bceb8889b2d97cb66aa36f456e/common/include/pcl/conversions.h#L107
 is broken but it's still archived here: https://web.archive.org/web/20120624165157/http://dev.pointclouds.org/issues/595

**Comment by SergioRAgostinho** [comment]
That is the reason why all loaders/readers support the type [`PCLPointCloud2`](http://docs.pointclouds.org/trunk/structpcl_1_1_p_c_l_point_cloud2.html). You can query the existing vector `fields` to make sure the field you need is there. If everything is ok, you can then convert to the point cloud type you need.
