### ISSUE TITLE
PCL Users mailing list not publishing messages

### ISSUE THREAD

**Issue by bbercovici** [PointCloudLibrary/pcl#2455]
[The PCL Users mailing list ](http://www.pcl-users.org/) is not publishing messages posted after July 21st . Prior to that day, new messages were being published at a steady rate of several new questions a day. 
 
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

**Comment by SergioRAgostinho** [comment]
Please see the comments in #2415.
