### ISSUE TITLE
ModelOutlierRemoval Documentation references non-existent member function setFilterLimitsNegative

### ISSUE THREAD

**Issue by c-edmonston** [PointCloudLibrary/pcl#2460]
## Your Environment

* Operating System and version: Manjaro Linux 17.1.12 
* Compiler: gcc 8.2.0
* PCL Version: 1.8.1 (from AUR)

## Context 
Found when trying to filter outside of a model given computed. 

## Expected Behavior

The documentation should be correct.

## Current Behavior

Current source code comments (and resulting documentation) refer to this function.
https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/model_outlier_removal.h#L64

## Code to Reproduce

N/A

## Possible Solution

Documentation needs to be updated to use setNegative() from pcl::FilterIndices

**Comment by SergioRAgostinho** [comment]
> Documentation needs to be updated to use setNegative() from pcl::FilterIndices

Agreed. Please feel free to open a PR with the change.

**Comment by taketwo** [comment]
Documentation also refers to non-existent `setSampleConsensusModelPointer()` and `setThreholdFunctionPointer()`.

**Comment by Zekrom-7780** [comment]
@mvieth I'll pick up this issue
