### ISSUE TITLE
The documentation for PointXYZRGB does not match the implementation

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2464]
## Your Environment

* PCL Version: the master branch

## Context

The doc at http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php says

> PointXYZRGB - float x, y, z, rgb;
> Similar to PointXYZRGBA, except rgb represents the RGBA information packed into a float.
>
```.cpp
union
{
  float data[4];
  struct
  {
    float x;
    float y;
    float z;
  };
};
union
{
  struct
  {
    float rgb;
  };
  float data_c[4];
};
```

**But** the implementation
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L524-L529
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L572-L577

indicates that `PointXYZRGB` and `PointXYZRGBA` have the same memory layout.

## Expected Behavior

The doc and the implementation should match.

## Current Behavior

Either the doc or the implementation is wrong.

## Code to Reproduce

See the code above.

## Possible Solution

Fix either the implementation or the doc.

**Comment by csukuangfj** [comment]
@SergioRAgostinho 
thanks for your reply.

> (Literally) Similar to PointXYZRGBA, except rgb represents the RGBA information packed into a float.

actually, they have the same representation in the implementation (please see the code I posted above).

Furthermore, the demo code in the doc
```.cpp
union
{
  float data[4];
  struct
  {
    float x;
    float y;
    float z;
  };
};
union
{
  struct
  {
    float rgb;
  };
  float data_c[4];
};
```
is not correct and does not match the actual implementation.

The implementation is
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L224-L239

which occupies only 4 bytes (i.e., sizeof(uint32_t)), but the demo code occupies 16 bytes (i.e., sizeof(float[4]) )

**Comment by csukuangfj** [comment]
@SergioRAgostinho 
1. Either the demo code or the implementation should be changed.
2. If `PointXYZRGBA` and `PointXYZRGB` have exactly the same memory layout, is there a need
to define two different types instead of using only one of them?

**Comment by taketwo** [comment]
IIRC `RGB` originally had the `float` representation and `RGBA` had the `uint32` representation, but it's been long since they both support both representations and are actually the same (as you correctly pointed out). The `float` representation is a legacy thing. Ideally, we would remove it and also keep only one type, however it doing so will break a lot of user code. That said, we may consider typedefing one to another, this will a) make it more clear that the types are the same; b) avoid unnecessary template instantiations.

But at any rate, the documentation should be updated to reflect the fact that the types are the same.

**Comment by kunaltyagi** [comment]
> the documentation should be updated to reflect the fact that the types are the same

**Comment by mvieth** [comment]
Seems like this was done by #3294
