### ISSUE TITLE
Unexpected results for the operators / and - between a scalar and a pcl point type

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2465]
## Your Environment

* PCL Version: master

## Context

```.cpp
    pcl::PointXY p;
    p.x = 10;
    p.y = 20;
    using namespace pcl::common;
    std::cout << "p/2: " << p/2 << "\n";
    std::cout << "2/p: " << 2/p << "\n";
    std::cout << "p-2: " << p-2 << "\n";
    std::cout << "2-p: " << 2-p << "\n";
```
output:
```
p/2: (5,10)
2/p: (5,10)
p-2: (8,18)
2-p: (8,18)
```

That is `p/2` and `2/p` give the same result. The same problem applies to `p-2` and `2-p`.

## Expected Behavior

`2/p` should be `(2/p.x, 2/p.y)`
and
`2-p` should be `(2-p.x, 2-p.y)`

## Possible Solution

Change the following two functions
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/register_point_struct.h#L285-L286

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/register_point_struct.h#L305-L306

**Comment by kunaltyagi** [comment]
Has this been resolved?
