### ISSUE TITLE
pcl::PCLHeader is not swapped in pcl::PointCloud::swap

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2470]
## Your Environment

* PCL Version: master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L407

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L563-L571

In addition, the same goes to
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L592

## Expected Behavior

All data members including `header` and `mapping_` should be swapped.
## Current Behavior

`header` and `mapping_` are missing.
## Code to Reproduce

See the code above.
## Possible Solution

Swap `header` and `mapping_`.

**Comment by taketwo** [comment]
:+1: for swapping `header`. I'm not sure what's the purpose of the mapping field, seems like unused legacy code to me.

**Comment by csukuangfj** [comment]
@taketwo 
It seems that `mapping_` is used only by
https://github.com/PointCloudLibrary/pcl/blob/d1d59c63e572b88f8c48f006095732d66aae301e/common/include/pcl/point_cloud.h#L600-L607

But `getMapping()` is never used in the project, so `mapping_` does not need to be swapped.

PS: `mapping_` and `getMapping()` might be removed from the project.
