### ISSUE TITLE
the header of a point cloud is not printed out

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2471]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L609-L626

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L407
is not printed out.

## Expected Behavior

`header` should also be printed.
## Current Behavior

But it is not.
## Code to Reproduce

See the code above
## Possible Solution

Print `header`.

**Comment by taketwo** [comment]
A pull request is welcome!
