### ISSUE TITLE
No assignment operator for pcl::PointCloud

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2472]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L199-L205

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_cloud.h#L204
uses the default assignment operator provided by the compiler.

If the default assignment is fine, why is there a need to provide a customized copy constructor?

## Expected Behavior

If a customized copy constructor is provided, then the assignment operator should also be implemented.
## Current Behavior

The assignment operator is missing.
## Code to Reproduce

See the code above.
## Possible Solution

Implement the assignment operator or remove the copy constructors.

**Comment by csukuangfj** [comment]
The same problem exists for
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/pcl_base.h#L82

**Comment by taketwo** [comment]
The copy constructor you quoted is supplied with the following comment:

> Copy constructor (needed by compilers such as Intel C++)

I'm not familiar with Intel C++, so can not confirm or disprove this statement. @svenevs you use it, right? Maybe you can comment?

**Comment by svenevs** [comment]
I have 2017 available. I'm not exactly sure what to test though.

1. Comment out the copy constructor.
2. Compile PCL
3. ???

Assuming 1 and 2 work, what else should I check here?

**Comment by svenevs** [comment]
Ok I will try and compile PCL with that commented out when I'm back at that machine tomorrow
