### ISSUE TITLE
Misleading comment in file point_types_conversion.h

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2473]
## Your Environment

* PCL Version: the master branch

## Context

The comment
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L49-L52
says
 - red, green, blue and intensity are in the range [0, 1]
 - h is -1 when s is 0

But
 - red, green blue are in the range [0, 255]
 - h is 0 when s is 0
See the code below

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L151
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L155-L156

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L201-L203
## Expected Behavior

The comment should be updated according to the implementation.

## Current Behavior

They two do not match.
## Code to Reproduce

See the code above.
## Possible Solution

Correct the comment.

**Comment by taketwo** [comment]
Agree, the comment is wrong.
