### ISSUE TITLE
Error in pcl::compute3DCentroid

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2480]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L49-L75

`cp` might be 0 which causes problems for
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L72

and violates the comments
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/centroid.h#L60
which is set to 0 at the entry of the function.
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L53-L54

## Expected Behavior

Early return when the cloud is empty.
## Current Behavior

Potential division by 0.
It definitely happens when the input cloud is empty.

## Code to Reproduce

See the code above.
## Possible Solution

Do early return when the input point cloud is empty.

**Comment by csukuangfj** [comment]
The same problem exists for
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L103-L120
`centroid` is changed even if the return value is 0. In addition, it causes division by 0 when all points are invalid.

**Comment by csukuangfj** [comment]
It happens that nearly all functions in 
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/impl/centroid.hpp
subject to this kind of problem.

**Comment by taketwo** [comment]
Hm, there even seems to be a test case for empty point clouds:

https://github.com/PointCloudLibrary/pcl/blob/abd1b93189867443fa9e01846e92e09d640f0a67/test/common/test_centroid.cpp#L66-L68

However it does not fail. But you are definitely right and very welcome to submit a PR fixing all affected functions.

**Comment by csukuangfj** [comment]
@taketwo 
Yes, when it is empty, it does not fail because of the following statement
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L82-L83

Furthermore, the test case covers only
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L78-L81

but not

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L49-L51

When the cloud is not empty but all points are invalid, then the problem division by zero still exists for
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/centroid.hpp#L78-L80

**Comment by adityamwagh** [comment]
Is this issue fixed?

**Comment by larshg** [comment]
> Is this issue fixed?

Not yet, but the pending PR seems ready to merge after a rebase, due to conflicts.

**Comment by larshg** [comment]
@mvieth is this one also fixed by #4983?

**Comment by mvieth** [comment]
> @mvieth is this one also fixed by #4983?

No, I didn't touch `compute3DCentroid` in that pull request

**Comment by mvieth** [comment]
Fixed by #5181
