### ISSUE TITLE
division by 0

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2481]
## Your Environment

* PCL Version: the master branch

## Context

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/common/impl/common.hpp#L80
## Expected Behavior

It should check for 0s before performing divisions.
## Current Behavior

Division by 0 might occur.
## Code to Reproduce

See code above.
## Possible Solution

Check for 0 before doing division.

**Comment by jatin69** [comment]
Hi, what is the value of `mean` you expect if `values.size ()` is 0 ?

**Comment by csukuangfj** [comment]
@jatin69 
thanks for the comment.

One alternative is to do an early return when the vector is empty. For example, it can return false to
indicate that the vector is empty.

**Comment by SergioRAgostinho** [comment]
Having the preservation of the function signature in mind I would simply throw an exception. Assuming we don't preserve the function signature, I would modify actually modify it to return the mean value instead of `void`, so it would still require the exception.

**Comment by jatin69** [comment]
I agree with @SergioRAgostinho 
Throwing an exception, "input array empty" would be the right way to go while preserving the function signature. Should I go ahead with this?

**Comment by SergioRAgostinho** [comment]
Sure. Help is always welcome :)

**Comment by csukuangfj** [comment]
@SergioRAgostinho 

In the context of this function, the return type is not part of the function signature.

**Comment by SergioRAgostinho** [comment]
> In the context of this function, the return type is not part of the function signature.\

Agreed. Although in this case, between returning a (false) bool or throwing the exception, I'm personally more inclined towards the exception.
