### ISSUE TITLE
narf keypoints extraction bug

### ISSUE THREAD

**Issue by rpfly3** [PointCloudLibrary/pcl#2482]
## Code

http://pointclouds.org/documentation/tutorials/narf_keypoint_extraction.php#narf-keypoint-extraction

## Problem
I was testing the narf keypoint extraction of above example. When I run the program with some pcd file, it can run. When I run it without pcd file, it throws segmentation fault at range_image.createFromPointCloud. I "fixed" this by use make_shared to create the pointer. However, if I run it with pcd file, it throws segmentation fault at the same function. 

Does anyone have an idea of what the problem is?

## Environment

* Operating System and version: Ubuntu 16.04
* Compiler: g++ 5.4.0
* PCL Version: 1.8.1

## Others

Does anyone have the same pcd file as used in the example? I want to test the program with that example.

**Comment by mvieth** [comment]
Likely fixed by https://github.com/PointCloudLibrary/pcl/pull/5149 , otherwise feel free to create a new issue
