### ISSUE TITLE
incorrect info given in the doc: writing pcd

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2484]
## Your Environment

* PCL Version: the master branch

## Context

The doc http://pointclouds.org/documentation/tutorials/writing_pcd.php#writing-pcd
gives the structure of the type
```.cpp
// \brief A point structure representing Euclidean xyz coordinates.
struct PointXYZ
{
  float x;
  float y;
  float z;
};
```
which is incorrect.
## Expected Behavior

It should give the correct memory layout, otherwise it is confusing for beginners.

**Comment by taketwo** [comment]
This is indeed not correct, however I'm not sure if a beginner needs to know about extra padding and union tricks. I would propose to remove the snippet and just say:

> The type of each point is set to `pcl::PointXYZ`, which is a structure that has `x`, `y`, and `z` fields.

@SergioRAgostinho?

**Comment by csukuangfj** [comment]
I agree. No info is better than bad info.

**Comment by SergioRAgostinho** [comment]
Ok by me.
