### ISSUE TITLE
confilict info in the doc: using_pcl_pcl_config

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2485]
## Your Environment

* PCL Version: the master branch

## Context

The tutorial at http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php#using-pcl-pcl-config says
> Let us say the project is placed under /PATH/TO/MY/GRAND/PROJECT that contains a lonely cpp file name pcd_write.cpp (copy it from the Writing Point Cloud data to PCD files tutorial). In the same folder, create a file named CMakeLists.txt that contains:
>
>cmake_minimum_required(VERSION 2.6 FATAL_ERROR)
project(MY_GRAND_PROJECT)
find_package(PCL 1.3 REQUIRED COMPONENTS common io)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_executable(pcd_write_test pcd_write.cpp)
target_link_libraries(pcd_write_test ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES})

But the actual CMakeLists.txt in http://pointclouds.org/documentation/tutorials/writing_pcd.php#writing-pcd
is
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/doc/tutorials/content/sources/pcd_write/CMakeLists.txt#L1-L12

## Expected Behavior

The info described in the tutorial should match.

## Current Behavior

They do not match.
## Code to Reproduce

See links above.
## Possible Solution

Correct the tutorial.

**Comment by csukuangfj** [comment]
then we have to change the CMakeLists.txt for all the tutorial code.

**Comment by SergioRAgostinho** [comment]
I believe what we we need to add is a note to all of these stating that from 1.9.0 onwards there's no need to explicitly include definitions, includes, etc... and provide an example of how the CMakeLists.txt now look. Old users are able to work with the old setup and new users can just shortcut most of the procedure.
