### ISSUE TITLE
dead link to RusuDissertation in the tutorial how_features_work.rst

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2504]
## Your Environment

* PCL Version: the master branch

## Context

The link

http://files.rbrusu.com/publications/RusuPhDThesis.pdf

in 

https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/how_features_work.rst

is not available

## Expected Behavior

The link should be accessible.
## Current Behavior

It is unaccessible.
## Code to Reproduce

Access the link above.
## Possible Solution

Fix the link.

**Comment by taketwo** [comment]
Here is a link to the thesis in the TUM library: http://mediatum.ub.tum.de/doc/800632/941254.pdf. I think it is future-proof to use this one.
