### ISSUE TITLE
Consider removing `mapping_` and `getMapping()` from `PointCloud`

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#2506]
It seems that `mapping_` is used only by
https://github.com/PointCloudLibrary/pcl/blob/d1d59c63e572b88f8c48f006095732d66aae301e/common/include/pcl/point_cloud.h#L600-L607

But `getMapping()` is never used in the project, so `mapping_` does not need to be swapped.

PS: `mapping_` and `getMapping()` might be removed from the project.

_Originally posted by @csukuangfj in https://github.com/PointCloudLibrary/pcl/issues/2470#issuecomment-425825284_

**Comment by SergioRAgostinho** [comment]
👍 it seems to be there since the first commit a024ad22dfe2665e31edb3d1f1b199bab834548c and nothing was using it back then.

**Comment by taketwo** [comment]
Also consider moving `detail::FieldMapping` and `MsgFieldMap` to "conversions.h", because this is the only place they are used.

**Comment by larshg** [comment]
This one can be closed?

**Comment by kunaltyagi** [comment]
I think so. 1.12 will take care of actually removing the variable

**Comment by larshg** [comment]
Yeah, its removed in #4341.
