### ISSUE TITLE
PCLBase::getIndices api discussion

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2514]
https://github.com/PointCloudLibrary/pcl/blob/d1d59c63e572b88f8c48f006095732d66aae301e/common/include/pcl/pcl_base.h#L131-L136

We cannot write
```
 inline IndicesPtr const  
 getIndices () **const** { return (indices_); } 
```
since overloading in c++ does not consider the return type, we will get compile error if a `const` is appended.

Shoud we change
```.cpp
 inline IndicesPtr const  
 getIndices () { return (indices_); } 
```

to
```.cpp
 inline IndicesPtr  
 getIndices () { return (indices_); } 
```
@taketwo @SergioRAgostinho

_Originally posted by @csukuangfj in https://github.com/PointCloudLibrary/pcl/issues/2501#issuecomment-425896181_

**Comment by csukuangfj** [comment]
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/common/include/pcl/pcl_base.h#L135-L136
can be invoked only by `const PCLBase`

If you have a non-const instance of `PCLBase`, then you will always get `IndicesPtr const`

**Comment by SergioRAgostinho** [comment]
> Shoud we change
> ```.cpp
>  inline IndicesPtr const  
>  getIndices () { return (indices_); } 
> ```
> 
> to
> ```.cpp
>  inline IndicesPtr  
>  getIndices () { return (indices_); } 
> ```

AFAIK that `const`qualifier on the return type is useless, so I'm ok with that.

> can be invoked only by const PCLBase
> 
> If you have a non-const instance of PCLBase, then you will always get IndicesPtr const
> 

Agreed.

Regarding the current api this it how I would do if I had to redo it keeping the same attributes in the class. http://cpp.sh/82dqq
```cpp
#include <memory>
#include <vector>
#include <iostream>

typedef std::shared_ptr<std::vector<int>> IdxPtr;
typedef std::shared_ptr<const std::vector<int>> IdxConstPtr;

struct S
{
  IdxPtr idx;

  S () : idx (new std::vector<int> ()) {}

  const IdxPtr& getIdx ()
  {
    std::cout << "Calling non-const getIdx" << std::endl;
    return idx;
  }

  IdxConstPtr getIdx () const
  {
    std::cout << "Calling const getIdx" << std::endl;
    return idx;
  }
};

void
print_use_count (const S& s)
{
  std::cout << "Use count of pointer (" << s.idx.get () << "): " << s.idx.use_count () << std::endl;
}

int
main ()
{
  S s;
  const S cs;

  // Just want to see the indices
  const IdxPtr& ref_s = s.getIdx ();
  // const IdxPtr& ref_cs = cs.getIdx (); //doesn't work

  // A new object is being created and temporary bounded for the lifetime of the ref
  const IdxConstPtr& ref_cs = cs.getIdx ();
  print_use_count (s);
  print_use_count (cs);
  ref_cs->size();

  // Want to make a new shared pointer which is modifiable
  IdxPtr ptr_s = s.getIdx ();
  // IdxPtr ptr_cs = cs.getIdx (); //doesn't work
  IdxConstPtr ptr_cs = cs.getIdx ();
  print_use_count (s);
  print_use_count (cs);
  ptr_s.reset ();
  ptr_cs.reset ();

  // Want to make a new shared pointer which is not modifiable
  IdxConstPtr cptr_s = s.getIdx ();
  IdxConstPtr cptr_cs = cs.getIdx ();
  print_use_count (s);
  print_use_count (cs);
  cptr_s.reset ();
  cptr_cs.reset ();
  return 0;
}
```

**Comment by csukuangfj** [comment]
```.cpp
  const IdxPtr& getIdx ()
  {
    std::cout << "Calling non-const getIdx" << std::endl;
    return idx;
  }
```
what is the point of adding `const` to the return value here?
