### ISSUE TITLE
non-dense point cloud becomes dense after pcl::removeNaNNormalsFromPointCloud

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2518]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/impl/filter.hpp#L96-L130

The `is_dense` field of `cloud_out` is not set in the function, which is `true` by default
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/common/include/pcl/point_cloud.h#L179-L180

So if the input point cloud is not dense, after the filtering, the output point cloud is dense even if
one of the fileds `x`, `y` or `z` is NaN .

## Expected Behavior

Set the `is_dense` field appropriately.
## Current Behavior

Currently, it is not set and uses the default value.

## Code to Reproduce

See the code above.

**Comment by taketwo** [comment]
You are right, the output cloud is always dense, so the field should be set. I propose to copy this block from another function:

https://github.com/PointCloudLibrary/pcl/blob/40480cdb60eba3e866f8d9d6d42008b8d5ed8576/filters/include/pcl/filters/impl/filter.hpp#L90-L91

**Comment by csukuangfj** [comment]
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/common/include/pcl/point_cloud.h#L163-L164

We have to check `x`,`y` and `z` to see whether any of them is NaN before assigning
`true` to `is_dense` as the current function deals only with normals.

**Comment by SergioRAgostinho** [comment]
This method could benefit from the use `[pcl::isFinite](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/point_tests.h)`. 

The downside is that `pcl::isFinite` is not actually implemented for a couple of types. It requires a type-trait/meta-programming magic, in order to avoid having to define the method explicitly to all newly added types.
