### ISSUE TITLE
inconsistent floating point types for filter limits.

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2525]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/passthrough.h#L215-L219
The limits are `float` in `PassThrough`

https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/voxel_grid.h#L478-L482
but are `double` in  `VoxelGrid`.

Furthermore, 
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/voxel_grid.h#L207-L208
uses `FLT_MIN` and `FLT_MAX` instead of `DBL_MIN` and `DBL_MAX` for the double type.

## Expected Behavior

The data types should be consistent, either `float` or `double`, not both.

**Comment by csukuangfj** [comment]
The two data members are not returned as references so I think there will be no problems if we change from `double` to `float` only for the data members.

As for the setter, we can use `static_cast<float>()` and for the getter, nothing needs to be done.

https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/voxel_grid.h#L410-L426

**Comment by taketwo** [comment]
> The two data members are not returned as references so I think there will be no problems if we change from double to float only for the data members.

Yes this can be done without API change, but what's the point then? It's even less consistency :laughing: 

@SergioRAgostinho OK, fine for me as well.
