### ISSUE TITLE
inconsistent handling of the boundary condition for filter_limit_min and filter_limit_max

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2527]
## Your Environment

* PCL Version: the master branch

## Context

See the code
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/impl/passthrough.hpp#L139-L152

https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/impl/voxel_grid.hpp#L293-L304

When `negative` is `true`, the boundaries are inclusive in `Passthrough` but exclusive in `VoxelGrid`.

## Expected Behavior

The boundary handling should be consistent.

**Comment by csukuangfj** [comment]
The same problem exists for
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/impl/voxel_grid.hpp#L70-L81

https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/impl/voxel_grid.hpp#L96-L107

**Comment by kunaltyagi** [comment]
Is this still an existing bug?
