### ISSUE TITLE
misleading name `leaf_size_` in voxel grid

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2528]
## Your Environment

* PCL Version: the master branch

## Context

Leaf is usually associated with a tree but the voxel grid filter has nothing to do with a tree.
The member
https://github.com/PointCloudLibrary/pcl/blob/3682b686605b5b20af4e0f6b3282f1d86a2bf1ea/filters/include/pcl/filters/voxel_grid.h#L458
is misleading. It actually represents the cell size of a voxel.

## Expected Behavior

It might be better to call it with another name (i.e., voxel_cell_size_) instead of `leaf_size_`

**Comment by taketwo** [comment]
Agree. Somehow I remember discussing this before, but can not find where. Anyway, there is a (long-standing) plan for Voxel Grid rewrite (#2211) and the rename should be addressed there.
