### ISSUE TITLE
OS X: runtime exceptions when using ImageViewer or PCLVisualizer from a single thread that is not the main thread

### ISSUE THREAD

**Issue by martyvona** [PointCloudLibrary/pcl#253]
I am getting repeatable runtime exceptions on OS X trying to use an ImageViewer or PCLVisualizer from a thread that is not the main thread.

NOTE: In all cases I am creating the object and calling APIs on it from only a single thread.  It just explodes when that thread is not the main thread.

OS X 10.8.4
PCL trunk 28d22bca0422
VTK 5.10.1

This is OS X specific.  Similar code works fine on Ubuntu.

Test case here: https://gist.github.com/martyvona/6471785

Full spew:

objc[21120]: Object 0x7ffcd90006d0 of class __NSDictionaryM autoreleased with no pool in place - just leaking - break on objc_autoreleaseNoPool() to debug
(SEVERAL MORE LIKE THAT)
2013-09-06 20:39:50.334 test_viz_from_thread[21120:1203] **\* Assertion failure in +[NSUndoManager _endTopLevelGroupings], /SourceCache/Foundation/Foundation-945.18/Misc.subproj/NSUndoManager.m:328
2013-09-06 20:39:50.336 test_viz_from_thread[21120:1203] +[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.
2013-09-06 20:39:50.338 test_viz_from_thread[21120:1203](0   CoreFoundation                      0x00007fff87c6ab06 __exceptionPreprocess + 198
        1   libobjc.A.dylib                     0x00007fff853d53f0 objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff87c6a948 +[NSException raise:format:arguments:] + 104
        3   Foundation                          0x00007fff8abf34c2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 189
        4   Foundation                          0x00007fff8ac59807 +[NSUndoManager%28NSPrivate%29 _endTopLevelGroupings] + 156
        5   AppKit                              0x00007fff901b924d -[NSApplication run] + 687
        6   libpcl_visualization.1.7.dylib      0x00000001027ec93d _ZN3pcl13visualization11ImageViewer8spinOnceEib + 253
        7   test_viz_from_thread                0x000000010276ae86 _Z2gov + 102
        8   libboost_thread-mt.dylib            0x0000000106185239 thread_proxy + 185
        9   libsystem_c.dylib                   0x00007fff8e4287a2 _pthread_start + 327
        10  libsystem_c.dylib                   0x00007fff8e4151e1 thread_start + 13)
(SEVERAL MORE LIKE THAT)
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6

**Comment by Ylannl** [comment]
I ran into this issue when trying the region growing segmentation example. Solved it by using the [PCLVisualizer](http://pointclouds.org/documentation/tutorials/pcl_visualizer.php) class instead of CloudViewer.

**Comment by themightyoarfish** [comment]
The PCLVisualizer has the same problem, actually.
