### ISSUE TITLE
Make PCLVisualizerInteractorStyle::CloudActorMapPtr public

### ISSUE THREAD

**Issue by OsePedro** [PointCloudLibrary/pcl#2540]
[`PCLVisualizerInteractorStyle::CloudActorMapPtr`](https://github.com/PointCloudLibrary/pcl/blob/e78bc5827d05034e72f439597a751cfbe7b82fce/visualization/include/pcl/visualization/interactor_style.h#L110) should be declared public, as it is used in `PCLVisualizerInteractorStyle`'s public interface.

**Comment by SergioRAgostinho** [comment]
Agreed 👍 . Please consider submitting a PR with the correction.
