### ISSUE TITLE
OrganizedPointCloudCompression Questiones

### ISSUE THREAD

**Issue by yazhouzheng** [PointCloudLibrary/pcl#2543]
Hi All, 
does anyone knows how to get OrganizedPointCloudCompression lib or compile one?

I compiled and installed PCL in my machine, but I found no OrganizedPointCloudCompression related lib, So I  found errors when compile my code and here is the errors.
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: bool __cdecl pcl::io::OrganizedPointCloudCompression<struct pcl::PointXYZRGBA>::decodePointCloud(class std::basic_istream<char,struct std::char_traits<char> > &,class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZRGBA> > &,bool)" (?decodePointCloud@?$OrganizedPointCloudCompression@UPointXYZRGBA@pcl@@@io@pcl@@QEAA_NAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEAV?$shared_ptr@V?$PointCloud@UPointXYZRGBA@pcl@@@pcl@@@boost@@_N@Z)	StreamCompression	D:\asher\project\visual studio 2015\DracoLib\StreamCompression\main.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __cdecl pcl::io::OrganizedPointCloudCompression<struct pcl::PointXYZRGBA>::encodePointCloud(class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZRGBA> const > const &,class std::basic_ostream<char,struct std::char_traits<char> > &,bool,bool,bool,int)" (?encodePointCloud@?$OrganizedPointCloudCompression@UPointXYZRGBA@pcl@@@io@pcl@@QEAAXAEBV?$shared_ptr@$$CBV?$PointCloud@UPointXYZRGBA@pcl@@@pcl@@@boost@@AEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@_N22H@Z.

Best Regards
Asher

## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

**Comment by SergioRAgostinho** [comment]
The documentation page is [here](http://docs.pointclouds.org/trunk/classpcl_1_1io_1_1_organized_point_cloud_compression.html).

- It belong to the io module.
- It's header is at `<pcl/compression/organized_pointcloud_compression.h>`

It is installed only if you have the libpng and OpenNi or OpenNi2

https://github.com/PointCloudLibrary/pcl/blob/4f90f3963433fca8006dc64cce915d8d848e585e/io/CMakeLists.txt#L299-L309

**Comment by yazhouzheng** [comment]
> The documentation page is [here](http://docs.pointclouds.org/trunk/classpcl_1_1io_1_1_organized_point_cloud_compression.html).
> 
> * It belong to the io module.
> * Its header is at `<pcl/compression/organized_pointcloud_compression.h>`
> 
> It is installed only if you have the libpng and OpenNi or OpenNi2
> 
> [pcl/io/CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/blob/4f90f3963433fca8006dc64cce915d8d848e585e/io/CMakeLists.txt#L299-L309)
> 
> Lines 299 to 309 in [4f90f39](/PointCloudLibrary/pcl/commit/4f90f3963433fca8006dc64cce915d8d848e585e)
> 
>  if(PNG_FOUND) 
>    list(APPEND compression_incs 
>        include/pcl/compression/organized_pointcloud_conversion.h 
>        include/pcl/compression/libpng_wrapper.h 
>        ) 
>    if(WITH_OPENNI OR WITH_OPENNI2) 
>      list(APPEND compression_incs 
>        include/pcl/compression/organized_pointcloud_compression.h 
>        ) 
>    endif() 
>  endif(PNG_FOUND)

**Comment by yazhouzheng** [comment]
Thanks, I've passed the compile and it can works when do the encode, but I can't do the decode based on the previous encode file. My code will read a continuous ply file to imitate the point cloud video and save it locally, does there has a specification of organized stream compression? or this interface need generate every compressed file for every frame(I am testing this kind of situation now)?

**Comment by kunaltyagi** [comment]
Please use discord or StackExchange for non-library-intrinsics (usage only) related questions
