### ISSUE TITLE
Revise cloud_composer dependency toolchain - Windows

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2551]
Hi @SergioRAgostinho, here is the report of my investigations.

With https://github.com/claudiofantacci/pcl/commit/82f17ec1410f1d07e754a76d3653d229e5004330 I can enable and compile correctly all apps. However, `cloud_composer` seems to find all the dependencies (even Qt4, that I don't have, but it is not apparently a problem...!), but fails to compile.
If I run the same configuration on my macOS, I get `cloud_composer: Cloud composer requires QVTK` and the app is skipped.

I'm not an expert of Qt dependency and toolchain, but I would say that `cloud_composer` should be skipped on Windows as well.

_Originally posted by @claudiofantacci in https://github.com/PointCloudLibrary/pcl/issues/2539#issuecomment-429313345_

**Comment by kunaltyagi** [comment]
We don't have VTK on Windows CI. This also needs help from @PointCloudLibrary/testers-windows

**Comment by larshg** [comment]
As I read the lines https://github.com/PointCloudLibrary/pcl/blob/c262ec63b1e95bf629b1011a25e87df0ade4e9f1/apps/cloud_composer/CMakeLists.txt#L11-L50.

There is check for VTK, QT5, and QVTK. If either of those is not found, it should be disabled.

Qt4 is not explicitly checked for, so this could be the culprint, but doesn't explain why QVTK_FOUND should somehow be TRUE even if it is not found.
