### ISSUE TITLE
Segmentation Fault: pcl::RangeImage::getImagePoint()

### ISSUE THREAD

**Issue by tcxxxx** [PointCloudLibrary/pcl#2557]
## Your Environment

* Operating System and version: Ubuntu 16.04 
* Compiler: gcc version 5.4.0
* PCL Version: 1.7.0

## Context

Hi all, I have encountered a problem when using the **RangeImage** class and I'm wondering if anyone has met this before. Many thanks in advance.

I was using **pcl::RangeImage**'s method **createFromPointCloud** to create a range Image when it prompted a Segmentation Fault error. Here is the code snippet:
```
...
boost::shared_ptr<pcl::RangeImage> range_image_ptr (new pcl::RangeImage);
pcl::RangeImage& range_image = *range_image_ptr;
range_image.createFromPointCloud (point_cloud, angular_resolution, pcl::deg2rad (360.0f), \
pcl::deg2rad (180.0f),scene_sensor_pose, coordinate_frame, noise_level, min_range, border_size);
...
```

The data I'm processing is the [Kitti odometry Velodyne laser data](http://www.cvlibs.net/datasets/kitti/eval_odometry.php). My codes worked well for processing most of the point cloud frames in *sequence 00* (actually it successfully processed the first 857 point cloud frames) until the problem arose when processing the *000858.bin* point cloud frame, and the point cloud file (in PCD format) is here:
[000858-pcd.zip](https://github.com/PointCloudLibrary/pcl/files/2476555/000858-pcd.zip)

## Expected Behavior

It should have successfully initialized the **RangeImage** object from the point cloud given. Actually, it worked for most of the point cloud frames I have tested on. 

## Current Behavior

It is prompting **Segmentation Fault** error. I have tried gdb and it referred to the function **pcl::RangeImage::getImagePoint()**.
![image](https://user-images.githubusercontent.com/19209239/46918436-47bbb100-cfa0-11e8-8378-c661d3dd28a8.png)

The complete code for my function is here if needed (and the whole pipeline is [here](https://github.com/tcxxxx/PCLearn/blob/master/registration_class_pipeline/registration.cpp)):
```
void narfKeyPoints(const PointCloud::Ptr cloud_src, \
  const PointCloud::Ptr keyPoints_NARF)
{
    //Parameters
    float angular_resolution = 0.5f;
    float support_size = 0.2f;

    PointCloud& point_cloud = *cloud_src;
    pcl::PointCloud<pcl::PointWithViewpoint> far_ranges;
    pcl::RangeImage::CoordinateFrame coordinate_frame = pcl::RangeImage::CAMERA_FRAME;
    Eigen::Affine3f scene_sensor_pose (Eigen::Affine3f::Identity ());

    angular_resolution = pcl::deg2rad (angular_resolution);
    scene_sensor_pose = Eigen::Affine3f (Eigen::Translation3f (point_cloud.sensor_origin_[0],
                                                               point_cloud.sensor_origin_[1],
                                                               point_cloud.sensor_origin_[2])) *
                        Eigen::Affine3f (point_cloud.sensor_orientation_);

    // -----Create RangeImage from the PointCloud-----
    float noise_level = 0.0;
    float min_range = 0.0f;
    int border_size = 1;
    boost::shared_ptr<pcl::RangeImage> range_image_ptr (new pcl::RangeImage);
    pcl::RangeImage& range_image = *range_image_ptr;
    range_image.createFromPointCloud (point_cloud, angular_resolution, pcl::deg2rad (360.0f), pcl::deg2rad (180.0f),
                                      scene_sensor_pose, coordinate_frame, noise_level, min_range, border_size);
    range_image.integrateFarRanges (far_ranges);

    // --------------------------------
    // -----Extract NARF keypoints-----
    // --------------------------------
    pcl::RangeImageBorderExtractor range_image_border_extractor;
    pcl::NarfKeypoint narf_keypoint_detector (&range_image_border_extractor);
    narf_keypoint_detector.setRangeImage (&range_image);
    narf_keypoint_detector.getParameters ().support_size = support_size;
    //narf_keypoint_detector.getParameters ().add_points_on_straight_edges = true;
    //narf_keypoint_detector.getParameters ().distance_for_additional_points = 0.5;

    pcl::PointCloud<int> keypoint_indices;
    narf_keypoint_detector.compute (keypoint_indices);
    std::cout << "Found "<<keypoint_indices.points.size ()<<" key points.\n";

    PointCloud& keypoints = *keyPoints_NARF;
    keypoints.points.resize (keypoint_indices.points.size ());
    for (size_t i=0; i<keypoint_indices.points.size (); ++i)
        keypoints.points[i].getVector3fMap () = range_image.points[keypoint_indices.points[i]].getVector3fMap ();
}
```

I am quite confused about why the problem came with this specific frame if there is a problem with my codes. If anyone has any thoughts on this, please share with me. Thanks a lot in advance.

**Comment by tcxxxx** [comment]
This thread seems like a similar situation: [narf keypoints extraction bug #2482 ](https://github.com/PointCloudLibrary/pcl/issues/2482).

**Comment by ChaoWang-create** [comment]
Hello,when I use the createFromPointCloud function,I have the same question,so I want to ask you how to solve the question?Thanks.

**Comment by Eikeike** [comment]
For me, I figured the problem is actually in [this line of code](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/range_image/impl/range_image.hpp#:~:text=angle_y%20%3D%20asinLookUp%20(transformedPoint%5B1%5D/range)%3B). Whenever you have a point with range=0, there is a division by 0, leading to a NaN and eventually to a segmentation fault. My solution was to filter my pointcloud and remove all points that are too close (<0.01m) to my sensor pose.
