### ISSUE TITLE
error: ‘Octree2BufBase’ was not declared in this scope

### ISSUE THREAD

**Issue by RogerAylagas** [PointCloudLibrary/pcl#2564]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: Cmake
* PCL Version: 1.6.0

## Context

I am trying to initialize an OctreePointCloudChangeDetector with the following code:
```
#include <pcl/point_cloud.h>
#include <pcl/octree/octree_pointcloud_changedetector.h>
#include <pcl/octree/octree_pointcloud_density.h>
#include <pcl/octree/octree2buf_base.h>
#include <iostream>
#include <vector>
#include <ctime>


int
main (int argc, char** argv)
{
  srand ((unsigned int) time (NULL));

  // Octree resolution - side length of octree voxels
  float resolution = 32.0f;

  // Instantiate octree-based point cloud change detection class
  pcl::octree::OctreePointCloudChangeDetector<pcl::PointXYZ> octree (resolution);
}
```

But while compiling this error appears:

> /usr/include/pcl-1.7/pcl/octree/octree_pointcloud_changedetector.h:64:43: error: ‘Octree2BufBase’ was not declared in this scope
>          LeafContainerT, BranchContainerT, Octree2BufBase<LeafContainerT, BranchContainerT>>

I think the issue might be caused by a wrong initialization of the object but I don't know how to initialize it.
**Can you help me with the issue?? Thank you**

**Comment by RogerAylagas** [comment]
In **usr/include/pcl-1.7/pcl/octree** the header **"octree_pointcloud_changedetector.h"** misses an include of the header **octree2buf_base.h**

CHANGELOG (in "octree_pointcloud_changedetector.h") -> add  `#include "octree2buf_base.h"`

**Comment by Achllle** [comment]
@RogerAylagas That fix resolves that error but a new one pops up:

> /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
> (.text+0x20): undefined reference to `main'
> collect2: error: ld returned 1 exit status
> ...
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j12 -l12" failed

Any ideas?
