### ISSUE TITLE
Bool PointFieldTypes in PCLPointField

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#2565]
## Your Environment
* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7
* PCL Version: Latest

## Context
I am trying to create a custom point type as shown in http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php#how-to-add-a-new-pointt-type. I then realize it's not possible to create an element with type `bool`. After a little bit of tracking, I realize the reason is because in http://docs.pointclouds.org/1.8.1/_p_c_l_point_field_8h_source.html there is no `bool` in the PointFieldTypes. 

Is this because `bool` won't work due to some complex reasons or is it just someone has to simply submit a PR to add it?

**Comment by taketwo** [comment]
I think it's a bit more complicated than editing just that file, see the discussion #1153.

I'd suggest you to simply use `uint8_t` as the field type.

**Comment by jasjuang** [comment]
@taketwo it does look a little bit more complicated than I initially thought. I will take a stab at it in the future when I got more time and if it works I will submit a PR for it

**Comment by taketwo** [comment]
Thanks! a) Feel free to reach out for discussions/advice; b) while adding `bool` consider also adding `uint64_t`, will kill two birds with the same stone.
