### ISSUE TITLE
Remove "redundant" test condition in pcl_targets.cmake.

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2569]
@jspricke Actually, do you see any reason for this test you referenced:

https://github.com/PointCloudLibrary/pcl/blob/a602b19cbb392bc16a26498443c3ba5010bd45f3/cmake/pcl_targets.cmake#L113

Why isn't the first part of the condition sufficient? Looking at the Git history, this was added as a single commit and does not provide any motivation. Maybe we just drop it? Or better after the release?

_Originally posted by @taketwo in https://github.com/PointCloudLibrary/pcl/pull/2563#issuecomment-431290683_

**Comment by jspricke** [comment]
my best bet would be https://cmake.org/cmake/help/latest/policy/CMP0012.html bot no idea otherwise.
