### ISSUE TITLE
Detecting people on a ground plane with RGB-D data using zed camera point cloud

### ISSUE THREAD

**Issue by itabr** [PointCloudLibrary/pcl#2571]
I am trying to use ground-based people detection using zed camera. the algorithm works good with Kinect but using the Zed camera point cloud, the clusters have out of bound values. I was wondering if anybody tried to use PCL with zed camera and encountered a similar issue. how is the point cloud generated from zed is different that Kinect_v2?

## Your Environment
* Operating System and version: ubuntu 16.04
* PCL Version: latest

## Expected Behavior
to have clusters with values within the bound, in zed the values come out really huge.

## Current Behavior
using the zed camera point cloud the clusters have huge value for the [top](https://github.com/PointCloudLibrary/pcl/blob/master/people/include/pcl/people/impl/ground_based_people_detection_app.hpp#L405) and [bottom](https://github.com/PointCloudLibrary/pcl/blob/master/people/include/pcl/people/impl/ground_based_people_detection_app.hpp#L407) which causes the detection to fail.

**Comment by mvieth** [comment]
I am closing this since it is _very_ application/hardware specific and, as you said, the detection algorithm seems to be ok. If you still have this issue, try asking the question in the discord community chat.
