### ISSUE TITLE
Adding PLY IO headers gives error at compile time

### ISSUE THREAD

**Issue by funmonty** [PointCloudLibrary/pcl#2583]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc
* PCL Version: 1.8.1

## Context
 I'm trying to add PLY headers for saving pointcloud as ply. I added `#include "pcl/io/ply_io.h`"
 to my application. When I run my application, my console is flooded with errors from ply_parser.h. Once I remove `#include "pcl/io/ply_io.h",` the error are gone. Am I missing anything or is it a bug? Has it got anything to do with the versions of the dependencies I installed?

## Expected Behavior
It should compile my application and I should be able to use the ply APIs.

## Current Behavior
 It throws the errors as follows : 

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(98): error: qualified name is not allowed

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(98): error: explicit type is missing ("int" assumed)

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(98): error: expected a ";"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(99): error: identifier "element_callbacks_type" is undefined

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(127): error: qualified name is not allowed

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(127): error: explicit type is missing ("int" assumed)

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(127): error: expected a ";"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(133): warning: parsing restarts here after previous syntax error

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(134): error: identifier "callbacks" is undefined

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(200): error: namespace "boost" has no member "tuple"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(200): error: expected a ">"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(204): warning: parsing restarts here after previous syntax error

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(204): error: expected an identifier

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(204): error: expected a ")"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(204): error: expected an identifier

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(218): error: namespace "boost::mpl" has no member "transform"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(218): error: expected a ">"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(218): error: too many arguments for class template "boost::mpl::fold"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(216): error: not a class or struct name

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(218): error: class or struct definition is missing

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(229): error: qualified name is not allowed

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(229): error: explicit type is missing ("int" assumed)

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(229): error: expected a ";"

/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h(230): error: identifier "callbacks" is undefined

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(291): error: qualified name is not allowed

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(291): error: this declaration has no storage class or type specifier

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(291): error: expected a ";"

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(309): error: qualified name is not allowed

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(309): error: this declaration has no storage class or type specifier

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(309): error: not a valid member class or function template declaration

/usr/local/include/pcl-1.8/pcl/io/ply_io.h(309): error: expected a ";"

**Comment by taketwo** [comment]
We can not exclude a possibility that this is a bug, however I think it's highly unlikely. Please post your CMakeLists.

**Comment by funmonty** [comment]
cmake_minimum_required(VERSION 2.4)

project(sample_ply)

#find required Packages
find_package(OpenCV)
find_package(PCL 1.8 REQUIRED)
find_package(CUDA REQUIRED )
find_package(PkgConfig REQUIRED)
pkg_search_module(GLIB REQUIRED glib-2.0)
pkg_search_module(UUID REQUIRED uuid)

if(COMMAND cmake_policy)
   cmake_policy(SET CMP0003 NEW)
endif(COMMAND cmake_policy)

set(CMAKE_BUILD_TYPE Release)

#set Compiler Options
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations -Wno-dev")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_STANDARD 11)

#set(VTK_INCLUDE_DIRS "/usr/include/vtk-6.2")

#set library output path
SET(LIBRARY_OUTPUT_PATH "${CMAKE_CURRENT_LIST_DIR}/../lib/")

include_directories (${OpenCV_INCLUDE_DIRS})
include_directories (${GLIB_INCLUDE_DIRS})
include_directories (${PCL_INCLUDE_DIRS})
#include_directories (${VTK_INCLUDE_DIRS})

link_directories (${PCL_LIBRARY_DIRS})

add_definitions(${PCL_DEFINITIONS})

set_directory_properties( PROPERTIES COMPILE_DEFINITIONS "" )

cuda_add_library(sample_ply abc.cu)

target_link_libraries(
      sample_ply
      ${GLIB_LIBRARIES}
      ${CUDA_LIBS}
      ${OpenCV_LIBS}
      ${PCL_LIBRARIES}
)

**Comment by funmonty** [comment]
@taketwo, However, on adding
```
#include <boost/tuple/tuple.hpp>
#include <boost/mpl/transform.hpp>
```
these two headers in "/usr/local/include/pcl-1.8/pcl/io/ply/ply_parser.h" file, a few errors can be seen vanishing. Still, some errors exist while compiling.

**Comment by taketwo** [comment]
The problem is that you are compiling the code using CUDA compiler. One of the transitive includes is ["io/boost.h"](https://github.com/PointCloudLibrary/pcl/blob/b6994d83830a3c52f2820369af8e312218890272/io/include/pcl/io/boost.h), where a lot of Boost headers are guarded with `#ifndef __CUDACC__`, meaning that they are **not** included when compiled with CUDA compiler. I don't know exact reason for this. It's possible that many of these headers can be included without issues. Therefore I'd propose you either experiment with manually including headers until everything compiles, or split your library into two. The first one will be CUDA-free and compiled with a normal compiler. The second one will be CUDA library and will link against the first one. Of course, care should be taken that the `ply_parser.h` is not a part of the first library's interface.

**Comment by funmonty** [comment]
I tried approach one. Added

```
#include <boost/tuple/tuple.hpp>
#include <boost/mpl/transform.hpp>
#include <boost/mpl/inherit_linearly.hpp>
```
these manually in ply_parser.h. Now, there are no errors. Thanks for the suggestion.

**Comment by HelliceSaouli** [comment]
Hello, is there any solution ? I add the header mentioned above yet still has couple of errors :

ply_parser.h(227): here
ply_parser.h(227): error: incomplete type is not allowed
ply_parser.h(227): error: namespace "boost::mpl" has no member "inherit"
ply_parser.h(227): error: expected a ">"
ply_parser.h(227): error: expected a ";"
