### ISSUE TITLE
test_octree compilation not working vcpkg 

### ISSUE THREAD

**Issue by rfsch** [PointCloudLibrary/pcl#2584]
## Your Environment

* Operating System and version: Windows 10 64 bit
* Compiler: VS 2017 
* PCL Version: 1.8.1 

## Context

I am trying to compile test_octree in Visualstudio 2017 and it fails with below error. PCL has been correctly installed using vcpkg. vcpkg integrate install has been executed. What is the problem ? 
## Current Behavior

> Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	22 unresolved externals	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\x64\Release\ConsoleApplication4.exe	1	
Error (active)	E0243	class or struct definition is missing	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_calendar.hpp	28	
Error (active)	E0065	expected a ';'	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_month.hpp	59	
Error (active)	E0260	explicit type is missing ('int' assumed)	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_month.hpp	59	
Error (active)	E0020	identifier "month_map_ptr_type" is undefined	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_month.hpp	77	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	62	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	64	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	65	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	66	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	67	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	68	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	69	
Error (active)	E0070	incomplete type is not allowed	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\date.hpp	70	
Error (active)	E0135	namespace "boost" has no member "shared_ptr"	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_month.hpp	59	
Error (active)	E0135	namespace "boost::date_time" has no member "months_of_year"	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_month.hpp	57	
Error (active)	E1018	namespace "boost::date_time" has no member class "gregorian_calendar_base"	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_calendar.hpp	28	
Error (active)	E0262	not a class or struct name	ConsoleApplication4	C:\vcpkg\installed\x64-windows\include\boost\date_time\gregorian\greg_calendar.hpp	28	
Error	LNK2001	unresolved external symbol "bool __cdecl testing::internal::IsTrue(bool)" (?IsTrue@internal@testing@@YA_N_N@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::GetBoolAssertionFailureMessage(class testing::AssertionResult const &,char const *,char const *,char const *)" (?GetBoolAssertionFailureMessage@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAssertionResult@2@PEBD11@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::internal::StringStreamToString(class std::basic_stringstream<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?StringStreamToString@internal@testing@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$basic_stringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class testing::AssertionResult __cdecl testing::AssertionFailure(void)" (?AssertionFailure@testing@@YA?AVAssertionResult@1@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class testing::AssertionResult __cdecl testing::AssertionSuccess(void)" (?AssertionSuccess@testing@@YA?AVAssertionResult@1@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class testing::AssertionResult __cdecl testing::internal::DoubleNearPredFormat(char const *,char const *,char const *,double,double,double)" (?DoubleNearPredFormat@internal@testing@@YA?AVAssertionResult@2@PEBD00NNN@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class testing::AssertionResult __cdecl testing::internal::EqFailure(char const *,char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?EqFailure@internal@testing@@YA?AVAssertionResult@2@PEBD0AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1_N@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "class testing::TestInfo * __cdecl testing::internal::MakeAndRegisterTestInfo(char const *,char const *,char const *,char const *,struct testing::internal::CodeLocation,void const *,void (__cdecl*)(void),void (__cdecl*)(void),class testing::internal::TestFactoryBase *)" (?MakeAndRegisterTestInfo@internal@testing@@YAPEAVTestInfo@2@PEBD000UCodeLocation@12@PEBXP6AXXZ3PEAVTestFactoryBase@12@@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual void __cdecl testing::Test::SetUp(void)" (?SetUp@Test@testing@@MEAAXXZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual void __cdecl testing::Test::TearDown(void)" (?TearDown@Test@testing@@MEAAXXZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "protected: __cdecl testing::Test::Test(void)" (??0Test@testing@@IEAA@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl testing::Message::GetString(void)const " (?GetString@Message@testing@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: int __cdecl testing::UnitTest::Run(void)" (?Run@UnitTest@testing@@QEAAHXZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: static class testing::UnitTest * __cdecl testing::UnitTest::GetInstance(void)" (?GetInstance@UnitTest@testing@@SAPEAV12@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual __cdecl testing::Test::~Test(void)" (??1Test@testing@@UEAA@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: void __cdecl testing::internal::AssertHelper::operator=(class testing::Message const &)const " (??4AssertHelper@internal@testing@@QEBAXAEBVMessage@2@@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl testing::AssertionResult::AssertionResult(class testing::AssertionResult const &)" (??0AssertionResult@testing@@QEAA@AEBV01@@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl testing::internal::AssertHelper::AssertHelper(enum testing::TestPartResult::Type,char const *,int,char const *)" (??0AssertHelper@internal@testing@@QEAA@W4Type@TestPartResult@2@PEBDH1@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl testing::internal::AssertHelper::~AssertHelper(void)" (??1AssertHelper@internal@testing@@QEAA@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl testing::Message::Message(void)" (??0Message@testing@@QEAA@XZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "void const * __cdecl testing::internal::GetTestTypeId(void)" (?GetTestTypeId@internal@testing@@YAPEBXXZ)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl testing::InitGoogleTest(int *,char * *)" (?InitGoogleTest@testing@@YAXPEAHPEAPEAD@Z)	ConsoleApplication4	C:\Users\RS\Source\Repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1

**Comment by larshg** [comment]
This can be closed as vcpkg currently run 1.9.1 of PCL. But it looks like a lot of libraries aren't well linked to the application.
