### ISSUE TITLE
hdl_grabber.cpp errors when compiling

### ISSUE THREAD

**Issue by goldenminerlmg** [PointCloudLibrary/pcl#2586]
Hi!
when I compile the source code, there are some errors:
I used Ubuntu16.04 and have run:
sudo apt-get install libpcap-*

here are the errors:
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp: In member function ‘void pcl::HDLGrabber::readPacketsFromPcap()’:
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:655:16: error: ‘PCAP_ERRBUF_SIZE’ was not declared in this scope
   char errbuff[PCAP_ERRBUF_SIZE];
                ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:657:3: error: ‘pcap_t’ was not declared in this scope
   pcap_t *pcap = pcap_open_offline (pcap_file_name_.c_str (), errbuff);
   ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:657:11: error: ‘pcap’ was not declared in this scope
   pcap_t *pcap = pcap_open_offline (pcap_file_name_.c_str (), errbuff);
           ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:657:63: error: ‘errbuff’ was not declared in this scope
   pcap_t *pcap = pcap_open_offline (pcap_file_name_.c_str (), errbuff);
                                                               ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:657:70: error: ‘pcap_open_offline’ was not declared in this scope
   pcap_t *pcap = pcap_open_offline (pcap_file_name_.c_str (), errbuff);
                                                                      ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:659:22: error: aggregate ‘pcl::HDLGrabber::readPacketsFromPcap()::bpf_program filter’ has incomplete type and cannot be defined
   struct bpf_program filter;
                      ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:669:78: error: ‘pcap_compile’ was not declared in this scope
 pcap_compile (pcap, &filter, stringStream.str ().c_str(), 0, 0xffffffff) == -1)
                                                                        ^
In file included from /home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:38:0:
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:671:104: error: ‘pcap_geterr’ was not declared in this scope
 bber::readPacketsFromPcap] Issue compiling filter: %s.\n", pcap_geterr (pcap));
                                                                             ^
/home/lmg/library/pcl-pcl-1.7.2/common/include/pcl/console/print.h:48:69: note: in definition of macro ‘PCL_WARN’
 #define PCL_WARN(...)    pcl::console::print (pcl::console::L_WARN, __VA_ARGS__
                                                                     ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:673:40: error: ‘pcap_setfilter’ was not declared in this scope
   else if (pcap_setfilter(pcap, &filter) == -1)
                                        ^
In file included from /home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:38:0:
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:675:102: error: ‘pcap_geterr’ was not declared in this scope
 rabber::readPacketsFromPcap] Issue setting filter: %s.\n", pcap_geterr (pcap));
                                                                             ^
/home/lmg/library/pcl-pcl-1.7.2/common/include/pcl/console/print.h:48:69: note: in definition of macro ‘PCL_WARN’
 #define PCL_WARN(...)    pcl::console::print (pcl::console::L_WARN, __VA_ARGS__
                                                                     ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:683:54: error: ‘pcap_next_ex’ was not declared in this scope
   int returnValue = pcap_next_ex(pcap, &header, &data);
                                                      ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:689:31: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
       lasttime.tv_sec = header->ts.tv_sec;
                               ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:690:32: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
       lasttime.tv_usec = header->ts.tv_usec;
                                ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:692:34: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
     if (lasttime.tv_usec > header->ts.tv_usec)
                                  ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:697:25: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
     uSecDelay = ((header->ts.tv_sec - lasttime.tv_sec) * 1000000) +
                         ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:698:24: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
                 (header->ts.tv_usec - lasttime.tv_usec);
                        ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:702:29: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
     lasttime.tv_sec = header->ts.tv_sec;
                             ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:703:30: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
     lasttime.tv_usec = header->ts.tv_usec;
                              ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;
          ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:706:39: error: invalid use of incomplete type ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
     enqueueHDLPacket(data + 42, header->len - 42);
                                       ^
/home/lmg/library/pcl-pcl-1.7.2/io/src/hdl_grabber.cpp:653:10: note: forward declaration of ‘struct pcl::HDLGrabber::readPacketsFromPcap()::pcap_pkthdr’
   struct pcap_pkthdr *header;

**Comment by SergioRAgostinho** [comment]
@goldenminerlmg 1.7.2 is quite old and we don't backport fixes to old versions. My best advice is to try the freshly released 1.9.0. It's well tested on 16.04.

**Comment by SergioRAgostinho** [comment]
Closing due to  inactivity.
