### ISSUE TITLE
vcpkg visualization include not installed #include <pcl/visualization/pcl_visualizer.h> missing from pcl installed include 

### ISSUE THREAD

**Issue by rfsch** [PointCloudLibrary/pcl#2590]
## Your Environment

* Operating System and version: Win10 
* Compiler: VS 2017 5.8.8
* PCL Version: 1.8.1-12 (head) 

## Context

standard installation of pcl with vcpkg does not generate visualization include directory.  

How can  the include directory get generated by pcl installation using vcpkg ? 
## Current Behavior

standard installation of pcl with vcpkg does not generate visualization include directory. 
When trying to compile a program that uses PCLVisualizer the needed include file pcl/visualization/pcl_visualizer.h is not found. 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pcl/visualization/pcl_visualizer.h': No such file or directory	velosam	c:\dld\velosam\velosam\velosam\velosim.cpp	26

**Comment by taketwo** [comment]
@UnaNancyOwen @jasjuang @claudiofantacci any comments on this?

**Comment by claudiofantacci** [comment]
The header is present in my installation which does not use vcpkg and is compiled from master.
I'm installing it now using vcpkg and see what happen.

**Comment by claudiofantacci** [comment]
My `vcpkg` installation of PCL has `pcl/visualization/pcl_visualizer.h`.

**Comment by rfsch** [comment]
Mine works now as well. But I believe it was only after I installed some other component which required vtk. Maybe it was opencv, But I am not sure. I know that when using : 
vcpkg install pcl[openni2,qt,pcap]:x64-windows --featurepackages
or maybe just  install pcl:x64-windows

I cant remember which one... But at that point pcl/visualization/pcl_visualizer.h. was missing. 

Hope that helps and does no confuse any more :)
