### ISSUE TITLE
PCL 1.8.1 on PPA launchpad is not available

### ISSUE THREAD

**Issue by funmonty** [PointCloudLibrary/pcl#2595]
## Your Environment

* Operating System and version: Ubuntu 16.04 (Nvidia - TX2)
* Compiler: gcc
* PCL Version: 1.8.1

Hi, I am using the beautiful PCL library on Nvidia TX2 device involving cuda. I want the PCL 1.8.1 version on PPA launchpad, the latest version on launchpad in still 1.7.2. Can you please update me if it is available anywhere and tell me the PPA repo name?

**Comment by jspricke** [comment]
Update your Ubuntu to 18.04:

https://packages.ubuntu.com/bionic/libpcl-dev

(I don't update the PPA anymore)

**Comment by funmonty** [comment]
Thanks @jspricke, I very much appreciate your response. Is it not possible to get it(PCL 1.8.1) for 16.04 because a majority of the devices still use 16.04.
