### ISSUE TITLE
Revise includes in io/boost.h when compiling with CUDA

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#2597]
The problem is that you are compiling the code using CUDA compiler. One of the transitive includes is "io/boost.h", where a lot of Boost headers are guarded with #ifndef __CUDACC__, meaning that they are not included when compiled with CUDA compiler. I don't know exact reason for this. It's possible that many of these headers can be included without issues. Therefore I'd propose you to experiment with manually including headers until everything compiles. 

_Originally posted by @taketwo in https://github.com/PointCloudLibrary/pcl/issues/2583#issuecomment-433422354_

> I tried approach one. Added
> #include <boost/tuple/tuple.hpp>
> #include <boost/mpl/transform.hpp>
> #include <boost/mpl/inherit_linearly.hpp>
> these manually in ply_parser.h. Now, there are no errors.

**Comment by HelliceSaouli** [comment]
Hello, is there any solution ? I add the header mentioned above yet still has couple of errors : 

ply_parser.h(227): here
ply_parser.h(227): error: incomplete type is not allowed
ply_parser.h(227): error: namespace "boost::mpl" has no member "inherit"
ply_parser.h(227): error: expected a ">"
ply_parser.h(227): error: expected a ";"

**Comment by al-tu** [comment]
hello, had problems building current pcl master when using clang + cuda. moving boost.mpl headers out of #ifdef solves the problem
https://github.com/PointCloudLibrary/pcl/pull/4783

**Comment by al-tu** [comment]
i can try moving all other headers as well, but what is important is that i'm not ci covers all possible cases and some configurations may render broken after these changes (like the configuration i used, though i guess this particular case is never guaranteed to be ok because of c++20)

**Comment by kunaltyagi** [comment]
We're in the process of removing use of such include files. This issue will soon be defunct

**Comment by mvieth** [comment]
The header [pcl/io/boost.h](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/boost.h) is not used any more and is marked deprecated. All files that previously used that header now include the needed headers from boost directly, see for example [ply_parser.h](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/ply/ply_parser.h). `#ifndef __CUDACC__` is not used any more.
Therefore I would consider this issue solved.
