### ISSUE TITLE
SupervoxelClustering extract generates "double free or corruption (out)"

### ISSUE THREAD

**Issue by fverdoja** [PointCloudLibrary/pcl#2598]
## Your Environment

* Operating System and version: Arch Linux, kernel v.4.18.16
* Compiler: gcc 8.2.1
* PCL Version: 1.8.1 (from AUR)

## Context

Trying to perform supervoxel clustering, even when using the example code provided [here](http://pointclouds.org/documentation/tutorials/supervoxel_clustering.php), results in an error.

## Expected Behavior

Running the [example code](http://pointclouds.org/documentation/tutorials/supervoxel_clustering.php) on a pcd file should produce a clustering of the pointcloud in the pcd

## Current Behavior

The execution crashes when running the `extract` function in `SupervoxelClustering` generating the following error: `double free or corruption (out)`

## Code to Reproduce

1. download the [example cpp](http://pointclouds.org/documentation/tutorials/_downloads/ea07f35bdb1c0311507a847ee6fd1428/supervoxel_clustering.cpp) file, [CMakeLists.txt](http://pointclouds.org/documentation/tutorials/_downloads/f6db2395b1d4f9e9169f232d3a62cf3a/CMakeLists.txt) and [sample pointcloud](https://github.com/PointCloudLibrary/data/blob/master/tutorials/correspondence_grouping/milk_cartoon_all_small_clorox.pcd?raw=true).
2. compile the example file (`cmake` and `make`)
3. run `./supervoxel_clustering milk_cartoon_all_small_clorox.pcd --NT`
```
> Loading point cloud...
> Extracting supervoxels!
double free or corruption (out)
```

## Possible Solution

Could this be related to #2100 ? I tried the solutions proposed there but they don't seem to work for me.

**Comment by taketwo** [comment]
I've just checked this with PCL that was compiled from source in early September, works fine. Please consider switching to the git master or wait until new release (will happen soon).

**Comment by SergioRAgostinho** [comment]
Probably today 👌

**Comment by fverdoja** [comment]
> Probably today 👌

wow that was fast! 😄 I was midway compiling from git master now, but I'll wait for the stable release then. I'll keep you posted on how it goes.

**Comment by taketwo** [comment]
But be aware that we don't manage AUR package, so the new version won't necessarily hit you soon.

**Comment by fverdoja** [comment]
Hi.
Updating to 1.9.0 fixed it. Thank you for your work.

**Comment by EngDanielAraujo** [comment]
> ## Your Environment
> * Operating System and version: Arch Linux, kernel v.4.18.16
> * Compiler: gcc 8.2.1
> * PCL Version: 1.8.1 (from AUR)
> 
> ## Context
> Trying to perform supervoxel clustering, even when using the example code provided [here](http://pointclouds.org/documentation/tutorials/supervoxel_clustering.php), results in an error.
> 
> ## Expected Behavior
> Running the [example code](http://pointclouds.org/documentation/tutorials/supervoxel_clustering.php) on a pcd file should produce a clustering of the pointcloud in the pcd
> 
> ## Current Behavior
> The execution crashes when running the `extract` function in `SupervoxelClustering` generating the following error: `double free or corruption (out)`
> 
> ## Code to Reproduce
> 1. download the [example cpp](http://pointclouds.org/documentation/tutorials/_downloads/ea07f35bdb1c0311507a847ee6fd1428/supervoxel_clustering.cpp) file, [CMakeLists.txt](http://pointclouds.org/documentation/tutorials/_downloads/f6db2395b1d4f9e9169f232d3a62cf3a/CMakeLists.txt) and [sample pointcloud](https://github.com/PointCloudLibrary/data/blob/master/tutorials/correspondence_grouping/milk_cartoon_all_small_clorox.pcd?raw=true).
> 2. compile the example file (`cmake` and `make`)
> 3. run `./supervoxel_clustering milk_cartoon_all_small_clorox.pcd --NT`
> 
> ```
> > Loading point cloud...
> > Extracting supervoxels!
> double free or corruption (out)
> ```
> 
> ## Possible Solution
> Could this be related to #2100 ? I tried the solutions proposed there but they don't seem to work for me.

Hello. I'm getting the same issue when running the [same supervoxel clustering example](https://pcl.readthedocs.io/en/latest/supervoxel_clustering.html#supervoxel-clustering) on PCL version 1.12.1 compiled from git master.

* Operating System and version: Ubuntu 22.04.1, kernel v.5.15.0-48-generic
* Compiler: gcc 11.2.0
* PCL Version: 1.12.1 (git master)
