### ISSUE TITLE
dist.h pop_t is not defined, if not define __GNUC__

### ISSUE THREAD

**Issue by dogod621** [PointCloudLibrary/pcl#2600]
## Your Environment

* Operating System and version: WIN10 1803
* Compiler: Visual Studio 2017
* PCL Version: 1.8.1

## Context

dist.h line 520: pop_t is not defined, if not define __GNUC__

compile got error: 
錯誤	C3861	'pop_t': 找不到識別項	AS	d:\pcl 1.8.1\3rdparty\flann\include\flann\algorithms\dist.h	522	

It is come from flann: https://github.com/mariusmuja/flann/issues/386

![1](https://user-images.githubusercontent.com/6807005/48106626-26847280-e277-11e8-882a-bf0ebd964d0a.png)

**Comment by taketwo** [comment]
Hi, as you correctly identified, this is a problem in FLANN package. We can not do anything about this here.
