### ISSUE TITLE
PointXYZRGBNormal type version of NormalEstimation, NormalEstimationOMP, FPFHEstimation, FPFHEstimationOMP is not in the released AllInOne lib.

### ISSUE THREAD

**Issue by dogod621** [PointCloudLibrary/pcl#2603]
## Your Environment

* Operating System and version: Win10 1803
* Compiler: Visual Studio 2017
* PCL Version: PCL 1.8.1

## Context

It will get LNK2001 Error...
Can I compile PointXYZRGBNormal type for the template by myself?
![2](https://user-images.githubusercontent.com/6807005/48168962-5f325380-e32c-11e8-888f-40c261fac7a1.png)

**Comment by taketwo** [comment]
Should be possible, try to include corresponding "hpp" file, e.g. "pcl/features/impl/normal_3d_omp.hpp" for `NormalEstimationOMP`.

**Comment by dogod621** [comment]
> Should be possible, try to include corresponding "hpp" file, e.g. "pcl/features/impl/normal_3d_omp.hpp" for `NormalEstimationOMP`.

It doesn't work... orz...

**Comment by dogod621** [comment]
I found it~~ how to undef PCL_NO_PRECOMPILE?

![e](https://user-images.githubusercontent.com/6807005/48237875-b0f9dd00-e403-11e8-9887-0b2930af34e1.png)
