### ISSUE TITLE
Has anyone ported PCL to QNX? 

### ISSUE THREAD

**Issue by darbee** [PointCloudLibrary/pcl#2606]
recently, I want to port PCL to QNX. And I realized that it depends on several other libraries, such VTK, Eigen, Boost and Flann. When VTK was transplanted, It may depend on openGL, which I have no idea which version openGL should be ported.  Any help is appreciated, thanks

**Comment by SergioRAgostinho** [comment]
The current VTK versions make use of OpenGL 2 and I believe they’re slowly rolling out OpenGL 3 features in their master branch.

Nevertheless the VTK support channels are the best place to ask info about VTK.

Cheers

--

**Comment by SergioRAgostinho** [comment]
I had a quick look into the simulation module and it seems we use OpenGL
ourselves and require version 3.3 in our shaders.

Example:
https://github.com/PointCloudLibrary/pcl/blob/master/simulation/src/single_texture.frag

**Comment by darbee** [comment]
hi  SergioRAgostinho  @SergioRAgostinho  thanks for your reply indeed. I want to know if I cross compile PCL for QNX, if I must   cross compile  VTK. Is it necessary?

**Comment by SergioRAgostinho** [comment]
VTK is an optional dependency for the project. It is a mandatory dependency of the `visualization` module and an optional dependency of the `io` module.

I.e. it is not necessary.

**Comment by darbee** [comment]
ok @SergioRAgostinho  thanks for your reply. I will try build PCL on QNX  without VTK

**Comment by MonsterBanjin** [comment]
> ok @SergioRAgostinho thanks for your reply. I will try build PCL on QNX without VTK

Hi Darbee, have you compiled PCL with just Boost, Eigen, and FLANN?
