### ISSUE TITLE
Double free or corruption error when use VLPGrabber

### ISSUE THREAD

**Issue by LiShuaixin** [PointCloudLibrary/pcl#2609]
## Your Environment

* Operating System and version: Ubuntu16.04
* Compiler: g++
* PCL Version: 1.8.1

## Current Behavior

I'm trying to read pointcloud data from a Velodyne VLP-16 lidar, which restores the sampled data as .pcap file. I want to use VLPGrabber class to read the .pcap file directly in my program. The class 'System' includes a VLPGrabber pointer member, and I try to construct the pointer in the constructor of 'System'. But there is a double free corruption error all the time. I found the VLPGrabber construction line in the script is the root of the problem.  By the way, I can run the example in the pcl/visualization/tools/vlp_viewer.cpp smoothly. What's the problem?

## Code to Reproduce

Here is the header System.h
class System
{
public:
    System(int` argc, char** argv, const bool use_viewer = false);
    
    void run();
    
public:
    std::string pcap_file_;
    std::string pos_file_;
    bool use_viewer_;
    
    pcl::VLPGrabber* vlp_grabber_;
    
    GridMap* map_;
};

Here is the constructor:
System::System(int argc, char** argv, const bool use_viewer) : use_viewer_(use_viewer)
{
    std::string pcap_file;
    pcl::console::parse_argument (argc, argv, "-pcapFile", pcap_file);
    
    std::cout << "Velodyne file was set at: " << pcap_file << std::endl;
    
    pcap_file_ = pcap_file;
    
    // Load velodyne  point cloud 
    vlp_grabber_ = new pcl::VLPGrabber( pcap_file );
   
    ...
    
    ...
}

Here is the output:
Velodyne file was set at: ../data/20181031/big_loop/2018-10-31-15-38-28_Velodyne-VLP-16-Data.pcap
*** Error in `./mapping': double free or corruption (out): 0x0000000001410040 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f16ab4a27e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f16ab4ab37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f16ab4af53c]
/usr/local/lib/libpcl_io.so.1.8(+0x16d91a)[0x7f16a9c8a91a]
/usr/local/lib/libpcl_io.so.1.8(_ZN5boost10shared_ptrIN3pcl10PointCloudINS1_8PointXYZEEEE5resetIS4_EEvPT_+0x75)[0x7f16a9c953b5]
/usr/local/lib/libpcl_io.so.1.8(_ZN3pcl10HDLGrabber10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x17e)[0x7f16a9c8d4fe]
/usr/local/lib/libpcl_io.so.1.8(_ZN3pcl10HDLGrabberC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_+0x60f)[0x7f16a9c8de8f]
/usr/local/lib/libpcl_io.so.1.8(_ZN3pcl10VLPGrabberC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x4a)[0x7f16a9ca543a]
/home/lee/experiment/6-clutter/lib/libMobile_Sensing.so(_ZN14Mobile_Sensing6SystemC1EiPPcb+0x5ed)[0x7f16ac04b16d]
./mapping(main+0x24)[0x406674]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f16ab44b830]
./mapping(_start+0x29)[0x4069e9]
======= Memory map: ========
00400000-0040e000 r-xp 00000000 08:05 2753620                            /home/lee/experiment/bin/mapping
0060d000-0060e000 r--p 0000d000 08:05 2753620                            /home/lee/experiment/bin/mapping
0060e000-0060f000 rw-p 0000e000 08:05 2753620                            /home/lee/experiment/bin/mapping
013c5000-01418000 rw-p 00000000 00:00 0                                  [heap]
7f1698000000-7f1698021000 rw-p 00000000 00:00 0 
7f1698021000-7f169c000000 ---p 00000000 00:00 0 
7f169dfe8000-7f169e00c000 r-xp 00000000 08:02 1985244                    /usr/local/lib/libvtklz4-8.0.so.1
7f169e00c000-7f169e20b000 ---p 00024000 08:02 1985244                    /usr/local/lib/libvtklz4-8.0.so.1
7f169e20b000-7f169e20c000 r--p 00023000 08:02 1985244                    /usr/local/lib/libvtklz4-8.0.so.1
7f169e20c000-7f169e20d000 rw-p 00024000 08:02 1985244                    /usr/local/lib/libvtklz4-8.0.so.1
7f169e20d000-7f169e23a000 r-xp 00000000 08:02 1985308                    /usr/local/lib/libvtkjpeg-8.0.so.1
7f169e23a000-7f169e43a000 ---p 0002d000 08:02 1985308                    /usr/local/lib/libvtkjpeg-8.0.so.1
7f169e43a000-7f169e43b000 r--p 0002d000 08:02 1985308                    /usr/local/lib/libvtkjpeg-8.0.so.1
7f169e43b000-7f169e43c000 rw-p 0002e000 08:02 1985308                    /usr/local/lib/libvtkjpeg-8.0.so.1
7f169e43c000-7f169e465000 r-xp 00000000 08:02 1985194                    /usr/local/lib/libvtkCommonMath-8.0.so.1
7f169e465000-7f169e665000 ---p 00029000 08:02 1985194                    /usr/local/lib/libvtkCommonMath-8.0.so.1
7f169e665000-7f169e666000 r--p 00029000 08:02 1985194                    /usr/local/lib/libvtkCommonMath-8.0.so.1
7f169e666000-7f169e667000 rw-p 0002a000 08:02 1985194                    /usr/local/lib/libvtkCommonMath-8.0.so.1
7f169e667000-7f169e6e9000 r-xp 00000000 08:02 1985312                    /usr/local/lib/libvtktiff-8.0.so.1
7f169e6e9000-7f169e8e8000 ---p 00082000 08:02 1985312                    /usr/local/lib/libvtktiff-8.0.so.1
7f169e8e8000-7f169e8e9000 r--p 00081000 08:02 1985312                    /usr/local/lib/libvtktiff-8.0.so.1
7f169e8e9000-7f169e8ed000 rw-p 00082000 08:02 1985312                    /usr/local/lib/libvtktiff-8.0.so.1
7f169e8ed000-7f169e921000 r-xp 00000000 08:02 1985310                    /usr/local/lib/libvtkpng-8.0.so.1
7f169e921000-7f169eb20000 ---p 00034000 08:02 1985310                    /usr/local/lib/libvtkpng-8.0.so.1
7f169eb20000-7f169eb21000 r--p 00033000 08:02 1985310                    /usr/local/lib/libvtkpng-8.0.so.1
7f169eb21000-7f169eb22000 rw-p 00034000 08:02 1985310                    /usr/local/lib/libvtkpng-8.0.so.1
7f169eb22000-7f169ec36000 r-xp 00000000 08:02 1985306                    /usr/local/lib/libvtkmetaio-8.0.so.1
7f169ec36000-7f169ee35000 ---p 00114000 08:02 1985306                    /usr/local/lib/libvtkmetaio-8.0.so.1
7f169ee35000-7f169ee37000 r--p 00113000 08:02 1985306                    /usr/local/lib/libvtkmetaio-8.0.so.1
7f169ee37000-7f169ee3c000 rw-p 00115000 08:02 1985306                    /usr/local/lib/libvtkmetaio-8.0.so.1
7f169ee3c000-7f169ee95000 r-xp 00000000 08:02 1985242                    /usr/local/lib/libvtkDICOMParser-8.0.so.1
7f169ee95000-7f169f094000 ---p 00059000 08:02 1985242                    /usr/local/lib/libvtkDICOMParser-8.0.so.1
7f169f094000-7f169f095000 r--p 00058000 08:02 1985242                    /usr/local/lib/libvtkDICOMParser-8.0.so.1
7f169f095000-7f169f098000 rw-p 00059000 08:02 1985242                    /usr/local/lib/libvtkDICOMParser-8.0.so.1
7f169f098000-7f169f0ac000 r-xp 00000000 08:02 1976060                    /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2
7f169f0ac000-7f169f2ac000 ---p 00014000 08:02 1976060                    /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2
7f169f2ac000-7f169f2ad000 r--p 00014000 08:02 1976060                    /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2
7f169f2ad000-7f169f2ae000 rw-p 00015000 08:02 1976060                    /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2
7f169f2ae000-7f169f305000 r-xp 00000000 08:02 1969139                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f169f305000-7f169f505000 ---p 00057000 08:02 1969139                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f169f505000-7f169f506000 r--p 00057000 08:02 1969139                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f169f506000-7f169f507000 rw-p 00058000 08:02 1969139                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f169f507000-7f169f550000 r-xp 00000000 08:02 1985196                    /usr/local/lib/libvtkCommonMisc-8.0.so.1
7f169f550000-7f169f74f000 ---p 00049000 08:02 1985196                    /usr/local/lib/libvtkCommonMisc-8.0.so.1
7f169f74f000-7f169f750000 r--p 00048000 08:02 1985196                    /usr/local/lib/libvtkCommonMisc-8.0.so.1
7f169f750000-7f169f752000 rw-p 00049000 08:02 1985196                    /usr/local/lib/libvtkCommonMisc-8.0.so.1
7f169f752000-7f169f7df000 r-xp 00000000 08:02 1985190                    /usr/local/lib/libvtksys-8.0.so.1
7f169f7df000-7f169f9df000 ---p 0008d000 08:02 1985190                    /usr/local/lib/libvtksys-8.0.so.1
7f169f9df000-7f169f9e0000 r--p 0008d000 08:02 1985190                    /usr/local/lib/libvtksys-8.0.so.1
7f169f9e0000-7f169f9e4000 rw-p 0008e000 08:02 1985190                    /usr/local/lib/libvtksys-8.0.so.1
7f169f9e4000-7f169fa00000 r-xp 00000000 08:02 1985232                    /usr/local/lib/libvtkzlib-8.0.so.1
7f169fa00000-7f169fbff000 ---p 0001c000 08:02 1985232                    /usr/local/lib/libvtkzlib-8.0.so.1
7f169fbff000-7f169fc00000 r--p 0001b000 08:02 1985232                    /usr/local/lib/libvtkzlib-8.0.so.1
7f169fc00000-7f169fc01000 rw-p 0001c000 08:02 1985232                    /usr/local/lib/libvtkzlib-8.0.so.1
7f169fc01000-7f169fc21000 r-xp 00000000 08:02 1985198                    /usr/local/lib/libvtkCommonSystem-8.0.so.1
7f169fc21000-7f169fe21000 ---p 00020000 08:02 1985198                    /usr/local/lib/libvtkCommonSystem-8.0.so.1
7f169fe21000-7f169fe22000 r--p 00020000 08:02 1985198                    /usr/local/lib/libvtkCommonSystem-8.0.so.1
7f169fe22000-7f169fe23000 rw-p 00021000 08:02 1985198                    /usr/local/lib/libvtkCommonSystem-8.0.so.1
7f169fe23000-7f169fe24000 rw-p 00000000 00:00 0 
7f169fe24000-7f169fe5b000 r-xp 00000000 08:02 1985200                    /usr/local/lib/libvtkCommonTransforms-8.0.so.1
7f169fe5b000-7f16a005a000 ---p 00037000 08:02 1985200                    /usr/local/lib/libvtkCommonTransforms-8.0.so.1
7f16a005a000-7f16a005c000 r--p 00036000 08:02 1985200                    /usr/local/lib/libvtkCommonTransforms-8.0.so.1
7f16a005c000-7f16a005d000 rw-p 00038000 08:02 1985200                    /usr/local/lib/libvtkCommonTransforms-8.0.so.1
7f16a005d000-7f16a0076000 r-xp 00000000 08:02 2626182                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f16a0076000-7f16a0275000 ---p 00019000 08:02 2626182                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f16a0275000-7f16a0276000 r--p 00018000 08:02 2626182                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f16a0276000-7f16a0277000 rw-p 00019000 08:02 2626182                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f16a0277000-7f16a0286000 r-xp 00000000 08:02 2626208                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f16a0286000-7f16a0485000 ---p 0000f000 08:02 2626208                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f16a0485000-7f16a0486000 r--p 0000e000 08:02 2626208                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f16a0486000-7f16a0487000 rw-p 0000f000 08:02 2626208                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f16a0487000-7f16a048a000 r-xp 00000000 08:02 2637118                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f16a048a000-7f16a0689000 ---p 00003000 08:02 2637118                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f16a0689000-7f16a068a000 r--p 00002000 08:02 2637118                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f16a068a000-7f16a068b000 rw-p 00003000 08:02 2637118                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f16a068b000-7f16a2845000 r-xp 00000000 08:02 1969508                    /usr/local/lib/libpcl_features.so.1.8.1
7f16a2845000-7f16a2a44000 ---p 021ba000 08:02 1969508                    /usr/local/lib/libpcl_features.so.1.8.1
7f16a2a44000-7f16a2b0c000 r--p 021b9000 08:02 1969508                    /usr/local/lib/libpcl_features.so.1.8.1
7f16a2b0c000-7f16a2b85000 rw-p 02281000 08:02 1969508                    /usr/local/lib/libpcl_features.so.1.8.1
7f16a2b85000-7f16a2ba8000 r-xp 00000000 08:02 1969510                    /usr/local/lib/libpcl_ml.so.1.8.1
7f16a2ba8000-7f16a2da7000 ---p 00023000 08:02 1969510                    /usr/local/lib/libpcl_ml.so.1.8.1
7f16a2da7000-7f16a2da8000 r--p 00022000 08:02 1969510                    /usr/local/lib/libpcl_ml.so.1.8.1
7f16a2da8000-7f16a2da9000 rw-p 00023000 08:02 1969510                    /usr/local/lib/libpcl_ml.so.1.8.1
7f16a2da9000-7f16a33ca000 r-xp 00000000 08:02 1985192                    /usr/local/lib/libvtkCommonCore-8.0.so.1
7f16a33ca000-7f16a35c9000 ---p 00621000 08:02 1985192                    /usr/local/lib/libvtkCommonCore-8.0.so.1
7f16a35c9000-7f16a35e7000 r--p 00620000 08:02 1985192                    /usr/local/lib/libvtkCommonCore-8.0.so.1
7f16a35e7000-7f16a35fc000 rw-p 0063e000 08:02 1985192                    /usr/local/lib/libvtkCommonCore-8.0.so.1
7f16a35fc000-7f16a35fd000 rw-p 00000000 00:00 0 
7f16a35fd000-7f16a3b61000 r-xp 00000000 08:02 1985202                    /usr/local/lib/libvtkCommonDataModel-8.0.so.1
7f16a3b61000-7f16a3d60000 ---p 00564000 08:02 1985202                    /usr/local/lib/libvtkCommonDataModel-8.0.so.1
7f16a3d60000-7f16a3d75000 r--p 00563000 08:02 1985202                    /usr/local/lib/libvtkCommonDataModel-8.0.so.1
7f16a3d75000-7f16a3d90000 rw-p 00578000 08:02 1985202                    /usr/local/lib/libvtkCommonDataModel-8.0.so.1
7f16a3d90000-7f16a3eae000 r-xp 00000000 08:02 1985206                    /usr/local/lib/libvtkCommonExecutionModel-8.0.so.1
7f16a3eae000-7f16a40ae000 ---p 0011e000 08:02 1985206                    /usr/local/lib/libvtkCommonExecutionModel-8.0.so.1
7f16a40ae000-7f16a40b7000 r--p 0011e000 08:02 1985206                    /usr/local/lib/libvtkCommonExecutionModel-8.0.so.1
7f16a40b7000-7f16a40bc000 rw-p 00127000 08:02 1985206                    /usr/local/lib/libvtkCommonExecutionModel-8.0.so.1
7f16a40bc000-7f16a4166000 r-xp 00000000 08:02 1985246                    /usr/local/lib/libvtkIOCore-8.0.so.1
7f16a4166000-7f16a4366000 ---p 000aa000 08:02 1985246                    /usr/local/lib/libvtkIOCore-8.0.so.1
7f16a4366000-7f16a436b000 r--p 000aa000 08:02 1985246                    /usr/local/lib/libvtkIOCore-8.0.so.1
7f16a436b000-7f16a436e000 rw-p 000af000 08:02 1985246                    /usr/local/lib/libvtkIOCore-8.0.so.1
7f16a436e000-7f16a4438000 r-xp 00000000 08:02 1985248                    /usr/local/lib/libvtkIOLegacy-8.0.so.1
7f16a4438000-7f16a4637000 ---p 000ca000 08:02 1985248                    /usr/local/lib/libvtkIOLegacy-8.0.so.1
7f16a4637000-7f16a463f000 r--p 000c9000 08:02 1985248                    /usr/local/lib/libvtkIOLegacy-8.0.so.1
7f16a463f000-7f16a4642000 rw-p 000d1000 08:02 1985248                    /usr/local/lib/libvtkIOLegacy-8.0.so.1
7f16a4642000-7f16a4879000 r-xp 00000000 08:02 1985214                    /usr/local/lib/libvtkImagingCore-8.0.so.1
7f16a4879000-7f16a4a79000 ---p 00237000 08:02 1985214                    /usr/local/lib/libvtkImagingCore-8.0.so.1
7f16a4a79000-7f16a4a83000 r--p 00237000 08:02 1985214                    /usr/local/lib/libvtkImagingCore-8.0.so.1
7f16a4a83000-7f16a4a85000 rw-p 00241000 08:02 1985214                    /usr/local/lib/libvtkImagingCore-8.0.so.1
7f16a4a85000-7f16a4c73000 r-xp 00000000 08:02 1985314                    /usr/local/lib/libvtkIOImage-8.0.so.1
7f16a4c73000-7f16a4e72000 ---p 001ee000 08:02 1985314                    /usr/local/lib/libvtkIOImage-8.0.so.1
7f16a4e72000-7f16a4e7c000 r--p 001ed000 08:02 1985314                    /usr/local/lib/libvtkIOImage-8.0.so.1
7f16a4e7c000-7f16a4e80000 rw-p 001f7000 08:02 1985314                    /usr/local/lib/libvtkIOImage-8.0.so.1
7f16a4e80000-7f16a4ebe000 r-xp 00000000 08:02 1975835                    /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4
7f16a4ebe000-7f16a50be000 ---p 0003e000 08:02 1975835                    /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4
7f16a50be000-7f16a50c0000 r--p 0003e000 08:02 1975835                    /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4
7f16a50c0000-7f16a50c1000 rw-p 00040000 08:02 1975835                    /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4
7f16a50c1000-7f16a50c2000 rw-p 00000000 00:00 0 
7f16a50c2000-7f16a5139000 r-xp 00000000 08:02 1974625                    /usr/lib/libOpenNI.so.0
7f16a5139000-7f16a5338000 ---p 00077000 08:02 1974625                    /usr/lib/libOpenNI.so.0
7f16a5338000-7f16a533a000 r--p 00076000 08:02 1974625                    /usr/lib/libOpenNI.so.0
7f16a533a000-7f16a533d000 rw-p 00078000 08:02 1974625                    /usr/lib/libOpenNI.so.0
7f16a533d000-7f16a533e000 rw-p 00000000 00:00 0 
7f16a533e000-7f16a537c000 r-xp 00000000 08:02 1990116                    /usr/lib/libOpenNI2.so.0
7f16a537c000-7f16a557b000 ---p 0003e000 08:02 1990116                    /usr/lib/libOpenNI2.so.0
7f16a557b000-7f16a557d000 r--p 0003d000 08:02 1990116                    /usr/lib/libOpenNI2.so.0
7f16a557d000-7f16a557e000 rw-p 0003f000 08:02 1990116                    /usr/lib/libOpenNI2.so.0
7f16a557e000-7f16a559f000 rw-p 00000000 00:00 0 
7f16a559f000-7f16a55b6000 r-xp 00000000 08:02 2626389                    /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f16a55b6000-7f16a57b5000 ---p 00017000 08:02 2626389                    /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f16a57b5000-7f16a57b6000 r--p 00016000 08:02 2626389                    /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f16a57b6000-7f16a57b7000 rw-p 00017000 08:02 2626389                    /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f16a57b7000-7f16a57db000 r-xp 00000000 08:02 2626188                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f16a57db000-7f16a59da000 ---p 00024000 08:02 2626188                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f16a59da000-7f16a59db000 r--p 00023000 08:02 2626188                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f16a59db000-7f16a59dc000 rw-p 00024000 08:02 2626188                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f16a59dc000-7f16a59f7000 r-xp 00000000 08:02 1985381                    /usr/local/lib/libvtkIOPLY-8.0.so.1
7f16a59f7000-7f16a5bf7000 ---p 0001b000 08:02 1985381                    /usr/local/lib/libvtkIOPLY-8.0.so.1
7f16a5bf7000-7f16a5bf8000 r--p 0001b000 08:02 1985381                    /usr/local/lib/libvtkIOPLY-8.0.so.1
7f16a5bf8000-7f16a5bf9000 rw-p 0001c000 08:02 1985381                    /usr/local/lib/libvtkIOPLY-8.0.so.1
7f16a5bf9000-7f16a5bfb000 rw-p 00000000 00:00 0 
7f16a5bfb000-7f16a5dac000 r-xp 00000000 08:02 1985360                    /usr/local/lib/libvtkIOGeometry-8.0.so.1
7f16a5dac000-7f16a5fac000 ---p 001b1000 08:02 1985360                    /usr/local/lib/libvtkIOGeometry-8.0.so.1
7f16a5fac000-7f16a5fb2000 r--p 001b1000 08:02 1985360                    /usr/local/lib/libvtkIOGeometry-8.0.so.1
7f16a5fb2000-7f16a5fb8000 rw-p 001b7000 08:02 1985360                    /usr/local/lib/libvtkIOGeometry-8.0.so.1
7f16a5fb8000-7f16a6016000 r-xp 00000000 08:02 1969471                    /usr/local/lib/libpcl_io_ply.so.1.8.1
7f16a6016000-7f16a6216000 ---p 0005e000 08:02 1969471                    /usr/local/lib/libpcl_io_ply.so.1.8.1
7f16a6216000-7f16a6219000 r--p 0005e000 08:02 1969471                    /usr/local/lib/libpcl_io_ply.so.1.8.1
7f16a6219000-7f16a621a000 rw-p 00061000 08:02 1969471                    /usr/local/lib/libpcl_io_ply.so.1.8.1
7f16a621a000-7f16a6220000 r-xp 00000000 08:02 1985572                    /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f16a6220000-7f16a6420000 ---p 00006000 08:02 1985572                    /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f16a6420000-7f16a6421000 r--p 00006000 08:02 1985572                    /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f16a6421000-7f16a6422000 rw-p 00007000 08:02 1985572                    /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f16a6422000-7f16a6439000 r-xp 00000000 08:02 1975037                    /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f16a6439000-7f16a6639000 ---p 00017000 08:02 1975037                    /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f16a6639000-7f16a663a000 r--p 00017000 08:02 1975037                    /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f16a663a000-7f16a663b000 rw-p 00018000 08:02 1975037                    /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f16a663b000-7f16a6652000 r-xp 00000000 08:02 1975036                    /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f16a6652000-7f16a6851000 ---p 00017000 08:02 1975036                    /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f16a6851000-7f16a6852000 r--p 00016000 08:02 1975036                    /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f16a6852000-7f16a6853000 rw-p 00017000 08:02 1975036                    /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f16a6853000-7f16a745d000 r-xp 00000000 08:02 1969297                    /usr/local/lib/libpcl_sample_consensus.so.1.8.1
7f16a745d000-7f16a765d000 ---p 00c0a000 08:02 1969297                    /usr/local/lib/libpcl_sample_consensus.so.1.8.1
7f16a765d000-7f16a768d000 r--p 00c0a000 08:02 1969297                    /usr/local/lib/libpcl_sample_consensus.so.1.8.1
7f16a768d000-7f16a7691000 rw-p 00c3a000 08:02 1969297                    /usr/local/lib/libpcl_sample_consensus.so.1.8.1
7f16a7691000-7f16a7693000 rw-p 00000000 00:00 0 
7f16a7693000-7f16a77c2000 r-xp 00000000 08:02 1969219                    /usr/local/lib/libpcl_kdtree.so.1.8.1
7f16a77c2000-7f16a79c1000 ---p 0012f000 08:02 1969219                    /usr/local/lib/libpcl_kdtree.so.1.8.1
7f16a79c1000-7f16a79ca000 r--p 0012e000 08:02 1969219                    /usr/local/lib/libpcl_kdtree.so.1.8.1
7f16a79ca000-7f16a79cc000 rw-p 00137000 08:02 1969219                    /usr/local/lib/libpcl_kdtree.so.1.8.1
7f16a79cc000-7f16a7ba6000 r-xp 00000000 08:02 1969282                    /usr/local/lib/libpcl_octree.so.1.8.1
7f16a7ba6000-7f16a7da6000 ---p 001da000 08:02 1969282                    /usr/local/lib/libpcl_octree.so.1.8.1
7f16a7da6000-7f16a7da9000 r--p 001da000 08:02 1969282                    /usr/local/lib/libpcl_octree.so.1.8.1
7f16a7da9000-7f16a7dac000 rw-p 001dd000 08:02 1969282                    /usr/local/lib/libpcl_octree.so.1.8.1
7f16a7dac000-7f16a7dcd000 r-xp 00000000 08:02 1966838                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f16a7dcd000-7f16a7fcc000 ---p 00021000 08:02 1966838                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f16a7fcc000-7f16a7fcd000 r--p 00020000 08:02 1966838                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f16a7fcd000-7f16a7fce000 rw-p 00021000 08:02 1966838                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f16a7fce000-7f16a7fd5000 r-xp 00000000 08:02 2637134                    /lib/x86_64-linux-gnu/librt-2.23.so
7f16a7fd5000-7f16a81d4000 ---p 00007000 08:02 2637134                    /lib/x86_64-linux-gnu/librt-2.23.so
7f16a81d4000-7f16a81d5000 r--p 00006000 08:02 2637134                    /lib/x86_64-linux-gnu/librt-2.23.so
7f16a81d5000-7f16a81d6000 rw-p 00007000 08:02 2637134                    /lib/x86_64-linux-gnu/librt-2.23.so
7f16a81d6000-7f16a82de000 r-xp 00000000 08:02 2626156                    /lib/x86_64-linux-gnu/libm-2.23.so
7f16a82de000-7f16a84dd000 ---p 00108000 08:02 2626156                    /lib/x86_64-linux-gnu/libm-2.23.so
7f16a84dd000-7f16a84de000 r--p 00107000 08:02 2626156                    /lib/x86_64-linux-gnu/libm-2.23.so
7f16a84de000-7f16a84df000 rw-p 00108000 08:02 2626156                    /lib/x86_64-linux-gnu/libm-2.23.so
7f16a84df000-7f16a89bb000 r-xp 00000000 08:02 1969514                    /usr/local/lib/libpcl_recognition.so.1.8.1
7f16a89bb000-7f16a8bbb000 ---p 004dc000 08:02 1969514                    /usr/local/lib/libpcl_recognition.so.1.8.1
7f16a8bbb000-7f16a8bda000 r--p 004dc000 08:02 1969514                    /usr/local/lib/libpcl_recognition.so.1.8.1
7f16a8bda000-7f16a8bde000 rw-p 004fb000 08:02 1969514                    /usr/local/lib/libpcl_recognition.so.1.8.1
7f16a8bde000-7f16a98bb000 r-xp 00000000 08:02 1969511                    /usr/local/lib/libpcl_segmentation.so.1.8.1
7f16a98bb000-7f16a9abb000 ---p 00cdd000 08:02 1969511                    /usr/local/lib/libpcl_segmentation.so.1.8.1
7f16a9abb000-7f16a9b16000 r--p 00cdd000 08:02 1969511                    /usr/local/lib/libpcl_segmentation.so.1.8.1
7f16a9b16000-7f16a9b1c000 rw-p 00d38000 08:02 1969511                    /usr/local/lib/libpcl_segmentation.so.1.8.1
7f16a9b1c000-7f16a9b1d000 rw-p 00000000 00:00 0 
7f16a9b1d000-7f16a9d6d000 r-xp 00000000 08:02 1969472                    /usr/local/lib/libpcl_io.so.1.8.1
7f16a9d6d000-7f16a9f6c000 ---p 00250000 08:02 1969472                    /usr/local/lib/libpcl_io.so.1.8.1
7f16a9f6c000-7f16a9f76000 r--p 0024f000 08:02 1969472                    /usr/local/lib/libpcl_io.so.1.8.1
7f16a9f76000-7f16a9f7a000 rw-p 00259000 08:02 1969472                    /usr/local/lib/libpcl_io.so.1.8.1
7f16a9f7a000-7f16a9f7b000 rw-p 00000000 00:00 0 
7f16a9f7b000-7f16aa717000 r-xp 00000000 08:02 1969467                    /usr/local/lib/libpcl_filters.so.1.8.1
7f16aa717000-7f16aa916000 ---p 0079c000 08:02 1969467                    /usr/local/lib/libpcl_filters.so.1.8.1
7f16aa916000-7f16aa944000 r--p 0079b000 08:02 1969467                    /usr/local/lib/libpcl_filters.so.1.8.1
7f16aa944000-7f16aa949000 rw-p 007c9000 08:02 1969467                    /usr/local/lib/libpcl_filters.so.1.8.1
7f16aa949000-7f16aab28000 r-xp 00000000 08:02 1969284                    /usr/local/lib/libpcl_search.so.1.8.1
7f16aab28000-7f16aad27000 ---p 001df000 08:02 1969284                    /usr/local/lib/libpcl_search.so.1.8.1
7f16aad27000-7f16aad33000 r--p 001de000 08:02 1969284                    /usr/local/lib/libpcl_search.so.1.8.1
7f16aad33000-7f16aad35000 rw-p 001ea000 08:02 1969284                    /usr/local/lib/libpcl_search.so.1.8.1
7f16aad35000-7f16aade4000 r-xp 00000000 08:02 1969217                    /usr/local/lib/libpcl_common.so.1.8.1
7f16aade4000-7f16aafe3000 ---p 000af000 08:02 1969217                    /usr/local/lib/libpcl_common.so.1.8.1
7f16aafe3000-7f16aafe7000 r--p 000ae000 08:02 1969217                    /usr/local/lib/libpcl_common.so.1.8.1
7f16aafe7000-7f16aafe8000 rw-p 000b2000 08:02 1969217                    /usr/local/lib/libpcl_common.so.1.8.1
7f16aafe8000-7f16ab000000 r-xp 00000000 08:02 2626163                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f16ab000000-7f16ab1ff000 ---p 00018000 08:02 2626163                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f16ab1ff000-7f16ab200000 r--p 00017000 08:02 2626163                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f16ab200000-7f16ab201000 rw-p 00018000 08:02 2626163                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f16ab201000-7f16ab205000 rw-p 00000000 00:00 0 
7f16ab205000-7f16ab229000 r-xp 00000000 08:02 1985575                    /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f16ab229000-7f16ab428000 ---p 00024000 08:02 1985575                    /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f16ab428000-7f16ab42a000 r--p 00023000 08:02 1985575                    /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0

## Possible Solution

I've also tried to create a VLPGrabber object directly and meanwhile deleted the VLPGrabber pointer member in the class 'System', which failed either.

**Comment by SergioRAgostinho** [comment]
Hey. Do you mind trying the latest 1.9.0 release? We had some important fixes which manifested in symptoms similar to the ones you're experiencing.

**Comment by kunaltyagi** [comment]
Closing due to no response
