### ISSUE TITLE
Build from source, pcl/test/CMakeList.txt GTEST_SRC_DIR duplicate "src/"

### ISSUE THREAD

**Issue by dogod621** [PointCloudLibrary/pcl#2613]
## Your Environment

* Operating System and version: WIN10
* Compiler: VS2017
* PCL Version: 1.9.0

## Current Behavior

![02](https://user-images.githubusercontent.com/6807005/48389779-eff89d00-e739-11e8-901a-aa4295b8897d.png)

If I set GTEST_SRC_DIR to my googletest dir (EX: D://googletest/), 
CMake will run Configure correctly,
But will make errors when run  Generate. 
it will duplicate "src/" when run  Generate and cannot find gtest-all.cc.

If I remove "src/" in pcl/test/CMakeList.txt.
![03](https://user-images.githubusercontent.com/6807005/48389925-95137580-e73a-11e8-90dc-3d3cd46bd45f.png)
And set GTEST_SRC_DIR to my googletest src dir (EX: D://googletest/src/),
Every thing will be fine~  CMake will run Configure and Generate correctly,

**Comment by taketwo** [comment]
@SergioRAgostinho yes makes sense! Do you we have any (de-facto) standard on naming such variables? First part - name of the library, but in which case? Second part - ROOT or DIR?

**Comment by dogod621** [comment]
I think you guys misunderstanding my problem @@...
It is not a naming issue，I set "D://googletest/" to GTEST_SRC_DIR，
CMake will run Configure correctly,
But will make errors when run Generate.

The error message shows, it duplicate "src/" twice: "D://googletest/" -> "D://googletest/src/src"

**Comment by dogod621** [comment]
Oh... It is a weird error...
I cannot duplicate it again... ORZ...
