### ISSUE TITLE
pcl_visualizer.cpp invalid conversion from 'int' to 'const char*' at 3567

### ISSUE THREAD

**Issue by CannieLI** [PointCloudLibrary/pcl#2614]
## Your Environment

* Operating System and version:Ubuntu 18.04
* Compiler:gcc-6
* PCL Version:1.9.0

## Context

The first time when i compiled pcl1.9.0,  I turned the visualization module off and it passed. Yesterday I rebuilt it with visualization module but failed because of the problem above. I thought maybe the latest pcl couldn't work well with VTK-8, then I reinstalled the vtk-7. Another problem ('internal error') came up which however I thought was caused by my tiny memory.  

## Possible Solution

Just in case, I rebuilt the pcl-1.8.1 with vtk-7.1, and then make -j2. Done!

**Comment by taketwo** [comment]
Hi, so what's the status of this issue? Can you state explicitly the complete environment configuration that lead to the error and post the console output?
