### ISSUE TITLE
Drop support of QT4

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2618]
Support of Qt4 ended [end of 2015](http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/). Is it still required to support it? With current modernization of PCL code we could drop supportof it and clean CMake code and switch to new way to include [Qt in CMake](http://doc.qt.io/qt-5/cmake-manual.html)

**Comment by taketwo** [comment]
I'm in favor of dropping Qt4 support. Any other opinions @PointCloudLibrary/maintainers?

**Comment by SergioRAgostinho** [comment]
Agreed 👍

**Comment by UnaNancyOwen** [comment]
Me too :+1:

**Comment by taketwo** [comment]
We should think what to do with the apps that are only enabled with Qt4. Try to upgrade? Remove? Removing doesn't sound right to me. @SunBlack are you willing to invest time into upgrade?

**Comment by SergioRAgostinho** [comment]
Try to upgrade, although I confess my Qt experience is non existent.

**Comment by SunBlack** [comment]
> @SunBlack are you willing to invest time into upgrade?
I tried to take a short look on this. But I'm not able to compile current master of PCL with VTK 8.1 (I got always unresolved symbols). And I don't really have enough time to look why I have this trouble.

**Comment by SunBlack** [comment]
> @SunBlack you are welcome to work on this and we will try to help you.

How I already wrote: I'm not able to compile PCL with VTK (VS2017). Tried it with stable VTK 8.1 and current master of VTK (8.2). As far as I can see you are even not building PCL with VTK on your build jobs on Windows, so I don't know if it is a issue by me or a general issue.

**Comment by taketwo** [comment]
Yes, at the moment our Windows CI builds are without VTK. Pipelines took very long and even ran out of disk space when we tried to enable VTK. Nevertheless, to the best of my knowledge, VS2017 is able to compile PCL with VTK. @UnaNancyOwen successfully produced an [All-in-one installer](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1) for the latest release a few hours ago.

What exactly is the problem you are experiencing?
