### ISSUE TITLE
Ugrade vtk api to 8.1 for 1.9

### ISSUE THREAD

**Issue by lingerer** [PointCloudLibrary/pcl#2619]
The newly 1.9.0 ship with VTK 8.1 and the visualization will make vtk pop warning window like:

> Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkrenderwindow.cxx, line 1480
vtkRenderWindow::GetPainterDeviceAdapter was deprecated for VTK 8.1 and will be removed in a future version.

Yes，it can turn off by set vtk disable warning，but the pre-compiled exe won't.

so ugrade some vtk api call？

**Comment by taketwo** [comment]
From what I can see, we use `GetPainterDeviceAdapter` only in a single place:  https://github.com/PointCloudLibrary/pcl/blob/e200f0088bd781cfb37135266cb7c29e8b3636f8/visualization/src/vtk/vtkVertexBufferObjectMapper.cxx#L106. This class (`vtkVertexBufferObjectMapper`) is a compatibility layer used with old (pre-2) OpenGL. I hope that in future we will switch to OpenGL 2 backend and get rid of this class entirely. Perhaps @UnaNancyOwen can comment on the status of switching to OpenGL 2.

**Comment by UnaNancyOwen** [comment]
Pre-built PCL that include in PCL 1.9.0 All-in-one Installer is linked VTK that rendering backend is OpenGL. The OpenGL rendering backend of VTK is will be deleted in near future. Therefore, the VTK displays a warning.
But, we could not switch it in PCL 1.9.0, because it have a bug yet. We can switch RenderingBackend to OpenGL2 when solved this problem https://github.com/PointCloudLibrary/pcl/issues/1601.

**Comment by jasonhurray** [comment]
> The newly 1.9.0 ship with VTK 8.1 and the visualization will make vtk pop warning window like:
> 
> > Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkrenderwindow.cxx, line 1480
> > vtkRenderWindow::GetPainterDeviceAdapter was deprecated for VTK 8.1 and will be removed in a future version.
> 
> Yes，it can turn off by set vtk disable warning，but the pre-compiled exe won't.
> 
> so ugrade some vtk api call？
Hello, could you tell me how to  turn off the warning by set vtk disable warning?

**Comment by lingerer** [comment]
> > The newly 1.9.0 ship with VTK 8.1 and the visualization will make vtk pop warning window like:
> > > Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkrenderwindow.cxx, line 1480
> > > vtkRenderWindow::GetPainterDeviceAdapter was deprecated for VTK 8.1 and will be removed in a future version.
> > 
> > 
> > Yes，it can turn off by set vtk disable warning，but the pre-compiled exe won't.
> > so ugrade some vtk api call？
> > Hello, could you tell me how to  turn off the warning by set vtk disable warning?

This will do the trick:

vtkObject::GlobalWarningDisplayOff();

**Comment by jasonhurray** [comment]
> > > The newly 1.9.0 ship with VTK 8.1 and the visualization will make vtk pop warning window like:
> > > > Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkrenderwindow.cxx, line 1480
> > > > vtkRenderWindow::GetPainterDeviceAdapter was deprecated for VTK 8.1 and will be removed in a future version.
> > > 
> > > 
> > > Yes，it can turn off by set vtk disable warning，but the pre-compiled exe won't.
> > > so ugrade some vtk api call？
> > > Hello, could you tell me how to  turn off the warning by set vtk disable warning?
> 
> This will do the trick:
> 
> vtkObject::GlobalWarningDisplayOff();

I did as you said, like this:
![image](https://user-images.githubusercontent.com/46080482/50401083-cca81f80-07c6-11e9-9ddf-b70c49954c02.png)

but it still shows this window:
![image](https://user-images.githubusercontent.com/46080482/50401144-43ddb380-07c7-11e9-8735-ca9f233fa386.png)
 ps: I use vs2017 and pcl1.9.1

**Comment by aditya369007** [comment]
Same here, tried doing this,
> > This will do the trick:
> > vtkObject::GlobalWarningDisplayOff();
> 
> I did as you said, like this:
> ![image](https://user-images.githubusercontent.com/46080482/50401083-cca81f80-07c6-11e9-9ddf-b70c49954c02.png)
> 
> but it still shows this window:
> ![image](https://user-images.githubusercontent.com/46080482/50401144-43ddb380-07c7-11e9-8735-ca9f233fa386.png)
> ps: I use vs2017 and pcl1.9.1

Has anyone come up with a fix for this?

**Comment by anelsalas** [comment]
To make win_->GlobalWarningDisplayOff(); work I added it at the end of the
constructor of the visualizer I was using, then rebuilded PCL.

For example when I use this constructor:

pcl::visualization::PCLVisualizer::PCLVisualizer (const std::string &name,
const bool create_interactor)

I added this to line 158 of pcl_visualizer.cpp.
win_->GlobalWarningDisplayOff();


I'm using visual studio 2017 and followed Tsukasa Sugiura's blog (
http://unanancyowen.com/) to build PCL.

**Comment by UnaNancyOwen** [comment]
Thanks @anelsalas,
We can consider to add following to PCLVisualizer constructor as temporary measure.
```cpp
#if VTK_RENDERING_BACKEND_OPENGL_VERSION < 2
win_->GlobalWarningDisplayOff();
#endif
```

**Comment by taketwo** [comment]
Is the constructor the best place for it? We would need to repeat this in each constructor then. Since we are calling this function on a render window object, maybe it's better to put it into `PCLVisualizer::setupRenderWindow`?

**Comment by UnaNancyOwen** [comment]
> it's better to put it into <code>PCLVisualizer::setupRenderWindow</code>

@taketwo Thanks for advice. I think that is good.

**Comment by aditya369007** [comment]
Sorry but I am new to this, but as far as my understanding goes, it is not possible to disable the warning window without recompiling PCL right?

**Comment by taketwo** [comment]
`PCLVisualizer` has an accessor for render window, you should be able to use it to get `win_` object and call `GlobalWarningDisplayOff()` on it.

**Comment by aditya369007** [comment]
> `PCLVisualizer` has an accessor for render window, you should be able to use it to get `win_` object and call `GlobalWarningDisplayOff()` on it.

apologies for my limited understanding of your solution, but could you please elaborate on how and where exactly to do this?
many thanks in advance

**Comment by taketwo** [comment]
> `PCLVisualizer` has an accessor for render window

Accessor is a function that allows to retrieve a class member field. Such function names typically start with `get`. We are talking about accessor for render window, so the name is likely to be `getRenderWindow()`. You can check either [source code](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/pcl_visualizer.h) or [documentation](http://docs.pointclouds.org/trunk/classpcl_1_1visualization_1_1_p_c_l_visualizer.html) to find this function.

> use it to get `win_` object and call `GlobalWarningDisplayOff()` on it

According to @anelsalas this should help.

Now in the screenshots you posted you use `CloudViewer`, which is a simplified interface on top of `PCLVisualizer`. It does not provide access to the render window. So if you want to get rid of warnings you will need to switch to using `PCLVisualizer`. Once you have visualizer, you need to call `visualizer.getRenderWindow()->GlobalWarningDisplayOff()`.

**Comment by lingerer** [comment]
> > `PCLVisualizer` has an accessor for render window
> 
> Accessor is a function that allows to retrieve a class member field. Such function names typically start with `get`. We are talking about accessor for render window, so the name is likely to be `getRenderWindow()`. You can check either [source code](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/pcl_visualizer.h) or [documentation](http://docs.pointclouds.org/trunk/classpcl_1_1visualization_1_1_p_c_l_visualizer.html) to find this function.
> 
> > use it to get `win_` object and call `GlobalWarningDisplayOff()` on it
> 
> According to @anelsalas this should help.
> 
> Now in the screenshots you posted you use `CloudViewer`, which is a simplified interface on top of `PCLVisualizer`. It does not provide access to the render window. So if you want to get rid of warnings you will need to switch to using `PCLVisualizer`. Once you have visualizer, you need to call `visualizer.getRenderWindow()->GlobalWarningDisplayOff()`.

GlobalWarningDisplayOff() is a static method，this can't pass under VS 2017

**Comment by taketwo** [comment]
@anelsalas reported that he used VS 2017 :confused:

**Comment by anelsalas** [comment]
It did work in the constructor in vs2017
I will test today adding it to  PCLVisualizer::setupRenderWindow  as
suggested.

I remember trying to use   get win_ object and it didn't work but will try
that option again once I finish figuring out why flann is not being added
in the additional dependencies field in VS2017.

Anel Salas

**Comment by anelsalas** [comment]
Indeed adding GlobalWarningDisplayOff  to setupRenderWindow removes the vtk warnings in PCLVisualizer. I'm using pcl 1.9.1.

I added it  right after the NULL check.

    void pcl::visualization::PCLVisualizer::setupRenderWindow (const std::string& name)
    {
      if (!win_)
      PCL_ERROR ("Pointer to render window is null");

    #if VTK_RENDERING_BACKEND_OPENGL_VERSION < 2
      win_->GlobalWarningDisplayOff();
    #endif

      win_->SetWindowName (name.c_str ());
      // By default, don't use vertex buffer objects
      use_vbos_ = false;

      // Add all renderers to the window
      rens_->InitTraversal ();
      vtkRenderer* renderer = NULL;
      while ((renderer = rens_->GetNextItem ()) != NULL)
        win_->AddRenderer (renderer);
    }

**Comment by aditya369007** [comment]
> Indeed adding GlobalWarningDisplayOff to setupRenderWindow removes the vtk warnings in PCLVisualizer. I'm using pcl 1.9.1 and VS2017.
> 
> I added it right after the NULL check.
> 
> ```
> void pcl::visualization::PCLVisualizer::setupRenderWindow (const std::string& name)
> {
>   if (!win_)
>   PCL_ERROR ("Pointer to render window is null");
> 
> #if VTK_RENDERING_BACKEND_OPENGL_VERSION < 2
>   win_->GlobalWarningDisplayOff();
> #endif
> 
>   win_->SetWindowName (name.c_str ());
>   // By default, don't use vertex buffer objects
>   use_vbos_ = false;
> 
>   // Add all renderers to the window
>   rens_->InitTraversal ();
>   vtkRenderer* renderer = NULL;
>   while ((renderer = rens_->GetNextItem ()) != NULL)
>     win_->AddRenderer (renderer);
> }
> ```

I believe this edit has to be done to the source .cpp file, but in my case I am using the precompiled libs. Do you have any suggestions for my case?
I did switch to the PCLVisualizer as @taketwo suggested me to, but still the issue prevails.
Many thanks in advance.

**Comment by anelsalas** [comment]
@aditya369007 You can build PCL and apply the change yourself or wait for this fix to be released. 
Other option may be that you find a way for me to send you the dll (pcl_visualization_release.dll). Then you can replace it in your bin folder, probably in C:\Program Files\PCL 1.9.1\bin if you are using the all in one installer.

**Comment by aditya369007** [comment]
That would be amazing! Thank you so for taking the time to do so.
My email id would be aditya.mulampally@gmail.com

**Comment by Austin1511** [comment]
@anelsalas Could you please send me the pcl_visualization_release.dll too. this problem bothers me a lot too, thank you very much! My email is austin1511@hotmail.com

**Comment by anelsalas** [comment]
Here is the dll for the release version without the vtk warnings.  
[https://github.com/anelsalas/PCL_1_9_1_prebuild_pcl_visualization_release.dll](url)

**Comment by Austin1511** [comment]
@anelsalas Thanks a ton!

**Comment by caibf** [comment]
> Once you have visualizer, you need to call `visualizer.getRenderWindow()->GlobalWarningDisplayOff()`.

If I don't decclare `win_->GlobalWarningDisplayOff();` in the setupRenderWindow method, then put `visualizer.getRenderWindow()->GlobalWarningDisplayOff()`. after visualizer created, the vtk warning window still pop up. I have tested this in my environment?
```
pcl::visualization::PCLVisualizer viewer("3D Viewer");
viewer.getRenderWindow()->GlobalWarningDisplayOff();
```
Am I right? @taketwo

**Comment by jafrado** [comment]
Those warnings probably mean something, so they should be debugged. But the easiest thing to do is simply call vtkObject::GlobalWarningDisplayOff()

**Comment by mzeeshanarshad** [comment]
> @Austin1511 Here is the dll for the release version without the vtk warnings.
> 
> > https://github.com/anelsalas/PCL_1_9_1_prebuild_pcl_visualization_release.dll

Hello, can you please also send the debug version of the dll? Thanks!

**Comment by fellenB** [comment]
@anelsalas  my project will use pcl 1.9.1 for a long time，I also want the debug vision of the dll ，my email is fellenB@outlook.com. thank you very much!

**Comment by lingerer** [comment]
2.11 works fine now。

**Comment by kunaltyagi** [comment]
@UnaNancyOwen Can this be closed?

**Comment by UnaNancyOwen** [comment]
@kunaltyagi Yes. This problem has been solved.

**Comment by ssstwo** [comment]
![image](https://user-images.githubusercontent.com/92913087/196383470-344e29cb-e266-4d9a-9065-629ae5bc5ba4.png)

**Comment by lingerer** [comment]
> 这是怎么回事 ![image](https://user-images.githubusercontent.com/92913087/196383470-344e29cb-e266-4d9a-9065-629ae5bc5ba4.png)

It has nothing to do with this issue
