### ISSUE TITLE
Missed move-constructor and move-assignment for pcl::PointCloud<T>

### ISSUE THREAD

**Issue by nickolaym** [PointCloudLibrary/pcl#2637]
The template class `pcl::PointCloud<T>` has a copy-constructor only.
Move would improve performance.

## Your Environment
* Operating System and version: ubuntu 16.04
* Compiler: clang version 6.0.0
* PCL Version: 1.8

## Context
I'm speeding up a chain of operations upon point clouds.

Possible quick fix is rewriting all the stuff with shared pointers to the pointclouds.
It looks redundant and ugly (lots of dereferencing, extra memory allocations).

## Expected Behavior
```
using MyCloud = pcl::PointCloud<MyPoint>;

MyCloud process(MyCloud&& tmp) {
  MyCloud result = std::move(tmp);
  ...
  return result;
}
```
should move the internal vector of points etc.

## Current Behavior
`std::move` does nothing, so it falls back to copy.

## Possible Solution
Add default move-ctor
```
PointCloud(PointCloud<PointT>&& pc) = default;
```

**Comment by taketwo** [comment]
@svenevs is our Intel expert, if I remember correctly. Perhaps he could comment on this.

**Comment by dvsorokin** [comment]
That's an important fundamental issue that affects performance. What is the reason of postponing the fix?

**Comment by SergioRAgostinho** [comment]
It believe it should be fixed in the current master through implicit generation.

**Comment by felixf4xu** [comment]
@SergioRAgostinho May I check from which version this issue is completed? I can't find the commit or PR.

**Comment by SergioRAgostinho** [comment]
Sorry @felixf4xu. I've not been active on this project for a couple of years now. At this point in time you know more about this problem than I do, so I won't be of much help.

**Comment by mvieth** [comment]
@felixf4xu This commit removed the copy constructors: https://github.com/PointCloudLibrary/pcl/commit/34d543d5f0ab99a7813c3c0e7232b6c042e32e0c
The first release in which it was included is PCL 1.10.0. I hope that helps.

**Comment by mvieth** [comment]
@felixf4xu As Sergio said, they are implicitly generated by the compiler. So you won't find them in the code.
With GCC 12, I verified experimentally that moving a cloud with 100 million points works as expected.

**Comment by huqin-RM** [comment]
> @felixf4xu As Sergio said, they are implicitly generated by the compiler. So you won't find them in the code. With GCC 12, I verified experimentally that moving a cloud with 100 million points works as expected.

But even if the implicit move copy is generated by the compiler, there is definitely no optimization of data copying, so isn't it still useless?

**Comment by abellgithub** [comment]
@huqin-RM The data is in a vector, which moves without copying data. The other members are trivial.
