### ISSUE TITLE
Build breaks when OpenMP isn't found

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#2638]
It still tries to link with omp_xxx functions.

Suggested solution: Add the cmake option ```USE_OPENMP``` and make it build with this option on or off.

Version 1.9.0
FreeBSD 11.2

**Comment by yurivict** [comment]
ping

**Comment by kunaltyagi** [comment]
We've made some updates to openmp handling. Could you test with PCL 1.11?

**Comment by kunaltyagi** [comment]
Giving one more reset to stalebot
