### ISSUE TITLE
WITH_QT doesn't do anything

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#2642]
```WITH_QT``` is supposed to find Qt5 and use it, but it doesn't do that.

**Comment by yurivict** [comment]
When I add ```-DBUILD_apps:BOOL=true``` it says that it won't build apps:

```
-- The following subsystems will not be built:
--   visualization: VTK was not found.
--   apps: No reason
```

**Comment by yurivict** [comment]
ping

**Comment by kunaltyagi** [comment]
Can you check with PCL 1.11 if this problem still exists?

**Comment by larshg** [comment]
WITH_QT enables finding the Qt package and use it accordingly.

**Comment by yurivict** [comment]
@larshg ```WITH_QT=QT5``` finds Qt5 but doesn't make any binaries linked with it.

Version: 1.12.1
