### ISSUE TITLE
Github repo shows obsolete tag as latest version 

### ISSUE THREAD

**Issue by luzpaz** [PointCloudLibrary/pcl#2644]
![image](https://user-images.githubusercontent.com/4140247/48978584-76d34100-f07b-11e8-9aaa-9ca888d2acff.png)

Can this be changed to [1.9.0](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.0) ?

**Comment by SergioRAgostinho** [comment]
Your GitHub interface looks different than mine. I'll assume you're running some chrome extensions to enhance GitHub. I have no idea how to change this and I'm surprised this even needs to be done manually.

Both links bellow seem to be pretty aware about what was the latest tag and release
https://github.com/PointCloudLibrary/pcl/releases
https://github.com/PointCloudLibrary/pcl/tags

What your plugin is showing is the first tag in the tag list
<img width="309" alt="screen shot 2018-11-26 at 10 14 16" src="https://user-images.githubusercontent.com/1709142/49004218-14a23b00-f164-11e8-89fb-0733c4a548c3.png">

**Comment by taketwo** [comment]
Perhaps we could abolish `pcl-ros-1.0` tag? Whatever that was, it's completely irrelevant nowadays. Without this tag the list will become homogeneous and sorted.

**Comment by luzpaz** [comment]
You're right I am running an extension I think it's Github-Extend. Forgot about that. Can't check till I'm on my laptop. Anyway, I wonder if it's a bug or that tag is marked differently.

**Comment by taketwo** [comment]
I don't care much about that Chrome extension, it's just that a sorted homogeneous list of tags without this outlier would be more pleasing so see. But I have no strong desires here, I'm absolutely fine with keeping things the way they are.
