### ISSUE TITLE
VTKUtils inconsistent with VTK io

### ISSUE THREAD

**Issue by greenbrettmichael** [PointCloudLibrary/pcl#2646]
## Your Environment

* Operating System and version: Windows 10 1803
* Compiler: msvc 15.9.1
* PCL Version: master

## Context
I want to use existing VTK tools (in this case in vtkPolyDataAlgorithm) on surfaces and then communicate this with pcl data elsewhere in an application.

## Expected Behavior
vtkPolyData is converted into PolygonMesh with positions, normals, and colors

## Current Behavior
pcl::VTKUtils::vtk2mesh PolygonMesh has no normals, while pcl::io::vtk2mesh produces normals

## Code to Reproduce
```
vtkSmartPointer<vtkCubeSource> planeSource = vtkSmartPointer<vtkCubeSource>::New();
  planeSource->SetBounds(0, 1, 0, 1, 0, 1);
  planeSource->Update();
  vtkSmartPointer<vtkPolyDataNormals> normalGenerator = vtkSmartPointer<vtkPolyDataNormals>::New();
  normalGenerator->SetInputData(planeSource->GetOutput());
  normalGenerator->ComputePointNormalsOn();
  normalGenerator->ComputeCellNormalsOff();
  normalGenerator->Update();
  vtkSmartPointer<vtkTriangleFilter> triangleFilter = vtkSmartPointer<vtkTriangleFilter>::New();
  triangleFilter->SetInputData(normalGenerator->GetOutput());
  triangleFilter->Update();
  pcl::PolygonMesh output1;
  pcl::PolygonMesh output2;
  pcl::io::vtk2mesh(triangleFilter->GetOutput(), output1);
  pcl::VTKUtils::vtk2mesh(triangleFilter->GetOutput(), output2);
  pcl::PointCloud<pcl::PointNormal> tempCloud;
  pcl::PointCloud<pcl::PointNormal> tempCloud2;
  pcl::fromPCLPointCloud2(output1.cloud, tempCloud);
  pcl::fromPCLPointCloud2(output2.cloud, tempCloud2);
```

## Possible Solution
Deprecate pcl::surface::VTKUtils and copy implementation from pcl::io vtk until deletion
*OR*
Seperate VTKUtils from surface as a new library and deprecate pcl::io vtk to use the new VTKUtils library

**Comment by SergioRAgostinho** [comment]
From an organization standpoint, the surface module should not have anything related to conversions between data types.  Since this one is just a wrapper to vtk functionalities, it needs to perform conversions to vtk native types inside. So in case this wrapper is build, it should use what is provided in `pcl::io::vtk`. I would add the the `io` module as an extra optional dependency to the `surface` module in case the user wants to use vtk smoothing.

The most fundamental question for me is why we're wrapping VTK functionalities in the first place. :'D

**Comment by greenbrettmichael** [comment]
Is there a case against adding IO dependency to surface (for VTK_FOUND specifically) ? That wouldn't be terribly difficult to implement, and IO is a lonely dependency

**Comment by greenbrettmichael** [comment]
I closed the corresponding PR as stale today. I don't remember the changes well enough.
