### ISSUE TITLE
How to read .pcd.bin?

### ISSUE THREAD

**Issue by RogerAylagas** [PointCloudLibrary/pcl#2647]
Hi,
I know this might be a noob question, but I am trying to read the point cloud of a pcd.bin file of the Lidar using PCL library in C++ but as the extension is pcd.bin loadPCDFile() does not work. I have alredy tried PCDReader but same error occurs

> [pcl::PCDReader::readHeader] No points to read

**How can I read the binary pointclouds using pcl in c++?**

**Comment by greenbrettmichael** [comment]
how was this file obtained? meaning from what program or executable?

**Comment by RogerAylagas** [comment]
Its a file from the Dataset NuScenes.

**Comment by greenbrettmichael** [comment]
NuScenes expects you to load this with their API. Here is the python loader provided by NuScenes https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes_utils/data_classes.py#L39

you will need to make a point type to support reading this header if you want to create a C++ library

**Comment by SergioRAgostinho** [comment]
Closing this one as solved.

**Comment by Abdelrahman350** [comment]
> Closing this one as solved.

Hello @SergioRAgostinho and @RogerAylagas, could you please tell me how did you solve it?

**Comment by mvieth** [comment]
@Abdelrahman350 Please see the answer by greenbrettmichael. The new link seems to be https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py

**Comment by Abdelrahman350** [comment]
> @Abdelrahman350 Please see the answer by greenbrettmichael. The new link seems to be https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py

Thank you very much.
