### ISSUE TITLE
SACSegmentation fails with RGBA cloud

### ISSUE THREAD

**Issue by clausmichele** [PointCloudLibrary/pcl#2662]
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: cmake
* PCL Version: 1.9

## Context
I am trying to perform a planar segmentation. It works if I load a .pcd file into a XYZRGB cloud but not with a RGBA one.
```
error: no matching function for call to ‘pcl::SACSegmentation<pcl::PointXYZRGB>::setInputCloud(pcl::PointCloud<pcl::PointXYZRGBA>::Ptr&)’
         seg.setInputCloud (cloud);
                                 ^
```

## Expected Behavior
It should work also with XYZRGBA format.

## Current Behavior
Works only with XYZ or XYZRGB.

**Comment by taketwo** [comment]
You forgot to change the template point type for `SACSegmentation`, it should also be `pcl::PointXYZRGBA`.

**Comment by clausmichele** [comment]
My bad, you're right!
Thank you
