### ISSUE TITLE
Window CI is failing

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2670]
The CMake configuration stage is failing to find Eigen on windows. This problem was originated upstream because we didn't change anything cmake that manifested in a build failure. I had a look at the commit history for vcpkg, nothing seemed to touch eigen in their latest commits.

See https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=110 for the build log.

We need some help @UnaNancyOwen .

**Comment by SergioRAgostinho** [comment]
Thanks for investigating. I'll close this since there's nothing we can do on our side.

**Comment by UnaNancyOwen** [comment]
Hmm, I don't know about that details.
@ras0219-msft @alexkaratarakis Can you give us advice?

**Comment by taketwo** [comment]
Seems like the builds are back to normal. However we still have this problem of not failing Install Dependencies stage, so keeping this open.

**Comment by alexkaratarakis** [comment]
@SergioRAgostinho
`vcpkg` returns EXIT_FAILURE when install fails. `vcpkg` generally doesn't rely on special error codes, it is either EXIT_SUCESS or EXIT_FAILURE + useful error message.

**Comment by SergioRAgostinho** [comment]
Then my only theory is that Azure Pipelines only cares about the return value of the last execute command. In our case it would be
```
vcpkg list
```
which naturally doesn't fail.
