### ISSUE TITLE
PCL is overriding default CMake scripts

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2677]
In our project we have currently following issue: If we build our project with PCL, FindGTest.cmake script of PCL will be used. In case we build our project without PCL, FindGTest.cmake script of CMake will be used.

So I see two possible solutions:
* Switch to shipped scripts of CMake in PCL
* Rename scripts in PCL to e.g. `FindPCLGTest` or `FindPCLBoost`

What do you think?

**Comment by SergioRAgostinho** [comment]
FindGTest is already present in 3.1.0. I would say we get rid of our vendored one (finally!).

**Comment by SunBlack** [comment]
Ok, I will take a look on this after #2667 is merged
