### ISSUE TITLE
copy document tutorial's code but meet error

### ISSUE THREAD

**Issue by cucrui** [PointCloudLibrary/pcl#2683]
## Your Environment

* Operating System and version: win10
* Compiler: vs2017
* PCL Version: pcl1.9.0

## Context

Im trying to run kd-tree demo from document "How to use a KdTree to search",but i meet an error that cant find 'pop_t' from 'dist.h' file. Is that the version of pcl is too new that cant match the demo code?

**Comment by SergioRAgostinho** [comment]
At first sight I don't think that is the problem. We now have a CI job which tests if the tutorials compile correctly and that one is compiling with no issues. Furthermore, there's we don't have any header named `dist.h` in our source tree at the moment. Why is your code looking for that file?

**Comment by taketwo** [comment]
Closing due to lack of feedback.
