### ISSUE TITLE
Raise minimum VTK version

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2684]
Currently no minimum required version of VTK is defined in root CMakeLists of PCL. Furthermore there are 65 files of PCL which are checking VTK_MAJOR_VERSION. Most of them are checking if we are using VTK in version 6 or older. A few (3 files as far as I can see) are checking for version 7. Maybe we could set minimum version of VTK and drop a lot of deprecated code:

Release dates:
- VTK 6.0.0: 12.06.2013
- VTK 7.0.0: 28.01.2016

**Comment by taketwo** [comment]
Indeed, VTK 6 was released more than 5 years ago and it may be tempting to drop support for it. Unfortunately, this is the highest version that has been packaged for Ubuntu 16.04. Even Ubuntu 18.04 (which is the current LTS) has only VTK 7 packaged.

Ubuntu 16.04 is our current baseline version, thus I'd only back dropping VTK 5 support.

**Comment by SergioRAgostinho** [comment]
Are we keeping the 16.04 till the LTS reaches EOL or until they drop the hardware maintenance updates?

Here's the release cycle for reference.
https://www.ubuntu.com/about/release-cycle

**Comment by taketwo** [comment]
Well, according to the chart hardware updates will be stopped by the end of this year. But I don't think it's time to drop Ubuntu 16.04 support just yet. I, for one, still use it :sunglasses:. Robotic systems are also usually slow to switch to a new LTS (compound by the ROS release cycle and transition problems).

I don't have a clear policy in my head, but it feels like another year is certainly needed. Besides, I don't think there is a good incentive to drop support anyway.
