### ISSUE TITLE
Create bounding box in plane detected

### ISSUE THREAD

**Issue by Dalde** [PointCloudLibrary/pcl#2688]
Hi, I'm new in PCL and I'm trying to find the size and location of the planes from the kinect's data. 
I just implemented the [Plane model segmentation](http://pointclouds.org/documentation/tutorials/planar_segmentation.php#planar-segmentation
) and it works fine. 

Now I would know the position in (x,y,z) coordinates of the vertices of the planes detected for create a bounding box in my project. 

For example in the [Plane model segmentation](http://pointclouds.org/documentation/tutorials/planar_segmentation.php#planar-segmentation
), I should have the values of the vertices of the table and the vertices of the floor (in this case I'm interested only in the table's vertices). 

How can I do this?

**Comment by SergioRAgostinho** [comment]
You can use [`getMinMax3D()`](http://docs.pointclouds.org/trunk/group__common.html#gafd9010977f5e52b35b484be7624df3f8) which will provide you with the minimum and maximum coordinates of the x, y, and z axis. That fully defines your bounding box.
