### ISSUE TITLE
Installing old version (pcl-1.8.1) using Homebrew 

### ISSUE THREAD

**Issue by RenChangHow** [PointCloudLibrary/pcl#2689]
Hi, I am trying to install pcl-1.8.1 on my mac using homebrew. When I try brew install pcl, the newest 1.9.1 version is installed. I want to ask how can I install the older version 1.8.1 using homebrew?

Thanks.

**Comment by SergioRAgostinho** [comment]
You can't :/ You'll need to compile the library from source.

**Comment by latte-z** [comment]
> Hi, I am trying to install pcl-1.8.1 on my mac using homebrew. When I try brew install pcl, the newest 1.9.1 version is installed. I want to ask how can I install the older version 1.8.1 using homebrew?
> 
> Thanks.

You can follow this steps: [Install old version](https://steemit.com/cs/@chaimyu/brew)

**Comment by RenChangHow** [comment]
> > Hi, I am trying to install pcl-1.8.1 on my mac using homebrew. When I try brew install pcl, the newest 1.9.1 version is installed. I want to ask how can I install the older version 1.8.1 using homebrew?
> > Thanks.
> 
> You can follow this steps: [Install old version](https://steemit.com/cs/@chaimyu/brew)

This helps a lot thanks!
