### ISSUE TITLE
Nested namespace definition

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2694]
C++17 supports [nested namespace defintion](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4230.html), so we could write
```
namespace pcl::gpu::kinfuLS {
    //…
}
```

instead of
```
namespace pcl
{
  namespace gpu
  {
    namespace kinfuLS
    {
//...
    }
  {
}
```
Requires at least MSVC 2015 Update 3 (see [here](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/visual-cpp-language-conformance.md))

//Edit: My fault: Believed it is a C++14 feature and not C++17

**Comment by SunBlack** [comment]
This modernization could be done with [clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/modernize-concat-nested-namespaces.html)

**Comment by taketwo** [comment]
Indeed, we can do this when we switch to C++17. However it is sooooo far away that I'd actually close this for now.
