### ISSUE TITLE
Migrating from Boost.Thread to std

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2700]
I'm just opening this one to mention I'm working on it. I've incorporated the corresponding commit from #2382 and I'm building up on it. 

Migration list:
- [x] boost::thread - #3060
- [x] boost::condition_variable
- [x] locks & mutexes
- [x] Remove search from Boost.Thread component in CMakeLists.txt

**Comment by taketwo** [comment]
Can we just keep `boost::shared_lock` in that module? We are not going to drop Boost dependency anyway. Thus I don't see why we need to sacrifice performance and (potentially) introduced hard-to-catch bugs just to get rid of some Boost class?

**Comment by SunBlack** [comment]
> Shared locks are only available in the standard from 2017 onwards.

Sure? `std::shared_lock` is labeled as C++14 [here](https://en.cppreference.com/w/cpp/thread/shared_lock).

**Comment by SergioRAgostinho** [comment]
> > Shared locks are only available in the standard from 2017 onwards.
> 
> Sure? `std::shared_lock` is labeled as C++14 [here](https://en.cppreference.com/w/cpp/thread/shared_lock).

Very very late answer. The issue comes from this line in that same page
> Mutex  -  the type of the shared mutex to lock. The type must meet the SharedMutex requirements

However [shared mutexes](https://en.cppreference.com/w/cpp/thread/shared_mutex) were only introduced in C++17. However, it appears [shared timed mutexes](https://en.cppreference.com/w/cpp/thread/shared_timed_mutex) were created for C++14 and appear to provide a superset of the functionality of the shared mutex. The shared mutex might have appeared later to reduce unwanted functionality.
