### ISSUE TITLE
FPFH implementation does not match documentation

### ISSUE THREAD

**Issue by wangbingqian110** [PointCloudLibrary/pcl#2706]
The FPFH equation:
FPFH(p) = SPFH(p) + weighted average of SPFH over neighbourhood
does not hold for the current implementation.([http://www.pointclouds.org/documentation/tutorials/fpfh_estimation.php#fpfh-estimation](http://www.pointclouds.org/documentation/tutorials/fpfh_estimation.php#fpfh-estimation))
PCL FPFH consists only of the weighted average, the query point SPFH is omitted.

This can be seen from the code logic, in features/impl/fpfh.hpp:

1. computeFeature calls computeSPFHSignatures and then iterates over points with weightPointSPFHSignature
2. computeSPFHSignatures fills three eigen matrices with SPFH split by feature
3. computeSPFHSignatures fills three eigen matrices with SPFH split by feature
weightPointSPFHSignature clears the FPFH, then iterates over neighbours, skipping the query point and adding weighted neighbour SPFH to the FPFH, and finally normalizes FPFH.

If this is intentional, I guess the documentation, tutorial and the wiki page should mention it.

**Comment by taketwo** [comment]
This is an exact copy of #1757. Please keep discussions there, no reason to create a new issue.
