### ISSUE TITLE
flann generate warning

### ISSUE THREAD

**Issue by ngcngc1** [PointCloudLibrary/pcl#2725]
When I used cmake generating pcl1.9.1, there were lots of warning about flann and ensenso and the project was failed.
the environment:
cmake 2.13.2
pcl1.9.1
3dparty  build from PCL-1.9.1-AllInOne-msvc2017-win64
WARNING: Target "pcl_kdtree" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_search" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_search" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_filters" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_io" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_io" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_convert_pcd_ascii_binary" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_convert_pcd_ascii_binary" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd_introduce_nan" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd_introduce_nan" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_hdl_grabber" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_hdl_grabber" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_features" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_segmentation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_surface" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_registration" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_keypoints" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_tracking" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_recognition" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_recognition" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_recognition" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_normal_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_normal_estimation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_normal_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_sac_segmentation_plane" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_sac_segmentation_plane" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_sac_segmentation_plane" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_boundary_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_boundary_estimation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_boundary_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_plane_projection" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_plane_projection" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_uniform_sampling" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_uniform_sampling" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_uniform_sampling" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd2ply" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd2ply" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_cluster_extraction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_cluster_extraction" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_cluster_extraction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pclzf2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pclzf2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_xyz2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_xyz2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ply2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ply2pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_morph" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_morph" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_morph" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fpfh_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fpfh_estimation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fpfh_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_lum" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_lum" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_lum" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd2vtk" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd2vtk" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fast_bilateral_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fast_bilateral_filter" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_fast_bilateral_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_vfh_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_vfh_estimation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_vfh_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_hausdorff" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_hausdorff" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_hausdorff" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_spin_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_spin_estimation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_spin_estimation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_voxel_grid" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_voxel_grid" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_voxel_grid" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_point_cloud" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_point_cloud" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_point_cloud" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_passthrough_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_passthrough_filter" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_passthrough_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_radius_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_radius_filter" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_radius_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_linemod_template" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_linemod_template" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_linemod_template" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt2d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt2d" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt2d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_elch" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_elch" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_elch" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_extract_feature" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_extract_feature" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_extract_feature" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_cloud_error" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_cloud_error" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_compute_cloud_error" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_unary_classifier" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_unary_classifier" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_train_unary_classifier" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_unary_classifier_segment" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_unary_classifier_segment" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_unary_classifier_segment" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_crf_segmentation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_crf_segmentation" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_crf_segmentation" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_add_gaussian_noise" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_add_gaussian_noise" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_outlier_removal" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_outlier_removal" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_outlier_removal" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_progressive_morphological_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_progressive_morphological_filter" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_progressive_morphological_filter" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_mls_smoothing" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_mls_smoothing" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_mls_smoothing" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_marching_cubes_reconstruction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_marching_cubes_reconstruction" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_marching_cubes_reconstruction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_gp3_surface" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_gp3_surface" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_gp3_surface" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp2d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp2d" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_icp2d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt3d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt3d" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_ndt3d" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd_change_viewpoint" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_pcd_change_viewpoint" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_concatenate_points_pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_concatenate_points_pcd" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_poisson_reconstruction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_poisson_reconstruction" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_poisson_reconstruction" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_match_linemod_template" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_match_linemod_template" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_match_linemod_template" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_linemod_detection" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_linemod_detection" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_linemod_detection" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_demean_cloud" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_demean_cloud" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_generate" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_generate" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_local_max" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_local_max" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_local_max" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_grid_min" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_grid_min" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_grid_min" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_from_viewpoint" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_from_viewpoint" requests linking to directory "C:/Program Files/PCL 1.9.0/3rdParty/FLANN/bin".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "pcl_transform_from_viewpoint" requests linking to directory "E:/Program Files/Ensenso/development/c/lib".  Targets may link only to libraries.  CMake is dropping the item.

**Comment by taketwo** [comment]
We have merged a large number of FLANN-related fixes since this was reported: https://github.com/PointCloudLibrary/pcl/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+closed%3A%3E2018-12-19+flann

Your problem is thus likely solved in master. Please re-open if not.
