### ISSUE TITLE
pcl && opengl

### ISSUE THREAD

**Issue by SunshineDou** [PointCloudLibrary/pcl#2729]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler:
* PCL Version: pcl 1.9.1

## Context
Hello, 
I have used the cloud_viewer.cpp in pcl to read and display 3D pcd pointcloud model of a room. as I want to get the scene of the pointcloud in any  viewpoint such as the openGL's virtual camera to realize scene roaming. So I want to know can I combine pcl and opengl to realize it? can I use pcl to read, display the 3D model and simultaneously use opengl to realize roaming?
Thank you very much

**Comment by taketwo** [comment]
PCL visualization is a wrapper around VTK, so I suggest you check their documentation and/or ask in their community regarding scene roaming realization.

**Comment by SunshineDou** [comment]
@taketwo ok, Thank you very much
