### ISSUE TITLE
Switch to using Boost imported targets

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2732]
Imported targets of Boost requires CMake 3.5. Ubuntu 16.04 has CMake 3.5.1, so it is okay, to raise minimum required CMake version?

**Comment by taketwo** [comment]
I'm fine with such a change, but would like to hear other opinions as well.

**Comment by taketwo** [comment]
@SergioRAgostinho are you also fine?

**Comment by SergioRAgostinho** [comment]
Yup. I was just waiting on having the reason to do it. This is what I had to do last time I did a bump #2605.

**Comment by taketwo** [comment]
We require 3.5 now.

**Comment by SergioRAgostinho** [comment]
We are already at 3.5. https://github.com/PointCloudLibrary/pcl/commit/fc9ffa1ae6b2abd1139557dab4e62032357099ac

**Comment by alokpr** [comment]
Please also do not disable the config mode by setting Boost_NO_BOOST_CMAKE=ON:
https://github.com/PointCloudLibrary/pcl/blob/49ca041a8b7a47e448dc42366858816c77e07ce5/cmake/pcl_find_boost.cmake#L23

This makes cmake super-project setting inconvenient where the embedding project builds both - boost and pcl. Is there a particular reason for explicitly disabling the config mode for Boost?

**Comment by SergioRAgostinho** [comment]
https://github.com/PointCloudLibrary/pcl/commit/da8c8407a771757db4e2ec278f888fd2f47357b9

The commit message (from 2012)
> disable the config mode of find_package(Boost) as it's not stable yet 

It's a remnant of the past that never got updated.

**Comment by kunaltyagi** [comment]
tagging @shrijitsingh99

**Comment by mvieth** [comment]
Closed by #4952
