### ISSUE TITLE
PCL CMake Version find package

### ISSUE THREAD

**Issue by MirrorSaver** [PointCloudLibrary/pcl#2738]
I downloaded the newest release of pcl 1.9.1 and I followed the buld instructions and installed the package. In the folder /usr/lib/x86_64-linux-gnu/cmake/pcl the files seem not to be updated and still refer to version 1.7 which was installed with ros. My problem is that I want to included PCL 1.9 i my project in the CMakeLists.txt by find_package(PCL 1.9 REQUIRED) However I can only find the version 1.7.  How can I fix this?

**Comment by taketwo** [comment]
Which build instructions did you follow? By default the library is installed in `/usr/local`. If you specified any other directory, you need to provide it to `cmake` while configuring your downstream project, e.g.

```bash
cmake .. -DPCL_DIR=<path-where-you-installed>/share/pcl-1.9`
```

**Comment by MirrorSaver** [comment]
I had to setup a new system for other reasons. Now it just finds the installation. I think the cmake files in /usr/lib/x86_64-linux-gnu/cmake/pcl are the ones created by my ROS installation. Now it finds the updated library directly in /usr/local . Thanks
