### ISSUE TITLE
Error of size of val_exp_rgb in bilateral_upsampling

### ISSUE THREAD

**Issue by BITVoyager** [PointCloudLibrary/pcl#2741]
https://github.com/PointCloudLibrary/pcl/blob/43b15dd62097c5587b837e35a97aaa9b9e87b82e/surface/include/pcl/surface/impl/bilateral_upsampling.hpp#L157
It should be
```C++
val_exp_rgb.resize (3 * 255 + 1); 
```
Line #172 should be
```C++
  for (int d_color = 0; d_color <= 3*255; d_color++) 
```

**Comment by taketwo** [comment]
You are right. `val_exp_rgb` is a lookup table mapping 1-norm distances in RGB space to weights. The the maximum possible distance is between black and white (0 to 255 * 3), thus the look up table should have 3 * 255 + 1 values.

Please send a patch!
