### ISSUE TITLE
"e" mode string in fopen

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2748]
Clang tidy suggest following changes in PCL source [android-cloexec-fopen](https://clang.llvm.org/extra/clang-tidy/checks/android-cloexec-fopen.html) and [android-cloexec-open](https://clang.llvm.org/extra/clang-tidy/checks/android-cloexec-open.html). "e" mode string is not mentioned in [documentation](https://en.cppreference.com/w/cpp/io/c/fopen), so I don't know if we should integrate it or not.

**Comment by taketwo** [comment]
Have no experience with this. As far as I understand this is a nonstandard GNU C extension, which, however, has been around for ages. Can you post the diff for the proposed change?

**Comment by SunBlack** [comment]
I created a PR as diff (#2755), so you can decide if you want to merge this or decline (feel free to decline PR in case)
