### ISSUE TITLE
fatal error LNK1104: can not open file “libboost_thread-vc141-mt-gd-1_64.lib”

### ISSUE THREAD

**Issue by errorplayer** [PointCloudLibrary/pcl#2751]
## Your Environment

* Operating System and version: Windows 10 64-bit  based on x64 processors
* Compiler: IDE VS2017 Community  
solution configuration: **Debug** platform: **x86**
* PCL Version:PCL 1.8.1 All-in-one Installer MSVC2017 Win32  
obtained from  http://unanancyowen.com/en/pcl181

## Context

I had originally installed the x64 version of all-in-one by mistake while I want it to work in _solution configuration: **Debug** platform: **x86**_ before I saw this error. Realizing the mismatch between all-in-one version(x64) and my platform(x86) and then after uninstalling my x64 all-in-one, I couldn't wait anymore to download a win32 all-in-one from the same page as I mentioned above. However, the same error occurred.

## Current Behavior

The output is below:
1>------ Rebuild All started: Project: PCL_test, Configuration: Debug Win32 ------
1>first.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>n:\pcl 1.8.1\include\pcl-1.8\pcl\point_traits.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>n:\pcl 1.8.1\3rdparty\boost\include\boost-1_64\boost\iostreams\positioning.hpp(96): warning C4996: 'std::fpos<_Mbstatet>::seekpos': warning STL4019: The member std::fpos::seekpos() is non-Standard, and is preserved only for compatibility with workarounds for old versions of Visual C++. It will be removed in a future release, and in this release always returns 0. Please use standards-conforming mechanisms to manipulate fpos, such as conversions to and from streamoff, or an integral type, instead. If you are receiving this message while compiling Boost.IOStreams, a fix has been submitted upstream to make Boost use standards-conforming mechanisms, as it does for other compilers. You can define _SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING to acknowledge that you have received this warning, or define _REMOVE_FPOS_SEEKPOS to remove std::fpos::seekpos entirely.
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\iosfwd(59): note: see declaration of 'std::fpos<_Mbstatet>::seekpos'
1>n:\pcl 1.8.1\include\pcl-1.8\pcl\visualization\interactor_style.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>n:\pcl 1.8.1\include\pcl-1.8\pcl\visualization\pcl_visualizer.h(1584): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc141-mt-gd-1_64.lib'
1>Done building project "PCL_test.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

## Code to Reproduce

I followed the first two steps(totally 5) mentioned in Oszkar's reply from this page.
https://stackoverflow.com/questions/16514762/setting-up-point-cloud-library-with-visual-studio

**Comment by UnaNancyOwen** [comment]
We recommend generate user own projects using CMake. Please read this [documents](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php).
Also, The each [tutorials](http://pointclouds.org/documentation/tutorials/) have CMakeLists.txt. It will be useful for you.

**Comment by errorplayer** [comment]
> We recommend generate user own projects using CMake. Please read this [documents](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php).
> Also, The each [tutorials](http://pointclouds.org/documentation/tutorials/) have CMakeLists.txt. It will be useful for you.

Hello, UNO.
Does CMake work for VS projects needing MFC support?
