### ISSUE TITLE
Run ./pcl_openni2_viewer but meet fail "No devices connected" using IntelRealsense D435

### ISSUE THREAD

**Issue by cucrui** [PointCloudLibrary/pcl#2764]
## Your Environment

* Operating System and version: Ubuntu18.04.1 LTS
* Compiler: gcc + cmake
* PCL Version: 1.9

The problem is that when I using Openni2 only and runing NiViewer，all is  well。But when I using PCL and run pcl_openni2_viewer, I met fail "No devices connected". If i miss something?

**Comment by wulalala1999** [comment]
Excuse me, can you tell me how you fix this problem?
