### ISSUE TITLE
GICP Overlap Ratio

### ISSUE THREAD

**Issue by meakcey** [PointCloudLibrary/pcl#2765]
Is there any parameter import for overlap ratio to Generalized ICP or other ICP methods?
I found overlap parameter in Correspondence Rejection Trimmed class but don't know how could it be implemented in ICP.

**Comment by mvieth** [comment]
I am not sure I understand the question.
As far as I know/see the (G)ICP algorithm does not require you to set an overlap ratio (if that answers your question).
Since this question is 3 years old, I am going to close it. If you still have this question, feel free to open a new issue
