### ISSUE TITLE
PLYReader should output appropriate error message when file is not found

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#2766]
For reference, error messages like this are terribly uninformative and misleading.  Plyreader should output an error to the effect of "Unable to find file with that name", rather than "unable to read header" which implies that the reader was able to find and open the file, but not read it.

_Originally posted by @msy22 in https://github.com/PointCloudLibrary/pcl/issues/2763#issuecomment-452466908_

**Comment by xkaraman** [comment]
Hey there, 
If i can be any help, i could try and implement it!
We could use experimental::filesystem::exists() since PCL now requires C++14.
What do you think?

**Comment by taketwo** [comment]
`boost::filesystem` [is said](https://en.cppreference.com/w/cpp/experimental/fs) to be available on more compilers and platforms. Besides, we already use it in other parts of PCL, so I would stick with it.

**Comment by xkaraman** [comment]
Sounds good, i did some work on it and more specifically on ` io/src/ply_io.cpp. Shall i do a pull request and see if it's any good?

**Comment by taketwo** [comment]
Sure, just create a pull request and we'll have a look.
