### ISSUE TITLE
VoxelGrid downsampling issues with custom point type

### ISSUE THREAD

**Issue by KirbX** [PointCloudLibrary/pcl#2774]
Hi!
I'm downsampling a point cloud (of custom point), and at the end, I saw that I lost my color information (all points are r(0), g(0) and b(0)), but I still have an intensity value.
I followed [this discussion](http://www.pcl-users.org/Voxel-Grid-with-Custom-Point-Types-td4034884.html)
that led me [here ](https://github.com/PointCloudLibrary/pcl/pull/805/files). I read the commit and saw that it was already in my version of PCL (I believe it was a standard after the discussion).

The custom point I'm using : 
```
struct _MyPoint {
	PCL_ADD_POINT4D;
	PCL_ADD_RGB;
	PCL_ADD_INTENSITY;

	EIGEN_MAKE_ALIGNED_OPERATOR_NEW
} /*EIGEN_ALIGN16*/;

struct EIGEN_ALIGN16 MyPoint : _MyPoint {
	inline MyPoint() {
		x = y = z = 0.0f;
		intensity = 0.0f;
		r = g = b = 0;
	}

	inline MyPoint(float _x, float _y, float _z, float _intensity, int _r, int _g, int _b) {
		x = _x;
		y = _y;
		z = _z;
		intensity = _intensity;
		r = _r;
		g = _g;
		b = _b;
	}

	bool isZero(double EPS) {
		return (abs(x) < EPS && abs(y) < EPS && abs(z) < EPS);
	}

	EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

POINT_CLOUD_REGISTER_POINT_STRUCT
(MyPoint,
(float, x, x)
(float, y, y)
(float, z, z)
(float, intensity, intensity)
(uint8_t, r, r)(uint8_t, g, g)(uint8_t, b, b)
)
```
and the function : 
```
pcl::PointCloud<MyPoint>::Ptr FILTRE::downSample_(pcl::PointCloud<MyPoint>::Ptr pointcloud, pcl::IndicesPtr indices, float x, float y, float z) {
	pcl::PointCloud<MyPoint>::Ptr filtered_pointCloud(new pcl::PointCloud<MyPoint>);
	pcl::VoxelGrid<MyPoint> sor;
	sor.setInputCloud(pointcloud);
	sor.setIndices(indices);
	sor.setLeafSize(x, y, z);
	sor.setDownsampleAllData(true);
	sor.filter(*filtered_pointCloud);
	return filtered_pointCloud;
}
```

is that normal?

**Comment by KirbX** [comment]
In fact, It seems that when it comes to create the centroid, I don't have any accumulator for rgb, while I have a field named "rgb" and one named "rgba" in my custom point. If I looked good for pcl::traits::has_color, it seems that it search for a field named rgba. I have it, but the accumulator isn't here...

**Comment by taketwo** [comment]
What does

```cpp
std::cout << "MyPoint has color: " << pcl::traits::has_color<MyPoint>::value << std::endl;
```

output for you?

**Comment by KirbX** [comment]
Hi, thanks for your answer.
`std::cout << "MyPoint has color: " << pcl::traits::has_color<MyPoint>::value << std::endl;`
output 
`MyPoint has color: 0`

**Comment by taketwo** [comment]
Yeah. I think you should use `(uint32_t, rgba, rgba)` when you register your point type, not individual color channel fields.
