### ISSUE TITLE
CMAKE Policy Error CMP0074 Windows 10, PCL 1.9.1, on PCL_ROOT

### ISSUE THREAD

**Issue by jmw992** [PointCloudLibrary/pcl#2777]
Receiving CMP0074 warning on the PCL_ROOT variable and it is reported as ignored.  I'm trying to build the project in the "Using PCL in your own project".  I've installed with the all in one installer and I've followed the issue in the link below but it was reported as fixed.

https://github.com/PointCloudLibrary/pcl/issues/2425

I'm very much a subject programmer and manipulation of cmake is not my expertise, I'm not married to using the particular PCL version, so willing to accept reverting to a prior known compatible CMAKE - PCL versions  as a fix.  Thanks!

##  Environment
* Windows 10 Version 1709, 64 bit
* Compiler: msvc 2017
* PCL Version: 1.9.1, installed via PCL-1.9.1-AllInOne-msvc2017-win64.exe
* CMAKE Version: 3.13.2

##  Outputs
[CMakeError.log](https://github.com/PointCloudLibrary/pcl/files/2764562/CMakeError.log)
[CMakeOutput.log](https://github.com/PointCloudLibrary/pcl/files/2764568/CMakeOutput.log)
[command_line_output.txt](https://github.com/PointCloudLibrary/pcl/files/2764569/command_line_output.txt)

## Potential Conflict Source
When installing PCL 1.9.1 I had the error message regarding too long of environmental variable name so manually made the following changes
* Added C:\Program Files\PCL 1.9.1\bin to Path Variable
* Added PCL_ROOT variable as C:\Program Files\PCL 1.9.1

## Possible Solution
- Go to previous version of PCL or CMAKE?

**Comment by taketwo** [comment]
@UnaNancyOwen do you have any suggestions here?

**Comment by SergioRAgostinho** [comment]
@jmw992 Are you setting the CMP0074 policy explicitly in your project / CMake file? Since you manually added a `PCL_ROOT` variable, I think CMake is warning you to be careful about the using that naming convention.

**Comment by UnaNancyOwen** [comment]
This warning is displayed.
It is because CMP0074 is set to OLD in PCL 1.9.1. ([pcl-1.9.1/PCLConfig.cmake.in#L21](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/PCLConfig.cmake.in#L21))
I have rewritten it to NEW. But, This warning is still displayed. (Hmm, I don't know this cause.)
```
CMake Warning (dev) at CMakeLists.txt:12 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable PCL_ROOT is set to:

    C:\Program Files\PCL 1.9.1

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

@jmw992 BTW, I have read your log. 
It appears that you seem to be using the default generator. In Windows, default generator is target for x86 (<code>Visual Studio 15 2017</code>).
You installed PCL using PCL All-in-one Installer for x64. Therefor,  You need specify generator for x64 (<code>Visual Studio 15 2017 Win64</code>).
On the command line, Please specify as follows.
```
mkdir build
cd build
cmake .. -G"Visual Studio 15 2017 Win64" 
```

**Comment by jmw992** [comment]
@UnaNancyOwen , I did the change on the compiler, the cmake is able to generate a project now, however when I go to build the project in visual studio 17 with x64 and any of the release modes they do not build.  I have attached the cmake logs, and command line output for reference, as well as the log from the output of the built project. 

[vs2017_build_fail_output.txt](https://github.com/PointCloudLibrary/pcl/files/2773511/vs2017_build_fail_output.txt)
[CMakeError.log](https://github.com/PointCloudLibrary/pcl/files/2773512/CMakeError.log)
[CMakeOutput.log](https://github.com/PointCloudLibrary/pcl/files/2773513/CMakeOutput.log)
[command_line_output.txt](https://github.com/PointCloudLibrary/pcl/files/2773514/command_line_output.txt)

There appears to be linking errors with the boost library, and with the command line output I saw it is referencing a different boost library than the install.  I have some environmental variables pointing to a different version of BOOST for running a different library they are.

* in Path  -> D:\my_libraries\boost_1_67_0\lib64-msvc-14.1
* BOOST_LIBRARYDIR -> D:\my_libraries\boost_1_67_0\lib64-msvc-14.1
* BOOST_INCLUDEDIR -> D:\my_libraries\boost_1_67_0

I'll try removing these environmental variables and I'll report what happens.

**Comment by jmw992** [comment]
So removed the boost variables in the environmental variables and it seems to be drawing from the proper Boost in the 3rd party library install.  The cmake error with pthread.h remains
* fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

As well as the linking error for the boost library when going to build
* pcd_write.obj : error LNK2019: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::detail::generic_category_ncx(void)" (?generic_category_ncx@detail@system@boost@@YAAEBVerror_category@23@XZ) referenced in function "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)

When I searched for a pthread file in the directory of pcl 1.9.1 this is what I find.
![image](https://user-images.githubusercontent.com/15371018/51398217-068feb80-1b11-11e9-88dc-5ee9fbaf3caf.png)

# Suggestions
* I do have some environmental variables pointing to a separate QT directory for building a different library, and a FLANN_ROOT from earlier install attempt through attempts at but I doubt that is involved.  If requested I can remove those and try to rebuild.

**Comment by UnaNancyOwen** [comment]
> There appears to be linking errors with the boost library, and with the command line output I saw it is referencing a different boost library than the install. I have some environmental variables pointing to a different version of BOOST for running a different library. They are....
> * in Path -> D:\my_libraries\boost_1_67_0\lib64-msvc-14.1
> * BOOST_LIBRARYDIR -> D:\my_libraries\boost_1_67_0\lib64-msvc-14.1
> * BOOST_INCLUDEDIR -> D:\my_libraries\boost_1_67_0
> 
> I'll try removing these environmental variables and I'll report what happens.

Please delete <code>BOOST_INCLUDEDIR</code> and <code>BOOST_LIBRARYDIR</code> from environment variables.

**Comment by UnaNancyOwen** [comment]
@jmw992 Please do it when trying again,
1. Delete CMake cache. (rmdir ./build)
2. Close and ReOpen command window to apply changed environment variables.

> Is there any building necessary on the 3rd party libraries that got installed?

Yes, It is full set dependencies for pre-built PCL libraries.

**Comment by UnaNancyOwen** [comment]
I was able to reproduce this problem, and found the cause.
<code>PCL_COMMON_LIBRARIES</code> and <code>PCL_IO_LIBRARIES</code> contains only each libraries (pcl_common and pcl_io).
It doesn't include the necessary dependencies (3rdParty). Therefore, LNK2019 has occurred.
Please change the following line to solve this problem.
```patch
- target_link_libraries(pcd_write_test ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES})
+ target_link_libraries(pcd_write_test ${PCL_LIBRARIES})
```

**Comment by jmw992** [comment]
@UnaNancyOwen The project builds in Visual studio, thank you very much for your efforts.

**Comment by taketwo** [comment]
>  PCL_COMMON_LIBRARIES and PCL_IO_LIBRARIES contains only each libraries (pcl_common and pcl_io).

Sadly, that's a shortcoming of our config script, have to be fixed at some point. In the meantime I sent a PR fixing the tutorial.
