### ISSUE TITLE
Mingw64 compilation

### ISSUE THREAD

**Issue by janekT** [PointCloudLibrary/pcl#278]
Hi, I can compile PCL 1.7 with mingw64. Only one thing to solve is error in file: \io\src\lzf.cpp 
line 100 - 105 :
# if defined (WIN32) && defined (_M_X64)

  // workaround for missing POSIX compliance
  unsigned _int64 off; 
# else

  unsigned long off;
# endif

\io\src\lzf.cpp:102:19: error: expected initializer before 'off'
\io\src\lzf.cpp:134:13: error: 'off' was not declared in this scope

how should be changed the IF statement tfor using mingw64?
thanks

**Comment by caibf** [comment]
Great. I meet the same problem in the liblzf/lzf_c.c. Thank you.
