### ISSUE TITLE
PCL Win64 binaries with /MT (static library) option?

### ISSUE THREAD

**Issue by 3DdeepAI** [PointCloudLibrary/pcl#2787]
I successfully implemented surface reconstruction through PCL using pre-built PCL-DLLs and a main project DLL which contains poisson_reconstruction.cpp  (plus related  parse.cpp, print.cpp, lzf.cpp, pcl_base.cpp
projection_matric.cpp). That project uses these already built binaries:
pcl_common_release.dll
pcl_kdtree_release.dll
pcl_octree_release.dll
pcl_search_release.dll
pcl_surface_release.dll
pcl_features_release.dll
pcl_filters_release.dll
pcl_sample_consensus_release.dll

Unfortunately they are using the shared Run-Time Library  (/MD option).
I want to use them as /MT (static build); So I tried to build them from source. 

1. During CMAKE  "cmTC_4a309.exe" crashes with an exception message*
2. And then CMAKE complains about missing EIGEN
  and so I set EIGEN_INCLUDE_DIR to   PCL-1.9.1/PCL 1.9.1/3rdParty/Eigen/eigen3
3. I use flann_s.lib and  for FLANN_LIBRARY and flann_s-gd.lib for debug lib
4. CMAKE then gives this error: 
 "Imported targets and dependency information not available for Boost version (all versions older than 1.33)"
 But there's no option to specify a path to Boost (I want to use 1.69.0 which works fine with the project already.) So where should I set it?
 I deselected all "WITH_..." lines and only selected the "BUILD_..." of the 8 DLL modules above.
5. Unfortunately CMAKE not even builds the solution file for the 8 modules.
  
So what I only need would be a list of all .h,.hpp,.cpp files
to build the 8 DLLs above from source without CMAKE;

For example on building pcl_common_release.dll: is it enough to simply build all files in all sub folders of pcl-pcl-1.9.1\common to create pcl_common_release.dll ? I also did not find any .def file, so how should I know which functions have to be exported?
I can try to build all of those files into one modue, but that would require always a full rebuild and would not create the DLLs.

however on compiling: kdtree_flann.cpp this error occurs:
flann/util/serialization.h(21): error C2228: left of '.serialize' must have class/struct/union

*NOTE: CMAKE  "cmTC_4a309.exe" crashes with an exception message:
_Performing Test HAVE_SSE4_2_EXTENSIONS - Failed_  
That is clear, cause my CPU has  only up to SSE 4.1; but no SSE 4.2 and so an "illegal instruction"
was executed; But in such a case an app should not crash; instead it should
use the CPU ID instruction to determine CPU capabilites

## Your Environment

* Operating System and version: Win10PRO 64bit Anniversary Update (v1607)   CUDA 9.0
* Compiler: VS2017 (toolset 140 of VS2015)    MSVC 19.0.24218.2
* PCL Version:  1.9.1

## Context

surface reconstruction through PCL using /MT option to build all with static library instead of shared library

## Expected Behavior

I would very appreciate pre-built binaries with /MT option  (toolset v140 VS2015 64bit Win)

## Current Behavior

CMAKE not even creates the expected .sln solution files

## Code to Reproduce

run CMAKE on a CPU which has no SSE 4.2 (then cmTC_4a309.exe crashes)
Boost present, but no way to specifiy in CMAKE

## Possible Solution

provide /MT binaries for 64bit Win toolset v140 
or a pure list of all required .h,.hpp,.cpp filess for all of the 8 DLLs listed above; from them those modules could be build without all the other dependencies (they obviously only need Eigen and Boost)

**Comment by UnaNancyOwen** [comment]
Please refer to this document.
https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-9-1-md

You need following settings for build static link library of PCL.
* **PCL**
  * **PCL_SHARED_LIBS** ☐(uncheck)
* **WITH**
  * **WITH_OPENNI2** ☐(uncheck)

**Comment by 3DdeepAI** [comment]
Thank you very much for your answer. Its very helpful.

Your link [https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-9-1-md](https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-9-1-md) should be included first in the readme.md file of PCL, that would have saved me lot of time!
before that I instead did what is presented on: [http://www.pointclouds.org/documentation/tutorials/compiling_pcl_windows.php](http://www.pointclouds.org/documentation/tutorials/compiling_pcl_windows.php)
but there nowhere the "serialization.h issue" of flann-1.8.4 was mentioned. Using 1.9.1 now.


Now I successfully build:
EIGEN 3.3.5: https://gist.github.com/UnaNancyOwen/08e5a9b8f5979ed0077c#file-eigen3-3-5-md
FLANN 1.9.1 https://gist.github.com/UnaNancyOwen/1e3fced09e4430ad0b7b#file-flann1-9-1-md
QHull 2015.2 https://gist.github.com/UnaNancyOwen/ffbe6b05ee0101620d3c#file-qhull-2015-2-md
VTK 8.1.2 https://gist.github.com/UnaNancyOwen/9d16060714ba9b28f90e#file-vtk8-1-2-md
Boost 1.69.0  (build as described for Boost 1.68.0  https://gist.github.com/UnaNancyOwen/d879a41710e9c05025f8#file-boost1-56-0-md)
Microsoft MPI v9.0.1 

In all the projects I was not able to use CMAKE_INSTALL_PREFIX C:\Program Files\...
due to ACL folder protection, so I chose always other destinations.  
there was no warning about that during config in CMAKE, but in Visual Studio then project build failed.
Ok with other destination.

Also it was always enough to build the "INSTALL" project only;
your additional steps "ALL BUILD" and again "INSTALL" were not needed, or did I miss something there?



after Microsoft MPI v9.0.1 was installed for Boost 1.69.0 I added "using mpi ;"    
but got this error message:
MPI auto-detection failed: unknown wrapper compiler mpic++
Please report this error to the Boost mailing list: http://www.boost.org
You will need to manually configure MPI support.

Also OpenNI2 support I had to deactivate yet.
However, finally the PCL.sln solution file was built.

In CMAKE I set :
BOOST_INCLUDE_DIR              to the include folder after running b2 on boost
BOOST_LIBRARYDIR                to the lib folder (to which I built all the .lib files through b2)
BOOST_LIBRARY_DIRS             same as BOOST_LIBRARYDIR
BOOST_ROOT                           the original boost folder 1.69.0
Boost_USE_STATIC_LIBS ON
Boost_USE_MULTITHREADED ON
Boost_USE_STATIC_RUNTIME ON
And I had to manually added these Boost libraries:   filesystem   thread   date_time   iostreams   system


In all Visual Studio Projects then I had to change /MD to /MT  manually,
cause even after some more online search I did not find any global option in Visual Studio to change
that for all projects in a solution. (I have not so much experience with the CMAKE list files, so I wanted to 
keep them unchanged; and so I did not add CMAKE_CXX_FLAGS_RELEASE... there)

The final file pcl_common_release.dll (using /MT) I already built now.

**Comment by 3DdeepAI** [comment]
in frustum_culling.hpp lines 112 + 113:
 
```
  pl_f.block (0, 0, 3, 1).matrix () = (fp_bl - fp_br).cross (fp_tr - fp_br);   // Far plane equation - cross product of the 
  pl_f (3) = -fp_c.dot (pl_f.block (0, 0, 3, 1));                    // perpendicular edges of the far plane
```

there is a **.matrix()**   but it should be a vector, so what should be replaced there?

**Comment by 3DdeepAI** [comment]
in frustum_culling.hpp lines 112 + 113:
 
```
  pl_f.block (0, 0, 3, 1).matrix () = (fp_bl - fp_br).cross (fp_tr - fp_br);   // Far plane equation - cross product of the 
 pl_f (3) = -fp_c.dot (pl_f.block (0, 0, 3, 1));  ;                    // perpendicular edges of the far plane
```

in my project I changed it to:

```
  pl_f.block (0, 0, 3, 1).matrix () = (fp_bl - fp_br).cross (fp_tr - fp_br);   // Far plane equation - cross product of the 
//ORG:  pl_f (3) = -fp_c.dot (pl_f.block (0, 0, 3, 1));                    // perpendicular edges of the far plane
  pl_f (3) = -fp_c.dot ((Eigen::Vector3f)pl_f.block (0, 0, 3, 1));                    // perpendicular edges of the far plane

  pl_n.block (0, 0, 3, 1).matrix () = (np_tr - np_br).cross (np_bl - np_br);   // Near plane equation - cross product of the 
//ORG:  pl_n (3) = -np_c.dot (pl_n.block (0, 0, 3, 1));                    // perpendicular edges of the far plane
  pl_n (3) = -np_c.dot ((Eigen::Vector3f)pl_n.block (0, 0, 3, 1));                    // perpendicular edges of the far plane
```


and a few lines later:


```
// ORG:  pl_r (3) = -T.dot (pl_r.block (0, 0, 3, 1));
// ORG:  pl_l (3) = -T.dot (pl_l.block (0, 0, 3, 1));
// ORG:  pl_t (3) = -T.dot (pl_t.block (0, 0, 3, 1));
// ORG:  pl_b (3) = -T.dot (pl_b.block (0, 0, 3, 1));
  
  pl_r (3) = -T.dot ((Eigen::Vector3f)pl_r.block (0, 0, 3, 1));
  pl_l (3) = -T.dot ((Eigen::Vector3f)pl_l.block (0, 0, 3, 1));
  pl_t (3) = -T.dot ((Eigen::Vector3f)pl_t.block (0, 0, 3, 1));
  pl_b (3) = -T.dot ((Eigen::Vector3f)pl_b.block (0, 0, 3, 1));
```

and so also pcl_filters_release.dll finally built. 

and finally : pcl_features_release.dll  built.

However, after and during compiling  often vcpkgsrv.exe nand svchost.exe (imgsvc) is active 
causing 100% disk usage; which made everything very slow.

But I'm glad, that I built all the modules I wanted.

**Comment by 3DdeepAI** [comment]
I tested them now in my main app and they work fine. I will not build the remaining other PCL modules for now. So thanks @UnaNancyOwen again for your help!!!
