### ISSUE TITLE
Clang-tidy: Automatic replacing of typedefs by using fails

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2791]
`modernize-use-using` of clang-tidy fails, so we have to do it manually or check whats going wrong.

[clang-tidy.log](https://github.com/PointCloudLibrary/pcl/files/2776821/clang-tidy.log)

**Comment by taketwo** [comment]
In most cases the error looks similar to this:

```
There are conflicting changes to /media/sf_pcl/apps/3d_rec_framework/include/pcl/apps/3d_rec_framework/pc_source/source.h:
The following changes conflict:
  Replace 32:9-32:63 with "using PointTPtr = typename pcl::PointCloud<PointT>::Ptr"
  Replace 32:9-32:63 with "using PointTPtr = typename pcl::PointCloud<PointXYZ>::Ptr"
  Replace 32:9-32:63 with "using PointTPtr = typename pcl::PointCloud<PointXYZRGB>::Ptr"
```

One of the `using`s is with template type (`PointT` in this example), and the rest are instantiations with different concrete types. Not clear why clang-tidy does this. Is it possible to limit its scope to only `.h` files (such that it does not see `.cpp` files and template instantiations therein)?

**Comment by SunBlack** [comment]
>  Is it possible to limit its scope to only `.h` files (such that it does not see `.cpp` files and template instantiations therein)?

Sure. Currently I'm always calling `run-clang-tidy -header-filter='.'`, so I could play with `header-filter` (it's a regex, so I have to test how they using it. Maybe `'.+(?<!.cpp)$'` could work).

**Comment by SunBlack** [comment]
Tried it today again with `run-clang-tidy-8` (before it was v6), and it works now :)
