### ISSUE TITLE
[Document out of date] PCL visualizer uses Orbit controller instead of mouse trackball controller

### ISSUE THREAD

**Issue by yiakwy** [PointCloudLibrary/pcl#2795]
PCL visualizer uses orbit controls as default controls. In case that we want zoom in to look at details of computed result of a cloud,we want to translate to a location and zoom in. Is there any solutions for us to use trackball alike controls?

**Comment by taketwo** [comment]
I use the following trick: hover the area you want to zoom in with the mouse and press `f` on the keyboard. The camera will "focus" on that point and zoom in a bit. All the subsequent rotations and zooming will be around this point.

**Comment by tanajikamble13** [comment]
thanks @taketwo. Why point cloud looks suddenly different when clicked with mouse ?
How can I view intensity cloud with gray color where black color represent  lowest intensity and white color represent maxm intensity.

**Comment by kunaltyagi** [comment]
@tanajikamble13 please create new issues for new questions
