### ISSUE TITLE
the question of getting cloud from cad model

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#2806]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler: gcc5.4.0
* PCL Version:1.72

## Context

I want to get the cloud from cad model. Firstly, I export the .STL from solidworks cad model.secondly,I open the .STL in meshlab and export the .ply . Finally i use the tool of pcl to generate the cloud. 

### question 1: When i use `pcl_mesh2pcd`,I find there is some extra point in the cloud. I don't know why.
the .ply opened in the meshlab:
![image](https://user-images.githubusercontent.com/39310744/51743645-4be78680-20d8-11e9-9cb6-47d8838b6f66.png)
the cloud generated by `pcl_mesh2pcd`
![image](https://user-images.githubusercontent.com/39310744/51743707-82250600-20d8-11e9-8dce-39a8b1546a76.png)
You can see in the image, there is some extra point in the cloud.

### question 2: scalar error
I type `pcl_viewer zed1.pcd` to see the cloud. Error occured in the terminal:
```
ERROR: In /build/vtk6-dmAaMa/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x27affd0): No scalar values found for texture input!
```

### question 3 : `pcl_ply2pcd` generate too few point
I tried the `pcl_ply2pcd` to generat the cloud. But the point generated is too few to use as the image show below:
![image](https://user-images.githubusercontent.com/39310744/51744243-22c7f580-20da-11e9-8452-44028e02020d.png)

### question 4: `pcl_mesh_sampling` can't run.
When i tried the `pcl_mesh_sampling` to convert the .ply to .pcd, there is error occured and can't generate the cloud. The error is:
```
Convert a CAD model to a point cloud using uniform sampling. For more information, use: pcl_mesh_sampling -h
ERROR: In /build/vtk6-dmAaMa/vtk6-6.2.0+dfsg1/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (0xd90e90): Input port 0 of algorithm vtkTriangleFilter(0xd8ec70) has 0 connections but is not optional.

ERROR: In /build/vtk6-dmAaMa/vtk6-6.2.0+dfsg1/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (0xd90e90): Input port 0 of algorithm vtkTriangleFilter(0xd8ec70) has 0 connections but is not optional.

ERROR: In /build/vtk6-dmAaMa/vtk6-6.2.0+dfsg1/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 710
vtkCompositeDataPipeline (0xd90e90): Input port 0 of algorithm vtkTriangleFilter(0xd8ec70) has 0 connections but is not optional.

Segmentation fault (core dumped)
```

Can you give me some advice to solve these problem? Thanks a lot!

**Comment by taketwo** [comment]
I'd recommend to start by getting the latest PCL version (1.9.1 or master from git). What you have is really ancient and I'm pretty sure we had a number of fixes in the components you mentioned.

**Comment by TouchDeeper** [comment]
Hi,@taketwo
I installed the pcl 1.9.1,now i have the version1.9.1 and the version1.7(ROS), i don't know how to choose the tool such as pcl_mesh2pcd, pcl_ply2pcd from the 1.9.1 instead of the 1.7. Can you give me some advice,. Thanks a lot!

**Comment by taketwo** [comment]
If you ran `make install` and assuming you did not change default installation path, PCL binaries landed in `/usr/local/bin`. You can execute them by spelling the complete path.

**Comment by TouchDeeper** [comment]
@taketwo  Thanks for your help!
