### ISSUE TITLE
How to convert PCD file to BIN?

### ISSUE THREAD

**Issue by jlllweco** [PointCloudLibrary/pcl#2813]
I have pcd file. How to convert PCD file to BIN? Another question is that Is there any examples to process a lot of files using a script?

Thank s a lot!

**Comment by SergioRAgostinho** [comment]
> How to convert PCD file to BIN? 

Hi. I don't remember any of our `io` functions supporting a file type with an extension `bin`. So I'm tempted to say you will likely have to write that conversion manually.

> Another question is that Is there any examples to process a lot of files using a script?

There's one in
http://pointclouds.org/documentation/tutorials/pairwise_incremental_registration.php#pairwise-incremental-registration

Check the function `loadData`.

**Comment by Camillaaaa** [comment]
May I ask is there any suggestions about manual conversion? I don't understand what's the principle behind it, so it's quite difficult for me.

Thank you so much！

**Comment by jlllweco** [comment]
Thank you so much for your reply.

> If what you are referring by "BIN" format is [this](https://www.cloudcompare.org/doc/wiki/index.php?title=BIN), then you can perhaps use CloudCompare.

Thank you so much for your reply. I have finished it. cloudcompare is very useful. 
As for I process quite a few files. I use command line mode in cloudcompare.
`cloudcomapre.CloudCompare -SAMPLE_MESH POINTS 1000000`
