### ISSUE TITLE
Add const interators in PointCloud to cbegin cend

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2814]
```
apps/in_hand_scanner/src/icp.cpp:407:33: error: no member named 'cbegin' in 'pcl::PointCloud<pcl::PointXYZRGBNormal>'; did you mean 'begin'?
  for (auto it_in = cloud_data->cbegin (); it_in!=cloud_data->cend (); ++it_in)
```

And pointcloud.h:
```
      inline iterator begin () { return (points.begin ()); }
      inline iterator end ()   { return (points.end ()); }
      inline const_iterator begin () const { return (points.begin ()); }
      inline const_iterator end () const  { return (points.end ()); }
```
`cloud_data` is const, so he should use correct version.

_Originally posted by @SunBlack in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI1MjIwMDE1OA==/comments/review_comment_

**Comment by SunBlack** [comment]
Do not rename this method. Just add additional methods `cbegin` and `cend`so we are [conform to stl](https://en.cppreference.com/w/cpp/container/vector/begin).

Reason: Range-based for loop are using begin/end and not cbegin/cend (see [here](https://en.cppreference.com/w/cpp/language/range-for))

**Comment by SunBlack** [comment]
Maybe we can fix this issue for 1.10.0?

**Comment by SergioRAgostinho** [comment]
We are really behind schedule already :/ There's still a lot of boost migrations to complete and this is not really a priority at the moment. I'm opposed to adding additional non-critical stuff. Open for discussion.

**Comment by taketwo** [comment]
If @SunBlack is willing to contribute such iterators (with tests), then why not?

**Comment by SergioRAgostinho** [comment]
It's more me saying that I won't likely review it until the release is out.

In the usual calendar, in average, I give priority to reviewing maintainers' PRs, then users PRs, then actually coding. Right now, I'm only picking up things which are directly related with the release e.g.: boost -> std PRs, vtk component selection and librealsense2 grabber; or if they are extremely trivial. If the PR falls outside these topics, it's likely I wont review it and I will work on submitting changes instead.

**Comment by taketwo** [comment]
Fair enough. So we are certainly not putting it on the milestone. But nevertheless this does not mean that merging such a PR is excluded.
