### ISSUE TITLE
GTEST_USE_OWN_TR1_TUPLE still required?

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2824]
Currently PCl code contains sometimes:

```
#if defined(_MSC_VER)
    #define GTEST_USE_OWN_TR1_TUPLE 0
#endif
```

In current googeltest code `GTEST_USE_OWN_TR1_TUPLE` is not even used anymore (see e.g. https://github.com/google/googletest/commit/abc803e28826b8d2c4817f2c44103e1c1d57a8c2) and since we requires C++14 tuples should be always supported. So can we remove this defines?

**Comment by SergioRAgostinho** [comment]
Makes sense to remove it :+1:
