### ISSUE TITLE
[textureMeshwithMultipleCameras] - mesh not aligned with texture files

### ISSUE THREAD

**Issue by rrbarioni** [PointCloudLibrary/pcl#2830]
Operating System and version: Windows 10
Compiler: Visual Studio 2015
PCL Version: 1.8.1

Hello,
I have a mesh of an object, where its triangles' color are defined by their vertices color.
As the mesh has a blurry aspect, I would like to perform texturization.
I am following the code described at https://github.com/PointCloudLibrary/pcl/blob/master/gpu/kinfu_large_scale/tools/standalone_texture_mapping.cpp
I have a set of images (related to the object) and its respective camera poses.
However, I am having problems when aligning those images with my mesh.

Here is my mesh without textures:
![image](https://user-images.githubusercontent.com/13512712/52372848-568f0d80-2a40-11e9-8805-c7ede2613622.png)

And here is some of my attempts to texturize the mesh:
![image](https://user-images.githubusercontent.com/13512712/52372890-6f97be80-2a40-11e9-9a9d-9547a7ac6270.png)

![image](https://user-images.githubusercontent.com/13512712/52372933-8dfdba00-2a40-11e9-810c-2a14c7b99ed2.png)

I think that I have problems related to the setup of the camera pose.
I have made several attempts:
- I tried to load the rotation matrix, but transposed;
- I tried to load the translation vector, but negative;
- I have also tried the way camera parameters are set as done in https://github.com/PointCloudLibrary/pcl/blob/master/gpu/kinfu_large_scale/tools/standalone_texture_mapping.cpp

Has anybody had a similar problem?
Thanks.

**Comment by rrbarioni** [comment]
Problem solved; I actually was passing the inverse of the pose matrix to the textureMeshwithMultipleCameras function.

**Comment by zengletian1491** [comment]
How do you generate the texture images/patches?

**Comment by kunaltyagi** [comment]
Closing the topic since it's solved. Please continue the discussion regardless of the state.

**Comment by rrbarioni** [comment]
@zengletian1491 for generating the mesh, I used a 3D object reconstruction from unordered RGB images. For this texturization, I actually used one of the input RGB images (and its respective camera pose, obtained from the structure-from-motion step).
