### ISSUE TITLE
Windows silent install (from pre-compiled binary) isn't silent?

### ISSUE THREAD

**Issue by SurferL** [PointCloudLibrary/pcl#2863]
I downloaded the latest pre-compiled binary for Windows (PCL-1.9.1-AllInOne-msvc2017-win64.exe), and tried to install it silently with:

`PCL-1.9.1-AllInOne-msvc2017-win64.exe /S`

However it doesn't seem to install silently? There is a popup for OpenNI 2.2 SDK which wants to confirm the install directory, and hence not finish the silent install.

## Context
Attempting to add PCL as a part of a build chain through CI to include onto build machines.

## Expected Behavior
Successfully installs silently with no popups.

## Current Behavior
A popup occurs for OpenNI 2.2 SDK during installation causing the CI to fail to install PCL.

**Comment by SurferL** [comment]
From looking at [pcl_all_in_one_installer.cmake](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_all_in_one_installer.cmake), OpenNI is installed with:

`'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_PACKAGE}\\\" '`.

I believe, that if the silent switch is used with NSIS install, the `msiexec` command needs the `/quiet` or `/qn` parameter in as well:

`'msiexec /i /qn \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_PACKAGE}\\\" '`.

**Comment by SergioRAgostinho** [comment]
If the fix turns out to be something simple please consider submitting a PR with the changes.

**Comment by SurferL** [comment]
Well,  I suppose there is a questions to ask first:

If installing normally (not-silently), does the user care if Open NI asks where it should be installed? or that it is fine installing in its default location, and no pop up comes up.

If so, the fix above we resolve it... if not, I believe some changes would need to be made in the NSIS installer to support the `SILENT` flag which would then somehow influence the variables in the `pcl_all_in_one_installer.cmake` file.

**Comment by SergioRAgostinho** [comment]
I believe @UnaNancyOwen might be a better qualified person for answering this one.

**Comment by UnaNancyOwen** [comment]
@SurferL Perhaps, I think that adding that change will not be a problem. Please send a pull request.

```patch
  set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS
-       "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_PACKAGE}\\\" '")
+       "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_PACKAGE}\\\" /quiet '")

  set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS
-       "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_SENSOR_PACKAGE}\\\" '")
+       "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI\\\\${OPENNI_SENSOR_PACKAGE}\\\" /quiet '")

  set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS
-         "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI2\\\\${OPENNI2_PACKAGE}\\\" '")
+         "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}\n    ExecWait 'msiexec /i \\\"$INSTDIR\\\\3rdParty\\\\OpenNI2\\\\${OPENNI2_PACKAGE}\\\" /quiet '")
```
