### ISSUE TITLE
Fail to addCube from example code

### ISSUE THREAD

**Issue by ferdyandannes** [PointCloudLibrary/pcl#2869]
## Your Environment

* Operating System and version: Ubuntu 16.04
* PCL Version: 1.8

## Context
Hello I tried to run example code from this example : http://pointclouds.org/documentation/tutorials/moment_of_inertia.php
But it failed to show the bounding box, the bounding box seems have an error like this http://www.pcl-users.org/Use-addCube-to-draw-a-bounding-box-td4042466.html , but there is no correct solution from that post. It only show a solid cube.
Is there anyone successfully run the example code from the site??

I install PCL based on this site : https://machineseez.blogspot.com/2017/06/installing-point-cloud-library-18-on.html

**Comment by ferdyandannes** [comment]
Hello I tried to run example code from this example : http://pointclouds.org/documentation/tutorials/moment_of_inertia.php
But it failed to show the bounding box, the bounding box seems have an error like this http://www.pcl-users.org/Use-addCube-to-draw-a-bounding-box-td4042466.html , but there is no correct solution from that post
Is there anyone successfully run the example code from the site??

* Operating System and version: Ubuntu 16.04
* PCL Version: 1.8

**Comment by taketwo** [comment]
You need to call something like (untested):

```cpp
viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, "OBB");
```

**Comment by lesterlo** [comment]
@taketwo I tested this code on my program. It's working.

Also, If you are lazy, you can set all of the objects in wireframe.
```
viewer->setRepresentationToWireframeForAllActors();
```

If you want to change multiple objects to wireframe, you can need to add a specific id name for it.
```
viewer->addCube(..., id);
viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, pcl::visualization::PCL_VISUALIZER_REPRESENTATION_WIREFRAME, id);
```

### Reference
https://lesterlo.wordpress.com/2018/08/21/pcl-addcube-draw-the-cube-that-not-in-wireframe/
