### ISSUE TITLE
removeNaNFromPointCloud not working with cloud created using push_back

### ISSUE THREAD

**Issue by shomedas** [PointCloudLibrary/pcl#2870]
## Your Environment

* Operating System and version: ubuntu , 16.04, 14.04
* Compiler: gcc 5.4.0,  4.8.4
* PCL Version: 1.8

## Context

Using the camera parameters I create a 3D points from a depth image and then copy to a cloud using push_back.  The zero depth points are converted to nan values which I try to remove using removeNaNFromPointCloud. But it fails to remove such nan points.   However if I load a pcd from an existing pcd file and then use pushback to copy the points, the removenan works fine.

## Expected Behavior

The removeNaNFromPointCloud should remove the nans irrespective of how it is created.

## Current Behavior

removeNaNFromPointCloud works fine if a cloud is loaded using loadpcdfile. If I use push_back to create a pointcloud with nans the API doesnt remove the nans. However if I load a pcd from an existing pcd file and then use pushback to copy nan points, the removeNaNFromPointCloud works fine.

removeNaNFromPointCloud should remove nans irrespective of how it is created.

## Code to Reproduce

#include <pcl/point_types.h>
#include<pcl/io/pcd_io.h>
#include <pcl/filters/filter.h>

int main(int argc, char *argv[]) 
{ 
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_in (new pcl::PointCloud<pcl::PointXYZ>);
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_out (new pcl::PointCloud<pcl::PointXYZ>);

pcl::io::loadPCDFile(argv[1],*cloud_in); **// pcl::removeNaNFromPointCloud doesnt work if this is commented**

pcl::PointXYZ p_nan,p_valid;

p_nan.x   = p_nan.y   = p_nan.z   = std::numeric_limits<float>::quiet_NaN();
p_valid.x = p_valid.y = p_valid.z = 1.0;

cloud_in->push_back(p_nan);
cloud_in->push_back(p_valid);

std::vector<int> ind; 
pcl::removeNaNFromPointCloud(*cloud_in, *cloud_out, ind); 

std::cout << "no. of pts in input=" << cloud_in->size()  << std::endl;
std::cout << "no. of pts in output="<< cloud_out->size() << std::endl;

for (int i=0;i< cloud_out->size();i++ )
{
    std::cout <<"point["<<i<<"]=" << cloud_out->points[i].x << "," 
				  << cloud_out->points[i].y << ","
				  << cloud_out->points[i].z <<  std::endl;
}

return 0; 
}

**Comment by taketwo** [comment]
Try to add `cloud_in->dense = false;` before removing NaNs. When you create a point cloud "by hand" it is assumed to be dense (i.e. not have NaNs). Thus `removeNaNFromPointCloud` is a no-op.

**Comment by shomedas** [comment]
yes I figured out that is_dense=false is needed in case the cloud is hand crafted. closing.

**Comment by juansolana** [comment]
> Try to add `cloud_in->dense = false;` before removing NaNs. When you create a point cloud "by hand" it is assumed to be dense (i.e. not have NaNs). Thus `removeNaNFromPointCloud` is a no-op.

This just made my day. Thanks

**Comment by cardboardcode** [comment]
> Try to add `cloud_in->dense = false;` before removing NaNs. When you create a point cloud "by hand" it is assumed to be dense (i.e. not have NaNs). Thus `removeNaNFromPointCloud` is a no-op.

Can confirm that this worked for me as well. Thanks.

**Comment by madvn** [comment]
Just ran into this issue..

>Expected Behavior
The removeNaNFromPointCloud should remove the nans irrespective of how it is created.

If this is indeed the case, then would it make sense to reopen this as a bug?

cc: @lmaddirala @SuragBalajepalli
