### ISSUE TITLE
Update Style Guide with new for-range loop rules

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2874]
I'm currently in vacation. But maybe you can already update style guide with all rules when use auto, const reference, ... (in loops and in general)

_Originally posted by @SunBlack in https://github.com/PointCloudLibrary/pcl/pull/2838#issuecomment-465691116_

**Comment by SunBlack** [comment]
As far as I remember we have now following rules discussed in #2838:

General for keyword `auto`
* Use always `auto` (if possible) for iterators
* In all other cases code authors can decide if `auto` is used or not

For for-ranged loop
* Use always const reference in case value does not to be modified.

Anything I forgot?

**Comment by Ruchirchheda** [comment]
Can I work on this issue, if no one else is working on it.

**Comment by SergioRAgostinho** [comment]
To my knowledge no one is working on it, so please go ahead. There's a couple of additional changes to perform in the style guide later, in case if you feel like it.

**Comment by Ruchirchheda** [comment]
Are these changes ok?
https://github.com/Ruchirchheda/pcl/commit/b8a3f8aef568d8ebeb9de52c00d3fafdee8793ba

**Comment by Ruchirchheda** [comment]
https://github.com/PointCloudLibrary/pcl/pull/3716#issue-383760878
