### ISSUE TITLE
pointclouds.org hacked

### ISSUE THREAD

**Issue by Wehrdo** [PointCloudLibrary/pcl#2876]
When arriving to pointclouds.org via Google search result, I got directed to a malicious site claiming my computer had a virus. Haven't been able to repeat, but about a month ago someone else mentioned it occurs occasionally in #2381. Opening as a new issue to raise visibility.

**Comment by SergioRAgostinho** [comment]
Thank you for reporting.

**Comment by nylocx** [comment]
Just had the same effect. So seems the servers are somehow infected.

**Comment by aditya369007** [comment]
I have been observing this since the past few weeks, didn't know where to report. 
Sorry

**Comment by pvaananen** [comment]
Happened to me twice on the pointclouds.org index page, latest one today.

**Comment by samkys** [comment]
Something to think about for the page manager:
The problem http: https://www.cloudflare.com/learning/ssl/why-is-http-not-secure/
The solution https: https://letsencrypt.org/

Hope this solves the problem :)

**Comment by aaronrancsik** [comment]
This problem is still exist, tested from different browsers, os, and the site is loading malicious content for first load.

**Comment by plampite** [comment]
Same problem here as well, but just happened randomly with Chrome on Desktop

**Comment by natowi** [comment]
Same here (dating sites), from google search. Worked after fourth try.

**Comment by kunaltyagi** [comment]
New website is up. PR welcome in the new website repo.
* Website: https://pointclouds.org
* Repo: https://github.com/pointcloudlibrary/pointcloudlibrary.github.io
