### ISSUE TITLE
Build on Jetson TX2 - undefined reference to `png_init_filter_functions_neon'

### ISSUE THREAD

**Issue by tilink** [PointCloudLibrary/pcl#2877]
This is my first GitHub issue, please let me know if I need to be doing anything different here. I'm also not very familiar with cmake so maybe (hopefully!) this is a simple fix or workaround?

## Your Environment

* Operating System and version: Jetson TX2 running Ubuntu 16.04 LTS, Jetpack 3.3, L4T 28.2.1
* Compiler: cmake 3.13.4
* PCL Version: 1.9.1

## Context

I'm attempting to build PCL following the [docs](http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php) on my Jetson TX2 (my host computer is not particularly powerful enough for this and I would prefer to develop on the Jetson if possible, but I'm new to these particular things so please let me know if this is not the right way). I can build without changing any of the settings and it works fine.

However, I am wanting to build/use the **face_detection** feature in PCL - this is what my whole project is. I also tried just using what was successful to recreate the face_detection executable from pcl/apps but it needs visualization which apparently I can't seem to build yet.

After building the default, I then went back to ccmake and enabled some more of the modules (like io, apps, visualization, etc), got around a few errors, but cannot get past this:

```
/usr/local/lib/libvtkpng-8.2.so.1: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_pcd_change_viewpoint.dir/build.make:233: recipe for target 'bin/pcl_pcd_change_viewpoint' failed
make[2]: *** [bin/pcl_pcd_change_viewpoint] Error 1
CMakeFiles/Makefile2:6803: recipe for target 'tools/CMakeFiles/pcl_pcd_change_viewpoint.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_pcd_change_viewpoint.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libvtkpng-8.2.so.1: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_concatenate_points_pcd.dir/build.make:233: recipe for target 'bin/pcl_concatenate_points_pcd' failed
make[2]: *** [bin/pcl_concatenate_points_pcd] Error 1
CMakeFiles/Makefile2:6842: recipe for target 'tools/CMakeFiles/pcl_concatenate_points_pcd.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_concatenate_points_pcd.dir/all] Error 2
[ 19%] Linking CXX executable ../../bin/pcl_example_get_max_min_coordinates
/usr/local/lib/libvtkpng-8.2.so.1: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
examples/common/CMakeFiles/pcl_example_get_max_min_coordinates.dir/build.make:225: recipe for target 'bin/pcl_example_get_max_min_coordinates' failed
make[2]: *** [bin/pcl_example_get_max_min_coordinates] Error 1
CMakeFiles/Makefile2:5140: recipe for target 'examples/common/CMakeFiles/pcl_example_get_max_min_coordinates.dir/all' failed
make[1]: *** [examples/common/CMakeFiles/pcl_example_get_max_min_coordinates.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

## Expected Behavior

I believe this should build on the Jetson from what I've seen posted by others, but maybe it's not supported?

## Current Behavior

It will not build when enabling modules other than default.

## Code to Reproduce

Here is my (advanced) ccmake:
![image](https://user-images.githubusercontent.com/33042510/53293256-73884800-3785-11e9-82c9-2afe26f72ca8.png)
![image](https://user-images.githubusercontent.com/33042510/53293258-8d298f80-3785-11e9-98db-cf9aa93dae31.png)
![image](https://user-images.githubusercontent.com/33042510/53293259-97e42480-3785-11e9-9b8f-f26885790d5c.png)
![image](https://user-images.githubusercontent.com/33042510/53293264-a16d8c80-3785-11e9-9e08-fee44981a0ee.png)
![image](https://user-images.githubusercontent.com/33042510/53293267-acc0b800-3785-11e9-9a5e-752ea865b8be.png)
![image](https://user-images.githubusercontent.com/33042510/53293270-b5b18980-3785-11e9-9c5f-faca787af322.png)

## Possible Solution

I have tried so many things to fix this that I lost track, but from what I can tell it may be due to the arm/aarch64 architecture - though I also saw that it should be supported? Similar issues are occuring in Tensorflow and OpenCV:
https://github.com/tensorflow/tensorflow/issues/18643#issue-315405747 (this says it was fixed)
https://github.com/opencv/opencv/issues/7600#issue-186745652 (apprently this was fixed? https://github.com/opencv/opencv/commit/262a52f3063c50fbb1236e2cba2bd3c68f9979bb)

libpng was also patched: https://sourceforge.net/p/libpng/bugs/230/
another workaround later: https://sourceforge.net/p/libpng/bugs/281/
another patch? https://github.com/glennrp/libpng/commit/32784523239c376dfe544bb6c7012c4934624a6d

A SO answer here with a workaround: https://stackoverflow.com/a/39046966

I've tried to add those things to the CMakeLists.txt to disable NEON (from what I understand, could be totally off here) but nothing seems to have an affect. 

Thank you in advance for any advice/assistance!

**Comment by lesterlo** [comment]
I think you can try pcl version 1.8.1 and 1.8.0. I used these version on Jetson TX2 with ubuntu 16.04( jetpack 3.3). I didn't get any error during compilation. I may test pcl version 1.9.1 on TX2 later on.

**Comment by SergioRAgostinho** [comment]
Hey. At first glance, your error log 
```
/usr/local/lib/libvtkpng-8.2.so.1: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
```

is complaining about an undefined reference to `png_init_filter_functions_neon`. Undefined references happen when some header defined a function but the actual implementation cannot found anywhere. This usually is caused by these three cases. 1) One actually forgot to link the library 2) The method was simply not implemented. 3) The method was not exported. 

From the looking at the log this looks like a VTK problem. It is trying to use a method that is "doesn't have". At this point my next step would be to check vtk's source code to find which function is actually invoking `png_init_filter_functions_neon`. Write a simple test app, which simply depends on vtk and invokes any method which makes use of `png_init_filter_functions_neon`. If it fails linking the same way, you'll be sure vtk is the causing the underlying problem here. If that's the case, I suggest asking in their community for some help. If not, then it's likely a problem from our side.

The second thing which flagged my attention was the fact that vtk is installed in `/usr/local/lib` and that is vtk 8.2. 

> I've tried to add those things to the CMakeLists.txt to disable NEON (from what I understand, could be totally off here) but nothing seems to have an affect.

You might think that you've disabled NEON optimizations during vtk's compilation but given your claimed inexperience I'm not sure you should count on that as being a fact. It's probably a good idea to ask the VTK community on how to enable/disable NEON optimizations.

**Comment by onier** [comment]
i fix it by -DVTK_USE_SYSTEM_PNG=ON.

**Comment by Nizarft** [comment]
@onier where did you add this flag?
