### ISSUE TITLE
wrong pcl::ModelCoefficients in pcl::SACSegmentation 2D line fitting

### ISSUE THREAD

**Issue by Osborn28** [PointCloudLibrary/pcl#2881]
hi all,

**environment:**
ubuntu 16.04
pcl 1.8

**question:**
I use pcl::SACSegmentation to fit 2D line(from Hokuyo urg), and want to get pose of the line, but pcl::ModelCoefficients result is wrong.
 (similar to this? #2767 

**code:**
```cpp
    pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients);
    pcl::PointIndices::Ptr inliers(new pcl::PointIndices);
    pcl::SACSegmentation<T> seg;
    seg.setOptimizeCoefficients(true);
    seg.setModelType(pcl::SACMODEL_LINE);
    seg.setMethodType(pcl::SAC_RANSAC);
    seg.setDistanceThreshold(sac_threshold_);
    if(pcl_filtered_ptr_->points.size()>0)
    {
        seg.setInputCloud(pcl_filtered_ptr_);
        seg.segment(*inliers, *coefficients);
        ......
    }
```

**visualization of pointcloud:** 
![1](https://user-images.githubusercontent.com/24198765/53544804-53c89980-3b62-11e9-8797-d9b34e6ff1c2.jpg)

**print coefficients:**
coefficients: 16028112, 0, 16028096, 0, 15904208, 15862672

**details in [http://docs.pointclouds.org/1.8.1/classpcl_1_1_sample_consensus_model_line.html](url) about ModelCoefficients:**
Detailed Description
template<typename PointT>
class pcl::SampleConsensusModelLine< PointT >
SampleConsensusModelLine defines a model for 3D line segmentation.

The model coefficients are defined as:

point_on_line.x : the X coordinate of a point on the line
point_on_line.y : the Y coordinate of a point on the line
point_on_line.z : the Z coordinate of a point on the line
line_direction.x : the X coordinate of a line's direction
line_direction.y : the Y coordinate of a line's direction
line_direction.z : the Z coordinate of a line's direction

you can see, the value of the coefficients is particularly large, and the result after settlement is not correct. Looking forward to your help, thank you.

**Comment by taketwo** [comment]
Please post a full snippet + data to reproduce the issue.

**Comment by Osborn28** [comment]
Thank you for your reply! And my dataset isn't in a generic format,  but the data content is common, which is not different from other Hokuyo urgs.
In fact, I have been using pcl 1.7 before, and everything is normal. Now I change to version 1.8, the problem described above occurred. I just retested in version 1.7, and found that it is indeed correct.
coefficients result of a frame of data:
coefficients: 0.2937, 0.591273, 0, 0.945175, -0.326564, 0

**Comment by Osborn28** [comment]
sorry, i made a mistake.
