### ISSUE TITLE
undefined reference to `vtkInteractorObserver::PickersModified()'

### ISSUE THREAD

**Issue by douxl5516** [PointCloudLibrary/pcl#2884]
## Your Environment
* Operating System and version: Manjaro KDE
* Compiler: g++
* PCL Version: 1.9
## Context
I am using pcl::visualization::CloudViewer. When I compile my project with CMake, the bash shows 
`/usr/bin/ld: /usr/lib/libpcl_visualization.so: undefined reference to vtkInteractorObserver::PickersModified()`
It turns out that the vtk version on my PC is 8.2, the VTK changed its API since 8.2, it removed the function PickersModified().

reference:
https://github.com/Kitware/VTK/commit/8e4f2f7c3a2e87e4567e5d1ff5fe93a32da8f1f0

**Comment by kunaltyagi** [comment]
Not an issue in PCL master. Issue will remain closed.
