### ISSUE TITLE
Problem with Windows builds on Azure

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#2886]
Windows builds on Azure have been failing since late February: https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=3

According to the log, the problem is that `src/gtest-matchers.cc` file is missing from `vcpkg`-installed Gtest.

**Comment by UnaNancyOwen** [comment]
It seems that forgot to add when updating gtest port.
I sent a pull request https://github.com/Microsoft/vcpkg/pull/5521 to fix it.

**Comment by taketwo** [comment]
Thanks for having a look and sending that patch, the build is back to normal already! https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=1874
