### ISSUE TITLE
build failed in ros

### ISSUE THREAD

**Issue by jlyw1017** [PointCloudLibrary/pcl#2889]
## Your Environment

* Operating System and version: Ubuntu 18
* Compiler: mrt builder
* PCL Version: 1.8

## Context
I building pcl in a ros package and met the following error
which should be the problem in this file 
/usr/include/vtk-6.3/vtkMath.h:664:3: error: multi-line comment [-Werror=comment]
have \\
## Current Behavior
Errors     << pcsskit_ros_tool:make /home/yawei/catkin_ws/logs/pcsskit_ros_tool/build.make.012.log
In file included from /usr/include/pcl-1.8/pcl/visualization/impl/pcl_visualizer.hpp:48:0,
                 from /usr/include/pcl-1.8/pcl/visualization/pcl_visualizer.h:2262,
                 from /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:39,
                 from /home/yawei/catkin_ws/src/pcsskit_ros_tool/src/point_preprocessor/point_preprocessor.hpp:21,
                 from /home/yawei/catkin_ws/src/pcsskit_ros_tool/src/point_preprocessor/point_preprocessor.cpp:1:
/usr/include/vtk-6.3/vtkMath.h:664:3: error: multi-line comment [-Werror=comment]
   // a & b \\
   ^
/usr/include/vtk-6.3/vtkMath.h:668:3: error: multi-line comment [-Werror=comment]
   // 1 & 0 \\
   ^
/usr/include/vtk-6.3/vtkMath.h:671:3: error: multi-line comment [-Werror=comment]
   // a & b \\
   ^
In file included from /usr/include/pcl-1.8/pcl/visualization/impl/pcl_visualizer.hpp:48:0,
                 from /usr/include/pcl-1.8/pcl/visualization/pcl_visualizer.h:2262,
                 from /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:39,
                 from /home/yawei/catkin_ws/src/pcsskit_ros_tool/src/point_preprocessor/point_preprocessor.hpp:21,
                 from /home/yawei/catkin_ws/src/pcsskit_ros_tool/src/point_preprocessor/point_preprocessor_nodelet.cpp:5:
/usr/include/vtk-6.3/vtkMath.h:664:3: error: multi-line comment [-Werror=comment]
   // a & b \\
   ^
/usr/include/vtk-6.3/vtkMath.h:668:3: error: multi-line comment [-Werror=comment]
   // 1 & 0 \\
   ^
/usr/include/vtk-6.3/vtkMath.h:671:3: error: multi-line comment [-Werror=comment]
   // a & b \\
   ^

cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/pcsskit_ros_tool-point_preprocessor-nodelet.dir/src/point_preprocessor/point_preprocessor_nodelet.cpp.o] Error 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/pcsskit_ros_tool-point_preprocessor-nodelet.dir/src/point_preprocessor/point_preprocessor.cpp.o] Error 1
make[1]: *** [CMakeFiles/pcsskit_ros_tool-point_preprocessor-nodelet.dir/all] Error 2
make: *** [all] Error 2

**Comment by taketwo** [comment]
Your build fails because warnings from VTK are treated as errors. Try to pass `-Wnoerror=comment`.

**Comment by taketwo** [comment]
Closing due to lack of feedback. Please re-open if needed.
