### ISSUE TITLE
io/CMakeFiles/pcl_io.dir/all    mistake

### ISSUE THREAD

**Issue by Yunworthy** [PointCloudLibrary/pcl#2899]
## Your Environment

* Operating System and version:ubuntu14.04
* Compiler:gcc5.5.0
* PCL Version:1.8.1

## Context
i want to make pcl but it has a mistake
![图片](https://user-images.githubusercontent.com/37265642/54083176-3c0bc500-435b-11e9-841c-c785786c613f.png)
                   ^

## Expected Behavior

i do not know
## Current Behavior
i do not know

## Code to Reproduce
......
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:259:48: error: ‘class xn::DepthMetaData’ has no member named ‘WritableData’
     XnDepthPixel* depth_map = depth_meta_data->WritableData ();
                                                ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:264:36: error: ‘XnDepthPixel’ does not name a type
         depth_map[k] = static_cast<XnDepthPixel> ((*cloud)[k].z * 1000);
                                    ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:282:24: error: ‘class xn::ImageMetaData’ has no member named ‘AllocateData’
       image_meta_data->AllocateData (cloud->width, cloud->height, XN_PIXEL_FORMAT_RGB24);
                        ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:292:24: error: ‘XnRGB24Pixel {aka struct XnRGB24Pixel}’ has no member named ‘nRed’
           image_map[k].nRed = static_cast<XnUInt8> (rgb.r);
                        ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:292:43: error: ‘XnUInt8’ does not name a type
           image_map[k].nRed = static_cast<XnUInt8> (rgb.r);
                                           ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:293:24: error: ‘XnRGB24Pixel {aka struct XnRGB24Pixel}’ has no member named ‘nGreen’
           image_map[k].nGreen = static_cast<XnUInt8> (rgb.g);
                        ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:293:45: error: ‘XnUInt8’ does not name a type
           image_map[k].nGreen = static_cast<XnUInt8> (rgb.g);
                                             ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:294:24: error: ‘XnRGB24Pixel {aka struct XnRGB24Pixel}’ has no member named ‘nBlue’
           image_map[k].nBlue = static_cast<XnUInt8> (rgb.b);
                        ^
/home/bill/pcl-trunk/io/include/pcl/io/pcd_grabber.h:294:44: error: ‘XnUInt8’ does not name a type
           image_map[k].nBlue = static_cast<XnUInt8> (rgb.b);
                                            ^
make[2]: *** [io/CMakeFiles/pcl_io.dir/src/pcd_grabber.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [io/CMakeFiles/pcl_io.dir/all] 错误 2
make: *** [all] 错误 2

## Possible Solution
i do not know

**Comment by Yunworthy** [comment]
![图片](https://user-images.githubusercontent.com/37265642/54083425-1207d200-435e-11e9-8e03-9afdf1aab412.png)

**Comment by andrewameri** [comment]
Hi,

How were you able to solve this issue? I'm getting same errors..

**Comment by Yunworthy** [comment]
Sorry it is been so long that i forgot
