### ISSUE TITLE
CMake Error at cmake/pcl_utils.cmake:397 (message):

### ISSUE THREAD

**Issue by Yunworthy** [PointCloudLibrary/pcl#2902]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler:
* PCL Version:1.8

## Context
.......

-- The imported target "vtkPythonCore" references the file
   "/usr/lib/libvtkPythonCore.so.5.10.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/vtk-5.10/VTKTargets.cmake"
but not all the files it references.

CMake Warning at CMakeLists.txt:361 (message):
  The minimum required version of VTK is 6.2, but found 5.10.1

-- Could NOT find PCAP (missing:  PCAP_LIBRARIES PCAP_INCLUDE_DIRS) 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   date_time
--   iostreams
--   chrono
--   system
--   atomic
--   regex
CMake Error at cmake/pcl_utils.cmake:397 (message):
  size mismatch between PCL_MODULES_DIRS 29 and PCL_MODULES_NAMES_UNSORTED 28
Call Stack (most recent call first):
  CMakeLists.txt:436 (sort_relative)

-- Configuring incomplete, errors occurred!
See also "/home/bill/pcl-trunk/build/CMakeFiles/CMakeOutput.log".
See also "/home/bill/pcl-trunk/build/CMakeFiles/CMakeError.log".

**Comment by taketwo** [comment]
>  The minimum required version of VTK is 6.2, but found 5.10.1

As the message suggests, you need a newer VTK version.

**Comment by Yunworthy** [comment]
yes  now,i have vtk8.0 but some error like

bill@bill:~/pcl-trunk/project$ make
Scanning dependencies of target pcl_test
[ 50%] Building CXX object CMakeFiles/pcl_test.dir/pcl_test.cpp.o
/home/bill/pcl-trunk/project/pcl_test.cpp:3:48: fatal error: pcl/visualization/pcl_visualizer.h: no such file or directory
compilation terminated.
CMakeFiles/pcl_test.dir/build.make:62: recipe for target 'CMakeFiles/pcl_test.dir/pcl_test.cpp.o' failed
make[2]: *** [CMakeFiles/pcl_test.dir/pcl_test.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pcl_test.dir/all' failed
make[1]: *** [CMakeFiles/pcl_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
 
i find this  file ,i can not find it in /usr/local/include

**Comment by Yunworthy** [comment]
i want to make a test  but i run into this problem, what is unreferenced definition,why can not find vtk i can not solve this problem

bill@bill:~/pcl-pcl-1.8.1/project$ cmake .
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
-- Could NOT find ensenso (missing:  ENSENSO_LIBRARY ENSENSO_INCLUDE_DIR) 
** WARNING ** io features related to ensenso will be disabled
-- Could NOT find DAVIDSDK (missing:  DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
** WARNING ** io features related to davidSDK will be disabled
-- Could NOT find DSSDK (missing:  _DSSDK_LIBRARIES) 
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

** WARNING ** io features related to libusb-1.0 will be disabled
-- looking for PCL_COMPONENT
-- Could NOT find PCL_COMPONENT (missing:  PCL_COMPONENT_LIBRARY PCL_COMPONENT_INCLUDE_DIR) 
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bill/pcl-pcl-1.8.1/project
bill@bill:~/pcl-pcl-1.8.1/project$ make
[ 50%] Linking CXX executable pcl_test
CMakeFiles/pcl_test.dir/pcl_test.cpp.o：在函数‘main’中：
pcl_test.cpp:(.text+0x277)：对‘pcl::visualization::CloudViewer::CloudViewer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
pcl_test.cpp:(.text+0x2ef)：对‘pcl::visualization::CloudViewer::showCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> const> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
pcl_test.cpp:(.text+0x32a)：对‘pcl::visualization::CloudViewer::wasStopped(int)’unreferenced definition
pcl_test.cpp:(.text+0x347)：对‘pcl::visualization::CloudViewer::~CloudViewer()’unreferenced definition
pcl_test.cpp:(.text+0x3a6)：对‘pcl::visualization::CloudViewer::~CloudViewer()’unreferenced definition
pcl_test.cpp:(.text+0x401)：对‘pcl::visualization::CloudViewer::~CloudViewer()’unreferenced definition
collect2: error: ld returned 1 exit status
CMakeFiles/pcl_test.dir/build.make:325: recipe for target 'pcl_test' failed
make[2]: *** [pcl_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pcl_test.dir/all' failed
make[1]: *** [CMakeFiles/pcl_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ManyingZhang** [comment]
CMake Error at cmake/pcl_utils.cmake:396 (message):
  size mismatch between PCL_MODULES_NAMES (length 21) and
  PCL_MODULES_NAMES_UNSORTED (length 4)
Call Stack (most recent call first):
  CMakeLists.txt:441 (sort_relative)

i install pcl1.9.0 in ubuntu18.04 , and trouble with this problem, how should i solve it?

**Comment by kunaltyagi** [comment]
Please open a new issue for that. Closing this due to activity

**Comment by Jaqen-H-ghar** [comment]
Hi，@Yunworthy

I met the same problem with you,

-- Could NOT find ensenso (missing: ENSENSO_LIBRARY ENSENSO_INCLUDE_DIR)
** WARNING ** io features related to ensenso will be disabled
-- Could NOT find DAVIDSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR)
** WARNING ** io features related to davidSDK will be disabled
-- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES)
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtk" references the file
"/usr/bin/vtk"
but this file does not exist. Possible reasons include:

The file was deleted, renamed, or moved to another location.
An install or uninstall procedure did not complete successfully.
The installation package was faulty and contained
"/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.



I solved the first and second line by installing ensenso and davidSDK. but still stuck on DSSDK, have you solved it yet?

**Comment by larsleimbach** [comment]
I had the same mistake because I installed the necesarry additional software in the PCL-Source-file folder.
So my error was : `size mismatch between PCL_MODULES_DIRS 31 and PCL_MODULES_NAMES_UNSORTED 28` because I installed 3 additional plug-ins. Maybe in your case you installed there on additional software too ?

**Comment by ManyingZhang** [comment]
您好，您的邮件我已收到，谢谢！This is an automatic reply, confirming that your e-mail was received.Thank you！

**Comment by OriKovacsiKatz** [comment]
I had this sort of message as well and cmake refused to generate a Makefile. (ubuntu 18.04 inside *.sqsh container under slurm)
pcl 1.8.1
CMake Error at cmake/pcl_utils.cmake:406 (message):
  size mismatch between PCL_MODULES_DIRS 29 and PCL_MODULES_NAMES_UNSORTED 28

I have a very simple resolution to this issue:
simply printed  the PCL_MODULES_DIRS and PCL_MODULES_NAMES_UNSORTED modules names
and noticed the wrapping tool (3DSmoothNet) has a script to build pcl, in one of the stages  
the script generates a file link 'pcl' pointing to 'pcl-trank' inside pcl folder.

this additional folder sarcastically is counted as a module under pcl and so PCL_MODULES_DIRS 
counts one DIR too much :)

I added a Message in the sort lines  'cmake/pcl_utils.cmake:406' display all directories and all required modules
it took me 5 seconds to compare and identify 'pcl-trank' folder link is not a mudule, erased it and CMake passed like 
a ninja!

**Comment by ManyingZhang** [comment]
您好，您的邮件我已收到，谢谢！This is an automatic reply, confirming that your e-mail was received.Thank you！
