### ISSUE TITLE
Ground filter not work properly

### ISSUE THREAD

**Issue by jinfagang** [PointCloudLibrary/pcl#2903]
I have a simple ground filter:

```
 pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients);
    pcl::PointIndices::Ptr inliers(new pcl::PointIndices);

    pcl::SACSegmentation<PointT> seg;
    seg.setOptimizeCoefficients(true);
    seg.setModelType(pcl::SACMODEL_PLANE);
    seg.setMethodType(pcl::SAC_RANSAC);
    seg.setDistanceThreshold(0.15);
    seg.setInputCloud(cloud);
    seg.segment(*inliers, *coefficients);

    if (inliers->indices.empty())
    {
      LOG(ERROR) << "Could not found any inliers.";
    }

    // extract ground
    pcl::ExtractIndices<PointT> extractor;
    extractor.setInputCloud(cloud);
    extractor.setIndices(inliers);
    extractor.setNegative(true);
    extractor.filter(*cloud_filtered);
```

But the result is not stable, the ground can segment out and most of time it does not work. the lidar sensor stay in a static place which makes cloud does not change at all:

![image](https://user-images.githubusercontent.com/21303438/54104874-4f2a9d80-440c-11e9-841e-a844f93aadd6.png)

it is not work

**Comment by mvieth** [comment]
I don't completely understand what you want to do. Do you want to remove the ground? Or keep the ground and remove everything else? `SACSegmentation` as you are using it tries to find a plane. To understand better what is happening in the segmentation, I would recommend to enable more logging with `pcl::console::setVerbosityLevel(pcl::console::L_VERBOSE);`. If the point cloud you are using has a specific orientation, e.g. that the xy-plane is the ground plane and the z-axis is the "up"-direction, you could easily use the PassThrough filter to remove every point where `-0.1<z<0.1`.
If you still have this problem, feel free to comment or reopen this issue.
