### ISSUE TITLE
HDLGrabber PCAP end of file check missing

### ISSUE THREAD

**Issue by akerckhofs** [PointCloudLibrary/pcl#2906]
### Issue
The HDLGrabber supports pcap files but doesn't have any flag for reaching the end of the file. This causes us to have to loop indefinitely as gaps in time between packet arrival are processed in real-time. A 30 seconds gap between 2 bursts of packets will result in the first burst being processed when it would have arrived and the second being processed 30 seconds later.

### Proposed solution
An indefinite loop is hardly ideal so I propose an additional flag which gets flipped when the end-of-file is reached and then either adding it as an extra boolean check for the `isRunning()` method or adding in another method entirely.

Libpcap returns a value of `-1` from `pcap_next_ex` when the end of file is reached. The current implementation makes use of this to exit the loop so all that would be needed is to flip a flag after the loop has exited.

Ideally an additional method would be used as you might want to grabber to keep running in some niche cases where the pcap file is still being written to.

### Code

```
bool
pcl::HDLGrabber::isRunning () const
{
  return (!hdl_data_.isEmpty () || (hdl_read_packet_thread_ != NULL && !hdl_read_packet_thread_->timed_join (boost::posix_time::milliseconds (10))) || !pcap_end_of_file);
}
```

```
void
pcl::HDLGrabber::readPacketsFromPcap ()
{
 ............
  while (returnValue >= 0 && !terminate_read_packet_thread_)
  {
    if (lasttime.tv_sec == 0)
    {
      lasttime.tv_sec = header->ts.tv_sec;
      lasttime.tv_usec = header->ts.tv_usec;
    }
    if (lasttime.tv_usec > header->ts.tv_usec)
    {
      lasttime.tv_usec -= 1000000;
      lasttime.tv_sec++;
    }
    uint64_t usec_delay = ((header->ts.tv_sec - lasttime.tv_sec) * 1000000) +
    (header->ts.tv_usec - lasttime.tv_usec);

    boost::this_thread::sleep (boost::posix_time::microseconds (usec_delay));

    lasttime.tv_sec = header->ts.tv_sec;
    lasttime.tv_usec = header->ts.tv_usec;

    // The ETHERNET header is 42 bytes long; unnecessary
    enqueueHDLPacket (data + 42, header->len - 42);

    returnValue = pcap_next_ex (pcap, &header, &data);
  }
  pcap_end_of_file = true;
}
```

**Comment by taketwo** [comment]
@UnaNancyOwen as far as I remember you used this grabber. Do you have an opinion here?

**Comment by UnaNancyOwen** [comment]
Sorry, I still do not understand the problem correctly.
Please help me to understand this problem.

In case of reached end of file, Does it mean that the following part conditions are not enough to isRunning()? The following part is waiting for the thread to finish.
```
(hdl_read_packet_thread_ != NULL && !hdl_read_packet_thread_->timed_join (boost::posix_time::milliseconds (10))
```

**Comment by akerckhofs** [comment]
This was my original thought too and it turns out you're right. I did some more tests today with the pcap files provided by Velodyne themselves and these appear to work correctly.

I'll take a look into what might be causing my other pcap files to work incorrectly. I'm closing the issue as it is clearly an issue on my end. Apologies for the inconvenience.

**Comment by UnaNancyOwen** [comment]
No problem, bug reporting is one of the important contribution.
Please open this again when reproduce this problem.
