### ISSUE TITLE
How can I resize an organized point cloud while preserving the contents?

### ISSUE THREAD

**Issue by msy22** [PointCloudLibrary/pcl#2908]
I have a organized point cloud which is roughly of the form:

```
cloud.points = [[ P1, P2, P3, 0, 0, 0 ],
                [ P4, P5, P6, 0, 0, 0 ],
                [ P7, P8, P9, 0, 0, 0 ],
                [  0,  0,  0, 0, 0, 0 ]]
```

Where I have a 2D arrangement of points (P1-P9) that I want to keep, and know the desired row and column dimensions that these points all lie within. The `cloud.points` structure is larger than this, and the excess space is padded with blank points (denoted by `0`). 

My question is: how can I resize the cloud to dimensions of row*col such that points P1-P9 are preserved and the padding zero points are removed?

This is a generalized question. The wider context is that I am trying to read LiDAR data, which I do not know the extents of in advance, organize it and then prune the points structure back to only the points I was able to fill in. I realize this is a question and not a bug/issue, but the mailing list seems dead/not working? If this is better suited to StackOverflow, let me know and I will shift it there.

## Your Environment

* Operating System and version: Ubuntu 14.04
* Compiler: GCC v4.8.4
* PCL Version: 1.8.1
* C++ Version: C++11

## Context

The `cloud.points` variable is of the type `std::vector< PointT, Eigen::aligned_allocator< PointT >>` as per the [API](http://docs.pointclouds.org/1.8.1/classpcl_1_1_point_cloud.html), which is more complicated than the standard `vector` object, and has a couple of overloaded function definitions provided in [Eigen/StdVector.h](https://github.com/libigl/eigen/blob/master/Eigen/src/StlSupport/StdVector.h).

The cloud itself is defined as a standard PCL point cloud object:
```C++
pcl::PointCloud<pcl::PointXYZ> cloud;
```
But obviously this should be applicable to point clouds with any other point type.

## Solutions I've Tried

I have tried the following methods:

<details><summary>Method 1</summary>
<p>

I have tried using the typical `resize` function:

```C++
// Method 1
cloud.height = row;
cloud.width = col;
cloud.points.resize(cloud.height * cloud.width);
```
However this does not seem to take into account the cloud height and width, according to [this line in point_cloud.h](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_cloud.h#L454) which just runs the normal resize function without accounting for the height/width.

</p>
</details>

<details><summary>Method 2</summary>
<p>

I've also tried re-sizing the outer and inner separately, as suggested by several StackOverflow questions for re-sizing generic vector objects.

```C++
// Method 2
cloud.points.resize(row);     // Re-sizes the outer vector
for (int k=0; k < row; k++)   // Re-size the inner vectors
{
  cloud.points[k].resize(vector<PointT, Eigen::aligned_allocator<PointT>>(col));
}
```
However this generates compilation errors about the `vector<PointT, Eigen::aligned_allocator<PointT>>` object not having a member function called "resize".

</p>
</details>

<details><summary>Method 3</summary>
<p>

I have also tried the one-line, 2-parameter resize method which the code in [Eigen/StdVector.h](https://github.com/libigl/eigen/blob/master/Eigen/src/StlSupport/StdVector.h) seems to support:

```C++
// Method 3
cloud.points.resize(row, vector<PointT, Eigen::aligned_allocator<PointT>>(col));
```

However this fails to compile with a lot of errors I don't really understand:

```
/home/matt/canis_repo/workspace/src/canis/src/testing_script.cpp: In instantiation of ‘void OrganizePointCloud(sensor_msgs::PointCloud2, pcl::PointCloud<PointT>&, int) [with PointType = pcl::PointXYZ; sensor_msgs::PointCloud2 = sensor_msgs::PointCloud2_<std::allocator<void> >]’:
/home/matt/canis_repo/workspace/src/canis/src/testing_script.cpp:852:51:   required from here
/home/matt/canis_repo/workspace/src/canis/src/testing_script.cpp:728:3: error: no matching function for call to ‘std::vector<pcl::PointXYZ, Eigen::aligned_allocator<pcl::PointXYZ> >::resize(int&, std::vector<pcl::PointXYZ, Eigen::aligned_allocator<pcl::PointXYZ> >)’
   cloud.points.resize(rings, vector<PointType, Eigen::aligned_allocator<PointType>>(columns));
   ^
/home/matt/canis_repo/workspace/src/canis/src/testing_script.cpp:728:3: note: candidates are:
In file included from /usr/include/eigen3/Eigen/StdVector:23:0,
                 from /home/matt/canis_repo/workspace/src/canis/src/testing_script.cpp:15:
/usr/include/eigen3/Eigen/src/StlSupport/StdVector.h:77:8: note: void std::vector<T, Eigen::aligned_allocator<T> >::resize(std::vector<T, Eigen::aligned_allocator<T> >::size_type) [with T = pcl::PointXYZ; std::vector<T, Eigen::aligned_allocator<T> >::size_type = long unsigned int]
   void resize(size_type new_size)
        ^
/usr/include/eigen3/Eigen/src/StlSupport/StdVector.h:77:8: note:   candidate expects 1 argument, 2 provided
/usr/include/eigen3/Eigen/src/StlSupport/StdVector.h:105:8: note: void std::vector<T, Eigen::aligned_allocator<T> >::resize(std::vector<T, Eigen::aligned_allocator<T> >::size_type, const value_type&) [with T = pcl::PointXYZ; std::vector<T, Eigen::aligned_allocator<T> >::size_type = long unsigned int; std::vector<T, Eigen::aligned_allocator<T> >::value_type = pcl::PointXYZ]
   void resize(size_type new_size, const value_type& x)
        ^
/usr/include/eigen3/Eigen/src/StlSupport/StdVector.h:105:8: note:   no known conversion for argument 2 from ‘std::vector<pcl::PointXYZ, Eigen::aligned_allocator<pcl::PointXYZ> >’ to ‘const value_type& {aka const pcl::PointXYZ&}’
make[2]: *** [canis/CMakeFiles/testing_script.dir/src/testing_script.cpp.o] Error 1
make[1]: *** [canis/CMakeFiles/testing_script.dir/all] Error 2

```

</p>
</details>

**Comment by taketwo** [comment]
`pcl::PointCloud` objects store points in a flat vector. There is no difference between organized and non-organized point clouds in this respect. So with your method 1 you are on the right track. What you need to do next is iterate over the points you want to copy and put them in the right locations in the new cloud using `at(column, row)` or `operator(column, row)` method. Also note that there is a special point cloud [constructor](https://github.com/PointCloudLibrary/pcl/blob/dd905161a242087a21ef367a6070ee86556ba2ac/common/include/pcl/point_cloud.h#L227) that creates an organized point cloud, so your snippet could be replaced with `pcl::PointCloud<pcl::PointXYZ> cloud(col, row);`

> The `cloud.points` variable is of the type `std::vector<PointT, Eigen::aligned_allocator<PointT>>` ... which is more complicated than the standard vector object

Not really. The second template parameter only affects allocation of memory for the vector. From the users viewpoint that makes no difference, it's still a flat vector of `PointT` objects. This is why your methods 2 and 3 don't work.

**Comment by msy22** [comment]
Thanks for the info @taketwo! I'm already using `cloud(col, row)` to insert points, I'm just not sure how to reduce the dimensions of the organized cloud afterwards.

I probably should have provided more detail. At the moment, I'm converting Velodyne HDL-32 data from a ROS `sensor_msgs::PointCloud2` object to a `velodyne_pointcloud::PointXYZIR` object so I can access the ring information, and then converting this to an organized `PointCloud<PointXYZ>` cloud where the "ring" determines the row, and I track the columns to make sure all the points are entered in the right order. 

I can't know in advance how many points will be in a row/ring of LiDAR data as some laser beams may deflect and lose the point... so I have to over-size the vector. But if don't remove the blank points afterwards, when I use this organized cloud for mesh generation, this happens: 

![image](https://user-images.githubusercontent.com/17462459/54231995-903ac300-456e-11e9-980b-5c55bf93bc20.png)

Which obviously causes problems later on, so I can't simply leave the blank points there. If I use the `cloud.points.resize(col, row)` method, then the rows and columns aren't respected, so in the sample cloud below, the points in red get deleted from the cloud:

![image](https://user-images.githubusercontent.com/17462459/54233007-dd1f9900-4570-11e9-8f32-3870be2cd217.png)

This happens even if I created the cloud in question using the organized constructor you mentioned above `PointCloud<PointXYZ> cloud(col, row);` This isn't an option either as I do want that data. 

And unfortunately I can't simply delete the points individually as the [API](http://docs.pointclouds.org/1.8.1/classpcl_1_1_point_cloud.html#a06463926e7cbe52ed3c024c7bc7565d3) explicitly states that using the `erase` function destroys the organized nature of the cloud.

So at this point, it looks like there might not be a clear solution to this problem. If that is the case I might be better to iteratively search for the blank points, and manually convert their coordinates to NaN, so they won't be used during mesh generation.

**Comment by taketwo** [comment]
Sorry, perhaps it was not clear from my answer, but it's not possible to "trim" zero points (from your initial example) by simply resizing the point cloud. So yes, you will have to resort to one of the options you listed. I can offer you an additional variant of the second option: after determining desired "compact" dimensions you don't create a new point cloud, but rather move points to their new locations within the new cloud and then shrink the point cloud.

Side note: you will be surprised what `cloud.points.resize(col, row)` does! `points` is a flat standard vector, so `points.resize()` with two arguments is the option (2) on [this page](https://en.cppreference.com/w/cpp/container/vector/resize). So by using this method you shrink your point cloud to a single row.

**Comment by msy22** [comment]
Ah, yeah I was afraid that would be the case. At least there is still a work-around! I don't quite understand your additional variant of the second option though.

And that makes sense, that explains the behaviour in the second image in my last post. All those red points must get cut out of the new single row.

**Comment by msy22** [comment]
So, both of the solutions I listed seem to work OK. Obviously number 1 results in unnecessary bloat in the cloud so I've gone with number 2, which essentially operates like this pseudo-code:

```C++
int columns = (num_points / rings) * 1.3;    // over-size by 30%
PointCloud<PointType> tmp_cloud(columns, rings);

// Organize the point cloud using tmp_cloud

output_cloud = PointCloud<PointType>(correct_num_columns, rings);
output_cloud.height = static_cast<uint32_t>(rings);
output_cloud.width = static_cast<uint32_t>(correct_num_columns);
for (int col=0; col < correct_num_columns; col++)
{
  for (int row=0; row < rings; row++)
  {
    output_cloud(col, row) = tmp_cloud(col, row);
  }
} 
```

Since I know both of these methods are valid work-arounds for the problem, I think this issue can probably be closed up.

**Comment by taketwo** [comment]
I'll use a toy example to explain my variation of the second option. Imagine organized 3x3 point cloud. On the left I show how it looks logically, and on the right its actual memory layout:

```
| 0 1 2 |             | 0 1 2 3 4 5 6 7 8 |
| 3 4 5 |
| 6 7 8 |
```

Now let's say the rightmost column is zero points and you want to remove it. Thus this is what we want to achieve:

```
| 0 1 |               | 0 1 3 4 6 7 |
| 3 4 |
| 6 7 |
```

So my proposal is to think in terms of actual memory layout and rearrange items in the vector using one-dimensional accesses:

```
| 0 1 2 3 4 5 6 7 8 |   ->    | 0 1 3 4 6 7 |
```

**Comment by msy22** [comment]
Aaaaahhh, ok that clears up everything. I wasn't sure how the data was actually being stored in memory. That explains why every method that copies the points as a single block of data will fail - because the points we want to remove/leave behind are embedded throughout the vector. 

How much faster is one-dimensional accessing that the pseudo-code I listed above?

**Comment by taketwo** [comment]
In two-dimensional case you have just one extra multiplication and addition per access (to compute flat index). This should not make any noticeable difference because fetching data from memory is longer than arithmetic operations by a magnitude anyway. But note that the advantage of my variation comes not from one-dimensional vs. two-dimensional accesses, but from the fact that you don't need to allocate memory for the shrinked point cloud.

**Comment by msy22** [comment]
Ah, I see. Thanks for the explanation! The row-by-column solution works for now, so I'm going to move on to other problems. But this would be worth revisiting if I or anyone else need a more efficient solution.

**Comment by Suujy** [comment]
After browsing your guys conversion, I still don't understand how to resize the point cloud, in the meanwhile, keep objects' shape. 

So how the problem is solved finally?

**Comment by kunaltyagi** [comment]
From the [OP's reply above](https://github.com/PointCloudLibrary/pcl/issues/2908#issuecomment-472686544) and [the docs](http://docs.pointclouds.org/trunk/classpcl_1_1_point_cloud.html) we can create the following function:
```c++
auto resize_row_col(const pcl::PointCloud<PointT>& pc,
    std::size_t rows, std::size_t cols) -> decltype(auto) {
  assert(rows <= pc.width);
  assert(cols <= pc.height);
  pcl::PointCloud<PointT> output;
  output.points.reserve(rows*cols);
  for (std::size_t i = 0; i < rows; ++i) {
    for (std::size_t j = 0; j < cols; ++j) {
      output.emplace_back(pc(j, i));  // doc says column, row access
    }
  }
  return output;
}
```
If this is something that should be in the library, please reply with a use-case different from above. Please don't reply if you found this useful. Just a thumbs up would suffice.

Personally I'd recommend using indices to solve this issue so that the original point-cloud remains and multiple algorithms can be applied on it creating a compute graph.
