### ISSUE TITLE
when I run point cloud compression sample code with device intelrealsense d435,I meet a bug!

### ISSUE THREAD

**Issue by cucrui** [PointCloudLibrary/pcl#2915]
## Your Environment

* Operating System and version: ubuntu18.0
* Compiler:gcc
* PCL Version:1.9.0

I want to compression real time point cloud straeam with pcl::io::OctreePointCloudCompression<> method, and I just run sample code from PCL org document, but when I run this code, I meet this termination named "terminate called after throwing an instance of ' std::length_error' what () : vector::reserve"
I guess maybe when compress point cloud, the use of vector reach the max length of vector.
so anyone meet the same problem or how can i fix it.
Thx for any reply!

**Comment by kunaltyagi** [comment]
Sorry for the delay. If you still have access to the hardware, can you perform more debugging and report back with some of the following:
* gdb stack trace
* valgrind (or any other santizer for) memcheck
* inputs that can reliable cause the crash (basically a MCVE)
