### ISSUE TITLE
Magic number in height map?

### ISSUE THREAD

**Issue by edwardwterry** [PointCloudLibrary/pcl#2920]
Does anyone have insight into the reason behind the magic number of 60 at this line?

https://github.com/PointCloudLibrary/pcl/blob/cc7fe363c6463a0abc617b1e17e94ab4bd4169ef/people/include/pcl/people/impl/height_map_2d.hpp#L103

**Comment by kunaltyagi** [comment]
It's clearing 2 feel high obstacles, IIRC. Might be wrong. The comments are certainly wrong wrt maximum height.
