### ISSUE TITLE
fromPCLPointCloud2 is 30x heavier in 1.8 on 18.04 vs 16.04 1.7

### ISSUE THREAD

**Issue by SteveMacenski** [PointCloudLibrary/pcl#2923]
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: apt installed package
* PCL Version: 1.8

## Context

In trying to migrate ROS packages from Kinetic (16.04) to Melodic (18.04) with the PCL library change of 1.7 to 1.8 for the ROS navigation stack plugins. 

## Expected Behavior

`fromPCLPointCloud2` converting a ROS type pointcloud to a PCL pointcloud to operate on.

## Current Behavior

We're seeing that the conversion method `fromPCLPointCloud2` takes 30x more CPU usage than it did in Kinetic, resulting in it no longer being computationally feasible to convert from ROS pointcloud2's to PCL pointcloud for operations in real time. 

## Code to Reproduce

This ticket in STVL covers reproduction method https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/117

**Comment by taketwo** [comment]
`fromPCLPointCloud2` is quite stable, we only had a [couple of bug fixes](https://github.com/PointCloudLibrary/pcl/commits/master/common/include/pcl/conversions.h) in the last five years. I think the only commit that has a potential to make such a drastic difference in runtime is a65b7069fbd.

**Comment by SteveMacenski** [comment]
I agree, its strange, I'm following up with the folks reporting the issue to dive deeper into it. I'm not seeing it on my side (16.04 with 1.7.x base installed with ROS). Might spin up a 18.04 machine next week to look into it there

**Comment by doisyg** [comment]
On the same hardware, I am not seeing it with Ubuntu 16.04 and PCL 1.7.x installed with ROS, but I am seeing it with Ubuntu 18.04 and PCL 1.8.x installed with ROS (with ubuntu deb libpcl-dev I believe). I will tried to create an isolated code sample around next week so it can be easily tested independently from STVL.

**Comment by doisyg** [comment]
Some updates, I tested outside the ROS STVL package on kinetic and melodic, with the minimal code below,  and I cannot reproduce the issue: I see the same performance on both distribution.

```
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/conversions.h>
#include <chrono>

using namespace std::chrono;

int
main (int argc, char** argv)
{
  pcl::PCLPointCloud2::Ptr cloud (new pcl::PCLPointCloud2 ());

  // Fill in the cloud data
  pcl::PCDReader reader;
  // Replace the path below with the path where you saved your file
  reader.read ("table_scene_lms400.pcd", *cloud); // Remember to download the file first!

  high_resolution_clock::time_point t1 = high_resolution_clock::now();
  for (int i=0;i<1000;i++) {
      pcl::PointCloud<pcl::PointXYZ> cloudXYZ;
      pcl::fromPCLPointCloud2(*cloud, cloudXYZ);
  }
  high_resolution_clock::time_point t2 = high_resolution_clock::now();
  auto duration = duration_cast<milliseconds>( t2 - t1 ).count();

  std::cerr << "Conversion time: " << duration << "";

  return (0);
}
```
PCD file to use is from the PCL tutorials: https://raw.github.com/PointCloudLibrary/data/master/tutorials/table_scene_lms400.pcd

We will investigate more to see exactly were it is coming from.
