### ISSUE TITLE
[CI] Build.MacOS keeps "In progress" status for 18 days

### ISSUE THREAD

**Issue by leemgs** [PointCloudLibrary/pcl#2924]
## Issue
It is strange. In case of PR #2771, The **build.MacOS** has been troubled 18 days ago. Why this issue is still not fixed?

* Screenshot:
![image](https://user-images.githubusercontent.com/82404/54393350-4b896600-46ed-11e9-93c0-07bb699e5a7c.png)

![image](https://user-images.githubusercontent.com/82404/54393644-04e83b80-46ee-11e9-9057-f848e8d002cb.png)

## Observation
As we can see, Many PRs as well as the PR (#2771) that has been submitted 15 days ago, do not get the review process and merging process in time because PCL's CI facility has been sometimes running for long days. BTW, Why this issue has been generated repeatedly? 

1. In case of the PR #2771, It is submitted on 14-Jan-2019
2. The PR had been reviewed from 14-Jan-2019 to Feb-25-2019
3. The PR had been updated by an author according to the review process on Feb-25-2019
4. On Mar-15-2019, The Build.MacOS is still "In progress - This check has started...".

## Question
What is a possible reasons? Who is in charge of the infrastructure and system of the CI facility in case of the PCL (Point Cloud Library) GitHub repository?

**Comment by taketwo** [comment]
PCL is maintained by a few unpaid volunteers. The time that we can spend on reviews, CI maintenance, etc. is very limited.

Personally, I haven't reviewed #2771 because I'm awaiting author's feedback on #2878.

**Comment by leemgs** [comment]
> PCL is maintained by a few unpaid volunteers. The time that we can spend on reviews, CI maintenance, etc. is very limited.

As we all know, there are lots of CI facilities in case that we use github.com hosting service. 
* https://github.com/marketplace/category/continuous-integration

When we try to use CI facilities of the github.com service for PCL, isn't the CI facilities not free?

**Comment by SergioRAgostinho** [comment]
We've been through this a couple of times and we've just recently migrated to Azure Pipelines. It's not a perfect, but the complains we have are really minor vs what we had before.

Usually what kills us are the limitations on build times. PCL is heavy, it takes time to compile. When we were on Travis the builds always aborted for exceeding the maximum allowed build time. Passing files (artifacts) between jobs, which would enable preserving compiled binaries to be used in later stages, is usually not allowed, not implemented or require external private storage we don't have.

If you feel there exists better options for us to use then I would ask that you try to replicate or improve our CI current pipeline, in your personal fork, with whatever service you think is better. If you succeed and your result is better, I don't think we'll have any problems migrating.

**Comment by taketwo** [comment]
It looks like the reported issue of staying in "In progress" state for many days was a one-time issue, so closing this.
