### ISSUE TITLE
eigen error on 32 bits odroid xu4

### ISSUE THREAD

**Issue by GaoGeolone** [PointCloudLibrary/pcl#2936]
## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: C++7
* PCL Version: 1.8
* ROS version: Melodic

## Context

Nodes frequently died with eigen error, I use gdb to trace back what happend, here is the info:

multiScanRegistration: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:109: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 4; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.

Thread 1 "multiScanRegist" received signal SIGABRT, Aborted.
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
47	../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xb674bb32 in __libc_signal_restore_set (set=0xbeffdb84)
    at ../sysdeps/unix/sysv/linux/nptl-signals.h:80
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb674c82e in __GI_abort () at abort.c:79
#4  0xb6746d22 in __assert_fail_base (
    fmt=0xb67fca78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0xb6d922f0 "(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (15)) == 0 && \"this assertion is explained here: \" \"http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.htm"..., 
    assertion@entry=0x0, 
    file=0xb6d922bc "/usr/include/eigen3/Eigen/src/Core/DenseStorage.h", 
    file@entry=0xade7bef0 "\001", line=109, line@entry=3067683516, 
    function=function@entry=0xb6d92a30 <Eigen::internal::plain_array<float, 4, 0, 16>::plain_array()::__PRETTY_FUNCTION__> "Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 4; int MatrixOrArrayOptions = 0]") at assert.c:92
#5  0xb6746daa in __GI___assert_fail (assertion=0x0, file=0xade7bef0 "\001", 
    line=3067683516, 
    function=0xb6d92a30 <Eigen::internal::plain_array<float, 4, 0, 16>::plain_array()::__PRETTY_FUNCTION__> "Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 4; int MatrixOrArrayOptions = 0]") at assert.c:101
---Type <return> to continue, or q <return> to quit---
#6  0xb6cc796c in Eigen::internal::plain_array<float, 4, 0, 16>::plain_array (
    this=0x479858) at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:109
#7  0xb6cc605e in Eigen::DenseStorage<float, 4, 4, 1, 0>::DenseStorage (
    this=0x479858) at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:187
#8  0xb6cc3eca in Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1, 0, 4, 1> >::PlainObjectBase (this=0x479858)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:484
#9  0xb6cd135a in Eigen::Matrix<float, 4, 1, 0, 4, 1>::Matrix<Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, 4, 1, 0, 4, 1> > > (this=0x479858, x=...)
    at /usr/include/eigen3/Eigen/src/Core/Matrix.h:294
#10 0xb6cd224c in pcl::PointCloud<pcl::PointXYZI>::PointCloud (this=0x479808)
    at /usr/include/pcl-1.8/pcl/point_cloud.h:182
#11 0xb6ce2404 in std::_Construct<pcl::PointCloud<pcl::PointXYZI>>(pcl::PointCloud<pcl::PointXYZI>*) (__p=0x479808)
    at /usr/include/c++/7/bits/stl_construct.h:75
#12 0xb6ce1918 in std::__uninitialized_default_n_1<false>::__uninit_default_n<pcl::PointCloud<pcl::PointXYZI>*, unsigned int> (__first=0x479808, __n=16)
    at /usr/include/c++/7/bits/stl_uninitialized.h:527
#13 0xb6ce0d8a in std::__uninitialized_default_n<pcl::PointCloud<pcl::PointXYZI>*, unsigned int> (__first=0x479808, __n=16)
    at /usr/include/c++/7/bits/stl_uninitialized.h:583
#14 0xb6cdff8c in std::__uninitialized_default_n_a<pcl::PointCloud<pcl::PointXYZ---Type <return> to continue, or q <return> to quit---
I>*, unsigned int, pcl::PointCloud<pcl::PointXYZI> > (__first=0x479808, __n=16)
    at /usr/include/c++/7/bits/stl_uninitialized.h:645
#15 0xb6cdf21c in std::vector<pcl::PointCloud<pcl::PointXYZI>, std::allocator<pcl::PointCloud<pcl::PointXYZI> > >::_M_default_append (this=0xbeffe768, __n=16)
    at /usr/include/c++/7/bits/vector.tcc:575
#16 0xb6cde850 in std::vector<pcl::PointCloud<pcl::PointXYZI>, std::allocator<pcl::PointCloud<pcl::PointXYZI> > >::resize (this=0xbeffe768, __new_size=16)
    at /usr/include/c++/7/bits/stl_vector.h:692
#17 0xb6cdceea in loam::MultiScanRegistration::process (this=0xbeffe750, 
    laserCloudIn=..., scanTime=...)
    at /home/odroid/XTScan/src/loam/src/lib/MultiScanRegistration.cpp:177
#18 0xb6cdcba8 in loam::MultiScanRegistration::handleCloudMessage (
    this=0xbeffe750, laserCloudMsg=...)
    at /home/odroid/XTScan/src/loam/src/lib/MultiScanRegistration.cpp:154
#19 0xb6ce340a in boost::_mfi::mf1<void, loam::MultiScanRegistration, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::operator() (this=0x46be6c, p=0xbeffe750, a1=...)
    at /usr/include/boost/bind/mem_fn_template.hpp:165
#20 0xb6ce25fa in boost::_bi::list2<boost::_bi::value<loam::MultiScanRegistration*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, loam::MultiScanRegistration, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::rrlist1<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&> > (this=0x46be74, f=..., a=...)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/boost/bind/bind.hpp:319
#21 0xb6ce1b26 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, loam::MultiScanRegistration, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<loam::MultiScanRegistration*>, boost::arg<1> > >::operator()<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&> (this=0x46be6c, a1=...)
    at /usr/include/boost/bind/bind.hpp:1306
#22 0xb6ce10e8 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, loam::MultiScanRegistration, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<loam::MultiScanRegistration*>, boost::arg<1> > >, void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::invoke (function_obj_ptr=..., a0=...)
    at /usr/include/boost/function/function_template.hpp:159
#23 0xb6ce36c8 in boost::function1<void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&>::operator() (this=0x46be68, a0=...)
    at /usr/include/boost/function/function_template.hpp:759
#24 0xb6ce2844 in boost::detail::function::void_function_obj_invoker1<boost::function<void (boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&)>, void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const>) (
    function_obj_ptr=..., a0=...)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/boost/function/function_template.hpp:159
#25 0xb6ce6602 in boost::function1<void, boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> >::operator() (this=0x473658, a0=...)
    at /usr/include/boost/function/function_template.hpp:759
#26 0xb6ce6118 in ros::SubscriptionCallbackHelperT<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > const> const&, void>::call (
    this=0x473654, params=...)
    at /opt/ros/melodic/include/ros/subscription_callback_helper.h:144
#27 0xb6f96552 in ros::SubscriptionQueue::call() ()
   from /opt/ros/melodic/lib/libroscpp.so
#28 0xb6f5d296 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) ()
   from /opt/ros/melodic/lib/libroscpp.so
#29 0xb6f5dca2 in ros::CallbackQueue::callAvailable(ros::WallDuration) ()
   from /opt/ros/melodic/lib/libroscpp.so
#30 0xb6f9912e in ros::SingleThreadedSpinner::spin(ros::CallbackQueue*) ()
   from /opt/ros/melodic/lib/libroscpp.so
#31 0xb6f89e48 in ros::spin() () from /opt/ros/melodic/lib/libroscpp.so
#32 0x0040b962 in main (argc=1, argv=0xbeffeea4)
    at /home/odroid/XTScan/src/loam/src/multi_scan_registration_node.cpp:16

## Expected Behavior

the fault mostly happened for this code
https://github.com/GaoGeolone/loam_velodyne/blob/ef1b9b7287438de9284c68ab39a172cff1eff1ff/src/lib/MultiScanRegistration.cpp#L176
## Current Behavior

Actually, I have already deleted macro todo with the compile choice  " -march=native"

**Comment by kunaltyagi** [comment]
> deleted macro todo with the compile choice " -march=native"

What do you mean by this?
