### ISSUE TITLE
Where is the openni_stream_compression.cpp file?

### ISSUE THREAD

**Issue by cucrui** [PointCloudLibrary/pcl#2937]
I read the document aboud point cloud compression, and in the document, the author mentioned that i can use command line to run ./openni_stream_compression, but i cant find that file.
anyone meet the same problem?

**Comment by Chibbluffy** [comment]
You have to run cmake and then make to create the executable.

**Comment by SergioRAgostinho** [comment]
Hmm. Usually our executables start with the prefix `pcl_`. Can you provide the url to this document/tutorial to help identify which app/tool is it?

**Comment by cucrui** [comment]
> Hmm. Usually our executables start with the prefix `pcl_`. Can you provide the url to this document/tutorial to help identify which app/tool is it?

[http://pointclouds.org/documentation/tutorials/compression.php](url)

**Comment by SergioRAgostinho** [comment]
Given the headers that are included, it's very likely that it is referring to `pcl_openni_octree_compression`.

https://github.com/PointCloudLibrary/pcl/blob/c20130b148faaff6c5944ad590ccd95ae2a32e21/apps/CMakeLists.txt#L96-L97

The usage info looks very similar
https://github.com/PointCloudLibrary/pcl/blob/c20130b148faaff6c5944ad590ccd95ae2a32e21/apps/src/openni_octree_compression.cpp#L64-L104

If the that executable is not on your installed binaries, it means you need to compile PCL with OpenNI support. From our side, it also means the tutorial needs to be updated.

**Comment by cucrui** [comment]
> Given the headers that are included, it's very likely that it is referring to `pcl_openni_octree_compression`.
> 
> [pcl/apps/CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/blob/c20130b148faaff6c5944ad590ccd95ae2a32e21/apps/CMakeLists.txt#L96-L97)
> 
> Lines 96 to 97 in [c20130b](/PointCloudLibrary/pcl/commit/c20130b148faaff6c5944ad590ccd95ae2a32e21)
> 
>  PCL_ADD_EXECUTABLE_OPT_BUNDLE(pcl_openni_octree_compression "${SUBSYS_NAME}" src/openni_octree_compression.cpp) 
>  target_link_libraries(pcl_openni_octree_compression pcl_common pcl_io pcl_filters pcl_visualization pcl_octree) 
> The usage info looks very similar
> [pcl/apps/src/openni_octree_compression.cpp](https://github.com/PointCloudLibrary/pcl/blob/c20130b148faaff6c5944ad590ccd95ae2a32e21/apps/src/openni_octree_compression.cpp#L64-L104)
> 
> Lines 64 to 104 in [c20130b](/PointCloudLibrary/pcl/commit/c20130b148faaff6c5944ad590ccd95ae2a32e21)
> 
>  char usage[] = "\n" 
>    "  PCL octree point cloud compression\n" 
>    "\n" 
>    "  usage: ./pcl_openni_octree_compression [mode] [profile] [parameters]\n" 
>    "\n" 
>    "  I/O: \n" 
>    "      -f file  : file name \n" 
>    "\n" 
>    "  file compression mode:\n" 
>    "      -x: encode point cloud stream to file\n" 
>    "      -d: decode from file and display point cloud stream\n" 
>    "\n" 
>    "  network streaming mode:\n" 
>    "      -s       : start server on localhost\n" 
>    "      -c host  : connect to server and display decoded cloud stream\n" 
>    "\n" 
>    "  optional compression profile: \n" 
>    "      -p profile : select compression profile:       \n" 
>    "                     -\"lowC\"  Low resolution with color\n" 
>    "                     -\"lowNC\" Low resolution without color\n" 
>    "                     -\"medC\" Medium resolution with color\n" 
>    "                     -\"medNC\" Medium resolution without color\n" 
>    "                     -\"highC\" High resolution with color\n" 
>    "                     -\"highNC\" High resolution without color\n" 
>    "\n" 
>    "  optional compression parameters:\n" 
>    "      -r prec  : point precision Hz\n" 
>    "      -o prec  : octree voxel size\n" 
>    "      -v       : enable voxel-grid downsampling\n" 
>    "      -a       : enable color coding\n" 
>    "      -i rate  : i-frame rate\n" 
>    "      -b bits  : bits/color component\n" 
>    "      -t       : output statistics\n" 
>    "      -e       : show input cloud during encoding\n" 
>    "\n" 
>    "      -minmax min-max  :: set the PassThrough min-max cutting values (default: 0-3.0)\n" 
>    "      -field  X        :: set the PassThrough field/dimension 'X' to filter data on (default: 'z')\n" 
>    "\n" 
>    "  example:\n" 
>    "      ./pcl_openni_octree_compression -x -p highC -t -f pc_compressed.pcc \n" 
>    "\n"; 
> If the that executable is not on your installed binaries, it means you need to compile PCL with OpenNI support. From our side, it also means the tutorial needs to be updated.

Thanks for your reply, I try to cmake .. and it comes out
```
unknow cmake command "PCL_SUBSYS_OPTION"
``` 
what should I do~
