### ISSUE TITLE
Is there any fast method to get the cluster of max size after segmentation?

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#2941]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler: gcc5.4.0
* PCL Version:1.9.1

## Question

Hi, Is there any fast method to get the cluster of max size after segmentation? I just know there is a way to get the max size of clusters.

**Comment by kunaltyagi** [comment]
That's the default behavior. If you intend to ask the maximum size before even performing the segmentation, then no. It's not possible (though theoretically, it's the size of the input cloud)
