### ISSUE TITLE
About KLD particle filter implementation 

### ISSUE THREAD

**Issue by Guptajakala** [PointCloudLibrary/pcl#2944]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc-5.5
* PCL Version: master branch

## Context
(https://github.com/PointCloudLibrary/pcl/blob/f029ba96f43f7bcaf35efd6e8e8bda03fd300fbc/tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter.hpp#L81). The "bins" seems to be processed but never used later. Is this implementation not done yet?

**Comment by mvieth** [comment]
Sorry that you did not get an earlier answer. The implementation is done. `bins` is a temporary storage that is used to look up whether a bin is empty or not (which is done by `insertIntoBins`), or more precisely, whether a new sample falls into an empty bin. But after all particles are selected, it is not important to know which bins are non-empty. You might also want to have a look at the paper (https://proceedings.neurips.cc/paper/2001/file/c5b2cebf15b205503560c4e8e6d1ea78-Paper.pdf), especially table 1.
