### ISSUE TITLE
pcl::GASDSignature512 doesn't work

### ISSUE THREAD

**Issue by liemwellys** [PointCloudLibrary/pcl#2945]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: default gcc / g++ Ubuntu
* PCL Version: 1.7.2

## Context

I'm going to extract object feature by using GASD.  The GASD is not available when I download stable PCL release by using "sudo apt-get install libpcl-dev", so I manually copy the "gasd.h" and "gasd.hpp" to the pcl library directory on my computer.

I successfully copy the "gasd.h" and "gasd.hpp" and put each of them on the right directory into my own computer, but when I type pcl::GASDSignature512, it was not listed and compile error (I provide the screenshot bellow)

## Expected Behavior

it should be possible to do GASD estmation like the tutorial on this link:
http://pointclouds.org/documentation/tutorials/gasd_estimation.php

## Current Behavior

![image](https://user-images.githubusercontent.com/11076479/54876901-a4c26980-4e52-11e9-84fe-f54471c383e0.png)
The "GASDSignature512" was marked by red color on CLion IDE because it can't be implemented.

**Comment by kunaltyagi** [comment]
`pcl::GASDEstimation<pcl::PointXYZ, pcl::GASDSignature984> gasd;` is the correct usage.
