### ISSUE TITLE
Normal Estimation crashes in Release Mode

### ISSUE THREAD

**Issue by medakk** [PointCloudLibrary/pcl#2953]
* Operating System and version: Windows 10
* Compiler: Visual Studio 2017
* PCL Version: 1.9.0 All-in-one installer

I'm trying to run some normal estimation code:

```
#include <iostream>
#include <fstream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/point_representation.h>
#include <pcl/features/normal_3d.h>

int main() {
	pcl::PointCloud<pcl::PointXYZI>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZI>);
	if (pcl::io::loadPCDFile("cloud.pcd", *cloud) == -1) {
		std::cerr << "Failed to load "<< std::endl;
		return -1;
	}

	pcl::NormalEstimation<pcl::PointXYZI, pcl::Normal> ne;
	ne.setInputCloud(cloud);

	pcl::search::KdTree<pcl::PointXYZI>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZI>());
	ne.setSearchMethod(tree);

	// Output datasets
	cloud_normals = pcl::PointCloud<pcl::Normal>::Ptr(new pcl::PointCloud<pcl::Normal>);

	// Use all neighbors in a sphere of radius 3cm
	ne.setRadiusSearch(0.03);

	// Compute the features
	ne.compute(*cloud_normals);
}
```

This works fine in debug mode. But in release mode, I get the message:

```
[initCompute] Failed to allocate 2242154625 indices.
```

I found this [issue](https://stackoverflow.com/questions/42801795/pcl-release-build-crashes-with-failed-to-allocate), but I'd prefer to fix it using the All-in-one installer.

**Comment by SergioRAgostinho** [comment]
This should not work fine in debug mode. You have too many points in your point cloud and your system is complaining because of it. Even if you managed to allocate them, PCL (unfortunately) is using `int`s has indexes and you're above 2^31. The results would be unreliable.

For now, I can only suggest the quick work around of downsampling your point cloud.

**Comment by medakk** [comment]
I think that is unlikely. My point cloud has ~120000 points.

**Comment by SergioRAgostinho** [comment]
That is weird... the error message seems to suggest that it has 2242154625 points. 

I'm assuming the message is coming from here, line 156
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/common/include/pcl/impl/pcl_base.hpp#L138-L170

**Comment by medakk** [comment]
> That is weird... the error message seems to suggest that it has 2242154625 points.

Sorry, I should have mentioned earlier: the number it shows changes on every run.

**Comment by medakk** [comment]
Also, in my actual code, my point cloud data is not coming from a PCD file(but I have confirmed that it has correctly loaded, by loading it into my visualization tool). I'd had used the `loadPCDFile` method to illustrate a minimal example for this issue. I've since discovered that the `loadPCDFile` also fails in release mode. I've showed this in this [issue](https://github.com/PointCloudLibrary/pcl/issues/3040).

**Comment by larshg** [comment]
Is this still an issue?

**Comment by medakk** [comment]
@larshg I've moved on that project, last I checked(around a year back) it was still an issue. I don't have access to the computer now to test it with newer PCL builds.

**Comment by larshg** [comment]
Okay, lets close this as well and please reopen a new one, if its still an issue in 1.10.1/master.
