### ISSUE TITLE
Cannot read .ply file properly.

### ISSUE THREAD

**Issue by msiraj83** [PointCloudLibrary/pcl#2958]
OS: Ubuntu 16.04 LTS
Compile: Linux,
PCL : pcl1.8

I try to read .ply file with the following information
`ply
format ascii 1.0
comment Created by Blender 2.76 (sub 0) - www.blender.org, source file: 'kevin_s.blend'
element vertex 73098
property float x
property float y
property float z
property float normal_x
property float normal_y
property float normal_z
property uchar red
property uchar greeb
property uchar blue
element face 24366
property list uchar uint vertex_indices
end_header
0.728624 -0.026104 -0.382993 0.812073 -0.520899 -0.263064 103 58 40
0.720970 -0.020042 -0.418624 0.812073 -0.520899 -0.263064 97 53 36
0.737289 0.004189 -0.416229 0.812073 -0.520899 -0.263064 100 57 41
0.728624 -0.026104 -0.382993 0.809565 -0.523336 -0.265939 103 58 40
0.737289 0.004189 -0.416229 0.809565 -0.523336 -0.265939 100 57 41
0.753462 0.010683 -0.379774 0.809565 -0.523336 -0.265939 106 62 45
0.700579 -0.043010 -0.416904 0.711466 -0.651385 -0.263654 95 49 31
0.720970 -0.020042 -0.418624 0.711466 -0.651385 -0.263654 97 53 36
0.728624 -0.026104 -0.382993 0.711466 -0.651385 -0.263654 103 58 40
0.700579 -0.043010 -0.416904 0.728908 -0.617903 -0.294770 95 49 31
0.728624 -0.026104 -0.382993 0.728908 -0.617903 -0.294770 103 58 40
0.697155 -0.066045 -0.377087 0.728908 -0.617903 -0.294770 99 53 33
0.754834 -0.003186 -0.328979 0.878306 -0.454661 -0.147856 115 71 54

I got two problem ...
First :-
`1;33m[pcl::PLYReader] kevin_s_new.ply:15: property 'list uint8 int32 vertex_index' of element 'face' is not handled �[0;m�[1;33mFailed to find match for field 'curvature'.
`
Second: -

When i check the values.. than vertex and normal is ok but got some strange values for RGB as shown below..

(0.728624,-0.026104,-0.382993 - 9.45911e-39 - 0.812073,-0.520899,-0.263064 - 103, 0, 40 - 0)
(0.72097,-0.020042,-0.418624 - 8.90809e-39 - 0.812073,-0.520899,-0.263064 - 97, 0, 36 - 0)
(0.737289,0.004189,-0.416229 - 9.18361e-39 - 0.812073,-0.520899,-0.263064 - 100, 0, 41 - 0)
(0.728624,-0.026104,-0.382993 - 9.45911e-39 - 0.809565,-0.523336,-0.265939 - 103, 0, 40 - 0)

Following is my code ..

`pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZRGBNormal>);
 pcl::PLYReader Reader; Reader.read("kevin_s_new.ply", *cloud); 
for(unsigned int i=0; i< cloud->points.size(); i++) 
{
std::cout<<cloud->points[i]<<std::endl; 
}
`
Can any body help me what is the error and how to fix it..
Thanks.

**Comment by msiraj83** [comment]
OS: Ubuntu 16.04 LTS
Compile: Linux,
PCL : pcl1.8

I try to read .ply file with the following information
`ply
format ascii 1.0
comment Created by Blender 2.76 (sub 0) - www.blender.org, source file: 'kevin_s.blend'
element vertex 73098
property float x
property float y
property float z
property float normal_x
property float normal_y
property float normal_z
property uchar red
property uchar greeb
property uchar blue
element face 24366
property list uchar uint vertex_indices
end_header
0.728624 -0.026104 -0.382993 0.812073 -0.520899 -0.263064 103 58 40
0.720970 -0.020042 -0.418624 0.812073 -0.520899 -0.263064 97 53 36
0.737289 0.004189 -0.416229 0.812073 -0.520899 -0.263064 100 57 41
0.728624 -0.026104 -0.382993 0.809565 -0.523336 -0.265939 103 58 40
0.737289 0.004189 -0.416229 0.809565 -0.523336 -0.265939 100 57 41
0.753462 0.010683 -0.379774 0.809565 -0.523336 -0.265939 106 62 45
0.700579 -0.043010 -0.416904 0.711466 -0.651385 -0.263654 95 49 31
0.720970 -0.020042 -0.418624 0.711466 -0.651385 -0.263654 97 53 36
0.728624 -0.026104 -0.382993 0.711466 -0.651385 -0.263654 103 58 40
0.700579 -0.043010 -0.416904 0.728908 -0.617903 -0.294770 95 49 31
0.728624 -0.026104 -0.382993 0.728908 -0.617903 -0.294770 103 58 40
0.697155 -0.066045 -0.377087 0.728908 -0.617903 -0.294770 99 53 33
0.754834 -0.003186 -0.328979 0.878306 -0.454661 -0.147856 115 71 54

I got two problem ...
First :- 
`1;33m[pcl::PLYReader] kevin_s_new.ply:15: property 'list uint8 int32 vertex_index' of element 'face' is not handled
[0;m[1;33mFailed to find match for field 'curvature'.`

Second: - 

When i check the values.. than vertex and normal is ok but got some strange values for RGB  as shown below..

(0.728624,-0.026104,-0.382993 - 9.45911e-39 - 0.812073,-0.520899,-0.263064 - 103, 0, 40 - 0)
(0.72097,-0.020042,-0.418624 - 8.90809e-39 - 0.812073,-0.520899,-0.263064 - 97, 0, 36 - 0)
(0.737289,0.004189,-0.416229 - 9.18361e-39 - 0.812073,-0.520899,-0.263064 - 100, 0, 41 - 0)
(0.728624,-0.026104,-0.382993 - 9.45911e-39 - 0.809565,-0.523336,-0.265939 - 103, 0, 40 - 0)

Following is my code ..

` pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr cloud (new 
   pcl::PointCloud<pcl::PointXYZRGBNormal>); 
   pcl::PLYReader Reader;
   Reader.read("kevin_s_new.ply", *cloud);
    for(unsigned int i=0; i< cloud->points.size(); i++)
    {
    	std::cout<<cloud->points[i]<<std::endl;
    }`

Can any body help me what is the error and how to fix it..
Thanks.

**Comment by SergioRAgostinho** [comment]
Can you try this on 1.9.1 or on master? We patched a number of things with respect to PLY loading.

**Comment by taketwo** [comment]
Closing due to lack of feedback. Please re-open if needed.
