### ISSUE TITLE
Getters in SampleConsensus should have const qualifiers

### ISSUE THREAD

**Issue by PPokorski** [PointCloudLibrary/pcl#2959]
## Your Environment
* PCL Version: master branch

## Context
Some methods in [SampleConsensus](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/sac.h) class.
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/sac.h#L142-L143

https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/sac.h#L152-L153

https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/sac.h#L163-L164
## Expected Behavior
Those methods should be marked as `const`.

## Current Behavior
`const` qualifier is not present.

## Code to Reproduce
I think examples above are enough :)

## Possible Solution
Add `const` qualifier.

**Comment by SergioRAgostinho** [comment]
Agreed. Feel free to open a PR with the changes.

**Comment by PPokorski** [comment]
Thank you. One more thing from [MaximumLikelihoodSampleConsensus](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/mlesac.h): there are some methods like those:
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/mlesac.h#L124-L127
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/mlesac.h#L135-L139
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/sample_consensus/include/pcl/sample_consensus/mlesac.h#L146-L149
which, I think, could also be `const`. What do you think?

**Comment by taketwo** [comment]
Sure, these are good candidates to be marked `const` as well.
