### ISSUE TITLE
/home/s/Documents/pcl_test/pcl_test.cpp:4:46: fatal error: pcl/visualization/pcl_visualizer.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by suyunzzz** [PointCloudLibrary/pcl#2960]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler:
* PCL Version:1.8

## Current Behavior
/home/s/Documents/pcl_test/pcl_test.cpp:4:46: fatal error: pcl/visualization/pcl_visualizer.h: no such file or directory

**Comment by suyunzzz** [comment]
i am sorry for my wrong using github...
but i don't have another solution.
thanks!

**Comment by SergioRAgostinho** [comment]
The first candidate is a problem with your cmake file. Are you specifying the include directories?

**Comment by suyunzzz** [comment]
@SergioRAgostinho  thanks. yesterday，i try again and succeeded,thank your help very much! god bless u!
