### ISSUE TITLE
Compiling error when use voxel in customized point type

### ISSUE THREAD

**Issue by nenger2** [PointCloudLibrary/pcl#2961]
I defined a customized point type:

#define PCL_NO_PRECOMPILE

#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/filters/voxel_grid.h>

namespace hvo
{
    struct PointXYZRGBLCov
    {
      PCL_ADD_POINT4D;                  // This adds the members x,y,z which can also be accessed using the point (which is float[4])
      PCL_ADD_RGB;
      unsigned char label;
      float cov[3];
      friend std::ostream& operator << (std::ostream& os, const PointXYZRGBLCov& p);
      EIGEN_MAKE_ALIGNED_OPERATOR_NEW   // make sure our new allocators are aligned
    } EIGEN_ALIGN16;                    // enforce SSE padding for correct memory alignment

    PCL_EXPORTS std::ostream&
    operator << (std::ostream& os, const PointXYZRGBLCov& p);
}

POINT_CLOUD_REGISTER_POINT_STRUCT (hvo::PointXYZRGBLCov,
                                   (float, x, x)
                                   (float, y, y)
                                   (float, z, z)
                                   (unsigned char, r, r)
                                   (unsigned char, g, g)
                                   (unsigned char, b, b)
                                   (unsigned char, label, label)
                                   (float[3], cov, cov)
)

but when I used a voxel on the point type:

	pcl::VoxelGrid<hvo::PointXYZRGBLCov> cloud_voxel_;
I get some compile error:
/usr/include/pcl-1.7/pcl/point_cloud.h: In instantiation of ‘void pcl::NdCopyPointEigenFunctor<PointInT>::operator()() [with Key = pcl::fields::weights; PointInT = hvo::LabelGMMPointType]’:
/usr/include/pcl-1.7/pcl/for_each_type.h:87:51:   recursively required from ‘static void pcl::for_each_type_impl<false>::execute(F) [with Iterator = boost::mpl::v_iter<boost::mpl::vector<pcl::fields::x, pcl::fields::y, pcl::fields::z, pcl::fields::label, pcl::fields::weights, pcl::fields::means, pcl::fields::covs>, 1l>; LastIterator = boost::mpl::v_iter<boost::mpl::vector<pcl::fields::x, pcl::fields::y, pcl::fields::z, pcl::fields::label, pcl::fields::weights, pcl::fields::means, pcl::fields::covs>, 7l>; F = pcl::NdCopyPointEigenFunctor<hvo::LabelGMMPointType>]’
/usr/include/pcl-1.7/pcl/for_each_type.h:87:51:   required from ‘static void pcl::for_each_type_impl<false>::execute(F) [with Iterator = boost::mpl::v_iter<boost::mpl::vector<pcl::fields::x, pcl::fields::y, pcl::fields::z, pcl::fields::label, pcl::fields::weights, pcl::fields::means, pcl::fields::covs>, 0l>; LastIterator = boost::mpl::v_iter<boost::mpl::vector<pcl::fields::x, pcl::fields::y, pcl::fields::z, pcl::fields::label, pcl::fields::weights, pcl::fields::means, pcl::fields::covs>, 7l>; F = pcl::NdCopyPointEigenFunctor<hvo::LabelGMMPointType>]’
/usr/include/pcl-1.7/pcl/for_each_type.h:98:94:   required from ‘void pcl::for_each_type(F) [with Sequence = boost::mpl::vector<pcl::fields::x, pcl::fields::y, pcl::fields::z, pcl::fields::label, pcl::fields::weights, pcl::fields::means, pcl::fields::covs>; F = pcl::NdCopyPointEigenFunctor<hvo::LabelGMMPointType>]’
/usr/include/pcl-1.7/pcl/filters/impl/voxel_grid.hpp:436:38:   required from ‘void pcl::VoxelGrid<PointT>::applyFilter(pcl::VoxelGrid<PointT>::PointCloud&) [with PointT = hvo::LabelGMMPointType; pcl::VoxelGrid<PointT>::PointCloud = pcl::PointCloud<hvo::LabelGMMPointType>]’
/home/nenger/ros/workspace/src/localization_gitlab/lidar_loc/loc/src/lib/core/loc/laser_loc_2d.cpp:410:1:   required from here
**/usr/include/pcl-1.7/pcl/point_cloud.h:121:21: error: invalid static_cast from type ‘T {aka const float [2]}’ to type ‘float’
       p2_[f_idx_++] = static_cast<float> (*reinterpret_cast<const T*>(data_ptr));**

PCL_INSTANTIATE(pcl::VoxelGrid, hvo::PointXYZRGBLCov);

I found that when I remove the float array "float cov[3]" from my point type, everything is fine.
what would be the problem in my code??
Thanks!!

**Comment by taketwo** [comment]
`VoxelGrid` computes centroid of points inside each voxel. Centroid computation happens separately for each field in the point. In order this to work, addition and division operations should be defined for the field types. This is not the case for `float[3]` type, compiler does not know how to add fields of this type.

Unfortunately I can not recommend an easy solution for your problem. If you do not need to compute point centroids, you may try to use uniform sampling filter.

**Comment by nenger2** [comment]
> `VoxelGrid` computes centroid of points inside each voxel. Centroid computation happens separately for each field in the point. In order this to work, addition and division operations should be defined for the field types. This is not the case for `float[3]` type, compiler does not know how to add fields of this type.
> 
> Unfortunately I can not recommend an easy solution for your problem. If you do not need to compute point centroids, you may try to use uniform sampling filter.

Thanks, your reply let me get the reason why this happen.
Here I get a solution: use union to define the float[], and my new struct define is as follows:


    struct PointXYZRGBLCov
    {
      PCL_ADD_POINT4D;                  // This adds the members x,y,z which can also be accessed using the point (which is float[4])
      PCL_ADD_RGB;
      unsigned char label;

        union
        {
            float cov[3];
            struct
            {
                float cov_1;
                float cov_2;
                float cov_3;
            };
        };

      EIGEN_MAKE_ALIGNED_OPERATOR_NEW   // make sure our new allocators are aligned
    } EIGEN_ALIGN16;                    // enforce SSE padding for correct memory alignment


POINT_CLOUD_REGISTER_POINT_STRUCT (hvo::PointXYZRGBLCov,
                                   (float, x, x)
                                   (float, y, y)
                                   (float, z, z)
                                   (unsigned char, r, r)
                                   (unsigned char, g, g)
                                   (unsigned char, b, b)
                                   (unsigned char, label, label)
                                   (float, cov_1, cov_1)
                                   (float, cov_2, cov_2)
                                   (float, cov_3, cov_3)
)

**Comment by taketwo** [comment]
Good idea :+1:
