### ISSUE TITLE
Copying pcl::IterativeClosestPoint object causes issues

### ISSUE THREAD

**Issue by PPokorski** [PointCloudLibrary/pcl#2965]
## Your Environment
* Operating System and version: Ubuntu 16.04.6 LTS
* Compiler: GCC 7.4.0
* PCL Version: 1.9.1 (commit d009887)

## Context
I stumbled upon this issue when I created a class with [pcl::IterativeClosestPoint](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/icp.h) as a member, and then made a std::vector of that class. Then it happened, for no reason, that the code hang at this method:
https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/registration.h#L408-L409

## Current Behavior
Currently copying (or reallocating) object of type [pcl::IterativeClosestPoint](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/icp.h) causes it to copy all of its fields, including (by default) pointer to [pcl::DefaultConvergenceCriteria](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/default_convergence_criteria.h). This object, in turns, holds const references to
* https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/registration.h#L490
* https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/registration.h#L507
* https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/registration.h#L548
which it uses to decide whether the algorithm has converged. So, if object [pcl::IterativeClosestPoint](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/icp.h) is reallocated (e.g. via [std::vector::resize](https://en.cppreference.com/w/cpp/container/vector/resize)) or copied, then those const references are invalid. This may lead to, e.g.:
* Algorithm getting stuck in a loop (as https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/default_convergence_criteria.h#L228) not longer points to a valid int)
* Algorithm immediately thinking that it converged (as https://github.com/PointCloudLibrary/pcl/blob/d00988784efd7efa8f006f1afa1c503636ca3104/registration/include/pcl/registration/default_convergence_criteria.h#L231 may point to a 0-initialized variable of other object)
This all was quite... painful to debug. I admit, that this maybe a bloated use-case, but nevertheless this happened without any warning.

## Expected Behavior
Accidental copy or reallocation of [pcl::IterativeClosestPoint](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/icp.h) should be either impossible or safe. Or at-least come with some kind of warning.

## Code to Reproduce
https://pastebin.com/fgZs6h8b

## Possible Solution
I'm not sure about this one. First shot would be at implementing copy-, move- -constructors, -assignment-operators for [pcl::IterativeClosestPoint](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/icp.h). The problem is that this problem occurs only for [pcl::DefaultConvergenceCriteria](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/default_convergence_criteria.h). But even some kind of PCL_WARN or entry in documentation would be nice.

Thanks for response.

**Comment by taketwo** [comment]
Thanks for the report. There are some questionable design decisions in the ICP implementation, especially the `pcl::DefaultConvergenceCriteria` class (e.g. see #1598 about another issue related to it).

Based on your personal goals and/or time constraints, I'd propose to do the following:
 * if you don't care about your original use-case, then we can think about `delete`ing certain constructors to make sure that code simply does not compile;
 * if you want to use ICP in a vector and have time, then let's discuss and implement a set of constructors that take care of the problematic member variables.

Your call.
