### ISSUE TITLE
#error PCL requires C++14 or above

### ISSUE THREAD

**Issue by RahulKumarBazia** [PointCloudLibrary/pcl#2968]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: g++ (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

* PCL Version:

## Context
While running catkin_make command, its throwing up the following error 
In file included from /usr/local/include/pcl-1.9/pcl/console/print.h:44:0,
                 from /usr/local/include/pcl-1.9/pcl/conversions.h:53,
                 from /opt/ros/kinetic/include/pcl_ros/point_cloud.h:8,
                 from /home/fluxdrive/catkin_ws/src/ti_mmwave_rospkg/src/DataHandlerClass.cpp:51:
/usr/local/include/pcl-1.9/pcl/pcl_config.h:7:4: error: #error PCL requires C++14 or above
   #error PCL requires C++14 or above

I tried by re-installing the g++ but it didn't work for me

**Comment by taketwo** [comment]
Please post your solution for future reference.

**Comment by anujgpatil** [comment]
Found anything?

**Comment by kunaltyagi** [comment]
2 options: 
- update gcc 
- supply additional flag to compile (-std=c++14) to cmake

Upgrading gcc on Ubuntu is possible by 
- adding repository ppa:ubuntu-toolchain-r/test 
- updating apt 
- installing required version of gcc 

Choose one with default version as c++14.

**Comment by anujgpatil** [comment]
Adding the addition flag alone didn't help.
I had to upgrade both GCC and G++, then restart compilation. I  installed gcc-9 
(after upgrading, added `set(CMAKE_C_COMPILER "/usr/bin/gcc-9")` and `set(CMAKE_CXX_COMPILER "/usr/bin/g++-9")` to the CMakelIsts.txt)

However for CUDA based targets, NVCC error says *GCC versions later than 6 are not supported*

I have 2 options:

1. Upgrade to latest NVCC (CUDA Toolkit)
2. Downgrade GCC,G++ to v6, then restart compilation?

Since `JetPack is the only official download method for the CUDA/NVCC version going on the Jetson.` , I will downgrade GCC to 6.x and update the results here.

**Comment by Vivekk9** [comment]
@anujgpatil Any updates so far, after downgrading GCC back to 6.x? I tried to update GCC 9.3 to 10.2 and used additional flag (std=c++14) as the default option which didn't worked.

**Comment by kunaltyagi** [comment]
Please note that Ubuntu 16.04 is EOL and is not supported by PCL anymore

**Comment by mohamedsayed18** [comment]
Ubuntu: 20.04
`gcc --version`: gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
/usr/include/pcl-1.10/pcl/pcl_config.h:7:4: error: #error PCL requires C++14 or above

**Comment by RahulKumarBazia** [comment]
apologies for the late reply. Simply open the CMakeLists.txt at /catkin_ws/src/ti_mmwave_rospkg
change the line  add_definitions(-std=c++11) to  add_definitions(-std=c++14)

**Comment by remmel** [comment]
in CMakeList.txt add `set(CMAKE_CXX_STANDARD 14)`

**Comment by daureliano** [comment]
Thanks you  powerfully!  The suggestion that you put indeed help me.

**Comment by arjunskumar** [comment]
Thanks it worked

**Comment by ram-bhaskara** [comment]
In my case, adding did not help as there was another command setting CXX to 11 prior. I just had to change 11 to 14. 
But first I had openCV errors. I had to edit my include file: 
Replaced #include <opencv/cv.h> with #include <opencv2/core/core.hpp>
