### ISSUE TITLE
No Dockerfile for pointcloudlibrary/env

### ISSUE THREAD

**Issue by borgmanJeremy** [PointCloudLibrary/pcl#2973]
I would like to understand all of the dependencies and versions used to build PCL in the Azure pipeline. I can see the environment is set up using pointcloudlibrary/env container. I can pull the container from dockerhub, but I am not able to find its Dockerfile.

This would be useful to publish so users can see exactly which versions of libraries are used (and in my case test the build against different boost releases). This also helps understand how to port PCL to different version of linux and ARM.

**Comment by taketwo** [comment]
Hi, thanks for bringing this up. In fact, somewhere on my TODO list is a task to include the Dockerfile into the repository and to create an Azure pipeline that rebuilds the image when the file is changed.

For now, here is the Dockerfile that I used to generate the current `env` image:

```
FROM ubuntu:16.04
MAINTAINER Sergey Alexandrov <alexandrov88@gmail.com>

RUN apt-get update && apt-get install -y \
      cmake \
      g++ \
      libboost-chrono-dev \
      libboost-filesystem-dev \
      libboost-iostreams-dev \
      libboost-thread-dev \
      libeigen3-dev \
      libflann-dev \
      libglew-dev \
      libgtest-dev \
      libopenni-dev \
      libopenni2-dev \
      libproj-dev \
      libqhull-dev \
      libqt5opengl5-dev \
      libusb-1.0-0-dev \
      libvtk6-dev \
      libvtk6-qt-dev \
      qtbase5-dev \
 && rm -rf /var/lib/apt/lists/*
```

**Comment by borgmanJeremy** [comment]
Thanks! Sorry I forgot to close this out.
