### ISSUE TITLE
Does the viewpoint of the camera means the position of the camera or the point the camera focus on?

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#2983]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler: gcc5.4.0
* PCL Version:1.9.1

## Question

Hi, I want to confirm a concept, Does the viewpoint of the camera means the position of the camera or the point the camera focus on? And What does the viewpoint of the pcd file mean?

**Comment by SergioRAgostinho** [comment]
To define a viewpoint you need a location for the camera centre and a 3D orientation. Having only the camera location and point to look at is not enough to fully define the orientation. The [specification](http://pointclouds.org/documentation/tutorials/pcd_file_format.php#pcd-file-format) tells you the format of the view point. It's composed of seven floats, the first three for the camera location and the last 4 for the camera orientation specified as a quaternion `[w, x, y, z]`.

**Comment by TouchDeeper** [comment]
But for a monocular camera, in my understanding, the location of a camera and the point to look at can define the orientation.  If I'm wrong, please tell me. Thanks a lot!

**Comment by SergioRAgostinho** [comment]
> But for a monocular camera, in my understanding, the location of a camera and the point to look at can define the orientation. 

If we consider the usual Computer Vision convention, with those two points you only defined the Z axis. There are still infinite valid 3D rotation, which have that same Z axis.

**Comment by TouchDeeper** [comment]
Oh, my fault, Thanks for your explanation.

**Comment by TouchDeeper** [comment]
Hi,
What is the difference between the viewpoint [here](https://github.com/PointCloudLibrary/pcl/blob/a13ad265dc17b6edf841d066c26ae185fe2b8c80/features/include/pcl/features/normal_3d.h#L343-L355) and viewpoint in pcd file.
Dose the (vpx,vpy,vpz) means the loacation of camera or the point focus on?

**Comment by SergioRAgostinho** [comment]
The viewpoint for `NormalEstimation` is used to disambiguate the "sign" of the normal. Imagine a horizontal plane, the normal could point up or down and both are correct. The viewpoint in `NormalEstimation` is the location of the camera. With this knowledge you can flip all your normals so that they in point to where the camera is (as much as possible).
