### ISSUE TITLE
Installing pcl on windows using all in one installer

### ISSUE THREAD

**Issue by CesMak** [PointCloudLibrary/pcl#2987]
Hey there,

My system:
- Win 64Bit,  SDK version 10.0.14393.0 to target Windows 10.0.17763.
- CMake 3.14.1
- Visual Studio Express 2015

What I did:
1.  install [all in one installer of PCL 1.6 of the official website](http://www.pointclouds.org/downloads/windows.html) failed cause of too old versions of OpenNI etc. 
2. I installed **PCL 1.8.1 All-in-one Installer MSVC2015 Win32** from  [here](http://unanancyowen.com/en/pcl181/), this worked.
- I then build a sample pcl project using cmake gui  --> **worked**
- I opened the .sln file in Visual Studio as admin and build the code --> **worked** .exe was created
- I tried to start the generated .exe file in *my_sample_project/build/Debug* folder  which failed and said missing .dll's I then copied all the .dll's from the C:\Program Files (x86)\PCL 1.8.1\bin to *my_sample_project/build/Debug*. I then did not have the missing .dll error anymore. However I had a **0xc70000 Error** when starting the *.exe* --> I read that I have a win64 Bit system and I installed the 32bit pcl version which I think was the problem
3. I installed **PCL 1.8.1 All-in-one Installer MSVC2015 x64** from  [here](http://unanancyowen.com/en/pcl181/), this worked so far
- I then build a sample pcl project using cmake gui --> **worked**
- I copied again the .dll's as in step 2
- I opened the .sln file in Visual Sutdio as admin and build the code and got **Errors**:

**For the pcl_visualizer exampe I got this error:** 
```
 ImmediateModeRenderingOff is no element of vtkmapper in 
C:\Program Files\PCL 1.8.1\include\pcl-1.8\pcl\visualization\impl\pcl_visualizer.hpp	1431	
: am_it->second.actor->GetMapper ()->ImmediateModeRenderingOff ();
```

**In General for other projects I have these errors**
```
LNK2019	"void __cdecl pcl::console::print(enum pcl::console::VERBOSITY_LEVEL,char const *,...)" (?print@console@pcl@@YAXW4VERBOSITY_LEVEL@12@PBDZZ)" in function ""public: void __thiscall pcl::detail::FieldMapper<struct pcl::PointXYZ>::operator()<struct pcl::fields::x>(void)" (??$?RUx@fields@pcl@@@?$FieldMapper@UPointXYZ@pcl@@@detail@pcl@@QAEXXZ)".	statistical_removal	
```

I already  tried to solve these LNK errors as written as follows:
- "My Problem was, besides the missing common.lib the problem that i used Visual studio with a 32 bit compiler. But PCL and all the dependencies were 64. so i installt the 32 bit PCL and it worked" from [here](http://www.pcl-users.org/Linker-Error-Visual-Studio-2010-Pro-td3800875.html)
- I also tried [this](https://stackoverflow.com/questions/10331341/point-cloud-library-simple-example-link-error/10339082)

Questions:
- For what do I need the .pdb files and where do I have to store them
- How to solve the LNK 2019, LNK 2001, LNK1120 Errror

**Comment by CesMak** [comment]
You can close this I found my issue:

I simply changed in cmake to 64bit and now everything works:

![image](https://user-images.githubusercontent.com/20240718/55857845-835dbf00-5b6e-11e9-9f41-1f6a5c67f4ab.png)

**Comment by SergioRAgostinho** [comment]
In case it is of interest, we now publish AllInOne installers in PCL's GitHub release page. [Here's](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.9.1) the one related to the latest release (scroll all the way down).

**Comment by CesMak** [comment]
Thanks :) thats of great help :)
