### ISSUE TITLE
Use C++11 random generator instead of Boost in RangeLikelihood

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2988]
Currently there is some Boost code, because `pdf`/`cdf` has no direct equivalent in C++14.

https://github.com/PointCloudLibrary/pcl/blob/93f9e7233dfa87299212f6cbaa35dedfc1dd251b/simulation/src/range_likelihood.cpp#L559-L584

**Comment by kunaltyagi** [comment]
@Morwenn We should close this issue, right? Based on the discussions before, using boost distributions provides better reproducibility.

**Comment by Morwenn** [comment]
Apparently the Boost components in `RangeLikelihood` have already been replaced by `std::` ones a year ago, so the issue should have been closed regardless. If you want to rollback the distribution to the Boost one, I guess that it can be done as part of #3996 or a new issue.
