### ISSUE TITLE
How can I use pcl on Android？Anyone compile successful？

### ISSUE THREAD

**Issue by dvlee1024** [PointCloudLibrary/pcl#2991]
as title.

**Comment by SergioRAgostinho** [comment]
The people involved in #2358 seemed to be relatively successful at doing so. I also know Debian is also able to compile PCL for its arm architecture.

I can't advise you on how to do it though.

**Comment by andophine** [comment]
Here is the information that I followed to build PCL for Android. https://github.com/bashbug/pcl-for-android. However, the performance is quite slow compared than running on MAC or Windows system.

**Comment by kunaltyagi** [comment]
@Morwenn is the conan setup significantly different in the aforementioned project and your conan file?

**Comment by Morwenn** [comment]
@kunaltyagi From what I can see there's a lot of variables manually provided to CMake that are implicit on mine (`CMAKE_BUILD_TYPE`, etc.) and some are fixed while we let the choice (libraries, shared PCL, static Flann) - it's pretty clear that they fixed the options to what they needed and that they know to work. It notably manually specifies the library paths which we don't need to do when generators are used properly.

The one thing it actually does and that I don't handle is the Android toolchain configuration, I'm not sure what Conan provides to simplify that and I never did it so I can't really comment on this part.

**Comment by kunaltyagi** [comment]
> ... which we don't need to do when generators are used properly

So apart from the android toolchain config, there's not much different? That's nice to know, because we can ask the author to try and update our recipe (once it's ready)

**Comment by kunaltyagi** [comment]
Needs #4076
