### ISSUE TITLE
pcl_viewer

### ISSUE THREAD

**Issue by SunshineDou** [PointCloudLibrary/pcl#2994]
## Your Environment

* Operating System and version:Ubuntu16.04
* Compiler:
* PCL Version:the latest version

hello, I want to use pcl_viewer to view a pcd file, but it report a problem as follows
![2019-04-12 23-27-48屏幕截图](https://user-images.githubusercontent.com/25578572/56019563-8fe14380-5d37-11e9-9e29-30a881cbc1e9.png)

I have installed QT5.11.0, and I have installed pcl successfully
Thanks

**Comment by borgmanJeremy** [comment]
Those libs appear to be in: https://packages.ubuntu.com/xenial/amd64/libqt5sql5/filelist
Try using: sudo apt install libqt5sql5
