### ISSUE TITLE
Switching from normal_distribution<> to normal_distribution<float> causes CorrespondenceRejectors.CorrespondenceRejectionPoly to fail

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#2995]
The following changes will cause the tests to fail, even it doesn't change anything relevant.

https://github.com/PointCloudLibrary/pcl/blob/88660062d88bcce91d9ea2f1547f7673c7910a26/test/registration/test_correspondence_rejectors.cpp#L101-L107

```
 std::normal_distribution<float> nd(0.0f, 0.005f); 
 for (auto &point : target) 
 { 
   point.x += nd(rng); 
   point.y += nd(rng); 
   point.z += nd(rng); 
 }
```

**Comment by kunaltyagi** [comment]
Verified, occurs only on Windows, not MacOS or Ubuntu

**Comment by larshg** [comment]
`std::normal_distribution<>` defaults to double, when no argument is supplied. I guess there could be rounding errors when doing static_cast to float.
std::normal_distribution with floats, just have lower variance?

This is what I get:
* std::normal_distribution with default double and cast to float gives 148 inliers.
* std::normal_distribution with float specified, gives 157 inliers.
* boost::normal_distribution with double and cast to float gives 147 inliers.
* boost::normal_distribution with float specified gives 143 inliers.

So there seems to be a variation between the implementations of the variance of the noise added.

Test criteria says "but not too many" - which could be raised to 1.6 times ground_truth_frac - 157(inliers)/397(total count) / 0.251889169(ground truth fraction) = 1.569999... which is within 1.6.

```
/*
   * Test criterion 1: verify that the method accepts at least 25 % of the input correspondences,
   * but not too many
   */
  EXPECT_GE(accepted_frac, ground_truth_frac);
  EXPECT_LE(accepted_frac, 1.6f*ground_truth_frac);
```

**Comment by kunaltyagi** [comment]
Thanks for the sleuthing. Please go ahead with a PR @larshg
