### ISSUE TITLE
detect circle

### ISSUE THREAD

**Issue by CesMak** [PointCloudLibrary/pcl#3000]
Hey there,

I hope its ok to ask this question here. 

I want to detect a circle in this pcl:
![image](https://user-images.githubusercontent.com/20240718/56196688-99b8be80-6037-11e9-8f0c-36f1ac93dbac.png)

Unfortunately my circle detection method thinks the outer square is a circle:
```

void 
detect_circle(pcl::PointCloud<PointT>::Ptr &cloud, pcl::ModelCoefficients::Ptr &coefficients_circle)
{
	//SACMODEL_CIRCLE2D - used to determine 2D circles in a plane.The circle's three coefficients are given by its center and radius as: [center.x center.y radius]
	print_info("\n Detect circle.\n");

	// All the objects needed
	pcl::PCDReader reader;
	pcl::PassThrough<PointT> pass;
	pcl::NormalEstimation<PointT, pcl::Normal> ne;
	pcl::SACSegmentationFromNormals<PointT, pcl::Normal> seg;
	pcl::PCDWriter writer;
	pcl::ExtractIndices<PointT> extract;
	pcl::ExtractIndices<pcl::Normal> extract_normals;
	pcl::search::KdTree<PointT>::Ptr tree(new pcl::search::KdTree<PointT>());

	// Datasets
	pcl::PointCloud<PointT>::Ptr cloud_filtered(new pcl::PointCloud<PointT>);
	pcl::PointCloud<pcl::Normal>::Ptr cloud_normals(new pcl::PointCloud<pcl::Normal>);
	pcl::PointCloud<PointT>::Ptr cloud_filtered2(new pcl::PointCloud<PointT>);
	pcl::PointCloud<pcl::Normal>::Ptr cloud_normals2(new pcl::PointCloud<pcl::Normal>);
	pcl::PointIndices::Ptr inliers_plane(new pcl::PointIndices), inliers_cylinder(new pcl::PointIndices);

	// Estimate point normals
	ne.setSearchMethod(tree);
	ne.setInputCloud(cloud);
	ne.setKSearch(50); //use neighbours for normals
					   //ne.setRadiusSearch(0.01); 	// Use all neighbors in a sphere of radius 3cm
	ne.compute(*cloud_normals);

	// Create the segmentation object for the planar model and set all the parameters
	seg.setOptimizeCoefficients(true);
	seg.setModelType(pcl::SACMODEL_CIRCLE2D);
	seg.setNormalDistanceWeight(0.1);
	seg.setMethodType(pcl::SAC_RANSAC);
	seg.setMaxIterations(100);
	seg.setDistanceThreshold(0.03);
	seg.setInputCloud(cloud);
	seg.setInputNormals(cloud_normals);
	// Obtain the plane inliers and coefficients
	seg.segment(*inliers_plane, *coefficients_circle);
	std::cerr << "Circle coefficients: " << *coefficients_circle << std::endl;
}
```

whats the best way to detect this 2D circle here?

**Comment by muzo583** [comment]
Hi,
did you try to change distance, radius and knn parameters?

**Comment by CesMak** [comment]
Hey,

well I guess I simply did not know that there is:
`seg.setRadiusLimits(0.008, 0.008);` option. 

Setting `seg.setDistanceThreshold(0.03);` makes sense to: 
 This is also where we specify the “distance threshold”, which determines how close a point must be to the model in order to be considered an inlier

Is there a way to also set a normal plane constraint? e.g. the circle has to lie in a defined plane?

**Comment by muzo583** [comment]
Hi ,
Maybe here?
http://docs.pointclouds.org/1.8.1/classpcl_1_1_sample_consensus_model_circle3_d.html

**Comment by SergioRAgostinho** [comment]
Just updating @muzo583 's link to the latest PCL version. http://docs.pointclouds.org/1.9.1/classpcl_1_1_sample_consensus_model_circle3_d.html

We removed some deprecated interfaces in the SAC module between versions.

**Comment by CesMak** [comment]
Well to set a predefined normal vector as constraint I guess I have to use:

![image](https://user-images.githubusercontent.com/20240718/56354644-9c9ce600-61d4-11e9-9318-961b29642540.png)


**However this is only a start point for the optimization and not a hard constraint....**

**Comment by kunaltyagi** [comment]
PCL doesn't support hard constraints. For that, please use other better suited generic constraints and optimization libraries.
