### ISSUE TITLE
Feature Request: Cylinder Detection with constraints

### ISSUE THREAD

**Issue by CesMak** [PointCloudLibrary/pcl#3002]
Hey there,

I wonder how to RANSAC fit a cylinder with constraints:
- using additional surface normal constraints
- using a fixed radius I guess I have to do:
`seg.setRadiusLimits(0.008, 0.008);` assuming a radius of 8mm

-> I am just interested in the center point. 

Does anyone know how to do that? 

With a look to the 
[API](http://docs.pointclouds.org/1.8.1/group__sample__consensus.html) I could not figure out how to do that... 

**Update**

[Here](http://www.pointclouds.org/blog/simpletree/) it says:

Typically cylinders are fitted into point clouds with either RANSAC or NLS fitting routines. **NLS needs initial estimates of cylinder parameters.** Also RANSAC tends to produce errourness cylinders, if no initial segmentation of the point cloud is performed before.

I currently did not saw any options in pcl to select NLS methods for estimating a cylinder.

**Comment by kunaltyagi** [comment]
Cylinder model consists of 4 variables: point_on_axis (x, y, z) and radius. You can find the min and max inlier on the model and compute the midpoint of the axis from them. For a cylinder, there's no "center"
