### ISSUE TITLE
problem with  pcl::SampleConsensus

### ISSUE THREAD

**Issue by pigluss** [PointCloudLibrary/pcl#3042]
I use pcl-1.9.1  ubuntu16.04  and  ros-kinetic .
when I compile a package  using  catkin_make the following problem has occurred:

```
undefined reference ‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::computeModelCoefficients(std::vector<int, std::allocator<int> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1>&)’
undefined reference ‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::optimizeModelCoefficients(std::vector<int, std::allocator<int> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, Eigen::Matrix<float, -1, 1, 0, -1, 1>&)’
undefiend reference
‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::getDistancesToModel(Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, std::vector<double, std::allocator<double> >&)’
undefined reference 
‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::countWithinDistance(Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, double)’
undefiend reference
‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::projectPoints(std::vector<int, std::allocator<int> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, pcl::PointCloud<pcl::PointXYZ>&, bool)’
undefiend reference
‘pcl::SampleConsensusModelLine<pcl::PointXYZ>::doSamplesVerifyModel(std::set<int, std::less<int>, std::allocator<int> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, double)’
```

**Comment by taketwo** [comment]
Well you have an issue with linking against PCL libraries. Make sure that you set `target_link_libraries` accordingly on your executable target.

**Comment by pigluss** [comment]
> Well you have an issue with linking against PCL libraries. Make sure that you set `target_link_libraries` accordingly on your executable target.

I have checked my CMakeLists.txt  .I have set target_link_libraries :

target_link_libraries(find_transform ${PCL_LIBRARIES})

**Comment by taketwo** [comment]
Please print the contents of `PCL_LIBRARIES` variable:

```cmake
message(STATUS "PCL Libraries: ${PCL_LIBRARIES})
```

**Comment by pigluss** [comment]
> Please print the contents of `PCL_LIBRARIES` variable:
> 
> ```cmake
> message(STATUS "PCL Libraries: ${PCL_LIBRARIES})
> ```

Sorry , I am a beginner of pcl .
I can not understand what you just say.
Could u speak more clearly?
Extremely grateful!!!

**Comment by taketwo** [comment]
What I posted is a CMake command that prints contents of a CMake variable. So just put this line in your "CMakeList.txt" file, next to the link libraries command.

**Comment by pigluss** [comment]
> What I posted is a CMake command that prints contents of a CMake variable. So just put this line in your "CMakeList.txt" file, next to the link libraries command.

Sorry,the problem has not been solved.

**Comment by pigluss** [comment]
> What I posted is a CMake command that prints contents of a CMake variable. So just put this line in your "CMakeList.txt" file, next to the link libraries command.

I can call other functions in PCL without error. But when I use ：
pcl::SampleConsensus
The program cannot be compiled.

**Comment by taketwo** [comment]
> Sorry,the problem has not been solved.

The command I posted was to get information that may help us to debug the issue, it was not supposed to solve the problem. As I wrote, please add it to your CMakeLists and post the output that it produces. This way we will be able to verify whether all the needed libraries are indeed linked.

**Comment by pigluss** [comment]
> > Sorry,the problem has not been solved.
> 
> The command I posted was to get information that may help us to debug the issue, it was not supposed to solve the problem. As I wrote, please add it to your CMakeLists and post the output that it produces. This way we will be able to verify whether all the needed libraries are indeed linked.

Thanks for your help!!! I have solved my problem after I reinstalled  PCL1.8.0 .
Thanks again!!!
