### ISSUE TITLE
Organized pcl or Non-organized pcl 

### ISSUE THREAD

**Issue by VIMOSBMOS** [PointCloudLibrary/pcl#3043]
Should the input for the morphology class be a organized point cloud or a non-organized point cloud?

https://github.com/PointCloudLibrary/pcl/blob/711b12144e2cb250fcbccf56b0c523a1d279297a/2d/include/pcl/2d/morphology.h#L45

**Comment by SergioRAgostinho** [comment]
From quickly skimming through the API, these are operations applied on "images"  and therefore the point cloud should be organized.

**Comment by VIMOSBMOS** [comment]
what happens when the height = 1(non-organized point cloud)? Can the morphology class still be used?

**Comment by VIMOSBMOS** [comment]
Is there a method to organize point cloud?
