### ISSUE TITLE
PCL duplicated includes required for 3dsc on Windows 10 with Visual Studio 2017

### ISSUE THREAD

**Issue by X-czh** [PointCloudLibrary/pcl#3046]
When I try to computer 3DSC features for the input point clouds, I have to include both <pcl/features/3dsc.h>and<pcl/features/impl/3dsc.hpp>. However, for other features like FPFH, SHOT, I only need to include <pcl/features/fpfh.h> and <pcl/features/shot.h> respectively.

I checked the source code of <pcl/features/3dsc.h>, and I found that the last lines of it are 
```c++
#ifdef PCL_NO_PRECOMPILE
#include <pcl/features/impl/3dsc.hpp>
#endif
```
It seems that I'm supposed to only include <pcl/features/3dsc.h> for usage (also aligned with what the PCL document writes), and the code should automatically include <pcl/features/impl/3dsc.hpp>. Am I right on this?

Environment:
Windows 10, version 1809 + Visual Studio 2017 version 15.9.11
PCL Version: 1.9.1, installed with PCL-1.9.1-AllInOne-msvc2017-win64.exe

**Comment by taketwo** [comment]
PCL has two main build modes, with and without precompilation. Further, if precompilation is enabled, then it can be done ether for all point types, or only for a subset of core types. @UnaNancyOwen may tell us which modes are used in the all-in-one installer.

For now let's assume precompilation is enabled, but only for core point types. This means that the class template will be instantiated only for these types:

https://github.com/PointCloudLibrary/pcl/blob/9e927997ed1a76cef3387fed46593b03fd2307fb/features/src/3dsc.cpp#L45-L46

If you want to use the class with a different type, then you have to include "hpp" file.

**Comment by UnaNancyOwen** [comment]
In Pre-built PCL, <code>PCL_NO_PRECOMPILE</code> is not defined.
It is configured these option with default settings.

https://github.com/PointCloudLibrary/pcl/blob/876a38df4db96d09687d017b37f75354bb9afcd3/cmake/pcl_options.cmake#L33-L39

**Comment by taketwo** [comment]
Thanks Tsukasa!

@X-czh this means that the library contained in the installer should have all necessary templates instantiated. Can you post errors that you get if you don't include "hpp" file?

**Comment by X-czh** [comment]
@taketwo 

The errors are as follows:

1>utils.obj : error LNK2001: unresolved external symbol "protected: virtual bool __cdecl pcl::ShapeContext3DEstimation<struct pcl::PointXYZRGB,struct pcl::Normal,struct pcl::ShapeContext1980>::initCompute(void)" (?initCompute@?$ShapeContext3DEstimation@UPointXYZRGB@pcl@@UNormal@2@UShapeContext1980@2@@pcl@@MEAA_NXZ)

1>utils.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::ShapeContext3DEstimation<struct pcl::PointXYZRGB,struct pcl::Normal,struct pcl::ShapeContext1980>::computeFeature(class pcl::PointCloud<struct pcl::ShapeContext1980> &)" (?computeFeature@?$ShapeContext3DEstimation@UPointXYZRGB@pcl@@UNormal@2@UShapeContext1980@2@@pcl@@MEAAXAEAV?$PointCloud@UShapeContext1980@pcl@@@2@@Z)
1>C:\Users\m1a2\Desktop\workspace\TeleWindow\registration\build\Release\registration.exe : fatal error LNK1120: 2 unresolved externals

**Comment by taketwo** [comment]
@UnaNancyOwen is it somehow possible to double-check if you have these symbols in the Windows installer?

(I checked that on Linux these symbols are present in the built PCL libraries.)

**Comment by UnaNancyOwen** [comment]
@X-czh Please provide simple code to reproduce this problem.

**Comment by X-czh** [comment]
@UnaNancyOwen 
Simplest possible code to reproduce this problem:
```c++
#include <pcl/point_types.h>
#include <pcl/features/3dsc.h>

int main() {
	pcl::ShapeContext3DEstimation<pcl::PointXYZRGB, pcl::Normal, pcl::ShapeContext1980> threedsc_est;
	return 0;
}
```

**Comment by UnaNancyOwen** [comment]
@X-czh Please add this line to your own CMakeLists.txt.
```
add_definitions( -DPCL_NO_PRECOMPILE )
```

**Comment by X-czh** [comment]
@UnaNancyOwen 
Thanks! Both solutions work. It is interesting though, to see that changing input point cloud type to pcl::PointXYZ from pcl::PointXYZRGB works as well. As I am working with colored point cloud, I will go for the first solution.

**Comment by taketwo** [comment]
FWIW first solution is equivalent to including the file manually.
