### ISSUE TITLE
is there a watershed segmentation class for PCL data?

### ISSUE THREAD

**Issue by VIMOSBMOS** [PointCloudLibrary/pcl#3047]
https://github.com/PointCloudLibrary/pcl/blob/711b12144e2cb250fcbccf56b0c523a1d279297a/2d/include/pcl/2d/morphology.h#L45

**Comment by kunaltyagi** [comment]
I guess the answer is no. @SergioRAgostinho ?

**Comment by mvieth** [comment]
Pretty sure there isn't
