### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by tub-sgg** [PointCloudLibrary/pcl#3049]
## Your Environment  MacOS  High Sierra

* Operating System and version:
* Compiler:clang 
* PCL Version:1.9.1
I install PCL1.9.1 using homebrew,and use cmake to creat the enviroment
CMakeLists is as follows:
cmake_minimum_required( VERSION 2.8 )

# Create Project
project( solution )
add_executable( project pcd_write.cpp )
set_property( DIRECTORY PROPERTY VS_STARTUP_PROJECT "project" )

# Find Packages
find_package( PCL REQUIRED )

if( PCL_FOUND )
  # Additional Include Directories
  # [C/C++]>[General]>[Additional Include Directories]
  include_directories( ${PCL_INCLUDE_DIRS} )

  # Preprocessor Definitions
  # [C/C++]>[Preprocessor]>[Preprocessor Definitions]
  add_definitions( ${PCL_DEFINITIONS} )
  #add_definitions( -DPCL_NO_PRECOMPILE )

  # Additional Library Directories
  # [Linker]>[General]>[Additional Library Directories]
  link_directories( ${PCL_LIBRARY_DIRS} )

  # Additional Dependencies
  # [Linker]>[Input]>[Additional Dependencies]
  target_link_libraries( project ${PCL_LIBRARIES} )
endif()

## Context

*** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1454.95/Foundation/Misc.subproj/NSUndoManager.m:361
2019-05-01 22:15:07.489 project[13119:584294] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff38bc69cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5fef8942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff38bcc5b2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3ad12150 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x00007fff3aca0d44 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff360c696e -[NSApplication run] + 997
	6   libpcl_visualization.1.9.dylib      0x0000000115482aa4 _ZN3pcl13visualization13PCLVisualizer8spinOnceEib + 318
	7   libpcl_visualization.1.9.dylib      0x00000001154a4710 _ZN3pcl13visualization11CloudViewer16CloudViewer_implclEv + 664
	8   libboost_thread-mt.dylib            0x000000010aaf5268 _ZN5boost12_GLOBAL__N_112thread_proxyEPv + 120
	9   libsystem_pthread.dylib             0x00007fff60e27661 _pthread_body + 340
	10  libsystem_pthread.dylib             0x00007fff60e2750d _pthread_body + 0
	11  libsystem_pthread.dylib             0x00007fff60e26bf9 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
  always occur like this

**Comment by kunaltyagi** [comment]
Solution is not to use Xcode instead set `xcode-select -s /Library/Developer/CommandLineTools` for compiling from command line
