### ISSUE TITLE
Error building pcl 1.8 

### ISSUE THREAD

**Issue by ChewbEp** [PointCloudLibrary/pcl#3052]
Hi there,
I've just installed pcl 1.8, and I was building it when I falled into a compiling error.
I am using Ubuntu 16.04 LTS, with a kinetic version of ROS.
I have created a workspace, with a directory called "pcl_demo"; in this directory, there's a folder (scr) in which I have located the .cpp file and the CMakeLists.txt files, both realized following the guide at this link:

http://pointclouds.org/documentation/tutorials/pcl_visualizer.php

The problem is that when I compile the file, typing "cmake ." and then "make", it turns out the following error:

> Scanning dependencies of target pcl_visualizer_demo
> [ 50%] Building CXX object CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.o
> In file included from /usr/include/c++/5/thread:35:0,
>                  from /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp:4:
> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
>  #error This file requires compiler and library support \
>   ^
> /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp:379:33: error: invalid suffix "ms" on integer constant
>      std::this_thread::sleep_for(100ms);
>                                  ^
> /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp:12:22: error: ‘chrono_literals’ is not a namespace-name
>  using namespace std::chrono_literals;
>                       ^
> /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp:12:37: error: expected namespace-name before ‘;’ token
>  using namespace std::chrono_literals;
>                                      ^
> /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp: In function ‘int main(int, char**)’:
> /home/alessiadele/VTK-7.1.0/build/pcl-pcl-1.8.0/pcl_demo/src/pcl_visualizer_demo.cpp:379:10: error: ‘std::this_thread’ has not been declared
>      std::this_thread::sleep_for(100ms);
>           ^
> CMakeFiles/pcl_visualizer_demo.dir/build.make:62: recipe for target 'CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.o' failed
> make[2]: *** [CMakeFiles/pcl_visualizer_demo.dir/pcl_visualizer_demo.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pcl_visualizer_demo.dir/all' failed
> make[1]: *** [CMakeFiles/pcl_visualizer_demo.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> 

I thought that the problem could be the file's location into the directories, but I've followed different tutorials, so I think that it is correct. Now I don't know where the error could be.
Could you please help me??
Thanks a lot!

**Comment by borgmanJeremy** [comment]
The error is telling you that your compiler does not have C++ 11 enabled. Try adding this to your cmake file (where $$REPLACE_ME$$ is the target you are trying to build). Also make sure your compiler supports C++.

set_target_properties( $$REPLACE_ME$$ PROPERTIES CXX_STANDARD 11)

**Comment by taketwo** [comment]
The tutorial on the website was updated few months ago to use C++11 features. But you can access an older version (which is essentially the same, for example [here](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/doc/tutorials/content/sources/pcl_visualizer/pcl_visualizer_demo.cpp).
