### ISSUE TITLE
Update PCD format documentation to include binary_compressed DATA format

### ISSUE THREAD

**Issue by nlgranger** [PointCloudLibrary/pcl#3053]
## Context

I am trying to import pcd files directly in python without using the PCL library python bindings.
My project is too small to justify pulling the whole PCL package just to load a few files. Besides the file format seems simple and designed to facilitate interoperability outside the PCL project.

## Expected Behavior

Documentation about the PCD file format http://pointclouds.org/documentation/tutorials/pcd_file_format.php should detail how to read  DATA in binary_compressed format.
I was not able to find informations elsewhere, the source code is not easy to find and read.

The documentation should also mention that data is transposed and explain how multidimensional points are handled in that context (flattened dimensions or still n-uplets?).

## Possible Solution

Update the documentation.
Explain that data is tranposed to improve compression (does this impact WIDTH/HEIGHT?)
Briefly document the lzf format as it is not widely known.
Maybe give a simple example to read it in python.

**Comment by mvieth** [comment]
@nlgranger I created a pull request to add the documentation. If you would have a look at it and say whether it is good, that would be very helpful.

**Comment by mvieth** [comment]
Great, thank you for your opinion!
