### ISSUE TITLE
flann path

### ISSUE THREAD

**Issue by tiger-bug** [PointCloudLibrary/pcl#3058]
## Your Environment
* Operating System and version: Windows 10
* Compiler: Visual Studio 19
* PCL Version: PCL-1.9.1-AllInOne-msvc2017-win64.exe

## Context
Newbie in both C++ and PCL.  I followed the tutorial on normal and region growing segmentation and attempted to build the executable.  It appears that it's looking in the incorrect directory.  I did the 3rd party library install in the all in one install which is saved them here: **C:\Program Files\PCL 1.9.1\3rdParty\**.  It appears it's looking for it here: **C:\Program Files\PCL 1.9.1\include\pcl-1.9\pcl/kdtree/flann.h**.    How do I set it to the 3rd party folder?
  I have the image of what was generated attached.  thanks!

![directory](https://user-images.githubusercontent.com/40045042/57085285-83f6fa80-6cc1-11e9-8338-b4591747027e.JPG)

**Comment by kunaltyagi** [comment]
We recommend using vcpkg for setting up PCL instead. Closing in favor of #4118
