### ISSUE TITLE
Undefined Reference error  to pcl::visualization while compiling with libtorch

### ISSUE THREAD

**Issue by UsamaHasan** [PointCloudLibrary/pcl#3059]
## Your Environment

* Operating System and version:Ubuntu 18.04
* Compiler: GCC
* PCL Version: 1.8

## Context

Hy there, I'm trying to compile PCL with libtorch, I got undefined reference to pcl::visualization. If I compile it separately without Libtorch, it works fine. I think there is an error with compiling due to difference in cmake compilation of both the libraries 
## Expected Behavior

My CMakeLists.txt file looks like this
cmake_minimum_required(VERSION 2.6)
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
endif()

find_package(PCL 1.7 REQUIRED)
find_package(Torch REQUIRED)
add_executable(main main.cpp)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

target_link_libraries(main ${PCL_LIBRARIES})

target_link_libraries(main ${TORCH_LIBRARIES})
target_include_directories(main PUBLIC ${PCL_INCLUDE_DIR})

message("STATUS PCL PATH${PCL_INCLUDE_DIRS}")

## Current Behavior

And the error is
..
ERROR:
In function main': main.cpp:(.text+0x1d44): undefined reference to pcl::visualization::PCLVisualizer::PCLVisualizer(std::string const&, bool)'
main.cpp:(.text+0x1eaf): undefined reference to `pcl::visualization::PCLVisualizer::setPointCloudRenderingProperties(int, double, std::string const&, int)'
collect2: error: ld returned 1 exit status

## Code to Reproduce

CMakeLists.txt

**Comment by taketwo** [comment]
I would speculate that the error has something to do with mixing C++ standards. Your PCL 1.8 was probably compiled without C++11, while the target that you are building is C++11 and thus expects to link against libraries with C++11 classes (specifically `std::string`) in ABI.

To solve your problem, try to build current PCL master from source and link against it.

**Comment by UsamaHasan** [comment]
Ok, I'll try to build it again with C++11 standards.

**Comment by UsamaHasan** [comment]
Noted!

**Comment by UsamaHasan** [comment]
Noted @SergioRAgostinho

**Comment by taketwo** [comment]
Any news here? Did you solve the problem?

**Comment by UsamaHasan** [comment]
Yes I did solved it by building it from source with c++14 Standards. Thanks @taketwo
