### ISSUE TITLE
VISP 3.2.0 fails to build with cmake 3.14.3 and PCL 1.9.1

### ISSUE THREAD

**Issue by fxcoudert** [PointCloudLibrary/pcl#3062]
## Your Environment

* Operating System and version: macOS 10.12 to 10.14
* Compiler: Apple LLVM version 10.0.1
* PCL Version: 1.9.1

## Context

Trying to build VISP 3.2.0 as part of Homebrew packaging: https://github.com/Homebrew/homebrew-core/pull/39438

## Current Behavior

Running `cmake` to build VISP fails due to PLC-related cmake files:
```
CMake Error at /usr/local/share/pcl-1.9/PCLConfig.cmake:361 (pcl_report_not_found):
  cmake_policy POP without matching PUSH
Call Stack (most recent call first):
  /usr/local/share/pcl-1.9/PCLConfig.cmake:545 (find_external_library)
  cmake/VISPUtils.cmake:533 (find_package)
  CMakeLists.txt:597 (VP_OPTION)


CMake Error in /usr/local/share/pcl-1.9/PCLConfig.cmake:
  cmake_policy PUSH without matching POP
Call Stack (most recent call first):
  cmake/VISPUtils.cmake:533 (find_package)
  CMakeLists.txt:597 (VP_OPTION)
```

**Comment by zbeekman** [comment]
FYI, this also still fails after installing pkg-config, as recommended by visp for resolving the build-system bug.
