### ISSUE TITLE
Voxel grid filter is often warning "Leaf size is too small for the input dataset"

### ISSUE THREAD

**Issue by dogod621** [PointCloudLibrary/pcl#3072]
Same as #86 #585.

Why not fix the index issue?  
The voxel grid filter is nearly unusable, because it  is always warning "Leaf size is too small" and then return (did not filter).

## Your Environment

* Operating System and version: Windows 10
* Compiler: 
* PCL Version: 1.9.1

**Comment by SergioRAgostinho** [comment]
Probably a good idea to reply under those same issues an not open a new one.

> Why not fix the index issue?
Mostly lack of time. Our users most desired feature at the moment is C++14, so that's where our limited is invested at.

Closing it as a duplicate.
