### ISSUE TITLE
cant Compile pcl/surface/on_nurbs

### ISSUE THREAD

**Issue by shammmmmless** [PointCloudLibrary/pcl#3097]
## Your Environment

* Operating System and version:ubuntu 16.04
* Compiler: cmake
* PCL Version:1.9

## Context

source code contains pcl/surface/on_nurbs, but after I install pcl1.9, I only find the other three folders(3rdparty, impl and vtk_smoothing) but no on_nurbs.

I install dependencies which are requested in cmake file. 
## Expected Behavior

If these files are Deprecated, pls tell which version should I use if I want on_nurbs; or some possible reason to lead this problem.

## Current Behavior

I tried 1.7, 1.8, both not work; I install pcl on another ubuntu 16.04 computer, also not work.
I install pcl by compiling source and apt-get, both not work.

**Comment by SergioRAgostinho** [comment]
Did you enable `-DBUILD_surface_on_nurbs` when invoking cmake? It is OFF by default.

**Comment by shammmmmless** [comment]
Thanks a lot, it works.

**Comment by gitouni** [comment]
> Did you enable `-DBUILD_surface_on_nurbs` when invoking cmake? It is OFF by default.

I have set this parameter ON but it still caused the same error
```bash
cmake -DBUILD_surface_on_nurbs=ON ..
```
```
fatal error: pcl/surface/on_nurbs/fitting_surface_tdm.h: file not found error
    6 | #include <pcl/surface/on_nurbs/fitting_surface_tdm.h>
```

**Comment by larshg** [comment]
Make sure you actually find the PCL version you have build from source then.
The file is here https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/on_nurbs/fitting_surface_tdm.h 
So if you have cmaked PCL with surface_on_nurbs and run make install, then it should be picked up by sub projects. But ensure that you don't have some other version of PCL installed without surface_on_nurbs, which get picked up.

**Comment by gitouni** [comment]
> Make sure you actually find the PCL version you have build from source then. The file is here https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/on_nurbs/fitting_surface_tdm.h So if you have cmaked PCL with surface_on_nurbs and run make install, then it should be picked up by sub projects. But ensure that you don't have some other version of PCL installed without surface_on_nurbs, which get picked up.

Thank you for your reply. I have solved this problem by re-cmaked PCL and fixed FLANN 1.9 error through #804 (https://github.com/PointCloudLibrary/pcl/issues/804#issuecomment-49752261)

**Comment by Simonespinosa** [comment]
Can` cmake -DBUILD_surface_on_nurbs=ON .. ` be done on clion? I tried it without clion and I get the same error, I went to my installation folder and it doesn't have the on_nurbs folder at all. Any ideas?

**Comment by larshg** [comment]
> Can`cmake -DBUILD_surface_on_nurbs=ON ..` be done on clion? I tried it without clion and I get the same error, I went to my installation folder and it doesn't have the on_nurbs folder at all. Any ideas?

Building PCL ? There shouldn't be any problem if you run cmake from clion, as long as the flag is set.

**Comment by Simonespinosa** [comment]
I have gone to the instalation folder and the folder on_nurbs doesn't exist. I have unistalled and installed pcl again and it is still not available.

**Comment by larshg** [comment]
> I have gone to the instalation folder and the folder on_nurbs doesn't exist. I have unistalled and installed pcl again and it is still not available.

How do you install PCL? You need to download the sources and compile it yourself.
