### ISSUE TITLE
Deprecation issues with boost 69.0

### ISSUE THREAD

**Issue by stoecker** [PointCloudLibrary/pcl#3114]
For boost 69.0 (openSUSE Tumbleweed) the package only builds with -DBOOST_ALLOW_DEPRECATED_HEADERS and then still issues a lot of warnings.

It would probably be a good idea to fix these deprecations, so building will not fail totally with next version. I assume these deprecated files are deprecated for some time, so that fixing this should not break older versions.

**Comment by taketwo** [comment]
Hi, thanks for bringing this up. So far we tried to remove all usage of deprecated headers as soon as it was reported. Can you post the complete log so that we can have a look? Also, are you using the `master` branch of PCL?

**Comment by stoecker** [comment]
Ah, seems to have been fixed in master at 22 Jan. Sorry for the noise. I'm a bit behind, as I overlooked the last release and only now build it :-)
