### ISSUE TITLE
Error when running SHOT_estimation with Eigen 3.2.10

### ISSUE THREAD

**Issue by Andreachen0707** [PointCloudLibrary/pcl#3126]
Hi,
I have a very weird problem when running SHOT feature descriptor extraction. The program just not working on my dataset so I tried the program with dataset provided in tutorial.http://pointclouds.org/documentation/tutorials/correspondence_grouping.php and got the following errors:

#0  0x00007ffff47f314a in void Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<float, -1, 1, 0, -1, 1>, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, 1, 0, -1, 1> >, Eigen::internal::assign_op<float, float> >(Eigen::Matrix<float, -1, 1, 0, -1, 1>&, Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Matrix<float, -1, 1, 0, -1, 1> > const&, Eigen::internal::assign_op<float, float> const&) ()
   from /usr/local/lib/libpcl_filters.so.1.8
#1  0x00007ffff37a607d in pcl::SHOTEstimation<pcl::PointXYZ, pcl::Normal, pcl::SHOT352, pcl::ReferenceFrame>::computePointSHOT(int, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> > const&, Eigen::Matrix<float, -1, 1, 0, -1, 1>&) () from /usr/local/lib/libpcl_features.so.1.8
#2  0x00007ffff379759e in pcl::SHOTEstimation<pcl::PointXYZ, pcl::Normal, pcl::SHOT352, pcl::ReferenceFrame>::computeFeature(pcl::PointCloud<pcl::SHOT352>&) () from /usr/local/lib/libpcl_features.so.1.8
#3  0x000000000043e747 in pcl::Feature<pcl::PointXYZ, pcl::SHOT352>::compute(pcl::PointCloud<pcl::SHOT352>&) ()
#4  0x000000000043b013 in main () 

Compiler is:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2

Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10+deb8u2' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10+deb8u2) 

Any suggestion would be highly appreciated! Thanks in advance!

Best,
Andrea

**Comment by kunaltyagi** [comment]
Ubuntu 16.04 is the oldest supported platform, which has Eigen 3.3 has the available version. PCL can't support versions it can't test
