### ISSUE TITLE
linux install pcl

### ISSUE THREAD

**Issue by tub-sgg** [PointCloudLibrary/pcl#3133]
An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
qtbase/src/gui/configure.json:
  expected replacement of "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\" ]," with "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\", \"xcb/shm.h\" ],"

when i install qt dependency like this  but i jh
## Your Environment

* Operating System and version:centos 7.0 and  ubuntu 18.04 
* Compiler:
* PCL Version:

**Comment by kunaltyagi** [comment]
Issue isn't with PCL. Please open a new issue is the problem still persists.
