### ISSUE TITLE
Error C1083 about FLANN_STATIC on Visual C++

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#3147]
This compiler error occurs when build user code with Visual C++.
```
1>FLANN_STATIC
1>c1xx : fatal error C1083: Cannot open source file: 'FLANN_STATIC': No such file or directory
```
If revert this change https://github.com/PointCloudLibrary/pcl/pull/2905, It will not occure this error.
```patch
-  set(FLANN_DEFINITIONS ${FLANN_DEFINITIONS} "FLANN_STATIC")
+  set(FLANN_DEFINITIONS ${FLANN_DEFINITIONS} "-DFLANN_STATIC")
```

## Your Environment
* Operating System and version: Windows 10
* Compiler: Visual Studio 2017 15.9.13 
* PCL Version: master/HEAD (built as dynamic link library)
* CMake Version: CMake 3.14.4

**Comment by SergioRAgostinho** [comment]
In your case, the definition switch `-D` and `/D` it on your case, doesn't get prepended. In the original bug #2904, the `-D` was not being parsed properly and created a bad definition inside the code. I'm not really sure how to proceed here. 

@dooxe which platform and cmake version were you using when you encountered the problem in #2904?

**Comment by dooxe** [comment]
Hello,

I'm using a cmake version 3.13.4, on MacOS Mojave.
I confirm the issue. After having tried a fresh build again, an error occurs.

Steps to reproduce: 
- clone (github) and build static LZ4 and use the cmake toolchain
- clone (github) and build static FLANN
- clone (github) and build static pcl using the correct paths for the above libraries.

This command:
`cat build/pcl/kdtree/CMakeFiles/pcl_kdtree.dir/flags.make | grep -e "FLANN"`
gives the following output:
`CXX_DEFINES = -D-DFLANN_STATIC`

Which is a weird behaviour if we look at cmake documentation:
https://cmake.org/cmake/help/v3.14/command/add_definitions.html?highlight=i

After some investigations I found out that the variable `FLANN_DEFINITIONS` that is filled in the file `FindFLANN.cmake` is used in the following cmake command: 
`set_target_properties(FLANN::FLANN PROPERTIES INTERFACE_COMPILE_DEFINITIONS "${FLANN_DEFINITIONS}")`
In the following documentation page https://cmake.org/cmake/help/v3.13/prop_tgt/COMPILE_DEFINITIONS.html, the `COMPILE_DEFINITIONS` values do not have a `-D` prefix, it says: "`VAR` or `VAR=value`".

I hope it will help.

**Comment by taketwo** [comment]
@dooxe I am confused by your conclusion. At the moment, we don't have `-D` prefix, as is required by `COMPILE_DEFINITIONS` property that we use. Why do you conclude that this can be the source of error?

**Comment by dooxe** [comment]
I meant that it could have been a source of error when coding this part of the cmake, not for the compilation itself. 

With the name `FLANN_DEFINITIONS`, one could think that this variable is passed to the macro `add_definitions`, which is not the case.

This variable is passed to the macro `set_target_properties` with property `COMPILE_DEFINITIONS` for which there is no need to prefix by `-D`.

**Comment by taketwo** [comment]
OK, I see. Then taking into account that @UnaNancyOwen's error occurs while building a downstream project, I wonder if there maybe a mistake in it's CMakeLists? E.g. some explicit manipulation of compiler definitions? @UnaNancyOwen can you post your script?

**Comment by UnaNancyOwen** [comment]
I tried three versions about <code>FLANN_STATIC</code>.
This macro may not be necessary in Visual C++. What do you think?

1. -DFLANN_STATIC
  I think this is definitely wrong. 
  It is output the following, but that doesn't make sense.
  ```
  /D "-DFLANN_STATIC"
  ```

2. FLANN_STATIC
  This is output the following. It is a command that makes sense.
  But, user project can't build (error C1083).
  ```
  /D "FLANN_STATIC"
  ```

3. Remove This Line
  It can be built library and user project.
  ```
  ```

**Comment by taketwo** [comment]
As far as I can see, it's indeed unnecessary to pass `FLANN_STATIC` to any code that consumes FLANN. The [only usage](https://github.com/mariusmuja/flann/search?q=FLANN_STATIC&type=Code) of this macro in the entire project is in a "cpp" file, so relevant only during compilation. Therefore, your solution 3 the way to go.

**Comment by UnaNancyOwen** [comment]
Is it still necessary on other platforms (Linux, Mac)?
If so, I will add condition branch that if not MSVC.
```patch
+ if(NOT MSVC)
set(FLANN_DEFINITIONS ${FLANN_DEFINITIONS} "FLANN_STATIC")
+ endif()
```
If not so, I will remove this line.
```patch
- set(FLANN_DEFINITIONS ${FLANN_DEFINITIONS} "FLANN_STATIC")
```

**Comment by taketwo** [comment]
FLANN does not need this definition, no matter the platform. We also don't use it anywhere in PCL. Therefore I think it's absolutely safe to remove this line.
