### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3149]
The README has outdated information.

Updates required:
* [gitter channel](https://gitter.im/PointCloudLibrary/pcl)
* Google group(?)
* Remove mailing list(?)
* Remove API Lab link

Any other suggestions?

**Comment by SergioRAgostinho** [comment]
Instructions to move Q&A to StackOverflow.

**Comment by kunaltyagi** [comment]
[PCL on Stackoverflow](https://stackoverflow.com/tags/point-cloud-library/info) has the mailing list in information section. Maybe that should also be updated

**Comment by SergioRAgostinho** [comment]
> Is [this google group](https://groups.google.com/forum/#!forum/point-cloud-library) the right one? It has only 6 members

I don't think so. I just created a test group when I was working on the migration, I believe it is still under private score. I'm unaware of this origins of this one.

> [PCL on Stackoverflow](https://stackoverflow.com/tags/point-cloud-library/info) has the mailing list in information section. Maybe that should also be updated.

Definitely.
