### ISSUE TITLE
[include trimmed icp] error: ‘aux’ has not been declared

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#3151]
## Your Environment

* Operating System and version:ubuntu16.04
* Compiler: gcc5.4.0
* PCL Version:1.9.1

## Context

Hi,
If I have a line `#include <pcl/recognition/ransac_based/trimmed_icp.h>`, there will be an error `error: ‘aux’ has not been declared
               aux::transform (guess_and_result, source_points.points[i], transformed_source_point);`

Is it a bug?

**Comment by taketwo** [comment]
Looks like a bug. As far as I can see, this function is available in `pcl/recognition/ransac_based/auxiliary.h`, so try to include this header.

**Comment by TouchDeeper** [comment]
Hello Alexandrov,


Why is there a little parameters that can adjust in Trimmed ICP?


I have a not good result using trimmed ICP.


 
---Original---

**Comment by taketwo** [comment]
Unfortunately I've never used this class and can not provide any insights.
