### ISSUE TITLE
Glew undefined reference on arch linux

### ISSUE THREAD

**Issue by tort-dla-psa** [PointCloudLibrary/pcl#3158]
## Your Environment

* Operating System and version: arch linux
* Compiler: gcc version 8.3.0 (GCC)
* PCL Version: release 1.9.1 from AUR

## Context
I'm trying to install pcl from AUR and there's this error:

> /usr/bin/ld: /usr/lib/libvtkRenderingOpenGL2.so.1: undefined reference to `glewInit'
/usr/bin/ld: /usr/lib/libvtkRenderingOpenGL2.so.1: undefined reference to `__glewBlendFuncSeparate'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/pcl_voxel_grid_occlusion_estimation.dir/build.make:304: bin/pcl_voxel_grid_occlusion_estimation] Error 1
make[1]: *** [CMakeFiles/Makefile2:4377: tools/CMakeFiles/pcl_voxel_grid_occlusion_estimation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Also "undefined reference" goes all the way up for every glew procedure. I have glew-git installed. All other software that requires it builds and runs as intended.

**Comment by taketwo** [comment]
So far I don't have any good hypothesis about what can be wrong. A couple of questions to get started:
 * Which VTK version are you using?
 * What's the output of `ldd /usr/lib/libvtkRenderingOpenGL2.so.1 | grep -i glew`? 
 * Where `glew-git` is installed?
 * If possible, post output from `make pcl_voxel_grid_occlusion_estimation VERBOSE=1`

**Comment by taketwo** [comment]
Have you solved the problem?

**Comment by taketwo** [comment]
Closing due to lack of feedback.
