### ISSUE TITLE
%d was deprecated for VTK 8.1 and will be removed in a future version / PointCloudViewer

### ISSUE THREAD

**Issue by aerarslan** [PointCloudLibrary/pcl#3161]
I am using win10 and PCL 1.9.1 for visual studio 2017.

I am trying to run point cloud viewer with kinect v2 but when I run the example, I keep getting 2 different errors in 2 different window. Errors:

```
Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkrenderwindow.cxx, line 1480
vtkRenderWindow::GetPainterDeviceAdapter was deprecated for VTK 8.1 and will be removed in a future version.
```

```
Generic Warning: In c:\vtk-8.1.2\rendering\core\vtkmapper.cxx, line 186
vtkMapper::ImmediateModeRenderingOff was deprecated for VTK 8.1 and will be removed in a future version.

```

Any solution for these?

**Comment by SergioRAgostinho** [comment]
They are warnings, not errors. One quick work around is making use of [GlobalWarningDisplayOff](https://vtk.org/doc/nightly/html/classvtkObject.html#a7e38ded43a1781d5c24125e820631073). The real way to fix it is to update PCL's code to stop making use of those classes. That is not a priority in the current release schedule.

**Comment by taketwo** [comment]
We don't use these classes explicitly. They are used by VTK itself when it's configured with OpenGL1 backend. On Windows we can not switch to OpenGL2 because of some issues. See #2619.
