### ISSUE TITLE
run pcl_kinfu_largeScale_debug.exe -pcd xxx\xxx\xxpcd .There is nothing!!!!!!!

### ISSUE THREAD

**Issue by jane96** [PointCloudLibrary/pcl#3162]
## Your Environment

* Operating System and version:win10
* Compiler:cmake3.6
* PCL Version:1.9.1

## Expected Behavior

``show the point cloud``
## Current Behavior

``there is nothing``
![image](https://user-images.githubusercontent.com/16450829/59491686-ded36280-8eb9-11e9-9580-7b4a9ce0ad73.png)

**Comment by SergioRAgostinho** [comment]
Already replied you on the other issue you raised.
