### ISSUE TITLE
I downloaded pcl.zip from github instead of git clone (network reason), I encountered a problem while compiling

### ISSUE THREAD

**Issue by zhaobingshuai** [PointCloudLibrary/pcl#3164]
## Your Environment
* Operating System and version:Linux mint19.1 based on Ubuntu 18.04
* Compiler:Terminal ,Cmake
* PCL Version:1.7.2

Hey, I downloaded pcl.zip from github instead of git clone (network reason), I encountered a problem while compiling. Can you give me some advice? thank you very much.
[ 74%] Built target pcl_keypoints
[ 74%] Building CXX object outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/outofcore_print.cpp.o
[ 74%] Building CXX object registration/CMakeFiles/pcl_registration.dir/src/correspondence_estimation_normal_shooting.cpp.o
In file included from /home/zbs/package/pcl-1.7.2/registration/src/correspondence_estimation_normal_shooting.cpp:40:0:
/home/zbs/package/pcl-1.7.2/registration/include/pcl/registration/correspondence_estimation_normal_shooting.h: In member function ‘void pcl::registration::CorrespondenceEstimationNormalShooting<PointSource, PointTarget, NormalT, Scalar>::getKSearch() const’:
/home/zbs/package/pcl-1.7.2/registration/include/pcl/registration/correspondence_estimation_normal_shooting.h:184:41: error: return-statement with a value, in function returning 'void' [-fpermissive]
         getKSearch () const { return (k_); }
                                         ^
registration/CMakeFiles/pcl_registration.dir/build.make:88: recipe for target 'registration/CMakeFiles/pcl_registration.dir/src/correspondence_estimation_normal_shooting.cpp.o' failed
make[2]: *** [registration/CMakeFiles/pcl_registration.dir/src/correspondence_estimation_normal_shooting.cpp.o] Error 1
CMakeFiles/Makefile2:1319: recipe for target 'registration/CMakeFiles/pcl_registration.dir/all' failed
make[1]: *** [registration/CMakeFiles/pcl_registration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/zbs/package/pcl-1.7.2/outofcore/include/pcl/outofcore/outofcore_impl.h:48:0,
                 from /home/zbs/package/pcl-1.7.2/outofcore/tools/outofcore_print.cpp:53:
/home/zbs/package/pcl-1.7.2/outofcore/include/pcl/outofcore/impl/octree_base_node.hpp: In instantiation of ‘uint64_t pcl::outofcore::OutofcoreOctreeBaseNode<ContainerT, PointT>::addPointCloud(const Ptr&, bool) [with ContainerT = pcl::outofcore::OutofcoreOctreeDiskContainer<pcl::PointXYZ>; PointT = pcl::PointXYZ; uint64_t = long unsigned int; pcl::PCLPointCloud2::Ptr = boost::shared_ptr<pcl::PCLPointCloud2>]’:
/home/zbs/package/pcl-1.7.2/outofcore/tools/outofcore_print.cpp:309:1:   required from here
/home/zbs/package/pcl-1.7.2/outofcore/include/pcl/outofcore/impl/octree_base_node.hpp:544:29: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
           if ( children_[i] == false )
                ~~~~~~~~~~~~~^~~~~~~~
/home/zbs/package/pcl-1.7.2/outofcore/include/pcl/outofcore/impl/octree_base_node.hpp: In instantiation of ‘uint64_t pcl::outofcore::OutofcoreOctreeBaseNode<ContainerT, PointT>::addPointCloud_and_genLOD(pcl::PCLPointCloud2::Ptr) [with ContainerT = pcl::outofcore::OutofcoreOctreeDiskContainer<pcl::PointXYZ>; PointT = pcl::PointXYZ; uint64_t = long unsigned int; pcl::PCLPointCloud2::Ptr = boost::shared_ptr<pcl::PCLPointCloud2>]’:
/home/zbs/package/pcl-1.7.2/outofcore/tools/outofcore_print.cpp:309:1:   required from here
/home/zbs/package/pcl-1.7.2/outofcore/include/pcl/outofcore/impl/octree_base_node.hpp:799:26: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
         if( children_[i] == false )
             ~~~~~~~~~~~~~^~~~~~~~
outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/build.make:62: recipe for target 'outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/outofcore_print.cpp.o' failed
make[2]: *** [outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/outofcore_print.cpp.o] Error 1
CMakeFiles/Makefile2:1651: recipe for target 'outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/all' failed
make[1]: *** [outofcore/tools/CMakeFiles/pcl_outofcore_print.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by taketwo** [comment]
Is there any specific reason why you decided to download the (very) old version 1.7.2? I'd suggest to try the latest release instead. Or, even better, install PCL using `apt-get`.

**Comment by taketwo** [comment]
Closing due to lack of feedback. Please re-open if needed.
