### ISSUE TITLE
StackOverflow "invalid" in README

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3175]
After the recent update in the README I see the following badges:

![image](https://user-images.githubusercontent.com/1241736/59748138-bad99d80-927a-11e9-9437-d179adcd39d4.png)

I'm not sure how the SO badge is supposed to look, but I guess "invalid" is not the right state. Ping @kunaltyagi.

**Comment by SergioRAgostinho** [comment]
This is an intermittent behavior. It happened to me before but now it is stable. I currently have this on my screen.
![Screen Shot 2019-06-19 at 11 07 19](https://user-images.githubusercontent.com/1709142/59752436-8964d000-9282-11e9-9a47-0962067f5401.png)

**Comment by taketwo** [comment]
Indeed, works for me now.

**Comment by kunaltyagi** [comment]
## Purely my guesswork

As per the docs, the only reason can be SO API response or shields.io API results. Both individually seem unlikely though the combination might explain the result.

SO expects API requests to be [throttled and non-abusive](https://api.stackexchange.com/docs/throttle). I don't think shields.io respects that and as a result gets dropped, thus resulting in the "invalid". As per their [github](https://github.com/badges/shields/blob/master/services/stackexchange/stackexchange-taginfo.service.js#L64), this occurs when the response is a no-show, mangled or 0.

## Future action
I've created a PR to see if this issue can be addressed upstream. If not, I'll remove the badge with a simple image and a link :)
