### ISSUE TITLE
Error to run the code "ensenso_cloud_images_viewer.cpp"

### ISSUE THREAD

**Issue by ZJU-PLP** [PointCloudLibrary/pcl#3196]
## Your Environment

* Operating System and version:Ubuntu16.04
* Compiler:g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 
* PCL Version:1.9.1

## Context

I want to try the code of "ensenso_viewer.cpp". I configured the a minimal project including the necessary libraries (PCL, Boost, VTK, Ensenso SDK, Eigen and Flann) to run the sample using the connected camera.

## Expected Behavior

Displaying a point cloud grabbed from a Ensenso device.
## Current Behavior

**make errors,details:**
 make -j4
[ 50%] Linking CXX executable ensenso_cloud_images_viewer
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibWriteDebugMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ensenso_cloud_images_viewer.cpp:(.text+0x255): undefined reference to `nxLibWriteDebugMessage'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibGetDebugMessages()':
ensenso_cloud_images_viewer.cpp:(.text+0x2aa): undefined reference to `nxLibGetDebugMessages'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibSetDebugThreadName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ensenso_cloud_images_viewer.cpp:(.text+0x3a9): undefined reference to `nxLibSetDebugThreadName'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibInitialize(bool)':
ensenso_cloud_images_viewer.cpp:(.text+0x3f8): undefined reference to `nxLibInitialize'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibFinalize()':
ensenso_cloud_images_viewer.cpp:(.text+0x43c): undefined reference to `nxLibFinalize'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibOpenTcpPort(int, int*)':
ensenso_cloud_images_viewer.cpp:(.text+0x490): undefined reference to `nxLibOpenTcpPort'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `nxLibCloseTcpPort()':
ensenso_cloud_images_viewer.cpp:(.text+0x4d4): undefined reference to `nxLibCloseTcpPort'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `main':
ensenso_cloud_images_viewer.cpp:(.text+0xd75): undefined reference to `pcl::EnsensoGrabber::EnsensoGrabber()'
ensenso_cloud_images_viewer.cpp:(.text+0xda3): undefined reference to `pcl::EnsensoGrabber::openDevice(int)'
ensenso_cloud_images_viewer.cpp:(.text+0xdbf): undefined reference to `pcl::EnsensoGrabber::openTcpPort(int)'
ensenso_cloud_images_viewer.cpp:(.text+0xf21): undefined reference to `pcl::EnsensoGrabber::closeDevice()'
ensenso_cloud_images_viewer.cpp:(.text+0xf38): undefined reference to `pcl::EnsensoGrabber::closeTcpPort()'
CMakeFiles/ensenso_cloud_images_viewer.dir/ensenso_cloud_images_viewer.cpp.o: In function `NxLibException::NxLibException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
ensenso_cloud_images_viewer.cpp:(.text._ZN14NxLibExceptionC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi[_ZN14NxLibExceptionC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi]+0x18a): undefined reference to `nxLibWriteDebugMessage'
collect2: error: ld returned 1 exit status
CMakeFiles/ensenso_cloud_images_viewer.dir/build.make:362: recipe for target 'ensenso_cloud_images_viewer' failed
make[2]: *** [ensenso_cloud_images_viewer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ensenso_cloud_images_viewer.dir/all' failed
make[1]: *** [CMakeFiles/ensenso_cloud_images_viewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Could you mind helping me solve this problem? Thanks a lot!**

Note:all necessary lib is followed by [http://www.pointclouds.org/documentation/tutorials/ensenso_cameras.php]

**Comment by mvieth** [comment]
Sorry that you did not get an earlier answer. It seems like the linking to the Ensenso SDK and to `pcl::EnsensoGrabber` goes wrong. Without seeing your CMakeLists.txt, it is difficult to say why exactly. It could be something wrong in there. Maybe have a look at https://github.com/PointCloudLibrary/pcl/blob/master/tools/CMakeLists.txt and https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/ensenso_cameras/CMakeLists.txt.
I am going to close this issue. If you still have problems with this, feel free to comment/reopen/open a new issue.
