### ISSUE TITLE
tracking has no members in pcl1.8.1

### ISSUE THREAD

**Issue by mujinveil** [PointCloudLibrary/pcl#3197]
i use the pcl tracking lib in version1,8,1,and the code comes from http://pointclouds.org/documentation/tutorials/tracking.php , but when i build it,it said the tracker has no member of setReferenceCloud or somewhat.Can someone help me to solve this issue?

**Comment by mujinveil** [comment]
who can help me?please

**Comment by SergioRAgostinho** [comment]
At first glance the documentation seems to suggest otherwise. `KLDAdaptiveParticleFilterOMPTracker` inherits from `ParticleFilterTracker` and this latter class has the member function you mention even in version 1.8.1.

http://docs.pointclouds.org/1.8.1/classpcl_1_1tracking_1_1_k_l_d_adaptive_particle_filter_o_m_p_tracker.html
(check the public members inherited)

**Comment by jazka** [comment]
Same issue for me, any update?

@SergioRAgostinho I know 'ParticleFilterTracker' has all the related membors, but as below it reports the error from  'Tracker' not 'ParticleFilterTracker', could you help for this? Thanks!

error: ‘class pcl::tracking::Tracker<pcl::PointXYZ, pcl::tracking::ParticleXYZRPY>’ has no member named ‘setMaximumParticleNum’
     tracker->setMaximumParticleNum (1000);

**Comment by yueqili-bella** [comment]
@jazka I have the same error as yours. Did you solve the problem?

**Comment by adityag6994** [comment]
Similar error for getParticles() 
` error: ‘class pcl::tracking::Tracker<pcl::PointXYZ, pcl::tracking::ParticleXYZRPY>’ has no member named ‘getParticles’
   ParticleFilter::PointCloudStatePtr particles = tracker_->getParticles ();`

**Comment by kunaltyagi** [comment]
Which PCL version?

**Comment by adityag6994** [comment]
@kunaltyagi PCL_VERSION_PRETTY : 1.7.2

**Comment by adityag6994** [comment]
So, changing from
`// ParticleFilter::Ptr tracker_;`
to
`boost::shared_ptr<ParticleFilter> tracker_;`
seems to be working. Not really sure why.

**Comment by mvieth** [comment]
@adityag6994 PCL 1.7.2 is a very old version. I would recommend you to update it. The tutorial you linked is for the _lastest_ PCL version (1.12.0).
In PCL 1.7.2, `ParticleFilterTracker` (aka `ParticleFilter` in the tutorial) did not have the member `Ptr` ([this commit](https://github.com/PointCloudLibrary/pcl/commit/f2a519a57a45f24bb03f13d5cf3db536b21be507) added it and also changed the tutorial), so apparently `Ptr` of the parent class `Tracker` is used

**Comment by kunaltyagi** [comment]
Closing the issue since it is quite old and not relevant anymore (but the conversation can continue)
