### ISSUE TITLE
Installation issue on windows 10 through conda

### ISSUE THREAD

**Issue by shamazharikh** [PointCloudLibrary/pcl#3203]
Installation Issue
Installing pcl 1.9 through conda. Installation prompt completes with out any warning or error.
When I attempt to import pcl, it gives me the error "ImportError: Module not found"
I checked in on the modules available in the environment using:
1. help("modules") - Did not find pcl
2. Anaconda navigator - Pcl was indicated as installed

## Your Environment
* Operating System and version: Windows 10
* Compiler: VS2015
* PCL Version: 1.9

**Comment by taketwo** [comment]
This is a bug tracker for PCL library proper, we do not deal with packaging. Please redirect your issue to conda.

Side note: PCL is a C++ library, therefore importing it in Python is expected to fail.
