### ISSUE TITLE
Run time error in incremental ICP example code

### ISSUE THREAD

**Issue by SubMishMar** [PointCloudLibrary/pcl#3210]
I am trying to learn about ICP by running the examples given on pcl's documentation website. Here is the link http://pointclouds.org/documentation/tutorials/pairwise_incremental_registration.php. But it seems visualization isn't working fine.  I get the following error::

```
ERROR: In /build/vtk6-dmAaMa/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x1798f30): No scalar values found for texture input!
```

Here is my system description:
OS: Ubuntu 16.04
PCL: 1.7.2

I will appreciate any help on this issue.

Thanks.

**Comment by kunaltyagi** [comment]
Closing since 16.04 will EOL soon. Issue is also in VTK6 not PCL
