### ISSUE TITLE
How to load and save .ply file containing user-defined info

### ISSUE THREAD

**Issue by yountreeg** [PointCloudLibrary/pcl#3213]
## Your Environment
* Operating System and version: OS X 10.14
* Compiler: CLion 
* PCL Version: 1.9.1

## Context
I want to load  a ply file containing user-defined information, then process the data.Finally I want to save result to a ply file including user-defined information.

If a ply file only contains points and faces, I should use `PLYReader`, `PLYWriter` and `PolygonMesh`. But when a ply file contains user-defined information, i don't know how to do.  

For example, a ply file containing edge information:
```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 8
property float x
property float y
property float z
element face 7
property list uchar int vertex_index
element edge 5
property int vertex1
property int vertex2
property uchar red
property uchar green
property uchar blue
end_header
0 0 0
0 0 1
0 1 1
0 1 0
1 0 0
1 0 1
1 1 1
1 1 0
3 0 1 2
3 0 2 3
4 7 6 5 4
4 0 4 5 1
4 1 5 6 2
4 2 6 7 3
4 3 7 4 0
0 1 255 255 255
1 2 255 255 255
2 3 255 255 255
3 0 255 255 255
2 0 255 255 255
```
Please give me some suggestions, thank you very much.

**Comment by taketwo** [comment]
PCL supports only vertices and faces, so it is not the right tool for manipulation of complex PLY files.

**Comment by yountreeg** [comment]
Okay, I know, thank you for your reply.
