### ISSUE TITLE
Can't build PCL IO Ensenso

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#3215]
## Your Environment

* Operating System and version: Windows 10
* Compiler: VS2019
* PCL Version: master

## Context

Can't build IO ensenso

## Expected Behavior

Compiled project

## Current Behavior

![image](https://user-images.githubusercontent.com/1165340/60840588-25259400-a1d0-11e9-9dc4-543de264f57c.png)

Error about typedef vs using and returning of functions.

## Code to Reproduce

`

     // Define callback signature typedefs
      using sig_cb_ensenso_point_cloud = void() (const pcl::PointCloud<pcl::PointXYZ>::Ptr &);

      using sig_cb_ensenso_images void() (const boost::shared_ptr<PairOfImages> &);

      using sig_cb_ensenso_point_cloud_images = void()
	    (const pcl::PointCloud<pcl::PointXYZ>::Ptr &, const boost::shared_ptr<PairOfImages> &);
`

## Possible Solution

Revert to:
`

      // Define callback signature typedefs
      typedef void(sig_cb_ensenso_point_cloud)(
          const pcl::PointCloud<pcl::PointXYZ>::Ptr&);

      typedef void(sig_cb_ensenso_images)(const boost::shared_ptr<PairOfImages>&);

      typedef void(sig_cb_ensenso_point_cloud_images)(
          const pcl::PointCloud<pcl::PointXYZ>::Ptr&,
          const boost::shared_ptr<PairOfImages>&);
`

**Comment by SergioRAgostinho** [comment]
Can you try instead this change
```cpp
// Define callback signature typedefs
using sig_cb_ensenso_point_cloud = void (const pcl::PointCloud<pcl::PointXYZ>::Ptr&);

using sig_cb_ensenso_images = void (const boost::shared_ptr<PairOfImages>&);

using sig_cb_ensenso_point_cloud_images = void (const pcl::PointCloud<pcl::PointXYZ>::Ptr&, const boost::shared_ptr<PairOfImages>&);
```

These look like simple syntax errors.

**Comment by SergioRAgostinho** [comment]
@taketwo is there anything blocking us from pre installing the ensenso 3rd party libs in our docker image? If not I would add it and start building this grabber as well alongside the corresponding tutorial.

**Comment by taketwo** [comment]
Shouldn't be a problem. Would you mind creating a ticket for me? I'll try to do on Friday or weekend.

**Comment by larshg** [comment]
@SergioRAgostinho I did try that yesterday, but VS still showed errors, but just tried it again to today to verify and it compiles fine. So the missing = should do it 👍
