### ISSUE TITLE
Impossible to link wih moment_of_inertia_estimation and pcl::PointXYZRGBNormal

### ISSUE THREAD

**Issue by FlowzZz** [PointCloudLibrary/pcl#3219]
## Your Environment

* Operating System and version: Win7 64bit
* Compiler: VS2019
* PCL Version: 1.9.1-3 (got with vcpkg)

## Context

I got linkage errors when I try to compile/link a code using MomentOfInertiaEstimation. It works correctly with pcl::PointXYZ (no errors).

Best regards,
## Expected Behavior
Successful linkage.

## Current Behavior

Errors got:
error LNK2001: unresolved external symbol "public: __cdecl pcl::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>(void)" (??0?$MomentOfInertiaEstimation@UPointXYZRGBNormal@pcl@@@pcl@@QEAA@XZ)
error LNK2001: unresolved external symbol "public: virtual __cdecl pcl::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>::~MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>(void)" (??1?$MomentOfInertiaEstimation@UPointXYZRGBNormal@pcl@@@pcl@@UEAA@XZ)
error LNK2001: unresolved external symbol "public: virtual void __cdecl pcl::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>::setInputCloud(class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZRGBNormal> const > const &)" (?setInputCloud@?$MomentOfInertiaEstimation@UPointXYZRGBNormal@pcl@@@pcl@@UEAAXAEBV?$shared_ptr@$$CBV?$PointCloud@UPointXYZRGBNormal@pcl@@@pcl@@@boost@@@Z)
error LNK2001: unresolved external symbol "public: void __cdecl pcl::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>::compute(void)" (?compute@?$MomentOfInertiaEstimation@UPointXYZRGBNormal@pcl@@@pcl@@QEAAXXZ)
error LNK2001: unresolved external symbol "public: bool __cdecl pcl::MomentOfInertiaEstimation<struct pcl::PointXYZRGBNormal>::getAABB(struct pcl::PointXYZRGBNormal &,struct pcl::PointXYZRGBNormal &)const " (?getAABB@?$MomentOfInertiaEstimation@UPointXYZRGBNormal@pcl@@@pcl@@QEBA_NAEAUPointXYZRGBNormal@2@0@Z)

## Code to Reproduce

    pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr AABB1(new pcl::PointCloud<pcl::PointXYZRGBNormal>);
    pcl::PointXYZRGBNormal min_point_AABB;
    pcl::PointXYZRGBNormal max_point_AABB;

    pcl::MomentOfInertiaEstimation <pcl::PointXYZRGBNormal> feature_extractor;
    feature_extractor.setInputCloud(AABB1);
    feature_extractor.compute();
    feature_extractor.getAABB(min_point_AABB, max_point_AABB);

**Comment by SergioRAgostinho** [comment]
Can you try defining 
```cpp
#define PCL_NO_PRECOMPILE
```

before including any PCL header?

**Comment by FlowzZz** [comment]
Thank you. It seems to work.

**Comment by SergioRAgostinho** [comment]
PCL precompiles  a couple of types to speed up compilation in downstream projects, like the one you're working on. `pcl::MomentOfInertiaEstimation <pcl::PointXYZRGBNormal>` was not one of those types.

Anyway, good luck with your project.
