### ISSUE TITLE
IntegralImageNormalEstimation get a few normal vector

### ISSUE THREAD

**Issue by chenshida** [PointCloudLibrary/pcl#3228]
## My Environment
* Operating System and version: Ubuntu 16.04
* Compiler: gcc 5.4.0
* PCL Version: 1.8

## Context
I`m useing IntegralImageNormalEstimation to compute an organized pointcloud normal vector, but after it running, the normal vector is tow few in the visualization, it show like this.

![normal_vector](https://user-images.githubusercontent.com/26617742/61261684-27ca4f80-a7b5-11e9-917c-9623f7bf3db3.png)

the green is origin point cloud data, and the white is normal vector. as is shown, the normal vector is loss in many where.

## Expected Behavior
In my expected, the normal vector will compute in everywhere, and I will use the normal vector in 
EDGELABEL_HIGH_CURVATURE detect, which use OrganizedEdgeFromNormals.But it can`t find EDGELABEL_HIGH_CURVATURE,  does is effected by prestep of normal vector estimate.

## Code to Reproduce
my normal estimate code is like this
```
   pcl::PointCloud<pcl::Normal>::Ptr normal(new pcl::PointCloud<pcl::Normal>);
    pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
    ne.setNormalEstimationMethod(ne.COVARIANCE_MATRIX); 
    ne.setNormalSmoothingSize(smooth_size);
    ne.setBorderPolicy(ne.BORDER_POLICY_MIRROR);
    ne.setInputCloud(cloud_xyz);
    ne.compute(*normal);
```

Could anyone give me an idea how to solve this problem?
thanks!

**Comment by dogod621** [comment]
ne.setRadiusSearch(*)

if your point cloud is sparser than your SearchRadius...
it cannot find enough neighbors to estimate normal vector

**Comment by chenshida** [comment]
I have try several different value for ne.setRadiusSearch(*), but it take a same result. it seems that this method needn`d set this param. and I try have setKSearch() , it also get the same result.

**Comment by dogod621** [comment]
What is your SearchMethod?
ne.setSearchMethod(*)?

**Comment by dogod621** [comment]
It "need"  setSearchMethod with setKSearch or setRadiusSearch to perform KNN search.
It need to find correct local neighbor point  first, and than estimate normal vector of the local area.

**Comment by chenshida** [comment]
I use IntegralImageNormalEstimation, pcl sample code has not set  SearchMethod, so I haven`t set this param. here is my all config for normal estimate.
```
pcl::PointCloud<pcl::Normal>::Ptr normal(new pcl::PointCloud<pcl::Normal>);
    pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
    ne.setNormalEstimationMethod(ne.COVARIANCE_MATRIX); 
    ne.setNormalSmoothingSize(smooth_size);
    ne.setBorderPolicy(ne.BORDER_POLICY_MIRROR);
    ne.setInputCloud(cloud_xyz);
    ne.compute(*normal);
```

**Comment by chenshida** [comment]
The article tell me  integral image normal estimate needn`t set neighbor points because the point cloud is organized.

**Comment by dogod621** [comment]
sorry I did not saw IntegralImageNormalEstimation....

**Comment by chenshida** [comment]
It`s ok , already thank you .

**Comment by dogod621** [comment]
Does these missing normal vectors become NAN?

http://www.pcl-users.org/IntegralImageNormalEstimation-with-NaN-points-problem-td4030119.html

**Comment by chenshida** [comment]
It may be this problem, my point cloud data just has 33% valid data.

**Comment by mvieth** [comment]
It sounds like the question has been answered, otherwise feel free to open a new issue

**Comment by ynma-hanvo** [comment]
> It may be this problem, my point cloud data just has 33% valid data.

hi,  did you find the result. even though the point cloud is sparse,  what i expected is the number of normals equal the number of valid points,  but i got quite fewer normals .
