### ISSUE TITLE
Sample PCL program build error in Visual Studio 2019

### ISSUE THREAD

**Issue by Newbieeeeeeee** [PointCloudLibrary/pcl#3241]
I have encountered several errors regarding the low_level_io.h file after building a sample PCL code in Visual Studio 2019. The error states that '_open' , '_close' , '_lseek' , '_read' , '_write' , and '_chsize' are not members of "global namespace".

## Your Environment
Visual Studio 2019
Operating System and version: Windows 10
Compiler: MSVC 
PCL Version: 1.9.1

## Context
I wanted to try visualizing point cloud data in Visual Studio using PCL. But first I tested a sample visualization program from PCL.

## Expected Behavior
Program should compile just fine since it came from PCL website.

## Current Behavior
The program gives me this error:
'_open': is not a member of '`global namespace'' and '_open': identifier not found
The error is the same with '_close', '_lseek', '_read', '_write', and '_chsize'.

## Code to Reproduce
This is the program I tried to build http://pointclouds.org/documentation/tutorials/pcl_visualizer.php#pcl-visualizer

**Comment by dogod621** [comment]
I build the sample with same environment without any problem...

Visual Studio 2019
Operating System and version: Windows 10
Compiler: MSVC
PCL Version: 1.9.1

Did you generate your vs2019 project via CMake?

![image](https://user-images.githubusercontent.com/6807005/61350116-0b074800-a899-11e9-8d42-36c9132e8330.png)

**Comment by Newbieeeeeeee** [comment]
Nope. I built it in VS2019. The error I'm getting is mainly caused by low_level_io.h file.

**Comment by dogod621** [comment]
You need add PCL pre-define definitions,

if you use CMake, it will set these definitions via 
```
add_definitions(${PCL_DEFINITIONS})
```

you will not want to set these definitions by your self in vs project....
so, use just use CMake~

![test](https://user-images.githubusercontent.com/6807005/61351807-4fe1ad80-a89e-11e9-8c82-42fbaac53a18.jpg)

**Comment by Newbieeeeeeee** [comment]
Okay, I will try to use CMake though I am not familiar in using it. Thank you very much for your response.

**Comment by dogod621** [comment]
Just use the CMkaeList.txt provided by the tutorial,
and use CMkae to generate your vs2019 project,
and compile the code via visual studio as same as you did.
(The only difference is CMake set those definitions, link librarys, include dirs... etc for you)

```
cmake_minimum_required(VERSION 2.6 FATAL_ERROR)

project(pcl_visualizer_viewports)

find_package(PCL 1.2 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (pcl_visualizer_demo pcl_visualizer_demo.cpp)
target_link_libraries (pcl_visualizer_demo ${PCL_LIBRARIES})
```

**Comment by Newbieeeeeeee** [comment]
Do you have a step by step procedure that I can follow in order to build the project using CMake? That would be very helpful.

**Comment by dogod621** [comment]
You already successfully compile the code...
It says you should set "Options"....
just type "pcl_visualizer_demo.exe -s" to rum simplest example....

CMake is a very very common tool to build up C project...
I thing google CMake tutorial is more helpful....

**Comment by Newbieeeeeeee** [comment]
Okay. So where exactly do I type "pcl_visualizer_demo.exe -s"? Because when I run the program the CMD window pops up and then if I press any key it closes. I'm sorry, I'm really not familiar with CMake. Thank you for all of your help.

**Comment by dogod621** [comment]
https://www.lifewire.com/how-to-open-command-prompt-2618089

**Comment by Newbieeeeeeee** [comment]
HAHAHAHA. Okay, I get what you mean. I'm so stupid. I was finally able to run it.
![image](https://user-images.githubusercontent.com/52987729/61360448-0b134200-a8b1-11e9-9bab-f53627224da6.png)

Thank you so much for your help.

**Comment by dogod621** [comment]
I really think you should learn and use CMake,
and use CMake to build PCL examples/project just like tutorial says,
or your try-error behavior will just make yourself painful....

**Comment by Newbieeeeeeee** [comment]
Okay. Thank you for the advice. It's just that it's my first time using CMake.
