### ISSUE TITLE
Update KdTreeFlann with flann 1.8 functions index::addPoints() index::removePoint() index::save()

### ISSUE THREAD

**Issue by uxhub** [PointCloudLibrary/pcl#3244]
Hi all,

Like I named the issue, I just wanted to use the flann functions index::addPoints() index::addRemovePoint() index::save() by using pcl::KdTreeFLANN.

I know what updating KdTrees involves, but is it the reason why PCL doesn't allow native flann features ?

I could suggest a pull request about this if no objections are raised. Any information will help !

Regards,

**Comment by kunaltyagi** [comment]
PR are welcome.

> is it the reason why PCL doesn't allow native flann features

People didn't think that was needed. If you feel it's a good thing to have, please create a PR (if it's not too huge) and we can have a discussion if the change is too intrusive.
