### ISSUE TITLE
Add Repology badge to README.md

### ISSUE THREAD

**Issue by luzpaz** [PointCloudLibrary/pcl#3247]
Repology shows what repositories a package is available in. For space purposes the small badge is appropriate here. Example:
[![Packaging status](https://repology.org/badge/tiny-repos/pcl-pointclouds.svg)](https://repology.org/project/pcl-pointclouds/badges)

But in other contexts the full badge is more informative. Example:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/pcl-pointclouds.svg?header=pcl-pointclouds)](https://repology.org/project/pcl-pointclouds/versions)

**Comment by SergioRAgostinho** [comment]
:o Super Cool. The first badge is not very useful, but the second is eye/functionality candy. I would be up to try to integrate in our README.md somehow. Opinions @taketwo, @kunaltyagi ?

**Comment by luzpaz** [comment]
you can put it in [collapsible markdown](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f)
