### ISSUE TITLE
Build error with VTK 8.2.0

### ISSUE THREAD

**Issue by OleB** [PointCloudLibrary/pcl#3274]
## Environment

* Windows 10 Pro 1809
* MSBuild 2019
* PCL 1.9+ (cloned from master)

## Context

It seems like CMake can't find all header files, specifically those located at VTK-8.2.0/Interaction/Image.  

## Possible Solution

Adding ``vtkInteractionImage`` to ``PCL_VTK_COMPONENTS`` in ``pcl/CMakeLists.txt`` seems to fix the problem.

**Comment by UnaNancyOwen** [comment]
Can you provide more details of this problem?

**Comment by OleB** [comment]
@UnaNancyOwen The problem occurred when I tried to compile pcl from source using CMake 3.15.0 and MSBuild 2019. The compiler errors indicated that some header files were missing. By editing the CMakeLists file, as mentioned above, I was able to fix the issue and compile the library successfully.

**Comment by UnaNancyOwen** [comment]
Which project occurred that error? (pcl_***)
If possible, Please tell us that error message.

**Comment by kunaltyagi** [comment]
Closing due to no reply from author for 9 months.
