### ISSUE TITLE
Can someone upload pcl-1.9.1 to Ubuntu Packages

### ISSUE THREAD

**Issue by akouri-doordash** [PointCloudLibrary/pcl#3283]
Currentl apt-get installs 1.8.1 on Ubuntu 18.04. I'd love to install this with `apt install libpcl-dev` rather than having to build from source every time.

**Comment by SergioRAgostinho** [comment]
The packages available on aptitude are not maintained by use. Have a look at https://wiki.ubuntu.com/StableReleaseUpdates . In summary, what that is saying is that they will only release security updates. Normal updates (from 1.8.1 to 1.9.1) don't happen on LTS releases. Once the package and their respective versions are selected, these will  not change. Ultimately this means that if you want to install the most current version of pcl in 18.04, you'll need to get it from a custom [ppa](https://askubuntu.com/questions/4983/what-are-ppas-and-how-do-i-use-them).
