### ISSUE TITLE
PCL_ADD_POINT4D causes warning in Visual Studio

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#3292]
## Your Environment
* Operating System and version: Windows 10
* Compiler: Visual Studio 2017
* PCL Version: 1.9.1

I created a custom point type, 

```
struct PointXYZS
{
  PCL_ADD_POINT4D;
  float saliency;
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW 
} EIGEN_ALIGN16;
```

Everything was good on Ubuntu but when I tried to compile this on Windows, I got the below warnings:

```
C4201 nonstandard extension used: nameless struct/union
```

What is a good way to resolve this?

**Comment by dogod621** [comment]
This is your compiler issue...
not PCL issue...

any library can cause same problem, 
for example GLM library:
https://github.com/g-truc/glm/issues/729

**Comment by taketwo** [comment]
This was brought up already in #3062.

I don't have a good solution for this. We need to use nameless structures, otherwise to access `x` field of a point the user will need to write something like `point.xyz.x` which is a bit awkward (and needless to say, will break tons of existing code).

**Comment by jasjuang** [comment]
@taketwo what you said makes sense, I will manually disable the warning by adding `/wd4201`. I am surprised this is part of the default warnings in `/W4` instead of additional warnings.
