### ISSUE TITLE
data type mismatch while creating pointcloud of type XYZRGB in pcl

### ISSUE THREAD

**Issue by shomedas** [PointCloudLibrary/pcl#3293]
summary:
For pcl::Pointcloud<pcl::pointXYZRGB> the data type should be 
TYPE F F F F. However after creating cloud i get data type for rgb as integer.

I follow the instruction at [pcl::PointXYZRGB Struct Reference](http://docs.pointclouds.org/1.3.1/structpcl_1_1_point_x_y_z_r_g_b.html) to pack rgb colors to float before storing in pointcloud
which says

 // pack r/g/b into rgb
 uint8_t r = 255, g = 0, b = 0;    // Example: Red color
 uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);
 p.rgb = *reinterpret_cast<float*>(&rgb);

After creating the cloud i check the data field. It is 
TYPE F F F **U**
Also the individual rows of the points have integer format instaed of float for the rgb field

# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F **U**
COUNT 1 1 1 1
WIDTH 1
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1
DATA ascii
1 0.5 0.1 **1266614272**

## Your Environment
* Operating System and version: ubuntu 16.04
* Compiler: gcc 5.4
* PCL Version: 1.8.1

## Context
I am trying to create a pointcloud of type XYZRGB from a depth and a rgb image using RGBD sensor parameters. I need the pcd to be read in a third party tool which uses pcl::pointXYZRGB and expects the data type to be of the format  TYPE F F F **F**. If I give data of type TYPE F F F **U**, the cloud is rendered black in color.

## Expected Behavior
The rgb field in the cloud header and data type should be of type float

## Code to Reproduce
```
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/common/io.h>
#include <pcl/pcl_config.h>

int
main (int argc, char** argv)
{

  pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_XYZRGB(new pcl::PointCloud<pcl::PointXYZRGB>);

  pcl::PointXYZRGB pt;

  pt.x = 1.0;
  pt.y = 0.5;
  pt.z = 0.1;

 uint8_t r = 255, g = 0, b = 0;    // Example: Red color
 uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);
 pt.rgb = *reinterpret_cast<float*>(&rgb);

 cloud_XYZRGB->push_back(pt);

  pcl::io::savePCDFileASCII("XYZRGB_cloud.pcd",*cloud_XYZRGB);

std::cout << PCL_VERSION << std::endl; // gives 1.8.1 for me

  return (0);
}
```

**Comment by dogod621** [comment]
p.rgba = rgb;

**Comment by shomedas** [comment]
I need to use the cloud type of pcl::PointXYZRGB. If I append a point of type pcl::PointXYZRGBA to cloud of type pcl::PointXYZRGB  I get 

error: no matching function for call to ‘pcl::PointCloud<pcl::PointXYZRGB>::push_back(pcl::PointXYZRGBA&)

**Comment by dogod621** [comment]
```C++
 struct EIGEN_ALIGN16 _PointXYZRGB
  {
    PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
    PCL_ADD_RGB;
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };

#define PCL_ADD_RGB \
  PCL_ADD_UNION_RGB \
  PCL_ADD_EIGEN_MAPS_RGB

#define PCL_ADD_UNION_RGB \
  union \
  { \
    union \
    { \
      struct \
      { \
        uint8_t b; \
        uint8_t g; \
        uint8_t r; \
        uint8_t a; \
      }; \
      float rgb; \
    }; \
    uint32_t rgba; \
  };
```

No matter RGBA or RGB... they all use same sturcture

**Comment by dogod621** [comment]
by the way...
the code indeed register rgb field as float... so weird

```C++
POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::_PointXYZRGB,
    (float, x, x)
    (float, y, y)
    (float, z, z)
    (float, rgb, rgb)
)
POINT_CLOUD_REGISTER_POINT_WRAPPER(pcl::PointXYZRGB, pcl::_PointXYZRGB)

```

**Comment by shomedas** [comment]
Its definitely a bug then. Can you suggest any workaround?

**Comment by dogod621** [comment]
The structure of PointXYZRGBA and PointXYZRGB are exactly same...

```C++
struct EIGEN_ALIGN16 _PointXYZRGBA
  {
    PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
    PCL_ADD_RGB;
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };

 struct EIGEN_ALIGN16 _PointXYZRGB
  {
    PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
    PCL_ADD_RGB;
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };
```

So... use  PointXYZRGBA,
when you need PointXYZRGB, just do some type convert trick...

```C++
pcl::PointXYZRGBA b;
pcl::PointCloud<pcl::PointXYZRGB> a;
...
a.push_back(*(pcl::PointXYZRGB*)(&b))
```

**Comment by shomedas** [comment]
I still get data type of uint32

```
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/common/io.h>

#include <pcl/pcl_config.h>


int
main (int argc, char** argv)
{
  pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_XYZRGB(new pcl::PointCloud<pcl::PointXYZRGB>);

  pcl::PointXYZRGBA pt;
  pt.x = 1.0;
  pt.y = 0.5;
  pt.z = 0.1;

 uint8_t r = 255, g = 0, b = 0;    // Example: Red color
 uint32_t rgb = ((uint32_t)r << 16 | (uint32_t)g << 8 | (uint32_t)b);
  pt.rgba = rgb;

 cloud_XYZRGB->push_back(*(pcl::PointXYZRGB*)(&pt));

  pcl::io::savePCDFileASCII("XYZRGB_cloud.pcd",*cloud_XYZRGB);

  return (0);
}
```
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z **rgb**
SIZE 4 4 4 4
TYPE F F F **U**
COUNT 1 1 1 1
WIDTH 1
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1
DATA ascii
1 0.5 0.1 16711680
```

**Comment by dogod621** [comment]
Naaa...
I means  always use  PointXYZRGBA...
and use PointXYZRGBA to save to pcd file too...

because that seems the io function fuck up rgb field...

and since PointXYZRGBA and PointXYZRGB are exactly same ...
soe it will not cause any problem...

**Comment by dogod621** [comment]
By the way ...

the structure order is "B G R A"... 8 bit for each channel 
not "R G B"...
so your packing is not correct... you invert the order and skip alpha channel 

```C++
#define PCL_ADD_UNION_RGB \
 union \
 { \
   union \
   { \
     struct \
     { \
       uint8_t b; \
       uint8_t g; \
       uint8_t r; \
       uint8_t a; \
     }; \
     float rgb; \
   }; \
   uint32_t rgba; \
 };
```

**Comment by dogod621** [comment]
Ohhhh...
I understand...
The IO function must write rgb field as uint...
that is not a bug...

because PCD file can use text mode to write the data..
and when you write rgb as float...
the Floating-Point Precision issue will fuck up R G B data,
since they must exactly same for each bit...

**### that is not a bug...**

**Comment by shomedas** [comment]
for cloud of type pcl::pointXYZRGB the documentation says that the data type for RGB is float.
it is mentioned at [pcl point types](http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php)

**Comment by dogod621** [comment]
NO.
NO.
NOOOO
The stucture is 
8 bit 4 channel data...
B G R A

```
#define PCL_ADD_UNION_RGB \
 union \
 { \
   union \
   { \
     struct \
     { \
       uint8_t b; \
       uint8_t g; \
       uint8_t r; \
       uint8_t a; \
     }; \
     float rgb; \
   }; \
   uint32_t rgba; \
 };
```

PCL pack them into a single rgb float  is just convenient for you the pass the rgb value,
EX:
```C++
a.rgb = b.rgb;
```

so the float data must keep exactly same bit,
or the B G R A data will be fucked up
and that is impossible when you write a float to text file

**Comment by dogod621** [comment]
Do you understand what I am saying.... ORZ...

**Comment by dogod621** [comment]
SO...
Just fix the error rgb packing of your code...
and current PCL IO is correct.
NOT A BUG...

**Comment by dogod621** [comment]
And the document is SOOOOO out date...
It is a issue https://github.com/PointCloudLibrary/pcl/issues/2864

SO, just read the source code...
not always trust document

**Comment by shomedas** [comment]
i guess i am being dumb here not able to understand what you want me to. 
basically i need to create a pcd of the same format as in [open3d sample pcd](https://github.com/intel-isl/Open3D/tree/master/examples/TestData/ICP). I need to use it along with their example code.

This pcd is of binary format with header

# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb normal_x normal_y normal_z curvature
SIZE 4 4 4 4 4 4 4 4
TYPE F F F F F F F F
COUNT 1 1 1 1 1 1 1 1
WIDTH 198835
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 198835
DATA binary

I am able to get the correct data type for x,y,z, normals_x, normals_y, normals_z, curvature but i am not able to set the rgb  as float type. My question is how to create the same type of pcd

I am attaching the open3d file herewith. I need to create file of this type with the same datatype.


[cloud_bin_0.pcd.zip](https://github.com/PointCloudLibrary/pcl/files/3502765/cloud_bin_0.pcd.zip)

**Comment by dogod621** [comment]
DATA binary

**Comment by dogod621** [comment]
int | pcl::io::savePCDFile (const std::string &file_name, const pcl::PCLPointCloud2 &cloud, const Eigen::Vector4f &origin=Eigen::Vector4f::Zero(), const Eigen::Quaternionf &orientation=Eigen::Quaternionf::Identity(), const bool binary_mode=false)


set binary_mode true

**Comment by dogod621** [comment]
You save PCD as DATA ascii(text), 
so he cant save rgb as float.... tou "CAN NOT" save pack RGB float as text...
but OK for binary PCD file 


VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 1
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1
DATA ascii
1 0.5 0.1 1266614272

**Comment by dogod621** [comment]
Why you don't understand... ORZ

for example:

pcl::PointXYZRGB a;
a.r = 253
a.g = 123
a.b = 102

than a.rgb = 0.2445271147511456746547 ( I randomly typed, just for example)

if you save DATA ascii as text, it will become 0.2445271 (maybe)

than, whatr will happend to a.r,  a.g, a.b
a.r = ???
a.g = ???
a.b = ???

**Comment by dogod621** [comment]
by the way,
why are you so insist on make pcl save rgb as float?
the pcl io reader can correctly handle the data...
It is not a bug, so there wont be any error when PCL save rgb  as uint32_t,

you do not need to care how PCL save pointcloud to PCD...
It will correctly read them back anyway...

**Comment by shomedas** [comment]
I am going to use it with a third party software called [open3d.](http://www.open3d.org/) They do not use pcl io reader to read the files.  Thats why i need the data type to be correct.

**Comment by dogod621** [comment]
Here is the code, 
PCL io write rgb uint32_t in purpose 

```C++
 case pcl::PCLPointField::FLOAT32:
          {
            /*
             * Despite the float type, store the rgb field as uint32
             * because several fully opaque color values are mapped to
             * nan.
             */
            if ("rgb" == fields[d].name)
            {
              uint32_t value;
              memcpy (&value, reinterpret_cast<const char*> (&cloud.points[i]) + fields[d].offset + c * sizeof (float), sizeof (float));
              if (pcl_isnan (value))
                stream << "nan";
              else
                stream << boost::numeric_cast<uint32_t>(value);
              break;
            }
            else
            {
              float value;
              memcpy (&value, reinterpret_cast<const char*> (&cloud.points[i]) + fields[d].offset + c * sizeof (float), sizeof (float));
              if (pcl_isnan (value))
                stream << "nan";
              else
                stream << boost::numeric_cast<float>(value);
            }
            break;
          }
```

**Comment by dogod621** [comment]
By the way...
PCD file format is invented by PCL,
so open3d may use pcl library too....

**Comment by taketwo** [comment]
Hi, I'm afraid our documentation is hopelessly outdated. Indeed, `RGB` and `RGBA` are the same and can be viewed either as `float`, as `uint32_t`, or a set of `uint8_t` fields. The former is for compatibility and should not be used. For writing PCD files in ASCII format we switched to using `uint32_t` because writing and then reading in float format lead to corruption of colors due to floating-point precision issues.
