### ISSUE TITLE
How to integrate PCL Viewer in Qt

### ISSUE THREAD

**Issue by Yanndou** [PointCloudLibrary/pcl#3298]
## Your Environment

* Operating System and version: Windows 10
* Compiler: CMAKE 3.15.1
* PCL Version: 1.9.1

## Context

Hello, when I include pcl_visualizer.h I get this error: 

"Error C2039'ImmediateModeRenderingOff': is not a member of'vtkMapper' MitkPCLmodule C:\Program Files\PCL 1.9.1\include\pcl-1.9\pcl\pcl\visualization\impl\pcl_visualizer.hpp"	
After verification, ImmediateModeRenderingOff is a member of vtkMapper.

Do you have any idea how to solve the problem?

**Comment by IkerJau** [comment]
Hello, I get the same error as @Yanndou:

![Captura](https://user-images.githubusercontent.com/50915851/64423966-1eb87900-d0a8-11e9-864c-1d9e7416a431.PNG)


### Environment

- Operating system: Windows 7 64 bits
- MSVC 2015 64 bits
- CMAKE 1.35.1
- PCL 1.9.1
- Eigen 3.3.7
- Boost 1.68.0
- FLANN 1.9.1
- VTK 8.2.0
- QT 5.11.2

**Comment by IkerJau** [comment]
> ## Your Environment
> * Operating System and version: Windows 10
> * Compiler: CMAKE 3.15.1
> * PCL Version: 1.9.1
> 
> ## Context
> Hello, when I include pcl_visualizer.h I get this error:
> 
> "Error C2039'ImmediateModeRenderingOff': is not a member of'vtkMapper' MitkPCLmodule C:\Program Files\PCL 1.9.1\include\pcl-1.9\pcl\pcl\visualization\impl\pcl_visualizer.hpp"
> After verification, ImmediateModeRenderingOff is a member of vtkMapper.
> 
> Do you have any idea how to solve the problem?
> 
> ## Expected Behavior
> ## Current Behavior
> ## Code to Reproduce
> ## Possible Solution

I solved the problem by changing the OpenGL version used by VTK as rendering backend. On the last line of "pcl_config.h", modify the code from "#define VTK_RENDERING_BACKEND_OPENGL_VERSION 1" to "#define VTK_RENDERING_BACKEND_OPENGL_VERSION **2**".
Source: https://blog.csdn.net/lm111111/article/details/98495467

Now, I don't get any compilation errors, but there are a bunch of Semantic Issues. If I run my app, it crashes.
![Captura](https://user-images.githubusercontent.com/50915851/64509840-e94aa000-d2e0-11e9-9c42-221a06a2a048.PNG)

**Comment by larshg** [comment]
A bit late, but example can be seen here:
https://pcl.readthedocs.io/projects/tutorials/en/master/qt_visualizer.html#qt-visualizer
