### ISSUE TITLE
Missing Attributes in the PCD files

### ISSUE THREAD

**Issue by Dinatorehanova** [PointCloudLibrary/pcl#3303]
Hi,
I am generating pcd file from my ros bag with the bag to pcd command.However, When I am opening the pcd file in the cloud compare I am missing some attributes.My pcd file file contains data for the (range,timestamp, reflectivity, ring, noise, intensity, x,y,z). But I am getting a constant value of 0 for the (timestamp, range,ring, noise,reflectivity).

This is the command output for"head"
![image](https://user-images.githubusercontent.com/51459647/63635148-796bc280-c61c-11e9-859c-e73c406c03cb.png)

When I am generating pcd files from my bag file it says it has value for (x,y,z,range, reflectivity, intensity, ring, noise)
![68728830_2624551044229865_8523050621077553152_n-min](https://user-images.githubusercontent.com/51459647/63635164-a61fda00-c61c-11e9-9f0b-fcf96f31ee6c.jpg)

This is my pcd file
https://drive.google.com/file/d/1ZI9hUIjoYdnPh_crXvKg-fJcRqrTSzXJ/view?usp=sharing

Getting a constant value of 0
![69269995_609565076236944_4736061390781939712_n](https://user-images.githubusercontent.com/51459647/63635171-addf7e80-c61c-11e9-8407-f96c7e4372f2.jpg)

Any help will be very appreciated.
Thanks

**Comment by mvieth** [comment]
I can't think of any reason why this might happen, and the google drive link does not work any more. Without any data to reproduce this, it is impossible to find out what goes wrong. I am going to close this issue. If you @Dinatorehanova or anyone else with the same problem can post a new link with data to reproduce this, we can see further.
Also for reference: the same issue in perception_pcl: https://github.com/ros-perception/perception_pcl/issues/245
