### ISSUE TITLE
Value evaluated in TfQuadraticXYZComparison

### ISSUE THREAD

**Issue by FlowzZz** [PointCloudLibrary/pcl#3304]
Looking at the code of conditional_removal.hpp, the formula use to evaluate TfQuadraticXYZComparison seems to be not equal to the formula written in the documentation (value substrated by 3, is there a reason?).
## Your Environment

* Operating System and version: Windows 10 64bits
* Compiler: VS2019
* PCL Version: 1.9.1

## Expected Behavior

  float myVal = static_cast<float>(2.0f * tf_comp_vect_.transpose () * pointAffine) + static_cast<float>(pointAffine.transpose () * tf_comp_matr_ * pointAffine) + comp_scalar_;

## Current Behavior

The value evaluated is substrated by 3.
  float myVal = static_cast<float>(2.0f * tf_comp_vect_.transpose () * pointAffine) + static_cast<float>(pointAffine.transpose () * tf_comp_matr_ * pointAffine) + comp_scalar_ - 3.0f;

**Comment by taketwo** [comment]
Disclaimer: I'm not familiar with this code. Could this be related to the fact that the documentation talks about non-homogeneous vectors/matrices, whereas the actual code uses homogeneous vectors?

**Comment by kunaltyagi** [comment]
That's indeed the cause.
