### ISSUE TITLE
pcl::console::print_highlight should not emit color codes on non-interactive terminals

### ISSUE THREAD

**Issue by rhuitl** [PointCloudLibrary/pcl#3308]
Using `pcl::console::print_highlight` and related methods is a nice way to make console output prettier and easier to read. However, when piped to an output file (or to another program) it garbles the output.

Typically, programs in UNIX environments check if `stdout` is an interactive terminal and do not emit color codes if it's non-interactive. See https://stackoverflow.com/questions/1312922/detect-if-stdin-is-a-terminal-or-pipe/1312957#1312957 for how to do the check.

It's worth to note that the same result could be achieved by PCL users (don't call highlight & friends when non-interactive), however that would seriously clutter up the caller's code.

## Your Environment
* Operating System and version: Linux & MacOS
* PCL Version: latest

## Context
Running PCL tools in an automatic pipeline where output is displayed in a web UI rather than a terminal with ANSI emulation.

## Expected Behavior
No color codes in output when run non-interactively. 

## Current Behavior
Color codes in the output when piping to a file or program.

## Code to Reproduce
```c++
pcl::console::print_error("hello");
```
Pipe the output of the program to a file and inspect it for color codes.

## Possible Solution
In `pcl::console::change_text_color` check if `stdout` is interactive by calling `isatty(fileno(stdout))`. Cache result in a static variable for minimal performance impact. Return early from `change_text_color` if it's non-interactive. Maybe check an environment variable to override this new behavior and still output color codes.

**Comment by taketwo** [comment]
Thanks, that's a useful suggestion. If you want this to be implemented sooner rather than later, please consider submitting a PR.

**Comment by rhuitl** [comment]
I opened a PR, it has been tested on MacOS only. I think it'll compile on Linux and Windows but not sure how to check - do you have a build server to test that?
