### ISSUE TITLE
Feature request for operator+= for pcl::PolygonMesh

### ISSUE THREAD

**Issue by jasjuang** [PointCloudLibrary/pcl#3311]
## Your Environment
* Operating System and version: Ubuntu 18.04
* Compiler: GCC 7
* PCL Version: Latest

## Context
```
pcl::PolygonMesh mesh1;
pcl::PolygonMesh mesh2;
pcl::io::loadPolygonFilePLY("mesh1.ply", mesh1);
pcl::io::loadPolygonFilePLY("mesh2.ply", mesh2);

mesh1+=mesh2; // wouldn't it be great to have this?
```

There is something similar for pointcloud
```
pcl::PointCloud<pcl::PointXYZ> cld1;
pcl::PointCloud<pcl::PointXYZ> cld2;
pcl::PLYReader Reader;
Reader.read("cld1.ply", cld1);
Reader.read("cld2.ply", cld2);

cld1+=cld2;
```

I ended up having my own small little function to do the `+=` for PolygonMesh, and initially, I was surprised that PCL does not have this. Is there something preventing having a `+=` for PolygonMesh, or is it simply a matter of me figuring out how to insert my function into the PCL  codebase so everyone can get to use it?

**Comment by taketwo** [comment]
I see no reason why we can not have it!
