### ISSUE TITLE
transformPointCloud and normals not correctly transformed

### ISSUE THREAD

**Issue by FlowzZz** [PointCloudLibrary/pcl#3313]
## Your Environment

* Operating System and version: Windows 7 64bits
* Compiler: VS2015
* PCL Version: PCL 1.8.0

## Context

I use transformPointCloud to translate/rotate a cylinder point cloud with normals. After transformation, normals are not coherent with the initial point cloud normal. On the other hand, points are correctly transformed.

Initial cloud with correct normals: 
![InputCloud](https://user-images.githubusercontent.com/25009963/63921279-cef00700-ca42-11e9-99f9-3aa9f8d2f303.PNG)

## Expected Behavior

Normals should stay cohenrently oriented according to the cylinder. 

## Current Behavior

Normals are not coherent after transformation.

![OutputCloud](https://user-images.githubusercontent.com/25009963/63921323-e3cc9a80-ca42-11e9-88d5-b38d9ddadac2.PNG)

## Code to Reproduce

Data are available in ZIP file attached.
[Data.zip](https://github.com/PointCloudLibrary/pcl/files/3554444/Data.zip)

`
std::string pathIN = "G:\\test\\bug\\InputCloud.ply";
    std::string resultPath = "G:\\test\\bug\\";
    pcl::PointCloud<pcl::PointXYZRGBNormal >::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGBNormal >);
    if (pcl::io::loadPLYFile<pcl::PointXYZRGBNormal >(pathIN, *cloud) == -1)
    {
        exit(0);
    }
    Eigen::Vector3f axis(-0.0314789, 0.0207277, -0.999289);
    pcl::PointXYZRGBNormal center;
    center.x = -0.00468551; center.y = 0.00173406; center.z = -0.442;

    Eigen::Quaternionf rotAxe;
    rotAxe.setFromTwoVectors(Eigen::Vector3f(0, 0, 1), axis);
    Eigen::Affine3f rotation = Eigen::Affine3f::Identity();
    rotation.prerotate(rotAxe);

    Eigen::Affine3f translation = Eigen::Affine3f::Identity();
    translation.translation() << center.getArray3fMap();

    pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr cylinderCloudTrans(new pcl::PointCloud<pcl::PointXYZRGBNormal>);
    pcl::transformPointCloud(*cloud, *cylinderCloudTrans, translation * rotation);

    pcl::io::savePLYFile<pcl::PointXYZRGBNormal >(resultPath + "\\OutputCloud.ply", *cylinderCloudTrans, true);`

**Comment by taketwo** [comment]
Please use `transformPointCloudWithNormals()` to transform normals as well.

**Comment by FlowzZz** [comment]
Thanks it works like a charm !
