### ISSUE TITLE
Statistical Outlier Removal is not working

### ISSUE THREAD

**Issue by MrGitGo** [PointCloudLibrary/pcl#3321]
I am not sure if this is a bug, but I use a launch file to start the statistical outlier removal like this:

```
<node pkg="nodelet" type="nodelet" name="pcl_manager" args="manager" output="screen" />
  <node pkg="nodelet" type="nodelet" name="outlier_removal" 
        args="load pcl/StatisticalOutlierRemoval pcl_manager" >
    <remap from="~input" to="/royale_camera_driver/point_cloud" />
    <remap from="~output" to="filtered_points" />
    <param name="~stddev" value="1" />
    <param name="~negative" value="False" />

  </node>

```

When I start the camera I get only 3 messages in 2 mins. I also get this:

```
[ WARN] [1567502002.376752445]: This node/nodelet subscribes topics only when subscribed.
[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!
Residual (MSE) 0.000544, using 1152 valid points
```

I am working on the jetsonboard tx2 with ros melodic
and I have a pico monstar camera

**Comment by taketwo** [comment]
As it is, I don't see any substantial evidence that PCL has a bug, rather that something is misconfigured in your ROS setup and/or your camera is not supported. I think you'll be better off redirecting this at ROS Answers.
