### ISSUE TITLE
MLS with kNN Search

### ISSUE THREAD

**Issue by JCA52** [PointCloudLibrary/pcl#3333]
MLS crashes if too few neighbors are included in the search radius.  Using kNN (specific number of neighbors) would fix this issue.

**Comment by kunaltyagi** [comment]
What's the lowest k it doesn't crash for? Where is the crash? Please provide more information

**Comment by kunaltyagi** [comment]
Closing the issue due to lack of community participation. Please reopen this issue or a PR if needed
