### ISSUE TITLE
Failed to Build PCL on Manjaro

### ISSUE THREAD

**Issue by ShtainZ** [PointCloudLibrary/pcl#3334]
## Your Environment

* Operating System and version: Linum Manjaro Gnome 18
* Compiler: GCC8
* PCL Version: 1.9.1 (https://aur.archlinux.org/packages/pcl/)

## Context
I'm a noob in linux os and in manjaro specfically. I'm trying to build PCL. After installing all required dependencies, I ran **makepkg** in the terminal from the pcl directory. After a few minutes the build process failed to complete. Any ideas what am I missing?

## Current Behavior
- Generating done
-- Build files have been written to: /home/zachi/pcl/src/build
[  4%] Built target pcl_common
[  5%] Built target pcl_kdtree
[  5%] Built target pcl_octree
[  6%] Built target pcl_search
[  9%] Built target pcl_sample_consensus
[ 15%] Built target pcl_filters
[ 15%] Built target pcl_io_ply
[ 20%] Built target pcl_io
[ 20%] Linking CXX executable ../../bin/pcl_hdl_grabber
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_version_info@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/libnetcdf.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [io/tools/CMakeFiles/pcl_hdl_grabber.dir/build.make:297: bin/pcl_hdl_grabber] Error 1
make[1]: *** [CMakeFiles/Makefile2:607: io/tools/CMakeFiles/pcl_hdl_grabber.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by GavinStrunk** [comment]
Is it possible you have two versions of curl installed? You could double check with curl --version and pacman -Qi curl to see if they match. It is also worth seeing if you have one installed in /usr/local/lib.

**Comment by ShtainZ** [comment]
Don't know about curl, but I have two netcdf packages (netcdf and netcdf-openmpi) which probably conflict:
