### ISSUE TITLE
Place for meta discussions

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3335]
Sometimes it makes sense to communicate the wider community. Present channels of communication do not feel suitable. I feel a replacement for the mailing-list is required.
 
## Your Environment
* Gitter requires participants to sync timings for discussions. A separate room might help but it'll need to be reserved for one topic at a time to keep history reserved.
* [PCL/issues](https://github.com/PointCloudLibrary/pcl/issues) feels like it should be reserved for the PCL that's visible to the library users. Tagging issues might help, but might clutter up genuine issues with meta ones
* SO is not really a place for discussion

## Context
Code API/performance needs to be designed for the expected use-case. For this, feedback from community is very important. However, there's no way currently to push "notifications" to the wider community when we want feedback from them before making decisions.

Some of the cases arise during
* refactoring code
* updating the API or adding new API
* fixing bugs that can create behavior changes
* discussions regarding the future direction
* making announcements (not in RELEASE notes and README)

## Current Behavior
* Maintainers can @ each other and have a discussions. They can't reach out to the users
* For contributors, it's difficult to call attention of the module experts/users when they wish to know some more details

### For helping the community communicate on issues/PR
[Teams](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#mentioning-people-and-teams) as replacement for distribution lists
* @PointCloudLibrary/core team: The benevolent committee of dictators. Can simply be the list of people with [some admin access](https://github.com/orgs/PointCloudLibrary/people)
* @PointCloudLibrary/module-XYZ: Teams of experts on a module. Makes it easy for newcomers to notify the relevant people on issues/PR. Seems a bit overkill based on the active contributors but feels useful while kick starting discussions to notify all concerned members

### For helping the team communicate with the community
A voluntary signup to a channel where they can be notified of discussions, polls, updates, etc. The channel can be a separate repository or a team + tagged issues. The benefits include
* Issues can have expiry dates (stale-bot)
* Members will get notifications (which they can switch on/off per issue, team and repo)
* Watch issues without participating in them
* Async discussions
* Ability to create a secret team to prevent spam
* Ability to notify people who join the "@PointCloudLibrary/all" team

Getting people to join will be slow but it might be an good experiment. There are Github apps for polls where people can vote their opinions (or just put emoji if every choice is a different comment 😆 )

**Comment by taketwo** [comment]
Great write-up, thanks! I like how you managed to fit this meta-topic into the standard issue template :laughing:

As I said before, community growing and engagement are important things. But, very unfortunately, I don't have enough free time to dedicate to this at the moment. But if some one other from core maintainers agrees to lead this effort, I'd support.

**Comment by kunaltyagi** [comment]
[Discord Server](https://discord.gg/gvcqHTW)
