### ISSUE TITLE
PolygonMesh Cropping CropHull

### ISSUE THREAD

**Issue by Jaykob** [PointCloudLibrary/pcl#3339]
Hi!
I'm trying to crop a PolygonMesh obtained with the Poisson surface reconstruction to get rid of the overlapping surface which is to be expected using the Poisson reconstruction.

My idea was to calculate the convex hull of the point cloud and use the CropHull class. 
The problem is that this class (as well as CropBox) only seem to support PointCloud and not PolygonMesh as input.

I have the feeling that I'm missing something here as I'm under the impression that this should be a standard operation. If not, do you have a suggestion where I could start, e.g. take a class that does something similar as a starting point?

**Comment by kunaltyagi** [comment]
Please use StackOverflow and point-cloud-library tag for questions. This is for "issues" only such as bug reports, wishlist, etc.

Also, PolygonMesh as a PointCloud2 data member which can be used to generate a PointCloud which is what you desire.

**Comment by Jaykob** [comment]
Sorry for this, I tried it on StackOverflow without any luck...

I noticed that PolygonMesh has ha PointCloud2 data member, however I don't see how it would help in my case.

I want to crop the mesh (PolygonMesh) with CropBox or CopHull. I could put back the points into PolygonMesh's cloud member after cropping with CropBox, however that would mess it up as the polygons wouldn't be updated, right?

**Comment by kunaltyagi** [comment]
I don't see your question on SO

**Comment by Jaykob** [comment]
It's a comment on the highest voted answer as it's directly related to my problem:
[https://stackoverflow.com/questions/23537734/removing-the-water-tight-ness-property-from-the-mesh-constructed-by-poisson-reco
](url)

**Comment by kunaltyagi** [comment]
I'm sorry @Jaykob , I should have been more clear. Would you mind creating a **new question** on SO and wait for some feedback from the user community of PCL? That'll allow future users to use SO as a knowledge-hub instead of Github issues. Comments don't garner the same interest from the wider community. Do link your new question here for future visitors 😃

**Comment by Jaykob** [comment]
No problem. I created the question here:
[https://stackoverflow.com/questions/57996042/crop-a-polygonmesh-in-pcl](https://stackoverflow.com/questions/57996042/crop-a-polygonmesh-in-pcl)

**Comment by Jaykob** [comment]
It seems as there's no out of the box method for what I consider a pretty standard use case. Wouldn't it make sense to give CropBox and CropHull the ability to support PolygonMesh and implement a proper cropping?

**Comment by kunaltyagi** [comment]
It'd indeed. Any help from your side is welcome
