### ISSUE TITLE
Potential compiler flag behavior change

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3347]
It appears that GCC has changed the behavior of `-Wabi`

## Your Environment
* Operating System and version: macOS Mojave 10.14.6
* Compiler: GCC-9.1, GCC-9.2
* PCL Version: `master`

## Context
While compiling, gcc gives the following warning
```
[build] cc1plus: warning: '-Wabi' won't warn about anything [-Wabi]
[build] cc1plus: note: '-Wabi' warns about differences from the most up-to-date ABI, which is also used by default
[build] cc1plus: note: use e.g. '-Wabi=11' to warn about changes from GCC 7
```

## Expected Behavior
No warnings

## Possible Solution
Update the flags used for compilation

**Comment by taketwo** [comment]
I don't see why we need this flag, so propose to remove it.

**Comment by taketwo** [comment]
#3446 removed the flag.
