### ISSUE TITLE
GPU normal illegal memory access

### ISSUE THREAD

**Issue by tonyhsiao1995** [PointCloudLibrary/pcl#3355]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler:
* PCL Version: PCL 1.9.1
* NVIDIA 2060
* CUDA 10.1

## Context

I am trying to compute point cloud normal by GPU in one process.
Input cloud is approximate ~25,000 points
pcl::gpu::NormalEstimation  => Segmentation Fault

## Current Behavior

Error: an illegal memory access was encountered	/home/tony/software/pcl/gpu/octree/src/cuda/octree_builder.cu:403
Segmentation Fault(Core dumped)

## Expected Behavior
No Error

**Comment by SergioRAgostinho** [comment]
Hopefully closed with the merge of #3627
