### ISSUE TITLE
Uniformsampling extracting removed indices

### ISSUE THREAD

**Issue by kyungjin-lee** [PointCloudLibrary/pcl#3362]
The getRemovedIndices function of Uniform Sampling in filters doesn't seem to work well
This is my sample code.

using PointType = pcl::PointXYZRGB;
pcl::UniformSampling<PointType> sample(true);
sample.setRadiusSearch(radius);
sample.setInputCloud(current_cloud);
pcl::PointCloud<PointType>::Ptr sampled_cloud(new pcl::PointCloud<PointType>);
sample.filter(*sampled_cloud);
PointIndices removedIndices;
sample.getRemovedIndices(removedIndices);

Sampling seems to work well but the getting the removed indices seems to not work properly.
The original input cloud (current_cloud) had 68679 points and the sampled cloud had 5014 points.
However, when I checked the size of removedIndices it only had 1929 points.
I was assuming it should be the same length has the sampled cloud length.
Hope anyone has an answer on this issue!

Thank you.

**Comment by taketwo** [comment]
A fix was merged a week ago to the master branch: #3323.

**Comment by kyungjin-lee** [comment]
checked and working beautifully! Thank you !!
