### ISSUE TITLE
Implicit fallthrough warning in convolution.hpp

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3367]
`filters/include/pcl/filters/impl/convolution.hpp` at lines 95-97 and 115-117 give a warning regarding implicit fallthrough `[-Wimplicit-fallthrough]`

I don't know if a `break` is needed of `PCL_FALLTHROUGH`

**Comment by SergioRAgostinho** [comment]
Fixed in #3429
