### ISSUE TITLE
QVTKWidget deprecated (in VTK >= 8.2 at least)

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3370]
`QVTKWidget` is used in apps (pcd_video_player, manual_registration, render_window, among others) and is deprecated at least on VTK v8.2

Rendering background used is OpenGL2

**Comment by Chen41284** [comment]
you could use the VTK v7.11(https://github.com/Kitware/VTK/tree/v7.1.1), this version support the QVTKWidget

**Comment by lesterlo** [comment]
I receive this warning after I change qvtkWidget to QVTKOpenGLNativeWidget on my program. This error appears on my mac and the program is not functional. 


Any suggestions to solve this question.

```bash
# Error

QVTKOpenGLNativeWidget requires a `vtkGenericOpenGLRenderWindow`. ` vtkCocoaRenderWindow ` is not supported.
ERROR: In /tmp/vtk-20200406-71083-llkp3g/VTK-8.2.0/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 754
vtkGenericOpenGLRenderWindow (0x7fa4b400d800): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.
```

**Comment by kunaltyagi** [comment]
>  This error appears on my mac and the program is not functional.

Mac isn't supported because Apple has deprecated OpenGL

**Comment by lesterlo** [comment]
@kunaltyagi 

Is there have any solution to prevent this error? Or I need to write 2 sets of Qt GUI Code, One for Mac and One for Linux?

Also, Could I use dear ImGUI with PCL?

Many Thanks!

**Comment by kunaltyagi** [comment]
We don't have enough hands on deck with experience in visualization. As a result, we haven't found a solution or a workaround.

I think using MoltenVK and GLOVE together should make it work, but I never investigated it deeply.

Regarding ImGUI, I'm sure you can use it with PCL. You can either create a new binding or use an existing one:
* https://github.com/lucasw/imgui_ros
* https://github.com/izumin5210/CiPointCloudViewer
* https://github.com/izumin5210/Cinder-PCL (if you use cinder)

**Comment by larshg** [comment]
Should have been solved by #4262.

**Comment by themightyoarfish** [comment]
Not solved with current master and vtk 9.0.3 on macos.

**Comment by themightyoarfish** [comment]
Is it definitive that visualization will not work on macos with VTK > 8?

**Comment by larshg** [comment]
> Is it definitive that visualization will not work on macos with VTK > 8?

Can you elaborate a bit whats not working? The CI builds with vtk 9.

**Comment by themightyoarfish** [comment]
I mean using the render window returned by `PCLVisualizer::getRenderWindow()` as the target for a Qt widget that inherits from `QVTKOpenGLNativeWidget`. When I call `setRenderWindow()` with the PCL visualizer window, I get the 
```
QVTKOpenGLNativeWidget requires a `vtkGenericOpenGLRenderWindow`. ` vtkCocoaRenderWindow ` is not supported.
```
warning/error and the PCL visualizer window pops up separately, instead of appearing inside the Qt widget.

**Comment by themightyoarfish** [comment]
Something like this, which used to work with `QVTKWidget` from vtk 8.2
```
class PointCloudWidget : public QVTKOpenGLNativeWidget {
public:
  PointCloudWidget(QWidget* parent) : QVTKOpenGLNativeWidget(parent) {
	this->setRenderWindow(m_visualizer->getRenderWindow());
}
};
```

**Comment by themightyoarfish** [comment]
What _seems_ to work is to call
```
  QSurfaceFormat::setDefaultFormat(QVTKOpenGLNativeWidget::defaultFormat());
```
before the QApplication gets instantiated and then something like this to set up the widget with the viewer inside:
```
PointCloudWidget::PointCloudWidget(QWidget* parent) :
    QVTKOpenGLNativeWidget(parent) {
  auto renderer     = vtkSmartPointer<vtkRenderer>::New();
  auto renderWindow = vtkSmartPointer<vtkGenericOpenGLRenderWindow>::New();
  renderWindow->AddRenderer(renderer);
  m_visualizer.reset(
      new PCLVisualizer(renderer, renderWindow, "viewer", false));
  this->setRenderWindow(m_visualizer->getRenderWindow());
…
}
```

**Comment by themightyoarfish** [comment]
Passing `true` for the last arg to PCLVisualizer makes it segfault, however.

**Comment by themightyoarfish** [comment]
Unfortunately without the interactor, the widget only displays new data when interacted with, so there must be some way to add one from the outside or fix the segmentation fault.

**Comment by themightyoarfish** [comment]
On [this page](https://pcl.readthedocs.io/en/latest/qt_visualizer.html) here, there is a workaround listed
```
#if VTK_MAJOR_VERSION > 8
  auto renderer = vtkSmartPointer<vtkRenderer>::New();
  auto renderWindow = vtkSmartPointer<vtkGenericOpenGLRenderWindow>::New();
  renderWindow->AddRenderer(renderer);
  viewer.reset(new pcl::visualization::PCLVisualizer(renderer, renderWindow, "viewer", false));
  ui->qvtkWidget->setRenderWindow(viewer->getRenderWindow());
  viewer->setupInteractor(ui->qvtkWidget->interactor(), ui->qvtkWidget->renderWindow());
#else
  viewer.reset(new pcl::visualization::PCLVisualizer("viewer", false));
  ui->qvtkWidget->SetRenderWindow(viewer->getRenderWindow());
  viewer->setupInteractor(ui->qvtkWidget->GetInteractor(), ui->qvtkWidget->GetRenderWindow());
#endif
```

But I have not yet tested this on macos.

**Comment by larshg** [comment]
Yes, to get it to rerender without interacting  you need to call whats in refreshView of the tutorial.

Its basically calling render() og the renderwindow or the renderer. Cant remember on top of my head.

**Comment by themightyoarfish** [comment]
Interesting, too bad the tutorial doesn't show the `refreshView()` code, but I'll try when I get to it.

**Comment by themightyoarfish** [comment]
Aha, it's here: https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/qt_colorize_cloud/pclviewer.cpp#L74
