### ISSUE TITLE
Failed to find match for field 'rgb'

### ISSUE THREAD

**Issue by ankitvora7** [PointCloudLibrary/pcl#3383]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: 5.4
* PCL Version: 1.9

## Context

My aim is to load a ROS point cloud msg (sensor_msgs::PointCloud2) from .pcd files, do some processing, and publish it as sensor_msgs::PointCloud2 to visualize on rviz.
Here's the header for the .pcd files:
```
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 156895
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 156895
DATA ascii
```
Now, when I use pcl_ros pcd_to_pointcloud node, everything works fine and I can see the colored pointcloud on rviz. But this is not the solution I'm looking for since I want to process this point cloud before publishing it. So, I write my own code where I load the pointcloud, do the manipulation and publish it as a sensor_msgs::PointCloud2 message. Now, I'm able to see the pointcloud on rviz but the rgb coloring is missing and I get the warning 'Failed to find match for field 'rgb'. in one of the steps.

## Code to Reproduce

Here's the code snippets I use to do what I explained above:

load the sensor_msgs::Pointcloud2 from .pcd

```
sensor_msgs::PointCloud2 ros_msg
pcl::io::loadPCDFile(path.c_str(), ros_msg)
```
convert from sensor_msgs::Pointcloud2 to pcl::PointXYZRGB

```
pcl::PointCloud<pcl::PointXYZRGB> cloud
pcl::fromROSMsg<pcl::PointXYZRGB>(ros_msg, cloud)
```
Then I do my processing (Let's assume there's no processing and I just convert it back to ROS msg

```
sensor_msgs::PointCloud2 ros_msg_new
pcl::fromROSMsg<pcl::PointXYZRGB>(cloud, ros_msg_new)
pcd_pub.publish(ros_msg_new)
```
Any idea where am I going wrong ?

**Comment by mvieth** [comment]
The following code works for me (Ubuntu 16.04, ROS kinetic, PCL 1.9.1). This is basically your code, just a bit more complete:
```
ros::Publisher pcd_pub = nh->advertise<sensor_msgs::PointCloud2>("/cloud_pcd", 1);  
ros::Duration(1.0).sleep();  
sensor_msgs::PointCloud2 ros_msg;  
pcl::io::loadPCDFile("/home/mvieth/test.pcd", ros_msg);  
ROS_INFO_STREAM("ros_msg size=" << ros_msg.height*ros_msg.width);  
pcl::PointCloud<pcl::PointXYZRGB> cloud;
pcl::fromROSMsg<pcl::PointXYZRGB>(ros_msg, cloud);
ROS_INFO_STREAM("cloud.points.size()=" << cloud.points.size());
sensor_msgs::PointCloud2 ros_msg_new;
pcl::toROSMsg<pcl::PointXYZRGB>(cloud, ros_msg_new);
ros_msg_new.header.frame_id = "base_link";
ROS_INFO_STREAM("ros_msg_new size=" << ros_msg_new.height*ros_msg_new.width);
for(auto field : ros_msg_new.fields) {
    ROS_INFO_STREAM("field: " << field);
}
pcd_pub.publish(ros_msg_new);
ros::spin();
```
Could you provide
- the output of `rostopic echo /your_cloud_topic --noarr` of one of point cloud messages. Interesting is especially the length of the fields array (3 or 4)
- a pcd file that makes the problem appear
- maybe a screenshot of your rviz settings and the warning

You could also test if the problem appears with the code I posted

As a side node, you can load the pcd file directly to a pcl::PointCloud instead of making the detour with sensor_msgs::PointCloud2 and fromROSMsg if you want to do processing anyway.

**Comment by mvieth** [comment]
Closing this due to lack of feedback and because the problem could not be reproduced.
