### ISSUE TITLE
feature request: cluster high dimension data

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#3407]
## Your Environment

* Operating System and version: Ubuntu16.04
* Compiler: gcc5.4.0
* PCL Version: 1.9.1

## Context

As the [question](https://stackoverflow.com/questions/58245922/how-can-i-use-pcls-clustering-method-to-cluster-6d-data-such-as-eigenmatrix?noredirect=1#comment102939817_58245922) that I asked in the StackOverflow, I need to cluster 6d data. I tried saving the data in `pcl::PointXYZRGB`, But the PCL's clustering method seems to only process the first three-dimension data XYZ. Could you please provide a method tho cluster high dimension data.

I used to try to save the data in an `std::vector`, but cannot compile successfully.
```
typedef Eigen::Matrix<double,6,1> Vector6d;
pcl::search::KdTree<Vector6d>::Ptr tree (new pcl::search::KdTree<Vector6d>);
tree->setInputCloud (pose_cloud);
pcl::EuclideanClusterExtraction<Vector6d> ec;
ec.setClusterTolerance (0.2); 
ec.setMinClusterSize (1);
ec.setMaxClusterSize (25000)
ec.setSearchMethod (tree);
ec.setInputCloud (pose_cloud);
std::vector<pcl::PointIndices> cluster_indices;
ec.extract (cluster_indices);
```

**Comment by shrijitsingh99** [comment]
You can use [Conditional Euclidean Clustering](http://www.pointclouds.org/documentation/tutorials/conditional_euclidean_clustering.php) to achieve this by creating a custom clustering constraint.

**Comment by TouchDeeper** [comment]
Thank you, I have used the conditional euclidean clustering and it fixed my issue.
