### ISSUE TITLE
how to only sample points from the surface of CADs?

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [PointCloudLibrary/pcl#3436]
I want to get points from the surface of a CAD model(without inner structure ). I have already tried tools/mesh_sampling, which doesn't slove the problem because it has inner structures. Could someone give me some suggestion? I can only slove it by modified the mesh_sampling code or there're other tools I can use? 

Thanks a lot!

## Your Environment

* Operating System and version: Win 10
* Compiler: vs2017
* PCL Version: 1.8.1

**Comment by taketwo** [comment]
As far as I know, PCL does not provide an "end-to-end" solution for this problem. However, there is a `RenderViewsTesselatedSphere` app which you can use to render views of your model. Naturally, only surface points will show up. So what you'll need to do is to render from a sufficient number of views, combine resultant point clouds, and post-process the merged cloud to remove duplicates (i.e. observations of the same surface point from different views).

General note: this is a bug tracker, not a support/discussion forum. Please use other platforms (e.g. StackOverflow) to ask such questions.
