### ISSUE TITLE
problems about changing the viewpoint by dragging the mouse using PCLVisualizer

### ISSUE THREAD

**Issue by Ace-242** [PointCloudLibrary/pcl#3443]
When a point cloud is displayed using PCLVisualizer, an afterimage remains when the viewpoint is changed by dragging the mouse.

There was never such a thing before, and the phenomenon suddenly started to be a problem.

If you know the solution, please help.

## Your Environment

* Operating System and version: Windows10
* Compiler: visual studio 2015
* PCL Version: PCL1.8.1

## Context
When a point cloud is displayed using PCLVisualizer, an afterimage remains when the viewpoint is changed by dragging the mouse.

There was never such a thing before, and the phenomenon suddenly started to be a problem.

If you know the solution, please help.

**Comment by kunaltyagi** [comment]
> There was never such a thing before, and the phenomenon suddenly started to be a problem

You're using PCL 1.8.1 which has not been updated in forever. That's not bad, just surprising.

Either you updated your library and the newer PCL has a bug. Else, something on your system changed and has incompatibility with your version of PCL.

Could you please investigate a bit more and report your findings?

**Comment by taketwo** [comment]
I'm closing due to lack of feedback. Please reopen if you have new information.
