### ISSUE TITLE
Re-add and deprecate `pcl_isnan`, `pcl_isfinite`, and `pcl_isinf` to avoid API breakage

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3444]
#2798 removed several public API functions without first deprecating them. We should re-introduce these functions before tagging 1.10 release.

**Comment by kunaltyagi** [comment]
Is this correct? Seems fishy to me. Maybe the commit message referenced wrong issue?

**Comment by SergioRAgostinho** [comment]
It does look fishy. Let's reopen.
