### ISSUE TITLE
Add Azure pipeline with Ubuntu 19.10

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3445]
Since we got two additional parallel jobs on Azure, I'd like to add a new pipeline with the latest Ubuntu. My idea is to have two Ubuntu jobs: one testing with the "ancient" baseline 16.04 system, one with the latest and greatest.

As of this writing, 19.10 has been released, so I'd go for it. I'm also considering installing the latest VTK there. However, version 7 is the newest available through `apt-get`. Thus I would use it for now and later, perhaps, install up-to-date VTK from source into the Docker image.

Opinions?

**Comment by SergioRAgostinho** [comment]
Agreed.I would proceed like you said, first adopt 19.10 but then extend slightly further in the way (I suspect) Kunay usually does, which is keep on the latest versions of everything, ideally even on RCs. Probably also allow this job to fail due to the potential instability.

**Comment by kunaltyagi** [comment]
I second (third?) the potential failing on latest version image.

**Comment by taketwo** [comment]
Done, here is the new pipeline: https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=7&_a=summary
