### ISSUE TITLE
Failed to build pcl-trunk + kinfu with cuda support

### ISSUE THREAD

**Issue by lanfeiying** [PointCloudLibrary/pcl#3453]
I was trying to build PCL-trunk + KinFu with CUDA support. However, It failed to pass the compilation.

## Your Environment

* Operating System and version: Archlinux
* Compiler: gcc8
* PCL Version: pcl-trunk
* Cuda version: cuda10
* OpenNI version: openni 1.5.7
* OpenNI2 version: 2.2.0
* VTK version: 8.2.0

## Expected Behavior

It is expected to pass the compilation and builds an executable file "pcl_gpu_kinfu".

## Current Behavior
During compilation, it shows:
nvcc fatal   : A single input file is required for a non-link phase when an output file is specified
The picture shows the output of the compilation:
![Screenshot from 2019-11-06 21-17-48](https://user-images.githubusercontent.com/22729258/68338666-eac6f780-00da-11ea-9b9a-d2ac57d7ad42.png)

I have no idea why it doesn't pass the compilation. I tried the method mentioned in previous issues. Such as removing the VTK definitions.

## Code to Reproduce

I use "ccmake .." to configure the settings.

## Possible Solution

Is it possible that I use very new packages such as VTK, OpenNI2, CUDA10?

**Comment by mvieth** [comment]
I found these two:
1. https://stackoverflow.com/questions/16528107/nvcc-fatal-a-single-input-file-is-required-for-a-non-link-phase-when-an-outputf
2. https://forums.developer.nvidia.com/t/solved-nvcc-fatal-a-single-input-file-is-required-for-a-non-link-phase-when-an-outputfile-is-s/37807

So it could be a wrong character/bad encoding, or some other incorrect configuration with ccmake. Hope that helps
