### ISSUE TITLE
`Registration::hasConverged()` should be const qualified

### ISSUE THREAD

**Issue by adishavit** [PointCloudLibrary/pcl#3455]
The method [`Registration::hasConverged()`](https://github.com/PointCloudLibrary/pcl/blob/c73a9108986ceeff306fc9611d291ead5cf5db5d/registration/include/pcl/registration/registration.h#L408) should be const qualified.
i.e. changed to:

```cpp
/** \brief Return the state of convergence after the last align run */
      inline bool 
      hasConverged () const { return (converged_); }
//                    ^^^^^
```

**Comment by SergioRAgostinho** [comment]
Agreed. Feel free to submit a pull request  with the change.

**Comment by adishavit** [comment]
Done. See PR #3456
