### ISSUE TITLE
Cannot build PCL Examples involving filtering.

### ISSUE THREAD

**Issue by xen20** [PointCloudLibrary/pcl#3458]
* Operating System and version: Windows 10, 10.0.18362.418
* Compiler: MSVC 14.23.28105 , VS2019
* PCL Version: 1.91

## Context
Cannot build PCL example : [http://pointclouds.org/documentation/tutorials/statistical_outlier.php](filtering). And additional filtering examples.

## Expected Behavior
Example being built. The final target for what I am doing would be a .dll file to use from a .NET application.

## Current Behavior
LNK2001 errors, such as
```Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "protected: virtual void __cdecl pcl::StatisticalOutlierRemoval<struct pcl::PointXYZ>::applyFilter(class pcl::PointCloud<struct pcl::PointXYZ> &)" (?applyFilter@?$StatisticalOutlierRemoval@UPointXYZ@pcl@@@pcl@@MEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@@Z)	pcd_write_test	C:\Users\Konstantin\source\repos\PCL_playground\pcd_write.obj	1	
```

## Code to Reproduce
See linked example. CMake used for project:
```cmake_minimum_required(VERSION 2.8 FATAL_ERROR)
project(MY_GRAND_PROJECT)
set(BUILD_SHARED_LIBS ON) # note that we will be building a dll.
find_package(PCL 1.2 REQUIRED)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_library(pcd_write_test pcd_write.cpp) # build a library
#add_executable(pcd_write_test pcd_write.cpp)
target_link_libraries(pcd_write_test ${PCL_LIBRARIES})
```

Reinstalled PCL twice to no result. Installed all PCL components - first and third party.
Examples such as [http://pointclouds.org/documentation/tutorials/random_sample_consensus.php](this one) work well.

Visual Studio Project set up using the following tutorial: 
[http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php](link)

**Comment by taketwo** [comment]
Our examples certainly work on Linux, but there is no CI job to routinely check Windows. So there may be a problem that we are not aware of. @UnaNancyOwen could you suggest steps to troubleshoot this issue?

**Comment by xen20** [comment]
Also, for reference: acquiring & building PCL from vcpkg works perfectly fine.

**Comment by larshg** [comment]
I have build and run the statistical outlier example with master. Please open a new ticket, if necessary.

Please close.
