### ISSUE TITLE
"Could NOT find OpenNI (missing:  OPENNI_INCLUDE_DIR)" on Mac

### ISSUE THREAD

**Issue by ky0on** [PointCloudLibrary/pcl#346]
I've installed OpenNI through Homebrew (https://github.com/totakke/homebrew-openni).
However, `cmake .` given the following error:

```
-- Could NOT find OpenNI (missing:  OPENNI_INCLUDE_DIR) 
```

Do you know any reasons?

**Comment by nomadsystem** [comment]
Hey folks.  Trying to get PCL running on my 10.9 laptop.  I tried both the packages listed on the website and the brew method.  With the latter (brew) I can compile some of the simple intro stuff like pcd_write.cpp.  But I cannot get anything with OpenNI to compile.  Specifically, I'm trying to get the example openni_viewer_simple.cpp to compile.  But there are a few issues it seems.  The first is the same message referenced in this thread.  The second is the seemingly more problematic #include from the example:  #include <pcl/io/openni_grabber.h>  That file simply doesn't exist on my machine.  Yes, I've done the complete install --with-openni, etc.  But who knows, maybe I missed something else.

I have several Linux boxes on hand, but they're older distros like Ubuntu 12.04.  Would I just be better off upgrading one of them to 14.04?  I feel like trying to work with PCL + OpenNI under Mac OS is going to be a very bumpy ride.  I mean, it has been already.  Spent an entire day today installing, uninstalling, etc.

**Comment by jspricke** [comment]
@nomadsystem: please use our mailing list (www.pcl-users.org) if you have questions. We provide a PPA for Ubuntu and starting with 14.10 we are part of the main unimportant repository.

**Comment by yiakwy** [comment]
Note  @fran6co  homebrew/science has been replaced by brewsci/science. For people who install pcl using homebrew, how can we modify the CMake file to add "/usr/local/include/ni"?
