### ISSUE TITLE
error: call of overloaded 'abs(flann:: KDTreeIndex<flann::L1<float>>::ElementType)' is ambiguous ElementType span =abs(point[i]-leaf_point[i]);

### ISSUE THREAD

**Issue by anujgpatil** [PointCloudLibrary/pcl#3463]
Experiencing the said error while building 3D-Recognition Framework under PCL apps

## Your Environment
Operating System and version: UBUNTU 16.04- Jetson TX2
Compiler: gcc 6.5.0
PCL Version: 1.9.1 release

## Current Behavior
![image](https://user-images.githubusercontent.com/29145342/68544211-dccceb80-03e6-11ea-87ba-ac72824483bc.png)

## Code to Reproduce
Simply enable 3D rec framework under APPS while building PCL library

Any suggestions?

**Comment by taketwo** [comment]
This looks like a FLANN issue, not PCL. Which version of FLANN are you using? Try to obtain the latest released, or better, the latest master.

**Comment by anujgpatil** [comment]
I'm using V1.8.4 from 2013...The latest is 1.9.1 from 2016.
When I upgrade,would that cause me to recompile the entire PCL library again?
(Doing that on limited memory of Jetson TX2 is a real pain in the tail)

**Comment by taketwo** [comment]
Yes, you will need to recompile PCL.

**Comment by jinfagang** [comment]
Got same issue here on Ubuntu 16.04 with flann 1.8.4

is that a
