### ISSUE TITLE
error: narrowing conversion of ‘-4’ from ‘int’ to ‘BuffersTest_MedianBufferWindow3_Test<char>::TypeParam {aka char}’ inside { } [-Wnarrowing]

### ISSUE THREAD

**Issue by anujgpatil** [PointCloudLibrary/pcl#3464]
Getting this error while building the GPU targets , disabled by default during compilation of PCL library.

## Your Environment
Operating System and version: UBUNTU 16.04- Jetson TX2
Compiler: gcc 6.5.0
PCL Version: 1.9.1 release

## Current Behavior
![image](https://user-images.githubusercontent.com/29145342/68544623-1d2e6880-03eb-11ea-9e3c-d2cdd52328c0.png)

## Code to Reproduce
Switch this flag from OFF to ON in CMakeCache file in Build folder.
//Build the GPU-related subsystems
BUILD_GPU:BOOL=**ON**

Any inputs?

**Comment by taketwo** [comment]
Not sure how this is related to the `BUILD_GPU` option,bBut I'll fix this next week.

**Comment by kunaltyagi** [comment]
Will be resolved once GPU CI is online.
