### ISSUE TITLE
Possible issue in UniformSampling, incorrect leaf centers?

### ISSUE THREAD

**Issue by ochilan** [PointCloudLibrary/pcl#3465]
I'm referring to the code in [filters/include/pcl/filters/impl/uniform_sampling.hpp](https://github.com/PointCloudLibrary/pcl/blob/e109b7f81e419d984baa52777c31e134b2a581cd/filters/include/pcl/filters/impl/uniform_sampling.hpp). In the applyFilter function, lines 115-116 https://github.com/PointCloudLibrary/pcl/blob/e109b7f81e419d984baa52777c31e134b2a581cd/filters/include/pcl/filters/impl/uniform_sampling.hpp#L115-L116 the distance between a point of the input point cloud and the leaf center is supposed to be computed in order to find the point closest to the leaf center.

However, the `ijk` vector is computed in lines 100-102 https://github.com/PointCloudLibrary/pcl/blob/e109b7f81e419d984baa52777c31e134b2a581cd/filters/include/pcl/filters/impl/uniform_sampling.hpp#L100-L102 as the input point scaled by `inverse_leaf_size_` and rounded (floored) to integers. The reason for this is that `ijk` is then used to compute a leaf index, but it is later also used as the leaf center. The problem is that the input point cloud and the `ijk` vector live in differently scaled spaces. In particular, if I'm not mistaken, the distance which is computed is the distance to some point which is pretty arbitrary, depending on the desired voxel size.

Indeed, if you try to apply uniform subsampling to a regular grid of points, the result is not even necessarily uniform since the point positions are biased toward the incorrectly computed voxel centers.

I think one possible solution could be to scale `ijk` by `leaf_size_` (not `inverse_leaf_size_`) before computing the distance to the input point. But since it's easy to get such details wrong, I would like to hear different opinions on this issue.

**Comment by taketwo** [comment]
Hi, sorry for the delayed reply and thanks for bringing this up. 

> Indeed, if you try to apply uniform subsampling to a regular grid of points, the result is not even necessarily uniform since the point positions are biased toward the incorrectly computed voxel centers.

Could you provide a toy numerical example of this? Just coordinates of a few points, leaf resolution, actual and expected output. Having this, we could discuss whether the filter performs according to its name/expectations.
