### ISSUE TITLE
Changes to RSSDK 2.0 grabber

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3467]
OK. My plan was to compile and include these files only under Windows and fork a new a issue to address the failures under Linux.

_Originally posted by @SergioRAgostinho in https://github.com/PointCloudLibrary/pcl/pull/2214#issuecomment-552419368_

Expanding on this topics with a list of items to address before the release:
- [ ] Restrict the building the grabber to Windows only.
- [ ] Address my final review comments in the original PR and remove some unnecessary checks.
- [ ] Fix warnings raise from not using `std::` int types.

**Comment by taketwo** [comment]
One more thing: fix warnings, there are plenty because of using int types without `std::` prefix.
