### ISSUE TITLE
Point cloud loaded by pcl::io::loadPCDFile is conflicted with addline in pcl::visualization::PCLVisualizer

### ISSUE THREAD

**Issue by why-scholar** [PointCloudLibrary/pcl#3468]
## Your Environment

* Operating System and version: win10 64bit
* Compiler:  vs2017
* PCL Version: 1.9.1

## Context
My aim is to show a point cloud and a line immediately in a PCLVisualizer.  But I meet a strange phe
nomenon that the point cloud and the line cannot be showed immediately when I load the point cloud by pcl::io::loadPCDFile, as shown below.  
![image](https://user-images.githubusercontent.com/5106287/68915830-98eb3500-079e-11ea-8705-6cd5a36ce87e.png)

The code is shown as below:
```cpp
std::string pcd_path = argv[1];
std::cout << "pcd file: " << pcd_path.c_str() << std::endl;

pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>());
if (pcl::io::loadPCDFile(pcd_path, *cloud) == -1)
   return 0;

pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> color_line(cloud, 0, 255, 0);
viewer->addPointCloud<pcl::PointXYZ>(cloud, color_line, "cloud with line");
	
pcl::PointXYZ p_s, p_e;
p_s.x = xx; p_s.y = yy; p_s.z = zz;//replace the coordinates with yourself
p_e.x = xx; p_e.y = yy; p_e.z =zz;
viewer->addLine<pcl::PointXYZ>(p_s, p_e, 1.0, 0.0, 0.0, "line");
viewer->spin();
```

The point cloud and the line can be showed successfully independently. I have checked the coordinates of the line and the point cloud, and make sure they are close to each other. I think The reason for this phenomenon is that function pcl::io::loadPCDFile has change the coordinates of point cloud. Thus, I create a new point cloud and copy the points from original cloud loaded by 
 pcl::io::loadPCDFile , show as follows:
```cpp
pcl::PointCloud<pcl::PointXYZ>::Ptr newcloud(new pcl::PointCloud<pcl::PointXYZ>());
for (int i=0;i<cloud->points.size();i++)
{
		pcl::PointXYZ point;
		point.x = cloud->points[i].x;
		point.y = cloud->points[i].y;
		point.z = cloud->points[i].z;

		newcloud->points.push_back(point);
}
```
and then add this new point cloud in the viewer instead of original point cloud, shown as follows:
```cpp
pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> color_line(newcloud, 0, 255, 0);
viewer->addPointCloud<pcl::PointXYZ>(newcloud, color_line, "cloud with rect");
```
![image](https://user-images.githubusercontent.com/5106287/68916332-693d2c80-07a0-11ea-9cad-49c9fcc57366.png)

Thus, I think there is some bug in function pcl::io::loadPCDFile. 

Please check it out.

**Comment by SergioRAgostinho** [comment]
Can you upload your pcd file somewhere?

>  The reason for this phenomenon is that function pcl::io::loadPCDFile has change the coordinates of point cloud.

If that was the case, adding `newcloud`  to the viewer would have generated the same 3D scene in which the entire point cloud appears to be rendered as a single point right? From your images, it did not.

**Comment by why-scholar** [comment]
@SergioRAgostinho 

You are right. This is why I can not understand. In addition, how can I upload my pcd file? I cann't find any button on the web pages.

**Comment by SergioRAgostinho** [comment]
I meant to upload to the pcd file to a file hosting server of your choice e.g., dropbox and share the url to it.

**Comment by why-scholar** [comment]
[test.zip](https://github.com/PointCloudLibrary/pcl/files/3851514/test.zip)
@SergioRAgostinho I upload the test file, and you can test it according to the code I pasted.

**Comment by sthoduka** [comment]
The pcd file has the sensor orientation set to `(0.707107, -0.707107, 0, 0)`.

Once you read the file into `cloud`, you can reset the sensor orientation with 
`cloud->sensor_orientation_ = Eigen::Quaternionf(1.0, 0.0, 0.0, 0.0);`
and it visualizes just fine with or without the line.

**Comment by larshg** [comment]
Closing since a possible cause has been answered.
