### ISSUE TITLE
Add virtual dtor to RangeImage

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3470]
This PR introduces the following warning:

```cpp
../keypoints/src/narf_keypoint.cpp: In member function ‘void pcl::NarfKeypoint::clearData()’:
../keypoints/src/narf_keypoint.cpp:75:52: warning: deleting object of polymorphic class type ‘pcl::RangeImage’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
     delete range_image_scale_space_[scale_space_idx];                                                   
```

_Originally posted by @taketwo in https://github.com/PointCloudLibrary/pcl/pull/3454#issuecomment-554310316_

**Comment by SergioRAgostinho** [comment]
We removed the dtor from `PointCloud` which was virtual. `RangeImage` inherited it from `PointCloud`. Since it was removed, `RangeImage` now needs it's virtual dtor explicitly defined.

**Comment by taketwo** [comment]
Ping @lightyear15
