### ISSUE TITLE
qustion: what paper can I refer to If I want to know the theory about the boundary estimation.

### ISSUE THREAD

**Issue by TouchDeeper** [PointCloudLibrary/pcl#3475]
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

## Context

Hello, as the title said, what paper can I refer to If I want to know the theory about the [boundary estimation](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/boundary.h)?

**Comment by taketwo** [comment]
You can start with Radu's PhD [thesis](http://mediatum.ub.tum.de/doc/800632/941254.pdf) (founder of PCL) and follow links thereof.

This is a bug tracker, not a support forum. Please post such questions elsewhere.
