### ISSUE TITLE
when “pcl” was a dependency library of "intro/rtabmap"  and "make" was typed, many strange errors, that had never existed, occurred as follows!

### ISSUE THREAD

**Issue by zengletian1491** [PointCloudLibrary/pcl#3476]
when “pcl” was a dependency library of "intro/rtabmap"  and "make" was typed, many strange errors, that had never existed, occurred as follows:

**/usr/local/include/pcl-1.9/pcl/point_types.h: In function ‘const pcl::_PointDEM& pcl::common::operator+=(pcl::_PointDEM&, const float&)’:
/usr/local/include/pcl-1.9/pcl/point_types.h:698:1: error: ‘plusscalar’ is not a member of ‘pcl::traits’
POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::_PointDEM,
^
/usr/local/include/pcl-1.9/pcl/point_types.h:698:1: error: ‘plusscalar’ is not a member of ‘pcl::traits’
POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::_PointDEM,
^**

/usr/local/include/pcl-1.9/pcl/point_types.h:874:33: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
using HasNoIntensity = std::enable_if_t<!has_intensity_v, bool>;
^
/usr/local/include/pcl-1.9/pcl/point_types.h:886:27: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
using HasColor = std::enable_if_t<has_color_v, bool>;
^

/usr/local/include/pcl-1.9/pcl/common/point_tests.h:120:38: error: ‘pcl::traits::HasNoNormal’ has not been declared
template <typename PointT, traits::HasNoNormal = true> constexpr inli
^
/usr/local/include/pcl-1.9/pcl/common/point_tests.h:120:49: error: expected ‘>’ before ‘<’ token
template <typename PointT, traits::HasNoNormal = true> constexpr inli

/usr/local/include/pcl-1.9/pcl/common/impl/copy_point.hpp:90:28: error: ‘enable_if_t’ is not a member of ‘std’
std::enable_if_t<boost::mpl::and_<boost::mpl::not_<s

/usr/local/include/pcl-1.9/pcl/PolygonMesh.h:48:48: error: request for member ‘vertices’ in ‘polygon’, which is of non-class type ‘int’
polygon.vertices.end (),
^

/usr/local/include/pcl-1.9/pcl/io/file_io.h:317:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
std::enable_if_t<std::is_integral::value, bool>
^

**/usr/local/include/pcl-1.9/pcl/common/io.h:65:77: required from here
/usr/include/c++/5/bits/predefined_ops.h:234:30: error: no match for call to ‘(pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)>) (const pcl::PCLPointField&)’
{ return bool(_M_pred(*__it)); }
^**

Please give me some suggestions! Thank you!

**Comment by zengletian1491** [comment]
Once we used "#include <pcl/point_types.h>", errors followed!

**Comment by kunaltyagi** [comment]
rtabmap has a very specific version of PCL that they support. The issue isn't in PCL
