### ISSUE TITLE
"X Error of failed request" when trying to plot range image

### ISSUE THREAD

**Issue by tolda** [PointCloudLibrary/pcl#3491]
## Your Environment
I tried the code on two different systems (suspecting it is a graphics related issue, I specified also the GPU model)
* Operating System and version: Ubuntu 16.04 / 18.04
* Compiler: gcc
* PCL Version: 1.7 (installed with apt install libpcl-dev)
* GPU: Intel UHD Graphics 620 / Nvidia TITAN Xp

## Current Behavior
I tried to plot a range image by following the tutorial in [here](http://www.pointclouds.org/documentation/tutorials/range_image_visualization.php#range-image-visualization) , but it gives me the following error

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  57
  Current serial number in output stream:  58

Debugging it, I found out that everything works fine in the example form me until I try to actually plot the image, in line 162
`range_image_widget.showRangeImage(range_image);`

**Comment by mvieth** [comment]
Possibly related to #3479 ? What is the output if you run it with valgrind? Could you please provide the pcd file you are using?

**Comment by kunaltyagi** [comment]
Closing due to lack of information
