### ISSUE TITLE
Set Enviornmental variables correctly on Windows

### ISSUE THREAD

**Issue by petrasvestartas** [PointCloudLibrary/pcl#3492]
Hi, 

I am new to PCL.

I am following installation tutorial: http://unanancyowen.com/en/pcl18/

I would like to ask how to set enviromental variables correctly?
I did it like this:

![EnvironmentalVariables](https://user-images.githubusercontent.com/18013985/69795329-acea5a00-11d4-11ea-8f3b-8fda1cab5277.png)
![EnvironmentalVariables2](https://user-images.githubusercontent.com/18013985/69795330-acea5a00-11d4-11ea-840f-42dfcdef57c2.png)

But when I compile PCL CloudViewer.cpp example in CMAKE I get following error:

![Cmake](https://user-images.githubusercontent.com/18013985/69795595-2aae6580-11d5-11ea-908c-87f5e4a7609f.png)

**Comment by taketwo** [comment]
@UnaNancyOwen

**Comment by UnaNancyOwen** [comment]
First, That semicolon (;) is not required. 
It is a platform-specific separator character used to separate path strings in environment variables. (e.g. path1;path2;path3;... )
In environment variable editor of Windows 10, the environment variable PATH is automatically insert separator. You don't have to write it.

<code>;%PCL_ROOT%\bin</code> -> <code>%PCL_ROOT%\bin</code>
<code>;%OPENNI2_REDIST64%</code> -> <code>%OPENNI2_REDIST64%</code>n the

Second, You have specified the generator incorrectly in CMake GUI.
You need specify the generator for this project to "Visual Studio 15 2017", and optional pratform for generator to "x64".

**Comment by petrasvestartas** [comment]
Thank you for the answer.
I deleted semicolons and change the x64 with VS 2017. Then configured the cmake again.
I get this red error at cmakelist line number 5:

![Question](https://user-images.githubusercontent.com/18013985/69813410-d0280000-11fa-11ea-9b1c-2936e8542a08.png)

I tried to generate the visual studio project but its empty and error happens when it is built.

**Comment by UnaNancyOwen** [comment]
Optional platform is not "ARM64". You need specify "x64".

**Comment by petrasvestartas** [comment]
I have just tried the x64. Still the same errror:

```
CMake Warning (dev) at CMakeLists.txt:5 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable PCL_ROOT is set to:

    C:\Program Files\PCL 1.9.1

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by SergioRAgostinho** [comment]
Note, that it is a warning an error. Your configuration phase is still completing successfully.

**Comment by petrasvestartas** [comment]
I wait then generate the project, then open the project in visual studio and get this when building:
![dsa](https://user-images.githubusercontent.com/18013985/69816106-614da580-1200-11ea-9939-985fa360b2c6.png)


I just installed PCL, added environmental variables, restarted computer and tried to configure again, still the same.

**Comment by UnaNancyOwen** [comment]
It looks like you are using Visual Studio 2019. Please specify "Visual Studio 16 2019".

**Comment by petrasvestartas** [comment]
I tried both

**Comment by kunaltyagi** [comment]
Closing in favor of #4118
