### ISSUE TITLE
Projecting points to a parametric sphere model

### ISSUE THREAD

**Issue by yellowpuppy** [PointCloudLibrary/pcl#3499]
The official tutorial “Projecting points using a parametric model” shows a example of projecting point cloud to a plane. However, now I wish to project points onto a sphere. I change the `proj.setModelType (pcl::SACMODEL_PLANE);`  to `proj.setModelType (pcl::SACMODEL_SPHERE);` but did not work. Any one can help me? maybe by showing a simple example?

**Comment by taketwo** [comment]
AFAIR it's not implemented, but there was a (not merged) PR that does. You may have a look there: https://github.com/PointCloudLibrary/pcl/pull/2562

**Comment by yellowpuppy** [comment]
@taketwo Thanks a lot!
