### ISSUE TITLE
errors about pcl 1.9 when pcl 1.9 is used as a dependent library

### ISSUE THREAD

**Issue by zengletian1491** [PointCloudLibrary/pcl#3502]
when pcl 1.9 is used as a dependent library, errors occurred as follows:

**error: undefined reference to `pcl::tracking::KLDAdaptiveParticleFilterTracker<pcl::PointXYZRGB, pcl::tracking::ParticleXYZRPY>::insertIntoBins(std::vector<int, std::allocator<int> >, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&)'**

could you please give some suggestions?

**Comment by kunaltyagi** [comment]
Please provide more context. Most likely, you are not linking the tracking library.

**Comment by kunaltyagi** [comment]
Closing due to no response (and it's not an issue in PCL)
