### ISSUE TITLE
HarrisKeypoint3D generate one singular keypoint

### ISSUE THREAD

**Issue by easterngarden** [PointCloudLibrary/pcl#3503]
HarrisKeypoint3D generates one weird keypoint with 132 good keypoints as shown in the picture:
![image](https://user-images.githubusercontent.com/36804327/70473850-98d11300-1a86-11ea-8281-29824f5f3554.png)

## Your Environment

* Operating System and version: Windows 10
* Compiler: Visual Studio 2017
* PCL Version: 1.9.1

## Expected Behavior

remove

 the sigular point, expected keypoints as:
![image](https://user-images.githubusercontent.com/36804327/70474309-362c4700-1a87-11ea-8dbe-a11992836f78.png)

## Code to Reproduce

The following codes creates one weird keypoint with 132 good keypoints:

		pcl::HarrisKeypoint3D<pcl::PointXYZRGBNormal, pcl::PointXYZI>::Ptr detector(new pcl::HarrisKeypoint3D<pcl::PointXYZRGBNormal, pcl::PointXYZI>());
		detector->setNonMaxSupression(true);
		detector->setThreshold(1e-6);
		detector->setRadius(radius);
		detector->setRadiusSearch(radius);
		detector->setRadius(tgtradius);
		detector->setRadiusSearch(tgtradius);
		detector->setInputCloud(tgt_cloud_pts);
		detector->setSearchSurface(tgt_cloud_pts);
		detector->compute(*target_keypoints);

**Comment by kunaltyagi** [comment]
The actual point cloud used is missing. Would it be possible to provide that?

**Comment by easterngarden** [comment]
Hi Kunal,
I could not find the place to upload the point cloud. Could you tell me how to upload the point cloud?
Thanks,Bill
    On Monday, December 9, 2019, 08:21:42 PM PST, Kunal Tyagi <notifications@github.com> wrote:  
 
 
The actual point cloud used is missing. Would it be possible to provide that?

**Comment by kunaltyagi** [comment]
> Could you tell me how to upload the point cloud?

You can zip the pcd and attach it in GitHub issues, or use pastebin or any of other persistent file/text sharing services. And then modify the code to work with the pcd instead. :smile:

**Comment by easterngarden** [comment]
Attached is point cloud set. radius/tgtradius size is around 5.
[tgtcloudpoints.zip](https://github.com/PointCloudLibrary/pcl/files/3946278/tgtcloudpoints.zip)

**Comment by easterngarden** [comment]
Add detector->setRefine(false); filtered out this weired point.  Looks like refineCorners creates this sort of points.

**Comment by kunaltyagi** [comment]
> Looks like refineCorners creates this sort of points.

Thanks for narrowing the issue. I looked at the code and this seems like the place where the point cloud is created: https://github.com/PointCloudLibrary/pcl/blob/master/keypoints/include/pcl/keypoints/impl/harris_3d.hpp#L531-L532

Perhaps there's something wrong in the condition?

**Comment by easterngarden** [comment]
Yes, I found the inverse matrix determinant too big in the second iteration for some reason.

**Comment by kunaltyagi** [comment]
Sorry, this slipped under the radar.

> inverse matrix determinant too big in the second iteration

Does it increase in more iterations? Can you print the value for nnT, NNT, NNTInv?
