### ISSUE TITLE
How can we compile the C++project via cmake on window system using vscode?

### ISSUE THREAD

**Issue by laiming997** [PointCloudLibrary/pcl#3506]
I just install the pcl library by the PCL 1.9.1 All-In-One Installer,an set the system environment,I succeed to build the pcl example project using the VS2017. But I want to wirte a project using the vscode and cmake,but it failed!

## Your Environment

* Operating System and version: Windows 64bit
* Compiler: mingw-x64 8.1.0
* PCL Version:1.9.1

## Context

this is my cmakelist code :
set(PCL_DIR "E:/pcl_library/PCL 1.9.1/cmake/")
find_package(PCL 1.9.1 REQUIRED COMPONENTS common io)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

and I see the  PCLConfig.cmake and PCLConfigVersion.cmake in this path , but when I cmake using the "MingW Makefiles" to cmake , the result is that
[cmake] CMake Error at E:/pcl_library/PCL 1.9.1/cmake/PCLConfig.cmake:56 (message):
[cmake]   PCL can not be found on this machine
[cmake] Call Stack (most recent call first):
[cmake]   E:/pcl_library/PCL 1.9.1/cmake/PCLConfig.cmake:444 (pcl_report_not_found)
[cmake]   CMakeLists.txt:19 (find_package)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "E:/point_cloud/project_1/build/CMakeFiles/CMakeOutput.log".
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.

the error happen at the command find_package,is that I was failed to find the library at this path ？or there are some problem of my system environment

**Comment by kunaltyagi** [comment]
Would vcpkg help with mingw?

You should point to the "base_path/PCL_1.9.1/" as PCL_DIR, not the cmake inside it. I don't know if you should precompile PCL and point PCL_DIR at the installation directory (I usually do a source compile and local install OR add as subproject)

**Comment by laiming997** [comment]
> Would vcpkg help with mingw?
> 
> You should point to the "base_path/PCL_1.9.1/" as PCL_DIR, not the cmake inside it. I don't know if you should precompile PCL and point PCL_DIR at the installation directory (I usually do a source compile and local install OR add as subproject)

thank you very much~I just modify the pcl_root path to base_path/PCL_1.9.1,and it succeed to find the pcl library.But there are still some problem of the vtk library . I don't know whether can't find the vtk library or other wrong.
the output of mingw32-make is that:
-- Configuring done
-- Generating done
-- Build files have been written to: E:/point_cloud/project_1/build
[ 33%] Linking CXX executable hello.exe
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__tcf_12':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::~vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__tcf_13':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::~vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `vtkRenderingCore_AutoInit::vtkRenderingCore_AutoInit()':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkInteractionStyle_AutoInit_Construct()'
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `vtkRenderingCore_AutoInit::~vtkRenderingCore_AutoInit()':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkInteractionStyle_AutoInit_Destruct()'
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkRenderingFreeType_AutoInit_Destruct()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__tcf_12':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::~vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__tcf_13':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::~vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::vtkObjectFactoryRegistryCleanup()'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\hello.dir\build.make:247: hello.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:75: CMakeFiles/hello.dir/all] Error 2

**Comment by kunaltyagi** [comment]
Closing this issue as resolved since there's a related issue which focuses with more depth for the VTK linker problems.

**Comment by laiming997** [comment]
> Closing this issue as resolved since there's a related issue which focuses with more depth for the VTK linker problems.

how can I close this issue? is that I modify the vtk module which enable? close the related module to close this issue to deal the problem ?

**Comment by kunaltyagi** [comment]
> I just modify the pcl_root path to base_path/PCL_1.9.1,and it succeed to find the pcl library

This essentially closes this issue (CMake not finding PCL) in favor of #3510 which is still open. Please post more details regarding your setup on the relevant issue (ie VTK libraries not found by linker)
