### ISSUE TITLE
Vcpkg failed

### ISSUE THREAD

**Issue by petrasvestartas** [PointCloudLibrary/pcl#3508]
Hi,

Can someone guide me through PCL installation using vcpkg?

I tried to install PCL and received following error
https://github.com/microsoft/vcpkg/issues/9338

I am really lost with PCL installation for weeks.

**Comment by jasjuang** [comment]
Maybe you can install the non-static version for now. `vcpkg install pcl:x64-windows` works.

**Comment by petrasvestartas** [comment]
Since I am not very good in C++, I would like to ask why there is a need to have a static library?

In the end, my goal is to have .exe file to execute one method from PCL and run it on another windows computer.
Do you think this would be feasible without having the static library?

**Comment by jasjuang** [comment]
Yes, you can do it without static library. vcpkg made it really simple because it performs app-local dll copy automatically for you. Static library is only needed if for some reason you don't want to distribute the dlls to your clients.

**Comment by kunaltyagi** [comment]
Closing this since vcpkg was working long after this issue got the last response.

**Comment by petrasvestartas** [comment]
I am trying to reference PCL in console app x64 bit , but eigen is not found?
Can someone help to resolve the eigen ?

![image](https://user-images.githubusercontent.com/18013985/96730409-69817700-13b6-11eb-8155-6b3d69fbb713.png)
