### ISSUE TITLE
compile my own project which contain pcl library, but failed with vtk wrong

### ISSUE THREAD

**Issue by laiming997** [PointCloudLibrary/pcl#3510]
## Your Environment

* Operating System and version:window10
* Compiler:mingw64
* PCL Version:1.9.1

## Context

when I include the #include <pcl/visualization/cloud_viewer.h> which has used the vtk library ,i went wronng.but the cmake command I wrote is that 
find_package(VTK 8.1.2 REQUIRED ${QUIET_})
when it can't find the VTK, i would occur error and can't generate the makefile .but  i showed that 
-- Configuring done
-- Generating done
which means I succeed to find the VTK library~
but when use mingw32-make,it has some error:

-- Configuring done
-- Generating done
-- Build files have been written to: E:/point_cloud/project_1/build
[ 33%] Linking CXX executable hello.exe
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__tcf_12':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::~vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__tcf_13':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::~vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `vtkRenderingCore_AutoInit::vtkRenderingCore_AutoInit()':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkInteractionStyle_AutoInit_Construct()'
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkRenderingFreeType_AutoInit_Construct()'
CMakeFiles\hello.dir/objects.a(main.cpp.obj): In function `vtkRenderingCore_AutoInit::~vtkRenderingCore_AutoInit()':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkInteractionStyle_AutoInit_Destruct()'
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkRenderingCoreModule.h:41: undefined reference to `vtkRenderingFreeType_AutoInit_Destruct()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__tcf_12':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::~vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__tcf_13':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::~vtkObjectFactoryRegistryCleanup()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkDebugLeaksManager.h:46: undefined reference to `vtkDebugLeaksManager::vtkDebugLeaksManager()'
CMakeFiles\hello.dir/objects.a(LasReader.cpp.obj): In function `__static_initialization_and_destruction_0':
E:/PCL 1.9.1/3rdParty/VTK/include/vtk-8.1/vtkObjectFactory.h:293: undefined reference to `vtkObjectFactoryRegistryCleanup::vtkObjectFactoryRegistryCleanup()'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\hello.dir\build.make:247: hello.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:75: CMakeFiles/hello.dir/all] Error 2
mingw32-make: *** [Makefile:83: all] Error 2
终端进程已终止，退出代码: 1

I don't know what happen and modify what to go ahead

**Comment by jasjuang** [comment]
Did you build PCL via [vcpkg](https://github.com/Microsoft/vcpkg/), or did you build it from scratch yourself?

**Comment by CesarNaranjoP** [comment]
I hava the same problem in Linux, though I have created my own makefile which includes the vtk include folder. When I execute the make command I get the same linker error:

main.cpp:(.text.startup+0x62): undefined reference to `vtkDebugLeaksManager::vtkDebugLeaksManager()'
main.cpp:(.text.startup+0x69): undefined reference to `vtkDebugLeaksManager::~vtkDebugLeaksManager()'
main.cpp:(.text.startup+0x88): undefined reference to `vtkObjectFactoryRegistryCleanup::vtkObjectFactoryRegistryCleanup()'
main.cpp:(.text.startup+0x8f): undefined reference to `vtkObjectFactoryRegistryCleanup::~vtkObjectFactoryRegistryCleanup()'

The error occurs when I include some of the vtk .h files (for example #include <vtkUnstructuredGrid.h>), but it doesn't happen with every file.

**Comment by bryanibit** [comment]
how to solve the problem? I met the same problem.

**Comment by StephenChen2016** [comment]
i have same problem

**Comment by Magi329** [comment]
Same problem with PCL1.12.1 VS2019 (debug Win32)
