### ISSUE TITLE
pcl1.8.1 SIGSEGV at RandomSampleConsensus?

### ISSUE THREAD

**Issue by YangSiri** [PointCloudLibrary/pcl#3511]
Hi, contributors,

Recently i rebuilt pcl 1.8.1 many times because there is always serious SIGSEGV problems(fig 1). At first, i thought it was because of the version of eigen i use in my project is different with the version pcl was compiled with. Then i changed the CMakeLists.txt of pcl in order to use eigen 3.3.4 (which is self-built in _/usr/local/include/eigen3_ instead of libeigen3.3.92 in _/use/include/eigen3_). However it somehow cant be made as fig2. I think im a little stupid to run into such situation as this is a simple environment related problem. But i hope anyone could give me some suggestions.

![pclSIG2](https://user-images.githubusercontent.com/33154113/71078187-d1c66180-21c3-11ea-8490-5bd95906faef.png)
![pclSIG1](https://user-images.githubusercontent.com/33154113/71078189-d25ef800-21c3-11ea-8aed-0b423c89fcd7.png)
![pclSIG](https://user-images.githubusercontent.com/33154113/71078423-5a450200-21c4-11ea-91c4-9fe83268d6db.png)

Looking forward to generous help.
THANKS

**Comment by kunaltyagi** [comment]
Could you please post how you resolved the issue?
