### ISSUE TITLE
Issue in building my own xcode project 

### ISSUE THREAD

**Issue by subhash2000** [PointCloudLibrary/pcl#3512]
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version: 1.9.1

## Error is as shown in the screenshot 
[![Screen-Shot-2019-12-17-at-3-10-06-PM.png](https://i.postimg.cc/KjRG3yPD/Screen-Shot-2019-12-17-at-3-10-06-PM.png)](https://postimg.cc/xNVDBhFX)

IDE is not identifying the PCL while I have installed PCL using homebrew.

**Comment by SergioRAgostinho** [comment]
I believe this already has been fixed in the current master branch.

**Comment by kunaltyagi** [comment]
Closing because marked as fixed. If issue persists, please reopen a new issue
