### ISSUE TITLE
Ubuntu 18.04 installation

### ISSUE THREAD

**Issue by FrancescoTerrosi** [PointCloudLibrary/pcl#3513]
I installed PCL with apt install libpcl-dev but, when I try to compile and run the tutorial, I get the following error:

By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "PCL", but
CMake did not find one.

And I can't find the file anywhere.
Any ideas?

Thanks

**Comment by kunaltyagi** [comment]
I could not reproduce it with a docker:
```
$ doker run --rm -it ubuntu:18.04 bash
root@hidden: apt update && apt install -y libpcl-dev cmake git
root@hidden: git clone https://github.com/kunaltyagi/pcl-cmake-minimum/
root@hidden: cd pcl-cmake-minimum && mkdir build && cd build
root@hidden: cmake ..
...
<succeeds>
```

So it seems to be an issue with how you're compiling the tutorials, not as much the issue of a bad install. Please provide more relevant details.

The "missing" file in question is located `/usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake` as returned by `dpkg-query -L libpcl-dev`
