### ISSUE TITLE
convert to sensor_msgs::PointCloud2 error

### ISSUE THREAD

**Issue by gongyue666** [PointCloudLibrary/pcl#3515]
#2740  Your Environment

* Operating System and version:ROS melodic
* Compiler: gcc 7.4.0
* PCL Version:1.9

## Context
I load a 1.ply as pcl::PointCloud<pcl::PointXYZ> and convert it to sensor_msgs::PointCloud2.
I publish it to rviz, and the result points is larger than it should do.The object in 1.ply should be never larger than 1.0m * 1.0m, but in rviz it become hundreds bigger. 

the image below is what I see in rviz, the grid is 1m*1m, the point cloud is so big.
![微信图片_20191225205815](https://user-images.githubusercontent.com/15926228/71445995-cc37c100-2759-11ea-8139-d6a1fd5d7f2c.png)

the code I used is like this:
![微信图片_20191225205827](https://user-images.githubusercontent.com/15926228/71446007-ed98ad00-2759-11ea-9369-a7efd4d5af83.jpg)

**Comment by kunaltyagi** [comment]
Hi

Could you create a minimal PCD file (just a few points, say 10 at max) which still causes this issue? After that, please paste the PCD file as response so we can verify that the issue lies in PCL or elsewhere.

**Comment by kunaltyagi** [comment]
Please reopen with requested details. Closing because the bug couldn't be confirmed and inactivity of OP
