### ISSUE TITLE
PCL 1.9 fails to detect installed VTK (v8.9)

### ISSUE THREAD

**Issue by resplendent-star** [PointCloudLibrary/pcl#3525]
I have install  vtk ,and pcl found it , but it said it consider vtk to be not found

## Your Environment

* Operating System and version:ubuntu 18.04   
* Compiler:  gcc 7.4
* PCL Version: 1.9

## Context

trying to install the PCL1.9 in my computer

## Code to Reproduce

CMake Warning at CMakeLists.txt:421 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/vtk-8.90/vtk-config.cmake

  but it set VTK_FOUND to FALSE so package "VTK" is considered to be NOT
  FOUND.  Reason given by package:

  Could not find the VTK package with the following required components:
  RenderingContextOpenGL.

-- VTK_MAJOR_VERSION 8, rendering backend: OpenGL
CMake Deprecation Warning at /usr/local/lib/cmake/vtk-8.90/vtk-use-file-deprecated.cmake:1 (message):
  The `VTK_USE_FILE` is no longer used starting with 8.90.
Call Stack (most recent call first):
  CMakeLists.txt:426 (include)

-- VTK found (include: , libs: 
-- Could NOT find PCAP (missing: PCAP_LIBRARIES PCAP_INCLUDE_DIRS) 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   date_time
--   iostreams
--   system
--   regex
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/include  
-- DOXYGEN_FOUND 
-- HTML_HELP_COMPILER 
-- Found CPack generators: DEB
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   tools
-- The following subsystems will not be built:
--   visualization: VTK was not found.
--   apps: No reason
--   outofcore: Disabled manually.
--   examples: Code examples are disabled by default.
--   people: Disabled manually.
--   simulation: Disabled by default.
--   global_tests: No reason
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lzw/for_dev_software/pcl-master/build

**Comment by jasjuang** [comment]
I agree this bug has to be solved at some point but I know that it works with VTK 8.2. If you don't mind using an older VTK you can temporarily workaround this problem.

**Comment by resplendent-star** [comment]
thanks～


 
---Original---

**Comment by rimmartin** [comment]
same issue with PCL Version: 1.10

**Comment by rimmartin** [comment]
VTK git HEAD has the module RenderingContextOpenGL2 where
pcl git HEAD is looking for RenderingContextOpenGL by default

Looking in CMakeLists.txt https://github.com/PointCloudLibrary/pcl/blob/master/#L410 the default for VTK_RENDERING_BACKEND is OpenGL if it is undefined.

So on the cmake command line adding -DVTK_RENDERING_BACKEND=OpenGL2 changes the default and pcl HEAD with VTK HEAD gets to the compile stage.

no successful compile yet but that's a different issue

**Comment by rimmartin** [comment]
This has been discussed in other issues
https://github.com/PointCloudLibrary/pcl/issues/1234
https://github.com/PointCloudLibrary/pcl/pull/1534
Perhaps a heads up in https://github.com/PointCloudLibrary/pcl#compiling section would help new users.

**Comment by taketwo** [comment]
Probably related: #3637

**Comment by rimmartin** [comment]
got pcl HEAD with VTK HEAD to compile successfully.

Needed to consider https://vtk.org/doc/nightly/html/classvtkCellArray.html#details VTK_CELL_ARRAY_V2 numerous places. vtkShaderProgram2 doesn't exist int VTK HEAD but vtkShaderProgra does.

I see other pull requests; I'll keep an eye and if this isn't building for others I'll then fork and make a pull request.

Working on usage and testing if visuals work

**Comment by larshg** [comment]
Close this as PCL 1.9 only support up to 8.1/8.2 maybe?

Work is in progress to support vtk 9.0, but that will be from PCL 1.12?

**Comment by kunaltyagi** [comment]
VTK 9.0 support: PCL 1.11.1 if possible, else 1.12

Also, before I close, does PCL >1.9 support VTK 8.9, that is, will moving to PCL 1.10 (or higher) resolve the issue?

**Comment by larshg** [comment]
VTK 8.9, is not an actual release. Only 8.2 was the latests before 9.0. So the answer is no.
