### ISSUE TITLE
Add Docker files for all Azure machines to repo

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#3528]
I currently can reproduce some compiler warnings on my machine, so I want to use same image like Azure pipeline, but I can only find Ubuntu 16.04 Docker file. Is it possible to add the other Docker files, too?

**Comment by taketwo** [comment]
We use the same Dockerfile for all Ubuntu images. Simply pass `--build-arg UBUNTU_DISTRO=19.10` to the Docker build command to get the 19.10 version.

That said, if you want to use the same exact image as Azure, then simply pull it from Dockerhup (`docker pull pointcloudlibrary/env:19.10`).

**Comment by SunBlack** [comment]
Good to know. I will not use the image directly, as I use e.g. ccache ;-). Just wanted to check which versions of dependencies are installed.

**Comment by kunaltyagi** [comment]
>  I will not use the image directly, as I use e.g. ccache

You can still use the image. In another dockerfile, use `FROM` or simply mount the ccache files (executable and cache) in correct places in the docker
