### ISSUE TITLE
Binary installation problem on Ubuntu 18.04

### ISSUE THREAD

**Issue by pauljurczak** [PointCloudLibrary/pcl#3531]
Following instructions from http://pointclouds.org/downloads/linux.html produces this error:
```
E: The repository 'http://ppa.launchpad.net/v-launchpad-jochen-sprickerhof-de/pcl/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by kunaltyagi** [comment]
Oh! That seems outdated. PCL is available without any repository on [ubuntu bionic 18.04](https://packages.ubuntu.com/source/bionic/pcl)

**Comment by pauljurczak** [comment]
Yes, I found it. How about updating http://pointclouds.org/downloads/linux.html ?

**Comment by kunaltyagi** [comment]
That'll require a maintainer with access to website. The website is outdated, but has been a low priority for a long time. There are issues open for that. Sorry about this !
