### ISSUE TITLE
Severity	Code	function template has already been defined when using custom point type in Point Cloud Library (PCL)

### ISSUE THREAD

**Issue by LL-Liu** [PointCloudLibrary/pcl#3532]
I came across a problem when trying to register two point clouds using PCL. Instead of using the provided PointT, I used custom point type and followed the tutorial(http://www.pointclouds.org/documentation/tutorials/adding_custom_ptype.php#adding-custom-ptype). However, when I complied the codes in VS2019, it failed. I also tried this post ( https://stackoverflow.com/questions/39221424/pcl-instantiating-new-point-types-for-all-functions). It didn't work neither.

I defined the custom point type as follows:
```
#ifndef PCL_NO_PRECOMPILE`
#define PCL_NO_PRECOMPILE
#endif
#include <iostream>
#include <pcl/pcl_macros.h>
#include <pcl/point_types.h> 
#include <pcl/impl/point_types.hpp>
#include <pcl/impl/instantiate.hpp>
#include <pcl/point_cloud.h>
#include <pcl/impl/point_types.hpp>
#include <pcl/common/transforms.h>
#include <pcl/common/impl/transforms.hpp>
#include <pcl/registration/icp.h>
#include <pcl/registration/impl/icp.hpp>
#include <pcl/features/fpfh.h>
#include <pcl/features/impl/fpfh.hpp>
#include <pcl/features/pfh.h>
#include <pcl/features/impl/pfh.hpp>
#include <pcl/registration/ia_ransac.h>
#include <pcl/registration/impl/ia_ransac.hpp>
#include <pcl/features/normal_3d.h>
#include <pcl/features/impl/normal_3d.hpp>
#include <pcl/kdtree/kdtree_flann.h>
#include <pcl/kdtree/impl/kdtree_flann.hpp>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/impl/voxel_grid.hpp>
#include <pcl/filters/approximate_voxel_grid.h>
#include <pcl/filters/impl/approximate_voxel_grid.hpp>
#include <Eigen/Core>
struct dPointXYZ {
        double x;
        double y;
        double z;
};
POINT_CLOUD_REGISTER_POINT_STRUCT(dPointXYZ,
(double, x, x)
(double, y, y)
(double, z, z)
)
PCL_INSTANTIATE(VoxelGrid, dPointXYZ);
PCL_INSTANTIATE(NormalEstimation, dPointXYZ);
PCL_INSTANTIATE(KdTree, dPointXYZ);
PCL_INSTANTIATE(FPFHEstimation,dPointXYZ);
PCL_INSTANTIATE(SampleConsensusInitialAlignment, dPointXYZ)
```

```
void voxelFilteringPoints(pcl::PointCloud<dPointXYZ>::Ptr& ProjPoint, pcl::PointCloud<dPointXYZ>::Ptr& filteredPoints, float dGridSize)
{

    pcl::VoxelGrid<dPointXYZ> ApproximateVoxelGrid;
    ApproximateVoxelGrid.setLeafSize(dGridSize, dGridSize, dGridSize);
    ApproximateVoxelGrid.setInputCloud(ProjPoint);
    ApproximateVoxelGrid.filter(*filteredPoints);
    //std::cout<<"Filtered points size: "<<*filteredPoints<<std::endl;
}

```
The build results are as follows:
![Annotation 2020-01-09 133436](https://user-images.githubusercontent.com/38683008/72043266-b2ff4a80-32eb-11ea-866b-206af35043da.png)

Do you have any ideas how to solve the problem?

**Comment by LL-Liu** [comment]
I followed this post (http://www.pcl-users.org/own-custom-PointT-type-td3978828.html). This time, the compiler doesn't show the template function has defined. Instead,  it shows 'getVector4fMap': is not a member of 'pcl::dPointXYZ'	
![image](https://user-images.githubusercontent.com/38683008/72050882-252c5b00-32fd-11ea-8685-65eb702f114b.png)
I checked the point_types.hpp, getVector4fMap is a function of pcl::Vector4fMap. I have included point_types.hpp in the include header. What should I do now?

**Comment by kunaltyagi** [comment]
Please take a look at Lines 280 through 312: [source code of point_types.hpp](https://github.com/PointCloudLibrary/pcl/blob/1e3c62e2df0c739a7f5fd13610b043408d03aebe/common/include/pcl/impl/point_types.hpp#L280)

**Comment by LL-Liu** [comment]
> Please take a look at Lines 280 through 312: [source code of point_types.hpp](https://github.com/PointCloudLibrary/pcl/blob/1e3c62e2df0c739a7f5fd13610b043408d03aebe/common/include/pcl/impl/point_types.hpp#L280)

Hi, thank you for the suggestion. Now, I modified defintions of dPointXYZ as follows
![image](https://user-images.githubusercontent.com/38683008/72062633-210b3800-3313-11ea-950f-1926e926e262.png)

New problems occur:
![image](https://user-images.githubusercontent.com/38683008/72062524-ec977c00-3312-11ea-8e74-4238363c6171.png)
Do you know how I can check which .h files I should include?

**Comment by kunaltyagi** [comment]
You don't have all dependencies to compile PCL (here: LZ4). That means the issue has been resolved (in favor of a new error). Please check the docs on how to compile PCL from source

**Comment by LL-Liu** [comment]
> You don't have all dependencies to compile PCL (here: LZ4). That means the issue has been resolved (in favor of a new error). Please check the docs on how to compile PCL from source

I installed PCL using PCL-1.9.1-AllInOne-msvc2017-win64.exe. It is supposed to have all dependencies. I will include LZ4 to see what happens. Thanks for the help.

**Comment by taketwo** [comment]
Note that having `double x, y, z` and  `float data[4]` in the same union does not make sense. I can also speculate that the problem is coming from the fact that you are trying to use `double` for the coordinates. I'd recommend to switch to `float` as this is the only type really supported by PCL.

**Comment by LL-Liu** [comment]
> Note that having `double x, y, z` and `float data[4]` in the same union does not make sense. I can also speculate that the problem is coming from the fact that you are trying to use `double` for the coordinates. I'd recommend to switch to `float` as this is the only type really supported by PCL.

I defined data[4] as double in the very begining. However, an Eigen error was reported when filtering the point cloud as the kernel function only supports the type of float. As such, I changed the type of data[4] to float. Because I use WGS84 coordinates and the values of the coordiantes are very large, using float will compromise the accuray. I know normalizing the coordinates will solve the problem, but I want to give it a try to define a new point type to see if it works.

**Comment by kunaltyagi** [comment]
Then you'll need to modify PCL for using double. Lot of algorithms internally use float casts (implicit) and the Eigen map will just fail to get any sensible data out of your union.

Having worked with datasets covering a [insert large area], I will recommend you to use a local frame (plenty of conversions from WGS84 to those) and normalize in that frame. Float with precision of 23 has plenty of spare precision for my usual computations. A local UTM is a good choice for getting computational accuracy in cm with data covering a few thousand km^2 (state or country for most countries). For large size datasets, the collection and collation often carries more errors than using float would.

There's parts of PCL that kinda-sorta work with double and there's parts that don't. It might be more trouble to use double than work with floats, but if you think double will help, then I'd love to see a PR 😄 .
