### ISSUE TITLE
undefined reference to SampleConsensusModelNormalPlane

### ISSUE THREAD

**Issue by JeromePerdrizat** [PointCloudLibrary/pcl#3544]
Dear all,
Hopefully this is a bug and not a misstake of mine. 
I always got an undefined Reference error during compiling the project. 

I found almost the same issue in the past, see here:
https://github.com/PointCloudLibrary/pcl/issues/3042

## Your Environment

* Operating System and version:
Ubuntu 18.04.3

* Compiler:
GCC  7.4

* PCL Version:
1.8.1 (using sudo apt-get install libpcl-dev to install it)

## Context

Spending a lot of time on Ioogle I just found this old issue here: #3042. This is almost the same, but I'm not using the ros-framework. I attached the requested data in the mentioned issue (Variable  `${PCL_LIBRARIES}`  of the CMakeList). Once I added as a formated a formated version and once the direct output of the compiler.

Ofcourse I tried the quick-and-dirty solution to reinstall the pcl-library like mentioned in the other issue, but this doesn't solve the problem. So I proceed the following way, trying to make sure no other stupid reason causing the problem:

1. Remove the installed packed libpcl-dev and build it from source (pcl-master) and reeinstall (several times, different flags) -> no success
2. Reeinstall Ubuntu from scratch, just make all updates, install qt-creator and some qt-stuff and then `sudo apt-get install libpcl-dev` -> still not working

**Important notice:**
As I've seen there is a cuda implementation in for this filter. I have an intel-graphicscard (on-board) so I had no possibility to check this with an installed cuda-library.

Hopefully It's not my fault, and I made a stupid misstake.
[AllFiles.zip](https://github.com/PointCloudLibrary/pcl/files/4049195/AllFiles.zip)

## Expected Behavior

Finding the functions/objects in the library

## Current Behavior

Undefined Reference 

## Code to Reproduce

To avoid a stupid misstake, I take the code of the minimal example [here](http://pointclouds.org/documentation/tutorials/random_sample_consensus.php) and replaced the used filter. I removed the argument -s, but this shouldn't matter, since it fails during the linking step.
I tested the code (before modifying it) on this machine and it worked fine.

## Possible Solution

Unfortunetally I don't have a lot of experience writting libraries and doing stuff like this. Therefore I'm not able to give an idea for the solution.

**Comment by taketwo** [comment]
The problem is that you are trying to use the following type: 

```cpp
SampleConsensusModelNormalParallelPlane<pcl::PointXYZ, pcl::PointXYZRGB>
```

This type was not instantiated during the compilation of PCL library. That's why it is missing from shared objects, and that's why you get undefined references.

The reason why it was not instantiated is that it does not make much sense. The second template argument should be a point type with normals; however `pcl::PointXYZRG` does not have normals.

How to solve this depends on what you want. If you indeed want to use SAC model with normal checks, then you need to change the second template parameter to, say, `pcl::Normal`. But more importantly, you need to supply normals! Since you actually have no normals, I'd rather switch to a SAC model that does not require them.

**Comment by JeromePerdrizat** [comment]
Dear taketwo

Thank you a lot for your fast response to my concern, you made my day. 
I'm sorry for being wrong in the forum, I spent such a lot of time, and expected it really as an issue. But I was unable to see the wood for the trees, and I searched far to far.

For anyone else who might read this:
The goal was to find a plane, of which I know it's normal. Here is a simple code snipped, which provide this function much easier, than in the first attempt:

` std::vector<int> inliers;
    pcl::SampleConsensusModelPerpendicularPlane<pcl::PointXYZ>::Ptr
            model (new pcl::SampleConsensusModelPerpendicularPlane<pcl::PointXYZ>(source));
    Eigen::VectorXf coefficients;
    model->setAxis (Eigen::Vector3f (0.0, 0.0, 1.0));
    model->setEpsAngle (pcl::deg2rad (15));
    pcl::RandomSampleConsensus<pcl::PointXYZ> ransac (model);
    ransac.setDistanceThreshold (0.1);
    ransac.computeModel();
    ransac.getInliers(inliers);`

**Comment by taketwo** [comment]
You're welcome. The snippet that you posted looks alright for your use-case :+1:
