### ISSUE TITLE
run 3D Object Recognition based on Correspondence Grouping

### ISSUE THREAD

**Issue by goog** [PointCloudLibrary/pcl#3547]
when run example from here http://pointclouds.org/documentation/tutorials/correspondence_grouping.php  
visual studio output:
“pcl/features/board.h”: No such file or directory

## Development Environment

* win10 64bit
* Compiler: vs 10
* PCL Version: All-in-one installers 1.6.0

**Comment by mvieth** [comment]
It seems like your PCL version (1.6.0) is simply too old. If you check [here](https://github.com/PointCloudLibrary/pcl/tree/pcl-1.6.0/features/include/pcl/features), you see that the header does not exist in version 1.6.0. Seems like it was added in PCL 1.7.0.
