### ISSUE TITLE
Adding third party tools alongside CI

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3564]
## Context
There are several issues such as undefined behavior, memory leaks, etc. that aren't being detected because we have not setup sanitizers and checks. Setting them up in CI is difficult, but using third party tools is easy.

Eg: https://app.codacy.com/manual/kunaltyagi/pcl/dashboard

## Possible Solution
Enable good third party tools (and keep monitoring them, disable them if they stop giving us any benefits). This requires organization ownership to manager. @jspricke

**Comment by taketwo** [comment]
I don't have prior experience with Codacy service, but the diagnostics generated for Kunal's fork look quite useful. I think it's a good idea to turn this on. (And anyway it does not cost us a cent.)

@jspricke would you mind doing the necessary administrative steps?

**Comment by taketwo** [comment]
Jochen have risen a concern that Codacy requests too many rights. Indeed:

![image](https://user-images.githubusercontent.com/1241736/75429218-bc02b480-5949-11ea-8a1f-71ac5c77d5e5.png)

**Comment by kunaltyagi** [comment]
No issues. I'll maintain it on my fork?

**Comment by aPonza** [comment]
Maybe a (pinned?) meta-issue tagged as `good first issue` linking to the Codacy review on your fork and explaining most of these problems are real and would be nice to fix could be beneficial to whoever wants to contribute?

**Comment by kunaltyagi** [comment]
Though codacy is quite noisy, this might be a good idea... but would require some details to go along with it to prevent weird PRs. Right now, I was cherry picking the issues to be bite-sized, understandable and mundane. Just reading `MISRA 15.4: 10k cases` doesn't exactly inspire confidence 😆 to tackle it.

**Comment by kunaltyagi** [comment]
Closing since this was specific to codacy and ... codacy has issues.
