### ISSUE TITLE
Index out of bounds in IntegralImageNormalEstimation

### ISSUE THREAD

**Issue by office-florian-hubner** [PointCloudLibrary/pcl#3573]
## Your Environment

* Operating System and version: Windows 10 x64
* Compiler: MSVC 2017
* PCL Version: master

## Context

I try to do a normal estimation on a subset of points of a point cloud using IntegralImageNormalEstimation. When I do the computation on all points
it works but when I set the indices the app crashes. Note that the
depth dependen smoothing has to be disabled for the crash to happen.

## Possible Solution

There seems to be a mixup with the index that is used to index
into the output cloud in `IntegralImageNormalEstimation::computeFeaturePart`.
In the branch when `use_depth_dependent_smoothing_` is disabled
you can see at the end that `pt_index` is used instead of `idx` to index into the output cloud.
When `use_depth_dependent_smoothing_` is enabled the correct index is used.

I already have it fixed locally on my machine. If you want me to I can submit a pull request
although the fix is just renaming a varibale in two lines of code.

**Comment by kunaltyagi** [comment]
> If you want me to I can submit a pull request

Sure, please go ahead.
