### ISSUE TITLE
PCL doesn't use SSE with custom CXX_FLAGS

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3578]
## Your Environment

* Operating System and version: Linux
* Compiler: GCC 9.2
* PCL Version: HEAD

## Context
Setting any warning flag or sanitizer from command line results in a very different compile than with default flags.

This causes local tests to be disabled (eg: SSE) which otherwise fail on the CI

## Expected Behavior
If some option has been switched on, it should not be overridden silently.

## Current Behavior
Setting CXX_FLAGS causes no SSE to be used.

## Possible Solution
See [Line 111 of CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L111) which has a pattern repeating several times

**Comment by kunaltyagi** [comment]
Removing the check just calls the `PCL_CHECK_FOR_SSE` function, but doesn't set the correct flags. I'm definitely missing something here

**Comment by SergioRAgostinho** [comment]
You need to have a way to disable SSE flags for packagers to be able to compile and bundle things in a controlled compilation flag. The mindset before was "if the user is manually setting flags, nothing else is added so that he/she can have full control over what compilation flags are being added."

**Comment by kunaltyagi** [comment]
> a way to disable SSE flags for packagers

For that will using `CMAKE_BUILD_TYPE` be a better option? We can set the flags manually for a custom build type ([see here](https://cmake.org/cmake/help/v3.5/variable/CMAKE_BUILD_TYPE.html))

This allows predefined flags for certain situations, like what you describe

**Comment by taketwo** [comment]
We (as in me and Sergio, "young" maintainers) were burnt hard by this. In fact, one of our releases (was it the one that went into 16.06 LTS?) was plagued due to us not understanding the intricacies of treating SSE/ARCH flags when packaging for Debian. Check the history of that line and discussions in associated PRs.

**Comment by kunaltyagi** [comment]
I'll take a look at those (#2100 and #2579, right)

**Comment by kunaltyagi** [comment]
I had a look, and the rationale behind disabling the SSE flags in presence of any other flag is to ensure that for packaging, SSE flags don't turn on. But there needs to be an override, a switch (`PCL_ENABLE_SSE` 😆 ) or something because I'm unable to use SSE with any other flag.

For a default sane choice (aka detect packaging), we can
* use `-DCMAKE_BUILD_TYPE=Package` and provide the necessary flags (just equal to default flags of `RelWithDebInfo` or `Release) and disable SSE flags explicitly in this mode
* disable the SSE logic in absence of `-DCMAKE_BUILD_TYPE=Release`
* disable in presence of [`CPack`](https://cmake.org/cmake/help/v3.13/module/CPack.html#module:CPack), which now has a [deb generator](https://cmake.org/cmake/help/v3.13/cpack_gen/deb.html)

Relying on "default flags" is not good for my health 🤣, and I was left wondering why this was happening to me (silently). For now, I'll send a patch which messages about lack of SSE flags, but I'm interested to know if any of the options I presented are .... enticing

**Comment by SergioRAgostinho** [comment]
> But there needs to be an override, a switch (`PCL_ENABLE_SSE` laughing ) or something because I'm unable to use SSE with any other flag.

In theory you can manually add them to your supplied list of flags? But I'm comfortable with the idea of supplying a mechanism to force the addition of SSE flags irrespective of the user specifying CMAKE_CXX_FLAGS.

From the three options you mentioned, I'm not fond of option 2 and I'm willing to give a shot at the other two. Whatever we do, as long as we print some informative messages at the end of the configuration stage informing the user of the things we forcefully enabled/disabled it should be fine.

**Comment by kunaltyagi** [comment]
> Whatever we do, as long as we print some informative messages at the end of the configuration stage informing the user of the things we forcefully enabled/disabled it should be fine.

Amen.

I also find the option 2 quite hacky. Option 1 feels the best to me, since the flags are fixed by us, and we can override the user provided flags. Option 3 also feels a bit hacky.

> In theory you can manually add them to your supplied list of flags?

Yes, but I don't know what all flags are available for my system on both my laptop and workstation. I can find out, but I'd rather not

**Comment by kunaltyagi** [comment]
This has turned out to be bit of a CMake nightmare and needs someone with much better CMake skills. If anyone is interested, I can create an issue for them to track their PR with.
