### ISSUE TITLE
[feature request] Azure Kinect grabber

### ISSUE THREAD

**Issue by Morwenn** [PointCloudLibrary/pcl#3580]
It would be interesting if PCL could provide optional support for a grabber compatible with the Azure Kinect DK. It doesn't work with OpenNI2 so it requires a dedicated grabber as far as I can tell. This sounds like a huge task, but actually there's [already such a project][1] on GitHub under a permissive license - maybe the author would be willing to contribute to PCL or to relicense the code under the PCL license so that it's fully compatible?

One of the tough parts would probably be to correctly handle the [Azure Kinect SDK (K4A)][2], which itself relies on an interesting amount of dependencies, including a version of libuvc more recent than any of the library's releases (which apparently stopped in 2017).

I don't know whether it's relevant, but the Azure Kinect DK repository also has [an example][3] about a fast method to extract a point cloud from its data.

  [1]: https://github.com/forestsen/K4aGrabber
  [2]: https://github.com/microsoft/Azure-Kinect-Sensor-SDK
  [3]: https://github.com/microsoft/Azure-Kinect-Sensor-SDK/tree/develop/examples/fastpointcloud

**Comment by kunaltyagi** [comment]
Did you contact the author regarding contributing PRs to PCL?

**Comment by Morwenn** [comment]
@kunaltyagi I didn't, but the author hasn't replied to any of the issues on his project (I opened one in November) and hasn't been active on GitHub since October, so I don't have high hopes.
