### ISSUE TITLE
Double include of pcl_targets

### ISSUE THREAD

**Issue by Neumann-A** [PointCloudLibrary/pcl#3589]
https://github.com/PointCloudLibrary/pcl/blob/8ed756fcfaf710cd5f3051704fdd8af7b0d4bf61/CMakeLists.txt#L475

already done at line 94 

https://github.com/PointCloudLibrary/pcl/blob/8ed756fcfaf710cd5f3051704fdd8af7b0d4bf61/CMakeLists.txt#L94

**Comment by taketwo** [comment]
Indeed, the second one is not necessary. Thanks for the heads-up, please submit a patch.
