### ISSUE TITLE
Revise images used in Azure pipelines

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3598]
Got a message from Azure support. We might need to revise our pipelines soon.

> Thank you for using Azure Pipelines! To prepare for another set of exciting updates this year and to better serve the needs of our growing user base, we have to make room – both in terms of Azure capacity and in terms of human support resources – and remove some of the less used, older images. On March 23, 2020, we’ll be removing the following Azure Pipelines hosted images:
> * Windows Server 2012R2 with Visual Studio 2015, a.k.a vs2015-win2012r2
> * macOS X High Sierra 10.13, a.k.a macOS-10.13
> * Windows Server Core 1803, a.k.a win1803
>
> Based on our telemetry, your organization has used one of these images in the past month and will be impacted by this change. To ensure your pipeline isn’t impacted by this change, please update your pipelines using the following steps.

**Comment by kunaltyagi** [comment]
From the list, we only use `macOS-10.13`, right? Weirdly, Microsoft docs still mentioned High Sierra in yaml files. But they do have [10.14 now](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)

**Comment by taketwo** [comment]
Right, `macOS-10.13` is the only affected image. @SergioRAgostinho attempted to enable `macOS-10.14` build some time ago but did not succeed: #2998.

**Comment by taketwo** [comment]
Closed via #2998.
