### ISSUE TITLE
coding mistake in io/src/ply_io.cpp

### ISSUE THREAD

**Issue by DiscreteLogarithm** [PointCloudLibrary/pcl#3599]
In line 1772 `fs.close()` should have been `fpout.close()`. `fs` has been closed before (on line 1685). This is actually not a bug as the `fstream` destructor always closes the file and line 1772 is redundant anyway.

I think it should be changed to correct code or removed altogether.

**Comment by kunaltyagi** [comment]
Thanks for reporting the bug @DiscreteLogarithm 

Would you mind creating a PR for this? 😄

**Comment by DiscreteLogarithm** [comment]
@kunaltyagi done
