### ISSUE TITLE
Hey I couldn't get this working. Can we please have some good examples of the color jet features to point clouds?

### ISSUE THREAD

**Issue by SiddhantNadkarni** [PointCloudLibrary/pcl#3600]
Hey I couldn't get this working. Can we please have some good examples of the color jet features to point clouds?

_Originally posted by @SiddhantNadkarni in https://github.com/PointCloudLibrary/pcl/pull/1581#issuecomment-578370294_

**Comment by VictorLamoine** [comment]
https://github.com/PointCloudLibrary/pcl/pull/1581#issuecomment-224101319

**Comment by SiddhantNadkarni** [comment]
It didn't work.

**Comment by kunaltyagi** [comment]
Please post more information than just "didn't work". What happened? How did you compile? What debugging steps did you follow?

Moreover, once resolved, please consider adding to the documentation of PCL to be better in the future. Did you consider asking this question to StackOverflow? Someone might be able to help you too

**Comment by SiddhantNadkarni** [comment]
Hi Kunal,

Sorry about that. I wanted to add a jet colormap/colorbar to my PCL Visualizer, as shown here: [#1581 (comment)](https://github.com/PointCloudLibrary/pcl/pull/1581#issuecomment-224101319) . However, it doesn't do that. I just get a plane white cloud i.e. the default color in the visualizer. 

My output: 
![screenshot-1580107720](https://user-images.githubusercontent.com/19183728/73154986-16300180-408e-11ea-8369-76b10e029be0.png)

The output I seek (as visualized on MATLAB): 
![CloudWithColMap](https://user-images.githubusercontent.com/19183728/73154996-221bc380-408e-11ea-8151-e1249a0ab16c.jpg)

My Code:
![Screen Shot 2020-01-26 at 10 50 26 PM](https://user-images.githubusercontent.com/19183728/73155054-4c6d8100-408e-11ea-9d84-44f0d453f351.png)

Compiled using CMake on gcc compiler.
