### ISSUE TITLE
Scope of variables can be reduced

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3608]
## Your Environment

* PCL Version: HEAD

## Context
Variables have unnecessarily large scope. Trim the scope to have better code

## Link for details
[Codacy of fork](https://app.codacy.com/manual/kunaltyagi/pcl/issues?bid=16056128&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjIxODkiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==)

**Comment by footyfreak** [comment]
@kunaltyagi , I would like to work on this. Is there any current progress or i shall start from scratch?

**Comment by kunaltyagi** [comment]
There's no active work on this issue.

**Comment by SergioRAgostinho** [comment]
A number of items were already addressed in #3665. Nurbs seems to be pending, but it might fall out of scope of a "good first issue".

**Comment by kunaltyagi** [comment]
3rd party is exempted, I guess. I'll get back with a new list excluding third party code

**Comment by kunaltyagi** [comment]
With the same link, there are 18 instances left (excluding 3rd party)
