### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3610]
## Your Environment

* PCL Version: HEAD

## Context
Variable are unneeded. Code can be simplified by removing them.

## Link for details
[Codacy of fork](https://app.codacy.com/manual/kunaltyagi/pcl/issues?bid=16056128&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjIwOTMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==)

**Comment by ChakshuGupta13** [comment]
Hey @kunaltyagi, I would like to help.
