### ISSUE TITLE
GPU/people_app is currently not compiling

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#3617]
Not sure if this issue is is already in 1.10.0, but currently I'm not able to compile the PCL (GCC-8):

```
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:390:3: error: reference to 'shared_ptr' is ambiguous
  shared_ptr<pcl::Grabber> capture;
  ^
/home/sunblack/dev/pcl/common/include/pcl/pcl_macros.h:90:3: note: candidate found by name lookup is 'pcl::shared_ptr'
  using shared_ptr = boost::shared_ptr<T>;
  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/shared_ptr.h:103:11: note: candidate found by name lookup is 'std::shared_ptr'
    class shared_ptr : public __shared_ptr<_Tp>
          ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:397:7: error: use of undeclared identifier 'capture'
      capture.reset( new pcl::OpenNIGrabber(openni_device) );
      ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:402:7: error: use of undeclared identifier 'capture'
      capture.reset( new pcl::ONIGrabber(oni_file, true, true) );
      ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:407:7: error: use of undeclared identifier 'capture'
      capture.reset( new pcl::PCDGrabber<PointXYZRGBA>(vector<string>(31, pcd_file), 30, true) );            
      ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:413:7: error: use of undeclared identifier 'capture'
      capture.reset( new pcl::PCDGrabber<PointXYZRGBA>(pcd_files, 30, true) );
      ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:417:7: error: use of undeclared identifier 'capture'
      capture.reset( new pcl::OpenNIGrabber() );      
      ^
/home/sunblack/dev/pcl/gpu/people/tools/people_app.cpp:459:23: error: use of undeclared identifier 'capture'
    PeoplePCDApp app(*capture, write);
```

**Comment by kunaltyagi** [comment]
PCL HEAD? or PCL 1.10?

**Comment by SunBlack** [comment]
master (I rebased my OpenMP branch)

**Comment by kunaltyagi** [comment]
What are your compile flags? I chased down some failing gpu builds, but I think my compile flags are not extensive if this error escaped.

The issue is a missing `#include <pcl/make_shared.h>` in the file.

**Comment by SunBlack** [comment]
I have everything enabled. But there is no missing include. The issue is another:

Because of:
https://github.com/PointCloudLibrary/pcl/blob/fce4141a7025ca9aad21a0e6b45af458914029b6/gpu/people/tools/people_app.cpp#L65-L66

the compiler does not know here:
https://github.com/PointCloudLibrary/pcl/blob/fce4141a7025ca9aad21a0e6b45af458914029b6/gpu/people/tools/people_app.cpp#L390
if it is a `pcl::shared_ptr` or a `std::shared_ptr`

**Comment by kunaltyagi** [comment]
🤦‍♂ Yeah, that should be `pcl::shared_ptr`. What are your GPU module related flags?

**Comment by SunBlack** [comment]
Which flags do you mean? It is just Ubuntu 19.10 like the Dockerfile, but with gcc-8, because of CUDA 10.2. Everything else is default. I just enabled everything in CMake with `BUILD_*`

**Comment by kunaltyagi** [comment]
I did compile using those flags, but I seemed to have missed this one. Are there any more errors? if no, then please create a PR and let's merge it in master

**Comment by SunBlack** [comment]
Yep, is the only compile issue. I'm currently trying to remove both usings, as prefix `pcl::` is used a lot of times there, so I don't believe we need this.

Will take a while because after switching back from my OpenMP branch the compiler has to rebuild everything.

Btw: This reminds me, that I have still have #3235 open (started to working on this, but I had compile error which I didn't understood 😢 )

**Comment by kunaltyagi** [comment]
Create an issue and shoot it my ways. I have had esoteric errors before

**Comment by kunaltyagi** [comment]
If you use make, there's a `make -t` which touches all files to prevent a recompile
