### ISSUE TITLE
Converter.cpp unable to find vtk_lib_io.h

### ISSUE THREAD

**Issue by Bradyk27** [PointCloudLibrary/pcl#3619]
## Your Environment

* Operating System and version: Mac OS 10.14.16
* Compiler: Clang 11.0.0
* PCL Version: 1.3

## Expected Behavior

Should be able to compile converter.cpp with no problem.

## Current Behavior

After successfully building with cmake, make returns an error that vtk_lib_io.h cannot be found although the file is exactly where it should be and other pre-made tools files have pulled files from the same directory w/ no issue.

## Code to Reproduce

CMAKELISTS:
`cmake_minimum_required(VERSION 2.6 FATAL_ERROR)
project(Converter)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(PCL 1.3 REQUIRED COMPONENTS common io)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_executable(converter converter.cpp)
target_link_libraries(converter ${PCL_LIBRARIES})
`

Converter.cpp can be found in io/tools.

**Comment by taketwo** [comment]
Is there a reason why you try to build converter as a standalone project? It's a part of PCL and, as such, is built when you build PCL.

**Comment by Bradyk27** [comment]
> Is there a reason why you try to build converter as a standalone project? It's a part of PCL and, as such, is built when you build PCL.

Yup, this fixed it. Sorry for the late reply, forgot I had opened this issue.
