### ISSUE TITLE
Remove deprecated headers introduced by #245

### ISSUE THREAD

**Issue by photoniker** [PointCloudLibrary/pcl#3625]
I have duplicated header files after the compilation of the pcl-INSTALL project. The directory install-path/include/pcl-1.10/pcl/recognition/ransac_based contains the same header files as the recognition directory. 

The compiler throws an error that functions are allready defined. 

## Your Environment

* Operating System and version: Win10 64bit
* Compiler: MSVC 2017
* PCL Version: 1.10.0

## Expected Behavior

only one defintion per function

## Current Behavior

duplicted definition in duplicated headers

## Possible Solution

use the headers from the recognition folder. Remove the duplicated headers in ransac_based

**Comment by taketwo** [comment]
Perhaps it's time to remove deprecated headers introduced in #245.
