### ISSUE TITLE
in_hand_scanner Intel RS D415 Compatibility

### ISSUE THREAD

**Issue by chrispduck** [PointCloudLibrary/pcl#3635]
I am trying to scan in some small objects using the Intel D415 stereo camera

* Operating System and version: Ubuntu 16.04 
* Compiler: g++
* PCL Version: 1.10

I installed the libraries from binaries and all seems fine with the installation.

When trying to run the application from /usr/local/bin with the command ./in_hand_scanner I get the error:

**ERROR in in_hand_scanner.cpp: void pcl::OpenNIGrabber::setupDevice(const string&, const pcl::OpenNIGrabber::Mode&, const pcl::OpenNIGrabber::Mode&) in /home/chris/Libs/pcl/io/src/openni_grabber.cpp @ 338 : No devices connected.
Segmentation fault (core dumped)**

I have also tried using the ROS version - ros_in_hand_scanner. It seems the D415 is also not able to connect. I have tried connecting to the camera via the realsense2 SDK and it works fine.

Any help would be appreciated!

**Comment by taketwo** [comment]
There are two issues here: 1) PCL does not have RealSense support on Linux and 2) the app in question is hard-coded to work with OpenNI cameras.
