### ISSUE TITLE
Dependency addition issue for VS2019 with pcl1.10.0

### ISSUE THREAD

**Issue by wz18207** [PointCloudLibrary/pcl#3638]
I‘m trying to add dependencies of pcl1.10.0 to VS2019.

## Your Environment

* Operating System and version: Windows 10 1803
* Compiler: VS2019 
* PCL Version: pcl 1.10.0

However I met the problem that I don't know which folder's *.lib should been added into the VS2019's project.

Here is my environment variables and my project's informations.
environment variables:
```
PCL_ROOT: D:\pcl1.10.0\PCL 1.10.0
Path: 
D:\pcl1.10.0\PCL 1.10.0\bin
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Boost\lib
D:\pcl1.10.0\PCL 1.10.0\3rdParty\FLANN\bin
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Qhull\bin
D:\pcl1.10.0\PCL 1.10.0\3rdParty\VTK\bin
```
2. VS2019
Release x64
VC++ contents:
```
IncludePath:
D:\pcl1.10.0\PCL 1.10.0\include\pcl-1.10;
C:\Program Files\OpenNI2\Include;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Boost\include\boost-1_72;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Eigen\eigen3;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\FLANN\include;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Qhull\include;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\VTK\include\vtk-8.2;$(IncludePath)

LibraryPath:
D:\pcl1.10.0\PCL 1.10.0\lib;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Boost\lib;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\FLANN\lib;
C:\Program Files\OpenNI2\Lib;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\Qhull\lib;
D:\pcl1.10.0\PCL 1.10.0\3rdParty\VTK\lib;$(LibraryPath)

SDL-Check
/sdl-

Preprocessor
_CRT_SECURE_NO_WARNINGS;
_SCL_SECURE_NO_WARNINGS;
_SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING;
_DEBUG;_CONSOLE;%(PreprocessorDefinitions)
```
Additional dependencies
I tried to add D:\pcl1.10.0\PCL 1.10.0\lib 's file names and the VTK's file names. However I met the compiler variable name conflict error.

Which file location's file name should I put that I could run my pcl's program completely.
Any help would be appreciated!

**Comment by dlazenby** [comment]
Not sure if this is helpful, but here are two Visual Studio prop sheets that I am using to include PCL 1.10.1 in my project.  It probably has more libs actually included than I am using, but this should be nearly a complete list of includes for most use cases, and therefore a user should just be able to add this prop sheet to their project via Property Manager and be able to build. 

NOTE: Users will need to customize the paths in this prop sheet.  I have PCL 1.10.1 installed at the default location but the OP here has a different location, and different version (1.10.0 vs 1.10.1)

NOTE: github apparently wont allow me to attach .props files directly, so I zipped them. One for Debug one for Release

[PCLPropSheets.zip](https://github.com/PointCloudLibrary/pcl/files/4576160/PCLPropSheets.zip)

**Comment by wz18207** [comment]
thanks! my friend.
I try it with pcl1.10.1 on VS and it works correctly.
Thanks for helping me!
