### ISSUE TITLE
Linker Error when registering PCLVisualizer keyboard callback

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#3641]
## Your Environment

* Operating System and version: MacOS Mojave
* Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
* PCL Version: 8888816e8d0d0db4133786d9fdc42ce55cd893d8

## Context
I installed 8888816e8d0d0db4133786d9fdc42ce55cd893d8 from source and code that previously worked, is somehow broken now.

## Expected Behavior

Program registering Keyboard Callback for PCLVisualizer links successfully

## Current Behavior
```
Undefined symbols for architecture x86_64:
  "pcl::visualization::PCLVisualizer::registerKeyboardCallback(boost::function<void (pcl::visualization::KeyboardEvent const&)>)", referenced from:
      _main in foo.cpp.o
```

## Code to Reproduce

**CMakeLists.txt**

```
if(CMAKE_MINIMUM_REQUIRED_VERSION)
  cmake_minimum_required(VERSION ${CMAKE_MINIMUM_REQUIRED_VERSION})
else()
  cmake_minimum_required(VERSION 3.15.0)
endif()

project(foo)

include_directories(${CMAKE_CURRENT_LIST_DIR})

find_package(PCL 1.9 REQUIRED COMPONENTS io visualization filters)
add_executable(pointcloud-viewer ${CMAKE_CURRENT_LIST_DIR}/foo.cpp)
target_compile_definitions(pointcloud-viewer PRIVATE ${PCL_DEFINITIONS})
target_link_directories(pointcloud-viewer PRIVATE ${PCL_LIBRARY_DIRS})
target_link_libraries(pointcloud-viewer ${PCL_LIBRARIES})
```

**foo.cpp**

```
#include <pcl/visualization/pcl_visualizer.h>

using namespace pcl;
using namespace pcl::visualization;

int main(int argc, char *argv[])
{
  PCLVisualizer visualizer("Standalone viewer.");
    auto kbd_connection = visualizer.registerKeyboardCallback(
        [&](const KeyboardEvent& event) {
        std::cout << "Wat" << std::endl;
        });

    return 0;
}
```

This used to work. I am also confused as to why the linker is looking for an overload taking `boost::function` as parameter, since the API says `std::function` is used. Since it compiles successfully, it seems to have to do something with template instantiation. Not sure.

**Comment by themightyoarfish** [comment]
Solution: Don't have several PCL versions installed at the same time. In my case, I had pcl 1.9 from homebrew and 1.10 from the source install.

**Comment by kunaltyagi** [comment]
> Don't have several PCL versions installed at the same time

I'll add this in the FAQ currently WIP. BTW, I didn't notice it before but I like how the hash is almost all 8s
