### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by tiexuedanxin** [PointCloudLibrary/pcl#3646]
sorry to bother you, i can't achieve a good performance with your code, could you make a statement of your code and provide some datasets to me, thank you very much.

**Comment by kunaltyagi** [comment]
> i can't achieve a good performance with your code

Please quantify `good performance`. Could you narrow down what you meant by `your code`? PCL is huge.

**Comment by tiexuedanxin** [comment]
it's just the ppf_object_recognition.cpp. could you provide some datasets and make a statement how to get a good performance.

**Comment by taketwo** [comment]
AFAIK there are numerous bugs in PCL's PPF implementation. You may have better luck with OpenCV's implementation.

**Comment by tiexuedanxin** [comment]
i want to modify the PCL's implementation of ppf, but i don't know how split the ppf code from the PCL. Could you help me.

**Comment by taketwo** [comment]
I'm afraid providing guidance on such matters is beyond our capacity, sorry.

**Comment by tiexuedanxin** [comment]
sorry to bother you, i have test your code with my dataset but can't get a good performance and don't know why. I have segment the scene object from the background, the dataset and result are as follow, please help, thank you for advance.

从QQ邮箱发来的超大附件

model.pcd (18.40M, 2020年02月20日 10:57 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0b61623996adbcc878c94215133557195602010e075155501856045f0418515705034f005651031b0607510805575d570202005d353c655b5a0507551b450652355c&code=5ab955e6




scene.pcd (36.47M, 2020年02月20日 10:57 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e396338300f88c87d9143141665021a5201535e035208071d5f530b5548040656004e005557521855085609045c02025658500a306c3046535c0d5d1e1553513004&code=09c80e05
