### ISSUE TITLE
clang fails with a cast "loses const" error

### ISSUE THREAD

**Issue by finostro** [PointCloudLibrary/pcl#3647]
Trunk does not compile with clang , besause of a reinterpret cast loses the const , on bivariate_polinomial.hpp. 

## Your Environment

* Operating System and version: Ubuntu 18.04
* Compiler: clang-10
* PCL Version: trunk

## Expected Behavior

I compiles with clang

## Current Behavior

Fails at 
`pcl/pcl/common/include/pcl/common/impl/bivariate_polynomial.hpp:269:13: error: reinterpret_cast from 'const int *' to 'char *' casts away qualifiers
  os.write (reinterpret_cast<char*> (&degree), sizeof (int));`

## Code to Reproduce

trunk , using clang-10

## Possible Solution

A Quick fix is to just add the const to bivariate_polynomial.hpp:269 and bivariate_polynomial.hpp:271

**Comment by kunaltyagi** [comment]
@finostro Please create a PR for this change. Good eyes for noticing the warning 😄

**Comment by finostro** [comment]
> @finostro Please create a PR for this change. Good eyes for noticing the warning smile
It's an error. 
I am looking up how to do that now.

**Comment by kunaltyagi** [comment]
You can use the Github interface to create a fork and then follow [this official help page](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
