### ISSUE TITLE
Unable to find the dataset for training pcl head pose estimation api

### ISSUE THREAD

**Issue by shomedas** [PointCloudLibrary/pcl#3653]
The existing pcl api "pcl_face_trainer" needs biwi head pose dataset **in pcl format** as described in blog http://pointclouds.org/blog/hrcs/aaldoma/index.php. As per the pdf attached to the blog, the dataset is at http://svn.pointclouds.org/data/biwi_face_database/pcl_biwi_version.tar.bz2. However when i tried to checkout from this link. I got message:

svn: E170013: Unable to connect to a repository at URL 'http://pointclouds.org/data/biwi_face_database/pcl_biwi_version.tar.bz2'
svn: E160013: '/data/biwi_face_database/pcl_biwi_version.tar.bz2' path not found

command used: svn checkout http://svn.pointclouds.org/data/biwi_face_database/pcl_biwi_version.tar.bz2 pcl_biwi_version.tar.bz2

How do I get access to the head pose dataset **in pcl format**.  It is somewhere in pcl repo, but I could not find it.

**Comment by taketwo** [comment]
Maybe this? https://github.com/PointCloudLibrary/data/tree/master/biwi_face_database
