### ISSUE TITLE
Please Help.

### ISSUE THREAD

**Issue by tiexuedanxin** [PointCloudLibrary/pcl#3658]

**Comment by rimmartin** [comment]
performance as in computation time?

How is your pcl build configured?

```
cmake --help-variable CMAKE_BUILD_TYPE
```
will show possible configs and give other suggestions. Also how are you set up to speed  up [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page)? I believe Intel has now made [MKL](https://software.intel.com/en-us/mkl) available
