### ISSUE TITLE
vcpkg install pcl[pcap] is failed on ubuntu 18.04

### ISSUE THREAD

**Issue by yes89929** [PointCloudLibrary/pcl#3660]
In installing pcl with pcap using vcpkg on ubuntu.
vcpkg try to install winpcap, not libpcap.

Computing installation plan...
The following packages will be built and installed:
    pcl[core,pcap]:x64-linux
  * winpcap[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: winpcap:x64-linux
Building package winpcap[core]:x64-linux...
-- Using cached /vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Using cached /vcpkg/downloads/Wpcap_license.htm
-- Extracting source /vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch /vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch /vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch /vcpkg/ports/winpcap/create_lib.patch
-- Applying patch /vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at /vcpkg/buildtrees/winpcap/src/4_1_3-100e7825a0
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: devenv.exe Packet.sln /Upgrade
    Working Directory: /vcpkg/buildtrees/winpcap/src/4_1_3-100e7825a0/packetNtx/Dll/Project
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  ports/winpcap/portfile.cmake:59 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package winpcap:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: winpcap:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by kunaltyagi** [comment]
This doesn't belong here. Please use the provided link to submit an issue on vcpkg instead
