### ISSUE TITLE
1.11.0 Release

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3661]
## Context
Next version release with backlog items + new features.

Backlog from #2772 (1.10.0 Release)
- [x] memory #2792

Backlog moved to 1.12.0 Release pending discussion regarding the status of random in PCL (#3996)
- [ ] random generators #2803 #2963 #2964 #2985 #2988 #2955

PS: It might be more prudent to do a faster release since 1.9.1 was on 2018 Nov 26 and 1.10 was on 2020 Jan 20. Scheduled releases might be better (aka every `N` months, come hell or high water) to prevent huge changes and giving something new every release. Some will be small, some will be large; doesn't matter.

**Comment by taketwo** [comment]
I recall discussing scheduled (aka "regular") releases quite a few times. Let's see how far we get this time :)

I'd like to have 1.10.1 soon because we had some header issues in 1.10.0.

**Comment by kunaltyagi** [comment]
What's blocking 1.10.1? Doing it before GSoC kicks would be best. There's already a lot of commits since 1.10, some might be breaking API/ABI (don't remember which one. It would be one of mine though)

**Comment by taketwo** [comment]
> some might be breaking API/ABI

At least none are labeled as such: https://github.com/PointCloudLibrary/pcl/pulls?page=2&q=is%3Apr+merged%3A%3E2020-01-19&utf8=%E2%9C%93

> What's blocking 1.10.1? 

I want to try to build a large codebase that uses plenty of PCL. Some ROS packages and proprietary projects at my company. So far no time :(

**Comment by tompollok** [comment]
Is it planned to completely deboostify pcl with 1.11 release?

**Comment by kunaltyagi** [comment]
We're on track to do that, but I don't know when we plan to flip the switch.

**Comment by kunaltyagi** [comment]
@taketwo you mentioned you compile PCL for some open (and closed) source projects. Which ones are those? That'll help in creating a release pipeline

**Comment by taketwo** [comment]
At my company, we use a lot of PCL+ROS. We package PCL ourselves, as well as those ROS packages that depend on it.

**Comment by kunaltyagi** [comment]
IIRC, PCL is an indirect dependency of other ROS packages, via the package [perception_pcl](https://github.com/ros-perception/perception_pcl). Just compiling `perception_pcl` would be sufficient for starters, right?

**Comment by taketwo** [comment]
Here is what I get with `$ apt-cache rdepends --installed libpcl-dev | uniq` on my system (proprietary packages stripped):

```
  ros-melodic-cartographer-ros
  ros-melodic-pcl-ros
  ros-melodic-pcl-conversions
```

So yes, I think `perception_pcl` would be sufficient for starters.

**Comment by kunaltyagi** [comment]
Note to self: `kinetic` and `melodic` are the active distributions

**Comment by kunaltyagi** [comment]
Where can I find the cmake flags used in configuration for debian release?

**Comment by jspricke** [comment]
https://sources.debian.org/src/pcl/1.10.1+dfsg-1/debian/rules/
and dpkg-buildflags

**Comment by SergioRAgostinho** [comment]
Debian is building with it's packages with clang :open_mouth:

**Comment by jspricke** [comment]
https://salsa.debian.org/science-team/pcl/-/commit/0cf19f69887891f6fcdf43863e49dcc608cc62c4
