### ISSUE TITLE
WIN32 instead of _WIN32 used in PCL

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3670]
## Your Environment

* Operating System and version: Windows
* PCL Version: HEAD

## Context
Accidentally `WIN32` and `WIN64` has been used for Windows OS detection instead of `_WIN32` and `_WIN64` (notice the underscore)

## Possible Solution
* Replacement of `WIN32` with `_WIN32`
* Compile test
* Behavior verification

**Comment by FSund** [comment]
I just noticed there are also some `WIN64` instances, like here: https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_system.h#L135

Are those valid?

That file also seems to indicate that `windows.h` has nested includes that define `WIN32`: https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_system.h#L142

**Comment by FSund** [comment]
I found an instance of

````
#ifndef WIN32
#define WIN32
#endif
```

in `minwindefs.h` in the headers that come with mingw, so it does seem like both ``_WIN32` and `WIN32` might appear on Windows platforms.

**Comment by kunaltyagi** [comment]
* _WIN64 implies _WIN32
* [Official docs](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019) don't claim WINXX, only _WINXX

I'm not a windows user, but from an implementor's PoV, I'd not recommend to keep the un-underscored versions. Maybe someone else can chime in with the recommended course of action.

**Comment by larshg** [comment]
WIN32 is added manually to the [default CXX flag] (https://github.com/PointCloudLibrary/pcl/blob/fe10b7619db9a89831b5ad418a265272ea15581e/CMakeLists.txt#L88)s if compiler is MSCV.

And atleast here it ends up in the definitions:

![image](https://user-images.githubusercontent.com/1165340/75225303-a1460980-57aa-11ea-9e43-257f0daf8f90.png)

Not sure if it applies to MSYS2/Mingw as @FSund uses?

**Comment by FSund** [comment]
`CMAKE_COMPILER_IS_MSVC` is false for mingw, so I don't think I would have ``WIN32` defined from there. That might be the reason for the issue I had in #3667.
