### ISSUE TITLE
Minor Release 1.10.1

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3675]
## Context
There should be a release 1.10.1 to fix some compilation issues in PCL 1.10 (which are visible because those modules aren't distributed, but they remain issue nonetheless)

## Next step
Compile PCL and test against a selection of packages, open and closed source.

**Comment by kunaltyagi** [comment]
Is there any issue (compilation, linking, test, etc.) on the master branch holding the release?

**Comment by UnaNancyOwen** [comment]
I have published PCL 1.10.1 All-in-one Installer on [release page](https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.10.1).
