### ISSUE TITLE
ConvexHull crashes in debug mode only

### ISSUE THREAD

**Issue by tommasocarella** [PointCloudLibrary/pcl#3678]
Hi everyone,

I am currently having an issue while trying to perfrom the convexHull reconstruction in debug mode; while in release mode it works just fine, in debug mode I got an access violation error at line 350 of the convex_hull.hpp file.

## Your Environment

* OS Microsoft Windows 10 Pro v10.0.17763 build 17763
* Microsoft Visual Studio Professional 2019 Version 16.4.5
* pcl 1.9.1-10 installed by vcpkg (Vcpkg package management program version 2020.02.04-nohash)
* HW: System Model HP Z2 Tower G4 Workstation, x64, Processor Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz, 3000 Mhz, 6 core, 6 processors, Memory (RAM) 8,00 GB

## Context

What I am trying ot do is to obtain a convex hull of a point cloud in order to use it to crop the Poisson-reconstructed mesh. In debug mode only I obtain an access violation error at line 350 of convex_hull.hpp file "int num_facets = qh  num_facets;" (see attached image).
In issue #369 someone had a similar problem due to the fact that qhull 2012 was not supported by the last version at the time.

## Expected Behavior

The function should reconstruct the convex hull.

## Current Behavior

convexHull algorithm gets an access violation at line 350 of convex_hull.hpp file "int num_facets = qh  num_facets;".

![Exception_Thrown](https://user-images.githubusercontent.com/14278767/75328281-0e769f00-587e-11ea-81a6-36d4e9f86a8f.png)

## Code to Reproduce

	PointCloud<PointXYZRGB>::Ptr convexHullPC(new PointCloud<PointXYZRGB>);
	PointCloud<PointXYZRGB>::Ptr toBeFilteredPC(new PointCloud<PointXYZRGB>);
	PointCloud<PointXYZRGB>::Ptr originalPC(new PointCloud<PointXYZRGB>);
	vector<Vertices> polygonsConvexHull;
	fromPCLPointCloud2(meshInput.cloud, *toBeFilteredPC);

	ConvexHull<PointXYZRGB> convexHullCalculation;

	convexHullCalculation.setInputCloud(originalPC);
	convexHullCalculation.reconstruct(*convexHullPC, polygonsConvexHull); // Access violation

**Comment by kunaltyagi** [comment]
Thanks for linking the issue. What version of QHull are you using? The vcpkg default or something else?

**Comment by tommasocarella** [comment]
Hi @kunaltyagi thank you for the quick reply. I am using the 7.3.2 version of QHull which I think is the default one when installing PCL 1.9.1 through Vcpkg.

**Comment by jafrado** [comment]
The vcpkg debug mode has an issue still - see here for the details - https://github.com/microsoft/vcpkg/pull/9923 - if you follow the PCL pipeline options you should be able to build it fine yourself without vcpkg. I'm still waiting for this to be fixed - @larshg found the issue.

**Comment by tommasocarella** [comment]
Hi @jafrado, thank you for your answer and for liniking the vcpkg issue! I will try your workaround and see what happens.
Just a quick clarification, my solution already works in release mode as it is but crashes in debug mode; does your workaround fix the problems in the debug mode, too?
Thank you again

**Comment by yes89929** [comment]
This problem was solved.
Try reinstall.
https://github.com/microsoft/vcpkg/pull/9923
