### ISSUE TITLE
Compilation error with MSYS2 mingw-w64, 'M_PI' was not defined in this scope

### ISSUE THREAD

**Issue by FSund** [PointCloudLibrary/pcl#3679]
When compiling pcl on Windows using MSYS2 mimgw-w64 I get a lot of `'M_PI' was not declared in this scope` errors.

Full error log
```
[  0%] Building CXX object common/CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.obj
cd /C/msys64/home/filip.sund/code/pcl-fsund/build/common && /C/msys64/mingw64/bin/g++.exe  -DBOOST_LIB_DIAGNOSTIC -DBOOST_THREAD_USE_LIB -DPCLAPI_EXPORTS -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -I/C/msys64/mingw64/include/vtk-8.2 -I/C/msys64/mingw64/include/freetype2 -I/C/msys64/mingw64/include/double-conversion -I/C/msys64/home/filip.sund/code/pcl-fsund/build/include -I/C/msys64/home/filip.sund/code/pcl-fsund/common/include -isystem /C/msys64/mingw64/include/eigen3 -isystem /C/msys64/home/filip.sund/code/pcl-fsund/recognition/include/pcl/recognition/3rdparty  -Wabi=11 -Wall -Wextra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion -march=native -msse4.2 -mfpmath=sse  -mwin32 -mthreads -O3 -DNDEBUG   -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -std=c++14 -o CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.obj -c /C/msys64/home/filip.sund/code/pcl-fsund/common/src/bearing_angle_image.cpp
C:/msys64/home/filip.sund/code/pcl-fsund/common/src/bearing_angle_image.cpp: In member function 'double pcl::BearingAngleImage::getAngle(const pcl::PointXYZ&, const pcl::PointXYZ&)':
C:/msys64/home/filip.sund/code/pcl-fsund/common/src/bearing_angle_image.cpp:78:73: error: 'M_PI' was not declared in this scope
   78 |     theta = std::acos ((a + b - c) / (2 * sqrt (a) * sqrt (b))) * 180 / M_PI;
      |                                                                         ^~~~
make[2]: *** [common/CMakeFiles/pcl_common.dir/build.make:258: common/CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.obj] Error 1
make[2]: Leaving directory '/home/filip.sund/code/pcl-fsund/build'
make[1]: *** [CMakeFiles/Makefile2:1033: common/CMakeFiles/pcl_common.dir/all] Error 2
make[1]: Leaving directory '/home/filip.sund/code/pcl-fsund/build'
make: *** [Makefile:152: all] Error 2
```

The first error is in `bearing_angle_image.cpp`, but I see `M_PI` is used in many other places as well.

Exact steps to reproduce are:
 - Install MSYS2 and all dependencies on Windows 10
 - Clone pcl
```
cd pcl
mkdir build
cd build
cmake -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
make
```

## How to fix
What I did was to just add a top-level `add_definitions(-D_USE_MATH_DEFINES)` to `CMakeLists.txt`, but I realize this is not the proper way to fix this.

I see some trickery is happening on Windows in [pcl_macros.h](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/pcl_macros.h#L115), but I am not certain if there is a similar way to do it for MSYS2.

~~I think the root issue is that the CMake command `set(CMAKE_CXX_STANDARD 14)` causes the `-std=gnu++14` flag to be added on Linux, but on Windows+MSYS2 the `-std=c++14` flag is added instead. This that `M_PI` is not defined on MSYS2, since that macro is not part of the C++14 standard.~~ This is not true. Since we have `set(CMAKE_CXX_EXTENSIONS OFF)` Linux, the flag is the same on Linux and Windows/MSYS2. 

## Your Environment

* Operating System and version: Windows 10, Version 10.0.18363 Build 18363
* Compiler: g++.exe (Rev2, Built by MSYS2 project) 9.2.0
* PCL Version: commit b1d9c7edd3eddd8f6f8626919b4667869459ceb7

**Comment by kunaltyagi** [comment]
I think mingw is simply broken due to assumption of msvc. Since it seems you are using MinGW, could you please help to improve the support on CI? That'd be a nice help apart from PR to resolve the issues.

**Comment by FSund** [comment]
What assumption of MSVC do you mean? That Windows == MSVC?

I have no experience with CI unfortunately.

**Comment by taketwo** [comment]
Regarding your fix idea, we already have that define in `pcl_macros.h`:

https://github.com/PointCloudLibrary/pcl/blob/b1d9c7edd3eddd8f6f8626919b4667869459ceb7/common/include/pcl/pcl_macros.h#L58-L59

Regarding `gnu++14`, is this true? Because we have `set(CMAKE_CXX_EXTENSIONS OFF)` in our CMakeLists, so extensions should not be used.

**Comment by kunaltyagi** [comment]
> That Windows == MSVC?

Yeah. We compile and test on Windows using only MSVC

> Regarding gnu++14, is this true?

No, I tested and PCL definitely uses `c++14` and not `gnu++14` as the compiler flag

**Comment by FSund** [comment]
Sorry, I was just assuming the `gnu++14` flag was being added on Linux, didn't realize you had  `set(CMAKE_CXX_EXTENSIONS OFF)`.

It's kind of strange the `#define _USE_MATH_DEFINES` in `pcl_macros.h` doesn't seem to be registering when I'm compiling. I'll have a look into 

I'll have a look at the yaml files and try to make a PR after I've fixed the compilation issues I'm having.

**Comment by FSund** [comment]
I think I might be on to something. The first `'M_PI' was not declared` error I get is in `bearing_angle_image.cpp` at line 78

https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/src/bearing_angle_image.cpp#L78

Now, the first include in this file is

https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/src/bearing_angle_image.cpp#L43

and the first lines of `eigen.h` are

https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/include/pcl/common/eigen.h#L43-L55

So this is the first time the `cmath` header is included in the context of `bearing_angle_image.cpp`, and no `_USE_MATH_DEFINES` has been defined so far. This means that `M_PI` should not be available at all in `bearing_angle_image.cpp`, or am I misunderstanding something? 

I'm not sure why compilation works on other platforms/compilers though, since the code would be the same for those.

Now if we just swap L55 and L56 of `eigen.h` 

https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/include/pcl/common/eigen.h#L55-L56

it seems like the error would go away, since `ModelCoefficients.h` includes `pcl_macros.h` (a couple of includes deep) before the `cmath` header is included. But I'm still not sure if this is the actual issue here, since compilation works on other platforms.

**Comment by kunaltyagi** [comment]
Could you check if #3545 fixes this issue?

**Comment by FSund** [comment]
I'll check that PR asap, but I've made several discoveries lately:

* Seems like Eigen includes `cmath` in some places, so you need to be very careful of the order in which Eigen is included, since any includes after that (even with `_USE_MATH_DEFINES`) will not lead to `M_PI` being defined. 
  * https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/Core#L72
  * https://gitlab.com/libeigen/eigen/-/blob/master/unsupported/Eigen/CXX11/Tensor#L36

* You already have the necessary `M_PI` and similar defines in `pcl_macros.h`, but they are only enabled for Windows+MSVC. Instead of relying on `M_PI` being defined in external headers I would just enable this code for all platforms, or perhaps put the definitions in a separate file. Any reasons why this would be a bad idea?
https://github.com/PointCloudLibrary/pcl/blob/b1d9c7edd3eddd8f6f8626919b4667869459ceb7/common/include/pcl/pcl_macros.h#L107-L123
I changed
https://github.com/PointCloudLibrary/pcl/blob/b1d9c7edd3eddd8f6f8626919b4667869459ceb7/common/include/pcl/pcl_macros.h#L103
to

      #if defined _WIN32 && (defined _MSC_VER || defined __MINGW32__)

  and everything compiled fine with mingw-w64 (as long as I remember `add_definitions(-DPCL_ONLY_CORE_POINT_TYPES)`).

**Comment by FSund** [comment]
#3545 did not fix the issue, compilation fails in the same place as before

```
Building CXX object common/CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.obj
cd /C/msys64/home/filip.sund/code/pcl/build/common && /C/msys64/mingw64/bin/g++.exe  -DBOOST_LIB_DIAGNOSTIC -DBOOST_THREAD_USE_LIB -DPCLAPI_EXPORTS -DPCL_ONLY_CORE_POINT_TYPES -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -I/C/msys64/mingw64/include/vtk-8.2 -I/C/msys64/mingw64/include/freetype2 -I/C/msys64/mingw64/include/double-conversion -I/C/msys64/home/filip.sund/code/pcl/build/include -I/C/msys64/home/filip.sund/code/pcl/common/include -isystem /C/msys64/mingw64/include/eigen3 -isystem /C/msys64/home/filip.sund/code/pcl/recognition/include/pcl/recognition/3rdparty  -Wabi=11 -Wall -Wextra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion -march=native -msse4.2 -mfpmath=sse  -mwin32 -mthreads -O3 -DNDEBUG   -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -std=c++14 -o CMakeFiles/pcl_common.dir/src/bearing_angle_image.cpp.obj -c /C/msys64/home/filip.sund/code/pcl/common/src/bearing_angle_image.cpp
C:/msys64/home/filip.sund/code/pcl/common/src/bearing_angle_image.cpp: In member function 'double pcl::BearingAngleImage::getAngle(const pcl::PointXYZ&, const pcl::PointXYZ&)':
C:/msys64/home/filip.sund/code/pcl/common/src/bearing_angle_image.cpp:84:73: error: 'M_PI' was not declared in this scope
   84 |     theta = std::acos ((a + b - c) / (2 * sqrt (a) * sqrt (b))) * 180 / M_PI;
      |                                                                         ^~~~
```
