### ISSUE TITLE
[Question] Qualified vs Unqualified lookup in pcl namespace

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3689]
## Context
Current code has both qualified names (`pcl::ModelCoefficients`) as well as unqualified code (`PointCloud<T>`) living inside `namespace pcl` scope.

There isn't any real benefit for using qualified names since we are not using any other namespace (eg: `using namespace boost;`). ADL prevention is a benefit but doesn't apply in our case sine these are variable declarations, not function calls.

## Current Behavior
Mix bag

## Question
Which one to choose for future code?

**Comment by SergioRAgostinho** [comment]
Inside our own namespace I am inclined to use unqualified. For examples, tutorials and other consumer code, use qualified.

**Comment by taketwo** [comment]
I have the same sentiment; library code does not need to be qualified, but everything that is a potential source for copy/pasting into consumer code should use qualified names.
