### ISSUE TITLE
Ubuntu16.04 fails to compile PCL1.10.0 source code

### ISSUE THREAD

**Issue by HongShiKuan** [PointCloudLibrary/pcl#3703]
The following dependencies are installed before compiling the source code：
`sudo apt-get update`
`sudo apt-get install git build-essential linux-libc-dev`
`sudo apt-get install cmake cmake-gui`
`sudo apt-get install libusb-1.0-0-dev libusb-dev libudev-dev`
`sudo apt-get install mpi-default-dev openmpi-bin openmpi-common`
`sudo apt-get install libflann1.8 libflann-dev`
`sudo apt-get install libeigen3-dev`
`sudo apt-get install libboost-all-dev`
`sudo apt-get install libvtk6.2 libvtk6.2-qt libvtk6-dev`
`sudo apt-get install libqhull* libgtest-dev`
`sudo apt-get install freeglut3-dev pkg-config`
`sudo apt-get install libxmu-dev libxi-dev`
`sudo apt-get install mono-complete`
`sudo apt-get install qt-sdk openjdk-8-jdk openjdk-8-jre`
`sudo apt-get install libopenni-dev libopenni2-dev`

When I make the code to 96%, I encountered the following error：
**error: ‘shared_ptr’ does not name a type;**
**error: ‘ConstPtr’ in ‘struct MapsBuffer::MapsRgb’ does not name a type**
**error: ‘ConstPtr’ is not a member of ‘MapsBuffer::MapsRgb’**
**error: ‘ConstPtr’ is not a member of ‘MapsBuffer::MapsRgb’**
**error: ‘class MapsBuffer’ has no member named ‘getFront’**

![2020-03-02 23-38-38屏幕截图](https://user-images.githubusercontent.com/45912889/75692131-0a180f00-5ce0-11ea-9c67-d9a58ecf8e95.png)

What is the problem? I currently use gcc7 and g ++ 7, which support C ++ 11. I hope I can get help. Thanks.

**Comment by kunaltyagi** [comment]
There are some issues on 1.10.0 release which will be remedied by 1.10.1 release. Please use the master HEAD in the meantime instead. 1.10.1 has not been scheduled, but consider it imminent.
