### ISSUE TITLE
pcl visualizer had not properly working on windows 

### ISSUE THREAD

**Issue by vigneshsara** [PointCloudLibrary/pcl#3705]
## Your Environment

* Operating System and version:windows
* Compiler:
* PCL Version:1.8.1

## Context
pcl visualizer had not properly working on windows ,some it produce the point like line 

## Current Behavior
![Screenshot ](https://user-images.githubusercontent.com/31008646/75780538-8f9fcb80-5d81-11ea-9746-5c71f10799a4.png)

**Comment by kunaltyagi** [comment]
@vigneshsara Could you give more information on how to reproduce the issue? What point cloud you used? How did you install PCL?

Note to maintainers: I labelled it as tools, it might be visualizer instead.

**Comment by vigneshsara** [comment]
@kunaltyagi 1. This error is Inconsitent.Run this application for 2 -3 minutes its may happen.and i have run this same code and same version of pcl in my linux pc its working without any issue.
2.build the pcl from source

**Comment by kunaltyagi** [comment]
> i have run this same code and same version of pcl in my linux pc its working without any issue

Thanks. This helps in narrowing the issue to Windows only.

Could you give us a very small code that can be compiled and a PCD file which can be used to recreate the error? ACK: the run-test will be flaky.

**Comment by UnaNancyOwen** [comment]
> * PCL Version: 1.8.1

In addition, Please confirm whether it is reproduced with the latest release (1.10.0) this problem.

**Comment by larshg** [comment]
Close in lack of response?

**Comment by kunaltyagi** [comment]
Usually, we give 1 month (for PR to mark as stale). Similar time here too. BTW, we should configure it to close issues with "author reply" label

**Comment by larshg** [comment]
Its posted 3. of march and haven't had any activities since 4. of march, which is more than 1 month ago :) ?
