### ISSUE TITLE
pcl 1.10.0-darwin tarball cannot be used on MacOS Catalina 10.15.3 

### ISSUE THREAD

**Issue by keesblom** [PointCloudLibrary/pcl#3707]
After download and unpack https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.10.0/pcl-1.10.0-darwin.md5sum-5d03bb0d044487b929b5ed2f46b70f95.tar.bz2
opening pcl-1.10.0-darwin/bin/pcl_viewer.app/
results in the error message:
![image](https://user-images.githubusercontent.com/11407442/75788089-03cd7580-5d68-11ea-9078-6ebb60934b03.png)
Similar for other executables that link with dynamic libraries in  pcl-1.10.0-darwin/lib.

This does not happen on MacOS Mojave 10.14.1.

Since MacOS 10.15 and up, Apple requires software distributions to use their "Notarization Service"
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by kunaltyagi** [comment]
> MacOS 10.15 and up, Apple requires software distributions to use their "Notarization Service"

Thanks for informing us. Sadly, my XCode is not willing to compile so I'm unable to help (since I was the person who uploaded the original tarball for 1.10.0).

However, if I'm not mistaken, you can circumvent the issue by using the following workflow: `System Preferences > Security & Privacy > General > Allow XYZ app > credential-verification`

**Comment by shrijitsingh99** [comment]
Apart from what @kunaltyagi  suggested, you can also use this to whitelist the app using CLI:
```sh
xattr -d com.apple.quarantine /path/to/app
```

**Comment by keesblom** [comment]
> On 3 Mar 2020, at 16:32, Kunal Tyagi <notifications@github.com> wrote:
> 
> MacOS 10.15 and up, Apple requires software distributions to use their "Notarization Service"
> 
> Thanks for informing us. Sadly, my XCode is not willing to compile so I'm unable to help (since I was the person who uploaded the original tarball for 1.10.0).
> 
> However, if I'm not mistaken, you can circumvent the issue by using the following workflow: System Preferences > Security & Privacy > General > Allow XYZ app > credential-verification

Thanks for your reply.

On my MacOS 10.15.3 Catalina installation at  "System Preferences > Security & Privacy > General >  Allow apps downloaded from:"
I only have the options:

o App Store
o App Store and identified developers

When I get the error message shown in my Issue Report, in "System Preferences > Security & Privacy > General"
I see the same error message and the extra option “Open Anyway”

However, these (tedious) actions are needed for every (90) executables and for every (21) libraries at first use after download.

After that things work normally.

So for the most recent MacOS version Apple wants developers only to distribute binaries that are suitably signed,
in their (justified) fight against malware.

**Comment by kunaltyagi** [comment]
I agree this is tedious, but sadly for now, until I (or someone with MacOS) have time to do this properly, this is the only solution. 😞
