### ISSUE TITLE
MarchingCubes is not setting meaningful resolution in default ctor

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3717]
Default ctor
https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/surface/include/pcl/surface/marching_cubes.h#L377-L383

The attributes
https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/surface/include/pcl/surface/marching_cubes.h#L436-L442

It won't produce results without proper values e.g.: 32x32x32. First time users then get confused at the absence of output, assuming it doesn't outright segfault.

**Comment by divmadan** [comment]
Can we call the `setGridResolution` function in the default constructor, and set the values as 32x32x32?
```
inline void
      setGridResolution (int res_x, int res_y, int res_z)
```

**Comment by SergioRAgostinho** [comment]
Use initialization just like here
https://github.com/PointCloudLibrary/pcl/blob/0bb69c0c795e852ddd731039cc1b0ac96b11d8ed/common/include/pcl/PCLHeader.h#L17-L23
