### ISSUE TITLE
[MacOS CI] Issue with cmath, boost and Apple

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3722]
## Your Environment

* Operating System and version: MacOS 10.14 (CI)
* Compiler: AppleClang 11
* PCL Version: HEAD

## Context
MacOS CI is red

## Current Behavior
```
/usr/local/include/boost/math/special_functions/fpclassify.hpp:552:17: error: no member named 'isnan' in namespace 'std'; did you mean simply 'isnan'?
        return (std::isnan)(x);
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:885:9: note: 'isnan' declared here
   bool isnan BOOST_NO_MACRO_EXPAND(T t);
        ^
```

**Comment by SergioRAgostinho** [comment]
Probably the same as #2601

**Comment by kunaltyagi** [comment]
Possibly. Apple loves breaking non XCode tool-chain. We'll most likely have to wait for an update?

**Comment by SergioRAgostinho** [comment]
Any idea of where to report this? It feels like something that the team from Azure pipelines should be aware. They have too many `azure-pipelines-*` [repos](https://github.com/microsoft?q=azure-pipelines&type=&language=) :/

**Comment by shrijitsingh99** [comment]
> Any idea of where to report this? It feels like something that the team from Azure pipelines should be aware. They have too many `azure-pipelines-*` [repos](https://github.com/microsoft?q=azure-pipelines&type=&language=) :/

An issue can be created at [virtual-environments](https://github.com/actions/virtual-environments) since [azure-pipelines-image-generation](https://github.com/microsoft/azure-pipelines-image-generation) has been replaced.

> Possibly. Apple loves breaking non XCode tool-chain. We'll most likely have to wait for an update?

Can we not switch to using the XCode bundled toolchain instead of being dependent on updates to the VM-image?

**Comment by kunaltyagi** [comment]
> switch to using the Xcode bundled toolchain

That's a possibility and IMO probably better for MacOS. If your build succeeds, please go ahead with a PR 😄

**Comment by shrijitsingh99** [comment]
So I did some more testing and only the Xcode toolchain with macOS SDK 10.15 works, rest all configurations are broken and are not working.
So if we switch to the default Xcode version and use the latest SDK on the VM, future builds should not break.

**Comment by kunaltyagi** [comment]
How is your CI using XCode? XCode.app isn't available on the PR I tried to emulate you

**Comment by shrijitsingh99** [comment]
`c` is small in Xcode.
It should be ```XCODE_APP_PATH=`/Applications/Xcode.app'```, you cant use ```XCODE_APP_PATH=`ls -d /Applications/XCode*```since there are multiple versions of Xcode available.

**Comment by SergioRAgostinho** [comment]
Side note: Ci appears to be running green again for OSX builds.

**Comment by kunaltyagi** [comment]
Where? #3732 just ended on red

**Comment by kunaltyagi** [comment]
@shrijitsingh99 Thanks a lot. This seems to have done the trick. Also, I added Catalina CI 😄 (1 more hour on 1 pipeline)

**Comment by SergioRAgostinho** [comment]
Here #3731, but it was false alarm. The entire CI ran in 14 minutes. :)

**Comment by kunaltyagi** [comment]
> The entire CI ran in 14 minutes

It doesn't build common or anything, and doesn't throw an error either. Might be a bug hiding in CMake.
<details>
<summary>CMake config log since CI deletes old logs</summary>

-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
--   outofcore: Requires visualization.
--   examples: Code examples are disabled by default.
--   people: Requires octree.
--   simulation: Disabled by default.
--   tests_2d: Requires filters.
--   tests_common: Requires common.
--   tests_features: Requires 2d.
--   tests_filters: Requires octree.
--   tests_geometry: Requires common.
--   tests_io: Requires octree.
--   tests_kdtree: Requires common.
--   tests_keypoints: Requires filters.
--   tests_people: Requires octree.
--   tests_octree: Requires common.
--   tests_outofcore: Requires visualization.
--   tests_recognition: Requires ml.
--   tests_registration: Requires filters.
--   tests_search: Requires octree.
--   tests_surface: Requires octree.
--   tests_segmentation: Requires ml.
--   tests_sample_consensus: Requires search.
--   tests_visualization: Requires octree.
--   tools: Disabled manually.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_apps_3d_rec_framework
    BUILD_apps_cloud_composer
    BUILD_apps_in_hand_scanner
    BUILD_apps_modeler
    BUILD_apps_point_cloud_editor
```
</details>

**Comment by shrijitsingh99** [comment]
> > The entire CI ran in 14 minutes
> 
> What wouldn't I give to have a build time of 14 minutes....
> 
> It doesn't build common or anything, and doesn't throw an error either. Might be a bug hiding in CMake.
> 
> CMake config log since CI deletes old logs

Yeah, it could not find boost dependency. Shouldn't we have something in the CI to catch such types of error i.e. if it just skips building packages for some reason? Cause it gives wrong indication that the CI was successful even though it wasn't.

**Comment by kunaltyagi** [comment]
> Shouldn't we have something in the CI to catch such types of error

Should: yes, but maybe it's compromised or doesn't exist. Maybe FindBoost is quiet or some other bug is present in CMake

**Comment by shrijitsingh99** [comment]
> > Shouldn't we have something in the CI to catch such types of error
> 
> Should: yes, but maybe it's compromised or doesn't exist. Maybe FindBoost is quiet or some other bug is present in CMake

Yeah so catch all of this. We could have a script run at the end of the tests to see if actually all the modules listed were actually built and fail if any module was skipped.
