### ISSUE TITLE
Ambiguous comment by codebase to developer

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3738]
## Context
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_traits.h#L200

`point_traits.h`:200 refers to a bug #821 but that doesn't explain anything.

## Possible Solution
Replace the comment by the actual reason. What's the actual reason though?

It makes sense from C++ perspective that the container of 0 fields will have a 1 byte memory usage, but I'm not sure that's what's happening here

**Comment by larshg** [comment]
Its changed in [this](https://github.com/PointCloudLibrary/pcl/commit/39db9f7e4dafd10f6a4c8a177b3692f332d7fdd6#diff-583b66afd70349525da0c65951211792) commit.

**Comment by taketwo** [comment]
By the way, it's a reference to the old (pre-GitHub) bugtracker, so no surprise GitHub issue by that number is unrelated.
