### ISSUE TITLE
[cuda/gpu] more than one instance __hadd matches argument list

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#3742]
**Describe the bug**

Eigen3 has a bug which has been updated in master.

See [bug at tensorflow](https://github.com/tensorflow/tensorflow/issues/19198)

Maintainer EDIT: [Eigen bugzilla](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1526)

**Context**

Compile PCL with gpu/cuda support

**Expected behavior**

Compiled PCL library.

**Current Behavior**

Compile errors.

**To Reproduce**

Compile PCL with a gpu arch > 5.3
 
**Screenshots/Code snippets**
![image](https://user-images.githubusercontent.com/1165340/76528610-63ff9e00-6471-11ea-82a1-b243169df8ba.png)

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: VS2019
 - PCL Version: Head
 - CUDA: 10.2
 - GFX: GTX980m

**Possible Solution**

- Tell the user to use eigen head build, as a fix has been merged, but there are no new release yet?

- Limit the gpu arch version to below 5.3.

**Comment by kunaltyagi** [comment]
> Tell the user to use eigen head build, as a fix has been merged, but there are no new release yet?

This is already incorporated in Eigen 3.3.6 release as per git log

**Comment by larshg** [comment]
I can see the commit in eigen master branch, but its not found in the 3.3 branch - where can you see its in 3.3.6?

**Comment by kunaltyagi** [comment]
I searched in [GitLab's graph](https://gitlab.com/libeigen/eigen/-/network/3.3.6?utf8=%E2%9C%93&extended_sha1=6dcd2642) since the release of 3.3.6 was after the commit's date. I might be wrong for this in which case your suggestions are very valid.

**Comment by larshg** [comment]
This one is still relevant.

**Comment by yes89929** [comment]
How can I limit the gpu arch version to below 5.3?

**Comment by larshg** [comment]
Since you have installed using VCPKG, its easiest just to do ./vcpkg.exe install eigen --head.
Uninstall the current one first.

But else I think you can set the variables, if you use cmake - think its CUDA_ARC_BIN (a space separated list of supported versions, ie 3.0 3.5 5.0...

**Comment by larshg** [comment]
Eigen has released new version which includes fix for this. So I'll close it. Eigen 3.3.9 works, maybe 3.3.8 also include the change.
