### ISSUE TITLE
[rs-pcl example ] I get an error when building the rs-pcl example

### ISSUE THREAD

**Issue by brycen-fpga** [PointCloudLibrary/pcl#3746]
*Environment
Compiler: [visual studio 2019]
PCL Version [ 1.10.0 ]
Device: Depth Realsense Camere D435i
*Describe the error
-  I get an error when building the rs-pcl example: https://github.com/IntelRealSense/librealsense/tree/master/wrappers/pcl/pcl
*Screenshots
![image](https://user-images.githubusercontent.com/60213619/76609284-b7451f80-6549-11ea-8b22-30faee46e78f.png)
Can you give me some advice?
Thanks a lot!

**Comment by SergioRAgostinho** [comment]
Your point cloud is too big. There's a big red message in the background saying "failed to allocate X indices". Your system is running out of memory.
