### ISSUE TITLE
[rs-pcl example ] I get an error when building the rs-pcl example

### ISSUE THREAD

**Issue by minhhieu14351997** [PointCloudLibrary/pcl#3748]
*sorry everyone, i'm the one who posted the problem # 3746. Because of the wrong login, I closed the problem and used my nick to ask again. please, feeling sorry for me
*Environment
Compiler: [visual studio 2019]
PCL Version [ 1.10.0 ]
Device: Depth Realsense Camere D435i
*Describe the error

I get an error when building the rs-pcl example: https://github.com/IntelRealSense/librealsense/tree/master/wrappers/pcl/pcl
*Screenshots
![image](https://user-images.githubusercontent.com/40237041/76612054-1d33a600-654e-11ea-8af9-b42a30abf1b1.png)

Can you give me some advice?
Thanks a lot!

**Comment by kunaltyagi** [comment]
Your point cloud is too big. There's a big red message in the background saying "failed to allocate X indices". Your system is running out of memory.

_Originally posted by @SergioRAgostinho in https://github.com/PointCloudLibrary/pcl/issues/3746#issuecomment-598637913_


You need to get permission to allocate more memory somehow. Not an issue in PCL

**Comment by minhhieu14351997** [comment]
> Your point cloud is too big. There's a big red message in the background saying "failed to allocate X indices". Your system is running out of memory.
> 
> _Originally posted by @SergioRAgostinho in [#3746 (comment)](https://github.com/PointCloudLibrary/pcl/issues/3746#issuecomment-598637913)_
> 
> You need to get permission to allocate more memory somehow. Not an issue in PCL

I don't really understand, can you explain clearly the problem I'm having.
Thanks you @kunaltyagi

**Comment by kunaltyagi** [comment]
[This link](https://www.harrisgeospatial.com/Support/Self-Help-Tools/Help-Articles/Help-Articles-Detail/ArtMID/10220/ArticleID/19259/3346) has some more details.

**Comment by minhhieu14351997** [comment]
> [This link](https://www.harrisgeospatial.com/Support/Self-Help-Tools/Help-Articles/Help-Articles-Detail/ArtMID/10220/ArticleID/19259/3346) has some more details.

I will try. thank you very much. @kunaltyagi
