### ISSUE TITLE
PCL installed but have errors when include libaries

### ISSUE THREAD

**Issue by duongbaoquy** [PointCloudLibrary/pcl#3749]
I am working with VS2015 so I installed PCL 1.8.1
After I installed pcl, I started adding a few libraries to implement my project - there were some errors from the PCL library - I tried changing to other versions from 1.6.0 to 1.10 .0, there's still errors from the library I included. Do you have any ideas to help me fix this?
![image](https://user-images.githubusercontent.com/62133702/76674620-f7f17700-65e3-11ea-8b2d-25ec8b2715a6.png)

Thanks for your time.

**Comment by SergioRAgostinho** [comment]
The best course of action is to provide an [MVCE](https://stackoverflow.com/help/minimal-reproducible-example). It will help you and us better understand what it going on.

**Comment by duongbaoquy** [comment]
One more question, is the use of CMake necessary? if in case i have downloaded and run PCL _AllInOne.exe. My project did not use CMake, only added the link to the library (where PCL_AllInOne was installed).

**Comment by SergioRAgostinho** [comment]
> is the use of CMake necessary?

Yes it is.
