### ISSUE TITLE
[ci] Addition of osx catalina in CI appears to have disabled ubuntu 19.10

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3757]
**Describe the bug**

The inclusion of OSX Catalina in CI seems to have "pushed out" the checks for ubuntu 19.10. Currently it is not appearing in the list of checks on GitHub. 

![Screenshot from 2020-03-16 22-46-07](https://user-images.githubusercontent.com/1709142/76802446-f9839080-67d7-11ea-9b44-696caa994f9e.png)

**Context**

At first sight it seems like we kicked out ubuntu 19.10 for Catalina. I'm not sure if things are running on Azure and are simply not being rendered on GitHub

**Expected behavior**

Both OSX Catalina and 19.10 should be running

**Current Behavior**

Only Catalina appears to be tested

**To Reproduce**

Check #3755 for instance

**Comment by shrijitsingh99** [comment]
They don't seem to be running on [Azure](https://dev.azure.com/PointCloudLibrary/pcl/_build).
Even Formatting has stoped running.

**Comment by kunaltyagi** [comment]
@taketwo Does azure have a cap on 9 pipelines?

**Comment by shrijitsingh99** [comment]
Azure only caps the max parallel jobs to 10 for open source repos, after that it just queues it and does not cancel it. Before the Catalina merge we had 10 pipelines so don't think there is a cap.
Even after adding macOS Catalina there were 2 more builds as seen [here](https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=7&_a=summary)

**Comment by SergioRAgostinho** [comment]
> Azure only caps the max parallel jobs to 10 for open source repos, after that it just queues it and does not cancel it.

That's the behavior I was expecting.

**Comment by shrijitsingh99** [comment]
> > Azure only caps the max parallel jobs to 10 for open source repos, after that it just queues it and does not cancel it.
> 
> That's the behavior I was expecting.
> 
> Edit: #3745 seems to not be affected by it anymore :o

Yeah, maybe the changes made in #3745 YAML configuration triggered something? Not, sure.

**Comment by taketwo** [comment]
So it seems like this was a temporary glitch?

**Comment by shrijitsingh99** [comment]
> So it seems like this was a temporary glitch?

Yeah, seems so. Nothing out of the ordinary that could have caused this.
