### ISSUE TITLE
[ci] Documentation runs Doxygen 3 times instead of 1

### ISSUE THREAD

**Issue by aPonza** [PointCloudLibrary/pcl#3759]
**Is your feature request related to a problem? Please describe.**

I'm running the Documentation job fairly often these days and noticing it takes forever to complete. While running, I check all the warnings coming from it and it shows the same exact warnings 3 times, one for each job, since the doc job is a dependency for all 3 doc, tutorial and advanced targets. Is Doxygen needed for Sphinx targets?

**Context**

Especially with the clang parser (#3744), this elongates build times to unbearable amounts.

**Expected behavior**

Doxygen is only run once if I'm building any combination of these jobs (so the single targets, all the pairs and the one triplet). This is if Doxygen is really required before Sphinx.

**Current Behavior**

Doxygen runs before the targets doc, tutorial and advanced even when all three are to be built in one run.

**Describe the solution you'd like**

I don't currently know why it would be needed, so I don't yet know if it's just a matter of removing the dependency in CMakeLists.txt or if it needs something different. Don't know if it's feasible.

**Describe alternatives you've considered**

Continue with the current way hoping the less warnings there are the quicker the job is.

**Additional context**

Last build with the clang parser is this one: 
[output_use_clang_parser_on_top_of_fix_doc_warnings_fix_std_fix_pcl1.txt](https://github.com/PointCloudLibrary/pcl/files/4342264/output_use_clang_parser_on_top_of_fix_doc_warnings_fix_std_fix_pcl1.txt)

**Comment by aPonza** [comment]
I'm fairly tired and might be misreading this, but [link](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/) seems to suggest in the second bullet point that it is possible to CMake-magic the way into having Doxygen not run if the sources didn't change, which would mean run only once in any real-world case.

Another interesting idea to speed up the documentation job would be using parallel building (same link as before) via separate doc targets for separate PCL modules which create each a [tagfile](http://www.doxygen.nl/manual/external.html). This way the final documentation is built off of the tagfiles.

**Comment by kunaltyagi** [comment]
Running 3 times might be happening because of `configure_file` which modifies `Doxyfile` which causes it to run again. We can use 2 `configure_file` to fix this problem:
```cmake
# CMakeLists.txt:
#...
configure_file(configure_doxyfile.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/configure_doxyfile.cmake @ONLY)

set(doxyfile ${CMAKE_CURRENT_BINARY_DIR}/doxyfile)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/html")

add_custom_command(OUTPUT doxyfile
  COMMAND ${CMAKE_COMMAND} -P
    ${CMAKE_CURRENT_BINARY_DIR}/configure_doxyfile.cmake
  DEPENDS
    ${CMAKE_CURRENT_BINARY_DIR}/configure_doxyfile.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/doxyfile.in
  COMMENT "Configuring doxyfile"
  VERBATIM)

add_custom_target(configure_doxyfile ALL
  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/doxyfile)
#...
# EOF


# configure_json_file.cmake.in:
# Don't know where the this should go...
set(STRIPPED_HEADERS "${PCL_SOURCE_DIR}/${PCL_MODULES_NAMES}/include")
string(REPLACE ";" "/include \\\n                         ${PCL_SOURCE_DIR}/" STRIPPED_HEADERS "${STRIPPED_HEADERS}")
set(DOC_SOURCE_DIR "\"${PCL_SOURCE_DIR}\"\\")
configure_file(@DOXYFILE_LOCATION@ "${doxyfile}")
# EOF

```

We might also investigate using the [`doxygen_add_docs`](https://cmake.org/cmake/help/v3.9/module/FindDoxygen.html#command:doxygen_add_docs) commands instead of generating doxyfile if this method is too roundabout.

> speed up the documentation job would be using parallel building

That might also allow each module to have its own tutorials, examples, on-boarding in the module itself, instead of in doc. Definitely something for the future (allowing parallel builds for doc, ie)

**Comment by aPonza** [comment]
Did you see [the 3.16.5 version](https://cmake.org/cmake/help/v3.17/module/FindDoxygen.html#command:doxygen_add_docs) has a stamp file? It's way too ahead than baseline CMake, but:

> If USE_STAMP_FILE is set, the custom command defined by this function will create a stamp file with the name <targetName>.stamp in the current binary directory whenever doxygen is re-run. With this option present, all items in <filesOrDirs> must be files (i.e. no directories, symlinks or wildcards) and each of the files must exist at the time doxygen_add_docs() is called. An error will be raised if any of the items listed is missing or is not a file when USE_STAMP_FILE is given. **A dependency will be created on each of the files so that doxygen will only be re-run if one of the files is updated.** Without the USE_STAMP_FILE option, doxygen will always be re-run if the <targetName> target is built regardless of whether anything listed in <filesOrDirs> has changed.

It's like the link said.

>  [link](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands/) seems to suggest in the second bullet point that it is possible to CMake-magic the way into having Doxygen not run if the sources didn't change

Maybe then the best way to proceed is to use `doxygen_add_docs` like you say but add a custom stamp file which can eventually be integrated? It should be a "copy" of the if-branch in [here](https://github.com/Kitware/CMake/blob/v3.16.5/Modules/FindDoxygen.cmake#L1126-L1154) (which is incidentally the same as `master`).

**Comment by kunaltyagi** [comment]
> Did you see the 3.16.5 version has a stamp file?
> add a custom stamp file which can eventually be integrated

I have it, but I didn't observe the new addition. IMO adding that functionality and then removing our custom code in a few cycles seems to be the best path forward
