### ISSUE TITLE
[common] Empty file in the repository

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3761]
Not much use in keeping this around. :)
https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/point_operators.h

**Comment by kunaltyagi** [comment]
Add a warning first or remove it directly?

**Comment by SergioRAgostinho** [comment]
Let's be safe and add the warning. Although I really don't believe anyone ever added this header. It has nothing!

**Comment by taketwo** [comment]
The last time this file had any content was in 2012, let's delete it and move on :)
