### ISSUE TITLE
[pcl] Can't include file `vtkImageViewer.h` (VTK v8.2)

### ISSUE THREAD

**Issue by JaKno63** [PointCloudLibrary/pcl#3762]
**Describe the bug**

These PCL projects

pcl_visualization
pcl_openni2_viewer
pcl_tiff2pcd
pcl_pcd_image_viewer
pcl_viewer
pcl_hdl_viewer_simple
pcl_vlp_viewer
pcl_virtual_scanner

 don't build (Debug and Release) because these include paths

Path_To_VTK\build\Interaction\Image
Path_To_VTK\Interaction\Image

are missing in the VS2019 project files generated by cmake 

**Context**

**Expected behavior**

**Current Behavior**

**To Reproduce**

**Your Environment (please complete the following information):**

 - OS: Windows 10 1903
 - Compiler: Microsoft Visual Studio Professional 2019
 - PCL Version 1.10.0, HEAD

**Possible Solution**

**Additional context**

**Comment by taketwo** [comment]
What's the VTK version?

**Comment by JaKno63** [comment]
8.2.0

**Comment by taketwo** [comment]
The status of VTK >= 8.2.0 support in PCL is not certain. There is a work-in-progress PR #3637 that fixes some issues, you may give it a try. Alternatively, downgrade.

**Comment by larshg** [comment]
How have you installed the dependency libs? VCPKG? can you post the result of the cmake - because I'm using VTK 8.2, but there are some problems with it linking to both release and debug of their 3. party libraries, which causes runtime errors for some in Debug build I think.

**Comment by JaKno63** [comment]
I pulled all sources (BOOST, EIGEN, FLANN, VTK and PCL) and compiled them. FLANN on Windows didn't compile due to missing lz4lib, so I also installed the latest PCL complete package and copied the FLANN libs to the corresponding folders (I had to rename the debug libs).

**Comment by larshg** [comment]
Normally CMake should include the appropriate headers directories and I haven't experienced this, even though I have compiled many times with VTK 8.2 from VCPKG.

Might have been a misconfiguration when building VTK?

I doubt its something in PCL.
