### ISSUE TITLE
How PassThrough's Filter works?

### ISSUE THREAD

**Issue by duongbaoquy** [PointCloudLibrary/pcl#3766]
Hi,	
I'm using the PCL library to output the PCD file - in which I have used some of the following filters:
```
            pcl :: PassThrough <pcl :: PointXYZRGB> Cloud_Filter;
            Cloud_Filter.setInputCloud (cloud);
            Cloud_Filter.setFilterFieldName ("x");
            Cloud_Filter.setFilterLimits (0.0, 0.6);
            Cloud_Filter.setFilterFieldName ("y");
            Cloud_Filter.setFilterLimits (0.0, 0.6);
            Cloud_Filter.setFilterFieldName ("z");
            Cloud_Filter.setFilterLimits (0.0, 1.0);
            Cloud_Filter.filter (* newCloud);
```
In the above code there is a place I still do not understand:
- setFilterLimits: how are min and max values ​​calculated? And which units are they calculated in?
- I am also wondering how to calculate X and Y values? As for Z - is it calculated by measuring the distance from the camera to the object? and is the measurement unit a meter?

Thanks

**Comment by kunaltyagi** [comment]
> how are min and max values ​​calculated?

They are user inputs. You calculate them based on your situation.

> And which units are they calculated in?

Same as the units of the point cloud. In my case, I often use the metric system and calibrate my sensors to it. This results in the units being metre. Some people prefer calibrating to cgs and use centimetre. In this case the unit are most likely in metre.

> Z - is it calculated by measuring the distance from the camera to the object?

In this case, yes. The coordinate frame is defined based on the calibration of the sensor, eg:  
* X is towards right, Y is bottom and Z is towards the object OR
* X is forwards, Y is towards left and Z is top OR
* X is towards right, Y is forwards and Z is top, etc.

**Comment by duongbaoquy** [comment]
Thanks - i got it now.
