### ISSUE TITLE
[visualization] Unable to compile with VTK 8.9

### ISSUE THREAD

**Issue by Zumbalamambo** [PointCloudLibrary/pcl#3769]
**Describe the error**

Unable to install while using make install

**To Reproduce**

just `make install`

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**

> I/usr/local/include/vtk-8.90/vtkCellArray.h:1375:12: note:   initializing argument 2 of ‘int vtkCellArray::GetNextCell(vtkIdType&, const vtkIdType*&)’
>  inline int vtkCellArray::GetNextCell(vtkIdType& npts, vtkIdType const*& pts) VTK_SIZEHINT(pts, npts)
>             ^~~~~~~~~~~~
> io/CMakeFiles/pcl_io.dir/build.make:296: recipe for target 'io/CMakeFiles/pcl_io.dir/src/vtk_lib_io.cpp.o' failed
> make[2]: *** [io/CMakeFiles/pcl_io.dir/src/vtk_lib_io.cpp.o] Error 1
> CMakeFiles/Makefile2:522: recipe for target 'io/CMakeFiles/pcl_io.dir/all' failed
> make[1]: *** [io/CMakeFiles/pcl_io.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2
> 

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 16.04] Ubuntu 18
 - Compiler: [:eg GCC 8.1] GCC 8.1
 - PCL Version [e.g. 1.10, HEAD] 1.9
 - PCL Type:  Compile from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes

**Comment by larshg** [comment]
VTK 8.9(head) is not yet supported, try merge #3637 and see if that helps.

**Comment by Zumbalamambo** [comment]
@SergioRAgostinho @kunaltyagi  which version of vtk does this support?

**Comment by Zumbalamambo** [comment]
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZ::getVector4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:224:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZ::getVector4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:224:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZ::getArray4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:224:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZ::getArray4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:224:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZI::getVector4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:382:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZI::getVector4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:382:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZI::getArray4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:382:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZI::getArray4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:382:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZL::getVector4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:421:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZL::getVector4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:421:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZL::getArray4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:421:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZL::getArray4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:421:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZRGBA::getVector4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:457:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZRGBA::getVector4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:457:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZRGBA::getArray4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:457:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16> pcl::_PointXYZRGBA::getArray4fMap() const’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:457:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(const Scalar*) [with Derived = Eigen::Array<float, 4, 1>; Eigen::PlainObjectBase<Derived>::ConstAlignedMapType = const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Array<float, 4, 1> >::ConstAlignedMapType {aka const Eigen::Map<const Eigen::Array<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘const Eigen::Map<const Eigen::Array<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])
     ^
In file included from /home/Documents/pcl-pcl-1.7.1/common/include/pcl/point_types.h:311:0,
                 from /home/Documents/pcl-pcl-1.7.1/common/src/point_types.cpp:37:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp: In member function ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16> pcl::_PointXYZRGB::getVector4fMap()’:
/home/Documents/pcl-pcl-1.7.1/common/include/pcl/impl/point_types.hpp:514:5: error: could not convert ‘Eigen::PlainObjectBase<Derived>::MapAligned(Eigen::PlainObjectBase<Derived>::Scalar*) [with Derived = Eigen::Matrix<float, 4, 1>; Eigen::PlainObjectBase<Derived>::AlignedMapType = Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >; Eigen::PlainObjectBase<Derived>::Scalar = float]()’ from ‘Eigen::PlainObjectBase<Eigen::Matrix<float, 4, 1> >::AlignedMapType {aka Eigen::Map<Eigen::Matrix<float, 4, 1>, 32, Eigen::Stride<0, 0> >}’ to ‘Eigen::Map<Eigen::Matrix<float, 4, 1>, 16>’
     PCL_ADD_POINT4D; // This adds the members x,y,z which can also be accessed using the point (which is float[4])

**Comment by kunaltyagi** [comment]
That's unrelated to this issue. Please file a separate issue.

**Comment by Zumbalamambo** [comment]
closing as it is stale
