### ISSUE TITLE
loadPLYFile works in debug version but not in release version

### ISSUE THREAD

**Issue by victoryc** [PointCloudLibrary/pcl#3771]
I am calling pcl::io:loadPlyFile to load point cloud data from a PLY file. It works fine when I link against the debug version of the libraries but not when linked against release version of the libraries. When run in release version, I get the following error message:

[pcl::PLYReader::read] File () not found!

Any idea what the issue might be?

I am linking against the debug/release libraries provided for Visual Studio 2019 on Windows platform.
PCL version: 1.10.1

Thanks!

**Comment by victoryc** [comment]
User error.

**Comment by kunaltyagi** [comment]
Any way the library can reduce chances of it recurring, or was it a severe case of user error?
