### ISSUE TITLE
Add empty newline in all files

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3773]
Several text files don't have an empty last line (which guarantees ending with `\n` required for their treatment as text files under strict POSIX interpretation).

Maybe there's a clang-format flag for this.

_For more details, see this comment by @kunaltyagi in https://github.com/PointCloudLibrary/pcl/pull/3760#issuecomment-602210672_

**Comment by mtochi** [comment]
Can I work on this issue?

**Comment by SergioRAgostinho** [comment]
Go ahead!

**Comment by kunaltyagi** [comment]
In light of #3784, maybe just ensure that all files have a '\n' at the end.

**Comment by mtochi** [comment]
I created a new branch with the changes, I tried to push this branch to pcl but it says that: "You don't have write access to pointcloudlibrary/pcl. Do you want to create a fork...?"

**Comment by kunaltyagi** [comment]
Yes. You need to create a fork, create a branch and push changes there, and then create a PR here.
