### ISSUE TITLE
[CI] Pipeline shows only 10 jobs active at a time

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3776]
Yes, we still have 12 jobs:

![image](https://user-images.githubusercontent.com/1241736/77072062-63c14e80-69ed-11ea-8950-ffc86d19bcbe.png)

_Originally posted by @taketwo in https://github.com/PointCloudLibrary/pcl/issues/3595#issuecomment-601176929_

https://dev.azure.com/PointCloudLibrary/pcl/_build?view=runs

It shows at max 10 jobs active (8 including Windows + MacOS both of which are 2 jobs).

Unless the matrix jobs cost 1 more job that the internal matrix (aka 3 instead of 2), we seem to be running at sub-capacity. Does any one know why this is so?

<img width="1129" alt="Screen Shot 2020-03-23 at 11 27 45" src="https://user-images.githubusercontent.com/2657068/77274478-5b248d00-6cf9-11ea-975f-5f04008659d6.png">

**Comment by taketwo** [comment]
I see 12 running jobs right now:

![image](https://user-images.githubusercontent.com/1241736/77295129-a634a500-6ce5-11ea-8ddc-177afc9a26c9.png)

**Comment by kunaltyagi** [comment]
I saw it consistently throttle me to 10 jobs when I was pushing my PR.
