### ISSUE TITLE
[IO] PCL 1.10.1 loadPCDFile throws "out of memory" bad_alloc

### ISSUE THREAD

**Issue by xiaodahai** [PointCloudLibrary/pcl#3782]
pcl::io::loadPCDFile<pcl::PointXYZRGB> (fileName, *cloud)报内存溢出，0x00007FFA3898A859 处(位于 my_shoes.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x00000028500FE160 处。

**Comment by kunaltyagi** [comment]
Please translate to English

**Comment by xiaodahai** [comment]
我是按照这篇文章进行配置的，https://blog.csdn.net/qq_33561192/article/details/104686500，作者也碰到了类似问题。

**Comment by xiaodahai** [comment]
I install PCL 1.10.1，when i input file erorr happened，the error is out of memory。pcl::io::loadPCDFilepcl::PointXYZRGB (fileName, *cloud)。i install PCL 1.10.1 according to this web link
https://blog.csdn.net/qq_33561192/article/details/104686500.

**Comment by xiaodahai** [comment]
can you give me a install outlet of PCL 1.10.1。

**Comment by wz18207** [comment]
@xiaodahai Sorry, I can’t open the link you have support. Also I don’t understand what your development environment looks like. Can you give me some detailed configuration information?

I think you can start from two aspects:
1. Check your environment variables to see if the corresponding path in correct
2. If the previous step is correct, I think you can check your cmakelists.txt 

If it doesn't work, I think you can do some more debugging on your code to see if the include files corresponding to the header files are one-to-one.

**Comment by wz18207** [comment]
@xiaodahai  could you please provide your code? I want to do some memory debugging.

**Comment by xiaodahai** [comment]
> @xiaodahai could you please provide your code? I want to do some memory debugging.

There are unhandled exceptions in 0x00007FFE0181A859 : Microsoft C++ exception: std::bad_alloc，In memory location  0x000000E9B72FE570 。

**Comment by xiaodahai** [comment]
> @xiaodahai could you please provide your code? I want to do some memory debugging.

could you please provide a  install outlet of PCL 1.10.1。

**Comment by wz18207** [comment]
@xiaodahai I think you can fill in your dependent projects according to the lib files in the installation directory of the previous installation version, it depends on which folder you want to use the lib files.

**Comment by ThreeWaterGG** [comment]
@wz18207 I encountered the same problem as his.Here is my code.
![图片](https://user-images.githubusercontent.com/53047525/78679799-43661f00-791d-11ea-95f3-a454ed58f4fd.png)
And the hightlighted line is the breakpoint and threw the following error:
![图片](https://user-images.githubusercontent.com/53047525/78680115-ac4d9700-791d-11ea-9277-357b3831e039.png)
There are unhandled exceptions in XXXXXX : Microsoft C++ exception: std::bad_alloc，In memory location XXXXXXXXX。
Really appreciate for your reply.

**Comment by wz18207** [comment]
@ThreeWaterGG Checking your working directory.
1: you have file and the error locations. Then put it into your project work directory. 
2: false file name. Change it in truth.
3. if these things in truth. I think you could check the dependencies of your project  and the environment variables filled in correct

**Comment by wz18207** [comment]
@xiaodahai could you please close this question?

**Comment by cynixcao** [comment]
@xiaodahai Have you soved your problem now? I cncountered the same probelm as you and I also use https://blog.csdn.net/qq_33561192/article/details/104686500 as my installation guide. If you have soled your probelm, please share with me. Thank you!

**Comment by cynixcao** [comment]
@ThreeWaterGG have you solved your problem, my code is similar as you and I cncountered the same problem. If you have solved it plz share with me. Thanks!

**Comment by mingtiancai** [comment]
> pcl::io::loadPCDFilepcl::PointXYZRGB (fileName, *cloud)报内存溢出，0x00007FFA3898A859 处(位于 my_shoes.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x00000028500FE160 处。

https://zhuanlan.zhihu.com/p/142955614这个链接我已经解决了。不要改源代码，是安装配置设置的错误问题。

**Comment by mingtiancai** [comment]
我今天配置的时候也看到了，作者直接换版本了，其实不用，把库和编译模式匹配好就行

**Comment by kunaltyagi** [comment]
Nice tutorial @mingtiancai, do you mind adding creating a PR to add an updated windows tutorial as per #4118?

**Comment by wz18207** [comment]
@kunaltyagi I think #4118 has made the point pretty well.
As for whether to add it to the windows tutorial, I think it can be left alone for now.
The problem that can be solved by compiling and installing according to cmake is that this person only applies to the distribution
