### ISSUE TITLE
[tools] Enable visualization of progress in registration_visualizer

### ISSUE THREAD

**Issue by democheng** [PointCloudLibrary/pcl#3788]
**Describe the bug**

pcl -> tools -> registration_visualizer.cpp

there is no way to visualize the progress of registration(icp), because the function "update_visualizer_" in icp.hpp is like this:

    // Update the vizualization of icp convergence
    //if (update_visualizer_ != 0)
    //  update_visualizer_(output, source_indices_good, *target_, target_indices_good );

**Comment by kunaltyagi** [comment]
How would you propose to display/send feedback of progress?

**Comment by kunaltyagi** [comment]
Closing due to lack of interest
