### ISSUE TITLE
Can't create .obj and .stl from .ply with RGB data

### ISSUE THREAD

**Issue by ghost** [PointCloudLibrary/pcl#3796]
pcl::PolygonMesh mesh;
 pcl::io::load(".ply",mesh);
 pcl::io::savePolygonFileSTL(".stl",mesh,false); 
 pcl::io::saveOBJFile(".obj",mesh,5);

files created but .obj files does not have rgb
stl cannot open.
any one help to me

**Comment by SergioRAgostinho** [comment]
Start by creating an MVCE 
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mvieth** [comment]
In case you or anyone else still has this problem: I tried your code (with appropriate file names) and was able to open both files (stl and obj), e.g. with blender or MeshLab. `pcl::PolygonMesh` does not store any color/texture information, but `pcl::TextureMesh` does. However, PCL can currently only read TextureMesh from OBJ files, and write TextureMesh to OBJ files. I hope that helps.
