### ISSUE TITLE
Unable to use cuda filters 

### ISSUE THREAD

**Issue by Leoole** [PointCloudLibrary/pcl#3797]
I'm trying to use cuda versions of passthrough and voxelgrid, only to see _pcl_cuda/filters/voxel_grid.h couldn't be found_ . I also didn't find cpp files in repository, are these functions usable at the moment?

**Comment by kunaltyagi** [comment]
Please provide more details (asked in the `compile_error` issue template. No need to create a new issue).

**Comment by Leoole** [comment]
It seems like I just can't figure out how to use them. I can use gpu namespace but not cuda, I also couldn't find answer in www.pcl-users.org, could anyone please give a code sample for cuda voxelgrid?

**Comment by Leoole** [comment]
Also here [2021](https://github.com/PointCloudLibrary/pcl/issues/2021) was mentioned that cuda is in unknown state without contributors, is it still same?

**Comment by kunaltyagi** [comment]
Very much so. We don't have resources for maintaining and updating CUDA module.
