### ISSUE TITLE
Implement a default `FilterIndices::applyFilter`

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3798]
This code is literally the same from the `Passthrough`, `CropBox`, `ExtractIndices`(almost) , `FrustrumCulling` filters. Maybe this should be the default implementation exposed by `FilterIndices`. @PointCloudLibrary/maintainers . Spin-off a new PR for it.

_Originally posted by @SergioRAgostinho in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM5Nzc0NjA1NA==/comments/review_comment_

**Comment by SergioRAgostinho** [comment]
FYI: I was "forced" to define a child class to `FilterIndices` -> `FilterIndicesXYZ` in order to define this common filter method.
