### ISSUE TITLE
[filters] Use `sample_size_` instead of `sample_`

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3799]
Yeah that makes more sense, but I recommend changing it across all the other filters as well since other algorithms that select a specified number of points (such as random sampling, normal space) use the same `sample_` naming.

_Originally posted by @haritha-j in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM5Nzc2NDE0OQ==/comments/review_comment_

**Comment by haritha-j** [comment]
I can take care of this, would it be acceptable to include it in the same PR as mentioned above, or should it be a seperate PR?

**Comment by kunaltyagi** [comment]
Separate is better

**Comment by kunaltyagi** [comment]
Mislabeled as stale. PR created to address this

**Comment by mvieth** [comment]
Closing due to the reasons I mentioned above
