### ISSUE TITLE
[tracking] Add to clang-format whitelist

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3800]
**Is your feature request related to a problem? Please describe.**

Code doesn't follow coding guidelines.

**Context**

We have a `format` CI which checks formatting for only whitelisted modules. `tracking` isn't one of them. Yet.

**Describe the solution you'd like**

`format` CI (or `make format`) flags the code which doesn't follow guideline in `tracking` module.

**Additional context**

The process is pretty simple:

* add a module to [whitelist](https://github.com/PointCloudLibrary/pcl/blob/811b57ce6fb3077074b5c8ddfca8e2eaaac7e57c/.dev/format.sh#L9-L11)
* run format a few times
* go through every file and correct errors so that clang-format doesn't redo them (doxygen comments, some places where formatting is for visual structrue, etc.)
* continue the edit, format cycle till the diff by make format is empty

PS: Having only a few files per commit helps in reviewing

**Comment by divmadan** [comment]
Can you give a bit more intuition on correcting errors?

**Comment by kunaltyagi** [comment]
Formatting errors, ie. code formatted the wrong way. There's no big intuition, just look out for:
* doxygen commands being formatted onto the previous line
* something like a matrix being formatted wrong
```
// before
1.03,     0,      0,
0,     1.03,      0,
0,          0, 1.03
// after
1.03, 0, 0,
0, 1.03, 0,
0, 0, 1.03
```
* etc.

**Comment by divmadan** [comment]
Cool, can I try this issue?

**Comment by divmadan** [comment]
@kunaltyagi 
Can we merge #3814?
