### ISSUE TITLE
Better deprecation policy

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3805]
**Is your feature request related to a problem? Please describe.**

It's hard to know when something got deprecated or when it would be removed (just from reading the code)

**Context**

If we can add the information regarding the cycle in which deprecation was added, we can automate removal of deprecated items too.

**Describe the solution you'd like**

[Working example](https://godbolt.org/z/U9Dyt3)
```cpp
#define DEPRECATED_IMPL_YES(msg) [[deprecated(msg)]]
#define DEPRECATED_IMPL_NO(msg) deprecation_over("Remove the deprecated content") \
DEPRECATED_IMPL_YES(msg)

#define DEPRECATED(version, msg) DEPRECATED_##version(msg)

#define DEPRECATED_1_10(msg) DEPRECATED_IMPL_YES(msg)
#define DEPRECATED_1_9(msg) DEPRECATED_IMPL_NO(msg)

DEPRECATED(1_10, "msg")
```
The `DEPRECATED_X_Y` can be generated using Boost.PP since they depend on the current minor version. For current version `1_10`, we should be removing all items from `1_8` (2 cycles before, this can be codified using a macro constant). This will force the release PR to remove the deprecation when the version is bumped to `1_11` or `2_0` but not if there's a patch release (eg: `1.10.1`).

`DEPRECATED_IMPL_YES` is the current macro `PCL_DEPRECATED`
`DEPRECATED_IMPL_NO` causes a simple compile error

**Comment by SergioRAgostinho** [comment]
I like it. :+1:
