### ISSUE TITLE
clang: error: linker command failed with exit code 1  vscode with vs code

### ISSUE THREAD

**Issue by siyutikitaka** [PointCloudLibrary/pcl#3816]
i'm a student. and the following is my code which i copy from books. only i run this code,the vs code will notify me the information"clang: error: linker command failed with exit code 1  vscode with vs code"
i'll be grateful if anyone helps me 

#include <stdio.h>
#include <malloc/malloc.h>
#include <stdlib.h>
#include <math.h>
#define MaxSize 50
typedef char ElemType;
typedef struct
{   
    ElemType data [MaxSize];//存放顺序表元素
    int length;//存放顺序表长度
}SqList;//声明顺序表的类型
void CreateList(SqList *&L, ElemType a[], int n)//整体建立顺序表
{
    L= (SqList * )malloc(sizeof(SqList));
    for(int i=0; i<n;i++)
        L->length=n;
}
void InitList(SqList *&L)//初始化线性表
{
    L =  (SqList *)malloc(sizeof(SqList));//分配存放线性表的空间
    L ->length=0;
}
void DestroyList(SqList *&L)//销毁线性表
{
    free(L);
}
bool ListEmpty(SqList *L)//判断是否为空表
{
    return(L->length==0);
}
int ListLength(SqList *L)//求顺序表的长度
{
    return(L->length);
}
void DispList(SqList *L)//输出顺序表
{
    for(int i=0; i<L->length;i++)
        printf("%c",L->data[i]);
    printf("\n");
}
bool GetElem(SqList *L,int i, ElemType &e)//求顺序表中第i个元素的元素值
{
    if(i<1 || i>L->length)
    return false;
    e =L->data[i-1];
    return true;
}
int LocateElem(SqList *L, ElemType e)//查找第一个值域为e的元素符号
{
    int i=0;
    while (i<L->length && L->data[i]!=e)
        i++;
    if(i>=L->length)
        return 0;
    else
        return i+1;
}
bool ListInsert(SqList *&L, int i, ElemType e)//插入第i个元素
{
    int j;
    if(i<1 || i>L->length+1)
        return false;
    i--;//将顺序表位序转化为data下标
    for(j=L->length;j>i;j--)
        L->data[i]=L->data[j-1];
        L->data[i]=e;
        L->length++;//顺序表长度+1
        return true;
}
bool ListDelete(SqList *&L, int i, ElemType &e) //删除第i个元素
{
    int j;
    if(i<1 || i>L->length)
        return false;
    i--;//将顺序表位序转化为data下标
    e=L->data[i];
    for(j=i;j<L->length-1;i--)
        L->data[j]=L->data[j+1];//将data[i]之后的元素前移一个位置
    L->length--;//顺序表长度-1
    return true;
}

**Comment by siyutikitaka** [comment]
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)




there are complete error code in terminal

**Comment by kunaltyagi** [comment]
Unrelated to PCL
