### ISSUE TITLE
Dating pcl in cmakelist.txt

### ISSUE THREAD

**Issue by mylove10086** [PointCloudLibrary/pcl#3828]
Using the installed version of pcl, how to introduce the pc's library files and dll files in the project's cmakelist.txt, I have searched for a long time and have not found an example of this. The ide I use is clion
Can you give an example

**Comment by aPonza** [comment]
Could you take a look at [[tutorial] Using PCL in your own project](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php#using-pcl-pcl-config) and see if this would answer your question?
