### ISSUE TITLE
GUI for pcl::visualizer

### ISSUE THREAD

**Issue by victoryc** [PointCloudLibrary/pcl#3831]
I would like to have some simple GUI on top of pcl:visualizer. Basically, I want to have a few buttons, drop-down lists etc. 
Are there any examples of doing it? Seems like using Qt is one way. Since Qt seems like an overkill for my needs, I am wondering whether I can use imGui. 

Any thoughts/suggestions/examples would be appreciated.
Thanks.

**Comment by taketwo** [comment]
Here is an example of using `PCLVisualizer` with Qt: http://pointclouds.org/documentation/tutorials/qt_colorize_cloud.php#qt-colorize-cloud

I'm not aware of imGui + `PCLVisualizer` usage.

**Comment by victoryc** [comment]
I  found a way to do what I asked by making a renderer (subclass of vtkRenderer) to render the GUI and adding it to vtkRenderWindow of PCLVisualizer using its AddRenderer method. Almost there now...

Does anybody know why does PCLVisualizer renders twice when spinOnce is called? I thought it is supposed to render just once?

**Comment by victoryc** [comment]
E

**Comment by mzeeshanarshad** [comment]
> I found a way to do what I asked by making a renderer (subclass of vtkRenderer) to render the GUI and adding it to vtkRenderWindow of PCLVisualizer using its AddRenderer method.

Hello, I am trying to to use imGUI with PCL visualizer as well. Can you please share a working example? Thanks

**Comment by hduonggithub** [comment]
Hi @victoryc 

I am wondering if you can share your changes adding imgui to PCLVisualizer? Thanks!

**Comment by 9and3** [comment]
> > I found a way to do what I asked by making a renderer (subclass of vtkRenderer) to render the GUI and adding it to vtkRenderWindow of PCLVisualizer using its AddRenderer method.
> 
> Hello @victoryc, I am trying to to use imGUI with PCL visualizer as well. Can you please share a working example? Thanks

Same thing! I am really looking to integrate ImGui to PCL. That would be a wonderful addition! Thanks!

**Comment by adahbingee** [comment]
> > > I found a way to do what I asked by making a renderer (subclass of vtkRenderer) to render the GUI and adding it to vtkRenderWindow of PCLVisualizer using its AddRenderer method.
> > 
> > 
> > Hello @victoryc, I am trying to to use imGUI with PCL visualizer as well. Can you please share a working example? Thanks
> 
> Same thing! I am really looking to integrate ImGui to PCL. That would be a wonderful addition! Thanks!
@victoryc 
+1

**Comment by leochien1110** [comment]
@victoryc  Could you please share the method with more details? Thank you in advance.

**Comment by QiuYilin** [comment]
Is there any new progress in this regard?

**Comment by t-black4** [comment]
> Is there any new progress in this regard?

Any updates?
