### ISSUE TITLE
[Registration] There is likely a bug in the implementation of line search in the NDT

### ISSUE THREAD

**Issue by atom2003** [PointCloudLibrary/pcl#3832]
A line search implementation of NDT has an initial computational phase, followed by a loop where the optimal step length is iteratively explored.
This loop works under the following conditions

```
// Iterate until max number of iterations, interval convergance or a value satisfies the sufficient decrease, Equation 1.1, and curvature condition, Equation 1.2 [More, Thuente 1994]
while (!interval_converged && step_iterations < max_step_iterations && !(psi_t <= 0 /*Sufficient Decrease*/ && d_phi_t <= -nu * d_phi_0 /*Curvature Condition*/))
```

https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L667

However, given that `step_max` > `step_min`, the variable `interval_converged` is pre-initialized to true in the following line.
```
  // Check used to allow More-Thuente step length calculation to be skipped by making step_min == step_max
  bool interval_converged = (step_max - step_min) > 0, open_interval = true;
```
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L636
This means that the condition of the while loop always evaluates to false,
so the line search "More-Thuente step length calculation" is not  performed.  

Is this a bug?
(Even if the step length is fixed without the loop, the Newton's method can converge, but global convergence is not guaranteed.)

**Comment by atom2003** [comment]
Looking at history, it looks like @bokorn has implemented NDT, but do you know anything about this issue?

**Comment by kunaltyagi** [comment]
> Is this a bug?

Possibly. There's a possible refactor of the implementation by @koide3 (https://github.com/PointCloudLibrary/pcl/pull/4135#issuecomment-632581929), where it might be looked at with more scrutiny.

**Comment by atom2003** [comment]
Oh! It is wonderful.
He is a great expert on SLAM.
Hopefully, with his help, this bug will be fixed.
