### ISSUE TITLE
[docs] Update Style wrt Code Formatting

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#3834]
The following section of the style guide needs to be updated

https://github.com/PointCloudLibrary/pcl/blame/master/doc/advanced/content/pcl_style_guide.rst#L317-L377

Currently the code style we're enforcing is with clang-format, whose config file is also picked up by most IDEs. The remaining style files which were previously distributed should be considered deprecated and not distributed anymore.

Currently, to format code, most IDEs parse clang-format files (ours is [here](https://github.com/PointCloudLibrary/pcl/blob/master/.clang-format)). On Linux and Mac, there's always the option to run
```
$ make format
```
If clang-format is installed and detected during configuration.

**Comment by divmadan** [comment]
Should we write the documentation for various editors, IDE's? 
Or the text you mentioned will suffice?

**Comment by kunaltyagi** [comment]
I'd start by specifying the `.clang-format`, what it does, a link to our `.clang-format` and how to use it in absence of a IDE plugin (aka running `make format `twice`).

Also, remove the links to other editor specific configs, maybe link to integrations on [this page](https://clang.llvm.org/docs/ClangFormat.html)

**Comment by taketwo** [comment]
>  (aka running make format twice`).

What was it about running it twice? If that's always necessary, then we should probably update the `make format` command (or the formatting script).

**Comment by kunaltyagi** [comment]
> What was it about running it twice?

It sometimes takes running format twice to reach stable diff, but that's not a concern on the CI, right?

**Comment by taketwo** [comment]
Agree regarding CI. But I think your message is the first mention of CI in this thread :)
