### ISSUE TITLE
[extract_clusters.h] ExtractEuclideanClusters with angles doesn't view densly sampled cylinder as single cluster

### ISSUE THREAD

**Issue by bene-inmach** [PointCloudLibrary/pcl#3842]
# Description
I feel like there are two errors in the extractEuclideanClusters method when it's used with an angle.
First of all the angle is not compared with the normal of the point which was used for the nearestNeighborSearch but simply with the normal of the first point which was used in the current segment.
Secondly i think the norm of the dotproduct should be taken and not the norm of the arccos of the dotproduct. In my mind the angle between two planes can be between 0° and 90° and not between 0° and 180°.
Taking the norm of the arccos doesn't do anything in this context since the arccos of [-1;1] is always positive anyway. Taking the norm of the dotproduct on the other hand does make sense since this makes the solution for the normal calculation unambiguous and leaves resulting angles in [0°,90°].

Concretely I'm talking about it's usage as f.ex. in https://github.com/PointCloudLibrary/pcl/blob/master/examples/segmentation/example_extract_clusters_normals.cpp
Now I am not 100% sure that these are bugs. Maybe I'm simply missing something. Or maybe the algorithm is mend to work that way?!? I have to say though that this approach seems rather unintuitive and unstable to me. But in the case it indeed is mend that way an explanation for this implementation is very welcome. It certainly isn't clear from the description of the method that it's supposed to work that way.

# Original

in  pcl/segmentation/include/pcl/segmentation/extract_clusters.h line 149 - 152:
```
double dot_p = normals.points[i].normal[0] * normals.points[nn_indices[j]].normal[0] +
               normals.points[i].normal[1] * normals.points[nn_indices[j]].normal[1] +
               normals.points[i].normal[2] * normals.points[nn_indices[j]].normal[2];

if ( std::abs (std::acos (dot_p)) < eps_angle )
```

# Proposal
```
double dot_p = normals.points[seed_queue[sq_idx]].normal[0] * normals.points[nn_indices[j]].normal[0] +
               normals.points[seed_queue[sq_idx]].normal[1] * normals.points[nn_indices[j]].normal[1] +
               normals.points[seed_queue[sq_idx]].normal[2] * normals.points[nn_indices[j]].normal[2];

if ( std::acos (std::abs (dot_p)) < eps_angle )
```

# Cylinder Clustering Example
original solution gives:
![was_mach_der_regenbogen_hier_O_O](https://user-images.githubusercontent.com/62999772/78164667-5de65700-744a-11ea-8d5c-251cf59507d0.png)
proposed solution gives:
![Screenshot_2020-04-01_18-54-33](https://user-images.githubusercontent.com/62999772/78164663-5d4dc080-744a-11ea-8fe6-88f0f19c40c2.png)

**Comment by kunaltyagi** [comment]
> In my mind the angle between two planes can be between 0° and 90° and not between 0° and 180°

You are right. Could you please create a PR rectifying this?

> the angle is not compared with the normal of the point which was used for the nearestNeighborSearch but simply with the normal of the first point which was used in the current segment

Please create another PR to handle this issue

Thanks a lot for getting to the root of the problem. Sorry for the huge delay in getting back to you
