### ISSUE TITLE
Why I can't find the relevant header files with gpu?

### ISSUE THREAD

**Issue by caibf** [PointCloudLibrary/pcl#3844]
### Environment
- Operating System: Windows 10(1909)
- IDE: Visual Studio 2017 Community
- PCL: 1.9.1

### Context
I have already installed pcl by all in one installer from this [link](https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.9.1/PCL-1.9.1-AllInOne-msvc2017-win64.exe). Howerver, when I include some header files with gpu(`#include <pcl/gpu/containers/device_array.h>`) the IDE does not find the corresponding file because it's not exist.

Could you tell me the reason? If I should compile the source code to acquire the gpu or other modules?

**Comment by SergioRAgostinho** [comment]
> If I should compile the source code to acquire the gpu or other modules?

You need to. The windows installer doesn't bundle gpu code.

**Comment by caibf** [comment]
> > If I should compile the source code to acquire the gpu or other modules?
> 
> You need to. The windows installer doesn't bundle gpu code.

Could you give me a detail turtorial about PCL compilation completely to me? I am the beginner of PCL. Thank you!!!

**Comment by SergioRAgostinho** [comment]
http://pointclouds.org/documentation/tutorials/compiling_pcl_windows.php#compiling-pcl-windows

Closing since this is not a pcl issue.

**Comment by caibf** [comment]
The software version in this tutorial is too old for me. Perhaps not work if I used the newest compiled tool...

**Comment by larshg** [comment]
@caibf I would use vcpkg to install all dependencies.
Clone pcl master and then use cmake(gui) to add the GPU modules and generate a solution. 
Build the install target debug/release. Then you'll have pcl in c:/programfiles(x86)/pcl.

If you want less control over pcl you can install that as well using vcpkg. But I cant remember if they have the 'gpu/cuda' features.

**Comment by caibf** [comment]
@larshg Nice! Too many 3rdParty libraries were a little headache to me. I know vcpkg before but never  use it. I think this toolkit is very useful to me. Thanks!
