### ISSUE TITLE
[segmentation] Improve error handling in OrganizedMultiPlaneSegmentation::segment

### ISSUE THREAD

**Issue by daniel-packard** [PointCloudLibrary/pcl#3855]
When using OrganizedMultiPlaneSegmentation, if the user does not specify _both_ an input cloud _and_ normals they will experience a segfault. This is because those pointers are dereferenced on line 95, without first checking if the pointers are valid:
* https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/organized_multi_plane_segmentation.hpp#L95-L101

I suggest adding additional guard clauses before line 95 to check for valid inputs. 

```c++
  if ( !input_ )
  {
    PCL_ERROR ("[pcl::%s::segment] You must provide a valid input cloud.\n",
               getClassName ().c_str ());
    return;
  }

  if ( !normals_ )
  {
    PCL_ERROR ("[pcl::%s::segment] You must provide a valid input normals.\n",
               getClassName ().c_str ());
    return;
  }
```

Alternatively it could throw an exception... but I figured it's better to match the other error handling inside this file.

I'm happy to open a PR if one or the other approach sounds good

**Comment by SergioRAgostinho** [comment]
Sounds good. Go for it :+1: Thanks!
