### ISSUE TITLE
[PCL_IO] libpcl_io.so.1.10: cannot open shared object file

### ISSUE THREAD

**Issue by ShivamPR21** [PointCloudLibrary/pcl#3856]
Continuous runtime error given by pcl_io while reading a PCD file as described in the PCL IO tutorial. I have compiled PCL from source and using it in a ROS2(ROS version:- Dashing) the package compiles fine but gives errors while runtime:- 

**The package build successively:-**

`colcon build --packages-select pkg`

**while running executable with:-**

`ros2 run pkg test_h "/home/shivam/test.pcd"
`

**The error occurs as:-**

`_/home/shivam/dev/install/pkg/lib/pkg/test_h: error while loading shared libraries: libpcl_io.so.1.10: cannot open shared object file: No such file or directory_
`
**lines in cmakelist.txt used  to link PCL as a dependency to pkg:-**

`link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
ament_target_dependencies(test_h rclcpp PCL) 
target_link_libraries(test_h ${PCL_LIBRARIES})`

Extra information:-
ROS- ROS2 Dashing
Build Type- ament-cmake
OS- Ubuntu 18.04

**Comment by ShivamPR21** [comment]
export this to solve this issue:- 
export LD_LIBRARY_PATH="<pcl_install_dir>/lib:$LD_LIBRARY_PATH"

**Comment by kunaltyagi** [comment]
PS: You should not need to export LD_LIBRARY_PATH if everything was setup properly

**Comment by ShivamPR21** [comment]
Everything is fine and just one change by me is the other installation path than that of specified in PCL install cmakelist.txt

**Comment by iremonur** [comment]
Hi, I get the same error : 
error while loading shared libraries: libpcl_io.so.1.10: cannot open shared object file: No such file or directory
Did you solve it?

**Comment by ShivamPR21** [comment]
@iremonur try to add `LD_Library_PATH`, [that worked for me](https://github.com/PointCloudLibrary/pcl/issues/3856#issuecomment-608539460).
