### ISSUE TITLE
use pointcloud with threshold

### ISSUE THREAD

**Issue by suk8267** [PointCloudLibrary/pcl#3870]
i want to get point cloud with threshold like range of Z is 0.00~30.00 cm but i don't know how to set threshold

my code is 
#include "ros/ros.h"
#include "sensor_msgs/PointCloud2.h"
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/PCLPointCloud2.h>
#include <pcl_ros/transforms.h>
#include <pcl/point_types.h>

void chatterCallback(const sensor_msgs::PointCloud2::ConstPtr& cloud_msg){
        pcl::PCLPointCloud2* cloud = new pcl::PCLPointCloud2;
        pcl::PCLPointCloud2ConstPtr cloudPtr(cloud);
        pcl::PCLPointCloud2 cloud_filtered;

        pcl_conversions::toPCL(*cloud_msg, *cloud);

        float x = cloud->points[p].x;
        float y = cloud->points[p].y;
        float z = cloud->points[p].z;
}

int main(int argc, char **argv){
        ros::init(argc, argv, "icp_sub");

        ros::NodeHandle nh;

	ros::Subscriber sub = nh.subscribe("/camera/depth_registered/points", 10000, chatterCallback);

        ros::spin();

        return 0;
}
please help me

**Comment by shrijitsingh99** [comment]
Use [CropBox Filter](http://docs.pointclouds.org/trunk/classpcl_1_1_crop_box.html) for this.
