### ISSUE TITLE
Bug: ProjectInliers for SACMODEL_CYLINDER

### ISSUE THREAD

**Issue by justinheinz** [PointCloudLibrary/pcl#3876]
### Problem Description
Hi,
I have had some problems with the ProjectInliers Filter for the SACMODEL cylinder.
The radius of the projected cylinder has been way too small.
After having a look at sac_model_cylinder.hpp and some debugging I found out that the fourth dimension of `dir` is nearly one, thus leading to a smaller radius, as this value is added:
`pp += dir * coefficients->values[6];`
### Solution
I was able to get it working by changing 
`			Eigen::Vector4f p(featureCloud->points[i].x,
				featureCloud->points[i].y,
				featureCloud->points[i].z,
				1);`
to
`			Eigen::Vector4f p(featureCloud->points[i].x,
				featureCloud->points[i].y,
				featureCloud->points[i].z,
				0);`
However, I am quite unsure about the math and also this step does not help if `copy_data_fields` is false.
Any ideas how to fix that generally?

**Comment by rl2222** [comment]
Btw, as an example you can just take the code of the cylinder segmentation tutorial:
[http://pointclouds.org/documentation/tutorials/cylinder_segmentation.php](http://pointclouds.org/documentation/tutorials/cylinder_segmentation.php)
And add a ProjectInliers Filter.

**Comment by rl2222** [comment]
Did someone already have a look on it?

**Comment by kunaltyagi** [comment]
I'd recommend starting a PR to get some discussion going since you already have a fix which works in some cases.
