### ISSUE TITLE
[CI] Unit Tests are skipped in Ubuntu 16.04 CI

### ISSUE THREAD

**Issue by shrijitsingh99** [PointCloudLibrary/pcl#3878]
**Context**
[Unit Tests](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=15568&view=logs&j=d5940dd1-f907-59fe-4c1f-39558d633862&t=4c568ee5-15ef-5b3c-af60-5de8beb315ba) are being skipped for some reason.
It seems quite similar to #3200, needs further investigation of why this error keeps on popping up randomly.

**Screenshots/Code snippets**
Log from Azure:

<img width="675" alt="Screenshot 2020-04-07 at 8 55 00 PM" src="https://user-images.githubusercontent.com/10333131/78687683-106a5e00-7912-11ea-9963-a8e7c8efa1c6.png">

**Possible Solution**
A fix similar to #3201 might fix it.

**Comment by taketwo** [comment]
I think it's the same as #3727. And apparently the temporary fix of #3789 disappeared during the transition to stages in #3795. A PR re-adding this fix is welcome :)

**Comment by kunaltyagi** [comment]
@taketwo [Link for you](https://discord.gg/gvcqHTW)
