### ISSUE TITLE
[Installation error] "There is a problem with this Windows Installer package"

### ISSUE THREAD

**Issue by jonathan84clark** [PointCloudLibrary/pcl#3881]
When attempting to run the Windows installer (Latest) on Windows 10, I am forced to install OpenNI 1.3.2.1. During that secondary installation process I get the following error:
"There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor."

If I install OpenNI, then try to re-install; the installation still fails. There is no way to resolve the dependency tree.

**Comment by larshg** [comment]
@UnaNancyOwen is OpenNI still part of the installer and can we close this one, either way?

**Comment by UnaNancyOwen** [comment]
> I am forced to install OpenNI 1.3.2.1.

OpenNI 1.x is not included in the installer. That options are disabled and the libraries and tools not depend on OpenNI 1.x.
OpenNI 2.x is included in the installer. That option are enabled and the libraries and tools depends on OpenNI 2.x.
If you want to install OpenNI 2.x separately PCL, you can uncheck the OpenNI 2.x checkbox from the install components on installer.

**Comment by larshg** [comment]
Thanks for info.
