### ISSUE TITLE
[compile error] "Child return status 2" when attempting to untar bzip2 file

### ISSUE THREAD

**Issue by jonathan84clark** [PointCloudLibrary/pcl#3882]
When I attempt to follow the first step for the Linux installation I get the following.
My Command
` tar xvfj pcl-pcl-1.10.1.tar.gz`

Result
` tar xvfj pcl-pcl-1.10.1.tar.gz bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now`

**Comment by SergioRAgostinho** [comment]
Remove the `j` switch the from the `tar` command.
