### ISSUE TITLE
[compile error] "Configure procedure of CMake is blocking if I checked Build_all_in_one_installer when building from source"

### ISSUE THREAD

**Issue by caibf** [PointCloudLibrary/pcl#3891]
**Describe the error**

I have finished the source code building of PCL 1.9.1 by using CMake 3.11. However, when I checked the option called **Build_all_in_one_installer** and configured again, the progress of building was always blocking at somewhere. The last line of output window of CMake was show as **HTML_HELP_COMPILER**.

**To Reproduce**

* Operating System: Windows 10(1909)
* IDE: Visual Studio 2017 Community
* PCL: 1.9.1（enabled GPU, CUDA）
* CMake: 3.11

**Screenshots/Code snippets/Build information**

* screenshots of the GUI issues
![未命名1586266515](https://user-images.githubusercontent.com/4711529/78758640-0481a900-79b1-11ea-93fe-7de42f50c95c.png)

**Comment by kunaltyagi** [comment]
@UnaNancyOwen recently posted his procedure of making the installer. https://github.com/PointCloudLibrary/pcl/issues/4053#issuecomment-627719812

Maybe you can create a PR to document it more thoroughly.
