### ISSUE TITLE
[vtk][windows]Runtime exception base on PCL 1.9.1 that compiled from source

### ISSUE THREAD

**Issue by caibf** [PointCloudLibrary/pcl#3900]
Hi everyone,

I have compiled PCL 1.9.1 with cuda module by myself from the source. The compilation environment as follows.

- Operating System: Windows 10(1909)
- IDE: Visual Studio 2017 Community
- PCL: 1.9.1（enabled GPU, CUDA）
- CMake: 3.11

Then, I wrote a simple application to test my PCL binary running well. The code snippet as follows.
```
#include <pcl/visualization/cloud_viewer.h>
#include <iostream>
#include <pcl/io/io.h>
#include <pcl/io/pcd_io.h>

#include <vtkAutoInit.h>
VTK_MODULE_INIT(vtkRenderingOpenGL);
VTK_MODULE_INIT(vtkRenderingFreeType);

int user_data;

void viewerOneOff(pcl::visualization::PCLVisualizer& viewer)
{
	viewer.setBackgroundColor(1.0, 0.5, 1.0);
	pcl::PointXYZ o;
	o.x = 1.0;
	o.y = 0;
	o.z = 0;
	viewer.addSphere(o, 0.25, "sphere", 0);
	std::cout << "i only run once" << std::endl;
}

void viewerPsycho(pcl::visualization::PCLVisualizer& viewer)
{
	static unsigned count = 0;
	std::stringstream ss;
	ss << "Once per viewer loop: " << count++;
	viewer.removeShape("text", 0);
	viewer.addText(ss.str(), 200, 300, "text", 0);

	//FIXME: possible race condition here:
	user_data++;
}

int main()
{
	pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGBA>);
	pcl::io::loadPCDFile("../TestData/rabbit.pcd", *cloud);

	pcl::visualization::CloudViewer viewer("Cloud Viewer");

	//blocks until the cloud is actually rendered
	viewer.showCloud(cloud);

	//use the following functions to get access to the underlying more advanced/powerful
	//PCLVisualizer

	//This will only get called once
	viewer.runOnVisualizationThreadOnce(viewerOneOff);

	//This will get called once per visualization iteration
	viewer.runOnVisualizationThread(viewerPsycho);
	while (!viewer.wasStopped())
	{
		//you can also do cool processing here
		//FIXME: Note that this is running in a separate thread from viewerPsycho
		//and you should guard against race conditions yourself...
		//user_data++;
	}
	return 0;
}
```

This application was building success so I glad to run it immediately.
![微信图片_20200410094454](https://user-images.githubusercontent.com/4711529/78954855-f8f8c400-7b0f-11ea-8e1f-5dd44227bfff.png)

Sadly, when I zoomed out the viewer the application crashed. Could you tell me the reason? 
![微信图片_20200410094459](https://user-images.githubusercontent.com/4711529/78955009-7cb2b080-7b10-11ea-88a2-3afc8d367794.png)

**Comment by caibf** [comment]
Furthermore, the 3rdParty program VTK in the All-In-One install of PCL, its bin folder doestn't have dll files. Why?

```
vtkEncodeString-8.1.exe
vtkHashSource-8.1.exe
vtkParseOGLExt-8.1.exe
```

I installed PCL at this path C:\Program Files\PCL 1.9.1.
![未命名1586489827](https://user-images.githubusercontent.com/4711529/78960106-9efffa80-7b1f-11ea-8ad2-a5559a64bcae.png)

**Comment by larshg** [comment]
If I remember correct the all-in-one installer compiles all libraries as static, hence there is no dlls.

And there has been some trouble with compiling vtk as static and pcl as dynamic(have you done this?), with among other rendering runtime issues, it fails to render spheres.

Try search for that issue.

**Comment by caibf** [comment]
@larshg I have found the reason that caused this issue. Be careless, multi version of vtk existed in my OS, but I ignored them. So at the time of compiling PCL 1.9.1, the option “VTK_DIR” in CMake was pointing to vtk 8.2 that compiled with **dynamic libraries** and **OpenGL2**. When I ran my application, the part of visualization was based on vtk. Therefore, that's the issue came from.

Additionally, I have the following questions.

- Does the PCL 1.9.1 is compatiable with Vtk 8.2?
- Does the PCL 1.9.1 may use OpenGL2 not OpenGL for rendering?

**Comment by SergioRAgostinho** [comment]
>     * May the PCL 1.9.1 use OpenGL2 not OpenGL for rendering?

Pass `-DVTK_RENDERING_BACKEND=OpenGL2` to your cmake call

**Comment by caibf** [comment]
@SergioRAgostinho Yeah, I know how to do this. But I don't know it could be supported by PCL.

**Comment by taketwo** [comment]
For sure this is supported on platforms other than Windows. And to my knowledge, in the past it used to work on Windows only when dynamic linking is used. But I don't know what's the current status. Please let us know about your results if you gave it a shot.

**Comment by larshg** [comment]
Using OpenGL backend will probably spew out deprecation warnings, but should still be running.

OpenGL2 still have some issues as mentioned in earlier comment.

**Comment by caibf** [comment]
Hey @taketwo @larshg 

In my own build, vtk compiled as static library and pcl as dynamic library, as same as the all-in-one-installer. Vtk should use vertion 8.1 other than 8.2 because of it doesn't support **OpenGL** since OpenGL2 has some issues that @larshg mentioned.

Back to beginning, the runtime exception come from the wrong rendering pointed to vtk 8.2 dynamic library with MT or MTd option.
