### ISSUE TITLE
[common] Header deprecation macro with scheduled removal version

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#3902]
Thanks to #3808, we now have a deprecation macro with a scheduled removal version. I think we should add something similar for the case of header file deprecation. Currently, a deprecated header looks like this:

https://github.com/PointCloudLibrary/pcl/blob/41a9d025fafe5b9ad10866623ef28aa7d30c897a/tracking/include/pcl/tracking/boost.h#L40-L46

Or like this:

https://github.com/PointCloudLibrary/pcl/blob/41a9d025fafe5b9ad10866623ef28aa7d30c897a/common/include/pcl/point_traits.h#L39-L43

Instead, we can have something like:

```cpp
PCL_DEPRECATED_HEADER(1, 12, "Deprecated in favor of pcl/type_traits.h") 
```

**Comment by kunaltyagi** [comment]
You can't use a macro like `#error`  or `#warning` in another macro.
* Pragma string can be used to circumvent this for warning
* For error, call a non-existent macro to cause a compile error, similar to the deprecated counterpart

This will need to be applied to the deprecated headers, not just added to `pcl_macros.h`
