### ISSUE TITLE
[docs] Ordering of header includes

### ISSUE THREAD

**Issue by divmadan** [PointCloudLibrary/pcl#3904]
**Description**

There is no documentation available to refer, regarding the ordering of includes to be followed throughout the source.

**Context**

While running clang-format, it rearranges header includes:
```
#include <pcl/common/eigen.h>	          #include <ctime>
#include <crime>	            ->    #include <pcl/common/eigen.h>	
#include <pcl/tracking/tracker.h>	  #include <pcl/tracking/tracker.h>	
```
[Blame from my PR](https://github.com/PointCloudLibrary/pcl/blame/723f2886a442dc82034be77568a8c65e913f9977/tracking/include/pcl/tracking/impl/tracker.hpp#L4L6)

While searching for documentation regarding the ordering, I found out there isn't one.

**Expected behaviour**

- A set pattern to be enforced throughout the source, with exceptions, if any, documented.
- No rearrangement while formatting code.

**Describe the solution you'd like**

1. Documentation of the order of includes, if we have one. Else, adoption of one.
    Example: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
2. Addition of a style option in our `.clang-format` file, to prevent rearranging.
    - Set `SortIncludes (bool)` as `false`.
    - Alternatively, explore options like `IncludeBlocks (IncludeBlocksStyle)` and `IncludeCategories (std::vector<IncludeCategory>)`.
    - [Clang format 10 documentation](https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormatStyleOptions.html)
3. Enforcing the order throughout the source (Discussion needed).
***
Initially suggested by @kunaltyagi in https://github.com/PointCloudLibrary/pcl/pull/3814#discussion_r406749664

**Comment by aPonza** [comment]
This was discussed previously, off the top of my head I can remember https://github.com/PointCloudLibrary/pcl/pull/3654#issuecomment-586961703 where there seemed to be an agreement on "library -> 3rd party -> std".

I'd argue it'd be nice to have the first include be the "main" include for the file: see https://github.com/PointCloudLibrary/pcl/pull/3898#issuecomment-611668454 where I mentioned clang-format's `IncludeIsMainSourceRegex` which would leave the first include of a file alone as the main one (i.e. the .h declaring the .hpp or the .cpp stuff to define).

**Comment by SunBlack** [comment]
Just to mention: I'm currently working on the adjustment to `.clang-format` (I don't see any PR currently for it, so just mention that not multiple PRs will be started ;-) )

**Comment by SunBlack** [comment]
PR is opened here #3909.

**Comment by kunaltyagi** [comment]
@divmadan @SunBlack Any new updates for doc module?

**Comment by divmadan** [comment]
If @SunBlack 's busy, I'll do it.

**Comment by divmadan** [comment]
To be added to the `2. Indentation and Formatting` in the [PCL style guide](https://github.com/PointCloudLibrary/pcl/blob/86ba2c118ac343d7ea8f8a21cf97364ff2d700a5/doc/advanced/content/pcl_style_guide.rst#pcl-c-programming-style-guide), right?
