### ISSUE TITLE
[Discussion] Ref-counted PointCloud

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3911]
**Is your feature request related to a problem? Please describe.**

Current ownership model is confusing. There's no way to use PCL and maintain value semantics.

**Context**

We see `shared_ptr` everywhere, which prohibit value-semantics based API. C++14 allows a more value-semantic based API due to:
* move semantics
* NVRO (underused in PCL)
* standard `atomic` and `shared_pointers` (for hiding ref-counting)

A value semantic based API will allow stack based variables to be used in the API.

**Expected behavior**
```cpp
pcl::PointCloud x;
filter.setInputCloud(x);
```

**Current Behavior**

```cpp
auto x = pcl::make_shared<pcl::PointCloud>();
filter.setInputCloud(x);
```

**Describe the solution you'd like**

A model similar to OpenCV, where:
* `Tensor<T>` as the base class for accessing underlying non-ref-counted data.
  * It's a vector and has a special value for invalid data (default: `std:numeric_limits<T>::max()`)
  * It can be a wrapper around `Eigen::Matrix` or `std::vector`
  * It takes care of memory layout (linear, row-wise, col-wise, weird, etc.), memory structure (direct-storage vs pointer-storage), etc
  * This class **needs** to be simple to move, but can be expensive to copy
* `StructuredTensor<std::tuple<T...>>` as a class for storing different `Tensor<T>` in some container (aka `std::tuple` or `std::vector` or `std::array` or `std::map`).
  * Each tensor is accessible by index (fast) as well as name (slow, `assert(s_tensor[0] == s_tensor["x"])`)
  * All stored tensors need to be of same "type". The "type" can be `Linear` (unstructured), `Planar` (structured), `Volumetric` (dense-structured). The size is stored in "type"
  * This class **needs** to be simple to move, but can be expensive to copy.
* `PointCloud` is a reference counter for `StructuredTensor`, is **cheap to copy**
  * It **must add no functionality** apart from the reference counting
  * Any functionality missing from `PointCloud` needs to be added to the class which is being stored with a reference count (in this case some derived class of `StructuredTensor`)
* `CloudIndices`, `CloudView` and `CloudSpan` are shared-owning classes giving an indirect-access, direct-read-only access and direct-write-access to the underlying `PointCloud`. These can't modify the details of the cloud (such as type, size, etc.)
* `TensorIndices`, `TensorView` and `TensorSpan` are non-owning counterparts which are faster because there's no ref-count access
* The pointcloud for the accessory classes can be modified by a single copy/move operation

`std::variant<T...>` for `StructuredTensor` would be something like `std::variant<PointXYZRGBA>`, but can be converted to something like `std::variant<PointXYZ, RGBA>` etc. This is similar to how you can split and merge channels in OpenCV.

The development would require:
* adding to `PointCloud` API and deprecate direct access to the underlying non-ref counted data
  * modifying the `PointCloud` to reference count instead, maybe using another name instead of `PointCloud` to prevent the 2 release cycle deprecation cycle
* add a `PointCloud` to `PCLIndices` and rename it to `CloudIndices` (we're already thinking of removing `PCLIndices` since it doesn't add much value over a simple `vector`)
  * modify `CloudIndices` to short circuit to `PointCloud` for the default case (all indices are valid)
* do the rest complicated stuff later.

The big benefit would involve:
* registration with images: `XYZ`+`RGB` can be stored separately. `RGB` can be a `cv::Mat` (or a wrapper for `cv::Mat`) in the application code (not in core library)
* filters will simply take the indices as input (instead of indices and point cloud)

**Describe alternatives you've considered**

Change the default pointer type from `shared_ptr` to a [custom class](https://godbolt.org/z/JcJ27_) which accepts non-owning pointers with minimal overhead. This allows similar semantics (but is a bit hacky) and could be useful for PCL's interface

**Additional context**

This started after the discord discussion (because I'm not satisfied with lack of value-semantics), where the availability of `shared_ptr` was preferred for ease of development

**Note**

No progress on implementation is expected anytime in the future (at least till GSoC 2020 ends) even if a decision is made.

**Comment by SergioRAgostinho** [comment]
Brief comments not addressing directly the content of the proposal at this stage:
- the level of changes required is worthy of bumping the major version, avoiding the deprecation cycle altogether.
- I would not like to perform this transition without library benchmarks metrics in place. I feel it's bad to go "blind" into a change of this magnitude.
- this is a topic I personally see as low priority in addressing. There are better candidates to spend man-hours in my opinion.
