### ISSUE TITLE
[compile error] Many winapi errors with All-in-one package 

### ISSUE THREAD

**Issue by takmin** [PointCloudLibrary/pcl#3913]
I failed to compile my source code with PCL 1.10.1 all-in-one package.

**My Environment:**

 - OS: Windows 10 Home versin:1903 build:18362.720
 - Compiler: Visual Studio 2019 Version 16.5.3
 - PCL Version 1.10.1 
 - PCL Type: I Installed windows all-in-one package linked the below
https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.10.1/PCL-1.10.1-AllInOne-msvc2019-win64.exe

**To Reproduce**
1. install windows all-in-one package
2. create new visual studio project
3. add the following simple cpp code to the project:

#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>

int main(int argc, char* argv[])
{
	return 0;
}

4. add include path:
    - '\Program Files\PCL 1.10.1\3rdParty\Eigen\eigen3;\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72;\Program Files\PCL 1.10.1\include\pcl-1.10'

5. compile it, then encounter many winapi errors. 

**Describe the error**
`
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(59,1): error C2116: 'boost::interprocess::winapi::CreateDirectoryA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(944): message : 'boost::interprocess::winapi::CreateDirectoryA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(59,1): error C2733: 'CreateDirectoryA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(944,48): message : 'boost::interprocess::winapi::CreateDirectoryA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(87,1): error C2116: 'boost::interprocess::winapi::CreateFileA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(931): message : 'boost::interprocess::winapi::CreateFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(87,1): error C2733: 'CreateFileA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(931,51): message : 'boost::interprocess::winapi::CreateFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(233,1): error C2116: 'boost::interprocess::winapi::FindFirstFileA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(915): message : 'boost::interprocess::winapi::FindFirstFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(233,1): error C2733: 'FindFirstFileA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(915,50): message : 'boost::interprocess::winapi::FindFirstFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(322,1): error C2116: 'boost::interprocess::winapi::FindNextFileA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(916): message : 'boost::interprocess::winapi::FindNextFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(322,1): error C2733: 'FindNextFileA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(916,50): message : 'boost::interprocess::winapi::FindNextFileA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(651,1): error C2116: 'boost::interprocess::winapi::GetFileInformationByHandle': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(963): message : 'boost::interprocess::winapi::GetFileInformationByHandle' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(651,1): error C2733: 'GetFileInformationByHandle': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(963,50): message : 'boost::interprocess::winapi::GetFileInformationByHandle' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(681,1): error C2116: 'boost::interprocess::winapi::GetFileSizeEx': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(937): message : 'boost::interprocess::winapi::GetFileSizeEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(681,1): error C2733: 'GetFileSizeEx': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(937,48): message : 'boost::interprocess::winapi::GetFileSizeEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(690,1): error C2371: 'boost::interprocess::winapi::GetFileType': 再定義されています。異なる基本型です。
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(914): message : 'boost::interprocess::winapi::GetFileType' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(690,1): error C2733: 'GetFileType': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(914,49): message : 'boost::interprocess::winapi::GetFileType' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(984,1): error C2116: 'boost::interprocess::winapi::LockFileEx': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(953): message : 'boost::interprocess::winapi::LockFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(984,1): error C2733: 'LockFileEx': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(953,48): message : 'boost::interprocess::winapi::LockFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1024,1): error C2116: 'boost::interprocess::winapi::ReadFile': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(956): message : 'boost::interprocess::winapi::ReadFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1024,1): error C2733: 'ReadFile': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(956,48): message : 'boost::interprocess::winapi::ReadFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1150,1): error C2116: 'boost::interprocess::winapi::SetFilePointerEx': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(950): message : 'boost::interprocess::winapi::SetFilePointerEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1150,1): error C2733: 'SetFilePointerEx': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(950,48): message : 'boost::interprocess::winapi::SetFilePointerEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1209,1): error C2116: 'boost::interprocess::winapi::UnlockFileEx': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(954): message : 'boost::interprocess::winapi::UnlockFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1209,1): error C2733: 'UnlockFileEx': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(954,48): message : 'boost::interprocess::winapi::UnlockFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1221,1): error C2116: 'boost::interprocess::winapi::WriteFile': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(955): message : 'boost::interprocess::winapi::WriteFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1221,1): error C2733: 'WriteFile': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(955,48): message : 'boost::interprocess::winapi::WriteFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1462,1): error C2371: 'boost::interprocess::winapi::GetTempPathA': 再定義されています。異なる基本型です。
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(946): message : 'boost::interprocess::winapi::GetTempPathA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h(1462,1): error C2733: 'GetTempPathA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(946,48): message : 'boost::interprocess::winapi::GetTempPathA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h(428,1): error C2116: 'boost::interprocess::winapi::CreateMutexA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(920): message : 'boost::interprocess::winapi::CreateMutexA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h(428,1): error C2733: 'CreateMutexA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(920,51): message : 'boost::interprocess::winapi::CreateMutexA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h(106,1): error C2116: 'boost::interprocess::winapi::GetProcessTimes': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(898): message : 'boost::interprocess::winapi::GetProcessTimes' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h(106,1): error C2733: 'GetProcessTimes': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(898,48): message : 'boost::interprocess::winapi::GetProcessTimes' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h(95,1): error C2116: 'boost::interprocess::winapi::GetSystemInfo': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(932): message : 'boost::interprocess::winapi::GetSystemInfo' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h(95,1): error C2733: 'GetSystemInfo': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(932,49): message : 'boost::interprocess::winapi::GetSystemInfo' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(68,1): error C2116: 'boost::interprocess::winapi::VirtualProtect': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(935): message : 'boost::interprocess::winapi::VirtualProtect' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(68,1): error C2733: 'VirtualProtect': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(935,48): message : 'boost::interprocess::winapi::VirtualProtect' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(231,1): error C2116: 'boost::interprocess::winapi::MapViewOfFileEx': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(929): message : 'boost::interprocess::winapi::MapViewOfFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(231,1): error C2733: 'MapViewOfFileEx': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(929,51): message : 'boost::interprocess::winapi::MapViewOfFileEx' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(273,1): error C2116: 'boost::interprocess::winapi::FlushViewOfFile': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(933): message : 'boost::interprocess::winapi::FlushViewOfFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(273,1): error C2733: 'FlushViewOfFile': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(933,48): message : 'boost::interprocess::winapi::FlushViewOfFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(282,1): error C2116: 'boost::interprocess::winapi::UnmapViewOfFile': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(924): message : 'boost::interprocess::winapi::UnmapViewOfFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(282,1): error C2733: 'UnmapViewOfFile': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(924,48): message : 'boost::interprocess::winapi::UnmapViewOfFile' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(342,1): error C2116: 'boost::interprocess::winapi::VirtualUnlock': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(934): message : 'boost::interprocess::winapi::VirtualUnlock' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h(342,1): error C2733: 'VirtualUnlock': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(934,48): message : 'boost::interprocess::winapi::VirtualUnlock' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(186,1): error C2116: 'boost::interprocess::winapi::FreeLibrary': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(960): message : 'boost::interprocess::winapi::FreeLibrary' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(186,1): error C2733: 'FreeLibrary': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(960,50): message : 'boost::interprocess::winapi::FreeLibrary' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(260,1): error C2371: 'boost::interprocess::winapi::GetModuleHandleA': 再定義されています。異なる基本型です。
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(962): message : 'boost::interprocess::winapi::GetModuleHandleA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(260,1): error C2733: 'GetModuleHandleA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(962,52): message : 'boost::interprocess::winapi::GetModuleHandleA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(342,1): error C2116: 'boost::interprocess::winapi::GetProcAddress': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(961): message : 'boost::interprocess::winapi::GetProcAddress' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(342,1): error C2733: 'GetProcAddress': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(961,54): message : 'boost::interprocess::winapi::GetProcAddress' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(663,1): error C2371: 'boost::interprocess::winapi::LoadLibraryA': 再定義されています。異なる基本型です。
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(959): message : 'boost::interprocess::winapi::LoadLibraryA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h(663,1): error C2733: 'LoadLibraryA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(959,52): message : 'boost::interprocess::winapi::LoadLibraryA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h(1054,1): error C2116: 'boost::interprocess::winapi::InitializeSecurityDescriptor': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(957): message : 'boost::interprocess::winapi::InitializeSecurityDescriptor' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h(1054,1): error C2733: 'InitializeSecurityDescriptor': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(957,48): message : 'boost::interprocess::winapi::InitializeSecurityDescriptor' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h(1390,1): error C2116: 'boost::interprocess::winapi::SetSecurityDescriptorDacl': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(958): message : 'boost::interprocess::winapi::SetSecurityDescriptorDacl' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h(1390,1): error C2733: 'SetSecurityDescriptorDacl': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(958,48): message : 'boost::interprocess::winapi::SetSecurityDescriptorDacl' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(3098,1): error C2116: 'boost::interprocess::winapi::CreateSemaphoreA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(925): message : 'boost::interprocess::winapi::CreateSemaphoreA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(3098,1): error C2733: 'CreateSemaphoreA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(925,51): message : 'boost::interprocess::winapi::CreateSemaphoreA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(3208,1): error C2116: 'boost::interprocess::winapi::CreateFileMappingA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(928): message : 'boost::interprocess::winapi::CreateFileMappingA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(3208,1): error C2733: 'CreateFileMappingA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(928,51): message : 'boost::interprocess::winapi::CreateFileMappingA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(212,1): error C2116: 'boost::interprocess::winapi::RegCloseKey': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(968): message : 'boost::interprocess::winapi::RegCloseKey' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(212,1): error C2733: 'RegCloseKey': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(968,49): message : 'boost::interprocess::winapi::RegCloseKey' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(692,1): error C2116: 'boost::interprocess::winapi::RegOpenKeyExA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(966): message : 'boost::interprocess::winapi::RegOpenKeyExA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(692,1): error C2733: 'RegOpenKeyExA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(966,49): message : 'boost::interprocess::winapi::RegOpenKeyExA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(848,1): error C2116: 'boost::interprocess::winapi::RegQueryValueExA': 関数パラメーター リストが宣言間で一致しません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(967): message : 'boost::interprocess::winapi::RegQueryValueExA' の宣言を確認してください
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h(848,1): error C2733: 'RegQueryValueExA': 'extern "C"' リンケージで関数をオーバーロードすることはできません
1>C:\Program Files\PCL 1.10.1\3rdParty\Boost\include\boost-1_72\boost\interprocess\detail\win32_api.hpp(967,49): message : 'boost::interprocess::winapi::RegQueryValueExA' の宣言を確認してください
1>C:\Program Files\PCL 1.10.1\include\pcl-1.10\pcl\io\low_level_io.h(73,16): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Program Files\PCL 1.10.1\include\pcl-1.10\pcl\io\low_level_io.h(78,16): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
`

**Comment by UnaNancyOwen** [comment]
It can be compile by adding following define to preprocessor definitions. 
I would recommend to create your own project using CMake.

```
_CRT_SECURE_NO_WARNINGS
BOOST_ALL_NO_LIB
BOOST_USE_WINDOWS_H
NOMINMAX
```

**Comment by takmin** [comment]
It works!
Thank you for your quick reply.
