### ISSUE TITLE
How to create point clouds Centroid to perform clustering from a set of coordinate  points in order to get the Oriented Bounding Box? 

### ISSUE THREAD

**Issue by astronaut71** [PointCloudLibrary/pcl#3918]
I have create a C++ function that get the coordinate points of the rectangle box of the detected object. I like to use this 8 points to create a Centroid and perform clustering with region growing algorithm in order to get the orientation of the object(quaternion). Here is my C++ function  to get the Box coordinate
```

void chatterCallback(const darknet_ros_3d_msgs::BoundingBoxes3d::ConstPtr& msg)
{ 
	if (!msg->bounding_boxes.empty())
		{
		    int inc = 1;
			if(msg->bounding_boxes[0].Class == "box")
				{
				std::vector<float> array_xmin(inc);
				std::vector<float> array_ymin(inc);
				std::vector<float> array_zmin(inc);
                                std::vector<float> array_xmax(inc);
				std::vector<float> array_ymax(inc);
				std::vector<float> array_zmax(inc);

				array_xmin[inc] = msg->bounding_boxes[0].xmin; 
				array_xmax[inc] = msg->bounding_boxes[0].xmax; 
			        array_ymin[inc] = msg->bounding_boxes[0].ymin;
				array_ymax[inc] = msg->bounding_boxes[0].ymax; 
				array_zmin[inc] = msg->bounding_boxes[0].zmin; 
				array_zmax[inc] = msg->bounding_boxes[0].zmax;  
					
				inc++;
							
				       }			
						
				}
	}
```
So how to feed this xmin, xmax, ymin, ymax, zmin, zmax in the point cloud to create Centroid and then segmentation and then get the orientation of the object? Thanks

**Comment by jasjuang** [comment]
You can compute the centroid via the [CentroidPoint](http://docs.pointclouds.org/trunk/classpcl_1_1_centroid_point.html) class, but you have to feed in point clouds as input instead of the bounding box coordinates.
