### ISSUE TITLE
Tutorials are out of date

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3919]
**Describe the bug**

The tutorials are out-of-date wrt
* Code
* Best practices

They also don't get tested on the CI using an expectation based testing framework.

This causes issues with old and new users of PCL who don't have a good reference source.

**How to help**

1. Please go through the tutorials
2. Flag any that's not up-to-date, gives wrong results or worse
3. Create and issue and refer the issue via a comment here or by using this issue's number over there.

**Comment by chaytanyasinha** [comment]
@kunaltyagi May I write new tutorial wrt to new codes and it's practices?

**Comment by kunaltyagi** [comment]
What kind of tutorial do you have in mind?

**Comment by chaytanyasinha** [comment]
@kunaltyagi  I will try using the new features added and bugs fixed and add about them in the existing tutorial along with examples where ever needed.

**Comment by kunaltyagi** [comment]
What new features do you have in mind?

**Comment by chaytanyasinha** [comment]
Adding about benchmarks,New CI after it's done and about the binding interfaces and unified API for PCL algorithm

**Comment by jedfrechette** [comment]
Where are the tutorials even located these days?

I thought they were at pointclouds.org (e.g. http://pointclouds.org/documentation/tutorials/pcd_file_format.php) but that just redirects to the API docs at pointcloudlibrary.github.io and results in 404 errors.

**Comment by kunaltyagi** [comment]
New location: https://pcl-tutorials.readthedocs.io/
Advanced: https://pcl-advanced.readthedocs.io/
