### ISSUE TITLE
[filters] Add set filter and set based operations to add/remove points from point clouds

### ISSUE THREAD

**Issue by duongbaoquy** [PointCloudLibrary/pcl#3921]
Hi,
Thanks for a very good library.
I am currently trying to merge point cloud,I have two point cloud aligned and concatenated but their concatenation contains duplicate point cloud of the same part. How can I delete this duplication without losing data. I searched the internet but there wasn't much information, I tried some sample code to look like this:
`
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud1(new pcl::PointCloud<pcl::PointXYZRGB>);
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud2(new pcl::PointCloud<pcl::PointXYZRGB>);
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr outputCloud(new pcl::PointCloud<pcl::PointXYZRGB>);
    pcl::io::loadPLYFile("a.ply", *cloud1);
    pcl::io::loadPLYFile("b.ply", *cloud2);

    pcl::copyPointCloud<pcl::PointXYZRGB, pcl::PointXYZRGB>(*cloud1, *cloud2);
    bool condition1 = false; bool condition2 = false;

    for (int i = 0; i < (cloud1->points.size()); i++) {
        condition1 = (isnan(cloud1->points[i].x)) && (isnan(cloud1->points[i].y)) && (isnan(cloud1->points[i].z));
        condition2 = (!isnan(cloud2->points[i].x)) && (!isnan(cloud2->points[i].y)) && (!isnan(cloud2->points[i].z));
        if (condition1 && condition2) {
            cloud1->points[i].x = cloud2->points[i].x;
            cloud1->points[i].y = cloud2->points[i].y;
            cloud1->points[i].z = cloud2->points[i].z;
        }
       
    }
    std::vector<int> indices;
    pcl::removeNaNFromPointCloud(*cloud1, *outputCloud, indices);
    pcl::io::savePLYFileBinary("out1.ply", *outputCloud);
`
but the output is not really different, i don't know why the size of output is smaller than normall
Thanks for your time.

**Comment by shrijitsingh99** [comment]
You can use VoxelFilter for this but their might be some loss in accuracy of the pointcloud.

**Comment by kunaltyagi** [comment]
Proposal: How about a sort based filter to remove duplicates? If the points are sorted (based on 3D Morton code) (or reversibly hashed), then it'll be easy to iterate on the sorted points (or hashed domain) and remove duplicates.

**Comment by duongbaoquy** [comment]
> You can use [VoxelGrid Filter](http://pointclouds.org/documentation/tutorials/voxel_grid.php) for this but their might be some loss in accuracy of the pointcloud.

Thanks for your reply, I used it - and it worked fine but that's not what I meant, it just removes Points on one layer. I will express my wishes through the image below, hope it is easy for you to understand

![123](https://user-images.githubusercontent.com/62133702/79527859-d415cb00-8092-11ea-9db5-fe2cd57a492a.jpg)



> Proposal: How about a sort based filter to remove duplicates? If the points are sorted (based on 3D Morton code) (or reversibly hashed), then it'll be easy to iterate on the sorted points (or hashed domain) and remove duplicates.

Yea, that would be great if i can do it - or at least look like the image above - Can you tell me how to do it or use which filter? Or I have to wait for the update?

**Comment by kunaltyagi** [comment]
> Can you tell me how to look like the image above or use which filter?

No such filter exists in PCL.

> I have to wait for the update?

It'd be better if you start a PR where others can help you. What you're trying to do is a set difference which would be a nice addition to point-wise operations

**Comment by duongbaoquy** [comment]
Ok thanks for your answer.

**Comment by Pran-Seven** [comment]
@duongbaoquy were you able to achieve your desired output?
