### ISSUE TITLE
[compile error] "Error linking with libomp with Apple Clang"

### ISSUE THREAD

**Issue by truhoang** [PointCloudLibrary/pcl#3922]
I've been trying for several days to build PCL on my mac unsuccessfully. I'm gonna keep trying but any pointers from veteran developers would be much appreciated. 

**Describe the error**
I recently updated to macOS Catalina 10.15.4 to fix #2601. Those errors don't come up anymore but now I'm getting these.
```
Undefined symbols for architecture x86_64:
  "___kmpc_dispatch_init_4", referenced from:
      _.omp_outlined. in range_image.cpp.o
  "___kmpc_dispatch_next_4", referenced from:
      _.omp_outlined. in range_image.cpp.o
  "___kmpc_end_reduce_nowait", referenced from:
      _.omp_outlined. in range_image.cpp.o
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in kiss_fft.c.o
  "___kmpc_for_static_init_4", referenced from:
      _.omp_outlined. in kiss_fft.c.o
  "___kmpc_fork_call", referenced from:
      pcl::RangeImage::getOverlap(pcl::RangeImage const&, Eigen::Transform<float, 3, 2, 0> const&, int, float, int) const in range_image.cpp.o
      _kf_work in kiss_fft.c.o
  "___kmpc_global_thread_num", referenced from:
      pcl::RangeImage::getOverlap(pcl::RangeImage const&, Eigen::Transform<float, 3, 2, 0> const&, int, float, int) const in range_image.cpp.o
      _.omp_outlined. in range_image.cpp.o
  "___kmpc_push_num_threads", referenced from:
      pcl::RangeImage::getOverlap(pcl::RangeImage const&, Eigen::Transform<float, 3, 2, 0> const&, int, float, int) const in range_image.cpp.o
  "___kmpc_reduce_nowait", referenced from:
      _.omp_outlined. in range_image.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Your Environment (please complete the following information):**

 - OS: macOS Catalina 10.15.4
 - Compiler: Apple clang version 11.0.3 (clang-1103.0.32.29)
 - PCL Version HEAD
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No
 - List and Version of dependencies used: all latest from Homebrew
 - Compilation flags are used

**Possible Solution**

I've tried solutions from [here](https://github.com/ethz-asl/pcl_catkin/pull/15), [here](https://github.com/pytorch/pytorch/issues/6328), and [here](https://github.com/CLIUtils/cmake/blob/2acdd6dd3f61dddba3448ab231e4adcf274a3ec3/PatchOpenMPApple.cmake)

**Comment by kunaltyagi** [comment]
Tracked in #3721

**Comment by SergioRAgostinho** [comment]
The first part of the problem should be fixed now. Just pull the latest HEAD. Your downstream project might complain about omp linker flags, but you can explicitly add those in your cmake file until we correct the situation and propagate the flags properly.

**Comment by truhoang** [comment]
@kunaltyagi thanks. I added the `target_link_libraries()` line from that PR to `pcl_targets.cmake` and it's building. Also is there a reason we don't use `llvm` for compiling?

**Comment by kunaltyagi** [comment]
> we don't use llvm for compiling?

I'm sorry, I didn't get this.

Do you link PCL with downstream targets? If so, can you confirm that the compiler flags are being propagated properly (by linking to pcl and not to libomp)?

**Comment by truhoang** [comment]
@kunaltyagi I'm still new to CMake so when I was debugging this issue, I saw that CMake defines specific flags for 4 compilers: clang, msvc, pathscale and mingw. Some of the link I listed suggested to use `llvm` in place of `clang`. I might be misunderstanding compilers.

I'm not linking PCL with any project. Was planning to add some features.
