### ISSUE TITLE
How to store point cloud data to array ?

### ISSUE THREAD

**Issue by minhhieu14351997** [PointCloudLibrary/pcl#3928]
Currently I have point cloud data as "newCloud_y" but I want to save point cloud data to array after each processing eg:
```cpp
unsigned __int32 cloud_i = 0;
pcl::PointCloud<pcl::PointXYZRGB>::Ptr newCloud_y(new pcl::PointCloud<pcl::PointXYZRGB>);
pcl::PointCloud<pcl::PointXYZRGB>::Ptr** cloud_clusters_ptr;
cloud_clusters_ptr[cloud_i] = new pcl::PointCloud<pcl::PointXYZRGB>::Ptr (new pcl::PointCloud<pcl::PointXYZRGB>);
...
cloud_i = cloud_i + 1;
pcl::copyPointCloud(*newCloud_y,*cloud_clusters_ptr[cloud_i]);
```
but appear this error: 
![image](https://user-images.githubusercontent.com/40237041/79426670-a9be0200-7fed-11ea-871d-811c79a445c9.png)
and if i'm use 
```cpp
*cloud_clusters_ptr[cloud_i] = *newCloud_y;
```
instead of above code
```cpp
pcl::copyPointCloud(*newCloud_y,*cloud_clusters_ptr[cloud_i]);
```
then I got this error:
![image](https://user-images.githubusercontent.com/40237041/79426944-16d19780-7fee-11ea-8add-e88a85961cca.png)
Please tell me how to solve this problem. Thanks so much

**Comment by kunaltyagi** [comment]
You can just use `PointCloud<T>::points` of type `std::vector<T, custom_allocator>`

**Comment by minhhieu14351997** [comment]
> You can just use `PointCloud<T>::points` of type `std::vector<T, custom_allocator>`

Can you say it in more detail?

**Comment by kunaltyagi** [comment]
If you want a deep-copy of the data, copy the vector.

If you want a reference to the data, use `std::vector<PointCloud<T>::Ptr>` and use `push_back` or `emplace_back` to save the point cloud.
