### ISSUE TITLE
How to get Rotational Matrix for Oriented Bounding Box. major_vector,   middle_vector, minor_vector and mass centerin Point Cloud Library

### ISSUE THREAD

**Issue by astronaut71** [PointCloudLibrary/pcl#3936]
I am able to get the min and max (8 points)  of the 3D centroid of the detected object in the point cloud. So I would like to find the orientation of this Bounding box using PCL. For that purpose I need OBB. I follower the tutorial here [http://pointclouds.org/documentation/tutorials/moment_of_inertia.php](url)  So how to find the rotation matrix, major_vector, middle_vector, minor_vector  so can rotate the axis aligned box according to the cloud as i need the yaw information from the box.

pcl::MomentOfInertiaEstimation <pcl::PointXYZ> feature_extractor;
feature_extractor.setInputCloud (cloud);
feature_extractor.compute ();

pcl::PointXYZ min_point_OBB;
pcl::PointXYZ max_point_OBB;
pcl::PointXYZ position_OBB;
Eigen::Matrix3f rotational_matrix_OBB;
Eigen::Vector3f major_vector, middle_vector, minor_vector;
Eigen::Vector3f mass_center;

feature_extractor.getOBB (min_point_OBB, max_point_OBB, position_OBB, rotational_matrix_OBB);
feature_extractor.getEigenVectors (major_vector, middle_vector, minor_vector);
feature_extractor.getMassCenter (mass_center);

Then how to get the rotational_matrix_OBBcause for the final OBB coordinates:

```
Eigen::Vector3f p1 (min_point_OBB.x, min_point_OBB.y, min_point_OBB.z);
Eigen::Vector3f p2 (min_point_OBB.x, min_point_OBB.y, max_point_OBB.z);
Eigen::Vector3f p3 (max_point_OBB.x, min_point_OBB.y, max_point_OBB.z);
Eigen::Vector3f p4 (max_point_OBB.x, min_point_OBB.y, min_point_OBB.z);
Eigen::Vector3f p5 (min_point_OBB.x, max_point_OBB.y, min_point_OBB.z);
Eigen::Vector3f p6 (min_point_OBB.x, max_point_OBB.y, max_point_OBB.z);
Eigen::Vector3f p7 (max_point_OBB.x, max_point_OBB.y, max_point_OBB.z);
Eigen::Vector3f p8 (max_point_OBB.x, max_point_OBB.y, min_point_OBB.z);

p1 = rotational_matrix_OBB * p1 + position;
p2 = rotational_matrix_OBB * p2 + position;
p3 = rotational_matrix_OBB * p3 + position;
p4 = rotational_matrix_OBB * p4 + position;
p5 = rotational_matrix_OBB * p5 + position;
p6 = rotational_matrix_OBB * p6 + position;
p7 = rotational_matrix_OBB * p7 + position;
p8 = rotational_matrix_OBB * p8 + position;
```

I need the rotational_matrix_OBB, but how to get it? Thanks

**Comment by mvieth** [comment]
Sorry that you did not get an earlier answer.
If you still need it (or if anyone else faces this problem): please have a closer look at [the documentation of getOBB()](https://pointclouds.org/documentation/classpcl_1_1_moment_of_inertia_estimation.html#a86e92ba5fc831ebbe4c106e1e0c60a8b). You basically get the rotation matrix by giving it as the last argument of the function. As a side note: if you only need the oriented bounding box, you don't need `major_vector`, `middle_vector`, `minor_vector`, and `mass_center`. I hope this helps.
