### ISSUE TITLE
Reading data from xyz file format?

### ISSUE THREAD

**Issue by ibrahimLearning** [PointCloudLibrary/pcl#3952]
I want to read data from .xyz format file. I searched in Internet and documentation of the pcl. I did not get any solution.

How can I read .xyz file format? 
I think classes, functions and documentation for reading and writing  should be improved.

**Comment by SergioRAgostinho** [comment]
https://stackoverflow.com/a/41590026/9458162

> No, there is not an official specification about the .xyz format for point clouds.
> 
> The .xyz format can be considered as part of a more general type of file formats: ASCII point cloud. You can consider members of this group many other extensions like: .asc,.txt,.pts
> 
> The problem is that because of that lack of specification the contents of the file may vary according to the creator. 

But what you want is probably  provided by [`pcl::ASCIIReader`](http://docs.pointclouds.org/trunk/classpcl_1_1_a_s_c_i_i_reader.html)
