### ISSUE TITLE
PCD binary compressed data

### ISSUE THREAD

**Issue by ChaturvediShilpa** [PointCloudLibrary/pcl#3955]
Hi team,

I want to know what is the difference between pcd binary and pcd binary compressed data format. 

Thanks

**Comment by SergioRAgostinho** [comment]
As the name implies, in the latter, the data is actually compressed with an LZF compression algorithm

From the [docs](http://docs.pointclouds.org/trunk/namespacepcl.html#a2bf72a3e909eaac4e666bc4ef0f835f8)
> Compress in_len bytes stored at the memory block starting at in_data and write the result to out_data, up to a maximum length of out_len bytes using Marc Lehmann's LZF algorithm. 

I believe it refers to this http://oldhome.schmorp.de/marc/liblzf.html
