### ISSUE TITLE
[filters] ConditionalRemoval sometimes produces incorrect filtered cloud

### ISSUE THREAD

**Issue by mhudnell** [PointCloudLibrary/pcl#3958]
**Describe the bug**

Using a ConditionalRemoval filter to remove points sometimes produces the correct filtered cloud, sometimes it produces an incorrect cloud (even though the code and inputs are the same). 

I am unsure why this happens, but I suspect it's some sort of multi-threaded race condition.

**Context**

I am trying to merge four point clouds, and then remove all points not within a specific cylinder.

**Expected behavior**

The filtered output cloud should be correct every time the code is run.

**Current Behavior**

Running the code sometimes produces the correctly filtered cloud, sometimes it is incorrect (even though the code is not changed).

**Screenshots/Code snippets**

```c++
int main(int argc, char** argv)
{

	// load in 4 point clouds
        ...

	// merge the 4 clouds
	pcl::PointCloud<pcl::PointXYZ>::Ptr merged_cloud(new pcl::PointCloud<pcl::PointXYZ>);
	*merged_cloud += cloud0;
	*merged_cloud += cloud1;
	*merged_cloud += cloud2;
	*merged_cloud += cloud3;

	// crop inner cylinder -- x^2/r^2 + z^2/r^2 = 1
	pcl::ConditionAnd<pcl::PointXYZ>::Ptr crop_condition(new pcl::ConditionAnd<pcl::PointXYZ>);

	Eigen::Matrix3f A;
	float radius = 0.7;
	float radius_sqr = radius * radius;
	A << 1 / radius_sqr, 0, 0,	
		0, 0, 0,
		0, 0, 1 / radius_sqr;
	Eigen::Vector3f v;
	float c = -1.0;

	pcl::TfQuadraticXYZComparison<pcl::PointXYZ>::Ptr quad_comp(new pcl::TfQuadraticXYZComparison<pcl::PointXYZ>(
		pcl::ComparisonOps::LT, A, v, c
		));

	crop_condition->addComparison(quad_comp);

	// crop floor (everything below y = -0.82)
	pcl::FieldComparison<pcl::PointXYZ>::Ptr floor_plane_comp(new pcl::FieldComparison<pcl::PointXYZ>(
		"y", pcl::ComparisonOps::GT, -0.8
		));

	crop_condition->addComparison(floor_plane_comp);


	// build the filter
	pcl::ConditionalRemoval<pcl::PointXYZ> condrem;
	condrem.setCondition(crop_condition);
	condrem.setInputCloud(merged_cloud);

	// get filtered cloud
	pcl::PointCloud<pcl::PointXYZ> filtered_cloud;
	condrem.filter(filtered_cloud);

	// write to .ply
	std::string file_name = "filtered_cloud.ply";
	pcl::io::savePLYFile(file_name, filtered_cloud);

}
```

correct cloud:
<img width="706" alt="correct_crop" src="https://user-images.githubusercontent.com/12748650/79937924-27887000-8429-11ea-8799-f882131af7b0.PNG">

incorrect cloud:
<img width="691" alt="incorrect_crop" src="https://user-images.githubusercontent.com/12748650/79937931-2e16e780-8429-11ea-9bff-b54e939d483b.PNG">

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: MSVC 19.16.27035.0
 - PCL Version 1.9.1

**Possible Solution**

I suspect it's some sort of multi-threaded race condition, but I'm not sure how to verify / fix. I would appreciate any insights!

**Comment by kunaltyagi** [comment]
Where's the race? I don't see any threading in your code.

**Comment by mhudnell** [comment]
I'm not intentionally multi-threading anything. That was more of a guess as to maybe what is happening in the internals of PCL, sorry.

**Comment by mhudnell** [comment]
I just fixed the bug, it was on my end. Did not initialize `Eigen::Vector3f v` to 0. Closing issue!
