### ISSUE TITLE
[common] Add member functions cbegin() and cend() for accessing const_iterator in PointCloud

### ISSUE THREAD

**Issue by shrijitsingh99** [PointCloudLibrary/pcl#3966]
Add member functions `cbegin()` and `cend()` to return `const_iterator` for pointclouds.
Currently to use `const_iterator` it has to be explicitly declared and you cannot use `auto`.

**Expected behavior**

```cpp
for (auto it = cloud.cbegin(); it != cloud.cend(); ++it ) { .. }
```

**Current Behavior**

```cpp
for (PointCloud<PointXYZ>::const_iterator it = cloud.cbegin(); it != cloud.cend(); ++it ) { .. }
```
or 

```cpp
for (auto it = cloud.points.cbegin(); it != cloud.points.cend(); ++it ) { .. }
```

**Comment by kunaltyagi** [comment]
It might be better to have PointCloud conform to requirements of a [`ReversibleContainer`](https://en.cppreference.com/w/cpp/named_req/ReversibleContainer)
