### ISSUE TITLE
[custom] Segmentation Fault during Normal Estimation "compute" - ROS

### ISSUE THREAD

**Issue by aled96** [PointCloudLibrary/pcl#3978]
Hi,
I am using PCL 1.10.1 with ROS. I am new and I trying to learn it but I have a problem.
When the node calls the function "compute" for the Normal Estimation of a point cloud, a segmentation fault comes out. I used rosmon to trace it, debugging and I obtained this:
![Error1](https://user-images.githubusercontent.com/37381508/80287783-8e609e80-8733-11ea-9132-d8bb09ada816.png)

The code I used it is the same of the tutorial on the official website and if I use it in a cpp file, it works, but when I move to a ROS node this problem comes out..

Thank you very much !

**Comment by kunaltyagi** [comment]
Does the problem exist without ROS?

**Comment by aled96** [comment]
No.. without ROS it works...

But other person, with the same code, do not have this problem and they can run also with ROS

What could it be?

**Comment by kunaltyagi** [comment]
In that case, your code is at fault. Probably bad memory management

Please consult with [ROS community](https://discourse.ros.org) to find the errors.
