### ISSUE TITLE
[GPU] Replace CV_XADD by C++11 method

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#3987]
Currently we are using proprietary code here

https://github.com/PointCloudLibrary/pcl/blob/7118b625bf815b829f802c660ab268da471338ac/gpu/containers/src/device_memory.cpp#L79-L94

I don't know why there is a thread-safety reference counter, but we can replace `CV_XADD` by [atomic operations](https://en.cppreference.com/w/cpp/atomic) of C++11 (I believe [atomic_fetch_add](https://en.cppreference.com/w/cpp/atomic/atomic_fetch_add) should fit)

**Comment by kunaltyagi** [comment]
If these are used in host, :+1:

For device however, proceed carefully since some versions of CUDA still don't support atomic operations.

**Comment by SunBlack** [comment]
This looks more like host code for me ;-).

**Comment by rabaho** [comment]
CV_XADD is host code for sure. First, the code was copied from OpenCV without acknowledgement, there is even comments left behind tying it to OpenCV. Second, I am not sure why we're reinventing the wheel with ref counting, shared_ptr would do the work.

**Comment by mvieth** [comment]
Fixed by the pull request linked above
