### ISSUE TITLE
[Windows] PCL and QHull: unresolved externals

### ISSUE THREAD

**Issue by JaKno63** [PointCloudLibrary/pcl#4000]
Hi,

OS: Windows 10 1903
Compiler: Microsoft Visual Studio Professional 2019
PCL Version 1.10.0, HEAD

I cloned Qhull from github, ran cmake and then Visual Studio to build it. After this I ran cmake for PCL, activated qhull, opened Visual Studio again and rebuilded all projects. So far ok for me.

But if I try to use qhull in my code
```
#include <pcl/surface/concave_hull.h>

pcl::PointCloud<<pcl::PointXYZ>>::Ptr cloud;
pcl::PointCloud<<pcl::PointXYZ>>::Ptr hull;

pcl::ConcaveHull<<pcl::PointXYZ>> chull;
chull.setInputCloud(cloud);
chull.setAlpha(0.1);
chull.reconstruct(*hull);
```
I get these unresolved externals
```
error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::ConcaveHull<struct pcl::PointXYZ>::performReconstruction(struct pcl::PolygonMesh &)" (?performReconstruction@?$ConcaveHull@UPointXYZ@pcl@@@pcl@@MEAAXAEAUPolygonMesh@2@@Z)
error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::ConcaveHull<struct pcl::PointXYZ>::performReconstruction(class std::vector<struct pcl::Vertices,class std::allocator<struct pcl::Vertices> > &)" (?performReconstruction@?$ConcaveHull@UPointXYZ@pcl@@@pcl@@MEAAXAEAV?$vector@UVertices@pcl@@V?$allocator@UVertices@pcl@@@std@@@std@@@Z)
error LNK2001: unresolved external symbol "public: void __cdecl pcl::ConcaveHull<struct pcl::PointXYZ>::reconstruct(class pcl::PointCloud<struct pcl::PointXYZ> &)" (?reconstruct@?$ConcaveHull@UPointXYZ@pcl@@@pcl@@QEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@@Z)
```
I already added pcl_surface.lib to the linker, so what I'm missing?

Thanks in advance
Jan

**Comment by JaKno63** [comment]
Do you need any additional information from my side?

**Comment by mvieth** [comment]
Sorry that you did not get an answer earlier. I would look into the output when building PCL, whether QHull was found and whether `ConcaveHull` was built. I am going to close this issue, but if you still have this problem, feel free to comment or open a new issue
