### ISSUE TITLE
[compile error] people/src/hog.cpp failure on non-SSE2 platform

### ISSUE THREAD

**Issue by tkircher** [PointCloudLibrary/pcl#4002]
In pcl::people::HOG::gradHist() there's an if defined(__SSE2__) where

int y=0;

is declared in the SSE2 section, but not in the non-SSE2 section, causing a build failure.

**Comment by kunaltyagi** [comment]
PTAL if the PR fixes the issue

**Comment by tkircher** [comment]
@kunaltyagi Yep, fixed.
