### ISSUE TITLE
[Announcement] GSoC 2021

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4008]
Hi,

We're happy to announce that PCL is participating in GSoC 2021. During these sprints, the maintainers and mentors will prioritize on reviewing PR by the officially accepted projects. This is because the projects will have the contributors working on a 30+ hour schedule a week and they can't be delayed since they face monthly evaluations by the organizers.

As a result, other contributors, issues and PR might see a reduced rate of response from the people working closely on GSoC and GSoD. The increased response time might be frustrating to others since they will see other issues and PRs being responded to with a much shorter turn around times. To mitigate this, we have 2 new labels for marking the priority issues and PRs: [`priority: gsoc`](https://github.com/PointCloudLibrary/pcl/labels/priority%3A%20gsoc) and [`priority: gsod`](https://github.com/PointCloudLibrary/pcl/labels/priority%3A%20gsod)

We encourage other members of the community to step-in and help reduce the resulting backlogs due to increased contributions during these periods. The non-priority (aka unlabeled) issues and PR can be found [here](https://github.com/PointCloudLibrary/pcl/issues?q=is%3Aopen+-label%3A%22priority%3A+gsoc%22+-label%3A%22priority%3A+gsod%22+)

Thank you for your understanding 😄

**Comment by kunaltyagi** [comment]
Update: PCL was not selected for GSoD 2020

**Comment by larshg** [comment]
Close this one or update it 😄
