### ISSUE TITLE
[Windows Installer] "Cmake does not work with Boost version provided in pcl-1.10.0 and pcl-1.10.1 AllinOne installers"

### ISSUE THREAD

**Issue by vestri** [PointCloudLibrary/pcl#4034]
**Describe the error**

Generation of a projet using CMake fails after installation of pcl-1.10.0 and pcl-1.10.1. 

**To Reproduce**

Just install pcl-1.10.1-pdb-msvc2019-win64.zip then compile minimum pcl projetc: https://github.com/kunaltyagi/pcl-cmake-minimum/

**Build information**

Next is the error:
Found Eigen: C:/Users/cvestri/Work/Install/PCL/PCL 1.10.1/3rdParty/Eigen/eigen3 (Required is at least version "3.1") 
Eigen found (include: C:/Users/cvestri/Work/Install/PCL/PCL 1.10.1/3rdParty/Eigen/eigen3, version: 3.3.7)
CMake Warning at C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:896 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1018 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindBoost.cmake:1694 (_Boost_MISSING_DEPENDENCIES)
  C:/Users/cvestri/Work/Install/PCL/PCL 1.10.1/cmake/PCLConfig.cmake:131 (find_package)
  C:/Users/cvestri/Work/Install/PCL/PCL 1.10.1/cmake/PCLConfig.cmake:311 (find_boost)
  C:/Users/cvestri/Work/Install/PCL/PCL 1.10.1/cmake/PCLConfig.cmake:546 (find_external_library)
  CMakeLists.txt:11 (find_package)

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: MSVC 16 2019
 - PCL Version: 1.10.0 and 1.10.1
 - PCL Type: AllInOne installer

**Possible Solution**

I made it working using Boost installation from 1.9.1 installer (boost version 1_68). I simply replaced the 3rdParty/Boost directory

**Comment by larshg** [comment]
It's only a warning. What version of cmake did you use - can you try update it?

**Comment by vestri** [comment]
Thanks for reply.
I used CMake-gui 3.14.1.
It is not only warnings, it could not find boost
![image](https://user-images.githubusercontent.com/4747304/80999192-919b0f00-8e44-11ea-959b-c200f870bdd4.png)

**Comment by larshg** [comment]
Arnes bilist 1.72 was first added to cmake 16.2. See [here](https://gitlab.kitware.com/cmake/cmake/-/commit/e51232b739b3eeae642be8a7e89079f7c2e8c1b2)

**Comment by vestri** [comment]
Thanks a lot. it worked.
