### ISSUE TITLE
[question]How does “determineCorrespondences()” in "correspondence_estimation.hpp" calculate the weight

### ISSUE THREAD

**Issue by nanfeng-dada** [PointCloudLibrary/pcl#4043]
i don't find the code to calculate the weight of correspondence in “determineCorrespondences()” in "correspondence_estimation.hpp" 

the pcl doc said  " weight denoting the confidence in correspondence estimation"，but I want to know how the weights are calculated.
` 
struct Correspondence
   {
     /** \brief Index of the query (source) point. */
     int index_query = 0;
     /** \brief Index of the matching (target) point. Set to -1 if no correspondence found. */
     int index_match = -1;
     /** \brief Distance between the corresponding points, or the weight denoting the confidence in correspondence estimation */
     union
     {
       float distance = std::numeric_limits<float>::max();
       float weight;
     };
  `

**Comment by kunaltyagi** [comment]
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/correspondence_estimation.hpp#L120

**Comment by nanfeng-dada** [comment]
I'm still confused, the code don't show how to calculate the weight, it did calculate the distance,index_query and index_match ; but I don't find weight
`

    for (std::vector<int>::const_iterator idx = indices_->begin (); idx != indices_->end (); ++idx)
    {
      tree_->nearestKSearch (input_->points[*idx], 1, index, distance);
      if (distance[0] > max_dist_sqr)
        continue;

      corr.index_query = *idx;
      corr.index_match = index[0];
      corr.distance = distance[0];
      correspondences[nr_valid_correspondences++] = corr;

`

**Comment by kunaltyagi** [comment]
Here, the distance is used as a measure of estimating the confidence in the match. Please read [the tutorial](https://pcl-tutorials.readthedocs.io/en/master/registration_api.html#correspondences-estimation) for more information

**Comment by kunaltyagi** [comment]
PS: Github issue-tracker is for bugs, proposals, etc. Such questions and discussion are better suited in discord or as a proposal to add new tutorials/documentation

**Comment by nanfeng-dada** [comment]
thanks for your answer and suggestion
