### ISSUE TITLE
[segmentation] How can I initialise coefficients for a model if I know its approximate location?

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4044]
I'm reading the tutorial on [plane segmentation](https://pcl-tutorials.readthedocs.io/en/latest/planar_segmentation.html#id1), because I want to find 3D circles in a very large and dense large pointcloud I have.

I know already the approximate values for center, radius and orientation of the circle, but I have found no way so far to inform the `SACSegmentation` object of this fact. I could also name 3 inliers to compute initial values on, but I also don't find a way to do this.

My pointcloud is extremely large (10-20M points), so just random samples will likely be prohibitive, especially since I know already more or less what the parameter values should be and only want to optimize them.

How can I set the starting point of the Sample Consensus optimization procedure?

**Comment by themightyoarfish** [comment]
I've posted this on Stackoverflow https://stackoverflow.com/questions/61615306/pcl-ransac-model-fitting-how-can-i-initialise-the-model-parameters.

Probably this issue tracker is not the place for support requests?

**Comment by kunaltyagi** [comment]
`SACSegmentation::segment` along with `SACSegmentation::setOptimizeCoefficients`

**Comment by themightyoarfish** [comment]
Huh, if that works, then I suppose the function documentation could use an update.

**Comment by kunaltyagi** [comment]
Please feel free to send a PR to both the documentation and tutorial if that works. If it doesn't, feel free to jump on discord or use SO or file a bug-report 😃

**Comment by mvieth** [comment]
In case anyone else finds this issue, some of the information here is not correct. Please read my comment from this other issue:
https://github.com/PointCloudLibrary/pcl/issues/5611#issuecomment-1469669615
