### ISSUE TITLE
[tests][CI] Visualization tests not being built/run on the CI

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4054]
The test is set as being build in the [cmake configuration](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=16109&view=logs&j=ee32b0f4-420e-5974-abf0-bb76a4ab271b&t=6a06a7d0-962a-5421-0000-9b8b322365a4&l=155).

but its not build and run in the [Run Unit Test](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=16109&view=logs&jobId=d0d530cd-2c5d-5eb2-7bb0-02dfe64fb679&j=ee32b0f4-420e-5974-abf0-bb76a4ab271b&t=11aea1df-f992-554b-c9de-a6b47ae4e2b9).

_Originally posted by @larshg in https://github.com/PointCloudLibrary/pcl/pull/4016#issuecomment-623169451_

**Comment by kunaltyagi** [comment]
It's not the test itself, it's the `tests_visualization` module as a whole. (Which contains a single target `test_visualization`).

Posted by @taketwo

**Comment by SergioRAgostinho** [comment]
The original xvfb suggestion should be fairly straighforward to set-up, enabling the unit tests to run.

**Comment by kunaltyagi** [comment]
Something for the person tacking this issue: CMake checks for `$DISPLAY`

**Comment by larshg** [comment]
Closed by #4589.
