### ISSUE TITLE
[search] isFinite is not found in brute_force.hpp

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#4055]
**Describe the bug**

as header says.

**Context**

Building pcl.

**Expected behavior**

Complete build.

**Current Behavior**

Fails with:
![image](https://user-images.githubusercontent.com/1165340/81148680-fd809300-8f7c-11ea-9583-9cc763464603.png)

**To Reproduce**

Build PCL.

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: VS2019
 - PCL Version: HEAD

**Possible Solution**

add:
`#include <pcl/common/point_tests.h> // for pcl::isFinite`

**Additional context**

Maybe a missed element in #3899. 

However the CI has passed the build of search. Maybe VS2019 is not as forgiving as VS2017?

**Comment by kunaltyagi** [comment]
@larshg looking forwards to the PR
