### ISSUE TITLE
addSphere is not working properly 

### ISSUE THREAD

**Issue by vigneshsara** [PointCloudLibrary/pcl#4068]
i want to mark the picking points form point picking event, so that i had use the addSphere to mark the point, if i had mark the multiple points in cloud its not working properly .
code sample
```
  pcl::PointXYZRGB currentPoint;
 event.getPoint(currentPoint.x,currentPoint.y,currentPoint.z);
 std::string sphere="s0"+boost::lexical_cast<std::string>(countOne);
 pclViewer->addSphere(currentPoint,0.005,255,0,0,sphere,portOne); 
```
output 
![Screenshot from 2020-05-08 19-49-26](https://user-images.githubusercontent.com/31008646/81415563-3cbe0800-9166-11ea-86ab-06f5f166654d.png)
if i have choice the points ,display sphere to nearest picked point

**Comment by kunaltyagi** [comment]
Please open an issue with correct format, and a MCVE so we can help you. Please choose one among the options that appear after clicking on "New issue" 

We don't know what result you're looking for and as such can't help you.
