### ISSUE TITLE
[Request] Delete/Modify tag `pcl-ros-1.0`

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4074]
**Is your feature request related to a problem? Please describe.**

Tag is counter to the other standard tag. It also makes it dangerous to sort the tags and arrive at some meaningful conclusion

**Context**

Auto detecting the latest release can be done by
```
git tag | sort -rV | head -1
```
except now it gives `pcl-ros-1.0`. Without that, it'd give the last release
```bash
$ git tag | sort -rV
pcl-ros-1.0
pcl-1.10.1
pcl-1.10.0
pcl-1.9.1
pcl-1.9.0
pcl-1.8.1rc2
pcl-1.8.1rc1
pcl-1.8.1
pcl-1.8.0rc2
pcl-1.8.0rc1
pcl-1.8.0
pcl-1.7.2rc2.1
...
```

**Describe the solution you'd like**

Removing `ros` altogether or appending it brings it in line with the rest of tags. The tag is old enough that we can expect no-one to rely on it. For those searching the tag, it'd still be found with `ros` as it's the sole tag with it.

**Describe alternatives you've considered**

Simple hack but inelegant
```
git tag | sort -rV | head -2 | tail -1
```

**Comment by jspricke** [comment]
Deleting the tag sound ok to me.

**Comment by SergioRAgostinho** [comment]
We had a similar discussion about this in the past #2644. Back then I was the main opposition to this change. Now, I do not care.

**Comment by kunaltyagi** [comment]
I made the following change on my fork:
```sh
git tag pcl-1.0-ros pcl-ros-1.0         # add new tag
git tag -d pcl-ros-1.0                  # remove old tag
git push origin :refs/tags/pcl-ros-1.0  # remove from remote
git push origin --tags                  # push new tag to remote
```
Result looks much nicer:
<img width="657" alt="Screen Shot 2020-05-10 at 21 59 57" src="https://user-images.githubusercontent.com/2657068/81499903-9e6aa780-9309-11ea-86a6-9e8280a363d9.png">

**Comment by taketwo** [comment]
SGTM

**Comment by kunaltyagi** [comment]
Done
