### ISSUE TITLE
[cmake] CUDA as a First Class Language

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#4077]
When we drop support for Ubuntu 16.04 and 18.04 becomes the baseline, we could switch from CMake 3.5 to 3.10 as minimum required version. Therefore we could switch to modern CUDA integration in CMake, which is available since [CMake 3.8](https://cmake.org/cmake/help/v3.8/release/3.8.html#cuda) (or [CMake 3.9](https://cmake.org/cmake/help/v3.9/release/3.9.html#languages) for MSVC).

So in case no one has a veto against it, I would add a deprecation warning for old versions of CMake. Question; New baseline is 3.9 or 3.10 than? 3.10 seems not be [this interesting](https://cmake.org/cmake/help/v3.10/release/3.10.html) for us - except we could add CppCheck - but not sure if this is relevant.

**Comment by kunaltyagi** [comment]
Let's start a list with all the new feature we can use from the upgrade (3.5 to 3.X, whatever the maximum version is in 18.04 by default)

**Comment by SunBlack** [comment]
Maybe we should start an epic issue for switching CMake version and this ticket just as subticket of it.

**Comment by kunaltyagi** [comment]
We have an Update dependencies project and a CMake update project

**Comment by larshg** [comment]
Added in https://github.com/PointCloudLibrary/pcl/pull/4619
