### ISSUE TITLE
[cmake] Update minimum required version of CMake

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#4078]
Current baseline is Ubuntu 16.04 with CMake 3.5. When the baseline is changed to Ubuntu 18.04, we could switch up to CMake 3.10 (see [here](https://packages.ubuntu.com/search?keywords=cmake&searchon=names&exact=1&suite=all&section=all)).

Things we could change then:
- Drop some legacy CMake code (we have some checks for CMake version in our code)
- Switch to modern CMake integreation #4077 (requires at least [CMake 3.8](https://cmake.org/cmake/help/v3.8/release/3.8.html#cuda) or [3.9 for MSVC](https://cmake.org/cmake/help/v3.9/release/3.9.html#languages))
- Integrate CppCheck (requires [CMake 3.10](https://cmake.org/cmake/help/v3.10/prop_tgt/LANG_CPPCHECK.html#prop_tgt:<LANG>_CPPCHECK))
- Integrate ClangTidy (requires [CMake 3.6](https://cmake.org/cmake/help/v3.6/prop_tgt/LANG_CLANG_TIDY.html#prop_tgt:<LANG>_CLANG_TIDY))

In case you see more interesting changes, you add them here, so we can decide which is the new minimum required CMake version.

Another thing: How we want to deprecate CMake code, as we don't have fixed release cycles? End date or end version?:
- ` message(DEPRECATION "Your CMake version is deprecated and it's supported will be dropped after April 2021.")` => not sure which PCL version will remove this version, but we can be sure we support Ubuntu 16.04 until it's end.
- ` message(DEPRECATION "Your CMake version is deprecated and it's supported will be dropped with PCL 1.14.")` => We can say with which PCL version it's end, but maybe it is before EOL of Ubuntu 16.04.

**Comment by taketwo** [comment]
I don't think we have this codified, but my idea was to always have the previous Ubuntu LTS release as the baseline environment. It is, therefore, time to lift our baseline to 18.04 and, _where needed_, update the minimum third-party dependency versions. I think you listed enough reasons to bump CMake dependency. I also think there is no reason to go for a version that is less than what is available in 18.04.

Regarding deprecation, I don't see a need for that, just update `cmake_minimum_required()` and that's it.

**Comment by larshg** [comment]
This was done in https://github.com/PointCloudLibrary/pcl/pull/4619
