### ISSUE TITLE
[visualization] How to integrate the viewer as a child window into the main window?

### ISSUE THREAD

**Issue by caibf** [PointCloudLibrary/pcl#4087]
Hi, 

I am using viewer of the pcl::visualization::PCLVisualizer class to display point cloud. The CloudViewer and PCLVisualizer classes are available for this purpose. But thery create their own window (via VTK). As I want to integrate the display window into the main window in a complete GUI by passing the main window handle.

I found below two methods maybe do that, but both them doesn't seem to take effect. Why?
`1. viewer->getRenderWindow()->SetParentId(hWnd);`
`2. SetParent((HWND)viewer->getRenderWindow()->GetGenericWindowId(), hwnd);`

**Comment by larshg** [comment]
I know you can do it using QT. There are various examples, just search for them.

I haven' seen any trying to incorporate directly with a WIN32 HWND handle or the like.

**Comment by caibf** [comment]
Hi guys,

After a few days investigation, I have solve this issue and write down the solution here to help others. 

Codes below implements my requirement.
```
pcl::visualization::PCLVisualizer viewer("3D Viewer");
viewer.setSize(640, 480);

pcl::visualization::PCLVisualizer test("Child");
test.setParentId(viewer.getWindowId());
test.getRenderWindow()->SetParentId(viewer.getRenderWindow()->GetGenericWindowId());
test.setSize(400, 200);
```

*Demonstration*
![2020-05-16_125015](https://user-images.githubusercontent.com/4711529/82110874-cf1c6800-9773-11ea-9075-66171751c743.png)

There are a few things you need to do:
- Invoked *setSize()* method should behind *setParentId()* because once set window size then the window rendering inside the implementation of *setSize()*.
- [**Optional (if only you want to create interactor)**] Comment `interactor_->Initialize ();` at line 285 in *createInteractor()* method in the *pcl_visualizer.cpp*. Because of Initialize method would set some flags and render the window and operation that set its parent window is invalid at this time. After modification, you need to recompile the module *pcl_visualization* and replace tis lib and dll.

_It should note that metions above was tested with PCL 1.9.1. I don't know other versions would take effect._

**Comment by WorstCodeWay** [comment]
Hi, @caibf calibf I want to create and show multiple PCLVisualizer directly without any qt widget. Is that possible.

In detail:
1. create a new pcl viewer in a new thread and call spinOnce(10) for example
2. update point cloud from a connection of signal and slot in other thread by calling addPointCloud from pcl viewer
3. another new pcl viewer and repeat 1-3

**Comment by larshg** [comment]
@WorstCodeWay you can use multiple viewports within one window of PCLVisualizer?
See https://pcl.readthedocs.io/projects/tutorials/en/latest/pcl_visualizer.html#pcl-visualizer
