### ISSUE TITLE
Match 3D point cloud to CAD model in real time

### ISSUE THREAD

**Issue by astronaut71** [PointCloudLibrary/pcl#4090]
Hi

I have a point cloud of an object in the scene, obtained with depth ZED camera( in real-time), and a CAD surface model of that object. How can I match the point cloud to the CAD model, to obtain the translation and rotation between the cloud and model in real-time? 

I suppose I could sample the surface and try the Iterative Closest Point (ICP) algorithm to match the resulting sampled point cloud to the CAD point cloud. Would that actually work? I was thinking to modify the registration algorithm and use this example [https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/registration_api/example2.cpp](url) . But what should I change in order to read the ZED Camera points clouds in real-time and match with the CAD model?

And are there better algorithms for this task?
Thanks

**Comment by kunaltyagi** [comment]
> Would that actually work?

With real-time, the performance relies on the quality of result wanted, algorithm and hardware. You control at least 2 of those factors. I'd suggest you try out and then if the result is unacceptable, reach out to us on discord or here with areas that need speed improvements.

> And are there better algorithms for this task?

Doubtless. But better is subjective and depends on the constraints. For real-time, if the shift is small enough, ICP would be a good start. PCL added a new ICP (or is it still a PR, I don't quite remember) which might help you.

Another avenue to look at would be feature-based registration but in my experience, it takes more time for most features and is better as a fallback when ICP fails.

Feel free to open another new issue later when you have an actionable issue. 😄 

PS: such discussions are better held on discord

**Comment by astronaut71** [comment]
sure. Thanks. what do you mean held on discord?

**Comment by kunaltyagi** [comment]
* shift: ICP is fast when the noise is less and the two clouds are similar enough (the Rotation and translation difference isn't large)
* held on discord: https://discord.gg/JFFMAXS

**Comment by astronaut71** [comment]
ok. got it. Well, the application is for construction. So I need to get the orientation of the blocks (for building construction) in the construction field. So, means, I don't know their initial orientation as can be anyone. Another issue can be when the block are on each other, so I have to find the 6D Pose of the top one. It would be in that case working the initial ICP algo, or I assume I need to modify the algo and make it more robust. Any suggestions for that case?

Ok, when having some results will held them on discord.

**Comment by kunaltyagi** [comment]
Start with registration and then move onto ICP for real time.

**Comment by astronaut71** [comment]
Do I need training data for feature based registration?

**Comment by kunaltyagi** [comment]
See you on discord @astronaut71 😄

**Comment by kausthubnarayan** [comment]
> Hi
> 
> I have a point cloud of an object in the scene, obtained with depth ZED camera( in real-time), and a CAD surface model of that object. How can I match the point cloud to the CAD model, to obtain the translation and rotation between the cloud and model in real-time?
> 
> I suppose I could sample the surface and try the Iterative Closest Point (ICP) algorithm to match the resulting sampled point cloud to the CAD point cloud. Would that actually work? I was thinking to modify the registration algorithm and use this example [https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/registration_api/example2.cpp](url) . But what should I change in order to read the ZED Camera points clouds in real-time and match with the CAD model?
> 
> And are there better algorithms for this task?
> Thanks

Were you able to figure this out? I have the same scope and problem to solve.
