### ISSUE TITLE
pcl::ConvexHull crashes

### ISSUE THREAD

**Issue by madduci** [PointCloudLibrary/pcl#410]
Hi

I've successfully compiled PCL from trunk on ArchLinux 64 bit with the following libraries:

Boost 1.55
Eigen 3.2 stable
Flann 1.8.4
VTK 5.10
QHull 2012
OpenNI 1.5.4
CUDA 5.5

When i run the convex hull algorithm, the program quits because of Segmentation fault signal.
On another machine, with Ubuntu 13.10 and all the latest libraries, the software runs perfectly. What could be the cause of the segmentation fault on that specific point?

**Comment by tkircher** [comment]
Ran into this issue building a recent version of PCL (1.11) with a recent version of qhull (8.0). Tried linking PCL with libqhull_r and of course ended up with an undefined reference to qh_qh. There's nothing in the PCL documentation about this. Linking to libqhullstatic.a solved it, as described above. As far as I can tell, this thread is the only explanation of this issue anywhere.

**Comment by jiapei100** [comment]
Yeah... found the same issue... 
Does this belong to a **PCL** issue ? or a **qhull** issue??
Check my issue at [https://github.com/PointCloudLibrary/pcl/issues/4394](https://github.com/PointCloudLibrary/pcl/issues/4394) .

**Comment by kunaltyagi** [comment]
Please keep conversation in the thread that you started.

@tkircher (or anyone else) Please feel free to create a PR to add this in the documentation

**Comment by tkircher** [comment]
This might be the best place to leave it. At the moment, getting a working build of libpcl with dependencies that aren't literally years and years out of date takes an experienced developer, and that wouldn't really change even with good documentation. But people who run into these same issues will find these threads and either give up or puzzle it out.

**Comment by kunaltyagi** [comment]
> dependencies that aren't literally years and years out of date

IMO, that's a false statement based on following observations:
1. PCL works with all the latest releases of its dependencies (except VTK-9) on ubuntu (sadly, we can't track every single distro). Even for VTK 9, there's a patch in progress.
2. PCL CI shows how absurdly simple setting up PCL for a "normal build" is.

If you're interested in making PCL work with the unreleased (on ubuntu-latest) version of libraries or abnormal build setups, please feel free to contribute too. For open source projects, it is vital that the community contributes actively, else the project goes out of sync with it
