### ISSUE TITLE
[Registration] `PPFRegistration<PointNormal, PointNormal>` estimates incorrect (NaN) TF for large translations

### ISSUE THREAD

**Issue by mitmy** [PointCloudLibrary/pcl#4102]
**Describe the bug**

When applying a big translation on point cloud (either cloud or cloud_scene), estimated translation is nan.

**To Reproduce**
Apply a translation to model cloud:
```
Eigen::Translation3f translation(1.0, 10.0, 100.0);
Eigen::Affine3f transform(translation);
pcl::transformPointCloud(*cloud, *cloud, transform);
```
estimated translation: [nan, nan, nan]

On the other hand, if apply a small translation:
```
Eigen::Translation3f translation(1.0, 10.0, 10.0);
Eigen::Affine3f transform(translation);
pcl::transformPointCloud(*cloud, *cloud, transform);
```
estimation translation is correct.

**Your Environment (please complete the following information):**

 - OS: Ubuntu 16.04
 - Compiler: GCC 6.0
 - PCL Version 1.9

**Comment by kunaltyagi** [comment]
* How are you estimating the transform?
* Is the issue present on PCL master (1.11)?

Please give a MVCE that can be used to pinpoint the issue

**Comment by mitmy** [comment]
-  I simply run ```apps/src/ppf_object_recognition.cpp``` adding following lines after line 62:

Eigen::Translation3f translation(0.0, 10.0, 100.0);
Eigen::Affine3f trans(translation);
pcl::transformPointCloud(*cloud_scene, *cloud_scene, trans);

The point cloud data I use to test could be found here 
```
https://github.com/alfonsoros88/PPFMap/blob/master/clouds/model_chair.pcd
https://github.com/alfonsoros88/PPFMap/blob/master/clouds/scene_chair.pcd
```

- v1.11 on master gives the same issue

**Comment by kunaltyagi** [comment]
Thanks for the details. It helped figure out the error.

Needs testing to figure out the source of error.

**Comment by mitmy** [comment]
Bug is from normal estimation. Simple test: add a random translation to point cloud, NormalEstimation gives completely different results. Problem solved after replacing the normal estimation with an implementation from Open3D.
