### ISSUE TITLE
[stale-bot] Bad config results in no response

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4103]
I noticed a silence from stale-bot as well as an issue which should have been closed by stale-bot.

I noticed that we configure 2 `onlyLabels`: `needs: author reply` and `needs: more work`. This sadly means both are needed for stale-bot to mark it as stale. [bot code](https://github.com/probot/stale/blob/master/lib/stale.js#L78)

We can either
1. switch stale-bot periodically from PR to issues and vice-versa.. (I'm *meh* on this)
2. choose a common label for stale-bot to search with:
  * `needs: more info/work` (or slog, drudgery, toil, etc.)
  * `needs: OP attention`, `needs: author's attention`
3. Add a separate label for stale-bot:
  * `needs: stale-bot` 🤣
  * `in-progress` separate from either

Some alternatives courtesy of thesaurus to help in bike-shedding the name:
* Fun: retaliation, reciprocation, reaction, clapback, rejoinder, retort, riposte, sally, comeback
* Neutral: feedback, commentary, reply, response

**Comment by kunaltyagi** [comment]
@aPonza mentioned we can also invert the labels to exclude all except the 2 in question.

**Comment by aPonza** [comment]
You only really need to exclude issues where maintainers haven't taken action, i.e. four of the needs: feedback, code review, testing, and pr merge. Maybe status:triage. It would work iff maintainers themselves remember to keep the labels updated (authors can always bump the issues, I guess). The backlog would be marked stale by stalebot, giving a notification to the author (right?), so the author could bump at that time, if interested.
