### ISSUE TITLE
flann errors occur when pcl 1.10.0 is used

### ISSUE THREAD

**Issue by zengletian1491** [PointCloudLibrary/pcl#4110]
when pcl 1.10.0 is used on windows10-64bit system, errors about flann 1.9.1 occur as follows:

  | Code | Interpretations | Files | Line
-- | -- | -- | -- | --
Error | C2065 | “flann_algorithm_t”: undeclared identifier | d: \pcl\flann\include\flann\util\params.h | 44
Error | C2913 | Explicit specialization；“flann::anyimpl::choose_policy” is not class template specialization | d:\pcl\flann\include\flann\util\params.h | 47
Error | C2913 | Explicit specialization；“flann::anyimpl::choose_policy” is not class template specialization | d:\pcl\flann\include\flann\util\params.h | 46
Error | C2913 | Explicit specialization；“flann::anyimpl::choose_policy” is not class template specialization | d:\pcl\flann\include\flann\util\params.h | 45
Error | C2913 | Explicit specialization；“flann::anyimpl::choose_policy” is not class template specialization | d:\pcl\flann\include\flann\util\params.h | 44
Error | C2923 | “flann::anyimpl::choose_policy”: “flann_algorithm_t” is not a valid template type variable for parameter “T” | d:\pcl\flann\include\flann\util\params.h | 44

Could you give me some suggestions? Thanks.

**Comment by kunaltyagi** [comment]
How did you install PCL? Please have a look at `compile_error` issue template in order to provide the correct information.

Note: Doesn't seem like an issue for PCL. The `params` header is a FLANN header, not a PCL one.

**Comment by zengletian1491** [comment]
I installed PCL with source code. The flann 1.9.1, which should be installed before PCL,  is one of the dependencies of PCL.

**Comment by kunaltyagi** [comment]
The issue is with your setup, not with PCL. Please use StackOverflow or Discord to discuss further.

PCL compiles with FLANN 1.9.1 as per our CI.
