### ISSUE TITLE
[CI] Monitor disk space in using `df -h`

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4120]
> > move the build directory
> 
> `BUILD_REPOSITORY_LOCALPATH` is indeed `D:`. Thanks for the suggestion. Will look into it over the weekend.

At least on GitHub Actions the actual available size depend on the image version, so tipically I monitor the actual available space  via a step  that executes on bash `df -h` to monitor the actual available space on the system, see: 
* https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/blob/v0.3.0/.github/workflows/ci.yml#L18
* https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/runs/652161005#step:3:4

_Originally posted by @traversaro in https://github.com/PointCloudLibrary/pcl/issues/3387#issuecomment-630828210_

**Comment by mvieth** [comment]
@kunaltyagi What about this issue? Since this was mainly to debug why the CI jobs ran out of memory (which does not happen any more), I currently don't really see a reason why this should be added ...
