### ISSUE TITLE
[Windows] Does All-In-One Installer provide dependencies as static or dynamic libraries?

### ISSUE THREAD

**Issue by vanloctc** [PointCloudLibrary/pcl#4132]
Hi,
Seems I can build PCL Static Library from the dependencies (Boost,qhull,flann,... except VTK) of PCL ALL IN ONE, but I dont know I can get the error any-time. I have search about What kind of library *.lib in PCL ALL IN ONE.
Who can give me about What kind of the library ( Boost,qhull,.. ) is a static library or dynamic library.

**Comment by larshg** [comment]
If there is a corresponding dll file in the bin(s) folder its dynamic. If there only is a .lib file its static.
I think most dependencies in All-In-One are static linked, but for >1.9.1 VTK is dynamically build due to runtime errors happening with static VTK.

See #1601
