### ISSUE TITLE
[compile error] Reference to unresolved external symbol

### ISSUE THREAD

**Issue by OgreTransporter** [PointCloudLibrary/pcl#4136]
Hello!
I have a problem compiling PCL and I cannot find the error.

**Describe the error**

```
25>linemod_detection.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowNonDense(int,int)" (?convolveOneRowNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
25>linemod_detection.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColNonDense(int,int)" (?convolveOneColNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
25>D:\PCL\build\bin\pcl_linemod_detection.exe : fatal error LNK1120: 2 nicht aufgelöste Externe
```

```
28>match_linemod_template.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowNonDense(int,int)" (?convolveOneRowNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
28>match_linemod_template.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColNonDense(int,int)" (?convolveOneColNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
28>D:\PCL\build\bin\pcl_match_linemod_template.exe : fatal error LNK1120: 2 nicht aufgelöste Externe
```

```
54>train_linemod_template.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowDense(int,int)" (?convolveOneRowDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneRowNonDense(int,int)" (?convolveOneRowNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
54>train_linemod_template.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColDense(int,int)" (?convolveOneColDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)" in Funktion ""private: struct pcl::RGB __cdecl pcl::filters::Convolution<struct pcl::RGB,struct pcl::RGB>::convolveOneColNonDense(int,int)" (?convolveOneColNonDense@?$Convolution@URGB@pcl@@U12@@filters@pcl@@AEAA?AURGB@3@HH@Z)".
54>D:\PCL\build\bin\pcl_train_linemod_template.exe : fatal error LNK1120: 2 nicht aufgelöste Externe
```

**To Reproduce**

`cmake -G "Visual Studio 15" -A x64 -D CMAKE_INSTALL_PREFIX:PATH=D:\PCL\install -D CMAKE_DEBUG_POSTFIX:STRING=d -D WITH_DOCS:BOOL=OFF -D BUILD_CUDA:BOOL=ON -D BUILD_cuda_io:BOOL=ON -D EIGEN_INCLUDE_DIR:PATH=D:\PCL\deps\Eigen\install\include\eigen3 -D FLANN_INCLUDE_DIR:PATH=D:\PCL\deps\FLANN\install\include -D FLANN_LIBRARY:FILEPATH=D:\PCL\deps\FLANN\install\lib\flann_s.lib -D FLANN_LIBRARY_DEBUG:FILEPATH=D:\PCL\deps\FLANN\install\lib\flann_sd.lib -D ZLIB_INCLUDE_DIR:PATH=D:\PCL\deps\zlib\install\include -D ZLIB_LIBRARY_DEBUG:FILEPATH=D:\PCL\deps\zlib\install\lib\zlibstaticd.lib -D ZLIB_LIBRARY_RELEASE:FILEPATH=D:\PCL\deps\zlib\install\lib\zlibstatic.lib -D GLEW_DIR:PATH=D:\PCL\deps\GLEW\install -D GLEW_INCLUDE_DIR:PATH=D:\PCL\deps\GLEW\install\include -D GLEW_SHARED_LIBRARY_DEBUG:FILEPATH=D:\PCL\deps\GLEW\install\lib\glewd.lib -D GLEW_SHARED_LIBRARY_RELEASE:FILEPATH=D:\PCL\deps\GLEW\install\lib\glew.lib -D PNG_PNG_INCLUDE_DIR:PATH=D:\PCL\deps\libpng\install\include -D PNG_LIBRARY_DEBUG:FILEPATH=D:\PCL\deps\libpng\install\lib\libpng16_staticd.lib -D PNG_LIBRARY_RELEASE:FILEPATH=D:\PCL\deps\libpng\install\lib\libpng16_static.lib -D Boost_INCLUDE_DIR:PATH=D:\PCL\deps\boost\install -D LZ4_LIBRARIES:FILEPATH=debug;D:\PCL\deps\lz4\install\lib\Debug\liblz4_static.lib;optimized;D:\PCL\deps\lz4\install\lib\Release\liblz4_static.lib -D LZ4_INCLUDE_DIR:PATH=D:\PCL\deps\lz4\install\include -D QHULL_LIBRARY:FILEPATH=D:\PCL\deps\Qhull\install\lib\qhullstaticd.lib -D QHULL_LIBRARY_DEBUG:FILEPATH=D:\PCL\deps\Qhull\install\lib\qhullstatic.lib -D LIBUSB_1_INCLUDE_DIR:PATH=D:\PCL\deps\libusb\install\include -D LIBUSB_1_LIBRARY:FILEPATH=debug;D:\PCL\deps\libusb\install\lib\libusbs-1.0d.lib;optimized;D:\PCL\deps\libusb\install\lib\libusbs-1.0.lib -D Qt5_DIR:PATH=D:\SDKs\Qt5\5.14.1\msvc2017_64\lib\cmake\Qt5 -D "CUDA_SDK_ROOT_DIR:PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" D:\PCL\src`

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: Visual Studio 2017
 - PCL Version: c80e408aaf9ee1b0cdc711555019454275189078
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - CUDA: Yes
 - List and Version of dependencies used
 -- boost (1.74, 77c62ecf759f489a8c83d958b54863475b66da35)
 -- Eigen (3.3.90, 4e7046063babd95e100ab202d52ca5776997c80c)
 -- FLANN (1.9.1, 1d04523268c388dabf1c0865d69e1b638c8c7d9d)
 -- GLEW (2.2.0, c4c1fd4fece3c8ebb3b69985fbb1656052e552bd)
 -- libpng (1.6.36, 3676fd324a8920930f1ee66248e3119d30c7c9a2)
 -- libusb (1.0.23, 26611eaa494ed9e077b5b0e1f999f5ae377de958)
 -- lz4 (1.9.2, 3d67671559be723b0912bbee2fcd2eb14783a721)
 -- Qhull (7.3.2, c59de95be3706546de8b16e1635bc01a555c8aa3)
 -- zlib (1.2.11, cacf7f1d4e3d44d871b605da3b647f07d718623f)

**Comment by kunaltyagi** [comment]
I think that's a known issue. #4082, and we're having trouble debugging it. Closing in favor of the original

**Comment by kunaltyagi** [comment]
If you can help in debugging, that'd be great, else you can unapply the 2 patches that caused the issue. (But if you use those headers, you'd still get another issue). This issue is WIndows only, while the other was for all platforms, and therefore has been left in
