### ISSUE TITLE
Error reading PCD file with pcl1.9.0 and VS2017

### ISSUE THREAD

**Issue by qq625924821** [PointCloudLibrary/pcl#4148]
**Describe the bug**

Debug Assertion Failed!
File:d:\soft\vs\setup\vc\too;s\msvc\14.16.27023\include\xmemory0
Line:122

Expression: invalid argument

in function pcl::LoadPCDFile‘s function read, when operation on return(res), an error occurred.

**Comment by SergioRAgostinho** [comment]
Please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by larshg** [comment]
And the pcd file in question.

**Comment by mvieth** [comment]
Closing this due to no feedback. If you still have this problem, feel free to comment/reopen this issue/open a new issue.
