### ISSUE TITLE
pointclouds.org serves raw PHP instead of processing it

### ISSUE THREAD

**Issue by I3ck** [PointCloudLibrary/pcl#4157]
I noticed one page serving the raw PHP code instead of processed version. It's likely that more/all .php urls are affected.  
Sensitive data might be leaked due to that.  
[Example](http://pointclouds.org/documentation/tutorials/pcd_file_format.php)

**Comment by tineras** [comment]
Is there another way to access the documentation in the mean time?

**Comment by SergioRAgostinho** [comment]
https://pcl-tutorials.readthedocs.io/en/latest/project_inliers.html

**Comment by I3ck** [comment]
Just Fyi:
You might want to 301 redirect to the new pages so you don't lose page ranks.  
E.g. https://www.google.com/search?q=pcd+file+format will yield the php link

**Comment by kunaltyagi** [comment]
Issue is not solved: https://github.com/PointCloudLibrary/documentation/search?q=php&unscoped_q=php
