### ISSUE TITLE
[Help] How to increase resolution Convex Hull

### ISSUE THREAD

**Issue by aled96** [PointCloudLibrary/pcl#4171]
Hi,

I have a plane which is with an irregular shape and I would like to obtain the convex hull. The problem is that the result has only 20-25 points, so I cannot use it to represent the plane.

This is the original plane:
![11111](https://user-images.githubusercontent.com/37381508/84137466-07e6ee80-aa4d-11ea-9587-62f996be40e7.png)

This instead is the result with the ConvexHull:
![222222](https://user-images.githubusercontent.com/37381508/84137490-10d7c000-aa4d-11ea-9185-2390e9bf913b.png)

How can I increase the resolution ? Is there a mechanism similar to the setAlpha for the Concave Hull?

The code I used is simply:
 _pcl::ConvexHull<pcl::PointXYZ> chull;
 chull.setInputCloud (planes[i]);
 chull.reconstruct (*cloud_hull);_

Thank you !

**Comment by kunaltyagi** [comment]
Increasing the resolution of a convex hull (aka number of vertices) doesn't make sense. The convex hull algorithm will only provide the vertices, but you can interpolate for more points yourself along the edges connecting the vertices (`vertex_a*factor + (1-factor)*vertex_b`). You can also choose to add lines in your visualization software if that's your goal.

**Comment by kunaltyagi** [comment]
Also, please use discord or StackExchange for questions related to the usage of the library
