### ISSUE TITLE
[compile error] build WITH_OPENNI failed

### ISSUE THREAD

**Issue by viisautta** [PointCloudLibrary/pcl#4175]
**Describe the error**

/usr/include/ni/XnPlatform.h:76:6: error: #error OpenNI Platform Abstraction Layer - Unsupported Platform!
76 | #error OpenNI Platform Abstraction Layer - Unsupported Platform!
| ^~~~~
In file included from /home/daqian/Public/Devel/pcl-pcl-1.11.0/io/include/pcl/io/openni_camera/openni.h:47,
from /home/daqian/Public/Devel/pcl-pcl-1.11.0/io/include/pcl/io/openni_camera/openni_image.h:44,
from /home/daqian/Public/Devel/pcl-pcl-1.11.0/io/include/pcl/io/pcd_grabber.h:50,
from /home/daqian/Public/Devel/pcl-pcl-1.11.0/io/src/pcd_grabber.cpp:39:
/usr/include/ni/XnOS.h:54:4: error: #error OpenNI OS Abstraction Layer - Unsupported Platform!
54 | #error OpenNI OS Abstraction Layer - Unsupported Platform!
| ^~~~~

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. Custom OS, custom PCL configs or custom build systems make the issue difficult to reproduce.
* Best reproducability: A docker image + code snippets provided here
* Good reproducability: Common Linux OS + default PCL config + code snippets provided here
* Poor reproducability: code snippets

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights
* debugging information:
  * the output of cmake using `cmake --debug`
  * the failing build command(s) using `VERBOSE=1 make`, `ninja -v` or similar
  * steps taken to narrow down the problem

**Your Environment (please complete the following information):**

 - OS: [fedora 32]
 - Compiler: [GCC 10.0.1]
 - PCL Version [1.11]
 - PCL Type: [Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes/No
 - List and Version of dependencies used
 - Compilation flags are used

If compiling against PCL:
 - Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
  * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
  * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**
$ dnf list installed | grep openni
openni.x86_64                                      1.5.7.10-18.fc32                    @fedora  
openni-devel.x86_64                                1.5.7.10-18.fc32                    @fedora

**Comment by larshg** [comment]
This seems to be an error in OpenNI implementation failing to recognize fedora as a linux variant. Not a bug in PCL.

Some suggest to update to OpenNI2. https://github.com/stevenlovegrove/Pangolin/issues/112

Alternatively see http://3dcv.science/engineering/2017/06/26/how-to-install-OpenNI-for-Kinect-V1.html

**Comment by viisautta** [comment]
At present, realsense D435i is applied.
With OpenNI2, cmake has the output as below:
        not building:
        |_ 3d_rec_framework: OpenNI was not found or was disabled by the user.
        |_ in_hand_scanner: OpenNI was not found or was disabled by the user.

**Comment by larshg** [comment]
So those two require OpenNI, so if you need to use those, you might have two options:

1) See what is required to use OpenNI2 instead of OpenNI and make a PR (so one can use either one)
2) Figure out how to make OpenNI run on your OS

I'm not that familiar with OpenNI/2 so I can't help much from here.

**Comment by viisautta** [comment]
thanks for your hints.
