### ISSUE TITLE
fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory

### ISSUE THREAD

**Issue by tiexuedanxin** [PointCloudLibrary/pcl#4176]
I have installed the pcl1.8 successfully,but when I test with a example, the following error occur.Is there someone could help me,thank you very much.

fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory

**Comment by kunaltyagi** [comment]
1.8 was released back in 2017. Please try with PCL 1.10 or PCL 1.11

**Comment by Pederzent** [comment]
I have installed PCL on two PC's running Windows 10. Both x64 and x86 fails to detect VTK when compiling PCL so pcl_visualizer.h is never installed. Run .\vcpkg install pcl and .\vcpkg install pcl:x64-windows. Installed that Windows tool (msm???) as well, sorry I don't remember what it is called.

**Comment by larshg** [comment]
Vcpkg has currently visualization disabled due to pcl doesn't support vtk 9 yet.
You can compile pcl from source, including the pr which is in progress of integrating vtk 9.

**Comment by Pederzent** [comment]
Hi,

Great response, thank you very much.
I will rather wait for vtk-support and look forward to the update.

Kind Regards,
Terje

Sent from ProtonMail mobile

-------- Original Message --------
