### ISSUE TITLE
[custom] A warning for PCLVisualizer::setUseVbos occurs in the case of template_alignment

### ISSUE THREAD

**Issue by viisautta** [PointCloudLibrary/pcl#4200]
$ pcl_viewer data/person.pcd output.pcd 
The viewer window provides interactive commands; for help, press 'h' or 'H' from within the window.
> Loading data/person.pcd [PCLVisualizer::setUseVbos] Has no effect when OpenGL version is ≥ 2
[done, 781.395 ms : 307200 points]
Available dimensions: x y z
> Loading output.pcd [done, 1.19922 ms : 1419 points]
Available dimensions: x y z

It seems to prefer LEGACY to GLVND for OpenGL_GL_PREFERENCE on installation of pcl-1.11.0. Is that so?

**Comment by viisautta** [comment]
Who can help me confirm this question?

**Comment by Leaveszy** [comment]
How did you solve this problem? I have the same problem with you
