### ISSUE TITLE
[build error] failure in building some modules related in eigen and cuda

### ISSUE THREAD

**Issue by yes89929** [PointCloudLibrary/pcl#4201]
Same problem in #3742 

![image](https://user-images.githubusercontent.com/33365390/84868938-5a14b900-b0b8-11ea-9c7f-f324c675ecfc.png)

```
Description: more than one instance of overloaded function "__hadd" matches the argument list:
Project: pcl_cuda_features
File: D:\vcpkg\vcpkg\vcpkg-export-20200617-151750\installed\x64-windows\include\eigen3\Eigen\src\Core\arch\CUDA\Half.h	212
```

**Your Environment (please complete the following information):**

 - OS: Windows 10 Pro
 - Compiler: vs2019
 - PCL Version 1.11.0
 - Dependencies
   - boost 1.73 (installed by vcpkg)
   - flann 1.9.1 (installed by vcpkg)
   - eigen 3.3.7 (installed by vcpkg)
   - qhull 7.3.2 (installed by vcpkg)
   - winpcap 4.1.3 (installed by vcpkg)
   - vtk 8.2 (installed by vcpkg)
   - cuda 10.2

**Comment by kunaltyagi** [comment]
Closing because duplicate

**Comment by WorstCodeWay** [comment]
> Closing because duplicate

Hi, kunaltyagi. I wonder which one it is duplicated with?  Has it been solved? I meet this error too.

**Comment by larshg** [comment]
@WorstCodeWay you need to use head of Eigen. Ie. ./vcpkg install Eigen --head.
That should solve it. Its a bug in Eigen.

**Comment by WorstCodeWay** [comment]
> @WorstCodeWay you need to use head of Eigen. Ie. ./vcpkg install Eigen --head.
> That should solve it. Its a bug in Eigen.
Thank you, larshg. I'll try it. BTW, I install eigen from source with cmake and I rollback Eigen version to 3.3.7, this helps some other errors, but nothing helps these `__hadd` errors.
