### ISSUE TITLE
[compile error] An error occurred after include “pcd_io.h”

### ISSUE THREAD

**Issue by Lanch97** [PointCloudLibrary/pcl#4210]
Use the VS 2019 IDE;
An error occurred after include “pcd_io.h”
The compilation prompts many files "Cannot overload functions with external 'C' links".
My project is a direct reference to PCL source code.

error msg:
Error C2733 "SetSecurityDescriptorDacl" : can't overloaded with external function of the "C" link ExDll1 C: \ Program Files \ Windows (x86) Kits 10 \ \ Include \ 10.0.18362.0 \ um \ securitybaseapi h 1390

Error C2116 "boost: : interprocess: : winapi: : CreateSemaphoreA" : the function parameter list does not match between different statement ExDll1 C: \ Program Files \ Windows (x86) Kits 10 \ \ Include \ 10.0.18362.0 \ um \ winbase h 3098

Error C2733 "CreateSemaphoreA" : Cannot override function ExDll1 C:\Program Files (x86)\ 10\Include\10.0.18362.0\um\ Winbase.h 3098 with external "C" link

Error C2116 "boost: : interprocess: : winapi: : CreateFileMappingA" : the function parameter list does not match between different statement ExDll1 C: \ Program Files \ Windows (x86) Kits 10 \ \ Include \ 10.0.18362.0 \ um \ winbase h 3208

There are about 20 files that prompt the same error

**Comment by kunaltyagi** [comment]
Please provide a minimum verifiable and complete example to reproduce the error.

**Comment by Lanch97** [comment]
> 请提供一个最少的可验证且完整的示例以重现该错误。
No code was written, only after importing "PCD_IO.h", the compilation failed. I suspected that it was a system environment problem, but compared with the projects generated by Cmake, I did not find any configuration differences.
I used cmake to build the project to compile and everything worked fine;

**Comment by kunaltyagi** [comment]
> I used cmake to build the project to compile and everything worked fine;

That implies some configuration difference. PCL only supports CMake or vcpkg based builds due to lack of maintainers with windows.
