### ISSUE TITLE
[apps] Clean a loop with for-range and don't use `points` in `result`.

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4214]
clean this loop with for-range and don't use `points` in `result`.

_Originally posted by @SergioRAgostinho in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDM1Njg2NzQ1/pull_request_reviews/more_threads_

apps/src/openni_tracking.cpp L480

**Comment by rabaho** [comment]
Which loop are we talking about here? It looks like line 480 isn't correct.

**Comment by mvieth** [comment]
Probably this one:
https://github.com/PointCloudLibrary/pcl/blob/master/apps/src/openni_tracking.cpp#L471
But the issue seems to be resolved already?

**Comment by rabaho** [comment]
Maybe https://github.com/PointCloudLibrary/pcl/blob/master/apps/src/openni_tracking.cpp#L438?

**Comment by kunaltyagi** [comment]
Might be. apps took a heavy beating due to the re-formatting, (which usually increases lines), so I think it's L438
