### ISSUE TITLE
[BUG] Point std:vector in (pcl::PointCloud) increases randomily the allocated size

### ISSUE THREAD

**Issue by gameanimation3d** [PointCloudLibrary/pcl#4215]
**Describe the bug**

The loaded point cloud (pcl::PointCloud) std::vector "points" get randomily increased in their allocated size on normal estimation.
This happens when the compute() function of the pcl::NormalEstimation Class gets called. 
In detail, in feature.hpp is the point cloud size still correct and std::vector has the correct size
![1](https://user-images.githubusercontent.com/44543590/85406918-caad5100-b562-11ea-970b-49c59d25a763.JPG)

However if "PCLBase<PointInT>::initCompute()" is called the point cloud changes. 
In pcl_base.hpp the std::vector points size has exploded. 
![2](https://user-images.githubusercontent.com/44543590/85407017-ec0e3d00-b562-11ea-83e5-ab68072bff26.jpg)

Since the randomly allocated points in the std::vector are null the normal estimation estimation fails. 

I am using mainly the code snippet written in the tutorial to call the normal estimation process. (https://pcl.readthedocs.io/projects/tutorials/en/latest/normal_estimation.html#normal-estimation)

However i am constructing the pcl::PointCloud<pcl::PointXYZ>::Ptr by using the resize() function to allocate the correct amount of point in the vector. Further i am using a for loop to add the individual points to the pcl:PointCloud Class from an different own point cloud class. 

 ```
// Generate PCL point cloud data remap data
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    cloud->resize(pts->size());

    // iterate through AliceVision Points and add point into PCL pointcloud data format
    for(int i = 0; i < pts->size(); i++)
    {
        Point3d& point3D = (*pts)[i];

        cloud->points[i].x = point3D.x;
        cloud->points[i].y = point3D.y;
        cloud->points[i].z = point3D.z;
    }

    ALICEVISION_LOG_TRACE("PCL Pointcloud has been created with point of AliceVision Data");

    // Create the normal estimation class, and pass the input dataset to it
    pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normalEstimationHelper;
    normalEstimationHelper.setInputCloud(cloud);

    // calc kd tree
    pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>());
    normalEstimationHelper.setSearchMethod(tree);

    ALICEVISION_LOG_TRACE("PCL KD-Tree has been calculated");

    // Output datasets
    pcl::PointCloud<pcl::Normal>::Ptr cloud_normals(new pcl::PointCloud<pcl::Normal>);

    // Use all neighbors in a sphere of radius 3cm
    normalEstimationHelper.setRadiusSearch(searchRadius);

    // Calc normal
    normalEstimationHelper.compute(*cloud_normals);
````

**Your Environment (please complete the following information):**

OS: Windows 10 64bit 
Visual Studio 2017 (v141)
PCL Version (via VCPKG): 1.9.1

**Comment by kunaltyagi** [comment]
Thanks for the trace. Could you provide this in form of a MCVE where we can see the values being printed out (expected and actual) to confirm that the bug is fixed?

**Comment by gameanimation3d** [comment]
I tried to trace the bug down using the MCVE Techniques. 
However if i created a complete new C++ application with just the PCL calls and same point cloud as input i wasn't able to reproduce the bug. 
By "reinstalling" PCL and linking it to desired C++ solution again the bug was gone.
