### ISSUE TITLE
build error with modules about CUDA on TX2

### ISSUE THREAD

**Issue by yes89929** [PointCloudLibrary/pcl#4223]
**Describe the bug**

Continues issue #4172

After upgrading eigen 3.3.4 ->3.3.7,
building pcl 1.11.1 is succeeded, but pcl 1.9.1 is failed.

```

[  6%] Building NVCC (Device) object cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o
/home/tx2/Downloads/pcl-pcl-1.9.1/cuda/common/include/pcl/cuda/point_cloud.h(369): error: namespace "thrust" has no member "device_malloc"

/home/tx2/Downloads/pcl-pcl-1.9.1/cuda/common/include/pcl/cuda/point_cloud.h(369): error: type name is not allowed

2 errors detected in the compilation of "/tmp/tmpxft_00007675_00000000-4_connected_components.cpp4.ii".
CMake Error at pcl_cuda_segmentation_generated_connected_components.cu.o.RelWithDebInfo.cmake:279 (message):
  Error generating file
  /home/tx2/Downloads/pcl-pcl-1.9.1/build/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.o


cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/build.make:63: recipe for target 'cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o' failed
make[2]: *** [cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.o] Error 1
CMakeFiles/Makefile2:1321: recipe for target 'cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/all' failed
make[1]: *** [cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/tx2/Downloads/pcl-pcl-1.9.1/cuda/common/include/pcl/cuda/point_cloud.h(369): error: namespace "thrust" has no member "device_malloc"

/home/tx2/Downloads/pcl-pcl-1.9.1/cuda/common/include/pcl/cuda/point_cloud.h(369): error: type name is not allowed

2 errors detected in the compilation of "/tmp/tmpxft_00007615_00000000-4_normal_3d.cpp4.ii".
CMake Error at pcl_cuda_features_generated_normal_3d.cu.o.RelWithDebInfo.cmake:279 (message):
  Error generating file
  /home/tx2/Downloads/pcl-pcl-1.9.1/build/cuda/features/CMakeFiles/pcl_cuda_features.dir/src/./pcl_cuda_features_generated_normal_3d.cu.o


cuda/features/CMakeFiles/pcl_cuda_features.dir/build.make:63: recipe for target 'cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o' failed
make[2]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o] Error 1
CMakeFiles/Makefile2:1266: recipe for target 'cuda/features/CMakeFiles/pcl_cuda_features.dir/all' failed
make[1]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2


```
**To Reproduce**
`sudo apt install libboost-all-dev`
`sudo apt install libqhull-dev`
`sudo apt install libpacp-dev`
`sudo apt install libvtk-dev`
`sudo apt install libflann-dev`
`build and install eigen3.3.7 src`
`download pcl 1.9.1`
`configuration and generation using cmake-gui`
`make -j1`

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04 arm64 (jetson TX2, jetpack 4.)
 - Compiler: GCC 7.5
 - PCL Version: 1.9.1
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes
 - List and Version of dependencies used
 -- boost 1.65.1
 -- CUDA 10.2(jetpack 4.)
 -- vtk 6.3.0
 -- eigen 3.3.7
 -- qhull 2015.2-4
 -- flann 1.9.1
 - Compilation flags are used
 -- WITH_CUDA
 -- WITH_PCAP
 -- WITH_GPU

**Comment by larshg** [comment]
PCL 1.9.1 probably don't support CUDA 10.2. 

Either figure out what changes has been made between 1.9.1->1.11.1 or possible downgrade CUDA runtime.

I haven't compiled PCL 1.9.1 for a long time, so I'm 100% sure which version might work.

**Comment by kunaltyagi** [comment]
Closing as wont-fix. PCL can't backport fixes due to lack of time.

Please continue the discussion if needed.

**Comment by OriKovacsiKatz** [comment]
namespace "thrust" has no member "device_malloc" on pcl 1.9.1 build from source with cuda 10.2 cudnn 7.6.5.32-1+cuda10.2 ubuntu 18.04 in container from nvidia 

hi  libcudnn7                                                        7.6.5.32-1+cuda10.2                 amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                                    7.6.5.32-1+cuda10.2                 amd64        cuDNN development libraries and headers

notice the additional #include on pcl/trust.h added one headeer from 1.9.1 to 1.10.0
I just added the folowing to the header
```
// added by Ori Kovacsi Katz 08_01_2025
#include <thrust/device_malloc.h>
```
(3dsmoothnet) root@n306:/opt/devel/pcl_build# nano /home/gal.yona/prjPCL/3DSmoothNet/pcl/cuda/common/include/pcl/cuda/thrust.h
(3dsmoothnet) root@n306:/opt/devel/pcl_build# 

  GNU nano 2.9.3                                            /home/gal.yona/prjPCL/3DSmoothNet/pcl/cuda/common/include/pcl/cuda/thrust.h                                             Modified  
```

 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *
 * $Id: point_cloud.h 4927 2012-03-07 03:35:53Z rusu $
 *
 */

#ifndef PCL_CUDA_COMMON_THRUST_H_
#define PCL_CUDA_COMMON_THRUST_H_

#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
**_// added by Ori Kovacsi Katz 08_01_2025
#include <thrust/device_malloc.h>_**
#include <thrust/copy.h>
#include <thrust/device_ptr.h>
#include <thrust/sequence.h>

#endif    // PCL_CUDA_COMMON_THRUST_H_

```

ISSUE WITH "device_malloc" ALLOCATE DISAPPEARS ,

just add this line to the trust header and all builds.

**one more thing use single process make build process , build has problems if using multiprocessor build (like "make -j16")   
it is not synchronized to wait for object completion before starting dependent libraries build and build process failed .**
