### ISSUE TITLE
[pcl_surface] new vtk requirement Version 1.11.0 *at least in all-in-one*

### ISSUE THREAD

**Issue by WargodHernandez** [PointCloudLibrary/pcl#4237]
pcl_surface has an unlisted dependency on VTKFILTERSMODELING, VTKFILTERSCORE-8.2, VTKCOMMONEXECUTIONMODEL-8.2, VTKCOMMONDATAMODEL-8.2 AND VTKCOMMONCORE-8.2 when installed from [PCL-1.11.0-AllInOne-msvc2019-win64.exe](https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.11.0/PCL-1.11.0-AllInOne-msvc2019-win64.exe)

Dependency-Walker shown on pcl_surface.dll

![image](https://user-images.githubusercontent.com/7495752/86289289-4da45c00-bba0-11ea-8564-10ad938f479f.png)

compared to pcl_surface_release.dl froml pcl-1.9.1 which does not have this dependency

![image](https://user-images.githubusercontent.com/7495752/86289407-7cbacd80-bba0-11ea-92e1-3be6a48815eb.png)

**Expected behavior**

I expect no VTK dependency as it is not listed in pcl_surface-1.11.pc 
![image](https://user-images.githubusercontent.com/7495752/86289567-ca373a80-bba0-11ea-9960-50323c1e4ff8.png)
also based on PCLConfig.cmake there is no dep on VTK
```CMake
set(pcl_surface_int_dep common search kdtree octree )

#list each component external dependencies (ext means mandatory and opt means optional)
set(pcl_common_ext_dep eigen boost )
set(pcl_kdtree_ext_dep flann )
set(pcl_search_ext_dep flann )
set(pcl_visualization_ext_dep vtk )

```

**Your Environment (please complete the following information):**

 - OS: [Windows10]
 - Compiler: [:MSVC 2019 Ver 16.6.3]
 - PCL Version [PCL-1.11.0-AllInOne-msvc2019-win64]

**Comment by WargodHernandez** [comment]
Same issue with the IO module

Here is pcl_io.dll in 1.11.0
![image](https://user-images.githubusercontent.com/7495752/86293826-3ec1a780-bba8-11ea-8f44-4c70879ae32a.png)

vs pcl_io_release in 1.9.1
![image](https://user-images.githubusercontent.com/7495752/86293926-6b75bf00-bba8-11ea-94d8-e49a7dcb7ce2.png)

**Comment by kunaltyagi** [comment]
IIRC, vtk is an optional dependency to enable more features in those modules, if it's present.

**Comment by larshg** [comment]
The last line in what you posted says it depends on VTK:
`set(pcl_visualization_ext_dep vtk )`

And it is an optional dependency at configurstion/compile time when @UnaNancyOwen packed the all-in-one installer.

But there might be a missing dependency somewhere in the cmake files, since its not propagated to .pc files.

I have seen some while in the progress towards vtk 9.

**Comment by UnaNancyOwen** [comment]
Currently, pre-built PCL that included in PCL All-in-one Installer dynamically linked VTK to avoid this problem https://github.com/PointCloudLibrary/pcl/issues/1601. Therefor, user programs that use PCL require VTK dll files at runtime.

**Comment by WargodHernandez** [comment]
I was pointing out with surface at least there is no optional dependency listed for surface on vtk

```CMake
#list each component dependencies IN PCL
set(pcl_kdtree_int_dep common )
set(pcl_octree_int_dep common )
set(pcl_search_int_dep common kdtree octree )
set(pcl_sample_consensus_int_dep common search )
set(pcl_filters_int_dep common sample_consensus search kdtree octree )
set(pcl_2d_int_dep common filters )
set(pcl_geometry_int_dep common )
set(pcl_io_int_dep common octree )
set(pcl_features_int_dep common search kdtree octree filters 2d )
set(pcl_ml_int_dep common )
set(pcl_segmentation_int_dep common geometry search sample_consensus kdtree octree features filters ml )
set(pcl_visualization_int_dep common io kdtree geometry search octree )
set(pcl_surface_int_dep common search kdtree octree )
set(pcl_registration_int_dep common octree kdtree search sample_consensus features filters )
set(pcl_keypoints_int_dep common search kdtree octree features filters )
set(pcl_tracking_int_dep common search kdtree filters octree )
set(pcl_recognition_int_dep common io search kdtree octree features filters registration sample_consensus ml )
set(pcl_stereo_int_dep common io )
set(pcl_outofcore_int_dep common io filters octree visualization )
set(pcl_people_int_dep common kdtree search features sample_consensus filters io visualization geometry segmentation octree )


#list each component external dependencies (ext means mandatory and opt means optional)
set(pcl_common_ext_dep eigen boost )
set(pcl_kdtree_ext_dep flann )
set(pcl_search_ext_dep flann )
set(pcl_visualization_ext_dep vtk )


set(pcl_2d_opt_dep vtk )
set(pcl_io_opt_dep openni2 vtk )
set(pcl_visualization_opt_dep openni2 )
set(pcl_surface_opt_dep qhull )
```
the only optional dep for surface listed is qhull, for IO vtk is a listed optional dep

**Comment by WargodHernandez** [comment]
in essence shouldn't the last line 
```Cmake
set(pcl_surface_opt_dep qhull )
```
actually be
```CMake
set(pcl_surface_opt_dep qhull vtk)
```

**Comment by larshg** [comment]
This one is fixed by https://github.com/PointCloudLibrary/pcl/pull/4262 (VTK hard requirement) which was wrong and corrected here: https://github.com/PointCloudLibrary/pcl/pull/4656 and part of the newly 1.12 release.
