### ISSUE TITLE
Error including cloud_viewer.h

### ISSUE THREAD

**Issue by yohanmr** [PointCloudLibrary/pcl#4238]
OS: Windows 10
Version: Downloaded and installed via the PCL-1.11.0 - All in one installer.
Compiler: The project is built on the latest VS2019 release 
Generates the below error when cloud_viewer.h is included and compiled.

A similar error was reported in #4189 however all function calls in pcl_visualizer.h do not have arguments in the get_color() function call either. I believe this is a library error in point_cloud_color_handlers.h.

![Bug](https://user-images.githubusercontent.com/24936213/86295124-c5778400-bbaa-11ea-8608-6896dc8bf3ea.PNG)

The projects builds and displays the point cloud fine by commenting out "PCL_DEPRECATED(1, 12, "use getColor() without parameters instead")" from line 619 and 117 of point_cloud_color_handlers.h. Not sure if there is a better fix for this.

**Comment by kunaltyagi** [comment]
> Generates the below error when cloud_viewer.h is included and compiled

Please provide a MCVE. There's no use of `getColor` with arguments in PCL except from `kinfu` which provides its own color handler.

> however all function calls in pcl_visualizer.h do not have arguments in the get_color() function call either

Please expand upon this, since I'm unable to understand what you're trying to convey.

Please use the correct template for reporting bugs in the future

**Comment by larshg** [comment]
Have you by any means warnings as errors or something like that turned on?
Because it should just be a warning and it shouldn't fail at compiling this.

I also get these warnings, but have no trouble compiling it.

**Comment by yohanmr** [comment]
Context:

I am using the PCL library downloaded via the PCL-1.11.0 - All in one installer to visualize a point cloud using the point_cloud.h header. The project is built on the latest VS 2019 release. I am unable to compile it and it terminates with the error in the image above.

Steps to reproduce error:
Compiling the code with the below header results in the error,
#include <pcl/visualization/cloud_viewer.h>

Additional Details:
> Please expand upon this, since I'm unable to understand what you're trying to convey.

When I tried to debug this it led me to line 117 and 619 of point_cloud_color_handlers.h. which was called by pcl_visualizer.h which was called by the cloud_viewer.h. Since the header itself does not compile, the error is not from any function call to get_color() written by the user, so I assumed it must be from the calls in pcl_visualizer.h. 


> Have you by any means warnings as errors or something like that turned on?
> Because it should just be a warning and it shouldn't fail at compiling this.
> 
> I also get these warnings, but have no trouble compiling it.

Warnings as errors is turned off. I even tried it compiling it by turning off all warnings.

**Comment by YBHkorea** [comment]
use #pragma warning(disable:4996)
i have same problem 
 - all in one installer 
 - vs 2019 
but, there's no solution of this error

this error is not warning , so compiler was stopped

**Comment by keineahnung2345** [comment]
By following the steps in [Turn off the warning for a project in Visual Studio](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=vs-2019#turn-off-the-warning-for-a-project-in-visual-studio), I can get rid of this error (I use VS2019 and pcl 1.11.1 all in one installer).

**Comment by takmin** [comment]
I had same problem, but solved it by security check unavailable in "C/C++" property

**Comment by larshg** [comment]
This one is removed from 1.12, in this https://github.com/PointCloudLibrary/pcl/pull/4341. Closing as it is fixed and there are other alternatives described in here.
