### ISSUE TITLE
[apps] Rectangle selection tool does not work properly on retina display

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4239]
**Context**

I run `pcl_point_cloud_editor` on a MacBook with 2880x1800 display resolution. The rectangle selection tool works in principle, but the selection does not scale properly with the mouse movement.
I suspect this has to do with HiDpi handling in Qt or OpenGL. I tried to dig around a bit, but am too unfamiliar with either framework to find the problem.

**Expected behavior**

When dragging selection rectangle, the corner should follow the mouse pointer.

**Current Behavior**

When dragging selection rectangle, the corner seems to follow the mouse pointer with some factor < 1 of its movement.

**To Reproduce**

1. Start `pcl_point_cloud_editor`
2. Load a PCD file
3. Select 2D selection tool
4. Drag around to observe incongruous selection.

**Screenshots/Code snippets**

![editor](https://user-images.githubusercontent.com/11613312/86441462-895c3480-bd0c-11ea-9274-09a421b99d00.gif)

**Your Environment (please complete the following information):**

 - OS: MacOS 10.14.6
 - Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
 - PCL Version: e6d032a1eed0115542ae9895679b75a5fca06eef

**Additional context**

I have inspected `QApplication::desktop()->screen()->size()`, which shows a resolution of 1920x1200 for my screen, which is 1/1.5 of the actual resolution. Maybe these are device-dependent pixels, which some Qt documentation hints at in regards to retina displays.

I attempted to scale the values processed in `mouse*Event()` callbacks in the main editor widget by 1.5, but this did not change the behaviour.

**Comment by themightyoarfish** [comment]
Anyone got advice on where to look here? I can try to fix it myself, but some pointers would be needed.

**Comment by kunaltyagi** [comment]
I'd eliminate factors of error:
* MacOS: try to replicate on another PC (with high resolution display)
* HiDPI screen: try and replicate on low resolution with MacOS
* Homebrew: (assuming you installed using this) install from source
* MacOS's animosity towards OpenGL: replicate in full screen mode in a Virtual Machine running Linux (Ubuntu preferably)

The first successful replication will tell us where the error lies

**Comment by themightyoarfish** [comment]
We found that Ubuntu 16.04 with a 1.11 source build does not exhibit the problem, while macos does.

**Comment by themightyoarfish** [comment]
Hopefully I will find the time to investigate more.

**Comment by kunaltyagi** [comment]
Good to know that the issue is platform specific

**Comment by themightyoarfish** [comment]
I have also tried **Larger text** in macos Display options, which didn't help. I suspect though that the display is still at  full resolution and windows a re just scaled. In previous osx versions one could select resolution explicitly, but I guess Apple removed that.
