### ISSUE TITLE
Update information regarding MSVC in tutorials and CHANGELOG

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4250]
@kunaltyagi Thanks for clarifying that. But I think this should be clearly stated somewhere. [Tutorials ](https://pcl-tutorials.readthedocs.io/en/latest/compiling_pcl_windows.html) still use MSVC 2010, and [changelog](https://github.com/PointCloudLibrary/pcl/blob/master/CHANGES.md) only mentions MSVC 2013 ans previous deprecations.

_Originally posted by @nicolas-cadart in https://github.com/PointCloudLibrary/pcl/issues/4248#issuecomment-654129789_

**Comment by vaibhavkoshti7** [comment]
I would like to work on this issue as my first PR. Can you assign me this?
