### ISSUE TITLE
[cmake] Compile flags that produce Eigen align Issue in a project C++17

### ISSUE THREAD

**Issue by b4l8** [PointCloudLibrary/pcl#4258]
**In a project compiling in [c++17] mode with a sufficiently recent compiler, should be safe from Eigen align issue.Linking to PCL will somehow deny it**

Some project are already using the convenience that we don't need to care about align issue using C++17. The whole project will not be guarded with eigen macro even though the macros are empty in C++17. Linking this kind of project to pcl , with was build with any of following flags "-mavx2 -mavx -mfma -mf16c" included by -march=native will produce this issue. 

**Is that really a bug from Eigen?**
I've checked that compile flags "-mavx2 -mavx -mfma -mf16c" will cause Eigen align issue even in C++17 if your code is not guarded by macros. Obviously , the Eigen user guide does not expect these flags being added. So linking to pcl just triggered this bug. Anyway, both eigen and pcl should notice user this behaviour.  As eigen user guide just saying : "If you're compiling in [c++17] mode only with a sufficiently recent compiler (e.g., GCC>=7, clang>=5, MSVC>=19.12), then everything is taken care by the compiler and you can stop reading." 

**Expected behavior**

As we know what will happen with this flags, -march=native should not be used. Since C++17 got us out of the eigen align problem, we shouldn't force users to add all macros back.

**Current Behavior**
In some project that get rid of the eigen align macros by updating standard to C++17.
Linking to PCL will cause following issue
Eigen assertion on unaligned arrays will fail even on C++17 with latest GCC
path/to/eigen/Eigen/src/Core/DenseStorage.h:44:
Eigen::internal::matrix_array<T, Size, MatrixOptions, Align>::internal::matrix_array()
[with T = double, int Size = 2, int MatrixOptions = 2, bool Align = true]:
Assertion `(reinterpret_cast<size_t>(array) & (sizemask)) == 0 && "this assertion
is explained here: http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html
     READ THIS WEB PAGE !!! ****"' failed.

**To Reproduce**
FIrst of all check if you have "-mavx2 -mavx -mfma -mf16c" enabled by -march=native
 '''gcc -march=native -Q --help=target ... | grep enabled'''
If not, you are free from this bug.
A project without eigen macros on C++17. You must make sure it will trigger eigen align issue in C++11. 
Linking to PCL, or just add one of the compile flags to your project.  Build with C++17.

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 18.04]
 - Compiler: [ GCC 9.3.0]
 - PCL Version [1.11]

**Possible Solution**
in cmake/pcl_find_sse.cmake
replace -march=native with suitable flags.
clean and recompile PCL

**Comment by kunaltyagi** [comment]
What do you suggest for PCL to do? In the possible solutions you've presented a fix for the user, not the library maintainers.

**Comment by SergioRAgostinho** [comment]
Thank you for the detailed explanation. Some thoughts:

>  As eigen user guide just saying : "If you're compiling in [c++17] mode only with a sufficiently recent compiler (e.g., GCC>=7, clang>=5, MSVC>=19.12), then everything is taken care by the compiler and you can stop reading."

The way I see it, the the user guide sentence is misleading. From what you describe, it sounds is that if I use Eigen and C++17, I will never be able to use `-march=native` without manually handling alignment, because now the Eigen alignment macros are empty. Is that the case?

> As we know what will happen with this flags, -march=native should not be used. Since C++17 got us out of the eigen align problem, we shouldn't force users to add all macros back.

These flags are not shipped by package providers which means you compiled PCL from source. If the user doesn't specify any flags while building, we supply a couple of flags by default to speed-up runtime execution. You can manually disable them in your PCL build by setting `PCL_ENABLE_SSE` to OFF during configuration, or alternatively supply your own set of compilation flags.

**Comment by b4l8** [comment]
> possible

Sorry for late reply, as I've been busy working on my company account. In fact, I agree with @SergioRAgostinho.  We can expect Eigen maintainer to solve this issue or just fix their user guide. User who build pcl from source can take care of this following my instructions. It is not good to tell a programmer avoid using -native. The meaning of its existence is gone.

**Comment by themightyoarfish** [comment]
So using C++17 does not magically avoid these problems? Dammit that was my only hope. These issues crop up even after the recent PRs which add the missing `ALIGNED_OPERATOR_NEW` macros in the filter module.
