### ISSUE TITLE
[features] Code Simplification introduced logic bug in OrganizedEdgeDetection

### ISSUE THREAD

**Issue by pionex** [PointCloudLibrary/pcl#4274]
** Summary **

A code change in commit 8092d6529eed0b489f3c7ab50be018f20b6da2bb subtly changed the logic in the extractEdges method of OrganizedEdgeDetection and causes occluded and occluding edges to be categorized incorrectly.

**Expected behavior**

Occluding and occluded edge extraction to perform the same as previous versions of PCL before 1.10.1

**Current Behavior**

Occluding and occluded edges are clearly miscategorized.  Although the total number of indices between the two matches previous versions of PCL, the edges types are incorrectly determined due to a logic bug.

**To Reproduce**

Run PCL 1.10.1 or later

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [GCC 9.3.0]
 - PCL Version [1.11]

**Possible Solution**

Line 135 of organized_edge_detection.hpp in commit 8092d6529eed0b489f3c7ab50be018f20b6da2bb should be reverted.

**Comment by kunaltyagi** [comment]
Thanks for tracking down the commit with the bug. Looks like the error passed through the tests. Can you recommend some test which succeeds on the old code but not in the new one?

**Comment by pionex** [comment]
#4275 is a PR to fix, but it does not include a test yet

My best guess for a test is to generate a synthetic organized cloud with a contrived number of occluding and occluded edges and compare that to what the algorithm calculates.

**Comment by pionex** [comment]
Here is a trivial cloud I generated with a smaller square in front of a larger square.  The proper code will find a similar number of occluding and occluded edge points, but the code with the bug will classify all of the points as occluded. 

```
  auto organized_test_cloud = pcl::make_shared<PointCloud>();
  auto box_width = 50;
  organized_test_cloud->width = box_width * 4;
  organized_test_cloud->height = box_width * 4;
  organized_test_cloud->is_dense = false;
  organized_test_cloud->points.resize(organized_test_cloud->height * organized_test_cloud->width);
  auto resolution = .005;
  auto disparity = .02;
  
  for(std::size_t i = 0; i < box_width * 2; i++)
  {
    for(std::size_t j = 0; j < box_width * 2; j++)
    {
      organized_test_cloud->at(j, i).x = i * resolution - (box_width / 2 * resolution);
      organized_test_cloud->at(j, i).y = j * resolution;
      organized_test_cloud->at(j, i).z = 2.0 + (disparity * 4);
      organized_test_cloud->at(j, i).r = 128;
      organized_test_cloud->at(j, i).g = 128;
      organized_test_cloud->at(j, i).b = 128;
      organized_test_cloud->at(j, i).a = 255;
    }
  }

  for(std::size_t i = box_width / 2; i < box_width / 2 + box_width; i++)
  {
    for(std::size_t j = box_width / 2; j < box_width / 2 + box_width; j++)
    {
      organized_test_cloud->at(j, i).x = i * resolution - (box_width / 2 * resolution);
      organized_test_cloud->at(j, i).y = j * resolution;
      organized_test_cloud->at(j, i).z = 2.0;
      organized_test_cloud->at(j, i).r = 192;
      organized_test_cloud->at(j, i).g = 192;
      organized_test_cloud->at(j, i).b = 192;
      organized_test_cloud->at(j, i).a = 255;
    }
  }
```

```
  auto oed = pcl::OrganizedEdgeFromRGB<pcl::PointXYZRGBA, pcl::Label>();
  auto MaxSearchNeighbors = 50; // 50

  oed.setEdgeType(oed.EDGELABEL_OCCLUDING | oed.EDGELABEL_OCCLUDED);
  oed.setInputCloud(organized_test_cloud);
  oed.setDepthDisconThreshold(disparity);
  oed.setMaxSearchNeighbors(MaxSearchNeighbors);

  auto labels = pcl::PointCloud<pcl::Label>();
  auto label_indices = std::vector<pcl::PointIndices>();

  oed.compute(labels, label_indices);

  std::cout << label_indices[1].indices.size() << std::endl;  // Occluding Indices
  std::cout << label_indices[2].indices.size() << std::endl;  // Occluded indices
```

**Comment by SergioRAgostinho** [comment]
Can we add this to the PR you submitted (or a new one) and proceed with the code review there? I have some questions/comments but I want to have the ability to make them inline with the code :')
