### ISSUE TITLE
Deprecate unneeded meta-headers

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4290]
> There's a very strong chance we can now deprecated and remove all headers of the form
module/*/boost.h

Not all, but some, yes. `pcl/common/boost.h`, `pcl/filters/boost.h`, and `pcl/sample_consensus/boost.h`, also `pcl/geometry/eigen.h` and `pcl/surface/eigen.h`aren't used internally by anyone.

_Originally posted by @mvieth in https://github.com/PointCloudLibrary/pcl/pull/4289#issuecomment-663819199_

**Comment by rabaho** [comment]
I'll take care of this.

**Comment by mvieth** [comment]
That's great!
`pcl/filters/boost.h`, `pcl/geometry/eigen.h`, and `pcl/surface/eigen.h` have already been deprecated by the linked pull request.
`pcl/common/boost.h`, `pcl/sample_consensus/boost.h`, `pcl/octree/boost.h`, and `pcl/recognition/boost.h` can be deprecated.
`pcl/features/boost.h` and `pcl/features/eigen.h` are still used internally, but can be deprecated if you replace their uses with their respective contents.
Slightly different matter, but while you are at it: `correspondence_rejection_median_distance.hpp` is empty and can also be deprecated, if you remove the include in the `.h` file.

**Comment by rabaho** [comment]
What version should they be deprecated in? 1.15?

**Comment by mvieth** [comment]
> What version should they be deprecated in? 1.15?

Yes
