### ISSUE TITLE
Configuring my PC to use the Nvidia GPU with PCL Tutorials

### ISSUE THREAD

**Issue by astronaut71** [PointCloudLibrary/pcl#4293]
Hi

I try to configuring my PC to use your Nvidia GPU with PCL. I have GPU gard and CUDA installed. And follloed this tutorial to configuring your PC to use your Nvidia GPU with PCL [https://pcl-tutorials.readthedocs.io/en/master/gpu_install.html#gpu-install](url) . There its says " However on Ubuntu 16.04, you will need to install GCC 7 or Clang 6 (lower versions not tested) manually because the versions available by default are: GCC 5 and Clang 3.8" But then on this [https://pcl-tutorials.readthedocs.io/en/master/gpu_install.html#gpu-install](url) it says" CUDA only compiles with gcc 4.4 and lower, so if your default installed gcc is 4.5 or higher you’ll need to install gcc 4.4:"

So Im confuse. Please can someone explain me the proper way how to configure my PC to use GPU with PCL?

Thanks

**Comment by kunaltyagi** [comment]
Both links are the same. The first one is correct: Needs GCC7 or Clang 6 and CUDA 10 I believe (based on testing on CI).

PCL might work with other versions, but they aren't tested or supported.

**Comment by astronaut71** [comment]
so I also need  Eigen v3.3.7+? then how to build my own code and make it use GPU?

**Comment by kunaltyagi** [comment]
> how to build my own code and make it use GPU?

Please use discord for such questions. They don't belong on an issue tracker
