### ISSUE TITLE
QT5.14 + VTK8.1 + PCLVisualizer(pcl 1.8)

### ISSUE THREAD

**Issue by heshiwen1989** [PointCloudLibrary/pcl#4300]
When I use the pcl + vtk + qt display pointcloud, firstly, all pointcloud(s)（e.g. 2 diffirence pcd file data） are display normally, but sometime later, some pointcloud display as box, and finally do not display? But I PointCloud(s) is ok

**Comment by heshiwen1989** [comment]
/home/heshiwen/Pictures/2020-07-31 20-14-44屏幕截图.png

**Comment by heshiwen1989** [comment]
![2020-07-31 20-14-44屏幕截图](https://user-images.githubusercontent.com/28886748/89034117-e7f7eb00-d36a-11ea-8dc2-d746a59a76b7.png)
Just like this, 3 PointCloud are displayed, but one display abnormally

**Comment by larshg** [comment]
I think this is a "feature" of vtk. If you rotate etc. it substitutes all points with a box. But the points should reappear when rotation/translation is stopped.

Can you try upload the point clouds - I'll try reproduce.

Which OS, pcl and vtk version do you use?

**Comment by heshiwen1989** [comment]
> I think this is a "feature" of vtk. If you rotate etc. it substitutes all points with a box. But the points should reappear when rotation/translation is stopped.
> 
> Can you try upload the point clouds - I'll try reproduce.
> 
> Which OS, pcl and vtk version do you use?

Hello, My System is Ubuntu 16.04, And Finally find that my compute cup is low, and i use more powerful computer this issue is not appear again, thanks again
