### ISSUE TITLE
vtkRenderingLOD-8.2-gd.dll was not found

### ISSUE THREAD

**Issue by Zumbalamambo** [PointCloudLibrary/pcl#4301]
**Describe the bug**

**Context**

What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world

I'm trying to build one of the tutorial code cloudviewer.

It must run the cloudviewer as intended
What happens instead of the expected behavior?

It throws the following error message,
"vtkRenderingLOD-8.2-gd.dll was not found"

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 16.04] Windows 10
 - Compiler: [:eg GCC 8.1] GCC 8.1
 - PCL Version [e.g. 1.10, HEAD] 1.11

**Comment by larshg** [comment]
How have you installed the dependencies?

Can you find the vtk bin folder, with the vtkRenderingLOD-8.2-gd.dll?

Either add that path to the environment path variable or copy the file next to the exe file you try to run.

**Comment by kunaltyagi** [comment]
Closing since the issue seems to have been found
