### ISSUE TITLE
pcl_virtual_scanner tool

### ISSUE THREAD

**Issue by haeginh** [PointCloudLibrary/pcl#4303]
**Describe the bug**

The point cloud is accumulated over the viewpoint

**Expected behavior**

New point cloud should be written for each viewpoint

**Current Behavior**

The point cloud is accumulated over the viewpoints, and thus the number of the point increases

**To Reproduce**

For any ply file, 
pcl_virtual_scanner XX.ply

To see the accumulation clearly,
pcl_virtual_scanner -organized 1 XX.ply

**Screenshots/Code snippets**

<NOW>
Wrote 810000 points (900 x 900) to test2.ply_output/0.pcd
Wrote 1620000 points (900 x 900) to test2.ply_output/1.pcd
Wrote 2430000 points (900 x 900) to test2.ply_output/2.pcd
Wrote 3240000 points (900 x 900) to test2.ply_output/3.pcd
Wrote 4050000 points (900 x 900) to test2.ply_output/4.pcd
Wrote 4860000 points (900 x 900) to test2.ply_output/5.pcd
Wrote 5670000 points (900 x 900) to test2.ply_output/6.pcd
Wrote 6480000 points (900 x 900) to test2.ply_output/7.pcd
Wrote 7290000 points (900 x 900) to test2.ply_output/8.pcd

<SUPPOSED TO BE>
Wrote 810000 points (900 x 900) to test2.ply_output/0.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/1.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/2.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/3.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/4.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/5.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/6.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/7.pcd
Wrote 810000 points (900 x 900) to test2.ply_output/8.pcd

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Compiler: GCC 7.5.0
 - PCL Version 1.8.1

**Possible Solution**

move the declaration of the point cloud into the viewpoint loop

**Comment by kunaltyagi** [comment]
Needs rephrasing to understand the issue. Some images/screencast would also be nice

**Comment by haeginh** [comment]
Sorry! I just copied and pasted the result printed in the terminal and it does not look so good here.
What I mean is that when I use -organized 1 option, it is supposed to generate clouds with (900*900)=810000 points, but the number of the points is accumulated over the loop; 0.pcd has 810000 points, 1.pcd has 810000*2 points, 2.pcd has 810000*3 points, and so on.
This is because the cloud is not initialized over the loop, and can be easily fixed by moving the declaration of the cloud(pcl::PointCloud<pcl::PointWithViewpoint> cloud;) in to the for loop(for (int i = 0; i < number_of_points; i++)). Thanks!

**Comment by kunaltyagi** [comment]
Got it. Thanks for the explanation. Please go ahead with a PR. If you need help regarding that, please check [GitHub's help page](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests)

**Comment by mvieth** [comment]
Should be fixed by pull request #4730
