### ISSUE TITLE
error LNK2001: "private: static class Scene * Scene::instance_" (?instance_@Scene@@0PEAV1@EA)

### ISSUE THREAD

**Issue by lvpinrui** [PointCloudLibrary/pcl#4304]
Header files and library files are added to the project，but when build this project,there is a question.
![image](https://user-images.githubusercontent.com/44189445/89395961-92dc2080-d740-11ea-8ff4-a2458c3dc0e7.png)

I am waitting for your reply!

**Comment by kunaltyagi** [comment]
Please provide the details asked in the issue format:
* OS
* Version of PCL
* Setup used
* Steps to replicate error

**Comment by lvpinrui** [comment]
thanks for your reply.
my environment is:
os:windows 64 
Setup used:  vs2015
Version of PCL:1.8.1
This error appears when I just use the method of the directory of outofcore/visualization/scene.h.
I added the outofcore  module library and outofcore module header files

**Comment by lvpinrui** [comment]
> Please provide the details asked in the issue format:
> 
> * OS
> * Version of PCL
> * Setup used
> * Steps to replicate error

thanks for your reply.
my environment is:
os:windows 64
Setup used: vs2015
Version of PCL:1.8.1
This error appears when I just use the method of the directory of outofcore/visualization/scene.h.
I added the outofcore module library and outofcore module header files

**Comment by larshg** [comment]
Hi
It looks like you need to include the scene.cpp file to your project as well. See the Tools example here how to do it:
https://github.com/PointCloudLibrary/pcl/tree/master/outofcore/tools/outofcore_viewer.cpp.

The Scene object, is not exported and seems oddly implemented in PCL.

**Comment by kunaltyagi** [comment]
Closing since it appears the issue was resolved
