### ISSUE TITLE
[Moving Least Squares] Segmentation fault on Moving Least Squares

### ISSUE THREAD

**Issue by luissantos27** [PointCloudLibrary/pcl#4329]
**Describe the bug**

I have this code for years and recently, when I executed I keep getting a segmentation fault on Moving Least Square. This used to work without any problem.

**Context**

The objective is to smooth a PCD file with moving least squares, and publish the result in ROS format. 

**Current Behavior**

Segmentation Fault

**Screenshots/Code snippets**
```
 void smooth_pcl(pcl::PointCloud<pcl::PointXYZ >::Ptr Cloud_) {

    pcl::search::KdTree<pcl::PointXYZ>::Ptr Ktree (new pcl::search::KdTree<pcl::PointXYZ>);

    pcl::PointCloud<pcl::PointNormal> mls_points;
    pcl::MovingLeastSquares<pcl::PointXYZ, pcl::PointNormal> mls;

    mls.setComputeNormals (true);

    mls.setInputCloud (Cloud_);
    mls.setPolynomialFit (true);
    mls.setSearchMethod (Ktree);
    mls.setSearchRadius (radius_neigh);


    mls.process (mls_points);  // Segmentation Fault HERE

    pcl::io::savePCDFile(pcd_file, mls_points);

  }
```

```
 pcl::PointCloud<pcl::PointXYZ>::Ptr Cloud_(new pcl::PointCloud<pcl::PointXYZ>);

    pcl::PointCloud<pcl::PointXYZ>::Ptr Cloud_surface(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointCloud<pcl::PointXYZ>::Ptr Cloud_corners(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointXYZ cloud_3d;

    Cloud_surface->header.frame_id = "map";
    Cloud_corners->header.frame_id = "map";
    sensor_msgs::PointCloud2 ros_cloud;


    if (pcl::io::loadPCDFile<pcl::PointXYZ>(surface_pcd_file.data(), *Cloud_surface) == -1) {  // * load the file
      PCL_ERROR ("Couldn't read file %s \n", surface_pcd_file.data());
    } else {

      std::cout << "Loaded "
                << Cloud_surface->width * Cloud_surface->height
                << " data points from "
                << surface_pcd_file.data()
                << " with the following fields: "
                << std::endl;


      Cloud_->is_dense = false;
      Cloud_->width = Cloud_surface->points.size();
      Cloud_->height = 1;

      for (int32_t i = 0; i < Cloud_surface->points.size(); i++) {

        cloud_3d.x = Cloud_surface->points[i].x;
        cloud_3d.y = Cloud_surface->points[i].z;   // SWITCHED on PURPOSE 
        cloud_3d.z = Cloud_surface->points[i].y;

        Cloud_->points.push_back(cloud_3d);
      }

      smooth_pcl(Cloud_);  // SEGMENTATION FAULT INSIDE
```

**When running, this is the output:**

```
Loaded 95093 data points from /home/user/catkin_ws/src/cornerMap.pcd with the following fields: 
Signal: SIGSEGV (Segmentation fault)
```

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
 - PCL Version 1.8
 - ROS Melodic

**Comment by kunaltyagi** [comment]
> PCL Version 1.8

Does this occur on latest PCL? PCL doesn't backport updates due to lack of manpower

**Comment by luissantos27** [comment]
> > PCL Version 1.8
> 
> Does this occur on latest PCL? PCL doesn't backport updates due to lack of manpower

This did not happen in the previous versions. I have not tried on the latest ones

**Comment by kunaltyagi** [comment]
> This did not happen in the previous versions

Which versions did you try on? We could probably find the commits affecting the class if you can narrow down the bug for us.

> How can I update on ubuntu?

I'd recommend install from source. Are you using ROS or something else? If you're using ROS, do you use `catkin` (aka catkin-tools) or `catkin_make`?

**Comment by luissantos27** [comment]
> > This did not happen in the previous versions
> 
> Which versions did you try on? We could probably find the commits affecting the class if you can narrow down the bug for us.
I am not sure. But this code was originally written in ubuntu 16.04. Last time I have used this code was in December, already on ubuntu bionic. 

> 
> > How can I update on ubuntu?
> 
> I'd recommend install from source. Are you using ROS or something else? If you're using ROS, do you use `catkin` (aka catkin-tools) or `catkin_make`?

I use catkin_make. Install by source it is not an option for me. All of my dependencies must be automatically and easily installed. Its a requirement of my research project.

**Comment by kunaltyagi** [comment]
> Its a requirement of my research project.

You can still use source for finding and helping fix the bug.

> Last time I have used this code was in December, already on ubuntu bionic.

Was the error present then or did it manifest now?

**Comment by kunaltyagi** [comment]
`git diff pcl-1.7.2 pcl-1.8.1 -- <mls, kdtree sources>` doesn't provide with any significant change. Could you try pinpoint the error happens inside `mls.process` call? `gdb` is a good tool to figure that out.

**Comment by luissantos27** [comment]
> > Its a requirement of my research project.
> 
> You can still use source for finding and helping fix the bug.
> 
> > Last time I have used this code was in December, already on ubuntu bionic.
> 
> Was the error present then or did it manifest now?

Just now.

**Comment by luissantos27** [comment]
> `git diff pcl-1.7.2 pcl-1.8.1 -- <mls, kdtree sources>` doesn't provide with any significant change. Could you try pinpoint the error happens inside `mls.process` call? `gdb` is a good tool to figure that out.

I will have to install by source to do that

**Comment by kunaltyagi** [comment]
Not to use gdb. Just run your code with gdb and check the backtrace.

> Just now

That makes it likely that the error is in your end, not PCL since PCL hasn't been updated on 18.04 since 2018

**Comment by mvieth** [comment]
@luissantos27 Can you also provide the pcd file(s) you are using? Without them it is hard to reproduce your bug.

**Comment by saber-ws** [comment]
I got the same error with PCL 1.8.0, when I set 
```
mls.setPolynomialFit (false);
```
program works well.
I update PCL to 1.11.0, both parameters works well.

**Comment by luissantos27** [comment]
> I got the same error with PCL 1.8.0, when I set
> 
> ```
> mls.setPolynomialFit (false);
> ```
I had this parameter set to "true". However, that makes no difference. I'm still getting the same error.
> 
> program works well.
> I update PCL to 1.11.0, both parameters works well.
Looks like I would have to update it by source, and that's not a good solution for me.

**Comment by luissantos27** [comment]
> @luissantos27 Can you also provide the pcd file(s) you are using? Without them it is hard to reproduce your bug.

Here are a few example: 


[pointcloud_examples.zip](https://github.com/PointCloudLibrary/pcl/files/5150639/pointcloud_examples.zip)

**Comment by mvieth** [comment]
I tried to reproduce your error but was unable to do so (Ubuntu 18.04.5, PCL 1.8.1). Please try to run your program with valgrind and/or gdb+backtrace

**Comment by luissantos27** [comment]
Thank you all for your help. The computer I am using had a previous installation of libpcl 1.8.0 installed by some unknown method. I had installed libpcl 1.8.1 from Synaptic in ubuntu , and the two libraries were conflicting. I have managed to delete libpcl 1.8.0, and the program is running with 1.8.1.
