### ISSUE TITLE
[io] PCD reader doesn't scale on parallelization due to too many memory allocations

### ISSUE THREAD

**Issue by chennuo0125-HIT** [PointCloudLibrary/pcl#4333]
- OS: [e.g. Ubuntu 16.04]
 - Compiler: [:eg GCC 5.4.0]
 - PCL Version [e.g. 1.8.1, HEAD]
 - CPU:  i5-8500
 - Mem: 16G

demo without omp : 
```
int main (int argc, char** argv)
{
    float ts = omp_get_wtime();
    string fdir = "/home/cn/temp/";
    for (int i = 0; i < 5; i++)
    {
        float t0 = omp_get_wtime();
        pcl::PointCloud<pcl::PointXYZI>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZI>);
        string file = fdir + to_string(i) + ".pcd";
        if(pcl::io::loadPCDFile(file, *cloud) == -1){
            cout<<"cant load file "<<file<<endl;
            continue;
        }
        float t1 = omp_get_wtime();
        cout<<"index "<<i<<" cost time "<<(t1-t0)<<endl;
    }
    float te = omp_get_wtime();
    cout<<"total cost time "<<(te-ts)<<endl;

    return 0;
}
```
result0:
```
index 0 cost time 7.75
index 1 cost time 7.6875
index 2 cost time 7.6875
index 3 cost time 7.875
index 4 cost time 7.75
total cost time 39
```

demo with omp : 
```
int main (int argc, char** argv)
{
    float ts = omp_get_wtime();
    string fdir = "/home/cn/temp/";
    #pragma omp parallel for num_threads(5)
    for (int i = 0; i < 5; i++)
    {
        float t0 = omp_get_wtime();
        pcl::PointCloud<pcl::PointXYZI>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZI>);
        string file = fdir + to_string(i) + ".pcd";
        if(pcl::io::loadPCDFile(file, *cloud) == -1){
            cout<<"cant load file "<<file<<endl;
            continue;
        }
        float t1 = omp_get_wtime();
        cout<<"index "<<i<<" cost time "<<(t1-t0)<<endl;
    }
    float te = omp_get_wtime();
    cout<<"total cost time "<<(te-ts)<<endl;

    return 0;
}
```
result1:
```
index 1 cost time 38.875
index 2 cost time 39.125
index 3 cost time 39.125
index 0 cost time 39.3125
index 4 cost time 39.3125
total cost time 39.3125
```
from above, can found that parallel loading pcd with openmp, but total cost time cant decrese :( :( :(, hope for solution

**Comment by chennuo0125-HIT** [comment]
at first, i doubt whether is no enough bandwidth for hard disk, but my hard disk is kinston SA400S3 which's read speed is 500M/S, so i can exclude above doubt. further more, i test example as follows:
demo1:
```
int main (int argc, char** argv)
{
    string fdir = "/home/cn/temp/";
    float fs = omp_get_wtime();
    for (int i = 0; i < 4; i++)
    {
        float start = omp_get_wtime();
        string load_file = fdir + to_string(i) + ".pcd";
        cout<<"read file -> "<<load_file<<endl;
        ifstream in;
        in.open(load_file.c_str());
        vector<string> lines;
        string line;
        while(!in.eof()){
            getline(in, line);
            lines.push_back(line);
        }
        float end = omp_get_wtime();
        cout<<"file "<<i<<"  lines size "<<lines.size()<<"  total cost time "<<(end-start)<<" [s]"<<endl;
    }
    float fe = omp_get_wtime();
    cout<<"total cost time "<<fe-fs<<endl;

    return 0;
}
```
result1:
```
read file -> /home/cn/temp/0.pcd
file 0  lines size 1588559  total cost time 0.3125 [s]
read file -> /home/cn/temp/1.pcd
file 1  lines size 1588559  total cost time 0.3125 [s]
read file -> /home/cn/temp/2.pcd
file 2  lines size 1588559  total cost time 0.3125 [s]
read file -> /home/cn/temp/3.pcd
file 3  lines size 1588559  total cost time 0.3125 [s]
total cost time 1.4375
```

demo2(with openmp):
```
int main (int argc, char** argv)
{
    string fdir = "/home/cn/temp/";
    float fs = omp_get_wtime();
    #pragma omp parallel for
    for (int i = 0; i < 4; i++)
    {
        float start = omp_get_wtime();
        string load_file = fdir + to_string(i) + ".pcd";
        cout<<"read file -> "<<load_file<<endl;
        ifstream in;
        in.open(load_file.c_str());
        vector<string> lines;
        string line;
        while(!in.eof()){
            getline(in, line);
            lines.push_back(line);
        }
        float end = omp_get_wtime();
        cout<<"file "<<i<<"  lines size "<<lines.size()<<"  total cost time "<<(end-start)<<" [s]"<<endl;
    }
    float fe = omp_get_wtime();
    cout<<"total cost time "<<fe-fs<<endl;

    return 0;
}
```
result2:
```
read file -> /home/cn/temp/0.pcd
read file -> /home/cn/temp/1.pcd
read file -> /home/cn/temp/2.pcd
read file -> /home/cn/temp/3.pcd
file 0  lines size 1588559  total cost time 0.4375 [s]
file 3  lines size 1588559  total cost time 0.4375 [s]
file 1  lines size 1588559  total cost time 0.4375 [s]
file 2  lines size 1588559  total cost time 0.4375 [s]
total cost time 0.5
```
from above can get that bandwidht of disk is enought, and use openmp can parallel loading data, and decrese load time, please tell me why pcl::io::loadPCDFile cant decrease loading time by use openmp ?

**Comment by kunaltyagi** [comment]
Closing as this is not an issue in PCL.


Feel free to continue discussion

**Comment by kunaltyagi** [comment]
OMP took the same time as normal, implying that somewhere linear behavior is being forced, eg: by some global.

Could you run perf on your PCL examples and see where they spend their time? That'd tell us where the blockage is happening.

Are the files same in both the cases (using PCL to read and dumping in std::vector)?

**Comment by chennuo0125-HIT** [comment]
yes, files are same in both the cases. linear behavior is forced in pcl::io::loadPCDFile() interface ? i cant found it by code :(, hope for your solution

**Comment by chennuo0125-HIT** [comment]
file link : https://drive.google.com/file/d/1g81yoewj9LAUzd7HFHg_W3O7zMbWMZuP/view?usp=sharing
i copyed the cloud to four clouds named 0.pcd 1.pcd 2.pcd and 3.pcd

**Comment by kunaltyagi** [comment]
>  linear behavior is forced in pcl::io::loadPCDFile() interface ? 

The code doesn't say so. That's why I asked if you could perf the binaries

**Comment by chennuo0125-HIT** [comment]
https://github.com/PointCloudLibrary/pcl/blob/809ef274a3adff4bf991cf537340153dcbebc11a/io/include/pcl/io/file_io.h#L338
https://github.com/PointCloudLibrary/pcl/blob/809ef274a3adff4bf991cf537340153dcbebc11a/io/include/pcl/io/file_io.h#L374
The reason is using stringstream object to convert data type, and need allocate memory on heap when using stringstream object. when use multi stringstream objects at same time, there will be mutex to allocate memory on heap, so lead to serial allocate memory operation !

**Comment by chennuo0125-HIT** [comment]
test demo 0 :
```
int main (int argc, char** argv)
{
    const int frame_num = 5;
    const int num = 5*1024*1024;
    vector<string> raw_datas(num, "666");

    float fs = omp_get_wtime();
    #pragma omp parallel for
    for (int i = 0; i < 5; i++)
    {
        float t0 = omp_get_wtime();
        for (int j = 0; j < num; j++)
        {
            stringstream ss(raw_datas[j]);
            int data;
            ss >> data;
        }
        float t1 = omp_get_wtime();
        cout<<"index "<<i<<" cost time "<<(t1-t0)<<" [sec]"<<endl;
    }
    float fe = omp_get_wtime();
    cout<<"total cost time "<<(fe-fs)<<" [sec]"<<endl;

    return 0;
}
```
result0:
```
index 0 cost time 1.85156 [sec]
index 1 cost time 1.85156 [sec]
index 2 cost time 1.86719 [sec]
index 3 cost time 1.85938 [sec]
index 4 cost time 1.85156 [sec]
total cost time 9.28125 [sec]
```

test demo 1 :
```
int main (int argc, char** argv)
{
    const int frame_num = 5;
    const int num = 5*1024*1024;
    vector<string> raw_datas(num, "666");

    float fs = omp_get_wtime();
    #pragma omp parallel for
    for (int i = 0; i < 5; i++)
    {
        float t0 = omp_get_wtime();
        for (int j = 0; j < num; j++)
        {
            stringstream ss(raw_datas[j]);
            int data;
            ss >> data;
        }
        float t1 = omp_get_wtime();
        cout<<"index "<<i<<" cost time "<<(t1-t0)<<" [sec]"<<endl;
    }
    float fe = omp_get_wtime();
    cout<<"total cost time "<<(fe-fs)<<" [sec]"<<endl;

    return 0;
}
```
result1:
```
index 0 cost time 10.3438 [sec]
index 4 cost time 11.4219 [sec]
index 3 cost time 11.4844 [sec]
index 1 cost time 11.6016 [sec]
index 2 cost time 11.6094 [sec]
total cost time 11.6172 [sec]
```

**Comment by kunaltyagi** [comment]
Thanks for pointing out the issue.

**Comment by kunaltyagi** [comment]
Can you try this fork and see if the results are better: https://github.com/kunaltyagi/pcl/tree/pcd_omp

**Comment by chennuo0125-HIT** [comment]
i test the start demo as follow : 
```
int main (int argc, char** argv)
{
    float ts = omp_get_wtime();
    string fdir = "/home/cn/temp/";
    #pragma omp parallel for num_threads(5)
    for (int i = 0; i < 5; i++)
    {
        float t0 = omp_get_wtime();
        pcl::PointCloud<pcl::PointXYZI>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZI>);
        string file = fdir + to_string(i) + ".pcd";
        if(pcl::io::loadPCDFile(file, *cloud) == -1){
            cout<<"cant load file "<<file<<endl;
            continue;
        }
        float t1 = omp_get_wtime();
        cout<<"index "<<i<<" cost time "<<(t1-t0)<<endl;
    }
    float te = omp_get_wtime();
    cout<<"total cost time "<<(te-ts)<<endl;

    return 0;
}
```
the result without omp : 
```
index 0 cost time 3.125
index 1 cost time 3.125
index 2 cost time 3.11719
index 3 cost time 3.125
index 4 cost time 3.15625
```
result with omp : 
```
index 3 cost time 14.3047
index 1 cost time 15.3672
index 0 cost time 15.3906
index 4 cost time 15.625
index 2 cost time 16.4141
```
from above, no performance improve :( :( :(

**Comment by kunaltyagi** [comment]
1. Are you using `-O2` or `-O3` flag for compilation?
2. I thought using `.str` would prevent dynamic allocation. What is the source of slowdown in this case?
3. Can you verify that my fork was used and not the pre-installed PCL? CMake sometimes favors system installed library

**Comment by kunaltyagi** [comment]
My fork-branch clearly has benefits over current PCL. [Customary godbolt](https://godbolt.org/z/so78sE)

Your timings also changed between the 1st and prev run (from 39 seconds down to 16). If this happened due to my fork rather than due to change in input files, I'll create a PR anyways since this is a speed-up of 50%.

**Comment by chennuo0125-HIT** [comment]
sorry, i didnt see the perfence for one pcd before. the fork you provided has big improvement when load single one pcd :) :) :), but still existing problem that cant decrease loading time by multi thread, could you optimize this ?

**Comment by kunaltyagi** [comment]
The input file of size 1.59 mil lines is causing 51 mil allocations. I'm pretty sure if we bring the number of allocations down the speed will go up (including multi-threaded speed)

However, the bigger issue might be the locale setting. IIRC, setting locale performs a lock if you're using an old API

**Comment by kunaltyagi** [comment]
The culprit has been narrowed down to `boost::split` here: https://github.com/PointCloudLibrary/pcl/blob/master/io/src/pcd_io.cpp#L446

I'm unable to remove them despite using `boost::iterator_range` (though that did reduce the memory usage a little (100 bytes or so per line) which isn't worth the ugly code)

Suggestions welcome on how to eliminate mem-alloc in that line

**Comment by mvieth** [comment]
@djanekovic Thank you for the detailed analysis and the nice write-up!
1. I am quite cautious with adding new dependencies. There is a lot to consider and a lot that can go wrong (now and in the future). For example: Is the license compatible with PCL's BSD license? How compatible is the dependency with different OSes and compilers? Can we be sure that it will be continued to be maintained in the future? How stable is the API? etc. If I understood you correctly, this would replace the `atof` in `copyStringValue`? Do you have an estimate how much improvement fast_float gives over `atof`? I haven't read [1] completely yet, but maybe we find an alternative that is better than `atof`, where we don't have to add a dependency?
2. I would estimate that replacing `boost::split` will give use the most improvement. I analysed `loadPCDFile` with valgrind's callgrind, not for allocations but for spent time, and about 40% of the time is spent in `boost::split`. I haven't seen your replacement yet, so I can't say much about that right now. If there are similarly performance-critical places that use `boost::split` (maybe ply_io.cpp or obj_io.cpp?) we could consider replacing it there, too.
3. I think I covered most the answer in 1., but just as a minor note, parsing everything as double, then casting to `int32_t` or whatever does not feel optimal

At some point we should also test how the improvements affect the behaviour in combination with OpenMP.
Thanks again!

**Comment by djanekovic** [comment]
Hi @mvieth!

First off all, after reading your answer I realized I haven't benchmarked just replacing `boost::split` without any other changes..
```
131 allocs, 76,382,651 bytes allocated
```
Ahh, I fully forgot to test just that! I went down the path, `boost::string_ref` -> replace `boost::split` -> `fast_float` and I forgot to benchmark every change in isolation... Sorry.. After running perf on this minimal example I see that now 25% of the time is spent in `__GI_____strtod_l_internal`.

I will now answer all your questions in details block so you can skip them if you don't have time to continue the discussion around them(or we can continue the discussion around some on discord if you want). I just realized they are not relevant anymore and they boil down to, you are correct `fast_float` is not needed and replacing `boost::split` is just fine

<details>

> How stable is the API? etc. If I understood you correctly, this would replace the atof in copyStringValue? Do you have an estimate how much improvement fast_float gives over atof? I haven't read [1] completely yet, but maybe we find an alternative that is better than atof, where we don't have to add a dependency?

`fast_float` is an implementation of C++17 standard so API is well defined and stable. I cannot comment a lot about the Apache v2 being compatible with BSD since I don't know a lot about that. All in all, I agree and I understand, adding new dependencies is a pain and should be avoided. `fast_float` was supposed to replace this pattern:
```
T value;
is.str(st);
is >> value;
```
and it was especially handy with `boost:string_ref` since the API can take begin and end. That library is just a super fast C++11 implementation of an algorithm for parsing real numbers and the API is following C++17 specification(two free functions and a struct for return value).

>I would estimate that replacing boost::split will give use the most improvement. I analysed loadPCDFile with valgrind's callgrind, not for allocations but for spent time, and about 40% of the time is spent in boost::split. I haven't seen your replacement yet, so I can't say much about that right now. If there are similarly performance-critical places that use boost::split (maybe ply_io.cpp or obj_io.cpp?) we could consider replacing it there, too.

That is aligned with my tests because with replacing `boost::split` my running time on this example is 33% faster. Ok, I will try to go through that code and check if we can speed up that part also.

>I think I covered most the answer in 1., but just as a minor note, parsing everything as double, then casting to int32_t or whatever does not feel optimal

Of course not! This was just a quick hack such that I can run the test suite and report the improvements here. Don't worry, I wouldn't open PR with something like that on my branch.

</details>

To conclude, I understand and I agree that adding new dependency is difficult and it becomes a big burden on developers. I would also like to say that on my part this was a premature optimization.  and I should have considered performance improvements just from replacing `boost::split`...

For starters I am going to put this new `pcl::split` function in `io/include/pcl/io/split.h` and we can go from there. Does that sound fine? I will also try to go through ply_io.cpp and obj_io.cpp and check can they also get some speedup from this change.

>At some point we should also test how the improvements affect the behaviour in combination with OpenMP.

Sure thing!

**Comment by mvieth** [comment]
After the big improvement by the latest pull request, I would consider this issue fixed
