### ISSUE TITLE
[sample_consensus\ransac] ransac.computeModel crashes

### ISSUE THREAD

**Issue by Aleksejus1** [PointCloudLibrary/pcl#4346]
**Describe the bug**

When running pcl::RandomSampleConsensus<PointXYZ>::computeModel with a SampleConsensusModelRegistration<PointXYZ>::Ptr model, the computeModel fails and try/catch outputs 'invalid map<K, T> key'

**Context**

I'm trying to use ransac to pull the points of one point cloud towards the points of another, specifically, points of a pointcloud are being pulled towards a mesh that was generated from that pointcloud.

**Expected behavior**

I expected the computeModel to succeed in computing a model or at least return a 'false' boolean telling me that it was unsuccessfull

**Current Behavior**

When executing computeModel, it crashes, and with a try/catch statement i'm able to get an exception which when printed to the console says: 'invalid map<K, T> key'

**To Reproduce**

Try running my code bellow on two pointclouds, which could be even random data (though i have not tried random pointclouds myself, but i can if needed)

**Screenshots/Code snippets**

```C++
#include <pcl\sample_consensus\sac_model_registration.h>
#include <pcl\sample_consensus\ransac.h>
#include <pcl\common\io.h>
#include <stdlib.h>

using namespace pcl;
using namespace std;

PointCloud<PointXYZ>::Ptr PCL::Ransac(PointCloud<PointXYZ>::Ptr cloudInput, PointCloud<PointXYZ>::Ptr cloudTarget, double threshold)
{
	try
	{
		SampleConsensusModelRegistration<PointXYZ>::Ptr sac_model(new SampleConsensusModelRegistration<PointXYZ>(cloudInput));
		sac_model->setInputTarget(cloudTarget);
		RandomSampleConsensus<PointXYZ> ransac(sac_model, threshold);
		if (ransac.computeModel(1)) {
			vector<int> inliers;
			ransac.getInliers(inliers);

			PointCloud<PointXYZ>::Ptr finalCloud(new PointCloud<PointXYZ>);
			copyPointCloud(*cloudTarget, inliers, *finalCloud);
			return finalCloud;
		}
	}
	catch (const exception& e)
	{
		cout << e.what() << endl;
	}
	return nullptr;
}
```

**Your Environment (please complete the following information):**

 - OS: Windows 10 x64
 - Compiler: where can i find this? I'm using Microsoft Visual Studio, running a c++ project
 - PCL Version where can i find it? I installed pcl using vcpkg a couple of days ago, so it should be one of the newest versions

**Possible Solution**

No idea. That's why i'm writing here.

**Additional context**

If i run this code and provide both pointclouds where every point is 0,0,0(x,y,z) then it does not crash but instead returns 'false' which is what i expected. So it only crashes on real data, where it's not all 0.
The threshold that i provide is 0.1.
If needed i can also send the two pointclouds that i'm using on this code.

**Comment by mvieth** [comment]
Could you test what `sizeof(int)` returns on your computer?
It would be useful if you could provide your two pointclouds, then I can see if I can reproduce the issue on Ubuntu.
I am not familiar with Visual Studio, but there is probably a way to debug your program and find out where the exception came from exactly? Can you try that?

**Comment by Aleksejus1** [comment]
> Could you test what `sizeof(int)` returns on your computer?
> It would be useful if you could provide your two pointclouds, then I can see if I can reproduce the issue on Ubuntu.
> I am not familiar with Visual Studio, but there is probably a way to debug your program and find out where the exception came from exactly? Can you try that?

`sizeof(int)` returns 4
I'm attaching a zip containing two .ply files. cloudInput.ply is the pointcloud used in cloudInput and cloudTarget.ply is a mesh which's vertex positions are used as the pointcloud for cloudTarget.
I am using threshold of 0.1
[pointclouds.zip](https://github.com/PointCloudLibrary/pcl/files/5168450/pointclouds.zip)

As far as debugging goes with Visual Studio goes, it's possible but a bit difficult because i'm currently building a c++ DLL that's then used from a c# script, so i'd need to write the test program in c++, but if it's absolutely necessery to fix this issue i'll put in the time to do so. For now, the best i can do from debuging quickly is try/catch which returns 'invalid map<K, T> key' as mentioned in my start post

**Comment by mvieth** [comment]
I think I found the problem: the two point clouds, input and target, must have the same size. That is checked [here](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/sac_model_registration.h#L310), before filling `correspondences_`, so `correspondences_` is empty. Later, when `correspondences_` is [accessed](https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/impl/sac_model_registration.hpp#L85), the exception is thrown.

On the PCL side, I guess logging/prints could be more helpful.

**Comment by kunaltyagi** [comment]
Awaiting PR or issue-closure

**Comment by mvieth** [comment]
@Aleksejus1 If you feel like your question is answered and the problem resolved, please close this issue. If you like, you can also have a look at the linked pull request.

**Comment by Aleksejus1** [comment]
Yeah, this specific issue was caused by input and target pointclouds being of different size.
