### ISSUE TITLE
[CI] Enable CUDA on Ubuntu 20.04 CI

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4351]
**Describe the bug**

Ubuntu 20.04 CI doesn't build with CUDA

**Additional context**

https://gitlab.com/nvidia/container-images/cuda/-/tree/master/dist/11.0

Thanks @larshg for bringing this to notice

(Estimated difficulty: low since code compiles with CUDA 10)

**Comment by mvieth** [comment]
@kunaltyagi Fixed by https://github.com/PointCloudLibrary/pcl/commit/09f705ec40704bf119a3e585b34ca87ebb3316dd ?

**Comment by mvieth** [comment]
@kunaltyagi ping

**Comment by kunaltyagi** [comment]
Yeah. Fixed (by me 🤦🏾)
