### ISSUE TITLE
cmake won't detect flann directory

### ISSUE THREAD

**Issue by tonifds** [PointCloudLibrary/pcl#4356]
![image](https://user-images.githubusercontent.com/39823863/91308126-84b97700-e7b7-11ea-9c65-f42374f0db2d.png)

Windows 10 Pro 64-bit
Visual studio 2019
PCL 1.11.1 all in one installer.

C++ file:

#include <pcl/io/pcd_io.h>
#include <pcl/kdtree/kdtree_flann.h>
#include <pcl/features/normal_3d.h>
#include <pcl/surface/gp3.h>

int
main(int argc, char** argv)
{
	// Load input file into a PointCloud<T> with an appropriate type
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::PCLPointCloud2 cloud_blob;
	pcl::io::loadPCDFile("bun0.pcd", cloud_blob);
	pcl::fromPCLPointCloud2(cloud_blob, *cloud);
	//* the data should be available in cloud

	// Normal estimation*
	pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> n;
	pcl::PointCloud<pcl::Normal>::Ptr normals(new pcl::PointCloud<pcl::Normal>);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
	tree->setInputCloud(cloud);
	n.setInputCloud(cloud);
	n.setSearchMethod(tree);
	n.setKSearch(20);
	n.compute(*normals);
	//* normals should not contain the point normals + surface curvatures

	// Concatenate the XYZ and normal fields*
	pcl::PointCloud<pcl::PointNormal>::Ptr cloud_with_normals(new pcl::PointCloud<pcl::PointNormal>);
	pcl::concatenateFields(*cloud, *normals, *cloud_with_normals);
	//* cloud_with_normals = cloud + normals

	// Create search tree*
	pcl::search::KdTree<pcl::PointNormal>::Ptr tree2(new pcl::search::KdTree<pcl::PointNormal>);
	tree2->setInputCloud(cloud_with_normals);

	// Initialize objects
	pcl::GreedyProjectionTriangulation<pcl::PointNormal> gp3;
	pcl::PolygonMesh triangles;

	// Set the maximum distance between connected points (maximum edge length)
	gp3.setSearchRadius(0.025);

	// Set typical values for the parameters
	gp3.setMu(2.5);
	gp3.setMaximumNearestNeighbors(100);
	gp3.setMaximumSurfaceAngle(M_PI / 4); // 45 degrees
	gp3.setMinimumAngle(M_PI / 18); // 10 degrees
	gp3.setMaximumAngle(2 * M_PI / 3); // 120 degrees
	gp3.setNormalConsistency(false);

	// Get result
	gp3.setInputCloud(cloud_with_normals);
	gp3.setSearchMethod(tree2);
	gp3.reconstruct(triangles);

	// Additional vertex information
	std::vector<int> parts = gp3.getPartIDs();
	std::vector<int> states = gp3.getPointStates();

	// Finish
	return (0);
}

CMakeLists.txt

cmake_minimum_required(VERSION 2.6 FATAL_ERROR)

project(pointcloud_mesh)

find_package(PCL 1.4 REQUIRED )
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(pcm pointcloudtomesh.cpp)
target_link_libraries(pcm ${PCL_LIBRARIES})

**in results flann directory not found and visual studio:**

![image](https://user-images.githubusercontent.com/39823863/91308865-8f284080-e7b8-11ea-864a-42109623949f.png)

**Comment by larshg** [comment]
Have you set the FLANN_ROOT environment variable?

**Comment by tonifds** [comment]
Yes already set

**Comment by larshg** [comment]
And have you verified this is the correct path?

**Comment by tonifds** [comment]
What should be the correct path?

**Comment by larshg** [comment]
Ohh, I just looked again:

It has found the two flann libraries and the include dir. FLANN_DIR is not relevant I think.


In VS you are trying to start the Build project, but thats just a helper project, not an exe that can be started.

Right click the PCM project and click "set as startup project".

Then see if it launches the program :)

**Comment by tonifds** [comment]
Hi, thank you it work

**Comment by larshg** [comment]
Closing as its not an issue in PCL :-)
