### ISSUE TITLE
[tutorials] All youtube embeds are note displayed

### ISSUE THREAD

**Issue by kbumsik** [PointCloudLibrary/pcl#4368]
The Youtube video embeds in Readthedocs.io tutorials https://pcl.readthedocs.io/projects/tutorials/en/latest/index.html are not displayed.

The non-exhaustive list of affected tutorial pages is:
* https://pcl.readthedocs.io/projects/tutorials/en/latest/voxel_grid.html
* https://pcl.readthedocs.io/projects/tutorials/en/latest/extract_indices.html
* https://pcl.readthedocs.io/projects/tutorials/en/latest/pcl_plotter.html

I tried Chrome, the new Edge, and Firefox but neither of them displays the video.

![image](https://user-images.githubusercontent.com/7823583/91660604-f70cbd00-eb11-11ea-832a-75fa989002d2.png)

The current youtube embed looks like this:
```
.. raw:: html
    
    <iframe width="480" height="270" src="http://www.youtube.com/embed/2Xgd67nkwzs" frameborder="0" allowfullscreen></iframe>
```
Compared to [the Readthedocs.org official documentation](https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html?highlight=screencast), the missing part is a `<div>` block but I am not sure  this will help.

```
.. raw:: html

    <div style="text-align: center; margin-bottom: 2em;">
    <iframe width="100%" height="350" src="https://www.youtube-nocookie.com/embed/oJsUvBQyHBs?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
```

**Comment by kunaltyagi** [comment]
> but I am not sure this will help

We can have a small PR to test this and revert it if it's not successful

**Comment by larshg** [comment]
I just had quick look and its because the links use http, which violates Mixed Content.
Changing the links to https solves it.
