### ISSUE TITLE
[CI/surface] Using default gcc (5) instead of gcc-7 causes compile failure in 3rd_party/poisson4

### ISSUE THREAD

**Issue by YouShaoze** [PointCloudLibrary/pcl#4372]
In Ubuntu 16.04， when i use make：
```
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:90: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 s=(StartingPolynomial<Degree>*)malloc(sizeof(StartingPolynomial<Degree>)*size);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:90: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In member function ‘pcl::poisson::PPolynomial<(Degree + Degree2)> pcl::poisson::PPolynomial<Degree>::operator*(const pcl::poisson::PPolynomial<Degree2>&) const’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:248:104: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 al<Degree+Degree2>*)malloc(sizeof(StartingPolynomial<Degree+Degree2>)*spCount);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In member function ‘pcl::poisson::PPolynomial<(Degree + 1)> pcl::poisson::PPolynomial<Degree>::MovingAverage(double)’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:401:97: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 Polynomial<Degree+1>*)malloc(sizeof(StartingPolynomial<Degree+1>)*polyCount*2);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In instantiation of ‘pcl::poisson::PPolynomial<Degree>::~PPolynomial() [with int Degree = 0]’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:379:19:   required from here
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:100:25: error: ‘free’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
       if(polyCount){free(polys);}
                         ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:483:13: note: ‘void free(void*)’ declared here, later in the translation unit
 extern void free (void *__ptr) __THROW;
             ^
In file included from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h:127:0,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:33,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In instantiation of ‘void pcl::poisson::PPolynomial<Degree>::set(std::size_t) [with int Degree = 0; std::size_t = long unsigned int]’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:380:14:   required from here
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:122:25: error: ‘free’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
       if(polyCount){free(polys);}
                         ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:483:13: note: ‘void free(void*)’ declared here, later in the translation unit
 extern void free (void *__ptr) __THROW;
             ^
In file included from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h:127:0,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:33,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:50: error: ‘malloc’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
         polys=(StartingPolynomial<Degree>*)malloc(sizeof(StartingPolynomial<Deg
                                                  ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:466:14: note: ‘void* malloc(size_t)’ declared here, later in the translation unit
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^
surface/CMakeFiles/pcl_surface.dir/build.make:446: recipe for target 'surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/bspline_data.cpp.o' failed
make[2]: *** [surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/bspline_data.cpp.o] Error 1
CMakeFiles/Makefile2:1259: recipe for target 'surface/CMakeFiles/pcl_surface.dir/all' failed
make[1]: *** [surface/CMakeFiles/pcl_surface.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kunaltyagi** [comment]
Please fill the format information that you deleted.

* PCL verison
* compiler version
* dependencies installed (and version)
* CMake config used to build PCL

**Comment by YouShaoze** [comment]
> Please fill the format information that you deleted.
> 
> * PCL verison
> * compiler version
> * dependencies installed (and version)
> * CMake config used to build PCL

 - OS:  Ubuntu 16.04
 - Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
                   cmake version 3.5.2
 - PCL Version [e.g. 1.11.1, HEAD]
 - PCL Type: Compiled from source

CMake config used to build PCL： default

dependencies installed (and version)：

sudo apt-get install cmake
sudo apt-get install g++  
sudo apt-get install libboost1.58-all-dev 
sudo apt-get install libeigen3-dev
sudo apt-get install libflann-dev
sudo apt-get install python
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install libudev-dev
sudo apt-get install freeglut3-dev
sudo apt-get install doxygen
sudo apt-get install graphviz
sudo apt-get install libpng12-dev
sudo apt-get install libgtest-dev
sudo apt-get install libxmu-dev
sudo apt-get install libxi-dev
sudo apt-get install libpcap-dev
sudo apt-get install libqhull-dev
sudo apt-get install libvtk5-qt4-dev
sudo apt-get install python-vtk

**Comment by kunaltyagi** [comment]
This seems to be a GCC issue. Our CI uses GCC 7.0 and this issue has apparently snuck in. In the meantime, please use GCC-7 via ubuntu's toolchain-r ppa

**Comment by YouShaoze** [comment]
> This seems to be a GCC issue. Our CI uses GCC 7.0 and this issue has apparently snuck in. In the meantime, please use GCC-7 via ubuntu's toolchain-r ppa

I update gcc to 7.3.0 and the problem still exist

[ 51%] Building CXX object surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/bspline_data.cpp.o
In file included from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h:127:0,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:33,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In member function ‘void pcl::poisson::PPolynomial<Degree>::set(std::size_t)’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:90: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 s=(StartingPolynomial<Degree>*)malloc(sizeof(StartingPolynomial<Degree>)*size);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:90: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In member function ‘pcl::poisson::PPolynomial<(Degree + Degree2)> pcl::poisson::PPolynomial<Degree>::operator*(const pcl::poisson::PPolynomial<Degree2>&) const’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:248:104: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 al<Degree+Degree2>*)malloc(sizeof(StartingPolynomial<Degree+Degree2>)*spCount);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In member function ‘pcl::poisson::PPolynomial<(Degree + 1)> pcl::poisson::PPolynomial<Degree>::MovingAverage(double)’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:401:97: error: there are no arguments to ‘malloc’ that depend on a template parameter, so a declaration of ‘malloc’ must be available [-fpermissive]
 Polynomial<Degree+1>*)malloc(sizeof(StartingPolynomial<Degree+1>)*polyCount*2);
                                                                              ^
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In instantiation of ‘pcl::poisson::PPolynomial<Degree>::~PPolynomial() [with int Degree = 0]’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:379:19:   required from here
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:100:25: error: ‘free’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
       if(polyCount){free(polys);}
                         ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:483:13: note: ‘void free(void*)’ declared here, later in the translation unit
 extern void free (void *__ptr) __THROW;
             ^
In file included from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h:127:0,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:33,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp: In instantiation of ‘void pcl::poisson::PPolynomial<Degree>::set(std::size_t) [with int Degree = 0; std::size_t = long unsigned int]’:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:380:14:   required from here
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:122:25: error: ‘free’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
       if(polyCount){free(polys);}
                         ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:483:13: note: ‘void free(void*)’ declared here, later in the translation unit
 extern void free (void *__ptr) __THROW;
             ^
In file included from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h:127:0,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:33,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp:127:50: error: ‘malloc’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
         polys=(StartingPolynomial<Degree>*)malloc(sizeof(StartingPolynomial<Deg
                                                  ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from /usr/include/c++/5/ext/string_conversions.h:41,
                 from /usr/include/c++/5/bits/basic_string.h:5249,
                 from /usr/include/c++/5/string:52,
                 from /usr/include/c++/5/stdexcept:39,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/poisson_exceptions.h:40,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.hpp:29,
                 from /home/ysz/depending/pcl/surface/include/pcl/surface/3rdparty/poisson4/bspline_data.h:149,
                 from /home/ysz/depending/pcl/surface/src/3rdparty/poisson4/bspline_data.cpp:37:
/usr/include/stdlib.h:466:14: note: ‘void* malloc(size_t)’ declared here, later in the translation unit
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^
surface/CMakeFiles/pcl_surface.dir/build.make:446: recipe for target 'surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/bspline_data.cpp.o' failed
make[2]: *** [surface/CMakeFiles/pcl_surface.dir/src/3rdparty/poisson4/bspline_data.cpp.o] Error 1
CMakeFiles/Makefile2:1259: recipe for target 'surface/CMakeFiles/pcl_surface.dir/all' failed
make[1]: *** [surface/CMakeFiles/pcl_surface.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by larshg** [comment]
`/usr/include/c++/5/cstdlib` This path, is this to GCC 5 og GCC 7 or is this not dependent on this? (5 vs 7)

**Comment by kunaltyagi** [comment]
The OS still might use GCC-5 as default. Please verify using `gcc --version`.
GCC-7 has no issues, as evident by the CI
