### ISSUE TITLE
[apps] Pointcloud editor fails to build when Qt5 is not found due to missing requirement enforcement

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4379]
I build PCL 1.11.0 with
```
cmake .. -DBUILD_apps=ON -DBUILD_apps_point_cloud_editor=ON
```
This fails at configure time because `Qt5::OpenGL`  is not found. But actually, it fails because Qt5 is not found at all (Homebrew does not link it to `/usr/local/` by default). This is confusing.

The `CMakeLists.txt`  includes
```
373 option(WITH_QT "Build QT Front-End" TRUE)
374 if(WITH_QT)
375   find_package(Qt5 COMPONENTS Concurrent OpenGL Widgets QUIET)
376 endif()
```
Which simply ignores when Qt is not found. Presumably, submodules which actually require it should enforce this themselves, but `point_cloud_editor`s cmake config does not, so i fails to build.

**Context**

Attempt to unsuccessfully configure `point_cloud_editor` due to missing Qt

**Expected behavior**

Configuring build should fail due to missing Qt5, not missing Qt5::OpenGL.

**Current Behavior**

Cmake complains that Qt5::OpenGL is not found.

**To Reproduce**

- cmake .. -DBUILD_apps=ON -DBUILD_apps_point_cloud_editor=ON
- error

**Your Environment (please complete the following information):**

 - OS: macos 10.14.6
 - Compiler: Apple Clang 11
 - PCL Version e.g. 1.11.0

**Possible Solution**

Modify `cmake/pcl_targets.cmake` around line 301 to error out if `Qt5_FOUND` is false.

**Additional context**

For me, the problem can be solved of course by 
```
cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.15.0/ -DBUILD_apps=ON -DBUILD_apps_point_cloud_editor=ON
```
and `brew unlink`ing `libomp` which otherwise produces linker errors.

**Comment by kunaltyagi** [comment]
PR is welcome 😄

**Comment by larshg** [comment]
It verifys that Qt5 is found here:
https://github.com/PointCloudLibrary/pcl/blob/d4312fcd3b7518f7931b8abe8303fa9c8f2264d0/apps/point_cloud_editor/CMakeLists.txt#L6-L12

Maybe it doesn't work correctly?

**Comment by larshg** [comment]
I don't think this is a bug, but hopefully #4767 enforces it better.
However, if Qt5_FOUND is set to true, and the target Qt::OpenGL or other targets that is used, is not defined for some reason, it would still produce errors.
