### ISSUE TITLE
visualizer setSize() and setPosition() failed

### ISSUE THREAD

**Issue by ciderpark** [PointCloudLibrary/pcl#4383]
PCL1.11 with vtk7.1 on Ubuntu 20.04, these two function crashed. Here is the output:
X Error of failed request:  GLXBadDrawable
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  11 (X_GLXSwapBuffers)
  Serial number of failed request:  1513
  Current serial number in output stream:  1513
Why did this happen? Wrong vtk version?Any solution here?

**Comment by mvieth** [comment]
I had this error in a different situation before. The solution there was to change the graphics driver (in the Software & Updates tool under Additional drivers).

**Comment by ciderpark** [comment]
> I had this error in a different situation before. The solution there was to change the graphics driver (in the Software & Updates tool under Additional drivers).

**Comment by ciderpark** [comment]
> I had this error in a different situation before. The solution there was to change the graphics driver (in the Software & Updates tool under Additional drivers).

Thanks for your reply. It doesn't work.
I was accidentally interrupted while updating my graphics driver and reinstall failed last month. So I removed it and installed another version successfully. It may caused by the graphics driver. Thanks anyway.

**Comment by mvieth** [comment]
What is the situation here? Do you still have this problem or can this issue be closed?
