### ISSUE TITLE
pcl/recognition/3rdparty/metslib/termination-criteria.hh against with qt-pclviewer

### ISSUE THREAD

**Issue by FENGZHANG123** [PointCloudLibrary/pcl#4386]
Hi,  I use pcl hv_go and qt-pclviewer seperately, everything is OK, but I combine hv_go with qt-pclviewer, following compilation error happened. I absolutely have no idea why this happened. Can you give me a hint about this bug, thank you. 

[ 92%] Building CXX object CMakeFiles/glue_robot_vision2.dir/src/pclviewer.cpp.o
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qwindowdefs.h:37:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmainwindow.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMainWindow:1,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/include/pclviewer.h:5,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/src/pclviewer.cpp:1:
/usr/include/pcl-1.9/pcl/recognition/3rdparty/metslib/termination-criteria.hh:231:9: error: expected identifier before ‘for’
   class forever : public termination_criteria_chain
         ^
/usr/include/pcl-1.9/pcl/recognition/3rdparty/metslib/termination-criteria.hh:231:9: error: expected unqualified-id before ‘for’
/usr/include/pcl-1.9/pcl/recognition/3rdparty/metslib/termination-criteria.hh:231:9: error: expected unqualified-id before ‘)’ token
   class forever : public termination_criteria_chain
         ^
In file included from /usr/include/boost/asio/handler_type.hpp:20:0,
                 from /usr/include/boost/asio/async_result.hpp:19,
                 from /usr/include/boost/asio.hpp:20,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/include/ftp_client.h:5,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/include/pipeline.h:9,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/include/pclviewer.h:22,
                 from /home/hrg/AWorkSpace/glue_robot_vision2/src/pclviewer.cpp:1:
/usr/include/boost/asio/detail/push_options.hpp:71:40: error: expected ‘}’ before end of line
/usr/include/boost/asio/detail/push_options.hpp:71:40: error: expected declaration before end of line

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 16.04]
 - PCL Version [ 1.9.1, HEAD]

**Comment by kunaltyagi** [comment]
Is the bug present in 1.11.1 or HEAD@master? If no, then you can run git-bisect to find the solution and close the issue.

Otherwise, we can take a deeper look at it

**Comment by FENGZHANG123** [comment]
It's 1.9.1 @kunaltyagi

**Comment by kunaltyagi** [comment]
I'm asking if the error is still in PCL or has it been resolved by some other PR

**Comment by FENGZHANG123** [comment]
I haven't found any similar error in historical issues.

**Comment by FENGZHANG123** [comment]
Hi，just delete following code at /pcl-pcl-1.9.1/recognition/include/pcl/recognition/3rdparty/metslib/termination-criteria.hh solve my problem.
//  class forever : public termination_criteria_chain
//  {
//  public:
//    forever() : termination_criteria_chain() {}
//    bool
//    operator()(const feasible_solution& /*fs*/)
//    { return false; }
//    void reset()
//    { termination_criteria_chain::reset(); }
//  };

**Comment by kunaltyagi** [comment]
Closing issue

PS: Commented code should not have any impact with a decent compiler
