### ISSUE TITLE
[pcl::VoxelGrid] Doesn't apply min_points_per_voxel_ in applyFilter for pcl::PCLPointCloud2

### ISSUE THREAD

**Issue by justinIRBT** [PointCloudLibrary/pcl#4388]
`pcl::VoxelGrid<pcl::PCLPointCloud2>::applyFilter (PCLPointCloud2 &output)`
doesn't use min_points_per_voxel_, so setMinimumPointsNumberPerVoxel has no effect
whereas
```
template <typename PointT> void
pcl::VoxelGrid<PointT>::applyFilter (PointCloud &output)
```
applies it correctly

**Context**

I was using pcl::VoxelGrid with ROS2, I used the following code to apply the filter:
```
void pcl_filter_pc2()
  {
      pcl::PCLPointCloud2::Ptr cloud_pcl(new pcl::PCLPointCloud2());
      pcl::PCLPointCloud2::Ptr cloud_filtered(new pcl::PCLPointCloud2());
      pcl_conversions::toPCL(m_msg_pointcloud, *cloud_pcl);
      pcl::VoxelGrid<pcl::PCLPointCloud2> vox_filt;
      vox_filt.setInputCloud(cloud_pcl);
      vox_filt.setFilterFieldName(m_voxel_filter_crop_axis);
      vox_filt.setFilterLimits(m_voxel_filter_min_axis, m_voxel_filter_max_axis);
      vox_filt.setDownsampleAllData(true);
      vox_filt.setLeafSize(m_voxel_filter_res, m_voxel_filter_res, m_voxel_filter_res);
      vox_filt.setMinimumPointsNumberPerVoxel(m_voxel_min_points);
      vox_filt.filter(*cloud_filtered);
      pcl_conversions::fromPCL(*cloud_filtered, m_msg_pointcloud);
  }
```
I noticed that no matter how high I set the setMinimumPointsNumberPerVoxel, the output was unchanged.
From code inspection, I see the implementation for the PCLPointCloud2 applyFilter case in 
https://github.com/PointCloudLibrary/pcl/blob/master/filters/src/voxel_grid.cpp doesn't use the variable min_points_per_voxel_.  I saw that it is applied in https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/impl/voxel_grid.hpp in the method
```
template <typename PointT> void
pcl::VoxelGrid<PointT>::applyFilter (PointCloud &output)
```
I then tried using the more indirect path (which has to go through a PCLPointCloud2 on the way to a pcl::PointXYZRGB and back through a PCLPointCloud2 on the way back to a ROS PointCloud2 message) to use the latter implementation with this function
```
void pcl_filter_pcxyz()
  {
      pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_pcl(new pcl::PointCloud<pcl::PointXYZRGB>());
      pcl::PointCloud<pcl::PointXYZRGB> cloud_filtered;
      pcl::fromROSMsg(m_msg_pointcloud, *cloud_pcl);
      pcl::VoxelGrid<pcl::PointXYZRGB> vox_filt;
      vox_filt.setInputCloud(cloud_pcl);
      vox_filt.setFilterFieldName(m_voxel_filter_crop_axis);
      vox_filt.setFilterLimits(m_voxel_filter_min_axis, m_voxel_filter_max_axis);
      vox_filt.setDownsampleAllData(true);
      vox_filt.setLeafSize(m_voxel_filter_res, m_voxel_filter_res, m_voxel_filter_res);
      vox_filt.setMinimumPointsNumberPerVoxel(m_voxel_min_points);
      vox_filt.filter(cloud_filtered);
      pcl::toROSMsg(cloud_filtered, m_msg_pointcloud);
  }
```
This approach worked as expected, applying the min points per voxel.
**Expected behavior**

`pcl::VoxelGrid<pcl::PCLPointCloud2>` should respect value set in setMinimumPointsNumberPerVoxel

**Current Behavior**

`pcl::VoxelGrid<pcl::PCLPointCloud2>` ignores setMinimumPointsNumberPerVoxel, unlike `pcl::VoxelGrid<pcl::PointXYZRGB>` which respects it

**To Reproduce**

Run filter setup in pcl_filter_pc2() above with artficial point cloud that puts points in a handful of voxels and very large setMinimumPointsNumberPerVoxel.  Will observe non-zero output points when no voxels should have satisfied the threshold.

**Screenshots/Code snippets**

**Your Environment (please complete the following information):**

 - OS: Raspbian Buster
 - Compiler: GCC 8.3
 - PCL Version 1.9 (also observed from code inspection on master)

**Possible Solution**

Use code block implementation in https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/impl/voxel_grid.hpp
(and resulting first_and_last_indices_vector later in the function)
```
  std::vector<std::pair<unsigned int, unsigned int> > first_and_last_indices_vector;
  // Worst case size
  first_and_last_indices_vector.reserve (index_vector.size ());
  while (index < index_vector.size ()) 
  {
    unsigned int i = index + 1;
    while (i < index_vector.size () && index_vector[i].idx == index_vector[index].idx) 
      ++i;
    if (i - index >= min_points_per_voxel_)
    {
      ++total;
      first_and_last_indices_vector.emplace_back(index, i);
    }
    index = i;
  }
```
instead of block in https://github.com/PointCloudLibrary/pcl/blob/master/filters/src/voxel_grid.cpp
```
while (index < index_vector.size ()) 
  {
    std::size_t i = index + 1;
    while (i < index_vector.size () && index_vector[i].idx == index_vector[index].idx) 
      ++i;
    ++total;
    index = i;
  }
```

**Comment by kunaltyagi** [comment]
Please go ahead with a PR and a test case which shows the current code failing

**Comment by justinIRBT** [comment]
Fixed in PR https://github.com/PointCloudLibrary/pcl/pull/4389

**Comment by nickvaras** [comment]
Can this be merged?
