### ISSUE TITLE
Point cloud and 3D CAD object matching

### ISSUE THREAD

**Issue by vinayakabhatkale** [PointCloudLibrary/pcl#4401]
Hello,
I am new to the field of point clouds.

I would like to know about an approach to match 3D CAD object and it's point cloud.

After doing some research i understood ICP would be a feasible algorithm to do this.

Kindly let me know if ICP would be good enough to do this or we should carry out both PCA and ICP (coarse and fine) .

Also let me know about how to do type conversion from 3D CAD file and Point cloud file.

Thank you!

**Comment by kunaltyagi** [comment]
Please use GitHub for issues only. Use discord for talking with other community members of PCL and StackOverflow for asking programming-bug/issue questions that discord and GitHub aren't suitable for.
