### ISSUE TITLE
Lost visualization module after installed by vcpkg

### ISSUE THREAD

**Issue by Erixar** [PointCloudLibrary/pcl#4403]
I installed pcl by vcpkg, when i'm testing pcl on VS2019 it showed

 “pcl/visualization/cloud_viewer.h”: No such file or directory	Project1“

and the visualization folder do no exist in C:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\pcl

**Comment by larshg** [comment]
VCPKG has disabled the visualization module, as we doesn't support VTK9 yet.

You can use CMake to  build PCL from source, if you install VTK9 as well and use this pr #4262.

**Comment by Erixar** [comment]
> VCPKG has disabled the visualization module, as we doesn't support VTK9 yet.
> 
> You can use CMake to build PCL from source, if you install VTK9 as well and use this pr #4262.
THX for your comment.It's really helpful for me.
