### ISSUE TITLE
[Visualizer] "How to get orthogonal view along X/Y/Z axis in a code?"

### ISSUE THREAD

**Issue by hduonggithub** [PointCloudLibrary/pcl#4405]
**Is your feature request related to a problem? Please describe.**

I have 3D point cloud of an object and would like to visualize it as 2D orthogonal View along 
  + X axis (YZ plane), 
  + Y axis (XZ plane), 
  + Z axis (YZ plane) 

in PCLVisualizer or in other modules? What should I do to get it? Please advise. Thanks!

**Comment by kunaltyagi** [comment]
Can't you just project along 3 planes: (a, b, c, 0) (with only one of a, b, c being 1 and the rest 0) and using `ProjectInliers`?

PS: Closing issue since it's not related to the core library. Please ask questions on discord (chat/discussion) or StackOverflow (pointed questions/bugs in user-code)

**Comment by hduonggithub** [comment]
Thanks @kunaltyagi 

I give it a try !
