### ISSUE TITLE
3rd party include file in pcl_recognition missing if pkg-config not available

### ISSUE THREAD

**Issue by magro11** [PointCloudLibrary/pcl#441]
Hello together,

I opened this issue due to the former discussion at pcl-users.org:

http://www.pcl-users.org/3rd-party-include-file-in-pcl-recognition-missing-if-pkg-config-not-available-td4031656.html

On Windows PC it is not common, that the tool pkg-config is available. Therefore no information about availibility of the library Metslab is obtained. nizar_sallem already suggested to create a specific FindMetslib.cmake file, that searches for this library with or without the optional tool pkg-config.

In the current trunk, the is an include directory to ${PCL_SOURCE_DIR}/recognition/include/pcl/recognition/3rdparty/ missing (in pcl_recognition) if pkg-config could not be found.

Cheers
Marc

**Comment by taketwo** [comment]
Closing since this is most likely obsolete. Sorry for the lack of attention from the maintainers.
