### ISSUE TITLE
error LNK2001: pcl::PLYReader::read()

### ISSUE THREAD

**Issue by old-beginner** [PointCloudLibrary/pcl#4423]
Hi,
I’m stack with my “Hello, World” using PCL:

#include <iostream>
#include <stdio.h>
#include <pcl/point_types.h>
#include <pcl/features/fpfh.h>
#include <pcl/io/pcd_io.h>
#include <pcl/point_cloud.h>
#include <pcl/io/ply_io.h>
#include <pcl/console/print.h>
//
int main()
{
pcl::PointCloud<pcl::PointNormal>::Ptr  cloud(new pcl::PointCloud<pcl::PointNormal>);
if (pcl::io::loadPLYFile<pcl::PointNormal>("Elbow.ply", *cloud) == -1)
printf("error ...\n");
return 0;
}
I got PCL by downloading PCL-1.11.1-AllInOne-msvc2019-win64.exe from https://github.com/PointCloudLibrary/pcl/releases , 
used VC2019, in Configuration Properties ->C/C++ -> General -> Additional Include Directories pointed to 
..\ PCL 1.11.1\include\pcl-1.11 
..\ PCL 1.11.1\3rdParty\Boost\include\boost-1_74 
..\ PCL 1.11.1\3rdParty\FLANN\include 
..\ PCL 1.11.1\3rdParty\Eigen\eigen3
and in Configuration Properties ->Linker->General->Additional Library Directories pointed to 
..\ PCL 1.11.1\lib
..\ PCL 1.11.1\3rdParty\Boost\lib
..\ PCL 1.11.1\3rdParty\FLANN\lib
and tried to build Release x64.

Got first this
1>main.cpp
1>C:\MyStuff\pcl_0\PCL 1.11.1\3rdParty\Boost\include\boost1_74\boost\function_output_iterator.hpp(14): message : This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.
1>C:\MyStuff\pcl_0\PCL 1.11.1\include\pcl-1.11\pcl\io\low_level_io.h(73,16): error C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\MyStuff\pcl_0\PCL 1.11.1\include\pcl-1.11\pcl\io\low_level_io.h(78,16): error C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. 

I silenced complier by disabling deprecation in Configuration Properties ->C/C++ -> Advanced -> Disable Specific Warnings
and got linker errors

1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl pcl::PLYReader::read(.....)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl pcl::PLYReader::readHeader(.....)
 
1>main.obj : error LNK2001: unresolved external symbol "void __cdecl pcl::console::print(.....)

Now – begging for help.
Old Beginner

**Comment by larshg** [comment]
Compiler warnings doesn't block you from getting things running.

However, you are probably missing to add the libraries that your application should link to, ie:
Configuration Properties ->Linker->Input->additional dependencies

You'll need to add something like:
common.lib
io.lib

And then all of the required external libraries, like:
boost_filesystem-vc140-mt.lib
boost_*

And so on, until you have no linking errors.

**Comment by old-beginner** [comment]
Thanks a lot. 

The program build/linked but when I tried to run, got err msg, see attached. In ..\PCL 1.11.1\3rdParty\OpenNI2 there is only one file OpenNI-Windows-x64-2.2.msi. I clicked, installer open, "Repair" was preselected and "Next" was grey out. Hit "Repair", then "Repair" on next screen, installer started doing/copying something (no log/info to user) and it finished (see sequence in attached 3 screenshots). I'm not sure what "Reinstalling" from err msg means, just rebuild the whole solution, got 74 warnings but program compiled/linked - and the same run time error as before.

![ErrMsg_screenshot](https://user-images.githubusercontent.com/71858575/94289575-e5f37800-ff26-11ea-898c-1a0594c3b9d6.png)
![OpenNi_Installer_screen1](https://user-images.githubusercontent.com/71858575/94289576-e5f37800-ff26-11ea-888b-19fc040e9106.png)
![OpenNi_Installer_screen2](https://user-images.githubusercontent.com/71858575/94289577-e5f37800-ff26-11ea-9eac-40dd38f1fd30.png)
![OpenNi_Installer_screen3](https://user-images.githubusercontent.com/71858575/94289572-e5f37800-ff26-11ea-99d3-276da9b660f0.png)

**Comment by larshg** [comment]
You can do either of two things:

1) Add the paths of the required dlls to the environment path variable (this might lead, to it being too long)

2) Alternatively you can find the required dlls and copy them next to your exe (ie. debug/release folder).
Remember to pick the corresponding versions that match, release to release. If there are some which only are release version, you can try copy those.

**Comment by larshg** [comment]
I'll close this. As its for bugs in PCL. This is setup of environment etc. Please use Discord/Stackoverflow for such questions.
