### ISSUE TITLE
ntdll.dll: 0xc0000139) 'Entry Point Not Found'

### ISSUE THREAD

**Issue by Ingsayyad** [PointCloudLibrary/pcl#4444]
Trying to write this simple program and getting error below:
I am getting problem with
    pcl::SACSegmentation<pcl::PointXYZ> seg;
Any idea?

------------------------------------------------------------------------------------------

#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/sample_consensus/method_types.h>
#include <pcl/sample_consensus/model_types.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/extract_indices.h>
**#include <iostream>**
using namespace std;
int main (int argc, char** argv)
{
   
    pcl::SACSegmentation<pcl::PointXYZ> seg;
   
	cout << "Segmentation" << endl;
  return (0);
}

----------------------------------------------------------------------------

_**I do not know why code is not showing **#include< iostream>**, but I added it already in code.**_
Error:

'planar_segmentation.exe' (Win32): Loaded 'E:\VCPKG\PCL_Solutions\Planedetection\Build\Debug\pcl_sample_consensusd.dll'. Symbols loaded.
'planar_segmentation.exe' (Win32): Loaded 'E:\VCPKG\PCL_Solutions\Planedetection\Build\Debug\pcl_commond.dll'. Symbols loaded.
'planar_segmentation.exe' (Win32): Loaded 'E:\VCPKG\PCL_Solutions\Planedetection\Build\Debug\lz4d.dll'. Symbols loaded.
Exception thrown at 0x00007FFEDCAFBF18 (ntdll.dll) in planar_segmentation.exe: 0xC0000139: Entry Point Not Found.
The thread 0x11678 has exited with code -1073741511 (0xc0000139).
The program '[71284] planar_segmentation.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.

**Comment by JStech** [comment]
The bare `#include` with no header definitely looks wrong.

**Comment by Ingsayyad** [comment]
I do not know why code is not showing #include< iostream>, but I added it already in code.

**Comment by larshg** [comment]
Have you installed all dependencies with x86 architecture?

And are you launching the program in debug mode?

**Comment by larshg** [comment]
This seems like a configuration issue and not an issue in PCL so I'll close it.
Please ask for help on Discord.
