### ISSUE TITLE
Reference PCL using VCPKG , Eigen missing

### ISSUE THREAD

**Issue by 9and3** [PointCloudLibrary/pcl#4456]
Hi,

I have installed PCL using vcpkg:
`.\vcpkg install pcl:x64-windows` and `.\vcpkg integrate install`

And I am trying just to reference any pcl header file for C++ 64 bit Console Application.
But the compiler cannot find Eigen.
The VCPKG shows that I installed the 64 bit version of Eigen.
I just want to see if I can build a console application by referencing any PCL header file and that it is recognized by Visual Studio.

I attached the screenshot below:
![image](https://user-images.githubusercontent.com/50238678/96630560-7ac67700-1315-11eb-977f-e7594670fe24.png)

How I can properly reference Eigen?

**Comment by larshg** [comment]
Did you solve this?
