### ISSUE TITLE
All in one Installer - CMake - 1.9.1 x64 Windows

### ISSUE THREAD

**Issue by petrasvestartas** [PointCloudLibrary/pcl#4457]
Hi,

I have installed 1.9.1 64 bit All in one installer.

I would like to ask how can I generate project using CMAKE?
Why CMAKE cannot find PCL and how can I generate simplest project file for Visual Studio 2017 ?
(I already tried VCPKG installation but it failed so I would like to do it through All in one installer)

What I did so far:

- Installed All in one installer 1.9.1 x64 Windows
- Added environmental variables and restarted windows computer
- Create a folder "C:\libs\PCL\build" where I made two files: 
-    CMakeLists (Attached)
-    main.cpp
-  Ignore the message below and build the project.
-   In main.cpp I tried to reference any PCL header. But I get error that Boost is not found:

![Question2](https://user-images.githubusercontent.com/18013985/96697979-dc75f800-138c-11eb-965f-eab08d39e33d.png)

[CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/files/5414561/CMakeLists.txt)

During CMake configure I get warning message:
![Qi](https://user-images.githubusercontent.com/18013985/96698318-4393ac80-138d-11eb-8700-3ddeb644cf4b.png)

![Question](https://user-images.githubusercontent.com/18013985/96697119-d4698880-138b-11eb-9758-29118e00e503.png)

**Comment by JoeDurand3** [comment]
I've had issues compiling 1.9.1 with VS2017. You might try PCL 1.8.1 instead.

**Comment by petrasvestartas** [comment]
Only stable way is 1.11.1 version

https://github.com/PointCloudLibrary/pcl/issues/4457
