### ISSUE TITLE
PCL: the code execution cannot proceed because vtkRenderingLOD-8.2-gd.dll was not found. Reinstalling the program may fix this problem

### ISSUE THREAD

**Issue by 9and3** [PointCloudLibrary/pcl#4458]
Hello there,

I managed to install PCL on my Windows 10 with all-in-one-installer (latest release). I was able to create a .sln (VS2019) from CMake-Gui. To give it a try I build the solution for the tutorial example cloud visualizer [https://pcl.readthedocs.io/projects/tutorials/en/latest/cloud_viewer.html#cloud-viewer](url), 
everything fine. But when I try to debug the solution I got these multiple error messages (please see attached screen-shot).

Does anyone has an idea? Thanks in advance!

![problemPCL](https://user-images.githubusercontent.com/50238678/96871002-f9382b80-1471-11eb-86ba-83b597385790.PNG)

"the code execution cannot proceed because vtkRenderingLOD-8.2-gd.dll was not found. Reinstalling the program may fix this problem" (among other .dll missing errors)

**Comment by larshg** [comment]
You need to copy the dlls from the all-in-one installer or add the path to the bin folder to the path enviromentvariable, for the exe to pick up the dlls.

**Comment by 9and3** [comment]
Thank you @larshg  for your answer! could you please expand on how to add the path to the bin folder. I am definitely missing something because I do not have a bin folder in my folder. Any idea? And sorry for the naivety 

![noBin](https://user-images.githubusercontent.com/50238678/96887701-20e4bf00-1485-11eb-8672-80c132c5d8fe.PNG)

**Comment by larshg** [comment]
Its the installation folder of pcl - which could be c:\program files\pcl\bin - I don't use the all-in-one installer, so I don't know the exact path.
Could also be various to where its installed, but you need to find the boost, vtk and pcl dlls etc.
![image](https://user-images.githubusercontent.com/1165340/97035938-59f56000-1567-11eb-90c7-36221b7d3cc8.png)

This is the path environment variable that need the path - hope you can figure out how to get there?

**Comment by larshg** [comment]
You can also see #4462

**Comment by 9and3** [comment]
Amazing! Thanks for the patience and time, it works perfectly.
