### ISSUE TITLE
[IO] HDL grabber will never return from stop() if data is not being received

### ISSUE THREAD

**Issue by stevenB-MF** [PointCloudLibrary/pcl#4460]
**Describe the bug**

When calling call "stop()" on an HDL_Grabber opened on an UDP port which is not receiving data, the call will freeze and never return, making it impossible to stop or delete the grabber. The stop function seems to be waiting on the hdl_read_packet_thread_ thread to join, which itself is waiting in a blocking receive_from call on the socket. receive_from never returns as data is not received on the socket, causing the function to hang forever.

**To Reproduce**

Create an HDL_Grabber (we're using the VLPGrabber, but any class using the start/stop code from HDL_Grabber should have the same behaviour) with a valid IP + a port which isn't receiving any network traffic. Call start, then stop on the grabber. It should freeze on the stop call.

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: VS 2019
 - PCL Version 1.11.0

**Comment by kunaltyagi** [comment]
Note: (Without looking at the code) This would need async with stop token support.

**Comment by larshg** [comment]
Should be fixed by #5826
