### ISSUE TITLE
Compressing and decompressing a point cloud

### ISSUE THREAD

**Issue by FrancescoMandru** [PointCloudLibrary/pcl#4461]
Suppose i want to compress a point cloud from KITTI dataset with your library, I read that it is possible but I don't know what I need to do to accomplish this task. Let's say that i have a .ply file and I want to compress and decompress it, what I have to do in detail? 

Thank you in advance!

**Comment by mvieth** [comment]
Do you mean creating a compressed file that has a smaller size? PLY files AFAIK do not have a compressed mode, but if it is originally in ASCII and you save it in binary, it should be smaller. Another option would be PCD files, which have a binary compressed option.

**Comment by FrancescoMandru** [comment]
@mvieth I wonder if there are some compression techniques that are built inside this library, just for example (GPCC or other compression techniques)

**Comment by mvieth** [comment]
Have you seen this tutorial yet: https://pcl.readthedocs.io/projects/tutorials/en/latest/compression.html
These two classes might help you: https://pointclouds.org/documentation/classpcl_1_1io_1_1_organized_point_cloud_compression.html and https://pointclouds.org/documentation/classpcl_1_1io_1_1_octree_point_cloud_compression.html
It is difficult to point you to a specific function or class without knowing what exactly you are trying to accomplish or what your use-case is.
