### ISSUE TITLE
[Filters] Wrong computation in VoxelGridCovariance

### ISSUE THREAD

**Issue by zxd123** [PointCloudLibrary/pcl#4463]
Hi! There is a bug in the pcl/filters/include/pcl/filters/impl/voxel_grid_covariance.hpp line 327
The code is `leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points;`.But according to the formula it should be
`leaf.cov_ *=  leaf.nr_points / (leaf.nr_points - 1.0);`
But it doesn't seem to matter much.

**Comment by mvieth** [comment]
So the fraction should be inverted?

> But according to the formula it should be

What formula are you referring to?

**Comment by zxd123** [comment]
> So the fraction should be inverted?
> 
> > But according to the formula it should be
> 
> What formula are you referring to?
@mvieth In the formula 6.3 of the paper [The Three-Dimensional Normal-Distributions Transform --- an Efficient Representation for Registration, Surface Analysis, and Loop Detection](https://www.researchgate.net/publication/229213868_The_Three-Dimensional_Normal-Distributions_Transform_---_an_Efficient_Representation_for_Registration_Surface_Analysis_and_Loop_Detection?enrichId=rgreq-6c46a67079d4614a3ada267b7866b6f6-XXX&enrichSource=Y292ZXJQYWdlOzIyOTIxMzg2ODtBUzoxMDExNjY0MzYzMjMzMzFAMTQwMTEzMTM2NjU0OA%3D%3D&el=1_x_3&_esc=publicationCoverPdf)，
![6 3](https://user-images.githubusercontent.com/22142312/97130122-74a02280-177b-11eb-9f09-45849652d504.jpg)
the denominator should be m-1, which is `(leaf.nr_points - 1.0)` ，so the fraction should be inverted. Thank you for your reply.

**Comment by mvieth** [comment]
@zxd123 thank you for posting this issue :smile:

I find it a bit suspicious that the person who wrote this code made this rather obvious mistake, but I can't find any reason behind it, so I guess it really must be a mistake.

When correcting the mistake, it may make sense to replace the lines 326 and 327 with this formula, which is a bit simpler:
`(leaf.cov_ - 2.0 * (pt_sum * leaf.mean_.transpose ()) + leaf.nr_points * leaf.mean_ * leaf.mean_.transpose ()) / (leaf.nr_points - 1.0)`

**Comment by zxd123** [comment]
@mvieth Yes, if the code is modified this way it will be cleaner, correct and easy to understand, hope this problem can be corrected as soon as possible. Thank you for your reply.

**Comment by mvieth** [comment]
If you like, maybe you can correct it and then create a pull request?

**Comment by zxd123** [comment]
@mvieth I'm sorry, I'm a beginner on GitHub, so these basic operations are not good enough, can you help correct them?

**Comment by mvieth** [comment]
If you don't know how to create a pull request, maybe an article like [this one](https://careerkarma.com/blog/git-pull-request/) can help you.
If you still feel that you don't now how to do that or don't have the time or anything, that is totally okay. Then I or someone else will correct this bug.

**Comment by zxd123** [comment]
@mvieth  Thank you for your article, but I still think it would be better if you or someone else corrected the mistake. 😄
