### ISSUE TITLE
How to display the debug info in console?

### ISSUE THREAD

**Issue by Micalson** [PointCloudLibrary/pcl#4475]
Hello, thank you for your nice code.
I have a question in debugging pcl source code. There are many places using "pcl::console::print (pcl::console::L_DEBUG, __VA_ARGS__)", but I could see nothing in cosole. How to display the debug info? (any macro definition?)
Thank you for your reply.

Regards,

**Comment by mvieth** [comment]
If you add this command to the start of your program, PCL will show all debug/logging:  `pcl::console::setVerbosityLevel(pcl::console::L_VERBOSE);`. [Here is the documentation](https://pointclouds.org/documentation/namespacepcl_1_1console.html#a1c1202ab693383b98842cb4f72ae625c).

**Comment by Micalson** [comment]
Thank you for your reply. I will try it.

**Comment by kunaltyagi** [comment]
If you wish to not modify your code (for any reason), you can also use environment variables to achieve the same result.

`PCL_VERBOSITY_LEVEL` can be `ALWAYS`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `VERBOSE` as and when needed.

There's another variable that might be helpful if you're using some other facility to log your logs: `PCL_CLICOLOR_FORCE`. If it's set to any valid string, it'll force the output to always be colored.

PS: Please close this issue once you're satisfied with the answers

**Comment by Micalson** [comment]
It's a nice answer. Thank you for your reply.
