### ISSUE TITLE
[CI] New CI for Ubuntu 20.10?

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#4478]
Now that Ubuntu 20.10 ("Groovy Gorilla") has been released, should we create a CI stage for it?

**Comment by kunaltyagi** [comment]
Created a PR for the docker image. Perhaps, we should convert the 20.04 CI into the 20.10 CI? It keeps 1 CI on an old LTS (18.04) and a CI tracking the latest changes (20.10)

**Comment by mvieth** [comment]
> Created a PR for the docker image. Perhaps, we should convert the 20.04 CI into the 20.10 CI? It keeps 1 CI on an old LTS (18.04) and a CI tracking the latest changes (20.10)

Hm, on the one hand, we shouldn't have too many CIs running, so converting one would make sense, but on the other hand, supporting the LTS versions is especially important. What about the 16.04 CI? How long will that be running?

**Comment by kunaltyagi** [comment]
Point. I forgot 16.04 was alive. Let's replace that since 1.11.1 is released and there's no 1.11.2 possible.

**Comment by mvieth** [comment]
Some jobs (documentation, tutorials, and others) seem to use 16.04 docker images, perhaps we should change that too?

**Comment by kunaltyagi** [comment]
#4509 should take care of these
