### ISSUE TITLE
[custom] Cloud fragments reconstruction

### ISSUE THREAD

**Issue by 9and3** [PointCloudLibrary/pcl#4485]
Hello PCL user!

I am aware that this is not really the best place to ask but I'll give it a shot anyway, pardon me.

I am trying to register two point clouds of the same object with PCL (C++, VS2019). I am a bit stuck and I was wondering if someone has an idea on how to solve my problem. I have these two point clouds, two fragment sides of the same object (flipped on one side). I am trying to properly register the two sides in one merged cloud, without any success. ICP and Ransac doesn't

 seem to work. They partially overlap and the idea is to "stitch" the two PC fragments together.

Any idea? Thanks in advance people:)

In yellow the representation of my failure as a programmer: PCL  doesn't overlap properly the two point clouds.
![tryouthhh](https://user-images.githubusercontent.com/50238678/97996197-c41fc780-1de7-11eb-8e94-f3f4a1b5560a.PNG)

Please find attached here the pcd files I am working with.

[Debug.zip](https://github.com/PointCloudLibrary/pcl/files/5481794/Debug.zip)

**Comment by larshg** [comment]
Just a thought, can you somehow take a snapshot of the item from the side? If there are too few points matching in both clouds it would be close to impossible to do icp/registration of the clouds.

Now if you have 3 or more shots of your item, you can probably get it to merge them all together.

**Comment by 9and3** [comment]
Hello @larshg , thanks for your commentary. What you are suggesting sounds good, so at least I should have 3 scans of the same object. 
The thing here is that already these two scans have some common overlapping sides (see gif), I wonder if that would be enough with the "pairwise registration" you suggested (even though it seems to fit more well-aligned point clouds from the start), I'll give it a shot.

![a3b311964cbc1dfb0fde5e310a3520b5](https://user-images.githubusercontent.com/50238678/98044438-2a780a80-1e27-11eb-82c3-f2061797e069.gif)

**Comment by larshg** [comment]
@9and3 Got any luck? Mind if I close this one?

**Comment by 9and3** [comment]
Hello @larshg, I am still working on a good solution, for now I am mixing RANSAC and ICP, but I will be glad to post my solution on the discord channel as soon as I got one. Thanks for asking by the way.

**Comment by mvieth** [comment]
I'm closing this issue since there isn't much activity here, and you already got some suggestions. If you have any results/methods that others might be interested in, feel free to post them here and/or on discord.
