### ISSUE TITLE
[io]  loadPolygonFilePLY segfaults when file does not exist

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4487]
This code
```
  PolygonMesh wat;
  io::loadPolygonFilePLY("n/a", wat);

```

produces a segfault in PCL 1.11.1, so there is no way to recover from the case that the file does not exist.

Some stuff is printed to console:
```
Warning: In /tmp/vtk@8.2-20200909-79228-1qm7d8t/VTK-8.2.0/IO/PLY/vtkPLYReader.cxx, line 132
vtkPLYReader (0x7ff83dc1a3f0): Could not open PLY file

ERROR: In /tmp/vtk@8.2-20200909-79228-1qm7d8t/VTK-8.2.0/Common/ExecutionModel/vtkExecutive.cxx, line 782
vtkCompositeDataPipeline (0x7ff83dc1aa70): Algorithm vtkPLYReader(0x7ff83dc1a3f0) returned failure for request: vtkInformation (0x7ff83dc1b3b0)
  Debug: Off
  Modified Time: 118
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0

Segmentation fault: 11
```

**System:**

- osx 10.15
- PCL 1.11.1
- vtk 8.2

**Comment by mvieth** [comment]
Hm, [`loadPolygonFilePLY`](https://github.com/PointCloudLibrary/pcl/blob/09f705ec40704bf119a3e585b34ca87ebb3316dd/io/src/vtk_lib_io.cpp#L115) looks unsuspicious, maybe the segfault happens in [`vtk2mesh`](https://github.com/PointCloudLibrary/pcl/blob/09f705ec40704bf119a3e585b34ca87ebb3316dd/io/src/vtk_lib_io.cpp#L236). Is it possible that you debug your program, e.g. with valgrind, to find out where the segfault happens exactly?
