### ISSUE TITLE
"pcl/point_types.h: No such file or directory" BUT no compilation error appears and the program works.

### ISSUE THREAD

**Issue by wgu93** [PointCloudLibrary/pcl#4498]
Hello all,

I am using PCL library on Ubuntu 16.04 with ROS Kinetic. I followed the installation instructions given by [here](https://pcl-tutorials.readthedocs.io/en/latest/compiling_pcl_posix.html) and tested my very first program following the official tutorials. Everything seems perfect except one strange thing: In QT Creator, the included header files (all the pcl headers, not limited to pcl/point_types.h) are with underlines in yellow. When I put my mouse on it, it shows "pcl/point_types.h: No such file or directory". However, the program passed compilation and actually worked. I double checked the CMakeList file for the PCL directory and I confirmed that the actual installation directory (i.e., /usr/include/pcl-1.7) has been included and all the required header files are contained therein. 

I am quite confused about this situation because the auto fill feature is disabled and I cannot access the header file directly in the QT Creator, despite the fact that the code seems to work every time (no compilation error and correct results are shown). Does anyone who faced the same issue with me? Thank you for any suggestion or help!

P.S. When I include pcl_ros headers, there is no such issue.

**Comment by kunaltyagi** [comment]
Closing since this isn't an issue with PCL. Please prefer Discord for informal discussions
