### ISSUE TITLE
The local reference frame is not valid! Aborting description of point with index

### ISSUE THREAD

**Issue by MrCrazyCrab** [PointCloudLibrary/pcl#4499]
**Your Environment (please complete the following information):**

 - OS: [e.g. windows10]
 - Compiler: [:eg VS2017]
 - PCL Version [e.g. 1.9.1, HEAD] 
 - PCL Type: [Installed]

i want to calculate the SHOT, and i do it as follows:
`	string path = "lower.pcd";//for test	

	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile<pcl::PointXYZ>(path, *cloud); 
	cout << "Loaded " << cloud->points.size() << " points." << std::endl;
	pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normalEstimation;
	normalEstimation.setInputCloud(cloud);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
	normalEstimation.setSearchMethod(tree);
	pcl::PointCloud<pcl::Normal>::Ptr cloudWithNormals(new pcl::PointCloud<pcl::Normal>);
	normalEstimation.setKSearch(10);
	normalEstimation.compute(*cloudWithNormals);	
	pcl::PointCloud<pcl::SHOT352>::Ptr descriptors(new pcl::PointCloud<pcl::SHOT352>);
	pcl::SHOTEstimation<pcl::PointXYZ, pcl::Normal, pcl::SHOT352, pcl::ReferenceFrame> shotEstimation;
	shotEstimation.setInputCloud(cloud);
	shotEstimation.setInputNormals(cloudWithNormals);
	// Use the same KdTree from the normal estimation
	//shotEstimation.setSearchMethod(tree);
	//shotEstimation.setKSearch(10);
	shotEstimation.setRadiusSearch(0.03);

	shotEstimation.compute(*descriptors);
	std::cout << "SHOT output points.size (): " << descriptors->points.size() << std::endl;`

and i met the problem "The local reference frame is not valid! Aborting description of point with index", how should i solve it ?

**Comment by JStech** [comment]
Bit of a wild guess, but maybe you need to call [setInputReferenceFrames](https://pointclouds.org/documentation/classpcl_1_1_feature_with_local_reference_frames.html#a88e05490c1db062dda72504d2e64fd63)?

**Comment by MrCrazyCrab** [comment]
@JStech thanks for you advice, i'm new for the PCL. How should i define a ReferenceFrames for the compute?

**Comment by JStech** [comment]
I don't know--I've never used this particular function myself.

Maybe [this example](https://github.com/daviddoria/Examples/blob/master/c%2B%2B/PCL/Descriptors/SHOT/SHOT.cpp) could help?

**Comment by MrCrazyCrab** [comment]
@JStech i have tried this before, and there is a error in line36 which is "namespace pcl don't have SHOT"
(⊙_⊙)?

**Comment by kunaltyagi** [comment]
PCL has SHOT352 and SHOT1344 types instead of the old SHOT type

**Comment by mvieth** [comment]
This question seems sufficiently answered - feel free to reopen this issue if you still have problems with this.
