### ISSUE TITLE
there are many erros (pcl1.11.0 allinone vs2019 win64,vs2019 x64)

### ISSUE THREAD

**Issue by guyuezuntinggithub** [PointCloudLibrary/pcl#4504]
**Describe the error**

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2678	二进制“+”: 没有找到接受“const wchar_t [8]”类型的左操作数的运算符(或没有可接受的转换)	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	64	
错误	C2116	“boost::interprocess::winapi::CreateDirectoryA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	59	
错误	C2733	“CreateDirectoryA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	59	
错误	C2116	“boost::interprocess::winapi::CreateFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	87	
错误	C2733	“CreateFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	87	
错误	C2116	“boost::interprocess::winapi::FindFirstFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	233	
错误	C2733	“FindFirstFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	233	
错误	C2116	“boost::interprocess::winapi::FindNextFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	322	
错误	C2733	“FindNextFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	322	
错误	C2116	“boost::interprocess::winapi::GetFileInformationByHandle”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	651	
错误	C2733	“GetFileInformationByHandle”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	651	
错误	C2116	“boost::interprocess::winapi::GetFileSizeEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	681	
错误	C2733	“GetFileSizeEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	681	
错误	C2371	“boost::interprocess::winapi::GetFileType”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	690	
错误	C2733	“GetFileType”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	690	
错误	C2116	“boost::interprocess::winapi::LockFileEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	984	
错误	C2733	“LockFileEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	984	
错误	C2116	“boost::interprocess::winapi::ReadFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1024	
错误	C2733	“ReadFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1024	
错误	C2116	“boost::interprocess::winapi::SetFilePointerEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1150	
错误	C2733	“SetFilePointerEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1150	
错误	C2116	“boost::interprocess::winapi::UnlockFileEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1209	
错误	C2733	“UnlockFileEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1209	
错误	C2116	“boost::interprocess::winapi::WriteFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1221	
错误	C2733	“WriteFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1221	
错误	C2371	“boost::interprocess::winapi::GetTempPathA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1462	
错误	C2733	“GetTempPathA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1462	
错误	C2116	“boost::interprocess::winapi::CreateMutexA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h	428	
错误	C2733	“CreateMutexA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h	428	
错误	C2116	“boost::interprocess::winapi::GetProcessTimes”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h	106	
错误	C2733	“GetProcessTimes”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h	106	
错误	C2116	“boost::interprocess::winapi::GetSystemInfo”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h	95	
错误	C2733	“GetSystemInfo”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h	95	
错误	C2116	“boost::interprocess::winapi::FlushViewOfFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	273	
错误	C2733	“FlushViewOfFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	273	
错误	C2116	“boost::interprocess::winapi::UnmapViewOfFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	282	
错误	C2733	“UnmapViewOfFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	282	
错误	C2116	“boost::interprocess::winapi::FreeLibrary”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	186	
错误	C2733	“FreeLibrary”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	186	
错误	C2371	“boost::interprocess::winapi::GetModuleHandleA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	260	
错误	C2733	“GetModuleHandleA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	260	
错误	C2116	“boost::interprocess::winapi::GetProcAddress”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	342	
错误	C2733	“GetProcAddress”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	342	
错误	C2371	“boost::interprocess::winapi::LoadLibraryA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	663	
错误	C2733	“LoadLibraryA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	663	
错误	C2116	“boost::interprocess::winapi::InitializeSecurityDescriptor”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1054	
错误	C2733	“InitializeSecurityDescriptor”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1054	
错误	C2116	“boost::interprocess::winapi::SetSecurityDescriptorDacl”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1390	
错误	C2733	“SetSecurityDescriptorDacl”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1390	
错误	C2116	“boost::interprocess::winapi::CreateSemaphoreA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3098	
错误	C2733	“CreateSemaphoreA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3098	
错误	C2116	“boost::interprocess::winapi::CreateFileMappingA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3208	
错误	C2733	“CreateFileMappingA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3208	
错误	C2116	“boost::interprocess::winapi::RegCloseKey”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	212	
错误	C2733	“RegCloseKey”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	212	
错误	C2116	“boost::interprocess::winapi::RegOpenKeyExA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	692	
错误	C2733	“RegOpenKeyExA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	692	
错误	C2116	“boost::interprocess::winapi::RegQueryValueExA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	848	
错误	C2733	“RegQueryValueExA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	848	
错误	C2678	二进制“+”: 没有找到接受“const wchar_t [8]”类型的左操作数的运算符(或没有可接受的转换)	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	59	
错误	C2664	“void dcmtk::log4cplus::Logger::forcedLog(const dcmtk::log4cplus::spi::InternalLoggingEvent &) const”: 无法将参数 3 从“int”转换为“const char *”	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	59	
错误	C2678	二进制“+”: 没有找到接受“const wchar_t [8]”类型的左操作数的运算符(或没有可接受的转换)	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	64	
错误	C2664	“void dcmtk::log4cplus::Logger::forcedLog(const dcmtk::log4cplus::spi::InternalLoggingEvent &) const”: 无法将参数 3 从“int”转换为“const char *”	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	64	
错误	C2665	“dcmtk::log4cplus::Logger::getInstance”: 2 个重载中没有一个可以转换所有参数类型	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\logmacro.h	106	
错误	C2116	“boost::interprocess::winapi::CreateDirectoryA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	59	
错误	C2733	“CreateDirectoryA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	59	
错误	C2116	“boost::interprocess::winapi::CreateFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	87	
错误	C2733	“CreateFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	87	
错误	C2116	“boost::interprocess::winapi::FindFirstFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	233	
错误	C2733	“FindFirstFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	233	
错误	C2116	“boost::interprocess::winapi::FindNextFileA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	322	
错误	C2733	“FindNextFileA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	322	
错误	C2116	“boost::interprocess::winapi::GetFileInformationByHandle”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	651	
错误	C2733	“GetFileInformationByHandle”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	651	
错误	C2116	“boost::interprocess::winapi::GetFileSizeEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	681	
错误	C2733	“GetFileSizeEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	681	
错误	C2371	“boost::interprocess::winapi::GetFileType”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	690	
错误	C2733	“GetFileType”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	690	
错误	C2116	“boost::interprocess::winapi::LockFileEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	984	
错误	C2733	“LockFileEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	984	
错误	C2116	“boost::interprocess::winapi::ReadFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1024	
错误	C2733	“ReadFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1024	
错误	C2116	“boost::interprocess::winapi::SetFilePointerEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1150	
错误	C2733	“SetFilePointerEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1150	
错误	C2116	“boost::interprocess::winapi::UnlockFileEx”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1209	
错误	C2733	“UnlockFileEx”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1209	
错误	C2116	“boost::interprocess::winapi::WriteFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1221	
错误	C2733	“WriteFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1221	
错误	C2371	“boost::interprocess::winapi::GetTempPathA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1462	
错误	C2733	“GetTempPathA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapi.h	1462	
错误	C2116	“boost::interprocess::winapi::CreateMutexA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h	428	
错误	C2733	“CreateMutexA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\synchapi.h	428	
错误	C2116	“boost::interprocess::winapi::GetProcessTimes”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h	106	
错误	C2733	“GetProcessTimes”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\processthreadsapi.h	106	
错误	C2116	“boost::interprocess::winapi::GetSystemInfo”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h	95	
错误	C2733	“GetSystemInfo”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\sysinfoapi.h	95	
错误	C2116	“boost::interprocess::winapi::FlushViewOfFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	273	
错误	C2733	“FlushViewOfFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	273	
错误	C2116	“boost::interprocess::winapi::UnmapViewOfFile”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	282	
错误	C2733	“UnmapViewOfFile”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\memoryapi.h	282	
错误	C2116	“boost::interprocess::winapi::FreeLibrary”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	186	
错误	C2733	“FreeLibrary”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	186	
错误	C2371	“boost::interprocess::winapi::GetModuleHandleA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	260	
错误	C2733	“GetModuleHandleA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	260	
错误	C2116	“boost::interprocess::winapi::GetProcAddress”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	342	
错误	C2733	“GetProcAddress”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	342	
错误	C2371	“boost::interprocess::winapi::LoadLibraryA”: 重定义；不同的基类型	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	663	
错误	C2733	“LoadLibraryA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\libloaderapi.h	663	
错误	C2116	“boost::interprocess::winapi::InitializeSecurityDescriptor”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1054	
错误	C2733	“InitializeSecurityDescriptor”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1054	
错误	C2116	“boost::interprocess::winapi::SetSecurityDescriptorDacl”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1390	
错误	C2733	“SetSecurityDescriptorDacl”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\securitybaseapi.h	1390	
错误	C2116	“boost::interprocess::winapi::CreateSemaphoreA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3098	
错误	C2733	“CreateSemaphoreA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3098	
错误	C2116	“boost::interprocess::winapi::CreateFileMappingA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3208	
错误	C2733	“CreateFileMappingA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h	3208	
错误	C2116	“boost::interprocess::winapi::RegCloseKey”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	212	
错误	C2733	“RegCloseKey”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	212	
错误	C2116	“boost::interprocess::winapi::RegOpenKeyExA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	692	
错误	C2733	“RegOpenKeyExA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	692	
错误	C2116	“boost::interprocess::winapi::RegQueryValueExA”: 不同声明之间的函数参数列表不匹配	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	848	
错误	C2733	“RegQueryValueExA”: 无法重载具有外部 "C" 链接的函数	pcl11poisson	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winreg.h	848	
错误	C2678	二进制“+”: 没有找到接受“const wchar_t [8]”类型的左操作数的运算符(或没有可接受的转换)	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	59	
错误	C2664	“void dcmtk::log4cplus::Logger::forcedLog(const dcmtk::log4cplus::spi::InternalLoggingEvent &) const”: 无法将参数 3 从“int”转换为“const char *”	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	59	
错误	C2664	“void dcmtk::log4cplus::Logger::forcedLog(const dcmtk::log4cplus::spi::InternalLoggingEvent &) const”: 无法将参数 3 从“int”转换为“const char *”	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\tracelog.h	64	
错误	C2665	“dcmtk::log4cplus::Logger::getInstance”: 2 个重载中没有一个可以转换所有参数类型	pcl11poisson	D:\project\volumerendering\pcl11poisson\3rdparty\DCMTK\include\dcmtk\oflog\logmacro.h	106	

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. Custom OS, custom PCL configs or custom build systems make the issue difficult to reproduce.
* Best reproducability: A docker image + code snippets provided here
* Good reproducability: Common Linux OS + default PCL config + code snippets provided here
* Poor reproducability: code snippets

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights
* debugging information:
  * the output of cmake using `cmake --debug`
  * the failing build command(s) using `VERBOSE=1 make`, `ninja -v` or similar
  * steps taken to narrow down the problem

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 16.04]
 - Compiler: [:eg GCC 8.1]
 - PCL Version [e.g. 1.10, HEAD] (NB: please ensure you don't have multiple versions available)
 - PCL Type: [Installed/Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes/No
 - List and Version of dependencies used
 - Compilation flags are used

If compiling against PCL:
 - Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
  * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
  * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by WorstCodeWay** [comment]
@guyuezuntinggithub  Hi~, could you tell me how you solve these build errors?
