### ISSUE TITLE
[mls] Question about mls.hpp's projectQueryPoint function's SIMPLE method

### ISSUE THREAD

**Issue by keineahnung2345** [PointCloudLibrary/pcl#4507]
In the `SIMPLE` method of `projectQueryPoint` function in `mls.hpp`:
https://github.com/PointCloudLibrary/pcl/blob/f9c2c7bf51461d77dbc26727938fba30512e5b4f/surface/include/pcl/surface/impl/mls.hpp#L707-L709

When it calculates partial derivative, it only use the `c_vec[order_+1]` and `c_vec[1]`, which correspond to the polynomial's `u` and `v` terms respectively. But the polynomial is not necessary of 2nd order, so the calculation of partial derivative here is not always correct.

Any ideas?

**Comment by mvieth** [comment]
Correct me if I missed something, but this is how I understand the code: The polynomial equation is differentiated and then evaluated at u=0, v=0. If you look e.g. at the second order example in the code:
https://github.com/PointCloudLibrary/pcl/blob/93d04f8b8b3408b0db4d823a249d03b8547b48d7/surface/include/pcl/surface/mls.h#L229
You see that after differentiating and then evaluating at u=0, v=0, only the linear terms, `c_vec[1]*v` and `c_vec[3]*u` (which is `c_vec[order+1]*u`), remain: `c_vec[0]` vanishes while differentiating, and all the higher order terms still have a `u` or `v` in them, which is 0, so they vanish too.

**Comment by mvieth** [comment]
@keineahnung2345 Does my explanation make sense to you? I don't see a bug in the code and would tend to close this issue

**Comment by keineahnung2345** [comment]
Yes, I just realized what the comment says, thank you!
