### ISSUE TITLE
[CI] Windows CI is down again due to inability to find Boost

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4511]
vcpkg is at it again

**Comment by larshg** [comment]
Actually its the VM images themselves as boost comes preinstalled 😄 - but still annoying. Might be just a boost update.

**Comment by kunaltyagi** [comment]
Oh. I really hope you can get back on the windows container PR. It'd be a huge relief to know the CI is stable for windows
