### ISSUE TITLE
[compile error] VCPKG Could NOT find Qhull

### ISSUE THREAD

**Issue by Zoylamb** [PointCloudLibrary/pcl#4515]
When installing PCL with VCPKG on Windows 7 x64

Qhull and PCL is installed and compiled just fine
But QHULL isn't found during PCL compilation 

in configx64-windows-out.log it's indicated 

> -- Could NOT find Qhull (missing: QHULL_LIBRARIES QHULL_INCLUDE_DIRS)

OS : Windows 7 x64
Visual 2019 PRO
Vcpkg version: 2020.11.12-nohash

**Comment by larshg** [comment]
This would be fixed by #3741.

**Comment by Zoylamb** [comment]
Thank you for this feedback.
I'll use the allinOne installer for now.

**Comment by mvieth** [comment]
Should be fixed by #4923 , otherwise please comment/reopen
