### ISSUE TITLE
How to support multi object tracking in 3D Point Cloud ?

### ISSUE THREAD

**Issue by WestbrookZero** [PointCloudLibrary/pcl#4525]

**Comment by mvieth** [comment]
You can see if you find anything useful here:
https://pointclouds.org/documentation/namespacepcl_1_1tracking.html
or here:
https://pointclouds.org/documentation/group__recognition.html

**Comment by WestbrookZero** [comment]
Both ParticleFilterTracker and KLDAdaptiveParticleFilterTracker  supports only one object tracking

**Comment by JStech** [comment]
Would it be feasible to just create multiple instances of them? I'm not familiar with this part of the library.
