### ISSUE TITLE
[cmake] PCL1.11 Wrong PCL_INCLUDE_DIRS under set EIGEN_ROOT

### ISSUE THREAD

**Issue by Durant35** [PointCloudLibrary/pcl#4545]
```cmake
set(PCL_VERSION "1.11.1" CACHE STRING "PCL version")
# PCL depends on Eigen3 and Boost
find_package(Eigen3 REQUIRED)
set(EIGEN_ROOT ${Eigen3_INCLUDE_DIRS})
find_package(Boost REQUIRED)
set(BOOST_ROOT ${Boost_INCLUDE_DIRS})
find_package(PCL ${PCL_VERSION} REQUIRED
    COMPONENTS common io gpu_containers
    PATHS /usr/local/pcl-${PCL_VERSION}
    NO_DEFAULT_PATH
)
```
+ Eigen3_INCLUDE_DIRS: `.../3rdparty/include/eigen3`
+ Boost_INCLUDE_DIRS: `/usr/include`
+ PCL_INCLUDE_DIRS: `/usr/local/pcl-1.11.1/include/pcl-1.11/usr/include/eigen3/usr/include`

### Why PCL_INCLUDE_DIRS doesn't contain `${Eigen3_INCLUDE_DIRS}` but `usr/include/eigen3`?

Related to https://github.com/PointCloudLibrary/pcl/issues/2393

**Comment by mvieth** [comment]
Just to be sure I understand you correctly: you would expect that `PCL_INCLUDE_DIRS` contains `.../3rdparty/include/eigen3`, not that it literally contains `${Eigen3_INCLUDE_DIRS}`, right?
This is the script that finds the Eigen installation:
https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindEigen.cmake

**Comment by Durant35** [comment]
Yes, I compile it by myself as following:
```bash
$ cmake -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr/local/pcl-1.11.1 \
        -DPCL_ENABLE_SSE=OFF -DBUILD_GPU=ON -DBUILD_apps=ON -DWITH_VTK=OFF ..
```

**Comment by mvieth** [comment]
What exactly are you trying to do? If you want to compile PCL with a specific Eigen installation, you will have to set `EIGEN_ROOT` for the PCL compilation. If you want _your project_ to use a specific Eigen installation, you have to search for it in your CMakeLists.txt, although the order of the listed include directories might be important, and using different Eigen versions for PCL and your own project can create problems.

**Comment by Durant35** [comment]
I got it, many thanks. However, does it mean the Eigen path should be fixed while building pcl, also my own project? Make it as 3rdparty is impossible?

**Comment by Durant35** [comment]
I mean: if EIGEN_ROOT is configured, PCL_INCLUDE_DIRS can dynamically adjust, will it be better?

**Comment by mvieth** [comment]
Sorry, I am not sure if I understand you correctly. Maybe this will help you:
PCL and your project (that uses PCL) should both use the same Eigen installation, or else bugs might appear. You can install a custom Eigen version on your computer, then compile and install PCL, and then build your own project. If you have multiple Eigen installations on your computer, you should make sure that you use the same one everywhere.

**Comment by Durant35** [comment]
Yes, I will use same eigen, a 3rdparty in my project, to rebuild PCL again. Besides, I hope the path to eigen (seems same as EIGEN_ROOT) could be flexible, due to it's a 3rdparty in my project, it is possible?

**Comment by Durant35** [comment]
@mvieth any comment? Maybe this issue could be closed if not.

**Comment by mvieth** [comment]
Sorry, I don't know what you mean by "flexible". What exactly are you trying to achieve?

**Comment by Durant35** [comment]
`.../3rdparty/include/eigen3` and `/usr/include/eigen3` are same version. I do want to use `.../3rdparty/include/eigen3` in my project, but `PCL_INCLUDE_DIRS` always contains `/usr/include/eigen3`.
I can configure EIGEN_ROOT to `${PATH_A}/3rdparty/include/eigen3` during build PCL, but I my project change to `PATH_B`, can I get `${PATH_B}/3rdparty/include/eigen3` in `PCL_INCLUDE_DIRS`?

**Comment by Durant35** [comment]
Currently I have to put `Eigen3_INCLUDE_DIRS` before `PCL_INCLUDE_DIRS` as following:
```cmake

```

**Comment by mvieth** [comment]
So the path/location of your Eigen installation changes? Generally, `PCL_INCLUDE_DIRS` is fixed (defined in PCLConfig.cmake).

**Comment by Durant35** [comment]
I see. I think this issue should be closed. Many thanks!
