### ISSUE TITLE
[Filters] Wrong computation in VoxelGridCovariance

### ISSUE THREAD

**Issue by zxd123** [PointCloudLibrary/pcl#4546]
Hi! There is a bug in the pcl/filters/include/pcl/filters/impl/voxel_grid_covariance.h line 99
The code is `cov_ (Eigen::Matrix3d::Identity ()),`.But according to the formula 
![sendpix2](https://user-images.githubusercontent.com/22142312/102199863-1849bb80-3eff-11eb-9385-b0da7e5a9f90.jpg)
it should be `cov_ (Eigen::Matrix3d::Zero ()),` . When the number of points is small, the difference will be more obvious.

**Comment by mvieth** [comment]
I think you are right. It seems like this class is not tested sufficiently, so the tests in test_filters.cpp should also be expanded.
You are welcome to create a pull request.

**Comment by zxd123** [comment]
> I think you are right. It seems like this class is not tested sufficiently, so the tests in test_filters.cpp should also be expanded.
> You are welcome to create a pull request.

Thank you for your advice. But I'm a beginner in PCL, NDT and GitHub, and may not be competent enough for this task. After that, if I am more proficient in these, I will seriously consider this proposal.
