### ISSUE TITLE
[Run Time Error] Run time error when using PCL 1.7.2 and Boost 1.58

### ISSUE THREAD

**Issue by SubMishMar** [PointCloudLibrary/pcl#4548]
Hi,
I am trying to use PCL 1.7.2 that came with ROS Kinetic in one my projects which also depends on BOOST libraries. I currently have BOOST 1.58, I feel this also came with ROS installation. I have been stuck with a SEG fault which results when I try to use both PCL and BOOST together. The debugger throws the following message: 
```

Program received signal SIGSEGV, Segmentation fault.
0x00007fa42fd4cce4 in long double boost::math::lanczos::lanczos17m64::lanczos_sum<long double>(long double const&) () from /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so.1.7
```

I am looking for recommendations on how to solve this issue and I will appreciate any help in this direction. If this is not the correct forum to post this issue then kindly direct me to the right place. 

Thanks.

**Comment by mvieth** [comment]
It would be helpful if you could try to debug the error with gdb and/or valgrind, and post the output here. Then we can try to determine where the segfault came from exactly.
It would also be helpful if you post a snippet of your code where the segfault happens.
Furthermore, you could try to compile a more recent version of PCL and test, whether the error still appears.

**Comment by SubMishMar** [comment]
Thanks for your response. I am using the GDB debugger that comes with CLION and I have posted the output above but I am adding a few snapshots here for your perusal. 

![Screenshot from 2020-12-15 13-44-21](https://user-images.githubusercontent.com/28704031/102264783-b75cbc00-3edb-11eb-9b87-8f3f822bfcad.png)

![Screenshot from 2020-12-15 13-44-40](https://user-images.githubusercontent.com/28704031/102264811-c04d8d80-3edb-11eb-8fd4-620bb1e39d20.png)

The error occurs when I try to use a function from the boost math library. 
```
   boost::math::chi_squared chi_squared_dist(res.rows());
   double chi2_check = boost::math::quantile(chi_squared_dist, 0.95);
```

If I don't use it then all's good. It is very confusing. At many places they have mentioned that PCL 1.7.2 and BOOST 1.58 are not compatible.

**Comment by mvieth** [comment]
Can you maybe do a `backtrace` in gdb?
So the report says that the segfault came from the sample consensus PCL module, but you did not call a function from PCL when it happened? That is indeed confusing.
What is `res` in your code?

> At many places they have mentioned that PCL 1.7.2 and BOOST 1.58 are not compatible.

What places are you referring to specifically?

**Comment by SubMishMar** [comment]
res is a Eigen::VectorXd, so res.rows() is a quantity of type size_t (or int). I was referring to https://github.com/PointCloudLibrary/pcl/issues/780 and https://github.com/felixendres/rgbdslam_v2/issues/8 .
Anyway I was able to fix it by doing what these two forums suggest, i.e. by building PCL (1.7) from source by adding the line `SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` to the CMakelists.txt at PCL's root directory. Since the issue is solved, I am closing it.
