### ISSUE TITLE
Retrieve 3D points based on the camera parameters

### ISSUE THREAD

**Issue by Zumbalamambo** [PointCloudLibrary/pcl#4552]
I have got the following data,

```
1. Point cloud
2. Camera Intrinsic, Extrinsic parameters as well as the Projection Matrix.
```

How do I retrieve the 3D points of the point cloud based on the camera's extrinsic information? or in other words, how do I retrieve the portion of the point cloud that the camera is looking at?

**Comment by mvieth** [comment]
Have a look at the `FrustumCulling` class (https://pointclouds.org/documentation/classpcl_1_1_frustum_culling.html) and check if this does what you want.

**Comment by mvieth** [comment]
I'm closing this issue because it seems the question was sufficiently answered.
