### ISSUE TITLE
path too long installer unable to modify path

### ISSUE THREAD

**Issue by ametemre** [PointCloudLibrary/pcl#4557]
hello while installing i got an error like this "path too long installer unable to modify path" click ok to continue.

dun know why and how to overcome it

**Comment by mvieth** [comment]
Please provide some more information. I assume you compiled PCL from source and are now trying to install it? What OS are you using? What commands/steps did you use?
Also please check if issue #2383 is the same as yours and if the suggestions there are helpful for you.

**Comment by mvieth** [comment]
Closing issue: no feedback from author

**Comment by ametemre** [comment]
i overcome the situation using allinone installer, thank you
