### ISSUE TITLE
[Question] Use kdtree for nearest searching

### ISSUE THREAD

**Issue by minwoo0611** [PointCloudLibrary/pcl#4559]
Hello, 
I am using pcl well for SLAM study. 
I tried to proceed with k-nearest search using pointcloud, but I found out that k-nearest search only uses xyz value(3-dimension).

Can other values ​​be used for k-nearest search by increasing the field dimension? For example, can I do K-nearest search using PointXYZI with 4 fields??

I look forward to your answer. Thank you.

**Comment by mvieth** [comment]
Please see if [`KdTreeFLANN`](https://pointclouds.org/documentation/classpcl_1_1_kd_tree_f_l_a_n_n.html) or [`FlannSearch`](https://pointclouds.org/documentation/classpcl_1_1search_1_1_flann_search.html) do what you want.

**Comment by larshg** [comment]
Please use Discord for these usage questions.
