### ISSUE TITLE
[compile error] FLANNConfig.cmake missing

### ISSUE THREAD

**Issue by JzEazy** [PointCloudLibrary/pcl#4561]
Examples from the [official PCL Tutorials](https://pcl.readthedocs.io/projects/tutorials/en/latest/vfh_recognition.html#vfh-recognition) depending on FLANN library don't compile. 

cmake compilation results:

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
-- Could NOT find DAVIDSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
** WARNING ** io features related to davidSDK will be disabled
-- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES) 
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

** WARNING ** io features related to libusb-1.0 will be disabled
-- Could NOT find DAVIDSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
** WARNING ** visualization features related to davidSDK will be disabled
-- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES) 
** WARNING ** visualization features related to dssdk will be disabled
-- Could NOT find RSSDK (missing: _RSSDK_LIBRARIES) 
** WARNING ** visualization features related to rssdk will be disabled
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_2D
-- looking for PCL_GEOMETRY
-- looking for PCL_FEATURES
-- looking for PCL_ML
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_SURFACE
-- looking for PCL_REGISTRATION
-- looking for PCL_KEYPOINTS
-- looking for PCL_TRACKING
-- looking for PCL_RECOGNITION
-- looking for PCL_STEREO
-- looking for PCL_APPS
-- looking for PCL_IN_HAND_SCANNER
-- looking for PCL_MODELER
-- looking for PCL_POINT_CLOUD_EDITOR
-- looking for PCL_OUTOFCORE
-- looking for PCL_PEOPLE
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindFLANN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FLANN", but
  CMake did not find one.

  Could not find a package configuration file provided by "FLANN" with any of
  the following names:

    FLANNConfig.cmake
    flann-config.cmake

  Add the installation prefix of "FLANN" to CMAKE_PREFIX_PATH or set
  "FLANN_DIR" to a directory containing one of the above files.  If "FLANN"
  provides a separate development package or SDK, be sure it has been
  installed.

**To Reproduce**
-install pcl with "sudo apt install libpcl-dev" 
-compile[ tutorial example](https://pcl.readthedocs.io/projects/tutorials/en/latest/vfh_recognition.html#vfh-recognition) 

 - OS: [ Ubuntu 18.04]
 - PCL Version [1.8]
 - PCL Type: [Installed]

**Comment by mvieth** [comment]
Could you try again with a more recent PCL version (at least 1.9.0)?

**Comment by JzEazy** [comment]
Thank you for the response! I did not realize how outdated the PCL version downloaded via apt is.  I am a bit confused why the pointclouds.org website recommends downloading libpcl-dev if the Version is outdated. I will reopen this issue if I experience a similar issue with the latest PCL version.

**Comment by mvieth** [comment]
:+1:
Well, the version in the apt repos is the latest version available when the specific Ubuntu distro was released. For Ubuntu 18.04 that was PCL 1.8.1, but that was almost 3 years ago, and e.g. Ubuntu 20.10 has PCL 1.11.1 (the current latest version). The confusion might be because the tutorial is for PCL 1.11.1. The tutorial for 1.8.1. is not available any more on the new website.

BTW #3309 describes a similar (or same?) problem, for more explanations please see there.
