### ISSUE TITLE
[Question] What is the difference between CUDA and GPU in pcl?

### ISSUE THREAD

**Issue by WorstCodeWay** [PointCloudLibrary/pcl#4564]
I'm building pcl from source with full features, suchlike GPU acceleration and applicaions. But I find there a two similar variables in cmake, `BUILD_CUDA`, `BUILD_GPU` and `WITH_CUDA`, should I check them all?

By the way, what is `BUILD_apps` for? If I need apps from pcl for conveniences, should I check it also?

**Comment by mvieth** [comment]
As far as I know, there is no clear distinction between the cuda module and the gpu module, and the classes in the gpu module use cuda as well. Perhaps @larshg knows more.
You can find some information on the apps in the tutorials on pointclouds.org, e.g. on the in-hand scanner.
Regarding the question which modules you should build, that depends on what you need. You can build everything, if you don't mind the additional build time and used disk space.

**Comment by larshg** [comment]
I think right now there isn't much difference between the two. GPU naming is more generic, so one could have OpenCL implementation there as well, where CUDA is very deterministic that its only CUDA.

But as @mvieth pointed out, there are no guidelines and the two could use a cleanup/merge.

**Comment by larshg** [comment]
Please use discord for further discussion to this.
