### ISSUE TITLE
Arrangement of the points pcl::fromROSMsg() 

### ISSUE THREAD

**Issue by Schloern93** [PointCloudLibrary/pcl#4578]
Hello,
I hope I'm not asking the question in the wrong place. I use the function to evaluate a PointCloud message:
```
void callback_depth_image_d435 (const sensor_msgs::msg::PointCloud2::SharedPtr point_cloud2_msgs)
    {

      pcl::PointCloud<pcl::PointXYZ> point_cloud;

      // convert point clouds2 msgs data to points
      pcl::fromROSMsg(*point_cloud2_msgs, point_cloud);
}
```
I am now trying to assign the points of the Point Cloud to the corresponding pixels, without success.
How are the points arranged in "point_cloud"?
If I access the first element with `point_cloud.points.at(0)` on which pixel does that correspond to the color_image?
I ask this now because I have already tested all possible variants for the evaluation and none has worked.
Thanks for the help

**Comment by mvieth** [comment]
There are two kinds of point clouds: organized and unorganized, which you can test with [`isOrganized`](https://pointclouds.org/documentation/classpcl_1_1_point_cloud.html#a914dbcef25abdb46f32991ac112002e7). If it is organized, you can access the points via row and column with [this operator](https://pointclouds.org/documentation/classpcl_1_1_point_cloud.html#ab4061110abf7f3761e6702c3d26397da) or similarly [with at](https://pointclouds.org/documentation/classpcl_1_1_point_cloud.html#a1155fe4ba5cdc7e83cb72159a4ea02dc)

**Comment by Schloern93** [comment]
Thanks for the answer. That means if I use the function at an image size 640w x 440h I get the pixels as follows
left upper corner:
`point_cloud.operator()(0, 0)._PointXYZ::x;`
right upper corner
`point_cloud.operator()(639, 0)._PointXYZ::x;`
lower-left corner
`point_cloud.operator()(0, 479)._PointXYZ::x;`
lower-right corner
`point_cloud.operator()(639, 479)._PointXYZ::x;`
center
`point_cloud.operator()(320, 220)._PointXYZ::x;`

**Comment by mvieth** [comment]
Actually, this is possible: `point_cloud(0, 0).x` and `point_cloud(0, 0).y` and `point_cloud(0, 0).z`

**Comment by Schloern93** [comment]
I still can not find the right points of the point cloud to the pixels.
I have now tried the following:
- I receive a bounding box from my object detection which is given in pixels (using a color_image height = 480 and width = 640)
- I receive a sorted PointCloud message with height = 480 and width = 640
- Im doing the conversion with : `pcl::fromROSMsg(*point_cloud2_msgs, point_cloud);`
- I calculate the center of the baunding box as follows: 
```
unsigned long x_middle_pos = (((bb.at(i).x_max - bb.at(i).x_min) / 2) + bb.at(i).x_min);
unsigned long y_middle_pos = (((bb.at(i).y_max - bb.at(i).y_min) / 2) + bb.at(i).y_min);

```
- Now I want to use the calculated center point of the bounding box (in pixel) to access the associated point of the Point Cloud message to determine the depth of the object.
`depth = point_cloud(x_middle_pos, y_middle_pos).z;`
- The red outlined object is the one for which I need the depth. The blue line shows the found depth of the pixel.

![Screenshot from 2021-01-21 11-18-49](https://user-images.githubusercontent.com/71652280/105337299-8b1f1400-5bda-11eb-95be-3f47e613bf3b.png)

Thanks for the help in advance!

**Comment by mvieth** [comment]
Did you check in what frame your point cloud is? It would have to be in a specific frame so that z-coordinate = depth.
If you only need the depth, it might be easier to work with a depth image.

**Comment by Schloern93** [comment]
My Point Cloud has the following frame.
> camera_depth_optical_frame

The visualization marker in which I draw the line has the same frame.
My fixed frame in rviz is `camera_link` --> these are transformed correctly via the tf2 tree.

When I move my object to the center of the room it recognizes the correct distance. But as soon as I move it too far from the center, it shows me the distance of the wall and not of the object.
Therefore I have the impression that I am accessing the points in the PointCloud matrix incorrectly.

**Comment by mvieth** [comment]
It is difficult to determine the exact cause of your problem without being able to work with your system. The way you are accessing the point cloud seems correct. Another tip I would give you is to check the depth not just at one pixel, but at a larger neighbourhood, maybe even every pixel inside the bounding box, and compute an average or median.

**Comment by Schloern93** [comment]
Hallo @mvieth,

Thanks for your answers.
I was able to solve the problem now.
The problem was that my color image which I use for object detection had a different FOV than my depth image. Therefore the pixels could not be assigned correctly.
