### ISSUE TITLE
How to convert OpenCV image coordinates into PCL point cloud coordinates?

### ISSUE THREAD

**Issue by WestbrookZero** [PointCloudLibrary/pcl#4580]

**Comment by mvieth** [comment]
Please give more information, e.g. describe what you are trying to do.

**Comment by WestbrookZero** [comment]
Point cloud based on multiple depth camera calibration after joining together to detect the 3d position, use pcl person detection is not accurate, so I changed to transformed into OpenCV image after splitting point cloud, as follows:
void extractRGBFromPointCloud(pcl::PointCloud<pcl::PointXYZRGB>::Ptr input_cloud,cv::Mat& combinedRgbMat)
{
        for (std::uint32_t j = 0; j < input_cloud->width; j++)
	{
		for (std::uint32_t i = 0; i < input_cloud->height; i++)
		{	
			combinedRgbMat.at<cv::Vec3b>(i, j) = cv::Vec3b((*input_cloud)(j, i).b, (*input_cloud)(j, i).g,  (*input_cloud)(j, i).r);
		}
	}
}

, then use to deep learning for 2d location, the main problem is that I don't know how to calculate the OpenCV 2d position into a point cloud of x and y, if you know the transformed coordinates of the point cloud, z axis can be based on “std::vector<pcl::people::PersonCluster<PointT>> clusters” results to match.

**Comment by mvieth** [comment]
Please see if issue #4578 helps you.

**Comment by dezbracaty** [comment]
I think if you know the transform information between two coordinates, you can use pcl::transformPointCloud to finish this .
