### ISSUE TITLE
[CI/Test] Try use virtual frame buffer to enable visualization unit tests

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#4585]
For running tests on the CI, will something like virtual frame buffer help?

_Originally posted by @kunaltyagi in https://github.com/PointCloudLibrary/pcl/issues/4527#issuecomment-739256682_

**Comment by mvieth** [comment]
@larshg Can this issue be closed, since PR #4589 is merged?

**Comment by larshg** [comment]
Indeed its fixed by #4589.
