### ISSUE TITLE
What is the interaction of Eigen's alignment macros and PCL transform functions?

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#4587]
https://github.com/PointCloudLibrary/pcl/blob/1d482d523ffc9602fb84a439b3f4c3fe46dff9a6/common/include/pcl/common/impl/transforms.hpp#L194

My code is currently failing on this AVX operation on unaligned data with something like this:
```
	typedef Eigen::Transform<double, 3, Eigen::Affine> Affine3;
	Affine transform = // returned from function

  pcl::transformPointCloud<pcl::PointXYZI, double>(
      points1, points2, transform);
```
I have checked and with `EIGEN_DONT_VECTORIZE` defined, the `Affine3` objects created with `Affine3::Identity()` are 8 byte aligned with the macro and 16 byte without. Neither matches the [requirement of 32 byte alignment](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/intrinsics-for-intel-advanced-vector-extensions/intrinsics-for-load-and-store-operations-1/mm256-load-pd.html). It also says [here](https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html#getrid) that fixed-size Eigen types should be 16-byte aligned, but the avx function requires 32-byte alignment, so am I misunderstanding something or is the implementation wrong? (assuming the former)

I should note that inside the `Transformer` constructor, `tf` always has 8-byte alignment (reported by `alignof`), even if I pass something which I explicitly declare `alignas(16)`. Not sure why that is.

My Eigen version is 30960d485ec7e45b095d3ad206b2dbcc8bc835ba (maybe Eigen master is unstable and that is the problem?) 

In any case, I'm interested to learn a) what influence the various [Eigen alignment directives](https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html) have, whether PCL disallows using them, and whether intrinsics relying on alignment can somehow be disabled in PCL (I've had nothing but problems using Eigen and PCL, and can never find where the alignment issues come from).

**Comment by themightyoarfish** [comment]
I should also note that despite passing `-mno-avx` on the command line, PCL still seems to have the `__AVX__` macro defined and thus executes these intrinsics.

**Comment by mvieth** [comment]
I assume this is a continuation of issue #4554 ?

I can't answer all your questions regarding Eigen on the spot, that is a quite complex topic. I will have to look into it further.
I agree that it seems to be problematic to assume that the Matrix `tf` is 32 byte aligned, and I don't see any reason why that can be safely assumed. In the last issue, I suggested replacing the aligned loads with unaligned loads (or at least some of them). This should eliminate this issue and cause at most minor performance penalties. If this solution works for you, we could create a pull request.
Regarding your issue that AVX is still enabled, I thought in the last issue you found that `-march=native` was enabled?

**Comment by themightyoarfish** [comment]
This issue arose with `-march=native`, but after updating the PCL version, it no longer occurred (1.11.1 exhibited the issue). I can't say if this is random or something was fixed, but I guess I should close this for now.

However, maybe someone with knowledge should take a look at whether 32-byte alignment can be assumed in that function.

**Comment by mvieth** [comment]
@themightyoarfish just to make sure I understand you correctly: with PCL 1.11.1 you did not have any issues, but with the PCL version you used before you did have issues? What version was that?

**Comment by mvieth** [comment]
`EIGEN_MAX_ALIGN_BYTES` and `EIGEN_MAX_STATIC_ALIGN_BYTES` determine the alignment of the transform (and of matrices etc). They are usually determined automatically, e.g. when AVX is available, they should be 32. It would be interesting to know what values they have in your case.
I suspect that the text [here](https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html#getrid) might be older, when AVX (with 32 byte alignment) was not available, and considers only SSE (with 16 byte alignment).

**Comment by themightyoarfish** [comment]
Next time I run into this I will double check, though i seem to remember they were 16, which is the value I find documented.
