### ISSUE TITLE
[common] Add tests for `vector`-like functions

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4588]
**Describe the bug**

The new accessors were added without tests in #4397

**Context**

The PR was important to go to allow for other PRs to move forward. However, it left a large gap in the code coverage of `PointCloud` struct.

**Comment by codeboy5** [comment]
Hey i would like to take this issue up, can you describe the issue a little more ?

**Comment by kunaltyagi** [comment]
If you see the file `common/include/pcl/point_cloud.h`, it has a lot of functions which perform abstractions over the points.

The non-trivial operators (the ones that do some custom work, not just pass the call to the std::vector points) haven't been tested. The PR is still waiting a merge, but you can check out the PR version as well for a few extra operators

**Comment by rabaho** [comment]
I can help as well.

**Comment by kunaltyagi** [comment]
No one has staked a claim yet. Please feel free to create a small PR so I can assign you the issue

**Comment by rabaho** [comment]
Just for clarification, I am writing tests for the new accessors (transient_stuff, assign, and resize)  not the actual accessors (assign, resize), is that correct?

**Comment by mvieth** [comment]
@kunaltyagi Can this issue be closed, since PR #4618 is merged?
