### ISSUE TITLE
error: ‘__m256’ does not name a type; did you mean ‘._656’?  inline __m256

### ISSUE THREAD

**Issue by zhaohaowu** [PointCloudLibrary/pcl#4594]
In file included from /home/zhw/下载/ubuntu文件/pcl-master/common/src/common.cpp:43:0:
/home/zhw/下载/ubuntu文件/pcl-master/common/include/pcl/common/common.h:114:10: error: ‘__m256’ does not name a type; did you mean ‘__m128d’?
   inline __m256
          ^~~~~~
          __m128d
/home/zhw/下载/ubuntu文件/pcl-master/common/include/pcl/common/common.h:131:10: error: ‘__m256’ does not name a type; did you mean ‘__m128d’?
   inline __m256
          ^~~~~~
          __m128d
In file included from /home/zhw/下载/ubuntu文件/pcl-master/common/include/pcl/common/common.h:267:0,
                 from /home/zhw/下载/ubuntu文件/pcl-master/common/src/common.cpp:43:
/home/zhw/下载/ubuntu文件/pcl-master/common/include/pcl/common/impl/common.hpp:104:8: error: ‘__m256’ does not name a type; did you mean ‘._656’?
 inline __m256
        ^~~~~~
        ._656
/home/zhw/下载/ubuntu文件/pcl-master/common/include/pcl/common/impl/common.hpp:112:8: error: ‘__m256’ does not name a type; did you mean ‘._656’?
 inline __m256
        ^~~~~~
        ._656

compile by cmake
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr \
           -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON \
           -DCMAKE_INSTALL_PREFIX=/usr ..
make -j16
sudo make install 

when i make -j16
some mistake above happen

**Comment by larshg** [comment]
It seems you have gotten AVX enabled, but using a compiler/system that doesn't really support it. Also: ```-DCMAKE_BUILD_TYPE=None``` should probably be either with `debug`, `release` or `RelWithDebInfo`.

**Comment by zhaohaowu** [comment]
> It seems you have gotten AVX enabled, but using a compiler/system that doesn't really support it. Also: `-DCMAKE_BUILD_TYPE=None` should probably be either with `debug`, `release` or `RelWithDebInfo`.

thanks first, but how i make AVX disabled, or how i solve the error above, or how i should "cmake .." in build folder

**Comment by mvieth** [comment]
@zhaohaowu Can try again with the current PCL master? Pull request #4627 might solve this problem.

**Comment by mvieth** [comment]
The pull request I linked above should fix the problem, and the current master should compile fine. So I am going to close this, but if you still get these errors, feel free to reopen or comment.
