### ISSUE TITLE
Move PointXYZLAB to common?

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#4600]
The point type PointXYZLAB is currently defined in [gicp6d](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/gicp6d.h). The definition could be moved to point_types.h and point_types.hpp, and conversions could be moved from [gicp6d.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/registration/src/gicp6d.cpp) to point_types_conversion.h

Pros:
- Types like PointXYZRGB(A) and PointXYZHSV are in point_types
- Currently doxygen seems to be confused by the macros in gicpd6d.h (see [here](https://pointclouds.org/documentation/group__registration.html) under Function Documentation), that would be solved by moving the definitions

Cons:
- Currently PointXYZLAB is only used by `GeneralizedIterativeClosestPoint6D`

**Comment by kunaltyagi** [comment]
Not against the proposal, and the cons is not that big of an issue ([IETF style](https://tools.ietf.org/html/rfc7282))
