### ISSUE TITLE
vcpkg install pcl failed when compiling boost-math

### ISSUE THREAD

**Issue by fl0kng** [PointCloudLibrary/pcl#4601]
Hi folks,
"vcpkg install pcl" fails on my windows 10 machine:

-------------- console output:

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: D:/dev/vcpkg/installed/x86-windows/tools/boost-build/b2.exe --stagedir=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel/stage --build-dir=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel --user-config=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sBZIP2_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sLZMA_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sZSTD_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: D:/dev/vcpkg/buildtrees/boost-math/src/ost-1.75.0-eaa6889798.clean/build
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\boost-math\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:364 (vcpkg_execute_required_process)
  ports/boost-math/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:128 (include)

Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

-------------------- build-x86-windows-rel-out.log:

msvc.link.dll D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll
LINK : fatal error LNK1104: cannot open file 'D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll'

        call "D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat" x86 >nul
 link /NOLOGO /INCREMENTAL:NO /DLL /DEBUG /MACHINE:X86 /MANIFEST:EMBED /OPT:REF,ICF /subsystem:console /out:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll" /IMPLIB:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.lib"     @"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll.rsp"
    
...failed msvc.link.dll D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.lib D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.pdb D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.pdb...
...skipped <pD:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\stage\lib>boost_math_tr1f-vc142-mt-x32-1_75.dll for lack of <pD:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62>boost_math_tr1f-vc142-mt-x32-1_75.dll...
common.copy D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\stage\lib\boost_math_tr1-vc142-mt-x32-1_75.lib
D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.lib
        1 file(s) copied.
common.copy D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\stage\lib\boost_math_tr1-vc142-mt-x32-1_75.dll
D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.dll
        1 file(s) copied.
common.copy D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\stage\lib\boost_math_tr1-vc142-mt-x32-1_75.pdb
D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.pdb
        1 file(s) copied.
compile-c-c++ D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\riemann_zetal.obj
riemann_zetal.cpp
compile-c-c++ D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\sph_bessell.obj
sph_bessell.cpp
compile-c-c++ D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\sph_neumannl.obj
sph_neumannl.cpp
...failed updating 1 target...
...skipped 1 target...
...updated 158 targets...

---

Thanks.

**Comment by larshg** [comment]
Since its a VCPKG issue with installing boost, please post the issue at https://github.com/microsoft/vcpkg.

Closing this, as its not a PCL issue.
