### ISSUE TITLE
[surface] Segfault when using ConvexHull reconstruct method

### ISSUE THREAD

**Issue by marcov868** [PointCloudLibrary/pcl#4602]
I'm attempting to perform convex hull but I got a segmentation fault. This is produced by the method reconstruct and I cannot find a way to resolve it.
To be sure it's not a problem of my code, I compiled and ran the [pcl tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/hull_2d.html#hull-2d) but it gave the same error.

The problem seems not to be related to a specific input PointCloud since I also tried to generate a simple cloud and the results it's the same:

```c++
#include <iostream>

#include <pcl/point_types.h>
#include <pcl/point_cloud.h>

#include <pcl/surface/convex_hull.h>

typedef pcl::PointXYZ Point;
typedef pcl::PointCloud<Point> PointCloud;

int main()
{
    PointCloud::Ptr cloud(new PointCloud);

    cloud->push_back(Point(0, 0, 0));
    cloud->push_back(Point(1, 0, 0));
    cloud->push_back(Point(0, 1, 0));
    cloud->push_back(Point(0, 0, 1));
    cloud->push_back(Point(0.1, 0.1, 0.1));

    pcl::ConvexHull<Point> chull;
    chull.setInputCloud(cloud);

    PointCloud hull_cloud;
    std::vector<pcl::Vertices> hull_polygons;

    chull.reconstruct(hull_cloud, hull_polygons);

    std::cout << "reconstruction succeeded. received hull with " << hull_cloud.size() << " points." << std::endl;

    return 0;
}
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a4fb4b in pcl::ConcaveHull<pcl::PointXYZ>::performReconstruction(pcl::PointCloud<pcl::PointXYZ>&, std::vector<pcl::Vertices, std::allocator<pcl::Vertices> >&) () from /usr/lib/libpcl_surface.so.1.11
```

**Environment**

 - OS: ArchLinux 5.4.94-1-lts
 - Compiler: GCC 10.2.0
 - PCL Version: 1.11.1-1 (installed from AUR)

**Comment by mvieth** [comment]
What version of qhull do you have installed?

**Comment by marcov868** [comment]
2020.2-4

> What version of qhull do you have installed?

**Comment by mvieth** [comment]
At the moment, PCL unfortunately does not work with the newest version(s) of qhull, because they dropped the support for the interfaces that PCL uses. There is at least one pull request that aims to fix this issue, we hope to integrate it soon.

**Comment by ruslo** [comment]
> I'm attempting to perform convex hull but I got a segmentation fault

Try to add `PCL_NO_PRECOMPILE=ON` while configuring PCL. Did the trick for me.

**Comment by mvieth** [comment]
@ruslo You might be experiencing a different issue, I don't see how `PCL_NO_PRECOMPILE` could solve the problem described above.
By the way: PCL now supports the new versions of qhull.
