### ISSUE TITLE
[Voxel Filter] Voxel Filter is filtering out to many points/ adding points at the wrong position

### ISSUE THREAD

**Issue by Zarbokk** [PointCloudLibrary/pcl#4604]
**Describe the bug**
I have a point cloud, which is filtered by the voxel Filter.
The resulting point cloud differs A LOT from the original point cloud.
This happens not always but only happens when the scene is changing very fast.

**Context**

I want to reduce the complexity of the point cloud. I always add 720 points to an existing point cloud, and then apply the voxel filter(each step).

**Expected behavior**

After that, the maximum points that should be reduced by the voxel filter are, to my understanding, 720. (if all points lie on other already existing points.).

**Current Behavior**

Instead, a lot of points are created in different spaces. This can be seen in the screenshot provided. The yellow Point cloud is the input cloud and the white cloud is the output cloud of the filter.

**To Reproduce**

I am using the ROS system and a Simulation. Therefore difficult.

**Screenshots/Code snippets**

![Screenshot from 2021-02-10 10-54-20](https://user-images.githubusercontent.com/10078972/107494645-52e27400-6b8f-11eb-8981-91173e835c13.png)

The code used in this example is the following:
```
void downsample(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud_input) {
        pcl::PointCloud<pcl::PointXYZ>::Ptr output(new pcl::PointCloud<pcl::PointXYZ>);
        sor.setInputCloud(cloud_input);
        sor.setLeafSize(0.10f, 0.10f, 0.10f);
        sor.filter(*output);
        cloud_input = output;
    }
```

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]
 - PCL Version [1.10]

**Possible Solution**

I am not sure if this is a bug or if I am too stupid to use the voxel filter.

**Comment by mvieth** [comment]
Can you store the input cloud as a PCD file and upload it here? That would make it at least a bit reproducible.

**Comment by Zarbokk** [comment]
Sadly I am not able to reproduce the error with the saved PCD files. Everything works as it should if I load the file and apply the same voxel filter.
Therefore I would say an error has to be in my code. 
Maybe you have an idea whats wrong:
The function downsample:
```
void downsample(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud_input, pcl::PointCloud<pcl::PointXYZ>::Ptr &output) {
    pcl::VoxelGrid<pcl::PointXYZ> sor;
    sor.setInputCloud(cloud_input);
    sor.setLeafSize(0.10f, 0.10f, 0.10f);
    sor.filter(*output);
}
```

The code looks as following:

```
pcl::PointCloud<pcl::PointXYZ>::Ptr myCloud (new pcl::PointCloud<pcl::PointXYZ>);
pcl::fromROSMsg(*msg,*myCloud);//get the cloud from ROS always size 720(laser scan)


pcl::transformPointCloud(*myCloud,*myCloud,shift,quat_rot);     //shift and Rotate the cloud

*current_map+= *myCloud;           //add myCloud(size = 720) to current map( size = 17908)

pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_output (new pcl::PointCloud<pcl::PointXYZ>);
pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_input (new pcl::PointCloud<pcl::PointXYZ>);

*cloudvoxel_input = *current_map;          //copy into new input 
pcl::io::savePCDFileASCII ("before_voxel.pcd", *cloudvoxel_input);     //size before downsampling = 18628
downsample(cloudvoxel_input,cloudvoxel_output);

pcl::io::savePCDFileASCII ("after_voxel.pcd", *cloudvoxel_output);     //output size is 7937
```

When doing that correct(with the pcd files) the resulting cloud is of size 18368, which means 260 points less

**Comment by mvieth** [comment]
So you are creating a new `VoxelGrid` object every time that you are filtering a cloud and the problem still exists? Otherwise I would have suspected that if you re-use a `VoxelGrid` object, the stored data from the previous uses might not be overwritten completely. Creating a new object for every filtering run is definitely the safer way.
Your `downsample` function looks okay. Did I understand you correctly: when you used the `downsample` function in your "online" program, it incorrectly downsampled from 18628 to 7937 points, but when you used the sample `downsample` function in an "offline" program, with the stored "before_voxel.pcd" cloud (the same cloud as in the "online" run), it correctly downsampled from 18628 to 18368 points?

**Comment by Zarbokk** [comment]
Both your points are correct.

1. I tried both, creating a new filter object for every loop and have it predefined. Same outcome. I thought about that overwriting as well. that's why I created the objects new every loop.

2. Exactly. In the online case, it incorrectly downsamples from 18628 to 7937 points, but in the offline case the exact same code is returning the correct downsampling to 18368 points.

So you understood that correctly I think.

**Comment by mvieth** [comment]
That is strange. Could you try - in the online program - to store the cloud as a PCD file, then load that same PCD file, and pass the loaded cloud to the `downsample` function?

**Comment by Zarbokk** [comment]
That was the right track, after adding a save and load directly before the downsampling method everything works as intended.
For completeness the new code looks like this:
```
pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_save (new pcl::PointCloud<pcl::PointXYZ>);
*cloudvoxel_save = *current_map;
pcl::io::savePCDFileASCII ("before_voxel.pcd", cloudvoxel_save);

pcl::io::loadPCDFile("/home/tim/catkin_ws/devel/lib/simulation_bluerov/before_voxel.pcd",*cloudvoxel_input);

downsample(cloudvoxel_input,cloudvoxel_output);
```

This means that somehow the data handover to the downsample function is corrupt/ wrong.

As far as I understand I have the PointCloud `cloudvoxel_input` as Ptr.
Then I give the reference to the `downsample` function and start filtering.
I return the output to the reference `cloudvoxel_output` which is also a Ptr.

There has to be something wrong.
Is it possible that a shared Ptr is a problem?

If I am correct the voxel grid output is a new Pointcloud for which new memory is allocated.
If the reference to this new cloud is then copied that should not be a problem.

Any Idea?

**Comment by mvieth** [comment]
And if you remove the `savePCDFile` and `loadPCDFile` again, the problem appears again?
Can you compare `cloudvoxel_save` and `cloudvoxel_input` to see if they are exactly the same? Width, height, every point, etc?

**Comment by Zarbokk** [comment]
The code used is the following:
```
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_output (new pcl::PointCloud<pcl::PointXYZ>);
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_output2 (new pcl::PointCloud<pcl::PointXYZ>);
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_save (new pcl::PointCloud<pcl::PointXYZ>);
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloudvoxel_input (new pcl::PointCloud<pcl::PointXYZ>);
        *cloudvoxel_save = *current_map;

        pcl::io::savePCDFileASCII ("before_voxel.pcd", *cloudvoxel_save);
        pcl::io::loadPCDFile("/home/tim/catkin_ws/devel/lib/simulation_bluerov/before_voxel.pcd",*cloudvoxel_input);

        printf("cloudvoxel_save number points %d \n",(*cloudvoxel_save).size());
        printf("cloudvoxel_input number points %d \n",(*cloudvoxel_input).size());
        //cloudvoxel_save->is_dense = true;
        downsample(cloudvoxel_save,cloudvoxel_output);
        printf("cloudvoxel_output number points(with cloudvoxel_save) %d \n",(*cloudvoxel_output).size());
        int tmp_d = (*cloudvoxel_output).size();

        downsample(cloudvoxel_input,cloudvoxel_output2);
        printf("cloudvoxel_output number points(with cloudvoxel_input) %d \n",(*cloudvoxel_output2).size());
        pcl::io::savePCDFileASCII ("after_voxel.pcd", *cloudvoxel_output);
```

The output(in terminal) is:
```
cloudvoxel_save number points 6004 
cloudvoxel_input number points 6004 
cloudvoxel_output number points(with cloudvoxel_save) 1168 
cloudvoxel_output number points(with cloudvoxel_input) 5776 
```

When using a debugger this can also be seen that everything is the same. Size Width height the starting points(checked first few points)
Only parameter that is different is the "is_dense" parameter(as far as I can tell)

**Comment by mvieth** [comment]
The `downsample` function can't give different outputs for the same input, so let's take a look at `is_dense`. What is the value for `is_dense` of `cloudvoxel_save`, `cloudvoxel_input`, `current_map`, and `myCloud` (the cloud that you add to `current_map`)? Do you see anything like `NaN` or infinity in `before_voxel.pcd`?

**Comment by Zarbokk** [comment]
That is it.... 
In the laser scan in a dynamic setup, it was possible that there are points at infinity, which I forgot to check.
Then the PointCloud is saved(with infinity points) but when loaded the infinity points are set at a maximum, not `NaN`. Therefore the `is_dense` parameter differs.
Now after removing these points or removing the infinite points in beforehand everything works as intended.

Thank you @mvieth  for your help
I close this issue.

**Comment by mvieth** [comment]
Happy to hear that the problem is solved for you. Do you feel like anything in PCL should be changed to prevent this problem for others? Did any function work differently than expected?

**Comment by Zarbokk** [comment]
That's a good question.

In my opinion, it would be useful to have a warning if points are `NaN`.

I would suggest that when a Point Cloud is loaded in `pcl::io::loadPCDFile()`
and `pcl::fromROSMsg()`(which is a ROS method and not directly PCL-Library I think).

Changing the Voxel filter to check for `NaN` is also an option. But I don't know if that is feasible, or fast enough.

In the end, I don't think the behavior itself should differ, since the user(me) made the error.

**Comment by mvieth** [comment]
Hm, having clouds where points are `NaN` is not uncommon and not really an "error", so a warning in the two functions you mentioned would be too invasive, I think. Every algorithm/function checks if the processed points are not `NaN` or infinite, unless `is_dense` is set to true. In VoxelGrid that is done [here](https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/impl/voxel_grid.hpp#L321), for example.
