### ISSUE TITLE
pcl::IterativeClosestPointWithNormals  has no member named ‘setUseSymmetricObjective’

### ISSUE THREAD

**Issue by Bannigo** [PointCloudLibrary/pcl#4607]
Hello Sir/Ma'am,
                          I am using pcl::1.11.1 on ubuntu 18.04 and I am trying to run ICP with the following code

pcl::IterativeClosestPointWithNormals<pcl::PointNormal, pcl::PointNormal, float> icp;
icp.setInputSource (in_with_normals);
icp.setInputTarget (out_with_normals);
icp.setUseSymmetricObjective(true);

I am not able to compile and the following error pops up:

pcl::IterativeClosestPointWithNormals<pcl::PointNormal, pcl::PointNormal, float>’ has no member named ‘setUseSymmetricObjective’
   icp.setUseSymmetricObjective(true);

How to proceed?

**Comment by mvieth** [comment]
Are you sure that you are using PCL 1.11.1? The function `setUseSymmetricObjective` is available since PCL 1.10.0. Perhaps you have multiple PCL installations and you are accidentally using the wrong one?

**Comment by Bannigo** [comment]
Hi, Thank you for your reply. Maybe it would be a problem that it gets confused with PCL1.8. I am using Ubuntu 18.04 with ROS melodic. So with that PCL 1.8 comes by default. I uninstalled PCL 1.8 and with that pcl_ros and pcl_conversions also gets removed. For my project, I do still want to use both of the packages. So how to proceed, does ROS procedure with PCL 1.11.1

**Comment by mvieth** [comment]
- You can require a specific version of a package in CMakeLists.txt, like this: `find_package(PCL 1.11.1 EXACT)`. For more information, see the cmake documentation
- You could build perception_pcl yourself (from source), then you don't need to have a specific PCL version installed

**Comment by Bannigo** [comment]
HI, Thank you so much for your reply. Can you possibly suggest me how to build perception_pcl from source. I tried doing it by my way of downloading the packahe and make a build directory and commanding cmake .. and then make -j8 followed by sudo make install. But it doesn't work and my package is not able to find perception_pcl.

**Comment by mvieth** [comment]
For instructions on how to build a package from source, please see the ROS tutorials, e.g. this one: https://wiki.ros.org/ROS/Tutorials/BuildingPackages
Assuming you already have a workspace for your own ROS package, you can just add perception_pcl next to your own package.

**Comment by Bannigo** [comment]
![Screenshot from 2021-02-22 14-24-13](https://user-images.githubusercontent.com/64646090/108714379-c2eee380-7519-11eb-8fb2-f1dfef72ab78.png)

![Screenshot from 2021-02-22 14-29-55](https://user-images.githubusercontent.com/64646090/108714998-8d96c580-751a-11eb-842f-e77e0204b86e.png)

So I tried the same thing. I just have PCL 1.11.1 and surely I deleted PCL 1.8. Still, these errors are coming. Maybe the problem is perceptionn_pcl don't know how to search for PCL 1.11.1. What do you suggest?

**Comment by mvieth** [comment]
Try one of the tutorials, let's say [this one](https://pcl.readthedocs.io/projects/tutorials/en/latest/random_sample_consensus.html#random-sample-consensus), to see whether PCL is properly installed.

**Comment by Bannigo** [comment]
Yes. It is working. I am able to execute the code.

**Comment by mvieth** [comment]
Then this does not seem like a PCL issue. If you have troubles compiling perception_pcl, you could try to seek help from that project (since PCL itself is not directly part of ROS). I can say for sure that perception_pcl (the current master) is compilable with PCL 1.11.1. You could also try to erase all PCL files and then reinstall PCL 1.11.1 to see if you accidentally missed anything from PCL 1.8. Or you try to reinstall PCL 1.8 and perception_pcl with `apt`, and specifically require PCL 1.11.1 (or any version since 1.10.0) for your own project like I suggested above. That is all the advice I can offer right now.

**Comment by Bannigo** [comment]
Okay, Sir. Thank you so much. I will close the issue from here
