### ISSUE TITLE
[tools/mesh_sampling.cpp] The option n_samples cannot work. And it cannot read the whole CAD object.

### ISSUE THREAD

**Issue by qinglew** [PointCloudLibrary/pcl#4608]
**Describe the bug**

When I use this code to generate the point cloud from the .obj file, sometimes, it cannot read the whole object, eg. the chair point cloud lacks the legs. Another problem is the option **n_samples** is not useful. It cannot generate the number of point cloud I want.

**Context**

I want to use this code to generate the point cloud as the ground truth for point cloud completion. I need to generate point cloud which contains 16384 points for every .obj file.

**Expected behavior**

I just hope that the code can read the whole object for any .obj file, and the option **n_samples** can work.

**Current Behavior**

Sometimes, the code cannot generate the whole object and the option **n_samples** cannot work.

**Screenshots/Code snippets**

The mesh_sampling.cpp has been compiled successfully.

Cannot generate the whole object:

<img src="https://github.com/qinglew/Images/blob/master/chair_obj.png?raw=true"/>

<img src="https://github.com/qinglew/Images/blob/master/chair_pcd.png?raw=true"/>

For another .obj file, it can generate the whole object, but cannot generate the number of points I want use the option **-n_samples 16384**.  The command I used is `./mesh_sampling model.obj model.pcd -n_samples 16384`.

<img src="https://github.com/qinglew/Images/blob/master/airplane_obj.png?raw=true"/>

<img src="https://github.com/qinglew/Images/blob/master/airplane_pcd.png?raw=true"/>

It has only 7494 points:

<img src="https://github.com/qinglew/Images/blob/master/points.png?raw=true"/>

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 18.04 LTS]
 - Compiler: [GCC 7.5.0]
 - PCL Version [1.10, HEAD]
 - VTK Version [9.0.1]

**Comment by mvieth** [comment]
Please see issue #4622 for the problem that mesh_sampling cannot read the whole object.
Regarding n_samples: the program first generates the samples (e.g. 16384), and then applies a VoxelGrid filter. You might be able to turn the filter of with something like `-leaf_size 0.0001`, or else you would have to remove it from mesh_sampling.cpp and recompile.

**Comment by lishawa** [comment]
Have you solved the problem that the option n_samples cannot work? I just met the same problem when batch convert mesh to point cloud. The number of some generated point clouds are not the specified.

**Comment by qinglew** [comment]
You just need to set a smaller `leaf_size` to get the number of points you want.
