### ISSUE TITLE
PCL can't read some newer .ONI files

### ISSUE THREAD

**Issue by sdmiller** [PointCloudLibrary/pcl#461]
I noticed this a few months ago, but was recently reminded by a colleague:

In openni_device.cpp, we seem to be expecting that any Depth Generator have embedded in it a ShadowValue and NoSampleValue. It seems that newer versions of openni no longer require this to be saved -- so plenty of ONI files return an error when read by PCL.

There's a simple quick fix for this: stop throwing an error, and instead default to something reasonable for these cases (e.g. 0 represents no sample -- is there a similar default for shadow?) Should we do this, or is there a deeper reason for this error?

**Comment by kunaltyagi** [comment]
Closing due to lack of interest
