### ISSUE TITLE
[pcl::KLDAdaptiveParticleFilterOMPTracker::computeTransformedPointCloudWithoutNormal] use_normal_ == true is not supported in this Point Type

### ISSUE THREAD

**Issue by Bannigo** [PointCloudLibrary/pcl#4630]
Hwllo, 
I am trying to track an object using KLD adaptive particle filter method. The object which I am using has very less features at is important to use the normals of the pointcloud.  I have a reference pointcloud and an incoming stream of pointcloud as a ROS message. I am computing point normals both the source and target pointcloud using the moving least square method. So the reference point type for the tracker is:

typedef pcl::PointNormal RefPointType;

The tracking particle is:
typedef pcl::tracking::ParticleXYZRPY ParticleT;

I am calling the tracker as 

boost::shared_ptr<pcl::tracking::KLDAdaptiveParticleFilterOMPTracker<RefPointType, ParticleT>> tracker
        (new pcl::tracking::KLDAdaptiveParticleFilterOMPTracker<RefPointType, ParticleT> (8));

Using coherences as:
pcl::tracking::ApproxNearestPairPointCloudCoherence<RefPointType>::Ptr coherence = pcl::tracking::ApproxNearestPairPointCloudCoherence<RefPointType>::Ptr
        (new pcl::tracking::ApproxNearestPairPointCloudCoherence<RefPointType> ());

    pcl::tracking::DistanceCoherence<RefPointType>::Ptr distance_coherence = pcl::tracking::DistanceCoherence<RefPointType>::Ptr
        (new pcl::tracking::DistanceCoherence<RefPointType> ());

While performing tracker->compute()

I am getting following errors:=
 [pcl::KLDAdaptiveParticleFilterOMPTracker::computeTransformedPointCloudWithoutNormal] use_normal_ == true is not supported in this Point Type

and also  showing that 

[pcl::ApproxNearestPairPointCloudCoherence::compute] target_input_ is empty!

Indeed the target point normal has 4832 points and corresponding normals for that. I am using PCL 1.11.1. Can you suggest how to proceed in this situation?

Regards,
Yash

**Comment by mvieth** [comment]
Did you check out this tutorial: https://pcl.readthedocs.io/projects/tutorials/en/latest/tracking.html?

**Comment by Bannigo** [comment]
Yes, I check that tutorial before, So in that tutorial, they haven't used the normals of the pointcloud and kept tracker_->setUseNormal(false);
So I have an assumption that the tracker works with normals as well so I have calculated the normals and I am using refPointtype as PointNormal and have changed setUseNormal from false to true. My objects have very few features and ICP point-to-point registration doesn't work in my case. Certainly point to plane with normals does work in my case. That's why I am planning to use particle filters with point normals to track the point cloud.

**Comment by Bannigo** [comment]
Is there any way to use tracker with normals of a pointcloud?

**Comment by Bannigo** [comment]
https://github.com/PointCloudLibrary/pcl/issues/727 . This is similar to my issue

**Comment by mvieth** [comment]
Did you test the solution from the issue you linked? I.e. adding the two defines before your includes?

**Comment by rabaho** [comment]
@mvieth Why can't we improve this by replacing the conditional compilation? I find it painful to require consumers of this library to define something for their code to work. Plus, that condition is not even documented, somebody has to look in the code to figure it out.

**Comment by mvieth** [comment]
> @mvieth Why can't we improve this by replacing the conditional compilation? I find it painful to require consumers of this library to define something for their code to work. Plus, that condition is not even documented, somebody has to look in the code to figure it out.

I generally agree with you, but looking at [particle_filter.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/tracking/include/pcl/tracking/impl/particle_filter.hpp#L295-L326) and [kld_adaptive_particle_filter.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/tracking/src/kld_adaptive_particle_filter.cpp), the conditional compilation is used because `computeTransformedPointCloudWithNormal` would not compile if `PointInT` does not have a normal. It just seems that [here](https://github.com/PointCloudLibrary/pcl/blob/master/tracking/include/pcl/tracking/impl/kld_adaptive_particle_filter_omp.hpp#L90), the wrong version of that function is used. If you have an idea how to solve that, you are very welcome to create a pull request :+1:

**Comment by kunaltyagi** [comment]
@rabaho The original authors weren't really into meta-programming, and it was added a bit later than the original design. As always, some sharp edges are still around.

@Bannigo Could you try my PR and see if that resolves the issues? I've removed the dependence on macro, and am instead using the point type itself to figure out the correct function to use.
