### ISSUE TITLE
[geometry] Update mesh_indices.h to not need a generator file

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4633]
**Context**

Currently, multiple copies of similar code is generated via a python file.

**Expected behavior**

It'd be better to instead use templates to get the expected behavior since only the filename is different.

[File in question](https://github.com/PointCloudLibrary/pcl/blob/master/geometry/include/pcl/geometry/mesh_indices.h)

**Comment by jmaiolini** [comment]
Hi @kunaltyagi, if possible I would like to take this issue. 
You want to get rid of the generator, right? 
Since is my first issue, can you give me another file as example for structure/naming convention to follow?

**Comment by kunaltyagi** [comment]
The contents of the python file can be converted into a template class.
```cpp
template <class Tag>
class IndexImpl {
// all details considering only IndexImpl
};

using FirstClass = IndexImpl<struct FirstClassTag>;
using SecondClass = IndexImpl<struct SecondClassTag>;
```
This allows two classes to have exactly the same API, ABI, except they aren't the same for the compiler.

Hope this makes sense

**Comment by jmaiolini** [comment]
Perfectly clear, thank you. 
Do you want me to modify the python generator such it will write a single template class or can I work directly on the .h file?
I will use IndexImpl as the class name for the template, is that ok?

**Comment by jmaiolini** [comment]
Perfectly clear, thank you.
Do you want me to modify the python generator such it will write a single template class or can I work directly on the .h file?
I will use IndexImpl as the class name for the template, is that ok?

**Comment by kunaltyagi** [comment]
Please work directly on the .h file since the aim is to remove the python file.

`IndexImpl` is a bad name :) Please use something more relevant, like `TaggedIndex` or something else that tells what the class is.

PS: the main class would go in `pcl::detail` namespace

**Comment by jmaiolini** [comment]
Fair enough, I'll post the file here before opening a PR in any case.

**Comment by kunaltyagi** [comment]
That's hard to review. Please open a PR and we'll discuss there :)

**Comment by mvieth** [comment]
@kunaltyagi I guess this can be closed now?
