### ISSUE TITLE
[custom] Out of hard memory running a cmake

### ISSUE THREAD

**Issue by iamsavva** [PointCloudLibrary/pcl#4637]
Hi, I was compiling PCL from master on a TX2, running Ubuntu 18.04, with CUDA support enabled. My cmake looked like this:
`cmake -DBUILD_GPU=ON -DBUILD_CUDA=ON -DCUDA_ARCH_BIN=6.2 -DCUDA_ARCH_PTX=6.2 -DBUILD_cuda_io=ON ..`, and ran `sudo make install`.

Before starting the cmake (i'm using gcc), I had 10gb of memory available on the TX2. After compiling everything (took about 7 hours), the cmake terminated with an error when it was installing / linking all the executables - the machine ran out of memory completely (not RAM, but regular memory). The TX2 isn't booting up now - the plan is to reflash it.

I was wondering as to why I am running out of memory. I am a novice when it comes to cmakes, so if somebody has a minute to enlighten me - I'd really appreciate it:)

1. Is it because pcl with CUDA is very large (does anyone have an estimate of the size btw)? It seems that way, since the cmake failed at the very last stage when it was installing each sub library.
2. I always thought that cmake is using computer memory in a temporary fashion during the build - like a cache - and would then clear it up after it's done. Is that correct? Or is it only using ram / swap space?
3. Would it be correct to say that to ensure that I don't use up all the memory, I should run `make install` first and then `sudo make install` (trying to install for the entire machine) - to give sudo privileges only if they are necessary? (i.e. it would throw an error ~when it's at 200mb)?
4. Can I delete the git repo together with the build directory after that? I thought that `make install` would transfer everything under `usr/bin`, hence I can remove the git / build directory, correct?
5. Are there any commands that ensure efficient memory usage / cleaning during cmake execution? Any tips on that? I know I should run it with too many threads or i'd run out of ram - are there any other things that should be considered?

Like I said - I am a novice with cmakes, so I would be really-really thankful if smbd could enlighten me on this:) cheers.

**Comment by mvieth** [comment]
1. My build folder is around 18 GB. This might be smaller or bigger for you, just saying that it is very possible that it exceeds 10 GB. Not sure if specifically CUDA makes it so large. You can try to disable the build for modules you do not need.
2. Yes, cmake/make/the compiler/the linker all store intermediary files on your hard drive. It think they do not automatically delete these, you would have to give the command.
3. Giving sudo privileges only when necessary is always a good idea, but why would it throw an error at 200mb? If you do `make install` it will probably compile/link everything and then fail when trying to copy to `/usr/...`
4. Yes, that should work
5. Sorry, no idea, google might help you there

**Comment by iamsavva** [comment]
@mvieth, thank you so much for such a detailed reply, you are awesome! One more follow up question. Even though the build folder might be 18GB, most of these are the intermediary files - correct? The executables that are then copied to /use/bin are a small portion of that, right?

**Comment by mvieth** [comment]
On my computer, the libraries are around 3 GB, the executables around 1.5 GB.

**Comment by larshg** [comment]
If you don't need all point types, you can set ONLY_CORE_POINTTYPE - not sure of the exact flag name. You'll have to look for it.

**Comment by kunaltyagi** [comment]
This is some good advice. Thoughts on adding this to the wiki FAQ under the header: How do I reduce the memory footprint of PCL compilation?
