### ISSUE TITLE
[3rd Party VTK] missing file "vtkalglib-8.2.lib"

### ISSUE THREAD

**Issue by alexis-shi** [PointCloudLibrary/pcl#4649]
l have downloaded the latest version of pcl , but in the directory <3rd Party VTK> there is no file named "vtkalglib-8.2.lib" while others have. 

my environment:
 - OS: Win10
 - PCL Version :1.11.1

**Comment by DISAPPEARED13** [comment]
could you please tell me how you fixed this problem? I just know that vtkalglib seems removed in VTK8.2, but I don't know how to find the replacement for using it.
