### ISSUE TITLE
Make tracking API more user friendly

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4655]
An option would be to call `computeTransformedPointCloudWithoutNormal` inside the `HasNoNormal` variant (in addition to the warning) and/or to only allow setting `use_normal_` to true if the point actually has a normal inside `setUseNormal`

_Originally posted by @mvieth in https://github.com/PointCloudLibrary/pcl/issues/4643_
_Slightly edited by @kunaltyagi_

**Comment by mvieth** [comment]
Hello and welcome! Great that you want to improve PCL!
Sorry, I am not totally sure what you want to modify. Do you mean in particle_filter.h or in particle_filter.hpp?
Some more information about the issue: if a user uses `ParticleFilterTracker` with a point type that does not have a normal (e.g. `PointXYZRGBA`), but tells the tracker to use the normal (with `setUseNormal(true)`), the tracker does not work, it only prints the warning. So one idea would be to call `computeTransformedPointCloudWithoutNormal` inside `computeTransformedPointCloudWithNormal`, after printing the warning. Another idea would be to check whether the point has a normal inside `setUseNormal`, if it does not have a normal and the user wants to set it to `true`, set it to `false` instead and print a warning. I think I would prefer the second option.

**Comment by NehilDanis** [comment]
> Hello and welcome! Great that you want to improve PCL!
> Sorry, I am not totally sure what you want to modify. Do you mean in particle_filter.h or in particle_filter.hpp?
> Some more information about the issue: if a user uses `ParticleFilterTracker` with a point type that does not have a normal (e.g. `PointXYZRGBA`), but tells the tracker to use the normal (with `setUseNormal(true)`), the tracker does not work, it only prints the warning. So one idea would be to call `computeTransformedPointCloudWithoutNormal` inside `computeTransformedPointCloudWithNormal`, after printing the warning. Another idea would be to check whether the point has a normal inside `setUseNormal`, if it does not have a normal and the user wants to set it to `true`, set it to `false` instead and print a warning. I think I would prefer the second option.

Hey, is this issue still open? I mean it looks like, but I wanted to make sure. If so, I can handle it. Thanks

**Comment by mvieth** [comment]
It seems like no one is working on this currently, and nobody has opened a pull request. So if you want to solve this, you are welcome to do it!

**Comment by NehilDanis** [comment]
> It seems like no one is working on this currently, and nobody has opened a pull request. So if you want to solve this, you are welcome to do it!

So basically I just used SFINAE in `setUseNormal` in particle_filter.h, just like it was done for `computeTransformedPointCloudWithNormal`
