### ISSUE TITLE
[CI] Windows x64 CI can't find Boost

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4658]
```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem date_time
  iostreams system) (Required is at least version "1.55.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
  cmake/pcl_find_boost.cmake:34 (find_package)
  CMakeLists.txt:393 (include)
-- Configuring incomplete, errors occurred!

```

Taken from [this CI run](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=18412&view=logs&j=b2e91478-826b-5668-35a1-2ffb6cc2ce81&t=7e072d12-9c35-5a96-2043-81e7c05cb12e&l=109)

**Comment by kunaltyagi** [comment]
Pinging @larshg

**Comment by larshg** [comment]
https://github.com/actions/virtual-environments/issues/2667

Boost is being removed altogether.

So we have to get it elsewhere, like everyone else:

- VCPKG install (takes time, due to being compiled)
- Download from scourgeforge
- Conan install

**Comment by kunaltyagi** [comment]
Any updates on the Windows docker? That'll help a lot for issues like this

**Comment by Chris45215** [comment]
> [actions/virtual-environments#2667](https://github.com/actions/virtual-environments/issues/2667)
> 
> Boost is being removed altogether.
> 
> So we have to get it elsewhere, like everyone else:
> 
> * VCPKG install (takes time, due to being compiled)
> * Download from scourgeforge
> * Conan install
> * Other?

doesn't the vcpkg lack the visualization toolkit? That sounds like this will become even more problematic. Otherwise, the vcpkg version of the project is the only one that I can get to work.

**Comment by kunaltyagi** [comment]
The Windows CI doesn't install visualization right now. This is an issue with just the CI, not PCL on windows.
