### ISSUE TITLE
How to find the boundary points of 3D point of cloud using pcl library

### ISSUE THREAD

**Issue by nikhilpatil99** [PointCloudLibrary/pcl#4663]
Respected All,
I have a set of 3D data points which look uniform plane. I want to find boundary points of that 3D points. I was researching and found the PCL library. I am very excited to work with this library. Based on this, I tried to do find out boundary points using the range_image_border_extraction.CPP. But, I am unable to do find it using PCL. I need to find out since I want to work on further processes using simulation, based on these boundary points.
I have attached the link to the ".pcd" file. I would like to know how to work with pcl to get such a kind of boundary points.
[pcd file link](https://drive.google.com/file/d/1J3-zqT7KhhN_4YoVpedPqGAJcBmZcGwr/view?usp=sharing)

Any leads will be appreciated.
Thanks in advance

**Comment by larshg** [comment]
Don't open these issue @nikhilpatil99. You have to read and learn cpp and how to use PCL from the existing tutorials. These issues are for errors in PCL.
