### ISSUE TITLE
[custom] Is there any way to disable warnings when loading ply cloud?

### ISSUE THREAD

**Issue by garryz94** [PointCloudLibrary/pcl#4673]
When I read ply file into my custom defined pointcloud, PCL always outputs warnings like "Failed to find match for ...". Is there any way to disable this warning?

![Screenshot from 2021-03-25 10-38-28](https://user-images.githubusercontent.com/63033682/112410548-4d637680-8d56-11eb-9537-27658525a9b9.png)

**Comment by kunaltyagi** [comment]
Not an issue. Environment variable (on linux like systems) `PCL_VERBOSITY_LEVEL` can be set to `ERROR` to reduce information printed on the terminal

**Comment by garryz94** [comment]
> Not an issue. Environment variable (on linux like systems) `PCL_VERBOSITY_LEVEL` can be set to `ERROR` to reduce information printed on the terminal
> 
> Please use discord for questions like this

So I should modify "pcl/cmake/pcl_verbosity.cmake" to set PCL_VERBOSITY_LEVEL to Error?
