### ISSUE TITLE
Runtime error :: PCL bilateral filter

### ISSUE THREAD

**Issue by Bannigo** [PointCloudLibrary/pcl#4676]
Hello,
I am facing a runtime error while processing the bilateral filter. 

Error-:
processing: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = std::vector<int>; typename boost::detail::sp_member_access<T>::type = std::vector<int>*]: Assertion `px != 0' failed.
Aborted (core dumped)

Code snippet-:

pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_p (new pcl::PointCloud<pcl::PointXYZI>);
pcl::search::KdTree<pcl::PointXYZI>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZI>);
pcl::BilateralFilter<pcl::PointXYZI> bf;
pcl::PointCloud<pcl::PointXYZI> cloud_bilateral;

bf.setInputCloud(cloud_p); 
bf.setHalfSize(2.0);
bf.setSearchMethod (tree);
bf.setStdDev(0.2);
bf.applyFilter(cloud_bilateral);

I have tried a lot of things, but haven't been able to find a solution. Do you know a way out. Thank you in advance!!

**Comment by mvieth** [comment]
`cloud_bilateral` has to be initialized like `cloud_p`, with `new pcl::PointCloud ...`

**Comment by Bannigo** [comment]
pcl::BilateralFilter<pcl::PointXYZI> bf (new pcl::BilateralFilter<pcl::PointXYZI>);

pcl::PointCloud<pcl::PointXYZI> cloud_bilateral;
bf->setInputCloud(cloud_p);
bf->setHalfSize(2.0);
bf->setSearchMethod (tree);
bf->setStdDev(0.2);
std::cout<< "Hello" <<std::endl;
bf->applyFilter(cloud_bilateral);

Now the code snippet looks like these. It's still the same issue.

**Comment by mvieth** [comment]
Oh sorry, I misread your code. I will try to further look into the issue tomorrow.
What version of PCL do you use? What operating system?
Have you noticed that the problem only occurs with specific point clouds, or with any clouds?
If you could run your code with a debugger (e.g. valgrind/gdb) to pinpoint where the error happens, that would be very helpful.

**Comment by mvieth** [comment]
I think I found the problem: you should call `bf.filter(cloud_bilateral)` instead of `bf.applyFilter(cloud_bilateral)`. `filter` calls `applyFilter`, but first sets the variable `indices_`, which is used [here](https://github.com/PointCloudLibrary/pcl/blob/97cb436308e240c34f49559ba3b89b6cdfc2e5ca/filters/include/pcl/filters/impl/bilateral.hpp#L102).
`applyFilter` should probably be `protected`, not `public`, in `BilateralFilter`, to avoid such a misunderstanding. If you like, you can open a pull request to fix that.

**Comment by Bannigo** [comment]
Yaa!! this solution fixed it up. Thank you so much. I will open a pull request

**Comment by mvieth** [comment]
@Bannigo Are you still interested in opening a pull request? It is probably a one-line-fix

**Comment by Bannigo** [comment]
I am actually interested in doing it. But I don't know the procedure. Besides sorry for the late reply, I am a bit stuck in writing my thesis.

**Comment by mvieth** [comment]
> I am actually interested in doing it. But I don't know the procedure. Besides sorry for the late reply, I am a bit stuck in writing my thesis.

No problem, good look with the thesis!
The procedure is like this (very condensed):
1. Fork this repository, clone the fork to your computer
2. Create a new branch in git and switch to it
3. Make the change
4. Make a git commit with the change
5. Push the commit and create the pull request. If you use the git terminal tool, it will offer a link to create the pull request when you push

If you don't have time right now, that is totally fine. I can make the change, and you can still try to create a pull request for something else when you have time - e.g. fixing one of the "good first issues"

**Comment by ArkaprabhaChakraborty** [comment]
Can I make this change? It's been there for a while I guess and It will also help me get started with contributing to this library.

**Comment by mvieth** [comment]
> If this hasn't been done yet, can I make this change? It's been there for a while I guess and It will also help me get started with contributing to this library.

Yes! Feel free to open a pull request
