### ISSUE TITLE
[pcl_features] Segfault while executing multiscale_feature_persistence_example

### ISSUE THREAD

**Issue by NehilDanis** [PointCloudLibrary/pcl#4679]
**Describe the bug**

Hi, I was following [this](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.11.1/apps/src/multiscale_feature_persistence_example.cpp) example, and I tried to use it with my own pcd file, but I got segmentation fault. I was debugging and I found out that the following code caused the problem, in particular the line number 98. 

https://github.com/PointCloudLibrary/pcl/blob/97cb436308e240c34f49559ba3b89b6cdfc2e5ca/features/include/pcl/features/impl/multiscale_feature_persistence.hpp#L89-L100

I changed the line 98 as the following:

```
features_at_scale_.push_back(feature_cloud); 
```
And then it worked.

**Context**

I needed to create an initial alignment for the ICP algorithm and for that I was trying to use multiscale feature descriptor. 

**Expected behavior**

To not crush

**Current Behavior**

Segmentation Fault

**To Reproduce**

Just execute the following [example](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.11.1/apps/src/multiscale_feature_persistence_example.cpp) with any point cloud data.

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Compiler:  GCC 7.5 and GCC 8.4
 - PCL Version: release 1.11.1(d983131)

**Possible Solution**

Use push_back instead of the assignment operator.

**Comment by mvieth** [comment]
Thank you for reporting this!
I can confirm the bug and like your solution. Would you be willing to open a pull request with the fix?
It seems like there is no unit test for `MultiscaleFeaturePersistence` (or else we would have noticed the bug sooner). Would you be interested in writing one?

**Comment by NehilDanis** [comment]
Hello, thanks a lot for the quick reply. Yes I will do this!

**Comment by larshg** [comment]
I'm wondering, isn't the features_at_scale_ resized/reserved the size in line 92, as the size of scale_values_, which is the one that is used in the for loop as well. Is there an out of bound indexing going on, but why? Is it the wrong size returned?

Just appending to the array, kinda contradicts the  "feature at scale i" doesnt it? (Even though it seems to go from 0 to size)

**Comment by NehilDanis** [comment]
Hello, so the thing is resizing and reserving a vector are different things. If you resize the vector, which means you use the constructor and you actually can access the elements using the squared brackets. So resize actually initializes the newly allocated vector while reserve allocates but not constructs, so it shows undefined behaviour. During the debug, the first and second element was placed into the vector without no issue and when it comes to the third element segfault occured. To prevent such undefined behaviours it is better to reserve and use push_back. You can also do resize and use the squared brackets to access the assing value but first approach is faster since it doesnt constructs!
