### ISSUE TITLE
Information on correspondence estimation back projection

### ISSUE THREAD

**Issue by Bannigo** [PointCloudLibrary/pcl#4684]
Hello everyone,
                         I have a doubt about the description of the Correspondence estimation back-projection method. The description seems to be incomplete. Does anyone know on which research paper, it's based?

Thank you in advance

**Comment by mvieth** [comment]
Sorry, no idea. It might not even be based on a specific paper. If you want to learn more about the class, you might have to look into the implementation.

**Comment by Bannigo** [comment]
Okay. Thank you!!
