### ISSUE TITLE
ERROR:#if VTK_RENDERING_BACKEND_OPENGL_VERSION < 2

### ISSUE THREAD

**Issue by Foward-Fu** [PointCloudLibrary/pcl#4687]
When I use pcl to view show simple point cloulds with c++ in Viusal Studio 2019, It could`t compile.The errors are as follow:
![image](https://user-images.githubusercontent.com/62982151/113398328-01a57280-93d1-11eb-8b42-b34fc79a30d0.png)
![image](https://user-images.githubusercontent.com/62982151/113398369-0f5af800-93d1-11eb-8a50-98a903a9dd02.png)
![image](https://user-images.githubusercontent.com/62982151/113398390-171a9c80-93d1-11eb-84d9-d2df03e19ff2.png)

my environment is as follow:
 - OS: Windows 10 
 - Compiler: Visual Studio 2019
 - PCL Version 1.11.1
 - PCL Type: use vcpkg installed

Thank you for you help.

**Comment by mvieth** [comment]
Do you have some option enabled to turn warnings into errors? Please check that and disable it.
Also: we are currently using VS 2017 in our CI, so we can't guarantee that it works with VS 2019 yet.

**Comment by larshg** [comment]
I'm using VS2019, so that is not an issue.

How have you made your test project? Cmake?

**Comment by Foward-Fu** [comment]
> 我正在使用VS2019，所以这不是问题。
> 
> 您是如何进行测试项目的？

I just compile the project in VS2019,This may be because the PCL version and the VKT version do not correspond

**Comment by Kush-Sh** [comment]
Go to solution properties -> C++ -> preprocessor -> Preprocessor Definitions and copy paste this,
_CRT_SECURE_NO_WARNINGS

This might help you!

**Comment by larshg** [comment]
Seems there are unrecognized characters in the code file. Not sure if this also impacts the problem. `VTK_RENDERING_BACKEND_OPENGL_VERSION` seems to be correctly defined, but shows as an error, but works here and on soon to merged med docker CI.

I don't recognize this as in bugs in PCL, but settings locally in Visual studio. Closing it, but feel free to add more information and continue discussion.

**Comment by larshg** [comment]
I just met this error when building a down-stream project, which reference the VCPKG version of PCL.

I think the reason is that Visualization is disabled in VCPKG at the moment and it leads to:
`#define VTK_RENDERING_BACKEND_OPENGL_VERSION ` being just defined, but not as 1 or 2 which it is supposed to.

So you'd have to remove PCL from VCPKG and compile PCL from source, having only the dependencies installed from VCPKG.
