### ISSUE TITLE
Line by mistake?

### ISSUE THREAD

**Issue by kd-mariyan** [PointCloudLibrary/pcl#4692]
https://github.com/PointCloudLibrary/pcl/blob/d98313133b014553ab1b1b5b112f9aade837d55c/doc/tutorials/content/sources/planar_segmentation/planar_segmentation.cpp#L64

**Comment by mvieth** [comment]
Thank you for noticing, yes it seems like that should have been removed in commit 009d73dbb51fcea8dbf8daeb1229dbb48e0f3870 . Would you be interested in creating a pull request to fix this?

**Comment by mvieth** [comment]
I was not sure whether you want to create a pull request, so I removed the extra line in pull request #4697 myself.
If you want to contribute to PCL, feel free to check out the other open issues.
