### ISSUE TITLE
[Runtime error] thrust::system::system_error, Two parts of codes work fine separately, but doesn't work together.

### ISSUE THREAD

**Issue by TuMePJlaH** [PointCloudLibrary/pcl#4700]
PCL version: 1.11.1 (build from last master branch);
OS: Ubuntu 20.04.
Compiler: GCC 9.3.0
GPU: GeForce RTX 2080Ti
CUDA Toolkit version: 11.1

Init cloud code:
```cpp
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
int y_size = 100;
int x_size = 100;
cloud->is_dense = true;
for (int y = 0; y < y_size; ++y) {
  for(int x = 0; x < x_size; ++x) {
    pcl::PointXYZ p(x, y, 0.0f);
    cloud->push_back(p);
  }
}
pcl::gpu::NormalEstimation::PointCloud cloud_device;
cloud_device.upload(cloud->points);
```

This code work fine:
```cpp
pcl::gpu::Octree octree_device;
octree_device.setCloud(cloud_device);
octree_device.build();
int max_ans = 100;
pcl::gpu::NeighborIndices indices;
octree_device.radiusSearch(cloud_device, 10.1, max_ans, indices);
```

And this code work fine:
```cpp
pcl::gpu::NeighborIndices indices = createNeighboursIndices(cloud, 150);
pcl::gpu::NormalEstimation ne;
pcl::gpu::NormalEstimation::Normals normals;
pcl::gpu::NormalEstimation::computeNormals(cloud_device, indices, normals);
```

But this code (previous two parts of codes together):
```cpp
pcl::gpu::Octree octree_device;
octree_device.setCloud(cloud_device);
octree_device.build();
int max_ans = 100;
pcl::gpu::NeighborIndices indices;
octree_device.radiusSearch(cloud_device, 10.1, max_ans, indices);

pcl::gpu::NormalEstimation ne;
pcl::gpu::NormalEstimation::Normals normals;
pcl::gpu::NormalEstimation::computeNormals(cloud_device, indices, normals);
```
and this code too (previous two parts of codes together):
```cpp
pcl::gpu::NeighborIndices indices = createNeighboursIndices(cloud, 150);
pcl::gpu::NormalEstimation ne;
pcl::gpu::NormalEstimation::Normals normals;
pcl::gpu::NormalEstimation::computeNormals(cloud_device, indices, normals);

pcl::gpu::Octree octree_device;
octree_device.setCloud(cloud_device);
octree_device.build();
int max_ans = 100;
pcl::gpu::NeighborIndices indices2;
octree_device.radiusSearch(cloud_device, 10.1, max_ans, indices2);
```

aborted with runtime error:
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 2nd step: cudaErrorInvalidConfiguration: invalid configuration argument
Aborted (core dumped)

**Comment by ueqri** [comment]
The error comes from an unresolved bug from Thrust library, when using the `thrust::sort` and `thrust::sort_by_key`.

Similar issue here: https://github.com/thrust/thrust/issues/936, and it seems that this error could be a result of a architecture mismatch, not very sure.

Did you provide `CUDA_ARCH_BIN` as the real compute capabilities of GPU for CMake command? If not, you can try to specify the arch for compile. For _GeForce RTX 2080Ti_ , this can be `-DCUDA_ARCH_BIN="7.5"` exactly. I hope this could help for now.

**Comment by TuMePJlaH** [comment]
Thanks for your reply!
I set CUDA_ARCH_BIN to 7.5 and re-compiled PCL.
But it did not help.

**Comment by kunaltyagi** [comment]
Doesn't seem like a bug in PCL (directly), so I'm in favor of closing the issue, but letting the discussion continue. Thoughts @mvieth?

**Comment by mvieth** [comment]
I agree, seems like that can only be solved in the thrust library. They are asking for a minimal reproducible example, so if someone who experiences this bug can create such an example, that would surely help fixing this bug.

**Comment by kunaltyagi** [comment]
Ack. Closing the issue here.

@TuMePJlaH if you could assist Thrust in resolving this issue, that'd be great :)
