### ISSUE TITLE
[Search module] Different speed of execution of the same code

### ISSUE THREAD

**Issue by TuMePJlaH** [PointCloudLibrary/pcl#4709]
OS: Ubuntu 20.04
Compiler: GCC 9.3.0
PCL Version: 1.11 (build from last master branch 21/04/16)

CMakeList.txt
```cmake
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)

set (p_name search_speed_test)

project(${p_name})

set(CMAKE_INCLUDE_CURRENT_DIR ON)

find_package(PCL 1.11 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (
  ${p_name} 
  main.cpp)
target_link_libraries (${p_name} ${PCL_LIBRARIES})
```

main.cpp:
```cpp
#include <iostream>
#include <chrono>

#include <pcl/point_cloud.h>
#include <pcl/search/kdtree.h>

#include <pcl/search/impl/flann_search.hpp>

int main(int argc, char** argv)
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);

    int x_size = 1000;
    int y_size = 1000;
    for (std::size_t y = 0; y < y_size; ++y) {
        for (std::size_t x = 0; x < x_size; ++x) {
            pcl::PointXYZ point(x, y, 0);
            cloud->push_back(point);
        }
    }

    auto begin = std::chrono::steady_clock::now();

    pcl::search::KdTree<pcl::PointXYZ>::Ptr kdtree (new pcl::search::KdTree<pcl::PointXYZ>);
    kdtree->setInputCloud(cloud);

    auto end = std::chrono::steady_clock::now();
    auto elapsed_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - begin);
    std::cerr << "Duration = " + std::to_string(elapsed_ms.count() / 1000.0f) << std::endl;

    //This line!!!
    pcl::search::FlannSearch<pcl::PointXYZ>::Ptr flann (new pcl::search::FlannSearch<pcl::PointXYZ>);

    return 0;
}
```

Program output: "Duration = 0.411" (bin file size 767K).
Program output without FlannSearch initialize line: "Duration = 0.116" (bin file size 133K).
I understand that when I include the FlannSearch initialization line, I add some of the PCL library to my program, which increases the size of the binary.
But I don't understand why the other part of my code starts working so much slower?
How can I avoid this in the future when I include other PCL library functionality?

**Comment by larshg** [comment]
How many times have you run the 'tests'? Could just be variation in other workloads on the PC.

I don't see why the measured part should be slower due to adding the offending line.

**Comment by TuMePJlaH** [comment]
Thanks for the quick response!

I have run many times, with and without this line. Since I could not believe it myself.
At this point, there were no other calculations on the PC.
I checked this problem on two PC's.

**Comment by kunaltyagi** [comment]
Tried and succeeded in replicating the issue. My PCL is built manually (in debug mode, at master, not 1.11 or some release).

Observations:
```
$ cmake .. && make && ./search_speed_test
Duration = 0.2 (approx)
$ cmake .. -DWITH_SEARCH && make && ./search_speed_test
Duration = 0.75 (approx)

$ cmake .. -DCMAKE_BUILD_TYPE=Release && make && ./search_speed_test
Duration = 0.2 (approx)
$ cmake .. -DWITH_SEARCH -DCMAKE_BUILD_TYPE=Release && make && ./search_speed_test
Duration = 0.19 (approx)
```

* Size without search: 41,432 bytes
* Size with search: 195,104 bytes

Conclusion:
* binary size doesn't impact speed
* not a bug in PCL. Please check the arguments used for compilation and linking

I believe that PCL in release mode will give similar results. The result observed by you could be an artifact of your toolchain re-ordering some functions around. Please consider using release builds or using memory barriers to reduce such pessimizations by the compiler.

**Comment by TuMePJlaH** [comment]
Thank you!
That really helped!
