### ISSUE TITLE
[search] Convert "test" to benchmark

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4718]
This "test" doesn't really belong here?

It seems to capture processing times, but don't print or use them / compare them?

_Originally posted by @larshg in https://github.com/PointCloudLibrary/pcl/pull/4712#discussion_r617306815_

**Comment by mvieth** [comment]
For anyone interested: benchmarks are added now, you can orient yourself at the existing benchmark(s).

**Comment by kunaltyagi** [comment]
Added a new label for the new module. Should have done that before :)

**Comment by Zekrom-7780** [comment]
Hey, @mvieth can I work on this issue?

**Comment by mvieth** [comment]
@Zekrom-7780 Yes, you can work on this issue. Thank you!

**Comment by Zekrom-7780** [comment]
@mvieth @kunaltyagi I AM SOO SORRY, for reaching THIS late, but is this Still open?
If yes, then I would still like to work on it

**Comment by mvieth** [comment]
@Zekrom-7780 Sure, go ahead.

**Comment by Zekrom-7780** [comment]
@mvieth , I finished setting up the repo, and I saw like an entire test folder, and a benchmarks folder. Could you tell me on how to proceed with this?

So sorry if this is a dumb question

**Comment by mvieth** [comment]
The goal is to convert this test: https://github.com/PointCloudLibrary/pcl/blob/e8ed4be802f7d0b1acff2f8b01d7c5f381190e05/test/search/test_organized_index.cpp#L359
to a proper benchmark (like the other benchmarks in the benchmarks folder). Notice how the test measures the time needed by `setInputCloud` and `radiusSearch`. The brute force search that is also performed in the test is pretty much useless and can be discarded.

**Comment by Zekrom-7780** [comment]
Thanks for the explanation @mvieth , I have made a [pull request](https://github.com/PointCloudLibrary/pcl/pull/5851), could you please look into it?

Also, please could you tell me on how to get the build checks to pass, like which script do I have to run?

Also, as mentioned in the pull request, Soo Sorry that I wasn't able to rebase the multiple commits into a single one

**Comment by larshg** [comment]
Fixed by #5851
