### ISSUE TITLE
[addText3D] is Support UTF-8 ?

### ISSUE THREAD

**Issue by jiaobinbin152** [PointCloudLibrary/pcl#4721]
addText3D(std::string("我是谁"),position,1,255,0,0,"cubeTrackId");

don‘t work!

**Comment by mvieth** [comment]
You already opened issue #4717 with the same problem. Please do not open duplicate issues!

**Comment by jiaobinbin152** [comment]
> You already opened issue #4717 with the same problem. Please do not open duplicate issues!

OK, Sorry.
