### ISSUE TITLE
Line segmentation SACMODEL_LINE wrong coefficients

### ISSUE THREAD

**Issue by alex-stonebridge** [PointCloudLibrary/pcl#4722]
Hello, I receive a point cloud from laser scanner and I want to detect a line there. I use SACMODEL_LINE to find the line and its coefficients. According the documentation, the coefficients vector has a next structure https://pointclouds.org/documentation/classpcl_1_1_sample_consensus_model_line.html
    point_on_line.x : the X coordinate of a point on the line
    point_on_line.y : the Y coordinate of a point on the line
    point_on_line.z : the Z coordinate of a point on the line
    line_direction.x : the X coordinate of a line's direction
    line_direction.y : the Y coordinate of a line's direction
    line_direction.z : the Z coordinate of a line's direction
That is what I receive:
![Wux0K2AijKM](https://user-images.githubusercontent.com/75436493/115727692-24012f00-a384-11eb-9933-6224e4969556.jpg)
Then, I use pcl::visualization::PCLVisualizer to visualise the segmented line of points and I use addLine function to draw a line between point_on_line.x,point_on_line.y and line_direction.x,line_direction.y points. This line has a red color on the picture. As it can be seen, the orientation of this line is completely different from the segemented line. What should I do to get the actual orientation of the segmented line?
![h8R8WRVg6LE](https://user-images.githubusercontent.com/75436493/115728007-69256100-a384-11eb-85cd-7059379fdca1.jpg)

**Comment by mvieth** [comment]
Maybe I misunderstood you: you tried to draw a line from point (0.158, 0.001, 0.0) to point (0.007, -0.999, 0.0)?
The first three components are the coordinates of a point on the line, but the next three components are the _direction_  of the line as a normalized vector.

**Comment by alex-stonebridge** [comment]
> Maybe I misunderstood you: you tried to draw a line from point (0.158, 0.001, 0.0) to point (0.007, -0.999, 0.0)?
> The first three components are the coordinates of a point on the line, but the next three components are the _direction_ of the line as a normalized vector.

You actually understood me correctly. However, could you please help me to come from that direction to the second point or the line equation probably. There must be some insanely simple math I suppose.

**Comment by mvieth** [comment]
The line equation could be simply `point_on_line + r * line_direction`, where `r` is a real number. So for _a_ second point on the line you can just add `point_on_line` and `line_direction`. But remember that RANSAC (and the other sample consensus methods) finds an infinite line, not finite line segment.

**Comment by alex-stonebridge** [comment]
> The line equation could be simply `point_on_line + r * line_direction`, where `r` is a real number. So for _a_ second point on the line you can just add `point_on_line` and `line_direction` (then `r=1`). But remember that RANSAC (and the other sample consensus methods) finds an infinite line, not a finite line segment.

Thank you, now it works perfectly.
![image](https://user-images.githubusercontent.com/75436493/115735329-b0aeeb80-a38a-11eb-97aa-b0391ed966af.png)
