### ISSUE TITLE
Running PCL algorithms on GPU

### ISSUE THREAD

**Issue by Bannigo** [PointCloudLibrary/pcl#4723]
Hello everyone,
                         I have faced some weird issues. I have been using PCL 1.8 for the past few months and it was working really nice For eg. I was able to compute an ICP registration in about 50ms. Unknowingly 2 days ago my Nvidia drivers stopped working and after doing a lot of research I was not able to fix it and I had to reinstall ubuntu 18.04. Right now my Nvidia drivers are working perfectly and I also installed Cuda 9. But now the same ICP registration is taking around 100-120 ms. I have to build a near real-time system and this computation time is too heavy for me. Do you know, what could have possibly gone wrong? I think that's the CPU vs GPU computations. I would really appreciate your suggestions and help.

Regards,
Yash

**Comment by Bannigo** [comment]
I am also using filtering methods in the same registration algorithm. Is it necessary to link PCL_FILTER_LIBS somewhere in the CMakelists.txt to get efficient computations?

**Comment by larshg** [comment]
So you are still using PCL 1.8, then it hardly a bug in PCL. I don't think that we can help you pinpoint where the bottleneck is.
I guess it can be everything from kernel version, to Nvidia drivers etc.

**Comment by larshg** [comment]
I'll close this, but feel free to post more info / questions.

**Comment by Bannigo** [comment]
Can you please tell me once, what are the other things from which the performance is affected? I can try to update kernel version and also other things

**Comment by larshg** [comment]
Well, for starters there are no ICP GPU implementation, so I'm not entirely sure what you think runs on your GPU? If its CPU code you use, then maybe you have set different compiler flags, got newer / older compiler. Its really difficult to say.
