### ISSUE TITLE
[custom] Question about PCD format

### ISSUE THREAD

**Issue by abellgithub** [PointCloudLibrary/pcl#4724]
I'm trying to understand the proper format of a PCD file. The [documentation](https://pcl.readthedocs.io/projects/tutorials/en/latest/pcd_file_format.html) says that ASCII output and the PCD header is delimited by the newline character. However, when I run the [sample PCD program](https://pcl.readthedocs.io/projects/tutorials/en/latest/writing_pcd.html) on Windows, it generates output with the standard Windows line separators (CR + NL).

Is the documentation wrong? Is the code wrong?

If the code is correct, is *either* fine? Should I be able to transfer *any* PCD file from a UNIX-like system to a Windows system without worrying about the line separators?

**Comment by mvieth** [comment]
Could you upload the PCD file written by the tutorial you linked? As far as I see, the PCDWriter always uses `\n`

**Comment by abellgithub** [comment]
I used the conda version of PCL on Windows 10. The code doesn't seem to open the file in binary mode for write, so I believe that `\n` will be translated to `\r\n` on Windows. Maybe I'm missing something.

[test_pcd.pcd.gz](https://github.com/PointCloudLibrary/pcl/files/6359652/test_pcd.pcd.gz)

```
C:\Users\andre\pcl>od -a test_pcd.pcd
0000000   #  sp   .   P   C   D  sp   v   0   .   7  sp   -  sp   P   o
0000020   i   n   t  sp   C   l   o   u   d  sp   D   a   t   a  sp   f
0000040   i   l   e  sp   f   o   r   m   a   t  cr  nl   V   E   R   S
0000060   I   O   N  sp   0   .   7  cr  nl   F   I   E   L   D   S  sp
0000100   x  sp   y  sp   z  cr  nl   S   I   Z   E  sp   4  sp   4  sp
0000120   4  cr  nl   T   Y   P   E  sp   F  sp   F  sp   F  cr  nl   C
0000140   O   U   N   T  sp   1  sp   1  sp   1  cr  nl   W   I   D   T
0000160   H  sp   5  cr  nl   H   E   I   G   H   T  sp   1  cr  nl   V
0000200   I   E   W   P   O   I   N   T  sp   0  sp   0  sp   0  sp   1
0000220  sp   0  sp   0  sp   0  cr  nl   P   O   I   N   T   S  sp   5
0000240  cr  nl   D   A   T   A  sp   a   s   c   i   i  cr  nl   1   .
0000260   2   8   1   2   5  sp   5   7   7   .   0   9   3   7   5  sp
0000300   1   9   7   .   9   3   7   5  cr  nl   8   2   8   .   1   2
0000320   5  sp   5   9   9   .   0   3   1   2   5  sp   4   9   1   .
0000340   3   7   5  cr  nl   3   5   8   .   6   8   7   5  sp   9   1
0000360   7   .   4   3   7   5  sp   8   4   2   .   5   6   2   5  cr
0000400  nl   7   6   4   .   5  sp   1   7   8   .   2   8   1   2   5
0000420  sp   8   7   9   .   5   3   1   2   5  cr  nl   7   2   7   .
0000440   5   3   1   2   5  sp   5   2   5   .   8   4   3   7   5  sp
0000460   3   1   1   .   2   8   1   2   5  cr  nl
0000473
```

**Comment by larshg** [comment]
I have verified that carriage return is appended. See https://stackoverflow.com/questions/43481143/stdofstream-is-adding-carriage-return-cr-r-after-n-automatically.

We need to change:
`fs.open (file_name.c_str ());      // Open file`
to
`fs.open (file_name.c_str (),std::ios::binary);      // Open file`

Then it works as expected.

**Comment by larshg** [comment]
@abellgithub can you somehow test the linked PR? Can you ask conda to use a specific git checkout perhaps?

**Comment by abellgithub** [comment]
I'm sorry but I'm not currently in a position to test this fix. But I simply ran the referenced test program on Windows. You should be able to link it with your changed code and check the output.
