### ISSUE TITLE
[compile error] "PCL conversions dont compile"

### ISSUE THREAD

**Issue by lidiaxp** [PointCloudLibrary/pcl#4731]
I trying to use a pcl with statistical filter and ROS.

I am using this [code](https://drive.google.com/file/d/1MWKKwsLDyzNMkdhi73HyXj60OHucvMnI/view?usp=sharing) with this [cmakeList](https://drive.google.com/file/d/1xmn-zw6nHZLdYBOoB29odQaZHYsnwSGr/view?usp=sharing).

When I try compile appear this error:

`collect2: error: ld returned 1 exit status
make[2]: *** [pcl_manipulation/CMakeFiles/pcl_sample_visualizer.dir/build.make:409: /home/lidiaxp/workspace/devel/lib/pcl_manipulation/pcl_sample_visualizer] Error 1
make[1]: *** [CMakeFiles/Makefile2:6445: pcl_manipulation/CMakeFiles/pcl_sample_visualizer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

`collect2: error: ld returned 1 exit status
make[2]: *** [pcl_manipulation/CMakeFiles/pcl_sample_filter.dir/build.make:409: /home/lidiaxp/workspace/devel/lib/pcl_manipulation/pcl_sample_filter] Error 1
make[1]: *** [CMakeFiles/Makefile2:6499: pcl_manipulation/CMakeFiles/pcl_sample_filter.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
`

I believe that this error is because the pcl conversions package because when I try run a package without it works. 

I install this package and ros-noetic-pcl-conversions. I am using Ubuntu 20.04 with ROS noetic and Python 3.8.

**Comment by kunaltyagi** [comment]
pcl_conversions is not part of this repo. It might be managed under perception_ros package, though I'm not sure.

On a side note, you didn't report the version of pcl or the actual errors that occurred.

**Comment by mvieth** [comment]
Just had a quick glance at your CMakeLists.txt, the line `find_package(pcl_conversions REQUIRED)` is wrong, pcl_conversions is meant to be found by specifying it under `find_package(catkin COMPONENTS pcl_conversions ...)` which is also done in your CMakeLists.txt. The linking then happens with something like `target_link_libraries(executable_name ${catkin_LIBRARIES} ...)`.
And yes, pcl_conversions is part of [perception_pcl](https://github.com/ros-perception/perception_pcl). If you have further issues with pcl_conversions, it is best when you open an issue there.

**Comment by lidiaxp** [comment]
Thx for advices, I transfer the question to [here](https://github.com/ros-perception/perception_pcl/issues/325).
