### ISSUE TITLE
[PCLVisualizer] "when mouse click，get coordinate of clicked point"

### ISSUE THREAD

**Issue by jiaobinbin152** [PointCloudLibrary/pcl#4736]
like the picture:
![image](https://user-images.githubusercontent.com/40234331/116516994-e448c300-a900-11eb-8c43-26260845da75.png)

**Comment by mvieth** [comment]
We really need more information. Is this a bug report? Or a feature request? Is this not working as it should or do you want this as a new feature? According to the title, you are talking about the PCLVisualizer, right?

**Comment by jiaobinbin152** [comment]
> We really need more information. Is this a bug report? Or a feature request? Is this not working as it should or do you want this as a new feature? According to the title, you are talking about the PCLVisualizer, right?

YES，I'm talking about thePCLVisualizer. I want to implement the function。

**Comment by mvieth** [comment]
Do you want to implement the function yourself or are you asking that someone else implements this? If you want to implement it, then sure, you are welcome to open a pull request. If you are asking that someone else implements it, we can leave this issue open and see if someone is interested to do it.
What I don't fully understand about your proposed feature yet: when the user clicks, should the coordinates of the nearest point of the point cloud be displayed? Or just the coordinates in space where the user clicked, no matter whether a point from the point cloud is close? I see the problem that the exact coordinate or the point of the cloud is ambiguous since the mouse click on the screen is in 2D, but the coordinate is in 3D

**Comment by jiaobinbin152** [comment]
> Do you want to implement the function yourself or are you asking that someone else implements this? If you want to implement it, then sure, you are welcome to open a pull request. If you are asking that someone else implements it, we can leave this issue open and see if someone is interested to do it.
> What I don't fully understand about your proposed feature yet: when the user clicks, should the coordinates of the nearest point of the point cloud be displayed? Or just the coordinates in space where the user clicked, no matter whether a point from the point cloud is close? I see the problem that the exact coordinate or the point of the cloud is ambiguous since the mouse click on the screen is in 2D, but the coordinate is in 3D

Yes! I want to ask that someone has implements it。

**Comment by larshg** [comment]
It should be possible to register an event, see:
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/point_picking_event.cpp

You can also search on google, it seems there are some hits there as well.

**Comment by jiaobinbin152** [comment]
Thank larshg.
search on google, find the Solution。

viewer->registerPointPickingCallback(pp_callback, nullptr);
void pp_callback(const pcl::visualization::PointPickingEvent& event, void* ptr)
{
    if (event.getPointIndex() != -1)
    {                
        float x, y, z;
        event.getPoint(x, y, z);
        print("x:%f, y:%f, z:%f",x,y,z)
		
    }
}

I'm china. Reference：https://blog.csdn.net/liang583206/article/details/73386836

**Comment by larshg** [comment]
Thanks for reporting back. Closing as I think its "solved"? Else feel free to re-open.

**Comment by qing130** [comment]
> Thank larshg. search on google, find the Solution。
> 
> viewer->registerPointPickingCallback(pp_callback, nullptr); void pp_callback(const pcl::visualization::PointPickingEvent& event, void* ptr) { if (event.getPointIndex() != -1) { float x, y, z; event.getPoint(x, y, z); print("x:%f, y:%f, z:%f",x,y,z) } }
> 
> I'm from china. Reference：https://blog.csdn.net/liang583206/article/details/73386836

I tried this,but it did not work. 
I use PCL12.1,win10.
