### ISSUE TITLE
pcl::SupervoxelClustering gives Segmentation Fault on extract 

### ISSUE THREAD

**Issue by mathislm** [PointCloudLibrary/pcl#4739]
**Describe the bug**
I get a segmentation fault when doing superVoxelCluster.extract().

**Context**
I'm trying to perfom supervoxel segmentation on a point cloud. For now I'm using the pcd file from https://pcl.readthedocs.io/en/latest/supervoxel_clustering.html to make sure the problem is not coming from my point cloud.

My environment is a bit special. I'm using cython to wrap my cpp code (including my pcl algorithms). I have been doing that for some time and it works like a charm, so I suppose it's not comming from here.

**To Reproduce**
My code is very simple :
```c++
pcl::io::loadPCDFile<pcl::PointXYZRGB> ("milk_cartoon_all_small_clorox.pcd", *cloud);

// Initialize superVoxelClustering
pcl::SupervoxelClustering<pcl::PointXYZRGB> superVoxelCluster(voxel_resolution, seed_resolution);

superVoxelCluster.setUseSingleCameraTransform(false);
superVoxelCluster.setInputCloud(cloud);
superVoxelCluster.setColorImportance(color_importance);
superVoxelCluster.setSpatialImportance(spatial_importance);
superVoxelCluster.setNormalImportance(normal_importance);

// Extracting sv
std::map<std::uint32_t, pcl::Supervoxel<pcl::PointXYZRGB>::Ptr> superVoxelClusters;
superVoxelCluster.extract(superVoxelClusters);
```
But it seg faults on the last line.

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: g++
 - PCL Version HEAD

**Additional context**

I can copy past the compilations commands done by Cython if it's any help

**Comment by mathislm** [comment]
Ok so I did a bit of digging and I found that that seg fault occures on line 406 of supervoxel_clustering.hpp : 
```c++
voxel_kdtree_ ->setInputCloud (voxel_centroid_cloud_);
```
It's strange because I happen to also use KdTreeFLANN in an other function, which is working perfectly well

I would really appreciate some insight on this bug.

**Comment by mvieth** [comment]
Can you try switching from `PointXYZRGB` to `PointXYZRGBA`?

**Comment by mathislm** [comment]
Seg faults as well !

I'll try to compile the exemple from https://pcl.readthedocs.io/en/latest/supervoxel_clustering.html on it's own without cython.

**Comment by mathislm** [comment]
Okay... that is annoying... it seems to works when I just compile it with CMake with no trace of cython. Do you know the extra compilation arguments that might add CMake ? If I know them I might be able to make it work with cython

**Comment by mvieth** [comment]
[See this](https://stackoverflow.com/questions/2670121/using-cmake-with-gnu-make-how-can-i-see-the-exact-commands) on how to display the exact commands that cmake and make execute. I can't help you with cython though.

**Comment by mvieth** [comment]
I am going to close this issue since there does not seem to be a problem in PCL. If you do find a problem after all, feel free to reopen. Also, feel free to comment if you solve the cython problem because it might help someone in the future with the same problem.

**Comment by mathislm** [comment]
I sorry I forgot to follow up. I fixed my problem. For some strange reason the import order in my python code was important. I suppose some of PCL's libraries were changed to older/newer versions, so I made sure to import my wrapper after Numpy and OpenCV.
Thanks !

**Comment by calmelo** [comment]
> **Describe the bug** I get a segmentation fault when doing superVoxelCluster.extract().
> 
> **Context** I'm trying to perfom supervoxel segmentation on a point cloud. For now I'm using the pcd file from https://pcl.readthedocs.io/en/latest/supervoxel_clustering.html to make sure the problem is not coming from my point cloud.
> 
> My environment is a bit special. I'm using cython to wrap my cpp code (including my pcl algorithms). I have been doing that for some time and it works like a charm, so I suppose it's not comming from here.
> 
> **To Reproduce** My code is very simple :
> 
> ```c++
> pcl::io::loadPCDFile<pcl::PointXYZRGB> ("milk_cartoon_all_small_clorox.pcd", *cloud);
> 
> // Initialize superVoxelClustering
> pcl::SupervoxelClustering<pcl::PointXYZRGB> superVoxelCluster(voxel_resolution, seed_resolution);
> 
> superVoxelCluster.setUseSingleCameraTransform(false);
> superVoxelCluster.setInputCloud(cloud);
> superVoxelCluster.setColorImportance(color_importance);
> superVoxelCluster.setSpatialImportance(spatial_importance);
> superVoxelCluster.setNormalImportance(normal_importance);
> 
> // Extracting sv
> std::map<std::uint32_t, pcl::Supervoxel<pcl::PointXYZRGB>::Ptr> superVoxelClusters;
> superVoxelCluster.extract(superVoxelClusters);
> ```
> 
> But it seg faults on the last line.
> 
> **Your Environment (please complete the following information):**
> 
>     * OS: Ubuntu 20.04
> 
>     * Compiler: g++
> 
>     * PCL Version HEAD
> 
> 
> **Additional context**
> 
> I can copy past the compilations commands done by Cython if it's any help

I also meet the problem, how do you resolve it?

**Comment by mathislm** [comment]
> I also meet the problem, how do you resolve it?

My case was very special since I was using a Cython wrapper. If you are also doing that, I suggest you try importing the wrapped library at different places. I can't help you more. Good luck
