### ISSUE TITLE
[PolygonMesh::concatenate(...)] indices are improperly handled

### ISSUE THREAD

**Issue by taehongjeong** [PointCloudLibrary/pcl#4743]
Dear PCL maintainers,

I believe that I've encountered a bug in the `PolygonMesh::concatenate` method below:

https://github.com/PointCloudLibrary/pcl/blob/e1664a4ba63107b2c5ca10bc4137c5a8f73ae0b5/common/include/pcl/PolygonMesh.h#L30-L57

Here, the `point_offset` should have computed before the concatenation of points **(at L33)**.

https://github.com/PointCloudLibrary/pcl/blob/e1664a4ba63107b2c5ca10bc4137c5a8f73ae0b5/common/include/pcl/PolygonMesh.h#L40

The current implementation would yield a wrong result as follows:

- Consider the case of concatenating an empty `PolygonMesh` with another `PolygonMesh` with 3 vertices.
- Suppose that the latter `PolygonMesh` has a face having ids (0, 1, 2) -- a single triangle
- The result of this concatenation will yield a face having ids (3, 4, 5) because the `point_offset` is computer after merging points.

Best,
Hugh

**Comment by mvieth** [comment]
Thank you for this bug report. It seems like pull request #4572 will fix this, can you confirm?

**Comment by taehongjeong** [comment]
Thank you for your quick response! The PR is exactly what I want.
I see the original author has not responded so far.
I guess I can take over the PR.
Let me add an accompanying unit test (mentioned in https://github.com/PointCloudLibrary/pcl/pull/4572#issuecomment-759314689).

**Comment by mvieth** [comment]
That would be great if you would create such a test!

**Comment by taehongjeong** [comment]
Instead of adding a new test, I've fixed the existing one.
I've made a new PR #4745. Please have a look.
Also, if my PR would work and be merged, I think it would be better close the original PR #4572.

Thank you for your efforts!
