### ISSUE TITLE
[recognition] External metslib support intentionally broken — remove the check for it?

### ISSUE THREAD

**Issue by drhpc** [PointCloudLibrary/pcl#4744]
**Describe the bug**

I noticed that the build of pcl-1.11.1 detects a present metslib in the system and claims to use it, but the
one header that references metslib is using the 3rdparty one that is shipped with pcl but not installed in this case.

The commit https://github.com/PointCloudLibrary/pcl/commit/4fdd12b0669347b51c83d00bbdccc9a82fd37372 killed the former way of referencing the system metslib, as I gather. It doesn't provide a reason.

Is system metslib still a supported configuration? In pkgsrc, we try to avoid needlessly vendored dependencies.

**Context**

I am packaging PCL in pkgsrc as a dependency for building SAGA (a GIS that is (co-)developed by people at my university).

**Expected behavior**

Install PCL to prefix /data/pkg/, where it finds the installed metslib (that works, via pkg-config).
Then have the installed headers actually reference the installed metslib.

```
$ grep metslib /data/pkg/include/pcl-1.11/pcl/recognition/hv/hv_go.h 
#include <metslib/mets.hh>
$ LANG=C ls /data/pkg/include/metslib-0.5/metslib/mets.hh 
/data/pkg/include/metslib-0.5/metslib/mets.hh
$ pkg-config --cflags metslib
-I/data/pkg/include/metslib-0.5 -I/data/pkg/lib/metslib-0.5/include
$ pkg-config --cflags pcl_recognition-1.11
-I/data/pkg/include/pcl-1.11 -I/data/pkg/include/eigen3 -I/data/pkg/include  -I/data/pkg/include/metslib-0.5
```

**Current Behavior**

```
$ grep metslib /data/pkg/include/pcl-1.11/pcl/recognition/hv/hv_go.h 
#include <pcl/recognition/3rdparty/metslib/mets.hh>
$ LANG=C ls /data/pkg/include/pcl-1.11/pcl/recognition/3rdparty/metslib/mets.hh
ls: cannot access '/data/pkg/include/pcl-1.11/pcl/recognition/3rdparty/metslib/mets.hh': No such file or directory
```

**To Reproduce**

Try to build PCL with metslib being present in the system, observe what the installed headers do. Right now, you could start from pkgsrc CVS and make graphics/pcl there (see http://pkgsrc.org/), I am awaiting the answers to this issue to clear up the question whether I should patch up PCL to use metslib correctly or ditch the external dependency. Note that I already have to include PR 4540 to make it build with current qhull, and will have to import more patches to make it work once we got VTK to the current state. A PCL-1.11.2 release that contains therese build fixes would be helpful.

**Your Environment (please complete the following information):**

 - OS: various, in this case Ubuntu 20.04/x86-64
 - Compiler: gcc 9.3.0
 - PCL Version: 1.11.1

**Possible Solution**

Decide to ditch external metslib support or fix it to work (again?) with a single-line change, undoing https://github.com/PointCloudLibrary/pcl/commit/4fdd12b0669347b51c83d00bbdccc9a82fd37372.

**Additional context**

I hope that's enough context for a one-line issue;-)

**Comment by kunaltyagi** [comment]
Sorry for the delay. Please go ahead with the bug fix PR.

Sadly, such errors can go unnoticed since we don't test with all PnC on our CI

**Comment by drhpc** [comment]
https://github.com/PointCloudLibrary/pcl/pull/4792
