### ISSUE TITLE
pcl_viewer visualise intensity for .pcd file with XYZI data 

### ISSUE THREAD

**Issue by Jinjing98** [PointCloudLibrary/pcl#4749]
Hello,
I know that we can visualize a .pcd with the **intensities** by using the PCL library, however,is there any way by using the terminal 'pcl_viewer' since it makes it a lot easier.So my .pcd file is x,y,z,intensity.
pcl_viewer works well for x,y,z,r,g,b data but I would really like to visualize the intensity for my XYZI data.

 Thank you in advance!

**Comment by larshg** [comment]
I think if you just supply your pcd file, then you can change what to visualize/color by pressing 1,2,3,4,5.
1 is all random
2 is X values
3 is Y values
4 is Z values
5 is intensity

Hope that works?

**Comment by larshg** [comment]
However, with the test cloud I just used, I'm not sure what the colors represents, but maybe you can figure it out 😄

**Comment by Jinjing98** [comment]
> However, with the test cloud I just used, I'm not sure what the colors represents, but maybe you can figure it out 😄

Thanks soo much!
Yes it works now. So basically 2,3,4,5 are visualizing the point cloud based on the x,y,z,intensity values. I am sure about it by checking several points by having the command like this  " pcl_viewer 1620399384820519.pcd -use_point_picking"  so as to interact.
