### ISSUE TITLE
Is all pcl point type's x y z base on float? what should I do if I need double ....

### ISSUE THREAD

**Issue by OrdinaryChen** [PointCloudLibrary/pcl#4756]
my data is really big, and it has 7 decimal places before the decimal point and 4 decimal places after the decimal point. when I use pointcloud XYZ, it lost precision, I think I need double , so what should I do...

**Comment by mvieth** [comment]
All of PCL's native point types use float for x, y, and z. You can create your own point type with double precision, but only few functions and classes will work correctly with double precision since PCL is designed for float/single precision (which is faster and accurate enough in most situations).
Regarding your situation: How did you notice that you "lost precision"? Where do you get your data from (a depth camera?) and what unit is it in? Floats can still represent large values. And if your data is noisy, a little loss of precision is not noticeable anyway.

**Comment by OrdinaryChen** [comment]
> 
> 
> All of PCL's native point types use float for x, y, and z. You can create your own point type with double precision, but only few functions and classes will work correctly with double precision since PCL is designed for float/single precision (which is faster and accurate enough in most situations).
> Regarding your situation: How did you notice that you "lost precision"? Where do you get your data from (a depth camera?) and what unit is it in? Floats can still represent large values. And if your data is noisy, a little loss of precision is not noticeable anyway.

thanks alot for your anwser, so, what you think about, if I downloads sourse file and replace all "float" with "double" in sourse code and make it by cmake. will I get a pointcloud library can deal with double?

**Comment by mvieth** [comment]
> thanks alot for your anwser, so, what you think about, if I downloads sourse file and replace all "float" with "double" in sourse code and make it by cmake. will I get a pointcloud library can deal with double?

Possibly, but that would be _a lot_ of work. Are you sure you need double precision?

**Comment by OrdinaryChen** [comment]
I have 3 choice. 1 remake source file .&nbsp; 2 offset the data which is difficult to decided how much to offset 3 leave pcl to use another library&nbsp; like open3d.&nbsp; is open3d use float or double？I think I need double .&nbsp; I work with map data and GPS value is big . it always&nbsp; over million


 
---Original---
From: "Markus ***@***.***&gt;
Date: 2021/5/13 00:31:40
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PointCloudLibrary/pcl] Is all pcl point type's x y z base on float? what should I do if I need double .... (#4756)




  
thanks alot for your anwser, so, what you think about, if I downloads sourse file and replace all "float" with "double" in sourse code and make it by cmake. will I get a pointcloud library can deal with double?
  
Possibly, but that would be a lot of work. Are you sure you need double precision?

**Comment by mvieth** [comment]
No idea about open3d, but [it seems like they use float as well](http://www.open3d.org/docs/release/cpp_api/classopen3d_1_1ml_1_1contrib_1_1_point_x_y_z.html)
Big values are not necessarily a problem for float. The largest value a float can represent is 3.402823e+38. Whether the precision is enough for you depends on what you want to do with your data, what algorithms you want to use, etc.

**Comment by OrdinaryChen** [comment]
> No idea about open3d, but [it seems like they use float as well](http://www.open3d.org/docs/release/cpp_api/classopen3d_1_1ml_1_1contrib_1_1_point_x_y_z.html)
> Big values are not necessarily a problem for float. The largest value a float can represent is 3.402823e+38. Whether the precision is enough for you depends on what you want to do with your data, what algorithms you want to use, etc. 

I know pdal use double... I did not know details of float. but when I give 3375876.5445 to a float value it become 3375876.5000 today I remember.

**Comment by mvieth** [comment]
An offset might really be a good solution then. The exact offset probably does not matter that much, you could for example just choose any point as an offset, or use a round value like 3375800, or a point at the centre of all the points.

**Comment by tx-lidar** [comment]
> my data is really big, and it has 7 decimal places before the decimal point and 4 decimal places after the decimal point. when I use pointcloud XYZ, it lost precision, I think I need double , so what should I do...

Hello, I have encountered the same problem. I want to transfer the PCD of a local coordinate system to the UTM coordinate system of a specified latitude and longitude, but the UTM coordinates of this point are very large and have exceeded the significant digits of decimal floating-point numbers. After translating the point cloud and storing it in another PCD file, I compared it with the original PCD using CloudCompare and found that not only did there be a loss in accuracy, but the structure or sorting of the point cloud also changed, which looked strange. Moreover, when I dragged the point cloud, the entire point cloud map trembled.
May I ask how you finally resolved it? Thank you very much for your reply.

**Comment by mvieth** [comment]
@tx-lidar If you just want to convert to double, translate all points, and then save as a PCD file, that should actually be possible. You would first need to create a new point type that is similar to `pcl::PointXYZ`, but with `double` instead of `float`, then copy all x, y, z coordinates to a new `pcl::PointCloud` of the new point type, translate, and finally save as PCD file.

**Comment by tx-lidar** [comment]
> @tx-lidar If you just want to convert to double, translate all points, and then save as a PCD file, that should actually be possible. You would first need to create a new point type that is similar to `pcl::PointXYZ`, but with `double` instead of `float`, then copy all x, y, z coordinates to a new `pcl::PointCloud` of the new point type, translate, and finally save as PCD file.

So, do I need to make corresponding modifications to this function when I use pcd_writer. writer Binary to write the point cloud I created into pcd.

**Comment by mvieth** [comment]
> So, do I need to make corresponding modifications to this function when I use pcd_writer. writer Binary to write the point cloud I created into pcd.

No, as far as I see, `PCDWriter::writeBinary` does not care whether the coordinates are double or float.

**Comment by tx-lidar** [comment]
> > So, do I need to make corresponding modifications to this function when I use pcd_writer. writer Binary to write the point cloud I created into pcd.
> 
> No, as far as I see, `PCDWriter::writeBinary` does not care whether the coordinates are double or float.

18/10000实时翻译
划译
Okay, then I'll give it a try. Thank you very much for your reply

**Comment by tx-lidar** [comment]
> > So, do I need to make corresponding modifications to this function when I use pcd_writer. writer Binary to write the point cloud I created into pcd.
> 
> No, as far as I see, `PCDWriter::writeBinary` does not care whether the coordinates are double or float.

Okay, then I'll give it a try. Thank you very much for your reply

**Comment by larshg** [comment]
Closing as both questions asked in this thread has been answered.
