### ISSUE TITLE
 pcl with open3d incompatible

### ISSUE THREAD

**Issue by mingyangpeng** [PointCloudLibrary/pcl#4757]
- OS: [Ubuntu 18]
 - Compiler: [ GCC 7]
 - PCL Version [ 1.11 ]
 - Open3d Version [0.12]

**Possible Solution**

It's normal for me to use the PCL library alone, but when I introduce the third-party library open3d, the system prompts that the PCL library can't be found or an error is reported

"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc"

or

"undefined reference to `pcl::visualization::PCLVisualizer::PCLVisualizer(std::string const&, bool)'
main.cpp:(.text+0x2432): undefined reference to `pcl::visualization::PCLVisualizer::addCoordinateSystem(double, std::string const&, int)'
collect2: error: ld returned 1 exit status

"

target_link_libraries(nano_o3d_regist  
                    ${PCL_LIBRARIES}
                    jsoncpp  
                    ${OpenCV_LIBS}                      
                    #${Open3D_LIBRARIES}  
)

**Comment by kunaltyagi** [comment]
I'm inclined to close the issue. Please use discord for this discussion.

Potential solution to cmake error: Make visualization a required component of PCL in your find_package command

---
Reasons for closing:
* No minimum complete verifiable example
* 2 errors, one runtime and one link time. Not feasible
* incomplete snippets
* downstream PCL is checked and works for several other projects
* GitHub issue is not a good place to host discussions. The newcomers channel on discord would be a better place :)
