### ISSUE TITLE
[GPU::DeviceArray] Subscript Operators and Iterators to facilitate leveraging GPU implementations

### ISSUE THREAD

**Issue by FabianSchuetze** [PointCloudLibrary/pcl#4759]
When I converted existing PCL code running on the CPU to leverage GPU implementations, I realized that such adjustments could be smoother. I would therefore like to suggest two addition to the `DeviceArray<T>` API. 

Firstly, a subscript operator:
```
DeviceArray<T>::operator[]
```
Subscript operators are particularly convenient for converting existing PCL code running on the CPU to code leveraging GPU implementations. For example, these lines of code are pervasive:
```
for (int i = 0; i < cloud->size(); ++i) {
	cloud[i] = SomeRandomPoint;
}
```
`cloud` can easily be converted to a `DeviceArray<pcl::PointType>`. Subscript operators allow continuing using CPU-type code instead of adjusting it to the existing device array API. 

Secondly, I would like to add an iterator member type.  A benefit of iterators was discussed in ticket #4741.  

What do others think about these two adjustments? I'd be happy to implement both adjustments to the API but wanted to ask for feedback first.

**Comment by kunaltyagi** [comment]
When would you upload the memory? If it's done every iteration, that would be quite slow, right?

**Comment by kunaltyagi** [comment]
> Secondly, I would like to add an iterator member type

This would be good to have

**Comment by FabianSchuetze** [comment]
I close this as the same is discussed in #4818 and will open a more detailed one once a PR is ready.
