### ISSUE TITLE
[Docker] Ubuntu CI builds failing

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4763]
**Describe the bug**

Recently added wget command fails. Link to error:
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=19012&view=logs&j=02e31b63-97df-57da-5c5b-409d1f33cda8&t=3198efe3-d7f9-5c6d-757b-14de2e7a3e6f&l=7394

Most probable error:
`wget -q0- https://...`

@SunBlack

**Comment by SunBlack** [comment]
It is a missing `;`, already solved locally for #4747 ;-)

**Comment by kunaltyagi** [comment]
Can we hostfix that before the weekend run?

**Comment by SunBlack** [comment]
Anything we need todo? Will be changes to a Docker script within a PR automatically pushed?

Btw: The [next](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=19020&view=results) build was successful.
