### ISSUE TITLE
[SupervoxelClustering] Extracting super voxels creates new points

### ISSUE THREAD

**Issue by mathislm** [PointCloudLibrary/pcl#4773]
**Describe the bug**

When displaying the result of the extraction, there are new points that appear.

**Context**

I'm trying to perform LCCP segmentation and I needed to display the super voxels to see the effect of each parameters. When I display the clusters with a very simple iterator, I get new points that appear seemingly randomly.

**Expected behavior**

I suppose there should be no new points being created. 

**Current Behavior**

But instead, as shown in the shared picture, there are some new voxels.

**To Reproduce**
I have a function that can display an eigen3 matrix, but I don't think this is where the problem comes from as I have been using it for some time. Here is my process to create my supervoxel clusters.
```C++
pcl::SupervoxelClustering<pcl::PointXYZRGBA> superVoxelCluster(voxel_resolution, seed_resolution);

detectedObjects.resize(0);

superVoxelCluster.setUseSingleCameraTransform(false);
superVoxelCluster.setInputCloud(cloud);
superVoxelCluster.setColorImportance(color_importance);
superVoxelCluster.setSpatialImportance(spatial_importance);
superVoxelCluster.setNormalImportance(normal_importance);

// Extraction des supervoxels
std::map<std::uint32_t, pcl::Supervoxel<pcl::PointXYZRGBA>::Ptr> superVoxelClusters;
superVoxelCluster.extract(superVoxelClusters);

std::vector<Eigen::MatrixXd> superVoxels;
for (auto const& [label, superVox] : superVoxelClusters) {
    superVoxels.push_back(superVox->voxels_->getMatrixXfMap().cast<double>());
}

return superVoxels;
```

**Screenshots/Code snippets**
Outside of the grey area, the new points. What is very strange is that they would be "behind" my camera !

![Screenshot from 2021-05-25 10-23-26](https://user-images.githubusercontent.com/22646123/119465468-fa04a900-bd43-11eb-9c0c-d31782fd9dec.png)

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: g++ -std=c++17
 - PCL Version 1.11.1

**Comment by mvieth** [comment]
> I suppose there should be no new points being created.

:laughing: 

Can you share the cloud you are using as a PCD file? That is necessary to reproduce your problem.
Have you tried out the [supervoxel clustering tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/supervoxel_clustering.html) with your point cloud?
Is it possible that the points have been there before, but you just did not see them?

**Comment by mathislm** [comment]
Sure, here is the point cloud. It should be noted that I did a few pre-processing steps with this point cloud before. This explain why you won't have the gray plane.

1. Decimation
2. Rotation here is the rotvec in radian for this point cloud.
3. Plane segmentation using classic pcl::SACSegmentation
4. Selection of the points above the plane using pcl::ExtractPolygonalPrismData

[point_cloud.zip](https://github.com/PointCloudLibrary/pcl/files/6539268/point_cloud.zip)

When I display the point cloud juste before the segmentation, the points do not appear. I would be very strange since they would be "behind" the camera. 

Also, I found out that if I display the result from `superVoxelCluster.getLabeledCloud()` there are no new points created. This might have something to do with the octree used ? The total number of points in the `superVoxelClusters` is 10 times smaller than the number of points in the original point cloud.
![Screenshot from 2021-05-25 14-19-17](https://user-images.githubusercontent.com/22646123/119498827-54aefc80-bd66-11eb-8c0d-2331792fee08.png)

**Comment by mathislm** [comment]
Update : I tried running the tutorial but I get a segfault I can't fix !
```
> Loading point cloud...
> Extracting supervoxels!
Found 14 supervoxels
> Getting supervoxel adjacency
Segmentation fault (core dumped)
```
If anyone has some insight on that, I'd love to hear. Thanks

**Comment by mathislm** [comment]
Update : I managed to make the tutorial work ! I don't get the new points, and the adjacency displayed is not strange like in my picture. I'll look at the difference between the 2 codes.

**Comment by mvieth** [comment]
@mathislm Did you make any progress? Is it possible that the parameters you used caused the problem? I am also not totally sure how `getMatrixXfMap` behaves if there are non-float values (R, G, B, A) in the point, and whether your function to display the matrices handles that, so maybe try to rewrite your code to not use `getMatrixXfMap` (if you haven't found a solution yet).

**Comment by mvieth** [comment]
@mathislm Is this problem solved? If I don't hear anything from you, I will consider it solved and close this issue.

**Comment by mathislm** [comment]
I'm sorry for leaving this issue un-attended. I figured that since superVoxelCluster.getLabeledCloud() gives me a proper point cloud, I didn't need to dig deeper. The problem with the adjacency is still here but I don't use it. Sadly I don't really have time to help with understanding where the issue was coming from, so I'll close the issue. I might re-open it if I find the time to dig. Bye
