### ISSUE TITLE
Use picture from documentation for paper

### ISSUE THREAD

**Issue by Me817** [PointCloudLibrary/pcl#4780]
Hello,

I am writing a paper in a seminar at university and I would like to use the picture showing the original object and the one showing the reconstructed mesh from [in-hand scanner](https://pcl.readthedocs.io/en/latest/in_hand_scanner.html#in-hand-scanner). May I use these images stitched together into one image in my paper with the appropriate reference?
I am looking forward to hearing from you.
Thank you in advance.

Yours sincerely,
Me817

**Comment by kunaltyagi** [comment]
Yes. Please feel free to use any part of PCL in your research, as long as you cite us. I've added the bibtex blurb for your convenience.
