### ISSUE TITLE
when i was reading the souce code of StatisticalOutlierRemoval ,i had a question ,why   the pcl::search::OrganizedNeighbor need to calculate project matrix , someone help me? thanks

### ISSUE THREAD

**Issue by jinneigeyu** [PointCloudLibrary/pcl#4782]
file : organized.h
` setInputCloud (const PointCloudConstPtr& cloud, const IndicesConstPtr &indices = IndicesConstPtr ()) override
        {
          input_ = cloud;
          
          mask_.resize (input_->size ());
          input_ = cloud;
          indices_ = indices;

          if (indices_ && !indices_->empty())
          {
            mask_.assign (input_->size (), 0);
            for (const auto& idx : *indices_)
              mask_[idx] = 1;
          }
          else
            mask_.assign (input_->size (), 1);

          estimateProjectionMatrix ();
        }`

**Comment by jinneigeyu** [comment]
I think the point cloud is organized , so when it needs to serch nearby, just  use the index point . why  calculate projective matrix .
and usualy the   projective matrix is not accurate .

**Comment by mvieth** [comment]
The projection matrix and other helper matrices that are calculated in `estimateProjectionMatrix` are used during radius search and nearest neighbour search.
Please ask these kind of questions in the discord community chat.

**Comment by jinneigeyu** [comment]
> The projection matrix and other helper matrices that are calculated in `estimateProjectionMatrix` are used during radius search and nearest neighbour search.
> Please ask these kind of questions in the discord community chat.

yes, i know it was used in searching points. but  i no not  understand why in nearest neighbour searching, when need to calculate distance of query point nerghbours. each point was projected.  (the " **pcl::search::OrganizedNeighbor<PointT>::nearestKSearch** "function , in the file " organized.hpp ",  line 130) 

> `  Eigen::Vector3f queryvec (query.x, query.y, query.z);
  // project query point on the image plane
  //Eigen::Vector3f q = KR_ * query.getVector3fMap () + projection_matrix_.block <3, 1> (0, 3);
  Eigen::Vector3f q (KR_ * queryvec + projection_matrix_.block <3, 1> (0, 3));
  int xBegin = int(q [0] / q [2] + 0.5f);
  int yBegin = int(q [1] / q [2] + 0.5f);
  int xEnd   = xBegin + 1; // end is the pixel that is not used anymore, like in iterators
  int yEnd   = yBegin + 1;`

**Comment by jinneigeyu** [comment]
> > The projection matrix and other helper matrices that are calculated in `estimateProjectionMatrix` are used during radius search and nearest neighbour search.
> > Please ask these kind of questions in the discord community chat.
> 
> yes, i know it was used in searching points. but i no not understand why in nearest neighbour searching, when need to calculate distance of query point nerghbours. each point was projected. (the " **pcl::search::OrganizedNeighbor::nearestKSearch** "function , in the file " organized.hpp ", line 130)
> 
> ```
> ...
>  Eigen::Vector3f queryvec (query.x, query.y, query.z);
>   // project query point on the image plane
>   //Eigen::Vector3f q = KR_ * query.getVector3fMap () + projection_matrix_.block <3, 1> (0, 3);
>   Eigen::Vector3f q (KR_ * queryvec + projection_matrix_.block <3, 1> (0, 3));
>   int xBegin = int(q [0] / q [2] + 0.5f);
>   int yBegin = int(q [1] / q [2] + 0.5f);
>   int xEnd   = xBegin + 1; // end is the pixel that is not used anymore, like in iterators
>   int yEnd   = yBegin + 1;
> ...
> ```

why the index : xbegin and ybegin need project .
