### ISSUE TITLE
[custom] No easy way to provide a donation to help fund the project :-)

### ISSUE THREAD

**Issue by DavidRobb** [PointCloudLibrary/pcl#4789]
I'm raising funds to support various projects that are useful to me:

https://www.justgiving.com/crowdfunding/100pcvatfreebridge

PCL is one of the current beneficiary projects. I would like to distribute some of these funds but can't find an easy way to do so for the PCL project.

**Comment by mvieth** [comment]
Thank you very much for considering a donation to PCL! We will set something up, that might take a while, though.

**Comment by kunaltyagi** [comment]
Liberapay added. Closing the issue

https://liberapay.com/PointCloudLibrary
