### ISSUE TITLE
[compile error] "Undefined reference to pcl::NarfKeypoint"

### ISSUE THREAD

**Issue by DyumanAditya** [PointCloudLibrary/pcl#4790]
**Describe the error**

Hi everyone,
I get the following error while trying to use the Narf keypoints. The code I'm trying to compile is found in [this tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/narf_keypoint_extraction.html#narf-keypoint-extraction):
```
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
[100%] Linking CXX executable test
/usr/bin/ld: CMakeFiles/test.dir/test.cpp.o: in function `main':
test.cpp:(.text+0xc85): undefined reference to `pcl::NarfKeypoint::NarfKeypoint(pcl::RangeImageBorderExtractor*, float)'
/usr/bin/ld: test.cpp:(.text+0xc9e): undefined reference to `pcl::NarfKeypoint::setRangeImage(pcl::RangeImage const*)'
/usr/bin/ld: test.cpp:(.text+0xce1): undefined reference to `pcl::NarfKeypoint::compute(pcl::PointCloud<int>&)'
/usr/bin/ld: test.cpp:(.text+0x1040): undefined reference to `pcl::NarfKeypoint::~NarfKeypoint()'
/usr/bin/ld: test.cpp:(.text+0x13f4): undefined reference to `pcl::NarfKeypoint::~NarfKeypoint()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:166: test] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**To Reproduce**
Copy the code from [this tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/narf_keypoint_extraction.html#narf-keypoint-extraction) and update the cmakelist provided in the tutorial.
Then run 
`cd build`
`cmake ..`
`make`

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - PCL Version 1.10
 - PCL Type: Installed through apt (`sudo apt install libpcl-dev`)

**Comment by mvieth** [comment]
It seems like the problem is simply that you don't link against the `keypoints` module. You mention that you updated the CMakeLists.txt provided in the tutorial - in which way did you update it? How does your CMakeLists.txt look now? Maybe have a look at [this tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/using_pcl_pcl_config.html) to find out how you can request all or just some of PCL's components (modules).

**Comment by DyumanAditya** [comment]
Thank you for your reply, I'm sorry, I was not clear in my first post: I didn't change anything in the cmakelist.txt.
I solved the problem by uninstalling pcl and re-installing it again.
