### ISSUE TITLE
[visualizer] qt_visualizer tutorial doesn't work

### ISSUE THREAD

**Issue by pettaa123** [PointCloudLibrary/pcl#4795]
I tried to use tutorial qt_visualizer. The points weren't displayed in renderwindow.
I had to change pclviewer.h from:

```
typedef pcl::PointXYZRGBA PointT;
typedef pcl::PointCloud<PointT> PointCloudT;
```
to:
`typedef pcl::PointCloud<pcl::PointXYZRGB> PointCloud;`

Othwerwise no pointcloud was visible in renderwindow.

 - OS: [e.g. Ubuntu 20.04]
 - PCL Version [e.g. 1.10.1] built from source
 - VTK 8.2.0 built from source

**Comment by larshg** [comment]
So this could be something with the alpha channel, making the points transparent?

**Comment by WangZP10969** [comment]
[https://gitlab.kitware.com/vtk/vtk/-/issues/18083#note_886067](url)
For the disappearance of transparent objects, I have encountered a similar situation when the virtual machine is running, for reference only.
When using vtk to display directly, turning on accelerated 3D graphics will cause objects whose transparency is not 1 to be displayed.
The opposite is true when using vtk+qt display. Turning off accelerated 3D graphics will cause objects whose transparency is not 1 to be displayed.
For running directly on the local system, this did not happen.

**Comment by kunaltyagi** [comment]
@pettaa123 if you can reproduce this, we can go ahead and close the issue.

**Comment by pettaa123** [comment]
I changed the tutorial code:
`    // Fill the cloud with some points
    for (auto& point: *cloud)
    {
        point.x = 1024 * rand () / (RAND_MAX + 1.0f);
        point.y = 1024 * rand () / (RAND_MAX + 1.0f);
        point.z = 1024 * rand () / (RAND_MAX + 1.0f);

        point.r = red;
        point.g = green;
        point.b = blue;
        point.a = 255; //added this line
    }`
Now the pointcloud is visible. Is this expected behaviour?

**Comment by kunaltyagi** [comment]
Thanks, your code showed me a place where you might have accidentally created a 100% transparent point. Made a PR to fix that
