### ISSUE TITLE
[Windows] PCLVisualizer cannot display point cloud correctly

### ISSUE THREAD

**Issue by TangToy** [PointCloudLibrary/pcl#4805]
I am using PCL 1.8.1, VS2017+Qt 5.9.9. I am creating a relatively big project. I am using PCLVisualizer to display point clouds and it worked well before. After I link Libtorch to my project, I found I cannot clear point clouds, such as the codes:
`
bool _r = viewer->removeAllPointClouds();
`
the return value _r is true, however, the point cloud cannot be removed, it is still on the window.
Besides, setting point size and line size cannot work either, such as the codes:
```
viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 5, "cloud");
...
viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_LINE_WIDTH, 5, "line");
```
The points and lines are still in their default sizes and widths, no matter which size I set.
Before I link Liborch library to my project, these functions work well. How to solve these problems? Thanks.

**Comment by kunaltyagi** [comment]
PCL 1.8 is not supported. Please verify this issue with a recent version of PCL (preferably PCL-1.12 rc1)

**Comment by larshg** [comment]
If you don't link to libtorch it works fine? Kinda of hard to help with. As I don't have libtorch installed.
I'm inclined to close this, but discussion can continue.

**Comment by TangToy** [comment]
Yes, when libtorch was not linked, it worked fine. Thanks.
