### ISSUE TITLE
Does the pcl1.11.1 supports to MacBook Pro M1 (macOS 11.4) ?

### ISSUE THREAD

**Issue by HongchunSun** [PointCloudLibrary/pcl#4808]
I got a MacBook Pro M1 (macOS 11.4), and I want to use PCL to test the project. I can install PCL 1.11.1 successful, using commend `brew install pcl`. But could not comple. So dose the pcl 1.11.1 supports to M1 macbook (macOS 11.4)?

**Comment by kunaltyagi** [comment]
We haven't tested PCL with ARM (and MacOS), so we can't say yes. However, PCL works without issues on Linux ARM.

**Comment by HongchunSun** [comment]
> We haven't tested PCL with ARM (and MacOS), so we can't say yes. However, PCL works without issues on Linux ARM.

ok, I will track the error. Thank you!

**Comment by kunaltyagi** [comment]
If you find any errors, please report back to us :)
