### ISSUE TITLE
1.11.0 still requiring Boost?!

### ISSUE THREAD

**Issue by yaadhavraajagility** [PointCloudLibrary/pcl#4822]
```
git checkout pcl-1.11.1
mkdir build; cd build; cmake..

CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/pcl_find_boost.cmake:33 (find_package)
  CMakeLists.txt:462 (include)
```

I thought boost was removed?

**Comment by kunaltyagi** [comment]
No, boost can't be removed, but we removed stuff that required boost despite it being present in stdlib

**Comment by mvieth** [comment]
Adding to Kunal's answer, `boost::shared_ptr` was replaced with `std::shared_ptr` for example. Other things from boost are not replaceable (yet), e.g. the boost filesystem module could earliest be replaced with equivalent classes and functions from `std` with C++17 (PCL currently uses C++14).

**Comment by mvieth** [comment]
I think that answers the question, so I am closing this issue. If there is still something unclear, feel free to comment.
