### ISSUE TITLE
Issue with kd_flann on Ubuntu

### ISSUE THREAD

**Issue by nallath** [PointCloudLibrary/pcl#483]
When including <pcl/features/normal_3d.h> the kdtree_flan.h is also included. When trying to compile, the compiler gives the error "error: field 'param_k_' has incomplete type" and "error: field 'param_radius_ 'has incomplete type"

**Comment by Mariusmssj** [comment]
This is issue still seems to be present in the RaspbianOS Jessie. If libpcl-dev and libopencv-dev are  installed using apt-get install the flann library has issues and will not allow PCL to compile causing the: 
"error: field 'param_k_' has incomplete type" and "error: field 'param_radius_ 'has incomplete type" errors.

I fixed this by completely removing openCV by "sudo apt-get purge libopencv-dev" then "sudo apt-get autoremove" but that still does not remove the opencvflann lib files those need to be removed manually from file system directories. 

I am going to compile opencv from source and exclude flann support.
