### ISSUE TITLE
[Filters] Incorrect random calculation in VoxelGridCovariance::getDisplayCloud

### ISSUE THREAD

**Issue by KotaYonezawa** [PointCloudLibrary/pcl#4831]
**Describe the bug**

Thanks a lot for great library.
I found an issue in VoxelGridCovariance::getDisplayCloud(), very useful function for visualizing NDT voxel covariance.

**Context**

I think following code is not correct.
(voxel_grid_covariance.hpp, line 450)

```
template<typename PointT> void
pcl::VoxelGridCovariance<PointT>::getDisplayCloud (pcl::PointCloud<PointXYZ>& cell_cloud)
{
  cell_cloud.clear ();

  int pnt_per_cell = 1000;
  boost::mt19937 rng;
  boost::normal_distribution<> nd (0.0, leaf_size_.head (3).norm ()); // <== THIS LINE
  boost::variate_generator<boost::mt19937&, boost::normal_distribution<> > var_nor (rng, nd);
```
This line should be modified as follows, I supposed.
```
  boost::normal_distribution<> nd (0.0, 1.0);
```

By this issue, covariance of each NDT cell looks too big on display cloud if the target point cloud is scaled.

Following is the code to explain issue.
Following test code outputs two pcd files.
scale_1.0.pcd is display cloud that target cloud is not scaled.
scale_10.0.pcd is display cloud that target cloud is 10 times scaled.
Note that on x10 scale case, resolution is x10 scaled.

```
#include <iostream>

#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>

#include <pcl/registration/ndt.h>

namespace pcl {
template <typename PointSource, typename PointTarget>
class NormalDistributionsTransform_Inspect : public NormalDistributionsTransform<PointSource, PointTarget> {
public:
    inline VoxelGridCovariance<PointTarget>*
    getTargetGridPtr ()
    {
        return &target_cells_;
    }
};
} // namespace pcl

int
main (int argc, char** argv)
{
  // Loading first scan of room.
  pcl::PointCloud<pcl::PointXYZ>::Ptr target_cloud (new pcl::PointCloud<pcl::PointXYZ>);
  if (pcl::io::loadPCDFile<pcl::PointXYZ> ("room_scan1.pcd", *target_cloud) == -1)
  {
    PCL_ERROR ("Couldn't read file room_scan1.pcd \n");
    return (-1);
  }
  std::cout << "Loaded " << target_cloud->size () << " data points from room_scan1.pcd" << std::endl;

  {
    pcl::NormalDistributionsTransform_Inspect<pcl::PointXYZ, pcl::PointXYZ> ndt;
    ndt.setResolution (0.5);
    ndt.setInputTarget (target_cloud);

    pcl::PointCloud<pcl::PointXYZ>::Ptr display_cloud (new pcl::PointCloud<pcl::PointXYZ>);
    ndt.getTargetGridPtr()->getDisplayCloud (*display_cloud);
    pcl::io::savePCDFileBinary ("scale_1.0.pcd", *display_cloud);
  }

  pcl::PointCloud<pcl::PointXYZ>::Ptr target_cloudx10 (new pcl::PointCloud<pcl::PointXYZ>);

  // x10 scaling
  Eigen::Matrix4f scalingMatrix (Eigen::Matrix4f::Identity());
  scalingMatrix (0, 0) = scalingMatrix (1, 1) = scalingMatrix (2, 2) = 10.0;
  pcl::transformPointCloud (*target_cloud, *target_cloudx10, scalingMatrix);

  {
    pcl::NormalDistributionsTransform_Inspect<pcl::PointXYZ, pcl::PointXYZ> ndt;
    ndt.setResolution (0.5 * 10.0); // Resolution is x10.
    ndt.setInputTarget (target_cloudx10);

    pcl::PointCloud<pcl::PointXYZ>::Ptr display_cloud (new pcl::PointCloud<pcl::PointXYZ>);
    ndt.getTargetGridPtr()->getDisplayCloud (*display_cloud);
    pcl::io::savePCDFileBinary ("scale_10.0.pcd", *display_cloud);
  }

  return (0);
}
```

**Expected behavior**

On above test, two display clouds (scale_1.0.pcd and scale_10.0.pcd) should be looks similar.

**Current Behavior**

On latest (HEAD) code, covariance looks too big on scale_10.0.pcd.

**Screenshots/Code snippets**

Following is scale_1.0.pcd. (using CloudCompare)
![scale_1 0](https://user-images.githubusercontent.com/39361859/124290126-0b847080-db8e-11eb-9e22-42f576e384f7.jpg)

Following is scale_10.0.pcd. (using CloudCompare)
![scale_10 0](https://user-images.githubusercontent.com/39361859/124290183-1b03b980-db8e-11eb-969b-c7407d84b683.jpg)

Following is scale_1.0.pcd after code modification.
![scale_1 0_modified](https://user-images.githubusercontent.com/39361859/124291708-ce20e280-db8f-11eb-9734-a80ab17bb363.jpg)

Following is scale_10.0.pcd after code modification.
![scale_10 0_modified](https://user-images.githubusercontent.com/39361859/124291762-db3dd180-db8f-11eb-8c98-061812f85077.jpg)

**Your Environment (please complete the following information):**

 - OS: Windows10
 - Compiler: Visual Studio 2019 Build Tools
 - PCL Version: HEAD

**Additional context**

I think following article is useful to understand getDisplayCloud() code. (Japanese article)
https://qiita.com/codehumgfk/items/dd5d2e6167c95478ac2d

**Comment by mvieth** [comment]
Thank you for the great description! I agree that the variance should be `1.0`, not the leaf size norm. Would you create a pull request to fix this?

**Comment by KotaYonezawa** [comment]
Thanks a lot for comment.
I'm not so familiar with github, but I tried to create pull request.
If something wrong, please let me know.
