### ISSUE TITLE
mak---->error:   epcl_poisson_reconstruction.dir/all] Error 2 Makefile:170: recipe for target 'all' failed make:

### ISSUE THREAD

**Issue by KangChou** [PointCloudLibrary/pcl#4832]
### OS and ENV:
ubuntu16.04
cuda11
python3.6
cmake-3.19
vkt8.2
QT5.12.0

`[ 72%] Built target pcl_match_linemod_template
Scanning dependencies of target pcl_poisson_reconstruction
[ 72%] Building CXX object tools/CMakeFiles/pcl_poisson_reconstruction.dir/poisson_reconstruction.cpp.o
[ 72%] Linking CXX executable ../bin/pcl_poisson_reconstruction
../lib/libpcl_surface.so.1.11.1.99: undefined reference to `qh_zero'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_poisson_reconstruction.dir/build.make:263: recipe for target 'bin/pcl_poisson_reconstruction' failed
make[2]: *** [bin/pcl_poisson_reconstruction] Error 1
CMakeFiles/Makefile2:2397: recipe for target 'tools/CMakeFiles/pcl_poisson_reconstruction.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_poisson_reconstruction.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by mvieth** [comment]
Please edit that title!
Please also add more information about your environment: What OS? Ubuntu? How are you trying to compile this? What version of Qhull do you have installed, and how did you install it?

**Comment by KangChou** [comment]
> Please edit that title!
> Please also add more information about your environment: What OS? Ubuntu? How are you trying to compile this? What version of Qhull do you have installed, and how did you install it?

### OS and ENV:
ubuntu16.04
cuda11
python3.6
cmake-3.19
vkt8.2
QT5.12.0
