### ISSUE TITLE
[pcl_ml] both pcl_ml and QtGui defines QMatrix

### ISSUE THREAD

**Issue by maz-1** [PointCloudLibrary/pcl#4857]
**Describe the bug**

Both pcl_ml and qtgui defines QMatrix, if i link both pcl_ml and QtGui statically i get duplicate symbols error

**Context**

**Expected behavior**

No duplicate symbols when link both pcl_ml and qtgui

**Current Behavior**

link both pcl_ml and QtGui statically cause duplicate symbols error

**To Reproduce**

Link a cmake project with both static qt5 and pcl

**Screenshots/Code snippets**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights

**Your Environment (please complete the following information):**

 - OS: windows 10
 - Compiler: MSVC 14.16.27023
 - PCL Version: 1.12.0

**Possible Solution**

AFAIK QMatrix is not used outside ml/src/svm.cpp so it should be safe to rename it

**Additional context**

**Comment by mvieth** [comment]
Yes, renaming it or putting it into a namespace should solve the issue. Would you be interested in opening a pull request?
