### ISSUE TITLE
Eigen::internal::aligned_free bug

### ISSUE THREAD

**Issue by xq198109** [PointCloudLibrary/pcl#4859]
I installed the PCL-1.12.0-AllInOne-msvc2019-win64 and test the fliter function of PCL using the following code "test3", a memory problem occured when the function return and the local variable release , the debug information prompt the problem is in the function Eigen::internal::aligned_free(void *) 
void test3()
{

    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);

    // Fill in the cloud data
    pcl::PLYReader reader;
    // Replace the path below with the path where you saved your file
    reader.read<pcl::PointXYZ>("E:/zhanjiang/bun_zipper.ply", *cloud);

    std::cerr << "Cloud before filtering: " << std::endl;
    std::cerr << *cloud << std::endl;

    // Create the filtering object
    pcl::StatisticalOutlierRemoval<pcl::PointXYZ> sor;
    sor.setInputCloud(cloud);
    sor.setMeanK(50);
    sor.setStddevMulThresh(1.0);
    sor.filter(*cloud_filtered);

    std::cerr << "Cloud after filtering: " << std::endl;
   // std::cerr << *cloud_filtered << std::endl;

    pcl::PCDWriter writer;
    writer.write<pcl::PointXYZ>("table_scene_lms400_inliersX.pcd", *cloud_filtered, false);

    sor.setNegative(true);
    sor.filter(*cloud_filtered);
    writer.write<pcl::PointXYZ>("table_scene_lms400_outliersX.pcd", *cloud_filtered, false);
}

 - OS: [WINDOW 10]
 - Compiler: [VS 2019]
 - PCL Version [1.12]

**Comment by larshg** [comment]
Could you enable AVX for the downstream project, I think this is the reason.
Its being fixed in #4698

**Comment by mvieth** [comment]
@xq198109 Would also be good to know where exactly the problem happens, ideally with a stack trace or the output of a debugger

**Comment by xq198109** [comment]
> I installed the PCL-1.12.0-AllInOne-msvc2019-win64 and test the fliter function of PCL using the following code "test3", a memory problem occured when the function return and the local variable release , the debug information prompt the problem is in the function Eigen::internal::aligned_free(void *)
> void test3()
> {
> 
> ```
> pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
> pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
> 
> // Fill in the cloud data
> pcl::PLYReader reader;
> // Replace the path below with the path where you saved your file
> reader.read<pcl::PointXYZ>("E:/zhanjiang/bun_zipper.ply", *cloud);
> 
> std::cerr << "Cloud before filtering: " << std::endl;
> std::cerr << *cloud << std::endl;
> 
> // Create the filtering object
> pcl::StatisticalOutlierRemoval<pcl::PointXYZ> sor;
> sor.setInputCloud(cloud);
> sor.setMeanK(50);
> sor.setStddevMulThresh(1.0);
> sor.filter(*cloud_filtered);
> 
> std::cerr << "Cloud after filtering: " << std::endl;
> ```
> 
> // std::cerr << *cloud_filtered << std::endl;
> 
> ```
> pcl::PCDWriter writer;
> writer.write<pcl::PointXYZ>("table_scene_lms400_inliersX.pcd", *cloud_filtered, false);
> 
> sor.setNegative(true);
> sor.filter(*cloud_filtered);
> writer.write<pcl::PointXYZ>("table_scene_lms400_outliersX.pcd", *cloud_filtered, false);
> ```
> 
> }
> 
> * OS: [WINDOW 10]
> * Compiler: [VS 2019]
> * PCL Version [1.12]

**Comment by xq198109** [comment]
> Could you enable AVX for the downstream project, I think this is the reason.
> Its being fixed in #4698

thanks, the problem is solved by enabling AVX

**Comment by larshg** [comment]
> > Could you enable AVX for the downstream project, I think this is the reason.
> > Its being fixed in #4698
> 
> thanks, the problem is solved by enabling AVX

Thanks for feedback 👍

**Comment by larshg** [comment]
@xq198109 I think @kunaltyagi would like this issue to remain open, until a proper fix is merged to master, so please let it be open for now.

**Comment by 01yaoyuan** [comment]
Hey,brother,you need to open advanced vector extensions in visual studio 2019,as shown in this picture
![微信图片_20250103131110](https://github.com/user-attachments/assets/42496b32-6854-4120-a118-374c58f491b6).

**Comment by wnpllrzodiac** [comment]
> Hey,brother,you need to open advanced vector extensions in visual studio 2022,as shown in this picture ![微信图片_20250103131110](https://private-user-images.githubusercontent.com/41202120/399866608-42496b32-6854-4120-a118-374c58f491b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MTM2MDksIm5iZiI6MTczNjkxMzMwOSwicGF0aCI6Ii80MTIwMjEyMC8zOTk4NjY2MDgtNDI0OTZiMzItNjg1NC00MTIwLWExMTgtMzc0YzU4ZjQ5MWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDAzNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGY3Nzg3ZTc0YTMwMjU4OWM0Y2FkZDk1NjJiY2E1ODdlOWE1OWFjYzYyMDI5YjNiMzUwYjM5OWZiOTc5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T2GDmlGFAzqZ2rwjExRZzO9Eh9liB_XIg6sv0ZGCVFM).

Cool chinese snapshot
