### ISSUE TITLE
ISSKeypoint3D::compute crashes with OMP and 0 threads.

### ISSUE THREAD

**Issue by MK-3PP** [PointCloudLibrary/pcl#4860]
Hello,

pcl::ISSKeypoint3D::compute runs into an error when started with 0 threads:
```
User Error 1001: argument to num_threads clause must be positive
```

Probably UB, because [this ](https://github.com/PointCloudLibrary/pcl/blob/97b0f0e63b3325bf8a19c99d0f0918b9cd86eb75/keypoints/include/pcl/keypoints/impl/iss_3d.hpp#L331)happens in PCL way before my build crashes somewhere in FLANN:
```
Eigen::Vector3d *omp_mem = new Eigen::Vector3d[threads_];
```

The problem is probably [here](https://github.com/PointCloudLibrary/pcl/blob/97b0f0e63b3325bf8a19c99d0f0918b9cd86eb75/keypoints/include/pcl/keypoints/iss_3d.h#L201):
```
setNumberOfThreads (unsigned int nr_threads = 0) { threads_ = nr_threads; }
```

pcl::NormalEstimationOMP does [this ](https://github.com/PointCloudLibrary/pcl/blob/97b0f0e63b3325bf8a19c99d0f0918b9cd86eb75/features/include/pcl/features/impl/normal_3d_omp.hpp#L47)instead, which is also my proposed fix:
```
template <typename PointInT, typename PointOutT> void
pcl::NormalEstimationOMP<PointInT, PointOutT>::setNumberOfThreads (unsigned int nr_threads)
{
  if (nr_threads == 0)
#ifdef _OPENMP
    threads_ = omp_get_num_procs();
#else
    threads_ = 1;
#endif
  else
    threads_ = nr_threads;
}
```

Cheers :)

**Comment by mvieth** [comment]
Thank you for your bug report, I agree with your analysis. Would you open a pull request to fix this? I would suggest to put the new implementation of `setNumberOfThreads` in the hpp file, similar as it is for `NormalEstimationOMP`.

**Comment by MK-3PP** [comment]
Pull request: #4863
