### ISSUE TITLE
user define point type compliation failure

### ISSUE THREAD

**Issue by xq198109** [PointCloudLibrary/pcl#4864]
I defined a new point type in  a header file of my of program, if i add the definition"PCL_NO_PRECOMPILE" in front of "<pcl/surface/convex_hull.h>" the program was builded failed,  the failure information prompt "pop_t" is undefined in "C:\Program Files\PCL 1.12.0\3rdParty\FLANN\include\flann\algorithms". if i move the  definition"PCL_NO_PRECOMPILE" to the back of "<pcl/surface/convex_hull.h>" the program was builded succeed. is this a PCL bug? 

failure code
```

 
#ifndef PCL_NO_PRECOMPILE
#define PCL_NO_PRECOMPILE
#endif   
#include <pcl/surface/convex_hull.h>
	
```

success code
```

 
 
#include <pcl/surface/convex_hull.h>
#ifndef PCL_NO_PRECOMPILE
#define PCL_NO_PRECOMPILE
#endif  
	
```

**Your Environment (please complete the following information):**

 - OS: [windows10 ]
 - Compiler: [:VS 2019]
 - PCL Version [1.12] 
 - PCL Type: [Installed]

**Comment by mvieth** [comment]
The code is quite hard to read, could you format it correctly? And explain again where you are adding what code. Are you changing anything in `C:\Program Files\PCL 1.12.0\3rdParty\FLANN\...`?

**Comment by xq198109** [comment]
> The code is quite hard to read, could you format it correctly? And explain again where you are adding what code. Are you changing anything in `C:\Program Files\PCL 1.12.0\3rdParty\FLANN\...`?

No,I do not change anything in `C:\Program Files\PCL 1.12.0\3rdParty\FLANN\...

**Comment by xq198109** [comment]
> The code is quite hard to read, could you format it correctly? And explain again where you are adding what code. Are you changing anything in `C:\Program Files\PCL 1.12.0\3rdParty\FLANN\...`?

the failure information prompt "pop_t" is undefined in "C:\Program Files\PCL 1.12.0\3rdParty\FLANN\include\flann\algorithms", so i try to add the definition of   pop_t  in the code , but it  can not work;
![image](https://user-images.githubusercontent.com/48425847/127279469-946d6193-1c6a-4d88-8da7-397c0a678a01.png)

**Comment by xq198109** [comment]
> The code is quite hard to read, could you format it correctly? And explain again where you are adding what code. Are you changing anything in `C:\Program Files\PCL 1.12.0\3rdParty\FLANN\...`?

if I define PCL_NO_PRECOMPILE in front of including <pcl/filters/statistical_outlier_removal.h> , <pcl/filters/radius_outlier_removal.h>, or  <pcl/surface/convex_hull.h> ,the error come out ,  i can use pcl::PassThrough to process my user defined point type points ,but can not use pcl::ProgressiveMorphologicalFilter to process them .

**Comment by mvieth** [comment]
What happens if you move the `typedef unsigned long long pop_t;` as described [in this related issue](https://github.com/flann-lib/flann/issues/386)?

**Comment by mvieth** [comment]
@xq198109 Did my suggestion above solve your problem? If I don't hear from you, I will assume that it does solve the problem and will close this issue. Seems like that should be fixed in FLANN, but since FLANN is basically unmaintained ...

**Comment by xq198109** [comment]
Yes，I  add "typedef unsigned long long pop_t" in front of `HammingLUT lut;
        result = lut(reinterpret_cast<const unsigned char*> (a),
                     reinterpret_cast<const unsigned char*> (b), size * sizeof(pop_t));` ,and include "flann_cpp_s.lib" in my project,solve the problem,Thanks you
