### ISSUE TITLE
[pcl::PassThrough] template type to filter

### ISSUE THREAD

**Issue by flynneva** [PointCloudLibrary/pcl#4866]
It would be great to use the pcl::PassThrough filter to filter other non-float values (intensity, rgb, etc.) instead of just floats.

**Context**

Right now the pcl::PassThrough package only supports a min/max value for floats. It should be not too hard to implement a template to define the type to filter rather than just floats (see above for some use cases).

**Expected behavior**

User-defined type to filter rather than only floats.

**Current Behavior**

Can only use a passthrough filter if the value is a float.

**Describe the solution you'd like**

User defined type to filter rather than just floats

**Describe alternatives you've considered**

Changing my UINT16 intensity values to floats, but this adds unnecessary bytes to the data which add up over time with large pointclouds.

**Comment by kunaltyagi** [comment]
We're trying to remove the passthrough filter soon (hopefully, with similar or the same api).

There are 2 options I can see for your use case:
* Use `ConditionalRemoval`: Stable, should work
* Use `experimental::FunctionFilter`: Very flexible and fast, but unstable API. This is also going to be the underlying code for Passthrough filter in the future (once the API stabilizes)

**Comment by flynneva** [comment]
`ConditionalRemoval` is perfect. thanks for the info! looking forward to seeing the finished `FunctionFilter` as well...sounds interesting.
