### ISSUE TITLE
Exception thrown when using pcl::PassThrough filter when in/out is same cloud

### ISSUE THREAD

**Issue by vestri** [PointCloudLibrary/pcl#4869]
**Describe the bug**

I updated PCL from 1.11.1 to 1.12.0 and got some exceptions. I simply use a  passThrough filter on a cloudPoint. It is functionning with PCL-1.11.1 (no exception thrown).

**Expected behavior**

I expect to have the same behaviour as version 1.11.1

**Current Behavior**

An exception is launch in 
/** \internal Frees memory allocated with aligned_malloc. */
EIGEN_DEVICE_FUNC inline void aligned_free(void *ptr)
{
  #if (EIGEN_DEFAULT_ALIGN_BYTES==0) || EIGEN_MALLOC_ALREADY_ALIGNED
    std::free(ptr);
  #else
    handmade_aligned_free(ptr);
  #endif
}

**To Reproduce**
Next is my code

        // filter with 3D min/max coordinates
        template <typename pointT>
        typename pcl::PointCloud<pointT>::Ptr applyPassThroughFilter(typename pcl::PointCloud<pointT>::Ptr& cloud, double minX, double maxX, double minY, double maxY, double minZ, double maxZ)
        {
            pcl::PointCloud<pointT>::Ptr out(new pcl::PointCloud<pointT>);
            pcl::PassThrough<pointT> pass;
            pass.setInputCloud(cloud);
            pass.setFilterFieldName("x");
            pass.setFilterLimits(minX, maxX);
            pass.filter(out);
            pass.setInputCloud(out);
            pass.setFilterFieldName("y");
            pass.setFilterLimits(minY, maxY);
            pass.filter(out);
            pass.setInputCloud(out);
            pass.setFilterFieldName("z");
            pass.setFilterLimits(minZ, maxZ);
            pass.filter(*out);
            return out;
        }
        // explicit instanciations
        template pcl::PointCloud<pcl::PointXYZ>::Ptr applyPassThroughFilter<pcl::PointXYZ>(pcl::PointCloud<pcl::PointXYZ>::Ptr& cloud, double minX, double maxX, double minY, double maxY, double minZ, double maxZ);
        template pcl::PointCloud<pcl::PointNormal>::Ptr applyPassThroughFilter<pcl::PointNormal>(pcl::PointCloud<pcl::PointNormal>::Ptr& cloud, double minX, double maxX, double minY, double maxY, double minZ, double maxZ);
        tmplate pcl::PointCloud<pcl::PointXYZRGB>::Ptr applyPassThroughFilter<pcl::PointXYZRGB>(pcl::PointCloud<pcl::PointXYZRGB>::Ptr& cloud, double minX, double maxX, double minY, double maxY, double minZ, double maxZ);

**Your Environment (please complete the following information):**

 - PCL Version 1.12.0 on windows

**Possible Solution**

could be linked to  https://github.com/PointCloudLibrary/pcl/pull/4742

Thanks

**Comment by larshg** [comment]
Its the same as for this one:https://github.com/PointCloudLibrary/pcl/issues/4859#event-5086543058

You need to enable AVX for your project.
