### ISSUE TITLE
[custom] Merge multiple Pcd files

### ISSUE THREAD

**Issue by ManChrys** [PointCloudLibrary/pcl#4871]
OS:Ubuntu 18.04 

Hello,

i have a livox mid 40 which output .lvx file. I convert lvx file to bag and after that to pcd files (one for every frame), so now i have 4k pcd files. Is there any way to merge all of this frames into one file and one point cloud ? 

Thanks in advance.

**Comment by mvieth** [comment]
The tool `pcl_concatenate_points_pcd` (source file `concatenate_points_pcd.cpp`) might be what you are looking for. But it also depends: if your 3D scanner changed position or orientation during recording or if the recorded environment changed, simply merging the files is not a good idea, instead you then might want to register and transform the frames. Also: 4k frames is a lot, I don't know how many points there are per frame, but using _all_ frames might not give you better results, just longer processing times than e.g. 100 frames (or even fewer). Depends on what you want to do exactly.
P.S.: Please use the [Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for application specific questions like this in the future.
