### ISSUE TITLE
[PCLVisualizer] try to inherit PCLVisualizer, adding custom OrientationMarkerWidgetAxes causing program crushed

### ISSUE THREAD

**Issue by ryanreadbooks** [PointCloudLibrary/pcl#4872]
### My environment:

* windows10
* MS2017 
* PCL1.8.1 + VTK-8.0 
* Qt5.12.10

I tried to add a custom orientationMarkerWidgetAxes in PCLVisualizer by inheriting the PCLVisualizer class. Below lists my code.

### **The header file [content_visualizer.h] is:**

```c++
#pragma once
#include <vtkRenderWindow.h>
#include <vtkOrientationMarkerWidget.h>
#include <vtkAxesActor.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <string>

using namespace pcl::visualization;

class ContentVisualizer : public PCLVisualizer {
public:
	ContentVisualizer(const std::string& name = "", const bool create_interactor = true);
public:
	void addCustomOrientationMarkerWidgetAxes(vtkRenderWindowInteractor* interactor,
		double x, double y, double x_width, double y_width);
private:
	vtkSmartPointer<vtkOrientationMarkerWidget> _axes_widget;
};
```

### **The source file [content_visualizer.cpp] is:**

```c++
#include "content_visualizer.h"
#include <vtkSmartPointer.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkInteractionWidgetsModule.h>

ContentVisualizer::ContentVisualizer(const std::string& name, const bool create_interactor) : PCLVisualizer(name, create_interactor) {}

void ContentVisualizer::addCustomOrientationMarkerWidgetAxes(vtkRenderWindowInteractor* interactor, double x, double y, double x_width, double y_width) {
	if (_axes_widget == nullptr) {
		vtkSmartPointer<vtkAxesActor> axes = vtkSmartPointer<vtkAxesActor>::New();
		_axes_widget = vtkSmartPointer<vtkOrientationMarkerWidget>::New();
		_axes_widget->SetOutlineColor(0.9300, 0.5700, 0.1300);
		_axes_widget->SetOrientationMarker(axes);
		_axes_widget->SetInteractor(interactor);
		_axes_widget->SetViewport(x, y, x_width, y_width);
		_axes_widget->SetEnabled(true);
		_axes_widget->InteractiveOn();
		// _axes_widget->SetInteractive(0);
	}
	else {
		_axes_widget->SetEnabled(true);
	}
}

```

### And I call the addCustomOrientationMarkerWidgetAxes function like this:

```c++
// ui.geometryDisplayWidget is a QVTKWidget from Qt
// _mid_visualizer is boost::shared_ptr<ContentVisualizer>
_mid_visualizer.reset(new ContentVisualizer("cus_visualizer", false));
ui.geometryDisplayWidget->SetRenderWindow(_mid_visualizer->getRenderWindow());
_mid_visualizer->setupInteractor(ui.geometryDisplayWidget->GetInteractor(), 
ui.geometryDisplayWidget->GetRenderWindow());
_mid_visualizer->setBackgroundColor(0.0275, 0.4549, 0.3137); 
// I tried to add my custom orientation marker widget
_mid_visualizer->
    addCustomOrientationMarkerWidgetAxes(ui.geometryDisplayWidget->GetInteractor(), 
                                     0.0, 0.0, 0.2, 0.2);
// if I comment the above line of code, the program runs just fine.
ui.geometryDisplayWidget->update();
```

**But when I called the addCustomOrientationMarkerWidgetAxes function, the following error occured in MS2017.**

Exception thrown at 0x0000000000000000 in AppView.exe: 0xC0000005: Access violation executing location 0x0000000000000000.

![the error message I got](https://user-images.githubusercontent.com/28601090/127834079-0ab7dc71-b8fd-46e5-9220-2de86eb7568d.jpg)

**Is there something I miss in inheriting the PCLVisualizer class or in using VTK. Or are there any other methods that I can use to add a custom OrientationMarkerWidgetAxes rather than using the official PCLVisualizer::addOrientationMarkerWidgetAxes function.**

**Thanks a lot!**

**Comment by larshg** [comment]
@ryanreadbooks Sorry for getting back so late. Did you solve your issue? It seems that the interactor might be a null pointer.
If you run in debug, VS should stop where it happens.

**Comment by larshg** [comment]
Please next time, make a complete example. I did a minimal example without Qt and QVTWidget, so it differs a bit but initial I got the same error which was a missing interactor.
You can see an example here: https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/qt_visualizer/pclviewer.cpp
I'll close it as a not in bug in PCL, but feel free to respond if you still have trouble.
