### ISSUE TITLE
Win86 docker image fails to build on Azure

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#4873]
See here: https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=11
The Win64 docker builds successfully.
The problem is at this command, but there is no error message:
```
RUN cd .\vcpkg;                                                `
    .\bootstrap-vcpkg.bat;                                            `
    .\vcpkg install boost flann eigen3 qhull vtk[qt,opengl] gtest benchmark --triplet $Env:PLATFORM-windows-rel --clean-after-build;
```

**Comment by larshg** [comment]
Opened issue here https://github.com/microsoft/vcpkg/issues/19333
