### ISSUE TITLE
Based the vcpkg to install PCL, but the visualization function can't be used.

### ISSUE THREAD

**Issue by sycamore27** [PointCloudLibrary/pcl#4878]
Based on windows10 and VS2019, use the vcpkg to install PCL. But the visualization function can't be used. How can I use vcpkg to realize the visualization function? Thank you very much!

**Comment by larshg** [comment]
Could you try follow https://github.com/larshg/pcl/blob/UpdateWindowsTutorial/doc/tutorials/content/pcl_vcpkg_windows.rst and see if it gives you any hints :wink:

**Comment by larshg** [comment]
Alternatively you can try merge https://github.com/microsoft/vcpkg/pull/18855

**Comment by sycamore27** [comment]
@larshg Thanks very much! Let me have a try~

**Comment by mvieth** [comment]
@sycamore27 What is the status? Can this issue be closed?
