### ISSUE TITLE
[pcl 1.12 /surface] duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;

### ISSUE THREAD

**Issue by cdb0y511** [PointCloudLibrary/pcl#4882]
My code works fine with pcl.1.11.1, however when i update to the pcl 1.12, "duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;" happens.
I think the name of function calculatePrincipalCurvatures is changed,  corrected from Principle? #4505

**To Reproduce**

include<pcl/surface/mls.h> or include <pcl/surface/impl/mls.hpp>
 "duplicate definition of plc::mlsresult::calculatePrincipalCurvatures (const double u, const double v) const;" is showed at link time.

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]
 - Compiler: [ GCC 8.1]
 - PCL Version [1.12, and latest from git]

**Possible Solution**

this commit may related with this bug
https://github.com/PointCloudLibrary/pcl/commit/a3a4ee918094b94c8ef10dc360d1aeb2803da36f

**Additional context**

**Comment by mvieth** [comment]
1. Is it possible that there are still some files left from PCL 1.11.1? Not sure if this can cause the problem, but to be sure, remove everything from PCL and then install the new version again
2. Are you including both mls.h _and_ mls.hpp? Under most circumstances, you should only include *.h files, not *.hpp. Or are you using `PCL_NO_PRECOMPILE`?

**Comment by larshg** [comment]
I noticed the old version is marked as inline, but new one is not?

**Comment by kunaltyagi** [comment]
I think that's correct. This function (and others from MLSResult) should be moved either:
* to the cpp file or
* inside the class definition
instead of using `inline`

**Comment by cdb0y511** [comment]
> 1. Is it possible that there are still some files left from PCL 1.11.1? Not sure if this can cause the problem, but to be sure, remove everything from PCL and then install the new version again
> 2. Are you including both mls.h _and_ mls.hpp? Under most circumstances, you should only include *.h files, not *.hpp. Or are you using `PCL_NO_PRECOMPILE`?

Thanks for the reply.
1. I remove the pcl 1.11.1 by "sudo make uninstall". Does it remove every old file? 
2. I carefully checked, no double include. I try include mls.h or mls.hpp respectively. The same error always occurs at link time. I use the PCL_NO_PRECOMPILE cause I define a point type.

**Comment by cdb0y511** [comment]
> I think that's correct. This function (and others from MLSResult) should be moved either:
> 
> * to the cpp file or
> * inside the class definition
>   instead of using `inline`

Can you or anyone give a hotfix?
I think this is a frequently used function on the surface.

**Comment by cdb0y511** [comment]
I am curious, does anyone try the pcl::MLSResult::calculatePrincipalCurvatures (const double u, const double v) const?
I don't find any call from mls.

**Comment by larshg** [comment]
Indeed, there doesnt seem to be any usage of the function. 

Not even in a unit test. 

Maybe you could write a unit test?

**Comment by AdamWill** [comment]
This actually prevents pcl building from scratch in Fedora. I'm trying to get it updated and rebuilt in Rawhide (it's blocking several dep chains currently), but the build fails on this problem - see https://kojipkgs.fedoraproject.org//work/tasks/9175/73809175/build.log .

**Comment by mvieth** [comment]
@cdb0y511 Can you post your code and CMakeLists.txt where the error occurs? I am trying to test a possible fix, but I can't reproduce the error

**Comment by mvieth** [comment]
I was finally able to reproduce the error: With an executable that is constructed from two .cpp files (e.g. `add_executable(mls_lib mls_lib1.cpp mls_lib2.cpp)`), and both .cpp files have `#define PCL_NO_PRECOMPILE 1` and `#include <pcl/surface/mls.h>`

**Comment by cdb0y511** [comment]
The easiest way is to comment them in mls.h and mls.hpp
   //Eigen::Vector2f
    //calculatePrincipalCurvatures (const double u, const double v) const;

    //PCL_DEPRECATED(1, 15, "use calculatePrincipalCurvatures() instead")
    //inline Eigen::Vector2f
    //calculatePrincipleCurvatures (const double u, const double v) const { return calculatePrincipalCurvatures(u, v); };

**Comment by mvieth** [comment]
We can't simply remove those functions from the library. It would be helpful if you could test the current solution in the linked pull request. I am pretty sure that it should solve the issue, but if you would also verify that, that would be great

**Comment by cdb0y511** [comment]
Thanks, I am glad it is solved.
