### ISSUE TITLE
[registration] A typo of hessian matrix computation in NDT.

### ISSUE THREAD

**Issue by HuaTsai** [PointCloudLibrary/pcl#4888]
Hello developers, thanks for your great work and I am appreciated of it.

**Describe the bug**

I think there is a small typo in the NDT implementation which has not been found for several years.

https://github.com/PointCloudLibrary/pcl/blob/fad821ef31eb92719c1005812666136f9664d365/registration/include/pcl/registration/impl/ndt.hpp#L295

Follow the derivation of (6.21) in paper [Magnusson 2009], the term `sy` in `d1` should be negative.

Note that the paper is incorrect at the term `-sx * sz` in `c2`, and pcl corrected it.
However, the paper is correct at the term `-sy` in `d1`, but the change of the sign by pcl made it incorrect.

**Possible Solution**

Change the code to `Eigen::Vector4d((-cy * cz), (cy * sz), (-sy), 0.0f);`.

**Additional context**

To avoid tedious computation by hand, I provide an easy code for symbolic mathematics evaluation.
I will be glad if the following code can help.

``` python
import sympy as sym

x1, x2, x3 = sym.symbols('x_1, x_2, x_3')
x = sym.Matrix([x1, x2, x3])

tx, ty, tz = sym.symbols('t_x, t_y, t_z')
t = sym.Matrix([tx, ty, tz])

thx, thy, thz = sym.symbols('θ_x, θ_y, θ_z')
Rx = sym.Matrix([[1, 0, 0],
                 [0, sym.cos(thx), -sym.sin(thx)],
                 [0, sym.sin(thx), sym.cos(thx)]])
Ry = sym.Matrix([[sym.cos(thy), 0, sym.sin(thy)],
                 [0, 1, 0],
                 [-sym.sin(thy), 0, sym.cos(thy)]])
Rz = sym.Matrix([[sym.cos(thz), -sym.sin(thz), 0],
                 [sym.sin(thz), sym.cos(thz), 0],
                 [0, 0, 1]])

te = Rx * Ry * Rz * x + t
params = sym.Matrix([tx, ty, tz, thx, thy, thz])

h0 = sym.hessian(te[0], params)
h1 = sym.hessian(te[1], params)
h2 = sym.hessian(te[2], params)
a = sym.Matrix([h0[3, 3], h1[3, 3], h2[3, 3]])
b = sym.Matrix([h0[3, 4], h1[3, 4], h2[3, 4]])
c = sym.Matrix([h0[3, 5], h1[3, 5], h2[3, 5]])
d = sym.Matrix([h0[4, 4], h1[4, 4], h2[4, 4]])
e = sym.Matrix([h0[4, 5], h1[4, 5], h2[4, 5]])
f = sym.Matrix([h0[5, 5], h1[5, 5], h2[5, 5]])

sym.pprint(d[0])
# -x₁⋅cos(θ_y)⋅cos(θ_z) + x₂⋅sin(θ_z)⋅cos(θ_y) - x₃⋅sin(θ_y)
```

**Comment by mvieth** [comment]
Thank you for reporting this! I agree, the term should be `(-sy)`, not `(sy)`. Would you create a pull request to fix this? It would also be great if you would add a comment to c2 explaining that the formula in the paper/thesis has an incorrect sign, but the formula in the PCL code has the correct sign.
