### ISSUE TITLE
[compile error] Error including cloud_viewer.h

### ISSUE THREAD

**Issue by NekoooooOoi** [PointCloudLibrary/pcl#4890]
OS:Windows 10
      the latest version of visual studio 2019
      pcl is downloaded by vcpkg
      the version of pcl is 1.11.1

## Here's my code:

#include <iostream>
#include <string>
#include <pcl/point_types.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <pcl/PCLPointCloud2.h>
#include <pcl/visualization/cloud_viewer.h>

using namespace pcl;
using namespace pcl::io;
using namespace std;

int main() {
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    if (pcl::io::loadPLYFile<pcl::PointXYZ>("bag.ply", *cloud) == -1) {
        PCL_ERROR("Couldnot read file.\n");
        system("pause");
        return(-1);
    }

    pcl::visualization::CloudViewer viewer("Cloud Viewer");
    viewer.showCloud(cloud);
    system("pause");
    return(0);
}

## Here's the output:
Build started...
1>------ Build started: Project: CPCsegment, Configuration: Debug x64 ------
1>CPC.cpp
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\interactor_style.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\pcl_visualizer.h(1606,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\impl\pcl_visualizer.hpp(581,42): fatal error C1017: invalid integer constant expression
1>Done building project "CPCsegment.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
![image](https://user-images.githubusercontent.com/86993604/129046464-271f2db5-7f13-43fa-ad97-8bfc43b24dad.png)

**Comment by mvieth** [comment]
See issue #4687

**Comment by larshg** [comment]
You can try install pcl master using --head in the vcpkg install command, when installing PCL after alle dependencies has been installed.

Also, you can see if this one makes sense:
https://github.com/larshg/pcl/blob/UpdateWindowsTutorial/doc/tutorials/content/pcl_vcpkg_windows.rst

**Comment by kunaltyagi** [comment]
Close as solved?

**Comment by NekoooooOoi** [comment]
@larshg  Thanks for your advice. However, there're some new problems.
I reinstalled the pcl in the vcpkg by the command "vcpkg install pcl[qt,vtk]:x64-windows", and some new issues occur. I didn't change the code.

##Here's the output:
Build started...
1>------ Build started: Project: CPCsegment, Configuration: Debug x64 ------
1>CPC.cpp
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\point_cloud_color_handlers.h(611,11): error C4996: 'pcl::visualization::PointCloudColorHandler<pcl::PCLPointCloud2>::getColor': use getColor() without parameters instead (It will be removed in PCL 1.12)
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\interactor_style.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\pcl_visualizer.h(1606,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\impl\pcl_visualizer.hpp(1704,35): error C2039: 'WritePointer': is not a member of 'vtkCellArray'
1>C:\vcpkg\installed\x64-windows\include\vtk-9.0\vtkUnstructuredGrid.h(38): message : see declaration of 'vtkCellArray'
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\pcl_visualizer.h(978,9): message : This diagnostic occurred in the compiler generated function 'bool pcl::visualization::PCLVisualizer::addPolygonMesh(const pcl::PointCloud<PointT>::ConstPtr &,const std::vector<pcl::Vertices,std::allocator<pcl::Vertices>> &,const std::string &,int)'
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\impl\pcl_visualizer.hpp(1881,28): error C2039: 'WritePointer': is not a member of 'vtkCellArray'
1>C:\vcpkg\installed\x64-windows\include\vtk-9.0\vtkUnstructuredGrid.h(38): message : see declaration of 'vtkCellArray'
1>C:\vcpkg\buildtrees\pcl\src\ade837d55c-9cde649e93.clean\visualization\include\pcl\visualization\pcl_visualizer.h(990,9): message : This diagnostic occurred in the compiler generated function 'bool pcl::visualization::PCLVisualizer::updatePolygonMesh(const pcl::PointCloud<PointT>::ConstPtr &,const std::vector<pcl::Vertices,std::allocator<pcl::Vertices>> &,const std::string &)'
1>Done building project "CPCsegment.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

##Here's the screenshot of the output
![image](https://user-images.githubusercontent.com/86993604/129441813-5515be32-3f57-4a83-8896-423f285ab4db.png)

**Comment by larshg** [comment]
Did you get it working :-) ?

**Comment by NekoooooOoi** [comment]
@larshg  I tried the right command “vcpkg install pcl[vtk,qt] —head”, however, a new error occurred in the vcpkg installing process.

 It’s about the CMake, the procedure can’t find the PCLConfig.cmake patch. And I opened a new issue in the vcpkg repository at https://github.com/microsoft/vcpkg/issues/19577.

Do you know something about the reason why this error happens during the vcpkg installing process?

Is there any chances that I could download a previous version of pcl or vtk through vcpkg so that I can use the visualization module in my work?

**Comment by larshg** [comment]
Ah, its because we added some changes to the PCLConfig.cmake.in and now one of the patched doesn't match.

You can try clone PCL directly and then just use VCPKG for all the dependencies.

Alternatively you can try checkout https://github.com/microsoft/vcpkg/issues/17662

Which are in progress of adding pcl 1.12. It should work on windows.

**Comment by NekoooooOoi** [comment]
@larshg Thanks a lot for your help. 

But I don’t really know how to “ clone PCL directly and then just use VCPKG for all the dependencies”. My understanding is to use the command “git clone” to clone the PCL file directly and then copy the PCL file to the directory “vcpkg/downloads”, and the use the command “vcpkg install pcl[vtk,qt] —head”. 

Is my understanding right? If not, is there any tutorials which can help me understand how to do that?

**Comment by NekoooooOoi** [comment]
Or what you mean is to add the cloned PCL file to the include directory in the Visual Studio? And use command “vcpkg install vtk,qt” to download the dependencies.

Is the second understanding right? lol

**Comment by NekoooooOoi** [comment]
Or what you mean is to add the cloned PCL file to the include directory in the Visual Studio? And use command “vcpkg install vtk,qt” to download the dependencies.

Is the second understanding right? lol

**Comment by larshg** [comment]
Well, when you try to install PCL with vcpkg, it install all dependencies for it, ie. Boost, eigen, flann, vtk.

However its probably easiest to try merge in the PR for pcl 1.12 in the vcpkg directory.

Try in vcpkg folder:
git fetch origin pull/18855/head:pclpr

This fetches the PR to branch "pclpr"

Then: git checkout pclpr
