### ISSUE TITLE
3D object recognition tutorial returns wrong result

### ISSUE THREAD

**Issue by lucarossini-iit** [PointCloudLibrary/pcl#4898]
Hello,

I am trying to run the 3D object recognition tutorial following these [instructions](https://pcl.readthedocs.io/projects/tutorials/en/latest/correspondence_grouping.html#correspondence-grouping). I copied and pasted the code as written in the tutorial but when I run it, it returns me the following wrong result:

```
Failed to find match for field 'rgba'.
Model total points: 13704; Selected Keypoints: 739
Scene total points: 307200; Selected Keypoints: 3747
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 1983
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 1548
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 1158
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 2737
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 2262
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 838
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 907
Correspondences found: 1783
Model instances found: 1

    Instance 1:
        Correspondences belonging to this instance: 77

            |  1.000 -0.000 -0.000 | 
        R = | -0.000  1.000 -0.000 | 
            |  0.000  0.000  1.000 | 

        t = < 0.000, -0.000, -0.000 >

```

However, the visualization tool rightly shows the scene and the milk cartoon highlighted in red. I attach a picture from the visualization tool:

![image](https://user-images.githubusercontent.com/57897293/129448786-43a4034d-cc28-43a7-abb6-7298b9329c69.png)

I am running the simulation on Ubuntu 20.04, using GCC 9.3.0 and PCL version 1.10.
Thank you a lot for your work and support.

**Comment by mvieth** [comment]
Regarding `Failed to find match for field 'rgba'.` : this is not a problem, `milk.pcd` just doesn't contain colour values. You can use `milk_color.pcd` instead (in the test folder of this repo), but that shouldn't matter.
Regarding `The local reference frame is not valid! Aborting description of point with index`: If that only appears for a few points then it should be fine. That might be the case for points in sparse regions.
The fact that the printed transformation is just the identity transformation is probably because `milk.pcd` seems to fit perfectly on `milk_cartoon_all_small_clorox.pcd` (without transformation). You can try to transform `milk.pcd` and use the transformed cloud, e.g. like this: `pcl_transform_point_cloud milk.pcd /tmp/milk.pcd -trans 0.1,0.2,-0.3`.
The tutorial should probably be updated in some way to avoid confusion and to use clouds where the transformation is not identity.

**Comment by lucarossini-iit** [comment]
Following you suggestion, I moved the points along the x-y-z axis of the model cloud. The results fit this modification as expected. Thank you very much for you fast explanation.

**Comment by mvieth** [comment]
You are welcome!

**Comment by larshg** [comment]
The tutorial do have a transformation that is different from identity, so it seems odd if you get these results with the tutorial code.

**Comment by mvieth** [comment]
> The tutorial do have a transformation that is different from identity, so it seems odd if you get these results with the tutorial code.

Are you sure? I ran the code as described in the tutorial and I also got an identity transform. I suspect that the example output in the tutorial came from different clouds than `milk.pcd` and `milk_cartoon_all_small_clorox.pcd`

**Comment by larshg** [comment]
Well, it seems for sure you are Right @mvieth. I also get identity. And I ust tried to rephrase the result from the tutorials but it seems to from different clouds. However the mentioned clouds haven't changed the last 6 years at least. So still seems a bit odd 😄

**Comment by lucarossini-iit** [comment]
Following the discussion, it was odd for me as well to have obtained the identity as a result copying the code as written in the tutorial. However, it is now clear how the algorithm works. I didn't understand that the transformation matrix refers to a reference frame fixed in the central point of the model cloud. 

I will follow the discussion for any further update!

**Comment by larshg** [comment]
Ahh, there is also some PCDs in this repo: https://github.com/PointCloudLibrary/data/tree/master/tutorials/correspondence_grouping

**Comment by larshg** [comment]
But colors of the scene in the repo, seems not to be working. Also they are mirrored someshow.
The transformation does however ends up as the one in the tutorial.
