### ISSUE TITLE
The cloud viewer cannot correctly show the point cloud

### ISSUE THREAD

**Issue by NekoooooOoi** [PointCloudLibrary/pcl#4899]
Recently I opened an issue about the compiling of cloudviewer in https://github.com/PointCloudLibrary/pcl/issues/4890. And thanks for @larshg 's advice, I finally successfully installed the pcl 1.12. However, when I try to use the visualization module, a new issue occurs.
## Here's my code
#include <iostream>
#include <string>
#include <pcl/point_types.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <pcl/PCLPointCloud2.h>
#include <pcl/visualization/cloud_viewer.h>

using namespace pcl;
using namespace pcl::io;
using namespace std;

int main() {
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
    if (pcl::io::loadPLYFile<pcl::PointXYZRGB>("bag.ply", *cloud) == -1) {
        PCL_ERROR("Couldnot read file.\n");
        system("pause");
        return(-1);
    }
    std::cout << "Loaded "
        << cloud->width * cloud->height
        << " data points from test_pcd.pcd with the following fields: "
        << std::endl;
    for (size_t i = 0; i < cloud->points.size(); ++i)
        std::cout << "    " << (int)cloud->points[i].r
        << " " << (int)cloud->points[i].g
        << " " << (int)cloud->points[i].b
        << std::endl;

    pcl::visualization::CloudViewer viewer("Cloud Viewer");
    viewer.showCloud(cloud);
    system("pause");
    return(0);
}

Since I can see the output of the following code :
>    for (size_t i = 0; i < cloud->points.size(); ++i)
>        std::cout << "    " << (int)cloud->points[i].r
>        << " " << (int)cloud->points[i].g
>        << " " << (int)cloud->points[i].b
>        << std::endl;
>
So I think the point cloud file 'bag.ply' is successfully loaded.
But I cannot see the output of the cloudviewer, it's like this:
![image](https://user-images.githubusercontent.com/86993604/129482097-4c06a7b3-af35-4146-80ed-fa65cd40fe33.png)

## Here's some of the log：
Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 271
vtkOpenGLPolyDataMapper::GetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetVertexShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 263
vtkOpenGLPolyDataMapper::SetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetVertexShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 301
vtkOpenGLPolyDataMapper::GetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetGeometryShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 293
vtkOpenGLPolyDataMapper::SetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetGeometryShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 286
vtkOpenGLPolyDataMapper::GetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetFragmentShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 278
vtkOpenGLPolyDataMapper::SetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetFragmentShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 271
vtkOpenGLPolyDataMapper::GetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetVertexShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 263
vtkOpenGLPolyDataMapper::SetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetVertexShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 301
vtkOpenGLPolyDataMapper::GetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetGeometryShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 293
vtkOpenGLPolyDataMapper::SetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetGeometryShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 286
vtkOpenGLPolyDataMapper::GetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetFragmentShaderCode instead.

Generic Warning: In C:\vcpkg\buildtrees\vtk\src\ad8774e85e-b4218d18df.clean\Rendering\OpenGL2\vtkOpenGLPolyDataMapper.cxx, line 278
vtkOpenGLPolyDataMapper::SetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetFragmentShaderCode instead.

**Comment by NekoooooOoi** [comment]
I‘ve tried to do some changes which are mentioned in the log above in the 'vtkOpenGLPolyDataMapper.cxx' file, however, i didn't work.

**Comment by larshg** [comment]
The warnings are not an issue. They can be disabled.
Have you tried pressing R to reset camera, or move the camera around?

**Comment by NekoooooOoi** [comment]
@larshg  It works!!!! Thanks a lot for your help these days! I really appreciate you!

**Comment by larshg** [comment]
Np.
To disable warnings you can add this:

vtkObject::GlobalWarningDisplayOff()
