### ISSUE TITLE
cuda filters voxel grid

### ISSUE THREAD

**Issue by ravikiransama** [PointCloudLibrary/pcl#4907]
Hi,
we are planning to use the cuda module of the pcl. We had started building the cuda, and found that the module in the cuda filters voxel grid is not built. I checked it and found that there is not cmakelists.  I would like to know if this is work in progress or is it finished?
BR
Ravi

**Comment by mvieth** [comment]
I think this answer your question: #4474 Short answer: the voxel grid in the cuda module is currently unusable.
