### ISSUE TITLE
What's the meaning of the unlabeled points, or labeled "0" points, in the Supervoxel segmentation of point cloud?

### ISSUE THREAD

**Issue by sycamore27** [PointCloudLibrary/pcl#4908]
What's the meaning of the unlabeled points, or labeled "0" points, in the Supervoxel segmentation of point cloud? How can I know what kind of supervoxels have these "0" points been divided into?
<img width="450" alt="591ff0e093440dd2bfa5515c8ce9886" src="https://user-images.githubusercontent.com/56253997/130315892-e3142084-24fc-4499-a0a4-a4f74838954b.png">

**Comment by mvieth** [comment]
If you look at [the implementation](https://github.com/PointCloudLibrary/pcl/blob/85fc1707dd28f4104a7cf6ab0f8570d11ec1b4c4/segmentation/include/pcl/segmentation/impl/supervoxel_clustering.hpp#L591), you see that for example points get the label 0 when they contain non-finite values (NaNs, infinity).
