### ISSUE TITLE
[pcl_conversions] toPCL segfaults sometimes with `munmap_chunk(): invalid pointer`

### ISSUE THREAD

**Issue by Kaju-Bubanja** [PointCloudLibrary/pcl#4912]
**Describe the bug**

I'm running a ros2 node with a sensor_msg pointcloud callback and transform that msg to a pcl cloud. This conversion works often, but sometimes the conversion segfaults.

**Context**

I can reproduce the issue in the debugger and step trough the frames and it seems like a deallocation of some memory is the problem. Below the stack trace with an arrow of where the debugger stopped.
Looking at the data in the pcl_conversions frame pcl_pc2 and pc2 they seem to be correctly copied from pc2 to pcl_pc2. The data field is the same in both and all the other fields seem to be copied correctly

```
// My code

void ObjectDetector::pointcloud_callback(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
    // Class variable    
    pcl::PCLPointCloud2 pcl_pc_;
    -> pcl_conversions::toPCL(*msg, pcl_pc_);
}


// pcl_conversions.h
inline
void toPCL(const sensor_msgs::msg::PointCloud2 &pc2, pcl::PCLPointCloud2 &pcl_pc2)
{
  copyPointCloud2MetaData(pc2, pcl_pc2);
  -> pcl_pc2.data = pc2.data;
}

// vector.tcc line 230
if (__xlen > capacity())
	    {
	      pointer __tmp = _M_allocate_and_copy(__xlen, __x.begin(),
						   __x.end());
	      std::_Destroy(this->_M_impl._M_start, this->_M_impl._M_finish,
			    _M_get_Tp_allocator());
	      -> _M_deallocate(this->_M_impl._M_start,
			    this->_M_impl._M_end_of_storage
			    - this->_M_impl._M_start);
	      this->_M_impl._M_start = __tmp;
	      this->_M_impl._M_end_of_storage = this->_M_impl._M_start + __xlen;
	    }

// stl_vector.h line 351
void
      _M_deallocate(pointer __p, size_t __n)
      {
	typedef __gnu_cxx::__alloc_traits<_Tp_alloc_type> _Tr;
	if (__p)
	  -> _Tr::deallocate(_M_impl, __p, __n);
      }

// alloc_traits.h line 470
static void
      deallocate(allocator_type& __a, pointer __p, size_type __n)
      -> { __a.deallocate(__p, __n); }

// new_allocator.h line 128
      void
      deallocate(pointer __p, size_type)
      {
#if __cpp_aligned_new
	if (alignof(_Tp) > __STDCPP_DEFAULT_NEW_ALIGNMENT__)
	  {
	    ::operator delete(__p, std::align_val_t(alignof(_Tp)));
	    return;
	  }
#endif
	-> ::operator delete(__p);
      }

// after that it's just assembly so I will omit it
```

**Expected behavior**

I would expect the code to always work and never segfault

**Current Behavior**

It segfaults sometimes

**To Reproduce**

I have a recording which reproduces the example, but it's quite rare. The program can run for a minute before it segfaults, other times it can run for 5min before it segfaults. I don't think I can upload the file to github because it is too large. Please let me know what is the best way to provide the recorded data

**Screenshots/Code snippets**

![Screenshot from 2021-08-23 16-28-37](https://user-images.githubusercontent.com/6259829/130464932-0e282330-0104-4e04-82f2-ccf07e775551.png)

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: GCC 9.3.0
 - PCL Version 1.10.0

**Possible Solution**

I have no clue what is going wrong, since the call to convert the pointcloud seems very simple

**Additional context**

This only happened after I added some code which made the callback run slower, which in itself shouldn't be a problem, just something I noticed

**Comment by kunaltyagi** [comment]
Doesn't seem to be an issue with PCL. Please head over to https://github.com/ros-perception/perception_pcl and report the bug.
