### ISSUE TITLE
GPU octree cluster    Error: invalid device function

### ISSUE THREAD

**Issue by kunzaiyy** [PointCloudLibrary/pcl#4918]
when i used pcl::gpu::Octree::Ptr octree_device (new pcl::gpu::Octree) in my code, i found an error , which is "Error: invalid device function" , i think maybe it's because my CUDA version is wrong, so i download the newest version of cuda--11.4,but , 
it dosen't work . Please help me, i will be very appreciate if you can help me to solve the problem.
 
 - OS: [e.g. Ubuntu 18.04]
 - Compiler: [:eg GCC 8.1]
 - PCL Version [e.g. 1.12, HEAD] (NB: please ensure you don't have multiple versions available)
 - PCL Type: [Installed/Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes
 - List and Version of dependencies used
 - Compilation flags are used

**Possible Solution**

Maybe CUDA version , but i'm not sure.

**Additional context**

**Comment by mvieth** [comment]
Closing due to no response from the author, and missing information
