### ISSUE TITLE
FindGLEW.cmake MacOS 10.9

### ISSUE THREAD

**Issue by mtourne** [PointCloudLibrary/pcl#492]
It looks like Mac OS Mavericks (10.9) stopped shipping with Glew, and that directory : 
/System/Library/Frameworks/GLEW.framework/ doesn't exist anymore.

As a result even if you're able to to compile pcl on this platform, doing a find_package(PCL) in your project won't work.

Glew now has to be installed via homebrew. The good news is that find_packages(Glew) seems to work with it.

Here is the diff that works for me on Mac os 10.9

---------- DIFF -----------
diff --git a/cmake/Modules/FindGLEW.cmake b/cmake/Modules/FindGLEW.cmake
index c45585c..a63336f 100644
--- a/cmake/Modules/FindGLEW.cmake
+++ b/cmake/Modules/FindGLEW.cmake
@@ -41,12 +41,8 @@ IF (WIN32)
 ELSE (WIN32)

   IF (APPLE)
-# These values for Apple could probably do with improvement.
-    FIND_PATH( GLEW_INCLUDE_DIR glew.h
-      /System/Library/Frameworks/GLEW.framework/Versions/A/Headers
-      ${OPENGL_LIBRARY_DIR}
-    )
-    SET(GLEW_GLEW_LIBRARY "-framework GLEW" CACHE STRING "GLEW library for OSX")
-       find_package(Glew)
-    SET(GLEW_GLEW_LIBRARY ${GLEW_LIBRARIES} CACHE STRING "GLEW library for OSX")
   SET(GLEW_cocoa_LIBRARY "-framework Cocoa" CACHE STRING "Cocoa framework for OSX")
  ELSE (APPLE)

**Comment by tophstar** [comment]
@pammacdotnet , if I can bother you I would like to know how you got this working?

I am experiencing this issue on the current --HEAD.  I have modified the /usr/local/share/pcl-1.8/PCLConfig.cmake file by adding the lines /usr/local/Cellar/glew/1.11.0/include/GL and SET(GLEW_GLEW_LIBRARY ${GLEW_LIBRARIES} CACHE STRING "GLEW library for OSX") as seen below.

<code>
  IF (APPLE)
    FIND_PATH( GLEW_INCLUDE_DIR glew.h
        /usr/local/Cellar/glew/1.11.0/include/GL
        ${OPENGL_LIBRARY_DIR}
    )
    SET(GLEW_GLEW_LIBRARY "-framework GLEW" CACHE STRING "GLEW library for OSX")
    SET(GLEW_GLEW_LIBRARY ${GLEW_LIBRARIES} CACHE STRING "GLEW library for OSX")
    SET(GLEW_cocoa_LIBRARY "-framework Cocoa" CACHE STRING "Cocoa framework for OSX")
</code>

I realize there is some redundancy to the changes I made above, but my CMAKE build command is as follows...

<code>
cmake 
-DOPENNI2_LIBRARY=/usr/local/lib/ni2/libOpenNI2.dylib 
-DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/4.9.2_1/bin/gcc-4.9 
-DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/4.9.2_1/bin/g++-4.9 
-DOPENNI2_REDIST=/usr/local/lib/ni2 
-DGLEW_INCLUDE_DIR=/usr/local/Cellar/glew/1.11.0/include/GL 
-DGLEW_LIBRARIES=/usr/local/Cellar/glew/1.11.0/lib/libGLEW.1.11.0.dylib 
-DCMAKE_OSX_ARCHITECTURES=x86_64 ..
</code>

**Comment by tophstar** [comment]
I actually just figured it out.  For anyone else experiencing this problem, I looked at the pull request here https://github.com/PointCloudLibrary/pcl/pull/529/files and realized I had missed adding in the find_package(Glew) line.  Now my PCLConfig.cmake file looks like

```javascript
  IF (APPLE)
# These values for Apple could probably do with improvement.
    find_package(Glew)
    SET(GLEW_GLEW_LIBRARY ${GLEW_LIBRARIES} CACHE STRING "GLEW library for OSX")
    SET(GLEW_cocoa_LIBRARY "-framework Cocoa" CACHE STRING "Cocoa framework for OSX")

  ELSE (APPLE)
```
