### ISSUE TITLE
[common] in feature_histogram.cpp ,maxidx value error

### ISSUE THREAD

**Issue by haqiankaka** [PointCloudLibrary/pcl#4920]
**Describe the bug**
in feature_histogram.cpp ,line139 ,maxidx means final value of histogram ,you pick histogram.size() for maxidx.
maxidx shoule be equal to （histogram.size() - 1 ) 。

**Comment by mvieth** [comment]
@haqiankaka Are you interested in creating a pull request? Otherwise someone else might fix this

**Comment by haqiankaka** [comment]
yep, i am doing a fix and then create the pull request.

**Comment by haqiankaka** [comment]
https://github.com/PointCloudLibrary/pcl/pull/4934
