### ISSUE TITLE
[Filters] Voxels for NDT sometimes removed suddenly by suspicious error check code in VoxelGridCovariance::applyFilter

### ISSUE THREAD

**Issue by KotaYonezawa** [PointCloudLibrary/pcl#4930]
**Describe the bug**

Thanks a lot for great library.
I faced strange behavior on NDT simulation using ideally accurate point cloud made by CG tools. (blender & CloudCompare)
Some voxels are strangely removed.
Through debug, I found suspicious error check code.

**Context**

I simply tried following code and saw display cloud to check NDT voxels.
```
namespace pcl {
template <typename PointSource, typename PointTarget>
class NormalDistributionsTransform_Inspect : public NormalDistributionsTransform<PointSource, PointTarget> {
public:
    inline VoxelGridCovariance<PointTarget>*
    getTargetGridPtr ()
    {
        return &target_cells_;
    }
};
} // namespace pcl

int
main (int argc, char** argv)
{
  // Loading first scan of room.
  pcl::PointCloud<pcl::PointXYZ>::Ptr target_cloud (new pcl::PointCloud<pcl::PointXYZ>);
  if (pcl::io::loadPCDFile<pcl::PointXYZ> ("box.pcd", *target_cloud) == -1)
  {
    PCL_ERROR ("Couldn't read file room_scan1.pcd \n");
    return (-1);
  }
  std::cout << "Loaded " << target_cloud->size () << " data points from box.pcd" << std::endl;

  {
    pcl::NormalDistributionsTransform_Inspect<pcl::PointXYZ, pcl::PointXYZ> ndt;
    ndt.setResolution (0.4);
    ndt.setInputTarget (target_cloud);

    pcl::PointCloud<pcl::PointXYZ>::Ptr display_cloud (new pcl::PointCloud<pcl::PointXYZ>);
    ndt.getTargetGridPtr()->getDisplayCloud (*display_cloud);
    pcl::io::savePCDFileBinary ("box_displaycloud.pcd", *display_cloud);
  }

  return (0);
}
```
box.pcd is following. (10m x 10m x 10m)
Cube (obj) was made using blender, and then generate point cloud from obj file using CloudCompare.
![MissingVoxel0](https://user-images.githubusercontent.com/39361859/131655221-432d136a-0e4a-409b-854c-410491bde8c3.jpg)

Output display cloud was following.
![MissingVoxel1](https://user-images.githubusercontent.com/39361859/131655347-97536d18-ccb8-47d9-9fcd-76998323d68b.jpg)

We can see several voxels are missing and we can find many holes.

I checked in voxel_grid_covariance.hpp and found that following code has some issue.
```
      //Normalize Eigen Val such that max no more than 100x min.
      eigensolver.compute (leaf.cov_);
      eigen_val = eigensolver.eigenvalues ().asDiagonal ();
      leaf.evecs_ = eigensolver.eigenvectors ();

      if (eigen_val (0, 0) < 0 || eigen_val (1, 1) < 0 || eigen_val (2, 2) <= 0) /* HERE */
      {
        leaf.nr_points = -1;
        continue;
      }

      // Avoids matrices near singularities (eq 6.11)[Magnusson 2009]

      min_covar_eigvalue = min_covar_eigvalue_mult_ * eigen_val (2, 2);
```

Using debugger, I found that eigen_value (0, 0) can become minus value on this case.
![GeneratePointCloud_5](https://user-images.githubusercontent.com/39361859/131659194-a0e72139-5922-4a3a-9c52-cfdbe9cb2d29.jpg)

After changing the code like as follows, voxels are not removed suddenly for now.
```
      if (eigen_val (2, 2) <= 0)
      {
        leaf.nr_points = -1;
        continue;
      }
```

Display cloud after above modification was as follows.
![MissingVoxel2](https://user-images.githubusercontent.com/39361859/131657357-555ec61c-231d-4ee8-b5e4-1bd43e16b5e7.jpg)

Even if eigen_value (0, 0) and eigen_value (1, 1) are minus value, these values are replaced by following code,
(just after eigen value error check I fixed)
```
      // Avoids matrices near singularities (eq 6.11)[Magnusson 2009]

      min_covar_eigvalue = min_covar_eigvalue_mult_ * eigen_val (2, 2);
      if (eigen_val (0, 0) < min_covar_eigvalue)
      {
        eigen_val (0, 0) = min_covar_eigvalue;

        if (eigen_val (1, 1) < min_covar_eigvalue)
        {
          eigen_val (1, 1) = min_covar_eigvalue;
        }
```
so I think eigen_val (0, 0) < 0 || eigen_val (1, 1) < 0 check is unnecessary.
What do you think?

**Expected behavior**

All valid voxels should not be removed suddenly.

**Current Behavior**

Several voxels can be removed suddenly if eigen_value (0, 0) or eigen_value (1, 1) are minus value.

**Your Environment (please complete the following information):**

OS: Windows10
Compiler: Visual Studio 2019 Build Tools
PCL Version: HEAD

**Comment by KotaYonezawa** [comment]
I forgot to attach the pcd file using on above check.
[box.zip](https://github.com/PointCloudLibrary/pcl/files/7090660/box.zip)

**Comment by kunaltyagi** [comment]
cc: @mvieth @tin1254

**Comment by mvieth** [comment]
It seems like this can happen in special cases, namely when all points in the voxel lie perfectly on a plane (like in your case) or on a line. Then one or two eigenvalues (respectively) would be 0, but through minor inaccuracies in Eigen's `SelfAdjointEigenSolver` or in the computation of the covariance matrix, the eigenvalues are very close to zero, but negative. As a side note, from a mathematical point of view, all eigenvalues must be non-negative because the covariance matrix is positive semi-definite, but that is of course not necessarily true for the limited precision calculations on a computer.
You are right that the further logic with `min_covar_eigvalue` would take care of that, but if one of the values is (significantly) negative, like e.g. -1.0 or -2.0, that should not simply be ignored because it would indicate an error either in `SelfAdjointEigenSolver` or in the computation of the covariance matrix. So I would suggest to only relax the test a bit, maybe like this: `eigen_val (0, 0) < -1.0e-12 || eigen_val (1, 1) < -1.0e-12 || eigen_val (2, 2) <= 0`. Perhaps a `PCL_WARN` would also be appropriate in that case.
@KotaYonezawa Are you interesting in opening a pull request to fix this?

**Comment by tin1254** [comment]
I agree with what @mvieth said.

One minor improvement is to use `Eigen::NumTraits<double>::dummy_precision()` to avoid magic number (the actual value is the same `1e-12`)

**Comment by mvieth** [comment]
Cool, I didn't know about `Eigen::NumTraits<double>::dummy_precision()`. TBH I chose `1e-12` kind of arbitrarily, but using the constant from `Eigen` is a good idea

**Comment by KotaYonezawa** [comment]
Thanks a lot for comments!

I modified the following code:
```
      if (eigen_val (0, 0) < 0 || eigen_val (1, 1) < 0 || eigen_val (2, 2) <= 0)
      {
        leaf.nr_points = -1;
        continue;
      }
```
to following:
```
      if (eigen_val (0, 0) < -Eigen::NumTraits<double>::dummy_precision () || eigen_val (1, 1) < -Eigen::NumTraits<double>::dummy_precision () || eigen_val (2, 2) <= 0)
      {
        leaf.nr_points = -1;
        continue;
      }
```

And it worked fine too.
![DisplayCloudOK](https://user-images.githubusercontent.com/39361859/132232067-4e0f0a2b-5f40-40c8-bcce-0928e64f83f0.jpg)

> Perhaps a PCL_WARN would also be appropriate in that case.

How message should "PCL_WARN" output?
```
PCL_WARN ("[VoxelGridCovariance::applyFilter] Invalid eigen value!\n");
```
or something like that?

**Comment by mvieth** [comment]
Maybe also print the three Eigenvalues in the warning message, so that it is clear why the condition triggered. Would you create a pull request with your code changes?

**Comment by KotaYonezawa** [comment]
Thanks. I'll try to create pull request.

So... the updated code should be...:
```
      if (eigen_val (0, 0) < -Eigen::NumTraits<double>::dummy_precision () || eigen_val (1, 1) < -Eigen::NumTraits<double>::dummy_precision () || eigen_val (2, 2) <= 0)
      {
        PCL_WARN ("[VoxelGridCovariance::applyFilter] Invalid eigen value! (%lg, %lg, %lg)\n", eigen_val (0, 0), eigen_val (1, 1), eigen_val (2, 2));
        leaf.nr_points = -1;
        continue;
      }
```
Is my understanding correct?

**Comment by mvieth** [comment]
I have never seen `%lg` before, I think just `%g` is fine? But we can discuss such things in the pull request

**Comment by KotaYonezawa** [comment]
Thanks! I understood.

**Comment by KotaYonezawa** [comment]
I created pull request.
https://github.com/PointCloudLibrary/pcl/pull/4937
Could you check it?
