### ISSUE TITLE
[visualization] Add eye dome lightning shading

### ISSUE THREAD

**Issue by gui2dev** [PointCloudLibrary/pcl#4940]
Hi !

In potree and CloudCompare, you can enable eye dome lightning shading.

VTK provides [some class](https://vtk.org/doc/nightly/html/classvtkEDLShading.html) to do that.

![edl image](https://discourse.vtk.org/uploads/default/original/1X/93a52a880ebf39b8782f994e2ef4441e13b88a11.png)

It would be nice to have this shading option in pcl visualizer.

**Comment by mvieth** [comment]
@larshg What do you think, how does it make sense to integrate this?

**Comment by larshg** [comment]
@gui2dev and @mvieth  take a look at the PR I made. It seems straigthforward to get a simple implementation, but as I write in the PR - the effect is applied to all actors, including text / fps which get pretty scrambled.

**Comment by gui2dev** [comment]
Thanks @larshg for the PR.
I guess it's ok if you don't display anything but the points.

**Comment by gui2dev** [comment]
Then, maybe having two rendering layers, one for points, and another for the other actors is the right way to do it ?

**Comment by larshg** [comment]
Yeah, it seems so. However, one has to change many calls to whether the actor being added should be an overlay or not. Also, I'm a bit unsure what will be rendered on top of what. Ie. if we add the coordinate system to layer 2, but points to layer 1 (with EDL), will the coordinate system then be on top of points, even though the points are closer to the viewpoint.

**Comment by gui2dev** [comment]
But for now everything is rendered in one layer, so it simply depends in which oder elements where added.
I am not sure how vtk manage layered renderers, but there maybe something like `vtkRenderer::SetLayer	(	int 	layer	)` and `void vtkRenderWindow::AddRenderer	(	vtkRenderer * 		)	` methods can do the trick?
