### ISSUE TITLE
PCL PolygonMesh concatenation error

### ISSUE THREAD

**Issue by joseandres15** [PointCloudLibrary/pcl#4942]
I'm trying to concatenate a pcl::PolygonMesh triangulation variable (triang) to a "buffer" pcl::PolygonMesh triangulation variable (triang_buffer). I've tried to do it by:

    triang_buffer += triang;

and by:

    bool pcl::PolygonMesh::concatenate(triang_buffer, triang);

but when I compile it, it appears these errors respectively:

> error: no match for 'operator+=' (operand types are 'pcl::PolygonMesh' and 'pcl::PolygonMesh')
  triang_buffer += triang;

and

> error: qualified-id in declaration before '(' token
  bool pcl::PolygonMesh::concatenate (triang_buffer, triang);

However, I've been looking at the pcl::PolygonMesh at PCL documentation, and it says both ways are available to use them.

Furthermore, I've looking at "PolygonMesh.h" file at Github [(Github PolygonMesh.h)](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/PolygonMesh.h) and it includes the "concatenate" tool, but in my installed "PolygonMesh.h", at "/usr/include/pcl-1.8/pcl/PolygonMesh.h", the file is much shorter and it doesn't include concatenate option.

I'm working with ROS Melodic Morenia at Ubuntu 18.04. I've installed ROS by following the Official Tutorial and it automatically includes "pcl-1.8", and I think that maybe in this version "PolygonMesh.h" is not updated with all this tools.

How could I achieve to apply the concatenation operation? Could I update my PCL version to 1.12?

I would appreciate if someone could help me. I'm new on C++ and PCL and I don't know how to solve this problem, and I need to do the concatenation operation with this pcl::PolygonMesh variables.

Thank you in advance.

**Comment by mvieth** [comment]
Yes, as you have noticed, those functions are not available in PCL 1.8. It seems they are available since PCL 1.10.0. So you could install PCL 1.12.0 as described in PCL's tutorials (compile from source, but you might also have to compile some ROS packages from source then), or you create your own concatenation function in your code, with code copied from PolygonMesh.h.

**Comment by joseandres15** [comment]
@mvieth Thank you for your response.

Could you describe me the process to do it? I'm new using ROS and maybe I'm missing some step. 

By the moment, I have compiled from source PCL 1.12.0 [from GitHub](https://github.com/PointCloudLibrary/pcl/releases) following the steps described [here](https://pcl.readthedocs.io/projects/tutorials/en/latest/compiling_pcl_posix.html#compiling-pcl-from-source-on-posix-compliant-systems). But now, I don't know what do next. I have changed the PCL version in my CMakeList.txt to "1.12" and executed `catkin_make` in my catkin_workspace but appear other errors.

**Comment by mvieth** [comment]
> but appear other errors.

It's always a good idea to post the actual error messages then. Just knowing that there are errors gives us very little information to work with :wink: 

If you want to use a PCL version other than the standard PCL version for your ROS release, you will likely have to compile some ROS packages from source. Probably all packages that use PCL (only the packages _you_ want to use of course), e.g. pcl_ros, pcl_conversions, ... I think you just have to put their source code into the `src` directory of your catkin workspace, but I would refer you to the ROS tutorials (maybe [this one](https://wiki.ros.org/ROS/Tutorials/BuildingPackages)) because PCL itself is not directly part of ROS.

**Comment by joseandres15** [comment]
@mvieth Sorry for my ignorance but I still don't know what I have to do.

Do you mean that I have to move the packages that I need (it seems to be pcl_conversions) to my workspace `catkin_ws/src` and run `catkin_make`? That would be the process?

By the way, this is the error, I forgot to post it before.

> [  0%] Building CXX object nodes/CMakeFiles/extractor2.dir/extractor2.cpp.o
In file included from /opt/ros/melodic/include/pcl_ros/point_cloud.h:9:0,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:4:
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h: In function 'void pcl_conversions::fromPCL(const pcl::Vertices&, pcl_msgs::Vertices&)':
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h:356:30: error: no match for 'operator=' (operand types are 'pcl_msgs::Vertices_<std::allocator<void> >::_vertices_type {aka std::vector<unsigned int, std::allocator<unsigned int> >}' and 'const Indices {aka const std::vector<int>}')
     vert.vertices = pcl_vert.vertices;
                              ^~~~~~~~
In file included from /usr/include/c++/7/vector:69:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/vector.tcc:179:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>]
     vector<_Tp, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/vector.tcc:179:5: note:   no known conversion for argument 1 from 'const Indices {aka const std::vector<int>}' to 'const std::vector<unsigned int, std::allocator<unsigned int> >&'
In file included from /usr/include/c++/7/vector:64:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/stl_vector.h:461:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^~~~~~~~
/usr/include/c++/7/bits/stl_vector.h:461:7: note:   no known conversion for argument 1 from 'const Indices {aka const std::vector<int>}' to 'std::vector<unsigned int, std::allocator<unsigned int> >&&'
/usr/include/c++/7/bits/stl_vector.h:482:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>]
       operator=(initializer_list<value_type> __l)
       ^~~~~~~~
/usr/include/c++/7/bits/stl_vector.h:482:7: note:   no known conversion for argument 1 from 'const Indices {aka const std::vector<int>}' to 'std::initializer_list<unsigned int>'
In file included from /opt/ros/melodic/include/pcl_ros/point_cloud.h:9:0,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:4:
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h: In function 'void pcl_conversions::moveFromPCL(pcl::Vertices&, pcl_msgs::Vertices&)':
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h:373:41: error: no matching function for call to 'std::vector<unsigned int, std::allocator<unsigned int> >::swap(pcl::Indices&'
     vert.vertices.swap(pcl_vert.vertices);
                                         ^
In file included from /usr/include/c++/7/vector:64:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/stl_vector.h:1229:7: note: candidate: void std::vector<_Tp, _Alloc>::swap(std::vector<_Tp, _Alloc>&) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>]
       swap(vector& __x) _GLIBCXX_NOEXCEPT
       ^~~~
/usr/include/c++/7/bits/stl_vector.h:1229:7: note:   no known conversion for argument 1 from 'pcl::Indices {aka std::vector<int>}' to 'std::vector<unsigned int, std::allocator<unsigned int> >&'
In file included from /opt/ros/melodic/include/pcl_ros/point_cloud.h:9:0,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:4:
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h: In function 'void pcl_conversions::toPCL(const Vertices&, pcl::Vertices&)':
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h:390:30: error: no match for 'operator=' (operand types are 'pcl::Indices {aka std::vector<int>}' and 'const _vertices_type {aka const std::vector<unsigned int, std::allocator<unsigned int> >}')
     pcl_vert.vertices = vert.vertices;
                              ^~~~~~~~
In file included from /usr/include/c++/7/vector:69:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/vector.tcc:179:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
     vector<_Tp, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/vector.tcc:179:5: note:   no known conversion for argument 1 from 'const _vertices_type {aka const std::vector<unsigned int, std::allocator<unsigned int> >}' to 'const std::vector<int>&'
In file included from /usr/include/c++/7/vector:64:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/stl_vector.h:461:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = int; _Alloc = std::allocator<int>]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^~~~~~~~
/usr/include/c++/7/bits/stl_vector.h:461:7: note:   no known conversion for argument 1 from 'const _vertices_type {aka const std::vector<unsigned int, std::allocator<unsigned int> >}' to 'std::vector<int>&&'
/usr/include/c++/7/bits/stl_vector.h:482:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = int; _Alloc = std::allocator<int>]
       operator=(initializer_list<value_type> __l)
       ^~~~~~~~
/usr/include/c++/7/bits/stl_vector.h:482:7: note:   no known conversion for argument 1 from 'const _vertices_type {aka const std::vector<unsigned int, std::allocator<unsigned int> >}' to 'std::initializer_list<int>'
In file included from /opt/ros/melodic/include/pcl_ros/point_cloud.h:9:0,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:4:
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h: In function 'void pcl_conversions::moveToPCL(pcl_msgs::Vertices&, pcl::Vertices&)':
/opt/ros/melodic/include/pcl_conversions/pcl_conversions.h:407:41: error: no matching function for call to 'std::vector<int>::swap(pcl_msgs::Vertices_<std::allocator<void> >::_vertices_type&)'
     pcl_vert.vertices.swap(vert.vertices);
                                         ^
In file included from /usr/include/c++/7/vector:64:0,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:26,
                 from /usr/include/boost/math/special_functions/round.hpp:15,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/c++/7/bits/stl_vector.h:1229:7: note: candidate: void std::vector<_Tp, _Alloc>::swap(std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
       swap(vector& __x) _GLIBCXX_NOEXCEPT
       ^~~~
/usr/include/c++/7/bits/stl_vector.h:1229:7: note:   no known conversion for argument 1 from 'pcl_msgs::Vertices_<std::allocator<void> >::_vertices_type {aka std::vector<unsigned int, std::allocator<unsigned int> >}' to 'std::vector<int>&'
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h: In member function 'void pcl::detail::FieldStreamer<Stream, PointT>::operator()()':
/opt/ros/melodic/include/pcl_ros/point_cloud.h:26:36: error: 'name' is not a member of 'pcl::detail::traits'
         const char* name = traits::name<PointT, U>::value;
                                    ^~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:26:36: note: suggested alternative:
In file included from /usr/local/include/pcl-1.12/pcl/type_traits.h:40:0,
                 from /usr/local/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/local/include/pcl-1.12/pcl/PCLHeader.h:3,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:47,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:3:
/usr/local/include/pcl-1.12/pcl/point_struct_traits.h:108:8: note:   'pcl::traits::name'
 struct name /** \cond NO_WARN_RECURSIVE */ : name<typename POD<PointT>::type, Tag, dummy> /** \endcond */
        ^~~~
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h:26:47: error: expected primary-expression before ',' token
         const char* name = traits::name<PointT, U>::value;
                                               ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h:32:40: error: 'offset' is not a member of 'pcl::detail::traits'
         std::uint32_t offset = traits::offset<PointT, U>::value;
                                        ^~~~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:32:40: note: suggested alternative:
In file included from /usr/local/include/pcl-1.12/pcl/type_traits.h:40:0,
                 from /usr/local/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/local/include/pcl-1.12/pcl/PCLHeader.h:3,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:47,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:3:
/usr/local/include/pcl-1.12/pcl/point_struct_traits.h:140:8: note:   'pcl::traits::offset'
 struct offset /** \cond NO_WARN_RECURSIVE */ : offset<typename POD<PointT>::type, Tag> /** \endcond */
        ^~~~~~
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h:32:53: error: expected primary-expression before ',' token
         std::uint32_t offset = traits::offset<PointT, U>::value;
                                                     ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h:35:41: error: 'datatype' is not a member of 'pcl::detail::traits'
         std::uint8_t datatype = traits::datatype<PointT, U>::value;
                                         ^~~~~~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:35:41: note: suggested alternatives:
In file included from /opt/ros/melodic/include/ros/serialization.h:37:0,
                 from /opt/ros/melodic/include/ros/publisher.h:34,
                 from /opt/ros/melodic/include/ros/node_handle.h:32,
                 from /opt/ros/melodic/include/ros/ros.h:45,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/opt/ros/melodic/include/ros/message_traits.h:261:20: note:   'ros::message_traits::datatype'
 inline const char* datatype(const M& m)
                    ^~~~~~~~
In file included from /opt/ros/melodic/include/ros/service_client.h:33:0,
                 from /opt/ros/melodic/include/ros/node_handle.h:35,
                 from /opt/ros/melodic/include/ros/ros.h:45,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/opt/ros/melodic/include/ros/service_traits.h:104:20: note:   'ros::service_traits::datatype'
 inline const char* datatype(const M& m)
                    ^~~~~~~~
In file included from /usr/local/include/pcl-1.12/pcl/type_traits.h:40:0,
                 from /usr/local/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/local/include/pcl-1.12/pcl/PCLHeader.h:3,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:47,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:3:
/usr/local/include/pcl-1.12/pcl/point_struct_traits.h:165:9: note:   'pcl::traits::datatype'
  struct datatype /** \cond NO_WARN_RECURSIVE */ : datatype<typename POD<PointT>::type, Tag> /** \endcond */
         ^~~~~~~~
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h:35:56: error: expected primary-expression before ',' token
         std::uint8_t datatype = traits::datatype<PointT, U>::value;
                                                        ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h:38:39: error: 'datatype' is not a member of 'pcl::detail::traits'
         std::uint32_t count = traits::datatype<PointT, U>::size;
                                       ^~~~~~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:38:39: note: suggested alternatives:
In file included from /opt/ros/melodic/include/ros/serialization.h:37:0,
                 from /opt/ros/melodic/include/ros/publisher.h:34,
                 from /opt/ros/melodic/include/ros/node_handle.h:32,
                 from /opt/ros/melodic/include/ros/ros.h:45,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/opt/ros/melodic/include/ros/message_traits.h:261:20: note:   'ros::message_traits::datatype'
 inline const char* datatype(const M& m)
                    ^~~~~~~~
In file included from /opt/ros/melodic/include/ros/service_client.h:33:0,
                 from /opt/ros/melodic/include/ros/node_handle.h:35,
                 from /opt/ros/melodic/include/ros/ros.h:45,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/opt/ros/melodic/include/ros/service_traits.h:104:20: note:   'ros::service_traits::datatype'
 inline const char* datatype(const M& m)
                    ^~~~~~~~
In file included from /usr/local/include/pcl-1.12/pcl/type_traits.h:40:0,
                 from /usr/local/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/local/include/pcl-1.12/pcl/PCLHeader.h:3,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:47,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:3:
/usr/local/include/pcl-1.12/pcl/point_struct_traits.h:165:9: note:   'pcl::traits::datatype'
  struct datatype /** \cond NO_WARN_RECURSIVE */ : datatype<typename POD<PointT>::type, Tag> /** \endcond */
         ^~~~~~~~
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h:38:54: error: expected primary-expression before ',' token
         std::uint32_t count = traits::datatype<PointT, U>::size;
                                                      ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h: In member function 'void pcl::detail::FieldsLength<PointT>::operator()()':
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:52: error: 'name' is not a member of 'pcl::detail::traits'
         std::uint32_t name_length = strlen(traits::name<PointT, U>::value);
                                                    ^~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:52: note: suggested alternative:
In file included from /usr/local/include/pcl-1.12/pcl/type_traits.h:40:0,
                 from /usr/local/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/local/include/pcl-1.12/pcl/PCLHeader.h:3,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:47,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:3:
/usr/local/include/pcl-1.12/pcl/point_struct_traits.h:108:8: note:   'pcl::traits::name'
 struct name /** \cond NO_WARN_RECURSIVE */ : name<typename POD<PointT>::type, Tag, dummy> /** \endcond */
        ^~~~
In file included from /root/catkin_ws/src/nodes/extractor2.cpp:4:0:
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:63: error: expected primary-expression before ',' token
         std::uint32_t name_length = strlen(traits::name<PointT, U>::value);
                                                               ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:66: error: expected primary-expression before '>' token
         std::uint32_t name_length = strlen(traits::name<PointT, U>::value);
                                                                  ^
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:69: error: '::value' has not been declared
         std::uint32_t name_length = strlen(traits::name<PointT, U>::value);
                                                                     ^~~~~
/opt/ros/melodic/include/pcl_ros/point_cloud.h:52:69: note: suggested alternative:
In file included from /usr/include/boost/bind.hpp:22:0,
                 from /opt/ros/melodic/include/ros/publisher.h:35,
                 from /opt/ros/melodic/include/ros/node_handle.h:32,
                 from /opt/ros/melodic/include/ros/ros.h:45,
                 from /root/catkin_ws/src/nodes/extractor2.cpp:1:
/usr/include/boost/bind/bind.hpp:118:25: note:   'boost::_bi::value'
 template<class T> class value
                         ^~~~~
/root/catkin_ws/src/nodes/extractor2.cpp: In member function 'void Subscriber::callback(const ConstPtr&)':
/root/catkin_ws/src/nodes/extractor2.cpp:66:37: error: qualified-id in declaration before '(' token
  bool pcl::PolygonMesh::concatenate (cloud_out_tri, triangles);
                                     ^
/root/catkin_ws/src/nodes/extractor2.cpp:76:52: error: no match for 'operator*' (operand type is 'pcl::PolygonMesh')
         pcl::io::savePLYFileBinary(writePathvoxel, *cloud_out_tri);
                                                    ^~~~~~~~~~~~~~
nodes/CMakeFiles/extractor2.dir/build.make:62: recipe for target 'nodes/CMakeFiles/extractor2.dir/extractor2.cpp.o' failed
make[2]: *** [nodes/CMakeFiles/extractor2.dir/extractor2.cpp.o] Error 1
CMakeFiles/Makefile2:1031: recipe for target 'nodes/CMakeFiles/extractor2.dir/all' failed
make[1]: *** [nodes/CMakeFiles/extractor2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j40 -l40" failed


Thanks for your help.

**Comment by mvieth** [comment]
> Do you mean that I have to move the packages that I need (it seems to be pcl_conversions) to my workspace catkin_ws/src and run catkin_make? That would be the process?

I believe so, but that is a ROS-specific question, and as I said above, PCL itself is not directly part of ROS, so this is not the appropriate place to ask this question. Please check out the ROS tutorials (especially those describing the process to compile packages from source with catkin) or ask in the ROS forum. The errors should disappear when you use the most recent version of pcl_conversions. Do you have any other _PCL-specific_ questions? Otherwise I would close this issue.

**Comment by joseandres15** [comment]
> Do you have any other PCL-specific questions? Otherwise I would close this issue.

No, thanks for your help.
