### ISSUE TITLE
[compile error] "pcl/visualization/pcl_visualizer.h" is missing.

### ISSUE THREAD

**Issue by MatthewMunks** [PointCloudLibrary/pcl#4949]
**Describe the error**

When using `sudo apt-get install libpcl-dev`, the visualization headers aren't installed (on my machine). It's slightly weird. It works fine for someone I'm collaborating with but not for me. All the other headers seem to be there as well. Only the visualisation ones are missing. 

```
[  3%] Building CXX object CMakeFiles/gpg_local_frame.dir/src/gpg/local_frame.cpp.o
In file included from /home/matthewmunks/orion_ws/src/gpg/src/gpg/local_frame.cpp:1:
/home/matthewmunks/orion_ws/src/gpg/include/gpg/local_frame.h:39:10: fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory
   39 | #include <pcl/visualization/pcl_visualizer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/gpg_local_frame.dir/build.make:63: CMakeFiles/gpg_local_frame.dir/src/gpg/local_frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:365: CMakeFiles/gpg_local_frame.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

```
matthewmunks@ori-28672:/usr/include/pcl-1.10/pcl$ dir
2d		  conversions.h     for_each_type.h  keypoints		  pcl_base.h	 pcl_macros.h	   PointIndices.h	     PolygonMesh.h	      sample_consensus	surface
cloud_iterator.h  correspondence.h  geometry	     make_shared.h	  pcl_config.h	 PCLPointCloud2.h  point_representation.h    range_image	      search		TextureMesh.h
common		  exceptions.h	    impl	     ml			  pcl_exports.h  PCLPointField.h   point_traits.h	     recognition	      segmentation	tracking
compression	  features	    io		     ModelCoefficients.h  PCLHeader.h	 pcl_tests.h	   point_types_conversion.h  register_point_struct.h  sse.h		Vertices.h
console		  filters	    kdtree	     octree		  PCLImage.h	 point_cloud.h	   point_types.h	     registration	      stereo
matthewmunks@ori-28672:/usr/include/pcl-1.10/pcl$ dir | grep vis
matthewmunks@ori-28672:/usr/include/pcl-1.10/pcl$ 
```

**To Reproduce**

Honestly not sure given that it's working for someone else but not for me. (His whole compile process is working. Mine keeps failing).
I noticed a slight difference in the versions that we have. He's on `1.10.0+dfsg-5ubuntu1` while I'm on `1.10.0+dfsg-6ubuntu1` but I don't think that should make much of a difference.

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [N/A]
 - PCL Version [1.10.0+dfsg-6ubuntu1]
 - PCL Type: [Installed]

I have tried uninstalling and reinstalling multiple times but to no avail.

**Comment by mvieth** [comment]
The "normal" package is the one which ends in `5ubuntu1` ([see here](https://packages.ubuntu.com/focal/libpcl-dev)). Is it possible that you get the package from somewhere else than the normal sources? Did you add any source/repository to your apt tool, e.g. in `/etc/apt/...`? Can you think of anything that makes your system different from your colleague's (configuration etc.)?

**Comment by MatthewMunks** [comment]
So we've both been working through ROS (so I think I may originally have downloaded through `ros-noetic-pcl-ros`). The only other thing I can think of is I've added an ssh into the anymal gitlab account so I can `apt install` from there. Could that have made a difference? (The anymal ssh is the only difference I can think of.)
