### ISSUE TITLE
MacOS: Project using PCL 1.12 fails to build after brew upgrade (VTK cannot find qt5)

### ISSUE THREAD

**Issue by jackjansen** [PointCloudLibrary/pcl#4951]
**Describe the error**

```
-- Eigen found (include: /usr/local/include/eigen3, version: 3.4.0)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
CMake Warning at /usr/local/lib/cmake/vtk-9.0/VTK-vtk-module-find-packages.cmake:209 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.15) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/vtk-9.0/vtk-config.cmake:131 (include)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:276 (find_package)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:325 (find_VTK)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:536 (find_external_library)
  CMakeLists.txt:33 (find_package)
```
**To Reproduce**

Build a package on MacOS (tried in MacOS 11 and on 10.15) that uses PCL, and worked for PCL 1.11. It will fail with 1.12.

**Screenshots/Code snippets/Build information**

Here is my cmake dependency line for PCL. I presume `visualisation` is the culprit.
```
find_package(PCL 1.10 REQUIRED COMPONENTS common io octree visualization filters features)
```

**Your Environment (please complete the following information):**

 - OS: MacOS 11.5.2
 - PCL Version 1.12
 - PCL Type: Installed with brew

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by mvieth** [comment]
I am not very familiar with brew, is Qt5 installed on your system?

**Comment by jackjansen** [comment]
qt5 is installed via brew. That was done by the brew recipes for pcl 1.12 (or by the recipes for vtk, I'm not sure).

But: qt5 is installed as keg-only, so it isn't linked into the normal `/usr/local` paths. Therefore, the pcl CMakefiles (or, again, the vtk CMakefiles, I am not sure) cannot find the Qt5 cmake configuration files.

I have tried a manual `brew link qt5` but that doesn't work either, although the error message is then different.

(I'm using brew on macOS because it is convenient, especially for CI/CD, but also because it is the suggested way to use PCL on macOS, according to the website)

**Comment by larshg** [comment]
Are you supplying the the path as an argument - like done here on the CI:
https://github.com/PointCloudLibrary/pcl/blob/master/.ci/azure-pipelines/build/macos.yaml

It seems to be VTK failing as PCL searches for Qt after VTK.

**Comment by jackjansen** [comment]
@larshg thanks, I've managed to include something similar in my CI/CD scripts (add `-DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5` if that directory exists).

**Comment by kunaltyagi** [comment]
@jackjansen should we close this issue then?
