### ISSUE TITLE
[compile error] object file cant recognise refrences

### ISSUE THREAD

**Issue by RhineArcedia** [PointCloudLibrary/pcl#4953]
the object file cant recognise the refrences to pcl and vtk libraries.
![Screenshot from 2021-09-25 02-34-47](https://user-images.githubusercontent.com/87337841/134749591-dbb8dbb7-4be1-4be9-80ff-698990b9aff6.png)

the cmake .. works.
the object file here calls for another object file which was successfully compiled and built. 

this is what i was trying to run:
https://bitbucket.org/alberto_pretto/d2co/src/master/

i tried using other versions of VTK and PCL but no matter which version it was it did this error

**Comment by mvieth** [comment]
So you simply tried to build the project you linked and got these errors? Then I would suggest that you contact the authors/maintainers of that project or open an issue there. We can't give support for all projects that use PCL.
On a quick glance, it seems that the object file(s) are not linked against the PCL libraries (`target_link_libraries`)
