### ISSUE TITLE
bug in saveOBJFile function,  io/src/obj_io.cpp  

### ISSUE THREAD

**Issue by whulc** [PointCloudLibrary/pcl#4957]
When writing faces to the obj file, an extra line which writes a number between the vertices index.
`<< "/" << tex_mesh.tex_polygons[m][i].vertices.size() * (i + f_idx) + j + 1`
The bug can be fixed by removing this line.

**Comment by mvieth** [comment]
You mean [this line](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/obj_io.cpp#L1117), right?
Could you explain the bug a bit more? What is happening, what would you expect to happen instead?
That number is the [vertex texture coordinate index](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Face_elements), so simply removing it can't be a good solution ...

**Comment by whulc** [comment]
Yes, this is not a good solution. In my case, the obj file saved with this line can not be correctly shown in Meshlab. For some face, the texture coordinate index is out of vertices index range. By removing this line, the index for the normal line is used for the texture and the obj looks correct in Meshlab, Maybe the texture coordinate index is not correctly calculated.

**Comment by mvieth** [comment]
@whulc You are trying to store a TextureMesh, right? Not a PolygonMesh? Where do you get the mesh from? Do you load it from some other file or generate it in some way?

**Comment by mvieth** [comment]
Fixed by #4971
