### ISSUE TITLE
Support for Qt6

### ISSUE THREAD

**Issue by bebuch** [PointCloudLibrary/pcl#4959]
The official open source support of Qt 5.15 ended with 5.15.2 on November 20, 2020. That was almost a year ago and with Qt 6.2 the third release of the 6 series will be released in a few days.

VTK is currently also working on support for Qt6.

The PCL currently only supports Qt5, which is no longer supported as open source. There are only a few breaking changes between Qt5 and Qt6, so it should not be very hard to support the new release.

**Comment by mvieth** [comment]
You are welcome to create a pull request to add support for Qt6. I am not sure when one of us maintainer will have the time to work on that.
