### ISSUE TITLE
Win64 docker image fails to build on Azure

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#4968]
See here: https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=11
The problem seems to be that libffi fails to build.
The Win86 image builds successfully (except the last time, but that was only because Eigen temporarily lost their Gitlab repo).

**Comment by larshg** [comment]
Seems this PR at VCPKG made it start failing:
https://github.com/microsoft/vcpkg/pull/19655

**Comment by mvieth** [comment]
libffi now succeeds, but it fails at a later point (msmpi)

**Comment by larshg** [comment]
Its already  reported here:
https://github.com/microsoft/vcpkg/issues/20417

**Comment by mvieth** [comment]
Docker builds successfully again :tada:
