### ISSUE TITLE
[ply] "please do not link to vtk"

### ISSUE THREAD

**Issue by PerspectivesLab** [PointCloudLibrary/pcl#4985]
it would be nice just to load a simple PLY file, to not install vtk binaries... 
we need to compile vtk 9.0, etc... what has VTK to do with just loading a file ?
thx

**Comment by mvieth** [comment]
Some parts of PCL's IO functionality use functions or classes from VTK in the background, e.g. `loadPolygonFile`. Do you compile PCL yourself or install it via apt or some other way? If you compile PCL yourself, I believe you can compile it without having VTK installed (then with reduced functionality)
