### ISSUE TITLE
Converting PCD from UTM to MGRS

### ISSUE THREAD

**Issue by mfapakhan** [PointCloudLibrary/pcl#4986]
Hello to everyone;

I want to ask another question.

I have a pointcloud, and this point cloud has points according to the UTM system. But, to match the point cloud with a vector map in lanelet format projected according to the MGRS, I want to project the PCD file, its points to the MGRS system. Is there any method for it?

Best regards.

**Comment by mvieth** [comment]
No, as far as I am aware of.
Please use [the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for these kinds of questions. There are more people with diverse experience there.
