### ISSUE TITLE
[visualization] PCLVisualizer crashes (read access violation)

### ISSUE THREAD

**Issue by Kilidsch** [PointCloudLibrary/pcl#4987]
If I try to visualize a point cloud with `PCLVisualizer`, I get an reading access violation. This only happens in Release (With Debug). In Debug, everything works fine.

Minimal code example:

```cpp
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);

    // Fill in the cloud data
    cloud->width = 5;
    cloud->height = 1;
    cloud->points.resize(cloud->width * cloud->height);

    for (auto &point : *cloud) {
        point.x = 1024 * rand() / (RAND_MAX + 1.0f);
        point.y = 1024 * rand() / (RAND_MAX + 1.0f);
        point.z = 1024 * rand() / (RAND_MAX + 1.0f);
    }

    pcl::visualization::PCLVisualizer::Ptr viewer
        = std::make_shared<pcl::visualization::PCLVisualizer>();
    viewer->setBackgroundColor(0, 0, 0);
    viewer->addPointCloud<pcl::PointXYZ>(cloud, "Sample Cloud");
    viewer->addCoordinateSystem(1);
    viewer->initCameraParameters();

    while (!viewer->wasStopped()) {
        viewer->spinOnce(100);
        std::this_thread::sleep_for(100ms);
    }
```

**Context**

I want to visualize a Point Cloud (technically a labeled one, but this here is the mininmal example of the same error).

**Expected behavior**

A window with a visualization.

**Current Behavior**

Exception: reading access violation

**To Reproduce**

see code-example above

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: MSVC / Visual Studio 16.11.5
 - PCL Version 1.12.0 (all in one installer)

**Possible Solution**

No idea. I don't have the code of VTK or PCL locally, only binaries. So I couldn't investigate further.

**Additional context**

n / a

**Comment by 155cannon** [comment]
You can try to use "pcl::visualization::PCLVisualizer::Ptr viewer(new pcl::visualization::PCLVisualizer);"

**Comment by Kilidsch** [comment]
@155cannon 
Have tried, doesn't help.

**Comment by Kilidsch** [comment]
@larshg 
I'm not sure what you mean with subproject?

If it is about the executable containing the code cited above, the instructions are generated via CMake without any modifications (i.e. also not adding an `\arch:AVX2` flag), so I _think_ it should be SSE2?

If it is about PCL, I just use the version from the "All In One Installer". I don't know how that was compiled.

**Comment by larshg** [comment]
I mean the project that you use PCL in.
All-in-One is build with AVX2, so you need to anable that as well.

**Comment by Kilidsch** [comment]
Adding `target_compile_options(myProject PUBLIC "/arch:AVX2")` didn't help.

Also, I apparently didn't add a stacktrace, so...

(main:265 is the line after `viewer->spinOnce(100);`)
```
1  vtkGenericDataArray<vtkAOSDataArrayTemplate<__int64>,__int64>::GetValue vtkCommonCore_9_0           0x7ffa00fad447 
2  vtkPixelTransfer::operator=                                             vtkCommonDataModel_9_0      0x7ffa02e7e344 
3  vtkPolyData::ComputeBounds                                              vtkCommonDataModel_9_0      0x7ffa02faaacf 
4  vtkDataSet::GetBounds                                                   vtkCommonDataModel_9_0      0x7ffa02ec7cb9 
5  vtkMapper::GetBounds                                                    vtkRenderingCore_9_0        0x7ffa04080658 
6  vtkActor::GetBounds                                                     vtkRenderingCore_9_0        0x7ffa0400968e 
7  vtkFrustumCoverageCuller::Cull                                          vtkRenderingCore_9_0        0x7ffa0403c80c 
8  vtkRenderer::AllocateTime                                               vtkRenderingCore_9_0        0x7ffa0409468f 
9  vtkRenderer::Render                                                     vtkRenderingCore_9_0        0x7ffa04096e96 
10 vtkRendererCollection::Render                                           vtkRenderingCore_9_0        0x7ffa040996a4 
11 vtkRenderWindow::DoStereoRender                                         vtkRenderingCore_9_0        0x7ffa0408de4a 
12 vtkRenderWindow::Render                                                 vtkRenderingCore_9_0        0x7ffa0408eb4d 
13 vtkOpenGLRenderWindow::Render                                           vtkRenderingOpenGL2_9_0     0x7ffa041f6863 
14 vtkWin32OpenGLRenderWindow::MessageProc                                 vtkRenderingOpenGL2_9_0     0x7ffa04254940 
15 vtkWin32OpenGLRenderWindow::WndProc                                     vtkRenderingOpenGL2_9_0     0x7ffa0425709e 
16 CallWindowProcW                                                         USER32                      0x7ffa7f2ee7e8 
17 CallWindowProcW                                                         USER32                      0x7ffa7f2ee47e 
18 glPushClientAttrib                                                      OPENGL32                    0x7ffa53f5f1b0 
19 CallWindowProcW                                                         USER32                      0x7ffa7f2ee7e8 
20 LoadMenuA                                                               USER32                      0x7ffa7f32fd74 
21 CallWindowProcA                                                         USER32                      0x7ffa7f3303bb 
22 vtkHandleMessage2                                                       vtkRenderingUI_9_0          0x7ffa2f573fac 
23 vtkHandleMessage                                                        vtkRenderingUI_9_0          0x7ffa2f574499 
24 CallWindowProcW                                                         USER32                      0x7ffa7f2ee7e8 
25 DispatchMessageW                                                        USER32                      0x7ffa7f2ee36c 
26 SendMessageTimeoutW                                                     USER32                      0x7ffa7f300f93 
27 KiUserCallbackDispatcher                                                ntdll                       0x7ffa80170ba4 
28 NtUserDispatchMessage                                                   win32u                      0x7ffa7da91704 
29 DispatchMessageW                                                        USER32                      0x7ffa7f2ee27a 
30 vtkWin32RenderWindowInteractor::StartEventLoop                          vtkRenderingUI_9_0          0x7ffa2f573eca 
31 pcl::visualization::PCLVisualizer::spinOnce                             pcl_visualization           0x7ffa232ba4ae 
32 main                                                                    main.cpp                265 0x7ff7b5d1460f 
33 __scrt_common_main_seh                                                  exe_common.inl          288 0x7ff7b5d4d7d0 
34 BaseThreadInitThunk                                                     KERNEL32                    0x7ffa7f5b7034 
35 RtlUserThreadStart                                                      ntdll                       0x7ffa80122651 
```

**Comment by kaitou1419** [comment]
for enable AVX2 manually in your project/subproject. you can go to Properties, and here it is: 
![image](https://user-images.githubusercontent.com/73357725/141410948-b15b1653-6906-4d5d-b672-672147230802.png)

**Comment by Kilidsch** [comment]
@kaitou1419 

I don't use MBuild. I use CMake and as such have to specifiy this in my CMakeLists.txt, which I did with `target_compile_options(myProject PUBLIC "/arch:AVX2")`, which is the `cl.exe` flag for turning on AVX2, see https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170

Thank you nonetheless.

**Comment by kaitou1419** [comment]
@Kilidsch yeah! I have had the same problem in this case. and i added Enable AVX in VS19 after build solution by Cmake. It's worked for me and i'm using it up to now. and i', an amateur in Cmake
you can find the way to make it out in Cmake. Hope you can find out the way soon!

**Comment by Qannaf** [comment]
You can try this function : 
    template<typename PointT>
    void addPointCloudToVisualizer ( const std::shared_ptr<pcl::PointCloud<PointT> > &_ip_pointCloud,
                                     const Eigen::Matrix4f &w_T_obj,
                                     const std::string &_ip_PCNameID,
                                     const int &_pointsSize,
                                     const int &_colorR,
                                     const int &_colorG,
                                     const int &_colorB,
                                     const double &_sizeCRF,
                                     const int &_viewPort,
                                     std::shared_ptr<pcl::visualization::PCLVisualizer> &viewer )
    {
        if ( _ip_pointCloud->size() < 1 )
            PCL_ERROR ("%s contains no points\n", _ip_PCNameID.c_str() );

        pcl::PointCloud<PointT>::Ptr tempPC_ptr(new pcl::PointCloud<PointT>);
        pcl::transformPointCloud( *_ip_pointCloud, *tempPC_ptr, w_T_obj );

        std::string recPointCloudType = pcl::getFieldsList(*tempPC_ptr);
        std::string cloudColorField;

        if ( recPointCloudType.compare("x y z intensity") == 0 ) {
            cloudColorField = "intensity";
            pcl::visualization::PointCloudColorHandlerGenericField<PointT> cloudColor( _ip_pointCloud, cloudColorField );
            viewer->addPointCloud<PointT> ( _ip_pointCloud, cloudColor, _ip_PCNameID, _viewPort );
        }
        else if ( recPointCloudType.compare("x y z rgb") == 0 ) {
            cloudColorField = "rgb";
            pcl::visualization::PointCloudColorHandlerGenericField<PointT> cloudColor( _ip_pointCloud, cloudColorField );
            viewer->addPointCloud<PointT> ( _ip_pointCloud, cloudColor, _ip_PCNameID, _viewPort );
        }
        else {
            pcl::visualization::PointCloudColorHandlerCustom<PointT> cloudColor( _ip_pointCloud, _colorR, _colorG, _colorB );
            viewer->addPointCloud<PointT> ( _ip_pointCloud, cloudColor, _ip_PCNameID, _viewPort );
        }

        viewer->setPointCloudRenderingProperties ( pcl::visualization::PCL_VISUALIZER_POINT_SIZE,
                                                   _pointsSize, _ip_PCNameID );

    }

**Comment by Qannaf** [comment]
After build solution, enable AVX in MCVS19

**Comment by Kilidsch** [comment]
**Ending Note**: I checked the generated project, it is correctly set to AVX, so that is **not** part of the problem.

However, after trying again with the _current master_, the problem is fixed. If this is due to #5147 or due to #5160 or due to sth. else, I cannot say. But since this is fixed, I'll close this issue.

**Comment by guyuezuntinggithub** [comment]
> **Ending Note**: I checked the generated project, it is correctly set to AVX, so that is **not** part of the problem.
> 
> However, after trying again with the _current master_, the problem is fixed. If this is due to #5147 or due to #5160 or due to sth. else, I cannot say. But since this is fixed, I'll close this issue.

will it occurs error or run slower than before if i disable the avx,?
