### ISSUE TITLE
[compile error] make command doesn't work

### ISSUE THREAD

**Issue by shreshtashetty** [PointCloudLibrary/pcl#4991]
When I try the example pcd_write, the make command doesn't work.

It gives: `make: *** No targets specified and no makefile found.  Stop.`

 - OS: Windows10
 - Compiler: Microsoft Visual Studio
 - PCL Version 1.12
 - PCL Type: Installed

**Additional context**

This is what my build folder looks like after running cmake if that is of any help.
![MakeErrorPCL](https://user-images.githubusercontent.com/14017651/138151641-eeaf8b35-601b-42a8-8c80-29e92050f797.PNG)

Which one of these is the Makefile? Is the makefile not getting formed during cmake?

**Comment by Kilidsch** [comment]
@shreshtashetty 

You're not using make (because you're not using gcc or clang but MSVC), thus no makefile is created/found.

Try using `cmake --build .` instead of `make`.

**Comment by shreshtashetty** [comment]
The only `.exe` file to be formed is the one in the Debug directory. Doing `.\pcd_write_test.exe` did not work (why?) so I `cd`ed into Debug and ran it instead. It doesn't run and I et the following errors:
![2021-10-21](https://user-images.githubusercontent.com/14017651/138158350-33ee39e6-7cd6-4782-a409-eaf9707b3185.png)
![2021-10-21 (1)](https://user-images.githubusercontent.com/14017651/138158390-cff57183-c9f4-479b-b9fa-362b0b0090a2.png)
