### ISSUE TITLE
[compile error]"Using  pcl::SACSegmentation Fail"

### ISSUE THREAD

**Issue by Tony-TF** [PointCloudLibrary/pcl#4993]
Hello everyone：
                        I have a problem, please help me to solve it，Thanks! The problem is that Use pcl::SACSegmentation to compile successfully, but the following error occurs when running:

![image](https://user-images.githubusercontent.com/35761167/138415136-2c9e412f-0428-4173-883e-d2616dac25b4.png)

long double boost::math::lanczos::lanczos17m64::lanczos_sum<long double>(long double const&) 0x00007f05e29d62e4
<unknown> 0x00007f05e2941d7f
call_init 0x00007f05e2f036fa
call_init 0x00007f05e2f0380b
_dl_init 0x00007f05e2f0380b
_dl_start_user 0x00007f05e2ef3c6a
<unknown> 0x0000000000000001
<unknown> 0x00007fffd03b3ca1
<unknown> 0x0000000000000000

The code 

![image](https://user-images.githubusercontent.com/35761167/138415346-4ab20e4e-61f8-409f-926e-24151f6ae197.png)

The  Cmakelist 
![image](https://user-images.githubusercontent.com/35761167/138416798-c009a35a-b344-4b54-9085-ec80a94400c9.png)

The PCL Version == 1.9.1    boost  == 1.58   ubuntu 16.04

**Comment by mvieth** [comment]
Since I didn't hear anything from you, I am going to assume that my comment above helped you solve the issue
