### ISSUE TITLE
[compile error] Matrix Transform Tutorial doesn't work (Windows)

### ISSUE THREAD

**Issue by shreshtashetty** [PointCloudLibrary/pcl#4994]
**Problem**
I am following the [matrix transform](https://pcl.readthedocs.io/projects/tutorials/en/latest/matrix_transform.html#matrix-transform) tutorial on Windows 10. `cmake ..` and `cmake --build .` run fine without giving me any error. But when I try to run the `.exe` file as `.\build\Debug\matrix_transform.exe cube.ply` , I don't get any output-- none of the `cout` statements are printed to the console, the visualization doesn't show and there is no error statement even for me to know what the problem is.

**Environment :**

 - OS: Windows 10
 - Compiler: MSVC
 - PCL Version 1.12
 - PCL Type: Installed
 
On adding `cout` statements, I feel like `pcl::io::loadPLYFile` might be the problem. Nothing is getting loaded into the `source_cloud`. When I try to print out the value of `pcl::io::loadPLYFile (argv[filenames[0]], *source_cloud)`, **nothing gets printed**-- no value greater or less than 0 indicating success or failure, nothing else. The rest of the program doesn't execute, it is like the program stops at 
```
if (file_is_pcd) {
    if (pcl::io::loadPCDFile (argv[filenames[0]], *source_cloud) < 0)  {
      std::cout << "Error loading point cloud " << argv[filenames[0]] << std::endl << std::endl;
      showHelp (argv[0]);
      return -1;
    }
  } else {
    if (pcl::io::loadPLYFile (argv[filenames[0]], *source_cloud) < 0)  {
      std::cout << "Error loading point cloud " << argv[filenames[0]] << std::endl << std::endl;
      showHelp (argv[0]);
      return -1;
    }
  }
```
Any help on how to fix this?

**Comment by shreshtashetty** [comment]
That worked, @raahilsha-z !Thanks.
Before I close this issue (finally!), I have 1 little problem.
This is what my visualization looks like:
![2021-10-30](https://user-images.githubusercontent.com/14017651/139522411-023e5060-78ea-48f0-aee4-b5bbe3710b99.png)

Which is clearly different from the one in the tutorial. Is there any problem?

**Comment by larshg** [comment]
Thats also how it looks for me. I wonder if its a different cube that has been used originally.

**Comment by shreshtashetty** [comment]
Ok. Thanks @larshg!
