### ISSUE TITLE
PCL exception Eigen::aligned_free

### ISSUE THREAD

**Issue by kaitou1419** [PointCloudLibrary/pcl#5009]
Issue: 
When is debug my function, it became an exception when freeing memory at the end of Function :
![image](https://user-images.githubusercontent.com/73357725/139789570-2164c887-b4f2-4da6-86c0-3f680f2c0242.png)
![image](https://user-images.githubusercontent.com/73357725/139789561-2bce85c9-9527-47c7-8d72-0d716932692e.png)

And an exception had occurred at aligned_free:
![image](https://user-images.githubusercontent.com/73357725/139789792-3ff36d14-6243-4bb7-9a5b-dbf584cd42e0.png)

I had finded ideas that need add AXV for my project : #4598, but through that conversation, i'm confusing what to do to add AXV for my project

My system: 
- PCL : all in one build, Ver 1.12.0
- OS : Windows 10
- Cmake: ver 3.21.3

**Comment by larshg** [comment]
Please see this post: https://stackoverflow.com/questions/20169064/does-archavx-enable-avx2

**Comment by larshg** [comment]
Closing as dublicate and its fixed when 12.1 is released.
