### ISSUE TITLE
[io] Open Chinese path ply file failed after upgrade to version 1.12

### ISSUE THREAD

**Issue by LeoYang-Chuese** [PointCloudLibrary/pcl#5014]
[io] Open Chinese path ply file failed after upgrade to version 1.12

**Describe the bug**

Open Chinese path ply file failed after upgrade to version 1.12,1.11.1 is normal.

**Context**

Version 1.12 calls `io::loadPolygonFile` function to read the Chinese path ply file, read the result PolygonMesh polygons is empty. Version 1.11.1 result is normal. 1.12 call ansi_to_utf8 to read Chinese paths after conversion is normal. 1.11.1 to 1.12 in this convenient what changes?

**Expected behavior**

1.12 and 1.11.1 are consistent, support Chinese path.Or the 1.12 plan no longer supports ANSI encoded paths.

**Current Behavior**

Call `io::loadPolygonFile` function to read the Chinese path ply file, read the result of PolygonMesh polygons is empty.

**To Reproduce**

Call `io::loadPolygonFile` function to read Chinese path ply file in version 1.12

**Screenshots/Code snippets**

In order to help explain your problem, please consider adding

* screenshots of the GUI issues
* ![Snipaste_2021-11-04_17-48-26](https://user-images.githubusercontent.com/18021614/140294422-c239228f-ac53-4c0a-96da-7981bb2457a9.jpg)

**Your Environment (please complete the following information):**

 - OS: Windows 19042, 64 bits
 - Compiler: *Visual Studio 2019 (v142)*
 - PCL Version:1.12

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

Chinese OS default ANSI encoding, this is the ANSI encoding incompatibility problem, after converting to UTF-8 encoding is normal. This is not caused by the change of 1.12 and 1.11.x incompatibility.

**Comment by mvieth** [comment]
I am pretty sure that nothing inside PCL was changed that could explain this error. `loadPolygonFile` uses functions from VTK internally, so maybe they changed something. Do you get any warning or error message when you call `loadPolygonFile`?
Alternatively, you can try [`load`](https://pointclouds.org/documentation/group__io.html#ga3c5d88dbcd766a748832161f1aede422), but I have no idea whether that can handle a path with Chinese characters. I usually only use ASCII characters for paths and filenames to avoid such headaches :smiley:

**Comment by mvieth** [comment]
Closing due to no response, and because it does not seem like PCL is at fault

**Comment by LeoYang-Chuese** [comment]
Thanks for your answer,` loadPolygonFile` is just a very thin layer of wrapping and I can confirm that it is not PCL's cause. However, I tested VTK v8.2 separately with the same problem, but it does not appear in PCL v1.11.x. I will follow up in the follow-up if I find the fundamental difference and the reason.
