### ISSUE TITLE
[Registration] cos_angle calculation is incorrect in NormalDistributionsTransform::computeTransformation.

### ISSUE THREAD

**Issue by KotaYonezawa** [PointCloudLibrary/pcl#5016]
**Describe the bug**

Thanks a lot for great library.
I found a bug in NormalDistributionsTransform::computeTransformation.
To handle "transformation rotation epsilon" parameter for determining  termination condition,
cosine angle is calculated from rotation vector.
But this calculation formula is not correct.

**Context**

There is an issue in following code in ndt.hpp, line 156, 157.
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L156

```
    const double cos_angle =
        0.5 * transformation_.template block<3, 3>(0, 0).trace() - 1;
```

According to following: 
https://en.wikipedia.org/wiki/Rotation_matrix#Determining_the_angle
trace(rotation matrix) = 2 * cos (rotation angle) + 1
So...
cos (rotation angle) = 0.5 * (trace (rotation matrix) - 1)

This means above code should be...

```
    const double cos_angle =
        0.5 * (transformation_.template block<3, 3>(0, 0).trace() - 1);
```

**Expected behavior**

After modification, setTransformationRotationEpsilon for NormalDistributionsTransform should work correctly.

**Current Behavior**

setTransformationRotationEpsilon for NormalDistributionsTransform class does not work correctly because of above wrong code.

**Your Environment (please complete the following information):**

- OS: Windows10
- Compiler: Compiler: Visual Studio 2019 Build Tools
- PCL Version: HEAD

**Comment by mvieth** [comment]
You are right, thanks for noticing! Would you create a pull request to fix this?

**Comment by KotaYonezawa** [comment]
Thanks a lot for comment!
I created the pull request.
Could you check it?
