### ISSUE TITLE
Run error while try the range image demo

### ISSUE THREAD

**Issue by gxmc0ming** [PointCloudLibrary/pcl#5019]
VS2019  X64  MSVC
PCL 1.12.0

I have successful installed the PCL and run some demos.

When I am try the tutorial about range image creation：
         http://pointclouds.org/documentation/tutorials/range_image_creation.html#range-image-creation

It can be compiled and build, However running with the error:
      Assertion failed: (internal::UIntPtr(array) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file C:\Program Files\Eigen3\include\eigen3\Eigen\src/Core/DenseStorage.h, line 128

How can I fix it .

**Comment by mvieth** [comment]
You probably have to enable AVX/AVX2 for your project

**Comment by mvieth** [comment]
Closing because of no response

**Comment by wangwenfeng0** [comment]
> 

Thank you for your reply, I want to know how to enable AVX/AVX2 for VS project.

**Comment by wangwenfeng0** [comment]
I test the pcl -1.11.1， that is ok.

**Comment by 804463592** [comment]
The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?

**Comment by larshg** [comment]
> The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?

If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.

How did you install PCL and what is your settings on your own project?

**Comment by 804463592** [comment]
> > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> 
> If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> 
> How did you install PCL and what is your settings on your own project?

It is the first time for me to install PCL1.12 on windows and when I call the createFromPointCloud function, the error occurs and I don't know where to configure the SSE/AVX(2) settings on PCL. However, for the version of  PCL1.11 , there is no problems.

**Comment by 804463592** [comment]
> > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> 
> If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> 
> How did you install PCL and what is your settings on your own project?

It is just a pcl demo, No any special settings.

**Comment by larshg** [comment]
> > > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> > 
> > 
> > If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> > How did you install PCL and what is your settings on your own project?
> 
> It is the first time for me to install PCL1.12 on windows and when I call the createFromPointCloud function, the error occurs and I don't know where to configure the SSE/AVX(2) settings on PCL. However, for the version of PCL1.11 , there is no problems.

How did you install PCL. with one-in-all-installer or vcpkg?
How do you generate your own solution?

**Comment by 804463592** [comment]
> > > > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> > > 
> > > 
> > > If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> > > How did you install PCL and what is your settings on your own project?
> > 
> > 
> > It is the first time for me to install PCL1.12 on windows and when I call the createFromPointCloud function, the error occurs and I don't know where to configure the SSE/AVX(2) settings on PCL. However, for the version of PCL1.11 , there is no problems.
> 
> How did you install PCL. with one-in-all-installer or vcpkg? How do you generate your own solution?

I use one-in-all-installer.
And CMake to generate the demo solution.

**Comment by larshg** [comment]
> > > > > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> > > > 
> > > > 
> > > > If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> > > > How did you install PCL and what is your settings on your own project?
> > > 
> > > 
> > > It is the first time for me to install PCL1.12 on windows and when I call the createFromPointCloud function, the error occurs and I don't know where to configure the SSE/AVX(2) settings on PCL. However, for the version of PCL1.11 , there is no problems.
> > 
> > 
> > How did you install PCL. with one-in-all-installer or vcpkg? How do you generate your own solution?
> 
> I use one-in-all-installer. And CMake to generate the demo solution.

Alright. The one-in-all is compiled without AVX at least, so you need to be sure your setup is the same. You can this in the settings, like seen in this issue: https://github.com/PointCloudLibrary/pcl/issues/4987

**Comment by 804463592** [comment]
> > > > > > The 1.12 version of PCL does have this problem，Does anyone know if the new version of PCL solves this problem?
> > > > > 
> > > > > 
> > > > > If its an SSE/AVX(2) problem you just need to be sure to have the same settings on PCL as in your own project that uses PCL.
> > > > > How did you install PCL and what is your settings on your own project?
> > > > 
> > > > 
> > > > It is the first time for me to install PCL1.12 on windows and when I call the createFromPointCloud function, the error occurs and I don't know where to configure the SSE/AVX(2) settings on PCL. However, for the version of PCL1.11 , there is no problems.
> > > 
> > > 
> > > How did you install PCL. with one-in-all-installer or vcpkg? How do you generate your own solution?
> > 
> > 
> > I use one-in-all-installer. And CMake to generate the demo solution.
> 
> Alright. The one-in-all is compiled without AVX at least, so you need to be sure your setup is the same. You can this in the settings, like seen in this issue: #4987

Thanks!!!

**Comment by larshg** [comment]
Did you get it work?

**Comment by 804463592** [comment]
> Did you get it work?

Yes, it works well!!! I did like this issue[https://github.com/PointCloudLibrary/pcl/issues/4987](url), adding a CMake statement “target_compile_options(PointCloudMaster PUBLIC "/arch:AVX2")”
