### ISSUE TITLE
The index of the input ordered point cloud is returned after each processing

### ISSUE THREAD

**Issue by SEUZTh** [PointCloudLibrary/pcl#5023]
I'm dealing with ordered point clouds. The input point cloud is 1920 * 1200. After filtering, downsampling, segmentation and other operations, the output is disordered point cloud. I want to be able to output ordered point clouds with the same height and width.
As follows, after four times of processing, the index of the corresponding first column can be found through the index of the last column.
```
1 1 1 1
2
3 2
4
5 3 2
6
7 4
8
9 5 3 2
```
I don't know whether it can be implemented by custom classes.
I look forward to receiving your reply!

**Comment by mvieth** [comment]
Please ask this kind of questions in the Discord community chat.
I would just give you two hints: check out [`setKeepOrganized`](https://pointclouds.org/documentation/classpcl_1_1_filter_indices.html#a21eb00357056c0cc432cd03afa84d08c), and consider if you want to work only with indices that refer to your initial, organized cloud (i.e. every operation/filter receives the initial cloud and a set of indices as input, and returns a reduced set of indices - whether this can work depends on the operations/filters)
