### ISSUE TITLE
[compile error] "Compilation error in PCL 1.10 eucliediean_cluster_comparator.h"

### ISSUE THREAD

**Issue by abmuslim** [PointCloudLibrary/pcl#5031]
### Describe the error
Facing error in euclidiean_cluster_comparator.h file when using setExcludeLabel() function. 

### Please paste the compilation results/errors.

> /usr/include/pcl-1.10/pcl/segmentation/euclidean_cluster_comparator.h:256:13: error: no matching functio
n for call to ‘std::set<unsigned int>::insert(std::size_t&) const’
  256 |             exclude_labels_->insert (i);

### To Reproduce
In order to reproduce the error I am sharing my code what I did,
`std::vector<bool> ignore_labels;
ignore_labels.resize(2);
 ignore_labels[0] = true;
 ignore_labels[1] = false;
pcl::EuclideanClusterComparator<PointT,pcl::Normal, pcl::Label>::Ptr ecc(new  pcl::EuclideanClusterComparator<PointT,pcl::Normal, pcl::Label>());
ecc->setExcludeLabels(ignore_labels);`

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

### Screenshots/Code snippets/Build information
![screenshot](https://user-images.githubusercontent.com/55253316/140979250-9ee21e56-68e1-44f4-b176-1a736816a0f8.png)

### Environment

 - OS: Ubuntu 20.04
 - Compiler: GCC 9.3.0
 - PCL Version 1.10
 - PCL Type: [Installed/Compiled from source]

**Possible Solution**
On line 179 of euclidiean_cluster_comparator.h instead of  
`ExcludeLabelSetConstPtr exclude_labels_;` 
put 
`ExcludeLabelSetPtr exclude_labels_;`
That is what I think but you can guide me further.

**Comment by mvieth** [comment]
Yes, `insert` would modify `exclude_labels_`, but that is const. However, the function you are trying to use is [declared deprecated](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.10.0/segmentation/include/pcl/segmentation/euclidean_cluster_comparator.h#L249) with a hint to use the other `setExcludeLabels` function, is that warning not displayed?
Also, [this is how euclidean_cluster_comparator.h looks now](https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/euclidean_cluster_comparator.h) (PCL 1.12.0, deprecated stuff removed)

**Comment by abmuslim** [comment]
Thank you for the reply @mvieth. No, the error was not displayed as you saw in the screenshot. But yeah now I am following this declared deprecated way. 
Basically, I am working on ROS noetic which supports version PCL 1.10, I ran the same code on PCL 1.8 it works fine but with PCL 1.10 it is not able to find the good clusters in the images.
