### ISSUE TITLE
Can't install openni_camera list

### ISSUE THREAD

**Issue by Windrag-Kong** [PointCloudLibrary/pcl#5035]
Can't install openni_camera list

**Comment by mvieth** [comment]
You definitely need to give us more information, like: What exactly are you doing (steps to reproduce)? What version of PCL are you using? What operating system are you using? Is there some kind of error message? ...

**Comment by Windrag-Kong** [comment]
[](url
![b876fc90945493f1a8701622200a49c](https://user-images.githubusercontent.com/93043313/142712267-04ee5795-4e18-480f-b78e-d0249de21b6e.png)
)
see the picture,the redline parts can't install the computer,see the follow picture

![f169b6f6d97740eb25e0a29fab14db4](https://user-images.githubusercontent.com/93043313/142712348-edcdb6d8-057c-4549-95e5-440b59a09915.png)

**Comment by mvieth** [comment]
So I see that you are using Windows and PCL 1.12.0, and your question is why those directories are not installed on your computer.
How did you install PCL?

**Comment by Windrag-Kong** [comment]
I used PCL-1.12.0-AllInOne-msvc2019-win64

**Comment by Windrag-Kong** [comment]
I used PCL-1.12.0-AllInOne-msvc2019-win64

**Comment by UnaNancyOwen** [comment]
OpenNI 1.x is not supported in Visual Studio 2012 and later, so the pre-built PCL that included in the PCL All-in-one Installer has OpenNI option disabled. Therefore, the OpenNI grabber is not available. We have enabled OpenNI2 option instead of OpenNI option. You can use the OpenNI2 grabber instead of the OpenNI grabber.

**Comment by kaitou1419** [comment]
@UnaNancyOwen I had tried using "openni2_viewer.CPP" in PCL/Tools. Project Compiled OK, but I Can't get data from my Microsoft Kinect camera. After running grabber_.start ();  An notification that's Failed to Synchronize Depth Color has occurred. Can you give me an advice!
![image](https://user-images.githubusercontent.com/73357725/143764108-2860ce04-c115-4e52-8491-e62101e4b936.png)

**Comment by UnaNancyOwen** [comment]
First of all, You need to check if your sensor works with OpenNI2. Please check it with NiViewer included in OpenNI2.
Also, We are unable to provide support for OpenNI2. Please do your own research on how to use OpenNI2.

The original problem with this issue has been solved. Please close this issue. As a general rule, please keep one problem per one issue. If you have more problem, Please open new issue with sufficient information (os, sensor, version, compiler, and other).
