### ISSUE TITLE
[gpu] Unused parameter

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#5036]
I don't know why the line numbers are wrong, but I'm getting following warnings:

```cpp
/.../pcl/gpu/containers/src/initialization.cpp:100:86: warning: unused parameter 'device_attribute' [-Wunused-parameter]
    template <class T> inline void getCudaAttribute(T *attribute, CUdevice_attribute device_attribute, int device)
                                                                                     ^
/.../pclgpu/containers/src/initialization.cpp:100:108: warning: unused parameter 'device' [-Wunused-parameter]
    template <class T> inline void getCudaAttribute(T *attribute, CUdevice_attribute device_attribute, int device)
                                                                                                           ^
/.../pcl/gpu/containers/src/error.cpp:42:94: warning: unused parameter 'func' [-Wunused-parameter]
void pcl::gpu::error(const char *error_string, const char *file, const int line, const char *func)
                                                                                             ^
```

**Comment by mvieth** [comment]
So I guess someone should investigate whether [this line](https://github.com/PointCloudLibrary/pcl/blob/master/gpu/containers/src/initialization.cpp#L137) is correct, and whether [this line](https://github.com/PointCloudLibrary/pcl/blob/master/gpu/containers/src/error.cpp#L48) should also include `func`?

**Comment by xiaolong-666** [comment]
Hi @mvieth I want to contribute my strength, this will be my first open source contribution, can I solve it?

**Comment by mvieth** [comment]
@xiaolong-666 That's great!
In error.cpp, I would suggest to simply print that the error happened in the function `func`, maybe after checking that `func` is not an empty string.
In initialization.cpp, I don't know why the `cuDeviceGetAttribute` call was commented out (if you have an idea please tell), but I would say it makes sense to enable it again.
[Here is a guide for creating a pull request](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request). If you have questions, feel free to ask

**Comment by xiaolong-666** [comment]
> @xiaolong-666 That's great! In error.cpp, I would suggest to simply print that the error happened in the function `func`, maybe after checking that `func` is not an empty string. In initialization.cpp, I don't know why the `cuDeviceGetAttribute` call was commented out (if you have an idea please tell), but I would say it makes sense to enable it again. [Here is a guide for creating a pull request](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request). If you have questions, feel free to ask

@mvieth Thanks for your suggestion, I will do it

**Comment by xiaolong-666** [comment]
Hi @mvieth i submitted a merge request, but `ci` faild, so what should i do? please review [Remove unused parameter](https://github.com/PointCloudLibrary/pcl/pull/5059)

**Comment by kunaltyagi** [comment]
> I don't know why the cuDeviceGetAttribute call was commented out

`* 3748a5d1b 2011-11-28 | edisabled temporary queering device attributes as it causes link errors for ubuntu64 [Anatoly Baksheev]`

I guess we can safely enable it back 😆

**Comment by Zekrom-7780** [comment]
Hi, @mvieth ,can i try to work on this one?
As this one says good first issue, and this will be my first open-source contribution??

**Comment by mvieth** [comment]
@Zekrom-7780 There is already someone working on this (see the linked pull request). Please look for another issue that interests you, if you like
