### ISSUE TITLE
[pcl::features] spin images can not change image_width, it only works well with "image_width=8"

### ISSUE THREAD

**Issue by wenxingguo** [PointCloudLibrary/pcl#5039]
**Describe the bug**
spin images can not change image_width, it only works well with "image_width=8"
**Screenshots/Code snippets**

```c++
#define IMAGE_WIDTH 9
#define DIM ((IMAGE_WIDTH+1)*(IMAGE_WIDTH*2 + 1))
int main{
    pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<DIM> > spin_image_descriptor(IMAGE_WIDTH, 0, 0);
    return 0;
}
```

Undefined symbols for architecture arm64:
  "pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<190> >::initCompute()", referenced from:
      vtable for pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<190> > in spin_image-49661c.o
  "pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<190> >::computeFeature(pcl::PointCloud<pcl::Histogram<190> >&)", referenced from:
      vtable for pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<190> > in spin_image-49661c.o
  "pcl::SpinImageEstimation<pcl::PointXYZ, pcl::Normal, pcl::Histogram<190> >::SpinImageEstimation(unsigned int, double, unsigned int)", referenced from:
      _main in spin_image-49661c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Your Environment (please complete the following information):**

 - OS: [mac os 11.6.1]
 - Compiler: [clang 12]
 - PCL Version [1.12]

**Comment by mvieth** [comment]
Does it work if you put `#define PCL_NO_PRECOMPILE 1` before `#include <pcl/features/spin_image.h>`?
The reason is that `SpinImageEstimation` is only instantiated for histograms of size 153, [see here](https://github.com/PointCloudLibrary/pcl/blob/master/features/src/spin_image.cpp)

**Comment by mvieth** [comment]
@wenxingguo Does the solution I suggested work? If I don't hear from you, I might close this issue soon
