### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by CrownW** [PointCloudLibrary/pcl#5041]
I deployed the same ubuntu18 vm image with pcl1.9 installed on intel11 and 10 processors. There is a problem that the program compiled by the 10th generation processor can be used in the 11th generation, but the program compiled by the 11th generation processor cannot be used in the 10th generation. How can I solve this problem?

**Comment by mvieth** [comment]
Which "program" do you mean specifically? Do you mean PCL itself, or your own project that uses PCL? How do you see that it cannot be used? Some error message?
To build a library/executable that works with multiple processors, you have to use the right flags/specify the architecture in the right way. [See this stackoverflow](https://stackoverflow.com/questions/2670121/using-cmake-with-gnu-make-how-can-i-see-the-exact-commands) for how to see the build commands (and flags). Problems could be `-march=native`, or, less likely, sse or avx flags. Use e.g. ccmake to disable those options

**Comment by mvieth** [comment]
Since you did not reply, I am going to assume that my last comment answered your question, and close this issue
