### ISSUE TITLE
[comError: Building package pcl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by antoniobelchiorferraz** [PointCloudLibrary/pcl#5043]
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j9
    Working Directory: C:/Users/aferraz/vcpkg/buildtrees/pcl/x64-windows-rel
    See logs for more information:
      C:\Users\aferraz\vcpkg\buildtrees\pcl\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core]:x64-windows -> 1.12.0
  vcpkg version: 203daf984 2021-11-19 (8 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

**Comment by larshg** [comment]
Please post this at VCPKG repository.
Closing as its not an error in PCl per se.

**Comment by halkuran** [comment]
How can one install PCL on windows? The default installation method doesn't work and the all-in-one installer is not available anymore.
We as beginner programmers appreciate your hard work. But it's pointless if we can't access PCL.
