### ISSUE TITLE
Looking for CropPolygon filter something similar to CropBox filter.

### ISSUE THREAD

**Issue by ajay1606** [PointCloudLibrary/pcl#5044]
Trying to crop part of the point cloud using polygon structure instead of Croping box. But after going through the PCL tutorial, I found the Concave Hull & Convex Hull example to crop point cloud. But it looks quite complicated than I expected. I tried to use CocaveHull to crop part point cloud, but it's not working.
 
Given input points cloud and polygon points to crop the desired region of points from the input cloud. Similar to crop box coordinate, which crop desired region using box coordinate points. As mentioned in the below image, looking to extract the point cloud mentioned in the red coloured points using ConcaveHull, but it's not working.

Given input point cloud and Polygon Points, But didn't understand hull cloud, why there should be another cloud input? Do we actually need that?
Input Point cloud:
![image](https://user-images.githubusercontent.com/29722843/142804923-172003b0-9b17-4bf1-a719-d5bc07097623.png)

Expected Cropped point cloud (Highlighted in Red color)
![image](https://user-images.githubusercontent.com/29722843/142790670-9b5c3d9d-5513-4192-98d4-d6be9f61d4b2.png)

Example case:
 In the Cloud Compare tool, it is possible to crop the cloud using a bounding box or polygonal lines. In the case of Polygonal Lines, the user will input polygonal points and based on points CC will take care of generating the desired polygon to crop point cloud.

![image](https://user-images.githubusercontent.com/29722843/142806397-61260b53-c2fa-481e-a865-650665fbcdbe.png)

**Expected behavior**
Expecting to crop point cloud using Polygon by inputting polygon points.

**Current Behavior**
Current ConvaveHull crop requires input point cloud and hull cloud along with the polygonal points. 
**Describe the solution you'd like**
Looking for crop point cloud by specifying the polygon coordinates. 

And what does the parameter alpha refer to? In my case I can cropped point cloud only if I set alpha value more than 20. Also cropped point cloud also not complete.

Any response much appreciated

**Comment by mvieth** [comment]
Which tutorial are you referring to?

**Comment by ajay1606** [comment]
@mvieth Thanks for your response, here is the example code I am referring to. https://github.com/PointCloudLibrary/pcl/blob/master/tools/crop_to_hull.cpp

  pcl::io::loadPCDFile ("scan.pcd", *cloud); //Input Cloud
  pcl::PointCloud<pcl::PointXYZ>::Ptr boundingbox_ptr (new pcl::PointCloud<pcl::PointXYZ>);//Used to store the boundary points

  pcl::PointCloud<pcl::PointXYZ>::Ptr hull(new pcl::PointCloud<pcl::PointXYZ>);
  
  boundingbox_ptr->push_back(pcl::PointXYZ(2.4540920,4.5372330,-1.765007));
  boundingbox_ptr->push_back(pcl::PointXYZ(17.673540,2.1049390,-1.575006));
  boundingbox_ptr->push_back(pcl::PointXYZ(31.024261,-5.344881,-1.856550));
  boundingbox_ptr->push_back(pcl::PointXYZ(29.543362,-11.701818,-2.249893));
  boundingbox_ptr->push_back(pcl::PointXYZ(13.183183,-4.748318,-1.984008));
  boundingbox_ptr->push_back(pcl::PointXYZ(4.4728370,-2.861379,-1.816805));

//Calculate Hull
 pcl::ConcaveHull<pcl::PointXYZ> hull_calculator;
 std::vector<pcl::Vertices> polygons;
 hull_calculator.setInputCloud (boundingbox_ptr);
 hull_calculator.setAlpha (20);
 hull_calculator.reconstruct (*hull, polygons);
 int dim = hull_calculator.getDimension ();

// Crop Hull
  CropHull<pcl::PointXYZ> crop_filter;
  crop_filter.setInputCloud (cloud);
  crop_filter.setHullCloud (hull);
  crop_filter.setHullIndices (polygons);
  crop_filter.setDim (dim);
  crop_filter.filter (*cloud_out);

Here is the current output.
![image](https://user-images.githubusercontent.com/29722843/143148501-be412a33-1325-46b2-bece-77320379cdb6.png)

What does actually alpha value mean to ! Could you please explain it?


Regards,
Ajay

**Comment by mvieth** [comment]
Ah, you mean the program from the "tools".
The alpha value controls how "concave" the hull should be, look e.g. at [this image](https://media.springernature.com/lw785/springer-static/image/art%3A10.1186%2Fs12862-018-1305-z/MediaObjects/12862_2018_1305_Fig1_HTML.png) and [the documentation](https://pointclouds.org/documentation/classpcl_1_1_concave_hull.html#ab2e24dc457ff32634aa2549a10bc7562).
I would recommend you to not use `ConcaveHull`: While it creates the `polygons` for you, I think it is difficult to find a good value for alpha, so that the polygon shape is exactly as you want it to be. You should rather construct `hull` and `polygons` for `setHullCloud` and `setHullIndices` yourself. You can use the PCLVisualizer with [addPolygonMesh](https://pointclouds.org/documentation/classpcl_1_1visualization_1_1_p_c_l_visualizer.html#a41454a3339e4ad13337901e2b5e55d2f) to see how the polygon shape looks

**Comment by ajay1606** [comment]
@mvieth Thanks for your kind & valuable suggestion. But sorry am not sure, whether I got it right or wrong. Appreciate your clarification on these. In the following code you mean to say that No need to compute concavehull, Just I can crop desired point cloud based on the polygon points input.

Suppose if I modify the code like below, how should I compute indices of polygon cloud?  Because in previous code, while computing Concave hull, Polygon Indices are extracted. But here, if Conccave hull computation is omitted, then how to compute point indices for polygon points?

// Crop Hull
  CropHull<pcl::PointXYZ> crop_filter;
  crop_filter.setInputCloud (cloud);
  crop_filter.setHullCloud (boundingbox_ptr);
  crop_filter.setHullIndices (polygons); 
  crop_filter.setDim (dim);
  crop_filter.filter `(*cloud_out);`

Thanks for the Visualization option. It was really helpful.

Regards,
Ajay

**Comment by mvieth** [comment]
You have to create `polygons` yourself, to describe the polygon shape you want to use for cropping. `polygons` describes the faces (each `pcl::Vertices` is one face). The indices are used on the cloud you set with `setHullCloud`. I recommended the visualization option so you can check whether the `polygons` you create are correct

**Comment by ajay1606** [comment]
@mvieth I mean, I can describe the shape of a polygon through a set of points,  but how can I generate Indices for those points?
because **crop_filter.setHullIndices (polygons)**; here it is necessary to input indices of polygonal points.

**Comment by mvieth** [comment]
I am not sure I understand the question? Every index is used to access the corresponding point in the cloud (the cloud you set with `setHullCloud`). So you just have to fill `polygons` with indices and the cloud with points, so that each index refers to the correct point. The simplest way would be to `cloud.push_back(...)` each point you want to use, and use `cloud.size()-1` as the index (refers to the last point, the one you just pushed)

**Comment by mvieth** [comment]
Ok, seems like that answered your question, so I am going to close this issue. Otherwise you can try to ask on the community discord
