### ISSUE TITLE
New header compatible issue with element face 0 on PCL1.12 

### ISSUE THREAD

**Issue by cdb0y511** [PointCloudLibrary/pcl#5050]
https://github.com/PointCloudLibrary/pcl/blob/7f87657e8f796373852ff7f80228a1573239de8d/io/src/ply_io.cpp#L795
I notice the header is changed from PCL 1.11.1 by adding element face 0. It should be compatible with VTK.
However, the new header will not be compatible with PoissonRecon.
https://github.com/mkazhdan/PoissonRecon
With a new header from PCL1.12 (element face 0 at the end of the header)
Poisson Recon Version 13.72 failed to read the *.ply (delete element face 0 will be OK).
I suggest the IO should have an option to choose whether add the element face 0 at the end of the header.

**Comment by mvieth** [comment]
I would tend to say that this is something that the PoissonRecon maintainers should fix. As far as I know, the line `element face 0` is valid in terms of the ply file format (although there isn't a very strict format specification, [this page](https://web.archive.org/web/20161204152348/http://www.dcs.ed.ac.uk/teaching/cs4/www/graphics/Web/ply.html) is probably the most "official", but it doesn't explicitly say whether or not there may be zero elements of something). I tested MeshLab and it also writes the line `element face 0` when there are no faces. I am not aware that any other program has a problem with the line `element face 0` being there, so I would consider it valid and PoissonRecon should be able to read it. Have you contacted the maintainers? It might be easy to fix.
On the possibility of adding an option to choose whether the line is added or not: not impossible, but it would be necessary to add parameters to several functions, and, as mentioned, is seems that only PoissonRecon has a problem with this.
There is of course also the option to remove the line after PCL wrote the file, e.g. manually or with `sed`

**Comment by cdb0y511** [comment]
Thanks, 
I will submit this issue to PoissonRecon.

**Comment by cdb0y511** [comment]
https://github.com/mkazhdan/PoissonRecon/issues/207#issuecomment-982326000
I link the discussion with PoissonRecon author here.
I hope it can help us to make a better header.

**Comment by mvieth** [comment]
Thank you @mkazhdan for the hint!
It is quite annoying that the PLY format is so loosely defined, leaving some room for interpretation regarding which files are valid and which are not.
I would be okay with adding `property list uchar int vertex_indices` or similar after `element face 0`, provided we can verify that e.g. VTK, CloudCompare, and MeshLab can still load the file.
@cdb0y511 Would you be interested in working on this and creating a pull request?

**Comment by cdb0y511** [comment]
> Thank you @mkazhdan for the hint! It is quite annoying that the PLY format is so loosely defined, leaving some room for interpretation regarding which files are valid and which are not. I would be okay with adding `property list uchar int vertex_indices` or similar after `element face 0`, provided we can verify that e.g. VTK, CloudCompare, and MeshLab can still load the file. @cdb0y511 Would you be interested in working on this and creating a pull request?

It is an honor to contribute to the community.
I will try to create a pull request. But timeliness cannot be guaranteed cause I have a full-time job to do.
