### ISSUE TITLE
Euclidean Cluster Extraction: extracting indices returns error Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to radiusSearch!"' failed

### ISSUE THREAD

**Issue by UmutUz** [PointCloudLibrary/pcl#5058]
I am on Windows 11 using PCL 1.8.1 with Visual Studio 2015

When I execute this code:

`	pcl::search::KdTree<pcl::PointXYZRGB>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZRGB>);
	tree->setInputCloud(cloud);

	std::vector<pcl::PointIndices> cluster_indices;
	pcl::EuclideanClusterExtraction<pcl::PointXYZRGB> ec;
	ec.setClusterTolerance(0.2);
	ec.setMinClusterSize(100);
	ec.setMaxClusterSize(25000);
	ec.setSearchMethod(tree);
	ec.setInputCloud(cloud);
	ec.extract(cluster_indices);`

I get the mentioned error in the title: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to radiusSearch!"' failed at ec.extract(cluster_indices);

Does anyone know how to fix this?

**Comment by mvieth** [comment]
Have you tried to remove all points where coordinates are NaN or Inf from the cloud, e.g. with `PassThrough` or `removeNaNFromPointCloud`?

**Comment by UmutUz** [comment]
oh man, yeah that was the problem... thanks a lot

**Comment by amgz1997** [comment]
can you please write the changes in your code  ?
