### ISSUE TITLE
using VoxelGridFilter and displaying the result causes "-1073740940" exit code stopping the program

### ISSUE THREAD

**Issue by UmutUz** [PointCloudLibrary/pcl#5068]
I am on Windows 11 and used PCL 1.8.1 which was working kinda fine so I upgraded to 1.12.0 and had to fix a lot of code (new to C++ so Pointers for example are still confusing).

Anyway, the below code finished with the exit code mentioned in the title:
 
```
int main(int argc, char** argv) {

	pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
	pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZRGB>);

	std::cout << "loading";

	if (pcl::io::loadPCDFile<pcl::PointXYZRGB>("zweitePC.pcd", *cloud) == -1) //* load the file
	{
		PCL_ERROR("Couldn't read file zweitePC.pcd \n");
		return (-1);
	}
	std::cout << "Loaded " << cloud->width * cloud->height << " data points from zweitePC.pcd with the following fields: " << std::endl;

	pcl::VoxelGrid<pcl::PointXYZRGB> downsample;

	downsample.setInputCloud(cloud);
	downsample.setLeafSize(0.01f, 0.01f, 0.01f);
	downsample.setFilterFieldName("z");
	downsample.setFilterLimits(0, 1.4);
	downsample.filter(*cloud_filtered);

	pcl::visualization::CloudViewer viewer0("Cloud Viewer");
	viewer0.showCloud(cloud_filtered, "pcl_camera4");


	while (!viewer0.wasStopped())
	{
	}
	

	viewer0.showCloud(cloud, "pcl_camera2");

	while (!viewer0.wasStopped())
	{
	}
}
```

Practically reaches the first viewer and then throws the exit code in release mode. In Debug Mode I get a CrtIsValidHeapPointer(Block). I have no clue why and what kind of error this is :/ Can anyone please help?

**Comment by larshg** [comment]
I have tried tested the cloudviewer and it works fine rendering a random cloud with 3 points.
Can you share your point cloud, then I can try your exact example with your code.

**Comment by UmutUz** [comment]
[erstePC.zip](https://github.com/PointCloudLibrary/pcl/files/7697689/erstePC.zip)

Okay, I am not allowed to upload a pcd file so i zipped it (hoping that it works lol). Can you try the same code in Release mode please? Maybe I should post my cmakelist.txt too if that helps

**Comment by larshg** [comment]
![image](https://user-images.githubusercontent.com/1165340/145692665-26f5b640-c8a8-49c3-85c4-d65b79554d6c.png)

Works fine here. I wonder if it is a GFX driver issue and it fail to create the openGL renderer or something similar.

Can you print the stack from ie. visual studio, if that's what your are using?

**Comment by UmutUz** [comment]
This is what I get first in Release mode:

![image](https://user-images.githubusercontent.com/47572028/145693732-d4dde652-edd3-414f-9331-9785299186d6.png)

 When I press next/play/resume to further execute the code I get:

![image](https://user-images.githubusercontent.com/47572028/145693773-966c980c-804c-450e-9fdb-293b03ad2426.png)

and only when I press F5, which return with exit code '0' which is fine I guess. But starting with ctrl + F5 gives me the error in the title and stopping the program (meaning code afterwards isnt executed anymore)

This is what I get in Debug mode using F5 to start debugging:

![image](https://user-images.githubusercontent.com/47572028/145693835-fe25f117-f5a3-4e51-863f-098951947431.png)

Using ctrl + F5 gives me the CrtIsValidHeapPointer(block) error.

I hope this helps or is what you asked for.

**Comment by larshg** [comment]
Ah, yes. You need to enable AVX2 in your project. Under properties->compile commands-> simd instruction set.
The actual names might be wrong, its just top of my memory.
Search for if you cant find it - we have other issues with AVX missing already.

**Comment by UmutUz** [comment]
Tried that, still having the same problem :/

**Comment by larshg** [comment]
Great!
Closing the issue then.
