### ISSUE TITLE
[compile error] "Windows KDtree fails cannot find lz4.lib"

### ISSUE THREAD

**Issue by pettaa123** [PointCloudLibrary/pcl#5069]
**Describe the error**

Build started...
>------ Build started: Project: pcl_kdtree, Configuration: Release x64 ------
>LINK : warning LNK4044: unrecognized option '/Wl,--push-state,--no-as-needed'; ignored
>LINK : warning LNK4044: unrecognized option '/Wl,--pop-state'; ignored
>LINK : fatal error LNK1181: cannot open input file 'lz4.lib'
>Done building project "pcl_kdtree.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**To Reproduce**

get latest dev lz4.lib from github
configure using cmake
build with MSVC vc143 64bit release
add path of lz4.lib to win path

get latest flann from github
change cmake with commit: https://github.com/flann-lib/flann/pull/400/commits/cae44ca0a17c9ca783a006d8c133a4dc1e26c010
configure using cmake
build with MSVC vc143 64bit release
add path of flann_cpp.lib to win path

git clone https://github.com/boostorg/boost.git --recursive
open msvc shell x64
cd into src
bootstrap.bat
b2 --build-dir=..\boost_build address-model=64 variant=release link=shared toolset=msvc threading=multi -j 8
add path of boost libs to win path

get latest pcl from github
configure using cmake
set flann include dir
set flann_library_static
set flann_library_shared
set flann_dir
set boost include dir
set boost library releases for all but mpi
build with MSVC vc143 64bit release

**Your Environment (please complete the following information):**

 - OS: Win1064
 - Compiler: MSVC vc143
 - PCL Version latest master

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No
 - With VTK 9.1
 - boost latest master
 - flann with latest mentioned PR commit

After adding the mentioned commit to flann I was able to build flann without errors in VS2022.
Unfortunately while building kdtree I get linker errors from lz4.lib. The Path to lz4.lib is in my Win path.

**Comment by larshg** [comment]
Install dependencies with VCPKG.

I have seen this error before with the: /Wl,--push-state,--no-as-needed etc. and it failed miserably. I can't however remember where this one is and it seems more an issue for lz4 than for PCL.

**Comment by larshg** [comment]
Ahh, now I remember a bit more. Its Flann that does some wierd stuff. See a patch used in VCPKG https://github.com/microsoft/vcpkg/blob/2462a956c8068e4dab8aa8bbe9a406016106e188/ports/flann/fix-build-error.patch

it removes the error, but again. Use VCPKG then it should be easier (however they also sometimes make things break 😄 )

**Comment by pettaa123** [comment]
I used vcpkg for pcl dependencies, despite qt and vtk. With using your pcl_vcpkg_Windows guide it compiled .
