### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by Rampantsen** [PointCloudLibrary/pcl#5072]
Operating System and version: Ubuntu 20.04
PCL Version: latest version
I'm getting the following error message while trying to install PCL

[ 34%] Building CXX object filters/CMakeFiles/pcl_filters.dir/src/local_maximum.cpp.o
[ 34%] Building CXX object filters/CMakeFiles/pcl_filters.dir/src/model_outlier_removal.cpp.o
[ 34%] Linking CXX shared library ../lib/libpcl_filters.so
[ 34%] Built target pcl_filters
[ 34%] Linking CXX shared library ../lib/libpcl_surface.so
[ 34%] Built target pcl_surface
make: *** [Makefile:152：all] 错误 2

**Comment by kunaltyagi** [comment]
This is part of the error message. We need more information (specifically the actual error)

**Comment by Rampantsen** [comment]
When I try to execute the order “make -j8", it stopped at 34% and say make: *** [Makefile:152：all] 错误 2

**Comment by Rampantsen** [comment]
And what does the following passage mean?


[ 25%] Building CXX object tracking/CMakeFiles/pcl_tracking.dir/src/tracking.cpp.o
/usr/bin/ld: 当搜索用于 /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libOpenNI2.so 时跳过不兼容的 -lOpenNI2
/usr/bin/ld: 当搜索用于 /usr/lib/../lib/libOpenNI2.so 时跳过不兼容的 -lOpenNI2
/usr/bin/ld: 当搜索用于 /usr/lib/gcc/x86_64-linux-gnu/9/../../../libOpenNI2.so 时跳过不兼容的 -lOpenNI2
/usr/bin/ld: 当搜索用于 /usr/lib/libOpenNI2.so 时跳过不兼容的 -lOpenNI2
/usr/bin/ld: 找不到 -lOpenNI2
collect2: error: ld returned 1 exit status
make[2]: *** [io/CMakeFiles/pcl_io.dir/build.make:807：lib/libpcl_io.so.1.12.0.99] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1223：io/CMakeFiles/pcl_io.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....

**Comment by kunaltyagi** [comment]
You don't have OpenNI2 library but have requested PCL to build features related to it. If you don't need those features (most likely), please consider switching them off using `cmake <PCL source directory> -DWITH_OPENNI:=OFF`

**Comment by Rampantsen** [comment]
thanks, the issue has solved .But I meet new problems
When I try to execute the order “make -j8", it stopped at 34% and say make: *** [Makefile:152：all] 错误 2

**Comment by kunaltyagi** [comment]
Please use discord for issues not in the core library. The community can help figure out how to best go ahead.

For now, I'd recommend using `make -j2` (will be slower, but uses less RAM in case that's slower), but it could be a useless recommendation given the lack of info (no visible error)

**Comment by Rampantsen** [comment]
Thanks for you help. I am really appreciate.
