### ISSUE TITLE
[features] boundaryEstimation does not work for rectangular orthogonal planes 

### ISSUE THREAD

**Issue by kaiwen2020** [PointCloudLibrary/pcl#5075]
**Describe the bug**

I would like to extract boundary points of a point cloud which is obtained from downsampling a CAD model. I find that the boundaryEstimation function does not work for rectangular orthogonal planes, for example, a cuboid. With a large angle threshold (pi/4),  I get no boundary point. With a small angle threshold (pi/16), many points on the surface are considered as boundary. 

**To Reproduce**
You can find an example point cloud at the following link:  [a triangular object.](url)

**Screenshots/Code snippets**

```c++
pcl::PointCloud<pcl::Normal>::Ptr normals(new pcl::PointCloud<pcl::Normal>); 
pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normEst; 
normEst.setInputCloud(pcl::PointCloud<pcl::PointXYZ>::Ptr(cloud_model)); 
normEst.setRadiusSearch(0.01); 
normEst.compute(*normals); 

pcl::PointCloud<pcl::Boundary> boundaries; 
pcl::BoundaryEstimation<pcl::PointXYZ, pcl::Normal, pcl::Boundary> boundEst;
boundEst.setInputCloud(cloud_model); 
boundEst.setInputNormals(normals); 
boundEst.setRadiusSearch(0.008); 
boundEst.setAngleThreshold(M_PI/16); //
boundEst.setSearchMethod(pcl::search::KdTree<pcl::PointXYZ>::Ptr (new pcl::search::KdTree<pcl::PointXYZ>)); 
boundEst.compute(boundaries); 

pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_boundary (new pcl::PointCloud<pcl::PointXYZ>);
for(int i = 0; i < cloud_model->points.size(); i++) 
{ 
    if(boundaries[i].boundary_point > 0) 
    { 
	cloud_boundary->emplace_back(cloud_model->points[i]); //
    } 
}   
```

A screenshot of the boundary points that I obtain:
![Screenshot from 2021-12-14 10-04-01](https://user-images.githubusercontent.com/68065984/145919621-b4752bbe-7a89-455b-8e5c-5b0406ef4176.png)

**My Environment :**
 - OS: [Ubuntu 18.04]
 - PCL Version [1.11.0,]

I wonder why does this happen? Is it because we can not get reliable normal vectors on the boundary? How can we do to solve this problem? Thank you.

**Comment by kaiwen2020** [comment]
Sorry, maybe I did not ask the right question. The question is it does not work for closed objects, for example cuboid; it works well for orthogonal planes.

**Comment by mvieth** [comment]
We are currently rather busy with the upcoming release 1.12.1, and I am not so familiar with the boundary estimation algorithm, so I would recommend you to look into the implementation, test other parameters for boundary estimation and normal estimation, and/or ask on the discord server if someone there has experience with the boundary estimation

**Comment by mvieth** [comment]
I had a quick look into the boundary estimation implementation, and I saw no reason why it would not work for closed objects. I suspect that the parameters you use for normal estimation and/or boundary estimation are the problem, so I am going to close this issue. However, if you do find a specific bug in the implementation of `BoundaryEstimation`, feel free to report it
