### ISSUE TITLE
[compile error]： Cannot find BUILD_gpu_* using ccmake

### ISSUE THREAD

**Issue by ymw123** [PointCloudLibrary/pcl#5087]
ubuntu20.04，gcc=9.3，Eigen, boost installed。
![图片](https://user-images.githubusercontent.com/23358682/146337572-dea693da-7526-4e11-a210-b1a0e321ff02.png)
Can anybody help me?

**Comment by mvieth** [comment]
Try to turn the advanced mode on (press "t") and configure (press "c"), then more options should show up
