### ISSUE TITLE
[bug] bug in pcl/common/eigen.hpp, computeRoots() 

### ISSUE THREAD

**Issue by EdwardDevil** [PointCloudLibrary/pcl#5089]
`Scalar c0 =      m (0, 0) * m (1, 1) * m (2, 2)
      + Scalar (2) * m (0, 1) * m (0, 2) * m (1, 2)
             - m (0, 0) * m (1, 2) * m (1, 2)
             - m (1, 1) * m (0, 2) * m (0, 2)
             - m (2, 2) * m (0, 1) * m (0, 1);`
When the determinant is expanded, the result of my calculation of c0 is 
`Scalar c0 =      m (0, 0) * m (1, 1) * m (2, 2)
      - Scalar (2) * m (0, 1) * m (0, 2) * m (1, 2)
             - m (0, 0) * m (1, 2) * m (1, 2)
             - m (1, 1) * m (0, 2) * m (0, 2)
             - m (2, 2) * m (0, 1) * m (0, 1);`
The symbol in line 76 should be a minus sign.

**Comment by mvieth** [comment]
Thank you for sharing your suspicion, but I did a quick check and the current formula (with plus sign) seems correct:
c0 is the determinant of the matrix. At the [Wikipedia page for determinant](https://en.wikipedia.org/wiki/Determinant), there is a formula for the determinant of a 3x3 matrix. `+Scalar (2) * m (0, 1) * m (0, 2) * m (1, 2)` in PCL's formula should be equivalent to `+ bfg + cdh` in Wikipedia's formula, considering the matrix is assumed to be symmetric. The remaining three products are then subtracted. So everything looks ok to me - would you check your math again and explain in detail how you end up with a minus sign there?

**Comment by EdwardDevil** [comment]
Thanks for replying to me.
I have performed many calculations, and the calculation process is as shown in the attached diagram. Maybe you got the sign wrong when you converted c0 to -c0?
If I make a mistake, I hope you point out the mistake in my calculation process, thank you :)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PointCloudLibrary/pcl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 晚上11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PointCloudLibrary/pcl] [bug] bug in pcl/common/eigen.hpp, computeRoots()  (Issue #5089)





 
Thank you for sharing your suspicion, but I did a quick check and the current formula (with plus sign) seems correct:
 c0 is the determinant of the matrix. At the Wikipedia page for determinant, there is a formula for the determinant of a 3x3 matrix. +Scalar (2) * m (0, 1) * m (0, 2) * m (1, 2) in PCL's formula should be equivalent to + bfg + cdh in Wikipedia's formula, considering the matrix is assumed to be symmetric. The remaining three products are then subtracted. So everything looks ok to me - would you check your math again and explain in detail how you end up with a minus sign there?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mvieth** [comment]
I don't see an attached diagram?
And when c0 is calculated, it is not negated yet (not -c0 yet). It is really just the determinant of the matrix

**Comment by EdwardDevil** [comment]
Yes, it is really just the determinant of the matrix.
I hope there is no error in my calculation, otherwise it will take you too much time, and then the calculation process is as follows.
![ComputeBoot](https://user-images.githubusercontent.com/96288155/146679682-7449f3e5-22ca-4418-bdf9-9d2dbfeb6769.jpg)

**Comment by mvieth** [comment]
In the first step, when you calculate `determinant(lambda*E-A)`, you only write a minus sign in front of the diagonal entries of A (m(0, 0), m(1, 1), m(2, 2)). This is not correct: You have to negate _all_ entries of A, so for example also m(0, 1), m(0, 2), and so on. This leads to the one product in c0 having the wrong sign.

**Comment by EdwardDevil** [comment]
I see, sorry to bother you for my mistake :)

**Comment by mvieth** [comment]
No problem. If someone has a legitimate concern that there is a bug in PCL, we want to know about it of course, even if it might turn out as a false alarm
