### ISSUE TITLE
3D Object Recognition based on Correspondence Grouping is unstable

### ISSUE THREAD

**Issue by MK2-3PP** [PointCloudLibrary/pcl#5090]
Hello,

for the past few weeks I've been working on a project regarding 3D object recognition. I'm quite new to point cloud processing and PCL so I've tried the tutorial for object recognition based on correspondence grouping. I am using voxel grids as keypoints, SHOT descriptors and Hough Voting as correspondence grouping method. I am working with my own point clouds and I've been playing with the parameters for quite some time now. For some of my scans the results are pretty good. 
This is the model (the point clouds have no color, for better visualization it's shown in a polygon mesh):
![Model](https://user-images.githubusercontent.com/96248184/146566256-1e58d2a7-dbeb-41f7-86be-c0e0764c1082.png)

And this is one of my scenes.
![Scan2](https://user-images.githubusercontent.com/96248184/146566491-9db8d28d-76b6-4224-9a0b-b1da5e37c6c2.png)
In the following screenshots you can see the scene cloud (green) and the found model (red overlay).
![Recognition2](https://user-images.githubusercontent.com/96248184/146566514-ad3e7857-a430-4aba-bf06-4c577189ae62.png)
![Recognition2_View2](https://user-images.githubusercontent.com/96248184/146566525-d14e414a-7f34-4144-9abe-de773be14f99.png)

I think the result is good. But with the same parameters the results can get worse for other scenes, e.g.:
![Scan1](https://user-images.githubusercontent.com/96248184/146563785-8ebf7af8-340b-444d-8b8d-3c08df15b757.png)
![Recognition1](https://user-images.githubusercontent.com/96248184/146567574-f43f8c9c-b3e9-449d-82b7-cdcd9cf132fa.png)
![Recognition1_View2](https://user-images.githubusercontent.com/96248184/146567522-a33f630d-b1e3-444a-8cda-d4985f900f65.png)

I can now change the parameters so that I receive a more precise result for that second scene. But at the same time the result will get worse for the first example. So I didn't find parameters yet that allow good object recognition for all of my scenes. I have to change the parameters for every scene individually. In addition to that the results will differ when I rotate the model or when I change the models position. So this toolchain seems quite unstable to me.

Do you have any ideas on how to improve the object recognition. Is it just that I didn't find the right parameters yet? Could I add something to my toolchain or change something? Are there other algorithms available in PCL that could provide better results? Are my point clouds not well suited for this task?

Just in case I have uploaded the two scenes and the model in the following zip-file:
[3D-Object-Recognition.zip](https://github.com/PointCloudLibrary/pcl/files/7736322/3D-Object-Recognition.zip)

Cheers :)

**Comment by larshg** [comment]
The first thing that comes to mind, is to use ICP when you have this good first estimate of position and rotation.
It could hopefully find the last transform that is required to get a better match.

**Comment by MK2-3PP** [comment]
Thanks for your comment! I will try this out.

**Comment by mvieth** [comment]
ICP is definitely worth a try. Using a voxel grid filter as the keypoint selection doesn't seem optimal, maybe one of PCL's other keypoint selection algorithms gives better results. Similarly, SHOT might not be the best descriptor for your case, but I can't recommend one that is definitely better (maybe check [this out](https://github.com/PointCloudLibrary/pcl/wiki/Overview-and-Comparison-of-Features)).
One last thing: If you always have a plane in your scene cloud (like a table where the objects are placed on), your pipeline might benefit if you first remove the plane via RANSAC.
I am going to close this because github issues are intended for bug reports etc. For questions about individual use cases, stackoverflow and the discord community chat are more appropriate

**Comment by MK2-3PP** [comment]
I've already tried out ISS, Harris and SIFT keypoint detectors but the voxel grids return the best results so far.
I'll try out some other descriptors and removing the plane via RANSAC.
Thanks a lot for your advices!
