### ISSUE TITLE
[compile error] z_errmsg already defined in pcl_surface.lib

### ISSUE THREAD

**Issue by LiuPeiqiCN** [PointCloudLibrary/pcl#5091]
**Describe the bug**

Compile error LNK2005.
```
2>zlib.lib(zutil.obj) : error LNK2005: z_errmsg already defined in pcl_surface.lib(zutil.obj)
2>zlib.lib(zutil.obj) : error LNK2005: zlibVersion already defined in pcl_surface.lib(zutil.obj)
2>zlib.lib(zutil.obj) : error LNK2005: zlibCompileFlags already defined in pcl_surface.lib(zutil.obj)
```

When I build PCL static library, I have set ZLIB:
```
          -D BUILD_surface_on_nurbs=ON `
          -D ZLIB_LIBRARY_RELEASE="${vcpkgPath}/installed/${platform}-windows-static/lib/zlib.lib" `
          -D ZLIB_LIBRARY_DEBUG="${vcpkgPath}/installed/${platform}-windows-static/debug/lib/zlibd.lib" `
          -D ZLIB_INCLUDE_DIR="${vcpkgPath}/installed/${platform}-windows-static/include" `
```

https://github.com/PointCloudLibrary/pcl/blob/8d5fa69f0a/surface/src/3rdparty/opennurbs/zutil.c

**Your Environment (please complete the following information):**

 - OS: win10
 - Compiler: MSVC
 - PCL Version: [git clone yesterday](https://github.com/PointCloudLibrary/pcl/tree/c51f7a2dfc2097e74957143e29a0310f3c1a5514)

**Comment by dg0yt** [comment]
I started to develop a patch to de-vendor zlib in https://github.com/microsoft/vcpkg/pull/30996, and I am willing to upstream it quickly.
Who is using surface on nurbs?
Would it be tested in PCL CI?

**Comment by mvieth** [comment]
> Who is using surface on nurbs?

You mean which users of PCL are using the openNURBS stuff in the surface module? Not many, would be my guess, but  honestly no idea.

> Would it be tested in PCL CI?

`BUILD_surface_on_nurbs` is enabled in PCL's Ubuntu and Windows CI, but the CI does not build static PCL libraries (and this clash seems to only appear then).

From the PCL side, my approach to solve this would be either to update the zlib source in pcl/surface/* (currently they are at version 1.2.3 which does not prefix `deflate_copyright`, `deflateSetHeader`, etc with `z_`, but newer versions of zlib do), or to only let PCL build its own zlib if `find_package(ZLIB)` does not turn up anything. I would have to check though, whether openNURBS can work with a "standard" system zlib.

**Comment by dg0yt** [comment]
No package maintainer wants vendored copies. I won't spent time on that copy.
OTOH tests of shared PCL builds with a de-vendored ZLIB should be fairly representative for static builds, too.
