### ISSUE TITLE
[SuperVoxel Clustering] How can i get the normal of voxels?

### ISSUE THREAD

**Issue by chenzongyi9708** [PointCloudLibrary/pcl#5112]
**Context**

  I am using supervoxel_clustering class to get a cloud segmentation,and I want to get normals of  voxels, I mean  geting  a PointNormal which include result of function getLabeledVoxelCloud(),with their normals. Code will be like this :
```
template <typename PointT> pcl::PointCloud<pcl::PointNormal>::Ptr
pcl::SupervoxelClustering<PointT>::getLabeledNormal() const
{
	pcl::PointCloud<pcl::PointNormal>::Ptr normal_voxel_cloud(new pcl::PointCloud<pcl::PointNormal>);
	for (typename HelperListT::const_iterator sv_itr = supervoxel_helpers_.cbegin(); sv_itr != supervoxel_helpers_.cend(); ++sv_itr)
	{
		typename pcl::PointCloud<PointXYZRGBA>::Ptr voxels;

		typename pcl::PointCloud<Normal>::Ptr normals;

		sv_itr->getVoxels(voxels);
		pcl::PointCloud<PointXYZ> voxels_xyz;
		pcl::copyPointCloud(*voxels, voxels_xyz);
		sv_itr->getNormals(normals);
		pcl::PointCloud<PointNormal> pointnormal;
		pcl::concatenateFields(voxels_xyz, *normals, pointnormal);
		*normal_voxel_cloud += pointnormal;
	}

	return normal_voxel_cloud;
}
```
but something wrong reading like:
```
 error LNK2001: unresolved external symbol "public: class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointNormal> > __cdecl pcl::SupervoxelClustering<struct pcl::PointXYZRGBA>::getLabeledNormal(void)const " (?getLabeledNormal@?$SupervoxelClustering@UPointXYZRGBA@pcl@@@pcl@@QEBA?AV?$shared_ptr@V?$PointCloud@UPointNormal@pcl@@@pcl@@@boost@@XZ)
1>G:\Code\Scene_Segmentation\x64\Release\Scene_Segmentation.exe : fatal error LNK1120: 1 unresolved externals
```
I am really new in c++,could someone help me?
**Expected behavior**
The Expected behavior is get a PointNormal which  made up by voxel's pointcloud with their normal (not only the centriods with thier normals like makeSupervoxelNormalCloud() do)

**Comment by EvanZarrella** [comment]
Hello,

The errors tells you that a class found in a library (boost) wasn't linked properly. 
Are you using vcpkg to use the PCL or are you using the windows installer ? 
For the latter, you might want to check your include path if all libraries are there. 

Best of luck

**Comment by mvieth** [comment]
Thank you @EvanZarrella , that seems like a good starting point.
