### ISSUE TITLE
[custom] after include convex_hull.h, program needs vtk dll to run.

### ISSUE THREAD

**Issue by Yourbee** [PointCloudLibrary/pcl#5114]
After #include <pcl/surface/convex_hull.h>, using pcl::ConvexHull. The compiled program needs the VTK dll to run, is this necessary, or there is something I don’t understand？

**Comment by mvieth** [comment]
- What operating system are you using? Windows?
- What version of PCL are you using, and how did you install it?
- Please copy-paste the exact error message

**Comment by larshg** [comment]
PCL surface optionally depends on VTK for a vtk smoothing algorithm.
And therefore if you link to PCL surface thats build with this, you will need the vtk libraries.
Alternatively you have to build PCL yourself without VTK support.

**Comment by Yourbee** [comment]
> PCL surface optionally depends on VTK for a vtk smoothing algorithm. And therefore if you link to PCL surface thats build with this, you will need the vtk libraries. Alternatively you have to build PCL yourself without VTK support.

Thanks, I thought vtk was just for display. *^_^*
