### ISSUE TITLE
Yet Another bug in computeRGBPairFeatures ?

### ISSUE THREAD

**Issue by darkblue346** [PointCloudLibrary/pcl#512]
(Previously reported as a comment in "bugs in computeRGBPairFeatures" but did not got any response, so registering it as a bug so that it could be appropriately tracked)

Hi, looking at this bug, I think I have discovered another bug (at the next lines :( ) : 
In pfh.cpp, line 159

// everything before was standard 4D-Darboux frame feature pair
// now, for the experimental color stuff
f5 = (colors2[0] != 0) ? static_cast (colors1[0]) / colors2[0] : 1.0f;
f6 = (colors2[1] != 0) ? static_cast (colors1[1]) / colors2[1] : 1.0f;
f7 = (colors2[2] != 0) ? static_cast (colors1[2]) / colors2[2] : 1.0f;

The supposed bug is in the next lines :
// make sure the ratios are in the [-1, 1] interval
if (f5 > 1.0f) f5 = - 1.0f / f5;
if (f6 > 1.0f) f6 = - 1.0f / f6;
if (f7 > 1.0f) f7 = - 1.0f / f7;
This process to make sure that the ratios is in [-1,1] is introducing unnecessary noise by making a discontinuity in the f5, f6, f7 values when ratios are close to 1. (which by the way is most of the time in smooth regions). 1.01 maps to -0.99 while 0.99 maps to 0.99, this is not preserving the distance (which I think they should though I could not find the original paper)

These f5, f6, f7 values are then quantized into different bins in pfhrgb.hpp (where nr_split = 5 usually) when they should have been quantified in the same
// color ratios are in [-1, 1]
00105 f_index_[4] = static_cast (floor (nr_split \* ((pfhrgb_tuple_[4] + 1.0) \* 0.5)));
00106 if (f_index_[4] < 0) f_index_[4] = 0;
00107 if (f_index_[4] >= nr_split) f_index_[4] = nr_split - 1;

a more appropriate mapping of ratios should be something like 
log( colors[1]) - log(colors[2]) with some (data learned) coefficients and capped and floored to -1,1
expression which doesn't introduce a strong discontinuity, (although logs should be optimized away by using some table based approach of the ratio map (or directy extracting the quantized ratio (but this is not ideal if we later want to improve pfhrgb histograms to "smoothed histograms" with some interpolation "a la HOG") )

(I can't pull/push requests (and test them) so could anyone make the corrections and at the same time correct the other bug I highlighted in pfhrgb normalization).

Thank you
Darkblue

**Comment by taketwo** [comment]
Closing due to lack of author response.
