### ISSUE TITLE
[NormalEstimationOMP]  does not seem to work

### ISSUE THREAD

**Issue by Philip035** [PointCloudLibrary/pcl#5124]
**Describe the bug**

pcl::NormalEstimationOMP<pcl::PointXYZ, pcl::Normal> est_normal;
	est_normal.setNumberOfThreads(6);
	est_normal.setInputCloud(input_cloud);
	est_normal.setSearchMethod(tree);
	est_normal.setKSearch(10);
	est_normal.compute(*point_normal);

There are 6cores,12threads in my PC, however the code does not seem to be accelerated by OMP. I am sure that I set the support for openmp in VS2017.

**Your Environment (please complete the following information):**

 - OS: [win10]
 - Compiler: [VS2017]
 - PCL Version [1.8.1]

**Comment by mvieth** [comment]
How did you install PCL? How do you notice that the code is not accelerated? How long does the `compute` function take? Did you check the load factor of each core with the task manager or similar?

**Comment by Philip035** [comment]
> How did you install PCL? How do you notice that the code is not accelerated? How long does the `compute` function take? Did you check the load factor of each core with the task manager or similar?

The PCL was compiled by CMake. When I run the program, the task manager showed that the usage of CPU is only around 30%, which obviously means not all cores are used. In contrast, when I run the parallel program(by openMP) written by myself, the usage of CPU is over 95%.

**Comment by mvieth** [comment]
How long does the `compute` function take?
What does the task manager show when you set the number of threads to 0, 1, 2, and 12?

**Comment by Philip035** [comment]
> 

I realize where I am wrong.
Actually, I use NormalEstimationOMP in Coarse Registration through FPFH and sac_ia.
The normal estimation and FPFH calculation is accelerated indeed, but the sac_ia is really slow.
