### ISSUE TITLE
Documentation about compiling from source doesn't mention how to run the testsuite

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#5126]
The [Compiling from source on Linux](https://pcl.readthedocs.io/projects/tutorials/en/latest/compiling_pcl_posix.html) page should explain how to run testsuite after pcl is compiled.

**Comment by mvieth** [comment]
That is explained in the tutorial after the one you linked: https://pcl.readthedocs.io/projects/tutorials/en/master/building_pcl.html#building-unit-tests

**Comment by mvieth** [comment]
@yurivict Would you say that is sufficient or do you have an idea to improve the tutorials (to make this information easier to find)?

**Comment by yurivict** [comment]
This is sufficient, thank you,
