### ISSUE TITLE
Tutorials are not accessible

### ISSUE THREAD

**Issue by cjllei** [PointCloudLibrary/pcl#5135]
Clicking on Tutorials shows that the site is inaccessible

**Comment by mvieth** [comment]
I assume you mean on https://pointclouds.org/ you click on "Tutorials" at the top?
Works fine for me (https://pcl.readthedocs.io/projects/tutorials/en/master/)
Could there be any firewall or similar blocking your access?

**Comment by mvieth** [comment]
Closing because there is no hint that the tutorials _are_ inaccessible
