### ISSUE TITLE
[compression] Decompressing/Decoding point cloud stuck forever!

### ISSUE THREAD

**Issue by bishoyroufael** [PointCloudLibrary/pcl#5138]
I am following the compression guide presented [here](https://pcl.readthedocs.io/projects/tutorials/en/latest/compression.html) to compress and decompress a point cloud. My code is as follows:
```
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/compression/octree_pointcloud_compression.h>
#include <fstream>



int
main(int argc, char* argv[] )
{
	if (argc < 2){std::cout << "Usage: " << argv[0] << " input_cloud_to_compress.pcd" << std::endl; return -1;}
	
	pcl::PointCloud<pcl::PointXYZ>::Ptr inCloud (new pcl::PointCloud<pcl::PointXYZ>);

	std::cout << "Loading cloud .." << std::endl;
	if(pcl::io::loadPCDFile<pcl::PointXYZ> (argv[1], *inCloud))
	{
		PCL_ERROR("Couldn't read the file, aborting .. \n");
		return -1;
	}


	bool showStatistics = true;

	// for a full list of profiles see: /io/include/pcl/compression/compression_profiles.h
	pcl::io::compression_Profiles_e compressionProfile = pcl::io::MED_RES_ONLINE_COMPRESSION_WITH_COLOR;

	pcl::io::OctreePointCloudCompression<pcl::PointXYZ>* PointCloudEncoder;
	pcl::io::OctreePointCloudCompression<pcl::PointXYZ>* PointCloudDecoder;


	PointCloudEncoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZ> (compressionProfile, showStatistics);
	PointCloudDecoder = new pcl::io::OctreePointCloudCompression<pcl::PointXYZ> ();

	std::stringstream compressedData;	
	pcl::PointCloud<pcl::PointXYZ>::Ptr outCloud (new pcl::PointCloud<pcl::PointXYZ> ());
	PointCloudEncoder->encodePointCloud(inCloud, compressedData);

	std::ofstream fileCompressedData ("compressed_data.txt");
	fileCompressedData << compressedData.rdbuf();
	// fileCompressedData.close();

	std::cout << "Decoding compressed data" << std::endl;
	PointCloudDecoder->decodePointCloud(compressedData, outCloud); 
	std::cout << "Decoding done, saving .." << std::endl;
	pcl::io::savePCDFileASCII ("decompressed_cloud.pcd", *outCloud);


	delete(PointCloudEncoder);
	delete(PointCloudDecoder);



	return 0;
}
```

This takes a filename of a point cloud and compress and decompress it and save the result as pcd. compression works, saving the compression on disk works, decoding doesn't work and hangs forever for no reason, Any idea what could be the problem?
Example of the output in the terminal:
```
Loading cloud ..
*** POINTCLOUD ENCODING ***
Frame ID: 1
Encoding Frame: Intra frame
Number of encoded points: 122627
XYZ compression percentage: 15.534507%
XYZ bytes per point: 1.864141 bytes
Color compression percentage: 0.000000%
Color bytes per point: 0.000000 bytes
Size of uncompressed point cloud: 1916.046875 kBytes
Size of compressed point cloud: 223.236328 kBytes
Total bytes per point: 1.864141 bytes
Total compression percentage: 11.650881%
Compression ratio: 8.583042

Decoding compressed data

```

I have tested it on both Ubuntu and Windows with the latest PCL version and getting the same result.

**Comment by mvieth** [comment]
Just to be sure: which PCL version exactly are you using? And how did you install it?

**Comment by b15h0y** [comment]
1.12.1 , installed using the all in one installer for windows. on ubuntu using `sudo apt-get install libpcl-dev`

**Comment by larshg** [comment]
Can you share a point cloud that does this or doesnt it work on any cloud?

**Comment by b15h0y** [comment]
it doesn't work on any cloud, I don't think it is cloud related issue, can anyone test the code above and share the output with the respective version of pcl?

**Comment by mvieth** [comment]
The problem is that `compressedData` does not contain the data any more after you write it to the file. If you remove
```c++
std::ofstream fileCompressedData ("compressed_data.txt");
fileCompressedData << compressedData.rdbuf();
```
everything works. Alternatively you could try to decode the data from the file.

I thought about changing `decodePointCloud` so that it returns immediately if the given stream does not contain any data, but on the other hand, it might be desired for some streams (network streams?) that reading is blocking and that the function only returns when it successfully decoded a cloud

**Comment by b15h0y** [comment]
Maybe a `PCL_WARN("Data is empty!")` could be a quick solution without returning. At least the user can get a feeling of what is happening 😉

**Comment by mvieth** [comment]
@b15h0y Sounds good. Would you be interested in opening a pull request? FYI: the "blocking" happens in [syncToHeader](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/compression/impl/octree_pointcloud_compression.hpp#L416)

**Comment by mvieth** [comment]
Warning added to documentation in pull request https://github.com/PointCloudLibrary/pcl/pull/5338
