### ISSUE TITLE
MSVC specific syntax should not be used for Clang-CL

### ISSUE THREAD

**Issue by yuanchen-zhu** [PointCloudLibrary/pcl#5140]
The following [line](https://github.com/PointCloudLibrary/pcl/blob/c034495dd8113f971f135b2fbbfb4f9b7c430312/common/include/pcl/for_each_type.h#L77) forces MSVC legacy syntax to be used when `_WIN32` and `_MSC_VER` are defined. When Clang-cl is used as the compiler, both macro are defined so the legacy syntax is used, but will trigger a compilation error:
```
<.....>\vcpkg_installed\x64-windows\include\pcl\for_each_type.h(80,38): error: use 'template' keyword to treat 'operator ()' as a dependent template name
      boost::mpl::aux::unwrap (f, 0).operator()<arg> ();
                                     ^
```

In our setup, we're using the vcpkg/msvc built PCL but depend on clang-cl to build our own code-base, so the above compilation error gets triggered when a pcl header gets included.

I propose to apply the following diff to fix this issue. 
```
--- a/common/include/pcl/for_each_type.h
+++ b/common/include/pcl/for_each_type.h
@@ -76,7 +76,7 @@ namespace pcl
     {
       using arg = typename boost::mpl::deref<Iterator>::type;
 
-#if (defined _WIN32 && defined _MSC_VER)
+#if (defined _WIN32 && defined _MSC_VER && !defined(__clang__))
       boost::mpl::aux::unwrap (f, 0).operator()<arg> ();
 #else
       boost::mpl::aux::unwrap (f, 0).template operator()<arg> ();
```

Moreover, more modern versions of MSVC might also balk at the legacy syntax (omitting the template keyword for dependent template invocation) when in non permissive mode, though I haven't verified that.

**Comment by kunaltyagi** [comment]
Please create a PR from this patch :)

**Comment by KartikShrivastava** [comment]
Hi, I'm interested in gsoc2022 and want to know if I can work on this issue?

**Comment by mvieth** [comment]
> Hi, I'm interested in gsoc2022 and want to know if I can work on this issue?

Since the original creator of this issue did not open a pull request so far, I would say yes, please go ahead

**Comment by KartikShrivastava** [comment]
Hi, can you please review the patch #5194. TBH I haven't tested whether the error is gone or not, because Visual Studio was adding extra 3GB load of clang compiler to my system. But please let me know if that is strictly required I'll do the same.

**Comment by yuanchen-zhu** [comment]
Yes it works for my usage case. Thanks!
