### ISSUE TITLE
/usr/local/lib/libvtkFiltersCore-8.2.so.1: 无法添加符号: DSO missing from command line

### ISSUE THREAD

**Issue by carrie-smy** [PointCloudLibrary/pcl#5142]
when i make the pcl
it happened:
/usr/bin/ld: CMakeFiles/pcl_obj2pcd.dir/obj2pcd.cpp.o: undefined reference to symbol '_ZN18vtkPolyDataNormals3NewEv'
/usr/local/lib/libvtkFiltersCore-8.2.so.1: 无法添加符号: DSO missing from command line
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_obj2pcd.dir/build.make:122: recipe for target 'bin/pcl_obj2pcd' failed
make[2]: *** [bin/pcl_obj2pcd] Error 1
CMakeFiles/Makefile2:4659: recipe for target 'tools/CMakeFiles/pcl_obj2pcd.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_obj2pcd.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Your Environment (please complete the following information):**

 - OS: [ Ubuntu 18.04]

 - PCL Version [1.9.0]

**Comment by tkircher** [comment]
I just had the same exact issue. VTK-8.2, pcl-1.12.1, and vtk2pcd is also affected.

`vtkSmartPointer<vtkPolyDataNormals> ng = vtkSmartPointer<vtkPolyDataNormals>::New ();`

If you don't need these two tools to work, but need the rest of PCL to build, you can just replace this line with

`vtkSmartPointer<vtkPolyDataNormals> ng;`

**Comment by mvieth** [comment]
@carrie-smy Is there a reason why you use VTK 8.2 instead of one of the VTK versions that come with apt (either VTK 6.3 or VTK 7.1)? If you use one of those, you should be able to build PCL without modifications.
We can try to make the master branch (and future versions) compatible with VTK 8, but for PCL 1.9.0, there is nothing we can do (you can make local changes as @tkircher suggested, of course)

**Comment by tkircher** [comment]
@mvieth There are several projects out there which require features found in VTK 8.2 as well as the PCL library but can not build with VTK 9. Good times. ;)

**Comment by carrie-smy** [comment]
> 
I'm a novice at these things. could you please tell  me where can I replace these lines? in which file?

**Comment by tkircher** [comment]
@carrie-smy I just built pcl-1.12.0 and it does not have the build issue that pcl-1.12.1 has. I recommend using that instead.

**Comment by themightyoarfish** [comment]
Related issue getting fixed here https://github.com/PointCloudLibrary/pcl/pull/5145
