### ISSUE TITLE
range_image_border_extraction.cpp (Segmentation fault (core dumped)) Error

### ISSUE THREAD

**Issue by gitttable** [PointCloudLibrary/pcl#5143]
Hey all, I have a truble with Segmentation fault.
I use Intel Realsense L515 Lidar.
When I tried GDB for debugging, Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7456303 in pcl::RangeImage::asinLookUp (value=<optimized out>)
     at /home/kjh/pcl/common/include/pcl/range_image/impl/range_image.hpp:58
58 static_cast<float> (lookup_table_size-1) / 2.0f)]);
(gdb)
an error will appear.
There is no problem with the .pcd file, and the same code works when I run the Jetson nano.
When a segment error occurs, it is usually said that it occurs when an unreferenceable memory is accessed, but I have no idea where it went wrong. I tried deleting and reinstalling the pcl library just in case, but to no avail. 
Help me plz....

**Comment by mvieth** [comment]
What operating system are you using? Which PCL version are you using and how did you install it? Please also provide the .pcd file you are using

**Comment by gitttable** [comment]
Using Linux 18.04 (PC) , pcl v1.8 [https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources/range_image_border_extraction](url)

**Comment by mvieth** [comment]
@gitttable I mean the **PCD** file you pass to the executable (the one that contains the point cloud). Above you said you are using a .pcd file? Please provide it so I can reproduce the error

**Comment by gitttable** [comment]
[L515Mark1.zip](https://github.com/PointCloudLibrary/pcl/files/7941470/L515Mark1.zip)

**Comment by gitttable** [comment]
Thank you for answer.
I'm curious, can the cpu be different depending on the difference between amd and arm even with the same code?
My computer is an intel chipset, Jetson nano is an arm chipset, Jetson nano works with the same code and same .pcd file.
Is it simply a bug on my computer?

**Comment by mvieth** [comment]
Yes, could be possible that there is a difference in the arithmetic, especially related to NaN, so that it leads to a segfault on your Intel CPU, but not on your Jetson nano

**Comment by gitttable** [comment]
Thank you for answer.
I'll try hard to find a way.
:)

**Comment by gitttable** [comment]
@mvieth I have a question, how do I delete the (0,0,0) point mentioned above?

**Comment by gitttable** [comment]
@larshg Oh, Thanks you very much. :)
