### ISSUE TITLE
can I just compile several modules？

### ISSUE THREAD

**Issue by TianchaoHuo** [PointCloudLibrary/pcl#5144]
Hello, mates:

can I just compile several modules like "common" "filters" "segmentation" "kdtree"?

**Comment by mvieth** [comment]
Sure, check out [the tutorials](https://pcl.readthedocs.io/projects/tutorials/en/master/), especially [this tutorial](https://pcl.readthedocs.io/projects/tutorials/en/master/building_pcl.html)
