### ISSUE TITLE
How to use GPU API to calculate normal vector

### ISSUE THREAD

**Issue by tangbinbinyes** [PointCloudLibrary/pcl#5146]
Hello, thank you very much for providing such an excellent project as PCL. In the process of using it, I found that it is very time-consuming to calculate the normal vector with the CPU, so that I could not wait for the result after waiting for five minutes. The hardware I used is Photoneo's high-precision camera, so the point cloud is very dense. In order to ensure the accuracy, I have to avoid downsampling, so I want to use the NVIDIA 1660Ti graphics card to calculate the normal vector. Maybe it will be much faster. I don't know how to call the API. I can't find any relevant information, the following is my code.
![image](https://user-images.githubusercontent.com/41097044/151279433-a43b7add-9a14-4847-b7d7-7afccc924f74.png)
I hope to get everyone's help, thank you very much.

**Comment by mvieth** [comment]
Have a look at [test_normals.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/gpu/features/test/test_normals.cpp).
Also, if you haven't done that yet, try [IntegralImageNormalEstimation](https://pcl.readthedocs.io/projects/tutorials/en/master/normal_estimation_using_integral_images.html)

**Comment by larshg** [comment]
Closing as it seems you got it working and now need to visualise it as requested in the other issue.
