### ISSUE TITLE
cmake configuration error!

### ISSUE THREAD

**Issue by Shibaditya99** [PointCloudLibrary/pcl#5150]
Just downloaded my pcl-pcl-1.12.1.tar.gz, extracted. after creating the build directory used a command `cmake -DCMAKE_BUILD_TYPE=Release ..`  but it's showing file missing errors like `No package 'metslib' found` `No package 'glut' found` etc.. the error is below:

`inxee@inxee:~/LiDAR/pcl-pcl-1.12.1/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE ClangFormat_VERSION) (Required is at least version "10")
-- Using CPU native flags for SSE optimization: -msse4.2 -mfpmath=sse -march=native
-- Found OpenMP, spec date 201511
-- Eigen found (include: /usr/include/eigen3, version: 3.3.7)
-- FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Could NOT find Qhull (missing: QHULL_LIBRARY QHULL_INCLUDE_DIR) 
CMake Warning at cmake/pcl_find_vtk.cmake:25 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:375 (include)

-- Qt is not found.
-- Checking for module 'glut'
--   No package 'glut' found
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_date_time"
  (requested version 1.71.0) with any of the following names:

    boost_date_timeConfig.cmake
    boost_date_time-config.cmake

  Add the installation prefix of "boost_date_time" to CMAKE_PREFIX_PATH or
  set "boost_date_time_DIR" to a directory containing one of the above files.
  If "boost_date_time" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/share/cmake-3.22/Modules/FindBoost.cmake:594 (find_package)
  cmake/pcl_find_boost.cmake:29 (find_package)
  CMakeLists.txt:399 (include)

-- Configuring incomplete, errors occurred!
See also "/home/inxee/LiDAR/pcl-pcl-1.12.1/build/CMakeFiles/CMakeOutput.log".
`

**Comment by mvieth** [comment]
Have a look [here](https://github.com/PointCloudLibrary/pcl/blob/master/.dev/docker/env/Dockerfile) to see which apt packages you need to install (not all are mandatory)

**Comment by Shibaditya99** [comment]
@mvieth is there any way to install all of them at once?

**Comment by mvieth** [comment]
> @mvieth is there any way to install all of them at once?

Yes, just like in the Dockerfile to which I posted the link??
