### ISSUE TITLE
pcl1.12.1 allinone  pcl::ConditionalRemoval and pcl::ConvexHull crash at eigen3\Eigen\src\Core\util\Memory.h aligned_free()

### ISSUE THREAD

**Issue by YuMeiWangddup** [PointCloudLibrary/pcl#5151]
when I use the  PCL-1.12.1-AllInOne-msvc2019-win64 and the  PCL-1.12.0-AllInOne-msvc2019-win64,both happened crash at eigen3\Eigen\src\Core\util\Memory.h aligned_free() free(ptr);
![image](https://user-images.githubusercontent.com/51939446/151684756-0980b168-1538-40b1-a08e-4b4e01f2a7b5.png)

So far,I've found that pcl::ConditionalRemoval , pcl::ConvexHull and pcl::StatisticalOutlierRemoval ,have the same problem.
One step closer,one of my function as follow.
if I call this function ,it works as it should .But when  surface_hull goes out of scope,I'm getting an crash at eigen3\Eigen\src\Core\util\Memory.h aligned_free()  free(ptr);

void _CalConvexHull(vtkSmartPointer<vtkPolyData> source, vtkSmartPointer<vtkPolyData> Convexout)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::vtkPolyDataToPointCloud(source, *cloud);

	pcl::ConvexHull<pcl::PointXYZ> hull;
	hull.setInputCloud(cloud);
	hull.setDimension(3);                   
	//hull.setComputeAreaVolume(true);

	pcl::PointCloud<pcl::PointXYZ>::Ptr surface_hull(new pcl::PointCloud<pcl::PointXYZ>);
	hull.reconstruct(*surface_hull);

	pcl::io::pointCloudTovtkPolyData(*surface_hull,Convexout);

#ifdef VIEW
	boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer);

	pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> sourceHandle(cloud, 255, 255, 0);
	viewer->addPointCloud(cloud, sourceHandle,"cloud");
	viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "cloud");

	pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ>  handler_tempt(surface_hull, 255, 0, 0);
	viewer->addPointCloud(surface_hull, handler_tempt, "Hull");
	viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "Hull");

	viewer->setBackgroundColor(255, 255, 255);
	while (!viewer->wasStopped())
	{
		viewer->spinOnce(100);
	}
#endif // VIEW
	//cloud->~PointCloud();
	//surface_hull->~PointCloud();
}

Additional,Icall cloud->~PointCloud();works well.But I call surface_hull->~PointCloud();will happen crash

**Comment by YuMeiWangddup** [comment]
i solved this problem by set avx option in my visual studio 2019 ,see https://stackoverflow.com/questions/20169064/does-archavx-enable-avx2

**Comment by unclesammy** [comment]
wow,how did you think of that.You really save my days.
