### ISSUE TITLE
[compile error] cannot build pcl 1.12.1 with cuda 11.6

### ISSUE THREAD

**Issue by keremcc** [PointCloudLibrary/pcl#5154]
Hi All,

I have difficulty building PCL with Cuda support. Is there a way to trace errors? Any clue is appreciated. 

![Screenshot from 2022-02-02 12-55-27](https://user-images.githubusercontent.com/47608531/152233311-fa68838f-2310-4ae6-88b1-b10b2d7c2d24.png)
![Screenshot from 2022-02-02 15-37-34](https://user-images.githubusercontent.com/47608531/152234542-97fa6575-ea04-4c93-8da8-006e9e933132.png)

ubuntu 18.04
g++ 7.5.0
cuda 11.6

**Comment by larshg** [comment]
Seems to be related to this https://github.com/NVIDIA/thrust/issues/1601.
