### ISSUE TITLE
[compile error] ply_io.h savePLYFile doesn't compile, missing pcl/common/io.h

### ISSUE THREAD

**Issue by yoavmil** [PointCloudLibrary/pcl#5157]
At ply_io.h, at `savePLYFile` there is a `copyPointCloud` call, which is from `pcl/common/io.h`, which isn't included.
I'm using vcpkg and visual studio 19.
```
pcl:x64-windows                                    1.12.0#2         Point Cloud Library (PCL) is open source library...
pcl[visualization]:x64-windows                                      Build visualization
```

**Possible Solution**
Add the include.

**Comment by mvieth** [comment]
Thank you for reporting this! Would you be interested in opening a pull request? If you do, please add `// for copyPointCloud` as an explanation behind the include

**Comment by yoavmil** [comment]
@mvieth I'll try
