### ISSUE TITLE
[compile error] boost-accumulators missing

### ISSUE THREAD

**Issue by yoavmil** [PointCloudLibrary/pcl#5167]
**Compilation error**
when trying to compile pcl from source, I get:
`Cannot open include file: 'boost/accumulators/accumulators.hpp': No such file or directory`

I'm using vcpkg, and I figure that `pcl` requires `boost` but not `boost-accumulators`. need to add it to the cmake I guess.

**To Reproduce**
make a clean repo of vcpkg and pcl and try to compile.

**Your Environment (please complete the following information):**
- Windows
- vs2019
- vcpkg - latest
- pcl - latest, compiled from source

**Comment by yoavmil** [comment]
also when building global tests, gtest is missing

**Comment by larshg** [comment]
@yoavmil which file require this boost header? I can't find it when I search for this include?

I'm not sure if vcpkg has added gtest as a (optionel)dependency, but its an issue at vcpkg and not PCL.
You can however just install gtest manually, if you compile PCL from sources.

**Comment by yoavmil** [comment]
I don't think it's a vcpkg error, because I was trying to compile pcl myself.
It's a cmake problem, meening it needs something like,
```cmake
if COMPILE_TESTS
find_package(GTest CONFIG REQUIRED)
endif
```

**Comment by larshg** [comment]
> I don't think it's a vcpkg error, because I was trying to compile pcl myself. It's a cmake problem, meening it needs something like,
> 
> ```cmake
> if COMPILE_TESTS
> find_package(GTest CONFIG REQUIRED)
> endif
> ```

I also use VCPKG for dependencies and have no problem generating targets for the test.
There is already something similar:
https://github.com/PointCloudLibrary/pcl/blob/10235c9c1ad47989bdcfebe47f4a369871357e2a/test/CMakeLists.txt#L14

**Comment by yoavmil** [comment]
well then, let's move on. closing.

**Comment by larshg** [comment]
> well then, let's move on. closing.

The missing boost dependency still be a problem. I havent verified it.
