### ISSUE TITLE
About save png from pcd

### ISSUE THREAD

**Issue by Corezcy** [PointCloudLibrary/pcl#5170]
https://github.com/PointCloudLibrary/pcl/blob/e1664a4ba63107b2c5ca10bc4137c5a8f73ae0b5/io/include/pcl/io/impl/point_cloud_image_extractors.hpp#L53

I want to consult why we should check the `height` element, we set most of the pcd file height 1... 
A little confused.

Appreciate for your answer.

**Comment by mvieth** [comment]
The class is intended for organized point clouds (see here: https://pointclouds.org/documentation/classpcl_1_1io_1_1_point_cloud_image_extractor.html).
For information about organized/unorganized point clouds, see here: https://pcl.readthedocs.io/projects/tutorials/en/master/basic_structures.html

For further questions, please use [discord or stackoverflow](https://github.com/PointCloudLibrary/pcl#community). The GitHub issues are for bugs and compile errors.
