### ISSUE TITLE
[compile error] i got a compilation failure C3052 at  common\src\fft\kiss_fft.c(269,14) when build pcl-1.12.1 on windows with msvc 17.0

### ISSUE THREAD

**Issue by GrayDust404** [PointCloudLibrary/pcl#5172]
**Describe the error**

I got a compilation failure C3052 at common\src\fft\kiss_fft.c(269,14) when build pcl-1.12.1 on windows with msvc

**To Reproduce**

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**
I checked the code, as microsoft said in this [link](https://docs.microsoft.com/fi-fi/cpp/error-messages/compiler-errors-2/compiler-error-c3052?view=msvc-160), the vatiable k must be explicitly specified as either shared or private

**Your Environment (please complete the following information):**

 - OS: windows server 2019
 - Compiler: msvc 17.0
 - PCL Version 1.12.1
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No
 - List and Version of dependencies used
 - Compilation flags are used:
   - BUILD_TESTING=OFF
   - BUILD_DOCUMENTATION=OFF
   - BUILD_EXAMPLES=OFF
   - BUILD_features=OFF
   - BUILD_keypoints=OFF
   - BUILD_outofcore=OFF
   - BUILD_stereo=OFF
   - BUILD_ml=OFF
   - BUILD_2d=OFF
   - BUILD_tracking=OFF
   - BUILD_registration=OFF
   - BUILD_segmentation=OFF
   - BUILD_surface=OFF
   - PCL_ENABLE_SSE=OFF
   - BUILD_SHARED_LIBS=ON
   - BUILD_visualization=OFF

**Possible Solution**

Can i disable some module to work around it?

**Additional context**

**Comment by larshg** [comment]
Thanks for reporting.
Its already fixed in this #5155.
If you get PCL from git, just pull master.
