### ISSUE TITLE
pcl/segmentation/sac_segmentation.h

### ISSUE THREAD

**Issue by xbx1** [PointCloudLibrary/pcl#5173]
Win 11 Pro
PCL 1.12.1
Visual Studio

I want to segment a plane within point cloud using SACsegmentation module and get some unexpected result. Though I solve this problem then, I want to know the reason causing the problem. I want to segment the ground, but the code returns the gross one as showed with red lines.
![image](https://user-images.githubusercontent.com/53611884/154783403-bbce098b-ce6f-4f23-89b8-39b7f5967fe7.png)
here is the code and pcd file.
[compress.zip](https://github.com/PointCloudLibrary/pcl/files/8101342/compress.zip)
And after sampling down the point cloud with UniformSample module, it generates the right result. Is it possible that the size of point cloud has some influence

**Comment by xbx1** [comment]
Win 11 Pro
PCL 1.12.1
Visual Studio

**Comment by mvieth** [comment]
You can use `pcl::console::setVerbosityLevel(pcl::console::L_VERBOSE);` to get more insight into the segmentation process, and spot possible errors. It might be that the distance threshold is too low, or that you need more iterations. The larger the cloud, the more accurate the segmentation result usually is.
For such application specific questions, please use Stackoverflow or the discord server in the future. The GitHub issues are for bugs and compile errors.
