### ISSUE TITLE
[test/visualization] Visualization test does not compile

### ISSUE THREAD

**Issue by Yaraslaut** [PointCloudLibrary/pcl#5188]
**Describe the bug**

test_visualization.cpp does not compile

**Screenshots/Code snippets**

```
pcl/test/visualization/test_visualization.cpp:117:9: error: expected unqualified-id
  float M_PIf = static_cast<float> (M_PI);
        ^
/usr/include/math.h:1168:17: note: expanded from macro 'M_PIf'
# define M_PIf          3.14159265358979323846f /* pi */
                        ^
1 error generated.
```

**Your Environment (please complete the following information):**

 - OS: [ Linux Arco 5.16.11-arch1-1]
 - Compiler: [GCC 11.2.0]
 - PCL Version [HEAD (e05fb583e1689c847b6962597aa1a901a3652f61) ]

**Possible Solution**
Change variable name or make cast in function call directly

**Comment by mvieth** [comment]
Thanks for reporting. Would you be interested in creating a pull request to fix this?

**Comment by Yaraslaut** [comment]
@mvieth  Yes, sure
