### ISSUE TITLE
Missing vtklOGeometry-9.1.dll

### ISSUE THREAD

**Issue by CapitanMarti** [PointCloudLibrary/pcl#5193]
Hello, I have just downloaded the AllInOne package (PCL-1.12.1-AllInOne-msvc2019-win64.exe, from https://github.com/PointCloudLibrary/pcl/releases); I have compiled my test program (it just call loadPCDFile to read a pcd file);  when I try to execute the code it cannot find dll file vtklOGeometry-9.1.dll. 
Indeed I have verified inside  PCL 1.12.1\3rdParty\VTK\bin folder and such dll is missing it is missing; more in general it is not present in the whole package.
I have downloaded the package twice (and also installed it twice), but the result is the same.

OS: Windows 10 Home
IDE: Microsoft Visual Studio 2019
Build configuration: x64 - Debug

**Comment by CapitanMarti** [comment]
Just an update: I experience the same problem when I try to execute any of the executable inside PCL 1.12.1\bin.
Four dll seem to be missing: 
- vktlOGeometry-9.1.dll, 
- vtklOPLY-9.1.dll
- vtklOImage-9.1.dll
- OpenNI2.dll

**Comment by UnaNancyOwen** [comment]
vtkIOGeometry-9.1.dll is exists in the PCL 1.12.1/3rdParty/VTK/bin directory.

![2022-03-01_23h12_04](https://user-images.githubusercontent.com/816705/156184725-27cc3610-89d4-41be-bd47-b39bc47cb8b5.png)

In your system, It is not setting necessary path.
Please set the environment variable to following path. And, re-boot your system.

| variable     | path |
|:------------:|:------|
| OPENNI2_REDIST64 | C:\Program Files\OpenNI2\Redist\ | 
| PCL_ROOT | C:\Program Files\PCL 1.12.1 |
| Path           | %PCL_ROOT%\bin<br>%PCL_ROOT%\3rdParty\VTK\bin<br>%OPENNI2_REDIST64%  |

There have been many similar questions in the past.
It is recommended that you search for problems and forums before posting.

**Comment by CapitanMarti** [comment]
Thanks for your answer. The problem wasn't a missing folder in the path; indeed some vtk dll's were actually missing in my folder.
I've seen that the reason was low space on my disk, and something went wrong during installation; after cleaning the disk I did again the installation and all vtk dll automagically appeared!
But than you very very much for such a quick answer.

**Comment by UnaNancyOwen** [comment]
Oh, that's a case I've never heard of before.
Thank you for sharing the cause and the solution.
It is helpful for everyone who has the same problem as you.
