### ISSUE TITLE
[pcl_io]  'boost::filesystem::filesystem_error'   what():  boost::filesystem::status: Function not implemented: "XXXX.pcd"

### ISSUE THREAD

**Issue by missechogao** [PointCloudLibrary/pcl#5197]
I have tried many times to reinstall boost(boost version is 1.76.0) and pcl(1.12.0) ,but the error still here .
When I type pcd_viewer at ubuntu shell,the error occured.

`terminate called after throwing an instance of 'boost::filesystem::filesystem_error' what():  boost::filesystem::status: Function not implemented: "kf_output.pcd"`

But I have wrote a small program to test boost like this 
```
#define BOOST_NO_CXX11_SCOPED_ENUMS  
#include <boost/filesystem.hpp>  
#undef BOOST_NO_CXX11_SCOPED_ENUMS  
#include <iostream>  
int main(int argc,char** argv)  
{  
    if (boost::filesystem::exists("1.pcd"))  
    {  
        std::cout<<"file exists "<<std::endl;  
    }  
    else  
    {  
        std::cout<<"file not exist!!!!!!!!!"<<std::endl;  
    }  
    return 0;  
}
```

the output 
`
file not exist!!!!!!!!!
`

 - OS: [Ubuntu 18.04]
 - Compiler: [GCC 7.5.0]
 - PCL Version [1.12.0]
 -Boost Version[1.76.0] 
![2022-03-03 14-04-26屏幕截图](https://user-images.githubusercontent.com/24429670/156507914-e63c6797-2c2a-4e83-9dcd-8930738ef4dc.png)

**Comment by mvieth** [comment]
So you just write `pcd_viewer` and then the path and name of your .pcd file? Are you sure path and name are correct and the file really exists?
Can you run the same command, but with `valgrind` in front of it?
I am not sure what you intend to do with the program you wrote. You are checking the existence of a file with name "1.pcd", in the same directory as the program. How does that help?
Is it possible that there are non-ASCII characters in the path or name of the file? I don't know how well Boost handles those.

**Comment by missechogao** [comment]
> So you just write `pcd_viewer` and then the path and name of your .pcd file? Are you sure path and name are correct and the file really exists? Can you run the same command, but with `valgrind` in front of it? I am not sure what you intend to do with the program you wrote. You are checking the existence of a file with name "1.pcd", in the same directory as the program. How does that help? Is it possible that there are non-ASCII characters in the path or name of the file? I don't know how well Boost handles those.

I solved the problem with uninstall boost1.76 and installed boost 1.65.But I don't know the why.

I wrote the program to sure the boost work rightly,I have tracked the pcl::io::loadpcdfile,always corrupted at boost::filesystem::exists().But the small program never corrupt.

**Comment by mvieth** [comment]
Closing this issue, since it appears to be solved and since the problem seems to come from Boost, not PCL
