### ISSUE TITLE
[segmentation] An error occurred when I used "sac.segment(*inlier,*coefficients);"

### ISSUE THREAD

**Issue by Duke-Rodriguez-Rudolph** [PointCloudLibrary/pcl#5198]
**Describe the bug**

An error occurred when I used "sac.segment(*inlier,*coefficients);". I kept debugging, and then found that there was a problem when the code ran to "if (! Sac_- > computemodel (0))" in "sac_segmentation.hpp". I checked the stack and found that it was finally related to eigen.

**Context**

I am a newer in pcl and I try to run a example of segmentation.

**Screenshots/Code snippets**
Here are the code in my main.cpp.
    SACSegmentation<PointXYZ> sac;
    PointIndices::Ptr inlier(new PointIndices);
    ModelCoefficients::Ptr coefficients(new ModelCoefficients);
    PointCloud<PointXYZ>::Ptr sac_cloud(new PointCloud<PointXYZ>);
    sac.setOptimizeCoefficients(true);
    sac.setModelType(SACMODEL_PLANE);
    sac.setMethodType(SAC_RANSAC);
    sac.setMaxIterations(100);
    sac.setDistanceThreshold(0.02);
    sac.setInputCloud(sor_cloud);
    sac.segment(*inlier,*coefficients);

Here are the code in sac_segmentation.hpp.
 if (!initSACModel (model_type_))
  {
    PCL_ERROR ("[pcl::%s::segment] Error initializing the SAC model!\n", getClassName ().c_str ());
    deinitCompute ();
    inliers.indices.clear (); model_coefficients.values.clear ();
    return;
  }
  initSAC (method_type_);

  if (!sac_->computeModel (0))   //here is the fault.
  {
    PCL_ERROR ("[pcl::%s::segment] Error segmenting the model! No solution found.\n", getClassName ().c_str ());
    deinitCompute ();
    inliers.indices.clear (); model_coefficients.values.clear ();
    return;
  }

Here are the code in eigen:
/** \internal Frees memory allocated with handmade_aligned_malloc */
inline void handmade_aligned_free(void *ptr)
{
  if (ptr) std::free(*(reinterpret_cast<void**>(ptr) - 1));
}

**Your Environment (please complete the following information):**
Ubuntu 18.04
cmake
pcl-1.8
eigen3.37

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**
I am looking forward to your early reply

**Comment by mvieth** [comment]
How did you install PCL?
How do you compile your own program (e.g. main.cpp)? If you use CMake, please post your CMakeLists.txt

**Comment by Duke-Rodriguez-Rudolph** [comment]
Thank you for your reply. I have solved this problem by installing pcl-1.12.

**Comment by mvieth** [comment]
> Thank you for your reply. I have solved this problem by installing pcl-1.12.

Great, I will close this issue then.
