### ISSUE TITLE
Implementation of a feature based registration for point cloud based on PCL library

### ISSUE THREAD

**Issue by ChaoyiZh** [PointCloudLibrary/pcl#5207]
I am trying to make a cpp program focusing on the feature based registration for point cloud based on PCL. As we know, PCL provides a lot functions which can be used for each steps. For example, we can extract narf, harries, sift and some other kind of keypoints by using different functions. However there are many functions I cannot find some materials (PCL official tutorial and examples)helpful for my implementation. Here is the list that I have problem and I appreciate anyone who can provide me some suggestions for that. Here is the list of all the functions that I have problem of implementation and the corresponding reason for them. Descriptors:

pcl::NarfDescriptor --- the output datatype is Narf36, which is not a valid type to be fed into the correspondence.

pcl::MomentInvariantsEstimation --don't know the datatype for the output

pcl::RSDEstimation--don't know the datatype for the output

pcl::IntensitySpinEstimation--don't know the datatype for the output

pcl::RIFTEstimation --the output is histogram which cannot be used to find the correspondence

pcl::CRHEstimation --the output is histogram which cannot be used to find the correspondence

pcl::GRSDEstimation --don't know the datatype for the output

pcl::GFPFHEstimation--don't know the datatype for the output

Correspondence estimation:

pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >--done with bug core dumped possible reason is converting xyzrgb to pointnormal

Correspondence rejection:

pcl::registration::CorrespondenceRejectorFeatures::FeatureContainer< FeatureT > ** --no resource to follow

**Comment by mvieth** [comment]
> pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >--done with bug core dumped possible reason is converting xyzrgb to pointnormal

For this one, I suggest you open a separate issue, with a reproducible code example.

For the cases where you don't know the output datatype, you can look into the .cpp files (e.g. grsd.cpp, intensity_spin.cpp, ...) where the classes are instantiated. If you are interested in improving the documentation of those classes, you are welcome to do so by opening a pull request.

**Comment by mvieth** [comment]
@ChaoyiZh What's the status here? Did my previous comment help you? Do you still get the "core dumped" error? If we don't get a response from you, we might close this issue soon
