### ISSUE TITLE
[compile error] Using filters module: ‘optional’ in namespace ‘boost’ does not name a template type

### ISSUE THREAD

**Issue by dongchenyu163** [PointCloudLibrary/pcl#5209]
**Describe the error**
- Description
    - I want to use `FastBilateralFilter` to do some stuff, but even the minimum program can not be compiled. Did I missing something?
    - I check the commit about the `convolution_3d.h:` file, the PR  #4289 removed the include header `boost.h` and the defination of `boost::optional` in the file `boost/optional.hpp` is also missing.

- Error information
Main error is: `‘optional’ in namespace ‘boost’ does not name a template type; did you mean ‘conditional’?`
Located in `pcl/filters/convolution_3d.h:160:16`.

- Full error message
```
[main] Building folder: PCL_Pure_Test 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/cookteam/Workspace/CPP_Program/PCL_Pure_Test/build --config Debug --target all -j 26 --
[build] Scanning dependencies of target MyApp
[build] [ 50%] Building CXX object CMakeFiles/MyApp.dir/main.cpp.o
[build] In file included from /home/cookteam/Workspace/CPP_Program/PCL_Pure_Test/main.cpp:3:
[build] /usr/local/include/pcl-1.12/pcl/filters/convolution_3d.h:160:16: error: ‘optional’ in namespace ‘boost’ does not name a template type; did you mean ‘conditional’?
[build]   160 |         boost::optional<float> sigma_coefficient_;
[build]       |                ^~~~~~~~
[build]       |                conditional
[build] /usr/local/include/pcl-1.12/pcl/filters/convolution_3d.h: In member function ‘void pcl::filters::GaussianKernel<PointInT, PointOutT>::setThresholdRelativeToSigma(float)’:
[build] /usr/local/include/pcl-1.12/pcl/filters/convolution_3d.h:143:11: error: ‘sigma_coefficient_’ was not declared in this scope; did you mean ‘sigma_coefficient’?
[build]   143 |           sigma_coefficient_.reset (sigma_coefficient);
[build]       |           ^~~~~~~~~~~~~~~~~~
[build]       |           sigma_coefficient
[build] In file included from /usr/local/include/pcl-1.12/pcl/filters/convolution_3d.h:287,
[build]                  from /home/cookteam/Workspace/CPP_Program/PCL_Pure_Test/main.cpp:3:
[build] /usr/local/include/pcl-1.12/pcl/filters/impl/convolution_3d.hpp: In member function ‘bool pcl::filters::GaussianKernel<PointInT, PointOutT>::initCompute()’:
[build] /usr/local/include/pcl-1.12/pcl/filters/impl/convolution_3d.hpp:89:7: error: ‘sigma_coefficient_’ was not declared in this scope
[build]    89 |   if (sigma_coefficient_)
[build]       |       ^~~~~~~~~~~~~~~~~~
[build] make[2]: *** [CMakeFiles/MyApp.dir/build.make:82: CMakeFiles/MyApp.dir/main.cpp.o] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/MyApp.dir/all] Error 2
[build] make: *** [Makefile:103: all] Error 2
[build] Build finished with exit code 2
```

**To Reproduce**
- CMakeLists.txt
```cmake:CMakeLists.txt
cmake_minimum_required(VERSION 3.10)
project(MyApp)

find_package(PCL 1.12 COMPONENTS common filters REQUIRED)

add_executable(MyApp main.cpp)
target_link_libraries(MyApp ${PCL_LIBRARIES})
```
- main.cpp
```cpp:main.cpp
#include <pcl/features/normal_3d.h>
#include <pcl/kdtree/kdtree.h>
#include <pcl/filters/convolution_3d.h>
#include <pcl/filters/fast_bilateral.h>

int main()
{
	pcl::FastBilateralFilter<pcl::PointXYZ> fbf;
	return 0;
}
```

**Screenshots/Code snippets/Build information**

Nothing.

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [GCC 8.4 9.3 10.1] all of them failed.
 - PCL Version [ 1.12.1 ]
 - PCL Type: [Compiled from source] clone and checkout into [pcl-1.12.1] tag, then compile.

**Possible Solution**

Maybe add `#include <boost.hpp>` or just `#include <boost/optional.hpp>` into  `pcl/filters/convolution_3d.h`.

**Additional context**

Nothing.

**Comment by mvieth** [comment]
Thank you for reporting. You are correct, `convolution_3d.h` is missing `#include <boost/optional.hpp>`. Are you interested in opening a pull request to fix this?

Two things to note:
- In your example program, `convolution_3d.h` isn't needed, and `FastBilateralFilter` also doesn't depend on it, so you can probably simply remove the include to avoid the error
- If you _do_ need `convolution_3d.h`, you can add `#include <boost/optional.hpp>` before the other includes to avoid the error

**Comment by dongchenyu163** [comment]
@mvieth  Thank you for your two notes.
Is there any instructions about creating a pull request?(Like How to write a commit message and the titile?)

**Comment by mvieth** [comment]
> @mvieth Thank you for your two notes. Is there any instructions about creating a pull request?(Like How to write a commit message and the titile?)

This might help you: https://github.com/PointCloudLibrary/pcl/blob/master/CONTRIBUTING.md
And this: https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request

**Comment by dongchenyu163** [comment]
Thank you.
I'll push it later.

**Comment by mvieth** [comment]
Fixed by the pull request
