### ISSUE TITLE
[octree] OctreePointCloudDensity could not serializeTree correctly.

### ISSUE THREAD

**Issue by T800GHB** [PointCloudLibrary/pcl#5215]
**Describe the bug**

I use following code to establish octree for density
  pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_density(0.2);
  
  octree_density.setInputCloud(background_points);
  octree_density.addPointsFromInputCloud();
serializeTree like this
  std::vector<char> disk_octree;
  octree_density.serializeTree(disk_octree);
Use  another tree to deserialize the content stored in vector of char
  pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_model(0.2);
  octree_model.deserializeTree(disk_octree);
Check it
  cout << "original: " << octree_density.getLeafCount() << ", new: " << octree_model.getLeafCount() << endl;
Get the result like this, leaf node count is not equal, and call the getVoxelDensityAtPoint function result is not same:
  original: 13264, new: 2

**Expected behavior**

The OctreePointCloudDensity B could restore all content in another OctreePointCloudDensity.

**To Reproduce**

pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_density(0.2);
for (auto i = 1; i < points_paths.size(); ++i) {
    auto point_data = LoadPoints(points_paths.at(i));    // Just get more than one frame point cloud
    octree_density.setInputCloud(point_data);
    octree_density.addPointsFromInputCloud();
}
std::vector<char> disk_octree;
octree_density.serializeTree(disk_octree);
pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_model(0.2);
octree_model.deserializeTree(disk_octree);

**Your Environment (please complete the following information):**

 - OS: MacOS 12.3
 - Compiler: 
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
 - PCL Version [1.11, HEAD]

**Possible Solution**

Maybe there are some usage about serializeTree is wrong.

**Comment by mvieth** [comment]
The `std::vector<char> disk_octree` only holds information about the tree structure, where branches are etc. but does not contain the information from the leafs. For that, you need a class that implements two callback functions, see for example [octree_pointcloud_compression.h](https://github.com/PointCloudLibrary/pcl/blob/a3edc28b318837bc2685e8135751c2291554b7b7/io/include/pcl/compression/octree_pointcloud_compression.h#L234) and [octree_pointcloud_compression.hpp](https://github.com/PointCloudLibrary/pcl/blob/a3edc28b318837bc2685e8135751c2291554b7b7/io/include/pcl/compression/impl/octree_pointcloud_compression.hpp#L471). Or you try [this other serializeTree function](https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree_base.html#a4e6c5b482d5280d7809b4a8484b77a5e)

**Comment by T800GHB** [comment]
@mvieth
I try to use other serializeTree function like this:
    std::vector<char> disk_octree;
    std::vector<pcl::octree::OctreePointCloudDensityContainer*> leaf_container;
    octree_density.serializeTree(disk_octree, leaf_container);
    pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_model(resolution);
    octree_model.deserializeTree(disk_octree, leaf_container);
    cout << "original: " << octree_density.getLeafCount() << ", de: " << octree_density.getLeafCount() << endl;

**Comment by T800GHB** [comment]
@mvieth I try other serializeTree function like this:
    std::vector<char> disk_octree;
    std::vector<pcl::octree::OctreePointCloudDensityContainer*> leaf_container;
    octree_density.serializeTree(disk_octree, leaf_container);
    pcl::octree::OctreePointCloudDensity<pcl::PointXYZI> octree_model(resolution);
    octree_model.deserializeTree(disk_octree, leaf_container);
    cout << "old: " << octree_density.getLeafCount() << ", new: " << octree_density.getLeafCount() << endl;`
the leaf count is same, but the member value like min_x_ and others in the new tree is not same as old tree.
so I can't fully restore a octree from old one.

**Comment by mvieth** [comment]
@T800GHB Yes, you would also have to store that additional information separately. In your last code snippet, you only have the tree structure and the information from the leaves stored.
Can you describe what you are trying to achieve? If you for example want to store the point cloud in a file, a PCD file would be a better option. If you want a lossy compression, OctreePointCloudCompression would fit. To my knowledge the `serializeTree` and `deserializeTree` functions are mainly helper functions for the OctreePointCloudCompression and might not be easy or convenient to use in another context.

**Comment by T800GHB** [comment]
@mvieth 
I want to build a model to describe background by point cloud.
First, I collect point cloud from pure background, maybe 1000 pcd files.
Second, Use pcd files to build a octree density model, dump this model to disk
Finally, Load this model from disk, as a foreground detector. Input a frame of point cloud, find the points that is not belong to background.

**Comment by mvieth** [comment]
Ok, I see. Well, `serializeTree` is not intended/not designed to store _all_ information from the octree object. You will have to store additional information like the bounding box separately. Or you could look into the Boost serialization library, maybe that helps you.
