### ISSUE TITLE
How to calculate the length (perimeter) of the curve obtained by point cloud fitting

### ISSUE THREAD

**Issue by CaiHuFan** [PointCloudLibrary/pcl#5217]
I used VS + PCL to fit the curve of the point cloud and wanted to get the length of the fitted curve.
If you know how to do that please give me a copy of your code because I'm terrible at programming.
Thank you!!!

**Comment by mvieth** [comment]
This is not the right place to ask such a question. You can try stackoverflow or the discord community chat (https://github.com/PointCloudLibrary/pcl#community)
