### ISSUE TITLE
[custom] Is there any GPU-based algorithm in PCL that can reconstruct mesh from RGBD?

### ISSUE THREAD

**Issue by G20202502** [PointCloudLibrary/pcl#5219]
Recently I was trying to use GreedyProjectionTriangulation to implement "RGBD to Mesh", but its speed is far from expected. SO I'm wondering if there's an algorithm in PCL that can do real-time reconstruction? I guess any algorithm based on GPU may achive this.

**Comment by mvieth** [comment]
There is a GPU-based marching cubes implementation, but I haven't used that myself yet, no idea if it does what you want.
Also depends on how you define "real-time".
You can try asking on the [Discord community chat](https://github.com/PointCloudLibrary/pcl#community), maybe someone there has a hint for you.

**Comment by yuyu19970716** [comment]
Hi, have you solved the real-time reconstruction problem now? May I ask you a few questions? The greedy projection triangulation algorithm I am using now completes the reconstruction, but I have no clue about how to use CUDA to complete the real-time reconstruction. What is the general idea of this approach?
