### ISSUE TITLE
[Normal Estimation Using Integral Images] Can't generate the normals

### ISSUE THREAD

**Issue by unclesammy** [PointCloudLibrary/pcl#5225]
My operating system is win10,and I install PCL-1.12.0-AllInOne-msvc2019-win64.exe verion.
I am trying to do this tutorial(https://pcl.readthedocs.io/en/latest/normal_estimation_using_integral_images.html#normal-estimation-using-integral-images)
But I can't read any xyz coordinate from my "table_scene_mug_stereo_textured.pcd".I check that every points' xyz return nan.
This is how I find out.
```
 for (int index = 0; index < cloud->points.size(); index++)
    {
        double x = cloud->points[index].x;
        double y = cloud->points[index].y;
        double z = cloud->points[index].z;
        double nx = normals->points[index].normal[0];
        double ny = normals->points[index].normal[1];
        double nz = normals->points[index].normal[2];
        cout << x << " " << y << " " << z << endl;
        cout << nx << " " << ny << " " << nz << endl;
    }
```
So this lead to the result that I can't get anything showed on my viewer.
This is How I read the point cloud data.
```
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::io::loadPCDFile("table_scene_mug_stereo_textured.pcd", *cloud);
```
The is how I estimate  and visualize normals

```
    normalEstimation.setNormalEstimationMethod(normalEstimation.AVERAGE_3D_GRADIENT);
    normalEstimation.setMaxDepthChangeFactor(0.02f);
    normalEstimation.setNormalSmoothingSize(10.0f);
    normalEstimation.setInputCloud(cloud);
    normalEstimation.compute(*normals);
    pcl::visualization::PCLVisualizer viewer("PCL Viewer");
    viewer.setBackgroundColor(0.0, 0.0, 0.5);
    viewer.addPointCloudNormals<pcl::PointXYZ, pcl::Normal>(cloud, normals,100,200);
    viewer.addCoordinateSystem(1.0);
```

I try different level and scale a few time,but it just won't work.Here's my result.
![image](https://user-images.githubusercontent.com/56534652/163347734-ac6b107d-4033-4e59-8a60-25c586d37ce7.png)

**Comment by mvieth** [comment]
Your problem is still unclear. Please add some code to show what you are doing, especially how you are reading the data from the file. Please also add which operating system you use and how you installed PCL.

**Comment by unclesammy** [comment]
@mvieth I update it,please check

**Comment by mvieth** [comment]
You mean that x, y, and z are nan? Or nx, ny, and nz? Do you print the values directly after `loadPCDFile` or after estimating the normals? The order of your code snippets is unclear, a short single code snippet with the essential parts that I can use to reproduce the problem would be more helpful.
Did you check that _all_ points are nan? The file (as most recorded real-world point clouds) contains _some_ nan points, especially at the beginning and end

**Comment by unclesammy** [comment]
@mvieth My bad,I just wait a little longer.I get the xyz coordinate befor or after the normals estimating.And I also get the nx,ny,nz..But the result is still the same.

**Comment by mvieth** [comment]
Ah, ok. I didn't understand that you basically just use the tutorial with minor modifications.
I added this after the normal estimation, before the visualization:
```c++
    for(std::size_t i=10000; i<11000; ++i) {
        std::cout << (*cloud)[i] << " " << (*normals)[i] << std::endl;
    }
```
I can see that some points (and the corresponding normals) are all nans, but there are also many points that have valid x, y, z and normals.
However, `viewer.addPointCloudNormals<pcl::PointXYZ,pcl::Normal>(cloud, normals);` also does not display the cloud for me. Not sure why yet. When I change it to `viewer.addPointCloud<pcl::PointXYZ>(cloud);`, it works (no normals, only points displayed then of course).

**Comment by mvieth** [comment]
I found out that `addPointCloudNormals` does not display the cloud and normals correctly when there are nans at the end of the cloud and/or normals. You can work around this by copying all valid points to a new cloud and pass that one to the visualizer:
```c++
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud2 (new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointCloud<pcl::Normal>::Ptr normals2 (new pcl::PointCloud<pcl::Normal>);
    for(std::size_t i=0; i<cloud->size(); ++i) {
        if(std::isfinite((*cloud)[i].x) && std::isfinite((*cloud)[i].y) && std::isfinite((*cloud)[i].z) && std::isfinite((*normals)[i].normal_x) && std::isfinite((*normals)[i].normal_y) && std::isfinite((*normals)[i].normal_z)) {
          cloud2->push_back((*cloud)[i]);
          normals2->push_back((*normals)[i]);
        }
    }
```

Long term, we should also look at `addPointCloudNormals` so that it also displays the cloud correctly even if it contains normals.

**Comment by unclesammy** [comment]
I run the code on my environment and It work.So I guess that something to do with 'nan' value and indices？Anyway,Thanks for solving my question.
