### ISSUE TITLE
Is RANSAC enough to fit a sphere?

### ISSUE THREAD

**Issue by UmutUz** [PointCloudLibrary/pcl#5227]
Sorry if this is a dumb question or the wrong place to ask but I hope someone here can help me out anyway:

I have a pointcloud with a few spheres on it. I would like to get the center of these spheres. Would RANSAC be ideal to use as a sphere fitting solution? Should I use another sphere fit after using RANSAC? 

I did some research and some say RANSAC should be enough if not better than least squares to fit a sphere and some say its not accurate enough and RANSAC isn't made to fit spheres. So I wonder: Is the PCL implementation of RANSAC accurate enough to fit spheres in pointclouds?

**Comment by mvieth** [comment]
Short answer: Yes, sounds like RANSAC is the right tool for you.
Longer answer: If I understood correctly, there is more than one sphere in your pointcloud. In this case, you should absolutely prefer RANSAC over simple least squares. Least squares won't work if not all points belong to the same model (sphere). With several spheres in your cloud, you can simply run RANSAC to find a sphere, remove all points which belong to the sphere, and repeat.
PCL has two sphere models, one that uses normals and one that doesn't. I would recommend to first try the model that doesn't use normals (easier), and try the other only if RANSAC mismatches some points.
Alternatively to RANSAC, you can try MSAC (`MEstimatorSampleConsensus`). To use it, you should be able to simply switch. It might be a bit more accurate, but it might also be a bit slower than RANSAC. I am not sure what is more important for your case.
There is also the option to optimize the model coefficients after using RANSAC (or MSAC). This is roughly like least squares fitting, but only with the inliers. I would recommend to do this (e.g. with `setOptimizeCoefficients(true)`).

Last thing, [stackoverflow or the discord community chat is a better place to ask such questions.](https://github.com/PointCloudLibrary/pcl#community) The GitHub issues are for bugs, compile errors, and similar.

**Comment by UmutUz** [comment]
Thanks a lot! This is exactly what I needed!
