### ISSUE TITLE
[convolution_3d.h] class GaussianKernel have bug in Definition of sigma_coefficient_

### ISSUE THREAD

**Issue by guess-who-ami** [PointCloudLibrary/pcl#5229]
**Describe the bug**
When initialize a GaussianKernel object 
`pcl::filters::GaussianKernel<pcl::PointXYZ, pcl::PointXYZ>::Ptr kernel(new pcl::filters::GaussianKernel<pcl::PointXYZ, pcl::PointXYZ>);`
the code in convolution_3d.h has an error.
**C4430: missing type specifier - int assumed. Note: C + + does not support default int**

* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights
![2022_4_21 20 5 35](https://user-images.githubusercontent.com/68978508/164454451-e9272fcf-0775-4fcd-a629-a237bc8444ee.png)

**Your Environment (please complete the following information):**

 - OS: win10
 - Compiler: vs2019-msvc 
 - PCL Version 1.12.0

****

**Comment by mvieth** [comment]
This was fixed in pull request #5213
See also issue #5209 where this was previously reported

**Comment by guess-who-ami** [comment]
> This was fixed in pull request #5213 See also issue #5209 where this was previously reported

I need to add `#include <boost/optional.hpp>` in my cpp or in other files

**Comment by mvieth** [comment]
Yes, if you add `#include <boost/optional.hpp>` at the top of your cpp file(s), this problem should disappear.
