### ISSUE TITLE
Does this version contain pcl_conversions.h 

### ISSUE THREAD

**Issue by Petros626** [PointCloudLibrary/pcl#5234]
Hello guys,

I want to merge several `sensor_msgs::PointCloud2` using the function `bool concatenatePointCloud `. Does this version of pcl contain the header file pcl_conversions.h?

Thank you

**Comment by mvieth** [comment]
> I want to merge several `sensor_msgs::PointCloud2` using the function `bool concatenatePointCloud `

PCL is not directly part of ROS. It is independent and you need the perception_pcl/pcl_conversions/pcl_ros package(s) to use PCL in ROS. So PCL does not have the `sensor_msgs::PointCloud2` data type, only the "equivalent" type `pcl::PCLPointCloud2`

> Does this version of pcl contain the header file pcl_conversions.h?

It doesn't, and neither did previous versions (you can check for yourself with the [Go to file](https://github.com/PointCloudLibrary/pcl/find/master) button on the main page of the GitHub repo)

**Comment by Petros626** [comment]
yes exactly these listed packages I already have installed. I have found an answer at ROS Answers that says this is supported (https://answers.ros.org/question/58626/merging-multiple-pointcloud2/). Yes you are right it is not included, however this can be found under perception_pcl (https://github.com/ros-perception/perception_pcl) on Github. I wanted to do it all in Python, but apparently there are no bindings yet, so I would have to write it all in C++.

**Comment by mvieth** [comment]
If a function `concatenatePointCloud` exists which works directly with `sensor_msgs::PointCloud2`, then it will be in pcl_conversions or pcl_ros, not in PCL itself. That's all I can tell you, everything else would be off topic here

**Comment by Petros626** [comment]
Yes your're right. It seems, that the binding isn't done until now in Python PCL librarys. Found it only for C++
