### ISSUE TITLE
hi guys,when i use "pcl::SIFTKeypoint<pcl::PointXYZRGBNormal, pcl::PointXYZRGBNormal> sift;" in pcl0.12.1,it occurs erros

### ISSUE THREAD

**Issue by guyuezuntinggithub** [PointCloudLibrary/pcl#5241]
**Describe the error**

error	C2039	“intensity”: is not member of “pcl::PointXYZRGBNormal”	PclCloudViewer	e:\facereconstruction\medical beauty\trunk\libs\pcl-1.12.1\include\pcl-1.12\pcl\keypoints\sift_keypoint.h	48	

**To Reproduce**

**Your Environment (please complete the following information):**

 - OS: [win 10]
 - Compiler: [vs2017]
 - PCL Version [0.12.1]
 - PCL Type: [vs 2017 build with gpu and install]

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by mvieth** [comment]
You can see here, the class currently only works with `PointNormal`, `PointXYZRGB`, `PointXYZRGBA`, and point types which have an `intensity` field:
https://github.com/PointCloudLibrary/pcl/blob/4ee60810fdefe48103db752ab85967c8f904a340/keypoints/include/pcl/keypoints/sift_keypoint.h#L42-L77
`PointXYZRGBNormal` does not have an `intensity` field, so it doesn't work. You can either add a specialization for that point type, or use one of the others that work.

**Comment by guyuezuntinggithub** [comment]
> You can see here, the class currently only works with `PointNormal`, `PointXYZRGB`, `PointXYZRGBA`, and point types which have an `intensity` field:
> 
> https://github.com/PointCloudLibrary/pcl/blob/4ee60810fdefe48103db752ab85967c8f904a340/keypoints/include/pcl/keypoints/sift_keypoint.h#L42-L77
> 
> 
> `PointXYZRGBNormal` does not have an `intensity` field, so it doesn't work. You can either add a specialization for that point type, or use one of the others that work.

very appratiate for your reply!
