### ISSUE TITLE
hi guys, when I run code about "pcl::SampleConsensusInitialAlignment". It occurs errors

### ISSUE THREAD

**Issue by guyuezuntinggithub** [PointCloudLibrary/pcl#5242]
this is my code 
pcl::SampleConsensusInitialAlignment<pcl::PointXYZRGB, pcl::PointXYZRGB, pcl::FPFHSignature33> scia;
			scia.setInputSource(cloudfacefilter);
			scia.setInputTarget(cloudfaceReffilter);
			scia.setSourceFeatures(fpfhsompsrc);
			scia.setTargetFeatures(fpfhsomptgt);
			//scia.setMinSampleDistance(1);
			//scia.setNumberOfSamples(2);
			//scia.setCorrespondenceRandomness(20);
			PointCloudT::Ptr sac_result(new PointCloudT);
			
			scia.align(*sac_result);
but when I run code "scia.align(*sac_result);" 
![image](https://user-images.githubusercontent.com/63081832/166235607-73f5274e-2344-46e9-b4ef-0f152c94bc0f.png)

**Comment by mvieth** [comment]
Please check again if all your point clouds (`cloudfacefilter`, `cloudfaceReffilter`, `fpfhsompsrc`, `fpfhsomptgt`) contain points and have `width` and `height` greater than zero.
By the way, this was fixed in pull request #5113

**Comment by guyuezuntinggithub** [comment]
> Please check again if all your point clouds (`cloudfacefilter`, `cloudfaceReffilter`, `fpfhsompsrc`, `fpfhsomptgt`) contain points and have `width` and `height` greater than zero. By the way, this was fixed in pull request #51

> 

very appreciate for your reply! although the point size is not zero ，but the width is zero
