### ISSUE TITLE
IntegralImageNormalEstimation not instantiated for many destination types

### ISSUE THREAD

**Issue by roncapat** [PointCloudLibrary/pcl#5244]
IntegralImageNormalEstimation is instantiated with the second template argument being only pcl::Normal or pcl::PointXYZRGBNormal, leaving outside other Normal types.

https://github.com/PointCloudLibrary/pcl/blob/0d3892c01c89b7c6034664edc0de15509cb35bcd/features/src/integral_image_normal.cpp#L46

differs from, for example, from:

https://github.com/PointCloudLibrary/pcl/blob/0d3892c01c89b7c6034664edc0de15509cb35bcd/features/src/normal_3d.cpp#L48

is there a specific reason?

**Comment by mvieth** [comment]
You are talking about the case when `PCL_ONLY_CORE_POINT_TYPES` is defined. This speeds up the compilation of the library and creates smaller binaries, by instantiating only the most important, "core" point types. To my knowledge, there is no common definition of "core point types" that is the same for all classes, meaning that the chosen types are somewhat arbitrary. So no, I don't know a specific reason. But depending on your platform and how you installed PCL, you might have all possible point types instantiated. If a class is not instantiated for a point type you want to use, you can use `PCL_NO_PRECOMPILE` as described [here](https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html)
