### ISSUE TITLE
[Build PCL from source in Windows 10] An error when configure PCL's source

### ISSUE THREAD

**Issue by kaitou1419** [PointCloudLibrary/pcl#5247]
Im trying build PCL ver 1.11.0 from source following this tutorial [https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-8-1-md](url)

In Step Configure i choose VS 2017 x64: and Configure. An error throw while configuring
![image](https://user-images.githubusercontent.com/73357725/167136589-cf6c2d37-caf7-495e-97a1-bb08abd50400.png)
![image](https://user-images.githubusercontent.com/73357725/167136793-b7e65a72-3278-4bff-930f-cd4d12859d0c.png)

whatever i update directory of 3rd library, it still got that error and don't have any Build checkbox

Please help me!
My ver: Win10, Boost 1.72.0, Eigen 3.3.7, FLANN 1.9.1, QHull 2019.1, VTK 8.2.0, OpenNI 2.2.0.33 Beta

**Comment by larshg** [comment]
Try follow this post here: https://github.com/PointCloudLibrary/pcl/issues/4462 - it might give some hints. But from what can be seen in log, it can't find Boost.

**Comment by kaitou1419** [comment]
@larshg I tried #4462 with PCL 1.11.1. And i tried to build CloudViewer like tutorial : but i don't know how it became lack ok lz4::lz4.lib 
i don't know how to fix it, lz4 might not install in 3rd of PCL
![image](https://user-images.githubusercontent.com/73357725/167300554-ed600b6a-aecb-44ae-bff9-986f66b7b421.png)


![image](https://user-images.githubusercontent.com/73357725/167300540-8c9c53bf-767b-4b1b-a6f4-00c9f39d211a.png)

**Comment by kaitou1419** [comment]
i had came over it by checking my environment path. so i will close this issuses
