### ISSUE TITLE
[transforms] transformPointCloud with Eigen's alignment error!

### ISSUE THREAD

**Issue by daohu527** [PointCloudLibrary/pcl#5248]
**Describe the bug**

When pass a `Eigen::Matrix4d` to `pcl::transformPointCloud` it will need the data 32 bytes aligment.
https://github.com/PointCloudLibrary/pcl/blob/1d482d523ffc9602fb84a439b3f4c3fe46dff9a6/common/include/pcl/common/impl/transforms.hpp#L191-L195

The question is the `Eigen::Matrix4d` variable is on the stack and it's member datas are default 16 bytes aligned. So how can I 32 bytes align?

**Context**

```cpp
  Eigen::Matrix4d align_pose;
  pcl::transformPointCloud(*map_ptr, *align_map_ptr, align_pose);
```

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Compiler: 
 - PCL Version : 1.10.0

I also read https://github.com/PointCloudLibrary/pcl/issues/4587, and we should check `tf.col (i).data ()`'s address is 32 bytes aligned

**Comment by mvieth** [comment]
@daohu527 In the issue you linked, my suggestion was to replace the aligned loads with unaligned loads (that is, replace `_mm_load_ps` with `_mm_loadu_ps`, replace `_mm_load_pd` with `_mm_loadu_pd`, and replace `_mm256_load_pd` with `_mm256_loadu_pd`). That will fix the problem, and should make the function only slightly slower, or not at all (there are at most 8 loads per constructor call, and the `Transformer` is only created once per call to `transformPointCloud`, so should be negligible). Would you be interested in creating a pull request to do that?
To answer your question, the values of `EIGEN_MAX_ALIGN_BYTES` and `EIGEN_MAX_STATIC_ALIGN_BYTES`, in combination with compiler flags that enable sse or avx, determine the alignment.

**Comment by daohu527** [comment]
While this seems reasonable, but the consistency of the interface is confusing. User passing float will work, but passing double will segmentation fault

if pcl separate enable `__AVX__` don't make sense, we should avoid to do this. seems Eigen have a EIGEN_MAX_ALIGN_BYTES why we didn't add this to avx support

**Comment by mvieth** [comment]
Eigen is a header-only library, so there is no pre-compiled code with AVX enabled/disabled. Only your compiler options or preprocessor-defines control Eigen's alignment behaviour. Unless there is a bug in Eigen, it should choose the correct alignment automatically.
Which compiler options do you enable? Do you use `EIGEN_DONT_VECTORIZE` or similar?

**Comment by daohu527** [comment]
> Eigen is a header-only library,

You mean I need to use -mavx or -DEIGEN_MAX_ALIGN_BYTES=32 to compile my own code to make `Eigen::Matrix4d` aligned? 

This seems reasonable, but requires the user's attention. I don't enable `avx` by default

**Comment by mvieth** [comment]
@daohu527 Could you tell me a bit more about your environment:
I assume you compiled your PCL from source (version 1.10.0)? Did you specify any CMake options or custom compiler flags or similar, or did you leave everything at the default values?
Which compiler do you use?
Could you post the CMakeLists.txt of your own project here?
Also: do you explicitly not want to enable AVX (e.g. because it creates some kind of problem), or did you not care whether it is enabled or not?

**Comment by daohu527** [comment]
I use bazel to compile, and the gcc version is 
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```
and also add `-march=native` and `-mavx` to gcc option. Right now I'm not quite sure what went wrong, so I want to confirm the following 2 questions
## q1
We need to compile PCL library with `-march=native` and `-mavx`, if not then there will a error?

## q2
After build PCL library with `-march=native` and `-mavx`, I also need to build my own code, which depends on `Eigen` and `PCL`, build with `-mavx`, then all thing will do right then?

**Comment by mvieth** [comment]
@daohu527 I suspect that bazel might be the problem. I tested the following:
```cpp
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/common/transforms.h>

int main () {
  pcl::PointCloud<pcl::PointXYZ>::Ptr map_ptr(new pcl::PointCloud<pcl::PointXYZ>), align_map_ptr(new pcl::PointCloud<pcl::PointXYZ>);
  map_ptr->emplace_back(1.0, 2.0, 3.0);
  Eigen::Matrix4d align_pose;
  for(int i=0; i<4; ++i)
    align_pose(i, i) = 1.0;
  pcl::transformPointCloud(*map_ptr, *align_map_ptr, align_pose);
  return 0;
}
```
Compiled with CMake:
```cmake
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)

project(SIMD_test)

find_package(PCL 1.12.1.99 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (test test.cpp)
target_link_libraries (test ${PCL_LIBRARIES})
```
CMake automatically adds compiler flags that were also used when PCL was compiled (`-msse4.2 -mfpmath=sse -march=native -mavx2` in my case). I don't have much experience with bazel, maybe it doesn't do this.
To answer your questions: You should also be able to build PCL without SIMD, by disabling the options `PCL_ENABLE_SSE`, `PCL_ENABLE_AVX`, and/or `PCL_ENABLE_MARCHNATIVE`.
Your own project should be built with the same options as PCL, otherwise there may be problems with alignment.

**Comment by daohu527** [comment]
https://github.com/introlab/rtabmap/issues/637 

It seems that all libraries should be built with `-avx`. I'll give up trying for now!
