### ISSUE TITLE
[cmake] " undefined reference to `boost::system::system_category()'"

### ISSUE THREAD

**Issue by uphome** [PointCloudLibrary/pcl#5249]
During installation and compilation, I used the command "make - j2", but I was in trouble. The terminal displays an error, like this.

~/pcl-pcl-1.12.1/build$ make -j2
[  1%] Built target pcl_io_ply
[  6%] Built target pcl_common
[  7%] Built target pcl_pcd_convert_NaN_nan
[  8%] Built target pcl_plyheader
[  8%] Built target pcl_ply2raw
[ 10%] Built target pcl_ply2ply
[ 10%] Built target pcl_ply2obj
[ 12%] Built target pcl_ml
[ 13%] Built target pcl_stereo
[ 13%] Built target pcl_kdtree
[ 13%] Built target pcl_octree
[ 17%] Built target pcl_sample_consensus
[ 27%] Built target pcl_io
[ 28%] Built target pcl_search
[ 29%] Linking CXX executable ../../bin/pcl_openni_grabber_example
[ 29%] Linking CXX executable ../../bin/pcl_openni_grabber_depth_example
/usr/bin/ld: ../../lib/libpcl_io.so.1.12.1: undefined reference to `boost::system::system_category()'
/usr/bin/ld: ../../lib/libpcl_io.so.1.12.1: undefined reference to `boost::system::generic_category()'
/usr/bin/ld: ../../lib/libpcl_io.so.1.12.1: undefined reference to `boost::system::system_category()'
/usr/bin/ld: ../../lib/libpcl_io.so.1.12.1: undefined reference to `boost::system::generic_category()'
collect2: error: ld returned 1 exit status
make[2]: *** [io/tools/CMakeFiles/pcl_openni_grabber_depth_example.dir/build.make:96：bin/pcl_openni_grabber_depth_example] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1208：io/tools/CMakeFiles/pcl_openni_grabber_depth_example.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
collect2: error: ld returned 1 exit status
make[2]: *** [io/tools/CMakeFiles/pcl_openni_grabber_example.dir/build.make:96：bin/pcl_openni_grabber_example] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1179：io/tools/CMakeFiles/pcl_openni_grabber_example.dir/all] 错误 2
make: *** [Makefile:152：all] 错误 2

I was puzzled by this question for a long time.
Do you have any good solutions? thank you！！！

**Comment by uphome** [comment]
Operating system ：Ubuntu 20.04.3
Compiler ：GNU C++ version 10.3.0
PCL version ：1.12.1
I use this command to install boost.         sudo apt-get install libboost-all-dev

**Comment by mvieth** [comment]
@uphome I am trying to reproduce your problem, but so far without success.
Can you describe how you try to build PCL?
Can you post the output from the CMake command?
Which CMake build type do you use (Release, Debug, RelWithDebInfo, ...)?

**Comment by uphome** [comment]
I found a solution from here. （ https://code-examples.net/en/q/cd7dc0 ）
Thank you for your reply！！！

**Comment by mvieth** [comment]
@uphome So what did you do exactly to fix the problem? (for anyone who also gets this error in the future)

**Comment by uphome** [comment]
From that article(https://code-examples.net/en/q/cd7dc0), I guess this is a linker problem.
So I used the following commands, as follows.
sudo ln -s libboost_ system. so. 1.12.1 libboost_ system. so
It did solved my problem.
