### ISSUE TITLE
[visualization] KeyBoardEvent.getKeySym() cannot read number "1"

### ISSUE THREAD

**Issue by Philip035** [PointCloudLibrary/pcl#5251]
**Describe the bug**

I want to add text to the vieport while I press the key of "1", but it seem not to work.
`if (event.getKeySym() == "1" && event.keyDown())`
	`{`
		`viewer->removeAllShapes(0);`
		`viewer->addText("demo2",200, 200, 20, 0, 1, 0, "err", 0);`
	`}`

But if the number "1" is replaced with "n", it will surely work if I press the key of "n".
`if (event.getKeySym() == "n" && event.keyDown())`
	`{`
		`viewer->removeAllShapes(0);`
		`viewer->addText("demo2", 200, 200, 20, 0, 1, 0, "err", 0);`
	`}`

**So how can I realize this function when I press the key of "1" while not the key of "n"?**

**Your Environment (please complete the following information):**

 - OS: [windows10]
 - Compiler: [VS2019]
 - PCL Version [1.12.0]

**Comment by mvieth** [comment]
@Philip035 Have you tried simply printing `event.getKeySym()` while pressing the "1" key? Then you know which value you have to check for.

**Comment by Philip035** [comment]
> 

Actually I tried that, the code follows:
`string press = event.getKeySym();`
`char keycode = event.getKeyCode();`
`std::cout << press << std::endl;`
`std::cout << keycode << std::endl;`
`qDebug() << QString::fromStdString(press) << endl;`

And the output is
`1`
`1`
`"1"`

So I tried the two ways:
`if(event.getKeySym() == "1")` and `if(event.getKeyCode() == '1')`

For another way, I tried this:
`if(press == "1")` and `if(keycode == '1')`

it didn't work either.

**Comment by mvieth** [comment]
@Philip035 This might be an oversight in the PCL code. Internally, there is a key listener for keys 0-9 and if the key is pressed down. But it seems the event is not relayed after processing it. On the other hand, the key-up event is relayed. So if you remove the check for `event.keyDown()` (or replace it with `event.keyUp()`), it should work for keys 0-9.

**Comment by Philip035** [comment]
> @Philip035 This might be an oversight in the PCL code. Internally, there is a key listener for keys 0-9 and if the key is pressed down. But it seems the event is not relayed after processing it. On the other hand, the key-up event is relayed. So if you remove the check for `event.keyDown()` (or replace it with `event.keyUp()`), it should work for keys 0-9.

It's really works! Thanks a million, I really appreciate it.
