### ISSUE TITLE
[fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory  #include <pcl/visualization/pcl_visualizer.h>] 

### ISSUE THREAD

**Issue by MarioCavero** [PointCloudLibrary/pcl#5253]
**Describe the error**

```
PCN-PyTorch/sample/build$ make
Scanning dependencies of target mesh_sampling
[ 50%] Building CXX object CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o
/home/mario/PCN-PyTorch/sample/mesh_sampling.cpp:39:10: fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory
 #include <pcl/visualization/pcl_visualizer.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/mesh_sampling.dir/build.make:62: recipe for target 'CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o' failed
make[2]: *** [CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mesh_sampling.dir/all' failed
make[1]: *** [CMakeFiles/mesh_sampling.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**To Reproduce**
Trying to compile (before being able to run the .py scripts) of the [PCN Pytorch repository](https://github.com/qinglew/PCN-PyTorch)
System: Ubuntu 18.04, freshly installed. 
Cuda version, came with 11.4, updated to 11.6. cudnn v8.4.0. According to the compatibility matrixes, there shouldn't be any problems. 

```
## CMake

Use this command to install CMake:

```bash
sudo apt-get udpate
sudo apt-get install cmake
```

PCL

The version I used is the latest version, you can use these commands to install:

```bash
sudo apt-get update  
sudo apt-get install git build-essential linux-libc-dev
sudo apt-get install cmake cmake-gui
sudo apt-get install libusb-1.0-0-dev libusb-dev libudev-dev
sudo apt-get install mpi-default-dev openmpi-bin openmpi-common 
sudo apt-get install libflann1.9 libflann-dev
sudo apt-get install libeigen3-dev 
sudo apt-get install libboost-all-dev
sudo apt-get install libqhull* libgtest-dev
sudo apt-get install freeglut3-dev pkg-config
sudo apt-get install libxmu-dev libxi-dev
sudo apt-get install mono-complete
sudo apt-get install openjdk-8-jdk openjdk-8-jre

git clone https://github.com/PointCloudLibrary/pcl.git
cd pcl
mkdir build && cd build
cmake ..
make -j4
sudo make install
```

 VTK

The version of the VTK is `8.2.0`. You can download it from the [website](https://vtk.org/download/) and use the commands blew to install:

```bash
tar -xzvf VTK-8.2.0.zip
cd VTK-8.2.0/
```

Before compiling, you need to edit the file `IO/Geometry/vtkOBJReader.cxx`. In line 859, add the following code:

```C++
// Here we turn off texturing and/or normals
if (n_tcoord_pts == 0)
{
    hasTCoords = false;
}
if (n_normal_pts == 0)
{
    hasNormals = false;
}
```

Continue to build:

```bash
mkdir build && cd build
cmake ..
make -j4
sudo make install
```

 Compile

In order to use the script, you need to compile it:

```bash
cd sample
mkdir build && cd build
cmake ..
make
```

```

VERBOSE=1 make
/usr/bin/cmake -H/home/mario/PCN-PyTorch/sample -B/home/mario/PCN-PyTorch/sample/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/mario/PCN-PyTorch/sample/build/CMakeFiles /home/mario/PCN-PyTorch/sample/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/mario/PCN-PyTorch/sample/build'
make -f CMakeFiles/mesh_sampling.dir/build.make CMakeFiles/mesh_sampling.dir/depend
make[2]: Entering directory '/home/mario/PCN-PyTorch/sample/build'
cd /home/mario/PCN-PyTorch/sample/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/mario/PCN-PyTorch/sample /home/mario/PCN-PyTorch/sample /home/mario/PCN-PyTorch/sample/build /home/mario/PCN-PyTorch/sample/build /home/mario/PCN-PyTorch/sample/build/CMakeFiles/mesh_sampling.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/mario/PCN-PyTorch/sample/build'
make -f CMakeFiles/mesh_sampling.dir/build.make CMakeFiles/mesh_sampling.dir/build
make[2]: Entering directory '/home/mario/PCN-PyTorch/sample/build'
[ 50%] Building CXX object CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o
/usr/bin/c++  -DDISABLE_PCAP -DDISABLE_PNG -Dqh_QHpointer -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -isystem /usr/local/include/vtk-8.2 -isystem /usr/local/include/pcl-1.12 -isystem /usr/include/eigen3  -msse4.2 -mfpmath=sse -march=native -mavx2 -std=gnu++14 -o CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o -c /home/mario/PCN-PyTorch/sample/mesh_sampling.cpp
/home/mario/PCN-PyTorch/sample/mesh_sampling.cpp:39:10: fatal error: pcl/visualization/pcl_visualizer.h: No such file or directory
 #include <pcl/visualization/pcl_visualizer.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/mesh_sampling.dir/build.make:62: recipe for target 'CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o' failed
make[2]: *** [CMakeFiles/mesh_sampling.dir/mesh_sampling.cpp.o] Error 1
make[2]: Leaving directory '/home/mario/PCN-PyTorch/sample/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mesh_sampling.dir/all' failed
make[1]: *** [CMakeFiles/mesh_sampling.dir/all] Error 2
make[1]: Leaving directory '/home/mario/PCN-PyTorch/sample/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Possible Solution**

Including libraries VTK with the proper path in the CMakeLists.txt. But it did not work.
```
find_package(VTK REQUIRED)
include_directories(SYSTEM ${VTK_INCLUDE_DIRS})
include(${VTK_USE_FILE})
```

**Comment by mvieth** [comment]
@MarioCavero Do you build and install PCL before you build and install VTK? PCL's visualization module needs VTK; if it doesn't find it, it won't be installed (including the visualization header files). So try building and installing VTK first, then PCL

**Comment by MarioCavero** [comment]
Thank you for the quick reply @mvieth . I did indeed (as the instructions I posted indicated first `PCL` then `VTK`). I also realised later after some research that the order would have to be `VTK` then `PCL`. I posted a [question](https://askubuntu.com/questions/1407719/revert-a-make-install-due-to-installing-pcl-before-vtk?noredirect=1#comment2445496_1407719) in Stack Exchange in order to fix it before posting any issue. I was told that I just had to re-run `PCL` again (building and installing). 
`PCL --> VTK` (is the incorrect order, but `VTK` was installed, so doing) `--> PCL` again, should have fixed the issue (as far as I understood from my research and comments). But it did not. 

Should I do any kind of `cmake --target clean` and `sudo make uninstall` of both (and sample), then proceed to reproduce again the instructions but with VTK first? I did not do what procedure to follow, so I did **`PCL --> VTK --> sample (error) --> PCL (again, as VTK was installed from the second step) --> sample (error again)`**

**Comment by mvieth** [comment]
@MarioCavero If you just do these steps for PCL again, it should work:
```C++
cmake ..
make -j4
sudo make install
```
CMake should realize that VTK is now available and build the visualization module. If that does not work, try deleting PCL's build folder and start from there.

**Comment by MarioCavero** [comment]
The solution was indeed deleting PCL's build folder and starting PCL's process again. Thank you very much for the quick useful responses.

**Comment by joerowelll** [comment]
Is there a work around without building from source and only using pcl's apt version? As I have found that visualization is not built with my apt installation

**Comment by mvieth** [comment]
@joerowelll Do you mean from the "standard" apt repository? Visualization is included there, see e.g. https://packages.ubuntu.com/jammy/amd64/libpcl-dev/filelist (installable with `sudo apt install libpcl-dev`)
