### ISSUE TITLE
[custom] Reorganize Data Fields While Concating 

### ISSUE THREAD

**Issue by OrcunCanDeniz** [PointCloudLibrary/pcl#5254]
I concat several pointclouds using PCL, then I use toRosMsg to publish the resulting concated PC. Which has a PointCloud2 msg fields as below. As far as I know, this field info shows each consecutive blocks of 32 bytes represents a point(XYZI). But also there are 4 fields holding 4 bytes(enum datatype 7 is float32), so there are only 16 meaningful bytes in this message's data array.  
      
    height: 1
    width: 80412
    fields: 
    - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
    - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
    - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
    - 
    name: "intensity"
    offset: 16
    datatype: 7
    count: 1
    is_bigendian: False
    point_step: 32

My question is how can I handle this to end up with point_step=16 data array?

**Comment by mvieth** [comment]
See here: #4939

**Comment by OrcunCanDeniz** [comment]
Is there an existing way to convert this type of received message to plain old std::vector<float> that only contains XYZI of points?

**Comment by mvieth** [comment]
@OrcunCanDeniz You can convert it to a `pcl::PointCloud<pcl::PointXYZI>`. If you want to convert it to a `std::vector<float>`, you have to do that manually.

**Comment by OrcunCanDeniz** [comment]
I am actually trying to copy the points to GPU(without padding bytes ofc). I need an array of floats which consists of {x,y,z,i,x,y,z,i,x,y,z,i, ...}. Then I will memcpy `4 * sizeof(float) * num_points` bytes of data from the beginning of the array.  

My idea about this is adding a non-aligned point type as below;

```
struct NonAlignedP{
    float x;
    float y;
    float z;
    float intensity;
};

POINT_CLOUD_REGISTER_POINT_STRUCT (NonAlignedP,
                                   (float, x, x)
                                   (float, y, y)
                                   (float, z, z)
                                   (float, intensity, intensity)
)

typedef pcl::PointCloud<NonAlignedP>     PointCloudT;
```
Then moving the PC2 msg to PCL cloud with the point type above;
```
PointCloudT::Ptr pc_ptr(new PointCloudT);
pcl::fromROSMsg(input_pointcloud_msg, *pc_ptr);
```

Finally 
```
float *points_data = nullptr;
size_t points_size = pc_ptr->size();
size_t points_data_size = points_size * sizeof(pc_ptr->points[0]);
checkCudaErrors(cudaMallocManaged((void **)&points_data, points_data_size));
checkCudaErrors(cudaMemcpy(points_data, (float*)(&pc_ptr->points[0]), points_data_size, cudaMemcpyDefault));
```

Any thoughts on this ? I really appreciate any opinions. Thanks a lot.

**Comment by mvieth** [comment]
Sounds like this could work.

**Comment by OrcunCanDeniz** [comment]
Yep, It worked
