### ISSUE TITLE
hi guys I got core dump when I use pcl::GreedyProjectionTriangulation

### ISSUE THREAD

**Issue by guyuezuntinggithub** [PointCloudLibrary/pcl#5257]
follwing is my fuction code:
pcl::PolygonMesh ImageProcessingUtility::meshReconstruct(const PointCloudT::Ptr input)
{
     pcl::PointCloud<pcl::Normal>::Ptr normals(new pcl::PointCloud<pcl::Normal>);
	pcl::search::KdTree<pcl::PointXYZRGB>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZRGB>);// 创建用于最近邻搜索的KD-Tree
	pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr cloud_with_normals(new pcl::PointCloud<pcl::PointXYZRGBNormal>);
	tree->setInputCloud(pointsmesh);

	pcl::NormalEstimation<pcl::PointXYZRGB, pcl::Normal> n;
	n.setInputCloud(pointsmesh);
	n.setSearchMethod(tree);
	n.setKSearch(20); // 0.1 -> 10cm
	// n.setRadiusSearch(5); // 0.1 -> 10cm
	n.compute(*normals);

	pcl::concatenateFields(*pointsmesh, *normals, *cloud_with_normals);
	pcl::GreedyProjectionTriangulation<pcl::PointXYZRGBNormal>::Ptr gp3(new pcl::GreedyProjectionTriangulation<pcl::PointXYZRGBNormal>);   // 
	gp3->setSearchRadius(0.155); 
	gp3->setMu(2.8); 
	gp3->setMaximumNearestNeighbors(100);   

	gp3->setMinimumAngle(M_PI / 18);
	gp3->setMaximumAngle(2 * M_PI / 3); 

	gp3->setMaximumSurfaceAngle(M_PI / 4); 
	gp3->setNormalConsistency(false);  

	gp3->setInputCloud(cloud_with_normals); 
	gp3->setSearchMethod(tree2);
	pcl::PolygonMesh meshtmp;

	gp3->reconstruct(meshtmp); 
    return meshtmp;
}

when it leave this fuction occurs erro

![image](https://user-images.githubusercontent.com/63081832/168205172-51994901-777b-4811-8c6d-5b76894f0faa.png)

**Comment by guyuezuntinggithub** [comment]
The version of pcl is 1.12.1

there is no erro in 0.8.0

**Comment by mvieth** [comment]
> there is no erro in 0.8.0

Do you mean 1.8.0?

Which operating system do you use?
How did you install PCL?
How do you build your own project? Which compiler do you use?

By the way, the Github issue templates exist for a reason :wink: the bug report template asks for the operating system, compiler, etc. That way, I wouldn't have to ask about that, and you would get a faster answer ...

**Comment by guyuezuntinggithub** [comment]
THANKS FOR YOUR REPLEY!

YES ,I MEAN 1.8.0

MY OPERATING SYSTEM IS FOLLOWING:
OS: WINDOWS 10
PCL: COMPILE FROM SOUCE
COPILER: VS2017

**Comment by mvieth** [comment]
See here: #5151

**Comment by guyuezuntinggithub** [comment]
> See here: #5151

thanks very much！
