### ISSUE TITLE
[cmake] Does not accept latest boost version (1.79.0)

### ISSUE THREAD

**Issue by fxcoudert** [PointCloudLibrary/pcl#5261]
**Describe the bug**

Compiling latest pcl (1.12.1) with latest boost (1.79.0) fails.

**Context**

Ship boost and pcl as part of Homebrew: https://github.com/Homebrew/homebrew-core/pull/101577

**Current Behavior**

In the cmake output:
```
-- Could NOT find Boost: Found unsuitable version "1.79.0", but required is exact version "1.78.0" (found /opt/homebrew/include, )
```

**To Reproduce**

We build with unpatched source and:

`cmake .. -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/pcl/1.12.1_3 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_apps=AUTO_OFF -DBUILD_apps_3d_rec_framework=AUTO_OFF -DBUILD_apps_cloud_composer=AUTO_OFF -DBUILD_apps_in_hand_scanner=AUTO_OFF -DBUILD_apps_point_cloud_editor=AUTO_OFF -DBUILD_examples:BOOL=OFF -DBUILD_global_tests:BOOL=OFF -DBUILD_outofcore:BOOL=AUTO_OFF -DBUILD_people:BOOL=AUTO_OFF -DBUILD_simulation:BOOL=ON -DWITH_CUDA:BOOL=OFF -DWITH_DOCS:BOOL=OFF -DWITH_TUTORIALS:BOOL=OFF -DBUILD_apps_modeler:BOOL=OFF `

**Your Environment (please complete the following information):**

 - OS: macOS 12
 - Compiler: system clang (from Xcode 13)
 - PCL Version: 1.12.1

**Comment by mvieth** [comment]
And Boost 1.79.0 will also be successfully found when using CMake 3.23.2 (will be released 2022-05-24)

**Comment by mvieth** [comment]
The PCL master branch can now successfully compile with Boost 1.79
