### ISSUE TITLE
Commercial use of PPFSignature PPFEstimation PPFHashMapSearch PPFRegistration

### ISSUE THREAD

**Issue by DevAnkylosaurus** [PointCloudLibrary/pcl#5263]
Hi everyone, does the classes
pcl::PPFSignature 
pcl::PPFEstimation
pcl::PPFHashMapSearch
pcl::PPFRegistration

permit commercial use? or how to use it commercially?

**Comment by mvieth** [comment]
PCL is released under the BSD 3-clause license, see here:
https://github.com/PointCloudLibrary/pcl/blob/master/LICENSE.txt
You can also find that information at the top of each header file.

**Comment by DevAnkylosaurus** [comment]
In features/ppf.h and registration/ppf_registration.h there're nothing but BSD clauses.

**Comment by mvieth** [comment]
You can find detailed explanations for this license elsewhere, e.g.:
https://tldrlegal.com/license/bsd-3-clause-license-(revised)
https://fossa.com/blog/open-source-software-licenses-101-bsd-3-clause-license/
