### ISSUE TITLE
Installing newer version on Ubuntu

### ISSUE THREAD

**Issue by The-Developer-02** [PointCloudLibrary/pcl#5266]
I'm trying to install a newer version of pointcloud on ubuntu, I'm currently using 1.10, the standarard sudo apt-get install libpcl-dev only gets 1.10 and I can't seem to specify a different version. I have also tried downloading from github and installing that way, but while building it freezes my pc and even leaving for several days, it doen't fully continue and gets stuck at about 40% at the highest. Any advice would be apreciated.

**Comment by mvieth** [comment]
Sound like the build process might use too much RAM, causing your computer to freeze. I have 16 GB of RAM and usually use two build jobs (`-j2` when using make), sometimes three when I don't have any other programs open that use up RAM

**Comment by The-Developer-02** [comment]
I've tried both -j2 and -j4 on seperate occasions and both still cause it to freeze

**Comment by The-Developer-02** [comment]
I've started it now with -j1, I hadn't monitored the ram before, I am this time, it got to 96% within a few minutes

**Comment by jspricke** [comment]
Which version of Ubuntu do you use?
1.12.1 is in jammy: https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=libpcl-dev

**Comment by The-Developer-02** [comment]
it has frozen again, I've left it running incase it comes back, the memory usage is at 99.7%, I can't check my ubuntu version, but I believe it is 18.04

**Comment by The-Developer-02** [comment]
I've got 8gb on it, there's nothing else running as far as I can tell, I've got no programs open

**Comment by mvieth** [comment]
Hm, I have never heard that 8 GB is not enough to compile PCL with a single build job. Then try the CMake option `PCL_ONLY_CORE_POINT_TYPES` to compile PCL only for the most common point types.

**Comment by The-Developer-02** [comment]
Sorry, bit new to this, how would I do that, I tried adding that to the end of cmake but it thinks that is a source directory and can't find it

**Comment by mvieth** [comment]
See here: https://pcl.readthedocs.io/projects/tutorials/en/master/building_pcl.html#building-pcl (press `t` for advanced options)

**Comment by The-Developer-02** [comment]
Ok, that has managed to build and install it thank you, but the core files don't include some of the ones I need, how would I go about installing those?

**Comment by mvieth** [comment]
> the core files don't include some of the ones I need, how would I go about installing those?

What do you mean exactly?

**Comment by The-Developer-02** [comment]
So one of the reasons I wanted to get a newer version of pcl was because I needed to use memory.h, but it hasn't been installed with this core set of files

**Comment by mvieth** [comment]
Please check again. I assume you ran `sudo make install`. `PCL_ONLY_CORE_POINT_TYPES` does not influence which files are installed, only which template instantiations are contained in the library files.

**Comment by The-Developer-02** [comment]
I did yes, I can find the file in the files that where downloaded and on here, but it's not been installed

**Comment by mvieth** [comment]
And the other files (let's say, point_types.h and point_cloud.h), have they been installed as you would expect?
Please describe your build and install process in detail.

**Comment by The-Developer-02** [comment]
yes those have installed fine, I downloaded the files from github as a zip folder, unpacked them and created a build file within, I moved within the build folder, I then used `cmake` as you instructed here, followed by `make` and then `sudo make install`.

**Comment by mvieth** [comment]
Maybe check that there is enough free space on your hard drive? Otherwise I see no reason why point_types.h and point_cloud.h would be installed correctly, but memory.h isn't. Then I would suggest to just copy memory.h manually.
Oh, and I assume you downloaded the master branch version from github? Or did you download a release as a zip?

**Comment by The-Developer-02** [comment]
There is definitely enough space on the hard drive, yes I did download the master branch, the memory.h file is in the files that where downloaded, so i've no idea either, I'll try copying it in and see how that goes

**Comment by 155cannon** [comment]
> Which version of Ubuntu do you use? 1.12.1 is in jammy: https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=libpcl-dev

If I use Ubuntu20.04,  "apt install libpcl-dev" will install pcl-1.10.0, how to install pcl-1.12.1 on Ubuntu20.04 by apt install?

**Comment by mvieth** [comment]
> If I use Ubuntu20.04, "apt install libpcl-dev" will install pcl-1.10.0, how to install pcl-1.12.1 on Ubuntu20.04 by apt install?

That's not possible. There is always just one PCL version available from apt. In Ubuntu 20.04 that is PCL 1.10.0. If you want a newer PCL version than that, either upgrade your Ubuntu (e.g. to Ubuntu 22.04), or compile PCL yourself from source.
