### ISSUE TITLE
provide pcl.js by wasm

### ISSUE THREAD

**Issue by naah69** [PointCloudLibrary/pcl#5271]
provide pcl.js by wasm or build document.
we need it in web.

**Comment by mvieth** [comment]
We don't offer official support for js/wasm. Emscripten seems to be a good starting point though.
You can also try asking on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community), maybe someone there has experience with this.

**Comment by luoxuhai** [comment]
@naah69 I built PCL using WebAssembly and now it works in the browser: https://github.com/luoxuhai/pcl.js
