### ISSUE TITLE
[compile error] "vtkRenderWindowInteractorFix while compiling latest pcl-master"

### ISSUE THREAD

**Issue by unclesammy** [PointCloudLibrary/pcl#5273]
**Describe the error**

Please paste the compilation results/errors.
When I try to ALL_BUILD the pcl-master,I get an error from vtkRenderWindowInteractorFix.cpp.
![image](https://user-images.githubusercontent.com/56534652/170217960-7ccc8f26-7fa5-4aec-8605-0601a7e0f22a.png)
![image](https://user-images.githubusercontent.com/56534652/170218059-33339cd7-9032-4083-ad2f-e3d6c14579f0.png)
which means that vtkXRenderWindowInteractor is not a member of pcl.

**Your Environment (please complete the following information):**

 - OS: WIN10
 - Compiler: Visual Studio 2022 (v143)
 - PCL Version:1.12.1

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No
 - List and Version of dependencies used
I'm using the 3rdParty that came with the pcl1.12.1 all in oneinstaller.

**Possible Solution**

I can note the `interactor = pcl::vtkXRenderWindowInteractor::New ();`,it will successfully build.

**Comment by mvieth** [comment]
@unclesammy Which VTK version are you using?
I am confused why it says `vtkRender...` in your code, it should be `vtkXRender...` (note the `X`):
https://github.com/PointCloudLibrary/pcl/blob/633ec389bc5bd5784c5035ffe44776dbd020a9b4/visualization/src/vtk/vtkRenderWindowInteractorFix.cpp#L53
Did you modify that?

**Comment by mvieth** [comment]
@unclesammy Can you try changing
`#if VTK_MAJOR_VERSION == 9 && ...`
to
`#if __unix__ && VTK_MAJOR_VERSION == 9 && ...`, adding `__unix__`?

**Comment by mvieth** [comment]
@unclesammy Yes, does that work?

**Comment by unclesammy** [comment]
@mvieth I still have another problem.It seems that when I try to read the file.I get this
![image](https://user-images.githubusercontent.com/56534652/170228128-8b0809bf-1a47-4a2b-ac81-6c4a9532383a.png)
It's similar to #3782

**Comment by mvieth** [comment]
@unclesammy Does that mean that adding `__unix__` solved the initial problem?

For the other, unrelated problem: it seems that there are several solutions in the issue you linked (although I didn't understand everything since I can't read Chinese). Please try those, and if they don't work, open a new, separate issue for that.

**Comment by unclesammy** [comment]
@mvieth ok,the __unix__ solve the compile problem.And for another,I will open a new one.I just don't know if these two are related.

**Comment by mvieth** [comment]
> @mvieth ok,the **unix** solve the compile problem.And for another,I will open a new one.I just don't know if these two are related.

I am quite sure they are not related.

**Comment by unclesammy** [comment]
It's just I forgot to throw the release mode of pcl.lib out of my property sheet.After I clear them out,it work out just fine.
![image](https://user-images.githubusercontent.com/56534652/170246093-6e1ad543-91d7-4f1f-b0d4-8593e9d0e61c.png)
