### ISSUE TITLE
[compile error] "ply_parser.cpp:(.text+0x1cfa): undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'"

### ISSUE THREAD

**Issue by Wang-sx0103** [PointCloudLibrary/pcl#5276]
## **OS** and **ENV**:
Windows 11 22H2
MinGW-w64 (gcc 8.1.0)
pcl 1.12.1
boost 1.79.0
## build>make
[ 21%] Linking CXX shared library ..\bin\libpcl_io_ply.dll
CMakeFiles\pcl_io_ply.dir/objects.a(ply_parser.cpp.obj):ply_parser.cpp:(.text+0x1cfa): undefined reference to `std::istream::seekg(std::fpos<_Mbstatet>)'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [io\CMakeFiles\pcl_io_ply.dir\build.make:99: bin/libpcl_io_ply.dll] Error 1
make[1]: *** [CMakeFiles\Makefile2:1004: io/CMakeFiles/pcl_io_ply.dir/all] Error 2
make: *** [Makefile:155: all] Error 2
![image](https://user-images.githubusercontent.com/52378569/170528292-b5bf8dbf-c35e-4efd-887b-2a75b8107f4f.png)

**Comment by mvieth** [comment]
It seem like there is a problem in your MinGW setup, see here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=1798
I don't think this is a bug in PCL.

**Comment by Wang-sx0103** [comment]
Thank you. I'll try to change the compiler.

**Comment by Wang-sx0103** [comment]
> It seem like there is a problem in your MinGW setup, see here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=1798 I don't think this is a bug in PCL.

Thank you again, I solved this problem by changing the compiler(gcc 12.1.1). Other configurations have not changed

**Comment by mvieth** [comment]
You're welcome!
