### ISSUE TITLE
This source file of ppf_object_recognition.cpp does not correctly work with  my example.

### ISSUE THREAD

**Issue by wujilingfeng** [PointCloudLibrary/pcl#5280]
I was learning the ppf algorithm, and I tested the source file of ppf_object_recognition.cpp . Below is the result:

 
![输出结果2](https://user-images.githubusercontent.com/35684738/171090086-d09d8585-c5f4-4e30-9fa3-f5cbccf3eadc.png)

What are the test data that you can work normally？

**Comment by mvieth** [comment]
Not sure what the suggested data is that should be given to ppf_object_recognition.cpp.
You might have to tune the parameters in ppf_object_recognition.cpp to get a good result (thresholds, normal estimation radius, subsampling leaf size, ...)

**Comment by wujilingfeng** [comment]
> Not sure what the suggested data is that should be given to ppf_object_recognition.cpp. You might have to tune the parameters in ppf_object_recognition.cpp to get a good result (thresholds, normal estimation radius, subsampling leaf size, ...)


Thank you very much. By the way ,have you not tested the code after you have written it?

**Comment by mvieth** [comment]
> Thank you very much! By the way ,have you not tested the code after you have written it?

ppf_object_recognition.cpp was written more than 10 years ago, and not by me. Many people contributed to this repository, I only joined in 2020.

**Comment by wujilingfeng** [comment]
> > Thank you very much! By the way ,have you not tested the code after you have written it?
> 
> ppf_object_recognition.cpp was written more than 10 years ago, and not by me. Many people contributed to this repository, I only joined in 2020.

No offense， Thank you for your help.

**Comment by mvieth** [comment]
No offence taken ;)
