### ISSUE TITLE
How to generate a solid mesh using Kinfu ? 

### ISSUE THREAD

**Issue by Amayess** [PointCloudLibrary/pcl#5283]
Hi,
Am creating an app using c++ and Qt. So far i have been able to link my C++ code with Qt, display the intel realsense frames on it with no problem and make a continous scan using Kinfu Realsense. 
[ https://github.com/IntelRealSense/librealsense/tree/master/wrappers/opencv/kinfu ]

Actually, am looking for a way to save the PLY generated with Kinfu as a solid Mesh. I tried several methods but none of them worked.

I saw that i can use the Kinfu_largescan but i didn't really understand how can i implement it on my code. 

Any help or suggestion ? 

This is my actual code 

![code 01](https://user-images.githubusercontent.com/105653860/171595001-e6dd4ffe-dea8-4e10-9d44-62917d74e9d9.JPG)

**Comment by mvieth** [comment]
You just want to save a mesh as a .ply file, or did I misunderstand your question? You can use `savePLYFile` or `savePLYFileBinary` for that.

**Comment by Amayess** [comment]
Yes exactly, so i have just to add the PLC library and that's it ?

**Comment by mvieth** [comment]
Not sure I understand the question? You have to install PCL of course, add it to your build configuration (e.g. find_library in CMakeLists.txt), include the header files you need, call the function ...

**Comment by Amayess** [comment]
Okay, thank you.

**Comment by Amayess** [comment]
hi @mvieth, in order to generate a solide PLY mesh with the function : pcl::io::savePLYFile ,  I have to do some conversion from "mat data" to "plc data" or no ? because the function  pcl::io::savePLYFile takes as parameter **Polygone Mesh** and i don't generate it with my program... (the picture before) 

For now, as a result i generate only a point cloud that i want to convert to solid mesh.
