### ISSUE TITLE
about move:  pcl::PassThrough<pcl::PointXYZ> to Qthread

### ISSUE THREAD

**Issue by MenGuangwen0411** [PointCloudLibrary/pcl#5286]
Hi，with WIN10 QT6.4 MSVC2019 PCL1.12.1
I define MyWork  as :
---------------------------------------------------------------------------------------------------------
class MyWork : public QObject
{
    Q_OBJECT
    int m_totalNum;
public:
    explicit MyWork(QObject *parent = nullptr,int totalNum=200);
    void working();

};

void MyWork::working() 
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
    cloud->width = 5;
    cloud->height = 1;
    cloud->points.resize(cloud->width * cloud->height);

    for (auto &point : *cloud)
    {
        point.x = 1024 * rand() / (RAND_MAX + 1.0f);
        point.y = 1024 * rand() / (RAND_MAX + 1.0f);
        point.z = 1024 * rand() / (RAND_MAX + 1.0f);
    }
    cloud->points[0].z = 1;
    cloud->points[1].z = 0;

    pcl::PassThrough<pcl::PointXYZ> pass;
    pass.setInputCloud(cloud);
    pass.setFilterFieldName("z");
    pass.setFilterLimits(0.0, 1.0);
    pass.filter(*cloud_filtered);

}
---------------------------------------------------------------------------------------------------------
with QT in MainWindow,
I use as :
---------------------------------------------------------------------------------------------------------
QThread * sub = new QThread;
MyWork* work = new MyWork();
work->moveToThread(sub);
connect(ui->startBtn, &QPushButton::clicked, work, &MyWork::working);
------------------------------------------------------------------------------------------------------------------------------
then generate:File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp  Line 904
expression:CrtlsValidheapPointer(block)...........

What's wrong? pcl::PassThrough<pcl::PointXYZ> can't be used as this method?

**Comment by mvieth** [comment]
My best guess is that you have to enable AVX: https://stackoverflow.com/questions/20169064/does-archavx-enable-avx2

**Comment by MenGuangwen0411** [comment]
> My best guess is that you have to enable AVX: https://stackoverflow.com/questions/20169064/does-archavx-enable-avx2

Thanks for your reply。
I use Qt Creator 7.0.2 (Community) with msvc2019 kit Desktop Qt6.4.0  MSVC2019 64bit.I don‘t learn more about AVX.
Please suggest me how to  ‘enable AVX’ with some detail ?
By the way, I try QtConcurrent and get the same erro.
-----------------------------------------------------------------------------------------------

......
QFuture<void> m_ProcessorFuture；
.......
connect(ui->startBtn, &QPushButton::clicked, this, &Widget::slotClickButtonApply);
......
......
void Widget::slotClickButtonApply()
{
    if (!m_ProcessorFuture.isRunning())
    {
        m_ProcessorFuture = QtConcurrent::run([this] { Widget::processing(); });
    }
}
void Widget::processing()
{
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
    cloud->width = 5;
    cloud->height = 1;
    cloud->points.resize(cloud->width * cloud->height);

    for (auto &point : *cloud)
    {
        point.x = 1024 * rand() / (RAND_MAX + 1.0f);
        point.y = 1024 * rand() / (RAND_MAX + 1.0f);
        point.z = 1024 * rand() / (RAND_MAX + 1.0f);
    }
    cloud->points[0].z = 1;
    cloud->points[1].z = 0;

    pcl::PassThrough<pcl::PointXYZ> pass;
    pass.setInputCloud(cloud);
    pass.setFilterFieldName("z");
    pass.setFilterLimits(0.0, 1.0);
    pass.filter(*cloud_filtered);
}
........


click startBtn also get the same erro:....minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp Line 904....

**Comment by mvieth** [comment]
> Please suggest me how to ‘enable AVX’ with some detail ?

I don't have any experience with Qt Creator, so I can't help with that. It might look similar to what is shown in the Stackoverflow question I posted above. Or maybe you can find something here: https://doc.qt.io/qtcreator/

**Comment by MenGuangwen0411** [comment]
Thank you all the same.
