### ISSUE TITLE
Every point pair feature should corresponds to multiple point pairs.

### ISSUE THREAD

**Issue by wujilingfeng** [PointCloudLibrary/pcl#5288]
![uxzdicqk7q](https://user-images.githubusercontent.com/35684738/172320837-ca123714-ed4f-403e-921f-75a1b3414338.jpeg)
According to the paper， Every point pair feature should corresponds to multiple point pairs just like picture above.
However, the code in ppf_registration.cpp seems that every point pair feature should corresponds to one point pair.
Namely, the point pairs which have same point pair feature will be covered.
```
// ppf_registration.cpp
void
pcl::PPFHashMapSearch::setInputFeatureCloud(
    PointCloud<PPFSignature>::ConstPtr feature_cloud)
{
  // Discretize the feature cloud and insert it in the hash map
  feature_hash_map_->clear();
  unsigned int n =
      static_cast<unsigned int>(std::sqrt(static_cast<float>(feature_cloud->size())));
  int d1, d2, d3, d4;
  max_dist_ = -1.0;
  alpha_m_.resize(n);
  for (std::size_t i = 0; i < n; ++i) {
    std::vector<float> alpha_m_row(n);
    for (std::size_t j = 0; j < n; ++j) {
      d1 = static_cast<int>(
          std::floor((*feature_cloud)[i * n + j].f1 / angle_discretization_step_));
      d2 = static_cast<int>(
          std::floor((*feature_cloud)[i * n + j].f2 / angle_discretization_step_));
      d3 = static_cast<int>(
          std::floor((*feature_cloud)[i * n + j].f3 / angle_discretization_step_));
      d4 = static_cast<int>(
          std::floor((*feature_cloud)[i * n + j].f4 / distance_discretization_step_));
      feature_hash_map_->insert(
          std::pair<HashKeyStruct, std::pair<std::size_t, std::size_t>>(
              HashKeyStruct(d1, d2, d3, d4),
              std::pair<std::size_t, std::size_t>(i, j)));
      alpha_m_row[j] = (*feature_cloud)[i * n + j].alpha_m;

      if (max_dist_ < (*feature_cloud)[i * n + j].f4)
        max_dist_ = (*feature_cloud)[i * n + j].f4;
    }
    alpha_m_[i] = alpha_m_row;
  }

  internals_initialized_ = true;
}
```

**Comment by mvieth** [comment]
I am not super familiar with the ppf registration, but I believe the code you posted is only for building the hash table for the model features. The matching between model and scene features seems to be done in a later step with `nearestNeighborSearch`, which indeed returns multiple matching results.

**Comment by wujilingfeng** [comment]
> I am not super familiar with the ppf registration, but I believe the code you posted is only for building the hash table for the model features. The matching between model and scene features seems to be done in a later step with `nearestNeighborSearch`, which indeed returns multiple matching results.

I have learned the unoredered_map,It won't cover the value that have same key. Thank you !

**Comment by mvieth** [comment]
> I have learned the unoredered_map,It won't cover the value that have same key. Thank you !

Here, `std::unordered_multimap` is used.
Does that mean that your question is answered and I can close this issue?

**Comment by wujilingfeng** [comment]
> question



> > I have learned the unoredered_map,It won't cover the value that have same key. Thank you !
> 
> Here, `std::unordered_multimap` is used. Does that mean that your question is answered and I can close this issue?

Yes, Thanks!
