### ISSUE TITLE
[custom] Something wrong when read .ply file which stores PointSurfel type vertex

### ISSUE THREAD

**Issue by JinYoung6** [PointCloudLibrary/pcl#5292]
I used
`pcl::PointCloud<pcl::PointSurfel>::Ptr surfel_cloud (new pcl::PointCloud<pcl::PointSurfel>);`
`pcl::PLYWriter writer;`
`writer.write(path, *surfel_cloud, false); `
to write a PointSurfel type pointclond to a .ply flie.

However, when I use
 `pcl::io::loadPLYFile<pcl::PointSurfel>(file_path, *surfel_cloud)`
to read the .ply file, I meet some problems :

At first, it reports
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:31: property 'float32 focal' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:32: property 'float32 scalex' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:33: property 'float32 scaley' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:34: property 'float32 centerx' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:35: property 'float32 centery' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:38: property 'float32 k1' of element 'camera' is not handled`
`[pcl::PLYReader] /home/xx/Desktop/surfel2.ply:39: property 'float32 k2' of element 'camera' is not handled`
`Core dumps`
Then I modify the .ply file using text edit. I delete the  element 'camera'. However，it still reports Core dumps without other information. 

I guess may be the method I used to read .ply file is wrong, but I have no idea to modify it.

**Comment by mvieth** [comment]
@JinYoung6 Please upload the .ply file (the original one, before modifying it with the text editor)
Which PCL version are you using?

**Comment by JinYoung6** [comment]
> @JinYoung6 Please upload the .ply file (the original one, before modifying it with the text editor) Which PCL version are you using?
[surfel2.txt](https://github.com/PointCloudLibrary/pcl/files/8883657/surfel2.txt)
Thanks for your reply!
Cause github doesn't support the .ply file, I change the file to a TXT file.

And my PCL version is 1.8.0

**Comment by mvieth** [comment]
@JinYoung6 These are just warnings, you can ignore them, the cloud is correctly loaded. If you want to modify the .ply file so that these warnings don't appear, you have to remove the line `element camera 1` and all following lines starting with `property ...`, and the very last line which is `0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 64 1 0 0`

**Comment by JinYoung6** [comment]
> @JinYoung6 These are just warnings, you can ignore them, the cloud is correctly loaded. If you want to modify the .ply file so that these warnings don't appear, you have to remove the line `element camera 1` and all following lines starting with `property ...`, and the very last line which is `0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 64 1 0 0`


Yeah, I removed the last line at the beginning, but still reported an error.
And Whether I modify it or not, a "core dumps" error will be reported. This error made me mad. Maybe it's my program environment problem. I'll try it on someone else's computer later.

**Comment by mvieth** [comment]
Oh, I missed the info that you get a core dump even with the unmodified file. Which operating system do you use? How did you install PCL? Which compiler do you use? Can you try the newest PCL version (1.12.1)?

**Comment by JinYoung6** [comment]
> Oh, I missed the info that you get a core dump even with the unmodified file. Which operating system do you use? How did you install PCL? Which compiler do you use? Can you try the newest PCL version (1.12.1)?


Thank you!  I solved the problem by using PCL1.12.0. Compile using source code. 

And my environment is 
Ubuntu18.04    
C++11(PCL1.8)     
C++14(PCL1.12)
