### ISSUE TITLE
[custom] slow speed with PCDWriter::write()

### ISSUE THREAD

**Issue by KainanSu** [PointCloudLibrary/pcl#5294]
Hi, I want to know why the PCDWriter::write() has a very slow speed.
Writing a 8M file, cost 20s.

version: PCL-1.8.0

**Comment by mvieth** [comment]
@KainanSu
- Which `write` function do you use exactly? Do you write a `pcl::PCLPointCloud2` or a templated `pcl::PointCloud`? If it is the latter, which point type? Do you write a binary file or an ASCII file? Ideally, please post a code snippet where you call the `write` function
- Can you be sure that the hard drive where you write the file isn't the bottleneck? How long does it take when you create a copy of the 8M .pcd file, right next to the original file?

**Comment by KainanSu** [comment]
Thanks for your reply!
1. I use `pcl::PointCloud`, `pcl::PointCloud<pcl::PointXYZRGB>`, `ASCII`.

My code below, it is short:
```cpp
pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud;

//
// ... some operation to set cloud
//

pcl::PCDWriter writer;
writer.write("rst.pcd",*cloud);
```
3. I think my ssd hard drive isn't the bottleneck. It takes a very short time to copy an 8M .pcd file, definitely within 1s.

**Comment by KainanSu** [comment]
@mvieth 
One .pcd has 252,672 points. When writing a binary .pcd instead, it cost just 600ms. 

Oh, I think convert to ASCII may be costly.

I use `win10`, `All-In-One Installer` from http://unanancyowen.com/en/pcl18/.

**Comment by mvieth** [comment]
@KainanSu Yes, writing a binary file is usually much faster. Do you need an ASCII file or would a binary file also be an option for you? In general, a binary file is recommended because of higher reading/writing speed, lower file size, and higher precision, unless you need an ASCII file because you want to manually look at the points and modify them in the file

**Comment by KainanSu** [comment]
@mvieth Thanks, mvieth.
I'm just new to PCL , I didn't know pcl has a binary writer .
I will use binary writer instead.
Thanks a lot!
