### ISSUE TITLE
[ApproximateProgressiveMorphologicalFilter] error in window size calculation for non 1 cell sizes

### ISSUE THREAD

**Issue by tpet93** [PointCloudLibrary/pcl#5298]
I believe there is an error in the implementation of ApproximateProgressiveMorphologicalFilter.
During window size calculations, the cell size setting is ignored. causing unexpected settings for cell sizes other than 1.0.

Fixing this may cause some peoples APMF  settings to break.
If they have tuned their APMF settings after defining a cell_size != 1.0, the fix disrupt their settings. 

**Expected behavior**

(https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/approximate_progressive_morphological_filter.hpp#L93)

(half_size code simplified for clarity)
```cpp
half_size = std::pow (base_, iteration);
window_size = cell_size_ * (2 * half_size + 1);
```

This matches the logic seen in https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/progressive_morphological_filter.hpp#L89-L92

```cpp
window_size = cell_size_ * (2.0f * std::pow (base_, iteration) + 1.0f);
```

**Current Behavior**

https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/approximate_progressive_morphological_filter.hpp#L93

```cpp
half_size = std::pow (base_, iteration);
window_size = 2 * half_size + 1;
```

**To Replicate**
 Set cell size to 0.05 and 
`pcl::console::setVerbosityLevel(pcl::console::L_DEBUG);`

**Environment :**
 - PCL Version [HEAD]

**Comment by mvieth** [comment]
I am unfortunately not very familiar with the (Approximate)ProgressiveMorphologicalFilter, but I had a quick look at [the paper](https://users.cis.fiu.edu/~chens/PDF/TGRS.pdf), and the approximate filter seems to follow the equations (4) and (5) there. Pull request https://github.com/PointCloudLibrary/pcl/pull/665 , which added the ApproximateProgressiveMorphologicalFilter, says that it is closer to the paper than ProgressiveMorphologicalFilter is. So maybe it is okay that the two versions handle the parameters differently? It is important to note that the ApproximateProgressiveMorphologicalFilter does use the cell size parameter, just not directly for calculating the `window_size` variable. And also, the `window_sizes` are not actually used later, only for one debug print. Aside from the different code, have you noticed any problems in the behaviour of the ApproximateProgressiveMorphologicalFilter?

**Comment by tpet93** [comment]
After some closer examination, the implementation does appear to work correctly.
It seems the variable `window_size` is referring to the number of cells in the window, not the size of the window in units (meters).
This matches the description in the paper

I think  this can cause some confusion, especially when people are using the debug messages.
I was specifying max_window_size_ in meters not number of cells, this was causing the iterations to stop prematurely.


this is  an example trying to run the APMF with the following parameters:
```yaml
base: 2.0
slope: 1.0
cell_size: 0.01
initial_distance: 0.01
```

Results in the following values for the first 4 iterations 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Tony/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Tony/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



iteration | reported window size | half   size | window   size (m) | height_threshold
-- | -- | -- | -- | --
0 | 3 | 1 | 0.03 | 0.01
1 | 5 | 2 | 0.05 | 0.03
2 | 9 | 4 | 0.09 | 0.05
3 | 17 | 8 | 0.17 | 0.09
4 | 33 | 16 | 0.33 | 0.17



</body>

</html>

**Comment by mvieth** [comment]
@tpet93 Good to hear that it is working correctly. If you have ideas how to improve the documentation to avoid confusion/misunderstandings in the future, feel free to create a pull request
