### ISSUE TITLE
Using csv file

### ISSUE THREAD

**Issue by manz00** [PointCloudLibrary/pcl#5302]
I have csv files with point cloud data (multple files). Is there a method to combine those files into a single pcd file that the pcl library can use?

**Comment by EvanZarrella** [comment]
I don't believe there's even a CSVReader or Writer method in the PCL as of today so I don't think there is. 

You have multiple options here I think : 
* Get all your CSV and convert them into a PLY file format with a tool like CloudCompare. Then load them with the PCL, merge the clouds, then export as PCD.
* Code yourself a simple CSV parser and add all points to a single cloud then export to PCD.
* Use a CSV parser (eg [this one](https://github.com/AriaFallah/csv-parser) that I have not tested) and convert it into point clouds then merge them.

As a side note, this question is, I think, more fitted for a stackoverflow question than github as it's more about the usage of the lib than a bug report or feature request. On the other hand, having a CSVReader/Writer methods could be nice to have in the PCL.

Regards

**Comment by mvieth** [comment]
Thank you @EvanZarrella for the great answer!
One addition: PCL has an [ASCIIReader](https://pointclouds.org/documentation/classpcl_1_1_a_s_c_i_i_reader.html). I haven't used that so far, but it sounds like that should read CSV files

**Comment by EvanZarrella** [comment]
I assumed that he cannot change his file encoding. I quickly looked into ASCIIReader and it should work provided that the CSV fields matches the `PointT` fields name. For example : 
```csv
x y z
1 0 1
0 1 0
0 1 1```
should work but :
```csv
px py pz
1 0 1
0 1 0
0 1 1```
