### ISSUE TITLE
[ppf] Program occured errors on windows

### ISSUE THREAD

**Issue by wujilingfeng** [PointCloudLibrary/pcl#5303]
I was running the ppf program, and there throwed an error when computing ppfsignature.
![屏幕截图 2022-06-21 154239](https://user-images.githubusercontent.com/35684738/174744504-147cd649-216d-49c8-abbd-8be34d8b9686.png)
![屏幕截图 2022-06-21 153932](https://user-images.githubusercontent.com/35684738/174744514-08ee0098-3e03-4321-a482-f66d97a94e9b.png)

**Comment by mvieth** [comment]
Please provide some more information:
- Which PCL version do you use? How did you install it?
- Which compiler do you use?
- Can you post some debugger output, like a stacktrace or similar?

**Comment by mvieth** [comment]
@wujilingfeng If you don't give us more information, there is nothing we can do ...

**Comment by mvieth** [comment]
I'm assuming the problem resolved itself in the meantime ...
