### ISSUE TITLE
Binary are linked with Qt5 even when WITH_QT=NO

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#5307]
```bin/pcl_hdl_viewer_simple``` is linked with Qt5 despite ```-DWITH_QT=NO```.

Version: 1.12.1
clang-13
FreeBSD 13.1

**Comment by mvieth** [comment]
That binary (and some others) are linked with Qt through the VTK libraries. `WITH_QT=NO` currently doesn't have influence on that. I am not sure whether it is possible to use VTK without Qt. Could you explain the situation a bit more: Why do you not want to link to Qt? Is Qt available on the system? Which VTK version is used?

**Comment by yurivict** [comment]
> That binary (and some others) are linked with Qt through the VTK libraries.

What does this mean? If some other library X is linked to Qt and your binary links to X this doesn't make your binary linked to Qt.

> Why do you not want to link to Qt?

I am trying to make FreeBSD port options to work cleanly with and without the QT option.

> Is Qt available on the system?

Yes.

> Which VTK version is used?

9.1

**Comment by larshg** [comment]
VTK can tell your app that it has to link to certain libraries as well, if its public linked. Ie. if VTK can return some Qt types, your app would need to know them.

One way is to disable Qt in VTK(would require own manual build, since public versions is linked with Qt, see its dependencies: https://www.freshports.org/math/vtk9).

**Comment by yurivict** [comment]
> VTK can tell your app that it has to link to certain libraries as well, if its public linked. Ie. if VTK can return some Qt types, your app would need to know them.

Such situations almost always don't require the dependency package to link transient dependencies. If your app cares about QT types returned by some VTK methods - it should link to Qt. If it for example doesn't use this part of VTK API at all - there's no need to link to Qt.

**Comment by larshg** [comment]
Maybe not, but its up to VTK to decide which libraries they are linking public - and afaik it is forced upon PCL. Qt is linked public [here](https://github.com/Kitware/VTK/blob/master/GUISupport/Qt/CMakeLists.txt#L62).

**Comment by yurivict** [comment]
Ok, thanks.
