### ISSUE TITLE
[custom] When I use pcl1.9 in ubuntu 20.04 it prompts PointXYZ does not name a type

### ISSUE THREAD

**Issue by kyoasu** [PointCloudLibrary/pcl#5323]
![image](https://user-images.githubusercontent.com/39193066/178145386-4573137f-4491-47bc-9993-8272c068feab.png)
Appreciate it if you can suggest me how to solve

**Comment by mvieth** [comment]
@kyoasu What project are you trying to compile? The error is probably that you are including `point_types.hpp`, but you should include `<pcl/point_types.h>` instead

**Comment by kyoasu** [comment]
> This is very useful! Thank you for answering me！XD
