### ISSUE TITLE
pcl::PassThrough<pcl::PointXYZRGB> for the rgb field should filter on the rgb intensity/grayscale value

### ISSUE THREAD

**Issue by 1ros0** [PointCloudLibrary/pcl#5328]
Hi, 

Applying the pcl::PassThrough to a pcl::PointXYZRGB on the "rgb" field results in unintuitive/meaningless behavior. The filter checks against the float representation of the rgb field which isn't a meaningful number when considering a min and max filter range.  

Here is the float representation:
`
std::uint8_t r = 255, g = 0, b = 0;    // Example: Red color
std::uint32_t rgb = ((std::uint32_t)r << 16 | (std::uint32_t)g << 8 | (std::uint32_t)b);
p.rgb = *reinterpret_cast<float*>(&rgb);
`
Comparing against this representation doesn't result in filtering values, in the manner the caller would expect. For instance, the above red color example results in a really large negative number when represented as a float. 

Todo: The passthrough filter for the "rgb" field should convert the rgb value into a intensity/grayscale value and then filter min and max based on that grayscale value.  

Thank you

**Comment by mvieth** [comment]
> The passthrough filter for the "rgb" field should convert the rgb value into a intensity/grayscale value and then filter min and max based on that grayscale value

IMO, if it did that automatically, that wouldn't be so intuitive either. You can of course convert your cloud to a cloud of `pcl::PointXYZI` and pass that to the filter. I'm not really sure what you expect when you tell the filter to keep all points where the "rgb" value is in a certain range, when you know those are actually three values packed into a float? The PassThrough isn't really meant to dealt with more complex situations like this, see here for more suggestions what you can do: https://stackoverflow.com/questions/72878613/passing-unit8-to-pclpassthrough

**Comment by 1ros0** [comment]
Hmm so maybe if filtering on the RGB field is requested the filter function
should return an error?

On a slightly different note, based on the page you linked, if the pass
through filter is requested on non-float fields that might exist in any
point type then too, it should return an error. The answer on the page you
linked shows that current functionality only works for float fields.

**Comment by mvieth** [comment]
@1ros0 That sounds like a good idea (maybe only a warning for rgb, error for non-float fields). Would you be interested in opening a pull request for this?

**Comment by mvieth** [comment]
@1ros0 Are you still planning to open a pull request?
