### ISSUE TITLE
How to print dimension size of keypoints or descriptors?

### ISSUE THREAD

**Issue by Haalum** [PointCloudLibrary/pcl#5337]
With the following code, I can print how many points I have in the point cloud. How do I print the dimension size [whether it has 3 values per point (XYZ) or 6 values per point (XYZRGB)]. 
```c
pcl::console::print_info ("Detected %lu keypoints\n", keypoints->size ());
```
I want to see the dimension size of the descriptors I have created. Thanks!

-- From an amateur C++ and new PCL user.

**Comment by mvieth** [comment]
Depends on what you want exactly. `sizeof(point)` gives you a hint (in bytes), but this might not be what you are looking for. For actual feature types, there is [pcl::detail::traits::descriptorSize](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/impl/point_types.hpp#L196) (but not for point types like PointXYZ). There is also [getFields](https://pointclouds.org/documentation/group__common.html#gac8788f010a13b19fc04d9dc2305fde22), but again, not sure if that is what you want.

In the future, please use [stackoverflow or the discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. GitHub is intended for bug reports and compile errors.
