### ISSUE TITLE
[VoxelGridCovariance] The covariance calculation is wrong(leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points; should be leaf.cov_ *= leaf.nr_points/ (leaf.nr_points - 1.0) ;)

### ISSUE THREAD

**Issue by chx725** [PointCloudLibrary/pcl#5341]
**Describe the bug**
The covariance calculation is wrong, leaf.cov_ *= (leaf.nr_points - 1.0) / leaf.nr_points  should be  leaf.cov_ *= leaf.nr_points/ (leaf.nr_points - 1.0) ;

**Context**

What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world

**Expected behavior**

**Current Behavior**

What happens instead of the expected behavior?

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. If you load data e.g. from a PCD or PLY file, please provide the file.

**Screenshots/Code snippets**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 18.04]
 - Compiler: [GCC 7.5.0]
 - PCL Version [1.8]

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by mvieth** [comment]
@chx725 It looks like you are referring to an old version of PCL. The current code doesn't have that line any more: https://github.com/PointCloudLibrary/pcl/blob/master/filters/include/pcl/filters/impl/voxel_grid_covariance.hpp
If you still think there is something wrong with the current code, please say so, otherwise I will close this issue.
