### ISSUE TITLE
[compile error] some hpp files can't open when i compilating pcl by myself

### ISSUE THREAD

**Issue by Bzz2745** [PointCloudLibrary/pcl#5343]
some *.hpp files like boost/mpl/assert.hpp can't open while i compilating pcl form source.
![image](https://user-images.githubusercontent.com/68807654/180435975-2c1c3771-41bf-4853-a4ee-c69c01e84276.png)
![image](https://user-images.githubusercontent.com/68807654/180436646-951e2868-fdac-46b4-9bbb-43ff8db99aae.png)
![image](https://user-images.githubusercontent.com/68807654/180436720-1106cc16-0754-4514-a7ae-36817d5722d9.png)

 - OS: Windows11
 - Compiler: Visual Studio 2019
 - PCL Version 1.12
 - PCL Type: Compiled from source
 - GPU,  CUDA enabled
 - boost 1.78(all are form all in one installer)
 - debug x64

How can i solve this?

**Comment by Bzz2745** [comment]
![image](https://user-images.githubusercontent.com/68807654/180436979-648d4b5d-5f5e-4348-856f-7d6ac6ee87e5.png)
here is the cmake setting of boost

**Comment by mvieth** [comment]
@Bzz2745 I am not very familiar with the all-in-one installer, but I believe that you have to install Boost in some other way if you want to compile PCL yourself, because the all-in-one installer doesn't contain all necessary header files.

**Comment by Bzz2745** [comment]
> @Bzz2745 I am not very familiar with the all-in-one installer, but I believe that you have to install Boost in some other way if you want to compile PCL yourself, because the all-in-one installer doesn't contain all necessary header files.

and another .hpp files also could found.......

**Comment by mvieth** [comment]
@Bzz2745 Can you try adding `/boost-1_78` at the end of CMake's `Boost_INCLUDE_DIR`

**Comment by Bzz2745** [comment]
> @Bzz2745 Can you try adding `/boost-1_78` at the end of CMake's `Boost_INCLUDE_DIR`

i have alreay try it,but it doesn't work....

**Comment by mvieth** [comment]
@larshg Can you take a look

**Comment by danielTobon43** [comment]
As a @mvieth mentioned @Bzz2745 you shou compile boost from source: Check this gist for compiling Boost on windows using MinGW https://gist.github.com/sim642/29caef3cc8afaa273ce6

**Comment by Bzz2745** [comment]
I have successfully compiled pcl (except kinfu), the reason for the error that I cannot find the .hpp file before is that nvcc does not correctly recognize my relative path, I don't know if it is my setting is wrong or it is just like this (so I Use notepad++ to change all the paths of the included boost header files in the generated files of the boost library compiled by myself to absolute paths, and do the same for the projects generated by CMAKE.). Hopefully this problem can be solved in the future, because it's really tortured.
Finally, thanks to everyone who answered my question.

**Comment by danielTobon43** [comment]
Hi @Bzz2745, you should close this issue if is already resolved.
