### ISSUE TITLE
what unit of  icp.getFinalTransformation result matrix? meter?

### ISSUE THREAD

**Issue by JACKLiuDay** [PointCloudLibrary/pcl#5355]
Hi, thank you for your great work about pcl. I want to know the result matrix of getFinalTransformation() unit. We all know the result matrix is [  r   r   r     t  ] ， the t is translation vector. But I do not know the unit of t. Is it meters? And the rotation unit is what for r?
              [  r   r   r     t   ] 
              [  r   r   r     t   ] 
              [  0  0   0    1  ] 

![image](https://user-images.githubusercontent.com/30967867/180955791-1ea465fe-4fdd-4436-811d-df6d03a86c69.png)

**Comment by mvieth** [comment]
The unit of the translation vector is the same unit as your point clouds. Could be meters, but you have to check the specifications of your sensor to know for sure.
The rotation matrix doesn't have any unit. All entries are between -1 and 1, and you can multiply it with a 3x1 vector to get the rotated vector.

**Comment by JACKLiuDay** [comment]
> The unit of the translation vector is the same unit as your point clouds. Could be meters, but you have to check the specifications of your sensor to know for sure. The rotation matrix doesn't have any unit. All entries are between -1 and 1, and you can multiply it with a 3x1 vector to get the rotated vector.

Hi, thank you so much for your reply. I am using velodyne-16. So I need to check out the velodyne-16 pointcloud unit. Is that right?

**Comment by mvieth** [comment]
Whether you are using ROS or not is likely not relevant, assuming the ROS package doesn't scale the pointcloud data.
Yes, you have to find out in which unit the velodyne-16 sensor returns the point clouds. I can't tell you where you find that information, maybe some datasheet/forum/manufacturer website.
