### ISSUE TITLE
[IO] Generating point cloud using kinect and kinect sdk

### ISSUE THREAD

**Issue by Vincent-Tann** [PointCloudLibrary/pcl#5356]
I'm using kinect sdk to get color and depth data and generating cloudpoint with them.
```
CameraSpacePoint rgb2camera[colorwidth*colorheight]; //  a mapping table 
ICoordinateMapper* mapper;         // Converts between depth, color, and 3d coordinates
PointCloud<PointXYZ>::Ptr cloud_origin(new PointCloud<PointXYZ>);
...
mapper->MapColorFrameToCameraSpace(width*height, buf, colorwidth*colorheight, rgb2camera);
```

With the last line, I store the coordinates(in camera coordinate system) of every pixels in the color picture. Now I want to store them in the format of organized point cloud, that is, using variable 'cloud_origin', then do some filtering and featuring work.
I'm new to pcl, could anyone tell me a proper and efficient way to generate the organized point cloud？ 
By the way, the definition of CameraSpacePoint is:

```
typedef struct _CameraSpacePoint
    {
    float X;
    float Y;
    float Z;
    } 	CameraSpacePoint;
```

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors. Two for-loops like this `for(...) { for(...) { /*copy x, y, z*/ } }` should probably do what you want
