### ISSUE TITLE
[segmentation] undocumented dependency for 'features' module

### ISSUE THREAD

**Issue by balthasarschuess** [PointCloudLibrary/pcl#5357]
**Context**
Building pcl library only with required modules.

Disabled non required modules for segmentation https://pointclouds.org/documentation/group__segmentation.html
with command line options like `-DBUILD_features=OFF`.

**Expected behavior**

Segmentation library should be built.

**Current Behavior**

 `-DBUILD_features=OFF` implicitly disables module segmentation as well.
 The dependency should be documented.

**Possible solution
Dependency should be confirmed and documented.

**Comment by mvieth** [comment]
Yes, the `UnaryClassifier` and the `SupervoxelClustering` from the segmentation module need things from the features module.
With "documented", do you mean to just enter it in the list of "Requirements" [here](https://pointclouds.org/documentation/group__segmentation.html)? If you like, you can open a pull request to do that, see this file: https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/segmentation.doxy

**Comment by balthasarschuess** [comment]
Yes, that's exactly what I meant and I'll create one. 
Thanks!
