### ISSUE TITLE
[compile error] "ConditionalEuclideanClustering"

### ISSUE THREAD

**Issue by sagarkalburgi** [PointCloudLibrary/pcl#5368]
Hi, 
I'm currently referring to the tutorial : 
`https://pcl.readthedocs.io/projects/tutorials/en/master/conditional_euclidean_clustering.html#conditional-euclidean-clustering`
and the build fails with the following errors: 

`1>region_growing_segmentation.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl pcl::NormalEstimation<struct pcl::PointXYZI,struct pcl::PointXYZINormal>::computeFeature(class pcl::PointCloud<struct pcl::PointXYZINormal> &)" (?computeFeature@?$NormalEstimation@UPointXYZI@pcl@@UPointXYZINormal@2@@pcl@@MEAAXAEAV?$PointCloud@UPointXYZINormal@pcl@@@2@@Z)`
`1>region_growing_segmentation.obj : error LNK2019: unresolved external symbol "public: void __cdecl pcl::ConditionalEuclideanClustering<struct pcl::PointXYZINormal>::segment(class std::vector<struct pcl::PointIndices,class std::allocator<struct pcl::PointIndices> > &)" (?segment@?$ConditionalEuclideanClustering@UPointXYZINormal@pcl@@@pcl@@QEAAXAEAV?$vector@UPointIndices@pcl@@V?$allocator@UPointIndices@pcl@@@std@@@std@@@Z) referenced in function "int __cdecl conditionalEuclideanClustering(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?conditionalEuclideanClustering@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
`

I am currently using windows 10 local machine and building it on VS19.

**Comment by mvieth** [comment]
How did you install PCL?

**Comment by sagarkalburgi** [comment]
Yes, I installed PCL using the following issue #4462. 
I am able to build and run other tutorials such as [Region growing segmentation](https://pcl.readthedocs.io/projects/tutorials/en/master/region_growing_segmentation.html#region-growing-segmentation) and [Filtering a PointCloud using ModelOutlierRemoval](https://pcl.readthedocs.io/projects/tutorials/en/master/model_outlier_removal.html#model-outlier-removal) but, not able to build [Conditional Euclidean Clustering](https://pcl.readthedocs.io/projects/tutorials/en/master/conditional_euclidean_clustering.html#conditional-euclidean-clustering).

**Comment by mvieth** [comment]
Try adding `#define PCL_NO_PRECOMPILE 1` at the top of the code. The All-In-One installer doesn't contain instantiation of all possible point type combinations. See also here: https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html

**Comment by sagarkalburgi** [comment]
I am getting the following error after adding `#define PCL_NO_PRECOMPILE 1`:
`fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`

**Comment by mvieth** [comment]
Google suggests:
- https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128?view=msvc-170
- https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-170
- https://stackoverflow.com/questions/8225078/how-to-set-compile-flag-bigobj-in-visual-studio

**Comment by sagarkalburgi** [comment]
Thank you the second link resolved the issue :)
