### ISSUE TITLE
PCLVisualizer Coordinate System

### ISSUE THREAD

**Issue by FeiSong123** [PointCloudLibrary/pcl#5374]
I am new in PCL and I have a question on PCLVisualizer. I use realsense device to generate pointCloud whose X positive is right, Y positive is down, but when I show it to PCLVisualizer, it seems like that X is reversed. I have tried to use addCoordinateSystem (double scale, const Eigen::Affine3f& t, int viewport), but it seemed like that only coordinate axis were changed and coordinate system unchanged.How can I change it ?

**Comment by mvieth** [comment]
You probably just have to flip/mirror the cloud with regard to the x-axis, e.g. with `transformPointCloud`

**Comment by FeiSong123** [comment]
I don't want to change my pointCloud's coordinate system but to change PCLVisualizer's, is there any way?

**Comment by mvieth** [comment]
If I understood your question correctly, there is no other way than to flip/mirror the cloud, but you can try asking on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community)
