### ISSUE TITLE
How use gicp to realize localization in a big pcd map? NDT or fast gicp or anything else?

### ISSUE THREAD

**Issue by JACKLiuDay** [PointCloudLibrary/pcl#5376]
Hi, thank you for your great work about pcl. I built a pcd map with velodyne-16 by using lio-sam algorithm. And I try to use NDT to get the tansformation of the velodyne pointcloud with the built map. This means that I am able to localize the robot in real time. It worked when I use NDT. Now I want to use GICP of pcl to do the same thing. I set the input target pointcloud and the source pointcloud, just like how I used it with NDT. But the transformation is not the same with NDT result. 
So I have a question. Dose gicp or icp only fit with two lidar scan registration. And it can not work with localization in a map. Is that right?

https://github.com/SMRT-AIST/fast_gicp
And this link has many registration methods. Does all of them work with localization? Or only NDT can achieve this function？

**Comment by mvieth** [comment]
> Now I want to use GICP of pcl to do the same thing

Out of interest: why do you want to use GICP when NDT worked?

> But the transformation is not the same with NDT result

Not _exactly_  the same, but close? Or completely different, meaning a wrong transformation?

> Dose gicp or icp only fit with two lidar scan registration. And it can not work with localization in a map. Is that right?

Is the question whether ICP/GICP can work if the target cloud (map) is much larger/has much more points than the source cloud (single scan)? I would say they can still work in such a situation.

It is important to understand that ICP and GICP work very locally. So they may return wrong results if you don't give them a good initial guess. In localization, you usually have an idea where the robot is (from past time steps). I am not so familiar with NDT, but I think it can find a good solution even with a bad initial guess.

**Comment by JACKLiuDay** [comment]
> > Now I want to use GICP of pcl to do the same thing
> 
> Out of interest: why do you want to use GICP when NDT worked?
> 
> > But the transformation is not the same with NDT result
> 
> Not _exactly_ the same, but close? Or completely different, meaning a wrong transformation?
> 
> > Dose gicp or icp only fit with two lidar scan registration. And it can not work with localization in a map. Is that right?
> 
> Is the question whether ICP/GICP can work if the target cloud (map) is much larger/has much more points than the source cloud (single scan)? I would say they can still work in such a situation.
> 
> It is important to understand that ICP and GICP work very locally. So they may return wrong results if you don't give them a good initial guess. In localization, you usually have an idea where the robot is (from past time steps). I am not so familiar with NDT, but I think it can find a good solution even with a bad initial guess.

Hi, thank you so much for your reply. 
I thought gicp is more accurate. So I want to compare the transformation result with GICP and NDT. Because I want to realize more accurate localization. My project need to be 5cm positioning error. When I use RTK to detect NDT positioning error with the evo tools. I found the mean error is 20cm. That's why I want to try GICP or other registration to improve positioning accuracy.

I tried a small map indoor as the input target pointcloud. And the next one is the source pointcloud. The source cloud is the map's fist scan. 
![微信图片_20220813172529](https://user-images.githubusercontent.com/30967867/184478052-e6bad98f-1c50-48d1-b6fd-6e9d8283e701.jpg)

![微信图片_20220813172534](https://user-images.githubusercontent.com/30967867/184478115-3a11bb50-eaf5-4a20-969c-836abbf667f8.jpg)
When I ran the program, the result was shown below.
![微信图片_20220813172537](https://user-images.githubusercontent.com/30967867/184478139-e689394c-4d81-49b2-a938-b17f85fa12cd.jpg)

It looks like the transformation varies a lot between different methods. The result should be 0 0 0 for the x,y,z position. So my question is :  if the target cloud (map) is much larger than the source cloud, does ICP or other registration method work? If it works, why the result is not the same. I set the filter param 0.1f for both target and source. And NDT resolution is 1.0.

Actually my map is the whole campus. It's really big about 1G. You say ICP or GICP can work in my situation. Just I need to provide a good initial value. So you mean when I try to use reg.align(*output, xxxxx), I have to set a good initial position with xxxxx param. Is there a quantitative standard for this initial value? 

For NDT, you are right. I tested it in my campus with the map. It worked well with a not so good initail guess.

**Comment by mvieth** [comment]
> So my question is : if the target cloud (map) is much larger than the source cloud, does ICP or other registration method work?

I think I already answered this in my last comment: Yes, I would say they can still work, at least ICP and GICP.

> Just I need to provide a good initial value. So you mean when I try to use reg.align(*output, xxxxx), I have to set a good initial position with xxxxx param. Is there a quantitative standard for this initial value?

I assume you run the localization in a loop: new scan -> register scan -> new scan -> register scan -> ... Then the last localization (the transformation from the previous registration) is a good initial guess.

If NDT is for some reason not accurate enough, you could try running first NDT and then ICP or GICP with the result you got from NDT.

One last thing: For questions specifically about the project you linked (https://github.com/SMRT-AIST/fast_gicp), you should ask there. I can't say anything about "fgicp", "vgicp", ... Your questions would anyway be better suited for [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community). The GitHub issues are intended for bug reports and compile errors.

**Comment by JACKLiuDay** [comment]
> > So my question is : if the target cloud (map) is much larger than the source cloud, does ICP or other registration method work?
> 
> I think I already answered this in my last comment: Yes, I would say they can still work, at least ICP and GICP.
> 
> > Just I need to provide a good initial value. So you mean when I try to use reg.align(*output, xxxxx), I have to set a good initial position with xxxxx param. Is there a quantitative standard for this initial value?
> 
> I assume you run the localization in a loop: new scan -> register scan -> new scan -> register scan -> ... Then the last localization (the transformation from the previous registration) is a good initial guess.
> 
> If NDT is for some reason not accurate enough, you could try running first NDT and then ICP or GICP with the result you got from NDT.
> 
> One last thing: For questions specifically about the project you linked (https://github.com/SMRT-AIST/fast_gicp), you should ask there. I can't say anything about "fgicp", "vgicp", ... Your questions would anyway be better suited for [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community). The GitHub issues are intended for bug reports and compile errors.

Hi, thank you so much for your patient reply. This helped me a lot.
