### ISSUE TITLE
[compile error] "vtk undefined reference to MPI, how can I solve this"

### ISSUE THREAD

**Issue by ChenGY-THU** [PointCloudLibrary/pcl#5377]
/usr/bin/ld: warning: libmpi.so.12, needed by /usr/local/lib/libvtkIOMPIImage-7.1.so.1, not found (try using -rpath or -rpath-link)
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_File_read'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Comm_rank'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Abort'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Waitany'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_Type_create_subarray'
/usr/local/lib/libvtkIOMPIParallel-7.1.so.1: undefined reference to `MPI_File_get_position'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Init'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_File_get_size'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Scatterv'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_Type_free'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_group'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_split'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_Error_string'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Waitsome'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Allreduce'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_set_errhandler'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_File_close'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Recv'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Wait'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Testsome'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Op_create'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_Get_elements'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Request_free'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Ssend'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Test'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Get_processor_name'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_create_errhandler'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Comm_size'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Waitall'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_dup'
/usr/local/lib/libvtkIOMPIParallel-7.1.so.1: undefined reference to `MPI_File_seek'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Get_count'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Op_free'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_create'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Errhandler_free'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Group_incl'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_File_set_view'
/usr/local/lib/libvtkIOMPIParallel-7.1.so.1: undefined reference to `MPI_File_read_at'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Bcast'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Scatter'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Iprobe'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Probe'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Testall'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Allgatherv'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_File_open'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Cancel'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Send'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Testany'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Irecv'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Comm_free'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Reduce'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Gatherv'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Allgather'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Isend'
/usr/local/lib/libvtkIOMPIParallel-7.1.so.1: undefined reference to `MPI_File_read_all'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Finalize'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Gather'
/usr/local/lib/libvtkParallelMPI-7.1.so.1: undefined reference to `MPI_Group_free'
/usr/local/lib/libvtkFiltersParallelDIY2-7.1.so.1: undefined reference to `MPI_Barrier'
/usr/local/lib/libvtkIOMPIImage-7.1.so.1: undefined reference to `MPI_Type_commit'

**Comment by cybaol** [comment]
it seems like you need to recompile `VTK`

**Comment by mvieth** [comment]
@ChenGY-THU 
- Which operating system do you use?
- Which PCL version do you use?
- Which compiler do you use?

**Comment by mvieth** [comment]
Closing because of no response.
