### ISSUE TITLE
[custom] How to change the shape of points in the point cloud

### ISSUE THREAD

**Issue by CGuangyan-BIT** [PointCloudLibrary/pcl#5380]
I rebuild PCL and found that the shape of points in the point cloud changes (sphere before and square after), and I prefer the sphere, how can I change the shape of points?
Before
![image](https://user-images.githubusercontent.com/96285708/184571201-1b7a2d34-7220-410b-8b9c-a7b308ad3d69.png)
As shown in the figure, the shape of the points before is a sphere.
After
![after](https://user-images.githubusercontent.com/96285708/184603088-53304ea0-1bfb-493d-a5a2-220e008a16a4.jpg)
and now become square

**Comment by mvieth** [comment]
@CGuangyan-BIT What operating system do you use? Which PCL version did you use before and which one now? Which VTK version do you use?

**Comment by CGuangyan-BIT** [comment]
It's hard for me to enumerate what I did due to a long time between installs, I think the version is 1.12 before and after, and I am sorry to forget the version of VTK before, the version of VTK is 7.1.1 now. Do you know what's causing this, it's very important to me, thank you!

**Comment by CGuangyan-BIT** [comment]
> @CGuangyan-BIT What operating system do you use? Which PCL version did you use before and which one now? Which VTK version do you use?

It's hard for me to enumerate what I did due to a long time between installs, I think the version is 1.12 before and after, and I am sorry to forget the version of VTK before, the version of VTK is 7.1.1 now. Do you know what's causing this, it's very important to me, thank you!

**Comment by mvieth** [comment]
@CGuangyan-BIT And you think you had a different VTK version before you rebuilt PCL? Which class are you using to display the clouds? Which operating system do you use? You are giving me very little information, which makes it much harder to suggest a solution to you ...

**Comment by CGuangyan-BIT** [comment]
> @CGuangyan-BIT And you think you had a different VTK version before you rebuilt PCL? Which class are you using to display the clouds? Which operating system do you use? You are giving me very little information, which makes it much harder to suggest a solution to you ...

Thank you for your suggestion, I change the version of PCL and VTK to 1.8.0 and 6.3, and the shape becomes the sphere.

**Comment by mvieth** [comment]
Interesting, I didn't know that the shape changed from sphere in VTK 6 to square in VTK 7 and newer.
Might also be possible to choose spheres in newer VTK versions: https://vtk.org/doc/nightly/html/classvtkProperty.html#a299ff684fcb7cdd2c53c68567e7f7e82
I am closing this issue, since you achieved what you wanted
