### ISSUE TITLE
error: ‘Index’ is not a member of ‘Eigen’

### ISSUE THREAD

**Issue by wanesta** [PointCloudLibrary/pcl#5381]
**Describe the error**
I'm trying to install pcl on ubuntu18.04 get this error ：
[ 17%] Building CXX object sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cone.cpp.o
[ 17%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ply_io.cpp.o
In file included from /home/gaosm/Downloads/pcl/sample_consensus/src/sac_model_circle3d.cpp:38:0:
/home/gaosm/Downloads/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle3d.hpp: In member function ‘void pcl::SampleConsensusModelCircle3D<PointT>::optimizeModelCoefficients(const Indices&, const VectorXf&, Eigen::VectorXf&) const’:
/home/gaosm/Downloads/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle3d.hpp:281:15: error: ‘Index’ is not a member of ‘Eigen’
   for (Eigen::Index i = 0; i < coeff.size (); ++i)
               ^~~~~
/home/gaosm/Downloads/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle3d.hpp:281:28: error: ‘i’ was not declared in this scope
   for (Eigen::Index i = 0; i < coeff.size (); ++i)
                            ^
[ 17%] Linking CXX shared library ../lib/libpcl_kdtree.so
[ 17%] Building CXX object io/CMakeFiles/pcl_io.dir/src/ascii_io.cpp.o
[ 17%] Built target pcl_kdtree

I download source code with git, and I am try two version with 1.12.1 and 1.11.1, get the same error.
**Screenshots/Code snippets/Build information**
![截屏2022-08-16 10 24 44](https://user-images.githubusercontent.com/8255532/184785106-5f6bb504-70b5-4ce3-a2f5-6d56350f609b.png)

 - OS: [Ubuntu 18.04]
 - Compiler: [GCC 7.5.0]
 - Cmake:[ 3.10.2 ]
 - PCL Version [1.12.1  &  1.11.1] ( Two version,  the same error. )
 - Eigen Version: [ 3.1.4 ]

**Possible Solution**

**Additional context**

**Comment by mvieth** [comment]
@wanesta Is there a reason why you don't install Eigen with apt (you get Eigen version 3.3.4), but use an older version instead? With Eigen 3.3.4, it will work.

**Comment by wanesta** [comment]
> 

I change eigen3 version to 3.3.4 and install pcl 1.11.1 get this error:

[ 45%] Linking CXX executable ../bin/pcl_passthrough_filter
[ 45%] Built target pcl_passthrough_filter
[ 45%] Building CXX object features/CMakeFiles/pcl_features.dir/src/flare.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
surface/CMakeFiles/pcl_surface.dir/build.make:254: recipe for target 'surface/CMakeFiles/pcl_surface.dir/src/mls.cpp.o' failed
make[2]: *** [surface/CMakeFiles/pcl_surface.dir/src/mls.cpp.o] Error 4
CMakeFiles/Makefile2:1136: recipe for target 'surface/CMakeFiles/pcl_surface.dir/all' failed
make[1]: *** [surface/CMakeFiles/pcl_surface.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Linking CXX executable ../bin/pcl_radius_filter
[ 45%] Building CXX object features/CMakeFiles/pcl_features.dir/src/cppf.cpp.o
[ 45%] Building CXX object features/CMakeFiles/pcl_features.dir/src/cvfh.cpp.o
[ 45%] Linking CXX executable ../bin/pcl_local_max
[ 45%] Building CXX object features/CMakeFiles/pcl_features.dir/src/boundary.cpp.o
[ 45%] Linking CXX shared library ../lib/libpcl_tracking.so
[ 46%] Building CXX object features/CMakeFiles/pcl_features.dir/src/brisk_2d.cpp.o
[ 47%] Building CXX object features/CMakeFiles/pcl_features.dir/src/our_cvfh.cpp.o
[ 47%] Building CXX object features/CMakeFiles/pcl_features.dir/src/crh.cpp.o
[ 47%] Built target pcl_radius_filter
[ 47%] Building CXX object features/CMakeFiles/pcl_features.dir/src/don.cpp.o
[ 47%] Built target pcl_local_max
[ 48%] Building CXX object features/CMakeFiles/pcl_features.dir/src/fpfh.cpp.o
[ 48%] Built target pcl_tracking
[ 48%] Building CXX object features/CMakeFiles/pcl_features.dir/src/from_meshes.cpp.o

**Comment by mvieth** [comment]
@wanesta Compiling mls.cpp in the surface module needs a lot of RAM (working memory).
- make sure you have enough free RAM by closing all other programs during compiling and use only one build job (`make -j1`)
- if that doesn't work, you can try the option `PCL_ONLY_CORE_POINT_TYPES`
- if that still doesn't work, try the option `PCL_NO_PRECOMPILE`

Remember to do a full rebuild each time (delete all previously built files)

**Comment by wanesta** [comment]
> @wanesta Compiling mls.cpp in the surface module needs a lot of RAM (working memory).
> 
> * make sure you have enough free RAM by closing all other programs during compiling and use only one build job (`make -j1`)
> * if that doesn't work, you can try the option `PCL_ONLY_CORE_POINT_TYPES`
> * if that still doesn't work, try the option `PCL_NO_PRECOMPILE`
> 
> Remember to do a full rebuild each time (delete all previously built files)

Thank you very much
