### ISSUE TITLE
pcl::GeneralizedIterativeClosestPoint::computeCovariances] Number or points in cloud (1) is less than k_correspondences_ (20)

### ISSUE THREAD

**Issue by JACKLiuDay** [PointCloudLibrary/pcl#5382]
![image](https://user-images.githubusercontent.com/30967867/184811293-9465cb06-014a-44c6-ba6e-5f25662a09dc.png)

Hi, thank you for your guys great work about pcl. I have some problem when I use GICP to registration in a big pcd map. It shows some error and I don't why. When I use NDT to registration. It has no error.

**Comment by mvieth** [comment]
@JACKLiuDay It seems one of your clouds only has one point. Check how many points the clouds have that you give to `GeneralizedIterativeClosestPoint`

**Comment by JACKLiuDay** [comment]
> @JACKLiuDay It seems one of your clouds only has one point. Check how many points the clouds have that you give to `GeneralizedIterativeClosestPoint`

OK, thank you for your reply. I will test the cloud size in my program.
