### ISSUE TITLE
Does positioning in a pre-built pcd map require motion distortion correction for real-time laser point clouds?

### ISSUE THREAD

**Issue by JACKLiuDay** [PointCloudLibrary/pcl#5388]
Hi, thank you for your great work about pcl.
I am working on a project with my robot. I built a map using LIO-SAM. And I save the map as a pcd file. Then I load the pcd map for localization in my campus. I set the map pointcloud and the source pointcloud with velodyne-16 real-time data. And the GICP works well. I can localize my robot in the map. But I have a question. When my robot moves about 0.5m/s-1m/s. Suppose the robot is moving at 1m/s，do we need to perform motion distortion correction on the real-time laser point cloud before performing the registration operation? That's my first question. My second question is: if we need to perform motion distortion correction, should this operation be placed before or after the filtering operation?

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such application-specific questions. The GitHub issues are intended for bug reports and compile errors.
