### ISSUE TITLE
Eigen: switch to imported modules and NO_MODULE?

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#5393]
As you require Eigen 3.3 now, you could also switch to imported modules & `NO_MODULE`: https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html, so you could remove `FindEigen.cmake`.

_Originally posted by @SunBlack in https://github.com/PointCloudLibrary/pcl/issues/5383#issuecomment-1219426387_

**Comment by ptrckschcknbch** [comment]
Hi @mvieth, I had a short look into this issue and I guess I could solve the request. Would it be fine for you if I'd take this up?

**Comment by larshg** [comment]
It would be very welcome, @ptrckschcknbch. Please go ahead.
