### ISSUE TITLE
compile failure <pcl/gpu/surface/convex_hull.h>

### ISSUE THREAD

**Issue by yuyu19970716** [PointCloudLibrary/pcl#5407]
Hello, why can't you import < pcl/gpu/surface/conv3x_hull.h > after installing pcl1.9, and show that there is no such file? I import other header files and it's okay, except for the GPU. After I compiled the pcl, there was no gpu and cuda folder. What is the reason for this?

**Comment by mvieth** [comment]
@yuyu19970716 Just to be sure, you tried to include `convex_hull.h`, right? Because `conv3x_hull.h` indeed does not exist.
Which operating system do you use? How did you install PCL 1.9? Do you have CUDA installed? (I mean CUDA in general, not PCL's CUDA submodule)

**Comment by yuyu19970716** [comment]
I'm sorry I wrote it wrong, I did import convec_hull.h and then failed to import, showing: fatal error: pcl/gpu/surface/convex_hull.h: There is no that file or directory.
The system I use is ubuntu18,04 .
The method I used to install pcl1.9 is to install from source: here are the installation steps:
cd pcl
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr \ -DBUILD_GPU=ON-DBUILD_apps=ON -DBUILD_examples=ON \ -DCMAKE_INSTALL_PREFIX=/usr ..
make  
sudo make install

My system's CUDA is 11.4：
![image](https://user-images.githubusercontent.com/76560812/187066958-aff2f41f-bc5d-47d6-ba0b-223d9da916fe.png)



Can you please see which step I have made a mistake? We look forward to hearing from you!

**Comment by yuyu19970716** [comment]
When I installed the pcl, there was no GPU and cuda file after running the compile command, I think it may be a problem with cuda, but I don't know what the problem is?

**Comment by yuyu19970716** [comment]
Whenever I run cmake to install pcl, it shows these: I know that my vtk version does not correspond, but I don't need to do visualization here, so please help me to see what the problem is?
![image](https://user-images.githubusercontent.com/76560812/187070541-7be3128e-cc3a-4728-ba40-0432498981d9.png)
![image](https://user-images.githubusercontent.com/76560812/187070562-0939e9ba-a382-4f1f-b507-1e7dc15b0d11.png)
![image](https://user-images.githubusercontent.com/76560812/187070576-f63be3ae-f2bd-46a1-8a4d-1dcf1b327ab7.png)
![image](https://user-images.githubusercontent.com/76560812/187070586-211998cc-d5b3-42e5-8839-7aaa5a32e353.png)

**Comment by mvieth** [comment]
@yuyu19970716 Can you delete the `release` directory and run the first few steps again:
cd pcl
mkdir release
cd release
cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/usr  -DBUILD_GPU=ON -DBUILD_apps=ON -DBUILD_examples=ON  -DCMAKE_INSTALL_PREFIX=/usr ..
And please post the output of the cmake command. When you run it for the first time in an empty directory, it should print something about CUDA (for example that CUDA was found or not found and why)

**Comment by yuyu19970716** [comment]
Thank you very much for your reply. I recreated the release folder as you said. After running cmake, the following is displayed：


![image](https://user-images.githubusercontent.com/76560812/187077675-d654a37e-e2d3-4b07-9c37-228055c0fbe4.png)
![image](https://user-images.githubusercontent.com/76560812/187077686-c62b31b0-fbc1-4281-a826-efe64884fd00.png)
![image](https://user-images.githubusercontent.com/76560812/187077709-4c9ce226-77d4-4b0c-857c-9116a55390d8.png)
![image](https://user-images.githubusercontent.com/76560812/187077732-fed492ef-7f24-43e9-a072-01d7bfe87c58.png)
![image](https://user-images.githubusercontent.com/76560812/187077753-152b0333-860b-4d49-8f73-5b7f5e832ac7.png)

**Comment by mvieth** [comment]
@yuyu19970716 How did you install CUDA on your system? It seems CMake cannot find CUDA. You might get more information if you change this line in the PCL sources to `FALSE`: https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.1/cmake/pcl_find_cuda.cmake#L8

**Comment by yuyu19970716** [comment]
Oh! I changed it to false and it did show that CUDA could not be found! I ran the program on the lab server, which was CUDA installed by my teacher at the time
![image](https://user-images.githubusercontent.com/76560812/187081498-4da25b1f-001b-4cfb-8dca-e728b25cbbcf.png)

**Comment by mvieth** [comment]
Then there doesn't seem to be any problem on the PCL side. Make sure that CUDA is correctly installed and PCL will find it and compile the GPU and CUDA submodules as you requested. These might help you:
https://cmake.org/cmake/help/v3.10/module/FindCUDA.html
https://stackoverflow.com/questions/19980412

**Comment by yuyu19970716** [comment]
OK! Thanks so much for your answer! I'll take a hard look at the method you've provided!
