### ISSUE TITLE
Unable to import GPU-related header files

### ISSUE THREAD

**Issue by yuyu19970716** [PointCloudLibrary/pcl#5409]
Hello, after I installing the PCL library with CUDA and importing < pcl/gpu/containers/device_array.h> in my .cpp file,it will show:
![image](https://user-images.githubusercontent.com/76560812/187134685-d3550356-3364-48f5-bc15-274410f92eef.png)
Is it the reason why the GPU was not compiled at the time of compilation? I found that it didn't display the GPU information when I compiled the PCL
![image](https://user-images.githubusercontent.com/76560812/187135104-919a7402-2f98-449e-a0a2-62226bf94753.png)

**Comment by mvieth** [comment]
@yuyu19970716  So more or less the same problem as in https://github.com/PointCloudLibrary/pcl/issues/5407 ?
Do you give `-DBUILD_GPU=ON` and `-DBUILD_gpu_containers=ON` to the cmake call? Or have a look at `ccmake`.
And yes, `gpu_containers` and other GPU modules should be listed under `The following subsystems will be built` if you expect that they are built.

**Comment by yuyu19970716** [comment]
Thank you for your reply, I am using the company's server now, there is no visual interface here, so I can not use ccmake, I set in the command line using cmake:-DBUILD_gpu_contrainers etc. do not work:
![image](https://user-images.githubusercontent.com/76560812/187157393-629ac8ad-0b63-47e9-bd27-e854db82667a.png)
it will be:
![image](https://user-images.githubusercontent.com/76560812/187157459-27c3dd92-84c4-4b15-88f6-6f3317890185.png)
Now cuda seems to work, but the GPU doesn't compile properly. I'm only new to C++, and I'm sorry to bother you, but I really don't know what the problem is? I can't use ccmake to set these variables, and variables set on the command line can't be compiled.

**Comment by mvieth** [comment]
@yuyu19970716 Is there a reason why you use backslashes `\` in your command (three times)? I can't say for sure that they cause the problem, but they are not necessary and I would recommend to remove them.

**Comment by yuyu19970716** [comment]
Hahaha! It is indeed the reason for the "/": the gpu problem was solved, but I ran into the third problem, I think this is my last problem, I'm so sorry to bother you again, I dare not imagine such a twist. My GPU is 3090 and I should have set the hash rate to 8.6, but that doesn't work, can you see what this is like?
![image](https://user-images.githubusercontent.com/76560812/187167667-e657c472-9493-47a3-a202-3b84d47aa445.png)

![image](https://user-images.githubusercontent.com/76560812/187167621-f236c50a-c76a-4500-9953-9e504138873c.png)

**Comment by mvieth** [comment]
`set(__cuda_arch_bin "8.6")` in the first if-case should do what you want. Maybe delete your build folder again and do all commands again, including `cmake`. If that does not work, I would recommend trying a newer PCL version. PCL 1.9 is a few years old, and getting it to work with a very new GPU and CUDA might be difficult.

**Comment by yuyu19970716** [comment]
Thank you very much for your reply! At present, I have installed the relevant parts of the pcl_gpu in the cmake and make stages, after compiling and installing successfully, I found that I still can't find the GPU-related header file when compiling in my own project, I wonder if there is a problem with my cmakelists.
![1661918321147](https://user-images.githubusercontent.com/76560812/187589607-c5cc913e-5664-4405-a6a2-9c811f002064.png)
Below are the cmakelists for my project：
![1661918379816](https://user-images.githubusercontent.com/76560812/187589689-0a859cb5-1ef6-4fb9-94cc-e660702b94f9.png)
Below is my cpp file when importing GPU related files:
![1661918445436](https://user-images.githubusercontent.com/76560812/187589805-9e252a87-00cc-4035-a249-3f72f0aab2bc.png)
can you help me look at it? I very much look forward to your reply! Thanks in advance!

**Comment by mvieth** [comment]
@yuyu19970716 
1. Check again that `device_array.h`, `gp3.h`, and the other header files are correctly installed, somewhere in the `/usr` directory, probably in `/usr/include/pcl/...`
2. When you run cmake for your own project, does it find PCL? Does it report any errors?
3. In your CMakeLists.txt, you are calling `find_package` twice for PCL -- don't do that. Check out this tutorial: https://pcl.readthedocs.io/projects/tutorials/en/master/using_pcl_pcl_config.html It is easiest to request all existing PCL modules. You also don't need `${PCL_COMMON_LIBRARIES}` and `${PCL_IO_LIBRARIES}` if you link to `${PCL_LIBRARIES}`

**Comment by yuyu19970716** [comment]
Thank you for your patience! I did find libraries for GPUs and CUDA under usr/lib,
![1661932548779](https://user-images.githubusercontent.com/76560812/187624586-6adb11c0-6226-4693-bc9b-fe2a5445da64.png)
I'm running cmake in my project: When indicating the location of cuda, so it looks like this:
![1661932940478](https://user-images.githubusercontent.com/76560812/187625255-52872ca5-0583-4bcc-afaf-6a4b66e11586.png)
![1661932940486](https://user-images.githubusercontent.com/76560812/187625279-69718eaf-43d7-45f5-97ee-54c4a7cc9ff9.png)
![Uploading 1661932940494.jpg…]()
![Uploading 1661932940502.png…]()
3.When I changed the cmakelists to look like this:
![1661933211071](https://user-images.githubusercontent.com/76560812/187626459-3526717a-b34c-4c65-ab22-beded788c6d4.png)
When I cmake it goes like this, haha:
![1661933285092](https://user-images.githubusercontent.com/76560812/187626786-d91b9184-23a6-47b3-9048-d0a15e4d3c55.png)
Thank you again for your generosity, I really don't know how to express my gratitude! I wish you a smooth future!

**Comment by mvieth** [comment]
You are welcome. Best to you as well.
