### ISSUE TITLE
How to check if rtabmap PCL lib is CUDA supported or not in Nvidia Jetson AGX?

### ISSUE THREAD

**Issue by tugbakara** [PointCloudLibrary/pcl#5410]
Hi, to improve and take full of advantage of GPU of AGX Xavier, in rtabmap_ros package we are making map but I am not sure rtabmap's PCL lib is CUDA supported or not? Can I check it from terminal and how?

**Comment by larshg** [comment]
Looking at their github and searching for pcl/gpu, doesn't show any real hits: https://github.com/introlab/rtabmap/search?q=pcl%2Fgpu

So its not supported as I can see it. They have however support of some OMP classes.

Please use discord, stackoverflow or the like for questions. Github is for issues in PCL.

**Comment by tugbakara** [comment]
In issue of rtabmap_ros, there is an GPU accelartion when PCL and openCV is installed with CUDa rtabmap_ros will wwork ok with libs but I am sure that our openCV not supported and I will rebuild with CUDA but I am not sure PCL, and how can I check whether CUDA support is existing in my PCL lib or not. Which terminal command or anythingelse can tell me the answer? I wanna check PCL is CUDA supported or not related to that ans I will rebuild PCL wih CUDA supported.

**Comment by tugbakara** [comment]
Ah, I checked my pcl libs there is not any folder as gpu and cuda, so I don't have CUDA supported, I will try my chance to install PCL CUDA supported for rtabmap if it won't well I will add the outcomes here.
Thanks for the answers, have a nice day @larshg !

**Comment by FeiSong123** [comment]
Hi, I don't know much about how to compile cuda when installing pcl. Can you give me some reference materials? @tugbakara

**Comment by tugbakara** [comment]
> Hi, I don't know much about how to compile cuda when installing pcl. Can you give me some reference materials? @tugbakara 

Actually you don't really search about it, as @larshg mentioned earlier you can check the folders. Also there exist how to install PCL with CUDA documentation in its page, note that there are boost library dependencies about version etc. Be careful.
@FeiSong123

**Comment by FeiSong123** [comment]
All right, I have found it. Thanks.
