### ISSUE TITLE
How to generate faces with Fast unorganized mesh methode ? 

### ISSUE THREAD

**Issue by Amayess** [PointCloudLibrary/pcl#5411]
Hi,

In order to generate a mesh with the intel RealSense D455, I used the PCL library and more precisely the Fast Organized Mesh method. I manage to generate a mesh in OBJ format but it only contains vertices and no faces.

Here is the code I used:

	```
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	cloud->resize(size);

	for (int i = 0; i < size; i++)
	{
		cloud->at(i).x = Cloud[i].x;
		cloud->at(i).y = Cloud[i].y;
		cloud->at(i).z = Cloud[i].z;

	}

	std::cout << "Fast mesh started " << "\n";
	pcl::OrganizedFastMesh<pcl::PointXYZ>::Ptr orgMesh(new pcl::OrganizedFastMesh<pcl::PointXYZ());
	pcl::PolygonMesh triangles;
	orgMesh->setTriangulationType(pcl::OrganizedFastMesh<pcl::PointXYZ>::TRIANGLE_RIGHT_CUT);
	orgMesh->setInputCloud(cloud);
	orgMesh->reconstruct(triangles);
	std::cout << "start saving the fast mesh obj..." << "\n";
	pcl::io::saveOBJFile("Mesh.obj", triangles);
```

Can someone explain how to make the method generate faces too?

Thanks for your help.

**Comment by mvieth** [comment]
Please don't open a GitHub issue if you have already asked the same question on stackoverflow https://stackoverflow.com/questions/73554594
