### ISSUE TITLE
[Pointcloud / PointXYZI] Incorrect intensity values in Eigen matrix on calling `getMatrixXfMap()` 

### ISSUE THREAD

**Issue by MyronRodrigues-StreetDrone** [PointCloudLibrary/pcl#5412]
## Environment
Ubuntu 22.04 running 20.04 Docker

## Tested on versions
pcl-1.10
pcl-1.12.1

## Issue

Pointcloud of type `pcl::PointCloud<pcl::PointXYZI>` outputs an incorrect Eigen matrix with all intensity values as 1.

On running the following 

```cpp
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>

int main()
{
    pcl::PointCloud<pcl::PointXYZ> cldXYZ;

    int dx = 4;
    int dy = 3;

    for (int i = 0; i < dx; ++i)
    {
        for (int j = 0; j < dy; ++j)
        {
            float pt = static_cast<float>(i * dy + j);
            cldXYZ.push_back({pt, pt + 1.f, pt + 2.f});
        }
    }

    std::cout << "cldXYZ: \n"
              << cldXYZ.getMatrixXfMap(3, sizeof(pcl::PointXYZ) / sizeof(float), 0).transpose()
              << std::endl;

    pcl::PointCloud<pcl::PointXYZI> cldXYZI;

    for (int i = 0; i < dx; ++i)
    {
        for (int j = 0; j < dy; ++j)
        {
            float pt = static_cast<float>(i * dy + j);
            cldXYZI.push_back({pt, pt + 1.f, pt + 2.f, pt + 3.f});
        }
    }

    std::cout << "\ncldXYZI: \n"
              << cldXYZI.getMatrixXfMap(4, sizeof(pcl::PointXYZI) / sizeof(float), 0).transpose()
              << std::endl;

    return 0;
}
```

The output is

```bash
cldXYZ: 
 0  1  2
 1  2  3
 2  3  4
 3  4  5
 4  5  6
 5  6  7
 6  7  8
 7  8  9
 8  9 10
 9 10 11
10 11 12
11 12 13

cldXYZI: 
 0  1  2  1
 1  2  3  1
 2  3  4  1
 3  4  5  1
 4  5  6  1
 5  6  7  1
 6  7  8  1
 7  8  9  1
 8  9 10  1
 9 10 11  1
10 11 12  1
11 12 13  1
```

The expected output for `cldXYZI` should be

```bash
cldXYZI: 
 0  1  2  3
 1  2  3  4
 ...
 ...
```

**Comment by mvieth** [comment]
@MyronRodrigues-StreetDrone Point types in PCL contain padding to achieve alignment and to make SIMD instructions efficient. Following the x, y, and z values, there is always an additional float set to 1 to make affine transformations easy and fast. For `PointXYZI`, after x, y, z, and 1, the intensity value follows, then 3 more floats for padding and alignment. See also `point_types.hpp`. So if you set `dim` to 5 instead of 4, the intensity values should be contained in the matrix (last column). So this is not a bug, this is just how `getMatrixXfMap` works because the padding

**Comment by mvieth** [comment]
Assuming my last comment answered the question ...

**Comment by MyronRodrigues-StreetDrone** [comment]
Yes, thanks. Wonder if this needs to be mentioned in the documentation, or hinting to check point types.

**Comment by mvieth** [comment]
@MyronRodrigues-StreetDrone If you have a suggestion, feel free to comment it here or create a pull request

**Comment by MyronRodrigues-StreetDrone** [comment]
@mvieth Just tested the solution you proposed. Maybe im still messing up something, anything to do with the offset?

```cpp
std::cout << "\ncldXYZI: \n"
              << cldXYZI.getMatrixXfMap(5, sizeof(pcl::PointXYZI) / sizeof(float), 0).transpose()
              << std::endl;
```

Gives:
```bash
cldXYZI: 
 0  1  2  1  0
 1  2  3  1  0
 2  3  4  1  0
 3  4  5  1  0
 4  5  6  1  0
 5  6  7  1  0
 6  7  8  1  0
 7  8  9  1  0
 8  9 10  1  0
 9 10 11  1  0
10 11 12  1  0
11 12 13  1  0
```

**Comment by mvieth** [comment]
@MyronRodrigues-StreetDrone Which PCL version do you use in that test?
With the current master, this:
```c++
    int dx = 4;
    int dy = 3;

    pcl::PointCloud<pcl::PointXYZI> cldXYZI;

    for (int i = 0; i < dx; ++i)
    {
        for (int j = 0; j < dy; ++j)
        {
            float pt = static_cast<float>(i * dy + j);
            cldXYZI.push_back({pt, pt + 1.f, pt + 2.f, pt + 3.f});
        }
    }
  std::cout << "\ncldXYZI: \n"
              << cldXYZI.getMatrixXfMap(5, sizeof(pcl::PointXYZI) / sizeof(float), 0).transpose()
              << std::endl;
```
gives me:
```
cldXYZI: 
 0  1  2  1  3
 1  2  3  1  4
 2  3  4  1  5
 3  4  5  1  6
 4  5  6  1  7
 5  6  7  1  8
 6  7  8  1  9
 7  8  9  1 10
 8  9 10  1 11
 9 10 11  1 12
10 11 12  1 13
11 12 13  1 14
```

**Comment by MyronRodrigues-StreetDrone** [comment]
@mvieth Ohh, this I tested with `PCL 1.10`, any idea how I could make this work with it or where I should look up for answers?

**Comment by mvieth** [comment]
@MyronRodrigues-StreetDrone Maybe try setting the intensity directly (like `point.intensity = ...`) instead of setting it via the constructor, to test whether that could be the problem.

**Comment by MyronRodrigues-StreetDrone** [comment]
@mvieth Yup that worked and also the following

```cpp
cldXYZI.push_back( pcl::PointXYZI({pt, pt + 1.f, pt + 2.f, 1.f, pt + 3.f}));
std::cout << cldXYZI[i] << std::endl;
```
