### ISSUE TITLE
About 3D reconstruction using gpu acceleration

### ISSUE THREAD

**Issue by yuyu19970716** [PointCloudLibrary/pcl#5416]
Hello, I am using the greedy projection triangulation algorithm based on the pcl library to do 3D reconstruction recently. The reconstruction speed is very slow. I want to use the gpu to accelerate the greedy projection triangulation algorithm. But I didn't find a related method based on gpu acceleration. Could you please tell me the general idea? Do you have relevant code that you can recommend for me to learn from?
I'm very sorry to trouble you again!
Thanks in advance！
Looking forward to your reply!

**Comment by mvieth** [comment]
There is a tutorial about `GreedyProjectionTriangulation`: https://pcl.readthedocs.io/projects/tutorials/en/master/greedy_projection.html
It also mentions the paper that was the basis for the implementation. The code of `GreedyProjectionTriangulation` is in gp3.h and gp3.hpp. I am not aware that PCL has a GPU version of `GreedyProjectionTriangulation` or something comparable.

Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions in the future. The GitHub issues are intended for bug reports and compile errors.
