### ISSUE TITLE
 Will point cloud distortion caused by motion affect the registration results between point clouds？

### ISSUE THREAD

**Issue by JACKLiuDay** [PointCloudLibrary/pcl#5420]
Hi，thank you for your great work about PCL. I am using GICP to registration two pointcloud. While I have some questions. Will point cloud distortion caused by motion affect the registration results between point clouds？My robot shakes seriously when it moves. I tried to use IMU angular_velocity data to correct distortion of point cloud when rotated. When I display the point clouds before and after correction together, I find that there is no change.
![image](https://user-images.githubusercontent.com/30967867/189307208-cd04f395-936e-4097-ab64-216b813d60e1.png)

The two pointcloud is red and green. It can be seen they almost coincide. It confused me a lot.

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
