### ISSUE TITLE
[filters] FrustumCulling: allowing zero near plane distance to extract a cone

### ISSUE THREAD

**Issue by keineahnung2345** [PointCloudLibrary/pcl#5423]
Hi, I would like to extract a cone from point cloud, is there an existing way to do this? What I think of is allowing **near plane distance** to be zero so that all points nearer than far plane could be kept.

Also, in other cases, I would like to allow infinite far plane distance so that all points further than near plane could be kept.
.

**Comment by mvieth** [comment]
I see no reason against setting the near plane distance to zero or the far plane distance to something very large (or even infinity).
Just to be sure there is no misunderstanding: FrustumCulling uses a [square frustum](https://en.wikipedia.org/wiki/Frustum#/media/File:Square_frustum.png), not a [conical frustum](https://en.wikipedia.org/wiki/Frustum#/media/File:CroppedCone.svg)
The sample consensus module also has a cone model, but not sure if that is useful to you, depends on what you mean with "extract a cone": Keep all points inside the cone and remove all points outside, _or_ keep all points close to the cone surface.

**Comment by keineahnung2345** [comment]
Thanks for clarafication, I mean exactly square frustum. 
It seems it's valid to near plane distance to zero and it works as expected. I've created a PR for the infinite far plane distance feature.
