### ISSUE TITLE
[features] Crash when destroying SHOTEstimation

### ISSUE THREAD

**Issue by zamx** [PointCloudLibrary/pcl#5425]
I have a crash in the destructor of SHOTEstimationBase happening in Eigen::aligned_free(). We are using Eigen 3.4.0. Is Eigen 3.4.0 supported with pcl 1.12.1?

**Comment by mvieth** [comment]
Yes, Eigen 3.4.0 is supported.
- Which operating system do you use?
- How did you install PCL?
- Which compiler do you use?
- Can you provide a stack trace from a debugger or similar?

**Comment by zamx** [comment]
We compiled PCL from source. OS is Windows 10 x64. It was compiled with VS2019.

[CrashPCL.txt](https://github.com/PointCloudLibrary/pcl/files/9556007/CrashPCL.txt)

**Comment by larshg** [comment]
How do you generate solutions for both PCL and own project?

What comes to my mind, when align_free error appears, could be mixmatch between having AVX/SSE flags matching in both projects.

**Comment by zamx** [comment]
we use cmake for both PCL and our own project.

**Comment by mvieth** [comment]
@zamx Can you post the CMakeLists.txt of your own project? Did you use any non-default options when you compiled PCL?

**Comment by zamx** [comment]
I don't know if I'm allowed the share the CMakeLists.txt, we're a closed source project. Is there something specific I can look for?

The non-default options we enable are: PCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32 & PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32. We no longer build for win32, so I can remove these.

**Comment by larshg** [comment]
I have build test test_shot_estimation and it works here.
Using:
VS2022
Eigen3 3.4.0 (vcpkg)

**Comment by zamx** [comment]
I'll test if I can reproduce it in a small example.

**Comment by mvieth** [comment]
@zamx Do you use any options in your own project that influence alignment, e.g. also SIMD (SSE and AVX)?

**Comment by zamx** [comment]
I'm not aware of any, but I'll ask around.

**Comment by zamx** [comment]
For windows build we add definition -D_ENABLE_EXTENDED_ALIGNED_STORAGE in cmake for libraries using PCL.

The crash only happens if pcl::SHOTEstimation::compute() is called.

**Comment by mvieth** [comment]
> For windows build we add definition -D_ENABLE_EXTENDED_ALIGNED_STORAGE in cmake for libraries using PCL.

Can you try using the same definition when you compile PCL?

> The crash only happens if pcl::SHOTEstimation::compute() is called.

The crash happens while destroying [`shot_`](https://pointclouds.org/documentation/classpcl_1_1_s_h_o_t_estimation_base.html#a28329c5272f722e4b0f4468a05641c3d). Inside `compute()` there is memory allocated for it. But actually, `shot_` can be local inside `compute()`, that will fix this problem. I will open a PR for this later.

**Comment by zamx** [comment]
I have built PCL with -D_ENABLE_EXTENDED_ALIGNED_STORAGE. It didn't fix the crash.

**Comment by mvieth** [comment]
@zamx I opened a pull request. Would be great if you could test it, to make sure this indeed fixes the problem :slightly_smiling_face:

**Comment by zamx** [comment]
@mvieth I'll test it today

**Comment by zamx** [comment]
@mvieth The pull request fixes the crash.

**Comment by mvieth** [comment]
Great!
