### ISSUE TITLE
use pcl in windows，I find slow, anyone know the reasony?

### ISSUE THREAD

**Issue by tust13018211** [PointCloudLibrary/pcl#5429]
--- pcl::NDT for linux ---
single : 203.83[msec]
--- pcl::NDT for windows---
single :  71304[msec]
I use the same cloud, why there is so big difference

**Comment by mvieth** [comment]
@tust13018211 I assume this is on the same computer/same hardware?
There can be many reasons, for example: different compiler, different build options (especially SIMD/SSE/AVX options), different build type (release or debug), ...
The operating system itself might also have an influence, but probably not this much

**Comment by tust13018211** [comment]
> @tust13018211 I assume this is on the same computer/same hardware? There can be many reasons, for example: different compiler, different build options (especially SIMD/SSE/AVX options), different build type (release or debug), ... The operating system itself might also have an influence, but probably not this much

I use the same compute, one in windwos ，one in ubuntu18.04, and all use the release model

**Comment by mvieth** [comment]
@tust13018211 Do you also use the same PCL version on Windows and Ubuntu?
On Windows, what build options do you use for your own project? Do you enable SIMD instructions (SSE/AVX)? Which optimization level does the compiler use?

**Comment by tust13018211** [comment]
> @tust13018211 Do you also use the same PCL version on Windows and Ubuntu? On Windows, what build options do you use for your own project? Do you enable SIMD instructions (SSE/AVX)? Which optimization level does the compiler use?

I us pcl 1.10.0 in windows，but i use pcl 1.7.0 in linux, I donn`t use SIMD instructions, I just use ompndt to test,  this is my cmakelist, and then I use vs2019 to compile,
cmake_minimum_required(VERSION 3.10)
project(ndt_omp)

add_definitions(-std=c++14)
set(CMAKE_CXX_FLAGS "-std=c++14")

if (BUILD_WITH_MARCH_NATIVE)
  add_compile_options(-march=native)
else()
  add_definitions(-msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2)
  set(CMAKE_CXX_FLAGS "-msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2")
endif()

# pcl 1.7 causes a segfault when it is built with debug mode
set(CMAKE_BUILD_TYPE "RELEASE")

# find_package(Boost REQUIRED COMPONENTS
#         timer
#         filesystem)
SET(BOOST_ROOT "C:/Program Files/PCL 1.10.0/3rdParty/Boost")
find_package(Boost COMPONENTS system date_time regex REQUIRED)

find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()

find_package(PCL 1.7 REQUIRED)
include_directories(${PCL_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

message(STATUS "PCL_INCLUDE_DIRS:" ${PCL_INCLUDE_DIRS})
message(STATUS "PCL_LIBRARY_DIRS:" ${PCL_LIBRARY_DIRS})
message(STATUS "PCL_DEFINITIONS:" ${PCL_DEFINITIONS})

###########
## Build ##
###########
include_directories(include)

add_library(ndt_omp
  src/pclomp/voxel_grid_covariance_omp.cpp
  src/pclomp/ndt_omp.cpp
  src/pclomp/gicp_omp.cpp
)

target_link_libraries(ndt_omp ${PCL_LIBRARIES})

if(OpenMP_CXX_FOUND)
  target_link_libraries(ndt_omp OpenMP::OpenMP_CXX)
else()
  message(WARNING "OpenMP not found")
endif()

add_executable(align
  apps/align.cpp
)
# add_dependencies(align
#   ndt_omp
# )
target_link_libraries(align
  ${Boost_LIBRARIES}
  ${PCL_LIBRARIES}
  ndt_omp
)

**Comment by mvieth** [comment]
So it appears you use this project https://github.com/koide3/ndt_omp ? It is not completely clear to me what code you time, but if it is code from that project, you should ask there.

> I donn`t use SIMD instructions

Yes, you do (`-msse -msse2 -msse3 -msse4 -msse4.1 -msse4.2`), and `-march=native` also enables SIMD instructions. These flags are however only understood by gcc and clang. The windows compiler needs different flags to enable SIMD instructions, so you probably don't use SIMD on windows. This can make a big difference.

The CMakeLists.txt also says that you use OpenMP. You would have to check whether OpenMP is actually found and used on windows. If it is used on ubuntu but not on windows, that could also explain the speed difference.

**Comment by mvieth** [comment]
I am closing this since I gave you several possible explanations. And if you really use the project I linked above, you should ask further questions there.
