### ISSUE TITLE
[MLS upsampling] I want to X4 upsample.

### ISSUE THREAD

**Issue by cyun-404** [PointCloudLibrary/pcl#5439]
I want to upsample with X4.
I'd like to do upsampling, but I'd like to modify the rate and specify the number of points to increase to obtain the result of upsampling 4 times. Is there a way?

**Comment by mvieth** [comment]
I would suggest to have a look at the different upsampling methods (https://pointclouds.org/documentation/classpcl_1_1_moving_least_squares.html#aa444c1e8df3498adba7f25918f4a961c).
For further questions about PCL's functionality, please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community). The GitHub issues are intended for bug reports and compile errors.

**Comment by cyun-404** [comment]
okay.. sorry.. thank you
