### ISSUE TITLE
the link libpcl_xxxx.so is broken

### ISSUE THREAD

**Issue by bigfacecat553** [PointCloudLibrary/pcl#5445]
Hello guys, I just want to catkin make the project and it tell me that libpcl_xxxx.so have some problem.

**Describe the error**

The link " libpcl_kdtree.so " is broken.
This link cannot be used because its target " lib_kdtree.so.1.10 " doesn't exit. 

**To Reproduce**
I installed the pcl and found that all my libpcl_xxxx.so is broken, and I delete the pcl and install the pcl again， but the problem still exist.

` sudo apt install libpcl-dev`

or I tried
`sudo apt install ros-noetic-desktop-full`

It seems that I only have the file “libpcl_xxx.so” and lack the “libpcl_xxxx.so.1.10” 

How can I fix it?

I have run the command
` locate libpcl`  and  I didn't find libpcl_kdtree.so.1.10.

I also have run `sudo apt-file seatch libpcl_kdtree.so `
and I found three files, which include libpcl_kdtree.so.1.10.0, libpcl_kdtree.so, libpcl_kdtree.so.1.10
under the dire: `/usr/lib/x86_64-linux-gnu/ `
but l just have the  libpcl_xxx.so 

**Screenshots/Code snippets/Build information**

![9G$KP(0%REIIR%J1Q8}36~F](https://user-images.githubusercontent.com/78061022/193230382-46e6bbe8-d3d7-419e-a4a4-4cd12d71cc6c.png)

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]

 - PCL Version [pcl 1.10 ]

**Comment by mvieth** [comment]
@bigfacecat553 Can you check whether `libpcl-kdtree1.10` is installed, and install it if it isn't? It _should_  be installed together with `libpcl-dev`, but maybe it wasn't for some strange reason

**Comment by bigfacecat553** [comment]
> @bigfacecat553 Can you check whether `libpcl-kdtree1.10` is installed, and install it if it isn't? It _should_ be installed together with `libpcl-dev`, but maybe it wasn't for some strange reason

Thanks, I check it through `sudo apt install libpcl-io1.10 `  as an example .  and it tells me that  it's already the newest version.

**Comment by bigfacecat553** [comment]
It seems that I already have the` libpcl-io1.10` but lack the `/usr/lib/x86_64-linux-gnu/libpcl_io.so.1.10, /usr/lib/x86_64-linux-gnu/libpcl_io.so.1.10.0` in` /usr/lib/x86_64-linux-gnu/`

**Comment by bigfacecat553** [comment]
well,  I check the file, and find that I don't have any fie in the list but it tells me that I already have the newest:
```
apt-file list libpcl-kdtree1.10
libpcl-kdtree1.10: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so.1.10
libpcl-kdtree1.10: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so.1.10.0
libpcl-kdtree1.10: /usr/share/doc/libpcl-kdtree1.10/changelog.Debian.gz
libpcl-kdtree1.10: /usr/share/doc/libpcl-kdtree1.10/changelog.gz
libpcl-kdtree1.10: /usr/share/doc/libpcl-kdtree1.10/copyright
```

**Comment by mvieth** [comment]
@bigfacecat553 Try removing and re-installing the package (`libpcl-io1.10` or `libpcl-kdtree1.10`) then

**Comment by bigfacecat553** [comment]
> @bigfacecat553 Try removing and re-installing the package (`libpcl-io1.10` or `libpcl-kdtree1.10`) then

well， I have tried that by：
sudo apt remove libpcl-io1.10 ,and it automatically remove all the pcl packages.
then I tried install the package and still lack the .so file.

**Comment by bigfacecat553** [comment]
I check the package` /var/cache/apt/archives/libpcl-kdtree1.10_1.10.0+dfsg-5ubuntu1_amd64.deb` and find that the deb files don't put all the files in the right place. I don't know why it cannot automatically decompression the .so file in `  /usr/lib/x86_64-linux-gnu/`.
It seems like something wrong, and it just extract part of the files and omit all the xxx.so files.  So, I manually extract them to the /usr/lib/x86_64-linux-gnu/.  Finally, it works.
