### ISSUE TITLE
***make[2]::no rules target“/usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.4pcl_common”

### ISSUE THREAD

**Issue by MonsterQhz** [PointCloudLibrary/pcl#5450]
How to solve the problem? The libconsole_bridge.so.0.4 exsists and works.I had the problem one month ago,but couldn't solve it.Could you help me?Thank you!

**Comment by mvieth** [comment]
@MonsterQhz  You have to give more information, otherwise we can't help you. What operating system are you using? Which compiler? Which PCL version and how did you install it? What are you trying to compile? If you are using CMake, please post the CMakeLists.txt

**Comment by MonsterQhz** [comment]
Sorry! Here are some additions. I run the test in Ubuntn20.04, ROS noetic. My PCL version is 1.12.1, and I use cmake to compiler.The issue is , "There are no rules to make goals, /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.4pcl_common".The following is the CMakeLists.txt.
[CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/files/9696212/CMakeLists.txt)

**Comment by MonsterQhz** [comment]
I have solve the problem. Thank you! Best wishes
