### ISSUE TITLE
[CMake] warning LNK4199: /DELAYLOAD:VCOMP140.dll ignored; no imports found from VCOMP140.dll

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#5455]
I'm getting `LINK : warning LNK4199: /DELAYLOAD:VCOMP140.dll ignored; no imports found from VCOMP140.dll` with MSVC 2019/22 (not sure if also with 2017)

I'm not really sure, if we still need this code:
https://github.com/PointCloudLibrary/pcl/blob/2db91255366ae3120256070b1dd913aedec74d89/CMakeLists.txt#L300-L314

The lines for the newer VS versions were added here, sadly no comment if it is really necessary
- VS 2017: #1762
- VS 2019: #2826
- VS 2022: #5022

As the name `VCOMP140` suggest, iut is for visual Studio 14.0 (MSVC 2015), see [here](https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html) (you can see that the version number of the DLL was matching in #1378)

**Comment by larshg** [comment]
Also seen in our build servers:
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=22013&view=logs&j=b7dd6ba8-1ad9-5018-2280-3f36c72607c9&t=2fd7de77-c8c6-5479-ec09-1c18859bcc95&l=84

**Comment by mvieth** [comment]
@UnaNancyOwen

**Comment by SunBlack** [comment]
> > I'm not really sure, if we still need this code
> 
> These lines was taken over and update when maintained old CMakeLists. I don't know if it is still necessary now. If you know please tell us.

Sadly I don't have MSVC 2015 anymore anywhere installed to compare the results. Was already thinking about creating a dummy OpenMP-Demo and check if there is a difference, when the DLL is available and not.

**Comment by mvieth** [comment]
The commit that first introduced this delayload is https://github.com/PointCloudLibrary/pcl/commit/8ebd66d62b50e45b369bad487a74c13a0066f0e5 It mentions compatibility with VS Express as the reason. To my understanding, the final release of VS Express was in 2017. So my suggestion would be to not add this delayload flag for all MSVC versions where we see the warning (2019 and 2022), and remove the CMake warning message in line 313
