### ISSUE TITLE
Is there any way to use voxel grid filter on custom point type?

### ISSUE THREAD

**Issue by ZhangZh3ng** [PointCloudLibrary/pcl#5458]
Hi, I'm using PCL processing lidar point clouds. The source data contains some special fields such as "ring" and "time", and I also want to add some fields that I need such as "column". So I created a new point type:
```
struct PointXYZIRC {
  PCL_ADD_POINT4D
  PCL_ADD_INTENSITY;
  std::uint16_t ring;
  std::uint16_t column;
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
} EIGEN_ALIGN16;
POINT_CLOUD_REGISTER_POINT_STRUCT (PointXYZIRC,
    (float, x, x) (float, y, y) (float, z, z) (float, intensity, intensity)
    (std::uint16_t, ring, ring) (std::uint16_t, column, column))
```
However, when I use VoxelGrid filter to downsample a point cloud with "PointXYZIRC" points, I got  a compile error.
The question is: Is there any way to "make" VoxelGrid filter also apply for my customized point type? If answer is Yes, how can I achieve that?

**Comment by mvieth** [comment]
See here: https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html

**Comment by ZhangZh3ng** [comment]
> See here: https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html
I have tried adding `PCL_INSTANTIATE(VoxelGrid PointXYZIRC);` , but I still meet compile error:
```
error: expected constructor, destructor, or type conversion before ‘(’ token
   22 | PCL_INSTANTIATE(VoxelGrid PointXYZIRC);
```

**Comment by ZhangZh3ng** [comment]
> `How to add a new PointT type` is the interesting section for you

Sorry, I may not express clearly enough before, actually I had successfully defined a new point type(PointXYZIRC), and create a point cloud(pcl::PointCloud<PointXYZIRC>), but I can't create a pcl::VoxelGrid<PointXYZIRC>.

**Comment by mvieth** [comment]
![Screenshot from 2022-10-07 10-44-18](https://user-images.githubusercontent.com/39675748/194513732-7a59d26d-0182-4802-b256-68540336779c.png)

**Comment by ZhangZh3ng** [comment]
Thanks to your patient help, I finally solved the problem.  Voxel grid with my customized point type can compile and work properly! By the way, I found that after voxel grid downsampling, only x, y, z, intensity fields has meaningful value, while my custom fields will always be 0, is that normal? (The following is my test code's output, and the first 3 data is x, y, z)
```
I1009 16:00:53.855191  6567 voxel_grid_filter_test.cc:82] 0.5 0.5 0.5 intensity = 0.05 ring = 0 column = 0
I1009 16:00:53.855396  6567 voxel_grid_filter_test.cc:82] 2.5 2.5 2.5 intensity = 0.25 ring = 0 column = 0
I1009 16:00:53.855405  6567 voxel_grid_filter_test.cc:82] 4.5 4.5 4.5 intensity = 0.45 ring = 0 column = 0
I1009 16:00:53.855410  6567 voxel_grid_filter_test.cc:82] 6.5 6.5 6.5 intensity = 0.65 ring = 0 column = 0
I1009 16:00:53.855417  6567 voxel_grid_filter_test.cc:82] 8.5 8.5 8.5 intensity = 0.85 ring = 0 column = 0
```

**Comment by mvieth** [comment]
Yes, that is to be expected. The VoxelGrid will compute a "centroid" of all points in each voxel, using `CentroidPoint` (see here: https://pointclouds.org/documentation/classpcl_1_1_centroid_point.html). I don't know what `ring` and `column` represent, but a simple mean computation would probably not make sense for them, right?

**Comment by ZhangZh3ng** [comment]
> Yes, that is to be expected. The VoxelGrid will compute a "centroid" of all points in each voxel, using `CentroidPoint` (see here: https://pointclouds.org/documentation/classpcl_1_1_centroid_point.html). I don't know what `ring` and `column` represent, but a simple mean computation would probably not make sense for them, right?

Yes, that behavior is very reasonable. Thanks again for your help mvieth!
