### ISSUE TITLE
pcl::io::OrganizedConversion<>::convert replacement?

### ISSUE THREAD

**Issue by Mariusmssj** [PointCloudLibrary/pcl#5462]
I used to use `pcl::io::OrganizedConversion<>::convert` to turn a depth and colour image pairs into point clouds, it appears that this is no longer available. I tried searching for an alternative but sadly found nothing. 

Is a recommended method of turning depth and colour image pairs into a pointcloud?

**Comment by mvieth** [comment]
I have never used this class, but I searched for it and it is still available:
https://pointclouds.org/documentation/structpcl_1_1io_1_1_organized_conversion.html
https://pointclouds.org/documentation/structpcl_1_1io_1_1_organized_conversion_3_01_point_t_00_01false_01_4.html
https://pointclouds.org/documentation/structpcl_1_1io_1_1_organized_conversion_3_01_point_t_00_01true_01_4.html
What makes you think that it is no longer available? If there is a compiler error, please post it. What PCL version are you using now, and in which PCL version did you use this class successfully?

**Comment by Mariusmssj** [comment]
I am using PCL 1.12.1 AllInOne-msvc2019-win64 and the `#include <pcl/compression/organized_pointcloud_conversion.h>` no longer works, the file does not exist. I used to use it in 1.9.0 if I remember that correctly.

I looked through the include directory and no files under organized_pointcloud_conversion exist.

**Comment by mvieth** [comment]
Have you always used the All-In-One installer?
That header file is only installed if libpng is available and found (https://github.com/PointCloudLibrary/pcl/blob/master/io/CMakeLists.txt#L309). I am not sure if that is the case with the All-In-One installer.
However, you should be able to use that header even without libpng if you manually copy it to the appropriate directory

**Comment by Mariusmssj** [comment]
@mvieth Thank you, all's working now just had to manually add it to the include directory.
