### ISSUE TITLE
[visualization] Interactor->GetKeyCode() returns 0 when some key event occurred.

### ISSUE THREAD

**Issue by dongchenyu163** [PointCloudLibrary/pcl#5467]
**Environment**

 - OS: Ubuntu 20.04
 - Compiler: GCC 8.1
 - PCL Version: HEAD at commit 6420445c0eba32ec41b8be63804a1b0acf6efc53
 - **VTK: 9.2.2 release**

**Describe the bug**
- The **point size could not  be changed by pressing numpad plus and minus key**, with above environment mentioned.
- Then i found `Interactor->GetKeyCode()` function in pcl::visualization::PCLVisualizerInteractorStyle::OnKeyDown() return 0 when some key event occurred.
    - Only [`a-z`] and some symbol like [ `, . / \ [ ]  `]  (Maybe the main part of keyboard?) can got a right return. The others just return 0.
- However, the `Interactor->GetKeySym()` function can still gets right result for each key event, like returns KP_Add when `+` key is pressed.

**Context**
- I also found the [VTK commit](https://github.com/Kitware/VTK/commit/30a89b03aa293bd326116ecaa22ccc5d5bbc71ce)  causes this issue.
     - It seem to be fixed at future, but this commit is pushed at 1 year before, nobody knows when the VTK team can fix this issue....

**To Reproduce**

Really simple program, any pointcloud file can reproduce this issue:
```cpp
#include <pcl/visualization/pcl_visualizer.h>

int main()
{
	using PCXYZ = pcl::PointCloud<pcl::PointXYZ>;
	using PCXYZ_Ptr = pcl::PointCloud<pcl::PointXYZ>::Ptr;

	PCXYZ_Ptr pc(new PCXYZ);
	pcl::io::loadPCDFile("../Test.pcd", *pc);

	pcl::visualization::CloudViewer CVis("test vis");
	CVis.showCloud(pc);
	while (!CVis.wasStopped());

        reutrn 0;
}
```

**Possible Solution**

Now, I use the code below to change the line 722:

FROM:
```cpp
  switch (Interactor->GetKeyCode ())
```

TO:
```cpp
  char KeyCodeChar = Interactor->GetKeyCode ();
  if (KeyCodeChar == 0)
  {
    std::string KeyString(Interactor->GetKeySym());
    if (KeyString == "KP_Add")
      KeyCodeChar = '+';
    else if (KeyString == "KP_Subtract")
      KeyCodeChar = '-';
  }

  switch (KeyCodeChar)
```

**Comment by mvieth** [comment]
Hi, thanks for reporting this and suggesting a fix.
However, I don't think that the commit from the VTK repo you linked causes the issue. I tested with VTK 9.1.0 (which doesn't contain the commit yet) and pressing the `+` and `-` keys on the numpad also doesn't do anything (`GetKeyCode` doesn't return `+` and `-` respectively). So I believe the `+` and `-` keys on the numpad never worked. But it would be great to enable those keys.
Would you be interested in creating a pull request?

**Comment by dongchenyu163** [comment]
Emmm... I can use the + and - keys on the numpad to change the point size when I use PCL1.12.1 + VTK 8.2.....

But anyway, I'll create a pull request.
