### ISSUE TITLE
[Surface]Using MovingLeastSquares results in a segfault within performUpsampling function

### ISSUE THREAD

**Issue by jsnapz** [PointCloudLibrary/pcl#5471]
**Environment Current - Not Working**
OS: Ubuntu 20.04.4 LTS
Compiler: GCC 9.4.0
PCL Version: 1.10.0
Architecture: aarch64

**Environment Past - Worked**
OS: Ubuntu 18.04.6 LTS
Compiler: GCC 7.5.0
PCL Version: 1.8.1
Architecture: aarch64

Hello,

I'm having an issue where I have ported my project over to a new environment. My project used to work before with my past environment but now it is not working with the current. Everything compiles fine but when I run I am getting a segmentation fault when I run. I narrowed it down to happening inside the process function and then inside that the performSampling function. It looks like there were changes in GitHub between these versions(1.8.1 vs 1.10.0) and I thought I accounted for everything but maybe not. I also checked with the master branch and 1.10.0 looks the same for that function.

Sor cloud was obtained through a .ply

**Picture of source code past environment** 

![old](https://user-images.githubusercontent.com/115811376/195913022-83a0e2a7-6c6d-4183-88db-9e1aa2b5430e.png)

**Picture of source code current environment** 

![New](https://user-images.githubusercontent.com/115811376/195911703-670cea84-d990-4c8d-9041-7046635dabff.png)

**Pictures of seg fault from current environment** 
![seg](https://user-images.githubusercontent.com/115811376/195913647-a85886b5-9792-463f-ab8f-7f8f81255e51.png)
![seg2](https://user-images.githubusercontent.com/115811376/195913670-d8d6d8aa-48ca-4009-9856-926ead6f4e6d.png)

Thank you for the help

**Comment by mvieth** [comment]
Thanks for the detailed issue report! It seems like this segfault happens when dereferencing `normals_`, which wasn't set because `setComputeNormals` was set to `false`. Try setting it to `true` instead.
This behaviour changed with this pull request: https://github.com/PointCloudLibrary/pcl/pull/1960 (since PCL 1.9.0). Let me check whether this is a bug and how to fix this in the PCL code

**Comment by mvieth** [comment]
I would say the fix is to simply move the `normals_.reset` out of the if-statement here: https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/impl/mls.hpp#L69
If you like, you could create a pull request to fix this. Otherwise I or someone else will do that sometime
