### ISSUE TITLE
[Correspondence Grouping] "The local reference frame is not valid!"

### ISSUE THREAD

**Issue by JamieRossiter** [PointCloudLibrary/pcl#5474]
**Describe the error**

When attempting to run the [correspondence grouping tutorial](https://pcl.readthedocs.io/projects/tutorials/en/latest/correspondence_grouping.html) with two of my own generated .pcd files (1 model, 1 scene), I receive the following output: 

```
# This appears for every point
[pcl::SHOTEstimation::computeFeature] The local reference frame is not valid! Aborting description of point with index 669969

# This appears at the end of output
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!

Correspondences found: 0
```
I am using point cloud data generated by a ZED 2 camera for both the model and the scene. The model data is an isolated cluster of points from the scene data, achieved using passthrough filtering. 

**To Reproduce**

1. Copy the code from and build the correspondence grouping tutorial.
2. Run ``./correspondence_grouping <model_file> <scene_file>``

Please note that running this with the .pcd files provided in the tutorial results in expected output. The issue arises with my particular .pcd files.

**Screenshots/Code snippets/Build information**

![image](https://user-images.githubusercontent.com/50314568/196136747-a2e6726e-f71d-4a00-a8e8-1f8538cff505.png)
![image](https://user-images.githubusercontent.com/50314568/196136927-05927100-24db-478d-94a9-178f26127096.png)

**Your Environment:**

 - OS: Debian GNU/Linux 11 (bullseye)
 - Compiler: CMake 3.18.4
 - PCL Version: 1.12.1
 - PCL Type: Installed with apt

**Possible Solution**

Previewing my .pcd files in the CloudViewer requires me to scroll/zoom out significantly before I can see the point cloud. I believe this may be related to the issue but cannot be certain.

**Comment by mvieth** [comment]
If you look at the `master` version instead of the `latest` version of the tutorial (https://pcl.readthedocs.io/projects/tutorials/en/master/correspondence_grouping.html#compiling-and-running-the-program), the following note was added:

> You may see warnings about invalid reference frames (this can happen if a keypoint does not have enough other points in its neighborhood). If these warnings are only displayed for few points and the results look good otherwise, you can ignore them, else you should try to adapt the parameters.

So you should try to find parameters that work for your own model/scene.

**Comment by JamieRossiter** [comment]
Thank you for your response. In what situation does a _"keypoint not have enough points in its neighborhood"_? What parameters are typically tweaked in cases like this... the reference frame radius, perhaps? Or the model and scene uniform sampling radius?

Any light that you can shed on this would be greatly appreciated!

**Comment by mvieth** [comment]
> Thank you for your response. In what situation does a _"keypoint not have enough points in its neighborhood"_? What parameters are typically tweaked in cases like this... the reference frame radius, perhaps? Or the model and scene uniform sampling radius?

Yes, exactly. Changing the model/scene uniform sampling radius may make the processing slower, so I would recommend to first try adapting the reference frame radius. And you could try the `-r` option if you haven't done that already

**Comment by mvieth** [comment]
I am closing this issue, assuming your questions are answered

**Comment by JamieRossiter** [comment]
Hi @mvieth, apologies for not closing this myself as I am still working through this problem.

Your suggestion has helped me progress, to the point where the algorithm finds correspondences.

The issue now is that when the program is about to present the visualisation showing said correspondences, I receive a "Segmentation fault". There program does not provide any other context with this error message. I know that segmentation faults are related to memory, however I'm struggling to understand what the issue could be here.

Any pointers on a way forward from here would be very much appreciated. Thank you for your help so far.

**Comment by mvieth** [comment]
Do you use VTK 9.0.2, 9.0.3, or 9.1.0? Then this might be the problem: https://github.com/PointCloudLibrary/pcl/issues/5237
Otherwise you would have to post the output from valgrind or the backtrace of a debugger like gdb.

**Comment by muneeb127** [comment]
Did you solve the problem @JamieRossiter? Can you share the solution?

**Comment by dawierha** [comment]
> Did you solve the problem @JamieRossiter? Can you share the solution?

I fixed it by changing:
```
 while (!viewer.wasStopped ())
   {
      viewer.spinOnce ();
   }
```
to `viewer.spin();`, then it only segfaults after you close the window
