### ISSUE TITLE
[apps] Read device id from command line args in openni apps

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#5475]
From [a discussion](https://github.com/PointCloudLibrary/pcl/pull/5460#discussion_r991625473):

> Is it me or is device_id_ not setable, but only "" as default value?

> You are right, [the usage text](https://github.com/PointCloudLibrary/pcl/blob/master/apps/src/openni_3d_concave_hull.cpp#L168) even says that it is possible to specify a device id. The main function should pass the device id (if given by the user) from `argv` to the `OpenNI3DConcaveHull` constructor. When no device id is given (`""`), `OpenNIGrabber` seems to select the first available device

One example is this file: https://github.com/PointCloudLibrary/pcl/blob/master/apps/src/openni_3d_concave_hull.cpp (but there are more files)

**Comment by sfbirdf** [comment]
Hi! I'm looking to start contributing to open source and feel that this would be an ideal place to start for me, could I please have a try at it? :D

If I understand the problem correctly, the main idea is that we should , for the following file https://github.com/PointCloudLibrary/pcl/blob/master/apps/src/openni_3d_concave_hull.cpp#L198

add something along the lines of
```
. . .
  std::string arg = "";
  if (argc > 1)
    arg = std::string(argv[1]);
. . .
  pcl::OpenNIGrabber grabber("");
  if (grabber.providesCallback<pcl::OpenNIGrabber::sig_cb_openni_point_cloud_rgba>()) {
    PCL_INFO("PointXYZRGBA mode enabled.\n");
    OpenNI3DConcaveHull<pcl::PointXYZRGBA> v(arg);
    v.run();
  }
  else {
    PCL_INFO("PointXYZ mode enabled.\n");
    OpenNI3DConcaveHull<pcl::PointXYZ> v(arg);
    v.run();
  }
  return 0;
}
```

and do that for other affected files, would that be accurate? Any additional infos would be very appreciated :)

**Comment by larshg** [comment]
Probably also in the first 

`pcl::OpenNIGrabber grabber("");`

As that is the device you actaully query if it has RGB or not.

But else yes, something along those lines.

Start by making the PR for one example. Then we can add the others afterwards!

Thanks for contributing!
