### ISSUE TITLE
[organized_neighbor_search] "Being able to set/provide the projection matrix"

### ISSUE THREAD

**Issue by Pran-Seven** [PointCloudLibrary/pcl#5485]
**Is your feature request related to a problem? Please describe.**

So I am using Organized neighbour search as the trer search for calculation of normals in my script.
Organized neighbour allows the user to set the projection matrix, but there's no parameter as such to pass it, so I was wondering how would one go about it?

File for reference - https://pointclouds.org/documentation/organized_8h_source.html

**Context**
When I am trying to calculate normals for my pointclud, it returns an error INPUT NOT FROM PROJECTED DEVICE, because of the calculated projection matrix, so I want to try passing the projection matrix I obtain from my camera instead.

**Expected behavior**

It should be simple as passing any another parameter to searches.

**Current Behavior**

Currently the variable is a protected member, making it difficult to access it from other scripts.

**Describe the solution you'd like**

It should be simple as passing any another parameter to searches.

**Describe alternatives you've considered**

I have tried other surface normal calculation methods (normal estimation, normal estimation OMP) as well, but for my real time use case, this is the only one which is fast enough, hence my requirement for a modification. I am open to other methods of computing surface normal as well.

**Comment by mvieth** [comment]
@Pran-Seven And you are sure that you can use the organized search for your point cloud?
I can't find the error message `INPUT NOT FROM PROJECTED DEVICE` in the PCL source code. Is that the exact message that you see? Which PCL version are you using?
There doesn't seem to be a way to set the projection matrix explicitly, only to influence the internal estimation via `eps` and `pyramid_level`. But if the internally computed projection matrix is wrong, it would be important to find out why.

**Comment by Pran-Seven** [comment]
@mvieth yes,fairly sure. Other functions that does not involve projecting on to a 2D plane but requiring an organized pointcloud seem to work fine.
The organized.h links to a organized.hpp, which is where the error is being throw from. [You can find it at line 364](https://pointclouds.org/documentation/organized_8hpp_source.html#:~:text=PCL_ERROR%20(%22%5Bpcl%3A%3A%25s%3A%3AestimateProjectionMatrix%5D%20Input%20dataset%20is%20not%20from%20a%20projective%20device!%5CnResidual%20(MSE)%20%25f%2C%20using%20%25d%20valid%20points%5Cn%22%2C%20this%2D%3EgetName%20().c_str%20()%2C%20residual_sqr%20/%20double%20(indices.size())%2C%20indices.size%20())%3B). 
Yeah, adding that feature would be nice, makes it easier in some niche cases like this. Sure, I am currently exploring that error as well as how to pass our own matrix and check if the error is being avoided in that case.

**Comment by mvieth** [comment]
@Pran-Seven Ah okay, you mean _that_ error message. What does it say is the residual (MSE), and how many "valid points"  does it use?
What are width and height of your point cloud? What is the projection matrix you would want to set?
Can you share the point cloud, e.g. as a zipped PCD file?

**Comment by Pran-Seven** [comment]
Residual (MSE) 0.055300, using 1024 valid points
Width - 1280; Height - 480
Projection matrix published by the sensor I am using - Realsense D415 - [615.7805786132812, 0.0, 314.04083251953125, 0.0, 0.0, 615.3659057617188, 229.0540771484375, 0.0, 0.0, 0.0, 1.0, 0.0]
Currently not saving the pointclouds and the system is not accessible, will share it at the earliest though.

**Comment by mvieth** [comment]
> Currently not saving the pointclouds and the system is not accessible, will share it at the earliest though.

That would be very helpful, then I can run my own tests

**Comment by mvieth** [comment]
@Pran-Seven Any update? Do you have a saved point cloud now that you can share?

**Comment by Pran-Seven** [comment]
Hey sorry for the delayed response, I am facing issues saving my PC as a pcd file and sharing it, I think this can be marked as stale until I get an output. But I would like some help regarding the whole task I am doing, is there any other medium that I can reach you?

**Comment by mvieth** [comment]
@Pran-Seven  Saving point clouds as pcd files is usually as easy as calling [`savePCDFile`](https://pointclouds.org/documentation/group__io.html#ga5e406a5854fa8ad026cad85158fef266) (or `savePCDFileBinary` or `savePCDFileBinaryCompressed`).

I usually don't answer questions or give recommendations for application-specific things due to lack of time (at most I give a very quick hint). You can try asking on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community), maybe someone there is interested in helping you with your application.

**Comment by Pran-Seven** [comment]
Yup, I did do that, but since I am running the code on a remote PC, it is being saved somewhere there and I am not able to locate where exactly it is. That is the difficulty I ma facing, but other than that the file is being saved. 

Oh, that is completely understandable, even a hint would be great, actually I am trying to stitch/merge/register real time two point clouds coming from two different cameras with some overlap where I know the transformation between them. But the final result comes out to be unordered. So is there any way I can keep them ordered or convert an unordered pointcloud to ordered as further processing of the stitched pointcloud by pcl libraries requires it to be ordered. 

Will definitely post my questions there as well, thank you!

**Comment by mvieth** [comment]
> as further processing of the stitched pointcloud by pcl libraries requires it to be ordered.

Why? What classes/algorithms are you using? To my knowledge, there is always a class/algorithm that works with unordered clouds, and sometimes an additional class/algorithm that only works with ordered clouds.
The cloud you pass to the organized neighbour search (where you get the message about it not being from a projective device): is this cloud from one sensor only or is it already a combination of both sensors? In the latter case, it is clear that you can't use the organized neighbour search.
If you need the organized neighbour search to compute normals, my hint would be to compute normals on each of the two clouds first (then organized neighbour search should work), then combine/merge the two clouds.

**Comment by Pran-Seven** [comment]
Hey! Thanks a lot for the response, highly appreciate it.

> Why? What classes/algorithms are you using? To my knowledge, there is always a class/algorithm that works with unordered  clouds, and sometimes an additional class/algorithm that only works with ordered clouds.

The final goal is to use Human RGBD detection and the pre processors for that are normal computation, plane segmentation, getting connected planes and RANSAC refinement. So for this I would be requiring ordered pointcloud for normal computation.

Yes, there are other methods available, but they are very very slow (Normal Estimation OMP) compared to Integrated Image Normal Search, which is where the Organized Neighbour search comes into picture.

> The cloud you pass to the organized neighbour search (where you get the message about it not being from a projective device): is this cloud from one sensor only or is it already a combination of both sensors? In the latter case, it is clear that you can't use the organized neighbour search.

It is the combination of both the sensors. Oh okay, my bad then, but as I mentioned i the previous part, the Image Integral normal is the function which calls it.
The reason why I need the normal is to get connected planes from the combined pointcloud (normal angle based threshold), doing it separately would not work out.

Once again, thanks a lot for your time!

**Comment by Pran-Seven** [comment]
Hey, just had a quick question. How can I get the variable values printed of some variables in the included header files. Like for example if i I want ot see the value of the projection matrix, how do I print it on the console when my ros node is running?

**Comment by mvieth** [comment]
> The final goal is to use Human RGBD detection and the pre processors for that are normal computation, plane segmentation, getting connected planes and RANSAC refinement. So for this I would be requiring ordered pointcloud for normal computation.
Yes, there are other methods available, but they are very very slow (Normal Estimation OMP) compared to Integrated Image Normal Search, which is where the Organized Neighbour search comes into picture.

To repeat my earlier hint/recommendation: I would compute normals separately on each of the two (organized) point clouds, then merge the two clouds (including the computed normals). RANSAC doesn't need organized clouds. (If I misunderstood your problem -- nevermind)

> How I am making my final cloud 2D (ordered according to my interpretation)

So you just put the clouds "next to each other", or put differently, concatenate them in the "width" direction? Then you break the assumption for organized point clouds that all points have the same sensor origin, and projecting 3D points does not work any more. Consider for example a point in the overlap of the two clouds: if you would project it, it would have to end up in two places, once in the "left" cloud, and once in the "right" cloud. Feel free to have a look at the code (organized.h and organized.hpp) to understand better what is going on.

If not all points in the cloud come from the same projective device, I see no way of making the organized search work, even if you explicitly set the projection matrix. So I am going to close this issue.
