### ISSUE TITLE
[ConditionalRemoval,OMP] Bug about using omp to extract specific labeled points from origin cloud

### ISSUE THREAD

**Issue by Philip035** [PointCloudLibrary/pcl#5493]
**Describe the bug**

In my data, every cluster was labeled by a specific intger. I tried to extract all the clusters that the number of points larger than a threshold. To accelerate the process, omp was used. The code is below:
```
     pcl::PointCloud<pcl::PointXYZRGBL>::Ptr result(new pcl::PointCloud<pcl::PointXYZRGBL>);
#pragma omp parallel for
     for (int i = 0;i < labels.size();i++)
     {
		pcl::ConditionAnd<pcl::PointXYZRGBL>::Ptr con(new pcl::ConditionAnd<pcl::PointXYZRGBL>());
		con->addComparison(pcl::FieldComparison<pcl::PointXYZRGBL>::ConstPtr(new
			pcl::FieldComparison<pcl::PointXYZRGBL>("label", pcl::ComparisonOps::EQ, labels[i])));
		pcl::ConditionalRemoval<pcl::PointXYZRGBL> condrem;
		condrem.setInputCloud(cloud_in);
		condrem.setCondition(con);
	    pcl::PointCloud<pcl::PointXYZRGBL>::Ptr tempt(new pcl::PointCloud<pcl::PointXYZRGBL>);
		condrem.filter(*tempt);
		if (tempt->size() > threshold)
		{
			(*result) += (*tempt);
		}
     }
```
However, it always points to an exception in  _**xmemory.h**_  line 849. The line is:
```
    template <class _Objty, class... _Types>
    _CXX17_DEPRECATE_OLD_ALLOCATOR_MEMBERS void construct(_Objty* const _Ptr, _Types&&... _Args) {
        ::new (_Voidify_iter(_Ptr)) _Objty(_STD forward<_Types>(_Args)...);
    }
```

**Your Environment (please complete the following information):**

 - OS: [Win10]
 - Compiler: [VS2019]
 - PCL Version [1.12]

**Comment by larshg** [comment]
With my limitee knowledge of omp, I think you need to set the result cloud as shared between the threads and when you do the actual accumulation that should be wrapped in #pragma critical - so only on thread as access at a time.

Alternatively they should have their own result cloud each and do the accumulation afterwards?

**Comment by larshg** [comment]
A stack trace from debug build would be good as well. And perhaps a small demo cloud.

**Comment by Philip035** [comment]
> With my limitee knowledge of omp, I think you need to set the result cloud as shared between the threads and when you do the actual accumulation that should be wrapped in #pragma critical - so only on thread as access at a time.
> 
> Alternatively they should have their own result cloud each and do the accumulation afterwards?

It seems that "critical" really works, thanks a lot for your help! The bug may be caused by threads conflict.
