### ISSUE TITLE
How to downsample a point cloud in a large area

### ISSUE THREAD

**Issue by ZhangZh3ng** [PointCloudLibrary/pcl#5498]
I need to merge a series of point clouds into one and perform downsampling by VoxelGrid filter. Because these point clouds are distributed in a wide space, I always meet this error when downsampling: "Leaf size is too small for the input dataset. Integer indices would overflow". 
However, I don't want to increase the leaf size for accuracy reason, and even if I increase leaf size, it just delay the happen of overflow not avoid that. 

Some Internet resource suggest that octree can be used in this problem, however, they don't provide any specific solution. I conceive a solution:
1. Add all point cloud into a large one
2. Split the large point cloud into several small segmentation according to points' spatial position(may be by octree?)
3. Downsample the small point clouds by VoxelGrid.

I don't know if this method is feasible, and haven't used octree before. Who can provide a specific solution to this problem？Thanks a lot!

**Comment by mvieth** [comment]
@ZhangZh3ng Can you post the point cloud you pass to the VoxelGrid as a zipped .pcd file? Then I will try to suggest a solution.

**Comment by ZhangZh3ng** [comment]
I have upload the pcd files to google drive:
https://drive.google.com/file/d/11LdendV2wRNdMYsXGX8nqh0jGCrYZKa3/view?usp=sharing

> @ZhangZh3ng Can you post the point cloud you pass to the VoxelGrid as a zipped .pcd file? Then I will try to suggest a solution.
I have uploaded the point clouds to google drive:
https://drive.google.com/file/d/11LdendV2wRNdMYsXGX8nqh0jGCrYZKa3/view?usp=sharing

**Comment by mvieth** [comment]
Ok, so I checked whether there are outliers that make the bounding box unnecessarily large (with `RadiusOutlierRemoval`). This wasn't the case, at least not for gate_01.pcd.
Using an octree to split the large point cloud into smaller clouds that the VoxelGrid can process sounds feasible. You could try `OctreePointCloud`, and set the octree leaf resolution (`setResolution`) to 1250 times the leaf resolution you want to use for the VoxelGrid (1250^3 is just below 2^31, the number of leaves VoxelGrid can handle). Then you would iterate through the octree, for example with `leaf_depth_begin` and `leaf_depth_end` and proceed as you described it.
Alternatively, if you are not so familiar with PCL's octree implementation, you could split the large cloud "manually" using PassThrough or CropBox filters.

**Comment by ZhangZh3ng** [comment]
I tried to iterate through the octree(by leaf_depth_begin), but when I dereference the iterator, I found the result type is pcl::octree::OctreeNode and I can only find two member methods on this type(deepCopy and getNodeType). In my thought, I have to get a part of the input cloud of  the octree and the pass it to a VoxelGrid filter, but apparently, pcl::octree::OctreeNode is not a point cloud, can you point out what I did wrong? Here is some of my code:

```
const kLeafSize = 0.1;
pcl::OctreePointCloud<pcl::PointXYZI> octree;
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_origin;
pcl::VoxelGrid<pcl::PointXYZI> filter;
...
octree.setResolution(1250 * kLeafSize);
octree.setInputCloud(cloud_origin);
for (auto it = octree.leaf_depth_begin(); it != octree.leaf_depth_end(); ++it) {
  // This is a pcl::octree::OctreeNode, I don't know how to transform it to a point cloud and pass to the VoxelGrid  filter
  auto tmp = *it; 
}
```

**Comment by mvieth** [comment]
Dereferencing the iterator gives you an `OctreeNode*`, which you can cast to an `OctreePointCloud::LeafNode` (https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree_leaf_node.html). The container is an `OctreeContainerPointIndices` (https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree_container_point_indices.html)

**Comment by ZhangZh3ng** [comment]
I have solved the problem with your help, thank you mvieth!

In order to help people who may have the same problem, I post my implementation, and if there
is anything that can be improved, please point out.
```
// cloud_map is the origin "large point cloud", and the downsampled result is
// stored by cloud_out.
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_map{new pcl::PointCloud<pcl::PointXYZI>{}};
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_out{new pcl::PointCloud<pcl::PointXYZI>{}};
// cloud_tmp is used to store the points in a specific "leaf node" in octree, and cloud_tmp
// is the downsampled result of cloud_tmp
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_tmp{new pcl::PointCloud<pcl::PointXYZI>{}};
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud_tmp_ds{new pcl::PointCloud<pcl::PointXYZI>{}};
// voxel grid filter
static float kLeafSize = 0.2;
pcl::VoxelGrid<pcl::PointXYZI> filter_map;
filter_map.setLeafSize(kLeafSize, kLeafSize, kLeafSize);

...

// downsample process
cloud_out->clear();
pcl::octree::OctreePointCloud<pcl::PointXYZI> octree{1250 * kLeafSize};
octree.setInputCloud(cloud_map);
octree.addPointsFromInputCloud();
for (auto it = octree.leaf_depth_begin(); it != octree.leaf_depth_end(); ++it) {
  auto ids = it.getLeafContainer().getPointIndicesVector();
  cloud_tmp->clear();
  for (auto id : ids) {
    cloud_tmp->push_back(octree.getInputCloud()->points[id]);
  }
  filter_map.setInputCloud(cloud_tmp);
  filter_map.filter(*cloud_tmp_ds);
  *cloud_out += *cloud_tmp_ds;
}
```
