### ISSUE TITLE
[Segfault]Exception thrown at 0x00007FFC01F20E9C (ucrtbased.dll) after returning CHULL_vertices

### ISSUE THREAD

**Issue by unclesammy** [PointCloudLibrary/pcl#5505]
So I was runnig this old project about filter that involve convexHull、fade2D.

````
boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ>> RasterProcessor::ConvexHull() {
    //使用pcl库计算凸包
    pcl::ConvexHull<pcl::PointXYZ> chull;
    pcl::PointCloud<pcl::PointXYZ>::Ptr chull_projection_points(new pcl::PointCloud<pcl::PointXYZ>);//原始点云投影到一个平面
    pcl::PointCloud<pcl::PointXYZ> chull_points;
    for (int i = 0; i < origin_cloud->size(); i++)
    {//先把点云都投影到一个平面上，再做凸包检测
        pcl::PointXYZ points;
        points.x = origin_cloud->points[i].x;
        points.y = origin_cloud->points[i].y;
        points.z = 1.0;
        chull_projection_points->push_back(points);
    }

    chull.setInputCloud(chull_projection_points);//放入点云
    chull.reconstruct(chull_points);//chull_point:位于凸包上的点；  polygons：凸包多边形顶点的索引号
    pcl::PointIndices hull_point_indicies;//获得凸包顶点在原始点云上的索引号
    chull.getHullPointIndices(hull_point_indicies);
    boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ>> CHULL_vertices = boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ>>(new pcl::PointCloud<pcl::PointXYZ>);
    for (int i = 0; i < hull_point_indicies.indices.size(); i++)
    {
        CHULL_vertices->push_back(pcl::PointXYZ(origin_cloud->points[hull_point_indicies.indices[i]].x, origin_cloud->points[hull_point_indicies.indices[i]].y, 1.0));
    }
    std::cout << "CHULL_vertices has points :" << CHULL_vertices->size() << std::endl;
    return CHULL_vertices;
}

````

But somehow it just throw this segfault after returning CHULL_vertices at debug_heap.cpp line 194.
![image](https://user-images.githubusercontent.com/56534652/199873568-54baaf84-c977-4dc7-b06c-978d9ed2e243.png)
I debug it and find it just keep looping till the error show up.
This my call stack.
![image](https://user-images.githubusercontent.com/56534652/199873974-f0933919-8150-40d9-9416-e3d2a23ef065.png)
I once thought maybe sth to do with AVX2?(#5151),but it still show the error.Properly sth to do with free the ptr?or just my pcl version is low.
My Environment:
PCL 1.9.1(along with the 3rd party)
OpenCV 3.1
fadeRelease_v2.01
Visual Studio 2017 (v141)

**Comment by mvieth** [comment]
Which line is line 237 in `RasterProcessor::ConvexHull()`? That is where a point cloud is destroyed and the error happens

**Comment by unclesammy** [comment]
> Which line is line 237 in `RasterProcessor::ConvexHull()`? That is where a point cloud is destroyed and the error happens.
I think it happen during or after `return CHULL_vertices;`
![e2](https://user-images.githubusercontent.com/56534652/199976571-2f7118e2-7c16-4917-99c1-7bbb522d5993.png)

**Comment by mvieth** [comment]
Can you try again with the latest PCL (PCL 1.12.1)?

**Comment by mvieth** [comment]
> And change all the boost::shared_ptr to std::shared_ptr.Maybe the boost::shared_ptr is not fitting the current standard？

PCL switched to `std::shared_ptr`, beginning with PCL 1.11.0
