### ISSUE TITLE
[compile error] PCLVisualizer::addPointCloud cause error in xstring _Large_string_engaged

### ISSUE THREAD

**Issue by ychwang** [PointCloudLibrary/pcl#5514]
when i use sample ,my env is win10 + VS2019 + pcl 1.12.1 
pcl::visualization::PCLVisualizer::Ptr simpleVis(pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud)
{
    // --------------------------------------------
    // -----Open 3D viewer and add point cloud-----
    // --------------------------------------------
    pcl::visualization::PCLVisualizer::Ptr viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
    viewer->setBackgroundColor(0, 0, 0);
    viewer->addPointCloud<pcl::PointXYZ>(cloud, "cloud");
    viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "cloud");
    viewer->addCoordinateSystem(1.0);
    viewer->initCameraParameters();
    return (viewer);
}
i use above sample,it can build ,but when i run this function it case an error in xstring below ,addpointcloud 
    _CONSTEXPR20_CONTAINER bool _Large_string_engaged() const noexcept {
#ifdef __cpp_lib_constexpr_string
        if (_STD is_constant_evaluated()) {
            return true;
        }
#endif // __cpp_lib_constexpr_string
        return _BUF_SIZE <= _Myres;
    }
i do not know how to fix it and the problem ,

**Comment by mvieth** [comment]
How did you install PCL?
What is the exact error message?
Can you provide a call stack (from a debugger or similar), so I can see how the error happens?

**Comment by ychwang** [comment]
Thanks for your help.I install PCL-1.12.1-AllInOne-msvc2019-win64.exe,i choose add path to all user selection,at last it append  warining the path is too long and not add into system path,i ignore this  warning, and use vs2019 to built sample i add include/lib to this project, it can built  but when it runs it cause the problem. I can not deal this error,so i uninstall PCL ,I try install it again, The second time,i add VTK ande OPENNI and  PCL into my system path, and check all system path,then i try run it , it works.i guess it is my system path is not correct setting cause this problem.Thanks again.

> How did you install PCL? What is the exact error message? Can you provide a call stack (from a debugger or similar), so I can see how the error happens?

**Comment by mvieth** [comment]
So your problem is solved now and I can close this issue?

**Comment by mvieth** [comment]
Assuming it is solved ...
