### ISSUE TITLE
[compile error] point_cloud_editor does not support Qt6

### ISSUE THREAD

**Issue by viisautta** [PointCloudLibrary/pcl#5518]
**Describe the error**

Please paste the compilation results/errors.
[ 99%] Building CXX object apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/select2DTool.cpp.o
In file included from /home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/src/select2DTool.cpp:40:
/home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/select2DTool.h:43:10: fatal error: qgl.h: No such file or directory
   43 | #include <qgl.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:279: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/select2DTool.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/src/cloud.cpp:41:10: fatal error: qgl.h: No such file or directory
   41 | #include <qgl.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:223: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/cloud.cpp.o] Error 1
/home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/src/select1DTool.cpp:41:10: fatal error: qgl.h: No such file or directory
   41 | #include <qgl.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:265: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/select1DTool.cpp.o] Error 1
/home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/src/cloudEditorWidget.cpp:44:10: fatal error: QDesktopWidget: No such file or directory
   44 | #include <QDesktopWidget>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:237: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/cloudEditorWidget.cpp.o] Error 1
In file included from /home/o/Public/pcl-1.13.0-rc1/build/apps/point_cloud_editor/pcl_point_cloud_editor_autogen/YWY2GWMH3X/moc_cloudEditorWidget.cpp:10,
                 from /home/o/Public/pcl-1.13.0-rc1/build/apps/point_cloud_editor/pcl_point_cloud_editor_autogen/mocs_compilation.cpp:2:
/home/o/Public/pcl-1.13.0-rc1/build/apps/point_cloud_editor/pcl_point_cloud_editor_autogen/YWY2GWMH3X/../../../../../apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/cloudEditorWidget.h:53:10: fatal error: QOpenGLWidget: No such file or directory
   53 | #include <QOpenGLWidget>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:97: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/pcl_point_cloud_editor_autogen/mocs_compilation.cpp.o] Error 1
In file included from /home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/src/mainWindow.cpp:41:
/home/o/Public/pcl-1.13.0-rc1/apps/point_cloud_editor/include/pcl/apps/point_cloud_editor/cloudEditorWidget.h:53:10: fatal error: QOpenGLWidget: No such file or directory
   53 | #include <QOpenGLWidget>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/build.make:125: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/src/mainWindow.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3265: apps/point_cloud_editor/CMakeFiles/pcl_point_cloud_editor.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. Custom OS, custom PCL configs or custom build systems make the issue difficult to reproduce.
* Best reproducability: A docker image + code snippets provided here
* Good reproducability: Common Linux OS + default PCL config + code snippets provided here
* Poor reproducability: code snippets

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights
* debugging information:
  * the output of cmake using `cmake --debug`
  * the failing build command(s) using `VERBOSE=1 make`, `ninja -v` or similar
  * steps taken to narrow down the problem

**Your Environment (please complete the following information):**

 - OS: Fedora 37
 - Compiler: GCC 12.2.1
 - PCL Version 1.13.0
 - PCL Type: Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes/No
 - List and Version of dependencies used
 - Compilation flags are used

If compiling against PCL:
 - Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
  * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
  * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by mvieth** [comment]
Hi, I am looking into this, but one question: Have you made any changes to the PCL source code, because there is no include for `QOpenGLWidget` in `cloudEditorWidget.h` line 53

**Comment by viisautta** [comment]
@mvieth You are right, I tried to make some changes to included headers files Qt6, but I am unfamiliar to the differences between Qt5 and Qt6, so I quitted this problem.

**Comment by mvieth** [comment]
@viisautta All of PCL, including the apps, are now Qt6 compatible
