### ISSUE TITLE
Whether there is a website providing benchmark dataset

### ISSUE THREAD

**Issue by ZhangZh3ng** [PointCloudLibrary/pcl#5534]
The tutorial on the PCL website usually chooses to generate a point cloud in the program rather than read an actual point cloud, but I think there must exist some websites that provide some benchmark point clouds. If you know similar websites, can you share them? Thank you very much!

**Comment by mvieth** [comment]
You can find some point clouds here: https://github.com/PointCloudLibrary/pcl/tree/master/test
And here: https://github.com/PointCloudLibrary/data

Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions in the future. The GitHub issues are intended for bug reports and compile errors.

**Comment by ZhangZh3ng** [comment]
> You can find some point clouds here: https://github.com/PointCloudLibrary/pcl/tree/master/test And here: https://github.com/PointCloudLibrary/data
> 
> Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions in the future. The GitHub issues are intended for bug reports and compile errors.

Sorry, I will pay attention to that problem in the future, and thank your for your help!
