### ISSUE TITLE
[io] No writeBinary() to ostream instead of file for PCDWriter?

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5539]
**Is your feature request related to a problem? Please describe.**

`PCDWriter` has a method `writeBinaryCompressed()` which writes to a stream instead of file, which is useful when serializing point clouds in memory. But no non-compressed version exists, which is unfortunate.

**Context**

I send PCD data over the network, but don't always want compression to save some time. Let's disregard whether using the PCD format for this is efficient at all.

**Expected behavior**

`PCDWriter` provides `writeBinary(std::ostream& os, PCLPointCloud …)`.

**Current Behavior**

Only compressed writing to stream is supported.

**Comment by mvieth** [comment]
I agree, this would be nice to have. Unfortunately, I don't know whether/when I will have time to implement this, but I will mark it as "good first issue", maybe someone else is interested. Would be important to not duplicate too much code.

**Comment by ptrckschcknbch** [comment]
Hey, this is still an open point, isn't it? I'd like to implement this. Is that fine for you?

**Comment by mvieth** [comment]
@ptrckschcknbch Sure, that would be great. So the goal is a function like this:
```c++
int writeBinary (std::ostream &os, const pcl::PCLPointCloud2 &cloud,
                 const Eigen::Vector4f &origin = Eigen::Vector4f::Zero (),
                 const Eigen::Quaternionf &orientation = Eigen::Quaternionf::Identity ());
```

**Comment by ptrckschcknbch** [comment]
@mvieth I opened a draft PR #5598, which implements the mentioned function. Actually I wanted to add some tests for this, but I was not able to find distinct test cases for the already existing `writeBinary (const std::string &file_name,..)` method. Hence, I assume that it is tested implicitly in other test cases. If that's the case, this would probably also hold for the newly added function as it is called by the already existing one. So, would you prefer that I add some new test cases for the newly added function (then I will do so) or do you think that the functionality is sufficiently tested by existing tests?

**Comment by mvieth** [comment]
Thanks again @ptrckschcknbch for implementing this
