### ISSUE TITLE
for vtk 9.2, vtkMutexLock.h don't exist and can remove

### ISSUE THREAD

**Issue by huanglilong** [PointCloudLibrary/pcl#5543]
https://github.com/PointCloudLibrary/pcl/blob/58f9cfb41115b1f2453dfe0ec75915243969fb66/outofcore/tools/outofcore_viewer.cpp#L115

outofcore_viewer.cpp:115:10: fatal error: vtkMutexLock.h: No such file or directory

**Comment by mvieth** [comment]
Thanks for the notice! I looked it up and the file was removed in https://gitlab.kitware.com/vtk/vtk/-/commit/d933bb8495c7a705df7fb35560c6a102fd2b67d1 The latest release, VTK 9.2.2 still has the file, but on the master branch it does no longer exist.
I agree that the include can be removed in outofcore_viewer.cpp. Are you interested in opening a pull request?

**Comment by huanglilong** [comment]
@mvieth  please review diff: https://github.com/PointCloudLibrary/pcl/pull/5544
thanks a lots

**Comment by larshg** [comment]
Lets wait with closing it until #5544 has been merged.

**Comment by huanglilong** [comment]
fixed in https://github.com/PointCloudLibrary/pcl/pull/5544
