### ISSUE TITLE
dynamic_cast will case crash with latest VTK(master version),  static_cast is fine but has others issue

### ISSUE THREAD

**Issue by huanglilong** [PointCloudLibrary/pcl#5545]
https://github.com/PointCloudLibrary/pcl/blob/58f9cfb41115b1f2453dfe0ec75915243969fb66/visualization/src/pcl_visualizer.cpp#L2966

issue from https://github.com/PointCloudLibrary/pcl/pull/5504

pcl_viewer crash in `pcl::visualization::PCLVisualizer::updateColorHandlerIndex`

![image](https://user-images.githubusercontent.com/7278867/206094279-8c6794c4-a500-4138-ae76-0d138bfd3f24.png)

**Comment by huanglilong** [comment]
pcl_viewer is fine with this patch https://github.com/PointCloudLibrary/pcl/compare/master...huanglilong:pcl:fix_crash_pcl_visualizer

**Comment by larshg** [comment]
How to reproduce it? I can test with 9.0 - think thats the one I have.

**Comment by larshg** [comment]
Nm - just reproduced it.

**Comment by larshg** [comment]
Doing `dynamic_cast `to `vtkDataSetMapper `works here - or using VTKs version: `vtkDataSetMapper::SafeDownCast((am_it->second.actor->GetMapper()));`

**Comment by larshg** [comment]
@huanglilong would you like to add a visualization unit test that loads colored point cloud to reproduce the error on our CI and eventually come up with a proper fix?

**Comment by mvieth** [comment]
@larshg There are some more places we have to look at:
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/interactor_style.cpp#L669
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/interactor_style.cpp#L699
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/impl/pcl_visualizer.hpp#L1790
https://github.com/PointCloudLibrary/pcl/blob/master/visualization/src/pcl_visualizer.cpp#L3123
For the first two, we can just change to `vtkDataSetMapper`, but what about the last two?
Also, there are some cases of `reinterpret_cast<vtkPolyDataMapper*>` in pcl_visualizer.hpp and pcl_visualizer.cpp. Using a reinterpret_cast doesn't seem right?

**Comment by huanglilong** [comment]
@mvieth @larshg unit test for this crash https://github.com/PointCloudLibrary/pcl/pull/5548
vtkDataSetMapper::SafeDownCast((am_it->second.actor->GetMapper())); works

**Comment by huanglilong** [comment]
`pcl_viewer` with button: 1, 2, 3, 4, 5 will crash.
maybe all related `dynamic_cast` should be change to `SafeDownCast`

**Comment by huanglilong** [comment]
i have tested with `pcl_viewer` all `dynamic_cast<vtkPolyDataMapper*>` causes crash
![image](https://user-images.githubusercontent.com/7278867/206440945-d1473bb9-9ff1-487b-9627-10f13aa3cd68.png)

**Comment by huanglilong** [comment]
@mvieth  @larshg  i'm so sorry, i don't know how to add unit test for `PCLVisualizerInteractorStyle::OnKeyDown`

**Comment by huanglilong** [comment]
this class need input from keyboard or mouse, i don't know how to pass params to this class

**Comment by larshg** [comment]
Np. I'm not sure either right now how to do it.

**Comment by huanglilong** [comment]
fixed in https://github.com/PointCloudLibrary/pcl/pull/5549
