### ISSUE TITLE
[custom] PairwiseGraphRegistration example

### ISSUE THREAD

**Issue by YuraCobain** [PointCloudLibrary/pcl#5559]
Hello,

I would like to test global registration functionality provided by PCL, however it looks like PCL is missing ready to use feature like multiway registration( pose graph for example).
On the other hand there is  pcl::PairwiseGraphRegistration< GraphT, PointT > class but is not included into compilation and there are not any example of usage.

Could you clarify if pcl::PairwiseGraphRegistration< GraphT, PointT > is going to be supported or other multiway registration methods?

**Comment by mvieth** [comment]
Hmm, so `pairwise_graph_registration.hpp` is installed but `pairwise_graph_registration.h` is not installed. That is weird. `graph_registration.h` and `graph_handler.h` would also have to be installed. I am not familiar with these classes, so I don't know whether they are working correctly or not. I will try to look into it but can't promise anything. If you copy the mentioned `.h` files to the appropriate installation locations, you can test the classes yourself (your compiler will automatically instantiate the templates).

**Comment by mvieth** [comment]
I also just found this page, which may or may not give you any hints: https://pcl.readthedocs.io/projects/advanced/en/master/pcl_registration.html

**Comment by mvieth** [comment]
@YuraCobain PCL also has ELCH and LUM, which may be of interest for you.
Did my hints help you? If I don't hear from you, I will probably close this issue soon.

**Comment by YuraCobain** [comment]
Thank you for reply. I will check provided information tomorrow and return with answer.

**Comment by mvieth** [comment]
Closing because of no reply ...
