### ISSUE TITLE
[compile error] pcl_surface.dll depends on VTK (and it should not, right ?)

### ISSUE THREAD

**Issue by benkuper** [PointCloudLibrary/pcl#5560]
**Describe the error**

Please paste the compilation results/errors.

**To Reproduce**

Using PC 1.13.0 All-In-One installer

Use MovingLeastSquare filter, include mls.h
#include <pcl/surface/mls.h>

! My code has NO dependencies to VTK whatsoever, and it was running fine before including mls !

The code actually compiles fun but the pcl_surface.dll containing MLS complains about needing vtk dlls to run, which should not happen I guess ? Or should I need to compile everything myself just to avoid using VTK in my project ?

**Your Environment (please complete the following information):**

 - OS: Windows 11 x64
 - Compiler: MSVC (Visual Studio 2022) using JUCE framework
 - PCL Version : 1.13.0
 - PCL Type: All-In-One

**Possible Solution**

Remove dependencies to VTK in the compiled pcl_surface.dll

**Comment by larshg** [comment]
Some mesh algorithms in surface depends on VTK, so you would have to compile it yourself with VTK disabled,  if you don't want VTK at all.

**Comment by benkuper** [comment]
Do you mean they depend on "functional" algorithms or just for visualization ?
I thought VTK is pure UI and visualization, bu1if removing VTK means not being able to use MLS, I guess I'll keep it.

**Comment by benkuper** [comment]
Interesting, thank you for the insight.
