### ISSUE TITLE
can't install python-pcl on Ubuntu 22.04 with python3 and pcl 1.12.1

### ISSUE THREAD

**Issue by Samer-Docs** [PointCloudLibrary/pcl#5565]
Operating System and version: Ubuntu 22.04.1 LTS
PCL Version: 1.12.1
Cython Version: 0.29.32
boost 1.74

I am trying to run [ILCC](https://github.com/mfxox/ILCC) for calibration between panoramic camera and HDL32 LiDAR. I installed ILCC and opened it as a PyCharm project. The following requirements in requirements file were installed properly:
PyYAML>=3.12
numpy>=1.12.1
sklearn>=0.0
scipy>=0.19.0
transforms3d>=0.3
matplotlib>=2.0.0
Cython
boost
pcl

I tried to install python-pcl using:
git clone https://github.com/mfxox/python-pcl
cd python-pcl
python3 setup.py install

As the setup.py file set for an older version of pcl. I replaced manually "pcl_version == '-1.9'" by "pcl_version == '-1.12'" in setup.py, but this doesn't help and the command python3 setup.py install lead to errors as you can see in the attached snapshot problem1.png.

However, I managed to run img_corners_est.detect_img_corners() and it works fine, but I couldn't run pcd_corners_est.detect_pcd_corners() which lead to the error:

File "/home/samer/Desktop/ILCC/ILCC/pcd_corners_est.py", line 751, in seg_pcd
import pcl
ModuleNotFoundError: No module named 'pcl'

More details are in the attached snapshot problem2.png. Did you face such a problem before? or manage to install and compile python-pcl on Ubuntu 22.04

Thanks in advance
![problem1](https://user-images.githubusercontent.com/80517101/209575472-793d7646-9cea-40b7-9793-0bfcf5dd8b02.png)
![problem2](https://user-images.githubusercontent.com/80517101/209575474-339107bc-b9f4-40fd-ac5d-a0ad02ef81ef.png)

**Comment by jspricke** [comment]
ILCC has not been updated in years and there are instructions for Ubuntu 14/16 here: python https://github.com/mfxox/ILCC#dependencies-tested-on-macos-sierra-and-ubuntu-14041604
Maybe use those as it is still a Python 2 project. python-pcl is actually in Debian/Ubuntu, so you can simply do `sudo apt install python3-pcl`.

**Comment by Samer-Docs** [comment]
> sudo apt install python3-pcl

@jspricke Thanks for your quick reply and for the suggestion. I am aware that the ILCC was tested on Ubuntu 14/16, but I thought it is easier to make it run on Ubuntu 22.04 than converting my Ubuntu to an older version (16). 
Today, I managed to compile and run pcd_corners_est.py, but the output was not correct and there is an error.
 
However, I have two general questions regarding your reply:

1) I configured a virtual environment called "my_env_prject" for the Pycharm project ILCC. 
**(my_env_project) samer@SamerUbuntu:~/my_env_project$ sudo apt install python3-pcl
[sudo] password for samer: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pcl is already the newest version (0.3.0~rc1+dfsg-12).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.**

As you can see above the python3-pcl is already installed on my computer. When I searched for python3-pcl, I found it in the directory: /usr/share/doc/python3-pcl
My question is: how to link it to the ILCC project that use the virtual environment my_env_project?
or how to reinstall it in away that it is located just in my virtual environment and not in the whole system?

2) As I said pcd_corners_est.py is compiled and run as you can see in the attached photo, but after processing several LiDAR files, it shows that there is an error in line 789 that: pcl has no attribute "PointCloud". I think this is an attribute that was in the previous version of pcl (1.7) and not in my current version 1.12.1. My question is: how to edit the line 789 to be compatible with pcl 1.12.1 ?
**pcd_pedestrian = pcl.PointCloud(arr_for_pedestrians_pcd)
AttributeError: module 'pcl' has no attribute 'PointCloud'**

Thanks in advance

![Screenshot from 2022-12-28 12-49-31](https://user-images.githubusercontent.com/80517101/209807672-f39d21d7-ac5d-4665-8d8a-f32a7a6724b3.png)

**Comment by jspricke** [comment]
1. That's a general Python question unrelated to PCL.
2. I guess ILCC needs updating for the new PCL version, maybe ask there.

**Comment by haeseulshin** [comment]
Did you solve this problem? i met same things
