### ISSUE TITLE
[pcd_io] pcl_io module sometimes doesn't work

### ISSUE THREAD

**Issue by Heyan-Lanan** [PointCloudLibrary/pcl#5569]
I'm running code that loads a pcd file, but the io::loadPCDFile method reports an error. I noticed that it has a Redefinition of 'PCDReader' error, which causes the program-1073741515 (0xC0000135) error to exit.
![image](https://user-images.githubusercontent.com/74441478/209949202-ce20d78a-ac60-4b6e-a06d-045e7dab59f4.png)
![image](https://user-images.githubusercontent.com/74441478/209949359-127bcd24-dfe5-4b76-9d48-ff7d03a378e5.png)
Here is my code.
![image](https://user-images.githubusercontent.com/74441478/209949386-bdb7c0d6-4af7-4342-92d6-71295d8a6174.png)

**Comment by mvieth** [comment]
Your code looks fine, although I would recommend against `using namespace` statements.
The error happens while running the program right? The compilation is successful?
I just googled the error code `0xC0000135` and found for example:
- https://answers.microsoft.com/en-us/windows/forum/all/0xc0000135-error-when-opening-most-applications/7db10be2-66fb-4e5d-b553-8fa524bb2124
- https://www.thewindowsclub.com/fix-the-application-failed-to-initialize-properly-0xc0000135-error-on-windows-10

So this does not look like a PCL error, more like a general Windows error.
