### ISSUE TITLE
[compile error] "When make, report error: '*.LC1' not specified in enclosing 'parallel' "

### ISSUE THREAD

**Issue by hsynklceng** [PointCloudLibrary/pcl#5573]
**Describe the error**
when doing make, get an error at pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp(519)
```
error: '*.LC1' not specified in enclosing 'parallel'
        PointInT corner;
```

and

pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp(508)
```
error: enclosing 'parallel'
        #pragma omp parallel for /...
```

 - Ubuntu 18.04
 - PCL Version 1.13.0

 - CUDA enabled
 - Nvidia AGX Xavier

**Comment by mvieth** [comment]
@hsynklceng You are trying to compile PCL, right? Or are you compiling your own project which depends on PCL?
Which compiler are you using, and which version?

**Comment by hsynklceng** [comment]
Yes i try to make PCL. And i follow [this](https://pcl.readthedocs.io/projects/tutorials/en/master/gpu_install.html#checking-cuda-version) instruction.

**Comment by hsynklceng** [comment]
I actually skipped the GCC update step. Now I upgraded gcc 8 and tried but still getting error.

**Comment by hsynklceng** [comment]
I installed gcc-9 and was now able to compile. i didn't get any errors.
Thank you very much for your support. :)

**Comment by mvieth** [comment]
You're welcome. Then I am going to close this issue.
