### ISSUE TITLE
[PCL] Linking against PCL and a different library using Eigen causes Eigen Unaligned Assertion Error

### ISSUE THREAD

**Issue by AndreiCostinescu** [PointCloudLibrary/pcl#5577]
**Describe the bug**
I have a program linking against PCL and against another library that just uses Eigen.
When I run the program it triggers an assertion failure with the following explanation: http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html
The assertion does not happen when I just use PCL or the other library alone. But when I link against both libraries, the assertion is triggered. 

**Context**
Using Eigen and PCL in the same program coming from two different libraries produces an Eigen unaligned error (I think coming from the other library).

**Expected behavior**
No Eigen alignment assertion errors to be triggered by running code using external libraries: one PCL and the other using normal Eigen.

**To Reproduce**
The archive [TestPCLError.zip](https://github.com/PointCloudLibrary/pcl/files/10403313/TestPCLError.zip) contains a cmake project. The project creates a library (simulating the external one using Eigen) and two executables, one linking to PCL and the other not linking to PCL (notice: PCL is actually not used in this example code, but it is used in my program. This code was just created for simplicity of the with and without PCL test).
The executable linking to PCL, named TestPCLError, creates the assertion failure.
The executable not linking to PCL, named, TestPCLNoError, does not trigger the assertion and finishes normally.

**My Environment:**
 - OS: Ubuntu 18.04
 - Compiler: GCC 7.5
 - PCL Version 1.13
 - Eigen Version 3.4
 - Cuda Version 11.8

**Additional context**
I need PCL's GPU and Cuda modules so I've built it with BUILD_CUDA=On and BUILD_GPU=On.

I tried setting the CMAKE_CUDA_STANDARD=17 and CMAKE_CXX_STANDARD=17 (be aware that CUDA17 is supported by a very new cmake version; I am using 3.25) as instructed on Eigen's webpage about the assertion, but the same results were observed.

I have tried using the suggestion by #4258, but the resulting code is really slow and I can't use it as desired.
The same slow-execution effect was observed when compiling PCL with the -DPCL_ENABLE_SSE=Off -DPCL_ENABLE_AVX=Off flags, but in this case the assertion is not triggered.

Furthermore, I can not change the code of the second external library using Eigen, so the solution would have to come from the PCL library :innocent:

**Comment by themightyoarfish** [comment]
So did you confirm that the dependency library and PCL were built with the same SSE flags (such as `-march=native`)? If those mismatch, you are going to run into problems.

**Comment by AndreiCostinescu** [comment]
Hi @themightyoarfish,
Thanks for your suggestion! As it turns out, the external library was not compiled with the same flags as PCL... If I do compile it with the same flags, the error does not happen. I'm going to close this issue :+1: 
It seems there are still things to learn about the interactions between multiple pieces of code :smile:
