### ISSUE TITLE
[Features] Access violation on computing point normal

### ISSUE THREAD

**Issue by hzhshok** [PointCloudLibrary/pcl#5578]
**Describe the bug**
I write a piece code for checking the function to generating normals, and it reads dem points  from pck file which is dense point cloud with 2017x2017 resolution, but it caused the error ''access violation reading position  0x00000149DAA122A4“ when running to computing normals.

I tested on windows11 and ubuntu 20.04, they all hanppened exception( access violation or SIGSEGV), but it was on different break points, see the context(for windows) and the 'Additional context'(for ubuntu 20.04).

**Context**
The following is my code for checkfing the exception of IntegralImageNormalEstimation.
pcl::PCLPointCloud2::Ptr xyzCloudPtr(new pcl::PCLPointCloud2);
	////    pcl::PCLPointCloud2::Ptr cloud (new pcl::PCLPointCloud2);
		//pcl::io::loadPCDFile(nptFileName /*imgDeriInfo.getImgFullName()*/, *xyzCloudPtr);

	Eigen::Vector4f translation;
	Eigen::Quaternionf orientation;

	std::cout << "Hello World!\n";

	if (pcl::io::loadPCDFile(nptFileName, *xyzCloudPtr, translation, orientation) < 0) {
		std::cout << "Failed to loadPCDFile from " << nptFileName << std::endl;
		return -1;
	}

	std::cout << "Successed to load pcd file from " << nptFileName << std::endl;

	pcl::PointCloud<pcl::PointXYZ>::Ptr xyz(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::fromPCLPointCloud2(*xyzCloudPtr, *xyz);

	pcl::PointCloud<pcl::Normal>  normals;
	// Try our luck with organized integral image based normal estimation
	if (xyz->isOrganized())
	{
		pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne; // = new pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal>;
		ne.setNormalEstimationMethod(ne.AVERAGE_3D_GRADIENT);
		ne.setInputCloud(xyz);
		ne.setNormalEstimationMethod(pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal>::COVARIANCE_MATRIX);
		ne.setNormalSmoothingSize(float(/*radius*/ 0.03));
		ne.setDepthDependentSmoothing(true);
		ne.compute(normals);

		//pcl::IntegralImageNormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
		//ne.setNormalEstimationMethod(ne.AVERAGE_3D_GRADIENT);
		//ne.setMaxDepthChangeFactor(0.02f);
		//ne.setNormalSmoothingSize(10.0f);
		//ne.setInputCloud(xyzCloudPtr);
		//ne.compute(normals);
	}
	else
	{
		pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
		ne.setInputCloud(xyz);
		pcl::search::KdTree<pcl::PointXYZ>::Ptr  kdTreePtr(new pcl::search::KdTree<pcl::PointXYZ>);
		ne.setSearchMethod(kdTreePtr);
		//ne.setKSearch(0);
		ne.setRadiusSearch(/*radius*/0.03); //3 centimeter
		ne.compute(normals);
	}

	std::cout << "normals, points: " << normals.points.size() << std::endl;

**Expected behavior**
The program always happens the exception on main function 'ne.compute(normals);', and it actually caused on pcl::IntegralImageNormalEstimation<PointInT, PointOutT>::computePointNormal, and 

The code line inside pcl::IntegralImageNormalEstimation<PointInT, PointOutT>::computePointNormal which caused the exception.

217  unsigned count = integral_image_XYZ_.getFiniteElementsCount (pos_x - (rect_width_2_), pos_y - (rect_height_2_), rect_width_, rect_height_); -- this line caused exception 

**Current Behavior**

'access violation reading position  0x00000149DAA122A4“ at  integral_image_XYZ_.getFiniteElementsCount inside the function 'pcl::IntegralImageNormalEstimation<PointInT, PointOutT>::computePointNormal'.

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. If you load data e.g. from a PCD or PLY file, please provide the file.

**Screenshots/Code snippets**

In order to help explain your problem, please consider adding
* screenshots of the GUI issues
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights

**Your Environment (please complete the following information):**

 - OS:  Win11
 - Compiler:  vs2019
 - PCL Version:  1.12 x64-windows-static-md using vcpkg .
 - 
**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**
I also tested on ubuntu 20.04, i used the same code, but it happened SIGSEGV exception inside the deconstructor of pcl::IntegralImageNormalEstimation.

**Comment by mvieth** [comment]
My best first guess is that the resolution is the problem, specifically that it is odd (2017) and not even (e.g. 2016 or 2018). I will look into this as soon as I have time.

**Comment by hzhshok** [comment]
Thanks @mvieth  for your quick response,  at current time i  only ebug into code which abort on eigen something, i just a new guy on pcl, so very appreciate for your fsupport.

In addition, i also delivery the pcd file.

Regards.

[test-github.zip](https://github.com/PointCloudLibrary/pcl/files/10420241/test-github.zip)

**Comment by mvieth** [comment]
@hzhshok Thanks for the pcd file! I can say now that the resolution is not the problem. Even when I crop your cloud to 2016x2016, the problem still occurs. I think most likely is that there is a bug in PCL that happens for the specific combination of options you used (`ne.setNormalSmoothingSize(float(/*radius*/ 0.03))` and `ne.setDepthDependentSmoothing(true)`)

**Comment by hzhshok** [comment]
Thanks @mvieth!
