### ISSUE TITLE
apt install of libpcl-dev pulls in 1248 dependencies?

### ISSUE THREAD

**Issue by unphased** [PointCloudLibrary/pcl#5580]
**Expecting a more reasonable (smaller) amount of dependent software packages to be installed**

The `apt install libpcl-dev` command pulls in a very large list of dependencies. It's concerning from the perspective of a developer hoping to prevent a very large change to their system just to add PCL as a dependency on some project. 

**Context**

What are you trying to accomplish? 

- Finding some answers on what portion out of the 1248 packages pulled in by libpcl-dev that may potentially be superfluous. 
- Alternatively, if the behavior is due to some misconfiguration or other problem, getting to the bottom of the issue.

Originally noticed this "problem" while working on a dockerfile based on `nvcr.io/nvidia/l4t-pytorch:r35.1.0-pth1.12-py3` but later found the issue to be present in the `ubuntu:20.04` image and presumably affecting any ubuntu 20.04 system.

**Expected behavior**

A more reasonable (under 50, let's say) number of packages pulled in as dependencies. 

**Current Behavior**

What happens instead of the expected behavior?

In summary: 

```
5 upgraded, 1248 newly installed, 0 to remove and 13 not upgraded.
Need to get 612 MB of archives.
After this operation, 3391 MB of additional disk space will be used.
```

This doesn't look like a reasonable install size for this library. 

**To Reproduce**

I've made a trivial docker based test: 

    ❯ cat Dockerfile.test_pcl_20.04
    FROM ubuntu:20.04
    
    RUN apt update
    RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y libpcl-dev
    ❯ mkdir scratchdir    
    ❯ uname -a  
    Linux slu-5950X 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    ❯ lsb_release -a                                                       
    LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
    Distributor ID: Ubuntu                                                 
    Description:    Ubuntu 20.04.5 LTS                                     
    Release:        20.04                                                  
    Codename:       focal                                                  
    ❯ docker build -t test-pcl-20.04 -f Dockerfile.test_pcl_20.04 scratchdir > pcl_docker_build.log 2>&1

A cut-down overview (in the interest of readability) of pcl_docker_build.log follows: 

```
Sending build context to Docker daemon  1.583kB
Step 1/3 : FROM ubuntu:20.04
 ---> 20fffa419e3a
Step 2/3 : RUN apt update
 ---> Using cache
 ---> ad90ccf37923
```
I assure you the cache was created recently.

```
Step 3/3 : RUN apt install -y libpcl-dev
 ---> Running in 8f75b5e31161

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  accountsservice acl adwaita-icon-theme alsa-topology-conf alsa-ucm-conf apg
  apport apport-symptoms aptdaemon aptdaemon-data aspell aspell-en
  at-spi2-core autoconf automake autotools-dev avahi-daemon avahi-utils
  bind9-host bind9-libs binutils binutils-common binutils-x86-64-linux-gnu
  bluez bolt bsdmainutils bubblewrap build-essential ca-certificates
  cheese-common colord colord-data cpp cpp-8 cpp-9 cracklib-runtime crda
```
A very long alphabetical list continues for about 250 lines.

```
  xserver-xorg-video-vmware xterm xtrans-dev xwayland xz-utils
  yaru-theme-gnome-shell yelp yelp-xsl zenity zenity-common zlib1g zlib1g-dev
Suggested packages:
  apport-gtk | apport-kde aspell-doc spellutils autoconf-archive gnu-standards
  autoconf-doc gettext avahi-autoipd binutils-doc whois vacation
```
Around 50 lines of suggested packages. Ignoring those...

```
The following NEW packages will be installed:
  accountsservice acl adwaita-icon-theme alsa-topology-conf alsa-ucm-conf apg
  apport apport-symptoms aptdaemon aptdaemon-data aspell aspell-en
  at-spi2-core autoconf automake autotools-dev avahi-daemon avahi-utils
```
Same list of 1248 as before seen.

```
  xserver-xorg-video-vmware xterm xtrans-dev xwayland xz-utils
  yaru-theme-gnome-shell yelp yelp-xsl zenity zenity-common zlib1g-dev
The following packages will be upgraded:
  gpgv libsystemd0 libudev1 perl-base zlib1g
5 upgraded, 1248 newly installed, 0 to remove and 13 not upgraded.
Need to get 612 MB of archives.
After this operation, 3391 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 perl-base amd64 5.30.0-9ubuntu0.3 [1514 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsystemd0 amd64 245.4-4ubuntu3.19 [268 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 liblocale-gettext-perl amd64 1.07-4 [17.1 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 keyboard-configuration all 1.194ubuntu3 [190 kB]
```
Seems an unreasonable quantity of dependencies.

```
Get:1248 http://archive.ubuntu.com/ubuntu focal/universe amd64 proj-bin amd64 6.3.1-1 [88.8 kB]
Get:1249 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 pulseaudio-module-bluetooth amd64 1:13.99.1-1ubuntu3.13 [60.4 kB]
Get:1250 http://archive.ubuntu.com/ubuntu focal/main amd64 rygel amd64 0.38.3-1ubuntu1 [299 kB]
Get:1251 http://archive.ubuntu.com/ubuntu focal/main amd64 usb-modeswitch-data all 20191128-3 [32.3 kB]
Get:1252 http://archive.ubuntu.com/ubuntu focal/main amd64 usb-modeswitch amd64 2.5.2+repack0-2ubuntu3 [53.1 kB]
Get:1253 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 xserver-xorg-legacy amd64 2:1.20.13-1ubuntu1~20.04.5 [32.7 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 612 MB in 1min 6s (9327 kB/s)
(Reading database ... 
```
An unreasonable quantity of GET requests.

```
aspell-autobuildhash: processing: en [en_GB-ize-w_accents-only].
aspell-autobuildhash: processing: en [en_GB-ize-wo_accents-only].
aspell-autobuildhash: processing: en [en_GB-variant_0].
aspell-autobuildhash: processing: en [en_GB-variant_1].
aspell-autobuildhash: processing: en [en_US-w_accents-only].
aspell-autobuildhash: processing: en [en_US-wo_accents-only].
Processing triggers for ca-certificates (20211016ubuntu0.20.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-3ubuntu0.4) ...
Processing triggers for rygel (0.38.3-1ubuntu1) ...
Processing triggers for sgml-base (1.29.1) ...
Removing intermediate container e48610dc4738
 ---> 3e48f64c845f
Successfully built 3e48f64c845f
Successfully tagged test-pcl-20.04:latest
```

The entire docker build of libpcl-dev takes a pretty long time to run, in this case 357 seconds. Again I wouldn't consider that to be a reasonable amount of time and as you can see above the network fetch only accounted for 66 of those seconds. 

- I would say that 612MB fetched is way more than it looks like should be taking place
- 3391MB of disk consumed is an even more serious overreach in my eyes
- 357 seconds to complete the build (6 minutes) is comparatively not as much of a concern

**Further context is on the way...**
- Currently obtaining output from `debtree`. The tree is very large. Waiting for `dot` to execute still.

**Comment by unphased** [comment]
Here we have a svg from debtree. 
![pcl](https://user-images.githubusercontent.com/1542910/212438662-33d279d4-942d-45fd-b9b7-e4e33d931a26.svg)

**Comment by unphased** [comment]
Overall I think I understand what's going on, there's pretty liberal dependencies touched by the project based on its wide scope in implementing many algorithms and visualization methods from many places. However I believe there should exist a package that is suitable for providing headers and libraries for building code against which can be more than a hundred times less resource intensive to deploy for CI purposes.

**Comment by jspricke** [comment]
There is not much we can do here. The direct dependencies are: libboost-all-dev, libeigen3-dev, libflann-dev, libvtk9-dev, libqhull-dev, libvtk9-qt-dev, libusb-1.0-0-dev, libopenni-dev and I think that's reasonable (taken from `apt show libpcl-dev`). The Debian project assumes that a Developer has enough disk space.
