### ISSUE TITLE
[compile error] ConvexHull static linking error

### ISSUE THREAD

**Issue by GengGode** [PointCloudLibrary/pcl#5587]
**Describe the error**
1>------ 已启动生成: 项目: test_pcl, 配置: Release x64 ------
1>test_pcl.cpp
1>E:\vcpkg\installed\x64-windows-static\include\Eigen\src\Core\arch\Default\Half.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>E:\vcpkg\installed\x64-windows-static\include\Eigen\src\Core\arch\Default\BFloat16.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>E:\vcpkg\installed\x64-windows-static\include\Eigen\src\Core\arch\Default\GenericPacketMathFunctions.h(676,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version 已经在 qhullstatic.lib(global.c.obj) 中定义
1>qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version2 已经在 qhullstatic.lib(global.c.obj) 中定义
1>C:\Users\xxxxxx\source\repos\tmp\test_pcl\x64\Release\test_pcl.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
1>已完成生成项目“test_pcl.vcxproj”的操作 - 失败。
========== 版本: 0 成功，1 失败，0 更新，0 跳过 ==========
**To Reproduce**
- Step.1 install vcpkg
``` ps
git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
cd .\vcpkg\
```
- Step.2 vcpkg install pcl,opencv,fmt,json11
``` ps
cd .\vcpkg\
.\vcpkg install opencv:x64-windows-static pcl:x64-windows-static fmt:x64-windows-static json11:x64-windows-static
```
- Step.3 vcpkg integrate install
``` ps
.\vcpkg integrate install
```
- Step.3 VS create c++ consnole project
- Step.4 main.cpp as :
``` c++
#include <iostream>
#include <pcl/common/common.h>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/filters/crop_hull.h>
#include <pcl/surface/convex_hull.h>
int main()
{
	pcl::ConvexHull<pcl::PointXYZ> hull;
}
```
- Step.4 setting Release/x64 vcpkg>`Use Static Libraries` = true AND C/C++>`CodeGen`>`/MT`
- Step.5 build Release/x64  and fail :)

**Screenshots/Code snippets/Build information**
![image](https://user-images.githubusercontent.com/47711102/213894620-61ee6de2-821d-490c-b12d-dde5c0212b09.png)

**Your Environment (please complete the following information):**

 - OS: win10 10.0.19045.2486
 - Compiler: VS2022
 - PCL Version  1.12.0#7
 - PCL Type:  Installed with VCPKG

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No
 - List and Version of dependencies used: from vcpkg install
 - Compilation flags are used: no

**Possible Solution**

I tried to delete two files from vcpkg/lib, but only delete file `qhullstatic.lib` can run normally. However, in the subsequent test, the program was full of memory when loading the ply file. I don't know the relationship between them, but it is obvious that deleting files is not the way to repair

**Additional context**

Because of some reasons, static links must be used. It's a pity if ConvexHull can't be used. It's strange that there are no other problems

Thank everyone

**Comment by mvieth** [comment]
@GengGode vcpkg applies some own changes to PCL that may cause this problem, see here: https://github.com/microsoft/vcpkg/blob/master/ports/pcl/fix-find-qhull.patch
I recently created a pull request to update PCL on vcpkg to the latest version 1.13.0: https://github.com/microsoft/vcpkg/pull/28818 This pull request also removes that patch.
So please wait until this pull request is merged and then try again.

**Comment by GengGode** [comment]
Thank you for your work. If his version is updated, I will test it as soon as possible. Thank you very much

**Comment by mvieth** [comment]
@GengGode The pull request that updates PCL on VCPKG is merged now. Please try again with PCL 1.13.0.

**Comment by GengGode** [comment]
I updated it with the following command. Here is the screenshot after the update
```
git pull
.\vcpkg.exe update
.\vcpkg upgrade --no-dry-run
```
![image](https://user-images.githubusercontent.com/47711102/217139428-8fdcf449-c835-4047-be38-30294d9cdd9e.png)

But the problem has not been solved. The same error is still reported

![image](https://user-images.githubusercontent.com/47711102/217139757-5e061532-1b82-4f99-b4d4-f8245269a53a.png)
```
1>qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version 已经在 qhullstatic.lib(global.c.obj) 中定义
1>qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version2 已经在 qhullstatic.lib(global.c.obj) 中定义
```

Do I need to clear some vcpkg?

**Comment by mvieth** [comment]
@GengGode Have you tried deleting all build files of your project and building again (as if you are building it for the first time)? It could be that VS stored some settings from the old PCL 1.12.0 installation that haven't been cleared.

**Comment by GengGode** [comment]
yes, I executed the cleaning solution, and then generated.
I noticed that `qhullstatic.lib`&`qhullstatic_r.lib` files still exist in the lib directory of vcpkg, and they are not updated.
![image](https://user-images.githubusercontent.com/47711102/217211679-56b29579-415b-4224-a837-40a59539e4e0.png)
Do I need to remove the package in vcpkg and reinstall it?

**Comment by mvieth** [comment]
@GengGode To be honest, I am not a vcpkg expert. You can try reinstalling, but I don't think it is a problem that the qhull libraries haven't been updated.
Can you show the exact commands VS uses when building your project?

**Comment by GengGode** [comment]
```
C:\Users\XXX\source\repos\tmp\test_pcl>msbuild test_pcl.sln  -p:Platform=x64 -p:Configuration=Release
```
```
MSBuild version 17.4.1+9a89d02ff for .NET Framework
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
生成启动时间为 2023/2/8 10:19:28。
节点 1 上的项目“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|x64”。
项目“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl.sln”(1)正在节点 1 上生成“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj”(2) (默认目标)。
InitializeBuildStatus:
  正在对“x64\Release\test_pcl.tlog\unsuccessfulbuild”执行 Touch 任务。
VcpkgTripletSelection:
  Using triplet "x64-windows-static" from "E:\vcpkg\installed\x64-windows-static\"
  Using normalized configuration "Release"
ClCompile:
  所有输出均为最新。
Link:
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\XXX\source\repos\tmp\test_pcl
  \x64\Release\test_pcl.exe" /NOLOGO /LIBPATH:"E:\vcpkg\installed\x64-windows-static\lib" /LIBPATH:"E:\vcpkg\installed\x64-windows-static\lib\manual-link" kernel32.lib user32.lib gd
  i32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "E:\vcpkg\installed\x64-windows-static\lib\*.lib" /MANIFEST /MAN
  IFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\XXX\source\repos\tmp\test_pcl\x64\Release\test_pcl.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:
  ICF /LTCG:incremental /LTCGOUT:"x64\Release\test_pcl.iobj" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\XXX\source\repos\tmp\test_pcl\x64\Release\test_pcl.lib" /MACHINE
  :X64 x64\Release\test_pcl.obj
qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version 已经在 qhullstatic.lib(global.c.obj) 中定义 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj]
qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version2 已经在 qhullstatic.lib(global.c.obj) 中定义 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj]
C:\Users\XXX\source\repos\tmp\test_pcl\x64\Release\test_pcl.exe : fatal error LNK1169: 找到一个或多个多重定义的符号 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj]
已完成生成项目“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj”(默认目标)的操作 - 失败。

已完成生成项目“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl.sln”(默认目标)的操作 - 失败。


生成失败。

“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl.sln”(默认目标) (1) ->
“C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj”(默认目标) (2) ->
(Link 目标) ->
  qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version 已经在 qhullstatic.lib(global.c.obj) 中定义 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj]
  qhullstatic_r.lib(global_r.c.obj) : error LNK2005: qh_version2 已经在 qhullstatic.lib(global.c.obj) 中定义 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj]
  C:\Users\XXX\source\repos\tmp\test_pcl\x64\Release\test_pcl.exe : fatal error LNK1169: 找到一个或多个多重定义的符号 [C:\Users\XXX\source\repos\tmp\test_pcl\test_pcl\test_pcl.vcxproj
]

    0 个警告
    3 个错误

已用时间 00:00:00.51
```

**Comment by GengGode** [comment]
[test_pcl.zip](https://github.com/PointCloudLibrary/pcl/files/10681077/test_pcl.zip)

The test solution are here.

**Comment by mvieth** [comment]
@GengGode  We recommend to use CMake as described here: https://pcl.readthedocs.io/projects/tutorials/en/master/pcl_vcpkg_windows.html
If I interpret the linking command correctly, VS basically links to all libraries in `.../vcpkg/installed/x64-windows-static/lib` . And qhullstatic.lib and qhullstatic_r.lib are not meant be be used at the same time. CMake should link them correctly.

**Comment by GengGode** [comment]
It still seems to be OK. When I use pcl-cmake-minimum-master and CMake GUI to generate, although I need to manually modify the lib path, it can be compiled and run.
![image](https://user-images.githubusercontent.com/47711102/217730470-552532b7-3c7a-4d4d-89f8-0b03de486997.png)
![image](https://user-images.githubusercontent.com/47711102/217730866-108e5e13-1bc4-4ad7-b0a6-46b66726023f.png)

**Comment by GengGode** [comment]
But the project under VS and vcpkg is still the original problem.

It can be compiled and run normally in MD mode

**Comment by GengGode** [comment]
Because of some historical problems, I can only compile the project using it under MT.
Though, still appreciate your work!

**Comment by mvieth** [comment]
Seems like you can tell CMake/vcpkg to use the static libraries: https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/
Either way, the double-defined `qh_version`/`qh_version` is not a PCL problem. If you can't or don't want to use CMake, you either have to find a way to tell VS not to link to `qhullstatic.lib`, or try deleting `qhullstatic.lib`.
