### ISSUE TITLE
Whether there are tools that can extract the line structure (boundary)

### ISSUE THREAD

**Issue by ZhangZh3ng** [PointCloudLibrary/pcl#5592]
I need to extract line struct from 3d point cloud like this, I want to know whether it can be realized through PCL, thanks!
![image](https://user-images.githubusercontent.com/63040423/215040658-beca05b4-7972-4750-8dc1-db939b4cd2d6.png)

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
