### ISSUE TITLE
[Help] pcl::RegionGrowing algorithm issue

### ISSUE THREAD

**Issue by 155cannon** [PointCloudLibrary/pcl#5594]
I find pcl::RegionGrowing algorithm with the same parameters generates different output results when input pointcloud rotates. Why?

**Comment by mvieth** [comment]
@155cannon  You are not giving enough information.
What do you mean with "different output results"? Please post screenshots that show what is different.
How much rotation are we talking about? Just a few degrees or like 90 degrees?
Please post a code snippet that shows the parameters you use.
Which PCL version are you using?

**Comment by mvieth** [comment]
@155cannon If you don't reply soon, I will close this issue
