### ISSUE TITLE
"support cuda 12"

### ISSUE THREAD

**Issue by zhangzscn** [PointCloudLibrary/pcl#5602]
In ubuntu 22.04,using cmake 3.25.2,build the pcl with cuda 12 hase some error:

Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE ClangFormat_VERSION) (Required is at least version "14")
Using CPU native flags for SSE optimization: -msse4.2 -mfpmath=sse -march=native
Found OpenMP, spec date 201511
Eigen found (include: /usr/include/eigen3, version: 3.4.0)
FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
Checking for module 'metslib'
  No package 'metslib' found
Found Qhull version 8.0.2
Found CUDA Toolkit v12.0
CMake Error at /snap/cmake/1216/share/cmake-3.25/Modules/CMakeDetermineCUDACompiler.cmake:277 (message):
  CMAKE_CUDA_ARCHITECTURES must be non-empty if set.
Call Stack (most recent call first):
  cmake/pcl_find_cuda.cmake:13 (enable_language)
  CMakeLists.txt:380 (include)

Configuring incomplete, errors occurred!

**Comment by zhangzscn** [comment]
add the code to cmake file
# Find CUDA
if(MSVC)
  # Setting this to true brakes Visual Studio builds.
  set(CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE OFF CACHE BOOL "CUDA_ATTACH_VS_BUILD_RULE_TO_CUDA_FILE")
endif()

set(CUDA_FIND_QUIETLY TRUE)
find_package(CUDA 9.0)

if(CUDA_FOUND)
  message(STATUS "Found CUDA Toolkit v${CUDA_VERSION_STRING}")
  message(STATUS "CMAKE_CUDA_ARCHITECTURES: ${CMAKE_CUDA_ARCHITECTURES}")

@larshg It is empty。

The C compiler identification is GNU 11.3.0
The CXX compiler identification is GNU 11.3.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: /usr/bin/cc - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: /usr/bin/c++ - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
Performing Test LIBATOMIC_NOT_NEEDED
Performing Test LIBATOMIC_NOT_NEEDED - Failed
Could NOT find ClangFormat (missing: ClangFormat_EXECUTABLE ClangFormat_VERSION) (Required is at least version "14")
Performing Test HAVE_MARCH
Performing Test HAVE_MARCH - Success
Performing Test HAVE_MM_MALLOC
Performing Test HAVE_MM_MALLOC - Success
Performing Test HAVE_POSIX_MEMALIGN
Performing Test HAVE_POSIX_MEMALIGN - Success
Performing Test HAVE_SSE4_2_EXTENSIONS
Performing Test HAVE_SSE4_2_EXTENSIONS - Success
Using CPU native flags for SSE optimization: -msse4.2 -mfpmath=sse -march=native
Performing Test HAVE_AVX2
Performing Test HAVE_AVX2 - Success
Found OpenMP_C: -fopenmp (found version "4.5") 
Found OpenMP_CXX: -fopenmp (found version "4.5") 
Found OpenMP: TRUE (found version "4.5") found components: C CXX 
Found OpenMP, spec date 201511
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
Found Threads: TRUE  
Checking for module 'eigen3'
  Found eigen3, version 3.4.0
Found Eigen: /usr/include/eigen3 (Required is at least version "3.3") 
Eigen found (include: /usr/include/eigen3, version: 3.4.0)
Checking for module 'flann>=1.9.1'
  Found flann, version 1.9.1
Found FLANN: /usr/lib/x86_64-linux-gnu/libflann_cpp.so (Required is at least version "1.9.1") 
FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
Checking for module 'libusb-1.0'
  Found libusb-1.0, version 1.0.25
Found libusb: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
OpenNI grabber support: not building because OpenNI not found
Could NOT find OpenNI2 (missing: OPENNI2_LIBRARIES OPENNI2_INCLUDE_DIRS) 
OpenNI2 grabber support: not building because OpenNI2 not found
Could NOT find Ensenso (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
IDS-Imaging Ensenso camera support: not building because Ensenso not found
Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
David Vision Systems SDK support: not building because davidSDK not found
Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
DepthSense SDK support: not building because DSSDK not found
Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
RealSense SDK support: not building because RSSDK not found
Could NOT find RSSDK2
RealSense SDK 2.0 (librealsense) support: not building because RSSDK2 not found
Checking for module 'metslib'
  No package 'metslib' found
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
Found Qhull version 8.0.2
Found CUDA Toolkit v12.0
CMAKE_CUDA_ARCHITECTURES: 
The CUDA compiler identification is unknown
CMake Error at /snap/cmake/1216/share/cmake-3.25/Modules/CMakeDetermineCUDACompiler.cmake:603 (message):
  Failed to detect a default CUDA architecture.

  

  Compiler output:

Call Stack (most recent call first):
  cmake/pcl_find_cuda.cmake:13 (enable_language)
  CMakeLists.txt:380 (include)


Configuring incomplete, errors occurred!

**Comment by mvieth** [comment]
@zhangzscn Try defining the `CUDA_PATH` environment variable, for example by putting `CUDA_PATH=/usr/local/cuda` before the CMake call (`CUDA_PATH=/usr/local/cuda cmake ..`)

**Comment by zhangzscn** [comment]
set this work

-DCMAKE_CUDA_ARCHITECTURES=86 -DCMAKE_CUDA_COMPILER=“/usr/local/cuda/bin/nvcc”
