### ISSUE TITLE
[segmentation] Any chance of making SACSegmentation faster to compile?

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5611]
This might be a fringe issue, but I wanted to raise awareness.
I recently profiled compile times, and I found that `SACSegmentation::initSACModel<PointXYZI>`'s instantiation alone takes more than 5 seconds on my M1 macbook pro. PCL is template-heavy, but even for that this seems excessive. The bulk of this time the compiler spends on instantiating things that are not actually used – I am fitting a plane for instance, but all kinds of other models are instantiated as well. Thus the compiler spends 

- 1+s on `SampleConsensusModelCircle2D`
- 1+s on `SampleConsensusModelCircle3D`
- 2+s on `SampleConsensusModelEllipse3D`

none of which I am actually using.

Attached is a profile that can be viewed with `chrome://tracing` in chrome. 

[make_segmenter.cpp_sac.json.zip](https://github.com/PointCloudLibrary/pcl/files/10775089/make_segmenter.cpp_sac.json.zip)

**Context**

Code is very slow to build. When used in more than one place without declaring `extern` templates. I had to enable `PCL_NO_PRECOMPILE` as it would lead to nonsensical runtime crashes (see  #5579).

**Expected behavior**

Less time is spent on instantiating unused templates.

**Current Behavior**

Much time is spent on instantiating unused templates.

**Describe the solution you'd like**

Would it make sense to either do refactoring, or add some macros that would guard which model types got instantiated?

**Additional context**

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/11613312/219888658-f55b8cda-508e-4e5f-9bd6-acfb10b1dac7.png">

**Comment by mvieth** [comment]
> Would it make sense to either do refactoring,

If you have a specific suggestion for a refactoring, feel free to describe it here, then we can discuss it

> or add some macros that would guard which model types got instantiated?

In my opinion it wouldn't make much sense to limit the model types the user can choose from at runtime. I doubt many people would use such macros (or would even become aware of their existence). As you noted, this is only a problem when using `PCL_NO_PRECOMPILE`. Of course, nothing stops you from adding such macros or commenting out some model types in your fork/local copy of PCL.
If you know that you only need a specific model type, I would recommend to not use SACSegmentation and instead use the method described in this tutorial: https://pcl.readthedocs.io/projects/tutorials/en/master/random_sample_consensus.html (see also sac_segmentation.hpp for reference)
This is slightly more complex to use, but will improve your compile time, and will even give you access to a few model and method options not available via SACSegmentation.

**Comment by mvieth** [comment]
@themightyoarfish Any reply to my comment? Did my previous suggestions help you? Do you have a specific idea for refactoring SACSegmentation that you want to discuss? If not, I will probably close this issue for the reasons I described ...

**Comment by themightyoarfish** [comment]
I am hoping to employ this suggestion soon, just did not get around to it. I suppose I can close this, as the number of people impacted will be fairly low.

**Comment by themightyoarfish** [comment]
With the API you linked, what is the way to specify initial model parameters? I can't seem to find an equivalent to `SACSegmentation::segment` which takes initial parameters.

**Comment by mvieth** [comment]
How do you specify initial model parameters with `SACSegmentation`? Both parameters of `segment` are pure output parameters, not input-output parameters. The documentation also says this: https://pointclouds.org/documentation/classpcl_1_1_s_a_c_segmentation.html#a514043477fc0efc79aaae0b595cc566c

**Comment by themightyoarfish** [comment]
ummm … i was going off of this [answer](https://stackoverflow.com/a/61615728/2397253) when I asked a few years ago, i'm not sure if this is still valid (or ever was)? 

In any case, is there no way to initialize the model? It seems fairly useful for many real world use cases where you can often know the rough location, but have no hope of converging with random initialization.

**Comment by mvieth** [comment]
I can say for sure that `SACSegmentation::segment` does not use the values given in `inliers` or `model_coefficients`, so you can't pass an initial estimate via these parameters. Feel free to check the code and the git history to confirm this yourself (https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/impl/sac_segmentation.hpp). `memcpy` may have caused the confusion, but considering that the first parameter of `memcpy` is the destination, it copies the values to, not from, `model_coefficients`.
Given how RANSAC works, there isn't really a way to give an initial guess (this can be either good or bad, depending on the situation). But if you know that some points in your cloud definitely do not belong to the model you want to find, you can use `setIndices` to only look at points that could belong to it. Also, if know which models are plausible and which aren't, you can specify model constraints (e.g. plane direction, min and max radius of a sphere, etc). If you use the API I linked, you can also use [setModelConstraints](https://pointclouds.org/documentation/classpcl_1_1_sample_consensus_model.html#a6e225e7e1e57af8191a4b6ecb20026ca) to specify arbitrary constraints.

**Comment by themightyoarfish** [comment]
Yeah, I looked at the code and apparently, the answer I got from the maintainer was incorrect. I guess I'll try my luck with indices instead.
