### ISSUE TITLE
Could not import the pcl correctly W/ plc(1.12.0) installed on anaconda(3.9.13)!!!

### ISSUE THREAD

**Issue by kt-rax** [PointCloudLibrary/pcl#5612]
I have the pcl installed on the conda. 
![image](https://user-images.githubusercontent.com/18671477/220054196-7751c255-9ede-4ea9-a8f7-b226bbd32ae3.png)
![image](https://user-images.githubusercontent.com/18671477/220054480-7fdb4ad2-79d9-4ef9-8adf-df3f2ed39f04.png)
But could not find it in python. Why? Is there anybody meet the same issue? Thanks!
![image](https://user-images.githubusercontent.com/18671477/220054831-f3bb1b4e-78c3-49b9-8f06-d4aca5235a9b.png)

**Comment by larshg** [comment]
Using PCL with python is not supported, so you would need to search for help elsewhere.
