### ISSUE TITLE
[pcd_io/ply_io] write pcd or ply file will lose some points information if I have lots of points 

### ISSUE THREAD

**Issue by Lurvelly** [PointCloudLibrary/pcl#5617]
Hi All, 

**Describe the bug**

I'm trying to save a large Point Cloud that about 295'445'813 points.  I have saved the the Point Cloud in a PCD file successfully, but when I trying to read this PCD file via CloudCompare, I found that some points disappear. 

Then I try to use pcd::PCDReader to check the PCD file that I saved. I found that these points after index "268'435'456" (268'435'457 th) are not the raw data.  

Sometimes these error points have the same data as the raw PointCloud begin. It seems like a loop.

I also try to save Point Cloud as a PLY file, but the similar reuslt.

Look at screenshot below, point in readCloud at index 268'435'456 is the same as allCloud at index 0, not the same as point in allCloud at the same index. The PCD file will lose some points information !!!

![Screenshot from 2023-02-23 03-48-37](https://user-images.githubusercontent.com/17422260/220817413-d976613c-ccf0-4a95-821f-ab0d97b606e3.png)

**To Reproduce**

Just try to save PointCloud with lots of points (more than 295'445'813) to a PCD or PLY file. 

I have attached the source file "main.cpp" and "CMakeLists.txt"

[test_code.tar.gz](https://github.com/PointCloudLibrary/pcl/files/10810016/test_code.tar.gz)

**Screenshots/Code snippets**

```c++
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>

constexpr size_t total{295'445'813};

using PointType = pcl::PointXYZI;

pcl::PointCloud<PointType>::Ptr allCloud{new pcl::PointCloud<PointType>()};
pcl::PointCloud<PointType>::Ptr readCloud{new pcl::PointCloud<PointType>()};

pcl::PCDWriter* pcdWriter {new pcl::PCDWriter()};
pcl::PCDReader* pcdReader {new pcl::PCDReader()};

int main(int argc, char** argv)
{
    allCloud->resize(total);
    for(size_t i = 0; i < total; i++)
    {
        allCloud->points[i].x = (float)(i/10.0f);
        allCloud->points[i].y = (float)(i/20.0f);
        allCloud->points[i].z = (float)(i *10 + i/10.0f);
        allCloud->points[i].intensity = 0.0f;
    }

    pcdWriter->write("allCloud.pcd", *allCloud, true);
    pcdReader->read("allCloud.pcd", *readCloud);

    std::cout << "readCloud->size() :" << readCloud->size() << std::endl;
    std::cout << "allCloud->size() :" << allCloud->size() << std::endl;

    size_t j = 0;
    if(readCloud->size() == allCloud->size())
    {
        for(size_t i = 0; i < allCloud->size(); i++)
        {
            if(abs(readCloud->points[i].x - allCloud->points[i].x) > 0.01)
            {
                std::cout << " readCloud[" << i << "]: " <<  readCloud->points[i].x << " | " << readCloud->points[i].y << " | " <<readCloud->points[i].z << std::endl;
                std::cout << " allCloud[" << i << "]: " <<  allCloud->points[i].x << " | " << allCloud->points[i].y << " | " << allCloud->points[i].z << std::endl;
                std::cout << " allCloud[" << j << "]: " <<  allCloud->points[j].x << " | " << allCloud->points[j].y << " | " << allCloud->points[j].z << std::endl;
                j++;
            }
        }
    }
}



```

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0]
 - PCL Version [1.10]

**Comment by mvieth** [comment]
Hi, the problem is likely an overflow of an `int`. You can solve this by compiling PCL 1.13.0 from source while setting the CMake option [PCL_INDEX_SIZE](https://github.com/PointCloudLibrary/pcl/blob/master/cmake/pcl_options.cmake#L96) to 64 (either via ccmake or `cmake -DPCL_INDEX_SIZE=64 ..`)

**Comment by Lurvelly** [comment]
Hi, @mvieth 

Thanks for your rapid reply. 
I have changed my PLC version  from 1.10 to 1.13.0 and set the CMake option PCL_INDEX_SIZE to 64. It works now.

**Comment by mvieth** [comment]
Beginning with PCL 1.13.1, up to 2 billion points (2^31) can be read from a file without changing PCL_INDEX_SIZE. See this commit: https://github.com/PointCloudLibrary/pcl/commit/d47f6d7fa6026e77e6d408b7c3e66e8dc40dfc49
