### ISSUE TITLE
error while using pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal>

### ISSUE THREAD

**Issue by buger-make** [PointCloudLibrary/pcl#5622]
Hi, i'm using the latest version(1.13.0). I compile it successfully(ubuntu22.04 wsl2). But when i write this line code
`pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> ne;`, 
it raises an error:

- /usr/bin/ld: CMakeFiles/test.dir/main.cpp.o:(.data.rel.ro._ZTVN3pcl16NormalEstimationINS_8PointXYZENS_6NormalEEE[_ZTVN3pcl16NormalEstimationINS_8PointXYZENS_6NormalEEE]+0x58): undefined reference to `pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal>::computeFeature(pcl::PointCloud<pcl::Normal>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:168: test] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

This is main.cpp:
```
#include <iostream>
#include <vector>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/search/search.h>
#include <pcl/search/kdtree.h>
#include <pcl/features/normal_3d.h>
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/filters/passthrough.h>
#include <pcl/segmentation/region_growing.h>
using namespace std;


int main()
{
    pcl::search::Search<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ>);
    pcl::PointCloud <pcl::Normal>::Ptr normals (new pcl::PointCloud <pcl::Normal>);
    pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> ne;
    cout << "can be done" << endl;
    return 0;
}
```

And this is CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)
project(test)

set(Qt6_DIR "/home/zhu/Qt/6.4.2/gcc_64/lib/cmake/Qt6")

find_package(PCL REQUIRED COMPONENTS io visualization filters)
find_package(Boost REQUIRED)
include_directories(${PCL_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(test main.cpp)
target_link_libraries(test ${PCL_LIBRARIES} ${Boost_LIBRARIES})
```

what should i do?

**Comment by mvieth** [comment]
@buger-make You have to list all PCL modules in `find_package` that you want to use. You forgot to list `features`.
Alternatively, you can use `find_package(PCL REQUIRED)` to have _all_ PCL modules available.
See also https://pcl.readthedocs.io/projects/tutorials/en/master/using_pcl_pcl_config.html

**Comment by buger-make** [comment]
ohhhhh!!!  it works.  thank you 👍

**Comment by mvieth** [comment]
@buger-make Out of interest, and to avoid others running into the same problem: where did you get your CMakeLists.txt from? Did you follow a tutorial?
