### ISSUE TITLE
PCL-CUDA Integration On Windows Platform

### ISSUE THREAD

**Issue by VrindaSav** [PointCloudLibrary/pcl#5623]
Hello All,

I am trying to integrate PCL 1.13.0 with Cuda 11.6 on Windows platform. But during my research I came across couple of things which I want to confirm and find out some solution for the same.

The link below mentions that 

Windows is currently not officially supported for the GPU methods.

https://pcl.readthedocs.io/projects/tutorials/en/master/gpu_install.html#gpu-install

Can anybody tell me whether my interpretation of PCL-CUDA integration is not possible on Windows platform is correct or there there is some way we can achieve this.

Thanks

**Comment by mvieth** [comment]
You may be able to achieve what you want by installing PCL via vcpkg while activating the `cuda` feature of the PCL package

**Comment by VrindaSav** [comment]
Thanks Markus. Will try using vcpkg
Thanks & Best Regards,

Vrinda Savargaonkar
+919884509568

**Comment by PatricianEagle** [comment]
I have tried to install pcl via vcpkg while activating the cuda feature of the PCL package, but i still can't use CUDA or gpu in VS2019, and the Gpu-related header file is not found in the installation directory of vcpkg.

**Comment by larshg** [comment]
> I have tried to install pcl via vcpkg while activating the cuda feature of the PCL package, but i still can't use CUDA or gpu in VS2019, and the Gpu-related header file is not found in the installation directory of vcpkg.Have you solved the problem?

What vcpkg command do you run?

**Comment by PatricianEagle** [comment]
> > I have tried to install pcl via vcpkg while activating the cuda feature of the PCL package, but i still can't use CUDA or gpu in VS2019, and the Gpu-related header file is not found in the installation directory of vcpkg.Have you solved the problem?
> 
> What vcpkg command do you run?

vcpkg install pcl[cuda]:x64-windows

**Comment by VrindaSav** [comment]
I will look into this and get back to you.

Thanks

Vrinda

**Comment by PatricianEagle** [comment]
Have you solved the problem?

**Comment by VrindaSav** [comment]
Tried installation with the below given command

vcpkg install pcl[cuda]:x64-windows

It is giving linker errors

Regards,
Vrinda

**Comment by mvieth** [comment]
@VrindaSav What kind of linker errors? Please post the error messages
@PatricianEagle What is the output when you run `vcpkg install pcl[cuda]:x64-windows`?

**Comment by PatricianEagle** [comment]
> @VrindaSav What kind of linker errors? Please post the error messages @PatricianEagle What is the output when you run `vcpkg install pcl[cuda]:x64-windows`?
It ended normally.
And now its output is
```
The following packages are already installed:
pcl[core,cuda]:x64-windows -> 1.13.0
pcl:x64-windows is already installed
```

**Comment by mynickmynick** [comment]
in my experience if i start adding or deinstalling stuff, vcpkg makes often a mess with any package (not only pcl). In my experience when it starts giving errors i reset the all vcpkg repo from scratch, checkout a tagged commit and reinstall everything i need..... may be I am too simplicistic....

**Comment by larshg** [comment]
Closing due to no response.
