### ISSUE TITLE
Compilation failure using pcl::MultiscaleFeaturePersistence for pcl::PFHSignature125 and pcl::SHOT352 feature estimator instances

### ISSUE THREAD

**Issue by JackCao-Git** [PointCloudLibrary/pcl#5625]
### The compilation errors:
**1.pcl::MultiscaleFeaturePersistence + pcl::SHOT352**
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __cdecl pcl::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::SHOT352>::determinePersistentFeatures(class pcl::PointCloud<struct pcl::SHOT352> &,class std::shared_ptr<class std::vector<int,class std::allocator<int> > > &)" (?determinePersistentFeatures@?$MultiscaleFeaturePersistence@UPointXYZ@pcl@@USHOT352@2@@pcl@@QEAAXAEAV?$PointCloud@USHOT352@pcl@@@2@AEAV?$shared_ptr@V?$vector@HV?$allocator@H@std@@@std@@@std@@@Z)	PointCloud_vcpkg	D:\Users\...\PointCloud_vcpkg\multi_scale_shot_feature_persistence.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl pcl::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::SHOT352>::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::SHOT352>(void)" (??0?$MultiscaleFeaturePersistence@UPointXYZ@pcl@@USHOT352@2@@pcl@@QEAA@XZ)	PointCloud_vcpkg	D:\Users\...\PointCloud_vcpkg\multi_scale_shot_feature_persistence.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	PointCloud_vcpkg	D:\Users\...\PointCloud_vcpkg\x64\Release\PointCloud_vcpkg.exe	1	

**2.pcl::MultiscaleFeaturePersistence + pcl::PFHSignature125**
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __cdecl pcl::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::PFHSignature125>::determinePersistentFeatures(class pcl::PointCloud<struct pcl::PFHSignature125> &,class std::shared_ptr<class std::vector<int,class std::allocator<int> > > &)" (?determinePersistentFeatures@?$MultiscaleFeaturePersistence@UPointXYZ@pcl@@UPFHSignature125@2@@pcl@@QEAAXAEAV?$PointCloud@UPFHSignature125@pcl@@@2@AEAV?$shared_ptr@V?$vector@HV?$allocator@H@std@@@std@@@std@@@Z)	PointCloud-FeaturesDiscriptors	D:\Users\...\PointCloud_vcpkg\multi_scale_pfh_feature_persistence.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl pcl::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::PFHSignature125>::MultiscaleFeaturePersistence<struct pcl::PointXYZ,struct pcl::PFHSignature125>(void)" (??0?$MultiscaleFeaturePersistence@UPointXYZ@pcl@@UPFHSignature125@2@@pcl@@QEAA@XZ)	PointCloud-FeaturesDiscriptors	D:\Users\...\PointCloud_vcpkg\multi_scale_pfh_feature_persistence.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	PointCloud-FeaturesDiscriptors	D:\Users\...\PointCloud_vcpkg\x64\Release\PointCloud_vcpkg.exe	1	

### **Code snippets**
The following is the source code of the compilation error.
**1.pcl::MultiscaleFeaturePersistence + pcl::SHOT352**
```
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/common/io.h>
#include <pcl/filters/extract_indices.h>
#include <pcl/features/normal_3d_omp.h>
#include <pcl/features/shot.h>
#include <pcl/features/multiscale_feature_persistence.h>
#include <boost/thread/thread.hpp>
//#include <pcl/visualization/pcl_visualizer.h>
//#include <pcl/visualization/cloud_viewer.h>

int
main() {
	/********************* ReadPointCloud *********************/
	pcl::PointCloud<pcl::PointXYZ>::Ptr targetPointCloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile<pcl::PointXYZ>("D:/Users/.../skin_P_Clipped_U.pcd", *targetPointCloud);
	std::cout << "The size of targetPointCloud" << targetPointCloud->points.size() << std::endl;

	/********************* SurfaceNormal *********************/
	pcl::NormalEstimationOMP<pcl::PointXYZ, pcl::Normal> targetNormalEstimator;
	targetNormalEstimator.setInputCloud(targetPointCloud);
	targetNormalEstimator.setNumberOfThreads(6);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr targetNormalKdTree(new pcl::search::KdTree<pcl::PointXYZ>);
	targetNormalEstimator.setRadiusSearch(1.0);			
	pcl::PointCloud<pcl::Normal>::Ptr targetPointCloudNormal(new pcl::PointCloud< pcl::Normal>);
	targetNormalEstimator.compute(*targetPointCloudNormal);

	/********************* MultiscaleFeaturePersistence *********************/
	pcl::MultiscaleFeaturePersistence<pcl::PointXYZ, pcl::SHOT352> mfpSHOT;
	std::vector<float> scaleValues{ 2.0, 2.2, 2.4, 2.6, 2.8, 3.0 };
	mfpSHOT.setScalesVector(scaleValues);
	mfpSHOT.setAlpha(1.0);

	pcl::SHOTEstimation<pcl::PointXYZ, pcl::Normal, pcl::SHOT352>::Ptr targetShotComputor(new pcl::SHOTEstimation<pcl::PointXYZ, pcl::Normal, pcl::SHOT352>());
	targetShotComputor->setInputCloud(targetPointCloud);
	targetShotComputor->setInputNormals(targetPointCloudNormal);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr targetFpfhKdTree(new pcl::search::KdTree<pcl::PointXYZ>);
	targetShotComputor->setSearchMethod(targetFpfhKdTree);
	mfpSHOT.setFeatureEstimator(targetShotComputor);
	mfpSHOT.setDistanceMetric(pcl::CS);

	pcl::PointCloud<pcl::SHOT352>::Ptr output_features(new pcl::PointCloud<pcl::SHOT352>());
	pcl::IndicesPtr output_indices(new std::vector<int>);
	mfpSHOT.determinePersistentFeatures(*output_features, output_indices);

	std::cout << "persistent features cloud size:" << output_features->points.size();

	pcl::ExtractIndices<pcl::PointXYZ> extract_indices_filter;
	extract_indices_filter.setInputCloud(targetPointCloud);
	extract_indices_filter.setIndices(output_indices);
	pcl::PointCloud<pcl::PointXYZ>::Ptr persistent_features_locations(new pcl::PointCloud<pcl::PointXYZ>());
	extract_indices_filter.filter(*persistent_features_locations);

	//boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
	//viewer->setBackgroundColor(0, 0, 0);

	//pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> color_target(persistent_features_locations, 255, 0, 0);
	//viewer->addPointCloud<pcl::PointXYZ>(persistent_features_locations, color_target, "target");
	//viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "target");

	//viewer->spin();

	//system("pause");

	return 0;

}
```
**2.pcl::MultiscaleFeaturePersistence + pcl::PFHSignature125**
```
#include <iostream>
 #include <pcl/io/pcd_io.h>
 #include <pcl/point_types.h>
 #include <pcl/point_cloud.h>
 #include <pcl/common/io.h>
 #include <pcl/filters/extract_indices.h>
 #include <pcl/features/normal_3d_omp.h>
 #include <pcl/features/pfh.h>
 #include <pcl/features/multiscale_feature_persistence.h>
 #include <boost/thread/thread.hpp>
 //#include <pcl/visualization/pcl_visualizer.h>
 //#include <pcl/visualization/cloud_viewer.h>
 int
 main() {
	/********************* ReadPointCloud *********************/
	pcl::PointCloud<pcl::PointXYZ>::Ptr targetPointCloud(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::io::loadPCDFile<pcl::PointXYZ>("D:/Users/.../skin_P_Clipped_U.pcd", *targetPointCloud);
	std::cout << "The size of targetPointCloud" << targetPointCloud->points.size() << std::endl;

	/********************* SurfaceNormal *********************/
	pcl::NormalEstimationOMP<pcl::PointXYZ, pcl::Normal> targetNormalEstimator;
	targetNormalEstimator.setInputCloud(targetPointCloud);
	targetNormalEstimator.setNumberOfThreads(6);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr targetNormalKdTree(new pcl::search::KdTree<pcl::PointXYZ>);
	targetNormalEstimator.setRadiusSearch(1.0);			
	pcl::PointCloud<pcl::Normal>::Ptr targetPointCloudNormal(new pcl::PointCloud< pcl::Normal>);
	targetNormalEstimator.compute(*targetPointCloudNormal);

	/********************* MultiscaleFeaturePersistence *********************/
	pcl::MultiscaleFeaturePersistence<pcl::PointXYZ, pcl::PFHSignature125> mfpFPFH;
	std::vector<float> scaleValues{ 2.0, 2.2, 2.4, 2.6, 2.8, 3.0 };
	mfpFPFH.setScalesVector(scaleValues);
	mfpFPFH.setAlpha(1.0);

	pcl::PFHEstimation<pcl::PointXYZ, pcl::Normal, pcl::PFHSignature125>::Ptr targetFpfhComputor(new pcl::PFHEstimation<pcl::PointXYZ, pcl::Normal, pcl::PFHSignature125>());
	targetFpfhComputor->setInputCloud(targetPointCloud);
	targetFpfhComputor->setInputNormals(targetPointCloudNormal);
	pcl::search::KdTree<pcl::PointXYZ>::Ptr targetFpfhKdTree(new pcl::search::KdTree<pcl::PointXYZ>);
	targetFpfhComputor->setSearchMethod(targetFpfhKdTree);
	mfpFPFH.setFeatureEstimator(targetFpfhComputor);
	mfpFPFH.setDistanceMetric(pcl::CS);

	pcl::PointCloud<pcl::PFHSignature125>::Ptr output_features(new pcl::PointCloud<pcl::PFHSignature125>());
	pcl::IndicesPtr output_indices(new std::vector<int>);
	mfpFPFH.determinePersistentFeatures(*output_features, output_indices);

	std::cout << "persistent features cloud size:" << output_features->points.size();

	pcl::ExtractIndices<pcl::PointXYZ> extract_indices_filter;
	extract_indices_filter.setInputCloud(targetPointCloud);
	extract_indices_filter.setIndices(output_indices);
	pcl::PointCloud<pcl::PointXYZ>::Ptr persistent_features_locations(new pcl::PointCloud<pcl::PointXYZ>());
	extract_indices_filter.filter(*persistent_features_locations);

	//boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
	//viewer->setBackgroundColor(0, 0, 0);

	//pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZ> color_target(persistent_features_locations, 255, 0, 0);
	//viewer->addPointCloud<pcl::PointXYZ>(persistent_features_locations, color_target, "target");
	//viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 2, "target");

	//viewer->spin();

	//system("pause");

	return 0;
}
```
Point cloud files: [https://bald-minute-830.notion.site/Storage-78e53cbe4b674cc882fd5881b6e23bb1]
If you replace pcl::PFHSignature125 with pcl::FPFHSignature33, the program can be compiled and run normally

**My Environment (please complete the following information):**
 - OS: Windows 10
 - Compiler: Visual Studio 2019 Release X64
 - PCL Version: pcl:x64-windows 1.13.0 (I still have PCL 1.12.1 installed through all-in-one on my computer, but I have configured them separately in different VS projects. Of course, the same problem occurs in the environment of all-in-one configuration)
 - PCL Type: Installed with VCPKG

**Additional context**
When using pcl::MultiscaleFeaturePersistence for pcl::PFHSignature125 and pcl::SHOT352 feature descriptors to obtain multi-scale persistent point clouds, a compilation error occurs, but it can run normally when used for pcl::FPFHSignature33 feature descriptors (strange The most important thing is that the function calls of pcl::PFH and pcl::FPFH are almost exactly the same, but PFH reports an error when compiling, and the same is true for pcl::SHOT). At first I thought there was a problem with my pcl environment configuration (environment configuration completed through all-in-one), so I reconfigured the environment through vcpkg, but the same compilation problem still occurred.
In the introduction of pcl::MultiscaleFeaturePersistence it is mentioned that it can be used for any feature estimator instance, why I failed? Hope someone can give me some advice, thank you very much.

**Comment by mvieth** [comment]
If you put `#define PCL_NO_PRECOMPILE 1` before `#include <pcl/features/multiscale_feature_persistence.h>`, it should work. But be aware, that VS seems to use the all-in-one installation even if you configured it to use the VCPKG installation (your error indicates this). I strongly recommend to only keep one PCL installation on your computer (either all-in-one or VCPKG), and remove the other. If you keep both, it is likely that you will run into problems, especially (but not only) since they are different PCL versions.

**Comment by JackCao-Git** [comment]
> If you put `#define PCL_NO_PRECOMPILE 1` before `#include <pcl/features/multiscale_feature_persistence.h>`, it should work. But be aware, that VS seems to use the all-in-one installation even if you configured it to use the VCPKG installation (your error indicates this). I strongly recommend to only keep one PCL installation on your computer (either all-in-one or VCPKG), and remove the other. If you keep both, it is likely that you will run into problems, especially (but not only) since they are different PCL versions.

Your suggestion is very effective, the problem has been solved smoothly, thank you very much.
