### ISSUE TITLE
Mention host / target triplets in VCPKG tutorial

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#5631]
Is this something we should put into the install-PCL-via-VCPKG tutorial?

_Originally posted by @mvieth in https://github.com/PointCloudLibrary/pcl/pull/5614#pullrequestreview-1310208954_

**Comment by rkscodes** [comment]
I would like to work on this, can you help me get started ?

**Comment by mvieth** [comment]
@rkscodes what do you want to know?

**Comment by rkscodes** [comment]
I can't find the tutorial for VCPKG in this repo, so how do I update it

**Comment by mvieth** [comment]
@rkscodes You can find the tutorial under doc/tutorials/content/pcl_vcpkg_windows.rst

**Comment by rkscodes** [comment]
Alright, got it. 
So  as far as I understand, while building qt in release mode it builds two times. This is due to qt assume default host triplet as x64-windows and if this is different from our default or mentioned triplet, it would build for both types. And to resolve it we should provide `--host-triplet <triplet_type>` same as `--triplet`. 

If you could confirm it, I would think ahead on how to include this info in docs. Please suggest changes or way on how to do it.

**Comment by larshg** [comment]
> Alright, got it. So as far as I understand, while building qt in release mode it builds two times. This is due to qt assume default host triplet as x64-windows and if this is different from our default or mentioned triplet, it would build for both types. And to resolve it we should provide `--host-triplet <triplet_type>` same as `--triplet`.
> 
> If you could confirm it, I would think ahead on how to include this info in docs. Please suggest changes or way on how to do it.

yeah, that sounds right. It probably though, also concerns other tools, which need to run on the host, but used to generate things for the target.
So all kind of executable tools.

**Comment by rkscodes** [comment]
I am thinking to modify this docs as follows, suggest me changes if required 
...
Install PCL for usage
=====================

Running the following command in powershell in the VCPKG directory,
will install PCL with default options as well as default triplet type (ie. x86).

  ./vcpkg install pcl
 
// Include new info at this place in docs  

.. note::
  This will build executables 2 times in release mode, as default host triplet is x64-windows
  in various executables, but we use x86 by default. So to fix it you can provide default
  host-triplet same as default triplet.

  ./vckpgk install pcl --host-triplet -x86 

  Or, you can use same custom triplet for both --triplet and --host-triplet

  ./vckpgk install pcl --triplet <same_custom_triplet_type> --host-triplet <same_custom_triplet_type>
  
  ...
