### ISSUE TITLE
SACSegmentationFromNormals returning worst fit when setting setOptimizeCoefficients to true

### ISSUE THREAD

**Issue by DuffRumkins** [PointCloudLibrary/pcl#5633]
I have been working on a script which uses `pcl::SACSegmentationFromNormals `to fit a cylinder model to segments in a point cloud. 

For this I had had the `setOptimizeCoefficients` to `true` since, as I understood it, this would result in better model coefficients for the resulting fit. I noticed some issues when trying to fit a roughly cylindrical section of a point cloud representing a branch. The axis of the cylinder looked correct, but the radius was negative. I had no idea how this was possible as other segments were being fit correctly.

After some messing about, I found that changing `setOptimizeCoefficients` to `false` fixed this issue and the branch was able to be fit quite well.

Am I misunderstanding how this optimisation works or is this an issue with implementation? Surely a negative radius should never be possible?

Thanks for your help!

**Comment by mvieth** [comment]
Hi! The optimization is done via an unconstrained Levenberg-Marquardt approach. During the optimization, the radius is used squared (like `radius*radius`), so a positive radius and a negative radius with the same absolute value would lead to the same result. See here: https://github.com/PointCloudLibrary/pcl/blob/master/sample_consensus/include/pcl/sample_consensus/sac_model_cylinder.h#L300

Things you could check:
- the inliers returned by `segment`, are they better or worse when you optimize vs don't optimize?
- if you use the absolute value of the radius returned by `segment`, does everything make sense then?

In general I would agree that the radius should not be negative. I will further look into the implementation when I find time.
If you are willing to share your point cloud and code (snippets), I might be able to tell you more about your specific case.

**Comment by mvieth** [comment]
Exit code 2 would translate to `RelativeErrorTooSmall` (see LevenbergMarquardt.h in the Eigen project), so the algorithm seems to have converged. The residual norm is also quite small.
You could try again with a smaller distance threshold, maybe 0.005? That's all I can say for now, I will come back when I have more time.

**Comment by DuffRumkins** [comment]
Decreasing the distance threshold to 0.005 does result in the optimised radius no longer being negative, but does not fix the issue.

The radius is still much too small, now even smaller at 0.00371741.

This is also way below the lower radius limit value so maybe this is not getting passed through correctly?

**Comment by DuffRumkins** [comment]
Thanks for taking the time to investigate this issue!

I think for now I will just keep `optimizeModelCoefficients` to false as this has been working well for me. 

Thanks again!
