### ISSUE TITLE
[custom] OctreePointCloudSearch::voxelSearch showing unexpected results

### ISSUE THREAD

**Issue by Destranix** [PointCloudLibrary/pcl#5637]
Following piece of code:

```
std::for_each(std::execution::seq, octree.leaf_depth_begin(), octree.leaf_depth_end(), [this, &octree](pcl::octree::OctreeNode* node){
    auto container_points = static_cast<const pcl::octree::OctreeLeafNode<pcl::octree::OctreeContainerPointIndices>*>(node)->getContainer();
		
    const size_t index = container_points.getPointIndex();

    pcl::Indices points;
    if(!octree.voxelSearch(octree.getInputCloud()->at(index), points)){
	RCLCPP_ERROR(this->get_logger(), "ERROR");
    }
});
```
returns me "ERROR" though it should not do that, cause the voxel for the point definitly exists in the octree.
Or am I getting that wrong?

PCL version is 101300. I'm testing at WSL1 on Windows 10 with Ubuntu 20.04.

**Comment by NishaMeyerGVh** [comment]
It's difficult to say for sure without more information, but there could be a few possible reasons why you are getting an error message despite the voxel for the point existing in the octree:

There may be an issue with the voxelSearch() function itself. Double-check that it is working correctly and that it is able to find the voxel for the given point.

There may be an issue with the input cloud or the octree. Check that both are correctly initialized and that the input cloud has the correct number of points and is properly aligned with the octree.

There may be an issue with the data type used to represent the points. Make sure that the data type used for the input cloud and the octree is consistent and matches the data type used by the voxelSearch() function.

You could try adding some additional error checking and logging to help narrow down the cause of the issue. For example, you could check the return value of voxelSearch() and log additional information about the point and voxel that are causing the error.

**Comment by Destranix** [comment]
Is this an AI generated message?

**Comment by mvieth** [comment]
Hmm, kinda looks like it. And it is quite comprehensible, although the advice is a bit generic.
@NishaMeyerGVh Here is your chance to proof that you are human: display the point cloud from https://pcl.readthedocs.io/projects/tutorials/en/master/pcd_file_format.html#example in a visualizer and tell us what it says :smile: 

@Destranix Regarding your problem: does it print "ERROR" every time or just for some calls to `voxelSearch`? What is `index` in the error case? Please also post a complete code example with which I can easily reproduce the error (that includes the creation of the octree, for example with a small toy cloud)

**Comment by Destranix** [comment]
Only for some calls.
I also checked that the Container has a size bigger than zero (cause otherwise the behavious would be undefined.)

Later I can try to create a stand-alone example.

**Comment by Destranix** [comment]
Okay, here a full example:

```
#include <algorithm>
#include <execution>

#include <pcl/pcl_base.h>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/octree/octree_search.h>


int main(int argc, char* argv[]) {
	(void) argc;
	(void) argv;
	
	pcl::PointCloud<pcl::PointXYZRGBL>::Ptr cloud = std::make_shared<pcl::PointCloud<pcl::PointXYZRGBL>>();
	
	for(size_t i = 0; i < 100; ++i){
		cloud->emplace(cloud->end(), pcl::PointXYZRGBL((i / 2), (i / 2) + 1, 0.0f));
	}
	
	pcl::octree::OctreePointCloudSearch<pcl::PointXYZRGBL> octree(0.15);
	octree.setInputCloud(cloud);
	octree.addPointsFromInputCloud();
	
	std::cerr << "Leaf count: " << octree.getLeafCount() << std::endl;
	
	std::for_each(std::execution::seq, octree.leaf_depth_begin(), octree.leaf_depth_end(), [&octree](pcl::octree::OctreeNode* node){
		auto container_points = static_cast<const pcl::octree::OctreeLeafNode<pcl::octree::OctreeContainerPointIndices>*>(node)->getContainer();
			
		const size_t index = container_points.getPointIndex();

		pcl::Indices points;
		if(!octree.voxelSearch(octree.getInputCloud()->at(index), points)){
			std::cerr << "Index:" << index << std::endl;
		}
	});
	return 0;
}
```

Gives me following output:
```
Leaf count: 50
Index:3
Index:21
Index:23
Index:25
Index:27
Index:29
Index:31
Index:33
Index:35
Index:37
Index:39
```

**Comment by mvieth** [comment]
So you are using the octree on a 2D cloud (z-coordinate always 0)? This might be problematic, I will try to check this when I have more time.

**Comment by Destranix** [comment]
"So you are using the octree on a 2D cloud (z-coordinate always 0)?"

In the example for simplicity. In my original setting they should have a z-coordinate, but the z-coordinate not varying much in range.

**Comment by mvieth** [comment]
@Destranix I finally found some time to test this, and I may have found a solution. Can you try replacing
`!bUpperBoundViolationX` by `bLowerBoundViolationX`
`!bUpperBoundViolationY` by `bLowerBoundViolationY`
`!bUpperBoundViolationZ` by `bLowerBoundViolationZ`
beginning here: https://github.com/PointCloudLibrary/pcl/blob/master/octree/include/pcl/octree/impl/octree_pointcloud.hpp#L526 (replace each one twice).
This solves the problem in the code example you gave, now the question would be if it also solves the problem in your original setting.

**Comment by Destranix** [comment]
Yes, seems to work.
