### ISSUE TITLE
Failed to find match for field 'x'. Failed to find match for field 'y'. Failed to find match for field 'z'.

### ISSUE THREAD

**Issue by Alissaxin** [PointCloudLibrary/pcl#5639]
I have a ply point cloud file with x, y, z coordinates of double type, and when reading this .ply file with the PCL, it will report this error: 

Failed to find match for field 'x'. Failed to find match for field 'y'. Failed to find match for field 'z'.

This error causes all my next code to apply x, y, z coordinates to fail, what should I do?

**Comment by mvieth** [comment]
@Alissaxin Please post the code you use to load the ply file, and the ply file itself (zipped, for example). Where did you get the ply file from?

**Comment by Alissaxin** [comment]
Thank you very much for your attention， The code I load the ply file code is：

    //Load input PLY file
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PLYReader reader;
    reader.read("/home/zhangyx/cloud/data/off-ground points.ply", *cloud);
    std::cout << "PointCloud has: " << cloud->points.size () << " data points." << std::endl;

and the warning result is：
![image](https://user-images.githubusercontent.com/119839443/227418612-5b56a318-c362-4ca5-85cf-fdced388e92e.png)

Although these warning codes are yellow, they affect my next operations about x,y,z.

I looked up a lot and said that my x,y,z coordinates are of double type, but the x,y,z coordinates of PCL loading ply files are float types, but I don't know how to change the x,y,z data types, because this file is too big (about 10G). In addition, this ply file cannot be uploaded due to privacy concerns, but I am sure that the x,y,z coordinates of this file can be displayed normally, and here is a screenshot of the data format when importing the file in Cloud Compar

![image](https://user-images.githubusercontent.com/119839443/227419757-95e0ab1d-406b-4833-8b93-77f3670ee92c.png)

So, what shall I do?

**Comment by dzenanz** [comment]
I am running into this problem too. If a file is opened and saved using MeshLab, it creates float fields. The saved file gets read normally by `pcl`. But reader getting completely foiled by higher precision fields is a really surprising behavior.
