### ISSUE TITLE
Fix extra semicolon warnings

### ISSUE THREAD

**Issue by Destranix** [PointCloudLibrary/pcl#5640]
Following error message:
```

/usr/local/include/pcl-1.13/pcl/filters/voxel_grid.h:193:36: error: extra ‘;’ [-Werror=pedantic]
  193 |       PCL_MAKE_ALIGNED_OPERATOR_NEW;
```

Problem is the extra semicolon here:
https://github.com/PointCloudLibrary/pcl/blob/30124ee1ab5518a5cc7d03a186c46caf9aa99513/filters/include/pcl/filters/voxel_grid.h#L193

Solution is to remove that semicolon, as also seen here:
https://github.com/PointCloudLibrary/pcl/blob/30124ee1ab5518a5cc7d03a186c46caf9aa99513/filters/include/pcl/filters/crop_box.h#L62

**Comment by mvieth** [comment]
@Destranix You are right, the semicolon is not needed. I found more instances of extra semicolons:
```
filters/include/pcl/filters/plane_clipper3D.h:      PCL_MAKE_ALIGNED_OPERATOR_NEW;
filters/include/pcl/filters/voxel_grid_occlusion_estimation.h:      PCL_MAKE_ALIGNED_OPERATOR_NEW;
filters/include/pcl/filters/uniform_sampling.h:      PCL_MAKE_ALIGNED_OPERATOR_NEW;
filters/include/pcl/filters/voxel_grid.h:      PCL_MAKE_ALIGNED_OPERATOR_NEW;
gpu/kinfu_large_scale/include/pcl/gpu/kinfu_large_scale/point_intensity.h:  PCL_MAKE_ALIGNED_OPERATOR_NEW;
registration/include/pcl/registration/gicp.h:  PCL_MAKE_ALIGNED_OPERATOR_NEW;
registration/include/pcl/registration/incremental_registration.h:  PCL_MAKE_ALIGNED_OPERATOR_NEW;
registration/include/pcl/registration/vertex_estimates.h:  PCL_MAKE_ALIGNED_OPERATOR_NEW;
test/common/test_transforms.cpp:  PCL_MAKE_ALIGNED_OPERATOR_NEW;
```
Would you be interested in opening a pull request to remove these?

**Comment by Destranix** [comment]
Seems like the same issue occures for other structs too:
PCL_ADD_RGB;
pcl-1.13/pcl/impl/point_types.hpp:368:5

**Comment by mvieth** [comment]
@Destranix Ah yes, you are right. If you like, feel free to open a pull request.

**Comment by Destranix** [comment]
I don't think that I have time currently. You can reopen the issue, so that it is in pending state again?

**Comment by Zekrom-7780** [comment]
@mvieth I'll pick up this issue
