### ISSUE TITLE
[compile error] "the error of the point_types.h"

### ISSUE THREAD

**Issue by ZkzMMDC** [PointCloudLibrary/pcl#5643]
When I include the point_types.h`#include <pcl/point_types.h>` and I do not do any programming. The console will report  errors E0077 and E0135.  
![1679997009151](https://user-images.githubusercontent.com/129166628/228198713-215878b5-ddf5-4f00-a07f-6c5574068ed6.png)

**Comment by mvieth** [comment]
@ZkzMMDC  Which PCL version do you use and how did you install it? Also, please post the error messages in English. I have no clue what they mean and I can't find any explanation of E0077 or E0135 on the internet.

**Comment by ZkzMMDC** [comment]
I use the PCL 12.0 and 13.0 with Visual studio 2022 on the win11. I installed them by the Allinone.exe.  pcl::Pointxyz is not even recognized. And when i include the point_type.h. The error messages will be like follow:
![1680005573737](https://user-images.githubusercontent.com/129166628/228232433-e06aa845-1c4a-4901-8264-dcf5f339f8c2.png)
![1680005588719](https://user-images.githubusercontent.com/129166628/228232441-4339986a-72be-4e59-b302-4ed3a95399e5.png)

**Comment by ZkzMMDC** [comment]
![1680005637177](https://user-images.githubusercontent.com/129166628/228232637-e7ad41dc-156b-4f24-bcb6-4d4ab7621a50.png)
maybe something wrong with the pcl_common?

**Comment by ZkzMMDC** [comment]
However I can find the pcl::PointXYZ in the point_type.h in the external dependencies

**Comment by ZkzMMDC** [comment]
In addition to this .h, there are many .h files that will report errors, and the types of errors are strange

**Comment by mvieth** [comment]
Assuming that fixed the problem ...
