### ISSUE TITLE
[pcl::on_nurbs::Triangulation::convertSurface2PolygonMesh] double free or corrupt

### ISSUE THREAD

**Issue by Simonespinosa** [PointCloudLibrary/pcl#5644]
**Describe the bug**

I am currently trying to run the bspline_fitting example and when it attempts to do the triangulation it runs into a "double free or corrupt" error. When debugging it is related to the shared_ptr_base.h

**Context**

I had previously done the same on a Ubuntu 20.4 and no error was identified

**Expected behavior**

It should run smoothly

**Current Behavior**

It breaks at that point due to the shared_ptr_base

**To Reproduce**

Nothing needed to reproduce as it is directly on the repository, it is an error due to Ubuntu version

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 22.04]
 - Compiler: [GCC 11.3.0]
 - PCL Version [Latest, HEAD]

Thank you very much in advance

**Comment by larshg** [comment]
I quickly tested this. It does do a double free or corrupt error, when run as a separate exectuable, that links to PCL. But if I add the code to a file within the PCL CMake project, it runs fine. So I think its some flags that are not propagated correctly.
I just haven't figured which ones yet.

**Comment by larshg** [comment]
It seems to be solveable with adding this:

```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

As GCC 11.3 defaults to c++17, there seems to be some issues with releasing memory. With above command its forced to c++14.
