### ISSUE TITLE
[compile error] "Please add a short description here"

### ISSUE THREAD

**Issue by LanTu1314** [PointCloudLibrary/pcl#5645]
为什么编译cuda的时候cuda下的filter不编译

**Comment by cybaol** [comment]
> 为什么编译cuda的时候cuda下的filter不编译

I suspect that the `cuda_filter` module has not yet been fully implemented.

**Comment by mvieth** [comment]
@LanTu1314 We don't offer support in Chinese. Please post your questions in English.
And @cybaol is correct: the only cuda filter that might be usable is the passthrough filter, and that is still quite experimental.
