### ISSUE TITLE
linker error while compiling with Point Cloud Library 1.13.0

### ISSUE THREAD

**Issue by Resacd** [PointCloudLibrary/pcl#5652]
I installed the PCL library version 1.13.0 using vcpkg. I also integrated vcpkg with visual studio. The library is linked to visual studio project and I confirm that by adding /showIncludes in c/c++ command line and /VERBOSE in linker command line. I can see that the code is finding the required headers and libs file correctly. I also included the following .libs to the project.
```
pcl_commond.lib
pcl_featuresd.lib
pcl_filtersd.lib
pcl_iod.lib
pcl_io_plyd.lib
pcl_kdtreed.lib
pcl_keypointsd.lib
pcl_mld.lib
pcl_octreed.lib
pcl_recognitiond.lib
pcl_registrationd.lib
pcl_sample_consensusd.lib
pcl_searchd.lib
pcl_segmentationd.lib
pcl_stereod.lib
pcl_surfaced.lib
pcl_trackingd.lib
```

but still I'm getting unresolved error for MarchingCube. These errors indicate that the linker is unable to find the definitions for several member functions of the pcl::MarchingCubes and pcl::MarchingCubesHoppe classes. Can anyone help me to find out what's wrong here? here is the errors 

Error LNK2019	unresolved external symbol "public: virtual __cdecl pcl::MarchingCubes<struct pcl::PointXYZ>::~MarchingCubes<struct pcl::PointXYZ>(void)" (??1?$MarchingCubes@UPointXYZ@pcl@@@pcl@@UEAA@XZ) referenced in function "public: virtual void * __cdecl pcl::MarchingCubes<struct pcl::PointXYZ>::`scalar deleting destructor'(unsigned int)" (??_G?$MarchingCubes@UPointXYZ@pcl@@@pcl@@UEAAPEAXI@Z)	

Error LNK2001	unresolved external symbol "protected: virtual float __cdecl pcl::MarchingCubes<struct pcl::PointXYZ>::getGridValue(class Eigen::Matrix<int,3,1,0,3,1>)" (?getGridValue@?$MarchingCubes@UPointXYZ@pcl@@@pcl@@MEAAMV?$Matrix@H$02$00$0A@$02$00@Eigen)

**Comment by mvieth** [comment]
@Resacd `MarchingCubes` does not work with `PointXYZ`, see here: https://github.com/PointCloudLibrary/pcl/blob/master/surface/src/marching_cubes.cpp#L42

**Comment by Resacd** [comment]
@mvieth so how I can use MarchingCube to generate bloclmesh? But why the error type is linking error?

**Comment by mvieth** [comment]
You would have to use `pcl::PointNormal`, `pcl::PointXYZRGBNormal`, or `pcl::PointXYZINormal` (at least for the cloud you give to marching cubes)

**Comment by Resacd** [comment]
@mvieth I think what you pointed out regarding the problem with having several copy of the same point in the cloud now is showing itself.
```
Little-endian
PCL version: 101300
Number of points in cloud: 3672
Number of normals: 3672
Vertex pair not in list 2       [6] (7 22 5)
Vertex pair not in list 2       [6] (40 5 19)
Vertex pair not in list 2       [6] (61 17 18)
Vertex pair not in list 2       [6] (59 25 29)
Vertex pair not in list 2       [6] (61 24 29)
Vertex pair not in list 2       [6] (3 53 12)
Vertex pair not in list 2       [6] (1 55 28)
Vertex pair not in list 2       [6] (4 56 28)
Vertex pair not in list 2       [6] (36 55 13)
Vertex pair not in list 2       [6] (62 39 19)
Vertex pair not in list 2       [6] (62 35 23)
Vertex pair not in list 2       [6] (62 35 23)
Vertex pair not in list 2       [6] (50 60 26)
Vertex pair not in list 2       [6] (23 3 35)
Vertex pair not in list 2       [6] (2 30 38)
Vertex pair not in list 2       [6] (8 21 59)
Vertex pair not in list 2       [6] (9 22 59)
Vertex pair not in list 2       [6] (1 31 60)
Vertex pair not in list 2       [6] (41 12 54)
Vertex pair not in list 2       [6] (43 22 60)
Vertex pair not in list 2       [6] (60 30 56)
Vertex pair not in list 2       [6] (7 39 59)
Vertex pair not in list 2       [5] (2 8 4)
Vertex pair not in list 2       [5] (1 8 8)
Vertex pair not in list 2       [5] (2 13 11)
Vertex pair not in list 2       [5] (2 8 14)
Vertex pair not in list 2       [5] (2 21 15)
Vertex pair not in list 2       [5] (25 29 8)
Vertex pair not in list 2       [5] (6 2 23)
Vertex pair not in list 2       [5] (1 15 22)
Vertex pair not in list 2       [5] (6 7 29)
Vertex pair not in list 2       [5] (3 10 27)
Vertex pair not in list 2       [5] (3 10 27)
Vertex pair not in list 2       [5] (18 12 30)
Vertex pair not in list 2       [5] (1 23 21)
Vertex pair not in list 2       [5] (0 16 24)
Vertex pair not in list 2       [5] (1 16 24)
Vertex pair not in list 2       [5] (1 18 28)
Vertex pair not in list 2       [5] (31 24 16)
Failed to find match for field 'normal_x'.
Failed to find match for field 'normal_y'.
Failed to find match for field 'normal_z'.
Failed to find match for field 'curvature'.
[pcl::io::saveVTKFile] Input point cloud has no data!
```
