### ISSUE TITLE
[cmake] Only require Flann for some pcl modules

### ISSUE THREAD

**Issue by Faroito** [PointCloudLibrary/pcl#5654]
Would it be possible to only require Flann dependency when compiling `pcl_search`, `pcl_segementation` or `pcl_kdtree`?

**Context**

I'm only building some modules of pcl and I don't want to provide Flann if pcl doesn't need it.

**Describe the solution you'd like**

I did this quick patch in root `CMakeLists.txt`
```cmake
if(BUILD_search OR BUILD_segmentation OR BUILD_kdtree)
  find_package(FLANN 1.9.1 REQUIRED)
  if(NOT (${FLANN_LIBRARY_TYPE} MATCHES ${PCL_FLANN_REQUIRED_TYPE}) AND NOT (${PCL_FLANN_REQUIRED_TYPE} MATCHES "DONTCARE"))
    message(FATAL_ERROR "Flann was selected with ${PCL_FLANN_REQUIRED_TYPE} but found as ${FLANN_LIBRARY_TYPE}")
  endif()
endif()
```

**Comment by mvieth** [comment]
@Faroito I am not sure if your patch is the best solution, but generally, this seems possible. I am just wondering which PCL modules you are building, because it seems to me that most if not all modules depend on pcl_search (and thus also on flann)?

**Comment by Faroito** [comment]
For my use case I’m only building common, geometry, io and octree. But maybe that is an edge case.
