### ISSUE TITLE
Execute: extract.filter(*Trcloud); ,an exception has occurred

### ISSUE THREAD

**Issue by yywd6** [PointCloudLibrary/pcl#5661]
Sorry to bother everyone, when I run a function to process the point cloud, I prepared to remove the index from the source point cloud, but every time I reported an exception at <memory.h>, if someone can help me solve this problem, thank you very much, the code and exception diagram are shown below：

> The first two pictures below are the code, the code two pictures are connected, and the third picture is the abnormal position

![ZROWB6Y0Y_OU}C04B4{4FI1](https://user-images.githubusercontent.com/101700971/231421111-8ab3b41d-852c-47fa-a3a3-5798e3bd6719.png)
![_G M%W(G GOQ4HMN 2C7L)G](https://user-images.githubusercontent.com/101700971/231421561-fc9af93d-2aba-473a-a194-98f2500864e4.png)

![G(1MT{}CI8UQI~ZDTDXUDTR](https://user-images.githubusercontent.com/101700971/231419775-345ae19b-e98b-48ea-b870-87566b412cb7.png)

**Comment by mvieth** [comment]
@yywd6 
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use?

**Comment by yywd6** [comment]
> @yywd6
> 
> * Which operating system do you use?
> * Which  do you use? How did you install it?
> * Which compiler do you use?

I'm sorry, I forgot to say it just now. 

> System: Windows 10;

> PCL version: PCL1.12.1；Download pcl，Then modify dependencies in vs, etc;

> Compiler：vs2019

**Comment by mvieth** [comment]
@yywd6 Try enabling AVX and AVX2 for your project

**Comment by yywd6** [comment]
> @yywd6 Try enabling AVX and AVX2 for your project

Thank you so much, with your help I have solved this problem, thank you very much and wish you all the best in your career and good health

**Comment by mvieth** [comment]
All the best for you, too
