### ISSUE TITLE
[custom] Connected AND Convex Clustering

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5662]
I would have liked to post this on Discord but I cannot because it is being blocked by my company firewall. I apologize for that. I would like to implement cloud library clustering imposing convexity to the cluster, not only connection. The conditional method of euclidean connection clustering allows, as far as I understood, only local condition enforcing (on couple of points) so it cannot be used for this purpouse. Of course I will try to implement it myself but I wonder if there is already something available with this scope, to avoid to reinvent the wheel. 
I know there is the [method ](pcl::ConvexHull< PointInT >) for instance but is there anything about using it for clustering/segmentation?
Any suggestions? thank you so much

(how to add labels to the issue?)

**Comment by mvieth** [comment]
I am not 100% sure what you mean with "imposing convexity", but maybe check all classes in the segmentation module if something fits (https://pointclouds.org/documentation/group__segmentation.html). The conditional euclidean clustering that you mentioned would also have been my first suggestion, but I am not sure what condition would be appropriate.

`ConvexHull` can not be used to do clustering/segmentation, it only computes the convex hull on a point cloud.

> (how to add labels to the issue?)

Only PCL maintainers can add labels, you can only choose the issue type (bug, compile error, request, ...) when opening the issue

**Comment by mynickmynick** [comment]
quite probably  
template<typename PointT>
class pcl::LCCPSegmentation< PointT >

or

template<typename PointT>
class pcl::CPCSegmentation< PointT >

thanks

**Comment by mynickmynick** [comment]
some other methods like 

SACSegmentation
SeededHueSegmentation

seems to provide no documentation or article reference

**Comment by mvieth** [comment]
SeededHueSegmentation is clustering based on distance and color (hue) I think.
SACSegmentation does have some documentation? (https://pointclouds.org/documentation/classpcl_1_1_s_a_c_segmentation.html , quite short admittedly)

**Comment by mynickmynick** [comment]
@mvieth @larshg 
could you please give a few tips/suggestions on pcl tools to estimate area of a pcl surface or volume of a pcl (defined in some way... for instance volume of the convex hull)

**Comment by mvieth** [comment]
@mynickmynick Due to time reasons, we maintainers in general don't offer advice/suggestions on what PCL classes/functions to use in a specific problem. Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for this. My ad-hoc guess would be that ConvexHull might offer something.
