### ISSUE TITLE
[request] Performance of pcl::KdTreeFLANN

### ISSUE THREAD

**Issue by jujimeizuo** [PointCloudLibrary/pcl#5663]
In the kdtree module, has the performance comparison between pcl::KdTreeFLANN and libnabo passed the benchmark test? Because the performance of libnabo is said to be good, I would like to ask.

**Comment by mvieth** [comment]
At the moment, PCL does not use or support libnabo, and there are currently no plans to change this. We have not done any performance comparison between FLANN and libnabo.

**Comment by larshg** [comment]
For reference, there is https://github.com/PointCloudLibrary/pcl/pull/5299, which looks into using nanoflann as an alternative as well or FLANN CUDA.

**Comment by jujimeizuo** [comment]
> For reference, there is #5299, which looks into using nanoflann as an alternative as well or FLANN CUDA.

Thank you, I mainly want to know who has the best performance among all kdtrees. And get the result through benchmark.

**Comment by yasamoka** [comment]
Check this out:

https://github.com/erikbern/ann-benchmarks
