### ISSUE TITLE
3D reconstruction

### ISSUE THREAD

**Issue by crdevvv** [PointCloudLibrary/pcl#5670]
I have a list of either RGB-D frames or  Single-View Pointclouds (captured by an external camera). I need a way to use this list of data to perform realtime 3d reconstruction of a scene. Has anyone done this before with pcl library?

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
