### ISSUE TITLE
[compile error] "Unable to install pcl[visualization] through vcpkg"

### ISSUE THREAD

**Issue by DanClappDelsys** [PointCloudLibrary/pcl#5676]
I am Trying to install pcl through vcpkg to use in my Visual Studio C++ project with MSBuild. I am able to install the base pcl through vcpkg, but I want to install the visualization library as well to run the cloud viewer example. I am getting errors trying to install it using vcpkg.

Computing installation plan...
The following packages will be rebuilt:
    pcl[core,visualization,vtk]:x64-windows-static -> 1.13.0#2
The following packages will be built and installed:
  * brotli[core]:x64-windows-static -> 1.0.9#5
  * cereal[core]:x64-windows-static -> 1.3.2#1
  * cgns[core,hdf5,lfs,lfsselector]:x64-windows-static -> 4.3.0#3
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows-static -> 8.0.1
  * double-conversion[core]:x64-windows-static -> 3.2.1#1
  * egl-registry[core]:x64-windows-static -> 2022-09-20
  * expat[core]:x64-windows-static -> 2.5.0#3
  * exprtk[core]:x64-windows-static -> 2022-01-01#2
  * fmt[core]:x64-windows-static -> 9.1.0#1
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows-static -> 2.12.1#3
  * gklib[core]:x64-windows-static -> 2022-07-27#2
  * glew[core]:x64-windows-static -> 2.2.0#1
  * hdf5[core,szip,tools,zlib]:x64-windows-static -> 1.14.0#1
  * jsoncpp[core]:x64-windows-static -> 1.9.5
  * libharu[core]:x64-windows-static -> 2.4.3
  * libiconv[core]:x64-windows-static -> 1.17#1
  * libjpeg-turbo[core]:x64-windows-static -> 2.1.5.1
  * libogg[core]:x64-windows-static -> 1.3.5#1
  * libtheora[core]:x64-windows-static -> 1.2.0alpha1-20170719#6
  * libxml2[core,iconv,lzma,zlib]:x64-windows-static -> 2.10.3#1
  * matio[core,hdf5,zlib]:x64-windows-static -> 1.5.23#2
  * metis[core]:x64-windows-static -> 2022-07-27
  * netcdf-c[core,dap,hdf5,nczarr,netcdf-4,platform-default-features]:x64-windows-static -> 4.8.1#3
  * nlohmann-json[core]:x64-windows-static -> 3.11.2
  * opengl[core]:x64-windows-static -> 2022-12-04#3
  * opengl-registry[core]:x64-windows-static -> 2022-09-29#1
  * pegtl[core]:x64-windows-static -> 3.2.6
  * pkgconf[core]:x64-windows -> 1.8.0#5
  * proj[core,net,tiff]:x64-windows-static -> 9.2.0
  * pugixml[core]:x64-windows-static -> 1.13.0
  * seacas[core]:x64-windows-static -> 2022-11-22#3
  * sqlite3[core,tool]:x64-windows -> 3.40.1#2
  * sqlite3[core]:x64-windows-static -> 3.40.1#2
  * szip[core]:x64-windows-static -> 2.1.1#11
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.5.0#2
  * utfcpp[core]:x64-windows-static -> 3.2.3
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
  * vcpkg-tool-meson[core]:x64-windows -> 0.63
  * verdict[core]:x64-windows-static -> 1.4.0
  * vtk[core,opengl]:x64-windows-static -> 9.2.0-pv5.11.0#6
Additional packages (*) will be modified to complete this operation.
Removing 1/42 pcl:x64-windows-static
Elapsed time to handle pcl:x64-windows-static: 1 s
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\dclapp\AppData\Local\vcpkg\archives in 1.04 ms. Use --debug to see more details.
Installing 2/42 brotli:x64-windows-static...
Building brotli[core]:x64-windows-static...
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz -> google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Extracting source C:/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/vcpkg/buildtrees/brotli/src/6c62fc2c71-3fc02d8e7f.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/lib/pkgconfig/libbrotlienc.pc
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/brotli_x64-windows-static/debug/lib/pkgconfig/libbrotlienc.pc
-- Installing: C:/vcpkg/packages/brotli_x64-windows-static/share/unofficial-brotli/unofficial-brotli-config.cmake
-- Installing: C:/vcpkg/packages/brotli_x64-windows-static/share/brotli/usage
-- Installing: C:/vcpkg/packages/brotli_x64-windows-static/share/brotli/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle brotli:x64-windows-static: 29 s
Installing 3/42 cereal:x64-windows-static...
Building cereal[core]:x64-windows-static...
-- Downloading https://github.com/USCiLab/cereal/archive/v1.3.2.tar.gz -> USCiLab-cereal-v1.3.2.tar.gz...
-- Extracting source C:/vcpkg/downloads/USCiLab-cereal-v1.3.2.tar.gz
-- Using source at C:/vcpkg/buildtrees/cereal/src/v1.3.2-6c68d7d381.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/vcpkg/packages/cereal_x64-windows-static/share/cereal/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle cereal:x64-windows-static: 5.3 s
Installing 4/42 szip:x64-windows-static...
Building szip[core]:x64-windows-static...
-- Downloading https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz -> szip-2.1.1.tar.gz...
-- Extracting source C:/vcpkg/downloads/szip-2.1.1.tar.gz
-- Applying patch fix-linkage-config.patch
-- Applying patch mingw-lib-names.patch
-- Using source at C:/vcpkg/buildtrees/szip/src/szip-2.1.1-15a12784d5.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/szip_x64-windows-static/lib/pkgconfig/szip.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/szip_x64-windows-static/debug/lib/pkgconfig/szip.pc
-- Installing: C:/vcpkg/packages/szip_x64-windows-static/share/szip/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle szip:x64-windows-static: 38 s
Installing 5/42 hdf5:x64-windows-static...
Building hdf5[core,szip,tools,zlib]:x64-windows-static...
-- Downloading https://github.com/HDFGroup/hdf5/archive/hdf5-1_14_0.tar.gz -> HDFGroup-hdf5-hdf5-1_14_0.tar.gz...
-- Extracting source C:/vcpkg/downloads/HDFGroup-hdf5-hdf5-1_14_0.tar.gz
-- Applying patch hdf5_config.patch
-- Applying patch szip.patch
-- Applying patch pkgconfig-requires.patch
-- Applying patch pkgconfig-link-order.patch
-- Using source at C:/vcpkg/buildtrees/hdf5/src/df5-1_14_0-18f435ca1a.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/hdf5/portfile.cmake:79 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j17
    Working Directory: C:/vcpkg/buildtrees/hdf5/x64-windows-static-rel
    See logs for more information:
      C:\vcpkg\buildtrees\hdf5\install-x64-windows-static-rel-out.log
      C:\vcpkg\buildtrees\hdf5\install-x64-windows-static-rel-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/hdf5/portfile.cmake:79 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building hdf5:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+hdf5
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[hdf5]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**To Reproduce**
.\vcpkg install --triplet x64-windows-static install pcl <-- This works fine
.\vcpkg --triplet x64-windows-static install pcl[visualization] --recurse <-- This causes the error log from above

 - OS: [Windows 10 64 bit]
 - Compiler: [MSBuild Visual Studio 17 2022]
 - PCL Version [1.13, HEAD]
 - PCL Type: [Installed with VCPKG]

**Comment by larshg** [comment]
```
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
Please ensure your system has sufficient memory.
```
Could seem you hit a memory limit when compiling.

Try [this](https://github.com/microsoft/vcpkg/issues/22689#issuecomment-1019290439)

**Comment by larshg** [comment]
Generally this seems like a vcpkg issue, so please open a issue there, if needed.
