### ISSUE TITLE
[apps] Point cloud editor selection broken

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5680]
**Describe the bug**

Selection feature in `pcl_point_cloud_editor` no longer works, the selection appears but the points no longer highlight, and cannot be deleted for instance.

**Context**

Use rectangle selection feature to select points.

**Expected behavior**

Points get selected and highlighted.

**Current Behavior**

Rectangle appears, but points do not get selected.

**To Reproduce**

- `cmake .. -DBUILD_apps=ON -DBUILD_apps_point_cloud_editor=ON`
- `./build/bin/pcl_point_cloud_editor <pcd>`
- hit `S`, select some points

**Your Environment (please complete the following information):**

 - OS: macos 12.5.1, Qt 5.15.8 via  `brew install qt@5`
 - Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
 - PCL Version HEAD

**Additional context**

I bisected the breakage to 38cbd621d0632895e1bed04841a612f97f574abc

![pcleditor](https://user-images.githubusercontent.com/11613312/233784007-f351c3b3-66be-43cb-a71e-391e70ddfed4.gif)

**Comment by mvieth** [comment]
@themightyoarfish Thanks for reporting and bisecting. I think I found a solution, can you please test https://github.com/PointCloudLibrary/pcl/pull/5685 ?
