### ISSUE TITLE
[qhull] ConvexHull prints a lot of unnecesary outputs on stdout, slowing down the elaboration: fixed with backward compatibility

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5681]
The class pcl::ConvexHull prints a lot of info on stdout (if compute area is set) which I think is undesirable and slows down the elaboration time.
I have written a patch that adds a private bit disable_stdout_ which is false by default (to keep backward compatibility) and can be set and get with two methods.
I have benchmarked in two cases, both show a 20% faster behaviour with the verbouse unnecessary stdout disabled

(1)
10 clusters convex hulled of totally 2205157 points
WITH OUTPUTS DISABLED: 125msec
WITH OUTPUTS: 155 msec

(2)
5 clusters convex hulled of totally 615690 points
WITH OUTPUTS DISABLED: 43msec
WITH OUTPUTS: 55 msec

Interesting would be investigating inside qhull lib if setting nullptr to the stdout is not sufficient to eliminate all xxprintf and similar overheads 

I could make a pull request from my fork after i finish to test and push the patch

**Comment by mynickmynick** [comment]
I have checked I think further optimization would be necessary also inside qhull lib cause many printf and similar seem to be still running though redirected to null (still getting unnecessary CPU time)

**Comment by mynickmynick** [comment]
the patch is in my fork, branch: disableQhull_stdout_byParameter

**Comment by mvieth** [comment]
@mynickmynick  I agree that it would be nice to have a way to disable qhull's output. I am surprised that it makes such a difference, speed-wise. But you are sure that the result is still the same?
Instead of adding a new option to `ConvexHull`, I would instead propose to link this with PCL's logging system by enabling qhull's output when PCL's logging level is `L_DEBUG`: `if(pcl::console::isVerbosityLevelEnabled(pcl::console::L_DEBUG))` (default is `L_INFO`).

**Comment by mynickmynick** [comment]
>Instead of adding a new option to ConvexHull, I would instead propose to link this with PCL's logging system by enabling qhull's output when PCL's logging level is L_DEBUG: if(pcl::console::isVerbosityLevelEnabled(pcl::console::L_DEBUG)) (default is L_INFO).

ok

>I am surprised that it makes such a difference, speed-wise. But you are sure that the result is still the same?

i think the results are the same but i will double check that.

**Comment by mynickmynick** [comment]
i had opened an issue also on qhull which I think I will soon close https://github.com/qhull/qhull/issues/129

**Comment by mynickmynick** [comment]
I checked the results are the same

**Comment by mvieth** [comment]
@mynickmynick Great! Then feel free to open a pull request if you like.
