### ISSUE TITLE
Cannot find PCL 1.8

### ISSUE THREAD

**Issue by gabrielbarsella** [PointCloudLibrary/pcl#5682]
Hello,
In order to compile and run a .cpp ML model on Windows, I need PCl version 1.8. 
I tried to install via vcpkg but this version is not available anymore.
Is this version still exist anywhere?

Thanks,
Gabriel

**Comment by larshg** [comment]
You can download source https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.0.
But you probably need to get older subdependencies as well.
It might be easier to just try getting the code you need to work with 1.13.

But please use SO or discord for these questions.
