### ISSUE TITLE
[IO] pcl::io::loadPCDFile fails to load point clouds correctly after QApplication is initialized

### ISSUE THREAD

**Issue by MaxFleur** [PointCloudLibrary/pcl#5694]
**Describe the bug**

If a point cloud is loaded using `pcl::io::loadPCDFile` before the initialization of a QApplication, the point cloud is loaded correctly. However, if the same is done after the initialization, the point cloud's values are loaded as integers, not floats.

**Context**

I am writing an application where two different viewers for point clouds are used. One of the point clouds is loaded directly at the start of the application, while the other one is updated later. However, the point cloud updated later is not displayed correctly because its values are not read correctly.

**Expected behavior**

The point cloud's values are read correctly as floating point values, even if a QApplication is initialized.

**Current Behavior**

The point cloud's values are read as integers after the initialization of the QApplication.

**To Reproduce**

I have included a minimal example with a main file, a CMakeLists.txt and an example pcd file as a tar.gz:
[example.tar.gz](https://github.com/PointCloudLibrary/pcl/files/11350961/example.tar.gz)

Extract it, then `cd` into the directory. Run: 
```
mkdir build
cd build
cmake ..
make -j8
./example_project ../data/writing.pcd ../data/writing.pcd
```
The point cloud's values are displayed in the console, so you should easily see that after the QApplication initialization, the read values are false.

**Screenshots/Code snippets**

If you do not want to use the tar.gz, here is the code snippet I am currently using:

main.cpp

```
#include <iostream>

#include <QApplication>
#include <QMainWindow>

#include <pcl/io/pcd_io.h>

void
showPointCloudData(pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud)
{
    for (int i = 0; i < cloud->points.size(); i++) {
        std::cout << cloud->points[i].x << " " << cloud->points[i].y << " " << cloud->points[i].z << std::endl;
    }
}


int
main(int argc, char *argv[])
{
    // Load the first cloud
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr firstCloud(new pcl::PointCloud<pcl::PointXYZRGB>());
    pcl::io::loadPCDFile(argv[1], *firstCloud);
    showPointCloudData(firstCloud);

    // Try the second one, here it works
    // pcl::PointCloud<pcl::PointXYZRGB>::Ptr secondCloud(new pcl::PointCloud<pcl::PointXYZRGB>());
    // pcl::io::loadPCDFile(argv[2], *secondCloud);
    // showPointCloudData(secondCloud);

    // Start the QT application
    QApplication a(argc, argv);

    // Here it does not
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr secondCloud(new pcl::PointCloud<pcl::PointXYZRGB>());
    pcl::io::loadPCDFile(argv[2], *secondCloud);
    showPointCloudData(secondCloud);

    // Initiate and show main window
    QMainWindow mainWindow;
    mainWindow.show();

    return a.exec();
}
```

CMakeLists.txt

```
cmake_minimum_required(VERSION 3.8)
project(example_project)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

find_package(PCL 1.12 REQUIRED)
find_package(Qt5 COMPONENTS Concurrent OpenGL Widgets REQUIRED)
find_package(VTK REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(example_project main.cpp)

target_link_libraries(example_project ${PCL_LIBRARIES} Qt5::Widgets)
```

Run the application with the following command: `./example_project path/to/first/cloud.pcd path/to/second/cloud.pcd`

**Environment:**

 - OS: Ubuntu 22.04 LTS
 - Compiler: Clang 15.0.7
 - PCL Version: 1.12.1, HEAD
 - Qt Version: 5.15.3

**Additional context**

To be honest, I am not sure if this problem is really related to PCL or if it is a Qt bug instead. Otherwise, I might have to file a bug report for Qt.

**Comment by mvieth** [comment]
@MaxFleur I can't reproduce the problem (Ubuntu 22.04, gcc 11.3.0, latest PCL master branch). With your program, the last few printed points are:
```c++
-0.15584 -0.25716 0
-0.0075775 -0.31546 0
-0.050817 -0.29595 0
-0.10306 -0.28653 0
-0.1319 -0.2831 0
-0.18716 -0.20571 0
-0.18369 -0.23729 0
```
Which seems correct? What output do you get?

**Comment by MaxFleur** [comment]
> @MaxFleur I can't reproduce the problem (Ubuntu 22.04, gcc 11.3.0, latest PCL master branch). With your program, the last few printed points are:
> 
> ```c++
> -0.15584 -0.25716 0
> -0.0075775 -0.31546 0
> -0.050817 -0.29595 0
> -0.10306 -0.28653 0
> -0.1319 -0.2831 0
> -0.18716 -0.20571 0
> -0.18369 -0.23729 0
> ```
> 
> Which seems correct? What output do you get?

That seems correct, yeah. For me it looks like this:
```
-0 -0 0
-0 -0 0
-0 -0 0
-0 -0 0
-0 -0 0
-0 -0 0
-0 -0 0
-0 -0 0
```

Maybe it has been fixed if you're using the latest PCL version? I might have to build it for myself and try it out then.

**Comment by mvieth** [comment]
> Maybe it has been fixed if you're using the latest PCL version? I might have to build it for myself and try it out then.

That would be a good idea. Although I can't remember any change since 1.12.1 that would explain this.

**Comment by MaxFleur** [comment]
Okay I did a few more tests. The problem still occurs under PCL 1.13, as you correctly assumed. 
What version of Qt are you using? In this case, the problem might be Qt related instead.

**Comment by MaxFleur** [comment]
Checked it with the latest master branch version... the error still happens.
The file is loaded correctly. The debug output also did not show any differences. I have attached a txt file with the content of both clouds. What this shows is quite interesting, though. For the second cloud, the very first coordinate (the x for the first point) seems to be loaded correctly. This one is as it should be. However, all following coordinates are cast down to integers.
No idea why this happens, though.

[output.txt](https://github.com/PointCloudLibrary/pcl/files/11353300/output.txt)

**Comment by mvieth** [comment]
Looking at your output, I have a new idea: the locale. I set my computer to use an English locale (decimal point), yours seems to use a German one (decimal comma), at least after `QApplication a(argc, argv);`. I will make further tests to see what is going on exactly.

**Comment by MaxFleur** [comment]
> Looking at your output, I have a new idea: the locale. I set my computer to use an English locale (decimal point), yours seems to use a German one (decimal comma), at least after `QApplication a(argc, argv);`. I will make further tests to see what is going on exactly.

Yup... that was the reason. Setting the locale to English solved the problem.
I would have NEVER thought that the problem is related to the locale, but thanks for the tip! I'll close the issue, problem is solved. Thanks! :-)
