### ISSUE TITLE
Receiving a read access violation when loading a .ply file in release mode

### ISSUE THREAD

**Issue by arielc-brillianetor** [PointCloudLibrary/pcl#5697]
Hi,
I'm receiving a read access violation when I try and load a .ply file. This exception happens only when I run the program in release mode, but works fine in debug mode.
Here is a snippet of the code:

```
// In order to use pcl::io::loadPCDFile
#define _CRT_SECURE_NO_WARNINGS

#include <iostream>
#include <chrono>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/io/ply_io.h>
#include <pcl/visualization/pcl_visualizer.h>

//--------------------------------------------------------------------------------
int main(int argc, char* argv[])
{
    const std::string SCANS_FOLDER = "C:\\Projects\\Scans\\";    
    const std::string FILENAME = "box";
    const std::string FILETYPE = ".ply";
    std::string sAddress = SCANS_FOLDER + FILENAME + FILETYPE;
    // Load data using pcl methods
    pcl::PointCloud<pcl::PointNormal> pclCloud;
    std::cout << "loading file: " << sAddress << std::endl;
    
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PLYReader Reader;
    Reader.read(sAddress, *cloud);
    
    std::cout << "done loading the point cloud\n";
    return EXIT_SUCCESS;
}

//--------------------------------------------------------------------------------
//--------------------------------------------------------------------------------
//--------------------------------------------------------------------------------

```

Thank you very much for your help!!

**Comment by mvieth** [comment]
@arielc-brillianetor Let's first check whether the .ply file is the problem. Please post the file you use (box.ply) and check whether you have the same problem with a different ply file, let's say this one: https://github.com/PointCloudLibrary/pcl/raw/master/test/cube.ply

Also:
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use?

**Comment by arielc-brillianetor** [comment]
So I figured it out. Feel a little silly but I hope this helps other people. The visual studio was reading the debug DLL's instead of the release ones. Now it works fine
