### ISSUE TITLE
Parser Error, calling loadPLYfile on binary ply file

### ISSUE THREAD

**Issue by DanClappDelsys** [PointCloudLibrary/pcl#5700]
**Describe the bug**

I am running the following lines of code:
```
pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
pcl::io::loadPLYFile<pcl::PointXYZ>("C:\\Users\\dclapp\\Desktop\\dan_projects\\point_cloud_data\\kinect_point_cloud0.ply", *cloud);
```

And I get this error:
```
[pcl::PLYReader] C:\Users\dclapp\Desktop\dan_projects\point_cloud_data\kinect_point_cloud0.ply:8: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
```

**Context**
The PLY file I am trying to load is in binary format. This is what the header and part of the data looks like:
```
ply
format binary_little_endian 1.0
comment 00:00:00.3460330
element vertex 737280
property short x
property short y
property short z
end_header
tüÜùiyüÞùi|üÚùo€üÙùq…üÙùs‰üØùuŒüÕùz‘üÕù|–üÖù|šüÕùüÑù…¡üÐù‡¥üÍùŒ©üÌù¬üÉù”±üÊù”µüÇù™¹üÇù›¼üÄù ÁüÄù¡ÅüÂù¥ÉüÀù©ÎüÀùªÑü½ù¯Öü¾ù¯Úü¼ù³ßü¼ù´áü¶ù¼æü·ù½êüµùÀïüµùÂòü±ùÇ÷ü°ùÊüü±ùÊÿü­ùÐý¬ùÓý©ù×ý©ùÙý§ùÜý¥ùàý¤ùãý ùéýžùì#ýšùò)ýžùï-ýšùô2ý›ùô7ý›ùö:ý˜ùû?ý–ùþBý“ùGý’ùKý‘ùQý’ùUýùYýŽù^ýùbý‹ùfý‡ùjý‡ùoý…ùrý‚ù$výù){ý}ù,~ýxù3ƒýwù5‡ýuù9Œýuù:ýsù=•ýsù>™ýpùCžýpùD£ýnùH§ýmùJ¬ýkùM
```

**Your Environment (please complete the following information):**

 - OS: [Windows 10]
 - Compiler: [Visual Studio 2022]
 - PCL Version [1.13.0]

**Possible Solution**

My only guess is that the "element vertex" number is larger than the actual number of points in the file, but I don't know if that will affect how the point cloud loads.

**Comment by mvieth** [comment]
> My only guess is that the "element vertex" number is larger than the actual number of points in the file

@DanClappDelsys if that is the case then yes, that could lead to problems. Can you upload the ply file (zipped)? Otherwise it will be very difficult for me to determine the exact problem.

**Comment by DanClappDelsys** [comment]
[kinect_point_cloud0.zip](https://github.com/PointCloudLibrary/pcl/files/11376250/kinect_point_cloud0.zip)

Here is the file. I don't know the exact number of points in the point cloud, but if I underestimate I get these new errors:

```
[pcl::PLYReader] C:\Users\dclapp\Desktop\dan_projects\point_cloud_data\kinect_point_cloud0.ply:8: ignoring extra data at the end of binary stream
Failed to find match for field 'x'.
Failed to find match for field 'y'.
Failed to find match for field 'z'.
```

**Comment by mvieth** [comment]
@DanClappDelsys the file is 2503513 bytes large, minus 145 bytes for the header, and each point has 3 shorts (3*2 bytes), so the file should contain (2503513−145)/6 = 417228 points
The `Failed to find match for field ...` is another problem: PCL does not have point types where x, y, and z are `short`, only `float` (in `PointXYZ` they are `float`), and PCL currently does not have the option to automatically convert the types when reading from files. Probably the easiest way for you is to create a new, custom point type where x, y, and z are `short`, then copy to a `pcl::PointCloud<pcl::PointXYZ>` in a for-loop.
