### ISSUE TITLE
Converting a point cloud in PCD format to OBJ format failed

### ISSUE THREAD

**Issue by yywd6** [PointCloudLibrary/pcl#5701]
**Describe the error**
There are many errors in code running and compiling

- The code and error are as follows
![}Z4531 9B~V51L`)N1MOKVK](https://user-images.githubusercontent.com/101700971/236621991-f404c0ea-61d9-4d74-abca-566cb07de5b1.png)

![5HK1NSK`X@2 W K~D2KTC7O](https://user-images.githubusercontent.com/101700971/236621720-14041bf7-edb9-49a4-b2af-7258fd9f9557.png)

**Your Environment (please complete the following information):**

System: Windows 10;

PCL version: PCL1.12.1；Download pcl，Then modify dependencies in vs, etc;

Compiler：vs2019

**Comment by mvieth** [comment]
@yywd6 I am not sure I understand the problem?

> The code ran with a lot of errors, but compiled without errors

Are you saying that there are errors when you _execute_ the code, but you can _compile_  the code without problems?
But the second image seems to show compilation errors?

**Comment by yywd6** [comment]
> @yywd6 I am not sure I understand the problem?
> 
> > The code ran with a lot of errors, but compiled without errors
> 
> Are you saying that there are errors when you _execute_ the code, but you can _compile_ the code without problems? But the second image seems to show compilation errors?


Sorry, I made a mistake and it has been revised

**Comment by mvieth** [comment]
@yywd6 Can you try changing `#include <pcl/io/io.h>` to `#include <pcl/common/io.h>` ?

**Comment by yywd6** [comment]
Thanks a lot, it's up and running now. But now there is another problem, that is, the file opening of the converted obj format is empty,
![MJ25O% P $7W17`5PF3_WE1](https://user-images.githubusercontent.com/101700971/236666516-79f65565-d033-4bbf-a133-0b86e7149e9e.png)


> @yywd6 Can you try changing `#include <pcl/io/io.h>` to `#include <pcl/common/io.h>` ?

**Comment by mvieth** [comment]
@yywd6 That is probably because the program you use to display the obj file does not understand the file correctly. PCD files only store points, but do not store information about faces/about the mesh. This means that the obj file will also only contain the points. You can try MeshLab instead to display the obj file, or open the obj file with a text editor to see that it is not empty.

**Comment by yywd6** [comment]
> @yywd6 That is probably because the program you use to display the obj file does not understand the file correctly. PCD files only store points, but do not store information about faces/about the mesh. This means that the obj file will also only contain the points. You can try MeshLab instead to display the obj file, or open the obj file with a text editor to see that it is not empty.

I really appreciate you taking time to explain everything to me!
