### ISSUE TITLE
error: no type named 'PCLVisualizer' in namespace 'pcl::visualization' and /home/developer/Qt-Work/PCLViewer/pclviewer.h:55: error: implicit instantiation of undefined template 'pcl::PointCloud<pcl::PointXYZRGBA>'

### ISSUE THREAD

**Issue by zoe9216** [PointCloudLibrary/pcl#5702]
Trying to follow the tutorial [Create a PCL visualizer in Qt with cmake](https://pcl.readthedocs.io/projects/tutorials/en/latest/qt_visualizer.html#id1). 
I have:
```
Ubuntu 22.04
Qt 5.15.3
QtCreator 6.0.2
Vtk 8.1 and 9.1
PCL 1.12
```

In `pclviewer.h` file I am getting errors on these two lines:
```
pcl::visualization::PCLVisualizer::Ptr viewer;
PointCloudT::Ptr cloud;
```
Qt could not find PCL files in `/usr/include` as I am not using .pro file, so I manually added them in the header file:
```
#include "/usr/include/pcl-1.12/pcl/point_cloud.h"
#include "/usr/include/pcl-1.12/pcl/point_types.h"
#include "/usr/include/pcl-1.12/pcl/visualization/pcl_visualizer.h"
```
But I get these errors:
```
error: no type named 'PCLVisualizer' in namespace 'pcl::visualization' 
/home/developer/Qt-Work/PCLViewer/pclviewer.h:55: error: implicit instantiation of undefined template 'pcl::PointCloud<pcl::PointXYZRGBA>'
```
Code is copied exactly from tutorial.

**Comment by mvieth** [comment]
@zoe9216 We strongly recommend to use either CMake or Qt Creator as described in the tutorial. We don't offer any help if you don't use CMake or Qt Creator. We especially discourage to specify the include files with an absolute path, because it is not portable and error prone.

**Comment by zoe9216** [comment]
> @zoe9216 We strongly recommend to use either CMake or Qt Creator as described in the tutorial. We don't offer any help if you don't use CMake or Qt Creator. We especially discourage to specify the include files with an absolute path, because it is not portable and error prone.

Thank you so much for responding. I was using `QtCreator version 6.0.2`. Its in the OP. And I am using `cmake` and `QtCreator` generates a `CMakeLists.txt` instead of a `.pro` file always. Anyways after your reply, I tried a trial-and-error on `CMakeLists.txt` and got it to work.
```
cmake_minimum_required(VERSION 3.5)

project(PCLViewer VERSION 0.1 LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(QT NAMES Qt6 Qt5 COMPONENTS Widgets REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Widgets REQUIRED)
find_package (PCL 1.2 REQUIRED)
set(PROJECT_SOURCES
        main.cpp
        pclviewer.cpp
        pclviewer.h
        pclviewer.ui
)

if(${QT_VERSION_MAJOR} GREATER_EQUAL 6)
    qt_add_executable(PCLViewer
        MANUAL_FINALIZATION
        ${PROJECT_SOURCES}
    )
# Define target properties for Android with Qt 6 as:
#    set_property(TARGET PCLViewer APPEND PROPERTY QT_ANDROID_PACKAGE_SOURCE_DIR
#                 ${CMAKE_CURRENT_SOURCE_DIR}/android)
# For more information, see https://doc.qt.io/qt-6/qt-add-executable.html#target-creation
else()
    if(ANDROID)
        add_library(PCLViewer SHARED
            ${PROJECT_SOURCES}
        )
# Define properties for Android with Qt 5 after find_package() calls as:
#    set(ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
    else()
        add_executable(PCLViewer
            ${PROJECT_SOURCES}
        )
    endif()
endif()

target_link_libraries(PCLViewer PRIVATE Qt${QT_VERSION_MAJOR}::Widgets ${PCL_LIBRARIES})

set_target_properties(PCLViewer PROPERTIES
    MACOSX_BUNDLE_GUI_IDENTIFIER my.example.com
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

if(QT_VERSION_MAJOR EQUAL 6)
    qt_finalize_executable(PCLViewer)
endif()

```
If you deem it correct maybe this CMakeLists.txt it can be included in the tutorial. Just a suggestion.

**Comment by mvieth** [comment]
@zoe9216 Do I understand it correctly that you do not use the CMakeLists.txt provided by the tutorial ([this one](https://github.com/PointCloudLibrary/pcl/blob/master/doc/tutorials/content/sources/qt_visualizer/CMakeLists.txt)), but instead you let QtCreator generate a _new_ CMakeLists.txt? That CMakeLists.txt will not have `find_package(PCL REQUIRED)` and will not link to the PCL libraries, which explains your problem. I just tested the tutorial again (with `cmake ../src && make -j2`) and it works perfectly. It seems to me that you are not configuring the project in the QtCreator like the tutorial says.
