### ISSUE TITLE
Makefile:151: recipe for target 'all' failed

### ISSUE THREAD

**Issue by Nick-Sun1018** [PointCloudLibrary/pcl#5703]
[ 66%] Building CXX object examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/example_get_keypoints_indices.cpp.o
In file included from /home/haoyang/pcl/keypoints/include/pcl/keypoints/harris_3d.h:182:0,
                 from /home/haoyang/pcl/examples/keypoints/example_get_keypoints_indices.cpp:40:
/home/haoyang/pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp: In member function ‘void pcl::HarrisKeypoint3D<PointInT, PointOutT, NormalT>::refineCorners(pcl::HarrisKeypoint3D<PointInT, PointOutT, NormalT>::PointCloudOut&) const [with PointInT = pcl::PointXYZRGB; PointOutT = pcl::PointXYZI; NormalT = pcl::Normal]’:
/home/haoyang/pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp:519:16: error: ‘*.LC0’ not specified in enclosing ‘parallel’
       PointInT corner;
                ^~~~~~
/home/haoyang/pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp:508:9: error: enclosing ‘parallel’
 #pragma omp parallel for \
         ^~~
examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/build.make:62: recipe for target 'examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/example_get_keypoints_indices.cpp.o' failed
make[2]: *** [examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/example_get_keypoints_indices.cpp.o] Error 1
CMakeFiles/Makefile2:2483: recipe for target 'examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/all' failed
make[1]: *** [examples/keypoints/CMakeFiles/pcl_example_get_keypoints_indices.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Did anybody meet this problem before,  how do I fix this, Thanks!

**Comment by mvieth** [comment]
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use?

**Comment by mvieth** [comment]
Closing because of no response
