### ISSUE TITLE
[sample consensus] Implement torus model

### ISSUE THREAD

**Issue by River-mao** [PointCloudLibrary/pcl#5706]
I saw most of the 3D models segmentation , expect the torus model, have been implemented. So, I want to know if it will be implemented soon? Thanks a lot!

**Comment by mvieth** [comment]
@River-mao To my knowledge, nobody is working on it currently. Out of interest: what do you want to use it for? Which torus-shaped object do you want to segment with it? I can't really think of a good practical use.

**Comment by River-mao** [comment]
Tnanks. I want to use this to segment the corner joints of pipes. I have use the cylinder model to fit the direct pipe, but the corner joint parts can't be fitted. This looks really like a torus, so I suppose if I can use a torus model to fit it.
