### ISSUE TITLE
[computeMeanAndCovarianceMatrix ]  can be made 8% faster eliminating the Eigen::Matrix<Scalar, 3, 1> K

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5709]
if you eliminate in computeMeanAndCovarianceMatrix the not necessary Eigen::Matrix<Scalar, 3, 1> K  the method gets about 8% faster
But I have seen it was introduced 2 years ago probably to get more accurate results in which case? probably when Deltaxyz/xyz is small (small cloud far from the origin)?
Cannot we make both functions available (something like "center mode" or "temporary shift mode")? because normally I don't think this trick is needed, it slows down the computation and in general I am not sure it improves accuracy. For instance if the first finite point is a spark much more distant than the average point it makes the opposite effect (lower accuracy).
One could introduce the K as an optional (0 at default) input, and the user is free to set it to a first approximate position
or give the option to use it or not (also defaulted) as it is now (by setting K to the first finite point)

**Comment by mvieth** [comment]
https://github.com/PointCloudLibrary/pcl/issues/4965 should answer your questions

**Comment by mynickmynick** [comment]
all right thanks I was not aware of a so detailed and long discussion and study on this matter. I will have a look at it later when I have more time. That confirms my suspects about the issue being originally with clouds with Delta(x,y,z) << (x,y,z) (dimensions much smaller than the  distance from the origin). It also calls for an optional full double support as in my experience doubles increase a lot the precision and have a relatively small impact on speed if you do not mix double with floats (in any case it would be an option, the user can choose the best trade off according to his/her needs). In my experience the use of double makes a relevant difference when there is a huge amount of additions and multiplications of numbers potentially very different in magnitude 
Like it is organized now (using a temporary pseudo-centroid K) computeMeanAndCovarianceMatrix is more precise on clouds of that sort but it's slower and can be predicted to be less precise on clouds that have outliers, sparkles that happen more often at the borders so are likely to be catched by that inital cycle looking for the first finite point.
Wouldn't it be better a method like the following?

  template <typename PointT, typename Scalar> inline unsigned int
  computeMeanAndCovarianceMatrix (const pcl::PointCloud<PointT> &cloud,
                                  Eigen::Matrix<Scalar, 3, 3> &covariance_matrix,
                                  Eigen::Matrix<Scalar, 4, 1> &centroid,
                                    Eigen::Matrix<Scalar, 3, 1> K_LocalShift=0,
                                  bool AutomaticLocalShift=true
);

where the last two arguments are not specified the implementations runs like now
where the last argument is not specified the implementations runs similar to now but with K given as an input by the user so to avoid outliers (not set automatically as the first finite point but specified by the user instead)
where K_LocalShift=0  and  AutomaticLocalShift=false
the implementation runs about 8% faster without using K


just a small very simple example about the double effect:


int main()
{
    float f=0,f1 = 1, f2 = 100000;
    double d=0, d1 = 1, d2 = 100000;

    for (int i = 0; i < 1000; ++i)
    {
        f += f1;
        f += f2;

        d += d1;
        d += d2;
    }

    printf("f= %.5f     d=%.5f\n", f, d);
}

outputs: (x64 Windows 10 machine)
f= 100000168.00000     d=100001000.00000

**Comment by mvieth** [comment]
Please see the issue I linked: using double instead of float and not shifting the points by `K` does not solve the problem when the points are far away from the origin. Only the distance from the origin can be higher when using double instead of float before the error becomes too large to tolerate. So shifting the points by `K` is necessary for accurate results.
Also, in my tests, the computation time was roughly twice as long when using double instead of float.
