### ISSUE TITLE
[NormalEstimationOMP] appearantly running with just one thread

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5717]
**Describe the bug**

Apperantly NormalEstimationOMP runs with just one thread on two different PCs I tested it
I guess it's not a bug of PCL and it's my fault somewhere, I cannot figure out where

**Context**

I was just making a test to benchmark on my PC what speed up would be given by NormalEstimationOMP from NormalEstimation
but it seems no speed up, so I investigated further and by ouputting 
        int total_td = omp_get_num_threads();
        printf("omp_get_num_threads %d \n", total_td);

i get 1

I tried it also on another pc and the same result

I wonder what am i doing wrong, in any case some sort of warning should be given

The compile config. WITH_OPENMP is true

I even added to CMakeLists to debug

if(OpenMP_FOUND)
  	message(STATUS "----------!!!!! OpenMP IS ACTIVE  !!!!!  OpenMP_FOUND: ${OpenMP_FOUND}")
  	message(STATUS "----------!!!!! OpenMP IS ACTIVE  !!!!!  OpenMP_VERSION: ${OpenMP_VERSION}")
  	message(STATUS " OpenMP_C_FOUND: ${OpenMP_C_FOUND}")
  	message(STATUS " OpenMP_CXX_FOUND: ${OpenMP_CXX_FOUND}")
  	message(STATUS " OpenMP_INCLUDE_DIRS: ${OpenMP_INCLUDE_DIRS}")
  	message(STATUS " OpenMP_C_INCLUDE_DIRS: ${OpenMP_C_INCLUDE_DIRS}")
  	message(STATUS " OpenMP_CXX_INCLUDE_DIRS: ${OpenMP_CXX_INCLUDE_DIRS}")
  	message(STATUS " OPENMP_INCLUDES: ${OPENMP_INCLUDES}")
  	message(STATUS " OPENMP_LIBRARIES: ${OPENMP_LIBRARIES}")

and I get

1> [CMake] -- ----------!!!!! OpenMP IS ACTIVE  !!!!!  OpenMP_FOUND: TRUE
1> [CMake] -- ----------!!!!! OpenMP IS ACTIVE  !!!!!  OpenMP_VERSION: 
1> [CMake] --  OpenMP_C_FOUND: TRUE
1> [CMake] --  OpenMP_CXX_FOUND: TRUE
1> [CMake] --  OpenMP_INCLUDE_DIRS: 
1> [CMake] --  OpenMP_C_INCLUDE_DIRS: 
1> [CMake] --  OpenMP_CXX_INCLUDE_DIRS: 
1> [CMake] --  OPENMP_INCLUDES: 
1> [CMake] --  OPENMP_LIBRARIES: 
1> [CMake] -- Found OpenMP, spec date 200203

I don't know if those empty strings  are a bad sign, I guess so but what to do??

I have also tried to add openMP pragmas to another for elsewhere in my code and it does the same (just one thread) so it must be a problem of my environment

**Expected behavior**

a speed up of the processing and more than one thread used and logged via omp_get_num_threads 

I don't understand because I think I used openMP not so long ago, I wonder if it is some wrong setting on my PC (but it's two PCs)

**Your Environment (please complete the following information):**

 - OS: [Windows 10]
 - Compiler: [MSVC2019]
 - PCL Version [last]

**Possible Solution**
very generic and not much helpful  hint:
give some warnings at some level, either compile or run time

The code using it

        if (globalState.calcNormal.get())
        {
            bool openMP = globalState.openMP.get();
            pcl::NormalEstimation<PointXYZRGB, Normal> n; 
            pcl::NormalEstimationOMP<PointXYZRGB, Normal> nomp(4); // instantiate n threads
            nomp.setNumberOfThreads(4);
            PointCloud<Normal>::Ptr normals(new PointCloud<Normal>());
            auto begin = std::chrono::high_resolution_clock::now();
            if (!openMP)
            {
                n.setInputCloud(filteredCloud);
                n.setKSearch(20);
                n.compute(*normals);
            }
            else
            {
                printf("\n using openMP\n");
                nomp.setInputCloud(filteredCloud);
                nomp.setKSearch(20);
                nomp.compute(*normals);
            }

            auto end = std::chrono::high_resolution_clock::now();
            auto elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin);
            printf("\n -----NORMALS TIME: %.3f msec.\n", elapsed.count() * 1e-6);

        }

**Comment by mynickmynick** [comment]
I am seeing now that _OPENMP is not #defined   

where am I supposed to add #define _OPENMP ??

if I add it in my application i get an other error

pcl_macros.h(68): fatal error C1017: invalid integer constant expression :
#if (defined _OPENMP && (_OPENMP <= 201307)) || (defined __GNUC__ && (__GNUC__ >= 6 && __GNUC__ < 9))

**Comment by mynickmynick** [comment]
something like convolve.cpp should be also in normals

#ifndef _OPENMP
    if (nb_threads > 1) {
      pcl::console::print_info("OpenMP not activated. Number of threads: 1\n");

**Comment by mynickmynick** [comment]
i think the reason is that my MSVC was missing an intel integration, my fault

but a warning of some kind I think should be generated somewhere by PCL

**Comment by mynickmynick** [comment]
also after the intel integration, still not working

**Comment by mvieth** [comment]
> i read suggested this for cmake?
target_link_libraries(MyTarget PUBLIC OpenMP::OpenMP_CXX)

See here: 
https://github.com/PointCloudLibrary/pcl/blob/cc4bde58d58783f20d84bba63d00349abef16b53/cmake/pcl_targets.cmake#L200-L202

You could add the following to your CMake diagnostics:
```cmake
  if(TARGET OpenMP::OpenMP_CXX)
    message(STATUS "OpenMP::OpenMP_CXX is available")
  else()
    message(STATUS "OpenMP::OpenMP_CXX is not available!")
  endif()
```

> but a warning of some kind I think should be generated somewhere by PCL
> something like convolve.cpp should be also in normals

I agree, I will look into it

I have no experience with using OpenMP with MSVC, so I can't help you with that problem.

**Comment by mynickmynick** [comment]
it seems that I have to add in the main (root) CmakeLists.txt of my application (linked to PCL) 

find_package(OpenMP COMPONENTS C CXX)

if i comment it i get
OpenMP::OpenMP_CXX is not available! 

by your suggested

  if(TARGET OpenMP::OpenMP_CXX)
    message(STATUS "OpenMP::OpenMP_CXX is available")
  else()
    message(STATUS "OpenMP::OpenMP_CXX is not available!")
  endif()

still in the same CMakeLists

still I am getting only one thread

but if I write a hello world simple program with a banal openmp for() like

#ifdef _OPENMP
#pragma omp parallel for num_threads(4)
  for (int i = 0; i < 1000000; ++i)
  {
      int total_td = omp_get_num_threads();  
      printf("iteration \t\t%d\t\t omp_get_num_threads  omp_get_max_threads  omp_get_thread_num   %d   %d   %d\n", i, total_td, omp_get_max_threads(),  omp_get_thread_num());

  }

#endif

i have succesfully 4 threads running

**Comment by mynickmynick** [comment]
now it seems to work but I had to add in my root CmakeLists.txt

find_package(OpenMP COMPONENTS C CXX)
if(OpenMP_FOUND)
  string(APPEND CMAKE_C_FLAGS " ${OpenMP_C_FLAGS}")
  string(APPEND CMAKE_CXX_FLAGS " ${OpenMP_CXX_FLAGS}")

endif()

the target_link_libraries(${RootProjectName} OpenMP::OpenMP_CXX) 
instead seems not necessary in this CmakeLists

I am sorry I thought it was sufficient the linking inside the PCL to openMP
instead I have to explicitely link also from my root CmakeLists

is that "normal"?

thanks

**Comment by larshg** [comment]
I have tried to reproduce it, but to me it seems to work well with multithreading, even though I haven't added OpenMP to my descendent project.
Now you mention root CMakelists - does that mean you include PCL as a submodule and include PCLs CMakelist in yours?

**Comment by larshg** [comment]
The defines might not show up correctly in a descendent opened project, since its not defined in that project. But it should still call and run OpenMP accelerated methods, if PCL was build with OpenMP support.

**Comment by mynickmynick** [comment]
@larshg i will get back to you as soon as possible and delete this temporary comment

**Comment by mynickmynick** [comment]
I don't know if I understood well your question but I will try to better explain.
I am not an expert of Cmake so I might have made something wrong
What I have is a CMake project which is an application that links to PCL as well as other libraries like openCV , RealSense , ImGUI and other stuff.
In the CMakeLists.txt of the main directory of the project I have 

find_package(PCL 1.2 REQUIRED)
actually I have also another probably redundant
find_package(PCL 1.2 REQUIRED)
in another CMakelIsts.txt down the folder submodules tree (Devices/Realsense/CmakeLists.txt)

then I have
Devices/Realsense/CmakeLists.txt
      include_directories(${PCL_INCLUDE_DIRS})
      link_directories(${PCL_LIBRARY_DIRS})
      add_definitions(${PCL_DEFINITIONS})
      target_link_libraries (RealSense ${PCL_LIBRARIES})

myImGUI/CmakeLists.txt
      include_directories(${PCL_INCLUDE_DIRS})
      link_directories(${PCL_LIBRARY_DIRS})
      add_definitions(${PCL_DEFINITIONS})
      target_link_libraries (myImGUI ${PCL_LIBRARIES})


and in a Globals.h I have

#define PCL_NO_PRECOMPILE //this define is very important!! otherwise many commands of the library do not work with XYZRGB points

I hope this is all, I am not finding other configurations

Actually as I wrote i do target_link_libraries ( ${PCL_LIBRARIES}) only inside 2 submodules, not in the main CMakeLists.txt

Inside the main CMakeLists.txt I have

target_link_libraries(${RootProjectName} myImGUI Devices)

In the main CMakeLists.txt I had to add

find_package(OpenMP COMPONENTS C CXX)
if(OpenMP_FOUND)
  string(APPEND CMAKE_C_FLAGS " ${OpenMP_C_FLAGS}")
  string(APPEND CMAKE_CXX_FLAGS " ${OpenMP_CXX_FLAGS}")
  message(STATUS "Found OpenMP, spec date ${OpenMP_CXX_SPEC_DATE}")
endif()

**Comment by mynickmynick** [comment]
>Now you mention root CMakelists - does that mean you include PCL as a submodule and include PCLs CMakelist in yours?

I only link to PCL with target_link_libraries 

> The defines might not show up correctly in a descendent opened project, since its not defined in that project. But it should still call and run OpenMP accelerated methods, if PCL was build with OpenMP support.

PCL was build with openMP support (WITH_OPENMP=true) but nope the number of threads was 1

1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_INSTALL_PREFIX:PATH="D:\U\Cdev\C++\repo\external\forks\pcl\out\install\x64-Release" -DBUILD_CUDA:BOOL="False" -DCMAKE_BUILD_TYPE:STRING="Release" -DVTK_DIR:PATH="C:/Users/User/source/repos/VTK/out/install/x64-Release" -DBUILD_visualization:BOOL="True" -DWITH_OPENMP:BOOL="True" -DBUILD_global_tests:BOOL="True" -DQhull_DIR:PATH="D:/U/Cdev/C++/repo/external/forks/qhull/out/install/x64-Release" -DCMAKE_CUDA_STANDARD:STRING="14" -DCMAKE_CXX_STANDARD:STRING="14" -DWITH_CUDA:BOOL="False"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Users/User/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\U\Cdev\C++\repo\external\forks\pcl" 2>&1"


1> [CMake] -- Found OpenMP, spec date 200203


1> [CMake] -- PCL build with following flags:
1> [CMake] -- /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj /FS -openmp

**Comment by larshg** [comment]
I recently created this https://github.com/PointCloudLibrary/pcl/pull/5718
Can you update PCL and see if it makes a difference?
I can also try a commit earlier without this fix, but I'm quite sure I did that, when I tested it.

But I noticed the AVX flags wasn't applied correctly during the multithread test and got a memory error when releasing a pointcloud.

The openmp part of that code, tries to detect the number of cores and supply that value to set how many theads it can use.
It could have had a impact, but I think it default to 0, which makes openMP check at runtime AFAIK.

**Comment by larshg** [comment]
> I recently created this #5718 Can you update PCL and see if it makes a difference? I can also try a commit earlier without this fix, but I'm quite sure I did that, when I tested it.
> 
> But I noticed the AVX flags wasn't applied correctly during the multithread test and got a memory error when releasing a pointcloud.
> 
> The openmp part of that code, tries to detect the number of cores and supply that value to set how many theads it can use. It could have had a impact, but I think it default to 0, which makes openMP check at runtime AFAIK.

Nm this. The mp count in this case is number if threads when compiling 😳

**Comment by larshg** [comment]
Could you set a breakpoint in the omp for loop and see the thread window to see if multiple threads get spawned, when you step forward. A blue circle will also appear at the program pointer, whenever it does a thread shift.

**Comment by mynickmynick** [comment]
> te PCL and see if it makes a difference? I can also try a commit earlier without this fix, but I'm quite sure I did that, when I tested it.
> 
> But I noticed the AVX flags wasn't applied correctly during the multithread test and got a memory error when releasing a pointcloud.
> 
> The openmp part of that code, tries to detect the number of cores and supply that value to set how many theads it can use. It could have had a impact, but I think it default to 0, which makes openMP check at runtime AFAIK.

i was setting the number of threads passing it to the constructor (typically as 4) so the

**Comment by mynickmynick** [comment]
> > and in a Globals.h I have
> 
> > #define PCL_NO_PRECOMPILE //this define is very important!! otherwise many commands of the library do not work with XYZRGB points
> 
> @larshg I think this might be the deciding point (the code is compiled in the user project, and the implementation from PCL is not used). Perhaps we should look into whether PCLConfig.cmake has to also find_package OpenMP? I think there are also OpenMP implementations of algorithms that have no instantiation in PCL and are always compiled in the user project (e.g. in the registration module). They would have the same problem.

I had to set this define cause otherwise I would not be able to use everything i needed for XYZRGB (I don't remember which features, i did this several months ago)

**Comment by larshg** [comment]
> I am sorry would you like me to make a test with a breakpoint or it's not useful anymore becasue you already figured out the matter?

I don't think its necessary to do it now. I think its clear, that if there is no find_package(OpenMP) in the PCLConfig and you compile with NO_PRECOMPILE, the OpenMP flags wouldn't be used and hence, you won't get any multithreading.
And you can solve it by adding it to your local file, just shows that it could be solved by have PCL looking for it as well.
