### ISSUE TITLE
[registration] Make ICP work with TransformationEstimationPointToPlane when only target point type has normals

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5727]
**Is your feature request related to a problem? Please describe.**

I have a target cloud for which I can estimate normals once, and want to align the source to it, for which I do not have normals. The `TransformationEstimationPointToPlane` only needs the target normals. However, one cannot instantiate an object of type `Registration<PointXYZ, PointNormal>`, because that tries to instantiate `pcl::KdTreeFLANN<pcl::PointNormal>>` for the reciprocal kdtree, even if the user does not want to use reciprocal correspondences. Hence code like this does not compile:

```
  IterativeClosestPoint<PointXYZ, PointNormal> icp;
```

```
prefix/include/pcl-1.13/pcl/registration/correspondence_estimation.h:93:5: error: no matching constructor for initialization of 'pcl::registration::CorrespondenceEstimationBase<pcl::PointXYZ, pcl::PointNormal>::KdTreeReciprocalPtr' (aka 'shared_ptr<KdTree<pcl::PointNormal, pcl::KdTreeFLANN<pcl::PointNormal>>>') , tree_reciprocal_(new pcl::search::KdTree<PointSource>)
    ^                ~~~
prefix/include/pcl-1.13/pcl/registration/correspondence_estimation.h:413:3: note: in instantiation of member function 'pcl::registration::CorrespondenceEstimationBase<pcl::PointXYZ, pcl::PointNormal>::CorrespondenceEstimationBase' requested here CorrespondenceEstimation() { corr_name_ = "CorrespondenceEstimation"; }
  ^
prefix/include/pcl-1.13/pcl/registration/icp.h:161:13: note: in instantiation of member function 'pcl::registration::CorrespondenceEstimation<pcl::PointXYZ, pcl::PointNormal>::CorrespondenceEstimation' requested here new pcl::registration::
            ^
file.cpp:111:48: note: in instantiation of member function 'pcl::IterativeClosestPoint<pcl::PointXYZ, pcl::PointNormal>::IterativeClosestPoint' requested here IterativeClosestPoint<PointXYZ, PointNormal> icp;
```

This is an unfortunate limitation, as the source point cloud may be much sparser and unsuitable for estimating normals, which are also not needed for the Point-to-Plane error function.

**Context**

When aligning to a model, the model can usually be enriched with normals easily, while the measurement may not.

**Expected behavior**

A registration can be instantiated which only requires target normals, not source normals at the same time.

**Current Behavior**

If target point requires normals, source point requires normals as well.

**Describe the solution you'd like**

Don't know, I feel like the current API does not support this, as it always instantiates the reciprocal kdtree, even if unused. 

**Describe alternatives you've considered**

Maybe one can pass empty normals for the source point cloud? That would be a hack however. I tested this briefly by just using `copyPointCloud<PointXYZ, PointNormal>`, but that seems to break registration completely in that case.

**Comment by themightyoarfish** [comment]
Looking at `registration/include/pcl/registration/correspondence_estimation.h`, one can also see a bug:
`  using KdTreeReciprocalPtr = typename KdTree::Ptr;` should be `  using KdTreeReciprocalPtr = typename KdTreeReciprocal::Ptr;`. Maybe it would be possible to switch around source and target to make it work?

**Comment by mvieth** [comment]
@themightyoarfish Would https://github.com/PointCloudLibrary/pcl/pull/4901 add the functionality you are looking for?

**Comment by themightyoarfish** [comment]
It seems that with that PR, `IterativeClosestPoint<PointXYZ, PointNormal>` and `IterativeClosestPoint<PointNormal, PointXYZ>` can indeed be instantiated.

**Comment by mvieth** [comment]
@themightyoarfish The PR I mentioned earlier is now merged, so I am closing this issue. However, if you are still missing something, feel free to comment.
