### ISSUE TITLE
Geometrical segmentation (vertical & horizontal ) on point clouds

### ISSUE THREAD

**Issue by HripsimeS** [PointCloudLibrary/pcl#5730]
@arjun810 @ibtaylor @garaemon @barhomi @moriarty 

Hello. I would appreciate if you inform me if there is a way with PCL to do a segmentation of horizontal and vertical point clouds. To get horizontal point clouds one color and other color for vertical point clouds.

I look forward to hearing from you and thanks in advance!!!

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
