### ISSUE TITLE
Compilation ERROR !!!!   duplicate symbol  pcl::Registration   

### ISSUE THREAD

**Issue by tust13018211** [PointCloudLibrary/pcl#5734]
I use PCL 1.10, But when I compile. I meet this error
![B9820758-897F-461c-BA5A-D23BBCCC5C36](https://github.com/PointCloudLibrary/pcl/assets/83019441/bfa30318-4a2f-47d7-89f0-24aafa5919c8)

So，How Can I fix this

**Comment by mvieth** [comment]
@tust13018211 How do you compile? Do you use CMake? Which compiler? How did you install PCL? Do you use static or dynamic PCL libraries?

**Comment by mvieth** [comment]
Closing because of no response ...
