### ISSUE TITLE
Custom Point type used in IterativeClosestPoint

### ISSUE THREAD

**Issue by xuanxianyou** [PointCloudLibrary/pcl#5739]
In the project, I customized a Point Type
’‘’
struct EIGEN_ALIGN16 MyPointType   
{
    PCL_ADD_POINT4D;
    // PCL_ADD_RGB;      
    float flag;
    PCL_MAKE_ALIGNED_OPERATOR_NEW  
};
‘’‘

’‘’
pcl::IterativeClosestPoint<MyPointType, MyPointType> icp;
‘’‘

when point cloud registration, it reported an error

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: __cdecl pcl::PCLBase<struct MyPointType>::PCLBase<struct MyPointType>(void)" (??0?$PCLBase@UMyPointType@@@pcl@@QEAA@XZ)，函数 "public: __cdecl pcl::registration::CorrespondenceEstimationBase<struct MyPointType,struct MyPointType,float>::CorrespondenceEstimationBase<struct MyPointType,struct MyPointType,float>(void)" (??0?$CorrespondenceEstimationBase@UMyPointType@@U1@M@registration@pcl@@QEAA@XZ) 中引用了该符号	D:\QtProject\pclDemo\out\build\x64-debug\pclDemo	D:\QtProject\pclDemo\out\build\x64-debug\icpNew.cpp.obj	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: __cdecl pcl::PCLBase<struct MyPointType>::PCLBase<struct MyPointType>(class pcl::PCLBase<struct MyPointType> const &)" (??0?$PCLBase@UMyPointType@@@pcl@@QEAA@AEBV01@@Z)，函数 "public: __cdecl pcl::registration::CorrespondenceEstimationBase<struct MyPointType,struct MyPointType,float>::CorrespondenceEstimationBase<struct MyPointType,struct MyPointType,float>(class pcl::registration::CorrespondenceEstimationBase<struct MyPointType,struct MyPointType,float> const &)" (??0?$CorrespondenceEstimationBase@UMyPointType@@U1@M@registration@pcl@@QEAA@AEBV012@@Z) 中引用了该符号	D:\QtProject\pclDemo\out\build\x64-debug\pclDemo	D:\QtProject\pclDemo\out\build\x64-debug\icpNew.cpp.obj	1

**Comment by mvieth** [comment]
@xuanxianyou Read this: https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html#how-to-add-a-new-pointt-type

**Comment by mvieth** [comment]
Since you did not respond, I am assuming that solved your issue.

**Comment by xuandong93** [comment]
Hi  I am working on this, created a custom point type, populated the data and managed to save it to a file , when i tried to read it back , it says no `Failed to find exact match for field 'nx'`, same for ny, nz, red, green, blue. Any idea what's wrong ? 
```cpp

struct MyPointXYZNTUV
{
  PCL_ADD_POINT4D;          // x, y, z + padding
  float nx, ny, nz;         // normals
  uint8_t red, green, blue; // color
  float s, t, u, v;         // texture coordinates
  PCL_MAKE_ALIGNED_OPERATOR_NEW
} EIGEN_ALIGN16;

// Register the struct with PCL
POINT_CLOUD_REGISTER_POINT_STRUCT(
    MyPointXYZNTUV,
    (float, x, x)(float, y, y)(float, z, z)(float, nx, nx)(float, ny, ny)(float, nz, nz)(uint8_t, red, red)(
        uint8_t, green, green)(uint8_t, blue, blue)(float, s, s)(float, t, t)(float, u, u)(float, v, v))

pcl::PointCloud<MyPointXYZNTUV>::Ptr cloudstuv(new pcl::PointCloud<MyPointXYZNTUV>);
pcl::io::savePLYFile("cloudstuv.ply", *cloudstuv);
pcl::io::loadPLYFile("cloudstuv.ply", *cloudstuv);

```
