### ISSUE TITLE
The link to the 3D Features tutorial seems to be broken

### ISSUE THREAD

**Issue by wyckster** [PointCloudLibrary/pcl#5745]
The link that produces a 404 error is http://pointclouds.org/documentation/tutorials/how_features_work.php

This is the line in the documentation that references the link.
https://github.com/PointCloudLibrary/pcl/blob/f0c7c46e82b70307922e4983cd1d850b47b54242/doc/tutorials/content/walkthrough.rst?plain=1#L107

What is the correct link?

**Comment by mvieth** [comment]
Thanks for reporting. This is the correct link: https://pcl.readthedocs.io/projects/tutorials/en/master/how_features_work.html

**Comment by larshg** [comment]
Fixed by #5747
