### ISSUE TITLE
The pcl program ran into problems

### ISSUE THREAD

**Issue by 0DWADE0** [PointCloudLibrary/pcl#5746]
**Describe the error**

I wrote a program with Qt, the function is to call the depth camera to shoot depth pictures to get the point cloud and then use pcl for processing, but I encountered some problems when running, the specific problems are as follows.

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. Custom OS, custom PCL configs or custom build systems make the issue difficult to reproduce.
* Best reproducibility: A docker image + code snippets provided here
* Good reproducibility: Common Linux OS + default PCL config + code snippets provided here
* Poor reproducibility: code snippets

Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)

**Screenshots/Code snippets/Build information**

* screenshots of the GUI issues 
* code snippets: [syntax for code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) with correct language highlights

* debugging information:
  * the output of cmake using `cmake --debug`
  * the failing build command(s) using `VERBOSE=1 make`, `ninja -v` or similar
  * steps taken to narrow down the problem

**Your Environment (please complete the following information):**

 - OS: [e.g. Ubuntu 16.04]
 - Compiler: [:eg GCC 8.1]
 - PCL Version [e.g. 1.10, HEAD] (NB: please ensure you don't have multiple versions available)
 - PCL Type: [e.g. Installed with VCPKG/Installed with apt/Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes/No
 - List and Version of dependencies used
 - Compilation flags are used

If compiling against PCL:
 - Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
  * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
  * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by larshg** [comment]
@0DWADE0 please edit your issue and fill in the various sections with your info.
And describe your problem with code examples and debug/conslle outputs.

**Comment by 0DWADE0** [comment]
> **Describe the error**
> 
> I wrote a program with Qt, the function is to call the depth camera to shoot depth pictures to get the point cloud and then use pcl for processing, but I encountered some problems when running, the specific problems are as follows.
> 
> **To Reproduce**
>This error occurs some time after I run the program, and I don't know why.
> 
> 
> * Best reproducibility: A docker image + code snippets provided here
> * GGood reproducibility: Common Linux OS + default PCL config + code snippets provided hereood reproducibility: Common Linux OS + default PCL config + code snippets provided here
> * Poor reproducibility: code snippets
> 
> Remember to reproduce the error in a clean rebuild (removing all build objects and starting build from scratch)
> 
> **Screenshots/Code snippets/Build information**
> 
![f7c76c6644cb84dd418c96db08abdfb](https://github.com/PointCloudLibrary/pcl/assets/121961555/496cb8dd-d4a0-404e-9563-df7489a60871)

> * screenshots of the GUI issues
> *
 #include <librealsense2/rs.hpp> // Include RealSense Cross Platform API
//#include <example.hpp>// Include short list of convenience functions for rendering

#include <QFileDialog>
#include <QPushButton>
#include <QString>
//#include <pclviewer.h>
#include <iostream>
#include <vtkRenderWindow.h>
#include <vtkOutputWindow.h>
#include <vtkImageViewer2.h>
#include <vtkPNGReader.h>
#include <vtkPolyDataAlgorithm.h>
#include <pcl/filters/passthrough.h>
#include <pcl/filters/voxel_grid.h>
#include <QFileDevice>
#include <QXmlStreamReader>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/filters/project_inliers.h>
#include <pcl/features/normal_3d.h>
#include <pcl/features/boundary.h>
#include <QCoreApplication>
#include <QTextStream>
#include <QStringList>
#include <QtSerialPort/QSerialPort> 
#include <QtSerialPort/QSerialPortInfo> 
#include <functional>
#include <vtkAutoInit.h>
#include <pcl/filters/radius_outlier_removal.h>
#include <pcl/filters/conditional_removal.h>
#include <pcl/io/pcd_io.h>
#include <QTimer>
#include <QVboxLayout>
#include <QHBoxLayout>
#include "vtkRenderer.h"
#include "vtkRenderWindowInteractor.h"
#include "vtkConeSource.h"

#include "QtGuiApp_Realsense.h"
#include "ui_QtGuiApp_Realsense.h"


#pragma execution_character_set("utf-8")

VTK_MODULE_INIT(vtkRenderingOpenGL2);
VTK_MODULE_INIT(vtkInteractionStyle);

using std::cerr;
using std::cout;
using std::endl;
using std::vector;
using namespace std;
const std::string _poindCloudID = "cloud";
const std::string _clickID = "click";

//struct state {
//	state() : yaw(0.0), pitch(0.0), last_x(0.0), last_y(0.0),
//		ml(false), offset_x(0.0f), offset_y(0.0f) {}
//	double yaw, pitch, last_x, last_y; bool ml; float offset_x, offset_y;
//};

//using pcl_ptr = pcl::PointCloud<pcl::PointXYZ>::Ptr;

QtGuiApp_Realsense::QtGuiApp_Realsense(QWidget *parent)
	: QWidget(parent)
	
{
	ui.setupUi(this);

	system_init();//系统初始化


	//cloud.reset(new PointCloudT);
	//main_cloud.reset(new PointCloudT);
	//main_cloud2.reset(new pcl::PointCloud<pcl::PointXYZ>);
	//sub_cloud2.reset(new pcl::PointCloud<pcl::PointXYZ>);

	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud1(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud2(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud3(new pcl::PointCloud<pcl::PointXYZ>);

	//connect(ui.pushButton, &QPushButton::clicked, [=]() {


}

void QtGuiApp_Realsense::system_init()
{
	//ui.lineEdit->setFocusPolicy(Qt::NoFocus);
	//ui.lineEdit_2->setFocusPolicy(Qt::NoFocus);
	//ui.lineEdit_3->setFocusPolicy(Qt::NoFocus);

	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud1(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud2(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr main_cloud3(new pcl::PointCloud<pcl::PointXYZ>);

	connect(ui.pushButton, &QPushButton::clicked, this, &QtGuiApp_Realsense::IsDevice);


}
void QtGuiApp_Realsense::IsDevice()
{
	rs2::pointcloud pc;
	//We want the points object to be persistent so we can display the last cloud when a frame drops 我们希望points对象是持久的，这样我们就可以在帧下降时显示最后一个云
	rs2::points points;

	//Declare RealSense pipeline, encapsulating the actual device and sensors 声明RealSense管道，封装实际的设备和传感器
	rs2::pipeline pipe;
	//Start streaming with default recommended configuration 使用默认推荐配置启动流
	rs2::config cfg;
	cfg.enable_stream(RS2_STREAM_COLOR);
	cfg.enable_stream(RS2_STREAM_INFRARED);
	cfg.enable_stream(RS2_STREAM_DEPTH);

	rs2::pipeline_profile selection = pipe.start(cfg);

	rs2::device selected_device = selection.get_device();
	auto depth_sensor = selected_device.first<rs2::depth_sensor>();

	depth_sensor.set_option(RS2_OPTION_MIN_DISTANCE, 0.1);
	// Wait for the next set of frames from the camera 等待来自相机的下一组帧
	auto frames = pipe.wait_for_frames();

	auto depth = frames.get_depth_frame();

	// Generate the pointcloud and texture mappings 生成点云和纹理映射
	points = pc.calculate(depth);

	auto pcl_points = points_to_pcl(points);

	DataProcessing(pcl_points);



}

void QtGuiApp_Realsense::DataProcessing(pcl::PointCloud<pcl::PointXYZ>::Ptr &main_cloud)
{

	main_cloud = PassThrough_filter(main_cloud, -0.16, 0.16, 0.8, 1.6);
	main_cloud = VoxelGrid_filter(main_cloud, 0.002f);
	main_cloud = Projection_filter(main_cloud, 4, 0, 1.0, 0, 0);
	main_cloud = Boundary_filter(main_cloud,0.001,0.50);

	bodymeasurement(main_cloud);



}

pcl::PointCloud<pcl::PointXYZ>::Ptr QtGuiApp_Realsense::points_to_pcl(const rs2::points& points)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);

	auto sp = points.get_profile().as<rs2::video_stream_profile>();
	cloud->width = sp.width();
	cloud->height = sp.height();
	cloud->is_dense = false;
	cloud->points.resize(points.size());
	auto ptr = points.get_vertices();
	for (auto& p : cloud->points)
	{
		p.x = ptr->x;
		p.y = ptr->y;
		p.z = ptr->z;
		ptr++;
	}

	return cloud;
}

//直通滤波
pcl::PointCloud<pcl::PointXYZ>::Ptr QtGuiApp_Realsense::PassThrough_filter(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud, float y1, float y2, float z1, float z2)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered0(new pcl::PointCloud<pcl::PointXYZ>);

	pcl::PassThrough<pcl::PointXYZ> pass;
	pass.setInputCloud(cloud);
	pass.setFilterFieldName("z");
	pass.setFilterLimits(z1, z2);
	pass.filter(*cloud_filtered);

	pcl::PassThrough<pcl::PointXYZ> pass1;
	pass.setInputCloud(cloud_filtered);
	pass.setFilterFieldName("y");
	pass.setFilterLimits(y1, y2);
	pass.filter(*cloud_filtered0);

	return cloud_filtered0;
}
//下采样
pcl::PointCloud<pcl::PointXYZ>::Ptr QtGuiApp_Realsense::VoxelGrid_filter(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud, float s)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);

	pcl::VoxelGrid<pcl::PointXYZ> sor;
	//pcl::VoxelGrid<pcl::PCLPointCloud2> sor;
	sor.setInputCloud(cloud);
	sor.setLeafSize(s, s, s);//设置滤波时创建的体素体积为1 cm3的立方体
	sor.filter(*cloud_filtered);

	return cloud_filtered;
}
//投影
pcl::PointCloud<pcl::PointXYZ>::Ptr QtGuiApp_Realsense::Projection_filter(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud, int re, float a, float b, float c, float d)
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);

	pcl::ModelCoefficients::Ptr coefficients(new pcl::ModelCoefficients());
	coefficients->values.resize(re);
	coefficients->values[0] = a;
	coefficients->values[1] = b;
	coefficients->values[2] = c;
	coefficients->values[3] = d;
	// --------------创建滤波器对象-------------------
	pcl::ProjectInliers<pcl::PointXYZ> proj;
	proj.setModelType(pcl::SACMODEL_PLANE);
	proj.setInputCloud(cloud);
	proj.setModelCoefficients(coefficients);
	proj.filter(*cloud_filtered);

	return cloud_filtered;
}
//边界点提取
pcl::PointCloud<pcl::PointXYZ>::Ptr QtGuiApp_Realsense::Boundary_filter(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud, float rs1, float rs2)
{
	pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> n;   //其中pcl::PointXYZ表示输入类型数据，pcl::Normal表示输出类型,且pcl::Normal前三项是法向，最后一项是曲率
	pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
	n.setInputCloud(cloud);
	n.setSearchMethod(tree);
	n.setRadiusSearch(rs1);
	pcl::PointCloud<pcl::Normal>::Ptr normals(new pcl::PointCloud<pcl::Normal>);
	n.compute(*normals);
	//-----------------------边界特征估计--------------------------
	pcl::BoundaryEstimation<pcl::PointXYZ, pcl::Normal, pcl::Boundary> boundEst;
	boundEst.setInputCloud(cloud);
	boundEst.setInputNormals(normals);
	boundEst.setRadiusSearch(rs2);
	boundEst.setAngleThreshold(M_PI / 2);//边界判断时的角度阈值

	boundEst.setSearchMethod(tree);
	pcl::PointCloud<pcl::Boundary> boundaries;
	boundEst.compute(boundaries);
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_boundary(new pcl::PointCloud<pcl::PointXYZ>);
	for (int i = 0; i < cloud->points.size(); i++)
	{

		if (boundaries[i].boundary_point > 0)
		{
			cloud_boundary->push_back(cloud->points[i]);
		}
	}

	return cloud_boundary;
}
//体尺计算
void QtGuiApp_Realsense::bodymeasurement(pcl::PointCloud<pcl::PointXYZ>::Ptr &cloud)
{
	float xmax = cloud->points[0].x;
	float ymax = cloud->points[0].y;
	float zmax = cloud->points[0].z;
	float xmin = cloud->points[0].x;
	float ymin = cloud->points[0].y;
	float zmin = cloud->points[0].z;
	PointT xmaxpoint;
	PointT midpoint;
	PointT ymaxpoint;
	PointT zmaxpoint;
	PointT xminpoint;
	PointT yminpoint;
	PointT backpoint;
	PointT legpoint;
	PointT legfrontpoint;
	PointT zminpoint;
	pcl::PointXYZ minBack, maxBack;
	PointCloudT::Ptr Backpoints(new PointCloudT);

	//pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered2(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered3(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered4(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered5(new pcl::PointCloud<pcl::PointXYZ>);
	//pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered6(new pcl::PointCloud<pcl::PointXYZ>);
	for (int i = 1; i < cloud->points.size(); i++)
	{

		if (cloud->points[i].x < xmin) //找到X值最小的点
		{
			xmin = cloud->points[i].x;
			//xminpoint.x = cloud->points[i].x;
			//xminpoint.y = cloud->points[i].y;
			//xminpoint.z = cloud->points[i].z;
		}
	}
	for (int i = 1; i < cloud->points.size(); i++)
	{

		if (cloud->points[i].x > xmax) //找到X值最大的点
		{
			xmax = cloud->points[i].x;
			//xmaxpoint.x = cloud->points[i].x;
			//xmaxpoint.y = cloud->points[i].y;
			//xmaxpoint.z = cloud->points[i].z;
		}
	}
	for (int i = 1; i < cloud->points.size(); i++)
	{
		if (cloud->points[i].x <= (xmin + xmax) / 2 + 0.04&&cloud->points[i].x >= (xmin + xmax) / 2 - 0.015)
		{
			backpoint.x = cloud->points[i].x;
			backpoint.y = cloud->points[i].y;
			backpoint.z = cloud->points[i].z;
			Backpoints->points.push_back(backpoint);
		}
	}

	pcl::getMinMax3D(*Backpoints, minBack, maxBack);

	double withers_height = 1.815 - minBack.z;
	double  Body_length = xmax - xmin;

	//cout << "模型羊的体高为" << withers_height << endl;
	//cout << "模型羊的体长为" << Body_length << endl;

	ui.lineEdit->setText(QString::number(withers_height));
	ui.lineEdit_2->setText(QString::number(Body_length));

}

> * debugging information:
>   
>   * the output of cmake using `cmake --debug`
>   * the failing build command(s) using `VERBOSE=1 make`, `ninja -v` or similar
>   * steps taken to narrow down the problem
> 
> **Your Environment (please complete the following information):**
> 
> * WIN: [10]
> * Compiler: [:eg VS017]
> * PCL Version [e.g. 1.9.1, HEAD] (NB: please ensure you don't have multiple versions available)
> * PCL Type: [e.g. Installed with apt]
> 
> If PCL was compiled from source or failure in compiling PCL itself:
> 
> * GPU, Kinfu, CUDA enabled? No
> * List and Version of dependencies used
> * Compilation flags are used
> 
> If compiling against PCL:
> 
> * Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
> 
> * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
> * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)
> 
> **Possible Solution**
> 
> Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.
> 
> **Additional context**
> 
> Add any other context about the problem here.

**Comment by mvieth** [comment]
@0DWADE0 That still does not tell us much. The messages in the screenshot are in Chinese, and we can't read Chinese. Did you at least try to find out in which line of your code the error happens? Or have you tried producing a backtrace with a debugger?

**Comment by 0DWADE0** [comment]
Hi@mvieth In the process of debugging the code today, I found that there are other problems below here.

void QtGuiApp_Realsense::DataProcessing(pcl::PointCloudpcl::PointXYZ::Ptr &main_cloud)
{
      main_cloud = PassThrough_filter(main_cloud, -0.16, 0.16, 0.8, 1.6);
      main_cloud = VoxelGrid_filter(main_cloud, 0.002f);
      main_cloud = Projection_filter(main_cloud, 4, 0, 1.0, 0, 0);
      main_cloud = Boundary_filter(main_cloud,0.001,0.50);
      bodymeasurement(main_cloud);
}

Whenever I call the filter function, the problem I raised above occurs, and I wonder if I'm assigning the value in the wrong way

**Comment by 0DWADE0** [comment]
Hi@mvieth The key problem I found was that the error occurred every time I called the filter function. Moreover, calling different filter functions will trigger different breakpoints, and the following error occurred when I called VoxelGrid.
![209b19274c6cfd5762699d9e170a6ef](https://github.com/PointCloudLibrary/pcl/assets/121961555/599dd153-119e-46aa-8cf8-5e14ecdb235a)

**Comment by mvieth** [comment]
@0DWADE0 an error in that function means that you likely have to activate AVX/AVX2 in your configuration

**Comment by 0DWADE0** [comment]
Hi @mvieth  I have fixed the problem because I added an additional dependency incorrectly. msvct.lib was added to msvctd.lib. Thank you.
