### ISSUE TITLE
include header file qvtk_compatibility.h doesn't include protection

### ISSUE THREAD

**Issue by aarizaq** [PointCloudLibrary/pcl#5752]
include header file qvtk_compatibility.h doesn't include protection

The solution is simple

#ifndef  __QVTK_COMPATIBILITY_H__
#define __QVTK_COMPATIBILITY_H__

#endif

**Comment by hoangtran080204** [comment]
I'm a first time contributor and would like to take up on this task and open a PR for it.

**Comment by mvieth** [comment]
@hoangtran080204 That is great! Please go ahead. If you have any questions, feel free to ask.
