### ISSUE TITLE
MLS output problem.

### ISSUE THREAD

**Issue by APOS80** [PointCloudLibrary/pcl#5753]
CloudCompare use PCL-MLS for smoothening surfaces but it has a problem with my cloud.
Some points seem to be created very far from the main cloud resulting in a NULL boundingbox.
https://sprend.com/download?C=d289122abe754e1e820ac79ebc5f7035

What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world

Get a smoother cloud

Getting a smoother cloud as before.

What happens instead of the expected behavior?

Strange new points far of i created resulting in a strange boundingbox.

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. If you load data e.g. from a PCD or PLY file, please provide the file.

https://sprend.com/download?C=d289122abe754e1e820ac79ebc5f7035
Run that with MLS

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: Its a plugin in cloudcompare
 - PCL Version Don know at this point.

**Possible Solution**

**Additional context**
Problem is in the latest Cloudcompare version

**Comment by mvieth** [comment]
@APOS80 The description of your problem reminds me of this issue: https://github.com/PointCloudLibrary/pcl/issues/4945
That issue was fixed by https://github.com/PointCloudLibrary/pcl/pull/4973 PCL 1.13.0 and newer include that fix. So my best guess is that your cloudcompare uses something older than PCL 1.13.0

**Comment by mvieth** [comment]
Question seems to be answered (and problem fixed on the PCL side), so I am closing this issue. Otherwise, feel free to comment
