### ISSUE TITLE
SIFT keypoint input values

### ISSUE THREAD

**Issue by drathin4** [PointCloudLibrary/pcl#5758]
I need some help for setting the appropriate constant values while computing SIFT keypoints - `minimum contrast, number of octaves, scales per octave`. From the code, I understood that `minimum scale` is the `voxel/leaf size`, but other constants are not clear. The original research paper by `Lowe` on `SIFT KeyPoints` is based on image processing and I'm still trying to contextualize that for point cloud processing. All the open source examples on the internet give some random values to these constants, but I think that they should be a function of the point cloud. Any suggestions for the same?

**Comment by mvieth** [comment]
Personally, I haven't worked much with PCL's `SIFTKeypoint` implementation yet, but I assume it makes sense to carefully read Lowe's paper to understand what these parameters do, even if that paper does not deal with point clouds. These parameters do not seem to be point cloud specific.
You can also ask on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) (the GitHub issues are rather intended for bug reports and compile errors)
