### ISSUE TITLE
 PPF gets other poses

### ISSUE THREAD

**Issue by Eray-L** [PointCloudLibrary/pcl#5759]
I am a PCL beginner.When using PPF, I found that it can only output a single final transformation.How can I get other poses?

**Comment by mvieth** [comment]
@Eray-L Do you mean when using `PPFRegistration`, or in which context? Can you describe in more detail what you are trying to do and why you need more than one transformation/pose?

**Comment by Eray-L** [comment]
Yeah, what I meant is that when using PPFRegistration in PCL, I can get a final transformation，use `getFinalTransformation()`.
However, in Drost's paper, the clustering process for poses can generate others results, not only one.as shown in the figure,
![image](https://github.com/PointCloudLibrary/pcl/assets/128468962/ac39aa76-a43c-4c5c-87a6-00b3bdc30931)
In the poses clustering, there are three winning clusters, but only one is  outputted. How can I get the other clusters with lower votes counts? Or am I misunderstanding something?

**Comment by mvieth** [comment]
@Eray-L Currently, there is no way to get the other clusters. I created a pull request to make that possible, and to add other improvements to `PPFRegistration`. Feel free to take a look.
