### ISSUE TITLE
sensor_origin and sensor_orientation not read when loading pointcloud from PLY file

### ISSUE THREAD

**Issue by flm8620** [PointCloudLibrary/pcl#5761]
https://github.com/PointCloudLibrary/pcl/blob/b268d07d9fa8faa8e46a0994a47d330e0d953da5/io/src/ply_io.cpp#L556C74-L556C85

The variable `origin` and `orientation` is not touched in this function:

```
int
pcl::PLYReader::readHeader (const std::string &file_name, pcl::PCLPointCloud2 &cloud,
                            Eigen::Vector4f &origin, Eigen::Quaternionf &orientation,
                            int &, int &, unsigned int &, const int)
{
  // Silence compiler warnings
  cloud_ = &cloud;
  range_grid_ = new std::vector<std::vector<int> >;
  cloud_->width = cloud_->height = 0;
  origin = Eigen::Vector4f::Zero ();
  orientation = Eigen::Quaternionf::Identity ();
  if (!parse (file_name))
  {
    PCL_ERROR ("[pcl::PLYReader::read] problem parsing header!\n");
    return (-1);
  }
  cloud_->row_step = cloud_->point_step * cloud_->width;
  return 0;
}
```

It seems a bug because there actually exists code to process origin and orientation information in PLY file, and assigned to member variable `origin` and `orientation_`: https://github.com/PointCloudLibrary/pcl/blob/b268d07d9fa8faa8e46a0994a47d330e0d953da5/io/include/pcl/io/ply_io.h#L352

But then these two variables is overwritten by empty values at https://github.com/PointCloudLibrary/pcl/blob/b268d07d9fa8faa8e46a0994a47d330e0d953da5/io/src/ply_io.cpp#L656

**Comment by mvieth** [comment]
Hi, seems like the assignments in line 656 and 657 should probably be the other way. Do you have a PLY file that specifies origin and orientation, or how did you notice this behaviour?

**Comment by flm8620** [comment]
I tried to assign sensor origin and orientation in C++, then save it as PCD/PLY then load it and check the two variables. The PCD one works but PLY doesn't. I checked the file content in PLY, it did write the sensor origin & orientation to the file.
