### ISSUE TITLE
PCL seg fault in multiple modules with specific CPP flags

### ISSUE THREAD

**Issue by Hubert51** [PointCloudLibrary/pcl#5763]
When I turn on the CPP compile flag: 
`set(CMAKE_CXX_FLAGS " -DEIGEN_DONT_VECTORIZE -DEIGEN_MAX_ALIGN_BYTES=0")`
The segmentation fault happens in multiple functions including 
```C++
// downsize pointcloud
pcl::VoxelGrid<pcl::PointXYZ> vox_grid;
vox_grid.setInputCloud (cloud);
vox_grid.setLeafSize (voxel_grid_size, voxel_grid_size, voxel_grid_size);
vox_grid.filter (*tempCloud);
```  
```
pcl::ConcaveHull<pcl::PointXYZ> chull;
chull.setInputCloud(cloud);
chull.reconstruct(*cloud_hull);
```

I tried these functions in pcl-1.10 and pcl-1.13 and different computers. All of them will seg fault if i turn on the CPP flag.

**To Reproduce**

Use any pcd file is ok. Run the above two functions with CPP flag
`set(CMAKE_CXX_FLAGS " -DEIGEN_DONT_VECTORIZE -DEIGEN_MAX_ALIGN_BYTES=0")`. The problem will be reproduced 

**Screenshots/Code snippets**
```
// with CPP flag
load person pcd file
start passthrough
size for tempCloud2: 46700
start downsampling
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

// without CPP flag
load person pcd file
Argument 2: /home/gengr/pcl_learn/cmake-build-debug/person.pcd
start passthrough
size for tempCloud2: 46700
start downsampling
downsize done
size: 7775
size: 1 7775
```

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [GCC 9.4]
 - PCL Version [1.10 and 1.13]

**Possible Solution**

I think we should do some pre-check during using Eigen library

**Comment by larshg** [comment]
Are you compiling your own app with these flags or PCL also?

**Comment by Hubert51** [comment]
Sorry, would you like to clarify the meaning of "app"? Does "app" mean PCL project or my own project?
I compiled my own app(project) with these flags. And I used PCL module in my app. With these two flags, some of PCL code will have seg fault

**Comment by mvieth** [comment]
@Hubert51 If you compile your own project with these flags, but you don't specify the flags when you compile PCL, then you will get these kinds of errors. Your own project and PCL must use the same alignment of Eigen vectors.

**Comment by Hubert51** [comment]
I see! Previously, I used `apt` to install the PCL library. Now I should download the source code and add these definitions in the cmake file, compile, and install. Is this correct?

Thanks very much!

**Comment by Hubert51** [comment]
Oh, another solution from my side, I can add the following line before including pcl header files in the code to avoid segfault
`#undef EIGEN_DONT_VECTORIZE`

**Comment by Hubert51** [comment]
Thanks for helping

**Comment by Hubert51** [comment]
Could you please share some ideas? I attempted to add these two definitions in the CMakeLists.txt file of the PCL library, re-compiled it, and installed it into the system. However, my project continues to experience segfaults, regardless of whether these two definitions are present in my CMakeLists.txt file or not.
