### ISSUE TITLE
How to download pcl::gpu::DeviceArray2D<pcl::FPFHSignature33> to cpu?

### ISSUE THREAD

**Issue by XZRRRRRR** [PointCloudLibrary/pcl#5781]
I try to use pcl::gpu::FPFHEstimation to compute FPFH, but when I use pcl::gpu::DeviceArray2D<pcl::FPFHSignature33> to get the result and try to download it to the cpu, it seemed not run well as my thought.
Here is my code:
`pcl::gpu::DeviceArray2D<pcl::FPFHSignature33> res;
    fe.compute(pc, nm, ids, res);
    std::vector<pcl::FPFHSignature33> re;
    res.download(re);`
and here is the error:
严重性	代码	说明	项目	文件	行	禁止显示状态	详细说明
错误(活动)	E0304	没有与参数列表匹配的 重载函数 "pcl::gpu::DeviceArray2D<T>::download [其中 T=pcl::FPFHSignature33]" 实例	PCL_Test	D:\PCL_Test\PCL_Test\main.cpp	71		参数类型为:  (std::vector<pcl::FPFHSignature33, std::allocator<pcl::FPFHSignature33>>)
            对象类型是:  pcl::gpu::DeviceArray2D<pcl::FPFHSignature33>

**Comment by mvieth** [comment]
@XZRRRRRR Did you have a look at https://github.com/PointCloudLibrary/pcl/blob/master/gpu/features/test/test_fpfh.cpp ?

**Comment by XZRRRRRR** [comment]
> @XZRRRRRR Did you have a look at https://github.com/PointCloudLibrary/pcl/blob/master/gpu/features/test/test_fpfh.cpp ?

Thax for your help! It really solved my problem!
