### ISSUE TITLE
Unable to Open PCD Files and Missing PCD File Option

### ISSUE THREAD

**Issue by szsu123** [PointCloudLibrary/pcl#5784]
Description:
Issue:
I am using CloudCompare version 2.13 and have chosen the basic default options along with additional PCL support during compilation. I have installed PCL and other dependencies using vcpkg, and I am able to successfully call PCL library functions within MainWindow. However, I'm encountering two issues:

When I attempt to open a PCD file, CloudCompare displays the error message: "can't guess file format: unhandled file extension ‘pcd’".
In the "Open" functionality's file filter, I am not able to find the option for PCD files.

windows10 qt5.15.2 msvc2019 x64 cmake3.23.5 cloudcompare2.13 pcl1.13.1

help!

**Comment by mvieth** [comment]
@szsu123 Please contact the CloudCompare maintainers or open an issue on their GitHub repo. This is not a problem caused by PCL.
