### ISSUE TITLE
[compile error] "point_xy.hpp:69:27 { this->template set<0>(v); }"

### ISSUE THREAD

**Issue by eslinan** [PointCloudLibrary/pcl#5789]
compile error
OS: Ubuntu 22.04.3
Compiler: GCC 11.4
pcl: 1.13.1
<img width="540" alt="1692000288153" src="https://github.com/PointCloudLibrary/pcl/assets/4784744/615ba2a6-c142-4418-901b-0a345be5c9f7">

but its ok unser ubuntu20.04.6 and gcc9.4

**Comment by mvieth** [comment]
This is an error in the `geometry` library of Boost, not in PCL.
