### ISSUE TITLE
[compile error] "I successfully compiled the PCL source code using CMake, but when I tried to run the GPU test files, the compilation did not pass."

### ISSUE THREAD

**Issue by wanglei4396** [PointCloudLibrary/pcl#5791]
**Describe the error**

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "void __cdecl pcl::detail::economical_download(struct pcl::gpu::NeighborIndices const &,class std::vector<int,class std::allocator<int> > const &,unsigned __int64,class std::vector<int,class std::allocator<int> > &)" (?economical_download@detail@pcl@@YAXAEBUNeighborIndices@gpu@2@AEBV?$vector@HV?$allocator@H@std@@@std@@_KAEAV56@@Z)，函数 "void __cdecl pcl::gpu::extractEuclideanClusters<struct pcl::PointXYZ>(class std::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZ> > const &,class std::shared_ptr<class pcl::gpu::Octree> const &,float,class std::vector<struct pcl::PointIndices,class std::allocator<struct pcl::PointIndices> > &,unsigned int,unsigned int)" (??$extractEuclideanClusters@UPointXYZ@pcl@@@gpu@pcl@@YAXAEBV?$shared_ptr@V?$PointCloud@UPointXYZ@pcl@@@pcl@@@std@@AEBV?$shared_ptr@VOctree@gpu@pcl@@@3@MAEAV?$vector@UPointIndices@pcl@@V?$allocator@UPointIndices@pcl@@@std@@@3@II@Z) 中引用了该符号	pcl_test1	H:\vs_test\pcl_test\pcl_test1\pcl_test1\main.obj	1	

![image](https://github.com/PointCloudLibrary/pcl/assets/77763561/49628308-0e32-4783-8640-5721483c814e)

 - OS: [ win10]
 - Compiler: [ mvsc 14.2]
 - PCL Version [pcl 1.13, HEAD]
 - PCL Type: [Installed with cmake Compiled from source]
 - CUDA 11.6 GPU3070
 - GPU, Kinfu, CUDA enabled Yes

Thank you for your help

**Comment by wanglei4396** [comment]
1. @mvieth Hello, thank you for your response. I have the **pcl_gpu_segmentation** library.          
![image](https://github.com/PointCloudLibrary/pcl/assets/77763561/ab3ffdc7-cda4-4662-a1a4-e0c5248fc7a3)

2.I have also correctly included it under the library files. I can also successfully navigate to the header file by pressing Ctrl and left-clicking the mouse. The linking error I see states that the linker cannot find the definition of the function named **pcl::detail::economical_download**
![image](https://github.com/PointCloudLibrary/pcl/assets/77763561/f3ffbe92-ea82-455e-9593-4e026bf45492)
The function **economical_download** has been declared, but I haven't found it anywhere else, including in the header files **copy_point.h** and ### gpu_extract_clusters.h.

**Comment by wanglei4396** [comment]
@mvieth It's resolved, seems like it was an error during compilation with CMake.

**Comment by mvieth** [comment]
@wanglei4396 Great that it is resolved. Out of interest, and for anybody who might have the same problem in the future, what did you do to fix the problem?

**Comment by wanglei4396** [comment]
@mvieth 
_#include <pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp>_ 

The function "economical_download" is declared in the file "gpu_extract_clusters.hpp", but I couldn't find its implementation elsewhere. Eventually, I copied the method for this function from the source code into "gpu_extract_clusters.hpp".

Former
![image](https://github.com/PointCloudLibrary/pcl/assets/77763561/21f481d8-8ade-48f2-8c98-bf4faf071f8f)

New
![image](https://github.com/PointCloudLibrary/pcl/assets/77763561/e7703cb2-f3ac-44ef-9e65-86c6df3c608d)

I'm not sure if doing it this way is correct, but it did run successfully.
