### ISSUE TITLE
[PCLVisualizer] Close one of multiply visualizers, Segmentation fault occurred

### ISSUE THREAD

**Issue by jiangzhiwei2018** [PointCloudLibrary/pcl#5794]
**Describe the bug**

I opened 2 visualizers(`vis1`, `vis2`) , the second is opened by keyboard event in a loop but just once.
Then I want to close the second visualizer(`vis2`), the error occurred.

`Segmentation fault (core dumped)`  after pressing `'q'`(or click `x` at top right to cancel)  in the windows`vis2`.
I noticed that the `vis2` could be closed successfully, then the program is terminated when tried to spinOnce `vis1`.

**Screenshots/Code snippets**

Here is my main code for the same feature.

```c++
static char kyboard_ch = ' ';
void
keyboard_callback(const pcl::visualization::KeyboardEvent& event, void*){
  if (event.keyUp()) 
     kyboard_ch = event.getKeyCode();
  
}
int
main (int argc, char **argv)
{
  pcl::visualization::PCLVisualizer visu1("vis1");  // open vis
  visu1.registerKeyboardCallback(&keyboard_callback, nullptr);

  while(true){
  if(kyboard_ch=='a' or kyboard_ch=='A'){
    kyboard_ch = ' '; // to ensure open once
    pcl::visualization::PCLVisualizer visu2("vis2"); // open new vis
    while (!visu2.wasStopped()) visu2.spinOnce(10);
    visu2.close();
  }
  visu1.spinOnce(10);
  }
  return (0);
}
```
**My Environment:**

 - OS:  Ubuntu 20.04
 - Compiler: GCC 9.4.0
 - PCL Version: 1.13.1
 -  VTK Version: 9.2.6

**Possible Solution**
Maby it is caused by `VTK`?

**Additional Text**
I had built `PCL` with `VTK-7.1`, use the same code and action in keyboard, the program would not be terminated, but the `vis2` was still remained in the screen so that I could not close `vis2` successfully.
so I followed [#3959 ](https://github.com/PointCloudLibrary/pcl/issues/3959#issuecomment-1340279993) to update my VTK to 9.2. But got new issue above.

**Comment by mvieth** [comment]
@jiangzhiwei2018 removing `visu2.close();` should fix the issue.

**Comment by jiangzhiwei2018** [comment]
solved 

> @jiangzhiwei2018 removing `visu2.close();` should fix the issue.
