### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for pcl

### ISSUE THREAD

**Issue by wangyuliu** [PointCloudLibrary/pcl#5802]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. As part of my dataset, I have collected the PCL project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be moderate, with a moderate amount of code related to the CPU architecture in the project. It would require a professional team, but not a large-scale one, to handle this task(referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.

**Comment by mvieth** [comment]
Honestly, even if I wanted to help you create your dataset, I would have no idea how to respond. Terms like "moderate", "professional team", "large-scale" are basically meaningless because everyone you ask will have a different idea of difficulty, team size, etc. If you don't use more objective metrics like hours, number of people, lines of code etc, your dataset will not be of much use, in my opinion.
The fact that you opened dozens of issues with seemingly auto-generated text makes this look like spam.

**Comment by wangyuliu** [comment]
> Honestly, even if I wanted to help you create your dataset, I would have no idea how to respond. Terms like "moderate", "professional team", "large-scale" are basically meaningless because everyone you ask will have a different idea of difficulty, team size, etc. If you don't use more objective metrics like hours, number of people, lines of code etc, your dataset will not be of much use, in my opinion. The fact that you opened dozens of issues with seemingly auto-generated text makes this look like spam.


Sorry, maybe I can provide you with some existing classification criteria and basis. Our tool focuses on factors such as architecture-related code.Our tool evaluated these projects and judged them to be of medium complexity: rt-thread, freeRTOS, uC-OS2, zephyr, etc. Projects with high portability complexity include gcc, openCV, binutils-gdb, etc., while projects with low portability complexity are similar to sqlite. Our tool scan found that pcl only has a small amount of architecture-related code, so it is assessed as a simple transplant difficulty. With the above specific classification situation, we invite you to continue to consider the difficulty of pcl transplantation. Do you think the assessment is correct?
