### ISSUE TITLE
[compile error] PCL find Boost but can not find boost_headers while cross compiling

### ISSUE THREAD

**Issue by pla66** [PointCloudLibrary/pcl#5808]
I am cross compiling pcl 1.10.1 in docker for Nvidia Orin Nano. First I cross compile Boost 1.72.0 (the docker container has no boost preinstalled) and other dependencies and installed them, then I run `cmake ..` to compile pcl, but I get this error:

================================================================================================
-- Found Boost 1.72.0 at /usr/local/lib/cmake/Boost-1.72.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;date_time;iostreams;system
CMake Error at /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:122 (find_package):
  Could not find a package configuration file provided by "boost_headers"
  (requested version 1.72.0) with any of the following names:

    boost_headersConfig.cmake
    boost_headers-config.cmake

  Add the installation prefix of "boost_headers" to CMAKE_PREFIX_PATH or set
  "boost_headers_DIR" to a directory containing one of the above files.  If
  "boost_headers" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:160 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  cmake/pcl_find_boost.cmake:38 (find_package)
  CMakeLists.txt:471 (include)

-- Configuring incomplete, errors occurred!

================================================================================================

I think this indicates that the `BoostConfig.cmake` file located in `/usr/local/lib/cmake/Boost-1.72.0/` is found by `find_package(Boost ...)`. However, why can not the cmake find `boost_headers` through `BoostConfig.cmake`? The `boost_headers-config.cmake` file is located in `/usr/local/lib/cmake/boost_headers-1.72.0/`, and the `get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)` in `BoostConfig.cmake` has also specified the file path.

Is there something wrong with my boost configuration?

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 20.04]
 - Compiler: [aarch64-linux-gnu-g++-9]
 - PCL Version [1.10.1] (NB: please ensure you don't have multiple versions available)
 - PCL Type: [Compiled from source]

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? No

**Comment by mvieth** [comment]
@pla66 Can you post the Dockerfile so I can test this myself? Otherwise it is difficult to say whether you may have made a mistake while installing Boost.

**Comment by pla66** [comment]
> @pla66 Can you post the Dockerfile so I can test this myself? Otherwise it is difficult to say whether you may have made a mistake while installing Boost.

Thanks for your reply. Actually, after testing I find out that it is maybe the CMake options that cause this problem. I decide to compile on AGX Orin and copy installation files to Orin Nano and has passed compilation. However, there is another problem about PCLVisualizer occurs, and I will discribe it in a new issue.
