### ISSUE TITLE
[custom] pcl_cuda_filter

### ISSUE THREAD

**Issue by lxh131419** [PointCloudLibrary/pcl#5809]
I try to build pcl with cuda,i find there is no module of pcl_cuda_filter.i really want to know the reason.

**Comment by mvieth** [comment]
That module is very experimental. The CUDA VoxelGrid filter simply does not work, so it is deprecated and will be removed in the future. The CUDA Passthrough filter may be usable, but is still far behind what the normal Passthrough filter can do. If you want to try it out, you can copy the header files to your own project. But as I said, it is experimental and I would not really recommend using it.
