### ISSUE TITLE
[compile error] "POINT_CLOUD_REGISTER_POINT_STRUCT register new type point,not working in octree."

### ISSUE THREAD

**Issue by Freeskylover** [PointCloudLibrary/pcl#5817]
**Describe the error**

POINT_CLOUD_REGISTER_POINT_STRUCT  register new type point,not working in octree.

**Screenshots/Code snippets/Build information**

CMakeFiles/octree_search.dir/octree.cpp.o：在函数‘main’中：
octree.cpp:(.text+0x2d4)：对‘pcl::octree::OctreePointCloud<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::addPointsFromInputCloud()’ 未定义的引用
octree.cpp:(.text+0x37e)：对‘pcl::octree::OctreePointCloudSearch<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::voxelSearch(MyPointType const&, std::vector<int, std::allocator<int> >&)’未定义的引 用
octree.cpp:(.text+0x742)：对‘pcl::octree::OctreePointCloudSearch<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::nearestKSearch(MyPointType const&, int, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&)’未定义的引用
octree.cpp:(.text+0xa76)：对‘pcl::octree::OctreePointCloudSearch<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::radiusSearch(MyPointType const&, double, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, unsigned int) const’未定义的引用
CMakeFiles/octree_search.dir/octree.cpp.o：在函数‘pcl::octree::OctreePointCloudSearch<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::OctreePointCloudSearch(double)’中：
octree.cpp:(.text._ZN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEC2Ed[_ZN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEC5Ed]+0x26)：对‘pcl::octree::OctreePointCloud<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::OctreePointCloud(double)’未定义的引用
CMakeFiles/octree_search.dir/octree.cpp.o：在函数‘pcl::octree::OctreePointCloudSearch<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>::~OctreePointCloudSearch()’中：
octree.cpp:(.text._ZN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEED2Ev[_ZN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEED5Ev]+0x26)：对‘pcl::octree::OctreePointCloud<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::~OctreePointCloud()’未定义的引用
CMakeFiles/octree_search.dir/octree.cpp.o:(.data.rel.ro._ZTVN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE[_ZTVN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE]+0x30)：对‘pcl::octree::OctreePointCloud<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::addPointIdx(int)’未定义的引用
CMakeFiles/octree_search.dir/octree.cpp.o:(.data.rel.ro._ZTVN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE[_ZTVN3pcl6octree22OctreePointCloudSearchI11MyPointTypeNS0_27OctreeContainerPointIndicesENS0_20OctreeContainerEmptyEEE]+0x38)：对‘pcl::octree::OctreePointCloud<MyPointType, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty, pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty> >::genOctreeKeyForDataT(int const&, pcl::octree::OctreeKey&) const’未定义的 引用
collect2: error: ld returned 1 exit status
CMakeFiles/octree_search.dir/build.make:367: recipe for target 'octree_search' failed
make[2]: *** [octree_search] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/octree_search.dir/all' failed
make[1]: *** [CMakeFiles/octree_search.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Freeskylover** [comment]
## test pcl octree demo with register new type point

```c++
#include<pcl/point_cloud.h>
#include<pcl/octree/octree_search.h>
 
#include<iostream>
#include<vector>
#include<ctime>


struct MyPointType    //定义点类型结构
{
    PCL_ADD_POINT4D;  //该点类型有4个元素      

    /*尝试新增一个自定义*/  
    float JoneAdd;    //定义自己新增的类型名称
     //测试了添加这么多个也没问题
    float JoneAdd1;
    float JoneAdd2;
    float JoneAdd3;
    float JoneAdd4;
    float JoneAdd5;
    float JoneAdd6;
    float JoneAdd7;
    float JoneAdd8;
    float JoneAdd9;

    EIGEN_MAKE_ALIGNED_OPERATOR_NEW   //确保new操作符对齐操作 

}EIGEN_ALIGN16;

POINT_CLOUD_REGISTER_POINT_STRUCT(MyPointType,    //注册点类型宏
    (float ,x,x)
    (float ,y,y)
    (float ,z,z)
    (float ,JoneAdd,JoneAdd)
    (float ,JoneAdd,JoneAdd1)
    (float ,JoneAdd,JoneAdd2)
    (float ,JoneAdd,JoneAdd3)
    (float ,JoneAdd,JoneAdd4)
    (float ,JoneAdd,JoneAdd5)
    (float ,JoneAdd,JoneAdd6)
    (float ,JoneAdd,JoneAdd7)
    (float ,JoneAdd,JoneAdd8)
    (float ,JoneAdd,JoneAdd9)
    )

 
using namespace std;
 
int
main(int argc, char** argv)
{
	//使用系统时间做随机数种子
	srand((unsigned int)time(NULL));
	//创建一个PointNormal类型点云指针 pcl::PointNormal
	pcl::PointCloud<MyPointType>::Ptr cloud(new pcl::PointCloud<MyPointType>);
 
	//初始化点云数据
	cloud->width = 1000;//宽为1000
	cloud->height = 1;//高为1，说明为无序点云
	cloud->points.resize(cloud->width * cloud->height);
	//使用随机数填充数据
	for (size_t i = 0; i < cloud->size(); ++i)
	{
		//PointCloud类中对[]操作符进行了重载，返回的是对points的引用
		// (*cloud)[i].x 等同于 cloud->points[i].x
		(*cloud)[i].x = 1024.0f * rand() / (RAND_MAX + 1.0f);
		cloud->points[i].y = 1024.0f * rand() / (RAND_MAX + 1.0f);//推进写法
		cloud->points[i].z = 1024.0f * rand() / (RAND_MAX + 1.0f);//推进写法
	}
 
	//创建八叉树对象
	float resolution = 128.0f;//设置分辨率
	pcl::octree::OctreePointCloudSearch<MyPointType> octree(resolution);
 
 
	//设置点云输入,将在cloud中搜索
	octree.setInputCloud(cloud);
	octree.addPointsFromInputCloud();
 
	//设置被搜索点,用随机数填充
	MyPointType searchPoint;
	searchPoint.x = 1024.0f * rand() / (RAND_MAX + 1.0f);
	searchPoint.y = 1024.0f * rand() / (RAND_MAX + 1.0f);
	searchPoint.z = 1024.0f * rand() / (RAND_MAX + 1.0f);
 
	//体素内近邻搜索
	//使用vector存储搜索结果下标
	vector<int> pointIdxVec;//保存下标
	if (octree.voxelSearch(searchPoint, pointIdxVec))
	{
		cout << "Neighbors within voxel search at (" << searchPoint.x
			<< " " << searchPoint.y
			<< " " << searchPoint.z
			<< ")"
			<< endl;
		for (size_t i = 0; i < pointIdxVec.size(); ++i)
		{
			cout << "    " << cloud->points[pointIdxVec[i]].x
				<< " " << cloud->points[pointIdxVec[i]].x
				<< " " << cloud->points[pointIdxVec[i]].z
				<< endl;
		}
	}
 
	//开始k最近邻搜索
	int K = 10;
	//使用两个vector存储搜索结果
	vector<int> pointIdxNKNSearch(K);//保存下标
	vector<float> pointNKNSquaredDistance(K);//保存距离的平方
 
	cout << "K nearest neighbor search at (" << searchPoint.x
		<< " " << searchPoint.y
		<< " " << searchPoint.z
		<< ") with K = " << K << endl;
 
 
 
	/**
	 * 假设我们的KdTree返回超过0个最近的邻居，
	 * 然后它打印出所有10个离随机searchPoint最近的邻居的位置，
	 * 这些都存储在我们之前创建的vector中。
	 */
	if (octree.nearestKSearch(searchPoint, K, pointIdxNKNSearch, pointNKNSquaredDistance) > 0)
	{
		for (size_t i = 0; i < pointIdxNKNSearch.size(); ++i)
		{
			cout << "    " << cloud->points[pointIdxNKNSearch[i]].x
				<< " " << cloud->points[pointIdxNKNSearch[i]].x
				<< " " << cloud->points[pointIdxNKNSearch[i]].z
				<< "( squared distance: " << pointNKNSquaredDistance[i] << " )" << endl;
		}
	}
 
	//基于半径的邻域搜索
	//搜索结果保存在两个数组中，一个是下标，一个是距离
	vector<int> pointIdxRadiusSearch;
	vector<float> pointRadiusSquaredDistance;
 
	//设置搜索半径，随机值
	float radius = 256.0f* rand() / (RAND_MAX + 1.0f);
 
	cout << "Neighbors within radius search at (" << searchPoint.x
		<< " " << searchPoint.y
		<< " " << searchPoint.z
		<< ") with radius=" << radius << endl;
 
	/**
	 * 如果我们的KdTree在指定的半径内返回超过0个邻居，它将打印出这些存储在向量中的点的坐标。
	 */
	if (octree.radiusSearch(searchPoint, radius, pointIdxRadiusSearch, pointRadiusSquaredDistance) > 0)
	{
		for (size_t i = 0; i < pointIdxRadiusSearch.size(); ++i)
		{
			cout << "    " << cloud->points[pointIdxRadiusSearch[i]].x
				<< " " << cloud->points[pointIdxRadiusSearch[i]].x
				<< " " << cloud->points[pointIdxRadiusSearch[i]].z
				<< "( squared distance: " << pointRadiusSquaredDistance[i] << " )" << endl;
		}
	}
 
	return 0;
}

```

**Comment by Freeskylover** [comment]
i find the problem
add one line in first line
```c++
#define PCL_NO_PRECOMPILE
```

**Comment by mvieth** [comment]
See also here: https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html
