### ISSUE TITLE
[filters] RadiusOulierRemoval uses OrganizedNeighbor on organized but unprojectable point clouds

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5819]
**Describe the bug**

`radius_outlier_removal.h` has such code

```
  // Initialize the search class
  if (!searcher_)
  {
    if (input_->isOrganized ())
      searcher_.reset (new pcl::search::OrganizedNeighbor<PointT> ());
    else
      searcher_.reset (new pcl::search::KdTree<PointT> (false));
  }
```

Which assumes that OrganizedNeighbor can be used with any point cloud that is organized. This is not true, as having non-unity height and width is not a sufficient condition for OrganizedNeighbor to work. Instead the point cloud must be created by a projective device.

`RadiusOutlierRemoval` should check `isValid()` to determine if it can actually be used on the input.

**Context**

When you use `RadiusOutlierRemoval` on an organized cloud from a rotating LIDAR, I have observed it to suddenly take ages, many seconds for operations that would take much less with the kd-Tree. I suspect that is because neither the outlier removal nor the organizedneighbor class check for `isValid()` before searching.

**Expected behavior**

`RadiusOutlierRemoval` figures out correctly if `OrganizedNeighbor` can be used, or exposes parameters to influence it.

**Current Behavior**

`RadiusOutlierRemoval` assumes incorrectly that `height != 1 && width != 1` means a projection matrix can be estimated.

**To Reproduce**

Attempt to filter attached file with radius filter.
[2023-09-07T13_53_58_282Z.pcd.zip](https://github.com/PointCloudLibrary/pcl/files/12683723/2023-09-07T13_53_58_282Z.pcd.zip)

**Your Environment (please complete the following information):**

 - OS: macOS 12.6.5 
 - Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
 - PCL Version 6c23c854389ee891847d1219387ba5639ae6c65f

**Possible Solution**

Maybe leave the decision to the user instead of trying to guess.

**Comment by mvieth** [comment]
Isn't this the same as https://github.com/PointCloudLibrary/pcl/issues/5720 ?
With the PCL commit you are using, you should get a warning like `Input dataset does not seem to be from a projective device!` from OrganizedNeighbor.
Currently, the only option to choose the kdtree would be to set the cloud height to 1, but I am open to the idea of adding a `setSearchMethod` function or similar

**Comment by themightyoarfish** [comment]
I might get a warning, but from what I see, `RadiusOutlierRemoval` does not actually check that the search object is valid.

**Comment by themightyoarfish** [comment]
#5720 is semi-related. The problem there was bad input data, here the cloud is properly organized, but the filter doesn't check if its also projectable.

**Comment by mvieth** [comment]
So in your opinion, the warning is not sufficient and the RadiusOutlierRemoval should refuse to do anything when the search method fails? I guess it could make sense to change `setInputCloud` to return a bool indicating success or failure. Not sure if there is any case for KdTree where a point cloud is not usable.

**Comment by mvieth** [comment]
@themightyoarfish I created a pull request, comments are welcome.
