### ISSUE TITLE
sac_model_cylinder.hpp maybe have a bug  in function projectPointToCylinder { } , shouble be float k = (pt.dot(line_dir) - line_pt.dot(line_dir)) / line_dir.dot(line_dir) ?

### ISSUE THREAD

**Issue by gaishunhua** [PointCloudLibrary/pcl#5820]
https://github.com/PointCloudLibrary/pcl/blob/b5ce8f5ff3f23dcade59c1b78351037cf4bb3f97/sample_consensus/include/pcl/sample_consensus/impl/sac_model_cylinder.hpp#L455

**Comment by larshg** [comment]
Seems right, at least thats how it is here:
https://github.com/PointCloudLibrary/pcl/blob/b5ce8f5ff3f23dcade59c1b78351037cf4bb3f97/sample_consensus/include/pcl/sample_consensus/sac_model_cylinder.h#L267

**Comment by larshg** [comment]
Will you open a PR and perhaps change to use the method from the .h file I linked to.
