### ISSUE TITLE
[compile error] "Unable to compile code with BRISK key point object"

### ISSUE THREAD

**Issue by shyam-botsync** [PointCloudLibrary/pcl#5823]
**Describe the error**

/usr/bin/ld: CMakeFiles/loc_monitor_node.dir/src/perception_pipe.cpp.o: in function `pcl::BriskKeypoint2D<pcl::PointXYZRGBA, pcl::PointWithScale, pcl::common::IntensityFieldAccessor<pcl::PointXYZRGBA> >::detectKeypoints(pcl::PointCloud<pcl::PointWithScale>&)':
/usr/include/pcl-1.10/pcl/keypoints/impl/brisk_2d.hpp:78: undefined reference to `pcl::keypoints::brisk::ScaleSpace::ScaleSpace(int)'
/usr/bin/ld: /usr/include/pcl-1.10/pcl/keypoints/impl/brisk_2d.hpp:79: undefined reference to `pcl::keypoints::brisk::ScaleSpace::constructPyramid(std::vector<unsigned char, std::allocator<unsigned char> > const&, int, int)'
/usr/bin/ld: /usr/include/pcl-1.10/pcl/keypoints/impl/brisk_2d.hpp:81: undefined reference to `pcl::keypoints::brisk::ScaleSpace::getKeypoints(int, std::vector<pcl::PointWithScale, Eigen::aligned_allocator<pcl::PointWithScale> >&)'
/usr/bin/ld: /usr/include/pcl-1.10/pcl/keypoints/impl/brisk_2d.hpp:78: undefined reference to `pcl::keypoints::brisk::ScaleSpace::~ScaleSpace()'
/usr/bin/ld: /usr/include/pcl-1.10/pcl/keypoints/impl/brisk_2d.hpp:78: undefined reference to `pcl::keypoints::brisk::ScaleSpace::~ScaleSpace()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/loc_monitor_node.dir/build.make:245: /home/shiva_uchiha/Documents/development/devel/.private/localization_monitor/lib/localization_monitor/loc_monitor_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:2410: CMakeFiles/loc_monitor_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**To Reproduce**

Just declaring BRISK detector key point object will throw an error .

#include <pcl/keypoints/brisk_2d.h>
 pcl::BriskKeypoint2D<pcl::PointXYZRGBA> brisk;

**Comment by mvieth** [comment]
@shyam-botsync Please post your CMakeLists.txt

**Comment by mvieth** [comment]
@shyam-botsync So apparently you are not calling `find_package(PCL ...)`, you are only relying on the PCL modules you implicitly get via `pcl_conversions` and `pcl_ros`. However, you don't link to the `pcl_keypoints` library this way, which explains the linker errors.
This tutorial will show you the proper way of using PCL in your own project: https://pcl.readthedocs.io/projects/tutorials/en/master/using_pcl_pcl_config.html
