### ISSUE TITLE
using Conditional Euclidean Clustering compile error

### ISSUE THREAD

**Issue by up-to-data** [PointCloudLibrary/pcl#5828]
Hello:
I'm recently referde to tutorial,
and using Conditional Euclidean Clustering compile code with the following  error

错误	LNK2001	无法解析的外部符号 "protected: virtual void __cdecl pcl::NormalEstimation<struct pcl::PointXYZI,struct pcl::PointXYZINormal>::computeFeature(class pcl::PointCloud<struct pcl::PointXYZINormal> &)" (?computeFeature@?$NormalEstimation@UPointXYZI@pcl@@UPointXYZINormal@2@@pcl@@MEAAXAEAV?$PointCloud@UPointXYZINormal@pcl@@@2@@Z)	
错误	LNK2019	无法解析的外部符号 "public: void __cdecl pcl::ConditionalEuclideanClustering<struct pcl::PointXYZINormal>::segment(class std::vector<struct pcl::PointIndices,class std::allocator<struct pcl::PointIndices> > &)" (?segment@?$ConditionalEuclideanClustering@UPointXYZINormal@pcl@@@pcl@@QEAAXAEAV?$vector@UPointIndices@pcl@@V?$allocator@UPointIndices@pcl@@@std@@@std@@@Z)

I am  using windows 11 local machine and building it on VS2022 and pcl 1.13.1.

**Comment by mvieth** [comment]
If you are using the all-in-one installer, add `#define PCL_NO_PRECOMPILE` before including any PCL headers.

**Comment by up-to-data** [comment]
Thanks for  your responed.
I am added it.
As a result,a new problem has arisen with following error
错误	C3861	“pop_t”: 找不到标识符	
错误	C2065	“pop_t”: 未声明的标识符		
What should I do ,please

**Comment by mvieth** [comment]
This is a problem in FLANN, see these issues:
- https://github.com/PointCloudLibrary/pcl/issues/4864
- https://github.com/flann-lib/flann/issues/386

**Comment by up-to-data** [comment]
I really appreciate your help.
I have successful solved the promblem.

**Comment by mvieth** [comment]
Great!
