### ISSUE TITLE
How to calculate curvature of a point cloud using pcl functions

### ISSUE THREAD

**Issue by PhuongNDVN** [PointCloudLibrary/pcl#5835]
I would like to calculate the curvature as described in here:
http://pointclouds.org/documentation/group__features.html

The curvature value should be the smallest eigenvalue divided by sum of all eigenvalues. However, when I check the function pcl::PrincipalCurvaturesEstimation(), it returns only value of min and max eigenvalues. How can I get all 3 eigenvalues to calculate the curvature value?

The decription of the pcl::PrincipalCurvaturesEstimation() is here:
http://pointclouds.org/documentation/classpcl_1_1_principal_curvatures_estimation.html#aa6051f3fa8fec96516c6236fd3f3b6bc

**Comment by mvieth** [comment]
`NormalEstimation` and `NormalEstimationOMP` should do what you want. In addition to the normal, they also compute the curvature.
In the future, please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
