### ISSUE TITLE
createFromPointCloud performs slow when using RangeImageSpherical

### ISSUE THREAD

**Issue by YuBoaKai** [PointCloudLibrary/pcl#5837]
I created a rangeImage like in your tutorial with my own Lidar +RGB Camera [pcl](https://github.com/PointCloudLibrary/pcl/tree/master)/[doc](https://github.com/PointCloudLibrary/pcl/tree/master/doc)/[tutorials](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials)/[content](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content)/[sources](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources)/[range_image_creation](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources/range_image_creation)
/range_image_creation.cpp using pcl::RangeImage::createFromPointCloud()

Since my LiDAR captures 360° view I started to use RangeImageSpherical instead of the baseclass RangeImage as suggested in the docs. After createFromPointCloud() my code is running almost 10x slower then before. This also happens with the self created pointcloud from the above mentioned tutorial example, which creates a bottlneck for me when I want to process my data in real time.  I am currently using pcl 1.10.

**Comment by mvieth** [comment]
I am not sure I fully understand the problem. Which code runs slower? `createFromPointCloud()`? Perhaps the problem will be clearer if you post some of your code.
My best guess right now is that you experience the difference between organized and unorganized point clouds. Organized clouds (more precisely: organized and projectable clouds) can use a special search algorithm (https://pointclouds.org/documentation/classpcl_1_1search_1_1_organized_neighbor.html) that is faster. An easy rule of thumb: if you check the height and width of a point cloud and either of them is 1, then the cloud is unorganized and the fast search algorithm can't be used.

**Comment by YuBoaKai** [comment]
Thanks for your quick answer. As an example I can produce my problem with the tutorial code snippet from [pcl](https://github.com/PointCloudLibrary/pcl/tree/master)/[doc](https://github.com/PointCloudLibrary/pcl/tree/master/doc)/[tutorials](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials)/[content](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content)/[sources](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources)/[range_image_creation](https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content/sources/range_image_creation):

```ruby
#include <pcl/range_image/range_image.h>

int main () {
  pcl::PointCloud<pcl::PointXYZ> pointCloud;
  
  // Generate the data
  for (float y=-0.5f; y<=0.5f; y+=0.01f) {
    for (float z=-0.5f; z<=0.5f; z+=0.01f) {
      pcl::PointXYZ point;
      point.x = 2.0f - y;
      point.y = y;
      point.z = z;
      pointCloud.push_back(point);
    }
  }
  pointCloud.width = pointCloud.size();
  pointCloud.height = 1;
  
  // We now want to create a range image from the above point cloud, with a 1deg angular resolution
  float angularResolution = (float) (  1.0f * (M_PI/180.0f));  //   1.0 degree in radians
  float maxAngleWidth     = (float) (360.0f * (M_PI/180.0f));  // 360.0 degree in radians
  float maxAngleHeight    = (float) (180.0f * (M_PI/180.0f));  // 180.0 degree in radians
  Eigen::Affine3f sensorPose = (Eigen::Affine3f)Eigen::Translation3f(0.0f, 0.0f, 0.0f);
  pcl::RangeImage::CoordinateFrame coordinate_frame = pcl::RangeImage::CAMERA_FRAME;
  float noiseLevel=0.00;
  float minRange = 0.0f;
  int borderSize = 1;
  
  pcl::RangeImage rangeImage;
  rangeImage.createFromPointCloud(pointCloud, angularResolution, maxAngleWidth, maxAngleHeight,
                                  sensorPose, coordinate_frame, noiseLevel, minRange, borderSize);
  
  std::cout << rangeImage << "\n";
}
```
when  changing  pcl::RangeImage rangeImage; to  pcl::RangeImageSpherical rangeImage; on line: https://github.com/PointCloudLibrary/pcl/blob/69e645c94686ec42a4b9891412921f77a9e83e8a/doc/tutorials/content/sources/range_image_creation/range_image_creation.cpp#L29. For me the code runs 5-10x slower then.

**Comment by mvieth** [comment]
So
```cpp
pcl::RangeImageSpherical rangeImageSpherical;
rangeImageSpherical.createFromPointCloud(pointCloud, angularResolution, maxAngleWidth, maxAngleHeight,
                                  sensorPose, coordinate_frame, noiseLevel, minRange, borderSize);
```
is much slower than
```cpp
pcl::RangeImage rangeImage;
rangeImage.createFromPointCloud(pointCloud, angularResolution, maxAngleWidth, maxAngleHeight,
                                  sensorPose, coordinate_frame, noiseLevel, minRange, borderSize);
```
? Is that the problem?

**Comment by YuBoaKai** [comment]
Yes, for me it is.

**Comment by mvieth** [comment]
Do you enable compiler optimizations in your own project? For example by adding compiler flags or setting the cmake build type?

**Comment by mvieth** [comment]
@YuBoaKai If I don't hear from you, I am going to assume that my last comment solved the problem, and close this issue soon.
