### ISSUE TITLE
where is the PhD thesis of “Fitting trimmed B-splines to unordered point clouds”

### ISSUE THREAD

**Issue by linbeijianbaoxia** [PointCloudLibrary/pcl#5841]
I would like to understand the theoretical background of the post: 'Fitting trimmed B-splines to unordered point clouds'. However, I can't open the link to the author's PhD thesis. Can you send it to me or tell me the title of the thesis? Thank you very much!

**Comment by mvieth** [comment]
This seems to be the thesis:
https://repositum.tuwien.at/handle/20.500.12708/9435

**Comment by linbeijianbaoxia** [comment]
> This seems to be the thesis: https://repositum.tuwien.at/handle/20.500.12708/9435

Thanks very much!!!
