### ISSUE TITLE
[compile error] error: ISO C++ prohibits anonymous structs [-Werror=pedantic]

### ISSUE THREAD

**Issue by jieunko** [PointCloudLibrary/pcl#5864]
Operating System and version: Ubuntu 20.04 (Jetpack 5.1.1)
Compiler: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1-20.04.1)
PCL Version: 1.10
ROS : Galactic

I am facing the same anonymous struct error while building pointcloud_preprocessor package in autoware as described in issue:2303. 
https://github.com/PointCloudLibrary/pcl/issues/2303

However, I could not solve the issue with the solution in the link.
Is there anyone who solved the issue?
Any advice will be grateful
Thanks.

**Comment by mvieth** [comment]
@jieunko What have you tried exactly? Please show your CMakeLists.txt

**Comment by larshg** [comment]
Closing as no response.
