### ISSUE TITLE
SVD in Feature-Based Point Cloud Registration

### ISSUE THREAD

**Issue by drathin4** [PointCloudLibrary/pcl#5866]
I'm working on the `point cloud registration` problem and I'm using `feature-based` approach for `initial alignment`. I found many public GitHub repos as well as PCL tutorials stating the workflow in which they're using **SVD** for `transform estimation`. But a major limitation of SVD is that the source and target size needs to be identical. In the feature-based approach, we compute the `keypoints` which in general cannot necessarily be equal in size for source and target. I'm aware that **SAC-IA** can be a potential alternative for **SVD** in feature-based registration, but my question is regarding SVD itself. Is there any specific reason that SVD is recommended everywhere? Also, is there any other alternative to **SAC-IA/SVD** for initial alignment? I'm intentionally not using **NDT/ICP** there.

Also, I'd like to point out that my point-cloud data-sets are far too complex than the typical data-sets used in examples and keypoints are never equal in size.

**Comment by mvieth** [comment]
PCL offers `FPCSInitialAlignment`, `KFPCSInitialAlignment`, `SampleConsensusInitialAlignment`, `SampleConsensusPrerejective`, and `PPFRegistration` for initial alignment. I am pretty sure that they all work even if source and target don't have the same number of points/features. Usually, SVD is performed with a small subset of the points.
In the future, please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
