### ISSUE TITLE
[custom] Linking error due to pcl::registration::CorrespondenceRejectorSurfaceNormal::getRemainingCorrespondences

### ISSUE THREAD

**Issue by drathin4** [PointCloudLibrary/pcl#5870]
Since this is a `linking error`, I've not included it in the category of `compilation error`. I'm using `PCL-1.13.0#3` using `VCPkg-x64-windows`
I'm pasting the error below which is specifically for `CorrespondenceRejectorSurfaceNormal` class, but the same is applicable for some other CorrespondenceRejector classes as well.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual void __cdecl pcl::registration::CorrespondenceRejectorSurfaceNormal::getRemainingCorrespondences(class std::vector<struct pcl::Correspondence,class Eigen::aligned_allocator<struct pcl::Correspondence> > const &,class std::vector<struct pcl::Correspondence,class Eigen::aligned_allocator<struct pcl::Correspondence> > &)" (?getRemainingCorrespondences@CorrespondenceRejectorSurfaceNormal@registration@pcl@@UEAAXAEBV?$vector@UCorrespondence@pcl@@V?$aligned_allocator@UCorrespondence@pcl@@@Eigen@@@std@@AEAV45@@Z)	point_cloud_registration	D:\OneDrive - Neilsoft\Scan2BIM\scan2bim_point_cloud_registration\build\registration.obj	1	

I want to use the correspondence rejector classes viz. `CorrespondenceRejectorSurfaceNormal, CorrespondenceRejectorTrimmed, CorrespondenceRejectorFeatures`, but I can't use any of them because the class method `getRemainingCorrespondences` is not overridden in any of the classes. The implementation *.hpp files of many correspondence rejectors seem to be deprecated and contains the function macro `PCL_DEPRECATED_HEADER(1, 15, "")`. Does it mean that these classes are deprecated? Or is there any other workaround?

**Comment by mvieth** [comment]
If a .hpp file contains the deprecation macro, then it doesn't mean that the class is deprecated, only that the .hpp is empty and you don't need to include it. The implementation then will either be in the .h file or the .cpp file.
The problem in your case is most likely that you don't link to the pcl_registration library. Please check that you do that (if in doubt, post your CMakeLists.txt)

**Comment by drathin4** [comment]
Thanks for your help. I included `registration` module in CMakeLists.txt and that solved the problem.
