### ISSUE TITLE
[common/transform] Fail of transformPointCloud for empty pointcloud

### ISSUE THREAD

**Issue by julia-sanchez-kitware** [PointCloudLibrary/pcl#5871]
**Describe the bug**

When using transformPointCloud OUT-of-place with an empty input cloud, and **copy_all_fields** to true (default behavior), it causes a segfault.
This seems caused by the assign function [here](https://github.com/PointCloudLibrary/pcl/blob/19a8221648576a17115f8ac9dbbb0d67f8c4b402/common/include/pcl/common/impl/transforms.hpp#L232C17-L232C23).

**Context**

I am trying to transform a pointcloud and put the output into a new pointcloud.

**Expected behavior**

When transforming a pointcloud of 0 point, the output should be a pointcloud with 0 point. The behavior inplace/out-of-place should be similar.

**Current Behavior**

Segfault

**To Reproduce**

pcl::PointCloud<pcl::PointXYZ> pcIn, pcOut;
pcl::transformPointCloud(pcIn, pcOut, Eigen::Isometry3d::Identity().matrix());

**My environment**

 - OS: [Ubuntu 22.04]
 - Compiler: [GCC 11.4]
 - PCL Version [1.12]

**Possible Solution**

Check if pointcloud is empty [here](https://github.com/PointCloudLibrary/pcl/blob/19a8221648576a17115f8ac9dbbb0d67f8c4b402/common/include/pcl/common/impl/transforms.hpp#L231).

**Comment by mvieth** [comment]
@julia-sanchez-kitware Hi, thank you for reporting this. The two lines you posted for reproducing did not cause any problem or segfault for me (I tested with GCC 13 and the current master branch). I believe that this problem was fixed by https://github.com/PointCloudLibrary/pcl/commit/c1835f442dde8a7567381388f19d6d05ad9d5a83 Could you test again with PCL 1.13, please?

**Comment by mvieth** [comment]
@julia-sanchez-kitware I just tested by undoing the changes from https://github.com/PointCloudLibrary/pcl/commit/c1835f442dde8a7567381388f19d6d05ad9d5a83 : then I get `Floating point exception (core dumped)`. I assume that is the error you also saw? So I am confident that this error does not occur any more in PCL 1.13.0 and newer. If you still have any doubts, feel free to comment/reopen this issue/open a new issue.

**Comment by Danendra10** [comment]
HI! @mvieth 

I got the same probelm with pcl::transformPointCloud. I have the same OS, compiler and PCL Version. I get SEGFPE error. Is it possible to update the pcl to version 1.13 with the same OS version without braking anything? Becasue right now, my system depends on Ubuntu 22.04

**Comment by mvieth** [comment]
@Danendra10 You could uninstall PCL and then compile it from source: https://pcl.readthedocs.io/projects/tutorials/en/master/compiling_pcl_posix.html
