### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for PCL

### ISSUE THREAD

**Issue by wangyuliu** [PointCloudLibrary/pcl#5875]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **pcl** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be moderate leaning towards simple, with a moderate amount of code related to the CPU architecture in the project.  Is this assessment accurate?Do you often have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by mvieth** [comment]
This again? I already gave an answer
https://github.com/PointCloudLibrary/pcl/issues/5802#issuecomment-1712447039
