### ISSUE TITLE
Using pcl::NormalEstimation, but i got something wrong!

### ISSUE THREAD

**Issue by BarryLoveBerry** [PointCloudLibrary/pcl#5877]
Hi all,

Here is my source code as below:
  pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normal_estimation;
  normal_estimation.setInputCloud(cloud);
  pcl::PointCloud<pcl::Normal>::Ptr cloud_normals(new pcl::PointCloud<pcl::Normal>);
  pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
  normal_estimation.setSearchMethod(tree);
  normal_estimation.setRadiusSearch(0.04);  
  normal_estimation.compute(*cloud_normals);

When I make compilation, I got the wrong info like this:
/usr/bin/ld: CMakeFiles/pcd_histogram.dir/normals.cpp.o:(.data.rel.ro._ZTVN3pcl16NormalEstimationINS_8PointXYZENS_6NormalEEE[_ZTVN3pcl16NormalEstimationINS_8PointXYZENS_6NormalEEE]+0x58): undefined reference to `pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal>::computeFeature(pcl::PointCloud<pcl::Normal>&)'
collect2: error: ld returned 1 exit status

It looks like that pcl::NormalEstimation::computeFeature function is undefined. Is there someone have this issue before?

**Comment by BarryLoveBerry** [comment]
I am curious about why I can't use the pcl::NormalEstimation::compute?

**Comment by mvieth** [comment]
@BarryLoveBerry Please show your CMakeLists.txt

**Comment by BarryLoveBerry** [comment]
> @BarryLoveBerry Please show your CMakeLists.txt

cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(PCD_Histogram)

find_package(PCL REQUIRED)
find_package(VTK REQUIRED)


include_directories(${PCL_INCLUDE_DIRS} 
                    ${VTK_INCLUDE_DIRS} 
)
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(pcd_histogram normals.cpp)
target_link_libraries(pcd_histogram ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES} ${PCL_VISUALIZATION_LIBRARIES} ${VTK_LIBRARIES})

**Comment by larshg** [comment]
PCL_COMMON_LIBRARIES and the others you have added doesn't exist.

Try it like this:

```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR) project(PCD_Histogram)

find_package(PCL REQUIRED)

include_directories(${PCL_INCLUDE_DIRS}) 
link_directories(${PCL_LIBRARY_DIRS}) 
add_definitions(${PCL_DEFINITIONS})
 
add_executable(pcd_histogram normals.cpp)
target_link_libraries(pcd_histogram ${PCL_LIBRARIES})


```

**Comment by BarryLoveBerry** [comment]
> PCL_COMMON_LIBRARIES and the others you have added doesn't exist.
> 
> Try it like this:
> 
> ```
> cmake_minimum_required(VERSION 3.0 FATAL_ERROR) project(PCD_Histogram)
> 
> find_package(PCL REQUIRED)
> 
> include_directories(${PCL_INCLUDE_DIRS}) 
> link_directories(${PCL_LIBRARY_DIRS}) 
> add_definitions(${PCL_DEFINITIONS})
>  
> add_executable(pcd_histogram normals.cpp)
> target_link_libraries(pcd_histogram ${PCL_LIBRARIES})
> ```

I see, It works! thanks a lot.

**Comment by larshg** [comment]
Great, thanks for the feedback!
