### ISSUE TITLE
Integrating PCL Visualizer in MFC/win32 window.

### ISSUE THREAD

**Issue by zirid** [PointCloudLibrary/pcl#5887]
I am trying to use the PCL Visializer as it is inside an MFC CStatic control : 

```
pcl::visualization::PCLVisualizer::Ptr simpleVis(pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud , HWND hParent_display )
{
	// --------------------------------------------
	// -----Open 3D viewer and add point cloud-----
	// --------------------------------------------
	pcl::visualization::PCLVisualizer::Ptr viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
	
	if (hParent_display) {
		
		SetParent((HWND)viewer->getRenderWindow()->GetGenericWindowId(), hParent_display);

		viewer->setWindowBorders(false);
		viewer->getRenderWindow()->SetParentId(hParent_display);

		//viewer->setPosition(-10, -50);  // Hacky way to hide the window borders

		viewer->setBackgroundColor(0, 0, 0);
		viewer->addPointCloud<pcl::PointXYZ>(cloud, "sample cloud");
		viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, "sample cloud");
		viewer->addCoordinateSystem(1.0);
		viewer->initCameraParameters();

	}

	return (viewer);
}
```
I call the above function in MFC` OnInitDialog()` like this :  

viewer = simpleVis(basic_cloud_ptr , GetDlgItem(IDC_STATIC_3D_VIWER)->m_hWnd);

and this is the result : 

![PCL_VIZ](https://github.com/PointCloudLibrary/pcl/assets/31682698/5bd6b143-43be-4778-8f31-5a0c03d8bddf)

As you can see the child window title bar is visible and the user can move it using a mouse.

![PCL_VIZ3](https://github.com/PointCloudLibrary/pcl/assets/31682698/eae25ad7-341c-4a77-8601-f99615d095f1)

`viewer->setWindowBorders(false);` didn't work. 
Using `viewer->setPosition(-10, -50);  `  hides the title bar but I am not sure if this is the proper way to achieve that.

![PCL_VIZ2](https://github.com/PointCloudLibrary/pcl/assets/31682698/b072a4ff-1a66-4969-9954-6620589efad8)

Is there a better way to integrate the Visualizer?

**Comment by mvieth** [comment]
Maybe this tutorial is helpful to you: https://pcl.readthedocs.io/projects/tutorials/en/master/qt_visualizer.html
I would also recommend to look into how VTK and MFC can be combined because the PCL Visualizer is based on VTK.
Lastly, you can also ask on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community). Perhaps someone there has experience with this.
