### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by CachCheng** [PointCloudLibrary/pcl#5888]
[ 31%] Linking CXX executable ../bin/pcl_tiff2pcd
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/[libSM.so](http://libsm.so/)：对‘uuid_generate@UUID_1.0’未定义的引用
/home/cash/anaconda3/lib/libfontconfig.so.1：对‘FT_Done_MM_Var’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/[libSM.so](http://libsm.so/)：对‘uuid_unparse_lower@UUID_1.0’未定义的引用
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_tiff2pcd.dir/build.make:287: recipe for target 'bin/pcl_tiff2pcd' failed
make[2]: *** [bin/pcl_tiff2pcd] Error 1
CMakeFiles/Makefile2:3692: recipe for target 'tools/CMakeFiles/pcl_tiff2pcd.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_tiff2pcd.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 31%] Linking CXX executable ../bin/pcl_ply2vtk
[ 31%] Built target pcl_ply2vtk
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mvieth** [comment]
Try `sudo apt install uuid-dev` (if you are on Ubuntu, otherwise use the appropriate install command and package name for your distribution)

**Comment by kingyongyongzz** [comment]
sudo apt install uuid-dev
then：
uuid-dev  (2.31.1-0.4ubuntu3.7)。
but still couldn't work
