### ISSUE TITLE
Memory leak when using pcl visualizer with MFC  (VS2022).

### ISSUE THREAD

**Issue by zirid** [PointCloudLibrary/pcl#5890]
**Describe the bug**

- Visual studio reports memory leak when adding: `#include <pcl/visualization/pcl_visualizer.h>` to the project.

  (just adding the header and running the application gives memory leak)

```
Detected memory leaks!
Dumping objects ->
{900} normal block at 0x000002AE992B26F0, 16 bytes long.
 Data: <0 +             > 30 87 2B 99 AE 02 00 00 00 00 00 00 00 00 00 00 
{896} normal block at 0x000002AE992B2B50, 16 bytes long.
 Data: < H+             > A0 48 2B 99 AE 02 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
```
- Intel inspector points to 	`vtkcommoncore-9.2d.dll`

**Context**

PCL was installed using vcpkg (x64-windows) .  the lib is linked with MFC Shared dll  (Debug version) 

**Expected behavior**

The application should exit without memory leaks.

**To Reproduce**

1) install pcl using vcpkg on windows .
2) create MFC shared dll project and link pcl lib.
3) Add `#include <pcl/visualization/pcl_visualizer.h>` header.
4) Run the application in debug mode.
5) Close the application.
6) check the output.

**Screenshots/Code snippets**

(intel inspector)
![mem_leak](https://github.com/PointCloudLibrary/pcl/assets/31682698/472d1c79-a9e4-46cf-ba87-8c433a5698bd)

**Your Environment (please complete the following information):**

 - OS: Win 10
 - Compiler: MSVC - VS2022
 - PCL Version : vcpkg  (x64-windows)

**Comment by mvieth** [comment]
If you say that the leak happens in vtkcommoncore-9.2d.dll, then we can't do anything on the PCL side. Please open an issue at https://gitlab.kitware.com/vtk/vtk/-/issues
