### ISSUE TITLE
[kdtree] ctypes call a function that use kdtree's setInputCloud function, found Segmentation fault

### ISSUE THREAD

**Issue by mujiubai** [PointCloudLibrary/pcl#5895]
**Describe the bug**
I use ctypes call a function A, and the function A call a function B. Function B create a kdtree, but found Segmentation fault when use setInputCloud function.
It's correct when use c++ call function A, but use ctypes is error (even if no parameters are passed), all the function A code is not change. 
I try to use python create kdtree by pclpy, but found same problem. 

**Context**

the code is want to create kdtree, but segmentation falut is fount when run setInputCloud  function. 
I confirmed the problem with this code by printing logs.
`	pcl::KdTreeFLANN<pcl::PointXYZ> kdtree;
	kdtree.setInputCloud(cloud);`

**Expected behavior**

no Segmentation fault

**Current Behavior**

found Segmentation fault

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 18.04]
 - Compiler: [GCC 7.5.0]
 - PCL Version [1.8.1 or 1.10.0]

**Comment by mvieth** [comment]
We do not offer any support for using PCL from python.
python-pcl, pclpy, and the like are separate projects and not maintained by us.
You can try asking on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) , but I can't guarantee that anyone there will have experience with this problem.
