### ISSUE TITLE
When my code creates ppf features, it cannot continue until ".compute" is reached.

### ISSUE THREAD

**Issue by WJunlan** [PointCloudLibrary/pcl#5916]
**Describe the error**
No compilation errors and can be generated successfully, but the execution has no response, as shown below
![image](https://github.com/PointCloudLibrary/pcl/assets/155532737/2dfde603-013a-443f-9f65-7463e65a3256)

**Screenshots/Code snippets/Build information**

    PointCloud<PointNormal>::Ptr cloud_model_input(new PointCloud<PointNormal>());
    PointCloud<PointXYZ>::Ptr cloud_model_subsampled(new PointCloud<PointXYZ>());
    VoxelGrid<PointXYZ> subsampling_filter2;
    subsampling_filter2.setInputCloud(cloud_model);
    subsampling_filter2.setLeafSize(subsampling_leaf_size);
    subsampling_filter2.filter(*cloud_model_subsampled);
    PointCloud<Normal>::Ptr cloud_model_normals(new PointCloud<Normal>());
    NormalEstimation<PointXYZ, Normal> normal_estimation_filter2;
    normal_estimation_filter2.setInputCloud(cloud_model_subsampled);
    //search::KdTree<PointXYZ>::Ptr search_tree2(new search::KdTree<PointXYZ>);
    //normal_estimation_filter2.setSearchMethod(search_tree2);
    normal_estimation_filter2.setRadiusSearch(normal_estimation_search_radius);
    normal_estimation_filter2.compute(*cloud_model_normals);
    pcl::concatenateFields(*cloud_model_subsampled, *cloud_model_normals, *cloud_model_input);

    cout << cloud_model->size() << " down to" << cloud_model_subsampled->size() << endl;

    PointCloud<PPFSignature>::Ptr cloud_model_ppf(new PointCloud<PPFSignature>());
    PPFEstimation<PointNormal, PointNormal, PPFSignature> ppf_estimator;
    ppf_estimator.setInputCloud(cloud_model_input);
    ppf_estimator.setInputNormals(cloud_model_input);
    PCL_INFO("aa");
    ppf_estimator.compute(*cloud_model_ppf); //卡在这
    PCL_INFO("bb");

![image](https://github.com/PointCloudLibrary/pcl/assets/155532737/43ed1886-a183-4b9d-9f6a-722712514fa0)

When I debug step by step, the following prompt appears midway
![image](https://github.com/PointCloudLibrary/pcl/assets/155532737/9aeb99e1-202c-47b0-afba-21ef8c88a9c3)
I can't find the cause of the problem and hope I can get a solution，Is there something wrong with my property configuration?
**Your Environment (please complete the following information):**

 - OS: [e.g. Windows Visual Studio2022]
 - PCL Version [e.g. 1.13.1, HEAD] (NB: please ensure you don't have multiple versions available)
 - PCL Type:Follow the tutorial to complete the property configuration
 - 
![image](https://github.com/PointCloudLibrary/pcl/assets/155532737/e536f758-e77e-4a02-883e-11d3907e61d0)

If compiling against PCL:
 - Checked `CMakeLists.txt` for simple errors like missing `find_package` or `target_link_libraries`?
  * [CMakeLists.txt for PCL >= 1.9](https://github.com/kunaltyagi/pcl-cmake-minimum/blob/master/CMakeLists.txt)
  * [CMakeLists.txt for older versions](https://github.com/PointCloudLibrary/pcl/blob/update-issue-templates/doc/tutorials/content/sources/concatenate_clouds/CMakeLists.txt)

**Possible Solution**

Not obligatory, but suggest a fix/reason for the bug. Feel free to create a PR if you feel comfortable.

**Additional context**

**Comment by WJunlan** [comment]
I'm sorry I didn't notice the Chinese display problem with the interface，I have been waiting for a long time, maybe five to ten minutes, I believe that the 2749 size point cloud does not need to be calculated for so long，The following is the English interface：
![image](https://github.com/PointCloudLibrary/pcl/assets/155532737/f7385bdf-dbbb-4943-8792-ea26b2009d0c)

**Comment by mvieth** [comment]
@WJunlan Any news? Did my suggestion help you? Can I close this issue?

**Comment by WJunlan** [comment]
The problem has been solved, it's just a matter of time, thank you for your help
