### ISSUE TITLE
I am using PCL for my Master's thesis. I am trying to use frustum culling on a point cloud data and trying to identify visible and occluded/not visible points. I am not getting the correct output and not sure how should I debug this.

### ISSUE THREAD

**Issue by Heavy0strich** [PointCloudLibrary/pcl#5919]
I have defined a viewpoint class, which basically stores the camera position, direction, and point cloud visible and occluded from the position in space. Since I know where the camera is, which direction it is pointing, and the camera up vector, I find the camera pose using the following:

```
void ViewPoint::setPose(){
    camera_pose = Eigen::Matrix4f::Identity();
    
    Eigen::Matrix3f R = Eigen::Matrix3f::Identity();

    Eigen::Vector3f world_x(1.0f, 0.0f, 0.0f);
    Eigen::Vector3f world_y(0.0f, 1.0f, 0.0f);
    Eigen::Vector3f world_z(0.0f, 0.0f, 1.0f);

    Eigen::Vector3f view = point2vector(direction).normalized();       //forward
    Eigen::Vector3f up = world_z;                                    // up
    Eigen::Vector3f right = (view.cross(up)).normalized();          //right                                    //(world_x.cross(cam_x)).normalized();        //up       
    
    camera_pose.block<3, 1>(0, 0) = view;
    camera_pose.block<3, 1>(0, 1) = up;
    camera_pose.block<3, 1>(0, 2) = right;
    camera_pose.block<3, 1>(0, 3) = point2vector(position);
}
```

**My Output**
![image](https://github.com/PointCloudLibrary/pcl/assets/67595567/68f6582c-f21a-4082-a47a-d3d51f022540)

The red colored cloud in the image is the visible portion(inside the view frustum(drawn with red lines)) and blue is occluded/not visible portion. 

My code for getting visible cloud from a set of defined viewpoints:

```
void getvisibleCloud(std::vector<ViewPoint *>& viewpoints, pcl::PointCloud<pcl::PointXYZ>::ConstPtr cloud){
    
    // Frustum culling to get indices of points that are in the viewfrustum of the camera
    std::cout<<"Frustum Culling..."<<std::endl;
    pcl::FrustumCulling<pcl::PointXYZ> fc;

    
    pcl::IndicesPtr visibleIndices(new std::vector<int>);
    pcl::IndicesPtr occludedIndices(new std::vector<int>);
    pcl::PointIndices::Ptr visibleIndicesPtr(new pcl::PointIndices);
    //pcl::Indices occludedIndices;

    pcl::octree::OctreePointCloudSearch<pcl::PointXYZ> octree(1.2f);
    octree.setInputCloud(cloud);
    octree.addPointsFromInputCloud();

    fc.setInputCloud(cloud);
    
    std::cout<<"ViewPoint size inside getvisibleCloud: "<<viewpoints.size()<<std::endl;     // Displays Number of points inside view frustum of the camera
    float distanceFromOrigin = 0.0f;
    

    for(int i = 0; i < viewpoints.size(); ++i){
        
        ViewPoint *vp = viewpoints[i];

        pcl::PointCloud<pcl::PointXYZ> FrustumCulledCloud;
        pcl::Indices frustumCulledIndices;
        std::cout<<"Evaluating for View Point:  "<<vp->position<<std::endl;

        fc.setVerticalFOV(vp->cam.v_FOV);
        fc.setHorizontalFOV(vp->cam.h_FOV);
        fc.setNearPlaneDistance(vp->cam.near_plane);
        fc.setFarPlaneDistance(vp->cam.far_plane);
        fc.setCameraPose(vp->camera_pose);
        
        //fc.filter(FrustumCulledCloud);
        fc.filter(frustumCulledIndices);
        std::vector<int> visibleIndicestemp;                             //private to each thread
        
        std::cout<<"No. of Points in the View Frustum(from FrustumCulledIndices): "<<frustumCulledIndices.size()<<std::endl;

        // Occlusion culling on the points inside the viewfrustum of the camera to get indices of points that are occluded by other points 
        
        pcl::PointXYZ ray = getDirection2(vp->position, cloud->points[0]);
        
        for(auto &id: frustumCulledIndices){
            
            pcl::PointXYZ point(cloud->points[id].x, cloud->points[id].y, cloud->points[id].z);
            pcl::Indices intersectedrayindices;
            Eigen::Vector3f origin = point2vector(vp->position);
            Eigen::Vector3f ray = point2vector(getDirection2(vp->position, point));
            

            auto count = octree.getIntersectedVoxelIndices(origin, ray, intersectedrayindices, 1);
            
            if(count > 0){
                for(auto &j : intersectedrayindices){
                    if(visibleIndicestemp.size() == 0){
                        visibleIndicestemp.push_back(j);
                    }
                    else if(std::find(visibleIndicestemp.begin(), visibleIndicestemp.end(), j) == visibleIndicestemp.end()){
                        visibleIndicestemp.push_back(j);
                    }
                }
            }  
        }
        
        pcl::ExtractIndices<pcl::PointXYZ> extract;
        extract.setInputCloud(cloud);
        extract.setIndices(visibleIndicesPtr);
        extract.setNegative(false);
        extract.filter(vp->visible_cloud);
        extract.setNegative(true);
        extract.filter(vp->occluded_cloud);
        
        visibleIndicestemp.clear();
        visibleIndices->clear();
        visibleIndicesPtr->indices.clear();
        frustumCulledIndices.clear();
    }
    std::cout<<"Frustum and Occlusion Culling Finished..."<<std::endl;

}
```

**Comment by mvieth** [comment]
So looking at your code, you are not just using `FrustumCulling` to filter a cloud, you are using `FrustumCulling` together with an octree to do raytracing? Honestly it is not completely clear to me what you are trying to accomplish. Are you trying to find all points that are "in view" of a camera (so not behind the camera or too far to the left/right of the camera)? Or are you trying to find all points that have a clear line to the camera position (not occluded by some other points)? You may also want to check out `VoxelGridOcclusionEstimation` (https://pointclouds.org/documentation/classpcl_1_1_voxel_grid_occlusion_estimation.html). In newer PCL versions, you can also set the far plane distance of `FrustumCulling` to infinity.

**Comment by Heavy0strich** [comment]
Yes. I am doing frustum culling to find the set of points inside the camera's view frustum. Then, I do raytracing to get indices of points not occluded by other points in the camera's view. I organized the original point cloud data in an Octree, using `octree.getIntersectedVoxelIndices(origin, ray, intersectedrayindices, 1)`. Origin is the camera position, and ray is the line joining origin and each point inside the view frustum. But I think I understand what the issue might be. Since I am marking all the points inside the intersected octree voxel as visible, those voxels may include some points beyond the camera position. My goal is to find a camera position that can see most regions of the point cloud. I thought of using octree to mark the node visible, occluded, or empty from a camera's view.

**Comment by mvieth** [comment]
Do you suspect that there is a bug in `FrustumCulling` or the octree implementation? Or do you want help coding your application? If it's the latter, I would ask you to seek help on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community). The GitHub issues are intended for bug reports and compile errors.

**Comment by Heavy0strich** [comment]
Thank you for the help.
