### ISSUE TITLE
[sample_consensus] optimizeModelCoefficientsCone linker error

### ISSUE THREAD

**Issue by keineahnung2345** [PointCloudLibrary/pcl#5925]
**Describe the bug**

Not sure if this is a bug, but when I use PCL 1.14.0, it gives the following error:
```
LNK2001	unresolved external symbol "int __cdecl pcl::internal::optimizeModelCoefficientsCone(class Eigen::Matrix<float,-1,1,0,-1,1> &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &)" (?optimizeModelCoefficientsCone@internal@pcl@@YAHAEAV?$Matrix@M$0?0$00$0A@$0?0$00@Eigen@@AEBV?$Array@M$0?0$00$0A@$0?0$00@4@11@Z)
LNK2001	unresolved external symbol "int __cdecl pcl::internal::optimizeModelCoefficientsCylinder(class Eigen::Matrix<float,-1,1,0,-1,1> &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &)" (?optimizeModelCoefficientsCylinder@internal@pcl@@YAHAEAV?$Matrix@M$0?0$00$0A@$0?0$00@Eigen@@AEBV?$Array@M$0?0$00$0A@$0?0$00@4@11@Z)
LNK2001	unresolved external symbol "int __cdecl pcl::internal::optimizeModelCoefficientsSphere(class Eigen::Matrix<float,-1,1,0,-1,1> &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &,class Eigen::Array<float,-1,1,0,-1,1> const &)" (?optimizeModelCoefficientsSphere@internal@pcl@@YAHAEAV?$Matrix@M$0?0$00$0A@$0?0$00@Eigen@@AEBV?$Array@M$0?0$00$0A@$0?0$00@4@11@Z)
```

I didn't get this kind of error when I used PCL 1.13.1.

**Your Environment:**

 - OS: Windows 11
 - Compiler: Visual Studio 2022
 - PCL Version 1.14.0

**Comment by mvieth** [comment]
Thanks for reporting, does this appear when you build PCL, or when you build your own project? In the latter case, please post your code or another reproducible example.

**Comment by keineahnung2345** [comment]
I have project A and B, project A has a function that calls `pcl::SACSegmentation` and it can be built successfully. Project B depends on the library generated by project A and it doesn't call `pcl::SACSegmentation` itself, but it fails with the above-mentioned error.

**Comment by mvieth** [comment]
Ah okay. The merged pull request should fix this problem, otherwise please notify us :slightly_smiling_face:

**Comment by 181404010226** [comment]
i met this issue too,it happened when i used custom point cloud type
