### ISSUE TITLE
[error: ‘const class std::shared_ptr<pcl::PointCloud<pcl::PointXYZ> >’ has no member named ‘__getDataType’ custom] Provide a general summary of the issue

### ISSUE THREAD

**Issue by ming868686** [PointCloudLibrary/pcl#5927]
![image](https://github.com/PointCloudLibrary/pcl/assets/147027826/4d303cb9-a699-42da-a446-629bdf6ce0d9)
![image](https://github.com/PointCloudLibrary/pcl/assets/147027826/a45607af-70f7-4e53-ab72-88ad59109577)
pcl:1.12，ros:noetic

**Comment by mvieth** [comment]
This is not a PCL issue. Please ask in the appropriate ROS forums. My best guess is that you have to convert the `pcl::PointCloud` to a `sensor_msgs::PointCloud2`
