### ISSUE TITLE
Use msys2 environment and related libraries under windows to compile and use pcl

### ISSUE THREAD

**Issue by Balcher** [PointCloudLibrary/pcl#5939]
Now there is a need，i have to use mingw-w64 in msys2 to compile PCL under windows system.

the problem encountered is as follows：
1. 【normal】program can work normally without include pcl_visualizer.h and cloud_viewer.h. 
2. 【abnormal】The program cannot print and display normally when i include pcl_visualizer.h and cloud_viewer.h（Uncomment in code）, Compilation can pass normally.

**normal VS abnormal**
![image](https://github.com/PointCloudLibrary/pcl/assets/47356320/6963084a-7191-402d-b1c6-d25c69808a9f)

Of course, I have compiled pcl_visualizer when compiling pcl.
![image](https://github.com/PointCloudLibrary/pcl/assets/47356320/bc005b00-dce1-419a-a1ce-af5d7516febe)

the test code is as follows:
```
#include <iostream>
#include <pcl/common/common_headers.h>
#include <pcl/io/pcd_io.h>
// #include <pcl/visualization/pcl_visualizer.h>
// #include <pcl/visualization/cloud_viewer.h>
#include <pcl/console/parse.h>
using namespace std;
 
int main(int argc, char **argv) {
  cout << "Test PCL !" << endl;
  pcl::PointCloud<pcl::PointXYZRGB>::Ptr point_cloud_ptr (new pcl::PointCloud<pcl::PointXYZRGB>);
  uint8_t r(255), g(15), b(15);
  for (float z(-1.0); z <= 1.0; z += 0.05) {
  	for (float angle(0.0); angle <= 360.0; angle += 5.0) {
      pcl::PointXYZRGB point;
      point.x = cos (pcl::deg2rad(angle));
      point.y = sin (pcl::deg2rad(angle));
      point.z = z;
      uint32_t rgb = (static_cast<uint32_t>(r) << 16 | static_cast<uint32_t>(g) << 8 | static_cast<uint32_t>(b));
      point.rgb = *reinterpret_cast<float*>(&rgb);
      point_cloud_ptr->points.push_back (point);
    }
    if (z < 0.0) {
      r -= 12;
      g += 12;
    }
    else {
      g -= 12;
      b += 12;
    }
  }
  
  point_cloud_ptr->width = (int) point_cloud_ptr->points.size ();
  point_cloud_ptr->height = 1;
  cout << "point size = " << point_cloud_ptr->size() << endl;
 
  // pcl::visualization::CloudViewer viewer ("pcl—test");

  // viewer.showCloud(point_cloud_ptr); 
  // while (!viewer.wasStopped()){ };

  return 0;
}

```

The development environment I use in msys2 is cmake 3.28.1, GCC version is 13.2.0, GNU Make 4.4.1.

The PCL version used is 1.12.1，And i borrowed some third party library versions of pcl from the Windows "all in one" package.
- FLANN 1.9.1 （there is no flann in msys2 package, Source code compilation）
- vtk 9.1 （vtk which in msys2 package don't have openmp，Source code compilation，tiff, eigen, openmp use libraries in msys2）
- boost 1.85（used msys2 libraries, boost version in allinone is 1.78）
- eigen 3.4 ( used msys2 libraries ,the same version in allinone)

**Comment by mvieth** [comment]
- I would strongly recommend against `using namespace std;` as it can lead to ambiguities and errors
- Mixing multiple versions of a library (or just having multiple versions of a library installed) can lead to problems. Not sure if that can cause your problem, but I would recommend to avoid multiple versions as much as possible (choose one version of the library and de-install all others, then recompile everything that depends on the library)
- So you say including the two header files makes the bug appear. Is including only one sufficient as well? What about other header files from pcl/visualization? What if you include some of the header files that are included in [pcl_visualizer.h](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/pcl_visualizer.h#L39)? Try to find the smallest change that makes the bug appear

**Comment by Balcher** [comment]
> * I would strongly recommend against `using namespace std;` as it can lead to ambiguities and errors
> * Mixing multiple versions of a library (or just having multiple versions of a library installed) can lead to problems. Not sure if that can cause your problem, but I would recommend to avoid multiple versions as much as possible (choose one version of the library and de-install all others, then recompile everything that depends on the library)
> * So you say including the two header files makes the bug appear. Is including only one sufficient as well? What about other header files from pcl/visualization? What if you include some of the header files that are included in [pcl_visualizer.h](https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/pcl_visualizer.h#L39)? Try to find the smallest change that makes the bug appear

- I get it, thank you.
- I initially used VTK from MSYS2. Later, when I encountered issues, I removed VTK and recompiled it from the source code. I believe there shouldn't be multiple versions coexisting at the same time.
- At first I tried other files under pcl/visualization, but it still didn't work. I guess it was a problem with vtk. Later I reinstalled msys2 and vtk was compiled directly from the source code. The problem is solved.
