### ISSUE TITLE
[feature] pcl::eigen33 maybe unstable when the algebraic multiplicity of the smallest eigenvalue is not 1

### ISSUE THREAD

**Issue by QiMingZhenFan** [PointCloudLibrary/pcl#5940]
**Describe the bug**

When solving the eigenvector corresponding to the smallest eigenvalue, pcl use **cross-product technique** in function [`getLargest3x3Eigenvector`](https://github.com/PointCloudLibrary/pcl/blame/910ccc61737612daad06e11fc79e51540d6480fc/common/include/pcl/common/impl/eigen.hpp#L273). This may be unavailable when the  algebraic multiplicity of the smallest eigenvalue is not 1.

**Context**

Let **λ1**, **λ2**, **λ3** be the eigenvalues of a 3*3 covariance matrix **A**. If **λ1 < λ2 < λ3**, **`scaledMat`**(which is **(A-λ1×I)**, calculated [here](https://github.com/PointCloudLibrary/pcl/blame/910ccc61737612daad06e11fc79e51540d6480fc/common/include/pcl/common/impl/eigen.hpp#L312C3-L312C12))  has **rank 2** and two of its three row vectors are linearly independent. Since the eigenvector are orthogonal to all row vectors of **`scaledMat`**, we can obtain the correct eigenvector by applying cross-product on row vectors.

However, if the algebraic multiplicity of the smallest eigenvalue is 2, which means **λ1 = λ2 < λ3**, **`scaledMat`** has **rank 1** and all its row vectors are linearly dependent. Thus [all the cross-products](https://github.com/PointCloudLibrary/pcl/blame/910ccc61737612daad06e11fc79e51540d6480fc/common/include/pcl/common/impl/eigen.hpp#L279) lead to zero vectors, which is not available for subsequent steps, i.e. [`solvePlaneParameters`](https://github.com/PointCloudLibrary/pcl/blob/910ccc61737612daad06e11fc79e51540d6480fc/features/include/pcl/features/impl/feature.hpp#L79).

**Comment by mvieth** [comment]
Hi, is this a purely theoretical consideration, or did you encounter this problem in practice? My intuition would be that in practice, with (typically) noisy data, it is very unlikely that the two smallest eigenvalues are the same. _Similar_  might be possible, but then the question would be, how similar do the eigenvalues have to be to cause this problem? And since you mentioned `solvePlaneParameters`: if the covariance matrix indeed comes from a planar point cloud, then this problem cannot happen anyways.

**Comment by mvieth** [comment]
If we agree that this is very unlikely to be a problem in practice, I would say that it is not worth it to spend a lot of time on it. However, if you like, you could add the following check (copied from the other eigen33 function below):
```c++
if ( (eigenvalues (1) - eigenvalues (0)) <= Eigen::NumTraits < Scalar > ::epsilon ())
```
and then a `PCL_WARN(...);` to tell the user that the smallest eigenvalue is not unique. Then we can also see if any of our tests prints this warning.
