### ISSUE TITLE
MovingLeastSquares cannot be written as a function

### ISSUE THREAD

**Issue by mcmingchang** [PointCloudLibrary/pcl#5944]
void pcl_surface_reconstruction(pcl::PointCloud<pcl::PointXYZ>::Ptr& cloud, pcl::PointCloud<pcl::PointNormal>& mls_points) {
	pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
	pcl::MovingLeastSquares<pcl::PointXYZ, pcl::PointNormal> mls;
	mls.setInputCloud(cloud);
	mls.setNumberOfThreads(100);  // 调用所有线程
	mls.setComputeNormals(true);
	mls.setPolynomialOrder(2);
	mls.setSearchMethod(tree);
	mls.setSearchRadius(5);
	mls.process(mls_points);  // 计算完成后，cloud的点分布更平滑
	cout << "!!" << endl;
}

In the latest version, writing this method as a function can cause a crash, but writing it directly to main can run normally.

**Comment by mvieth** [comment]
@mcmingchang 
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use?
- When it crashes, is there any error message? Can you post a stack trace?

**Comment by mvieth** [comment]
@mcmingchang If you do not provide additional information (the questions I asked in my previous comment) then I will close this issue soon.
