### ISSUE TITLE
[NDT Registration]Can calculate distribution map once?

### ISSUE THREAD

**Issue by PigBroA** [PointCloudLibrary/pcl#5961]
Dear all,

I am using NDT registration for localization, let LiDAR local frame data as source cloud, and let global map(pre-built) as target cloud.

I guess NDT(in PCL) makes distribution map in "align" function, and "align" function usually operates in loop.

In my system, I don't have to change target cloud, so I think the system doesn't have to make distribution values in every loops.

Is there any solution the issue? I mean I want to calculate distribution map of target cloud once, let the distribution map hold on memory ,and then load the data to estimate transformation matrix.

Thanks for reading my question.

Please let me know how to do it or solution that already exist.

**Comment by mvieth** [comment]
The normal distributions of the target cloud are computed in `setInputTarget`. So if you call `setInputTarget`  in the initial setup, and then alternately call `setInputSource` and `align`, the normal distributions will not be recomputed as far as I can see (though I have not tested this).

**Comment by PigBroA** [comment]
Dear @mvieth ,

Thanks for quick reply.

I am using pcl 1.10 version now, is this version doing same as well?

Actually, I tried 2 variations to test them, first one used voxelized target cloud, and second one used original target cloud, they have different point size. (the other conditions are all same, especially NDT resolution and source cloud size is same)

However, 2 processing time output very difference results, first case is very faster than second case(around 100 times, the value is not important), so I guess distribution map creation is on "align" function.
(In loop, there are "setInputSource" and "align" function, other registration initializations are on outside of loop)

And in "align" function, we can see "computeTranformation" function and the function include distribution calculation.

Please re-check it.

Thank you very much.

**Comment by PigBroA** [comment]
Dear @mvieth ,

I am really appreciate your reply.

I have more a few questions.

Have you checked the processing time of a call to setInputTarget on its own? If you downsample the target cloud (fewer points), I would not be surprised if a single computation of the normal distributions is faster. It might also happen that the distribution map is different: there might be fewer cells with enough points to robustly estimate a normal distribution, which means that the overall registration process will be faster, but less precise. So just because the processing is faster if the target cloud is downsampled, does not necessarily mean that the distribution map is recomputed each time in the align function.
>> that means "some NDT grid be able to be ignored if the NDT grid includes a few point"?
"
and I just saw "align" function in ndt.hpp, I think there is no way to skip "computTransformation". Only "initCompute()" can pass "computTransformation" function, but the way can't operate anything. 
-------------------------------------------------------------------
template <typename PointSource, typename PointTarget, typename Scalar>
inline void
Registration<PointSource, PointTarget, Scalar>::align(PointCloudSource& output,
                                                      const Matrix4& guess)
{
  if (!initCompute())
    return;

  // Resize the output dataset
  output.resize(indices_->size());
  // Copy the header
  output.header = input_->header;
  // Check if the output will be computed for all points or only a subset
  if (indices_->size() != input_->size()) {
    output.width = indices_->size();
    output.height = 1;
  }
  else {
    output.width = static_cast<std::uint32_t>(input_->width);
    output.height = input_->height;
  }
  output.is_dense = input_->is_dense;

  // Copy the point data to output
  for (std::size_t i = 0; i < indices_->size(); ++i)
    output[i] = (*input_)[(*indices_)[i]];

  // Set the internal point representation of choice unless otherwise noted
  if (point_representation_ && !force_no_recompute_)
    tree_->setPointRepresentation(point_representation_);

  // Perform the actual transformation computation
  converged_ = false;
  final_transformation_ = transformation_ = previous_transformation_ =
      Matrix4::Identity();

  // Right before we estimate the transformation, we set all the point.data[3] values to
  // 1 to aid the rigid transformation
  for (std::size_t i = 0; i < indices_->size(); ++i)
    output[i].data[3] = 1.0;

  computeTransformation(output, guess);

  deinitCompute();
}
-------------------------------------------------------------------

By the way, could you please let me know distribution level access for pcl if there are?

Otherwise, can I get distribution visualization method with pcl? (any tips?)

Thank you.

**Comment by mvieth** [comment]
> That means "some NDT grid be able to be ignored if the NDT grid includes a few point"?

I am not sure I understand what you mean

> and I just saw "align" function in ndt.hpp, I think there is no way to skip "computTransformation". Only "initCompute()" can pass "computTransformation" function, but the way can't operate anything.

You mean the `align` function in registration.hpp?
No, I did not mean that `computeTransformation` is skipped.

> By the way, could you please let me know distribution level access for pcl if there are?

Again, I am not sure what you mean. If you want to access `target_cells_`, then you would have to create a subclass for `NormalDistributionsTransform` since it is a protected member.

> Otherwise, can I get distribution visualization method with pcl? (any tips?)

`NormalDistributionsTransform` does not really have anything ready-to-use for visualization. When you found a way to get access to `target_cells_`, then you could have a look at [getDisplayCloud](https://pointclouds.org/documentation/classpcl_1_1_voxel_grid_covariance.html#accf21aea709481f32a3ab000efde490f)

**Comment by PigBroA** [comment]
Dear @mvieth ,

Thank you very much, I'am gonna study more about procedure(NDT).

Have a good day.

**Comment by yt2639** [comment]
Hii thanks for committing a function to facilitate this. I do see there is now a function `getTargetCells` (https://github.com/PointCloudLibrary/pcl/blob/c9a17509ba36950c7d21101da530d838cbf97b9c/registration/include/pcl/registration/ndt.h#L258) to expose NDT representation.

Is there any example to illustrate how we can do that?

For example, a simplest version like:

```
pcd = read_PLY_file('xxxxxxx')
ndt = NormalDistributionsTransform()
ndt.setInputTarget(cloud)
ndtcells = ndt.getTargetCells()
```

Do we have this type of example for tutorial?

Thanks!

**Comment by yt2639** [comment]
In addition to that, I found with small voxel size, there are increasingly spiked gaussians using the above code.

`ndt.setResolution(1.5);`

![Image](https://github.com/user-attachments/assets/72140ac9-716d-46e5-8533-feb0b2cafeb8)

`ndt.setResolution(0.5);`

![Image](https://github.com/user-attachments/assets/55fdabd3-e7f0-4863-83a0-7eec696f1c74)

`ndt.setResolution(0.1);`

![Image](https://github.com/user-attachments/assets/6a9b1b0d-00d7-495c-aac6-ff09a0a9f24a)

Do you have any idea why this is happening and does this indicate my code implementation was incorrect?

Many thanks!

**Comment by mvieth** [comment]
> But after I run this, it shows a large mismatch among NDT leaves size, Display cloud size, and get centroid
> I think these three numbers should be equal, correct? So which number is really representing the number of NDTs (gaussians)? And how should I fix this to export a .txt file containing the mean and covariance of each NDT cell?

In your code, `NDT leaves` are all leaves that contain _any_ points. However, a leaf needs a certain number of points to reliably compute the covariance matrix. For example, if a leaf only contains one or two points, it cannot compute the matrix. In your example, 121 leaves have a sufficient number of points and therefore have a valid covariance matrix. For the `Display cloud`, PCL _samples_ 1000 points from each valid gaussian distribution.
The smaller/finer you set the grid resolution, the more leaves contain too few points to compute a valid covariance matrix. So if `get centroid` gets too small, try increasing the resolution.
