### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by OgreTransporter** [PointCloudLibrary/pcl#5962]
https://github.com/PointCloudLibrary/pcl/blob/44790b403313799caa20594d95e94edcfb21326f/io/include/pcl/io/ply/ply_parser.h#L76

For `std::function`
```
#include <functional>
```
is missing in that file.

**Comment by mvieth** [comment]
@OgreTransporter Hi, thanks for reporting this. You are right, `ply_parser.h` should include `functional`. If you like, feel free to create a pull request, otherwise I will create one in a few days.
