### ISSUE TITLE
[custom] Provide a general summary of the issue

### ISSUE THREAD

**Issue by GL-tony** [PointCloudLibrary/pcl#5971]
I deployed the latest PCL 1.14.0 release version of the file. At this stage, there are the following problems:
1. Error reminder on VS. These errors all appear in the.hPP file, see the attached figure for details.
2. None of these issues occur when I compile with the DEBUG version.
3, although the release version has problems, it can run the program normally, and it can also output the sample point cloud image normally.
Ask for help, what is the problem and how to solve it.
![1](https://github.com/PointCloudLibrary/pcl/assets/37897989/98f814fa-c181-4f13-9dc3-1163ac8874bf)

**Comment by mvieth** [comment]
@GL-tony I do not understand Chinese. If you want my help, post a screenshot with English text.

**Comment by mvieth** [comment]
Closing because of no response
