### ISSUE TITLE
Support `pcl::PointXYZLNormal` in `GreedyProjectionTriangulation`

### ISSUE THREAD

**Issue by roncapat** [PointCloudLibrary/pcl#5981]
I noticed that GP3 can't be used out of the box with all PCL point types containing normals, but only a certain subset. For example, `PointXYZLNormal` is not included in the instantiation list here below. May I ask to add it? I can provide a PR if ok for the maintainers.

https://github.com/PointCloudLibrary/pcl/blob/ccc4eee90a7242cf0d3c5e1ddb79716eabe4eb8c/surface/src/gp3.cpp#L44

**Comment by mvieth** [comment]
Hi, I have no objections. Are you using `PointXYZLNormal` in your code?

**Comment by roncapat** [comment]
> Are you using `PointXYZLNormal` in your code?
Exaclty, I'm using "L" field to encode terrain segmentation/classification in an autonomous navigation scenario.
