### ISSUE TITLE
[obj_io.cpp] vector subscript out of range

### ISSUE THREAD

**Issue by 181404010226** [PointCloudLibrary/pcl#5987]
environment:
 vs2022,vcpkg,windows10;
bug:
When I load an OBJ file downloaded from a website, I encounter a 'vector subscript out of range' error:
![屏幕截图 2024-03-27 092218](https://github.com/PointCloudLibrary/pcl/assets/108257182/4e03de90-43c1-456c-8300-af865eb69b42)

**Comment by mvieth** [comment]
@181404010226 Where can I download the file?

**Comment by 181404010226** [comment]
@mvieth I downloaded the file from https://www.cgtrader.com/items/2827838/download-page, and it appears that I didn't download the .mtl file. Regardless, this omission is likely to cause issues that could break the program.
