### ISSUE TITLE
Is the gpu-accelerated VoxelGrid method unavailable in pcl 1.14.0 version?

### ISSUE THREAD

**Issue by qilinhu** [PointCloudLibrary/pcl#5989]
I saw the VoxelGrid method implemented by cuda in version 1.14.0. When I compiled it, I found that there was no corresponding header file and output. Is this method unavailable now? I hope to get replies and help. Thanks

**Comment by mvieth** [comment]
This should answer your question: https://github.com/PointCloudLibrary/pcl/issues/5809
We hope that someone is interested and implements a gpu-accelerated VoxelGrid that actually works.

**Comment by qilinhu** [comment]
@mvieth Thank you for your reply. Has the pcl official considered implementing a truly efficient and usable cuda voxel_grid method?
