### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by huangfengge** [PointCloudLibrary/pcl#5992]
make[2]: *** [tools/CMakeFiles/pcl_ply2pcd.dir/build.make:123：bin/pcl_ply2pcd] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1710：tools/CMakeFiles/pcl_ply2pcd.dir/all] 错误 2
make: *** [Makefile:156：all] 错误 2

**Comment by mvieth** [comment]
@huangfengge I need more information. Most importantly, there should have been an error message just above the lines you posted. Please show the _complete_ error message.
I also need to know: Which operating system are you using? Which PCL version?

**Comment by mvieth** [comment]
@huangfengge Last chance: if you don't provide more information soon, I will close this issue.

**Comment by mvieth** [comment]
Closing because of no answer
