### ISSUE TITLE
[SamplingSurfaceNormal]ERROR LNK2001 pcl::SamplingSurfaceNormal<struct pcl::PointXYZ>::applyFilter

### ISSUE THREAD

**Issue by QiuYilin** [PointCloudLibrary/pcl#6007]
I use pcl with vcpkg (HEAD version), When I use SamplingSurfaceNormal (This error will not occur in other class)there will be error :

`error LNK2001:  "protected: virtual void __cdecl pcl::SamplingSurfaceNormal<struct pcl::PointXYZ>::applyFilter(class pcl::PointCloud<struct pcl::PointXYZ> &)" (?applyFilter@?$SamplingSurfaceNormal@UPointXYZ@pcl@@@pcl@@MEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@@Z) `

my code:
```
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/filters/sampling_surface_normal.h>

pcl::SamplingSurfaceNormal<pcl::PointXYZ> sampling_surface_normal;

```

 - OS: [Windows]
 - Compiler: [MSVC]
 - PCL Version [1.14.0]

**Comment by mvieth** [comment]
@QiuYilin `SamplingSurfaceNormal` needs a point type with xyz and normal information. `pcl::PointXYZ` cannot store the normal information. You can choose between `pcl::PointNormal` or `pcl::PointXYZRGBNormal` or `pcl::PointXYZINormal`. If you don't want or have color or intensity, then `pcl::PointNormal` is probably the right choice for you.

**Comment by mvieth** [comment]
Assuming that answered the question ...

**Comment by QiuYilin** [comment]
@mvieth Is there any way to quickly figure out what type of point cloud a function requires? I often make mistakes by just looking at the template parameters, and not every class has relevant explanations in the comments.

**Comment by mvieth** [comment]
@QiuYilin You could look into the .cpp files (for example sampling_surface_normal.cpp) to see for which point types the class is instantiated

**Comment by QiuYilin** [comment]
I see. I should search for "PCL_INSTANTIATE" in cpp.
