### ISSUE TITLE
Segmentation fault for mesh2pcd

### ISSUE THREAD

**Issue by RLHI** [PointCloudLibrary/pcl#601]
Hi

I was able to convert a few number of the .obj files (3D images) by mesh2pcd but for the rest in the same directory there was this error:

Convert a CAD model to a point cloud using ray tracing operations. For more information, use: ./pcl_mesh2pcd -h
Segmentation fault (core dumped)

I wish I could attach both non-error and error causing files but you don-t support .obj files to get uploaded.

**Comment by VictorLamoine** [comment]
I have tested this again in detail; the pull request solved this issue, `mesh2pcd` doesn't crash anymore.
#381 still needs to be fixed.

**Comment by nomi321** [comment]
@VictorLamoine  can you tell me that how did u clear this issue as I am facing the same issue. 

thanks in advance
