### ISSUE TITLE
[FastBilateralFilterOMP] FastBilateralFilterOMP does not support PointXYZI

### ISSUE THREAD

**Issue by QiuYilin** [PointCloudLibrary/pcl#6018]
I can see FastBiateralFilterOMP supports PointXYZ PointXYZRGB PointXYZRGBA in fast_bilateral_omp.cpp
`
PCL_INSTANTIATE (FastBilateralFilterOMP, (pcl::PointXYZ)(pcl::PointXYZRGB)(pcl::PointXYZRGBA))`

I think since PointXYZ is supported why PointXYZI is not supported, so I can only split the intensity information first and then merge it?

**Comment by mvieth** [comment]
I am not sure why FastBilateralFilterOMP is not instantiated for PointXYZI. You can try adding `#define PCL_NO_PRECOMPILE` before including the header file and check if you can use it with PointXYZI then. See also https://pcl.readthedocs.io/projects/tutorials/en/master/adding_custom_ptype.html#adding-custom-ptype

**Comment by QiuYilin** [comment]
@mvieth  Thank you !
