### ISSUE TITLE
[module_There is a logic error in the code of the computeTransformation function in the gicp.hpp file when calculating the transformation matrix Tname] Provide a general summary of the issue

### ISSUE THREAD

**Issue by mawenwuda** [PointCloudLibrary/pcl#6022]
`final_transformation_ = guess;    //**New code**

while (!converged_) {
    for (std::size_t i = 0; i < 4; i++)
      for (std::size_t j = 0; j < 4; j++)    //**modified**
          transform_R(i, j) = static_cast<double>(final_transformation_(i, j));

    query.getVector4fMap() =        
    final_transformation_.template cast<float>() * query.getVector4fMap();    //**modified**

    final_transformation_ = transformation_ * final_transformation_;    //**modified**
    nr_iterations_++;    //**Add the above modified statement before this statement**
}
//Computation of the final transformation matrix is not possible, because the previous_transformation_ variable does not implement the cumulative transformation matrix.
final_transformation_ = previous_transformation_ * guess;    //**delete**`

**Comment by mvieth** [comment]
@mawenwuda Sorry, I am having difficulties interpreting your modifications. Could you explain, what exactly does not work currently? If you could provide an example where you call GICP, and show how the result does not match your expectations, that would be very helpful.

**Comment by mvieth** [comment]
> While reading the source code of the computeTransformation function in the gicp.hpp file, I encountered some issues that I couldn't understand

@mawenwuda But have you tried running GICP? I have successfully used GICP several times, and as far as I can tell, the transformation it returned was always correct.
1. `M` is a reference, so by assigning to it, we actually assign to `mahalanobis_[i]`
2. `transformation_` is the total transformation matrix from all iterations (excluding the `guess` I think). `rigid_transformation_estimation_` updates the matrix
3. `transformation_` is the accumulated transformation, why do you think it isn't?
4. I would suggest that you try running GICP yourself, and at the end, use `gicp.getFinalTransformation()` to get `final_transformation_` and inspect its value

As I said in my last comment, if you have a test case where you run GICP and the behaviour is different from what you expected (so you observe a bug in practice), I am happy to investigate, but so far it seems to me that you simply misunderstand the code and assume it is a logic error.

**Comment by mawenwuda** [comment]
@mvieth I think I misunderstood this piece of code, thank you very much for your explanation!

**Comment by mvieth** [comment]
You are welcome
