### ISSUE TITLE
[custom] Does PCLVisualizer support to display vertical colorbar? 

### ISSUE THREAD

**Issue by hitbuyi** [PointCloudLibrary/pcl#6032]
I have learned the offical tutorial on pcl visualization,  and foud pcl supports horizontal colorbar, but I  don't know whether PCL support to display vertical colorbar.  Someone used customed code(more than 300 + lines of code ) to support vertical colorbar in old version of  PCL v1.8.1,  like below figure, we can set  the colorbar's  title,color step and color range, even the colorbar can be moved anywhere within the window, similiar to MATLAB  style.
![pcl_colorbar](https://github.com/PointCloudLibrary/pcl/assets/10301777/07438111-f491-4091-91a6-ec903f8acdd5)

I want to know whether  PCL v1.14  can support the vertical colorbar without too many customed codes. beside, adding a label to XYZ axis is convenient for me, I can't find where to add the axis' label.

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
