### ISSUE TITLE
 undefined reference to `KD_TREE<pcl::PointXYZINormal>::Nearest_Search(pcl::PointXYZINormal

### ISSUE THREAD

**Issue by FranciscoAnayaPalacios** [PointCloudLibrary/pcl#6034]
I'm trying to build FastLio and it appears the error refering to the pcl__PointXYZINormal type:

/usr/bin/ld: CMakeFiles/fastlio_mapping.dir/src/laserMapping.cpp.o: in function `h_share_model(state_ikfom&, esekfom::dyn_share_datastruct<double>&) [clone ._omp_fn.0]':
laserMapping.cpp:(.text+0x16a89): undefined reference to `KD_TREE<pcl::PointXYZINormal>::Nearest_Search(pcl::PointXYZINormal, int, std::vector<pcl::PointXYZINormal, Eigen::aligned_allocator<pcl::PointXYZINormal> >&, std::vector<float, std::allocator<float> >&, float)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/fastlio_mapping.dir/build.make:476: fastlio_mapping] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:593: CMakeFiles/fastlio_mapping.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< fast_lio [3.36s, exited with code 2]

**Comment by mvieth** [comment]
PCL does not have a class called `KD_TREE` with member function `Nearest_Search`, so this is not a PCL problem. I suggest you contact the FastLio maintainers.
