### ISSUE TITLE
[CorrespondenceEstimation] There may be something wrong with the annotation

### ISSUE THREAD

**Issue by QiuYilin** [PointCloudLibrary/pcl#6043]
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/correspondence_estimation.h#L386

It says "CorrespondenceEstimation represents the base class for determining correspondences between target and query point sets/features.", but CorrespondenceEstimation does not have subclasses. Instead, it has a base class named CorrespondenceEstimationBase.

**Comment by mvieth** [comment]
Yeah, that might be a bit confusing. `CorrespondenceEstimationBase` is abstract (so not usable by itself) and the base class/parent class of four non-abstract correspondence estimation methods, including `CorrespondenceEstimation`. `CorrespondenceEstimation` is probably the most "basic" or "simple" of the four correspondence estimation methods. See also the inheritance diagram at https://pointclouds.org/documentation/classpcl_1_1registration_1_1_correspondence_estimation_base.html

**Comment by QiuYilin** [comment]
Then I think it would be more clear if I simply modify the comment.As you said, change it to "CorrespondenceEstimation represents the basic/simple class for determining correspondences between target and query point sets/features"
