### ISSUE TITLE
The implementation of the 'computePairFeatures' function in pfh_tools.h was not found.

### ISSUE THREAD

**Issue by mawenwuda** [PointCloudLibrary/pcl#6066]
I would like to understand the specific implementation of the computePairFeatures function in pfh_tools.h, but I couldn't find it. I hope to get clarification.
`PCL_EXPORTS bool 
computePairFeatures (const Eigen::Vector4f &p1, const Eigen::Vector4f &n1, 
                     const Eigen::Vector4f &p2, const Eigen::Vector4f &n2, 
                     float &f1, float &f2, float &f3, float &f4);`

**Comment by mvieth** [comment]
The implementation is here: https://github.com/PointCloudLibrary/pcl/blob/master/features/src/pfh.cpp#L45

**Comment by mawenwuda** [comment]
@mvieth Is it because of the version that I couldn't find the src folder in 1.13.1?

**Comment by mawenwuda** [comment]
@mvieth I installed the PCL-1.13.1-AllInOne-msvc2022-win64.exe version from the official website, but I couldn't find the src folder in the installation directory. Is this the reason?
