### ISSUE TITLE
Some of the PCL DLLs cannot be integrated into the project's final DLL.

### ISSUE THREAD

**Issue by mawenwuda** [PointCloudLibrary/pcl#6068]
In the VS2022 + PCL 1.13.1 environment, I generated the DLL file for my project. However, when calling this DLL on another device, it shows a lack of some PCL dependencies, such as pcl_common.dll. I have already checked that the project properties include the corresponding pcl_common.lib in additional dependencies.How can I integrate these DLLs into the project's final DLL?

**Comment by larshg** [comment]
Then you need to build PCL yourself as static libraries instead of standard shared.

**Comment by mawenwuda** [comment]
thank you!
