### ISSUE TITLE
Outdated cJSON sources with potential missing fixes

### ISSUE THREAD

**Issue by Garnik645** [PointCloudLibrary/pcl#6080]
### Summary

This project includes outdated cJSON sources (pcl/outofcore/src/cJSON.cpp), which might be missing important updates and bug fixes. I recommend updating the cJSON sources to the latest version available.

### Report origin
This potential issue was detected by a tool designed in [CAST](https://castech.am/).

**Comment by mvieth** [comment]
Hi, thanks for reporting. I have created a pull request to make PCL use a system-wide installation of cJSON, if available.
