### ISSUE TITLE
Access violation when calling RandomSampleConsensus::computeModel

### ISSUE THREAD

**Issue by OlClown** [PointCloudLibrary/pcl#6081]
**Describe the bug**

When attempting to compute the Ransac Model on a SampleConsensusModelPlane I get an access violation when I call the computeModel member function of  RandomSampleConsensus class

**Context**

I am trying to find a best fit plane for a group of points.

**Expected behavior**

I expect the function call to complete and have calculated the model coefficients

**Current Behavior**

It crashes when the function gets to a point where it is trying to get samples,  It tries to resize a vector called samples.

**To Reproduce**
`#include <iostream>

#include <pcl/common/common.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/sample_consensus/ransac.h>
#include <pcl/sample_consensus/sac_model_plane.h>

int main()
{

	// Create a point cloud
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);

	// Example points
	cloud->push_back(pcl::PointXYZ(1.0, 2.0, 0.001));
	cloud->push_back(pcl::PointXYZ(4.0, 5.0, 0.002));
	cloud->push_back(pcl::PointXYZ(7.0, 8.0, 0.003));

	// Perform RANSAC plane fitting
	pcl::SampleConsensusModelPlane<pcl::PointXYZ>::Ptr model_plane(new pcl::SampleConsensusModelPlane<pcl::PointXYZ>(cloud));
	pcl::RandomSampleConsensus<pcl::PointXYZ> ransac(model_plane);
	ransac.setDistanceThreshold(0.01); // Set an appropriate distance threshold

	ransac.computeModel();  //Crashes here

	// Get the inliers
	std::vector<int> inliers;
	ransac.getInliers(inliers);

	// Debugging: Check inliers
	if (inliers.empty()) {
		std::cerr << "No inliers found\n";
		return -1;
	}

	// Extract the coefficients of the plane (normal vector and distance to origin)
	Eigen::VectorXf coefficients;
	ransac.getModelCoefficients(coefficients);

	// Debugging: Check coefficients
	if (coefficients.size() < 4) {
		std::cerr << "Invalid coefficients size: " << coefficients.size() << "\n";
		return -1;
	}

	Eigen::Vector3f normal_vector(coefficients[0], coefficients[1], coefficients[2]);

	// Print the normal vector
	std::cout << "Normal Vector: " << normal_vector.transpose() << std::endl;

	return 0;
}`

This is the code that throws the access violation

**Your Environment (please complete the following information):**

 - OS: [Windows 10 19045.4529]
 - Compiler: [MSVC 199711]
 - PCL Version [1.14.1] used VCPKG to build this
 
What I am noticing is that on line 70 of ransac.hpp  a vector called selection is declared. Then, on line 117 that is passed by reference to SampleConsensusModel::getSamples.  When I step into this function, the capacity of that vector is quite large where as before I step into the function it is 0 because it has only just been instantiated.

**Comment by mvieth** [comment]
@OlClown My best guess would be that there is a mix-up between release and debug libraries. How do you build your code? Do you use CMake? If yes, please post your CMakeLists.txt

**Comment by OlClown** [comment]
I used vcpkg to handle the pcl code and all dependences.  Past that, I just set the Include/Library directories in my Visual Studio project to the vcpkg install location.  From that description does it seem like I did something incorrect?

**Comment by OlClown** [comment]
You were correct, The library directory was pointing to the release libraries.  Thanks for the point in the right direction. I should have caught that.

**Comment by mvieth** [comment]
Great that the problem is solved! I would also recommend to have a look at https://pcl.readthedocs.io/projects/tutorials/en/master/pcl_vcpkg_windows.html#using-dependencies-installed-with-vcpkg-in-cmake-projects
