### ISSUE TITLE
[pcl/registration/ia_ransac>] I cannot find the specific implementation code for the feature search function.

### ISSUE THREAD

**Issue by mawenwuda** [PointCloudLibrary/pcl#6085]
In the function `findSimilarFeatures()`, the statement` feature_tree_->nearestKSearch(input_features, sample_indices[i], k_correspondences_, nn_indices, nn_distances) `performs nearest neighbor feature search. I cannot locate the specific implementation code for this. I would like to view this code and would appreciate any assistance.

**Comment by mawenwuda** [comment]
I want to verify if the criterion for finding nearest neighbors of features is the Kullback-Leibler distance, and I also want to learn techniques for handling infinite KL divergence.

**Comment by mvieth** [comment]
Please use [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community) for such questions. The GitHub issues are intended for bug reports and compile errors.
