### ISSUE TITLE
install PCL 1.14.1 in nvidia orin(aarch64)

### ISSUE THREAD

**Issue by lisa0501** [PointCloudLibrary/pcl#6090]
platform: NVIDIA ORIN aarch64

when make from source files, bugs reported,

pcl-pcl-1.14.1/gpu/people/src/bodyparts_detector.cpp:46:10: fatal error: emmintrin.h: No such file or directory
   46 | #include "emmintrin.h"
compilation terminated.
make[2]: *** [gpu/people/CMakeFiles/pcl_gpu_people.dir/build.make:63: gpu/people/CMakeFiles/pcl_gpu_people.dir/src/bodyparts_detector.cpp.o] Error 1

 - OS: [Ubuntu 20.04, in NVIDIA ORIN]  
 - Compiler: [GCC 9.4]
 - PCL Version [1.14.1]

**Comment by mvieth** [comment]
From what I can see, bodyparts_detector.cpp actually does not need to include emmintrin.h. So you could try to remove that line.
In case you don't need the gpu-people module, you can disable the option `BUILD_gpu_people`, either by using `ccmake` or by passing `-DBUILD_gpu_people=OFF` to cmake.

**Comment by mvieth** [comment]
@lisa0501 Did that help? Can I close this issue?

**Comment by mvieth** [comment]
Closing because of no response ...

**Comment by Beatlesso** [comment]
> From what I can see, bodyparts_detector.cpp actually does not need to include emmintrin.h. So you could try to remove that line. In case you don't need the gpu-people module, you can disable the option `BUILD_gpu_people`, either by using `ccmake` or by passing `-DBUILD_gpu_people=OFF` to cmake.

Thank you, I solved this problem by removing this line.
But why don't you remove this line? 
I've been troubled by it for hours.

**Comment by mvieth** [comment]
@Beatlesso Feel free to create a pull request to remove that line.

**Comment by lisa0501** [comment]
> Closing because of no response ...

good job!
