### ISSUE TITLE
[Features] IntegralImageNormalEstimation example crashes, ubuntu 22.04

### ISSUE THREAD

**Issue by nxlou94** [PointCloudLibrary/pcl#6091]
**Describe the bug**

`IntegralImageNormalEstimation` example crashes with ubuntu 22.04 desktop, libpcl-dev 1.12.1.

**Context**

I'm trying to use `IntegralImageNormalEstimation` since I'm trying to find normal of a surface scanned by LIDAR. I am using `ubuntu 22.04 desktop`, and I installed `libpcl-dev` using `apt`.
I tried the example in this link:
[https://pcl.readthedocs.io/projects/tutorials/en/master/normal_estimation_using_integral_images.html#normal-estimation-using-integral-images](https://pcl.readthedocs.io/projects/tutorials/en/master/normal_estimation_using_integral_images.html#normal-estimation-using-integral-images)
and it crashes.
I changed the code, and found that it crashes with 3 of 4 `NormalEstimationMethod` options.
```cpp
enum NormalEstimationMethod
{
  COVARIANCE_MATRIX,  // crash
  AVERAGE_3D_GRADIENT,  // crash
  AVERAGE_DEPTH_CHANGE,  // doesn't crash
  SIMPLE_3D_GRADIENT  // crash
};
```

**Expected behavior**

Example should not crash.

**Current Behavior**

executable crashes with following output:
```shell_session
user@pc:~/path/to/dir$ ./test_integral_normal
test_integral_normal: /usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:133: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long int; int Value = 3]: Assertion `v == T(Value)' failed.
Aborted (core dumped)
```

**To Reproduce**

on a ubuntu 22.04 desktop system, install `libpcl-dev`:
`sudo apt install libpcl-dev`
Then:

**Option 1:** follow steps in link above

**Option 2:** use the archive here:
[pcl_playground.zip](https://github.com/user-attachments/files/16331307/pcl_playground.zip)
compile and run test_integral_normal.

**Your Environment (please complete the following information):**

 - OS: [Ubuntu 22.04 desktop]
 - Compiler: [g++ 11.4]
 - PCL Version [1.12.1]

**Additional context**

I tried with ubuntu 18.04 desktop, which has libpcl-dev 1.8.1 and libeigen3-dev 3.3.4, where everything worked.
On ubuntu 22.04 desktop, I have libpcl-dev 1.12.1 and libeigen3-dev 3.4.0, and the example crashes.

**Comment by mvieth** [comment]
This seems to be the same problem as in https://github.com/PointCloudLibrary/pcl/issues/5063 . The problem was fixed in https://github.com/PointCloudLibrary/pcl/commit/614e19d96bd8415dbfb52d86df0f3774a9f462fe (PCL 1.13.0 and newer)
