### ISSUE TITLE
[common] Warning messages when converting empty PCLPointCloud2

### ISSUE THREAD

**Issue by at-wat** [PointCloudLibrary/pcl#6092]
**Describe the bug**

Since pcl-1.14.0, `pcl::fromPCLPointCloud2()` outputs `[pcl::fromPCLPointCloud2] No data to copy.` as warning when handling empty (but having headers) `PCLPointCloud2`, and it floods log output.

**Context**

Especially on robotics applications, empty PointCloud2 message is often used to indicate there are no points.

**Expected behavior**

No log or lower verbosity level log when converting empty PCLPointCloud2.

**Current Behavior**

`[pcl::fromPCLPointCloud2] No data to copy.` is shown as warning.

**To Reproduce**

```cpp
// g++ -I/usr/include/pcl-1.14 -I/usr/include/eigen3 test.cpp -lpcl_common
#include <pcl/conversions.h>
#include <pcl/point_types.h>

int main() {
  // Create zero points XYZ PointCloud2
  pcl::PointCloud<pcl::PointXYZ> pc;
  pcl::PCLPointCloud2 pc2;
  pcl::toPCLPointCloud2(pc, pc2);

  // Convert zero points XYZ PointCloud2
  pcl::PointCloud<pcl::PointXYZ> out;
  pcl::fromPCLPointCloud2(pc2, out);
}
```
Running this outputs
```
[pcl::fromPCLPointCloud2] No data to copy.
```

**Screenshots/Code snippets**

This problem is introduced by this commit: https://github.com/PointCloudLibrary/pcl/commit/788c53eab2123df25e5eb34f45d2ed7dfe6cb48b
https://github.com/PointCloudLibrary/pcl/blob/2661588573771c7c32568fa3657c9f5d4f8a3c11/common/include/pcl/conversions.h#L241-L246

**Your Environment (please complete the following information):**

 - OS: [Alpine 3.20] (not related to the issue)
 - Compiler: [GCC 13.2.1] (not related to the issue)
 - PCL Version [1.14.1]

**Possible Solution**

Remove
https://github.com/PointCloudLibrary/pcl/blob/2661588573771c7c32568fa3657c9f5d4f8a3c11/common/include/pcl/conversions.h#L244
or change it to `PCL_DEBUG`

**Additional context**

**Comment by mvieth** [comment]
> Especially on robotics applications, empty PointCloud2 message is often used to indicate there are no points.

Hi, I do not really understand: why, or for what purpose, is it necessary to explicitly indicate no points? Why should the sender not simply omit the message?

I think the warning could be helpful for users who made a mistake and forgot to fill in the `PCLPointCloud2`. While an empty `PCLPointCloud2` is not an error, I would consider it to be unusual.

@larshg What is your opinion on removing the warning? (since it was your commit that added it)

**Comment by at-wat** [comment]
> Hi, I do not really understand: why, or for what purpose, is it necessary to explicitly indicate no points? Why should the sender not simply omit the message?

In our case, PointCloud2 data is transferred as [ROS](https://www.ros.org/) message.

For example, a obstacle detection ROS node (process) detects points which may collide with the robot, and publish detected points as PointCloud2 ROS message
(PointCloud2 ROS message's payload is same as PCL PointCloud2 and usually converted by [pcl_conversion package](https://github.com/ros-perception/perception_pcl/blob/ros2/pcl_conversions/include/pcl_conversions/pcl_conversions.h) which internally use `pcl::fromPCLPointCloud2()`)
If there are no obstacle points, an empty PointCloud2 message is published.

A motion planner ROS node subscribes the detected obstacle points as PointCloud2 ROS message and plan the robot motion.
If the motion planner ROS node receives empty PointCloud2 message, it means there are no obstacles and the robot can move freely, but if the node doesn't receive any PointCloud2 messages, it may mean the sensor device or the obstacle detection node is dead, so the robot must be stopped.

In such robotics case, empty PointCloud2 has proper meaning which is different from no-data.

**Comment by mvieth** [comment]
Thanks for the explanation, that sounds reasonable. If @larshg is fine with removing the warning then I am as well.

**Comment by larshg** [comment]
Sure go ahead.

**Comment by at-wat** [comment]
Thank you!

**Comment by felixf4xu** [comment]
I happened to have pcl 1.14 (ubuntu 24.04's default), what's the workaround for me to disable the warning now?
