### ISSUE TITLE
Octree boundary problem

### ISSUE THREAD

**Issue by liyuping0906** [PointCloudLibrary/pcl#6096]
When I used ubuntu20.04 and ros-noetic to filter the robot base location, an octree error occurred. As shown in the picture below, we are here to find a solution to this error,thanks a lot.

![1100](https://github.com/user-attachments/assets/019f3636-418c-49c3-86f5-d1792560ff4c)

**Comment by mvieth** [comment]
@liyuping0906 The error suggests that the program tried to access a point outside of the octree bounding box (in z direction). If you want me to guess why this happens, I need more information. You should run your program with a debugger (like gdb) to get a backtrace. What exactly are you running there? I see rviz, but are you using some plugin that uses PCL's octree? If you wrote your own code, I need to see the places where you call PCL's octree.

**Comment by mvieth** [comment]
Closing because of no response
