### ISSUE TITLE
‘kdtree’ is predetermined ‘shared’ for ‘shared’

### ISSUE THREAD

**Issue by usama0300854** [PointCloudLibrary/pcl#6098]
Built target pcl_extract_feature
[ 77%] Building CXX object keypoints/CMakeFiles/pcl_keypoints.dir/src/narf_keypoint.cpp.o
In file included from /home/usama/kinect_v2_ws/src/pcl/registration/include/pcl/registration/gicp.h:541,
                 from /home/usama/kinect_v2_ws/src/pcl/registration/src/gicp.cpp:40:
/home/usama/kinect_v2_ws/src/pcl/registration/include/pcl/registration/impl/gicp.hpp: In member function ‘void pcl::GeneralizedIterativeClosestPoint<PointSource, PointTarget, Scalar>::computeCovariances(typename pcl::PointCloud<PointTDiff>::ConstPtr, typename pcl::search::KdTree<PointT>::Ptr, pcl::GeneralizedIterativeClosestPoint<PointSource, PointTarget, Scalar>::MatricesVector&)’:
/home/usama/kinect_v2_ws/src/pcl/registration/include/pcl/registration/impl/gicp.hpp:97:56: error: ‘kdtree’ is predetermined ‘shared’ for ‘shared’
         firstprivate(mean, cov, nn_indices, nn_dist_sq)
                                                        ^
make[2]: *** [registration/CMakeFiles/pcl_registration.dir/build.make:384: registration/CMakeFiles/pcl_registration.dir/src/gicp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1293: registration/CMakeFiles/pcl_registration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by usama0300854** [comment]
error is gone when i remove kdtree from file registration/include/pcl/registration/impl/   gicp.hpp.

change line no : 97 : firstprivate(mean, cov, nn_indices, nn_dist_sq)

**Comment by mvieth** [comment]
@usama0300854 Which compiler are you using? Which version?
