### ISSUE TITLE
Update our clang-tidy github action

### ISSUE THREAD

**Issue by mvieth** [PointCloudLibrary/pcl#6115]
See https://github.com/PointCloudLibrary/pcl/blob/master/.github/workflows/clang-tidy.yml
- 22.04 -> 24.04
- `actions/checkout@v3` -> `actions/checkout@v4`
- clang-14 -> clang-18
- See if the action now gives any new errors, and fix those to make the action succeed

**Comment by DIlkhush00** [comment]
Hey @mvieth , I would like to do the changes you mentioned

**Comment by mvieth** [comment]
@DIlkhush00 Great, feel free to open a pull request.
