### ISSUE TITLE
CMake Error: Could not find CMAKE_ROOT !!!

### ISSUE THREAD

**Issue by MortezaHG** [PointCloudLibrary/pcl#6130]
When I run `.\vcpkg install pcl` I get this error:

Computing installation plan...
command:
"C:\Windows\System32\vcpkg\downloads\tools\cmake-3.29.2-windows\cmake-3.29.2-windows-i386/bin/cmake.exe" -DVCPKG_ROOT_DIR=C:/Windows/System32/vcpkg -DPACKAGES_DIR=C:/Windows/System32/vcpkg/packages -DBUILDTREES_DIR=C:/Windows/System32/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Windows/System32/vcpkg/installed -DDOWNLOADS=C:/Windows/System32/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Windows\System32\vcpkg\buildtrees\0.vcpkg_dep_info.cmake"
failed with the following output:
CMake Error: Could not find CMAKE_ROOT !!!, CMake has most likely not been installed correctly., Modules directory not found in, C:/Windows/System32/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/share/cmake-3.29, CMake Error: Not a file: C:\Windows\System32\vcpkg\buildtrees\0.vcpkg_dep_info.cmake, CMake Error: Error processing file: C:\Windows\System32\vcpkg\buildtrees\0.vcpkg_dep_info.cmake

**Comment by larshg** [comment]
Seems more like a [vcpkg issue](https://github.com/microsoft/vcpkg), so please open a issue there.

**Comment by larshg** [comment]
Simliar issue here https://github.com/microsoft/vcpkg/issues/17188.

Also it seems you installed vcpkg in c:\windows\system32 - that could probably lead to some permission issues.
