### ISSUE TITLE
pcl::on_nurbs::FittingSurface::~FittingSurface() crash

### ISSUE THREAD

**Issue by sushilk-pcl** [PointCloudLibrary/pcl#6146]
We are trying to fit the bsp surface on region of mesh body.
bellow are the function calls done from PCL and at the end of function it crash in the
pcl::on_nurbs::FittingSurface::~FittingSurface()

::pcl::on_nurbs::FittingSurface::Parameter params;
::pcl::on_nurbs::NurbsDataSurface data;
::pcl::on_nurbs::FittingSurface::initNurbsPCABoundingBox(order, &data);
::pcl::on_nurbs::FittingSurface fit(&data, nurbs);

will provide more information in case if needed.

Which operating system do you use?
Windows 11 Enterprise,
OS Version 22631.3880.

Which PCL version do you use? How did you install it?
pcl-1.14.1

Which compiler do you use?
Microsoft Visual Studio 2022 LTSC 17.4.

Which PCL version do you use? How did you install it?
pcl-1.14.1

partSvcD.dll!Eigen::internal::aligned_free(void * ptr) Line 208 C++
partSvcD.dll!Eigen::internal::conditional_aligned_free<1>(void * ptr) Line 260 C++
partSvcD.dll!Eigen::internal::conditional_aligned_delete_auto<double,1>(double * ptr, unsigned __int64 size) Line 447 C++
partSvcD.dll!Eigen::DenseStorage<double,-1,-1,-1,0>::~DenseStorage<double,-1,-1,-1,0>() Line 465 C++
partSvcD.dll!Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>>::~PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>>() C++
partSvcD.dll!Eigen::Matrix<double,-1,-1,0,-1,-1>::~Matrix<double,-1,-1,0,-1,-1>() C++
partSvcD.dll!pcl::on_nurbs::NurbsSolve::~NurbsSolve() C++
partSvcD.dll!pcl::on_nurbs::FittingSurface::~FittingSurface() Line 110 C++

**Comment by larshg** [comment]
How did you install PCL?
How do you make your VS project - cmake? Manual setup of VS++ project?

**Comment by larshg** [comment]
Please keep the info in the same issue instead of writing in both. You could have reopened the first one you made.

**Comment by mvieth** [comment]
@sushilk-pcl Are you going to answer the questions from Lars' comment? Otherwise I will close this issue because there is currently not enough information to give a solution to your problem.

**Comment by mvieth** [comment]
Closing due to no response. My best guess would be that you are not using CMake and are therefore missing some compiler flags that CMake would automatically set correctly.

**Comment by sushilk-pcl** [comment]
We took the precompiled libs from toolkit and integrated it directly.
Should we change this process?

**Comment by sushilk-pcl** [comment]
any suggestion on this

**Comment by larshg** [comment]
Have you enabled AVX in your project?
