### ISSUE TITLE
"Cannot open source file: 'flann/util/params.h': No such file or directory

### ISSUE THREAD

**Issue by VisionLab3** [PointCloudLibrary/pcl#6149]
Hi there, disclosing that I wasn't the one who downloaded PCL on my desktop and thus I am not aware of vcpkg or all-in-one installer etc. 
I am unable to build the code and the only error that I see is "Cannot open source file: 'flann/util/params.h': No such file or directory.
Things I have tried:
- changing the include statement
- bringing in the flann sub-folder from flann and placing it next to the pcl lib (did this since the include statement says "#include <flann/util/params.h>")

Please tell me what else I can try, I'll try my best to provide you with all the info you could need to help me.
Thank You.

**Comment by larshg** [comment]
Please ask for help for this on Discord or Stackoverflow. These issues are only if you think there is a bug in PCL.
Read the tutorials if you use VCPKG. Find the already existing issue about setting up if you use All-In-One installer.
You cant just copy libraries next to your build/source folder.
To get proper help, you'll need to tell if you use Cmake(advise to do so) or if you manually have set up a VS project etc.

Ill close the issue, but you can comment if you like.
