### ISSUE TITLE
pointclouds.org Download page obfuscates  source code

### ISSUE THREAD

**Issue by gdt** [PointCloudLibrary/pcl#6156]
For background, I package a number of geo things for pkgsrc, a multi-os multi-cpu packaging system.   Recently, the pcl package stopped building, and from the error I guessed it was about not being new enough for the latest boost. 

I went to https://pointclouds.org/downloads/ to find out how to download the library and find out the current version.  For me, as should be normal in the open source world, this means downloading the source code.   That page instead gives instructions about how to install binaries using a number of packaging systems.

The page did not contain a link to download tarballs of the current and previous release, and did not give the version number of the latest release.   This lack is a defect, and hence the issue.

(Yes, I was able to find the github page for pointcloud projects in general and then guess which repo was the right one, and so on, but "ignore the project's website and look on github" is not a reasonable approach.)

To fix, adjust the website to be source first and then give packaging system advice.

**Comment by mvieth** [comment]
Hi, to be honest, I kind of disagree with your view that pointclouds.org obfuscates/hides the source code. On the starting page, the GitHub is mentioned: "An additional Wiki resource for developers is available at https://github.com/PointCloudLibrary/pcl/wiki.". The downloads page mentions "[...] in our [Releases](https://github.com/PointCloudLibrary/pcl/releases) page on our [GitHub repository](https://github.com/PointCloudLibrary/pcl)". Admittedly, there is indeed no separate "Source Code" section on the downloads page which makes finding the GitHub completely obvious, so I will add that someday.

**Comment by gdt** [comment]
I won't debate what is there.  I only meant that my subjective experience was that on going to the downloads page, I expected to find the source code as the most prominent thing, and it was non-obvious.    Thanks for listening and it would be great to make a source section and put it first.

**Comment by mvieth** [comment]
Added section "Source code" to downloads page
