### ISSUE TITLE
How to decide the sign of pca calculation?

### ISSUE THREAD

**Issue by 1404561326521** [PointCloudLibrary/pcl#6163]
PCL 1.13.0
Visual Studio 2019

I want to use pcl::PCA to calculate the principal component of the point cloud data so as to adjust the posture of the point cloud. However, the positive and negative symbols of the calculated principal component vector are different from the directions of pca in sklearn in python, and there will be a problem that one or two principal component vectors are opposite. The principal component calculated in python is what I need. I want to know how to solve the sign problem in pcl, is there any way to control the sign of the principal component vector? Thank you very much!

PCL
`
#include <iostream>
#include <pcl/io/ply_io.h>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>
#include <pcl/common/pca.h>

int main() {
    
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
    std::string file_path = "E:/Desktop/pose_cloud_data/3D_martixpred_src/train/sample_model/3_lower_16_transformed.ply";

    
    if (pcl::io::loadPLYFile<pcl::PointXYZ>(file_path, *cloud) == -1) {
        std::cerr << "read error: " << file_path << std::endl;
        return -1;
    }

    pcl::PCA<pcl::PointXYZ> pca;
    pca.setInputCloud(cloud);

    Eigen::Matrix3f eigenvectors = pca.getEigenVectors().transpose();
    Eigen::Vector3f eigenvalues = pca.getEigenValues();   

    std::cout << "eigenvectors:\n" << eigenvectors << std::endl;
    std::cout << "eigenvalues:\n" << eigenvalues.transpose() << std::endl;

    return 0;
}
`
pcl result:
`eigenvectors:
 0.626321  0.434546 -0.647218
-0.761413  0.519113 -0.388293
 0.167248  0.735997     0.656
eigenvalues:
401.454   186.1 13.3162`

 python
`import numpy as np
from sklearn.decomposition import PCA
import open3d as o3d

pcd = o3d.io.read_point_cloud(r"E:\Desktop\pose_cloud_data\3D_martixpred_src\train\sample_model/3_lower_16_transformed.ply")
points = np.asarray(pcd.points)

pca = PCA(n_components=3)
pca.fit(points)

print("components_:\n", pca.components_)
print("explained_variance_:\n", pca.explained_variance_)
`
python sklearn result:
`components_:
 [[ 0.62632135  0.43454578 -0.64721831]
 [ 0.76141288 -0.51911326  0.38829351]
 [-0.1672483  -0.73599687 -0.65600047]]
explained_variance_:
 [401.45444616 186.10030778  13.31626398]`

**Comment by mvieth** [comment]
The solutions from PCL and sklearn are equally valid, they are just rotated by 180 degrees around the first principal component.
See also:
https://stats.stackexchange.com/questions/30348/is-it-acceptable-to-reverse-a-sign-of-a-principal-component-score/30352#30352
https://stats.stackexchange.com/questions/39073/are-pca-solutions-unique
