### ISSUE TITLE
[compile error] Calculating FPFH/PFH descriptor pointer error in version PCL1.14

### ISSUE THREAD

**Issue by dancelycs** [PointCloudLibrary/pcl#6164]
Using the method on the official website, a pointer error occurred at the end of the calculation, but the relevant descriptors have already been calculated!!!!!
Expression: _CrtlsValidHeapPointer(block)

#include <pcl/point_types.h>
#include <pcl/features/pfh.h>

{
  pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
  pcl::PointCloud<pcl::Normal>::Ptr normals (new pcl::PointCloud<pcl::Normal> ());

  ... read, pass in or create a point cloud with normals ...
  ... (note: you can create a single PointCloud<PointNormal> if you want) ...

  // Create the PFH estimation class, and pass the input dataset+normals to it
  pcl::PFHEstimation<pcl::PointXYZ, pcl::Normal, pcl::PFHSignature125> pfh;
  pfh.setInputCloud (cloud);
  pfh.setInputNormals (normals);
  // alternatively, if cloud is of tpe PointNormal, do pfh.setInputNormals (cloud);

  // Create an empty kdtree representation, and pass it to the PFH estimation object.
  // Its content will be filled inside the object, based on the given input dataset (as no other search surface is given).
  pcl::search::KdTree<pcl::PointXYZ>::Ptr tree (new pcl::search::KdTree<pcl::PointXYZ> ());
  //pcl::KdTreeFLANN<pcl::PointXYZ>::Ptr tree (new pcl::KdTreeFLANN<pcl::PointXYZ> ()); -- older call for PCL 1.5-
  pfh.setSearchMethod (tree);

  // Output datasets
  pcl::PointCloud<pcl::PFHSignature125>::Ptr pfhs (new pcl::PointCloud<pcl::PFHSignature125> ());

  // Use all neighbors in a sphere of radius 5cm
  // IMPORTANT: the radius used here has to be larger than the radius used to estimate the surface normals!!!
  pfh.setRadiusSearch (0.05);

  // Compute the features
  pfh.compute (*pfhs);
  // pfhs->size () should have the same size as the input cloud->size ()*
}

**Comment by mvieth** [comment]
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use? Do you use CMake?
- You marked this as a "compile error". Does the problem really happen during compilation, or does it happen when you run the program?

**Comment by mvieth** [comment]
Did you enable AVX and/or AVX2 for the compilation of the code? We usually highly recommend using CMake because it automatically handles these options.

**Comment by dancelycs** [comment]
Thank you very much, it was in the 'not set' state before.
