### ISSUE TITLE
[visualization] libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by hclzer** [PointCloudLibrary/pcl#6168]
When I ran the normal_estimation_using_integral_images in the tutorial, there is a warning of libpng warning: ICCP: Known Incorrect SRGB Profile, and nothing is displayed.
**The environment is:**
OS: Windows 11
Compiler: MSVC2022_64
PS D:\> vcpkg list
boost-accumulators:x64-windows                    1.86.0              Boost accumulators module
boost-algorithm:x64-windows                       1.86.0              Boost algorithm module
boost-align:x64-windows                           1.86.0              Boost align module
boost-any:x64-windows                             1.86.0              Boost any module
boost-array:x64-windows                           1.86.0              Boost array module
boost-asio:x64-windows                            1.86.0              Boost asio module
boost-assert:x64-windows                          1.86.0              Boost assert module
boost-atomic:x64-windows                          1.86.0              Boost atomic module
boost-bimap:x64-windows                           1.86.0              Boost bimap module
boost-bind:x64-windows                            1.86.0              Boost bind module
boost-chrono:x64-windows                          1.86.0              Boost chrono module
boost-circular-buffer:x64-windows                 1.86.0              Boost circular_buffer module
boost-cmake:x64-windows                           1.86.0              Boost CMake support infrastructure
boost-compute:x64-windows                         1.86.0              Boost compute module
boost-concept-check:x64-windows                   1.86.0              Boost concept_check module
boost-config:x64-windows                          1.86.0              Boost config module
boost-container-hash:x64-windows                  1.86.0              Boost container_hash module
boost-container:x64-windows                       1.86.0              Boost container module
boost-context:x64-windows                         1.86.0              Boost context module
boost-conversion:x64-windows                      1.86.0              Boost conversion module
boost-core:x64-windows                            1.86.0              Boost core module
boost-coroutine:x64-windows                       1.86.0              Boost coroutine module
boost-date-time:x64-windows                       1.86.0              Boost date_time module
boost-describe:x64-windows                        1.86.0              Boost describe module
boost-detail:x64-windows                          1.86.0              Boost detail module
boost-dynamic-bitset:x64-windows                  1.86.0              Boost dynamic_bitset module
boost-endian:x64-windows                          1.86.0              Boost endian module
boost-exception:x64-windows                       1.86.0              Boost exception module
boost-filesystem:x64-windows                      1.86.0              Boost filesystem module
boost-foreach:x64-windows                         1.86.0              Boost foreach module
boost-format:x64-windows                          1.86.0              Boost format module
boost-function-types:x64-windows                  1.86.0              Boost function_types module
boost-function:x64-windows                        1.86.0              Boost function module
boost-functional:x64-windows                      1.86.0              Boost functional module
boost-fusion:x64-windows                          1.86.0              Boost fusion module
boost-graph:x64-windows                           1.86.0              Boost graph module
boost-headers:x64-windows                         1.86.0              Boost headers module
boost-integer:x64-windows                         1.86.0              Boost integer module
boost-interprocess:x64-windows                    1.86.0              Boost interprocess module
boost-interval:x64-windows                        1.86.0              Boost interval module
boost-intrusive:x64-windows                       1.86.0              Boost intrusive module
boost-io:x64-windows                              1.86.0              Boost io module
boost-iostreams:x64-windows                       1.86.0              Boost iostreams module
boost-iostreams[bzip2]:x64-windows                                    Support bzip2 filters
boost-iostreams[lzma]:x64-windows                                     Support LZMA/xz filters
boost-iostreams[zlib]:x64-windows                                     Support zlib filters
boost-iostreams[zstd]:x64-windows                                     Support zstd filters
boost-iterator:x64-windows                        1.86.0              Boost iterator module
boost-lambda:x64-windows                          1.86.0              Boost lambda module
boost-lexical-cast:x64-windows                    1.86.0              Boost lexical_cast module
boost-logic:x64-windows                           1.86.0              Boost logic module
boost-math:x64-windows                            1.86.0              Boost math module
boost-move:x64-windows                            1.86.0              Boost move module
boost-mp11:x64-windows                            1.86.0              Boost mp11 module
boost-mpl:x64-windows                             1.86.0              Boost mpl module
boost-multi-array:x64-windows                     1.86.0              Boost multi_array module
boost-multi-index:x64-windows                     1.86.0              Boost multi_index module
boost-numeric-conversion:x64-windows              1.86.0              Boost numeric_conversion module
boost-optional:x64-windows                        1.86.0              Boost optional module
boost-parameter:x64-windows                       1.86.0              Boost parameter module
boost-phoenix:x64-windows                         1.86.0              Boost phoenix module
boost-pool:x64-windows                            1.86.0              Boost pool module
boost-predef:x64-windows                          1.86.0              Boost predef module
boost-preprocessor:x64-windows                    1.86.0              Boost preprocessor module
boost-property-map:x64-windows                    1.86.0              Boost property_map module
boost-property-tree:x64-windows                   1.86.0              Boost property_tree module
boost-proto:x64-windows                           1.86.0              Boost proto module
boost-ptr-container:x64-windows                   1.86.0              Boost ptr_container module
boost-random:x64-windows                          1.86.0              Boost random module
boost-range:x64-windows                           1.86.0              Boost range module
boost-ratio:x64-windows                           1.86.0              Boost ratio module
boost-regex:x64-windows                           1.86.0              Boost regex module
boost-scope:x64-windows                           1.86.0              Boost scope module
boost-serialization:x64-windows                   1.86.0              Boost serialization module
boost-signals2:x64-windows                        1.86.0              Boost signals2 module
boost-smart-ptr:x64-windows                       1.86.0              Boost smart_ptr module
boost-sort:x64-windows                            1.86.0              Boost sort module
boost-spirit:x64-windows                          1.86.0              Boost spirit module
boost-static-assert:x64-windows                   1.86.0              Boost static_assert module
boost-system:x64-windows                          1.86.0              Boost system module
boost-thread:x64-windows                          1.86.0              Boost thread module
boost-throw-exception:x64-windows                 1.86.0              Boost throw_exception module
boost-tokenizer:x64-windows                       1.86.0              Boost tokenizer module
boost-tti:x64-windows                             1.86.0              Boost tti module
boost-tuple:x64-windows                           1.86.0              Boost tuple module
boost-type-index:x64-windows                      1.86.0              Boost type_index module
boost-type-traits:x64-windows                     1.86.0              Boost type_traits module
boost-typeof:x64-windows                          1.86.0              Boost typeof module
boost-ublas:x64-windows                           1.86.0              Boost ublas module
boost-uninstall:x64-windows                       1.86.0              Internal vcpkg port used to uninstall Boost
boost-unordered:x64-windows                       1.86.0              Boost unordered module
boost-utility:x64-windows                         1.86.0              Boost utility module
boost-uuid:x64-windows                            1.86.0              Boost uuid module
boost-variant2:x64-windows                        1.86.0              Boost variant2 module
boost-variant:x64-windows                         1.86.0              Boost variant module
boost-winapi:x64-windows                          1.86.0              Boost winapi module
boost-xpressive:x64-windows                       1.86.0              Boost xpressive module
brotli:x64-windows                                1.1.0#1             a generic-purpose lossless compression algorithm...
bzip2:x64-windows                                 1.0.8#6             bzip2 is a freely available, patent free, high-q...
bzip2[tool]:x64-windows                                               Builds bzip2 executable
cereal:x64-windows                                1.3.2#1             a header-only C++11 serialization library (built...
cgns:x64-windows                                  4.4.0               The CFD General Notation System (CGNS) provides ...
cgns[hdf5]:x64-windows                                                Enable hdf5 support
cgns[lfs]:x64-windows                                                 Enable LFS support
cgns[lfsselector]:x64-windows                                         Selector for LFS
cuda:x64-windows                                  10.1#13             A parallel computing platform and programming model
curl:x64-windows                                  8.11.0#1            A library for transferring data with URLs
curl[non-http]:x64-windows                                            Enables protocols beyond HTTP/HTTPS/HTTP2
curl[schannel]:x64-windows                                            SSL support (Secure Channel)
curl[ssl]:x64-windows                                                 Default SSL backend
curl[sspi]:x64-windows                                                SSPI support
dbus:x64-windows                                  1.15.8#5            D-Bus specification and reference implementation...
double-conversion:x64-windows                     3.3.0               Efficient binary-decimal and decimal-binary conv...
egl-registry:x64-windows                          2024-01-25          EGL API and Extension Registry
eigen3:x64-windows                                3.4.0#4             C++ template library for linear algebra: matrice...
expat:x64-windows                                 2.6.3               XML parser library written in C
exprtk:x64-windows                                2022-01-01#2        Simple to use, easy to integrate and extremely e...
fast-float:x64-windows                            6.1.6               Fast and exact implementation of the C++ from_ch...
flann:x64-windows                                 2019-04-07#7        Fast Library for Approximate Nearest Neighbors
fmt:x64-windows                                   11.0.2#1            {fmt} is an open-source formatting library provi...
freetype:x64-windows                              2.13.3              A library to render fonts.
freetype[brotli]:x64-windows                                          Support decompression of WOFF2 streams
freetype[bzip2]:x64-windows                                           Support bzip2 compressed fonts.
freetype[png]:x64-windows                                             Support PNG compressed OpenType embedded bitmaps.
freetype[zlib]:x64-windows                                            Use zlib instead of internal library for DEFLATE
gklib:x64-windows                                 2023-03-27          General helper libraries for KarypisLab.
glew:x64-windows                                  2.2.0#4             The OpenGL Extension Wrangler Library (GLEW) is ...
harfbuzz:x64-windows                              10.1.0              HarfBuzz OpenType text shaping engine
harfbuzz[freetype]:x64-windows                                        Enable FreeType support
hdf5:x64-windows                                  1.14.4.3#2          HDF5 is a data model, library, and file format f...
hdf5[szip]:x64-windows                                                Build with szip
hdf5[tools]:x64-windows                                               Build hdf tools
hdf5[zlib]:x64-windows                                                Build with zlib
icu:x64-windows                                   74.2#4              Mature and widely used Unicode and localization ...
icu[tools]:x64-windows                                                Build tools
jsoncpp:x64-windows                               1.9.6               JsonCpp is a C++ library that allows manipulatin...
kinectsdk1:x64-windows                            1.8#8               Kinect for Windows SDK for Kinect v1 sensor.
libharu:x64-windows                               2.4.4#1             libharu - free PDF library
libiconv:x64-windows                              1.17#4              GNU Unicode text conversion
libjpeg-turbo:x64-windows                         3.0.4               libjpeg-turbo is a JPEG image codec that uses SI...
liblzma:x64-windows                               5.6.3               Compression library with an API similar to that ...
libogg:x64-windows                                1.3.5#1             Ogg is a multimedia container format, and the na...
libpng:x64-windows                                1.6.43#3            libpng is a library implementing an interface fo...
libpq:x64-windows                                 16.4                The official database access API of postgresql
libpq[lz4]:x64-windows                                                Use lz4
libpq[openssl]:x64-windows                                            support for encrypted client connections and ran...
libpq[zlib]:x64-windows                                               Use zlib
libtheora:x64-windows                             1.2.0alpha1-2...    Theora is a free and open video compression form...
libusb:x64-windows                                1.0.27#2            a cross-platform library to access USB devices
libxml2:x64-windows                               2.11.9              Libxml2 is the XML C parser and toolkit develope...
libxml2[iconv]:x64-windows                                            Add ICONV support
libxml2[lzma]:x64-windows                                             Use LZMA
libxml2[zlib]:x64-windows                                             Use ZLib
lz4:x64-windows                                   1.10.0              Lossless compression algorithm, providing compre...
metis:x64-windows                                 2022-07-27          Serial Graph Partitioning and Fill-reducing Matr...
netcdf-c:x64-windows                              4.8.1#5             A set of self-describing, machine-independent da...
netcdf-c[dap]:x64-windows                                             Build with DAP remote access client support
netcdf-c[hdf5]:x64-windows                                            Build with HDF5 support
netcdf-c[nczarr]:x64-windows                                          Build with NCZarr cloud storage access support
netcdf-c[netcdf-4]:x64-windows                                        Build with netCDF-4 support
nlohmann-json:x64-windows                         3.11.3#1            JSON for Modern C++
opengl-registry:x64-windows                       2024-02-10#1        OpenGL, OpenGL ES, and OpenGL ES-SC API and Exte...
opengl:x64-windows                                2022-12-04#3        Open Graphics Library (OpenGL)[3][4][5] is a cro...
openni2:x64-windows                               2.2.0.33#15         OpenNI is open source library for access to Natu...
openssl:x64-windows                               3.4.0               OpenSSL is an open source project that provides ...
pcl:x64-windows                                   1.14.1#3            Point Cloud Library (PCL) is open source library...
pcl[apps]:x64-windows                                                 Build application examples/samples that show how...
pcl[cuda]:x64-windows                                                 CUDA support for PCL
pcl[examples]:x64-windows                                             Build PCL examples
pcl[libusb]:x64-windows                                               Build USB RGBD-Camera drivers
pcl[opengl]:x64-windows                                               OpenGL support for PCL
pcl[openni2]:x64-windows                                              OpenNI2 support for PCL
pcl[pcap]:x64-windows                                                 PCAP support for PCL
pcl[qt]:x64-windows                                                   Qt support for PCL
pcl[simulation]:x64-windows                                           Build Point Cloud Library Simulation
pcl[surface-on-nurbs]:x64-windows                                     Fitting NURBS to point clouds
pcl[tools]:x64-windows                                                Build PCL utilities
pcl[visualization]:x64-windows                                        Build visualization
pcl[vtk]:x64-windows                                                  An alias for visualization
pcre2:x64-windows                                 10.43               Regular Expression pattern matching using the sa...
pcre2[jit]:x64-windows                                                Enable support for Just-In-Time compiling regex ...
pcre2[platform-default-features]:x64-windows                          Enable default features
pegtl:x64-windows                                 3.2.8               The Parsing Expression Grammar Template Library ...
pkgconf:x64-windows                               2.3.0               pkgconf is a program which helps to configure co...
proj:x64-windows                                  9.5.0               PROJ library for cartographic projections
proj[net]:x64-windows                                                 Enable network support
proj[tiff]:x64-windows                                                Enable TIFF support to read some grids
pugixml:x64-windows                               1.14                Light-weight, simple and fast XML parser for C++...
qhull:x64-windows                                 8.0.2#5             computes the convex hull, Delaunay triangulation...
qtbase:x64-windows                                6.7.3#1             Qt Base (Core, Gui, Widgets, Network, ...)
qtbase[brotli]:x64-windows                                            Support for downloading and decompressing resour...
qtbase[concurrent]:x64-windows                                        Provides a high-level multi-threading API. Qt Co...
qtbase[dbus]:x64-windows                                              Qt D-Bus
qtbase[default-features]:x64-windows                                  Platform-dependent default features
qtbase[dnslookup]:x64-windows                                         Enable DNS lookup support
qtbase[doubleconversion]:x64-windows                                  Enable double conversion support
qtbase[freetype]:x64-windows                                          Supports the FreeType 2 font engine (and its sup...
qtbase[gui]:x64-windows                                               Qt Gui
qtbase[harfbuzz]:x64-windows                                          Use harfbuzz
qtbase[icu]:x64-windows                                               Enable ICU support
qtbase[jpeg]:x64-windows                                              Enable JPEG
qtbase[network]:x64-windows                                           Qt Network
qtbase[opengl]:x64-windows                                            OpenGL
qtbase[openssl]:x64-windows                                           Enable OpenSSL
qtbase[pcre2]:x64-windows                                             Enable PCRE2 support
qtbase[png]:x64-windows                                               Enable PNG
qtbase[sql-psql]:x64-windows                                          Enable SQL Driver psql
qtbase[sql-sqlite]:x64-windows                                        Enable SQL Driver sqlite
qtbase[sql]:x64-windows                                               Qt Sql
qtbase[testlib]:x64-windows                                           Qt Testlib
qtbase[thread]:x64-windows                                            Thread support; provides QThread and related cla...
qtbase[widgets]:x64-windows                                           Qt Widgets
qtbase[zstd]:x64-windows                                              Zstandard support
qtdeclarative:x64-windows                         6.7.3               Qt Declarative (Quick 2)
qtlanguageserver:x64-windows                      6.7.3               An implementation of the Language Server Protocol.
qtshadertools:x64-windows                         6.7.3               The Qt Shader Tools module is designed to provid...
qtsvg:x64-windows                                 6.7.3               Qt SVG provides classes for rendering and displa...
seacas:x64-windows                                2022-11-22#7        The Sandia Engineering Analysis Code Access Syst...
sqlite3:x64-windows                               3.47.0#2            SQLite is a software library that implements a s...
sqlite3[json1]:x64-windows                                            Enable JSON functionality for sqlite3
sqlite3[tool]:x64-windows                                             Build sqlite3 executable
szip:x64-windows                                  2.1.1#12            Szip compression software, providing lossless co...
tiff:x64-windows                                  4.7.0               A library that supports the manipulation of TIFF...
tiff[jpeg]:x64-windows                                                Support JPEG compression in TIFF image files
tiff[lzma]:x64-windows                                                Support LZMA compression in TIFF image files
tiff[zip]:x64-windows                                                 Support ZIP/deflate compression in TIFF image files
utfcpp:x64-windows                                4.0.5               UTF-8 with C++ in a Portable Way
vcpkg-boost:x64-windows                           2024-05-15
vcpkg-cmake-config:x64-windows                    2024-05-23
vcpkg-cmake-get-vars:x64-windows                  2024-09-22
vcpkg-cmake:x64-windows                           2024-04-23
vcpkg-msbuild:x64-windows                         2023-08-08
vcpkg-pkgconfig-get-modules:x64-windows           2024-04-03
vcpkg-tool-lessmsi:x64-windows                    1.10.0#1            This is a utility with a graphical user interfac...
vcpkg-tool-meson:x64-windows                      1.6.0               Meson build system
verdict:x64-windows                               1.4.0               Compute quality functions of 2 and 3-dimensional...
vtk:x64-windows                                   9.3.0-pv5.12.1#5    Software system for 3D computer graphics, image ...
vtk[cgns]:x64-windows                                                 CGNS functionality for VTK
vtk[libharu]:x64-windows                                              PDF functionality for VTK
vtk[libtheora]:x64-windows                                            Compressed ogg functionality for VTK
vtk[netcdf]:x64-windows                                               NetCDF functionality for VTK
vtk[opengl]:x64-windows                                               All opengl related modules
vtk[proj]:x64-windows                                                 Geographic projection functionality for VTK
vtk[qt]:x64-windows                                                   Qt functionality for VTK
vtk[seacas]:x64-windows                                               Exodus and IOSS functionality for VTK
vtk[sql]:x64-windows                                                  SQL functionality for VTK
winpcap:x64-windows                               4.1.3#12            WinPcap is the industry-standard tool for link-l...
zlib:x64-windows                                  1.3.1               A compression library
zstd:x64-windows                                  1.5.6               Zstandard - Fast real-time compression algorithm

![QQ20241114-003233](https://github.com/user-attachments/assets/247b1807-529b-478a-8c19-3821c96ac226)

**Comment by mvieth** [comment]
@hclzer Have you tried to zoom out or move the camera around, to make sure there is really nothing displayed? To my knowledge, that is just a warning which can be ignored.

**Comment by hclzer** [comment]
> @hclzer Have you tried to zoom out or move the camera around, to make sure there is really nothing displayed? To my knowledge, that is just a warning which can be ignored.

I tried, it still displayed nothing.

**Comment by hclzer** [comment]
> @hclzer Have you tried to zoom out or move the camera around, to make sure there is really nothing displayed? To my knowledge, that is just a warning which can be ignored.

I change x64-Debug to x64-Release, it displays! Thank you!
