### ISSUE TITLE
[make error] make error at point_types.hpp

### ISSUE THREAD

**Issue by YeHuanjie** [PointCloudLibrary/pcl#6170]
In file included from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/point_types.h:354:0,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/src/point_types.cpp:37:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::RGB::RGB(uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:397:128: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
     inline constexpr RGB (std::uint8_t _r, std::uint8_t _g, std::uint8_t _b, std::uint8_t _a = 255) : _RGB{{{{_b, _g, _r, _a}}}} {}
                                                                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity::Intensity(float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:416:80: error: could not convert ‘_intensity’ from ‘float’ to ‘pcl::_Intensity::<anonymous struct>’
     inline constexpr Intensity (float _intensity = 0.f) : _Intensity{_intensity} {}
                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity8u::Intensity8u(uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:436:89: error: could not convert ‘_intensity’ from ‘uint8_t {aka unsigned char}’ to ‘pcl::_Intensity8u::<anonymous struct>’
     inline constexpr Intensity8u (std::uint8_t _intensity = 0) : _Intensity8u{_intensity} {}
                                                                                         ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity32u::Intensity32u(uint32_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:462:92: error: could not convert ‘_intensity’ from ‘uint32_t {aka unsigned int}’ to ‘pcl::_Intensity32u::<anonymous struct>’
     inline constexpr Intensity32u (std::uint32_t _intensity = 0) : _Intensity32u{_intensity} {}
                                                                                            ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBA::PointXYZRGBA(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:569:135: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
                          std::uint8_t _g, std::uint8_t _b, std::uint8_t _a) : _PointXYZRGBA{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}} {}
                                                                                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGB::PointXYZRGB(float, float, float, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:636:63: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGB{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, 255}}}} {}
                                                               ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBL::PointXYZRGBL(float, float, float, uint8_t, uint8_t, uint8_t, uint32_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:660:71: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGBL{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}, _label} {}
                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:964:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:973:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZLNormal::PointXYZLNormal(float, float, float, uint32_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1059:7: warning: narrowing conversion of ‘_label’ from ‘uint32_t {aka unsigned int}’ to ‘float’ inside { } [-Wnarrowing]
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointSurfel::PointSurfel(float, float, float, float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1711:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       } {}
       ^
In file included from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/point_types.h:354:0,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/copy_point.hpp:40,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/copy_point.h:58,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/io.hpp:45,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/io.h:571,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/src/PCLPointCloud2.cpp:43:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::RGB::RGB(uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:397:128: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
     inline constexpr RGB (std::uint8_t _r, std::uint8_t _g, std::uint8_t _b, std::uint8_t _a = 255) : _RGB{{{{_b, _g, _r, _a}}}} {}
                                                                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity::Intensity(float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:416:80: error: could not convert ‘_intensity’ from ‘float’ to ‘pcl::_Intensity::<anonymous struct>’
     inline constexpr Intensity (float _intensity = 0.f) : _Intensity{_intensity} {}
                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity8u::Intensity8u(uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:436:89: error: could not convert ‘_intensity’ from ‘uint8_t {aka unsigned char}’ to ‘pcl::_Intensity8u::<anonymous struct>’
     inline constexpr Intensity8u (std::uint8_t _intensity = 0) : _Intensity8u{_intensity} {}
                                                                                         ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity32u::Intensity32u(uint32_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:462:92: error: could not convert ‘_intensity’ from ‘uint32_t {aka unsigned int}’ to ‘pcl::_Intensity32u::<anonymous struct>’
     inline constexpr Intensity32u (std::uint32_t _intensity = 0) : _Intensity32u{_intensity} {}
                                                                                            ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBA::PointXYZRGBA(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:569:135: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
                          std::uint8_t _g, std::uint8_t _b, std::uint8_t _a) : _PointXYZRGBA{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}} {}
                                                                                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGB::PointXYZRGB(float, float, float, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:636:63: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGB{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, 255}}}} {}
                                                               ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBL::PointXYZRGBL(float, float, float, uint8_t, uint8_t, uint8_t, uint32_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:660:71: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGBL{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}, _label} {}
                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:964:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:973:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZLNormal::PointXYZLNormal(float, float, float, uint32_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1059:7: warning: narrowing conversion of ‘_label’ from ‘uint32_t {aka unsigned int}’ to ‘float’ inside { } [-Wnarrowing]
       }
       ^
In file included from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/point_types.h:354:0,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/copy_point.hpp:40,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/copy_point.h:58,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/io.hpp:45,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/io.h:571,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/src/pcl_base.cpp:43:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::RGB::RGB(uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:397:128: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
     inline constexpr RGB (std::uint8_t _r, std::uint8_t _g, std::uint8_t _b, std::uint8_t _a = 255) : _RGB{{{{_b, _g, _r, _a}}}} {}
                                                                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity::Intensity(float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:416:80: error: could not convert ‘_intensity’ from ‘float’ to ‘pcl::_Intensity::<anonymous struct>’
     inline constexpr Intensity (float _intensity = 0.f) : _Intensity{_intensity} {}
                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity8u::Intensity8u(uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:436:89: error: could not convert ‘_intensity’ from ‘uint8_t {aka unsigned char}’ to ‘pcl::_Intensity8u::<anonymous struct>’
     inline constexpr Intensity8u (std::uint8_t _intensity = 0) : _Intensity8u{_intensity} {}
                                                                                         ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity32u::Intensity32u(uint32_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:462:92: error: could not convert ‘_intensity’ from ‘uint32_t {aka unsigned int}’ to ‘pcl::_Intensity32u::<anonymous struct>’
     inline constexpr Intensity32u (std::uint32_t _intensity = 0) : _Intensity32u{_intensity} {}
                                                                                            ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBA::PointXYZRGBA(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:569:135: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
                          std::uint8_t _g, std::uint8_t _b, std::uint8_t _a) : _PointXYZRGBA{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}} {}
                                                                                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGB::PointXYZRGB(float, float, float, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:636:63: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGB{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, 255}}}} {}
                                                               ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBL::PointXYZRGBL(float, float, float, uint8_t, uint8_t, uint8_t, uint32_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:660:71: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGBL{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}, _label} {}
                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:964:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:973:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZLNormal::PointXYZLNormal(float, float, float, uint32_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1059:7: warning: narrowing conversion of ‘_label’ from ‘uint32_t {aka unsigned int}’ to ‘float’ inside { } [-Wnarrowing]
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointSurfel::PointSurfel(float, float, float, float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1711:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       } {}
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointSurfel::PointSurfel(float, float, float, float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1711:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       } {}
       ^
common/CMakeFiles/pcl_common.dir/build.make:78: recipe for target 'common/CMakeFiles/pcl_common.dir/src/point_types.cpp.o' failed
make[2]: *** [common/CMakeFiles/pcl_common.dir/src/point_types.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/point_types.h:354:0,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/copy_point.hpp:40,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/copy_point.h:58,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/impl/io.hpp:45,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/common/io.h:571,
                 from /home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/src/io.cpp:41:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::RGB::RGB(uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:397:128: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
     inline constexpr RGB (std::uint8_t _r, std::uint8_t _g, std::uint8_t _b, std::uint8_t _a = 255) : _RGB{{{{_b, _g, _r, _a}}}} {}
                                                                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity::Intensity(float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:416:80: error: could not convert ‘_intensity’ from ‘float’ to ‘pcl::_Intensity::<anonymous struct>’
     inline constexpr Intensity (float _intensity = 0.f) : _Intensity{_intensity} {}
                                                                                ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity8u::Intensity8u(uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:436:89: error: could not convert ‘_intensity’ from ‘uint8_t {aka unsigned char}’ to ‘pcl::_Intensity8u::<anonymous struct>’
     inline constexpr Intensity8u (std::uint8_t _intensity = 0) : _Intensity8u{_intensity} {}
                                                                                         ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::Intensity32u::Intensity32u(uint32_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:462:92: error: could not convert ‘_intensity’ from ‘uint32_t {aka unsigned int}’ to ‘pcl::_Intensity32u::<anonymous struct>’
     inline constexpr Intensity32u (std::uint32_t _intensity = 0) : _Intensity32u{_intensity} {}
                                                                                            ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBA::PointXYZRGBA(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:569:135: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
                          std::uint8_t _g, std::uint8_t _b, std::uint8_t _a) : _PointXYZRGBA{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}} {}
                                                                                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGB::PointXYZRGB(float, float, float, uint8_t, uint8_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:636:63: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGB{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, 255}}}} {}
                                                               ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBL::PointXYZRGBL(float, float, float, uint8_t, uint8_t, uint8_t, uint32_t, uint8_t)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:660:71: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘uint32_t {aka unsigned int}’ in initialization
       _PointXYZRGBL{{{_x, _y, _z, 1.0f}}, {{{_b, _g, _r, _a}}}, _label} {}
                                                                       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:964:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZRGBNormal::PointXYZRGBNormal(float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:973:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointXYZLNormal::PointXYZLNormal(float, float, float, uint32_t, float, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1059:7: warning: narrowing conversion of ‘_label’ from ‘uint32_t {aka unsigned int}’ to ‘float’ inside { } [-Wnarrowing]
       }
       ^
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp: In constructor ‘constexpr pcl::PointSurfel::PointSurfel(float, float, float, float, float, float, uint8_t, uint8_t, uint8_t, uint8_t, float, float, float)’:
/home/tplink/mechanical_arm/pcl/pcl-1.14.0/common/include/pcl/impl/point_types.hpp:1711:7: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘float’ in initialization
       } {}
       ^
common/CMakeFiles/pcl_common.dir/build.make:106: recipe for target 'common/CMakeFiles/pcl_common.dir/src/PCLPointCloud2.cpp.o' failed
make[2]: *** [common/CMakeFiles/pcl_common.dir/src/PCLPointCloud2.cpp.o] Error 1
common/CMakeFiles/pcl_common.dir/build.make:120: recipe for target 'common/CMakeFiles/pcl_common.dir/src/io.cpp.o' failed
make[2]: *** [common/CMakeFiles/pcl_common.dir/src/io.cpp.o] Error 1
common/CMakeFiles/pcl_common.dir/build.make:92: recipe for target 'common/CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o' failed
make[2]: *** [common/CMakeFiles/pcl_common.dir/src/pcl_base.cpp.o] Error 1
CMakeFiles/Makefile2:1580: recipe for target 'common/CMakeFiles/pcl_common.dir/all' failed
make[1]: *** [common/CMakeFiles/pcl_common.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YeHuanjie** [comment]
with cmake3.31.0 pcl-1.14.0 boost-1.65.0 flann-1.9.2 vtk-7.1.1 eigen-3.3.7

**Comment by mvieth** [comment]
@YeHuanjie Which compiler do you use? Do you set any options in CMake (anything that is not the default)?

**Comment by YeHuanjie** [comment]
GNU5.4.0, default cmake ..

**Comment by YeHuanjie** [comment]
i fixed it by updating g++ from 5.4.0 to 9.0, thanks
