### ISSUE TITLE
Inconsistency in documentation (PointCloud, PCLPointCloud2 related)

### ISSUE THREAD

**Issue by alexeygritsenko** [PointCloudLibrary/pcl#6180]
Hi, I need to use filters for cleaning. I consulted the documentation. 
At first I did it like here https://pcl.readthedocs.io/projects/tutorials/en/master/statistical_outlier.html
hen I needed a voxel grid like here https://pcl.readthedocs.io/projects/tutorials/en/master/voxel_grid.html
I was stumped. Why does the first example `use pcl::PointCloud` as base points class, and the second example use `pcl::PCLPointCloud2`. I thought okay, probably the first class is outdated and now we need to strive to move to `v2`. I rewrote the first example for `v2` and now I have two filters running sequentially.
Then I needed another filter by condition. My surprise was that now it gives an error
`E0322	object of abstract class type "pcl::ConditionalRemoval<pcl::PCLPointCloud2>" is not allowed: pure virtual function "pcl::Filter<pcl::PCLPointCloud2>::applyFilter" has no overrider`
It turns out that now I need to rewrite it back to `pcl::PointCloud`. 
Why are there two of them at all and what is the difference? It looks like **duplication (code smells)** and if there is some reasonable reason for this, it is much more difficult to maintain two documentations for this and explain in which case it is better to use what.

I would also like to know if the library uses multithreading? For example, for another task using `pcl::RadiusOutlierRemoval` takes about an hour for 12 million points. At the same time, in the task manager I see a load of **only 11%** on my **13600KF**

**Comment by mvieth** [comment]
Just a very quick answer, I can add more detail later when I have more time:
- Regarding PCLPointCloud2: I recommend using `pcl::PointCloud`. Using the filters with PCLPointCloud2 is basically only useful if you use them inside ROS, then you can avoid an extra conversion step. 
- Multithreading/parallelization: Some classes/function in PCL are parallelized, RadiusOutlierRemoval is currently still single-threaded

**Comment by mvieth** [comment]
Regarding slow `RadiusOutlierRemoval` you can try the following:
```c++
pcl::IndicesPtr valid_indices(new pcl::Indices);
pcl::removeNaNFromPointCloud(*your_cloud, *valid_indices);
your_cloud->dense=true;
radius_outlier_removal.setInputCloud(your_cloud);
radius_outlier_removal.setInputIndices(valid_indices);
// .. rest of filter setup
radius_outlier_removal.filter(...);
your_cloud->dense=false;
```
This may make it faster. But test thoroughly as I was not yet able to confirm this works correctly!
Regarding multithreading: if a class has the function `setNumberOfThreads` then you can generally assume that it is parallelized, otherwise not.
Does that answer your questions?

**Comment by alexeygritsenko** [comment]
Yes, you helped me a lot. Thanks for the library, I will continue to have this knowledge. 
I also hope in the near future you will consider the introduction of ubiquitous multithreading. Now everyone has many cores on CPU, and someone even has a GPU with cuda/opencl.

**Comment by larshg** [comment]
@alexeygritsenko with #6182 merged, you can try install master branch of PCL using vcpkg with the [--head](https://learn.microsoft.com/en-us/vcpkg/commands/install#--head) argument.
