### ISSUE TITLE
[PCLPointField.h] PointFieldTypes enum change breaks legacy code

### ISSUE THREAD

**Issue by Nosille** [PointCloudLibrary/pcl#6200]
In commit 4d9df3b and the subsequent 1.13 release, the PointFieldTypes enum was changed in a way that redefines all of the index values.  This change breaks legacy code that relies on the old indexing values, including causing an incompatibility with ROS 1 and ROS 2 sensor_msgs/PointField msgs.  My experience is with ROS, but I assume this change also breaks legacy data storage methods.  

Can the new enum entries be moved to the end of the list to avoid issues with legacy systems?

**Comment by mvieth** [comment]
@Nosille Hi, I don't understand why that change would break legacy code. Please note that the values of the enum entries (`INT8`, `UINT8`, etc) are not automatically assigned (in that case the order would indeed make a difference), instead the values are explicitly assigned (`INT8 = traits::asEnum_v<std::int8_t>` etc). See also the code in type_traits.h.
Why do you believe that this is a problem? Do you have code that worked with older PCL versions but not with newer ones? If yes, please show that code.

**Comment by Nosille** [comment]
You are correct.  My issues using pcl::PointFieldTypes to determine data size when reading in data from an old database must be something else.

I apologize for my mistake and appreciate your prompt response.  You can delete this issue.

**Comment by mvieth** [comment]
Great :+1:
