### ISSUE TITLE
Data race in OpenNI 1.x grabber

### ISSUE THREAD

**Issue by kwaegel** [PointCloudLibrary/pcl#629]
The convertTo[...]PointCloud(..) functions in the openni_grabber class use statically allocated resize buffers to copy the RGB and depth data. If more than one sensor is being used at the same time, the two grabbers will happily trample each others data when creating a point cloud. This is a race condition and can happen (or not) randomly.

The RGB resize buffer is used every time an image is copied, even if the output is the same size, hence you get frequent data corruption. The depth data only goes through a resize buffer if the depth image actually needs to be resized, so this problem is seen less frequently. I'm not sure why the two cases are handled differently.

The easiest solution is to convert the two resize buffers to be instance members of the grabber, not function-scope static. I [implemented such a fix](https://github.com/kwaegel/pcl/commit/ebd82de938627787078c57fe9ca9bd1458b3b365) when I wrote the OpenNI 2.x grabber.

(I would fix this myself, but OpenNI 1.x is not forward-compatible with my compiler and I couldn't test any changes.)

**Comment by kunaltyagi** [comment]
Closing due to lack of interest.
