### ISSUE TITLE
Don't die with bus error when hard drive is full

### ISSUE THREAD

**Issue by nh2** [PointCloudLibrary/pcl#637]
I was using `kinfu` and didn't notice my hard drive was full.

When saving a point could to a `cloud_bin.pcd` file by pressing `1` for saving as binary PCD (after having pressed `t` for taking a point cloud from the GPU), kinfu died with a `bus error` when writing the PCL file.

When pressing `2` instead of `1` (saving to a text file `cloud.pcd`), no bus error occurred. The written file was naturally truncated, but it would be much better if `kinfu` (or maybe the underlying PCL function that writes the point cloud to disk) could at least print a warning instead of dying silently.

**Comment by de-vri-es** [comment]
Got bitten by this too.

**Comment by taketwo** [comment]
Fixed with #2325.
