### ISSUE TITLE
Exporting -march=native breaks on Haswell CPUS with gcc=4.6

### ISSUE THREAD

**Issue by ahendrix** [PointCloudLibrary/pcl#641]
gcc-4.6 has a bug where the compiler will generate invalid instructions when compiling some code with `-march=native` on an Intel Haswell CPU.

This is problematic because gcc-4.6 is the default compiler on Ubuntu Precise, and switching to a newer version of gcc is problematic, fragile, and results is even more compiler warnings, and possible ABI mismatches with installed binaries.

Exporting `-march=native` is also a bad idea because it means that any binary packages which are distributed on top of PCL will be compiled for the build machine, rather than using the Ubuntu standard architecture flags.

**Comment by SergioRAgostinho** [comment]
I'm not sure how it was 3 years ago, but we currently provide the option PCL_ENABLE_SSE which you can set to OFF. That will prevent adding `-march=native` and other SSE/AVX compiler flags when building PCL. Also, you can always pass the compilation flags manually through CMAKE_CXX_FLAGS.
