### ISSUE TITLE
Several unit tests fail when compiled with gcc

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#677]
I mentioned that when compiled with _gcc 4.9.0_ several unit tests consistently fail. This does not happen with _clang 3.4.1_ on my machine and _clang 3.4_ on Travis.

The tests in question are:
-  6 - test_non_linear
- 29 - feature_cppf_estimation
- 49 - filters_sampling
- 73 - a_registration_test

**Comment by frozar** [comment]
My configuration:
Ubuntu 16.04.3
cmake version 3.5.1
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
VTK 6.2.0

```
95% tests passed, 5 tests failed out of 104

Total Test time (real) = 3201.40 sec

The following tests FAILED:
	 13 - common_eigen (Failed)
	 25 - feature_cppf_estimation (Failed)
	 27 - feature_pfh_estimation (Failed)
	 48 - filters_sampling (Failed)
	 73 - a_octree_test (OTHER_FAULT)
[...]
make: *** [tests] Erreur 2
```

PS : almost 1 hour to run 104 unit tests... Do these test be really unit?

**Comment by taketwo** [comment]
Obsolete, all tests pass nowadays.
