### ISSUE TITLE
Modification of the Travis tasks

### ISSUE THREAD

**Issue by taketwo** [PointCloudLibrary/pcl#699]
A pull request that adds support for _vtk6_ was merged just a few moments ago (#363). This raises a question if we should devise a separate Travis task to compile/link/test PCL with this version of the library.

I think that we should do this, however
- only with _clang_;
- only compile a subset of targets that actually depend on visualization.

This will minimize the risk of failing due to 50-minute timeout and impose less burden on Travis.

While we are at it, I would also propose to discuss a modification of the build task for _gcc_. More often than not this task fails due to timeout. This is a) confusing for those contributors who are new to PCL; b) makes Travis status non-informative for maintainers. I think we should articulate why do we want to have both _clang_ and _gcc_ tasks at the same time (i.e. what exactly do we test with the latter). Depending on the goal we should either get rid of if completely, or reduce the amount of targets.

**Comment by VictorLamoine** [comment]
For the future: [Migrating from legacy to container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)
This will allow using `ccache` and thus much faster build times.

**Comment by SergioRAgostinho** [comment]
For the latest updates on the topic #1786 #1892.
