### ISSUE TITLE
visualization::ImageViewer too slow

### ISSUE THREAD

**Issue by MichaelKorn** [PointCloudLibrary/pcl#710]
I observed that our ROS wrapper of KinFuLS has a significant higher Framerate as the origin code. One reason is a poor performance of visualization::ImageViewer. The visualization (and I just mean the painting of the windows) takes longer then the KinFu algorithm!
I compared (average time of 60 frames) visualization::ImageViewer with OpenCV on Ubuntu 12.04, Cuda 5.5, VTK 5.8, GTX680, Xeon E5-2640.

4.3-11.6ms  vs  ca. 0.63 ms:

```
viewerScene_->showRGBImage(reinterpret_cast<unsigned char*>(&view_host_[0]),
                    view_device_.cols(), view_device_.rows());

cv::Mat viewerSceneImage (480, 640, CV_8UC3, (void*)&view_host_[0]);
cv::imshow("viewerSceneImage", viewerSceneImage);
```

ca. 13 ms  vs  ca. 7 ms:

```
image_view_.viewerDepth_->showShortImage(depth_->data, depth_->cols, depth_->rows, 0, 5000, true);

cv::Mat depthImage (depth_->rows, depth_->cols, CV_16UC1,(void*)depth_->data);
depthImage *=  ((1<<16)-1)/5000.;
cv::imshow("depthImage", depthImage);
```

**Comment by kunaltyagi** [comment]
KinFu and related sub-modules are unmaintained and deprecated
