### ISSUE TITLE
PLY reader is not working

### ISSUE THREAD

**Issue by translunar** [PointCloudLibrary/pcl#720]
I've been trying to load the Stanford Bunny PLY, and I get errors with my own extremely simple app —

``` c++
pcl::PointCloud<PointXYZCI> cloud;
pcl::io::loadPLYFile(filename, cloud);
```

which gives

```
[pcl::PLYReader] ../../bun_zipper.ply:2: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYWriter::writeASCII] Input point cloud has no data!
```

So I thought I'd give it a try with `pcl_ply2pcd`, which gives a similar error:

```
$ pcl_ply2pcd ../../bunny2.ply test.pcd
Convert a PLY file to PCD format. For more information, use: pcl_ply2pcd -h
PCD output format: binary
[pcl::PLYReader] ../../bunny2.ply:2: parse error
[pcl::PLYReader::read] problem parsing header!
[pcl::PLYReader::read] problem parsing header!
```

I just pulled from Github and compiled, so I'm using the most up-to-date version of PCL.

My compiler is:

```
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix
```

**Comment by shashwat-delhi** [comment]
What should I use if I don't want to ignore the faces?

**Comment by mschoeler** [comment]
If one needs to sample on the faces of a polygon mesh they can use the tool convert2pcd from the pull request #895. It reads PLY, OBJ and STL files.
Cheers
