### ISSUE TITLE
Using a guess transformation in GICP alignment leads to wrong results.

### ISSUE THREAD

**Issue by saarnold** [PointCloudLibrary/pcl#754]
Using a guess transformation, other than the identity, for the alignment with GICP leads to a wrong results.

It is very easy to test, by transforming the target pointcloud somewhere and using the same transformation as guess. This should lead to the same result, but it doesn't.

You can find a corresponding test case in my clone of PCL.

**Comment by SergioRAgostinho** [comment]
Closed with #989
