### ISSUE TITLE
Segfault on roslaunch rgbdslam - PCL 1.7 related

### ISSUE THREAD

**Issue by TSC21** [PointCloudLibrary/pcl#780]
I'm trying to run rgbdslam (v2 with proper adaptations) in Ubuntu 13.10, with ROS Indigo and PCL 1.7. Getting gdb running to bt the reason why the launch crashes, I get the following log:

    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>...
    Reading symbols from /home/nuno/AIMAVProject_hydro_ws/devel/lib/rgbdslam/rgbdslam...(no debugging symbols found)...done.
    Starting program: /home/nuno/AIMAVProject_hydro_ws/devel/lib/rgbdslam/rgbdslam __name:=rgbdslam __log:=/home/nuno/.ros/log/243e0bb4-ff85-11e3-ac9d-0090f5eb9422/rgbdslam-2.log
    warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7fffd3b3c700 (LWP 4859)]
    [New Thread 0x7fffd333b700 (LWP 4860)]
    [New Thread 0x7fffd2b3a700 (LWP 4861)]
    [New Thread 0x7fffd2339700 (LWP 4862)]
    [New Thread 0x7fffd1b38700 (LWP 4863)]
    [New Thread 0x7fffd1337700 (LWP 4864)]
    [New Thread 0x7fffd0b36700 (LWP 4865)]
    [New Thread 0x7fffd0335700 (LWP 4866)]
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff75defa0 in boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() ()
       from /usr/local/lib/libpcl_io.so.1.7
    (gdb) bt
    #0  0x00007ffff75defa0 in boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::init::init() ()
       from /usr/local/lib/libpcl_io.so.1.7
    #1  0x00007ffff75595f9 in _GLOBAL__sub_I_hdl_grabber.cpp ()
       from /usr/local/lib/libpcl_io.so.1.7
    #2  0x00007ffff7de9856 in call_init (l=l@entry=0x7ffff7fbd4e8, 
        argc=argc@entry=3, argv=argv@entry=0x7fffffffd968, 
        env=env@entry=0x7fffffffd988) at dl-init.c:84
    #3  0x00007ffff7de9910 in call_init (env=<optimized out>, 
        argv=<optimized out>, argc=<optimized out>, l=0x7ffff7fbd4e8)
        at dl-init.c:55
    #4  _dl_init (main_map=0x7ffff7ffe268, argc=3, argv=0x7fffffffd968, 
        env=0x7fffffffd988) at dl-init.c:133
    #5  0x00007ffff7ddb66a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
    #6  0x0000000000000003 in ?? ()
    #7  0x00007fffffffdd42 in ?? ()
    #8  0x00007fffffffdd7f in ?? ()
    #9  0x00007fffffffdd90 in ?? ()
    #10 0x0000000000000000 in ?? ()
    (gdb) continue
    Continuing.
    [Thread 0x7fffd1337700 (LWP 4864) exited]
    [Thread 0x7fffd0335700 (LWP 4866) exited]
    [Thread 0x7fffd333b700 (LWP 4860) exited]
    [Thread 0x7ffff7f5fac0 (LWP 4854) exited]
    [Thread 0x7fffd0b36700 (LWP 4865) exited]
    [Thread 0x7fffd1b38700 (LWP 4863) exited]
    [Thread 0x7fffd2b3a700 (LWP 4861) exited]
    [Thread 0x7fffd3b3c700 (LWP 4859) exited]
    
    Program terminated with signal SIGSEGV, Segmentation fault.
    The program no longer exists.

**Comment by JoonasMelin** [comment]
I figured out at least one way to fix this here: https://github.com/felixendres/rgbdslam_v2/issues/8
Works by cimpiling the PCL with C++11

**Comment by taketwo** [comment]
Not a PCL bug. See the referred thread for possible solutions.
