### ISSUE TITLE
test_io fails

### ISSUE THREAD

**Issue by salino** [PointCloudLibrary/pcl#835]
Output:

    $ ./test_io
    [==========] Running 15 tests from 1 test case.
    [----------] Global test environment set-up.
    [----------] 15 tests from PCL
    [ RUN      ] PCL.ComplexPCDFileASCII
    [       OK ] PCL.ComplexPCDFileASCII (2 ms)
    [ RUN      ] PCL.AllTypesPCDFile
    [       OK ] PCL.AllTypesPCDFile (1 ms)
    [ RUN      ] PCL.ConcatenatePoints
    [       OK ] PCL.ConcatenatePoints (0 ms)
    [ RUN      ] PCL.ConcatenateFields
    [       OK ] PCL.ConcatenateFields (0 ms)
    [ RUN      ] PCL.IO
    [       OK ] PCL.IO (5948 ms)
    [ RUN      ] PCL.PCDReaderWriter
    [       OK ] PCL.PCDReaderWriter (119 ms)
    [ RUN      ] PCL.PCDReaderWriterASCIIColorPrecision
    [       OK ] PCL.PCDReaderWriterASCIIColorPrecision (812 ms)
    [ RUN      ] PCL.ASCIIReader
    [       OK ] PCL.ASCIIReader (2 ms)
    [ RUN      ] PCL.PLYReaderWriter
    [pcl::PLYReader] test_pcl_io.ply:2: parse error
    [pcl::PLYReader::read] problem parsing header!
    [pcl::PLYReader::read] problem parsing header!
    /Users/Martin/libs/pcl/src/test/io/test_io.cpp:846: Failure
    Value of: cloud_blob2.width * cloud_blob2.height
      Actual: 0
    Expected: cloud_blob.width * cloud_blob.height
    Which is: 307200
    Failed to find match for field 'x'.
    Failed to find match for field 'y'.
    Failed to find match for field 'z'.
    Failed to find match for field 'intensity'.
    /Users/Martin/libs/pcl/src/test/io/test_io.cpp:857: Failure
    Value of: cloud2.size ()
      Actual: 0
    Expected: cloud.size ()
    Which is: 307200
    Segmentation fault: 11

Environment:
Mac OS X Mavericks (10.9.4)

    $ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
    Target: x86_64-apple-darwin13.3.0
    Thread model: posix

**Comment by SergioRAgostinho** [comment]
This should be good to be closed
