### ISSUE TITLE
test_ply_mesh_io fails

### ISSUE THREAD

**Issue by salino** [PointCloudLibrary/pcl#836]
Output:

    $ ./test_ply_mesh_io ../../../src/test/tum_rabbit.vtk 
    [==========] Running 2 tests from 1 test case.
    [----------] Global test environment set-up.
    [----------] 2 tests from PCL
    [ RUN      ] PCL.PLYPolygonMeshIO
    PLY file type = 1
    PLY file type = 3
    [pcl::PLYReader] test_mesh_ascii.ply:2: parse error
    [pcl::PLYReader::read] problem parsing header!
    [pcl::PLYReader::read] problem parsing header!
    [pcl::PLYReader] test_mesh_binary.ply:2: parse error
    [pcl::PLYReader::read] problem parsing header!
    [pcl::PLYReader::read] problem parsing header!
    Failed to find match for field 'x'.
    Failed to find match for field 'y'.
    Failed to find match for field 'z'.
    Failed to find match for field 'x'.
    Failed to find match for field 'y'.
    Failed to find match for field 'z'.
    /Users/Martin/libs/pcl/src/test/io/test_ply_mesh_io.cpp:84: Failure
    Value of: verts.size ()
      Actual: 10429
    Expected: verts_ascii_pcl.size ()
    Which is: 0
    /Users/Martin/libs/pcl/src/test/io/test_ply_mesh_io.cpp:85: Failure
    Value of: verts.size ()
      Actual: 10429
    Expected: verts_binary_pcl.size ()
    Which is: 0
    unknown file: Failure
    C++ exception with description "vector" thrown in the test body.
    [  FAILED  ] PCL.PLYPolygonMeshIO (218 ms)
    [ RUN      ] PCL.PLYPolygonMeshColoredIO
    Failed to find match for field 'rgb'.
    Failed to find match for field 'rgba'.
    PLY file type = 1
    PLY file type = 1
    PLY file type = 3
    PLY file type = 3
    PLY file type = 1
    PLY file type = 1
    PLY file type = 3
    PLY file type = 3
    [       OK ] PCL.PLYPolygonMeshColoredIO (441 ms)
    [----------] 2 tests from PCL (659 ms total)

    [----------] Global test environment tear-down
    [==========] 2 tests from 1 test case ran. (659 ms total)
    [  PASSED  ] 1 test.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] PCL.PLYPolygonMeshIO

     1 FAILED TEST

Environment:
Mac OS X Mavericks (10.9.4)

    $ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
    Target: x86_64-apple-darwin13.3.0
    Thread model: posix

**Comment by SergioRAgostinho** [comment]
This should be good to be closed.
