### ISSUE TITLE
ICP CorrespondenceRejectorSurfaceNormal bug + fix

### ISSUE THREAD

**Issue by aecins** [PointCloudLibrary/pcl#868]
I have written a simple ICP code with PCL that uses [CorrespondenceRejectorSurfaceNormal] (http://docs.pointclouds.org/trunk/classpcl_1_1registration_1_1_correspondence_rejector_surface_normal.html). When I ran the code I got a segfault `Segmentation fault (core dumped)`.

After looking at the code I suspect that the problem is in line 60 [here](https://github.com/PointCloudLibrary/pcl/blob/master/registration/src/correspondence_rejection_surface_normal.cpp#L60):

`if (boost::static_pointer_cast<DataContainer<pcl::PointXYZ, pcl::PointNormal> >
        (data_container_)->getCorrespondenceScoreFromNormals (original_correspondences[i]) > threshold_)`

`pcl::PointNormal` should be replaced by `pcl::Normal`:
`if (boost::static_pointer_cast<DataContainer<pcl::PointXYZ, pcl::Normal> >
        (data_container_)->getCorrespondenceScoreFromNormals (original_correspondences[i]) > threshold_)`

to match the the declaration in line 296 [here](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/correspondence_rejection_surface_normal.h#L296). This fix solved my segfault issue.

**Comment by andreaskoepf** [comment]
I was affected by this bug and created a PR #1536. I added `getCorrespondenceScoreFromNormals()` to the `DataContainerInterface` to enable normal based rejection while hiding the concrete point / normal type.

**Comment by jspricke** [comment]
should be fixed in the next release.
