### ISSUE TITLE
pcl::visualization::PCLVisualizer::setSize has no effect

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#871]
The window size of a PCL Visualizer cannot be changed using the `pcl::visualization::PCLVisualizer::setSize` method

**visualizer.cpp**

``` cpp
#include <pcl/visualization/pcl_visualizer.h>

int
main (int argc, char *argv[])
{
  pcl::visualization::PCLVisualizer viewer ("PCL visualizer");
  viewer.addCoordinateSystem (1.0, "axis", 0);
  viewer.setSize (666, 555);
  viewer.spin ();
  return (0);
}
```

**CMakeLists.txt**

``` cmake
cmake_minimum_required(VERSION 2.6 FATAL_ERROR)

project(pcl-visualizer)
find_package(PCL 1.7 REQUIRED)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (visualizer visualizer.cpp)
target_link_libraries (visualizer ${PCL_LIBRARIES})
```

The window size should be [666, 555] but pressing `c` (without resizing the visualizer) outputs [960, 540] instead.

The behavior becomes very strange when using 2 monitors, here is a table that shows what I have seen so far: (the expected window size is always [666, 555])

| Screen resolution* | PCL Visualizer window size | Comment |
| --- | --- | --- |
| **With one monitor:** |  |  |
| 1920x1080 | [960, 540] | Half of screen size |
| 1280x1024 | [640, 512] | Half of screen size |
| **With two monitors:** |  |  |
| 1920x1080 (1st monitor) | [1600, 540] | ~Half of "screens" size |
| 1280x1024 (2nd monitor) | [666, 555] | It worked |

\* screen resolution: size of the screen where the terminal to launch `visualizer` is located

I am using VTK 5.8.

**Comment by lamogui** [comment]
Hi I have still the same issue in 2015 with the initialisation
```   boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer (new pcl::visualization::PCLVisualizer ("Kinect2 Surface Reconstruction"));
  viewer->setSize(800,600); ```

**Comment by VictorLamoine** [comment]
What version of PCL do you use? This has been fixed since PCL 1.7.2 so if you need at least this version to get the fix.

If if doesn't work with PCL 1.7.2 and above, please test with the code above and tell us the window size (by pressing C) and your screen resolution. Also tell us which version of VTK you have compiled PCL against.

**Comment by taketwo** [comment]
To clarify Victor's answer, you need to use the trunk version of PCL, because the issue was fixed _after_ 1.7.2 release.

**Comment by VictorLamoine** [comment]
Oh right... August is before September :smile:  Poor me...!

**Comment by lamogui** [comment]
Ok I understand now in fact the last release is old (more than 1 year !), I use unbuntu packages (1.7.2-7).

**Comment by taketwo** [comment]
Yep, we've been quite sluggish with releases in the recent years...
