### ISSUE TITLE
ImageViewer  "Error vtkTrivialProducer: This data object does not contain the requested extend

### ISSUE THREAD

**Issue by norminu** [PointCloudLibrary/pcl#910]
Creating an instance of pcl::visualization::ImageViewer

pcl::visualization::ImageViewer::Ptr m_viewer = pcl::visualization::ImageViewer::Ptr(new pcl::visualization::ImageViewer("PCL Image Viewer"));

I got the following error:

ERROR: In VTK-6_1_0\src\Common\ExecutionModel\vtkTrivialProducer.cxx, line 268
vtkTrivialProducer (00000010A7774E50): This data object does not contain the requested extent.

I don't know if is a VTK issue or is pcl integration.

http://www.pcl-users.org/PCL-Visualizer-Error-vtkTrivialProducer-td4035513.html

**Comment by janeyuhui** [comment]
The SetInputData() does not set a pipeline connection. When you use it, you need to make sure that the pipeline that produce the data is manually updated. So adding a
color->Update();  or colorMap->Update()  ....
before rendering happens will fix the issue.

If your intention is to setup a pipeline connection such that any change in filter parameters are automatically reflected in the viewer, use this instead:
imageViewer->SetInputConnection(color->GetOutputPort());
