### ISSUE TITLE
problem in SACMODEL_NORMAL_PARALLEL_PLANE

### ISSUE THREAD

**Issue by ClaireXie** [PointCloudLibrary/pcl#918]
I tried to detect two perpendicular planes in which the normal of the first plane is parallel to the second plane. So I set the normal of the first plane as the axis in SACMODEL_NORMAL_PARALLEL_PLANE and use SACSegmentationFromNormals. However, after it, I find the two detected planes are almost parallel to each other, instead of perpendicular. When I dig into the code, in sample_consensus/impl/sac_model_normal_parallel_plane.hpp, in function isModelValid(), you are checking

``` cpp
if (fabs (axis_.dot (coeff)) < cos_angle_)
      return  (false);
```

which, I feel strange. 
I thought it should be (consistent with 'sac_model_parallel_plane'):

``` cpp
if (fabs (axis.dot (coeff)) > sin_angle_)
      return  (false);
```

**Comment by mvieth** [comment]
This thread is rather old so maybe no one is interested any more, but for what it is worth:
`SACMODEL_NORMAL_PARALLEL_PLANE` is like `SACMODEL_PERPENDICULAR_PLANE`, but the points are only counted as inliers if they are close to the plane **and** their normals are close to the normal of the estimated plane. See also `SACMODEL_NORMAL_PLANE`
