### ISSUE TITLE
Bug in pcl::gpu::PrincipalCurvaturesEstimation::compute

### ISSUE THREAD

**Issue by beetleskin** [PointCloudLibrary/pcl#940]
The gpu::PrincipalCurvatureEstimation does not support to set a surface the way it is intended to be. If surface and adequate normals are set, the pc is computed for the surface points, not for those of input cloud. Consequently the output feature vector will have the size of the normals (resp. surface) provided, not the size of the input cloud, [pcl / gpu / features / src / features.cpp:362](https://github.com/PointCloudLibrary/pcl/blob/647de7bed7df7cd383e5948ff42b116e5aae0e79/gpu/features/src/features.cpp#L362):

``` cpp
features.create(normals_.size());
```

I can't imagine that this behaviour is intended, since the input cloud is completely ignored, if the surface is set.

**Comment by beetleskin** [comment]
> Marking this as stale due to 30 days of inactivity.

:D :D :D

**Comment by kunaltyagi** [comment]
What's your idea @beetleskin ?

**Comment by beetleskin** [comment]
I have no clue what I was doing 4 yeas ago. So I have no idea. We might as well close it.
