### ISSUE TITLE
MSVC 2012 + PCL/git-master: linking errors on pcd2png tools

### ISSUE THREAD

**Issue by madduci** [PointCloudLibrary/pcl#952]
Hi,
I'm running a Windows 8.1 x64 box with the following software and dependences:
- Visual Studio 2012
- CMake 3.0.2
- Windows SDK 8.1 Kit
- Flann 1.8.4 (already compiled for VS x64)
- Boost 1.5.6 (already compiled for VS x64)
- QHull 2012.1 (already compiled for VS x64)
- Qt 5.2.1 with OpenGL (already compiled for VS x64)
- VTK 6.1 (already compiled for VS x64)
- OpenNI 2

I'm still having some linking problems (only 4 subprojects of the entire solution cannot be built, but 108 succeeded!) and I don't know which libraries are still missing.

Here in Pastebin you can look at the output given by Visual Studio

http://pastebin.com/q9pEM5Un

One of the biggest errors are the missing definitions of "unsigned char const \* const pcl::GLASBEY_LUT" and "unsigned int const pcl::GLASBEY_LUT_SIZE"

Also convex hull fails to compile, due to some qhull functions not defined, even when CMake didn't throw any error and I'm linking the correct qhullstatic.lib.

The errors appear on both debug and release mode.

**Comment by JACK-HAI** [comment]
> I've solved mostly of the qhull issue.
> It was my fault trusting the already-there QHull's ".sln" for Windows: it simply doesn't produce the expected libraries with qh_QHpointer enabled, as suggested in Qhull news and in #852.
> Running it from scratch, it generates the correct QHull libs and the convex hull project requires only the unresolved external symbol "qh_qh"
> 
> Update: linking qhullstatic_p.lib and qhullstatic_pd.lib fixes the ConvexHull project.
> 
> Now waiting only for the #955 merge



> #852
I recently encountered this problem, as you said, I solved it. Thanks
