### ISSUE TITLE
building with Eigen HEAD and -std=c++11 

### ISSUE THREAD

**Issue by rimmartin** [PointCloudLibrary/pcl#980]
Hi,

I built pcl with only one line needing a change in https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt_2d.hpp  to satisfy Eigen.
I cloned pcl and required supporting libraries last evening.  Used cmake-2.8.12.2 and more particularly -std=c++11 and compiler g++ (GCC) 4.10.0 20140510 (experimental)

``` Diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- <html>ndt_2d.hpp (<b>Today 10:05:34 AM</b>)</html>
+++ <html><b>Current File</b></html>
@@ -432,7 +432,7 @@
       if (min_eigenvalue < 0)
       {
         double lambda = 1.1 * min_eigenvalue - 1;
-        score.hessian += Eigen::Vector3d (-lambda, -lambda, -lambda).asDiagonal ();
+        score.hessian.diagonal() += Eigen::Matrix<double,3,1> (-lambda, -lambda, -lambda);
         solver.compute (score.hessian, false);
         PCL_DEBUG ("[pcl::NormalDistributionsTransform2D::computeTransformation] adjust hessian: %f: new eigenvalues:%f %f %f\n",
             float (lambda),
```

The += works with this change.  Have not run tests yet but am compiled successfully

**Comment by fidergo-stephane-gourichon** [comment]
# Summary: "worksforme"

## Observed: works here on several variants of Ubuntu

Current master does not apply the patch discussed here ([ref](https://github.com/PointCloudLibrary/pcl/blob/521a3acfcc24b19942fb4020ecd0729866b46a94/registration/include/pcl/registration/impl/ndt_2d.hpp#L439)), yet its absence does not cause any problem during compilation here.

Context:

- Ubuntu 16.04 x86_64
- cmake version 3.5.1
- CMAKE_CXX_STANDARD set to 11
- libeigen3-dev                    3.3~beta1-2 
- gcc 5.4.0-6ubuntu1~16.04.10

Also, no such problem observed on AMD64 architecture, same parameters as above.

Also, no such problem observed on:

- Ubuntu 14.04 x86_64
- cmake version 2.8.12.2
- libeigen3-dev                    3.2.0-8 
- gcc 6.3.0-18ubuntu2~14.04

Link to master at the time you read this message: https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt_2d.hpp#L439

## Next step

- Hypothesis: eigen evolved, removing need for such a patch? 
- Does this suggest just closing the issue?

**Comment by rimmartin** [comment]
Hi,

I made a small unit test in a second project of mine:
```
    Eigen::Matrix<double, 3, 3> hessian = Eigen::Matrix<double, 3, 3>::Identity ();
    double lambda = -1;
    hessian += Eigen::Vector3d (-lambda, -lambda, -lambda).asDiagonal ();
    std::cout<<" "<<hessian<<std::endl;

```
result:
```
2 0 0
0 2 0
0 0 2
```

It does appear eigen added a += that knows what a diagonal is from the right side and alters the diagonal of the matrix on the left

Thank you, this can be closed

**Comment by taketwo** [comment]
Thanks for digging this up and updating us.
