### ISSUE TITLE
Error Link: Missing externals (build with OpenNI2 only)

### ISSUE THREAD

**Issue by Ptitclem** [PointCloudLibrary/pcl#983]
Hi,
I am new to PCL so I don't know if my issue/question is relevant.
I am building PCL with the following software and dependencies:
- Visual Studio 2010
- CMake 3.0.2
- Windows SDK 8.1 Kit
- Every depencies binaries from PCL website (Windows MSVC 2010 64bit) except OpenNI
- OpenNI 2 sources from Occipital's Github

I built OpenNI2 sources and filled the CMake OpenNI2 paths accordingly. I **unchecked** the OpenNI "option" in the BUILD group, but **checked** OpenNI2.

Every project was built successfully (_except "pcl_pcd2png" and "pcl_organized_pcd_to_png" but that's another point_) but the pcl_io was displaying the following errors: 

```
pcd_grabber.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl openni_wrapper::ImageRGB24::isResizingSupported(unsigned int,unsigned int,unsigned int,unsigned int)const " (?isResizingSupported@ImageRGB24@openni_wrapper@@UEBA_NIIII@Z)
pcd_grabber.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl openni_wrapper::ImageRGB24::fillRGB(unsigned int,unsigned int,unsigned char *,unsigned int)const " (?fillRGB@ImageRGB24@openni_wrapper@@UEBAXIIPEAEI@Z)
pcd_grabber.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl openni_wrapper::ImageRGB24::fillGrayscale(unsigned int,unsigned int,unsigned char *,unsigned int)const " (?fillGrayscale@ImageRGB24@openni_wrapper@@UEBAXIIPEAEI@Z)
pcd_grabber.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl openni_wrapper::ImageRGB24::~ImageRGB24(void)" (??1ImageRGB24@openni_wrapper@@UEAA@XZ) referenced in function "public: virtual void * __cdecl openni_wrapper::ImageRGB24::`scalar deleting destructor'(unsigned int)" (??_GImageRGB24@openni_wrapper@@UEAAPEAXI@Z)
```

Do I need to add OpenNI anyway ? That seems strange as OpenNI2 alone should be enough.

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen did you have any issues similar to this lately? You normally use OpenNI2 right?

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho I was test pcl_openni2_viewer (that included in PCL 1.8.1 All-in-one Installer) with Kinect v1. It seems to be working normally.
![2017-12-09_08h08_25](https://user-images.githubusercontent.com/816705/33788936-8a6facbc-dcb8-11e7-88b2-c37c9d310a49.png)

**Comment by SergioRAgostinho** [comment]
Hmm. Well let's close this for now. Just open it up if there's new info.

**Comment by kaisark** [comment]
If you build with both "WITH_OPENNI" and "WITH_OPENNI2" make options set to ON, what is the expected result regarding built application executables? I think a viewer is built for each, but what about all the other executables? Are the other apps sitting in the $PCL_ROOT/build/bin directory coded/built for OPENNI only?

**Comment by SergioRAgostinho** [comment]
This is not a comprehensive answer but in most cases I've seen just work with one of the versions, most commonly they just check for the OPENNI found/build status.
